### ISSUE TITLE
[Bug] Soldevi Sentry doesn't allow opponent to draw a card

### ISSUE THREAD

**Issue by xenohedron** [magefree/mage#10016]
[[Soldevi Sentry]]

Looks like the text was previously hacked on without confirming correct functionality. Probably could be refactored to a simple implementation.

**Comment by Susucre** [comment]
![image](https://github.com/magefree/mage/assets/34709007/93c7071f-77e6-4d92-bb08-786015125cf1)

It seems to work in my limited testing
