### ISSUE TITLE
Shu Cavalry card not present in the database

### ISSUE THREAD

**Issue by cybernova** [magefree/mage#1001]
In Xmage version 1.4.0v2 that card is not present.
http://magiccards.info/query?q=shu+cavalry&v=card&s=cname

**Comment by LevelX2** [comment]
Please don't create issues for not yet implemented cards.
You can post requests to the forum: http://www.slightlymagic.net/forum/viewtopic.php?f=70&t=14062

**Comment by cybernova** [comment]
Done, thanks
