### ISSUE TITLE
[GUI] Estrid -1 ask you twice to pick targets

### ISSUE THREAD

**Issue by copperfield42** [magefree/mage#10035]
![025 estrid -1 ask twice](https://user-images.githubusercontent.com/4504719/220239112-58ecd9f0-206a-43d4-b5e3-c0d219795f47.png)

[[Estrid, the Masked]] -1 ask you twice to pick targets, the first time when you activate it and put it on the stack as normal and then a second time when the Mask is created, on the second time choosing a different target does nothing (or seemingly nothing, it may be the case that something that care for targeting might trigger) the mask is still attached to the first.

**Comment by theelk801** [comment]
superceded by #10830
