### ISSUE TITLE
Death Triggers Not Triggering

### ISSUE THREAD

**Issue by LegionedintheDamned** [magefree/mage#10037]
Both [Pitiless Plunderer] and [Morbid Opportunist] failed to trigger 2 turns in a row with a token death.  Screenshot attached.
![image](https://user-images.githubusercontent.com/82664393/220264038-73678e0d-7883-4ffd-a15d-514c16c8d490.png)

**Comment by LegionedintheDamned** [comment]
Can confirm this was not fixed with the most recent patch.  In this screenshot, demonstrated with [Pawn of Ulamog].
![image](https://user-images.githubusercontent.com/82664393/221450005-519cecc5-0a05-4b3a-8fa1-bc6191fe0868.png)

**Comment by PurpleCrowbar** [comment]
Could not reproduce with either [[Pitiless Plunderer]] or [[Pawn of Ulamog]]. See the case with Pitiless Plunderer below:
![image](https://user-images.githubusercontent.com/26198472/221450826-244cb82a-ee30-4460-8002-7a933a905f25.png)
And Pawn of Ulamog:
![image](https://user-images.githubusercontent.com/26198472/221450880-a21f38a2-3651-48bd-ac2f-12a8a4ef83d0.png)

**Comment by LegionedintheDamned** [comment]
Apologies - this was meant to be in the exile/death triggers thread.  Please disregard my reply.
