### ISSUE TITLE
Niv-Mizzet Reborn doesn't reveal chosen cards

### ISSUE THREAD

**Issue by stevedavidmusic** [magefree/mage#10046]
Niv-Mizzet Reborn doesn't reveal the chosen cards that you put into your hand. Logs simply say "puts a card into their hand". I opened a similar issues recently regarding initiative / Atraxa, Grand Unifier, so I'd imagine the solution would be the same.

**Comment by jeffwadsworth** [comment]
[[Niv-Mizzet Reborn]]

**Comment by PurpleCrowbar** [comment]
Fixed in 03b82ff7ee8c920f68ffdd8033d06e6fccf92803
