### ISSUE TITLE
Exile trigger with dies trigger

### ISSUE THREAD

**Issue by LegionedintheDamned** [magefree/mage#10058]
I have [Mari, the Killing Quill] out.  My commander is also out, [Kelsien, the Plague].  Kelsien is equipped with [Thornbite Staff].  If I am reading correctly, Mari's ability triggers after the 'dies' resolves.  So Kelsien should untap on hitting a creature.  This appears not to be happening.

3 AI, 1 player, Commander.
![image](https://user-images.githubusercontent.com/82664393/220826043-73c386a6-e722-4fbb-91d4-0dcf0394c3ad.png)

**Comment by Grath** [comment]
If/when someone reviews #10059 this will be fixed. Mari was implemented incorrectly.
