### ISSUE TITLE
Gifts Ungiven [weird resolution]

### ISSUE THREAD

**Issue by Blitkun** [magefree/mage#1005]
On a multiplayer match, a player cast Gifts Ungiven and it resolved quite strangely:

- 4-card selection was ok;
- All 4 cards were revealed to me as expected;
- As I clicked on the first chosen card for the graveyard, the Revealed prompt vanished;
- My opponent received a message to "choose order in which cards are put into graveyard";
- After clicking "Done" for the message, all 4 cards ended up on his hand.

(by checking the GameLog, it seems all cards were put in the graveyard and then immediately passed to his hand)

I was able to replicate the issue - the searched cards were different and we were, again, in a 3-player Free For All.

I haven't tested if the same issue happens on 1x1 as well.

Gamelog Excert:

<font color="#20B2AA">Bharamhir</font><font color="White"> 
    casts </font><font color="#87CEFA">Gifts Ungiven [2a6]</font>
<font color="#CCCC33">09:24: </font><font color="#20B2AA">Bharamhir</font><font color="White"> 
    searches his or her library</font>
<font color="#CCCC33">09:26: </font><font color="#20B2AA">Bharamhir</font><font color="White"> 
    reveals </font><font color="#F0E68C">Elesh Norn, Grand Cenobite [e42]</font><font color="White">, 
    </font><font color="#F0E68C">Wrath of God [137]</font><font color="White">, 
    </font><font color="#F0E68C">Sun Titan [cb3]</font><font color="White">, </font><font color="#F0E68C">Oblivion 
    Ring [833]</font>
<font color="#CCCC33">09:27: </font><font color="#20B2AA">Bharamhir</font><font color="White"> 
    puts </font><font color="#F0E68C">Elesh Norn, Grand Cenobite [e42]</font><font color="White"> 
    from library into his or her graveyard</font>
<font color="#CCCC33">09:27: </font><font color="#20B2AA">Bharamhir</font><font color="White"> 
    puts </font><font color="#F0E68C">Wrath of God [137]</font><font color="White"> 
    from library into his or her graveyard</font>
<font color="#CCCC33">09:27: </font><font color="#20B2AA">Bharamhir</font><font color="White"> 
    puts </font><font color="#F0E68C">Sun Titan [cb3]</font><font color="White"> 
    from library into his or her graveyard</font>
<font color="#CCCC33">09:27: </font><font color="#20B2AA">Bharamhir</font><font color="White"> 
    puts </font><font color="#F0E68C">Oblivion Ring [833]</font><font color="White"> 
    from library into his or her graveyard</font>
<font color="#CCCC33">09:27: </font><font color="#20B2AA">Bharamhir</font><font color="White"> 
    puts </font><font color="#F0E68C">Elesh Norn, Grand Cenobite [e42]</font><font color="White"> 
    from library into his or her hand</font>
<font color="#CCCC33">09:27: </font><font color="#20B2AA">Bharamhir</font><font color="White"> 
    puts </font><font color="#F0E68C">Wrath of God [137]</font><font color="White"> 
    from library into his or her hand</font>
<font color="#CCCC33">09:27: </font><font color="#20B2AA">Bharamhir</font><font color="White"> 
    puts </font><font color="#F0E68C">Sun Titan [cb3]</font><font color="White"> 
    from library into his or her hand</font>
<font color="#CCCC33">09:27: </font><font color="#20B2AA">Bharamhir</font><font color="White"> 
    puts </font><font color="#F0E68C">Oblivion Ring [833]</font><font color="White"> 
    from library into his or her hand</font>
<font color="#CCCC33">09:27: </font><font color="#20B2AA">Bharamhir</font><font color="White"> 
    shuffles his or her library.</font>
<font color="#CCCC33">09:27: </font><font color="#20B2AA">Bharamhir</font><font color="White"> 
    puts </font><font color="#87CEFA">Gifts Ungiven [2a6]</font><font color="White"> 
    from stack into his or her graveyard</font>

**Comment by LevelX2** [comment]
Gifts Ungiven was reworked meanwhile (e.g. corrected target opponent handling and card movement).

So check if you can reproduce any problem and reopen in that case the issue.
