### ISSUE TITLE
Aesthetic - Dynamically resizing tooltip text box

### ISSUE THREAD

**Issue by jgod** [magefree/mage#1007]
Similar to issues [117](https://github.com/magefree/mage/issues/117) and [47](https://github.com/magefree/mage/issues/47). 

On cards with less text the huge tooltip looks silly. With some fixed dimensions (like font size and padding) and a way to determine line break length (if it's not already fixed, maybe based on resolution) it should be pretty easy to calculate the appropriate dimensions.

A change like this goes a long way towards the usability of the program. If I can get a dev env set up, I'll take a look to see how it all works as is.
![screen shot 2015-06-01 at 3 55 35 am](https://cloud.githubusercontent.com/assets/3506872/7908342/22843258-0812-11e5-89b7-3d6bf36aeff4.png)

**Comment by LevelX2** [comment]
It's not so easy to get the correctly needed size of the box.
But another thing that should be improved in this area is the duration to wait until the tooltip text boy is shown.
It should be adjustable in the preferences.

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.

Specifically, there's now a (reasonable) minimum size that expands if there's a lot of text.
