### ISSUE TITLE
[BUG] [TMP] Deadshot

### ISSUE THREAD

**Issue by xenohedron** [magefree/mage#10077]
The second target deals damage to itself, but it should be the first target dealing damage to the second.
[[Deadshot]]

**Comment by chesse20** [comment]
https://github.com/magefree/mage/blob/754a5b38ebba104b83494629c1f3881020168b1e/Mage.Sets/src/mage/cards/c/ClearShot.java
I recommend using clear shots code as a template instead of trying to navigate deadshot's code, which is pretty messy
