### ISSUE TITLE
[BUG] Graaz not making crawling barrens a 5/3

### ISSUE THREAD

**Issue by VGBBY** [magefree/mage#10084]
![image](https://user-images.githubusercontent.com/125227902/221750806-89dc44cf-65ef-4055-a55c-c2619ffcd796.png)
[[graaz unstoppable juggernaut]]
[[crawling barrens]]
pretty much as title says, also it wasn't forced to attack.

**Comment by sprangg** [comment]
If you use Crawling Barrens's ability to turn it into a creature after Graaz entered the battlefield, it still becomes a 0/0 elemental that isn't forced to attack.

I doubt there's any bug here, unless you used Crawling Barrens before Graaz Entered the battlefield and it didn't become a juggernaut when Graaz entered the battlefield.
