### ISSUE TITLE
[Bug] [TMP] Dracoplasm disappears if you sacrifice any creatures to it

### ISSUE THREAD

**Issue by sprangg** [magefree/mage#10099]
When you play [[Dracoplasm]] and sacrifice any creatures to it, the end result is that the creatures get sacrificed and Dracoplasm completely disappears from the game, not existing in any zone.

If you don't sacrifice any creatures to Dracoplasm it goes to the graveyard, so this is the only scenario where it works as intended.

**Comment by sprangg** [comment]
My guess is this happens because Dracoplasm treats the sacrifice ability as a replacement effect, and it replaces the whole entering the battlefield, putting Dracoplasm into oblivion.

The replacement effect only returns true when any creatures are sacrificed, which is why Dracoplasm goes to the graveyard instead of disappearing when no creatures are sacrificed.

**Comment by Grath** [comment]
You would be correct. Just tested it and swapping that `return true` to `return false` fixes it.

**Comment by sprangg** [comment]
Awesome, thanks for the fix
