### ISSUE TITLE
Maddening Hex sacrifices itself in 1v1s

### ISSUE THREAD

**Issue by stonedgirl** [magefree/mage#10104]
Maddening Hex sacrifices itself when it's ability resolves in 1v1 games even though ruling says it would stay attached

**Comment by Merlingilb** [comment]
I can't reproduce this... do you have an example where it gets destroyed? for me it doesn't

**Comment by maximuscesar** [comment]
Happened to me a while ago: My opponent had a defense grid and I had a Maddening hex. My opponent then cast a rite of flame, took the damage from the hex and then it went to the graveyard instead of attaching back to my opponent.
