### ISSUE TITLE
[BUG] Hoarder's Greed causes NullPointerException on first loop

### ISSUE THREAD

**Issue by bobwoco** [magefree/mage#10103]
Found when testing other clash cards after fixing the return to hand ones in #10097.

**Comment by xenohedron** [comment]
The card works fine in the unit test framework, but the NPE arises from `HumanPlayer::choose()` and `HumanPlayer::chooseUse()`. Appears to be related to
```
game.fireSelectTargetEvent(getId(), new MessageToClient(target.getMessage(), getRelatedObjectName(source, game)), possibleTargetIds, required, getOptions(target, options));
```

`game.getState().processAction(game);` in the do-while loop doesn't help.

**Comment by bobwoco** [comment]
I've been doing some more testing on this, and it seems like the reason for the NPE is on line 219 of `CallbackCardImpl::processCallback`.  It tries to get the correct message for the target with 
```
GameClientMessage message = (GameClientMessage) callback.getData();
```
but that gets back null and then gets accessed.

 @JayDi85 have you ever seen something like this? I did some debugging and as far as I can tell the callback gets correctly sent with data in it, but then when it's received by CallbackCardImpl the data is somehow no longer there.
