### ISSUE TITLE
K'rrik doesn't correctly replace the cost of black mana with phyrexian mana

### ISSUE THREAD

**Issue by Tharkon** [magefree/mage#10119]
With both [[Verrak, Warped Sengir]] and  [[K'rrik, Son of Yawmoth]] any {B} replaced by {B/P} by K'rrik is not seen by Verrak.

Examples:
Activating [[Arguel's Blood Fast]] does trigger Verrak, but you only have to pay 2 instead of 4 life to copy it, even if 4 life was paid to activate it.
Activating either of [[Asmodeus the Archfiend]]'s abilities does not trigger Verrak even if life was paid to activate the ability.
The same goes for activating [[Barren Moor]]'s cycling ability.
Activating [[Pestilent Souleater]] *does* trigger Verrak so the problem does not seem to be with Verrak but with K'rrik or with the FilterMana or ManaCostsImpl classes.

**Comment by Susucre** [comment]
[[K'rrik, Son of Yawgmoth]]
