### ISSUE TITLE
[40K] Missing Card: The Red Terror

### ISSUE THREAD

**Issue by GiacomoTacomo** [magefree/mage#10128]
The card from the 40K set the red terror is missing from XMage. Its a card from the precon "tyranid swarm" which i would love to try.
![image](https://user-images.githubusercontent.com/48278699/226220527-e2524cdf-9086-4b77-9b6f-e41ab4030f28.png)

**Comment by Grath** [comment]
#8954 lists the remaining cards from 40k that haven't been implemented yet. That is one of them.
