### ISSUE TITLE
Using Metalworker and Cavern of Souls to Cast an Artifact Creature

### ISSUE THREAD

**Issue by Badaro** [magefree/mage#1012]
Scenario:

1) I have a Cavern of Souls in play, naming Construct
2) I have a Metalworker in play
3) I have a Kuldotha Forgemaster in my hand, alongside two other artifacts

I want to use Metalworker to generate 6 mana then cast the Forgemaster using four of the colorless mana from Metalworker, plus one mana from the Cavern of Souls to make it uncounterable, however I could not find a way to do it, as even if I add the Cavern mana to the pool beforehand it still uses only the colorless mana.

Ideally in this scenario the game should ask if I want to use the Cavern of Souls mana, or at least default to using its mana if available.

**Comment by Badaro** [comment]
Gamelog: http://pastebin.com/9e4Z4TqQ

I tried to do it on Turn 6, however the log doesn't display the mana pool status, so I'm not sure it'll be very helpful.

**Comment by thejayvm** [comment]
Did it still not let you use the mana from cavern even if you right clicked the playing field and unchecked the auto use mana option?

**Comment by Badaro** [comment]
Didn't know about that option, will have to run some tests.

**Comment by jgod** [comment]
Funnily enough, this is a problem on the [official client](https://www.youtube.com/watch?v=L77eaOYa5NM&list=PL04lbfeNAaS9GvvMzigOyy9ZRmRl2LRV4&index=4&t=4m7s) too. I would like to see smarter default mana handling; I'll look into it.

**Comment by emerald000** [comment]
I think a decent way to handle that and other similar problems would be not to consume mana automatically when more than one mana is in the mana pool. That way you could pick the colored mana you need, then the colorless to finish paying. That would also simplify using bouncelands for example when you need to split the mana in two spells, or storm decks that generate a bunch of mana and need to spend the correct amount of each color.

Yes, you could disable auto mana payments, but it would be even better if you didn't have to think to turn it on/off when it matters.

**Comment by jgod** [comment]
I was thinking about how to prioritize the type of mana automatically spent, but now that I think about it, that won't work. I don't like the idea of "knowing what's best" for the user since there are edge cases where there'd still be issues, so your idea is probably most practical.

**Comment by LevelX2** [comment]
> I think a decent way to handle that and other similar problems would be not to consume mana automatically when more than one mana is in the mana pool. That way you could pick the colored mana you need, then the colorless to finish paying. That would also simplify using bouncelands for example when you need to split the mana in two spells, or storm decks that generate a bunch of mana and need to spend the correct amount of each color.

I like the idea and have implemented a similar logic now.
I had to modify the basic idea a bit I guess. The logic is now if the new option is activated that mana that is already in the mana pool as you cast/activate a spell or ability won't be used to pay automatically. You have to use it manually. But mana you produce after you clicked the  spell/ability will be used automatically as before (sure only if automatic mana payment is active) .

Here a image the menu looks like now:
![poolmanaautomatic](https://cloud.githubusercontent.com/assets/2066790/8024573/53664160-0d38-11e5-96bd-69cb5bd50a80.jpg)

**Comment by LevelX2** [comment]
> Scenario:
> 
> 1) I have a Cavern of Souls in play, naming Construct
> 2) I have a Metalworker in play
> 3) I have a Kuldotha Forgemaster in my hand, alongside two other artifacts
> 
> I want to use Metalworker to generate 6 mana then cast the Forgemaster using four of the colorless mana from Metalworker, plus one mana from the Cavern of Souls to make it uncounterable, however I could not find a way to do it, as even if I add the Cavern mana to the pool beforehand it still uses only the colorless mana.

Tested it now, works like a charm with the new option.
