### ISSUE TITLE
Token type prioritises over availableImageSetCodes list in certain cases, causes wrong image to be assigned

### ISSUE THREAD

**Issue by PurpleCrowbar** [magefree/mage#10139]
Description of bug: a hypothetical card from set "ABC" creates a 3/3 Zombie token of class "Zombie33Token". However, this set only has a token image for a 2/2 Zombie token, which is not the right image, as it's for token class "Zombie22Token". In the code for Zombie33Token, `availableImageSetCodes = Arrays.asList("DEF");` is in the constructor (in this example there is only one set code in the list for simplicity of explanation). This means that, if the set code of the source creating the token is not found in the `availableImageSetCodes` list, then a random set code from that list will be used as that token's `originalExpansionSetCode` which, despite the name, has less to do with being the *original* expansion set code and more to do with image assignation. See below for how `availableImageSetCodes` is used:
https://github.com/magefree/mage/blob/77209073e9bfd130bb752d7bae9e22aec30c179e/Mage/src/main/java/mage/game/permanent/token/TokenImpl.java#L437-L453
Unfortunately, because we are using `availableImageSetCodes` and sets ABC and DEF both have a Zombie token with a matching token type, 0, XMage prioritises the Zombie image from ABC's token image folder, despite ABC not being part of the available image set codes list.

This issue does *not* occur when writing `this.setExpansionSetCodeForImage("DEF");` in the constructor instead of using the available image set codes. For some reason, using a list of available image set codes only affects the image chosen for the token, but the token itself is still apparently from the set of the card that created it, regardless of the image it's using. However, when using `this.setExpansionSetCodeForImage("DEF");`, the source card that created the token has its set disregarded, and the set of the created token is DEF. This means this issue can be resolved in the case of tokens that only appear in one set by simply setting the original expansion set code in the constructor instead of using a list, though this is a band-aid fix that won't apply in the majority of situations that this bug pops up.

**IMPORTANT**: Token types are **not 1 by default**, despite mention in the code and in discussions on GitHub of this being the case. If a token shares a name with no other tokens in the set, **it will have a token type of 0**. Only when a token shares a name with one or more other tokens in the set do they become token type 1, 2, 3, etc.

Real, non-hypothetical examples of this bug can be found in the case of [[Wilhelt, the Rotcleaver]] and [[Urza, Chief Artificer]]. Wilhelt is an MIC card which creates decayed zombie tokens, which are exclusive to the MID set. MIC has 2 token images for Zombies, and MID also has 2 token images for Zombies, with token type 1 being the decayed zombie image. Because of the bug described in this issue, the current implementation of the code (which uses `availableImageSetCodes` in ZombieDecayedToken) causes decayed zombies created by Wilhelt to use the token type 1 Zombie token image from MID (his set code), as opposed to using the token type 1 Zombie token image from MIC. As previously mentioned, this *specific* issue can be fixed by changing the original set code in the constructor, but this does not apply to the next example.

In the case of Urza, who creates 0/0 Constructs which get +1/+1 for each artifact its controller controls, the same issue appears. Urza is from BRC, and his construct tokens use images from multiple sets, such as DMR. BRC contains a single unrelated 1/1 Construct token, which therefore has token type 0. DMR has a single Construct token, the one that Urza uses, but because it's the only Construct token in that set, its token type is also 0. Because of this, any time that one of Urza's Constructs has DMR randomly chosen from the list of available image set codes, it will *always* display the wrong image, the 1/1 from BRC. This also happens with MH1 for the exact same reasons - there's only one Construct in that set, so its token type is 0, so the BRC token image wrongly takes priority.

**Comment by PurpleCrowbar** [comment]
@JayDi85 Given you are the most experienced with how the tokens in XMage work, do you have any idea as to why this happens?

**Comment by JayDi85** [comment]
@PurpleCrowbar if some ability put multiple tokens to the battlefield -- what's the best solution for the images selection?
 1. Put all tokens with **single** random-selected image;
 2. Put all tokens with **multiple** random-selected images for each token instance;

**Comment by PurpleCrowbar** [comment]
> @PurpleCrowbar if some ability put multiple tokens to the battlefield -- what's the best solution for the images selection?
> 
> 1. Put all tokens with **single** random-selected image;
> 2. Put all tokens with **multiple** random-selected images for each token instance;

I suppose it’s down to preference, but in most circumstances I would say that option 1 would be preferrable.

**Comment by JayDi85** [comment]
Most of the token's images problems were fixed in prev commits, so issue can be closed.
