### ISSUE TITLE
Donal, Herald of Wings

### ISSUE THREAD

**Issue by LegionedintheDamned** [magefree/mage#10141]
Evening, Donal created a copy of Loyal Drake.  The creature type and card copy were right, but the power and toughness were wrong.  I'll try to grab another screenshot this game.

![image](https://user-images.githubusercontent.com/82664393/227099799-58100a79-f3a1-4b66-b4bf-b3c4c838272b.png)

**Comment by xenohedron** [comment]
Fixed in #10389
