### ISSUE TITLE
Client app freeze after bundled cacerts

### ISSUE THREAD

**Issue by lewismather** [magefree/mage#10155]
<img width="798" alt="Screen Shot 2023-03-28 at 10 21 44 pm" src="https://user-images.githubusercontent.com/77604779/228424224-2795f0d2-e2c6-455f-935a-f643fb14e9c8.png">

**Comment by lewismather** [comment]
While trying to open the client- Some errors occured- anyone else had this problem? thanks

**Comment by JayDi85** [comment]
Your logs on screenshot are fine, there aren't any errors. Cacert needs to download images and symbols: #9135

**Comment by JayDi85** [comment]
OK, I've got you mean -- your client app freeze on startup without any errors in the logs. There are truevfs and swing gui code init after cacerts, so something wrong with it.

![shot_230401_093613](https://user-images.githubusercontent.com/8344157/229267660-15c716b0-07ad-4f33-854b-858cbe976706.png)


You can enable debug logs for more info:
* Go to `launcher -> settings -> java -> client options`
  * Change and put that command to the start: `-Dlog4j.configuration=file:./config/log4j.properties `
![shot_230401_092747](https://user-images.githubusercontent.com/8344157/229267357-66779981-2648-48fb-897e-d5be1dfeffbe.png)
* Go to `\xmage\mage-client\config\` and edit `log4j.properties` with any text editor:
  * Change: `log4j.rootLogger=info` to `log4j.rootLogger=debug`
  * Change: `log4j.appender.console.Threshold=info` to `log4j.appender.console.Threshold=debug`
![shot_230401_093421](https://user-images.githubusercontent.com/8344157/229267597-f87d6c9d-ee38-43ce-bd75-e4f458ae3c35.png)
  * Run client and look at new logs, maybe it will catch the real error.
