### ISSUE TITLE
[LEG] Implement three cards

### ISSUE THREAD

**Issue by xenohedron** [magefree/mage#10153]
Some old weird cards if anyone wants to take a crack at them:

[[Takklemaggot]]
[[Firestorm Phoenix]]
[[Illusionary Mask]]

**Comment by Grath** [comment]
A lot of the old weird cards aren't implemented because they're difficult to impossible to implement; if you'd like to see them happen, a more helpful approach would be to try it yourself.

**Comment by xenohedron** [comment]
Oh, I don't disagree, but I couldn't find them in an open issue and thought it worth tracking.

**Comment by Susucre** [comment]
All three cards covered by #11320 list.
