### ISSUE TITLE
Ability that not working at 100% | Liberator, Urza's Battlethopter + Morph creatures (blood moon problem)

### ISSUE THREAD

**Issue by MelestorIX** [magefree/mage#10168]
Hi, the third ability of [Liberator, Urza's Battlethopter] say "You may cast **colorless** spells and artifact spells as though they had **flash**", but in the game is **unable** to play any **morph creatures** as they had **flash** (they are all **colorless** if played as face down).

**Comment by JayDi85** [comment]
It's a "blood moon problem" (see #4202) -- xmage can't look ahead to see object stats before process a real resolve. Maybe will be fixed in the future.
