### ISSUE TITLE
Venser, Shaper Savant error

### ISSUE THREAD

**Issue by ndscable** [magefree/mage#1016]
I was playing against the AI in a Commander match and this card popped an error

Here is the error log, hopefully this helps:

Game exception occurred: java.lang.ClassCastException: mage.target.common.TargetSpellOrPermanent cannot be cast to mage.target.TargetPermanent
Server version: 1.4.0v2
mage.player.ai.ComputerPlayer.chooseTarget(ComputerPlayer.java:695)
mage.target.TargetImpl.chooseTarget(TargetImpl.java:319)
mage.target.Targets.chooseTargets(Targets.java:104)
mage.abilities.AbilityImpl.activate(AbilityImpl.java:335)
mage.players.PlayerImpl.triggerAbility(PlayerImpl.java:1139)
mage.game.GameImpl.checkTriggered(GameImpl.java:1419)
mage.game.GameImpl.checkStateAndTriggered(GameImpl.java:1381)
mage.game.GameImpl.playPriority(GameImpl.java:1139)
mage.game.turn.Step.priority(Step.java:87)
mage.game.turn.Phase.playStep(Phase.java:203)
mage.game.turn.Phase.play(Phase.java:115)
mage.game.turn.Turn.play(Turn.java:143)
mage.game.GameImpl.playTurn(GameImpl.java:738)
mage.game.GameImpl.play(GameImpl.java:661)
mage.game.GameImpl.start(GameImpl.java:628)
mage.game.GameImpl.start(GameImpl.java:613)
mage.server.game.GameWorker.call(GameWorker.java:60)
java.util.concurrent.FutureTask.run(Unknown Source)
java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
java.lang.Thread.run(Unknown Source)

**Comment by duncant** [comment]
I've experienced this bug as well, in the same context.

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.
