### ISSUE TITLE
Adriana, Captain of the Guard not triggering

### ISSUE THREAD

**Issue by LegionedintheDamned** [magefree/mage#10170]
As per the screenshot: melee is not triggering at all.

![image](https://user-images.githubusercontent.com/82664393/229684568-d5736ef7-68d9-4a51-a206-2e1646ef7961.png)

**Comment by Grath** [comment]
Duplicate of #9848 (also the screenshot clearly shows it IS triggering, but it's not actually pumping creatures.)
