### ISSUE TITLE
Instill Energy isn't giving haste

### ISSUE THREAD

**Issue by Chewbaklava** [magefree/mage#10176]
![image](https://user-images.githubusercontent.com/83886086/229968982-28afee1b-0f32-4fa6-a05c-fe9c6c84423d.png)

**Comment by theelk801** [comment]
[[instill energy]] doesn't grant hate, it just allows the creature to attack as though it has haste

**Comment by Chewbaklava** [comment]
Oh oof, Thanks. TIL
