### ISSUE TITLE
Save user's adjustments to size of frames between sessions

### ISSUE THREAD

**Issue by fireshoes** [magefree/mage#1018]
For example, the completed games area defaults to half of the vertical space with the active games above it, which is more than I like, so I have to drag the completed games lower each session. I know you can toggle it off, but I do want to see the completed games. Also in the deck editor, each time I go it, I have to reduce the size of the cards displayed in the search results to increase the size of the main deck. It would be much more convenient if these adjustments persisted each time I opened the client.

**Comment by JayDi85** [comment]
Deck editor saves devider settings. So no more actual.
