### ISSUE TITLE
Isshin two heavens as one and Raiyuu, Storm's edge.

### ISSUE THREAD

**Issue by jayzz911** [magefree/mage#10196]
Raiyuu gives you an additional combat phase when a samurai attacks alone if it is during the first attack phase.  Isshin allows abilities to trigger twice. The interaction in XMage currently gives you infinite attack phases.

**Comment by xenohedron** [comment]
The correct interaction should be to get two additional combat phases (three total), right?

**Comment by xenohedron** [comment]
Could not reproduce. The ability on Raiyuu still triggers twice (it's not an intervening if) in the additional combat phases, but total number of combat phases is three.

**Comment by jayzz911** [comment]
Indeed does not happen anymore,
