### ISSUE TITLE
jaheira's respite dont take attacking creatures into account

### ISSUE THREAD

**Issue by Fweiberth** [magefree/mage#10206]
jaheira's respite lets you fetch as many lands as you want from your deck when you cast it. It does not care about attacking creatures. I cast it during my main phase and fetched 18 lands.

Xmage version - 1.4.52-V3-beta2

[Jaheira's respite](https://scryfall.com/card/clb/238/jaheiras-respite)

**Comment by JayDi85** [comment]
[[Jaheira's Respite]]

**Comment by JayDi85** [comment]
Card's code looks fine. It's count only player's attackers, not a battle or a planeswalker (due rules, [see notes](https://magicjudge.tumblr.com/post/134054182316/does-arachnogenesis-count-creatures-attacking) for [[Arachnogenesis]])

**Comment by JayDi85** [comment]
Fixed by 79b8093047390e4f87481de1224a73c9d22334c2, added card hint about creature attacking amount
