### ISSUE TITLE
Allow click and drag selection of permanents

### ISSUE THREAD

**Issue by thefnitalian** [magefree/mage#10201]
A way to click and drag a box to select permanents on the battlefield similar to windows explorer.

**Comment by JayDi85** [comment]
It's a complicated task for GUI/UX cause xmage engine requiring a client's feedback on each choice, processing it on server side and continue/stop a choosing process due that single selection.

Please describe few examples with that feature:
1. Discard cards from the hand;

**Comment by thefnitalian** [comment]
This idea was only for the battlefield. I wasn’t even thinking of other zones.
For example,
1. Selecting permanents when asked to sacrifice permanents from an opponent’s effect.
2. Selecting permanents for when asked which attackers you would like to attack with.
3. Selecting targets for devour effect.
4. Etcetera.
