### ISSUE TITLE
Baba Lysaga, Night Witch

### ISSUE THREAD

**Issue by LegionedintheDamned** [magefree/mage#10210]
This creature's ability does not work as intended.  Two attempts:
1. Mishra's Factory: when activated, this should count as all 3 permanent types; artifact, creature, and land.  It does not.
2. Liquimetal Coating and man lands: the combination should count as all 3 permanent types; artifact, creature, and land.  It does not.

**Comment by JayDi85** [comment]
[[Baba Lysaga, Night Witch]]

**Comment by JayDi85** [comment]
[[Mishra's Factory]], [[Liquimetal Coating]]

**Comment by JayDi85** [comment]
Related rule's notes:

Check the types of those permanents as they last existed on the battlefield to see if there were three or more card types among the sacrificed permanents. (2022-06-10)

**Comment by LegionedintheDamned** [comment]
![image](https://user-images.githubusercontent.com/82664393/236727904-6ecb8fd3-1699-4671-80b8-6c0f8fccc5cc.png)
![image](https://user-images.githubusercontent.com/82664393/236727997-f71a530e-75aa-4230-9742-fe8f2cb516cf.png)
![image](https://user-images.githubusercontent.com/82664393/236728042-68a8c7a9-9ee2-41a7-a7d2-4b75486fafc6.png)

These are from just now, in the current environment.  As you can see: Mishra transforms into an artifact creature and was a land already/  Baba Lysaga sacrifices it - no trigger.
