### ISSUE TITLE
[INV] Split cards incorrectly showing text for Fuse ability

### ISSUE THREAD

**Issue by xenohedron** [magefree/mage#10217]
The original ten split cards (<https://scryfall.com/search?q=is%3Asplit+block%3Ainv>) do not have the fuse ability. On xmage the cards are shown with the fuse ability, although the behavior is correct and the cards cannot be cast with fuse.

**Comment by JayDi85** [comment]
Fixed by 29afbe042c4c8e1d08115c6e7b21017898c1d044
