### ISSUE TITLE
Problem with Blast-Furnace Hellkite's artifact offering ability

### ISSUE THREAD

**Issue by TakeHeedStruggler** [magefree/mage#10218]
I was trying to cast Blast-Furnace Hellkite with flash offering a Treasure token, but I got the following report:

Game exception occurred: java.lang.NullPointerException
Server version: 1.4.52-V3-beta5 (build: 2023-04-14 15:23)
mage.abilities.keyword.OfferingCostReductionEffect.apply(OfferingAbility.java:229)
mage.abilities.effects.ContinuousEffects.costModification(ContinuousEffects.java:741)
mage.abilities.AbilityImpl.activate(AbilityImpl.java:392)
mage.abilities.ActivatedAbilityImpl.activate(ActivatedAbilityImpl.java:265)
mage.game.stack.Spell.activate(Spell.java:145)
mage.players.PlayerImpl.cast(PlayerImpl.java:1212)
mage.players.PlayerImpl.activateAbility(PlayerImpl.java:1470)
mage.player.human.HumanPlayer.activateAbility(HumanPlayer.java:2149)
mage.player.human.HumanPlayer.activateAbility(HumanPlayer.java:2172)
mage.player.human.HumanPlayer.priority(HumanPlayer.java:1239)
mage.game.GameImpl.playPriority(GameImpl.java:1563)
mage.game.turn.Step.priority(Step.java:61)
mage.game.turn.Phase.playStep(Phase.java:184)
mage.game.turn.EndPhase.playStep(EndPhase.java:47)
mage.game.turn.Phase.play(Phase.java:89)
mage.game.turn.Turn.play(Turn.java:125)
mage.game.GameImpl.playTurn(GameImpl.java:1057)
mage.game.GameImpl.play(GameImpl.java:967)
mage.game.GameImpl.start(GameImpl.java:943)
mage.server.game.GameWorker.call(GameWorker.java:34)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)

**Comment by JayDi85** [comment]
[[Blast-Furnace Hellkite]]

**Comment by JayDi85** [comment]
Fixed by ce3cf742c99beab3f2d18c10dafb6bc7d37cc3a8
