### ISSUE TITLE
Split cards not accepted in Tiny Leaders

### ISSUE THREAD

**Issue by emerald000** [magefree/mage#1022]
xMage will not let you add a split card with total CMC > 3. Split cards where each half has CMC <= 3 are legal in Tiny Leaders.

For example: Fire // Ice and Far // Away

**Comment by LevelX2** [comment]
Fixed with https://github.com/magefree/mage/commit/65401f1cbc96668afefd4084c0164ef8dce2ed48.

Added also the missing check of cards in the sideboard.
