### ISSUE TITLE
Token copies inherit the set code of the card that created them, not the original permanent

### ISSUE THREAD

**Issue by PurpleCrowbar** [magefree/mage#10222]
If a player controls an NEC [[Silver Myr]], an MH2 [[Esper Sentinel]], and a 0/0 MED Construct token, then casts a BRC [[March of Progress]] with overload to create token copies of each of those artifact creatures, those token copies will have set code BRC as opposed to their respective set codes. 

Xmage searches the BRC set for images to assign these token copies, but because BRC does not contain Silver Myr or Esper Sentinel no images are found, and so no images are assigned. In the case of copying tokens, Xmage searches the BRC set for a token image with the same name as the copied permanent. In this case, it finds a token image called "Construct token" and uses it for the image of the token copy. Unfortunately, because it uses a BRC Construct token image, the image depicts a 1/1 Construct token with no ability, whereas the copied permanent was a 0/0 with "This creature gets +1/+1 for each artifact you control". See below:

![image](https://user-images.githubusercontent.com/26198472/232263177-80250c45-cfe3-41a1-a296-5b2b108dfc65.png)
<details><summary>Click to view incorrectly assigned token image (note the set code, BRC)</summary>

![image](https://user-images.githubusercontent.com/26198472/232263307-d6279694-77aa-4da1-a812-9c586ce1dd29.png)
</details>

When creating a token copy of a permanent, Xmage must inherit the set code and token type of the original permanent.

To test this bug yourself, use the following command list on a test server (-2 Karn to generate the Construct token):

```
[Testing Copied Permanents' Setcodes]
hand:YourUsername:BRC-March of Progress:1
battlefield:YourUsername:Island:7
battlefield:YourUsername:NEC-Silver Myr:1
battlefield:YourUsername:MH2-Esper Sentinel:1
battlefield:YourUsername:MED-Karn, Scion of Urza:1
```

**Comment by JayDi85** [comment]
Fixed by 94819ff91c526679556839c32938a11ac4dfc3ea
