### ISSUE TITLE
Dead Reckoning can be cast without a target in play (and then does nothing)

### ISSUE THREAD

**Issue by NibiruMTG** [magefree/mage#10224]
[[Dead Reckoning]] needs two targets - a creature in play and a creature in your yard. It can be cast without the former and then doesn't return the creature to your hand, which is confusing and should not be possible.

**Comment by xenohedron** [comment]
Fixed by 19f38a70dabe60f9bd334b39b527a65367a3372d

**Comment by theelk801** [comment]
thanks, forgot to tag this in the commit message
