### ISSUE TITLE
Ancient Imperiosaur does not enter the battlefield with any counters when convoked

### ISSUE THREAD

**Issue by PurpleCrowbar** [magefree/mage#10237]
When convoking [[Ancient Imperiosaur]], the creature does not enter the battlefield with any +1/+1 counters on it. Seemingly related to #10233 and `ConvokeSourceCount` not working as intended.

**Comment by JayDi85** [comment]
Must be fixed after refactor in 5474787641a7f19cc5fc471327cf73549d7d7c06 and 689b93d0058e512eca3abf31cb3b3616be29aa7a

**Comment by PurpleCrowbar** [comment]
@JayDi85 Those changes seem to have fixed Knight-Errant of Eos, but this card remains broken with the counters not being added as expected

**Comment by xenohedron** [comment]
I bet this is another MageObjectReference issue like Mindlink Mech - reference #10391
