### ISSUE TITLE
First Strike Anthem Dying in First Strike Phase Resulting in Double Strike

### ISSUE THREAD

**Issue by LegionedintheDamned** [magefree/mage#10232]
Board setup:
Computer 2 has [[Dread]].  Computer 4 has [[Archetype of Courage]] and [[Battle Angels of Tyr]].  I have [[Nymris, Oona's Trickster]] (only relevant part of that is 1/6 body).

Computer 4 attacks Computer 2 with Archetype.  Everyone is attacked by a Battle Angel.  I block with Nymris.  Archetype dies in the first strike damage step, due to Dread.  Nymris takes 5 damage in the first strike damage step.  In the normal strike damage step, Nymris takes a further 5 damage from Battle Angel.

As per
702.7b If at least one attacking or blocking creature has first strike or double strike (see rule 702.4) as the combat damage step begins, the only creatures that assign combat damage in that step are those with first strike or double strike. After that step, instead of proceeding to the end of combat step, the phase gets a second combat damage step. The only creatures that assign combat damage in that step are the remaining attackers and blockers that had neither first strike nor double strike as the first combat damage step began, as well as the remaining attackers and blockers that currently have double strike. After that step, the phase proceeds to the end of combat step.
702.7c: Giving first strike to a creature without it after combat damage has already been dealt in the first combat damage step won’t prevent that creature from assigning combat damage in the second combat damage step. Removing first strike from a creature after it has already dealt combat damage in the first combat damage step won’t allow it to also assign combat damage in the second combat damage step (unless the creature has double strike).

![image](https://user-images.githubusercontent.com/82664393/232958828-141c7c88-9f89-4745-a693-9e0642c9b939.png)

**Comment by xenohedron** [comment]
Wow, apparently nobody ever noticed that first strike is fundamentally bugged in violation of 702.7c

![image](https://github.com/magefree/mage/assets/12538125/fb140722-075b-4b44-bc63-55d6eff1e7a7)

The method as written doesn't have enough info to determine according to the rules whether a creature should be dealing damage. Needs game param and must check watcher for that combat phase.
