### ISSUE TITLE
Enchantment Creature Treated as Creature on Entry (bloodmoon problem)

### ISSUE THREAD

**Issue by LegionedintheDamned** [magefree/mage#10239]
[[Xenegos, God of Revels]] was allowed _riot_ when entering via [[Rhythm of the Wild]].  This is similar to issue #10211 and perhaps #4202.

![image](https://user-images.githubusercontent.com/82664393/233250348-51d6da50-6c09-4259-b835-32e48c443561.png)

**Comment by JayDi85** [comment]
[[Xenagos, God of Revels]]
