### ISSUE TITLE
Xmage fails to account for "next spell you cast has convoke" when determining whether or not a card can be cast

### ISSUE THREAD

**Issue by PurpleCrowbar** [magefree/mage#10247]
Presumably also applies to improvise. When using the second ability of [[Wand of the Worldsoul]], and having two untapped lands and one untapped creature, the user cannot play a 3 cost card that would be playable when using the convoke ability. This is because the card does not "have" convoke whilst in hand, only gaining the ability when being cast. For this reason, despite the next spell you cast having convoke, you can only play cards that you could already cast with the mana available to you from lands and other mana sources.

**Comment by PurpleCrowbar** [comment]
[[Wand of the Worldsoul]]

**Comment by xenohedron** [comment]
Perhaps it could be implemented as `GainAbilityControlledSpellsEffect`, with a condition that checks the watcher, so the convoke ability appears in other zones not just the stack. Might need a bit of refactoring.

**Comment by Susucre** [comment]
#10112 has similar issue.

**Comment by xenohedron** [comment]
Fixed by #10787
