### ISSUE TITLE
Omnath, Locus of All bug

### ISSUE THREAD

**Issue by catman123456** [magefree/mage#10248]
[[Omnath, Locus of All]] did not give the 3 mana for reveling [[Atraxa, Praetors' Voice]]

![image](https://user-images.githubusercontent.com/64045003/233597970-713db366-fec3-4e2b-b8e7-e90d8eb8ec8d.png)

**Comment by ZarakiKanzaki** [comment]
Indeed it doesn't, I would love to help solve this issue, I need to know where to find the card though.
