### ISSUE TITLE
Color selection dialog window turns the client unresponsive

### ISSUE THREAD

**Issue by calkno** [magefree/mage#10243]
Issue occurred when attempting to assign color for Utopia Sprawl, but noticed it when other cards have a color dialog box open. Perhaps an issue with MacOS and the latest 2 updates? Attached is the returned log.

[xmage_issue_20230420.txt](https://github.com/magefree/mage/files/11284521/xmage_issue_20230420.txt)

**Comment by JayDi85** [comment]
Try to open multiple times: connection -> country flag choose dialog. Is it works for you?

![shot_230420_135116](https://user-images.githubusercontent.com/8344157/233330166-cb8145f4-0472-4eff-9791-005dd5637f16.png)

**Comment by calkno** [comment]
This caused the same issue

**Comment by JayDi85** [comment]
@calkno then it's a third party app problem like Contexts app, see more details and examples in https://github.com/magefree/mage/issues/4920#issuecomment-517944308

**Comment by calkno** [comment]
Thank you for the guidance. I tracked the fix back to a setting I was screwing around with the other night. Once disabling this setting I no longer have the issue.

![image](https://user-images.githubusercontent.com/36138660/233693828-70c7045a-b4b4-473b-8491-dfe0de71fbbc.png)
