### ISSUE TITLE
AI stops working with Battle cards in play

### ISSUE THREAD

**Issue by PurpleCrowbar** [magefree/mage#10246]
I've found that when a battle permanent is in play the AI seems to totally freeze up. This means taking the full amount of time it is allowed to process the board, and spends so long processing every time it's given priority that it will end up passing the turn having done nothing, eventually discarding to hand size (and discarding lands that it would otherwise have played). Given that this is a new card type I imagine there's no AI code to handle them yet and that that may be causing the issue.

**Comment by JayDi85** [comment]
Must be fixed by e4157fefb8d924cbf014534753e13c288d2d902f -- now AI can find and attack battle permanents
