### ISSUE TITLE
Invasion of ikoria can’t tutor

### ISSUE THREAD

**Issue by Deedl1e** [magefree/mage#10249]
When you go to tutor it says an error has occurred some shows sort of code and then rolls back the turn ):

**Comment by theelk801** [comment]
can you post the error you got? I can't recreate this

**Comment by theelk801** [comment]
[[invasion of ikoria]]

**Comment by Deedl1e** [comment]
Since the time I posted that, it has since been fixed and is working.
However not fully… the card also reads that it can get cards from the
graveyard or library and it’s not even allowing the graveyard portion.

**Comment by JayDi85** [comment]
> and it’s not even allowing the graveyard portion

If you choose nothing in library then it allows to search in graveyard too
