### ISSUE TITLE
Jace, Telepath Unbound won't let me cast split cards in GY for their chosen cost

### ISSUE THREAD

**Issue by duelcastermage** [magefree/mage#10272]
With the flipside planeswalker of [[Jace, Vryn's Prodigy]] (Jace, Telepath Unbound), I -3'd and targeted [[Fire // Ice]] in my graveyard with two mana open. I never got to cast either half of the card; I think XMage assumed its mana value was 4 and I couldn't cast anything(?)

**Comment by xenohedron** [comment]
duplicate of #9607
