### ISSUE TITLE
unable to update Xmage

### ISSUE THREAD

**Issue by salyG** [magefree/mage#1027]
Boss, i press update but the system just wont update it to ver 1.4.1v0 .  it updated itself, removed previous versions but in the end the version is still 1.4.0v2 .

**Comment by LevelX2** [comment]
The download files work for me and many others. So it's probably a problam, that your client cant access the files in the internet.
So maybe a firewall/router problem.

What's your Operation System and OS version?

Does it work if you download the launcher again and save it to another directory?

**Comment by R1ncewind** [comment]
I have the same problem, the updater says
> Reading config from http://xmage.info/xmage/config.json
> Invalid config from http://xmage.info/xmage/config.json

**Comment by vexguine** [comment]
Same problem here:

Xmage Launcher v0.3.4 shows the following

"Reading config from http://xmage.info/xmage/config.json
Invalid config from http://xmage.info/xmage/config.json"

i saw that xmage.info does not work anymore. So I changed the xmage home in the "settings" of Launcher. It shows:

Reading config from http://xmage.de/config.json
Error reading config from http://xmage.de/config.json
Possible causes:  Site is offline or internet connection is unavailable.


using Win7. Any solution?

**Comment by salyG** [comment]
well, the previous updates have been fine until now. i guess there goes my career of xmage. 
"Error, could not find or load main class mage cilent.mageframe".

Windows 7 home premium. 64 bit operating system.

**Comment by salyG** [comment]
Error:could not find or load main class mage frame.

**Comment by LevelX2** [comment]
> Reading config from http://xmage.de/config.json
> Error reading config from http://xmage.de/config.json
> Possible causes: Site is offline or internet connection is unavailable.

Seems like you set the XMage home to  "http://xmage.de/" instead of correctly  "http://xmage.de/xmage".

**Comment by salyG** [comment]
ok nevermind. i found my way back into the server and its updated to the latest.  Thanks boss
