### ISSUE TITLE
Dictate of Karametra

### ISSUE THREAD

**Issue by Diegogrt93** [magefree/mage#1028]
Dictate of Karametra is adding a colorless mana, instead of a mana from the type of the first mana produced.

**Comment by LevelX2** [comment]
I can't reproduce this problem. By using which land that problem happens?

**Comment by fireshoes** [comment]
If you recall, I had that problem with Mana Flare a couple weeks ago.


Re: Bug Reports xmage 1.4.0
Mana Flare is only adding colorless mana, at least off of dual lands (Watery Grave in this instance).

Edit: Island only adds colorless. Plains adds white though.

LevelX: Can't reproduce this.

by fireshoes
    03 Jun 2015, 22:48

**Comment by drmDev** [comment]
Not sure if this is still an issue, will need to test later

**Comment by drmDev** [comment]
Also cannot duplicate this old issue. In game tested fine with all sorts of lands.
