### ISSUE TITLE
Adding cards + features for Yedora

### ISSUE THREAD

**Issue by jal218** [magefree/mage#10298]
Hello, 
would it be possible to add cards Henzie 'Toolbox' Torre and Recommission to the card pool. Furthermore, for the card Yedora Grave Gardener if it returns a creature face-down as a forest, the card should be able to turn face-up if it has a morph ability. Would it be possible to fix this?
Kind regards
JL

**Comment by alexander-novo** [comment]
Henzie has had some work done on it, but currently is very broken. I guess there are some issues with Blitz. You can track progress at #9463. It looks like those involved have moved on.

As far as I know, Recomission is already available.

The yedora bug is already report at #8109
