### ISSUE TITLE
Baral and Kari Zev trigger doesn't work

### ISSUE THREAD

**Issue by NapoleonBorn2Party** [magefree/mage#10295]
This cards' ability to cast an instant or sorcery spell that shares a card type with it with a lesser mana value from hand without paying its mana cost doesn't work, as it doesn't even trigger. The deck I was testing it on is [this one](https://www.mtggoldfish.com/deck/5565460#paper). The game mode tested was Constructed - Modern, Two Player Duel.

**Comment by alexander-novo** [comment]
[[Baral and Kari Zev]]
