### ISSUE TITLE
Belfry Spirit (Haunt in general?) not working on opponent's token

### ISSUE THREAD

**Issue by duelcastermage** [magefree/mage#10308]
I had a [[Belfry Spirit]] that died. I put the haunt on an opponent's 1/1 token. Later I killed that token, but the haunt trigger that I should've gotten never triggered.

**Comment by xenohedron** [comment]
Sounds like #7689 can be successfully reproduced

**Comment by xenohedron** [comment]
I'm working on fixing this one.

**Comment by xenohedron** [comment]
* Resolved by #10310
