### ISSUE TITLE
Zurzoth + Gibbering did not trigger

### ISSUE THREAD

**Issue by LegionedintheDamned** [magefree/mage#10305]
![image](https://user-images.githubusercontent.com/82664393/235406381-e749ceb9-698e-459c-b01c-3627fa86cc4a.png)

As per the image, only one trigger happened as opposed to previously where it correctly triggered.

**Comment by alexander-novo** [comment]
What is Gibbering? I don't see anything with that name in the image?

[[Zurzoth, Chaos Rider

**Comment by alexander-novo** [comment]
What is Gibbering? I don't see anything with that name in the image?

[[Zurzoth, Chaos Rider]]

**Comment by LegionedintheDamned** [comment]
[[Gibbering Fiend]].  Sorry.

**Comment by alexander-novo** [comment]
I don't see a gibbering fiend in that screenshot. Are you mistaking the devil token for a gibbering fiend?

**Comment by LegionedintheDamned** [comment]
I was a tiny bit delayed taking the screenshot.  Zurzoth attached the player 'Foamy'.  Gibbering attacked the player 'DonJuba'.  DonJuba blocked with Umbris and killed it.

**Comment by alexander-novo** [comment]
That screenshot doesn't say that, it says that the only attacker was Zurzoth. But even if there was a gibbering fiend attacking here, what was the missed trigger? It looks like Zurzoth's trigger happened?

**Comment by LegionedintheDamned** [comment]
Correct, but Zurzoth should be 1 trigger per player attacked.  So it should have been 2 devils.

**Comment by alexander-novo** [comment]
Zurzoth says "Whenever one or more Devils you control attack one or more players', so it's one trigger per attack, no matter the number of attacking creatures or attacked players.

**Comment by LegionedintheDamned** [comment]
Yes, but the key wording is :"..you and those players each draw a card, then discard a card at random."  So there's only 1 devil token post swing, but there should have been 2.

**Comment by alexander-novo** [comment]
Okay, so did each opponent do the draw/discard, but the devil trigger only happened once, or did only one person draw/discard?

**Comment by LegionedintheDamned** [comment]
Correct.  Both opponents drew and discarded, and only a single devil was created.

**Comment by alexander-novo** [comment]
I can't reproduce this issue, and the given screenshot/description isn't really helping. Unfortunately, the screenshot doesn't actually show the bug being described. I set up a test for anyone who wants to look into it further, it can be found on [this branch of my fork](https://github.com/alexander-novo/mage/tree/fix-zurzoth).
