### ISSUE TITLE
Extended ignore system 

### ISSUE THREAD

**Issue by spjspj** [magefree/mage#10316]
Currently you are able to type in /ignore and ignore a given username.  This is good and works ok.
The problem is that if a troll is actively targeting you, you will say /ignore TrollUser, they will immediately then create TrollUser0, then TrollUser1 etc.  They could also use another name such as NormalDude.

If the xmage client added an unique uuid to the registry and sent that uuid through as part of the connection information, the server would have a hash of   {uuid} => {TrollUser, TrollUser0, TrollUser1, TrollUser2, NormalDude}, tying together the troll with all of their currently used user names.

Thus, when someone /ignores TrollUser, they also would get, for free and totally opaque to them, get to ignoreTrollUser0, TrollUser1 and NormalDude.

Maybe keep the original option of being able to ignore individual usernames 
(aka:  /ignore TrollUser) 
which would keep the same functionality as now,

but then an extended version:
/ignore_extended TrollUser 
which would then ignore all of the following TrollUser, TrollUser0, TrollUser1, TrollUser2, NormalDude.  

The user would only actually know that they've ignore_extended TrollUser, but would have, opaquely, also silently ignored TrollUser0, TrollUser1, TrollUser2, NormalDude at the server level.

The list of extended users to ignore (aka TrollUser0, TrollUser1, TrollUser2, NormalDude) would be sent to the xmage client on login to live in memory and add to the list of explicit /ignore from the registry.

There would also have to be a command such as /refresh_ignore that would cause the server to send through an updated ignore list in memory that would add to the list of ignore_extended people (aka if the troll has added a new username of 'ReallyNormalDude', the refreshed list would come back from the server as:  {TrollUser0, TrollUser1, TrollUser2, NormalDude, ReallyNormalDude})

**Comment by alexander-novo** [comment]
This is an open-source app, if we store a UUID like this somewhere, it will get around how to delete it. You would need something closer to a hardware ID, but there are privacy concerns with something like this.

I've thought about it, and I think it would be nice to instead have an option to create a room with a minimum # of games required to join the room. And the feature would only unlock after so many games (maybe 100), and you would be capped at 10% of your total game.

So if you had played 200 games, you could require someone have 20 or more games before joining your rooms. This encourages longer running accounts.

**Comment by spjspj** [comment]
If they delete it, the UUID's blank, so they can get automatically ignored as well, depending on if that's what the client wants.  There's no privacy concerns - it's just a random UUID being sent to the server which already has your IP/xmage-names/etc.  I agree, adding the minimum number of games would be good but then new players would never get a game potentially.

**Comment by Grath** [comment]
How do you solve "everyone gets a UUID" problem without "if you delete it, the system that generates a new one for people who don't have one yet generates a new one for you"? It'd mean that the trolls have to do an extra step between jumping usernames, but given what we've seen of troll behavior they're pretty dedicated since they'll do stuff like waste an entire day just crashing the server over and over.

**Comment by alexander-novo** [comment]
> If they delete it, the UUID's blank, so they can get automatically ignored as well, depending on if that's what the client wants. There's no privacy concerns - it's just a random UUID being sent to the server which already has your IP/xmage-names/etc. I agree, adding the minimum number of games would be good but then new players would never get a game potentially.

That's just moving the goalpost - then people are just going to modify the UUID rather than delete it.

As far as new players, nothing stops them from creating their own rooms. From what I've seen of how the power level restrictions on rooms go - adding a new restriction will only make it harder for the people who want to be restrictive to find games. Then people need to choose if they want ti to be harder to find a game or allow newer players. And in general people will join whatever room is available, even if it was started by a new player.

**Comment by spjspj** [comment]
Most people don't change a single thing via regedit.  The server will know precisely which client is coming in - from IP, from previous names in the regedit, from the UUID identifier.  If the client changes the UUID or removes it, the server will still know, for that session, that that particular UUID is associated with those particular usernames and/or given username.  The other client is still able to add new ignores.  If it makes it harder for trolls, how is it a bad thing?

**Comment by Grath** [comment]
Most people don't spend hours trolling people on XMage with racist nonsense and attempting to slow down and/or crash the server. Given the dedication I've heard described (4-8 hours of endless trolling), I don't see it being likely that this actually inconveniences the trolls beyond "they have to figure out that this happened, which they could do from this issue and/or the ensuing commits."

**Comment by spjspj** [comment]
Most systematic / programmatic attempts to do so are eventually stopped (for example #9815).  The /ignore option has been available for like 5+ years without any update.  Tying together multiple annoying users in one UUID, along with IP, such that if any of the annoying usernames are ignored then all are ignored, can only help.  If the trolls have to jump through more hoops, that seems like a good thing.

**Comment by JayDi85** [comment]
Yes, there is possible to use a hardware id for users ban/black list (same blacklist commands, but client will save hardware id for online user too). It's a private, anon and can be useful for current anon server mode (connect to server without a registration). Trolls will still be able to bypass these restrictions, but it will be made much more difficult (example: needs to change MAC-address).

A users registration can fix that problem at all, but I don't want to enable it for current server yet.

P.S. Some plans for the future:
- serverless connect by openid/jwt, so any server will able to use approved users to play: anon connect by any username or approved connect by email confirmation (it's like current registration by email but without users data store on the server side);
- shared stats/rating/leaderboard for approved users and matches (can able to play approved matches on any servers and send results to the official).

**Comment by Anarasha** [comment]
> A users registration can fix that problem at all, but I don't want to enable it for current server yet.

Why? We desperately need it. 
Currently the server is being stalked by a nazi troll spouting racial slurs, roping games and all in all ruining the experience for everyone, and if people are to be believed, this has been the case for a really long time. 
Please enable it.

**Comment by alexander-novo** [comment]
> along with IP

IP bans don't work. Games tried them long ago and found the IPs change too easily, and you can end up IP banning someone innocent because they ended up with someone else's IP.

> Trolls will still be able to bypass these restrictions, but it will be made much more difficult (example: needs to change MAC-address).

It's much easier than that. Just need a client which has been modified to send spoofed data instead of actual hardware info. This is an open source app, we can't trust anything the client sends the server.

In the end, the real problem is that eventually a troll will be able to make a new "account" not tied to any other account no matter what reasonable restrictions we put on them. This is an intrinsic problem of free & open source apps. The only solutions are being able to filter out all of these new accounts in some reasonable manner (as described above) and preventing these new accounts from becoming "old" accounts through some sort of community moderation.

**Comment by spjspj** [comment]
It's not just IP - it would be the proposed solution of a new, separate UUID, along with the already used list username and IP.  The confluence of those identifying factors is quite a bunch of hurdles for someone to go through and recompile against given the frequency of updates to the client.  Recompiling a custom client takes time for fairly limited benefit to the troll.

**Comment by JayDi85** [comment]
> What is the reasoning behind this

1. Don't want to restore old users database from a de-server (I have some backups);
2. Want to keep current server faster and easy to use;
3. Waiting for global auth server and mutual mode (anon and registered, see [comments above](https://github.com/magefree/mage/issues/10316#issuecomment-1555868874)).

P.S. I plan to finish players list, turn order and range refactor soon (it took an unexpectedly long time) and will take ignore and moderation tools on work. Just wait.

**Comment by Anarasha** [comment]
> Exactly. What is the reasoning behind this? With the current situation XMage is not even usable, the racist Troll is joining every single Lobby as I am typing this. So at least give us a good reason why. Why go the lengths and try to find another, apparently more complicated solution?


Racist troll is an understatement. He's also xenophobic with Nazi statements and names. It goes far beyond dumb racism

**Comment by Anarasha** [comment]
> Yes, he is absolutly insane. Really makes me feel bad when I read his mental garbage. I hope the update will come soon.

Honestly, I mostly feel bad for him. Something must be seriously wrong in his life if this is how he needs to get attention. But talking with him is not on the table because of the nature of trolls

**Comment by alexander-novo** [comment]
Fast from a "new user" standpoint. He wants to keep the barrier to entry low because of the low player base.

**Comment by Anarasha** [comment]
Okay, I understand why my comment was deleted. 
But the fact that a comment where I quote what the troll is saying gets deleted almost instantly hopefully at least underlines my point.

**Comment by Anarasha** [comment]
> Fast from a "new user" standpoint. He wants to keep the barrier to entry low because of the low player base.

Anyway, a slightly filtered version of what I said was that while I don't have any concrete data to refer to, my gut tells me that far fewer people are going to be scared off from xMage by required registration than logging on and the first thing they see is someone ruining tables by roping while writing..... well racial slurs of the nastiest kind, especially about Muslims and black people. 
And this is every single day. 
I just reached 190 ignores, at least half of them are the troll

**Comment by Anarasha** [comment]
> I just decided to quit XMage until this Problem is fixed , and we we get this centralized registartion server.

I considered it too. The racism and Nazi leanings are revolting to say the least.

**Comment by jeffwadsworth** [comment]
This is a free, open-source project.  Anyone can setup their own server and try to restrict access to chaotic accounts.  This isn't a corporate setup.

**Comment by Anarasha** [comment]
> This is a free, open-source project. Anyone can setup their own server and try to restrict access to chaotic accounts. This isn't a corporate setup.

It's not like we don't know this. But the fact of the matter is, there is a server that's considered the official one, and bringing up serious issues with Nazi rhetoric on said server isn't the antithesis to appreciating the voluntary work put in.
