### ISSUE TITLE
Permanents' hint text duplicated when on battlefield

### ISSUE THREAD

**Issue by PurpleCrowbar** [magefree/mage#10312]
When a permanent with a hint (e.g. Artifacts you control) is on the battlefield, any hints associated with that permanent's abilities have their text duplicated. Whilst the card is in hand, however, the hint only displays once, as expected. See permanent card with hint in hand compared to on the battlefield:

<details><summary>In hand</summary>

![image](https://user-images.githubusercontent.com/26198472/235813151-a2141a65-6fba-41a1-af02-2f4c23891a42.png)
</details>

<details><summary>On the battlefield</summary>

![image](https://user-images.githubusercontent.com/26198472/235813303-479db908-7681-4961-9e12-2c0593034a2b.png)
</details>

This is a relatively recent regression, though I'm not sure which commit caused it.

**Comment by xenohedron** [comment]
The offending commit is 914cfc1d3abf035b29054eb64ab675e4f6b808c8

**Comment by JayDi85** [comment]
Same hints must be ignored
