### ISSUE TITLE
When casting spells or using abilities the existing mana in mana pool is not being used

### ISSUE THREAD

**Issue by Greeneye0** [magefree/mage#1031]
See the attached screen shot:
![image](https://cloud.githubusercontent.com/assets/11687236/8165258/281965cc-134c-11e5-920a-686ca0515127.png)

note that I have 4 white mana in my mana pool.  I had the same problem when trying to cast as well.

**Comment by Greeneye0** [comment]
Nevermind, I see that you now have to click on the mana in your mana pool that you want to use.

**Comment by LevelX2** [comment]
Beside this you can force the old behaviour by setting the related option to off.
![savemana](https://cloud.githubusercontent.com/assets/2066790/8171324/540262d6-13b7-11e5-8294-868b1d695292.jpg)
