### ISSUE TITLE
[BUG] HAKTOS THE UNSCARRED

### ISSUE THREAD

**Issue by Clipper70** [magefree/mage#10314]
Seems to be bugged regarding it's protection clause.  doesn't seem to gain protection to numbers other than the randomly selected number (including 0 cmc which it should always have protection from; on xmage Haktos can still be blocked by flying shark tokens created from shark typhoon etc).  The example from me just then was that i played Haktos, 4 was the randomly selected number and then my opponent was able to target and kill it with the 3 cmc spell Hero's Downfall.

**Comment by Grath** [comment]
Should be fixed by #10289 next time there's a release.

**Comment by Clipper70** [comment]
awesome, thanks for the heads up :)
