### ISSUE TITLE
Initiative seems to be bugged

### ISSUE THREAD

**Issue by TakeHeedStruggler** [magefree/mage#10338]
When taking the initiative, the game correctly identifies that you have it, but no further abilities trigger, effectively preventing you from advancing into the dungeon

**Comment by Grath** [comment]
The Initiative is somehow no longer venturing into The Undercity at all. @JayDi85 - tagging you in because you were reworking things including The Initiative.

**Comment by stevedavidmusic** [comment]
Monarch is also bugged too, probably for the same reason initiative is.
