### ISSUE TITLE
Monarch doesn't trigger carddraw anymore

### ISSUE THREAD

**Issue by rockydirtbag** [magefree/mage#10334]
When a player becomes the monarch, there is no triggered ability to draw at the endstep.

**Comment by TakeHeedStruggler** [comment]
It's also impossible to steal the Monarchy from any player who gets it

**Comment by stevedavidmusic** [comment]
I'd imagine monarch bugs are probably related to initiative bugs in issue #10338

**Comment by JayDi85** [comment]
Fixed by 6d4e353867feaea7b839b5aa30b94cbb3468ea56
