### ISSUE TITLE
Baral and Kari Zev trigger does not work

### ISSUE THREAD

**Issue by Mercsetronics** [magefree/mage#10336]
https://scryfall.com/card/mom/218/baral-and-kari-zev
The not keyword ability does not work, does not trigger, it does nothing.
"Whenever you cast your first instant or sorcery spell each turn, you may cast a spell with lesser mana value that shares a card type with it from your hand without paying its mana cost. If you don’t, create First Mate Ragavan, a legendary 2/1 red Monkey Pirate creature token. It gains haste until end of" 
Whenever I cast my first instant/sorcery, nothing happens at all.

**Comment by Grath** [comment]
Already fixed by https://github.com/magefree/mage/commit/c270e5f20e5d498947cd95038c59f2dfc59593a2 so it'll work on the next release.
