### ISSUE TITLE
Undercover Operative doesn't get the shield counter

### ISSUE THREAD

**Issue by TakeHeedStruggler** [magefree/mage#10340]
It seems like Undercover Operative doesn't get a shield counter when it ETBs as a copy of a creature you control

**Comment by xenohedron** [comment]
[[Undercover Operative]]

**Comment by xenohedron** [comment]
Guessing it has to do with `((Permanent) blueprint).isControlledBy(source.getControllerId()))` which is the only instance in the codebase of `blueprint` being cast to `Permanent`.

**Comment by xenohedron** [comment]
Actually, when I tried this it seemed to work fine as is. Can you give any more information on how to reproduce?
