### ISSUE TITLE
BUG / MOM: "Halo Forager" does not cast the targeted spell

### ISSUE THREAD

**Issue by Don-Cruz** [magefree/mage#10348]
When Halo Forager enters the battlefield it correctly triggers: the player gets the opportunity to choose a certain cmc and then target an instant or sorcery in the graveyard with the same cmc. Unfortunately the ability does not cast the spell but fizzles:
<img width="685" alt="Halo Forager 1" src="https://github.com/magefree/mage/assets/78379079/4aeb5a39-d5c8-48ab-a77a-2a7eeceb9712">
Halo Forager entered the battlefield, the ability triggered, but not completely.

<img width="872" alt="Halo Forager 2" src="https://github.com/magefree/mage/assets/78379079/d3733423-cb96-4c1a-8a32-c4db43df7dc0">
The mana was paid (3 for the Forager, 4 for "Deadly Derision"), the stack is empty but the targeted spell "Deadly Derision" was not casted and remained in graveyard.

**Comment by NapoleonBorn2Party** [comment]
Can confirm that the same happened to me. Spell targeted was [[Fractured Identity]]. [[Halo Forager]]'s ability didn't cast the spell when resolved.
