### ISSUE TITLE
Errant Minion from Ice Age acts weird

### ISSUE THREAD

**Issue by Kjhendir** [magefree/mage#10342]
The card doesn't deal any damage if the creature's controller pays no mana but deals 1 damage if they pay 1 mana, if they pay the 2 they don't recieve any damage as normal.

**Comment by lagdotcom** [comment]
Here's the culprit:
https://github.com/magefree/mage/blob/master/Mage.Sets/src/mage/cards/e/ErrantMinion.java#LL88C32-L88C32

Looks like it doesn't even try to apply the damage effect if they pay 0 (as reported). Easy fix, though.
