### ISSUE TITLE
BUG ? // Tiana, Ship's Caretaker & Mazzy Truesword Paladin can be played as Partner-Commanders

### ISSUE THREAD

**Issue by randomsuspect** [magefree/mage#10345]
Second time i see this guy with both Commanders in a EDH Game. None have Partner or similar, so this should not be possible.

**Comment by chesse20** [comment]
are you playing freeform commander?

**Comment by randomsuspect** [comment]
No, i am not. It s the usual commander format "Commander Free for all"
