### ISSUE TITLE
Transformed incubator tokens still have a transform ability

### ISSUE THREAD

**Issue by Don-Cruz** [magefree/mage#10351]
[https://scryfall.com/card/mom/29/norns-inquisitor](url)
Norn's Inquisitor should only trigger on controller's transformations into phyrexians. In fact it triggers on transformations of all players:
<img width="704" alt="Norn Inquisitor" src="https://github.com/magefree/mage/assets/78379079/4e603323-cf68-4bc6-9c34-30d40faf4b05">
In this example the Inquisitor of my opponent ("computer 8") triggered on the transformation of my ("cruz") Incubator token, despite the card says only "permanents you control".
<img width="925" alt="Norn Inquisitor 2" src="https://github.com/magefree/mage/assets/78379079/c6e185ca-da92-4474-8c34-e8447de6f054">
You can see the "Norn's Inquisitor"-Trigger on the stack.

Another bug: 
Incubator tokens correctly have the activated ability to transform into a phyrexian 0/0 creature. But this creature still has the activated ability to transform. It can retransform into an incubator token again, this activated ability should not exist any more.

**Comment by xenohedron** [comment]
* Primary bug fixed in #10357
* Transform ability on back side probably due to this code in `TokenImpl`:
![image](https://github.com/magefree/mage/assets/12538125/2f17b99b-f75a-450d-9a80-b18d40eb7fe0)
