### ISSUE TITLE
client hang in discard state after discardTargetEffect ask player to discard more than the player able to discard

### ISSUE THREAD

**Issue by wanderer120** [magefree/mage#1035]
Happens when Mind Sludge target a player and the player has less cards than the Mind Sludge's caster's total swamp.
(currently fixing it)

**Comment by LevelX2** [comment]
It's already fixed for the next update.

http://www.slightlymagic.net/forum/viewtopic.php?f=70&t=17295&sid=15a314231ead0f6df498a0a864439b58

**Comment by wanderer120** [comment]
o..silly me..nevermind then.
