### ISSUE TITLE
Zhulodok, Void Gorger double cascade bug

### ISSUE THREAD

**Issue by catman123456** [magefree/mage#10360]
[[Zhulodok, Void Gorger]] cascade did not activate when i cast [[Scour from Existence]].

![image](https://github.com/magefree/mage/assets/64045003/7ac7ca93-0819-483c-88b9-ac4d8f55e1c8)

**Comment by xenohedron** [comment]
and of course, we have `mage.abilities.effects.GainAbilitySpellsEffect` independent from `mage.abilities.effects.common.continuous.GainAbilityControlledSpellsEffect` with similar but not identical code.

[[Abaddon the Despoiler]] uses the other one and its cascade ability works fine on the stack but isn't visible in the hand
