### ISSUE TITLE
BUG / MOM: Streetwise Negotiator's ability is a global effect

### ISSUE THREAD

**Issue by Don-Cruz** [magefree/mage#10362]
The ability of "Streetwise Negotiator" seems to be a global effect instead of an ability which only affects the creature itself:
<img width="1092" alt="Streetwise Negotiator 1" src="https://github.com/magefree/mage/assets/78379079/a395871c-1f8b-4ea9-9fff-96ba2069d197">
<img width="638" alt="Streetwise Negotiator 2" src="https://github.com/magefree/mage/assets/78379079/b0266b4f-2c33-49f5-ac65-2c37f48778b3">
In this example the player cruz attacks with two creatures including "Saiba Cryptomancer" as a 3/4 creature. Instead of 3 damage the Cryptomancer does damage euqal to his toghness which probably is due to the Negotiator's ability.

**Comment by Susucre** [comment]
[[Streetwise Negotiator]]
