### ISSUE TITLE
BUG // Mass Mutiny doesn't trigger at the endstep

### ISSUE THREAD

**Issue by randomsuspect** [magefree/mage#10384]
Mass Munity's ability doesnt trigger at the endstep. There should be a trigger that returns the creatures if i'm not mistaken. Instead, the creatures leave your control as soon as your turn ends and the next players turn begins.

**Comment by xenohedron** [comment]
[[Mass Mutiny]] has no triggered abilities. What you describe sounds like the correct behavior.
