### ISSUE TITLE
Feldon of the Third Path doesn't trigger ETB effects

### ISSUE THREAD

**Issue by Pohltron** [magefree/mage#10392]
When creating a token with his ability, the token just appears on the battlefield without triggering anything.

As per the rules for that card on the MTG site: "Any enters-the-battlefield abilities of the copied creature card will trigger when the token enters the battlefield. Any “as [this permanent] enters the battlefield” or “[this permanent] enters the battlefield with” abilities of the copied creature card will also work."

Thanks!

**Comment by xenohedron** [comment]
[[Feldon of the Third Path]]

**Comment by xenohedron** [comment]
I can't reproduce a bug here. Do you have a specific card interaction that you found not to work?

**Comment by Pohltron** [comment]
Last time I was playing with Scion of the Ur dragon with Maskwood Nexus and if I copied Feldon and targeted Archon of Cruelty in my graveyard, the token wouldn't proc any EtB triggers.

It seems if it the original Feldon on the battlefield.

Thanks for your time!
