### ISSUE TITLE
Titania, Gaea Incarnate Meld Still Triggering Back Side Abilities

### ISSUE THREAD

**Issue by JelloPiranha** [magefree/mage#10417]
The meld card Titania, Gaea Incarnate is benefitting from its back side Titania, Voice of Gaea and triggering the "gain 2 life whenever a land card is put into your graveyard" ability. I'm, like, 99% certain that meld cards are supposed to ignore whatever their original cards did, and it's possible that this is affecting other meld cards as well, but I've only tested Titania.

**Comment by Grath** [comment]
This is a known issue with meld cards, hopefully some of the work @theelk801 is doing on refactoring transforming double-faced cards might help with this?

**Comment by JelloPiranha** [comment]
Sounds good! I'm new here, so I just wanted to make sure it was a known issue.
