### ISSUE TITLE
Zoetic Cavern can be cast as morphed creature at times only instants can be cast

### ISSUE THREAD

**Issue by LevelX2** [magefree/mage#1041]
Zoetic Cavern can be cast as morphed creature at times only instants can be cast
![zoeticcaverninstant](https://cloud.githubusercontent.com/assets/2066790/8273364/621c1e72-186a-11e5-8a9a-da0b053496c4.jpg)

**Comment by drmDev** [comment]
interesting... will test

**Comment by drmDev** [comment]
Confirmed still is happening. Very odd. Checked it against other lands and looks okay, the only difference is the morph ability part. So perhaps something is wrong there?

**Comment by Plopman** [comment]
Fixed in XMage 1.4.21V1
