### ISSUE TITLE
Hoarding Broodlord ETB does not trigger

### ISSUE THREAD

**Issue by abrahamdrinkin** [magefree/mage#10410]
Title says it all. I have not tried hard casting Broodlord to see if there is a difference but every time I use Reanimate on Broodlord when it ETBs nothing happens. 

Didn’t see a thread about it so I made one

**Comment by xenohedron** [comment]
Could not reproduce as stated

**Comment by abrahamdrinkin** [comment]
I’m not at home to test my commander was K’rrik and specific series of events was to cast final parting, grab reanimate and Broodlord, put Broodlord in grave and then use reanimate. I did it several times on different days and it did not trigger for me.

**Comment by Susucre** [comment]
[[hoarding broodlord]]
