### ISSUE TITLE
Issue: Isochron Scepter bug

### ISSUE THREAD

**Issue by c0akz** [magefree/mage#10422]
Hello! Isochron Scepter gives the dialog to "exile an instant with CMC 2 or less from your hand?" for imprint, but then does not allow you to exile an instant from your hand.

Thanks!

**Comment by ghost209** [comment]
I'm unable to reproduce this and was able to imprint a couple instant 1 and 2 mana cards onto it with no issues.

Was there a specific hand you were holding, or a particular card that didn't register as a valid instant?

**Comment by c0akz** [comment]
I was trying to imprint a fire prophecy.

    On Wednesday, May 31, 2023 at 07:16:06 PM EDT, ghost209 ***@***.***> wrote:  
 
 


I'm unable to reproduce this and was able to imprint a couple instant 1 and 2 mana cards onto it with no issues.

Was there a specific hand you were holding, or a particular card that didn't register as a valid instant?

**Comment by ghost209** [comment]
![image](https://github.com/magefree/mage/assets/6320501/265d849e-d1eb-4c06-928f-d78973b595bc)
Its imprinting fine over here.

**Comment by c0akz** [comment]
Ok, don't know what was going on that one game, but thanks for checking it out!

    On Wednesday, May 31, 2023 at 09:14:25 PM EDT, ghost209 ***@***.***> wrote:  
 
 



Its imprinting fine over here.
