### ISSUE TITLE
Path of Ancestry Not Triggering on Commander

### ISSUE THREAD

**Issue by JelloPiranha** [magefree/mage#10429]
Path of Ancestry should scry 1 when casting your Commander as it shares a creature type with itself. After looking around a little, it seems like this part of a larger issue with casting things from the Command Zone: https://github.com/magefree/mage/issues/7750 Some parts of this issue seem to have been addressed, but Path of Ancestry is still not working at the very least.

**Comment by Susucre** [comment]
[[path of ancestry]]
