### ISSUE TITLE
Effects which create copies of cards and then cast those copies don't cast them from the correct zone

### ISSUE THREAD

**Issue by alexander-novo** [magefree/mage#10435]
[[Delayed Blast Fireball]]

Steps:

1) Put a delayed blast fireball in a graveyard

2) Exile it with something like [[Saruman of Many Colors]] or [[Mizzix's Mastery]], then copy the card and cast it

3) It only deals 2 damage even though it was cast from exile

![image](https://github.com/magefree/mage/assets/11657716/6840cf9a-6210-48e1-b5e7-2832ea285d83)

I'll open a PR with a unit test in a sec

**Comment by alexander-novo** [comment]
This is actually a problem with the effects of Saruman and Mizzix's Mastery not creating the copy of the card in the correct zone - and can be observed with, for instance, [[Faldorn, Dread Wolf Herald]] along with any card cast with those effects, not just Delayed Blast Fireball.

**Comment by JayDi85** [comment]
Fixed in #10436
