### ISSUE TITLE
BUG / MOM: "Corruption of Towashi" does not trigger when flipping battles

### ISSUE THREAD

**Issue by Don-Cruz** [magefree/mage#10463]
[https://scryfall.com/card/mom/53/corruption-of-towashi](url)
The enchantment "Corruption of Towashi" triggers when a transformed permanent enters the battlefield. It funtions correctly with e.g. transforming incubator tokens.
But it should also trigger when a transformed battle enters the battlefield which it does not. 

<img width="1469" alt="Towashi" src="https://github.com/magefree/mage/assets/78379079/3443d707-afe8-4b04-8fc5-e92fd2db22cf">
In this example the player cruz had attacked the battle "Invasion of Lorwyn" and successfully casted the backside of it. "Winnowing Forces" entered the battlefield but Towashi did not trigger.

**Comment by ssk97** [comment]
This is not a bug- Corruption of Towashi only works once per turn, and you already triggered it earlier in the turn by transforming the incubator token.
