### ISSUE TITLE
Lae'zel interaction with Myojin

### ISSUE THREAD

**Issue by Bdett151** [magefree/mage#10472]
While Lae'zel, Vlaakith's Champion was on the battlefield, I cast Myojin of Blooming Dawn but it only entered with one indestructible counter when it should have had two due to Lae'zel.

**Comment by JayDi85** [comment]
@xenohedron also miss `getPermanentEntering` in [[Blightbeetle]] and [[Vizier Of Remedies]]?

**Comment by xenohedron** [comment]
Ah thanks, I'll fix those as well

**Comment by JayDi85** [comment]
@xenohedron please, can you check [[Rasputin Dreamweaver]] too -- it's the only card that uses `ADD_COUNTER` event instead `ADD_COUNTERS`. Maybe a typo.
