### ISSUE TITLE
[BUG] Quintorius, Loremaster doesn't work

### ISSUE THREAD

**Issue by Notshauna** [magefree/mage#10480]
[[Quintorius, Loremaster]] can't activate his ability, to sacrifice a spirit to cast a spell he exiled.

**Comment by Susucre** [comment]
So I think I have identified the issue.
The two abilities are not sharing a shared exileZoneId. So the activated ability thinks there is no valid target card exiled with Quintorius.
I am not sure how to inject a shared notion of "the common exile zone for Quintorius abilities", between the two;
- Exiling the card is using `new ExileTargetForSourceEffect()`, which define its exile zone with `source.getSourceId()` (and a source zcc) 
- The targetting uses `input.getSource()`, with input being the activated ability, inside a `Predicate`.

I do not know if we have an elegant way to align those two `exileZoneId` to be the same? Maybe someone with more experience on the codebase has insight on that?

**Comment by xenohedron** [comment]
Yeah, this sort of misalignment between exile zone ids of different abilities has been the cause of quite a few bugs. It's worth an investigation to figure out why that is.
