### ISSUE TITLE
Windows preventing other UI pieces from being interacted with is very annoying

### ISSUE THREAD

**Issue by alexander-novo** [magefree/mage#10486]
![image](https://github.com/magefree/mage/assets/11657716/135243fc-980f-4b66-afe6-f288248005e1)

These two windows are preventing each other from being interacted with - I can't select a triggered ability, and I can't press "OK" to dismiss the dialog. I also can't type in chat or view anyone's graveyards or exile zones to check how I want to order triggers.

**Comment by xenohedron** [comment]
I've always found those popup game messages super annoying. I changed in 2e018b2 so that it writes to the gamelog instead by default. Not a true fix for the problem described here but should at least reduce the frequency.
