### ISSUE TITLE
intermittently failing test

### ISSUE THREAD

**Issue by xenohedron** [magefree/mage#10481]
`[ERROR]   ReturnToHandEffectsTest.testDemonicVigorAgain:240->CardTestPlayerAPIImpl.execute:282 Can't find ability to activate command: Cast Dryad Sophisticate`

I wrote this and I need to tighten up the logic apparently

**Comment by xenohedron** [comment]
Looks like it's just occasionally tapping the wrong lands, easy enough fix

**Comment by JayDi85** [comment]
@xenohedron it can be a popular bug with wrong mana usage by AI (if you catch a test with random fails then it's a mana problem in 99%). Unit tests uses AI to pay mana costs by default and AI uses little random (diff mana, diff activate order). You must manually setup mana for payment by `activateManaAbility` before a cast command -- it will put mana to mana pool, so AI will use it by priority.

Example: 
```
activateManaAbility(1, PhaseStep.PRECOMBAT_MAIN, playerA, "{T}: Add {G}", 4);
```

**Comment by xenohedron** [comment]
Yeah that makes sense. In this case I just made it so it's possible to pay all abilities regardless of how AI taps lands, but I'll keep this in mind for more complex tests.
