### ISSUE TITLE
Tribute to the World Tree: Double Triggers

### ISSUE THREAD

**Issue by LegionedintheDamned** [magefree/mage#10499]
In the screenshot below, I cast Primordial Hydra for X=1.  It should have just gotten 2 counters.  Instead I got 2 counters and a card.

[[Tribute to the World Tree]
![image](https://github.com/magefree/mage/assets/82664393/668ebeb9-f0f4-4d65-b0c2-4445105ead62)

**Comment by xenohedron** [comment]
See #10413
