### ISSUE TITLE
[Bug] Firkraag, Cunning Instigator not triggering

### ISSUE THREAD

**Issue by oscscull** [magefree/mage#10518]
Had a game earlier, attacking with [[Firkraag, Cunning Instigator]] on multiple turns never triggered the goad ability, and subsequently also did not trigger the draw or counter ability. Was attacking with a dragon token made by [[Goro-goro and Satoru]], and also by itself. Neither had any effect.

**Comment by xenohedron** [comment]
Looks like the trigger is missing `return true;`
