### ISSUE TITLE
One with the Multiverse infinite free cast

### ISSUE THREAD

**Issue by chamnyne** [magefree/mage#10529]
Hello,

I was playing a local game against AI to test my Alrund Commander Deck and I played One with the Multiverse.
A turn after having casting it, I noticed that I was suddenly able to cast literally everything without the software asking me to pay for any of it. I played way more than one free spell and I didn't have an omniscience on the field. I don't know if this bug is already reported, but just in case.

Linked is a copy of the game log and a screenshot of the board state.

![board state](https://github.com/magefree/mage/assets/28005572/2bff761e-b219-416b-a349-58fb1b9255cd)
[game log.txt](https://github.com/magefree/mage/files/11876726/game.log.txt)

**Comment by Susucre** [comment]
see also #10519.
