### ISSUE TITLE
Usable zone logic bugged in DiesCreatureTriggeredAbility with Zone.GRAVEYARD (Syrix, Carrier of the Flame)

### ISSUE THREAD

**Issue by xenohedron** [magefree/mage#10550]
reported 2023-04-06 on discord:

> [[Syrix, Carrier of the Flame]] abilities are not working properly. The first ability never triggers, no matter what leaves the graveyard.
> 
> The second ability is a whole new mess: 
> 
> * It does not trigger if Syrix is already in the graveyard
> * It triggers only if both him and another phoenix die at the same time (going against the rulings of the card)
> * Even if you trigger it using this glitch, Syrix is never considered to have hit the graveyard - which doesn't trigger any related abilities and still leaves him as target for spells and abilities targeting the "old Syrix" on the stack

Related PR #10057

**Comment by xenohedron** [comment]
- Tests added in 038cf01.
- The ability that triggers if a creature card left the graveyard has been fixed.
- The last ability on [[Syrix, Carrier of the Flame]] is bugged due to this:

https://github.com/magefree/mage/blob/f75b1c9f0aa8f17c6df4e2570c39739a9a2691b7/Mage/src/main/java/mage/abilities/common/DiesCreatureTriggeredAbility.java#L83-L86

The usable zone logic does not seem to be accounting for the zone of the ability being GRAVEYARD.

**Comment by xenohedron** [comment]
@JayDi85 do you know what would need to be done here?

**Comment by JayDi85** [comment]
Also make sure you work with card owner, not card controller

**Comment by xenohedron** [comment]
Not sure what you're referring to there

**Comment by JayDi85** [comment]
Graveyard related code must use card owner data, not controller. Thats code looks buggy. Possible bad use case: if someone try to use cards from opponent’s graveyard. Hmm. But its another bug, not for your use case (failed test used only single graveyard).

![IMG_9551](https://github.com/magefree/mage/assets/8344157/90b69fe6-ae36-4710-a847-fa2310f6395a)
![IMG_9550](https://github.com/magefree/mage/assets/8344157/e0864beb-b201-4403-b76b-587be7e299a3)

**Comment by xenohedron** [comment]
Player id code related to card from event didn't seem to be buggy in that use case but I fixed it in 473d899.

The question about usable zone logic is separate though.
