### ISSUE TITLE
Game automatically rollsback when Misery's Shadow exiles something

### ISSUE THREAD

**Issue by stevedavidmusic** [magefree/mage#10561]
We ran into an issue where the game automatically would rollback whenever something would be put into the graveyard from play when Misery's Shadow was in play. It did not matter which player put something into the graveyard: 

EXAMPLE LOG
10:39 PM, T6.M1: Zerris casts [Snuff Out] [825] using alternative casting costs targeting [Worldspine Wurm][5c9]
10:39 PM, T6.M1: Auto-restored to T6.M1 due game error: null

**Comment by Susucre** [comment]
Something must have gone poorly with the refractor for those effects on implementing the stone from ltr. I'll look into it.

**Comment by Susucre** [comment]
Erf, I did introduce a very stupid NullPointerException.
All 4 cards are broken in the current build: Liesa Forgotten Archangel, Lorcan Warlock Collector, Misery's Shadow and Stone of Erech.

**Comment by xenohedron** [comment]
I apologize for missing this on review.
