### ISSUE TITLE
No indicator of which creature is the Ring bearer

### ISSUE THREAD

**Issue by stevedavidmusic** [magefree/mage#10572]
Can we get a ring icon or something that indicates the Ring bearer? And / or have the ring emblem indicate which creature (with the UUID) is the Ring bearer? Currently I have to look at the tool tip and see if the creature is legendary or not. However, this doesn't work if all your creatures are legendary anyways.

**Comment by Susucre** [comment]
I think there was at some points the ringbearer abilities being added to the ringbearer's text.
An icon would indeed be great, as well as a text mention on the permanent, and maybe also a message in the game log?

**Comment by Susucre** [comment]
This is my work in progress, I'll soon make a PR for it:
![ringbearing](https://github.com/magefree/mage/assets/34709007/35c863f9-3786-4374-9225-ec5143f7c886)
![ringtempting](https://github.com/magefree/mage/assets/34709007/cb73e50e-29e5-4908-b6f1-b9eca4a3b186)

I am using the cog svg, definitively could use something that looks like a ring instead.
