### ISSUE TITLE
Opposition Agent Bugged

### ISSUE THREAD

**Issue by tav3281** [magefree/mage#10576]
Played Opposition Agent alongside Maralen of the Mornsong. Exiled one card from each of my opponent's libraries. Opposition Agent was stolen by a Gilded Drake. I then Defiled it. I no longer had access to the cards I exiled with it which goes against the text on Opposition Agent. My opponent played their own Opposition Agent and then ***played the cards I had exiled previously with my Opposition Agent***. Either I'm *really* not understanding a rules interaction or Opposition Agent is bugged.

**Comment by xenohedron** [comment]
[[Opposition Agent]]

See previous #7405.

Maybe relevant to new PR #10573

**Comment by Susucre** [comment]
Definitively relevant for #10573, adding it to my list of cards to give another look to, and produce a few unit tests for.
