### ISSUE TITLE
Any support for deck files generation by external tools?

### ISSUE THREAD

**Issue by taw** [magefree/mage#1059]
Hi,

I have a bunch of scripts [ https://github.com/taw/mtg ] to import various formats and convert them to `.cod`, and I wanted to extend support to mage's `.dck` files.

This runs into instant problem that I have lines like `4 Misty Rainforest` but mage expects lines like `4 [ZEN:220] Misty Rainforest` - otherwise the best I can do is create some text file, and manually import/save them one at a time, which is a lot of busywork.

So, the issue is that I'd like xmage to either be able to directly load `.dck` files with lines like `4 Misty Rainforest` and be able to interpret that, or to have some kind of script readable (xml, json, or whatever) external tools could use to do this mapping.

`cards.xml` generated by Cockatrice Oracle contains information which set cards are from (so I could use that to get to `4 [ZEN] Misty Rainforest`), but it doesn't contain card number, so that's not enough.

I thought about just generating a "deck" with every possible card (based on let's say `cards.xml`), import/save that in mage, and using this silly `.dck` file as reference, but I'm not sure if that would even work with unsupported cards.

Is there any way to deal with this?

**Comment by thejayvm** [comment]
I'm pretty sure you could use the text files that mage uses for the set(s) list and just select a random/latest/earliest version of the given card name and extract the set acronym and collector's number from those files.

**Comment by taw** [comment]
There are any text files? The only ones with card names I can see in mage installation is `mage-client/db/cards.h2.mv.db` and that's some binary format.

**Comment by thejayvm** [comment]
Check out Utils/mtg-cards-data.txt
I'm pretty sure this file is parsed when XMage is first run on a machine and builds the db file you mentioned.

**Comment by LevelX2** [comment]
We use Utils/mtg-cards-data.txt only during card frame generation from perl script in development environment. It's not included in the xmage download. The card data goes to the h2 database is is read later from there if needed.
However you can access the file github project.

Main topic:
But it should be easily possible to support a format like    
4 [ZEN] Misty Rainforest  

I'll have to check.

**Comment by taw** [comment]
I got this script [ https://github.com/taw/mtg/blob/master/mage_card_map_generator ] to generate something useful [ https://github.com/taw/mtg/blob/master/mage_cards.txt ]. It's fairly messy, but I should be able to move from here.

(there's also a bunch of minor typos in the files)

**Comment by taw** [comment]
Just to be sure, `Eidolon of the Great Revel`, `Master of the Feast`, and `Silence the Believers` are not currently supported? I don't see them in txt files, and it's especially suprising with `Eidolon of the Great Revel`.

**Comment by LevelX2** [comment]
You're right. There are 20 cards from  Journey into Nyx missing. I will add them soon to complete the file
.
We don't need that data once the cards are implemented, so it does not attract attention normally.
Only if we check in IDE if cards from a set are missing or such things we use that file with some Perl scripts.

**Comment by tobz** [comment]
it might be useful to consider using https://github.com/lsmoura/mtgjson as a way to go from "<qty> <card name>" to the XMage `.dck` format.  It's a little indirect, but if you use the "all sets" data, you can scan through each set to find if it contains a card, which then gives you set and card number.  Sets are ordered in the file chronologically, so you could just:

- loop through each card in your list
- for each card, loop through all sets
- loop through all cards in set
- if unadorned card is in set, keep track of set/card number
- when done looping through sets, use latest set/card number to generate XMage-compatible entry

This would be an easy well to take you "<qty> <card name>" list and go to an XMage-compatible format, albeit using only the latest version of the card.  This is a dumb approach: it obviously doesn't consider wanting to use versions of a card from a particular set, nor does it consider multiple printings within a single set (like full-art lands vs half-art lands in BFZ) but for the purpose of generating a functional deck to use in XMage.... it should work just fine.

**Comment by taw** [comment]
@tobz Yeah, I discovered mtgjson too, it's pretty useful here.
