### ISSUE TITLE
Martyr of Frost can't reveal cards with empty hand

### ISSUE THREAD

**Issue by Jipsu** [magefree/mage#10590]
[[Martyr of Frost]] apparently can't be activated when you have an empty hand, ie. xmage doesn't let you choose reveal cost of X=0. I'm unsure if the whole Martyr cycle from Coldsnap is affected or all cards that use revealing as a cost. Niche issue but a need to self-sacrifice came up.

I believe this is a bug. Comprehensive rules on Reveal make no mention of or against X=0 [https://mtg.fandom.com/wiki/Reveal](https://mtg.fandom.com/wiki/Reveal) and 107.3 on Numbers and Symbols doesn't seem to mention instances where X couldn't be 0  [https://mtg.fandom.com/wiki/Numbers_and_symbols](https://mtg.fandom.com/wiki/Numbers_and_symbols).

**Comment by Susucre** [comment]
The bug was a little deeper than that, the game would not let you pay the cost if you had no possibility to reveal a card for the effect (a blue card for Martyr of Frost).
