### ISSUE TITLE
Can't run launcher (nothing opens)

### ISSUE THREAD

**Issue by maingesteve** [magefree/mage#10602]
launched XmageLauncher-0.3.8.jar in java but nothing opens.

Waited and waited but nothing is happening?

redownloaded all items a few times and same thing continues to occur?!

any help?

**Comment by JayDi85** [comment]
Got to http://xmage.today/ , download full zip-file from it and unpack to any folder like d:\games\xmage After that double click on `run-LAUNCHER.cmd` file instead jar.

**Comment by kopeto** [comment]
Same issue here. It freezes after "DB: creating cards database (it can take few minutes)..."
This is the log I get before freezing. There is no info:

INFO  2023-07-11 22:03:00,314 Starting MAGE client version 1.4.52-V4-beta7 (build: 2023-07-07 12:15)                     =>[main] MageFrame.main 
INFO  2023-07-11 22:03:00,316 Logging level: INFO                                                                        =>[main] MageFrame.main 
INFO  2023-07-11 22:03:00,316 Default charset: UTF-8                                                                     =>[main] MageFrame.main 
INFO  2023-07-11 22:03:00,377 Custom (or bundled) Java certificate file (cacerts) file found                             =>[AWT-EventQueue-0] MageFrame.<init> 
INFO  2023-07-11 22:03:01,448 Using GUI theme: Default                                                                   =>[AWT-EventQueue-0] PreferencesDialog.getCurrentTheme 
INFO  2023-07-11 22:03:01,463 Loading database...                                                                        =>[AWT-EventQueue-0] RepositoryUtil.bootstrapLocalDb 
INFO  2023-07-11 22:03:15,597 Database stats:                                                                            =>[AWT-EventQueue-0] RepositoryUtil.bootstrapLocalDb 
INFO  2023-07-11 22:03:16,598  - sets: 481                                                                               =>[AWT-EventQueue-0] RepositoryUtil.bootstrapLocalDb 
INFO  2023-07-11 22:03:16,598  - cards: 0                                                                                =>[AWT-EventQueue-0] RepositoryUtil.bootstrapLocalDb 
INFO  2023-07-11 22:03:16,599  - tokens: 1689                                                                            =>[AWT-EventQueue-0] RepositoryUtil.bootstrapLocalDb 
INFO  2023-07-11 22:03:16,599  - emblems: 102                                                                            =>[AWT-EventQueue-0] RepositoryUtil.bootstrapLocalDb 
INFO  2023-07-11 22:03:16,600  - planes: 21                                                                              =>[AWT-EventQueue-0] RepositoryUtil.bootstrapLocalDb 
INFO  2023-07-11 22:03:16,600  - dungeons: 3                                                                             =>[AWT-EventQueue-0] RepositoryUtil.bootstrapLocalDb 
INFO  2023-07-11 22:03:18,906 DB: creating cards database (it can take few minutes)...                                   =>[AWT-EventQueue-0] MageFrame.<init>

**Comment by kopeto** [comment]
I executed the jar file using the downloaded java executable and it worked. I'm almost sure I tried it yesterday and it freezed, now it works, magic happened. 
In case you want to try, I launched the jar file with this(after cd ing to the xmage root directory):

java/jre1.8.0_201/bin/java -jar XMageLauncher-0.3.8.jar

Good luck.

**Comment by kopeto** [comment]
Forgot to tell I'm on Ubuntu 22.04.

**Comment by JayDi85** [comment]
Game db creating can be freezes on running another client (if both app instances trying to update same db then it freezes in the lock).
