### ISSUE TITLE
Firkraag, Cunning Instigator's second ability doesn't trigger

### ISSUE THREAD

**Issue by alexander-novo** [magefree/mage#10606]
![image](https://github.com/magefree/mage/assets/11657716/bf1a84ac-9fb4-44d8-b42e-9fd84c65cc13)

In this example, an elephant has been goaded. It attacks another of my opponents and deals combat damage to them, but [[Firkraag, Cunning Instigator]], still on the battlefield, doesn't trigger.

**Comment by alexander-novo** [comment]
[[Firkraag, Cunning Instigator]]

**Comment by xenohedron** [comment]
Looks like predicate doesn't work as intended.

https://github.com/magefree/mage/blob/1e1423a1013bba5804545256911485f29aef2110/Mage.Sets/src/mage/cards/f/FirkraagCunningInstigator.java#L80C1-L93C2

`.getCreaturesForcedToAttack()` has the creatures as the _keys_, not the values.

Try testing something like this instead.
```
        return game
                .getCombat()
                .getCreaturesForcedToAttack()
                .keySet()
                .stream()
                .anyMatch(input.getId()::equals);
```

**Comment by permadeath** [comment]
> Try testing something like this instead.
> 
> ```
>         return game
>                 .getCombat()
>                 .getCreaturesForcedToAttack()
>                 .keySet()
>                 .stream()
>                 .anyMatch(input.getId()::equals);
> ```

Yup, that works.  I tested it out and the second ability triggers correctly now.  Thanks!
