### ISSUE TITLE
Game exception when manifesting a split card

### ISSUE THREAD

**Issue by heloirf** [magefree/mage#10608]
Thieving Amalgam: At the beginning of each opponent’s upkeep, you manifest the top card of that player’s library.

Manifested: Dusk // Dawn

Error: 
Game exception occurred: 

java.lang.IllegalArgumentException: ERROR, **can't create permanent card from split or mdf: Dusk // Dawn**
Server version: 1.4.52-V4-beta6 (build: 2023-06-30 03:27)
Stack trace:
mage.game.permanent.PermanentCard.<init>(PermanentCard.java:53)
mage.game.ZonesHandler.maybeRemoveFromSourceZone(ZonesHandler.java:358)
mage.game.ZonesHandler.lambda$moveCards$0(ZonesHandler.java:106)
java.util.ArrayList.removeIf(ArrayList.java:1413)
mage.game.ZonesHandler.moveCards(ZonesHandler.java:106)
mage.players.PlayerImpl.moveCards(PlayerImpl.java:4555)
mage.cards.t.ThievingAmalgamManifestEffect.apply(ThievingAmalgam.java:104)
mage.abilities.AbilityImpl.resolveMode(AbilityImpl.java:199)
mage.abilities.AbilityImpl.resolve(AbilityImpl.java:183)
mage.abilities.TriggeredAbilityImpl.resolve(TriggeredAbilityImpl.java:152)
mage.game.stack.StackAbility.resolve(StackAbility.java:87)
mage.game.GameImpl.resolve(GameImpl.java:1691)
mage.game.GameImpl.playPriority(GameImpl.java:1616)
mage.game.turn.Step.priority(Step.java:65)
mage.game.turn.Phase.playStep(Phase.java:184)
mage.game.turn.Phase.play(Phase.java:89)
mage.game.turn.Turn.play(Turn.java:125)
mage.game.GameImpl.playTurn(GameImpl.java:1088)
mage.game.GameImpl.play(GameImpl.java:997)
mage.game.GameImpl.start(GameImpl.java:973)
mage.server.game.GameWorker.call(GameWorker.java:34)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)

**Comment by xenohedron** [comment]
There are quite a few engine issues with MDFCs and with face-down permanents which this might be connected to. But there really shouldn't be a reason for manifest to fail here, split cards still have a back and can be turned face down. Need to investigate to see how challenging to fix.

**Comment by xenohedron** [comment]
https://github.com/magefree/mage/blob/cbd5651f80dae2ca524c303b2c217e5fd8a0bddb/Mage/src/main/java/mage/game/permanent/PermanentCard.java#L37-L59

**Comment by JayDi85** [comment]
Fixed by 11ddfa0087519b434eb594e20285c8fdba0744d9, part of #11873
