### ISSUE TITLE
Tergrid God of fright and Scion of the Ur Dragon + Maskwood Nexus interaction

### ISSUE THREAD

**Issue by Pohltron** [magefree/mage#10607]
Hi!

I can't pick Tergrid as a valid dragon creature with Maskwood Nexus on the battlefield with Scion of the Ur-Dragon ability.

Notice on the picture every other non dragon creature are yellow and valid choices.

![image](https://github.com/magefree/mage/assets/134063676/d9249f32-cfdd-47c2-a873-bf5d1165da82)

Thanks!

**Comment by xenohedron** [comment]
Is this specific to Tergrid, or a general problem with MDFCs not gaining all creature types from Maskwood Nexus?

**Comment by Susucre** [comment]
I do agree that this looks like a bug of
[[Maskwood Nexus]] not working with dfc properly.
[[Scion of the Ur-Dragon]] just being one of the card looking for a specific subtype.
