### ISSUE TITLE
Balor is not triggering

### ISSUE THREAD

**Issue by LegionedintheDamned** [magefree/mage#10611]
As per the attached screenshot, Balor is just not triggering at all.  None of the events went off.  The player was prompted to choose, but no ability went on the stack at all.

![image](https://github.com/magefree/mage/assets/82664393/c59376a3-b78b-4152-8ca2-edf445c60de1)

**Comment by Susucre** [comment]
[[Balor]]

**Comment by PurpleCrowbar** [comment]
#11149 is likely the cause of this. Balor *does* trigger, as you wrote in the body of the issue, but players can circumvent choosing a mode.
