### ISSUE TITLE
Game Keeper Did Not Trigger on Sacrifice

### ISSUE THREAD

**Issue by LegionedintheDamned** [magefree/mage#10610]
[[Game Keeper]] was sacrificed to attacking [[Vaevictus Asmadi, the Dire]].  Vaev's ability went off, Keeper never triggered, not even on the stack.

![image](https://github.com/magefree/mage/assets/82664393/da764ddd-8ec3-456f-9f34-db416880c9ea)

**Comment by xenohedron** [comment]
There seem to be a few other reports of death triggers not working with sacrifice effects:
* #9688
* #8481
