### ISSUE TITLE
AI Programming

### ISSUE THREAD

**Issue by LegionedintheDamned** [magefree/mage#10635]
My son is taking programming right now, and I have a lot of ideas on how to make the AI function a little better.  I recall reading about having access to the AI code some time back - is there a resource someone can point me to, and how we would submit/test AI code?

**Comment by alexander-novo** [comment]
https://github.com/magefree/mage/blob/master/Mage.Server.Plugins/Mage.Player.AI.MA/src/mage/player/ai/ComputerPlayer7.java

You can add a new class based off this one (current AI)

**Comment by JayDi85** [comment]
Here is a good starting topic about AI and related materials: #10154
