### ISSUE TITLE
Add feedbacks for more permanent designation.

### ISSUE THREAD

**Issue by Susucre** [magefree/mage#10640]
Similar to #10596, there are others "designations" status on permanents that could benefit from icons/additional hint in their textbox/gamelog on change. I did not yet check what are the current feedback for those, some may already be good.

 - [x] Renowned Edit: icon is not necessary, adding hint would be sufficient. (hint added with #10644)
> 702.112b Renowned is a designation that has no rules meaning other than to act as a marker that the
renown ability and other spells and abilities can identify. Only permanents can be or become
renowned. Once a permanent becomes renowned, it stays renowned until it leaves the
battlefield. Renowned is neither an ability nor part of the permanent’s copiable values.

- ~~Monstrous~~ Edit: hint is good enough.
> ~~701.31b Monstrous is a designation that has no rules meaning other than to act as a marker that the
monstrosity action and other spells and abilities can identify. Only permanents can be or
become monstrous. Once a permanent becomes monstrous, it stays monstrous until it leaves the
battlefield. Monstrous is neither an ability nor part of the permanent’s copiable values.~~

- ~~Class Levels~~ Edit: Already in!
> ~~716.2b A level is a designation that any permanent can have. A Class retains its level even if it stops
being a Class. Levels are not a copiable characteristic.~~

 - [ ] Goaded (More of a [Goaded by] really, we could use a single icon if the creature is goaded by a player, and the text have a hint for each)
> 701.38b Goaded is a designation a permanent can have. A goaded creature attacks each combat if
able and attacks a player other than the controller of the permanent, spell, or ability that caused
it to be goaded if able. Goaded is neither an ability nor part of the permanent’s copiable values.

Edit: Goaded may deserve a common icon for all the 'must attack' effects, with full details in the hovered text. I'll give that more time to think about it.

Similar as for the Ringbearer, if other people have good svg to represent each designation (either CC or from their own design), that would be most welcome. I'll probably find something good enough for the initial implementation.

**Comment by JayDi85** [comment]
1. If you will add all that icons then add it to the left side of the card with other ability icons with default color.2. Class level icon already exists: [AFR] added card icons with class level info (#7808) · ***@***.*** ID: ***@***.***>

**Comment by Susucre** [comment]
Agreed, those are way less important to understanding the game state than the Ringbearer info, the left IconPanel is appropriate.

And thanks for the class Icons, I did not yet look at what we currently have. Will try and report with what exactly I want to improve soon.

**Comment by Susucre** [comment]
Back from testing:

Monstrous has an hint working, which is strangely duplicated, but I want to add an icon (head of some beast?):
![not monstrous](https://github.com/magefree/mage/assets/34709007/200682ee-9891-46ae-8f1c-b61f01fba3e9)
![monstrous](https://github.com/magefree/mage/assets/34709007/0cd1a508-f767-443c-9fe1-dbc1681b978f)

Renowned has no feedback (aside from the +1/+1 counter, which could have been put there from another effect), plan to add icon (a Laurel wreath maybe?), and hover text.
![not_renowned](https://github.com/magefree/mage/assets/34709007/b0f7ed5b-4ad6-4060-9cf1-2f00b21ab2ec)
![renowned](https://github.com/magefree/mage/assets/34709007/6994ea3f-ae48-464a-b2fd-ed9ecefe3cff)

Class is indeed great already (altough there is the double hint like monstrous, not sure what is wrong with hints?)
![class1](https://github.com/magefree/mage/assets/34709007/7ebf2fbd-36a9-4192-af28-4963cfb505dc)
![class2](https://github.com/magefree/mage/assets/34709007/e44da9e8-82bf-41a0-8da4-0a6b16dd1d44)
![class3](https://github.com/magefree/mage/assets/34709007/7eee412b-2a81-4168-8da6-61767ba25f5a)

Goaded has 0 feedback. Not sure of the proper icon (an exclamation mark if we group all "must attack" effect in the same icon, with the full description as hints?)
![goaded](https://github.com/magefree/mage/assets/34709007/040ffebd-3168-4f2f-868e-339f0f5cfdf9)

**Comment by xenohedron** [comment]
See #10312 about duplicated hints on permanents

**Comment by xenohedron** [comment]
I don't really think monstrous and renowned need icons as long as they have hints. The counters suffice in most situations and it's not info that needs to be shown at a glance.
Icon would certainly be useful for attacking/blocking restrictions/requirements though.
