### ISSUE TITLE
Yasharn does not stop life to be paid and creature to be sacrified, as part of a cost

### ISSUE THREAD

**Issue by Reya87** [magefree/mage#10643]
Hello. I identified two issues with the boar:

1) I had [[Yasharn, implacable earth]] on the field and my opponent had [[K'rrik, son of Yawgmoth]]. My opponent was able to pay life for phyrexians manas and pay life to cast blacks spells using K'rrik ability allowing to pay life instead of black mana. Yasharn shouldn't be allowing this.

2) Yasharn on the field, my opponent had [[Anhelo, the painter]]. My opponent was then able to sacrifice creature as part of casualty additional cost when casting spell. Yasharn should not allow this as well.

**Comment by xenohedron** [comment]
see #9650
