### ISSUE TITLE
Weathered Bodyguards not dying on lethal damage (always)

### ISSUE THREAD

**Issue by duelcastermage** [magefree/mage#10649]
Weird bug.

I had a [[!Weathered Bodyguards]] that I unmorphed during combat on my opponent's turn. I used it to block a 2/2 while taking about 10 additional damage from other creatures. My life total (correctly) stayed the same, but the Bodyguards did not die after that combat phase was over (should have taken 2 + 10 = 12 total damage).

Weirdly, while it was still in play and untapped during my opponent's next turn, I took another 5 damage in the air from a flyer. The damage redirected to the Bodyguards as before, but this time it actually died. Not sure exactly what triggered this strange behavior.

**Comment by xenohedron** [comment]
[[Weathered Bodyguards]]

**Comment by xenohedron** [comment]
Quick fix to the replacement effect in 8b6373eebf2200ce1ba8186c7a2e6ff412c54f31. In future this and other similar cards should be refactored to implement redirection with the common ability class rather than custom effects.
