### ISSUE TITLE
Activated Ability menu is showing entirely disabled abilities

### ISSUE THREAD

**Issue by Susucre** [magefree/mage#10642]
We are currently using replacement effects to disable abilities of permanents.
In a number of situation, knowing that the ability is disabled could be decided before attempting to activate the ability.
As of now, abilities are always displayed in the ability menu, and it is once the player is clicking on one that it is considered disabled, and nothing happen. See #10620 for an example.

This feels similar, yet a little different, from #8960 that is centered on spell casting.

**Comment by JayDi85** [comment]
It's not a GUI problem.

Ability's menu uses `getPlayable` data for abilities list and object's playable mark (see `getPlayableObjects` for details). `getPlayable` is shared data for unit tests, AI and GUI to find a possible playable abilities. Xmage engine has some limitation to find a real playable abilities list before real usage.

My comment from #10446 about it:

`getPlayable` code:
- related to GUI and AI only
- it's limited for some dynamic use cases and do not show a real playable objects/abilities (example: some restriction/replacement effects for attack/defend/mana usage/mana reduction -- applied after a real use only, not before);
- it's uses "if can't calc/predict then allows to activate" logic;
- it's depends on current game cycle result (e.g. on other applied effects);
- so getPlayable usage in the cards is bad workaround and must be removed;

So it's impossible to fully fix the topic's problem, it's only possible to improve some effects/logic to support playable searching code.

**Comment by JayDi85** [comment]
It's not about menu -- it really allow to activate non mana ability. So it's [[Sharkey, Tyrant of the Shire]] and [[Karakas]] bug

Game logs example:

12:15, T4.M1: Human plays Karakas [aa3]
12:16, T4.M1: Human activates: return target legendary creature to its owner's hand. from Karakas [aa3] targeting Sharkey, Tyrant of the Shire [7ca]
12:16, T4.M1: Human puts Sharkey, Tyrant of the Shire [7ca] from battlefield into their hand

**Comment by JayDi85** [comment]
Arght, wrong test

**Comment by JayDi85** [comment]
Added restriction check of ACTIVATE_ABILITY events in canActivate (393dbc4047099019d3b2868ff45b05e779e1471b). So playable works fine now.
