### ISSUE TITLE
Sacrificing The One Ring does not stop life loss

### ISSUE THREAD

**Issue by LegionedintheDamned** [magefree/mage#10659]
As per the screenshot:
1. [[The One Ring]]'s life loss ability went on stack.
2. Tapped ring to increase counters to 3, drawing 3 cards.
3. Used [[Audacious Reshapers]] to sacrifice the Ring.
4. Revealed 1 card, put it into play.
5. Ring's ability in 1 resolved, causing me to lose 3 life.  Should be 0 life, since there is no Ring, and even if it is looking back at the ring, in the graveyard it has 0 counters.

![image](https://github.com/magefree/mage/assets/82664393/c6e663d0-3b9d-46b2-9f20-a3c9e4b1f5d4)

**Comment by Grath** [comment]
608.2h If an effect requires information from the game (such as the number of creatures on the battlefield), the answer is determined only once, when the effect is applied. If the effect requires information from a specific object, including the source of the ability itself, the effect uses the current information of that object if it’s in the public zone it was expected to be in; if it’s no longer in that zone, or if the effect has moved it from a public zone to a hidden zone, the effect uses the object’s last known information.

When it was on the battlefield, it had three counters; this last-known information is used per rule 608.2h
