### ISSUE TITLE
Someone deliberately crashing the server

### ISSUE THREAD

**Issue by spjspj** [magefree/mage#10656]
It appears that someone's deliberately crashing the beta.xmage.today server (repeatedly and programmatically).  There may be non-checked strings (such as the username could be gigabytes long prior to it being set to a maximum of 14 characters) that the server is currently taking in from the client and and then crashing on.  If possible, could JayDi85 put up the server logs somewhere convenient for devs to check where and what may be causing the crashes?  Not sure what value they would be (depending on the level the logs are logging at) but definitely better than nothing :(  
I know of at least one string passed from the client to the server that should probably have a sensible length imposed on it.
For example, beta.xmage.today crashed 3 times in the last hour or so with minimal people and games started on it.

**Comment by sunrosa** [comment]
The server has indeed been crashing very often (once a day at least) recently, at very similar times, around maybe 5am UTC.
