### ISSUE TITLE
Night Soil(?) Bug

### ISSUE THREAD

**Issue by Schmitin** [magefree/mage#10654]
When an opponent has one creature in the graveyard, Night Soil is able to be activated showing that opponent as a valid target despite the card requiring two creatures in grave. There is no cancel or undo button, so the game is bricked unless you rollback.

**Comment by xenohedron** [comment]
I think `TargetCardInASingleGraveyard` needs reworked to use a TargetAdjuster

**Comment by xenohedron** [comment]
[[Night Soil]]
Only other card that uses this as a cost is [[Jotun Grunt]]

**Comment by jeffwadsworth** [comment]
https://github.com/magefree/mage/issues/8771

**Comment by JayDi85** [comment]
Looks like fixed in #8771
