### ISSUE TITLE
I can't do anything on USA server.

### ISSUE THREAD

**Issue by Fuukie** [magefree/mage#1068]
I was playing normal today in the server, so i went to play few hours later, but i can't. It appears i'm connected in server but my nickname don't show in player list, chat is blank, and i can't join or watch any game. I tried to join other server, it's all okay, that's only happening in usa server.
![bug](https://cloud.githubusercontent.com/assets/13128104/8446554/af4393f0-1f82-11e5-9d2d-6b848284d1ab.png)

**Comment by LevelX2** [comment]
Server was restarted at 08:00 CET, so it should work again since then.
