### ISSUE TITLE
Ultramarine Honor Guard squad ability does not work

### ISSUE THREAD

**Issue by Omega0zero** [magefree/mage#10695]
[[Ultramarines Honor Guard]]'s squad ability does not produce token after paying the 2 for squad cost. I can assume it wouldn't make more tokens for each extra 2 paid. There's a chance all other cards with the squad ability do not work right.

**Comment by ssk97** [comment]
There's some sort of a weird problem with Squad involving the subability list getting desynced, it'll be fixed with #10546. I haven't pinned down exactly when it does vs. does not work but the rework fixes it by just not needed to access the subability list during gameplay.
