### ISSUE TITLE
Writing a test for Battlefield Thaumaturge

### ISSUE THREAD

**Issue by Simown** [magefree/mage#1070]
Quick question. I'm trying to write a test for Battlefield Thaumaturge:

```java
public class BattlefieldThaumaturgeTest extends CardTestPlayerBase {

    @Test
    public void testSingleTargetReduction() {

        addCard(Zone.BATTLEFIELD, playerA, "Battlefield Thaumaturge");
        addCard(Zone.BATTLEFIELD, playerA, "Mountain");
        addCard(Zone.HAND, playerA, "Lightning Strike");

        addCard(Zone.BATTLEFIELD, playerB, "Battlewise Hoplite");

        // Lightning Strike - {1}{R} -  Lightning Strike deals 3 damage to target creature or player.
        // Because Battlefield Thaumaturge is on the battlefield, and the creature is targeted by the
        // Lightning Strike it will be payable with one {R}.
        castSpell(2, PhaseStep.POSTCOMBAT_MAIN, playerA, "Lightning Strike", "Battlewise Hoplite");
        setStopAt(3, PhaseStep.END_TURN);
        execute();

        // PlayerA still has the Battlefield Thaumaturge
        assertPermanentCount(playerA, "Battlefield Thaumaturge", 1);
        // The Battlewise Hoplite has been killed by the Lightning Strike
        assertPermanentCount(playerB, "Battlewise Hoplite", 0);
        assertGraveyardCount(playerB, "Battlewise Hoplite", 1);
    }
}
```
The applies method registered in BattlefieldThaumaturgeSpellsCostReductionEffect will always return false regardless of what is cast, specifically:

```java
Spell spell = (Spell) game.getStack().getStackObject(abilityToModify.getId());
```
Will return null, and the cost replacement effect will never be applied. Saying that the cost modification effect works correctly in a real game for this example. and correctly reduces the cost to {R}. Is this a limitation of the testing framework or am I missing something?

EDIT: Adding 2 mountains to the battlefield will give a passing test, the cost isn't being reduced by {1} in this case.

Thanks.

**Comment by LevelX2** [comment]
Of course there are some limitations now to the computerPlayer.getPlayable(game, true) that retrieves all playable spells for the test player. Because in this case the calculation does not know how many creatures will be targeted and reduces the cost that much.

You can often overcome the limitation by giving the player more available mana and check later how much mana was really used (e.g. check how many lands are tapped).

**Comment by Simown** [comment]
I see, thanks for the tip. I'll give the mana counting a go.
