### ISSUE TITLE
Rework Replicate ability to handle multiple instances independently

### ISSUE THREAD

**Issue by xenohedron** [magefree/mage#10702]
Found while implementing Hatchery Sliver (#10694).

> 702.56b. If a [spell](https://yawgatog.com/resources/magic-rules/#spell) has multiple instances of [replicate](https://yawgatog.com/resources/magic-rules/#replicate), each is paid separately and [triggers](https://yawgatog.com/resources/magic-rules/#trigger) based on the payments made for it, not any other instance of [replicate](https://yawgatog.com/resources/magic-rules/#replicate).

As currently implemented in XMage, this rule isn't being followed. When additional cost is paid for one instance, the other instances also notice it and produce additional copies.

I'm not sure where to start with trying to fix this, hopefully someone else has an idea.

**Comment by ssk97** [comment]
Note that this problem also applies to Kicker and Squad as well. Kicker attaches the cost of the kicker as an identifier, but that would still fail if WotC ever does something like [[Wicker Picker]] in black-border where independent kicker effects should all apply separately.

**Comment by Susucre** [comment]
I have good result on that one with just the 'am i a sub ability of the main ability' check in the trigger:

```java
for (Ability ability : card.getAbilities(game)) {
    if (!(ability instanceof ReplicateAbility) || !ability.isActivated()) {
        continue;
    }
    // Need to make sure this is the parent ability.
    if (!ability.getSubAbilities().contains(this)) {
        continue;
    }
    for (Effect effect : this.getEffects()) {
        effect.setValue("ReplicateSpell", spell);
        effect.setValue("ReplicateCount", ((ReplicateAbility) ability).getActivateCount());
    }
    return true;
}
```

**Comment by Grath** [comment]
(Wicker Picker is black bordered and non-acorn, it's just that nobody's cared enough to implement Stickers or Attractions.)

**Comment by ssk97** [comment]
> I have good result on that one with just the 'am i a sub ability of the main ability' check in the trigger:

Right now subabilities get duplicated during copying, which is bad. My solution was to just officially desync the subability list, making it so that subabilities don't get copied in a second time. However, this would invalidate this solution.

Perhaps a better solution would've been to identify subabilities during a copy and then re-copy them in so as to ensure the list stays synced?

**Comment by Susucre** [comment]
Oh right, the subability issue.
I think there is no real need to do the check this way, there just need to be a way for the ReplicateTriggeredAbility to know which ReplicateAbility to look for. This could be an unique identifier set in the ReplicateAbility constructor (and a different one for the copy constructor? not sure)

**Comment by ssk97** [comment]
Actually, maybe we should have something like that. Linked Abilities are an official thing in the MTG rules that xmage probably should directly support rather than the roundabout method of storing them via `game.getState.get/setValue()` as we do now.
