### ISSUE TITLE
Norn's Annex causes game to hang

### ISSUE THREAD

**Issue by andyfries** [magefree/mage#1071]
When my opponent attacks me while I have Norn's Annex out, they are shown three buttons: "Pay 2 life", "yes", "no". Clicking any of these buttons causes the game to hang and be permanently stuck on the declare attackers phase. Rolling back to the start of the turn also does not work in this state, it stays stuck on declare attackers.

**Comment by LevelX2** [comment]
It should only hang (no button visible) if you chose "Pay 2 life" on the first dialog.
It's not intended to show this button at this time.
You can go on with F2 to the next dialog.

Anyway the behavior is not correct and I will look into it to fix it.

**Comment by klayhamn** [comment]
It seems like this is already fixed, no?

**Comment by LevelX2** [comment]
Yes i guess it should be fixed using the current client.
