### ISSUE TITLE
Game Frozen

### ISSUE THREAD

**Issue by catman123456** [magefree/mage#10748]
After updating the game is frozen at the start

![image](https://github.com/magefree/mage/assets/64045003/9df8b566-1a3e-498f-9800-599225a0ac0e)

**Comment by catman123456** [comment]
Also quitting does nothing

![image](https://github.com/magefree/mage/assets/64045003/1c0e3bb1-a801-4c28-9e71-07a12e9ef8d5)

**Comment by JayDi85** [comment]
Is it related to AI games, cards or to any game? Look at console for logs, must show something.

**Comment by Susucre** [comment]
Here is a fix for the Dragon (and the 3 other cards that shared the same code) #10751
