### ISSUE TITLE
Investigate MageObject stored in CardView

### ISSUE THREAD

**Issue by xenohedron** [magefree/mage#10745]
As discovered during #10742 `CardView` contains a field that should not be getting sent to the client.

https://github.com/magefree/mage/blob/005f32cfff9db205e913bff59a9142302909246c/Mage.Common/src/main/java/mage/view/CardView.java#L132

This is potentially an unnecessarily large amount of data transferred that could impact performance, and also a potential leakage of information. MageObject can have other inner fields and nested objects storing lots of game state info.

Need to look into reworking this to only send sanitized xxxView data to the client.

**Comment by Susucre** [comment]
Ok my initial impression on the matter:

That originalObject is used for a only a couple reason:
1. Basic public Card/Token info, Notably power/toughness, to display differently the card if the value is not the original one. Another is Color Identity.
2. Card rating, in Collection/Deck Editor. (passed as argument of `RateCard.rateCard`)

So the basic info that are not that many could either be moved directly in fields of CardView (originalPower, etc..), or in a separate OriginalCardView (that would also accept Token to be constructed).
The Rating, I feel should only use info in CardView. But I am not knowledgeable enough on the matter to be quite sure. If not possible and real Card info is needed, it should be computed server-side (once if there is no other factor to compute it) and sent with CardView.

**Comment by xenohedron** [comment]
I haven't looked into this myself but based on what you're saying, it sounds like we should just make new fields in `CardView` to hold the relevant information.
