### ISSUE TITLE
mulligan

### ISSUE THREAD

**Issue by ChaoticJexak** [magefree/mage#10760]
thanks to the new update no one asked for, the local ai mode now gets stuck after you mulligan and wont let you plan. congratulations. fix it like yesterday please.

**Comment by xenohedron** [comment]
The following three cards are bugged in the present release and will freeze the game on start if in a deck. Will be fixed next release:

* Earthquake Dragon
* Metalwork Colossus
* Nyxborn Behemoth

Please update if the problem persists after removing these cards. Sorry for the inconvenience.

**Comment by ChaoticJexak** [comment]
great so i have to change my deckbecuase of a bug. lovely.
