### ISSUE TITLE
Control opponent [Mindslaver]

### ISSUE THREAD

**Issue by apucaratia** [magefree/mage#1077]
I can't control opponents during mindslaver, i can just see their hands but can't take actions for them.

**Comment by LevelX2** [comment]
Reports:
http://www.slightlymagic.net/forum/viewtopic.php?f=70&t=17295&p=181663&hilit=Mindslaver#p181663
http://www.slightlymagic.net/forum/viewtopic.php?f=70&t=17365&p=182603&hilit=Mindslaver#p182603
http://www.slightlymagic.net/forum/viewtopic.php?f=70&t=17186&p=180311&hilit=Mindslaver#p180311

**Comment by LevelX2** [comment]
Handled now in #1840
