### ISSUE TITLE
Tests: make VerifyTest check rarity in set files

### ISSUE THREAD

**Issue by Susucre** [magefree/mage#10780]
From the Xmage's Discord, at least Guttersnipe and Cryptic Serpent are at the wrong rarity in the cmm set.

I think we could add an automatic check for the rarities of cards in each set, as this info should be in the mtgjson data.

**Comment by xenohedron** [comment]
Yeah this would be great to have. I did fix those two card rarities manually for now.

**Comment by Susucre** [comment]
I am just finishing cleanup to add those. PR for the test incoming.
![image](https://github.com/magefree/mage/assets/34709007/fbf1fd90-9269-44d4-adaf-9e8fa0283f9d)
