### ISSUE TITLE
Last March of the Ents Bug

### ISSUE THREAD

**Issue by catman123456** [magefree/mage#10798]
I played [[Last March of the Ents]] and the game froze on me.

![image](https://github.com/magefree/mage/assets/64045003/ec790aa5-83fe-4cda-b73f-2a04e7296a2c)

**Comment by xenohedron** [comment]
I can't reproduce a freeze. The current implementation unnecessarily creates a popup window for the cards in your hand to choose from, which might be related to the problem. I can fix that.
