### ISSUE TITLE
Unable to set custom Battlefield background image

### ISSUE THREAD

**Issue by calkno** [magefree/mage#10809]
I previously had a custom battlefield background, but changed the theme  I was using and it was reset. It's been a long time since I screwed around with background images and cannot recall how to set the custom battlefield background. I've selected the a custom background which is working, but I can't seem to get it to be used on the battlefield. Apologies if I'm simply overlooking this.

![Screen Shot 2023-08-15 at 6 09 45 AM](https://github.com/magefree/mage/assets/36138660/f74f93e4-0313-4c47-8d58-0703f807c750)

**Comment by JayDi85** [comment]
It was a confusion with the input fields - the bottom one used for battlefield:
![shot_240703_050114](https://github.com/magefree/mage/assets/8344157/e84497eb-d435-429b-b045-815c8519af2d)

Middle field for app's background in non game GUI.
