### ISSUE TITLE
1.4.2v0 doesn't like my cards

### ISSUE THREAD

**Issue by Shomotion** [magefree/mage#1081]
I updated to 1.4.2v0 this morning and when I selected my modern Burn list when trying to make a game on the xmage.de server it gave me this error message (http://imgur.com/EKqRTCh) for many of my cards. I went back and changed the sets but it even said I had the wrong edition of Skullcrack, which only has one printing. I used 1.4.1v3 last night and had no problems like this. Any idea what's going on?

**Comment by LevelX2** [comment]
Can you post your dck file content here?

**Comment by Badaro** [comment]
Happening for me as well, currently it's complaining about Spreading Seas.

Deckfile: http://pastebin.com/Rzep1G1q

**Comment by Shomotion** [comment]
[my list](http://i.imgur.com/OsgatXg.png)
[the .dck file](https://onedrive.live.com/redir?resid=BA635B9CB7ECE325!71364&authkey=!AGH2gHPh0OTAC7I&ithint=file%2cdck)

**Comment by LevelX2** [comment]
Server was restarted. I guess some bugs caused memory overflow. If that happens some/all cards are no longer found, that caused your problems.
But the real cause is something else I'm looking into.
