### ISSUE TITLE
Verify test: false positive on mana abilities adding choice of multiple colors

### ISSUE THREAD

**Issue by xenohedron** [magefree/mage#10832]
Here's another example of a discrepancy that shouldn't be flagged but currently is. This one might be harder to account for, but I think it should be possible to write a regex for converting the reference ability into two abilities the way xmage handles it.

(Unless we'd want to change xmage implementation but that seems like a lot of effort without really much benefit.)

```
Wrong card 62864: Horizon Canopy
+ {1}, {T}, Sacrifice Horizon Canopy: Draw a card.
- {T}, Pay 1 life: Add {G}.
- {T}, Pay 1 life: Add {W}.

ref:
+ {1}, {T}, Sacrifice Horizon Canopy: Draw a card.
- {T}, Pay 1 life: Add {G} or {W}.
 
```

**Comment by Susucre** [comment]
We probably want to extend on that verify logic?
![image](https://github.com/magefree/mage/assets/34709007/c5e34c32-8c9d-4d05-b86a-2353ec9f7f1a)

**Comment by Susucre** [comment]
I did try using Java 8's Regex/Matcher for the double cycling from alara: https://github.com/magefree/mage/pull/11036/commits/18e7bfa48a8d2530aaa50f42a8fa89610a1b3d08

Think I'll be able to work soon on a somewhat decent regex-based splitting of activated abilited that do produce mana. Should clean some of the false verify errors.
