### ISSUE TITLE
Joraga Invocation must be reworked

### ISSUE THREAD

**Issue by LevelX2** [magefree/mage#1093]
It's a rule changing effect and has to be applied also to creatures that enter the battlefield after resolution of Jorgan Invocation.

**Comment by drmDev** [comment]
@LevelX2 do you remember what this was about and if it still is relevant?

**Comment by emerald000** [comment]
The issue was that it was only applied to creatures that were on the battlefield as it resolved. If you casted a creature afterwards, the effect would not apply. Not idea if it still occurs, but probably.

**Comment by Zerrisx** [comment]
The way the card works currently is correct; this is not a bug.
