### ISSUE TITLE
null pointer exception.....

### ISSUE THREAD

**Issue by salyG** [magefree/mage#1094]
FATAL 2015-07-07 11:29:08,839 Communication error                                                                        =>[pool-1-thread-1] SessionImpl.handleThrowable 
java.lang.NullPointerException   

Boss, what does it mean?

**Comment by Nidhoegger** [comment]
Could you provide more informations? When does it happen? Post the whole exception stack pls (if you dont know what i mean, post the whole log)

**Comment by salyG** [comment]
ok nevermind. it is working fine again. thx anyway
