### ISSUE TITLE
Reckless Imp came back to hand after being destroyed while dashing

### ISSUE THREAD

**Issue by cchron1907** [magefree/mage#1095]
I haven't done any other Dash effects yet so I'm not sure if this is just with Reckless Imp or if it has to do with the dash effect since the new update. definitely needs fixed.

**Comment by LevelX2** [comment]
It's fixed with the next update. 
On xmage.de server there will be an 1.4.2v2a1 version active (restart 2015-07-07 13:00 CET) with that fix.
On woogerworks server that version should already be active since last restart.
