### ISSUE TITLE
Refactor: regroup together the Mistmeadow Witch kind of effect

### ISSUE THREAD

**Issue by Susucre** [magefree/mage#10978]
[Scryfall Search](https://scryfall.com/search?q=o%3A%2Fexile%5B%5E.%5D*target%5B%5E.%5D*.+Return+%5B%5E.%5D*+to+the+battlefield+under+%5B%5E.%5D*+owner%E2%80%99s+control+at+the+beginning+of+the+next+end+step.%2F)

21 Cards with the [[Mistmeadow Witch]] effect, each having its own implementation.

**Comment by Susucre** [comment]
Oh and also have an option to return on the owner's next end step [[The Eternal Wanderer]]

**Comment by xenohedron** [comment]
I've been planning to do this
