### ISSUE TITLE
Doenst Work

### ISSUE THREAD

**Issue by vsdiaz86** [magefree/mage#1098]
Hi,

When i try execute xmage for the first time he doenst work, he stops in the command window when i click in "Launch client and server" or "Launch Client". The java is in lattest version, and the executable of xmage too.

**Comment by LevelX2** [comment]
1) Please post the exact error reports from the console.
2) More information needed. 
Which server did you try to conenct to?
Which OS System (windows/Linus/OSX) and OS version do you use?

**Comment by vsdiaz86** [comment]
Image error posted.
Is before the connection server
System Windows 8 ultimate

I tried in other computer and works :/

![bug xmage](https://cloud.githubusercontent.com/assets/13224819/8576797/ce7482d4-25a4-11e5-8cda-26bb9b77166e.jpg)

**Comment by LevelX2** [comment]
What is written to the xmage_launcher.log file (located in the same directory as the launcher jar file).

I guess the firewall is blocking.

**Comment by markedagain** [comment]
closing ticket since no extra details were supplied
