### ISSUE TITLE
Aura fizzling for no reason

### ISSUE THREAD

**Issue by emerald000** [magefree/mage#1100]
Round 2, game 1 of an ORI sealed tournament. I cast a Totem-Guide Hartebeest grabbing an Infernal Scarring. The following turn, I cast the aura targeting one of my creatures and it gets fizzled and go to the graveyard. The log shows I targeted a creature that was not on the battlefield somehow, and the spell most likely fizzled as a result.

[Game log](http://pastebin.com/wXj9zgvz). Fizzling happens on line 287.

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.
