### ISSUE TITLE
Unable to connect to server

### ISSUE THREAD

**Issue by TubeTVman** [magefree/mage#1101]
Since the most recent update I have had trouble connecting. This image appears after I attempt to connect. 
<img width="1280" alt="screen shot 2015-07-07 at 8 27 19 pm" src="https://cloud.githubusercontent.com/assets/13228569/8560566/237cf89c-24e7-11e5-9b63-548f27a9ae67.png">

Any help would be greatly appreciated.

**Comment by LevelX2** [comment]
You should use xmage.woogerworks.info.
Because the .com domain has currently some problems to get resolved.

Also xmage.de had some trouble last night, and was also not available from about 01:00 - 07:30 CET.
