### ISSUE TITLE
Creating an Aura token attached to a permanent should check for Protection

### ISSUE THREAD

**Issue by Susucre** [magefree/mage#11022]
When you target [[Azorius First-Wing]] with for instance [[Croaking Curse]], the spell should resolve, but the Aura token should not be created at all, as Protection does prevent enchantment of the proper quality. As of now the Role enters the battlefield attached to the Griffin, and is moved (is that a sacrifice? does not really matter) to the graveyard next SBA check.

https://yawgatog.com/resources/magic-rules/#R3034i
> 303.4i. If an [effect](https://yawgatog.com/resources/magic-rules/#effect) attempts to put an [Aura](https://yawgatog.com/resources/magic-rules/#aura) onto the [battlefield](https://yawgatog.com/resources/magic-rules/#battlefield) attached to an [object](https://yawgatog.com/resources/magic-rules/#object) or [player](https://yawgatog.com/resources/magic-rules/#player) it can't legally [enchant](https://yawgatog.com/resources/magic-rules/#enchant), the [Aura](https://yawgatog.com/resources/magic-rules/#aura) remains in its current [zone](https://yawgatog.com/resources/magic-rules/#zone), [unless](https://yawgatog.com/resources/magic-rules/#unless) that [zone](https://yawgatog.com/resources/magic-rules/#zone) is the [stack](https://yawgatog.com/resources/magic-rules/#stack). In that case, the [Aura](https://yawgatog.com/resources/magic-rules/#aura) is put into its [owner](https://yawgatog.com/resources/magic-rules/#owner)'s [graveyard](https://yawgatog.com/resources/magic-rules/#graveyard) [instead](https://yawgatog.com/resources/magic-rules/#instead) of entering the [battlefield](https://yawgatog.com/resources/magic-rules/#battlefield). If the [Aura](https://yawgatog.com/resources/magic-rules/#aura) is a [token](https://yawgatog.com/resources/magic-rules/#token), it isn't created.

**Comment by xenohedron** [comment]
`PermanentImpl::cantBeAttachedBy` should have logic to check this

**Comment by Susucre** [comment]
So what is not done yet in the two branches for Curse of the Werefox and Yenna:
- protection from a player is not quite right to check a Token neither Permanent nor Card. See the Curse of the Werefox work on the protection from card. Should be rather straightforward
- the token creation (in TokenImpl) of an aura is retrieving the Target for the aura, but do not add anything relative to cantBeAttachedBy. So the player can choose a permanent/player protected from the aura qualities.

**Comment by xenohedron** [comment]
Did this get resolved?

**Comment by Susucre** [comment]
don't think so
