### ISSUE TITLE
Tree of Redemption Underflow Error

### ISSUE THREAD

**Issue by JelloPiranha** [magefree/mage#11023]
![image](https://github.com/magefree/mage/assets/134155990/dffce19a-d5fe-453a-bf5a-a4229de8b028)

At least I assume that's what's happening. The toughness and life total values switch correctly, but afterwards, there's suddenly a huge negative value for Tree of Redemption's power.

**Comment by Susucre** [comment]
Well that is not technically an Underflow Error.

Just an interesting choice of power value:
![image](https://github.com/magefree/mage/assets/34709007/819e58f7-a31b-4abb-a6a3-2f586414058a)
