### ISSUE TITLE
Screen Glitching

### ISSUE THREAD

**Issue by DargonMayor** [magefree/mage#11026]
![Screenshot 2023-08-25 191016](https://github.com/magefree/mage/assets/143230656/f1b584f4-d76d-432b-abd4-6331e0e206e5)

Screen keeps flickering with this and many other images from the game, getting in the way of seeing things on the table. I don't know if it's just this game, but it's my first game and already ran into it.
 
        Please fix, Thank you

**Comment by Susucre** [comment]
@JayDi85 just reproduced this I think.
![image](https://github.com/magefree/mage/assets/34709007/6d55c6d7-46d9-4a74-ad01-b969d12f3260)

Here is the client error:
![image](https://github.com/magefree/mage/assets/34709007/e8ee62f3-ca9e-47ff-bf6a-db3d9b9ab4f0)

I'll investigate. I did apparently miss something with removing the MageObject originalCard.

**Comment by Susucre** [comment]
@DargonMayor If that happens again (or does that happen always?), there might be an error log in the console, so please report back if you have any. Can help pinpoint the issue, those are hard to fix without being able to reproduce.

**Comment by JayDi85** [comment]
GUI drawing problems related to:
1. Client errors, including outdated versions. For client errors look at logs. For wrong client/server versions look at windows title (it's not your use case -- both versions are same);
2. Graphic card driver issue, can be fixed by additional launcher params: https://github.com/magefree/mage/issues/4626#issuecomment-374640070

**Comment by DargonMayor** [comment]
@Susucre It seems to happen every game, I just don't much know how to fix it tbh. If there is any advice I'd love to hear it, from you or anyone else on here. But I'm not amazing with computers, so i may not understand too much complicated stuff lol.

**Comment by Susucre** [comment]
You can first look at what JayDi said above, might be configuration issue for your computer.
