### ISSUE TITLE
Oppressive rays seems to break the AI

### ISSUE THREAD

**Issue by Greeneye0** [magefree/mage#1102]
When the AI has a creature it wants to attack with and that creature has oppressive rays on it but not enough mana then the computer will sit there forever and not move:
![image](https://cloud.githubusercontent.com/assets/11687236/8580674/24eabe7a-2579-11e5-9285-9afcb8441053.png)

**Comment by fireshoes** [comment]
Probably not related, but I noticed this the other day with Liliana, Defiant Necromancer.

**Comment by thejayvm** [comment]
I noticed this with Ghostly Prison out as well. I don't think it was consistently happening... but it does seem pretty easy to get the AI into too complex of a decision tree state in certain match ups.

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.
