### ISSUE TITLE
Game Exception Occured

### ISSUE THREAD

**Issue by JasonInouye** [magefree/mage#11080]
Game exception occurred: 

java.lang.IllegalArgumentException: Wrong code usage. Choices must contains some values
Server version: 1.4.52-V5-beta4 (build: 2023-08-25 15:34)
Stack trace:
mage.player.human.HumanPlayer.choose(HumanPlayer.java:474)
mage.abilities.effects.common.ChooseACardNameEffect$TypeOfName.getChoice(ChooseACardNameEffect.java:65)
mage.abilities.effects.common.ChooseACardNameEffect$TypeOfName.getChoice(ChooseACardNameEffect.java:54)
mage.abilities.effects.common.ChooseACardNameEffect.apply(ChooseACardNameEffect.java:131)
mage.abilities.AbilityImpl.resolveMode(AbilityImpl.java:199)
mage.abilities.AbilityImpl.resolve(AbilityImpl.java:186)
mage.game.stack.Spell.resolve(Spell.java:281)
mage.game.GameImpl.resolve(GameImpl.java:1698)
mage.game.GameImpl.playPriority(GameImpl.java:1623)
mage.game.turn.Step.priority(Step.java:66)
mage.game.turn.Phase.playStep(Phase.java:204)
mage.game.turn.Phase.play(Phase.java:90)
mage.game.turn.Turn.play(Turn.java:137)
mage.game.GameImpl.playTurn(GameImpl.java:1095)
mage.game.GameImpl.play(GameImpl.java:1002)
mage.game.GameImpl.start(GameImpl.java:978)
mage.server.game.GameWorker.call(GameWorker.java:34)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)

**Comment by Susucre** [comment]
Hello, thanks for the report. What was the card that triggered the error?

**Comment by JayDi85** [comment]
Not actual without problem card
