### ISSUE TITLE
[WOE] Hamlet Glutton and similar cards can't be cast for bargain without the full mana

### ISSUE THREAD

**Issue by Susucre** [magefree/mage#11087]
[[Hamlet Glutton]] [[Johann's Stopgap]] and [[Ice Out]] are not letting players cast them when they could be paid with Bargain (and cost reduction), but not with the full cost.

For instance here is a situation where I should be able to play the bargained glutton:
![image](https://github.com/magefree/mage/assets/34709007/d371db16-2459-480f-a68f-a8dee6892f66)

You can bargain once you got 7 mana.

**Comment by xenohedron** [comment]
I'm guessing the cost adjuster needs to check `game.inCheckPlayableState() || BargainedCondition.instance.apply(game, ability)`
