### ISSUE TITLE
The pick trigger abillity window is invisible.

### ISSUE THREAD

**Issue by juggalotic** [magefree/mage#11086]
![Screenshot (10)](https://github.com/magefree/mage/assets/121203446/5a4876b9-6de1-49e9-abd0-b14595effa11)

**Comment by Susucre** [comment]
#11052

**Comment by SoulTheif001** [comment]
I have the same problem across multiple decks with several different card triggers.

**Comment by xenohedron** [comment]
Closing as duplicate
