### ISSUE TITLE
For Cube Draft type "Cube From Deck", art is not always the same as in the listed Deck

### ISSUE THREAD

**Issue by Zerrisx** [magefree/mage#11090]
If you set up a tournament like so: 

![image](https://github.com/magefree/mage/assets/59861365/a56cfe05-05e8-4db7-9a32-8f35231cf089)

It will correctly grab all the _cards_ from the .dck file, but the art is not always the specified art for each card in said .dck file.  This results in cube drafts that are not as aesthetically pleasing or controlled as one might like for a highly curated format, and is particularly annoying when it picks alternate-language art, i.e. Japanese planeswalkers.

Update: It looks like this might happen with arts in the same set, where it picks the same art every time, rather than the matching one.

Example: a deck with 384 matching copies of this art (CMM 5):
![image](https://github.com/magefree/mage/assets/59861365/bad7dd43-02ce-40a4-956e-dfe458fa5988)

Results in this cube draft (CMM 1059):
![image](https://github.com/magefree/mage/assets/59861365/249e3f0b-6d64-45d6-baba-5c4dd26c3719)

**Comment by Susucre** [comment]
Of note, the bug is probably limited to cards that have multiple arts in the same set.

**Comment by Zerrisx** [comment]
For another example, Gideon Blackblade (WAR 13) is always replaced by Gideon Blackblade (WAR13*)

Draft Deck:
![image](https://github.com/magefree/mage/assets/59861365/612aa325-e500-4a61-aa56-500d3f86ab3a)

Resulting Cube:
![image](https://github.com/magefree/mage/assets/59861365/d07bdfcc-1b82-40c3-ab22-eab6f356eac9)

**Comment by Susucre** [comment]
Fixed version of Cube From Deck:
![image](https://github.com/magefree/mage/assets/34709007/969f6e1d-4f3c-4d7f-a9e3-1ed38b1e129d)
