### ISSUE TITLE
"Do this only once each turn" issue

### ISSUE THREAD

**Issue by PurpleCrowbar** [magefree/mage#11106]
An ability with "Do this only once each turn" is an optional ability which can trigger until the player chooses to "use" the ability, at which point the ability can no longer trigger and any other instances of the ability on the stack fizzle when they resolve.

I've found an issue concerning [[Ondu Spiritdancer]] which triggers when an enchantment enters the battlefield. The ability creates a copy of the enchantment (should the player choose to). The issue is that this copied permanent triggers the ability of the Spiritdancer, even though the ability has already been "used". 

The ability on the stack predictably fizzles but it shouldn't trigger at all. My understanding is that the gamestate value which is used to determine whether or not the ability has been used that turn is only updated at the *end* of the ability's resolution. This means that the effect of Spiritdancer's ability is finishing and queueing another trigger before the game knows the ability has already been used for the turn. See L164 below in TriggeredAbilityImpl, where the gamestate is only updated after the ability's effects have been handled (see L161).

https://github.com/magefree/mage/blob/c36e5c4a1c837a8fb25f0b566b95f8d06803988d/Mage/src/main/java/mage/abilities/TriggeredAbilityImpl.java#L143-L170

If the gamestate is updated before `!super.resolve(game)` is called, the bug is resolved. However, I fear this may open the door to future issues (e.g., an ability failing to resolve, but still being marked as having been used for the turn). I tested with [[Riveteers Ascendancy]] and making the target of its trigger illegal (i.e., by exiling the target in my graveyard), however it did not break anything. As it stands, this fixes the issue and does not *appear* to create any problems with other existing cards, however I would be happy to hear some thoughts on this.

**Comment by xenohedron** [comment]
> If the gamestate is updated before `!super.resolve(game)` is called, the bug is resolved. However, I fear this may open the door to future issues (e.g., an ability failing to resolve, but still being marked as having been used for the turn). I tested with [[Riveteers Ascendancy]] and making the target of its trigger illegal (i.e., by exiling the target in my graveyard), however it did not break anything.

As I understand it, even if `super.resolve(game)` returns false, the triggered ability should still be marked as having been used for the turn, so what you've done in #11107 would be correct.

**Comment by xenohedron** [comment]
[potentially affected cards for reference](https://scryfall.com/search?q=o%3A%22do%20this%20only%20once%20each%20turn%22)

**Comment by JayDi85** [comment]
Hmm. Optional and "do this only once each turn" must use different mechanics and times. Is it good with updated code?

1. Optional triggers must goes to stack all the times due 603.2 and 603.5 rules:

> 603.2. Whenever a game event or game state matches a triggered ability’s trigger event, that ability
automatically triggers. The ability doesn’t do anything at this point.

> 603.5. Some triggered abilities’ effects are optional (they contain “may,” as in “At the beginning of
your upkeep, you may draw a card”). These **abilities go on the stack when they trigger, regardless of
whether their controller intends to exercise the ability’s option or not**. The choice is made when the
ability resolves. Likewise, triggered abilities that have an effect “unless” something is true or a
player chooses to do something will go on the stack normally; the “unless” part of the ability is
dealt with when the ability resolves.

2. "Do this only once each turn" must be checked before triggers and must prevents it from goes to a the stack due 603.2i rules:

> 603.2i A triggered ability may have an instruction followed by “Do this only once each turn.” This
ability triggers only if its source’s controller has not yet taken the indicated action that turn.

**Comment by PurpleCrowbar** [comment]
Yes that functionality remains with the updated code and I wrote a test for it (`testAbilityCantTriggerSameTurn`) in that PR
