### ISSUE TITLE
Tournament points calculation wrong

### ISSUE THREAD

**Issue by LevelX2** [magefree/mage#1113]
Player A won first match of first round of tournament.
Player A conceded at the start of game two from the tournament,
Player A was eliminated with 3 points.
Player B the opponent got 0 points from first round.
![tournamentwrongpoints](https://cloud.githubusercontent.com/assets/2066790/8638899/6016ff60-28c9-11e5-9e20-ac22663dbbb8.jpg)

**Comment by LevelX2** [comment]
The wrong calculation is corrected some time later (probably with the next update).
![wrongcaclculation](https://cloud.githubusercontent.com/assets/2066790/8639032/7c150474-28cd-11e5-9b26-ac9bd35adfb6.jpg)

**Comment by Zerrisx** [comment]
I think this has been fixed; I'm no longer seeing it.
