### ISSUE TITLE
Eriette of the Charmed Apple roll back bug

### ISSUE THREAD

**Issue by catman123456** [magefree/mage#11148]
When the CPU got drained a Null error happen

![image](https://github.com/magefree/mage/assets/64045003/c2905cfd-d078-4b36-a962-c2bb1903d985)

Game exception occurred: 

java.lang.NullPointerException
Server version: 1.4.52-V5-beta6 (build: 2023-09-07 05:11)
Stack trace:
mage.abilities.condition.common.AttachedToMatchesFilterCondition.apply(AttachedToMatchesFilterCondition.java:32)
mage.abilities.decorator.ConditionalRestrictionEffect.applies(ConditionalRestrictionEffect.java:80)
mage.abilities.effects.ContinuousEffects.getApplicableRestrictionEffects(ContinuousEffects.java:277)
mage.game.permanent.PermanentImpl.canUseActivatedAbilities(PermanentImpl.java:1517)
mage.players.PlayerImpl.getManaAvailable(PlayerImpl.java:3274)
mage.players.PlayerImpl.getPlayable(PlayerImpl.java:3929)
mage.players.PlayerImpl.getPlayableObjects(PlayerImpl.java:4119)
mage.server.game.GameSessionPlayer.prepareGameView(GameSessionPlayer.java:216)
mage.server.game.GameSessionPlayer.getGameView(GameSessionPlayer.java:200)
mage.server.game.GameSessionPlayer.lambda$select$2(GameSessionPlayer.java:67)
java.util.Optional.ifPresent(Optional.java:159)
mage.server.game.GameSessionPlayer.select(GameSessionPlayer.java:67)
mage.server.game.GameController.lambda$select$20(GameController.java:862)
mage.server.game.GameController.perform(GameController.java:1001)
mage.server.game.GameController.perform(GameController.java:994)
mage.server.game.GameController.select(GameController.java:862)
mage.server.game.GameController.lambda$init$3aa0d15c$2(GameController.java:199)
mage.game.events.EventDispatcher.fireEvent(EventDispatcher.java:28)
mage.game.events.PlayerQueryEventSource.select(PlayerQueryEventSource.java:41)
mage.game.GameImpl.firePriorityEvent(GameImpl.java:2803)
mage.player.human.HumanPlayer.priority(HumanPlayer.java:1181)
mage.game.GameImpl.playPriority(GameImpl.java:1602)
mage.game.turn.Step.priority(Step.java:66)
mage.game.turn.Phase.playStep(Phase.java:204)
mage.game.turn.Phase.play(Phase.java:90)
mage.game.turn.Turn.play(Turn.java:137)
mage.game.GameImpl.playTurn(GameImpl.java:1095)
mage.game.GameImpl.play(GameImpl.java:1002)
mage.game.GameImpl.start(GameImpl.java:978)
mage.server.game.GameWorker.call(GameWorker.java:34)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)

[[Eriette of the Charmed Apple]]

**Comment by xenohedron** [comment]
I don't see that this has anything to do with Eriette. Looks like `AttachedToMatchesFilterCondition` could use better null checking; I'll work on cleaning up that and similar condition classes, probably should add some unit tests as well.

**Comment by xenohedron** [comment]
fixed by 595b0e00
