### ISSUE TITLE
No Triggered Ability to select: Chronozoa

### ISSUE THREAD

**Issue by LegionedintheDamned** [magefree/mage#11156]
As per screenshot:
![image](https://github.com/magefree/mage/assets/82664393/ef3dc47b-7b02-42b7-8aef-52ff1ed5f559)

**Comment by LegionedintheDamned** [comment]
Was able to view by clicking different skips - to your turn (F9) made it show up.

**Comment by JayDi85** [comment]
Fixed by #11189
