### ISSUE TITLE
Assigning stack order not appearing across multiple games with different decks.

### ISSUE THREAD

**Issue by SoulTheif001** [magefree/mage#11171]
When playing against my opponent multiple triggers happen at once and I usually select how I want the triggers to go on the stack. On multiple occasions the optoin to select the stack order doesn't appear and I can only interact with the cards in my hand. The game ends by running out of time or people leave because they think I'm intentionally stalling the game

**Comment by Susucre** [comment]
#11052

**Comment by xenohedron** [comment]
Closing as duplicate
