### ISSUE TITLE
Brenard, Ginger Sculptor food typed bug

### ISSUE THREAD

**Issue by catman123456** [magefree/mage#11176]
The tokens made with [[Brenard, Ginger Sculptor]] are not created with food type.

![image](https://github.com/magefree/mage/assets/64045003/e3caec3d-6a3f-4616-a450-c844e3790311)

**Comment by xenohedron** [comment]
It's a problem with `CreateTokenCopyTargetEffect` only supporting one additional subtype... need to refactor that a little
