### ISSUE TITLE
Firkraag sometimes does not trigger

### ISSUE THREAD

**Issue by Susucre** [magefree/mage#11199]
Reported on Discord by user Cotton:
> Cotton: just had a bug come up, [[firkraag]] goaded my [[consecrated sphinx]], i dealt combat dmg with it to an opponent and the owner of firkraag did not get to draw a card, this is the boardstate

![image](https://github.com/magefree/mage/assets/34709007/a03f75c4-d74b-4a64-acf7-8d89d8b5d406)

**Comment by Susucre** [comment]
[[Firkraag]] [[Consecrated Sphinx]]

**Comment by Susucre** [comment]
Reading the situation again, don't think the Sphinx is related to the issue.

**Comment by JayDi85** [comment]
Logs don't have goad, so no trigger:

![shot_230925_024255](https://github.com/magefree/mage/assets/8344157/f35a02ee-ae83-46d2-a91e-38ec8cbcd287)
