### ISSUE TITLE
Game freezing upon combat damage

### ISSUE THREAD

**Issue by HeroVorpal** [magefree/mage#11202]
Hello,

Starting last night, every game I played with my friends would immediately crash for everyone as soon as anyone received combat damage. I got off and they tried again later with no issues. A friend and I tried again this morning and it appears its an issue with my computer. It was different creatures each time, and it didn't matter who attacked or took damage. The game would immediately freeze and sometimes restart but more often just crash. I've updated windows, and redownloaded both Xmage and Java with no success. Any help would be greatly appreciated.

**Comment by xenohedron** [comment]
It is likely a regression on a card in the deck you are using. Could you please share your decklist?

**Comment by JayDi85** [comment]
I can see only two error types in server's logs:
* [[Aurelia's Fury]] -- just wait next update;
* `chooseTriggeredAbility` and "Whenever {this} deals combat damage to a player, you may draw a card" (or another multiple triggers) --  as workaround: right click on battlefield and select menu to reset all trigger answers, don't use remember answer until next update.

**Comment by HeroVorpal** [comment]
Huh, I was running a deck with Aurelia's Fury each time. Weird. Thanks!
