### ISSUE TITLE
Guff Rewrites History reported bugged

### ISSUE THREAD

**Issue by Susucre** [magefree/mage#11206]
Reported on Discord by user Sunny:

> i use [[grima, saruman's footman]] and snag [[guff rewrites history]] but after combat in 2nd main, i cannot cast the nonland spell it exiled

After pointing out that those effects do not allow to cast cards after they resolved, I got the following response:

> I mean I couldn't cast them when they were on the stack either
Grima always pops up with the yes/no "do you wanna cast X?" In the dialogue box, but guff didn't do that

Might be some confusing choices to chain cast cards.

[[grima, saruman's footman]] [[guff Rewrites History]]

**Comment by xenohedron** [comment]
There is a bug in the code:

https://github.com/magefree/mage/blob/1e482ece12a6fab0063e964bf33b948ce12cc873/Mage.Sets/src/mage/cards/g/GuffRewritesHistory.java#L164

`nonland` is a `Card` but `cards` is a `Collection<UUID>`, I think the intent here is to check if `.contains(nonland.getId())`

this may or may not be related

**Comment by xenohedron** [comment]
I'll assume this is fixed by the related commit, can be reopened if reported in future
