### ISSUE TITLE
Terraformer's ability reported non functional

### ISSUE THREAD

**Issue by Susucre** [magefree/mage#11204]
I have not experienced it first hand, but [[Terraformer]]'s activated ability has been reported not working during an xdhs event.

**Comment by xenohedron** [comment]
Second report today that the ability does nothing

**Comment by Susucre** [comment]
The card code is quite long and I fail to see why. Probably could be rewritten from scratch.

**Comment by Susucre** [comment]
[[Elsewhere Flask]]
