### ISSUE TITLE
Intellect Devourer reported bugged

### ISSUE THREAD

**Issue by Susucre** [magefree/mage#11205]
From user Sunny in Discord:
> [[intellect devourer]] exiles a creature that i have enough mana to play and unless im mistake creatures are still spells, yeah? and the color of mana shouldnt matter, but i cannot cast it immediately.

[[Intellect Devourer]]

**Comment by PurpleCrowbar** [comment]
Issue appears to be that although the player can spend mana as though it were mana of any colour to cast the exiled spells, the game only considers the cards castable if the player's mana sources could produce colours to pay for the original cost of the spell.

**Comment by JayDi85** [comment]
Cause `IntellectDevourerManaEffect` must check both current (exile) and +1 (stack) zcc states:

![shot_230925_211303](https://github.com/magefree/mage/assets/8344157/48e5b8be-8bca-4cba-a83d-d1b24d422e53)

**Comment by PurpleCrowbar** [comment]
@JayDi85 I ended up fixing the card (and massively reducing the volume of code) a different way, but when originally implementing Intellect Devourer I used the (broken) code of [[Rogue Class]] as a reference. Your insight above may be better suited to #10905 as it could be the solution to that issue

**Comment by jeffwadsworth** [comment]
This card does not work now, same issue.  The exiled card cannot be cast, but it does get highlighted.

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/53b791d6-0666-450b-a50a-06962aa3c105" />

**Comment by jeffwadsworth** [comment]
I should have specified that [[Duress]] is the card in exile that can't be cast.  As JayDi no doubt noticed, a targeting issue apparently.
