### ISSUE TITLE
Golgothian Sylex & Apocalypse Chime don't work on reprinted cards

### ISSUE THREAD

**Issue by sprangg** [magefree/mage#11211]
[[[Golgothian Sylex]]](https://github.com/magefree/mage/blob/master/Mage.Sets/src/mage/cards/g/GolgothianSylex.java) doesn't work on reprinted Antiquities cards. Looking at its code, it seems to only check whether the card is from Antiquities itself.

Same for Apocalypse Chime.

**Comment by xenohedron** [comment]
City in a Bottle works by hardcoding possible names. Might need to do the same for this and Apocalypse Chime.
