### ISSUE TITLE
Cannot stay connected on xmage for more than a few seconds for the last 28 hours.

### ISSUE THREAD

**Issue by tiera3** [magefree/mage#11231]
I am using mobile internet in Australia and usually have a ping around 300-330 to the private server I play xmage games on.
I have been able to play in the past, but for the last 28 hours this has been impossible.

For the most part, I will disconnect within less than a second - at best managing to type two characters into the chat box before disconnecting again.
I did manage to stay connected for about eight minutes watching one game yesterday. (When I thought I had finally managed a stable connection, I thought watching for 10 minutes would be a good test, but it disconnected after about eight.)

Today, over the course of an hours worth of attempts, I managed to start two games. The first one, I disconnected on turn three. The second one during the initial hand/mulligan phase.

---------------
I have been told that there was a recent networking change in order to ensure triggers were handled in the correct order.
Could this be the source of my difficulty?

--------------
Someone suggested I should check whether I could stay connected to beta. I just ran a test - managed to watch a match for ten minutes. Was about to respond that I had a stable ten minutes watching, when it disconnected. This time it only took three attempts to reconnect.

**Comment by tiera3** [comment]
Also, yesterday, when I couldn't stay connected and thus had to pull out of the tournament, the person that replaced me also had issues and disconnected during the draft portion - forcing the other players to continue with a bot. That person had previously told me that he was based in France.

**Comment by JayDi85** [comment]
It's your proxy or connection -- it must keep alive it to play on xmage, but it doesn't. Some services/apps can disable connection by timeout or sleep. Also check mobile power optimization settings.

**Comment by JayDi85** [comment]
Follow that instructions for hot spot settings on Android devices:
https://www.quora.com/How-do-I-keep-a-mobile-hotspot-always-on-an-Android-phone

**Comment by tiera3** [comment]
It stays always on. I use the same hotspot to play MTGA, play xmage successfully in the past, and also to use Putty to connect to my work machine.

Putty is a good indicator because it is susceptible to minor disruptions. (If I let the laptop go to sleep, that will terminate a Putty connection.)

**Comment by tiera3** [comment]
I also have a second phone connected to the first one via wifi - that keeps the connection open always and it doesntt shutdown when the laptop goes to sleep.

Also - all the while, whilst xmage was constantly disconnecting, I was chatting on Discord with the other people involved in the tournament. - And discord didn't have any connection problems.

**Comment by tiera3** [comment]
Most of the disconnects gave normal errors, but once I received the following error:

Remote task error: Socket timed out. Waited 1800000 milliseconds for res
                                                                 InvokerLocator
[bisocket://privateservername:17171/?onewayThreadPool=mage.remote.CustomThread
                                           nested exception is: java.net.SocketTimeoutException: Read

with a big okay button underneath. It was obvious that the right half of the message wasn't shown because it overflowed the dialog box.

**Comment by JayDi85** [comment]
Are you using any proxy or vpn?

**Comment by tiera3** [comment]
No

**Comment by tiera3** [comment]
I am sure this is not relevant, but I was assigned an IP via ZeroTier in my work server last week. I thought it was only relevant inside the work network and didn't apply otherwise, but I could be wrong.

**Comment by tiera3** [comment]
Opens up ZeroTier and looks. It includes something called Unchecky. That appears something that could interfere, but I dont think it is.

**Comment by tiera3** [comment]
After writing the above message (no nearly twenty minutes ago) I connected to the xmage server to try and get more information about the problem, and haven't gotten any disconnects in that time. I am just sitting in the lobby. There are two events being drafted at the moment, so once one starts playing, I will start watching one.

Took me awhile writing this message - game has started and I am watching with no disconnects. Ping 307.

**Comment by JayDi85** [comment]
ZeroTier uses own virtual networks and servers, so it can be the reason.

Here is a possible problem: https://github.com/zerotier/ZeroTierOne/issues/860 (Windows SSDP/UPnP packets can disconnects ZeroTier node/client machines every hour -- you can apply a fixes from it: [one](https://github.com/zerotier/ZeroTierOne/issues/860#issuecomment-427466588), [two](https://github.com/zerotier/ZeroTierOne/issues/860#issuecomment-433739006)).

And another problem example (someone fix it with UPnP disable too): https://discuss.zerotier.com/t/unstable-connection/453/24

So I recommends to check and test ZeroTier -- it's can be a reason for all current problems.

**Comment by tiera3** [comment]
Since I only need ZeroTier for work, I don't need it running at home.
I clicked ZeroTier and Suspend Service.
Should that be enough? Or do I need to try and understand the links you sent?

**Comment by JayDi85** [comment]
> Should that be enough?

yes, its enough to disable it

**Comment by tiera3** [comment]
Just ran a test game - and whilst there were disconnects, they were attached to bad pings (and my son was streaming video at the same time). Didn't have any disconnects with normal pings, so I think this issue is resolved.
