### ISSUE TITLE
Cannot connect to localhost until I've connected to another server

### ISSUE THREAD

**Issue by Zerrisx** [magefree/mage#11233]
If I launch the XMage beta launch and immediately try to connect to [Local, AI],  Server name: localhost, it throws this error:

![image](https://github.com/magefree/mage/assets/59861365/7b42b977-c23e-4da4-878c-942234bdc15d)

However, if I connect to any other server (Beta, or even a private server), then disconnect and connect to localhost, I get no error.

I need to follow this process again every time I close and reopen the launcher to get around the error.

**Comment by ssk97** [comment]
The server can take a minute or two to start up, have you tried just waiting a while before trying to connect?

**Comment by Zerrisx** [comment]
...I am not the brightest human.

**Comment by JayDi85** [comment]
Nope, there is really exist connection bug with same steps to reproduce (fast connect to non started/bad server can freeze a port uses and you must start client to fix port error).
