### ISSUE TITLE
Your incompetence knows NO bounds, fix the server stability. 

### ISSUE THREAD

**Issue by Navyguy330** [magefree/mage#11252]
For years the servers crash and clients crash at over a dozen times a day, just check the current really only server online the beta. literally joined and saw it crash in 20 seconds, has already crashed 7 or 8 times today and it's barely early afternoon. 

I played a few years ago, well before xmage.de went down, and since then it's the same garbage.  Your last close of this was that you had no plans, but you add garbage cards how about slow that down and make the app actually usable. 

Came back after a few years and seeing the same hot garbage, but then having a donate button. Fix stability and you will get donations. At least from me.

**Comment by JayDi85** [comment]
If you want to help then report steps to reproduce a server's crash. It will help to fix it.
