### ISSUE TITLE
Instead of deleting, how about fucking play on the beta server? It crashes within 20 or 30 mins every time. ASK ANYONE on the server

### ISSUE THREAD

**Issue by Navyguy330** [magefree/mage#11253]
title. 

reproduce?  Just go on it and it will crash within 30 mins, I will bet money on it.

**Comment by JayDi85** [comment]
Beta server restarted 8 times today. One of the possible reason -- commander games with lost cards, see #11081. If you have a workable steps then report it. If you haven't then please spend your time on something more useful than useless issues.
