### ISSUE TITLE
Elesh Norn not triggering on damaged permanent

### ISSUE THREAD

**Issue by xenohedron** [magefree/mage#11262]
Reported on discord: [[Elesh Norn]] first ability doesn't trigger when a permanent you control takes damage

https://scryfall.com/card/mom/12/elesh-norn-the-argent-etchings

**Comment by Zerrisx** [comment]
Confirmed this bug: 
![image](https://github.com/magefree/mage/assets/59861365/698b7f26-a343-4cf6-9e37-e63068f08903)
