### ISSUE TITLE
Chandra, Fire of Kaladesh does not trigger transform ability

### ISSUE THREAD

**Issue by filipebfs** [magefree/mage#1126]
1.4.2v3 version

**Comment by LevelX2** [comment]
For me this does work.
How do you do the 3 damage to the opponent player?

**Comment by filipebfs** [comment]
Main phase. I did cast 3 red spells and for each one, activated chandra's ability on response

**Comment by LevelX2** [comment]
I can't reproduce this.
Can you prove a game log?

**Comment by filipebfs** [comment]
Turn 10...

<html>
  <head>
    
  </head>
  <body>
    <font color="#CCCC33">20:40: </font><font color="#20B2AA">FBF</font><font color="Orange"> 
    has joined the game</font>
<font color="#CCCC33">: </font><font color="Orange"><br><b>Match score:</b><br></font><font color="#20B2AA">FBF</font><font color="Orange"> 
    - 1 win<br>DeckHash: -3824640370501090044<br></font><font color="#20B2AA">kiranearitachi</font><font color="Orange"> 
    - 0 wins<br>DeckHash: -3590704872028725404<br><br>You have to win 2 games 
    to win the complete match<br><br>Game has started<br><br></font>
<font color="#CCCC33">20:40: </font><font color="#20B2AA">FBF</font><font color="White"> 
    shuffles his or her library.</font>
<font color="#CCCC33">20:40: </font><font color="#20B2AA">kiranearitachi</font><font color="White"> 
    shuffles his or her library.</font>
<font color="#CCCC33">20:40: </font><font color="#20B2AA">kiranearitachi</font><font color="White"> 
    chooses that he or she takes the first turn</font>
<font color="#CCCC33">20:40: </font><font color="#20B2AA">kiranearitachi</font><font color="White"> 
    draws seven cards</font>
<font color="#CCCC33">20:40: </font><font color="#20B2AA">FBF</font><font color="White"> 
    draws seven cards</font>
<font color="#CCCC33">20:40: </font><font color="#20B2AA">kiranearitachi</font><font color="White"> 
    keeps hand</font>
<font color="#CCCC33">20:40: </font><font color="#20B2AA">FBF</font><font color="White"> 
    keeps hand</font>
<font color="#CCCC33">20:40: </font><font color="Orange">Turn 1 </font><font color="#20B2AA">kiranearitachi</font><font color="Orange"> 
    (20 - 20)</font>
<font color="#CCCC33">20:41: </font><font color="#20B2AA">kiranearitachi</font><font color="White"> 
    plays </font><font color="#B0C4DE">Sandsteppe Citadel [c2e]</font>
<font color="#CCCC33">20:41: </font><font color="#20B2AA">kiranearitachi</font><font color="White"> 
    attacks with 0 creatures</font>
<font color="#CCCC33">20:41: </font><font color="Orange">Turn 2 </font><font color="#20B2AA">FBF</font><font color="Orange"> 
    (20 - 20)</font>
<font color="#CCCC33">20:41: </font><font color="#20B2AA">FBF</font><font color="White"> 
    draws a card</font>
<font color="#CCCC33">20:41: </font><font color="#20B2AA">FBF</font><font color="White"> 
    plays </font><font color="#B0C4DE">Mountain [9a5]</font>
<font color="#CCCC33">20:41: </font><font color="#20B2AA">FBF</font><font color="White"> 
    casts </font><font color="#FF6347">Zurgo Bellstriker [0d5]</font>
<font color="#CCCC33">20:41: </font><font color="#20B2AA">FBF</font><font color="White"> 
    attacks with 0 creatures</font>
<font color="#CCCC33">20:41: </font><font color="Orange">Turn 3 </font><font color="#20B2AA">kiranearitachi</font><font color="Orange"> 
    (20 - 20)</font>
<font color="#CCCC33">20:41: </font><font color="#20B2AA">kiranearitachi</font><font color="White"> 
    draws a card</font>
<font color="#CCCC33">20:41: </font><font color="#20B2AA">kiranearitachi</font><font color="White"> 
    casts </font><font color="#90EE90">Elvish Mystic [815]</font>
<font color="#CCCC33">20:41: </font><font color="#20B2AA">kiranearitachi</font><font color="White"> 
    plays </font><font color="#B0C4DE">Yavimaya Coast [03d]</font>
<font color="#CCCC33">20:41: </font><font color="#20B2AA">kiranearitachi</font><font color="White"> 
    loses 1 life</font>
<font color="#CCCC33">20:41: </font><font color="#20B2AA">kiranearitachi</font><font color="White"> 
    casts </font><font color="#90EE90">Elvish Mystic [2e9]</font>
<font color="#CCCC33">20:41: </font><font color="#20B2AA">kiranearitachi</font><font color="White"> 
    attacks with 0 creatures</font>
<font color="#CCCC33">20:41: </font><font color="Orange">Turn 4 </font><font color="#20B2AA">FBF</font><font color="Orange"> 
    (20 - 19)</font>
<font color="#CCCC33">20:41: </font><font color="#20B2AA">FBF</font><font color="White"> 
    draws a card</font>
<font color="#CCCC33">20:41: </font><font color="#20B2AA">FBF</font><font color="White"> 
    plays </font><font color="#B0C4DE">Mountain [09f]</font>
<font color="#CCCC33">20:42: </font><font color="#20B2AA">FBF</font><font color="White"> 
    casts </font><font color="#FF6347">Monastery Swiftspear [2a1]</font>
<font color="#CCCC33">20:42: </font><font color="#20B2AA">FBF</font><font color="White"> 
    attacks with 2 creatures</font>
<font color="#CCCC33">20:42: </font><font color="White">Attacker: </font><font color="#FF6347">Monastery 
    Swiftspear [2a1]</font><font color="White"> (1/2) unblocked</font>
<font color="#CCCC33">20:42: </font><font color="White">Attacker: </font><font color="#FF6347">Zurgo 
    Bellstriker [0d5]</font><font color="White"> (2/2) unblocked</font>
<font color="#CCCC33">20:42: </font><font color="#20B2AA">kiranearitachi</font><font color="White"> 
    loses 1 life</font>
<font color="#CCCC33">20:42: </font><font color="#20B2AA">kiranearitachi</font><font color="White"> 
    loses 2 life</font>
<font color="#CCCC33">20:43: </font><font color="Orange">Turn 5 </font><font color="#20B2AA">kiranearitachi</font><font color="Orange"> 
    (20 - 16)</font>
<font color="#CCCC33">20:43: </font><font color="#20B2AA">kiranearitachi</font><font color="White"> 
    draws a card</font>
<font color="#CCCC33">20:43: </font><font color="#20B2AA">kiranearitachi</font><font color="White"> 
    casts </font><font color="#90EE90">Satyr Wayfinder [500]</font>
<font color="#CCCC33">20:43: </font><font color="White">Ability triggers: </font><font color="#90EE90">Satyr 
    Wayfinder [500]</font><font color="White"> - When </font><font color="#90EE90">Satyr 
    Wayfinder [500]</font><font color="White"> enters the battlefield, reveal 
    the top four cards of your library. You may put a land card from among 
    them into your hand. Put the rest into your graveyard.</font>
<font color="#CCCC33">20:43: </font><font color="#20B2AA">kiranearitachi</font><font color="White"> 
    reveals </font><font color="#696969">Merciless Executioner</font><font color="White">, 
    </font><font color="#90EE90">Den Protector</font><font color="White">, </font><font color="#F0E68C">Rally 
    the Ancestors</font><font color="White">, </font><font color="#87CEFA">Jace, 
    Vryn's Prodigy</font>
<font color="#CCCC33">20:43: </font><font color="#20B2AA">kiranearitachi</font><font color="White"> 
    puts </font><font color="#696969">Merciless Executioner [97d]</font><font color="White"> 
    from library into his or her graveyard</font>
<font color="#CCCC33">20:43: </font><font color="#20B2AA">kiranearitachi</font><font color="White"> 
    puts </font><font color="#90EE90">Den Protector [918]</font><font color="White"> 
    from library into his or her graveyard</font>
<font color="#CCCC33">20:43: </font><font color="#20B2AA">kiranearitachi</font><font color="White"> 
    puts </font><font color="#F0E68C">Rally the Ancestors [b70]</font><font color="White"> 
    from library into his or her graveyard</font>
<font color="#CCCC33">20:43: </font><font color="#20B2AA">kiranearitachi</font><font color="White"> 
    puts </font><font color="#87CEFA">Jace, Vryn's Prodigy [772]</font><font color="White"> 
    from library into his or her graveyard</font>
<font color="#CCCC33">20:43: </font><font color="#20B2AA">kiranearitachi</font><font color="White"> 
    casts </font><font color="#90EE90">Sylvan Caryatid [efc]</font>
<font color="#CCCC33">20:43: </font><font color="#20B2AA">kiranearitachi</font><font color="White"> 
    attacks with 0 creatures</font>
<font color="#CCCC33">20:43: </font><font color="Orange">Turn 6 </font><font color="#20B2AA">FBF</font><font color="Orange"> 
    (20 - 16)</font>
<font color="#CCCC33">20:43: </font><font color="#20B2AA">FBF</font><font color="White"> 
    draws a card</font>
<font color="#CCCC33">20:43: </font><font color="#20B2AA">FBF</font><font color="White"> 
    plays </font><font color="#B0C4DE">Mountain [920]</font>
<font color="#CCCC33">20:44: </font><font color="#20B2AA">FBF</font><font color="White"> 
    attacks with 2 creatures</font>
<font color="#CCCC33">20:44: </font><font color="White">Attacker: </font><font color="#FF6347">Monastery 
    Swiftspear [2a1]</font><font color="White"> (1/2) blocked by </font><font color="#90EE90">Sylvan 
    Caryatid [efc]</font><font color="White"> (0/3) </font>
<font color="#CCCC33">20:44: </font><font color="White">Attacker: </font><font color="#FF6347">Zurgo 
    Bellstriker [0d5]</font><font color="White"> (2/2) blocked by </font><font color="#90EE90">Satyr 
    Wayfinder [500]</font><font color="White"> (1/1) </font>
<font color="#CCCC33">20:44: </font><font color="#90EE90">Satyr Wayfinder [500]</font><font color="White"> 
    died</font>
<font color="#CCCC33">20:44: </font><font color="#20B2AA">FBF</font><font color="White"> 
    casts </font><font color="#FF6347">Chandra, Fire of Kaladesh [9a1]</font>
<font color="#CCCC33">20:44: </font><font color="Orange">Turn 7 </font><font color="#20B2AA">kiranearitachi</font><font color="Orange"> 
    (20 - 16)</font>
<font color="#CCCC33">20:45: </font><font color="#20B2AA">kiranearitachi</font><font color="White"> 
    draws a card</font>
<font color="#CCCC33">20:45: </font><font color="#20B2AA">kiranearitachi</font><font color="White"> 
    loses 1 life</font>
<font color="#CCCC33">20:45: </font><font color="#20B2AA">kiranearitachi</font><font color="White"> 
    casts </font><font color="#87CEFA">Jace, Vryn's Prodigy [b33]</font>
<font color="#CCCC33">20:45: </font><font color="#20B2AA">kiranearitachi</font><font color="White"> 
    casts </font><font color="#696969">Grim Haruspex [71a]</font>
<font color="#CCCC33">20:45: </font><font color="#20B2AA">kiranearitachi</font><font color="White"> 
    attacks with 0 creatures</font>
<font color="#CCCC33">20:45: </font><font color="Orange">Turn 8 </font><font color="#20B2AA">FBF</font><font color="Orange"> 
    (20 - 15)</font>
<font color="#CCCC33">20:45: </font><font color="#20B2AA">FBF</font><font color="White"> 
    draws a card</font>
<font color="#CCCC33">20:46: </font><font color="#20B2AA">FBF</font><font color="White"> 
    activates: Convoke (Your creatures can help cast this spell. Each creature 
    you tap while casting this spell pays for {1} or one mana of that 
    creature's color.) from </font><font color="#FF6347">Stoke the Flames [671]</font><font color="White"> 
    choosing </font><font color="#FF6347">Chandra, Fire of Kaladesh [9a1]</font><font color="White"> 
    </font>
<font color="#CCCC33">20:46: </font><font color="White">Convoke: </font><font color="#20B2AA">FBF</font><font color="White"> 
    taps </font><font color="#FF6347">Chandra, Fire of Kaladesh [9a1]</font><font color="White"> 
    to pay one colorless mana</font>
<font color="#CCCC33">20:46: </font><font color="#20B2AA">FBF</font><font color="White"> 
    casts </font><font color="#FF6347">Stoke the Flames [671]</font><font color="White"> 
    targeting </font><font color="#696969">Grim Haruspex [71a]</font><font color="White"> 
    </font>
<font color="#CCCC33">20:46: </font><font color="White">Ability triggers: </font><font color="#FF6347">Chandra, 
    Fire of Kaladesh [9a1]</font><font color="White"> - Whenever you cast a 
    red spell, untap </font><font color="#FF6347">Chandra, Fire of Kaladesh 
    [9a1]</font><font color="White">.</font>
<font color="#CCCC33">20:46: </font><font color="White">Ability triggers: </font><font color="#FF6347">Monastery 
    Swiftspear [2a1]</font><font color="White"> - Prowess <i>(Whenever you 
    cast a noncreature spell, this creature gets +1/+1 until end of turn.)</i></font>
<font color="#CCCC33">20:47: </font><font color="#20B2AA">FBF</font><font color="White"> 
    puts </font><font color="#FF6347">Stoke the Flames [671]</font><font color="White"> 
    from stack into his or her graveyard</font>
<font color="#CCCC33">20:47: </font><font color="#696969">Grim Haruspex [71a]</font><font color="White"> 
    died</font>
<font color="#CCCC33">20:47: </font><font color="#20B2AA">FBF</font><font color="White"> 
    attacks with 3 creatures</font>
<font color="#CCCC33">20:47: </font><font color="White">Attacker: </font><font color="#FF6347">Chandra, 
    Fire of Kaladesh [9a1]</font><font color="White"> (2/2) unblocked</font>
<font color="#CCCC33">20:47: </font><font color="White">Attacker: </font><font color="#FF6347">Monastery 
    Swiftspear [2a1]</font><font color="White"> (2/3) unblocked</font>
<font color="#CCCC33">20:47: </font><font color="White">Attacker: </font><font color="#FF6347">Zurgo 
    Bellstriker [0d5]</font><font color="White"> (2/2) unblocked</font>
<font color="#CCCC33">20:47: </font><font color="#20B2AA">kiranearitachi</font><font color="White"> 
    loses 2 life</font>
<font color="#CCCC33">20:47: </font><font color="#20B2AA">kiranearitachi</font><font color="White"> 
    loses 2 life</font>
<font color="#CCCC33">20:47: </font><font color="#20B2AA">kiranearitachi</font><font color="White"> 
    loses 2 life</font>
<font color="#CCCC33">20:47: </font><font color="Orange">Turn 9 </font><font color="#20B2AA">kiranearitachi</font><font color="Orange"> 
    (20 - 9)</font>
<font color="#CCCC33">20:47: </font><font color="#20B2AA">kiranearitachi</font><font color="White"> 
    draws a card</font>
<font color="#CCCC33">20:47: </font><font color="#20B2AA">kiranearitachi</font><font color="White"> 
    plays </font><font color="#B0C4DE">Yavimaya Coast [0ce]</font>
<font color="#CCCC33">20:47: </font><font color="#20B2AA">kiranearitachi</font><font color="White"> 
    activates: Draw a card, then discard a card. If there are five or more 
    cards in your graveyard, exile </font><font color="#87CEFA">Jace, Vryn's 
    Prodigy [b33]</font><font color="White">, then return him to the 
    battlefield transformed underhis owner's control. from </font><font color="#87CEFA">Jace, 
    Vryn's Prodigy [b33]</font>
<font color="#CCCC33">20:47: </font><font color="#20B2AA">kiranearitachi</font><font color="White"> 
    draws a card</font>
<font color="#CCCC33">20:47: </font><font color="#20B2AA">kiranearitachi</font><font color="White"> 
    discards </font><font color="#B0C4DE">Mana Confluence [fef]</font>
<font color="#CCCC33">20:47: </font><font color="#20B2AA">kiranearitachi</font><font color="White"> 
    moves </font><font color="#87CEFA">Jace, Vryn's Prodigy [b33]</font><font color="White"> 
    from battlefield to the exile zone</font>
<font color="#CCCC33">20:47: </font><font color="#20B2AA">kiranearitachi</font><font color="White"> 
    puts </font><font color="#87CEFA">Jace, Vryn's Prodigy [b33]</font><font color="White"> 
    from exiled onto the Battlefield</font>
<font color="#CCCC33">20:48: </font><font color="#20B2AA">kiranearitachi</font><font color="White"> 
    activates: Up to one target creature gets -2/-0 until your next turn. from </font><font color="#87CEFA">Jace, 
    Telepath Unbound [b33]</font><font color="White"> targeting </font><font color="#FF6347">Zurgo 
    Bellstriker [0d5]</font><font color="White"> </font>
<font color="#CCCC33">20:48: </font><font color="#20B2AA">kiranearitachi</font><font color="White"> 
    casts </font><font color="#90EE90">Deathmist Raptor [802]</font>
<font color="#CCCC33">20:48: </font><font color="#20B2AA">kiranearitachi</font><font color="White"> 
    attacks with 0 creatures</font>
<font color="#CCCC33">20:48: </font><font color="Orange">Turn 10 </font><font color="#20B2AA">FBF</font><font color="Orange"> 
    (20 - 9)</font>
<font color="#CCCC33">20:48: </font><font color="#20B2AA">FBF</font><font color="White"> 
    draws a card</font>
<font color="#CCCC33">20:49: </font><font color="#20B2AA">FBF</font><font color="White"> 
    casts </font><font color="#FF6347">Lightning Berserker [cf7]</font>
<font color="#CCCC33">20:49: </font><font color="White">Ability triggers: </font><font color="#FF6347">Chandra, 
    Fire of Kaladesh [9a1]</font><font color="White"> - Whenever you cast a 
    red spell, untap </font><font color="#FF6347">Chandra, Fire of Kaladesh 
    [9a1]</font><font color="White">.</font>
<font color="#CCCC33">20:49: </font><font color="#20B2AA">FBF</font><font color="White"> 
    activates: </font><font color="#FF6347">Chandra, Fire of Kaladesh [9a1]</font><font color="White"> 
    deals 1 damage to target player. If </font><font color="#FF6347">Chandra, 
    Fire of Kaladesh [9a1]</font><font color="White"> has dealt 3 or more 
    damage this turn, exile </font><font color="#FF6347">Chandra, Fire of 
    Kaladesh [9a1]</font><font color="White">, then return her to the 
    battlefield transformed underher owner's control. from </font><font color="#FF6347">Chandra, 
    Fire of Kaladesh [9a1]</font><font color="White"> targeting </font><font color="#20B2AA">kiranearitachi</font><font color="White"> 
    </font>
<font color="#CCCC33">20:49: </font><font color="#20B2AA">kiranearitachi</font><font color="White"> 
    loses 1 life</font>
<font color="#CCCC33">20:50: </font><font color="#20B2AA">FBF</font><font color="White"> 
    casts </font><font color="#FF6347">Lightning Berserker [d36]</font>
<font color="#CCCC33">20:50: </font><font color="White">Ability triggers: </font><font color="#FF6347">Chandra, 
    Fire of Kaladesh [9a1]</font><font color="White"> - Whenever you cast a 
    red spell, untap </font><font color="#FF6347">Chandra, Fire of Kaladesh 
    [9a1]</font><font color="White">.</font>
<font color="#CCCC33">20:50: </font><font color="#20B2AA">FBF</font><font color="White"> 
    activates: </font><font color="#FF6347">Chandra, Fire of Kaladesh [9a1]</font><font color="White"> 
    deals 1 damage to target player. If </font><font color="#FF6347">Chandra, 
    Fire of Kaladesh [9a1]</font><font color="White"> has dealt 3 or more 
    damage this turn, exile </font><font color="#FF6347">Chandra, Fire of 
    Kaladesh [9a1]</font><font color="White">, then return her to the 
    battlefield transformed underher owner's control. from </font><font color="#FF6347">Chandra, 
    Fire of Kaladesh [9a1]</font><font color="White"> targeting </font><font color="#20B2AA">kiranearitachi</font><font color="White"> 
    </font>
<font color="#CCCC33">20:50: </font><font color="#20B2AA">kiranearitachi</font><font color="White"> 
    loses 1 life</font>
<font color="#CCCC33">20:51: </font><font color="#20B2AA">FBF</font><font color="White"> 
    casts </font><font color="#FF6347">Zurgo Bellstriker [ccc]</font>
<font color="#CCCC33">20:51: </font><font color="White">Ability triggers: </font><font color="#FF6347">Chandra, 
    Fire of Kaladesh [9a1]</font><font color="White"> - Whenever you cast a 
    red spell, untap </font><font color="#FF6347">Chandra, Fire of Kaladesh 
    [9a1]</font><font color="White">.</font>
<font color="#CCCC33">20:51: </font><font color="#20B2AA">FBF</font><font color="White"> 
    activates: </font><font color="#FF6347">Chandra, Fire of Kaladesh [9a1]</font><font color="White"> 
    deals 1 damage to target player. If </font><font color="#FF6347">Chandra, 
    Fire of Kaladesh [9a1]</font><font color="White"> has dealt 3 or more 
    damage this turn, exile </font><font color="#FF6347">Chandra, Fire of 
    Kaladesh [9a1]</font><font color="White">, then return her to the 
    battlefield transformed underher owner's control. from </font><font color="#FF6347">Chandra, 
    Fire of Kaladesh [9a1]</font><font color="White"> targeting </font><font color="#20B2AA">kiranearitachi</font><font color="White"> 
    </font>
<font color="#CCCC33">20:52: </font><font color="#20B2AA">kiranearitachi</font><font color="White"> 
    loses 1 life</font>
<font color="#CCCC33">20:52: </font><font color="#FF6347">Zurgo Bellstriker 
    [0d5]</font><font color="White"> is put into graveyard from battlefield</font>
<font color="#CCCC33">20:53: </font><font color="#20B2AA">FBF</font><font color="White"> 
    activates: Convoke (Your creatures can help cast this spell. Each creature 
    you tap while casting this spell pays for {1} or one mana of that 
    creature's color.) from </font><font color="#FF6347">Stoke the Flames [c54]</font><font color="White"> 
    choosing </font><font color="#FF6347">Zurgo Bellstriker [ccc]</font><font color="White"> 
    </font>
<font color="#CCCC33">20:53: </font><font color="White">Convoke: </font><font color="#20B2AA">FBF</font><font color="White"> 
    taps </font><font color="#FF6347">Zurgo Bellstriker [ccc]</font><font color="White"> 
    to pay one red mana</font>
<font color="#CCCC33">20:53: </font><font color="#20B2AA">FBF</font><font color="White"> 
    activates: Convoke (Your creatures can help cast this spell. Each creature 
    you tap while casting this spell pays for {1} or one mana of that 
    creature's color.) from </font><font color="#FF6347">Stoke the Flames [c54]</font><font color="White"> 
    choosing </font><font color="#FF6347">Lightning Berserker [d36]</font><font color="White"> 
    </font>
<font color="#CCCC33">20:53: </font><font color="White">Convoke: </font><font color="#20B2AA">FBF</font><font color="White"> 
    taps </font><font color="#FF6347">Lightning Berserker [d36]</font><font color="White"> 
    to pay one red mana</font>
<font color="#CCCC33">20:53: </font><font color="#20B2AA">FBF</font><font color="White"> 
    activates: Convoke (Your creatures can help cast this spell. Each creature 
    you tap while casting this spell pays for {1} or one mana of that 
    creature's color.) from </font><font color="#FF6347">Stoke the Flames [c54]</font><font color="White"> 
    choosing </font><font color="#FF6347">Lightning Berserker [cf7]</font><font color="White"> 
    </font>
<font color="#CCCC33">20:53: </font><font color="White">Convoke: </font><font color="#20B2AA">FBF</font><font color="White"> 
    taps </font><font color="#FF6347">Lightning Berserker [cf7]</font><font color="White"> 
    to pay one colorless mana</font>
<font color="#CCCC33">20:53: </font><font color="#20B2AA">FBF</font><font color="White"> 
    activates: Convoke (Your creatures can help cast this spell. Each creature 
    you tap while casting this spell pays for {1} or one mana of that 
    creature's color.) from </font><font color="#FF6347">Stoke the Flames [c54]</font><font color="White"> 
    choosing </font><font color="#FF6347">Chandra, Fire of Kaladesh [9a1]</font><font color="White"> 
    </font>
<font color="#CCCC33">20:53: </font><font color="White">Convoke: </font><font color="#20B2AA">FBF</font><font color="White"> 
    taps </font><font color="#FF6347">Chandra, Fire of Kaladesh [9a1]</font><font color="White"> 
    to pay one colorless mana</font>
<font color="#CCCC33">20:53: </font><font color="#20B2AA">FBF</font><font color="White"> 
    casts </font><font color="#FF6347">Stoke the Flames [c54]</font><font color="White"> 
    targeting </font><font color="#20B2AA">kiranearitachi</font><font color="White"> 
    </font>
<font color="#CCCC33">20:54: </font><font color="White">Ability triggers: </font><font color="#FF6347">Monastery 
    Swiftspear [2a1]</font><font color="White"> - Prowess <i>(Whenever you 
    cast a noncreature spell, this creature gets +1/+1 until end of turn.)</i></font>
<font color="#CCCC33">20:54: </font><font color="White">Ability triggers: </font><font color="#FF6347">Chandra, 
    Fire of Kaladesh [9a1]</font><font color="White"> - Whenever you cast a 
    red spell, untap </font><font color="#FF6347">Chandra, Fire of Kaladesh 
    [9a1]</font><font color="White">.</font>
<font color="#CCCC33">20:54: </font><font color="#20B2AA">kiranearitachi</font><font color="White"> 
    loses 4 life</font>
<font color="#CCCC33">20:54: </font><font color="#20B2AA">FBF</font><font color="White"> 
    puts </font><font color="#FF6347">Stoke the Flames [c54]</font><font color="White"> 
    from stack into his or her graveyard</font>
<font color="#CCCC33">20:55: </font><font color="#20B2AA">FBF</font><font color="White"> 
    attacks with 0 creatures</font>
<font color="#CCCC33">20:55: </font><font color="Orange">Turn 11 </font><font color="#20B2AA">kiranearitachi</font><font color="Orange"> 
    (20 - 2)</font>
<font color="#CCCC33">20:55: </font><font color="#20B2AA">kiranearitachi</font><font color="White"> 
    draws a card</font>
<font color="#CCCC33">20:55: </font><font color="#20B2AA">kiranearitachi</font><font color="White"> 
    casts </font><font color="#90EE90">Satyr Wayfinder [cf8]</font>
<font color="#CCCC33">20:55: </font><font color="White">Ability triggers: </font><font color="#90EE90">Satyr 
    Wayfinder [cf8]</font><font color="White"> - When </font><font color="#90EE90">Satyr 
    Wayfinder [cf8]</font><font color="White"> enters the battlefield, reveal 
    the top four cards of your library. You may put a land card from among 
    them into your hand. Put the rest into your graveyard.</font>
<font color="#CCCC33">20:55: </font><font color="#20B2AA">kiranearitachi</font><font color="White"> 
    reveals </font><font color="#B0C4DE">Opulent Palace</font><font color="White">, 
    </font><font color="#B0C4DE">Frontier Bivouac</font><font color="White">, </font><font color="#696969">Mogis's 
    Marauder</font><font color="White">, </font><font color="#696969">Nantuko 
    Husk</font>
<font color="#CCCC33">20:55: </font><font color="#20B2AA">kiranearitachi</font><font color="White"> 
    has conceded.</font>
<font color="#CCCC33">20:55: </font><font color="#20B2AA">FBF</font><font color="White"> 
    has won the game</font>
<font color="#CCCC33">20:55: </font><font color="#20B2AA">kiranearitachi</font><font color="White"> 
    has lost the game.</font>
<font color="#CCCC33">20:55: </font><font color="#20B2AA">kiranearitachi</font><font color="White"> 
    puts </font><font color="#B0C4DE">Opulent Palace [a3c]</font><font color="White"> 
    from library into his or her graveyard</font>
<font color="#CCCC33">20:55: </font><font color="#20B2AA">kiranearitachi</font><font color="White"> 
    puts </font><font color="#B0C4DE">Frontier Bivouac [f62]</font><font color="White"> 
    from library into his or her graveyard</font>
<font color="#CCCC33">20:55: </font><font color="#20B2AA">kiranearitachi</font><font color="White"> 
    puts </font><font color="#696969">Mogis's Marauder [ab2]</font><font color="White"> 
    from library into his or her graveyard</font>
<font color="#CCCC33">20:55: </font><font color="#20B2AA">kiranearitachi</font><font color="White"> 
    puts </font><font color="#696969">Nantuko Husk [028]</font><font color="White"> 
    from library into his or her graveyard</font>
  </body>
</html>

**Comment by drmDev** [comment]
will test more later

**Comment by drmDev** [comment]
Tested in game even using the same spells here and Chandra successfully transformed.

This issue was posted about a year ago, so unless I can find a way to reproduce it in a few days I'll mark it closed.
