### ISSUE TITLE
Custom Card Giving Player's Cards Storm Doesn't Work as an Emblem

### ISSUE THREAD

**Issue by grandogarndo** [magefree/mage#11289]
Hello!
I asked about emblems a while back and the team was awesome enough to actually implement them, but I do have a small problem. I made a simple card that gives all spells you cast storm, and it works perfectly well as an actual card (I tested using many dark rituals and copies of it). However, when put in the command zone as an emblem through the new emblem addition feature, the ability doesn't work. It uses the exact same code as Thrumming Stone except "Ripple 4" is replaced with "Storm". It might be that the wording is the problem, as it currently is a static ability, "Spell you cast have storm", but I don't know how I'd word it to trigger on every spell.

**Comment by xenohedron** [comment]
The culprit for abilities not working as emblems is probably `game.getPermanent()` somewhere in the `apply()` method which will return false when null checked as an emblem is not a permanent. In this case `GainAbilityControlledSpellsEffect` does check it, and probably doesn't need to.

**Comment by xenohedron** [comment]
Should be fixed in 578b682 although there are likely other similar issues, feel free to reopen if you find another to report or it still doesn't work for you.
