### ISSUE TITLE
Add p2p (torrent) exchange of card images

### ISSUE THREAD

**Issue by phughk** [magefree/mage#11287]
I can imagine quite a few users re-download the images for cards. This could be causing an unnecessary burden on scryfall and other sites.

Instead, we could have torrents for each individual set, and then add support for the torrents within xmage.
Doing so would increase the download speeds, lessen traffic, and overall create a better experience.

Obviously this is probably the lowest of priorities, but creating the ticket for gathering thoughts.

**Comment by JayDi85** [comment]
There was a torrent support for image files, but it was not used by users and outdated. See #4246. With fast connection for most users, scryfall support and usage of jpg images instead png -- no needs in torrents at all.
