### ISSUE TITLE
Client Freezes as Soon as it Starts up on MacOS

### ISSUE THREAD

**Issue by sechecopar** [magefree/mage#11292]
So, I figured out that some other people were having the same issue I was on Mac which was basically some other program is interfering with Java so the client can't run properly. 

What sucks though is that the replies are always "it must be Contexts or Magnet or something" I have neither of those apps, so I have no idea what it is that's conflicting with Xmage.

I could go and delete absolutely everything from my Activity Monitor but that would mean I'd have to do that every single time I wanna run Xmage, and since it's not a fast process it would render it virtually unusable anyways. 

Anyone know how I can find out exactly what is clashing with the client so I can just shut that down? Thank you!

Related:
https://github.com/magefree/mage/issues/4920

https://github.com/magefree/mage/issues/5928

https://github.com/magefree/mage/issues/6398

**Comment by JayDi85** [comment]
If it freeze before you see a connection dialog then it's auto-connect problem. See [here for the fix](https://github.com/magefree/mage/issues/4461#issuecomment-361108597).

**Comment by SteffenJahr** [comment]
@JayDi85 Not working for me:
<img width="802" alt="Screenshot 2023-10-11 at 13 46 04" src="https://github.com/magefree/mage/assets/7164777/9c1b4dac-225b-4bae-96b7-faf4b93ecf05">

**Comment by JayDi85** [comment]
@SteffenJahr are you a topic starter? You must restart mac to apply new settings. If not helps then describe your problem with details:
1. Hows you run it?
2. What you see at the end (on freeze moment)?
3. Is it open something on startup?
4. Is it allows to open connect dialog?
5. Is it allows to open country/flag search button in connect dialog?

**Comment by sechecopar** [comment]
> If it freeze before you see a connection dialog then it's auto-connect problem. See [here for the fix](https://github.com/magefree/mage/issues/4461#issuecomment-361108597).

Hi, OP here, that com.apple.java.util.prefs API isn't showing up on my end:
<img width="1680" alt="Screenshot 2023-10-11 at 3 30 28 PM" src="https://github.com/magefree/mage/assets/55767487/441482f2-948a-48f9-8a43-7d48963496eb">

This is where I get to before it freezes:
<img width="1680" alt="Screenshot 2023-10-11 at 3 32 14 PM" src="https://github.com/magefree/mage/assets/55767487/6eeade4b-5b78-4547-9715-ffc46ba4b2d6">

For reference this is my Activity Monitor:
<img width="1680" alt="Screenshot 2023-10-11 at 3 33 22 PM" src="https://github.com/magefree/mage/assets/55767487/c84c0c82-51d8-47cc-9bad-c1fe93c7f336">
Notice the size of the scrolling bar to the right to see how just blindly closing everything isn't a viable option.

**Comment by DeliriumXDHS** [comment]
> > If it freeze before you see a connection dialog then it's auto-connect problem. See [here for the fix](https://github.com/magefree/mage/issues/4461#issuecomment-361108597).
> 
> Hi, OP here, that com.apple.java.util.prefs API isn't showing up on my end: <img alt="Screenshot 2023-10-11 at 3 30 28 PM" width="1680" src="https://private-user-images.githubusercontent.com/55767487/274410602-441482f2-948a-48f9-8a43-7d48963496eb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE2MDkyOTcsIm5iZiI6MTcwMTYwODk5NywicGF0aCI6Ii81NTc2NzQ4Ny8yNzQ0MTA2MDItNDQxNDgyZjItOTQ4YS00OGY5LThhNDMtN2Q0ODk2MzQ5NmViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjAzVDEzMDk1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY5Njg4ZGUzOGZlNTY1NGVjNTA4NmU3YTk3ODJhZGYyMmRiNzIyMDIwOTNhMTY1ZWIzYThiMTQ1OTI1MTNjMzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-BXkKXKGSfc3__jDxMgyGdxYp8RIIi0acuWirpUX6PE">
> 
> This is where I get to before it freezes: <img alt="Screenshot 2023-10-11 at 3 32 14 PM" width="1680" src="https://private-user-images.githubusercontent.com/55767487/274410729-6eeade4b-5b78-4547-9715-ffc46ba4b2d6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE2MDkyOTcsIm5iZiI6MTcwMTYwODk5NywicGF0aCI6Ii81NTc2NzQ4Ny8yNzQ0MTA3MjktNmVlYWRlNGItNWI3OC00NTQ3LTk3MTUtZmZjNDZiYTRiMmQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjAzVDEzMDk1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQyZjVkOGIzZTIyZTdiOWY2MWE1NDI0MmI1YjhkMzk0NTI0Mjg5YjU4MGIwM2Q0OTg3MTM0Y2M0NDgzMTc2MjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.s7akbfZhrpa-uRhAU_59w0XNZ0tLWHC8i7QgDVapdWQ">
> 
> For reference this is my Activity Monitor: <img alt="Screenshot 2023-10-11 at 3 33 22 PM" width="1680" src="https://private-user-images.githubusercontent.com/55767487/274410984-c84c0c82-51d8-47cc-9bad-c1fe93c7f336.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE2MDkyOTcsIm5iZiI6MTcwMTYwODk5NywicGF0aCI6Ii81NTc2NzQ4Ny8yNzQ0MTA5ODQtYzg0YzBjODItNTFkOC00N2NjLTliYWQtYzFmZTkzYzdmMzM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjAzVDEzMDk1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkNWU1NmQ5YjZkNGI4MWU5ZTIxMWE0OTI1YzNhMTE5MDFmMmJhNjgyZmU4NmY4OTViNDM0YWY1YzA0NWUyMmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xWS0B3Ob-QNqxERW2rq28twp8V6w0eLMhXg4AOO4_Gg"> Notice the size of the scrolling bar to the right to see how just blindly closing everything isn't a viable option.
> 
> Thank you for any help you can provide!

Hey, did you solve this issue in any way? It looks like I have the same thing and I can't seem to fix it.

**Comment by JayDi85** [comment]
Follow that instructions to replace xmage’s java with updated version - it must fix most problems: https://github.com/magefree/mage/issues/8406#issuecomment-1011720728

**Comment by DeliriumXDHS** [comment]
Hello,
sorry for getting back to you this late, sadly this has not worked - (I downloaded the newest Mac tar file and overwrote my Contents folder. Still the same issue of an unresponsive XMage Connect Screen.
I really appreciate the help though,


Have a great new year!
 

 
 

Gesendet: Freitag, 15. Dezember 2023 um 03:49 Uhr
Von: "Oleg Agafonov" ***@***.***>
An: "magefree/mage" ***@***.***>
Cc: "DeliriumXDHS" ***@***.***>, "Comment" ***@***.***>
Betreff: Re: [magefree/mage] Client Freezes as Soon as it Starts up on MacOS (Issue #11292)


 

Follow that instructions to replace xmage’s java with updated version - it must fix most problems: #8406 (comment)

**Comment by kholbekj** [comment]
Same issue. no autoconnect, updated the java version.

Tiny detail is, it doesn't hang on startup directly, it hangs right after any interaction with the window (ie. clicking anywhere).

**Comment by JayDi85** [comment]
Solutuion for users who raplaced java, but can't play on public servers -- now it can be compatible: https://github.com/magefree/mage/issues/12768

**Comment by JayDi85** [comment]
Original problem was in wrong implementation of modal windows (xmage code for system events processing). Not actual anymore with non-blocking UI in last release #12825
