### ISSUE TITLE
Can't connect to server

### ISSUE THREAD

**Issue by darthflaw** [magefree/mage#1131]
I followed the instructions on the forums to update my server location(in the launcher settings) and my URL connection list however I still can't connect to any servers. I just get an error saying I'm not using the newest version of XMage.

I've deleted and redownloaded the newest version twice now. Still getting the error, settings still match the instructions I was given.

**Comment by LevelX2** [comment]
Which version number is shown in the title bar when you start the client?

And if you push the check Version button what is shown in the text box?

**Comment by markedagain** [comment]
closing ticket since no extra details were supplied
