### ISSUE TITLE
Aether Vial/Evoke Glitch

### ISSUE THREAD

**Issue by TheDJAB** [magefree/mage#11322]
I put a Solitude into play with Aether Vials activated ability. This triggered the evoke ability, which it should not. Consequently my Solitude sacrificed itself.

**Comment by Susucre** [comment]
[[Solitude]] [[Aether Vial]]

For now I do suspect the bug is due to a cast cancellation leaving some dirty data that evoke was activated.

**Comment by Susucre** [comment]
I failed to replicate the described bug.
Did something happened to the card before in that game? (like cast with evoke, then bounce, or maybe countered by Subtlety?). Might be a wrong interaction with a third effect.

**Comment by TheDJAB** [comment]
I might have put it onto the stack by mistake, then canceled the cast. I don't remember any other interaction with the Solitude before that.
