### ISSUE TITLE
Zirda seemingly doesn't check for companion restriction

### ISSUE THREAD

**Issue by Jipsu** [magefree/mage#11346]
[[Zirda, the Dawnwaker]] companion requires that all permanents in deck have an activated ability. However, it can be chosen as companion with permanents in deck that have no activated ability. Companionable with vanilla creatures; with Urborg, Tomb of Yawgmoth; and correctly with creatures that actually do have an activated ability.

**Comment by xenohedron** [comment]
Looks like this was broken in 13ac8f2c
