### ISSUE TITLE
Unwinding Clock not always untapping artifacts

### ISSUE THREAD

**Issue by Cguy7777** [magefree/mage#11347]
I just played a game of commander against the computer using my artifact deck. During the game, [[Unwinding Clock]] failed to untap my artifacts during the computer's untap several times.

As far as I can tell, nothing in the game should have interfered with the clock's ability. I think [[Storage Matrix]] was the only other thing out that messed with untapping. Rolling back seemed to fix it the first time it happened, but did not the second time despite rolling back multiple times.

[Game Log](https://github.com/magefree/mage/files/13112123/Gamelog.txt)

Screenshot of final board:
![Screenshot from 2023-10-24 02-34-01](https://github.com/magefree/mage/assets/44722506/906e8aa7-cfca-448b-88ad-b0b219901955)

**Comment by jeffwadsworth** [comment]
What type did you choose for the Storage Matrix?  The AI on a turn chose "Creature" type.  That is a restriction effect.

**Comment by xenohedron** [comment]
Looks like Storage Matrix doesn't check which player is actually untapping a permanent when applying the restriction effect, so is bugged when another player would get to untap during that untap step, as with Unwinding Clock.
