### ISSUE TITLE
Unban Chaos Orb in Oldschool Formats

### ISSUE THREAD

**Issue by sebastiandine** [magefree/mage#11344]
With #11306 we have now a suitable implementation of Chaos Orb. Thus, the B&R lists of old-school formats should be updated. Chaos Orb is restricted in all of them.

**Comment by JayDi85** [comment]
@Jipsu banned field and other settings available in the constructed format class, so you can modify it. Example:
https://github.com/magefree/mage/blob/7ec64639bda64c84586aecf64dbfbc0ea8a77114/Mage.Server.Plugins/Mage.Deck.Constructed/src/mage/deck/OldSchool9394EG.java#L34

**Comment by Susucre** [comment]
The issue is that ChaosOrb is banned in Constructed.java (which the OldSchool formats inherit). I'll unban them in the 5 OldSchool formats so they would be properly restricted.
