### ISSUE TITLE
Fateful Absence is putting a clue into play instead of a full investigate effect.

### ISSUE THREAD

**Issue by Susucre** [magefree/mage#11353]
I did not actually tested that it is wrong, but reading the code I would assume [[Fateful Absence]] does not properly work with anything that would care about investigating.
From a quick search [[Erdwal Illuminator]] is one such interaction.

**Comment by Susucre** [comment]
[[Erdwal Illuminator]]

**Comment by xenohedron** [comment]
[Also applies to Declaration in Stone and Blink](https://scryfall.com/search?q=o%3Ainvestigates&unique=cards&as=grid&order=name)

Probably we should make an InvestigateTargetEffect. (I guess it's technically possible to manually fire the INVESTIGATED event, but I don't like that style.)
