### ISSUE TITLE
Random booster draft iterates endless while booster generation

### ISSUE THREAD

**Issue by LevelX2** [magefree/mage#1136]
Random booster draft adds a lot of server CPU load by iterating endless

![randomboosterdraft](https://cloud.githubusercontent.com/assets/2066790/8838546/8e96d58e-30cd-11e5-90fe-b6bb9f7a0ed1.jpg)

**Comment by LevelX2** [comment]
Added a workaround but it's still not clear to me, why this looping happens.

**Comment by LevelX2** [comment]
I deactivated random booster draft in config.xml on xmage.de and restarted the server.

**Comment by Simown** [comment]
Do we know what triggers this behaviour or was it just observed on the server? And every time you do a random booster draft?

**Comment by LoneFox78** [comment]
I see two possible explanations:
1. Some set simply does not have enough commons implemented, or has wrong rarity assigned to them, so there really aren't enough cards to choose from.
2. A thread syncronization problem is messing up the list of available cards.
Considering that there have been random problems with pack generation in other draft formats as well, I do suspect the latter...

**Comment by Simown** [comment]
1) I am not certain there is a set with < 10 commons, or it is trying to get unique commons for each booster? I haven't looked deeply into it yet. In this case it should handle it a bit better and have a maximum iterations before it bails out and tries to generate a new booster. 
2) Thread synchronization should be easily fixable with the correct locking, if indeed it is that.

I have had a quick look at the offending code this morning and some of the logic looks a bit suspect to me. Regardless of the problem, it should be more robust in handling cases like this and *never* have the chance to get in an infinite loop and eat up all the CPU on the server.

**Comment by LevelX2** [comment]
> Do we know what triggers this behaviour or was it just observed on the server? And every time you do a random booster draft?

NO I have no idea. I guess someone started a random booster draft.I don't know which sets were selected.
The list of tournements did not show any running random booster draft tables.
What we can do is add some logging messages at tournament start and /or if the iteration limit is reached to get the information which set(s) can cause this problem.

And I guess we should add some logic to fill up the booster at least with some basic lands, so the tournament itself stays healthy.

**Comment by LevelX2** [comment]
> 1. Some set simply does not have enough commons implemented, or has wrong rarity assigned to them, so there really aren't enough cards to choose from.

What's unclear to me, why the iteration also executes always the remove from the list of commons. That does mean that the list is not empty, because the remove will only be done if the list is not empty because it's checked in the previous code line.

**Comment by Simown** [comment]
> What's unclear to me, why the iteration also executes always the remove from the list of commons. That does mean that the list is not empty, because the remove will only be done if the list is not empty because it's checked in the previous code line.

I don't know if it's the commons being empty that's causing the issue. If this was the case the removal would throw an IndexOutOfBounds exception instead of looping endlessly. If the list of cards were empty looks like it would get stuck as no cards would ever be added to the booster. 

> What we can do is add some logging messages at tournament start and /or if the iteration limit is reached to get the information which set(s) can cause this problem.
Logging is a good idea and @LoneFox78 commented that there is a random issue with pack generation in other formats, so all booster drafts may be affected.  

> And I guess we should add some logic to fill up the booster at least with some basic lands, so the tournament itself stays healthy.
Good plan, rather than filling up with lands we could just select any rarity cards from the set or just duplicate cards that have already been added to the pack, to keep the number of playable picks balanced.

**Comment by Simown** [comment]
An offending set in Dragon's Maze (DGM), the way it's coded is that a common is added and then removed from the set of commons as it is added to the booster. Although this might not have been the planned behaviour. A set with less than 80 commons  (for 8 players) will run out of unique commons to add to the booster and get in to an infinite loop. 

You certainly can have repeats in booster packs, although I suspect it's not truly random, but good enough. I am quite busy this weekend, but I'll fix it up when I get the time.

**Comment by Simown** [comment]
Looks like Dragon's Maze was one of the only sets to override the base behaviour in an attempt to reduce DB load when drafting, which had a bug not copying the retrieved cards and modifying them directly. I have commited a fix for it. It should not get in to an infinite loop now during any draft.

Needs reworking in future to deal with sets that don't have enough cards to fill their place in the booster. I'm closing this as fixed now and adding reworking drafting to my TODO list.
