### ISSUE TITLE
why are new cards made for xmage slower and slower?

### ISSUE THREAD

**Issue by SmokinDice** [magefree/mage#11361]
I was wondering why it takes so long nowadays to get the new cards. I remember updates beeing released to the beta client just a few days after new cards come out.
Now I am waiting for more than 3 weeks for doctor who cards like the eleventh doctor.

Is it because of so much sets beeing released? Or are there less people working on this nowadays.
I kinda wish I could program to help.

**Comment by xenohedron** [comment]
It all depends on how many devs we have volunteering their time to implement cards. (Fwiw, we did get WOE fully implemented the day of the prerelease.) Not sure what else to tell you, you're welcome to try and implement cards if you wish.
