### ISSUE TITLE
Chain of Vapor + Sensei's Divining Top, Sneak Attack

### ISSUE THREAD

**Issue by jlin14** [magefree/mage#1137]
19:32: Turn 17 tek (14 - 13)
19:32: tek draws a card
19:32: tek activates: You may put a creature card from your hand onto the battlefield. That creature gains haste. Sacrifice the creature at the beginning of the next end step. from Sneak Attack [ba1]
19:33: tek puts Griselbrand [0df] from hand onto the Battlefield
19:33: tek attacks with 1 creature
19:33: technotoy casts Chain of Vapor [187] targeting Griselbrand [0df] 
19:33: tek loses 7 life
19:33: tek activates: draw seven cards. from Griselbrand [0df]
19:33: tek draws seven cards
19:33: tek casts Spell Pierce [d10] targeting Chain of Vapor [187] 
19:34: technotoy casts Dark Ritual [7c4]
19:34: technotoy puts Dark Ritual [7c4] from stack into his or her graveyard
19:34: tek puts Spell Pierce [d10] from stack into his or her graveyard
19:34: technotoy puts Griselbrand [0df] from battlefield into its owner's hand
19:34: tek sacrificed Island [b95]
19:34: Chain of Vapor [187] is now targeting Sensei's Divining Top [0ed] 
19:34: tek copies copies Chain of Vapor [187] targeting Sensei's Divining Top [0ed] 
19:34: technotoy puts Chain of Vapor [187] from stack into his or her graveyard
19:34: technotoy activates: look at the top three cards of your Library, then put them back in any order. from Sensei's Divining Top [0ed]
19:34: technotoy puts a card from library to the top of his or her library
19:34: technotoy puts a card from library to the top of his or her library
19:34: technotoy puts a card from library to the top of his or her library
19:35: tek plays Volcanic Island [a35]
19:35: tek casts Gitaxian Probe [e69] targeting technotoy 
19:35: tek draws a card
19:35: tek puts Gitaxian Probe [e69] from stack into his or her graveyard
19:35: tek casts Lotus Petal [d06]
19:35: tek casts Lotus Petal [409]
19:36: tek sacrificed Lotus Petal [d06]
19:36: tek casts Show and Tell [dcb]
19:36: tek puts Griselbrand [0df] from hand onto the Battlefield
19:36: tek puts Show and Tell [dcb] from stack into his or her graveyard
19:36: Ability triggers: Sneak Attack [ba1] - At the beginning of the next end step, sacrifice Griselbrand.
19:36: tek sacrificed Griselbrand [0df]

1) copied Chain of Vapor should've returned Top to opponent's hand (assuming no activation), but it didn't.

2) Sneak Attack's Griselbrand shouldn't have been sacrificed at EOT, since it was returned to my hand and brought back into play with Show and Tell.

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.
