### ISSUE TITLE
Better audio usage

### ISSUE THREAD

**Issue by martsve** [magefree/mage#1138]
I propose a rework of how audio is used in the game.

At the moment all audio is used when YOU perform actions. This works as a feedback to the user for their actions. However, a better usage would be to alert the user of game state.

A few examples, in importance order as I see it:

1. A chime is played every time you pass priority. This serves no point. The sound should be played every time you RECEIVE priority, to alert you that you have to take action. 

2. When you draft, sound is played every time you select a card. However, sound should be played every time you are passed new cards!

3. Audio is currently played every time you select a creature to attack with. Instead, "attack" audio should be played when you receive player damage or 1+ creature are selected for attacking (combat phase). This makes the user more aware that they are taking damage (or are being attacked). Currently it is very "difficult" to notice when your life total is reduced. F.ex. MTGO has both audio and visual notice.

**Comment by LevelX2** [comment]
Valid points.

**Comment by jgod** [comment]
Very nice suggestions. I haven't contributed in a while but the last time I used the client, some of the sounds seemed really silly and pretty low quality (annoying imo). Playing them at weird times wasn't helping anything haha.

Should we just do an audio overhaul in general? 

 UI sounds can be clean, short "clicky" sounds for user feedback like you see in modern applications, while the longer sounds could be replaced with shorter, more neutral ones. If they were cohesive, even better. With some processing (EQ, noise removal) we could really polish it.

**Comment by LevelX2** [comment]
> Should we just do an audio overhaul in general?

Yeah, go for it!

**Comment by jonhwoods** [comment]
>With some processing (EQ, noise removal) we could really polish it.

I found the sounds really annoying too. I edited them a bit to make them shorter and quieter. I'll try to merge them but I'm not really used to github.

**Comment by LevelX2** [comment]
You have to do a pull request to the main repository.

**Comment by jonhwoods** [comment]
Done! https://github.com/magefree/mage/pull/1200

I had to redo it because an xmage update undid the work and deleted the contents of custom folders in the client folder. Still, it was pretty quick and the sounds are much better this way in my opinion.

**Comment by drmDev** [comment]
this one has been completed. We can still improve the audio further, though we'll have a separate issue for it with specifics if needed
