### ISSUE TITLE
are suspend cards hard to do?

### ISSUE THREAD

**Issue by SmokinDice** [magefree/mage#11383]
I was wondering why it takes so long to do some of the doctor who cards, like the eleventh doctor and face of boe.
is it just hard to program? I hope they will be added soon, waiting for a month now :(

**Comment by Susucre** [comment]
If you want specific cards faster, your best bet is to start contributing to the codebase.
This is an open source project with people contributing on their free time, so there is no time table, neither guarantee that these cards will be implemented in the futur.
