### ISSUE TITLE
Refactor: group together cards like Gift of the Gargantuan

### ISSUE THREAD

**Issue by Susucre** [magefree/mage#11389]
Followup of https://github.com/magefree/mage/commit/d08c61c2adbd5b570fc96ef6b37a119669dd90b5#r131723337

[[Gift of the Gargantuan]] way to select "creature card and/or land card" is nicely done. Grouping the targetting in a common class would make it more easily used as a default if new cards using that templating are added.

Probably excluded from the following list are Alchemized Nahiri and [[Axgard Armory]] (although we could use similar technology for other kind of predicates)
https://scryfall.com/search?q=o%3A%2Fan%3F+%5Ba-zA-Z%5D%2B+card+and%5C%2For+an%3F+%5Ba-zA-z%5D%2B+card%2F&unique=cards&as=grid&order=name

**Comment by Susucre** [comment]
[[Gift Gargantuan]] [[Axgard Armory]]

**Comment by xenohedron** [comment]
We have a general case class e.g. `SubTypeAssignment extends RoleAssignment<SubType>` already
