### ISSUE TITLE
Magmatic Channeler doesn't allow you to play MDFCs

### ISSUE THREAD

**Issue by bobwoco** [magefree/mage#11381]
When a card with an alternate cost is exiled with [[magmatic channeler]], you cannot cast it for that cost. This was observed two seperate times, once with [[bala ged recovery]] not being able to be cast on its spell side and once with [[vault skirge]] being unable to pay life.

**Comment by xenohedron** [comment]
Note that neither scenario is actually an alternative cost:
* MDFC is a separate castable component of the card- this is a common bug not handled correctly.
* Phyrexian mana is handled separately as a way to pay the Phyrexian mana cost and I'm surprised this could go wrong.

**Comment by xenohedron** [comment]
Can't reproduce the second- Phyrexian mana works fine for me.
Won't let me cast either side of Bala Ged Recovery, so I suspect it just doesn't handle MDFC correctly.
