### ISSUE TITLE
Retrieve - only brings back selected creature - DOES NOT return selected non-creature

### ISSUE THREAD

**Issue by wb1292** [magefree/mage#11386]
"Return up to one target creature card and up to one target non-creature permanent card from your graveyard to your hand. Exile Retrieve."

After casting Retrieve the selection prompt appears, allowing you to target a creature, then allowing you to target non-creature permanent.  After successfully targeting the 2 cards the game proceeds allowing the mana to be selected to pay for the cost.  As the spell resolves, targeted creature will then return to hand as it should, but the second card targeted, the non-creature, never returns to hand.  The card will no longer be in your graveyard, nor hand.  Retrieve moves to exile as it should.

**Comment by xenohedron** [comment]
Probably missing an EachTargetPointer on the effect
