### ISSUE TITLE
F-keys don't work after graveyard/exile/reveal windows are in focus

### ISSUE THREAD

**Issue by martsve** [magefree/mage#1139]
You can't use F-keys after a graveyard/exile/reveal window have been in focus. Even after it is closed you need to re-select the main window to be able to use F-keys.

They should be useable in all windows..

**Comment by Nidhoegger** [comment]
I guess this is caused by The focus stealing bugfix.

**Comment by LevelX2** [comment]
I noticed this too. And It's a bit annoying.

I guess we have to archieve that the F-Key stroke events are ignored by the exile/graveyard windows and be forwarded to the main panel with the key listener.

**Comment by Nidhoegger** [comment]
I will have a look at it tomorrow

**Comment by LevelX2** [comment]
Another example is the select window if multiple triggered abilities happen. After selecting the order you have to reselect the game window to have F-Keys working.

**Comment by Nidhoegger** [comment]
I am working on a fix, but there are several problems here. But I might have an idea.

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.
