### ISSUE TITLE
Empress Galina ability not working on artifacts  

### ISSUE THREAD

**Issue by catman123456** [magefree/mage#11394]
[[Empress Galina]] is not allowing me to take the [[Sting, the Glinting Dagger]]

![image](https://github.com/magefree/mage/assets/64045003/b9184dce-9815-4515-a3e6-6fc013665970)

**Comment by PurpleCrowbar** [comment]
In the attached image it can be seen that you *do* control the permanent. Gaining control of an equipment while it’s attached to a creature doesn’t cause it to unattach, you just control it i.e., you can activate its abilities (such as equip, in the image you posted), you become the controller of any of its triggered abilities, etc.
