### ISSUE TITLE
Bugreport: Hurkyl, Master Wizard

### ISSUE THREAD

**Issue by TheLobsterMan** [magefree/mage#11397]
Found the following, consistend bug/unintended behavior with 
### Hurkyl, Master Wizard 

When triggered ability 

"_At the beginning of your end step, if you've cast a noncreature spell this turn, reveal the top five cards of your library. For each card type among noncreature spells you've cast this turn, you may put a card of that type from among the revealed cards into your hand. Put the rest on the bottom of your library in a random order._"

resolves, the game lets you pick any singular card out of the 5 revealed cards. This includes creature cards (which shouldn't be possible), as well as not taking the card type of the spell(s) which was cast to trigger the ability in the first place into account. It also is always limited to a single card, even when multiple non-creature spells of different card types have been cast during the turn.

**Comment by xenohedron** [comment]
See #10116
