### ISSUE TITLE
Francisco, Fowl Marauder Damage Issue

### ISSUE THREAD

**Issue by Bdett151** [magefree/mage#11403]
Francisco, Fowl Marauder should trigger off of any damage dealt by a pirate but when it is in play, it is only triggering off of combat damage from pirates. This occured for me when I used Lightning Rig Crew to deal damage to each of my opponents and no triggers happened for Francisco. 

The word "combat" gets added to Francisco's text box when in a game but does not appear there when in the deck editor.

**Comment by xenohedron** [comment]
Yeah I noticed this on code review / text discrepancy, it wasn't an easy fix so hasn't been done yet
