### ISSUE TITLE
Get alerted when you have priority when the window is not in focus

### ISSUE THREAD

**Issue by emerald000** [magefree/mage#1141]
Since the update that removed the focus stealing whenever you got priority, there is no way to know when it is your turn when you are not looking at the game.

Flashing the icon in the taskbar would work, or maybe getting a message in the system tray (like the "Player joined your table").

**Comment by Nidhoegger** [comment]
You should get a notification when a player joins. Focus stealing bugfix only affects active games

**Comment by emerald000** [comment]
I mean during an active game, if you change windows, you cannot know when you are given priority. You have to look manually every 10 seconds.

**Comment by Nidhoegger** [comment]
Thats true. What kind of alert do you think would fit most? Display a message like the "player joined" message or audio notification?

**Comment by emerald000** [comment]
My first guess was to blink the icon in the taskbar, but there might be a better solution.

**Comment by LevelX2** [comment]
There was once a audio signal if a player gets priority.
Maybe we should reactivate this.
It should be discreet and the user should be able to activate/deactivate it in the preferences.
Anyway a blink in the icon of the taskbar could happen as well if xmage is not in the foreground.

**Comment by Nidhoegger** [comment]
I would definitively prefer notfication "player joined table"-like or audio. Personally, I dont give much attention to the TrayIcon...

**Comment by jgod** [comment]
What about [growl-like](http://www.swingfx.ch/twinkle) notifications? The official client does this and it looks slick.

**Comment by fireshoes** [comment]
I noticed that the Rollback Request steals focus, so if you are typing in the chat box and your opponent requests a rollback, your keystroke in the chat box will decline the request before you realize what is happening.

**Comment by datenkeller** [comment]
I would love a subtle sound signal whenever I have priority.

**Comment by dperegolise** [comment]
I believe this PR addresses this super old ticket: https://github.com/magefree/mage/pull/6558

It's done via auditory indication, more details in the PR.

**Comment by Zerrisx** [comment]
Closing as fixed by #6558
