### ISSUE TITLE
Elite spellbinder not allowing exiled card to be cast.

### ISSUE THREAD

**Issue by zoot4life** [magefree/mage#11415]
Opponent used elite spellbinder's ability to exile timewarp from my hand. Timewarp went into the permanent exile zone and i was not able to cast the spell when having the mana available to pay the 2 extra. This happened in a cube draft match and 2 games in a row.

**Comment by jeffwadsworth** [comment]
Works for me in testing.
![worksForMe](https://github.com/magefree/mage/assets/1496996/7ef1e5ac-3e90-493c-b57e-0bb491258bfb)
