### ISSUE TITLE
Text Error: Blade of Selves

### ISSUE THREAD

**Issue by PurpleCrowbar** [magefree/mage#11414]
In Xmage, [[Blade of Selves]]' text has quotation marks around the word "myriad", no full stop, and no hint for myriad, all of which are errors.

In Xmage:
![image](https://github.com/magefree/mage/assets/26198472/048115f8-a9b3-4bd1-a407-94e3d94e6c21)

<details><summary>Real card</summary>

![clb-301-blade-of-selves](https://github.com/magefree/mage/assets/26198472/f913cb2f-4711-4c7f-852c-959be2d042f3)
</details>

**Comment by ldeluigi** [comment]
{{Blade of Selves}}

**Comment by xenohedron** [comment]
This is a common issue for keyword abilities that aren't static abilities. Unless we make some sort of interface that the gain effects can check if an ability is a keyword ability, the best solution is to manually set the text. If you want the reminder text to accurately match the printed card then `setText()` is probably the only way to do it.

**Comment by JayDi85** [comment]
Related issue about that problem: #6728
