### ISSUE TITLE
Banewasp Affliction causing you to lose life, not creature's controller

### ISSUE THREAD

**Issue by Cguy7777** [magefree/mage#11421]
Version: 1.4.52-V6-beta6 (build: 2023-11-10 14:03)

Discovered this while testing. [[Banewasp Affliction]] should cause the controller of the creature it's enchanting to lose life equal to that creature's toughness when it dies, but instead, *I* lost that life.

I tried enchanting and bolting my own creature, and I lost life as expected.

Steps to reproduce:
1. Enchant a creature an opponent controls with Banewasp Affliction.
2. Kill that creature (I tried normal combat damage and Lightning Bolt, and both had the bug).

PS: I just wanted to say that I've been very impressed with the quick response on issues here. Keep up the great work! :-)

**Comment by xenohedron** [comment]
`LoseLifeAttachedControllerEffect` is bugged

**Comment by xenohedron** [comment]
Thanks for writing a clear bug report btw, very helpful
