### ISSUE TITLE
Hellkite Courser Issue

### ISSUE THREAD

**Issue by LizzurdvsSandwurm** [magefree/mage#11426]
Game exception occurred: 

java.lang.IllegalStateException: Target wasn't handled in computer's choose method: mage.target.TargetCard
Server version: 1.4.52-V6-beta6 (build: 2023-11-10 14:03)
Stack trace:
mage.player.ai.ComputerPlayer.choose(ComputerPlayer.java:528)
mage.player.ai.ComputerPlayer.choose(ComputerPlayer.java:129)
mage.cards.h.HellkiteCourserEffect.apply(HellkiteCourser.java:87)
mage.abilities.AbilityImpl.resolveMode(AbilityImpl.java:201)
mage.abilities.AbilityImpl.resolve(AbilityImpl.java:185)
mage.abilities.TriggeredAbilityImpl.resolve(TriggeredAbilityImpl.java:172)
mage.game.stack.StackAbility.resolve(StackAbility.java:87)
mage.game.GameImpl.resolve(GameImpl.java:1744)
mage.game.GameImpl.playPriority(GameImpl.java:1669)
mage.game.turn.Step.priority(Step.java:66)
mage.game.turn.Phase.playStep(Phase.java:204)
mage.game.turn.Phase.play(Phase.java:90)
mage.game.turn.Turn.play(Turn.java:137)
mage.game.GameImpl.playTurn(GameImpl.java:1122)
mage.game.GameImpl.play(GameImpl.java:1029)
mage.game.GameImpl.start(GameImpl.java:1005)
mage.server.game.GameWorker.call(GameWorker.java:34)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)

**Comment by jeffwadsworth** [comment]
[[Hellkite Courser]]
