### ISSUE TITLE
Tiller Engine Doesn't Tap Nonland Permanent

### ISSUE THREAD

**Issue by PsiKoTicK** [magefree/mage#11423]
XMage version installed:  1.4.51-dev (2023-11-18 11-54)

If you select "Tap that creature" instead of "Untap that land" nothing happens.  It untaps lands without issue if that is selected.

**Comment by Susucre** [comment]
[[Tiller Engine]]

**Comment by xenohedron** [comment]
Probably the effect in the second mode needs a `SecondTargetPointer` set, since the triggered ability is adding the land as the first target regardless

**Comment by xenohedron** [comment]
well actually it was much gnarlier than that... with a SetTargetPointer, the trigger overwrites the target pointer defined by the effect, so if there are multiple modes and one needs its own target independent of the trigger, then have to use `SetTargetPointer.NONE` and for the mode that depends on the trigger, must align it to its target some other way.

(if someone has a simpler solution do let me know)
