### ISSUE TITLE
add a monarch/initiative hint to the hints windows

### ISSUE THREAD

**Issue by copperfield42** [magefree/mage#11424]
![image](https://github.com/magefree/mage/assets/4504719/7b037f05-af43-4a9d-afc4-32ea6ff09521)

I like this new hints windows, ~~but I find it odd that you can open it multiple times, up to 6 times apparently, by clicking the hints bottom. I think it should close just like with the grave windows when clicked a second time, or just not open a new one.~~

~~Additionally~~ I would like that indicate who is the monarch and who have the initiative, I think it show in the avatar picture, but as you can see given my circumstances the avatar doesn't show

**Comment by JayDi85** [comment]
Multiple windows by design -- it allows to setup diff settings, e. g. one
for card, one for important condition, etc.

**Comment by copperfield42** [comment]
oh, I see, alright, then just the second part, I would like to request the inclusion of monarch and initiative hints if isn't a problem :)

**Comment by xenohedron** [comment]
Also I'm not familiar with the collapsed button display of the avatar as in your screenshot, is that a setting or automatic depending on window size? does it still have a tooltip? I believe the monarch/initiative designations should be indicated in the tooltip already.

**Comment by JayDi85** [comment]
1. It’s a special small mode (without avatars), auto-enabled on small app’s window size (you can resize it to test manually);
2. Designation info like monarch added to avatar tooltip, but its hard to monitor. So its can be added as card hint to all related cards (best solution);
3. One of the idea behind helper dialog — users will use card hints more often and make more requests to improve miss cards and data;

**Comment by JayDi85** [comment]
New monarch card hints:
![shot_231119_223335](https://github.com/magefree/mage/assets/8344157/55969d38-2309-4d32-9a6f-8bd9d5787e40)
![shot_231119_223215](https://github.com/magefree/mage/assets/8344157/af4a6d7a-ffd4-482a-ae1e-534acc834e33)

Also checked monarch icon -- it appears in full mode only, so players with minimized avatars don't see it (as stated above):
![shot_231119_223322](https://github.com/magefree/mage/assets/8344157/d99e816b-300e-4dbb-b916-3f41d6a0f8c9)
