### ISSUE TITLE
Add ID of card that causes trigger of Lazav, Dimir Mastermind's triggers on the stack

### ISSUE THREAD

**Issue by fireshoes** [magefree/mage#1142]
I was playing Lazav EDH earlier. When multiple creatures enter your opponents' graveyards at the same time, it causes multiple triggers. Without a tag, it's very hard to tell which creature you will clone with the trigger.

**Comment by klayhamn** [comment]
+1!
super useful

**Comment by LevelX2** [comment]
The related permanent is shown in the tooltip for the ability on the stack.
That's where you would like to have added the id?
![lazav](https://cloud.githubusercontent.com/assets/2066790/8892948/b79432b2-3378-11e5-9e7e-a63d58d7247a.jpg)

**Comment by fireshoes** [comment]
Yeah, looks good. Will that also show when choosing the order that the triggers go on the stack? Also, I usually play with tooltips off and turn them on when needed, but if I recall correctly, you're not able to access the preferences menu when there is a popped out window, like choosing the order of triggers or searching your library, so not able to toggle tooltips when one of them is open.

**Comment by drmDev** [comment]
As @LevelX2 mentioned, I believe this enhancement has been taken care of?

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.
