### ISSUE TITLE
Ichor Shade triggers on every end step

### ISSUE THREAD

**Issue by bobwoco** [magefree/mage#11433]
[[Ichor Shade]] triggers at the beginning of every end step, regardless of whether or not a permanent went to the graveyard from the battlefield that turn.

![image](https://github.com/magefree/mage/assets/7343371/50394a40-16fb-4859-8aab-aa76dde3189c)

**Comment by xenohedron** [comment]
Watcher is checking all zone changes, need to restrict to graveyard from battlefield
