### ISSUE TITLE
COMMAND_CARDS_ADD_TO_HAND cheat also passes priority

### ISSUE THREAD

**Issue by ssk97** [magefree/mage#11437]
Using the cheat command to add a card of your choice to hand also causes you to pass priority to your opponent.

I think it would be better if it didn't, but I wasn't sure if it was intentional for some reason (and also I haven't looked too closely at that code before, probably easier to change for someone who already knows that code.)

**Comment by JayDi85** [comment]
It can be bug with get amount or other choose dialog (duplicated commands from client side)

**Comment by JayDi85** [comment]
Well, there are more global problems with user’s response and diff feedback dialogs (diff response types). Writing and waiting code on server side must be reworked somehow to fix it.
