### ISSUE TITLE
[GUI] Minas Tirith and the other LTR legendary lands have the hint is inverted

### ISSUE THREAD

**Issue by copperfield42** [magefree/mage#11441]
[[Minas Tirith]]'s legend hint is inverted

![029 minas Tirith hint](https://github.com/magefree/mage/assets/4504719/ef541ec7-7178-40fc-9735-95b16463ebfd)
it indicate that I have a legend when I don't

![029 minas Tirith hint 2](https://github.com/magefree/mage/assets/4504719/47198e4b-fbdf-4661-b458-73e22f4b48f4)
and vice versa, _Brimaz, King of Oreskos_ in this case

**Comment by permadeath** [comment]
I can confirm that [[Barad-dûr ]], [[Mines of Moria]], [[Rivendell]], and [[The Shire]] are bugged this way as well due to this:

```
    private static final Condition condition
            = new PermanentsOnTheBattlefieldCondition(filter, ComparisonType.EQUAL_TO, 0);
    private static final Hint hint = new ConditionHint(condition, "You control a legendary creature");
```
