### ISSUE TITLE
Timing of Geist of Saint Traft Delayed Trigger incorrect

### ISSUE THREAD

**Issue by ngenisis** [magefree/mage#1145]
Geist of Saint Traft creates a delayed trigger effect that triggers at the beginning of the end of combat step. Gameplay with this card suggests that it is actually triggering at the beginning of the postcombat main phase. I copied the relevant part of the Geist code, and it seems like this is a problem with how Xmage handles end of combat triggers.

CreateDelayedTriggeredAbilityEffect(new AtTheEndOfCombatDelayedTriggeredAbility(effect), false);

**Comment by drmDev** [comment]
Will need to test later to confirm

**Comment by drmDev** [comment]
This issue isn't occurring anymore - confirmed in game. Trigger occurs during EndCombat step and resolves during it as well.
