### ISSUE TITLE
Powerstones don't tap for mana with spells that have been made artifacts by mycosynth lattice

### ISSUE THREAD

**Issue by dashosa** [magefree/mage#11459]
![61caf9ca8f8a08a3ec3b7f7d354384ca (1)](https://github.com/magefree/mage/assets/63882410/fccf9555-b085-4b90-9271-7f7debc857d1)

**Comment by JayDi85** [comment]
Fixed in #11447, will be available with next update.

**Comment by ssk97** [comment]
This is actually not a bug - Mycosynth Lattice makes all cards/spells colorless, but only permanents become artifacts.

**Comment by dashosa** [comment]
Thank you for letting me know. Makes sense. Cheers
