### ISSUE TITLE
Mikaeus  the unhallowed

### ISSUE THREAD

**Issue by drwi** [magefree/mage#11465]
Hi everyone :)

I have a lot of fun playing magic on xmage.. but I've had this behaviour that seemed strange to me, during a xmage duel using mikaeus the unhallowed triggered ability: the creatures that get undying which in xmage come back once dead but only ~exiled and one has to actually cast them ###for their summoning cost from exile### 

This seems surprisingly off as compared to the rule

https://gatherer.wizards.com/pages/card/Details.aspx?multiverseid=456702

And as compared to what happens when one plays IRL tournaments..

Maybe I am mistaken as to what really happened.. maybe the creature was exiled by some other effect .. but I wonder..

Have a great day
Yours faithfully

**Comment by JayDi85** [comment]
[[Mikaeus, the Unhallowed]]

**Comment by jeffwadsworth** [comment]
This works fine for me.  Please re-open if it happens again.
