### ISSUE TITLE
No oracle text reveal on hover over double row of draft pack

### ISSUE THREAD

**Issue by tiera3** [magefree/mage#11466]
When the draft pack is a single row of cards, hovering over a card gives a popup of oracle text.
However, when it is a double row of cards, this does not occur.

**Comment by xenohedron** [comment]
I don't have this problem. Does anyone else have this problem?

**Comment by JayDi85** [comment]
It can be related to bug from last release (works fine on maximized app window, but buggy on small window sizes -- popups in wrong place).
