### ISSUE TITLE
Computer Equipped Team Pennant to Creature They Didn't Control

### ISSUE THREAD

**Issue by JelloPiranha** [magefree/mage#11473]
![Screenshot 2023-11-26 215541](https://github.com/magefree/mage/assets/134155990/9724a74e-c1d4-4bf1-aa86-2357cfa2eda7)

This is a new one for me. Computer 3 was able to equip their Team Pennant to my Necron Warrior Token. I've never had them do anything like this before, so I have to assume the separate "Equip creature token" cost is the culprit.

**Comment by jeffwadsworth** [comment]
[[Team Pennant]]
