### ISSUE TITLE
Stuck on Beta XMage Server Connect Screen

### ISSUE THREAD

**Issue by DeliriumXDHS** [magefree/mage#11488]
When I launch XMage it does so normally. But when I arrive at the Server Connect Screen, theres an infinite loading icon popping up within 2 seconds (not even clicking connect). 

I am on a MacBook and I tried rebooting the laptop and redownloading xmage.

**Comment by JayDi85** [comment]
1. If it's a first run on that machine then nothing to do with it -- used java doesn't support your version, see #11292 (as alternative -- try to install latest java version like 11, 17 or more and run client from a script in mage/mage-client folder, not by a launcher)
2. If you play it already then it's auto-connect problem, see topic above to find a solution.

**Comment by xenohedron** [comment]
User reports problem resolved itself but root cause is unclear
