### ISSUE TITLE
Regression on latest commit: can't select cards in hand

### ISSUE THREAD

**Issue by xenohedron** [magefree/mage#11493]
Introduced by e534497. Clicking does nothing- can't play lands, cast spells, or discard to hand size.

interestingly, spells are highlighted as playable, but lands are not.

**Comment by JayDi85** [comment]
> interestingly, spells are highlighted as playable, but lands are not.

It's a problem with full art lands drawing:

![shot_231130_112247](https://github.com/magefree/mage/assets/8344157/b10b8b4b-ea07-4f28-9b95-0c3e50b5481f)
