### ISSUE TITLE
Command Tower and friends now ask to pick a color regardless if color is needed

### ISSUE THREAD

**Issue by copperfield42** [magefree/mage#11494]
![image](https://github.com/magefree/mage/assets/4504719/802180f4-53bd-4fc7-be92-28d049428a46)

[[Command Tower]] and [[Path of Ancestry]] now ask you pick a color regardless of your color needs if any, in previous versions that was automatic and you only needed to pick is multiple colors were needed...

By extension I suppose the others similar mana producing cards are also affected...

**Comment by xenohedron** [comment]
Probably related to the adjustment from #11467
