### ISSUE TITLE
Dev: problems with IntelliJ IDE and access to PRs list?

### ISSUE THREAD

**Issue by JayDi85** [magefree/mage#11501]
Saw that discussion on discord, but can't confirm it -- IntelliJ works fine and do not require any additional access.

Is it an actual problem? If yes then need details on it to fix.

Works fine for me:
![shot_231201_224149](https://github.com/magefree/mage/assets/8344157/f2daf942-fba3-4293-aff2-fc71ce5eedf6)

**Comment by xenohedron** [comment]
Yes, this is an actual problem for me. The magefree organization doesn't allow OAuth. Strangely, it used to work fine when I didn't have write access, and once I was added as committer it stopped working entirely.

**Comment by Grath** [comment]
I believe IntelliJ full version can access it, but Community Edition isn't allowed to OAuth to the project. I can confirm the same issues with Community Edition.

**Comment by JayDi85** [comment]
ok, I can confirm the problem now:
![shot_231201_231740](https://github.com/magefree/mage/assets/8344157/ec9c70b0-a749-42fd-8bd7-ebdb706cd7b1)

Try settings -> github -> add new account via token and generate it -- is it works for your account?
![shot_231201_232100](https://github.com/magefree/mage/assets/8344157/cff84c00-6dd3-4d4a-ab97-f29795a4c02e)

**Comment by JayDi85** [comment]
I enabled access for JetBrains IDE Integration anyway, so it works fine with oauth too. If not works then go to https://github.com/settings/applications , revoke access for it and create new one by IDE.
![shot_231202_064918](https://github.com/magefree/mage/assets/8344157/f19d47bd-6ccc-4def-872d-caacae5a456e)
