### ISSUE TITLE
Images: phyrexian cards must be downloadable

### ISSUE THREAD

**Issue by JayDi85** [magefree/mage#11537]
https://scryfall.com/search?q=lang%3Aphyrexian

logs example:
```
WARN  2023-12-10 12:12:19,837 Image download failed for DMU - Ajani, Sleeper Agent, http code: 404, url: https://api.scryfall.com/cards/dmu/370/en?format=image =>[pool-11-thread-2] DownloadPicturesService$DownloadTask.run 
WARN  2023-12-10 12:12:19,837 Image download failed for DMU - Ajani, Sleeper Agent, http code: 404, url: https://api.scryfall.com/cards/dmu/370/?format=image =>[pool-11-thread-2] DownloadPicturesService$DownloadTask.run 
WARN  2023-12-10 12:12:19,840 Image download failed for DMU - Sheoldred, the Apocalypse, http code: 404, url: https://api.scryfall.com/cards/dmu/369/en?format=image =>[pool-11-thread-1] DownloadPicturesService$DownloadTask.run 
WARN  2023-12-10 12:12:19,841 Image download failed for DMU - Sheoldred, the Apocalypse, http code: 404, url: https://api.scryfall.com/cards/dmu/369/?format=image =>[pool-11-thread-1] DownloadPicturesService$DownloadTask.run
```

**Comment by LawfulGreen** [comment]
I think the issue is with the language field. 
The download looks for ../xxx/en? and ../xxx/? when it should be asking for ../xxx/**ph**? which gives the image.

This download issue and others seems to have already been brought up in issue #10833

**Comment by JayDi85** [comment]
It's related to scryfall api changes -- they broke old api logic and do not return first available image version now like old days did.

Example:
* Mysterious Egg from IKO https://api.scryfall.com/cards/iko/385/?format=image

I think direct download images format must be changed to support default language code, see `ScryfallImageSupportCards.java::directDownloadLinks` like:
* `put("IKO/Mysterious Egg/385/ja", "https://api.scryfall.com/cards/iko/385/");`

**Comment by LawfulGreen** [comment]
Would it be easier to pull the image directly from .../set/xxx/ { { image_uris: { large:"https..."} } } ?
That ignores language field if not set, but the image is accessible regardless

**Comment by JayDi85** [comment]
Interesting idea. Yes, it can be used as additional source of card's urls. `ScryfallImageSource::getFaceImageUrl` used json data already, but for single card instead whole set.

**Comment by tiera3** [comment]
With regards to LawfulGreen's suggestion, note that DFCs have their images in a slightly different place.
["card_faces"][0]["img_uris"]["large"] for the front face, and
["card_faces"][1]["img_uris"]["large"] for the back face.

**Comment by tiera3** [comment]
I just discovered a possible simple solution

https://api.scryfall.com/cards/dmu/369/?format=image fails with a 404 error
https://api.scryfall.com/cards/dmu/369?format=image successfully returns an image

So if you remove the trailing / (prior to ?format=image) from the API call, that should solve this issue for most of these language fails.
