### ISSUE TITLE
Ward doesn't interact consistently with modal spells like Mystic Confluence / Kolaghan's Command

### ISSUE THREAD

**Issue by stevedavidmusic** [magefree/mage#11539]
We found some inconsistencies regaring ward and modal spells where you get 2 or more effects like Mystic Confluence / Kolaghan's Command:

If I choose triple bounce on Phyrexian Fleshgorger, it will trigger properly. 
<img width="1280" alt="Screen Shot 2023-12-11 at 11 17 49 AM" src="https://github.com/magefree/mage/assets/45299811/3cdd5229-1ee1-4fba-91c0-8b346777edc5">

However, if I target the Phyrexian Fleshgorger once with Mystic Confluence's bounce ability and choose draw a card twice, it does not trigger the ward of Phyrexian Fleshgorger.
<img width="1280" alt="Screen Shot 2023-12-11 at 11 18 46 AM" src="https://github.com/magefree/mage/assets/45299811/9f3dde56-466b-44e0-b5d9-03bddad81b86">

If I use all 3 modes to bounce 2 Phyrexian Fleshgorgers, only the first Phyrexian Fleshgorger I target will have its ward triggered.
<img width="1280" alt="Screen Shot 2023-12-11 at 11 19 18 AM" src="https://github.com/magefree/mage/assets/45299811/dce70e89-62cf-4fc5-829b-27f7b0683cb0">

Kolaghan's Command works similarly to Mystic Confluence. It might have something to do with the order of the modes. Here I select destroy target artifact and deal 2 damage to the player and the ward doesn't trigger.
<img width="1280" alt="Screen Shot 2023-12-11 at 11 36 46 AM" src="https://github.com/magefree/mage/assets/45299811/21b8b927-3372-4048-b6a0-723588fa9408">

However, selecting to deal 2 damage to the creature and having the player discard a card, it DOES trigger the ward. 
<img width="1280" alt="Screen Shot 2023-12-11 at 11 28 13 AM" src="https://github.com/magefree/mage/assets/45299811/ce59a035-3b9f-4960-b2f0-2835ec635e92">

Here I target two different Phyrexian Fleshgorgers with the 2 damage and destroy target artifact modes. Only the creature that was targeted for 2 damage had its ward triggered.
<img width="1280" alt="Screen Shot 2023-12-11 at 11 40 30 AM" src="https://github.com/magefree/mage/assets/45299811/d4c2f793-c0c7-4fce-8237-2cb330753624">

Dividable burn seems to trigger the wards just fine. Example A of targeting 3 Phyrexian Fleshgorgers and all of their wards trigger. 
<img width="1280" alt="Screen Shot 2023-12-11 at 11 26 31 AM" src="https://github.com/magefree/mage/assets/45299811/a31fb583-6c38-4693-8531-7ebe04c11aab">

Example B of targeting two Phyrexian Fleshgorgers
<img width="1280" alt="Screen Shot 2023-12-11 at 11 34 36 AM" src="https://github.com/magefree/mage/assets/45299811/38feb6ae-251c-4235-aa34-3705397a0c29">

Example C of just targeting Phyrexian Fleshgorger and a player.
<img width="1280" alt="Screen Shot 2023-12-11 at 11 27 36 AM" src="https://github.com/magefree/mage/assets/45299811/6bde4bbc-3f93-4a26-a553-e610d8468dd5">

**Comment by xenohedron** [comment]
Thanks for the bug report with clear examples. I believe this is related to #11185, with the helper functions that find the actual target not handling multiple modes as expected.
