### ISSUE TITLE
Scholar of the Lost Trove fails to exile cards

### ISSUE THREAD

**Issue by iamrm91** [magefree/mage#11547]
[[Scholar of the Lost Trove]] is supposed to exile instant or sorcery cards it casts, but the spells are incorrectly returning to the graveyard

**Comment by xenohedron** [comment]
I'd guess this is due to zcc off by one on the fixed target. Possibly affected by 89a7a938, but haven't tested or researched.

```java
ContinuousEffect effect = new ThatSpellGraveyardExileReplacementEffect(true);
effect.setTargetPointer(new FixedTarget(card.getId(), game.getState().getZoneChangeCounter(card.getId())));
game.addEffect(effect, source);
```
