### ISSUE TITLE
Please add Jon Irenicus

### ISSUE THREAD

**Issue by TheDeathryder** [magefree/mage#11555]
Is it possible to add in Jon Irenicus, Shattered One to a release that us non coders have access to?  I did a search and saw that it looked like a few people have messed with him in the past, but he doesn't appear to be in the game client at this time.

**Comment by Susucre** [comment]
[[Jon Irenicus]] can't be added until the game engine can support the 'This creature can’t be sacrificed'. There are a few other cards postponed for the same reason.

**Comment by Susucre** [comment]
[[Jon Irenicus, Shattered]]

**Comment by JayDi85** [comment]
@Susucre sacrifice event and restrict already implemented, see [[Tajuru Preserver]] as example.

**Comment by Susucre** [comment]
No, there is a range of sacrifice in cost that are not covered by Tajuru Preserver.
See #9375 with Assault Suite (that is the only one implemented and has many bugs), and the linked issues/prs.
