### ISSUE TITLE
When using "build-and-package" perl script there is a maven error

### ISSUE THREAD

**Issue by grandogarndo** [magefree/mage#11552]
[Perl and Mvn error.txt](https://github.com/magefree/mage/files/13694416/Perl.and.Mvn.error.txt)
I haven't gotten any maven errors before, is there some compatibility that I need that isn't showing up?

**Comment by JayDi85** [comment]
Thats perl script and other command line features uses a default maven from your system/path (you miss it, so it must be [installed first](https://maven.apache.org/install.html)).

BUT you don’t need it at all. IntelliJ IDEA already has built in maven, so just follow dev instructions to [setup and build xmage by IDE from a wiki](https://github.com/magefree/mage/wiki/Setting-up-your-Development-Environment#intellij-idea).

**Comment by grandogarndo** [comment]
There aren't any instructions on the wiki to make that perl script use the maven running in IntelliJ. Sorry if I'm missing something I picked up this project again after a long time, but I'm pretty sure the whole thing is built with maven correctly.

**Comment by JayDi85** [comment]
I mean you don't need to build xmage by perl script. If you really need it then just install maven to your system by official maven instructions (put bin folder to path variable, add maven_home variable).

**Comment by grandogarndo** [comment]
I downloaded maven (tested it with mvn -v its all set up) and got this error: 
[Perl and Mvn error 2.txt](https://github.com/magefree/mage/files/13707406/Perl.and.Mvn.error.2.txt)
Is there supposed to be a pom.xml file in the Utils folder? I'm running the perl file in IntelliJ maybe that's the problem.

**Comment by JayDi85** [comment]
Must setup IDE script’s working directory to the root folder

**Comment by JayDi85** [comment]
Miss “mage” in working dir:

![IMG_9362](https://github.com/magefree/mage/assets/8344157/354e08c0-efff-413d-bf5d-b8b89d4a021f)

**Comment by grandogarndo** [comment]
And how exactly would I do that? I don't ever remember setting Maven to work just in the IdeaProjects directory.

**Comment by JayDi85** [comment]
ok, I see. Use that two commands to run script from Utils folder:
```
cd .\Utils
perl.exe build-and-package.pl
```

**Comment by grandogarndo** [comment]
Oh great thanks I was overthinking it that worked. I'll make sure to shout you out in this new build its just a fun new gamemode. Cheers!
