### ISSUE TITLE
Solphim, Mayhem Dominus - Ability paid but not activated

### ISSUE THREAD

**Issue by wb1292** [magefree/mage#11564]
Two different occurrences, I paid the mana, discarded the cards and failed to get the indestructible counter on him.

Using the oil slick version of the card if it makes a difference.

**Comment by Susucre** [comment]
[[Solphim, Mayhem Dominus]]

**Comment by Susucre** [comment]
It is working for me
![image](https://github.com/magefree/mage/assets/34709007/a85371a1-ba2d-4ef0-aec2-457d1d19f3bc)

Are you sure no opponent had [[Vorinclex, Monstrous Raider]] in play?
