### ISSUE TITLE
Lucea Kane Copied Neverwinter Hydra

### ISSUE THREAD

**Issue by skaspels** [magefree/mage#11581]
I used Magus Lucea Kane's ability to cast Neverwinter hydra; It copied the neverwinter hydra, the copy showed on the stack with the same value of X (x=4), but when the copy entered the battlefield no dice were rolled and the copy died instantly as it was 0/0. Shouldn't it have rolled dice, just like the regular card did when it entered?

**Comment by skaspels** [comment]
This issue happens with several types of hydras, not just neverwinter hydra. e.g., it also happens with Apocalypse hydra. I think the problem is that neveriwnter hydra and apocalypse hydra both use special effect subroutines to add X counters, and they determine the value of X with, e.g., line 90 in Neverinwterhydra.java:
`int xValue = spellAbility.getManaCostsToPay().getX();` 
and  line 82 in Apocalypse Hydra
`int amount = spellAbility.getManaCostsToPay().getX();`
It looks like getmanacoststopay gets the value of X that was actually paid with mana, and when lucea creates the copy of the spell on the stack, evne though it copies the value of X on the stack, the creature card when it enters BF is looking at the amount of mana that was spent on X, not the value of X. Is there a way to get the value of X while the copy was on the stack that doesn't look at the mana that was spent on X on the stack?

**Comment by DominionSpy** [comment]
As far as I can see, the X value returns the correct amount, however in both Neverwinter Hydra and Apocalypse Hydra, there is a check:
**Neverwinter Hydra**
```
if (spellAbility == null
    || !spellAbility.getSourceId().equals(source.getSourceId())
    || permanent.getZoneChangeCounter(game) != spellAbility.getSourceObjectZoneChangeCounter()) {
  return true;
}
if (!spellAbility.getSourceId().equals(source.getSourceId())) {
  return true;
} // put into play by normal cast
```

**ApocalypseHydra.java**
```
if (spellAbility == null
    || !spellAbility.getSourceId().equals(source.getSourceId())
    || permanent.getZoneChangeCounter(game) != spellAbility.getSourceObjectZoneChangeCounter()) {
  return false;
}
```
In the case of the copy, the spell ability source ID doesn't match the source source ID and the zone change counters also don't match.

I'm not sure what these are trying to prevent. If I remove these checks, the ability works as expected and a permanent copy effect (e.g. Glasspool Mimic) still correctly enters with 0 +1/+1 counters.
