### ISSUE TITLE
Cards Vanish and Won't allow for Casting of Cards

### ISSUE THREAD

**Issue by eHag-FRU** [magefree/mage#11588]
Played a Planes and it went right to grave yard at beginning of game, for no reason, the card also vanished.

Also had tapped land for mana (the right cost for commander) and would not let me cast it and took my mana and left me tapped out!

**Comment by tiera3** [comment]
Especially the second point would have benefited from a screenshot. Did you tap out the mana first (ie put it in your pool) then attempt to move your commander to the stack? Or did you start by moving your commander to the stack, then tap the lands when prompted to pay the cost?
