### ISSUE TITLE
Suspend Casting rules

### ISSUE THREAD

**Issue by Platinum-Bullet** [magefree/mage#11583]
Hey so there is an understandable miss in the way Xmage handles Suspend cards and Boromir. Boromir counters spells that are cast without paying their mana costs, and in the reminder text of suspend cards it says that when you run out of time counters you cast without pay its mana cost. However, reminder text is not rules text.

702.62a Suspend is a keyword that represents three abilities. The first is a static ability that functions while the card with suspend is in a player’s hand. The second and third are triggered abilities that function in the exile zone. “Suspend N—[cost]” means “If you could begin to cast this card by putting it onto the stack from your hand, you may pay [cost] and exile it with N time counters on it. This action doesn’t use the stack,” and “At the beginning of your upkeep, if this card is suspended, remove a time counter from it,” and “When the last time counter is removed from this card, **if it’s exiled, play it without paying its mana cost if able.** If you can’t, it remains exiled. If you cast a creature spell this way, it gains haste until you lose control of the spell or the permanent it becomes.”

Rule 702.62a very specifically says play it not cast it, therefore Boromir Warden of the Tower should not counter suspend cards.

**Comment by xenohedron** [comment]
601.1a. Some [effects](https://yawgatog.com/resources/magic-rules/#effect) still refer to "playing" a [card](https://yawgatog.com/resources/magic-rules/#card). "Playing a [card](https://yawgatog.com/resources/magic-rules/#card)" means playing that [card](https://yawgatog.com/resources/magic-rules/#card) as a [land](https://yawgatog.com/resources/magic-rules/#land) or casting that [card](https://yawgatog.com/resources/magic-rules/#card) as a [spell](https://yawgatog.com/resources/magic-rules/#spell), whichever is appropriate.
