### ISSUE TITLE
Grasp of Fate does not allow player to select/exile nonland permanent for Computer3 in quick 4 player game

### ISSUE THREAD

**Issue by jimga150** [magefree/mage#11594]
Works in quick 2 player game, just allowing me to exile from "Computer". However in the 4 player, it will only ever cycle through Computer and Computer2, skipping Computer3. looking through the adjuster, i can't divine why this would happen.

**Comment by xenohedron** [comment]
Sounds like a range of influence thing

**Comment by jimga150** [comment]
Lol looks like you're right
