### ISSUE TITLE
Game often freezes when tapping for mana. 

### ISSUE THREAD

**Issue by stevedavidmusic** [magefree/mage#11595]
My XMage client has been freezing often, and it almost always happens when I'm tapping for mana. I'm not sure if this has happened with artifacts, but it definitely happens with lands. When it does freeze, it'll always do so when the land is about 45 degrees while tapping as shown in the image below. This probably happens at least once per draft that I play. 

![Screen_Shot_2023-12-30_at_10 43 50_PM](https://github.com/magefree/mage/assets/45299811/d4ee92af-466a-4fe4-bb68-4f66cb1c74ac)

**Comment by JayDi85** [comment]
Look at client logs (launcher/xmage/mage-client/ folder) - it must contains error messages. I don't remember bugs like that (half rotated card image).

**Comment by tiera3** [comment]
I just had this happen to me - and when I went to check the log, it begins presumably after I was able to get back in. So I cannot find any errors.

1:04 PM, T8.ET: tiera3 has rejoined the game
1:04 PM: Turn 9 tiera3 (15 - 18)
1:04 PM, T9.DR: tiera3 draws a card
1:05 PM, T9.DA: tiera3 attacks with 1 creature
1:05 PM, T9.DB: Attacker: [Undead Minotaur](https://github.com/magefree/mage/issues/11595#Undead%20Minotaur) [a1d] (2/3) unblocked
1:05 PM, T9.CD: brotendo loses 2 life at combat from [Undead Minotaur](https://github.com/magefree/mage/issues/11595#Undead%20Minotaur) [a1d]
1:05 PM: Turn 10 brotendo (15 - 16)
1:05 PM, T10.DR: brotendo draws a card
1:06 PM, T10.DA: brotendo attacks with 1 creature
1:06 PM, T10.DB: Attacker: [Predatory Sliver](https://github.com/magefree/mage/issues/11595#Predatory%20Sliver) [57b] (2/2) unblocked
1:06 PM, T10.CD: tiera3 loses 2 life at combat from [Predatory Sliver](https://github.com/magefree/mage/issues/11595#Predatory%20Sliver) [57b]
1:06 PM, T10.M2: brotendo puts [Forest](https://github.com/magefree/mage/issues/11595#Forest) [f14] from hand onto the Battlefield
1:06 PM, T10.M2: brotendo plays [Forest](https://github.com/magefree/mage/issues/11595#Forest) [f14]
1:06 PM, T10.M2: brotendo casts [Sliver Construct](https://github.com/magefree/mage/issues/11595#Sliver%20Construct) [cee]
1:06 PM, T10.M2: brotendo puts [Sliver Construct](https://github.com/magefree/mage/issues/11595#Sliver%20Construct) [cee] from stack onto the Battlefield
1:06 PM, T10.M2: brotendo casts [Deadly Recluse](https://github.com/magefree/mage/issues/11595#Deadly%20Recluse) [ca2]
(rest of long continues until end of game)

Even looking at the file in notepad, there is no other information prior to that point

And here is the screenshot
![image](https://github.com/magefree/mage/assets/87589219/78b8f2d9-affd-4af3-8375-220c937c495b)
It occurred when I was attempting to pay the final mana needed to cast Cancel targetting his creature spell on the stack. When I got back in, it was my turn. I no longer had Cancel in my hand, and he didn't have his creature on the battlefield either. So it appears that Cancel resolved correctly.

**Comment by tiera3** [comment]
Sorry, just realised I looked at the wrong log. Here is the right log.

[extract_from_mageclient.log](https://github.com/magefree/mage/files/13897857/extract_from_mageclient.log)
