### ISSUE TITLE
FightTargetsEffect doesnt work on Tokens

### ISSUE THREAD

**Issue by jimga150** [magefree/mage#11615]
It appears that tokens get null-checked out of `FightTargetsEffect` effects.

Test:
1. Play Wayta, Trainer Prodigy (implemented on #11608) and duplicate with Double Major
2. Play imperial Ceratops and Ripjaw Raptor
3. Tap non-copy Wayta to have the dinosaurs fight each other, each enrage ability will trigger 3 times as expected
4. Tap copied Wayta to have the same two dinosaurs fight each other, fight will not occur at all

**Comment by xenohedron** [comment]
Just fixed in aa4d165 :)
