### ISSUE TITLE
Prevention effects incorrectly applying to different spells (with same card)

### ISSUE THREAD

**Issue by Cguy7777** [magefree/mage#11623]
Tested on the current codebase at time of writing (most recent commit: b3c55555a17100144878c4869f35b7fb691da53f)

To reproduce:
1. Have Consulate Surveillance on the battlefield
2. Cast Shock targeting yourself
3. Activate Consulate's ability in response, choosing the Shock on the stack as the source, and let it resolve
4. Cast Unsubstantiate targeting the Shock, and let it resolve (Shock returns to your hand, and the stack is now empty)
5. Cast the same Shock again, targeting yourself, and let it resolve

Expected result: No damage is prevented, since the Shock that was targeted by the Consulate's ability was a different object than the one that just resolved.

Actual result: Damage from the second Shock to you is prevented.

This is not limited to Consulate Surveillance; it also happens with a Healing Grace, and presumably others.

PS: Thanks for the quick fix on #11606. I found both of these while testing #11596 (Torrent of Lava).

**Comment by xenohedron** [comment]
Oof this one looks less easy :(

**Comment by jeffwadsworth** [comment]
Consulate Surveillance and Healing Grace fixed.  If all goes well, the other custom cards can be added.
