### ISSUE TITLE
Morph creatures on battlefield should use morph token image

### ISSUE THREAD

**Issue by tiera3** [magefree/mage#11622]
I may be wrong, but it appears that the morph token is not used for morphed creatures. 
![image](https://github.com/magefree/mage/assets/87589219/d7e07c6f-3db3-4412-aa58-8fd0653a5c9c)

**Comment by xenohedron** [comment]
Sporadic- sometimes works, often doesn't. Needs investigation.

**Comment by tiera3** [comment]
I looked in the xmage CardViewer at tokens yesterday, and the token does not appear in any of the four sets that have the morph token. https://scryfall.com/search?q=layout%3Atoken+morph+unique%3Aprints&unique=cards&as=grid&order=name

![image](https://github.com/magefree/mage/assets/87589219/b5bf73f1-9db3-4e14-997e-f20e09fe7ffc)

![image](https://github.com/magefree/mage/assets/87589219/1a610ea7-2e69-41ac-8c11-0ec1e22c900d)

![image](https://github.com/magefree/mage/assets/87589219/68122642-44ee-41c6-80ef-42eee0dd705a)

![Uploading image.png…]()

**Comment by tiera3** [comment]
I manually put morph tokens into TOK.zip in the appropriate directories, and now they show up on the battlefield for me - so it appears it is definately an image download issue.

**Comment by jeffwadsworth** [comment]
Do you have some new pics of your viewer?

**Comment by tiera3** [comment]
Morph tokens still dont show in CardViewer, but it is visable on battlefield (after I manually added the image files where they should be). I didn't take a pic of the battlefield though.

**Comment by JayDi85** [comment]
Card Viewer improved to view inner xmage images like morph, blessing, etc. It's added for images check only, real game can be unsupported (blessing) or used as custom object (copy, morph, etc).

All custom token images can be found in `TokenRepository::loadXmageTokens`.

Example:
![shot_240131_034249](https://github.com/magefree/mage/assets/8344157/01074d2b-bd08-45cd-b6d4-695e0af87e56)

**Comment by tiera3** [comment]
It appears the manifest tokens are also valid options for displaying the morph creatures. (I played a morph creature yesterday and it showed no image, but the path to the image was listed as FRF which includes a manifest token not a morph token.) I am about to manually add the manifest tokens to my image files - but they still don't download automatically.

**Comment by tiera3** [comment]
I cannot find that page (view inner xmage images) in my cardviewer. I put Manifest token files into TOK.zip under the sets they belonged to, but the images are still not showing up on the battlefield.

![image](https://github.com/magefree/mage/assets/87589219/8c94705f-860e-4b94-bf7d-25cd285a556b)

Can't quite read the filename it is looking for, but I definately see TOK.zip and FRF\

Looking through the file system, there is however the TOK.ZIP/XMAGE that shows the images you have displayed above.

**Comment by JayDi85** [comment]
Fixed in #11873 and related commits
