### ISSUE TITLE
Runadi Behemoth caller bug

### ISSUE THREAD

**Issue by skaspels** [magefree/mage#11626]
Runadi behemoth caller is not working properly for creature spells with X in their mana cost. I think the problem is in the addcounters line here:

`public boolean replaceEvent(GameEvent event, Ability source, Game game) {
        Permanent creature = ((EntersTheBattlefieldEvent) event).getTarget();
        if (creature != null) {
----->            creature.addCounters(CounterType.P1P1.createInstance(creature.getManaValue() - 4),
                    source.getControllerId(), source, game, event.getAppliedEffects());
        }
        return false;
    }`
Runadi is creating the replacment effect based on the creatures mana cost on the battlefield, not the creatures mana cost while on the stack.
EDIT: formatting

**Comment by jeffwadsworth** [comment]
[[Runadi, Behemoth Caller]]

**Comment by xenohedron** [comment]
probably the replacement event should just take a constructor parameter for the number of counters and store it as a field alongside the spell id
