### ISSUE TITLE
SUPPORT Java Settings

### ISSUE THREAD

**Issue by tiera3** [magefree/mage#11632]
I was advised (the help with memory issues) to add -Xmx26 flag to Client Java Options (On the Java tab of settings in the Xmage Launcher).

![image](https://github.com/magefree/mage/assets/87589219/04aa79ad-5967-40f0-902a-5f1eee6be763)

With that flag set, when I press "Launch Client", I get the following two messages and nothing further happens.

![image](https://github.com/magefree/mage/assets/87589219/e5bf2931-66da-49b4-9d60-f2b0b6347a79)

Removing the flag enables the client to launch normally.

Without the flag, my Client java options are:
-Xmx1024m -Djava.net.preferIPv4Stack=true -Dfile.encoding=UTF-8

What is recommended to use?

**Comment by JayDi85** [comment]
-Xmx??? is a max memory usage flag. You can increase is to -Xmx2000m for better performance (2000m = 2g = give 2 Gb memory to the app).

**Comment by tiera3** [comment]
I see what the problem was. The screenshot I was following showed it as a second argument, so I added it after the existing -Xmx1024mb and obviously two entries for the same flag clashed.

Instead, I changed -Xmx1024mb to -Xmx2048mb and it launches correctly (and shows 1909mb data available - previously there was only 955mb).

-------------------------

Can I ask what other flags are a good idea to include?

The screenshot showing where to add the memory increasing flag shows 
-Xms256m -Xmx2G -XX:MaxPermSize=384m -XX:+UseConcMarkSweep....
It is cut off at that point, so I didn't see the full flag for the last one.

**Comment by JayDi85** [comment]
It’s outdated flags from old launcher/client. Use xmx, encoding and ipv4 only: xmx for memory limit, encoding to fix broken images download in non utf windows versions, ipv4 to fix broken connection and download in some windows versions.

Beta launcher/client already has good settings (well, maybe memory settings can be changed), you don't need to setup it. Additional command line params can helpful to fix some problems and compatibility issues like https://github.com/magefree/mage#troubleshooting--faq
