### ISSUE TITLE
Java Not Found

### ISSUE THREAD

**Issue by ArdentDawn** [magefree/mage#1163]
I've been playing on XMage over the last few days without any problems, but my client is now missing the Java file and repeatedly fails to install it - each time that I click Update, it gives the 'First time running the XMage server' error and goes through the following.

"Java version installed:  
Java version available:  1.7.0_75
Java not found
XMage version installed:  1.4.2v4 (2015-07-25)
XMage version available:  1.4.2v4 (2015-07-25)
Removing previous versions ...
Downloading Java from http://download.oracle.com/otn-pub/java/jdk/7u75-b13/jre-7u75-windows-x64.tar.gz
Installing Java ...Java version installed:  
Java version available:  1.7.0_75
Java not found"

Is there any way to download the appropriate version of Java separately?

**Comment by Zerrisx** [comment]
By now, this has either been resolved or rendered obsolete.
