### ISSUE TITLE
Duration.UntilYourNextTurn is not checked for in DelayedTriggeredAbility

### ISSUE THREAD

**Issue by jimga150** [magefree/mage#11634]
This issue seems to have been referenced in #2078, but the issue was closed with a workaround instead of addressing the root cause.

`DelayedTriggeredAbility` only has support for `EndOfTurn` and `EndOfCombat`. Other durations arent checked for, it seems. I dug in to see what would need to be added to add support for `UntilYourNextTurn`, and it looks like it would involve adding a new method in `DelayedTriggeredAbility` as well as some checks in `CleanupStep`, but the logic for persisting until the controlling player's next turn is a little above my understanding of this codebase.

**Comment by JayDi85** [comment]
Need cards example and reproduceable steps for that bug.

**Comment by xenohedron** [comment]
It's not a bug, but a refactor to support using standard duration parameter instead of workaround.
