### ISSUE TITLE
Picture clarity problem

### ISSUE THREAD

**Issue by SlippyJimmy** [magefree/mage#11640]
<img width="650" alt="image" src="https://github.com/magefree/mage/assets/45062658/34d722cb-aa4d-4bac-8a0d-c1fb3e340db2">

The picture on the left is the effect I previewed in the xmage software, and the right is the effect I used to view the picture using the system picture viewer. It can be clearly seen that the picture in the xmage software is very blurry.

OS: macOS Ventura14.6
Monitor: 4K and enable HIDPI

**Comment by JayDi85** [comment]
Main topic #11640
