### ISSUE TITLE
BUG - Alistair, the Brigadier checks historic permanents incorrectly (WHO)

### ISSUE THREAD

**Issue by Athanar90** [magefree/mage#11665]
![image](https://github.com/magefree/mage/assets/156782362/634d2b60-d9f6-4cbf-8549-baffab28e068)

![who-112-alistair-the-brigadier](https://github.com/magefree/mage/assets/156782362/e48ba98f-b850-40b1-85c3-aea15435f15f)

> Whenever Alistair attacks, you may pay {8}. If you do, creatures you control get +X/+X until end of turn, where X is the number of historic permanents you control.

When activated in a game, this ability granted +15/+15 to all the creatures on the controller's field instead of the expected +6/+6. This corresponded to the total number of historic permanents on all players' battlefields, rather than those controlled by the creature.

Note: The other difference in power comes from Tanazir Quandrix, who set all base power/toughness to 4/4 for the combat. This user would like to point out that no multiple of stacking the two abilities would result in Tanazir Quandrix causing this exact number. Whether the card had any effect at all may be a different story.

**Comment by Susucre** [comment]
Fixed by https://github.com/magefree/mage/commit/027bda9c04e0602ba30bed612a9b8f97d2577500
