### ISSUE TITLE
pooling venom has a bug

### ISSUE THREAD

**Issue by ineiver** [magefree/mage#11679]
Pooling venom

when the controlled tap enchant land, DON'T LOSES 2 life.    That trigger don't work correctly.

Please fix that.

thank you for you work.

**Comment by xenohedron** [comment]
presumably related to f46ac4c5

**Comment by ineiver** [comment]
thank you, good job!
________________________________
De: xenohedron ***@***.***>
Enviado: sábado, 20 de enero de 2024 0:32
Para: magefree/mage ***@***.***>
Cc: ineiver ***@***.***>; Author ***@***.***>
Asunto: Re: [magefree/mage] pooling venom has a bug (Issue #11679)


Closed #11679<https://github.com/magefree/mage/issues/11679> as completed via #11680<https://github.com/magefree/mage/pull/11680>.
