### ISSUE TITLE
Audio Bug

### ISSUE THREAD

**Issue by straightshifty** [magefree/mage#11675]
When I go to spectate or enter a game on XMage on the beta server, audio files from my drive gets played at random and cannot be muted. I changed all settings in the client to mute audio but the sound continued to play. I have tried a fresh restart and full uninstalling and reinstalling the client. I am not sure what is causing the audio to play.

**Comment by JayDi85** [comment]
What's type of audio files (game sounds, music or other)?

**Comment by straightshifty** [comment]
the sounds playing were mp4 files that are saved onto my drive. Sound bits, songs, any mp4 file

**Comment by straightshifty** [comment]
Mp3 files are included

**Comment by JayDi85** [comment]
Go to Preferences -> Sound and disable music. You must restart game/client to apply new settings.

![shot_240117_120512](https://github.com/magefree/mage/assets/8344157/28cb3ad9-6fe6-4c7a-8e9c-14e9ae9c0e0d)
