### ISSUE TITLE
Can a cancel button be added while selecting objects to pay costs, but costs are not payed yet?

### ISSUE THREAD

**Issue by Greeneye0** [magefree/mage#1168]
Can a cancel button be added when selecting creature for Ghirapur AEther Grid?
It would be nice for when we select the wrong target creature:
![image](https://cloud.githubusercontent.com/assets/11687236/8971326/986bf4e2-360c-11e5-9e22-c1c72673d095.png)

**Comment by LevelX2** [comment]
If you selected the wrong creature you can click on the wrongly slected creature again to deselect it.

**Comment by Greeneye0** [comment]
I want to change the target of the damage not the tap.

**Comment by drmDev** [comment]
This could be an all-over enhancement request on cards that have you specify targets etc. Would require a little inner plumbing on the framework to incorporate it.

**Comment by JayDi85** [comment]
Fixed via 3fb18b334d1f8ddbba460090eee68c907505cf92
