### ISSUE TITLE
GainAbilityControlledSpellsEffect not adding AlternativeSourceCosts in time to check playable

### ISSUE THREAD

**Issue by xenohedron** [magefree/mage#11714]
Noticed bug with [[Hunting Velociraptor]] that even if Prowl ability is added, if the normal cost couldn't be paid, the game won't allow casting for Prowl cost either.

> I noticed that you can't cast something for its prowl cost if you could not afford to cast it for its normal cost. The game won't allow me to put the creature on the stack at all.

 > It seems it is only in the case of Hunting Velociraptor and not Prowl in general.
I think this might be because Hunting Velociraptor correctly only grants Prowl to spells you cast and not cards in your hand so the game does not detect for cards that might gain Prowl after being put on the stack.
While perhaps it does check for cards that might gain Convoke after being put on the stack, because Chief Engineer does work.
I have no idea what part of the code verifies if a card can be cast or not though or I would scan that code for any possible fixes.

_Originally posted by @Tharkon in https://github.com/magefree/mage/issues/11600#issuecomment-1911405898_

**Comment by jimga150** [comment]
I can modify hunting velociraptor to act like chief engineer unless you plan to fix the casting cost check issue globally?

**Comment by jimga150** [comment]
scratch that, i didnt check the example first--chief engineer was my template...

**Comment by jimga150** [comment]
It looks like the difference lies in how `ProwlAbility` extends `AlternativeSourceCostsImpl`, while `ConvokeAbility` implements `AlternateManaPaymentAbility`.
