### ISSUE TITLE
Savior of Ollenbock ability triggers even if no +1/+1 counters were put on it

### ISSUE THREAD

**Issue by Cguy7777** [magefree/mage#11718]
Tested on latest codebase at time of writing (most recent commit: 645b79d07ecf6a7ba3fde9411d9bad3b37e3ddc5)
Discovered this while working on #11716.

To reproduce:
1. Have Solemnity on the battlefield.
2. Attack with Savior of Ollenbock and at least one other creature that has greater power
3. Allow Savior's training ability to resolve (no +1/+1 counter will be put on it due to Solemnity)

Expected result: Savior's second ability (Whenever Savior of Ollenbock trains, ...) doesn't trigger, since no +1/+1 counter was put on it. [702.149c](https://yawgatog.com/resources/magic-rules/#R702149) states "When this creature trains" means "When a resolving training ability puts a +1/+1 counter on this creature."

Actual result: Savior's second ability triggers, and lets you exile a creature.

**Comment by JayDi85** [comment]
[[Solemnity]] [[Savior of Ollenbock]]

> A creature “trains” when a +1/+1 counter is put onto it at as a result of its training ability resolving. (2021-11-19)
