### ISSUE TITLE
Starfall draws a card on resultion

### ISSUE THREAD

**Issue by duelcastermage** [magefree/mage#11710]
[[Starfall]] draws a card when it resolves. I targeted an enchantment creature fwiw, haven't tested on a non-enchantment creature yet. Will reply back in this thread if I get the chance to see that and the behavior is different.

**Comment by xenohedron** [comment]
no idea how that would happen based on the code - sure there was no other effect that could have caused that?

**Comment by duelcastermage** [comment]
There was a [[Battlefield Thaumaturge]] in play at the time, IIRC. Perhaps that card caused the bug somehow? (Thaumaturge wasn't targeted by Starfall)

**Comment by xenohedron** [comment]
After investigation of the game log it appears that starfall was cast during upkeep in response to a trigger and then a card was drawn during draw step as would be expected - not a bug
