### ISSUE TITLE
Groundswell Landfall does not always work 

### ISSUE THREAD

**Issue by LevelX2** [magefree/mage#1172]
Played a land and attacked. Cast Groundswell but the targeted attacking creature was only boosted by +2/+2 instead of +4/+4.

21:04: arucki has joined the game
21:04: para has joined the game
: Match score:para
    - 0 winsDeckHash: -3919471667112118846arucki
    - 0 winsDeckHash: 9215796669205848664You have to win 1 game to
    win the complete matchGame has started
21:04: para shuffles his or her library.
21:04: arucki shuffles his or her library.
21:04: para won the toss
21:04: para chooses that he or she takes the first turn
21:04: para draws seven cards
21:04: arucki draws seven cards
21:04: para keeps hand
21:04: arucki keeps hand
21:04: Turn 1 para (25 - 25)
21:04: para plays Forest [9d5]
21:04: para discards Tranquil Thicket [437]
21:04: para
    activates: draw a card. from Tranquil Thicket
    [437]
21:04: para
    draws a card
21:05: para
    attacks with 0 creatures
21:05: Turn 2 arucki
    (25 - 25)
21:05: arucki
    draws a card
21:05: arucki
    plays Misty Rainforest [0e2]
21:05: arucki
    attacks with 0 creatures
21:05: Turn 3 para
    (25 - 25)
21:05: para
    draws a card
21:05: para
    plays Forest [469]
21:05: para
    casts Exploration [e3a]
21:05: arucki
    loses 1 life
21:05: arucki
    sacrificed Misty Rainforest [0e2]
21:05: arucki
    activates: search your library for a Forest or Island and put it onto the
    battlefield. Then shuffle your library. from Misty
    Rainforest [0e2]
21:05: arucki
    searches his or her library
21:05: arucki
    puts Bayou [3f8]
    from library onto the Battlefield
21:05: arucki
    shuffles his or her library.
21:06: para
    attacks with 0 creatures
21:06: Turn 4 arucki
    (25 - 24)
21:06: arucki
    draws a card
21:06: arucki
    plays Inkmoth Nexus [1b5]
21:06: arucki
    casts Sylvan Library [868]
21:06: arucki
    attacks with 0 creatures
21:06: Turn 5 para
    (25 - 24)
21:06: para
    draws a card
21:06: para
    plays Forest [4f3]
21:07: para
    casts Dungrove Elder [101]
21:07: para
    attacks with 0 creatures
21:07: Turn 6 arucki
    (25 - 24)
21:07: arucki
    draws a card
21:07: Ability triggers: Sylvan
    Library [868] - At the beginning of your draw
    step, you may draw two additional cards. If you do, choose two cards in
    your hand drawn this turn. For each of those cards, pay 4 life or put the
    card on top of your library.
21:07: arucki
    draws two cards
21:07: arucki
    loses 4 life
21:07: arucki
    pays 4 life to keep a card on hand
21:07: arucki
    puts 1 card(s) back to library
21:07: arucki
    plays Swamp [db5]
21:07: arucki
    casts Wild Defiance [990]
21:08: arucki
    attacks with 0 creatures
21:08: Turn 7 para
    (25 - 20)
21:08: para
    draws a card
21:08: para
    plays Forest [e86]
21:08: para
    casts Sylvan Scrying [b73]
21:08: para
    searches his or her library
21:08: para
    puts Wasteland [5f1]
    from library into his or her hand
21:08: para
    reveals Wasteland
21:08: para
    shuffles his or her library.
21:08: para
    puts Sylvan Scrying [b73]
    from stack into his or her graveyard
21:08: para
    plays Wasteland [5f1]
21:09: para
    sacrificed Wasteland [5f1]
21:09: para
    activates: destroy target nonbasic land. from Wasteland
    [5f1] targeting Bayou
    [3f8] 
21:09: Bayou [3f8]
    was destroyed
21:09: para
    attacks with 1 creature
21:09: Attacker: Dungrove
    Elder [101] (4/4) unblocked
21:09: arucki
    loses 4 life

21:09: Turn 8 arucki (25 - 16)
21:09: arucki draws a card
21:09: Ability triggers: Sylvan Library [868] - At the beginning of your draw step, you may draw two additional cards. If you do, choose two cards in your hand drawn this turn. For each of those cards, pay 4 life or put the card on top of your library.
21:09: arucki draws two cards
21:09: arucki loses 4 life
21:09: arucki pays 4 life to keep a card on hand
21:09: arucki puts 1 card(s) back to library
21:09: arucki plays Twilight Mire [f4d]
21:10: arucki activates: Inkmoth Nexus [1b5] becomes a 1/1 Blinkmoth artifact creature with flying and infect until end of turn. It's still a land. (It deals damage to creatures in the form of -1/-1 counters and to players in the form of poison counters.). from Inkmoth Nexus [1b5]
21:10: arucki casts Groundswell [b28] targeting Inkmoth Nexus [1b5]
21:10: Ability triggers: Wild Defiance [990] - Whenever a creature you control becomes the target of an instant or sorcery spell, that creature gets +3/+3 until end of turn
21:10: arucki puts Groundswell [b28] from stack into his or her graveyard
21:10: arucki attacks with 1 creature
21:10: Attacker: Inkmoth Nexus [1b5] (6/6) unblocked

21:11: Turn 9 para (25[P:6] - 12)
21:11: para draws a card
21:12: para announces a value of 1 for 
21:12: para casts Lifeblood Hydra [4e0]
21:12: para attacks with 1 creature
21:12: Attacker: Dungrove
    Elder [101] (4/4) unblocked
21:12: arucki
    loses 4 life
21:12: Turn 10 arucki
    (25[P:6] - 8)
21:12: arucki
    draws a card
21:12: Ability triggers: Sylvan
    Library [868] - At the beginning of your draw
    step, you may draw two additional cards. If you do, choose two cards in
    your hand drawn this turn. For each of those cards, pay 4 life or put the
    card on top of your library.
21:13: arucki
    draws two cards
21:13: arucki
    puts 2 card(s) back to library
21:13: arucki
    activates: Inkmoth Nexus [1b5]
    becomes a 1/1 Blinkmoth artifact creature with flying and infect until end
    of turn. It's still a land. (It deals damage to creatures in the form
    of -1/-1 counters and to players in the form of poison counters.).
    from Inkmoth Nexus [1b5]
21:13: arucki
    casts Might of Old Krosa [cf0]
    targeting Inkmoth Nexus [1b5]
21:13: Ability triggers: Wild
    Defiance [990] - Whenever a creature you
    control becomes the target of an instant or sorcery spell, that creature
    gets +3/+3 until end of turn
21:13: arucki
    loses 2 life
21:13: arucki
    casts Mutagenic Growth [a48]
    targeting Inkmoth Nexus [1b5]
21:13: Ability triggers: Wild
    Defiance [990] - Whenever a creature you
    control becomes the target of an instant or sorcery spell, that creature
    gets +3/+3 until end of turn
21:13: para
    has conceded.
21:13: arucki
    has won the game
21:13: para
    has lost the game.

**Comment by rollergo11** [comment]
Has this been fixed yet? I have used groundswell and it works every time for me. Would it have anything to do with Inkmoth Nexus being a token?

**Comment by LevelX2** [comment]
I don't know. I respostet here athe report of the user arucki.
But I was not able to reproduce the problem yet.

**Comment by drmDev** [comment]
Tests also are unable to duplicate the issue. Haven't heard of anyone having this problem either. Tests here:
https://github.com/magefree/mage/blob/master/Mage.Tests/src/test/java/org/mage/test/cards/abilities/keywords/LandfallTest.java#L149-L218
