### ISSUE TITLE
Add artifact and planeswalker count to deck editor

### ISSUE THREAD

**Issue by fireshoes** [magefree/mage#1173]
We already have land, creature, instant, sorcery, and enchantment counts...

**Comment by emerald000** [comment]
No love for Tribals?

**Comment by drmDev** [comment]
I believe Artifact count was added a few months ago? Don't believe we have Planeswalker yet.

**Comment by JayDi85** [comment]
There are only lands and creatures count info. All other can be calculated by sort button, e.g. sorting by card type. Nothing to add.
