### ISSUE TITLE
Eldritch Pact [CLB] Chooses Caster as Target Player regardless of Target Choice

### ISSUE THREAD

**Issue by FoulHowler** [magefree/mage#11736]
Eldritch Pact [CLB] will always choose the caster as the Target Player instead of the chosen target.

This has happened in numerous EDH Games, and is completely recreatable.

**Comment by jeffwadsworth** [comment]
[[Eldritch Pact]]

**Comment by jeffwadsworth** [comment]
Yeah, a little mistake in the oneshoteffect.  I will check it tomorrow time permitting.
