### ISSUE TITLE
[DEV] Adding a card to exile during a card test doesn't work

### ISSUE THREAD

**Issue by DominionSpy** [magefree/mage#11738]
The `CardTestPlayerBase` method `addCard` does not allow the developer to add a card into exile.

**Steps to Reproduce**
- Create a test case with the line `addCard(Zone.EXILED, playerA, "Llanowar Elves");`
- After an `execute()`, assert that the card is in the exile zone: `assertExileCount(playerA, "Llanowar Elves", 1);`
- Observe that the test fails

**Comment by JayDi85** [comment]
Fixed by #11739
