### ISSUE TITLE
Laelia, the Blade Reforge's last ability triggers twice when a single spell or ability exiles from both library and graveyard

### ISSUE THREAD

**Issue by DominionSpy** [magefree/mage#11747]
[[Laelia, the Blade Reforged]]'s third ability reads:
> Whenever one or more cards are put into exile from your library and/or your graveyard, put a +1/+1 counter on Laelia.

According to the rulings, this should only trigger once if a spell or ability exiles cards from the library and graveyard:
>The last ability only triggers once for each time cards are put into exile from your library and/or graveyard, no matter how many cards were exiled at the same time.

Currently this is triggering twice.

**Steps to Reproduce**
Setup:
- A nonland card should be in your graveyard
- The same card should also be in your library
- Laelia, the Blade Reforged should be on your battlefield
- Cranial Extraction should be in your hand
Steps:
- Cast Cranial Extraction targeting yourself and choose the nonland card name
- Exile the copy in the graveyard and the copy in your library
- Observe that two copies of the Laelia trigger are put onto the stack

A similar issue also affects a new MKM card [[Kaya, Spirits' Justice]].

**Comment by xenohedron** [comment]
can presumably be fixed by using new `ZONE_CHANGE_BATCH` (see #11895)
