### ISSUE TITLE
Warden of the Eye Illegal State Exception - Target wasn't handled in Computer's ChooseTarget Method

### ISSUE THREAD

**Issue by MrL4ws0n** [magefree/mage#11757]
I received the below Game error (AI opponent) And when it rollsback the AI attempts to do the same action again, essentially locking the game in purgatory.

All cards in the AI's graveyard are Blasphemous act, Fog Bank, and Supreme Verdict.

Game error occurred: 

java.lang.IllegalStateException: Target wasn't handled in computer's chooseTarget method: mage.target.TargetCard
Server version: 1.4.52-V7-beta7 (build: 2024-01-30 18:53)
Stack trace:
mage.player.ai.ComputerPlayer.chooseTarget(ComputerPlayer.java:1133)
mage.target.TargetImpl.chooseTarget(TargetImpl.java:371)
mage.target.Targets.chooseTargets(Targets.java:96)
mage.abilities.AbilityImpl.activate(AbilityImpl.java:352)
mage.players.PlayerImpl.triggerAbility(PlayerImpl.java:1623)
mage.game.GameImpl.checkTriggered(GameImpl.java:2254)
mage.game.GameImpl.checkStateAndTriggered(GameImpl.java:2148)
mage.game.GameImpl.playPriority(GameImpl.java:1640)
mage.game.turn.Step.priority(Step.java:67)
mage.game.turn.Phase.playStep(Phase.java:204)
mage.game.turn.Phase.play(Phase.java:90)
mage.game.turn.Turn.play(Turn.java:137)
mage.game.GameImpl.playTurn(GameImpl.java:1117)
mage.game.GameImpl.play(GameImpl.java:1024)
mage.game.GameImpl.start(GameImpl.java:1000)
mage.server.game.GameWorker.call(GameWorker.java:34)
mage.server.game.GameWorker.call(GameWorker.java:15)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)

**Comment by JayDi85** [comment]
Well, it's not a real fix. Something wrong with TargetCard processing in AI code. E.g. miss graveyard zone check or wrong filter
