### ISSUE TITLE
[DOM] Corrosive Ooze does not destroy Equipment

### ISSUE THREAD

**Issue by aquibulhaq** [magefree/mage#11766]
The triggered ability of [[Corrosive Ooze]] appears on the stack, but it does not destroy the Equipment attached to the creature being blocked. Game log and demonstration are attached.

Version information:

>Reading config from http://xmage.today//config.json
>XMage folder:  D:\Games\Windows\XMage\Beta
>XMage Launcher version installed:  0.3.8
>XMage Launcher version available:  0.3.8
>Java version installed:  1.8.0_201
>Java version available:  1.8.0_201
>XMage version installed:  1.4.51-dev (2024-01-30 19-35)
>XMage version available:  1.4.51-dev (2024-01-30 19-35)

[20240209_011927_Two Player Duel_1.html.txt](https://github.com/magefree/mage/files/14217699/20240209_011927_Two.Player.Duel_1.html.txt)

https://github.com/magefree/mage/assets/54506546/8d8ed8c6-ecb3-4d26-92cd-54ce27d51d31

**Comment by xenohedron** [comment]
Well the code for that effect is a mess.

Relevant rulings:

_The set of Equipment to be destroyed is determined only as Corrosive Ooze’s delayed triggered ability resolves at the end of combat. The Equipment will be destroyed even if Corrosive Ooze leaves the battlefield before that time. (2018-04-27)_

_If the creature Corrosive Ooze blocks or is blocking leaves the battlefield, the Equipment that was attached to that creature immediately before it left the battlefield will be destroyed as Corrosive Ooze’s delayed triggered ability resolves at the end of combat. (2018-04-27)_
