### ISSUE TITLE
Chandra, Fire of Kaladesh combat damage not triggering transformation

### ISSUE THREAD

**Issue by roberttkelly** [magefree/mage#1176]
As the title says, the pinging ability of chandra is working for the transformation if I can activate it three times, however if I ping, cast a red spell, untap chandra, and deal 2 combat damage with her, she is not transforming as she should

**Comment by emerald000** [comment]
The transform ability is part of her ping ability. So she should only flip after activating her ability.

**Comment by roberttkelly** [comment]
This is not true, it says if she's dealt 3 damage this turn transform her. Combat damage is her dealing damage also

**Comment by Greeneye0** [comment]
According to this page it isn't just ping damage. Its my understanding that she should flip right after she has delt 3 or more damage (in any way) in a turn.

http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=398422

6/22/2015	Chandra, Fire of Kaladesh’s activated ability will count any damage Chandra has dealt during the turn to any permanent or player, including combat damage.

**Comment by LevelX2** [comment]
**But read the rulings:**
The check happens only as that activated ability resolves. You must activate the ability in order to exile Chandra and return her to the battlefield transformed, even if Chandra has already dealt 3 or more damage during the turn.
