### ISSUE TITLE
Missing cards from "Exit from Exile" precon

### ISSUE THREAD

**Issue by drownik** [magefree/mage#11793]
There are 2 missing cards for a basic precon: Exit from Exile.

The missing cards are:

Durnan of the Yawning Portal (https://www.moxfield.com/cards/dX69X-tlincalli-hunter)
Tlincalli Hunter (https://www.moxfield.com/cards/nay6x-durnan-of-the-yawning-portal)

Please, add them so I can test the deck properly.

**Comment by Grath** [comment]
Duplicate of #8785
