### ISSUE TITLE
manifested land rendered with color, but should be colorless

### ISSUE THREAD

**Issue by xenohedron** [magefree/mage#11792]
![image](https://github.com/magefree/mage/assets/12538125/f13bf01e-b063-4f91-8d38-b93f9af35cc0)

**Comment by xenohedron** [comment]
10:01 PM, T13.CD: Face down card reveal: Tr3nZ had Mountain [5d1]

**Comment by xenohedron** [comment]
in another game, a red creature was manifested and it correctly appeared colorless

**Comment by JayDi85** [comment]
Fixed in #11873 and related commits
