### ISSUE TITLE
Skill selection in create Tournament dialog does not work correct.

### ISSUE THREAD

**Issue by LevelX2** [magefree/mage#118]
The skill for the AI players can't be selected for the values of the drop down box that are displayed outside of the area of the dialog window. The click does not work, only if I click on a vlaue inside of the area of the dialog window can be selected.
![SkillSelection](https://f.cloud.github.com/assets/2066790/120801/3c946b04-6d37-11e2-9ea0-74b7f55d9b0a.jpg)

**Comment by drmDev** [comment]
This does not appear to be an issue anymore. I am able to select any of the skill levels, though it can be finicky and require multiple attempts at times.

**Comment by LevelX2** [comment]
I still have this problem. It happens exactly if the values you like to select are outside of the frame of the underlying window (shown by the red circle).
This does not happen on your system?

**Comment by drmDev** [comment]
I am able to select them, and it accepts it. Like I said, sometimes it takes more than one attempt for some weird reason, but I am able to select them. I'll keep it open then if its still an issue for others.
