### ISSUE TITLE
MB1 / FMB1 upstream database change

### ISSUE THREAD

**Issue by xenohedron** [magefree/mage#11806]
From scryfall discord 2024-01-21:

> In order to better match how stores and WotC are organizing the various List-like cards (mostly, they’re not and also they’re adding repeats to more products) we’ve made the following changes:
> - PLIST has been re-coded PLST (the old code is still an alias) https://scryfall.com/sets/plst
> - ULIST has been re-coded ULST (the old code is still an alias) https://scryfall.com/sets/ulst
> - PAGL (Angels, They’re Just Like Us) has been merged into PLST
> - PHED (Heads I Win) has been merged into PLST
> - PCTB (Cute to Brute) has been merged into PLST
> - MB1 (Mystery Booster) has been merged into PLST
> - FMB1 (Mystery Booster Retail Foils) has been merged into PLST

This results in mtgjson verify warnings for the whole MB1 set, e.g.:
> Warning: Can't find card in mtgjson to verify for MB1 - Absorb Vis - 558

As an example for recategorized card: https://scryfall.com/card/plst/CN2-126/absorb-vis

The collation for Mystery Booster has been carefully implemented into xmage and must be preserved when adjusting. However, adjustment will be needed in order to support image download from scryfall's updated database.

One thought I have is to transform the existing MB1 collation into a framework for custom boosters, with the additional advantage that other remastered sets (consisting of custom collation from existing prints) can be implemented in a similar way.

**Comment by tiera3** [comment]
Also note, whilst the set may still be an alias, the collector numbers don't match what is currently listed in the xmage code, so it is my guess that the collector numbers have changed.

**Comment by JayDi85** [comment]
For info: 
* Xmage must use scryfall sets structure (except for custom and inner sets like star wars and xmage);
* No needs in set aliases. Deck editor will warn and auto-convert decks with wrong card numbers on editing.

**Comment by JayDi85** [comment]
![IMG_0215](https://github.com/magefree/mage/assets/8344157/73ab89be-01d3-46a5-86cc-df427548d268)

Possible problems before migration/refctor:
1. [ ] 3500 cards in one set can be a problem (by performance, by cards amount limit). Need to test performance for booster generation, drafts, cubes, deck editor and card viewer;
2. [ ] Looks like a mb1 has special collation and it must be implemented for old mb1 cards, not full PLIST? How critical is this problem? Is it possible to migrate that collation to PLIST?
3. [ ] What’s about mtgjson - is it use old or new cards structure?

P.S. Both mtgjson and scryfall download has set code replacement feature, but it works with set code only, not card numbers. It’s possible to split one big set to multiple smaller (card numbers will be compatible and same as big set). Xmage uses it in old days for some special sets like mtg events (before scryfall).

**Comment by Susucre** [comment]
The MB1 cards can be found with that search: [https://scryfall.com/search?q=is%3Amb1&unique=cards&as=grid&order=name](https://scryfall.com/search?q=is%3Amb1&unique=cards&as=grid&order=name)
 
The card number has nothing in common though. Probably the easiest way would be to produces a static MB1 => PLST mapping just once.

**Comment by xenohedron** [comment]
I'd argue that there's no reason for XMage to support PLIST at all. There's no unique art, it's always an existing card print just with a tiny symbol in the corner.

Basically, MysteryBooster could be adjusted so that it doesn't have any unique cards, but populates its booster map from the original prints of all those cards.

**Comment by Susucre** [comment]
> I'd argue that there's no reason for XMage to support PLIST at all.

I do agree with this. PLST is very bloated, and skip referencing it altogether does make a lot of sense, as it's neither new art nor cards.
