### ISSUE TITLE
Lifelink should not have reminder text

### ISSUE THREAD

**Issue by PurpleCrowbar** [magefree/mage#11812]
The last time cards with lifelink were printed with reminder text was four years ago in M21. What with this keyword being evergreen, and every card with the keyword in the last four years being printed without reminder text, XMage should likewise stop including reminder text with the keyword.

**Comment by xenohedron** [comment]
Seems reasonable. Any other evergreen / MageSingleton keywords you think shouldn't have reminder text anymore?

**Comment by PurpleCrowbar** [comment]
> Seems reasonable. Any other evergreen / MageSingleton keywords you think shouldn't have reminder text anymore?

Couldn't say off the top of my head, lifelink is just the most obvious offender given its prevalence in every set
