### ISSUE TITLE
Mob Rule Bug

### ISSUE THREAD

**Issue by skaspels** [magefree/mage#11811]
Cast [[Mob rule]] using the power 3 or less mode against a board with several merfolk, including two lords. When the spell resolved, I gained control of two lords, which caused one merfolk on the opponents board to drop below power 3. The spell then untapped the merfolk I got control of AND the one still on opponents board that had dropped below power 3; last, the spell granted the merfolk on the opponents board that it untapped to gain haste, but the three I had gained control of did not get haste.

**Comment by xenohedron** [comment]
related to #9560
