### ISSUE TITLE
Fix CardHintsTest after adjustment to logs for face-down objects

### ISSUE THREAD

**Issue by xenohedron** [magefree/mage#11828]
[ERROR] Failures:

[ERROR] CardHintsTest.test_ObjectNamesInHtml:130->assertObjectSupport:74->assertObjectHtmlLog:47 [4b3]: can't find full text in face down object [4b3] expected:<[][4b3]> but was:<[face down object ][4b3]>

Relevant commit is e264457, temporarily ignored by 07c2cda8

**Comment by JayDi85** [comment]
Fixed by #11873
