### ISSUE TITLE
Sacrificing to Eldrazi Monument should not be optional.

### ISSUE THREAD

**Issue by Tharkon** [magefree/mage#11823]
[[Eldrazi Monument]] has a triggered ability at your upkeep that requires you to sacrifice a creature.
The game asks if you want to and gives you the option to decline, causing Eldrazi Monument to be sacrificed.
This is not how the card works, you must sacrifice a creature if you can, only if you can't will the Monument be sacrificed.

**Comment by xenohedron** [comment]
Looks like a refactor in a55cfe2 failed to account for that
