### ISSUE TITLE
Ledger Shredder Connive not triggering?

### ISSUE THREAD

**Issue by SargeRyong** [magefree/mage#11824]
Ledger Shredder's connive triggered ability isn't triggering for some reason.

In my game:
T2, cast Ledger Shredder
T3, swing with Ledger Shredder, cast Chart a Course in main phase two.  Chart a course resolves normally, cards are drawn, but Ledger Shredder does not trigger.
T4, I cast Frantic Search, drawing additional cards and the trigger still did not activate.

On version 1.4.52-V7-beta7

**Comment by xenohedron** [comment]
[[Ledger Shredder]]

**Comment by xenohedron** [comment]
Based on your description, no player cast their second spell on any turn, so I don't see why you would expect the ability to trigger.

**Comment by SargeRyong** [comment]
> Based on your description, no player cast their second spell on any turn, so I don't see why you would expect the ability to trigger.

...  I'm dumb, please disregard.

I was thinking "draws their second card" rather than "casts their second spell".
