### ISSUE TITLE
Since 1.4.2v5 Update "Target Player" Selection is Semi-Inresponsive

### ISSUE THREAD

**Issue by FastTadpole** [magefree/mage#1182]
Select starting Player or Select target creature or player (when selecting player) for any reason takes many many clicks to actually pick up the click and resolve the target as player, no issue with players. I find that sometimes when clicking elsewhere on the field it can help somewhat but not consistently as it is hard to replicate.

**Comment by LevelX2** [comment]
It's already fixed for the version beyond 1.4.2v5.
