### ISSUE TITLE
UNCONFIRMED BUG - LCI The Enigma Jewel

### ISSUE THREAD

**Issue by tiera3** [magefree/mage#11832]
During the game, I thought the hint said "craft with four nonlands" so I attempted to craft and targeted four non-land cards in my graveyard. (Only two of them had activated abilities.)

At that point, my opponent pointed out that not all those cards had activated abilities. I hovered over the card and read the image that said "craft with four nonlands with activated abilities" and responded that I hadn't read that the first time.

My opponent commented that xmage must not be correctly enforcing it and initiated a rollback - which I accepted.

**Comment by xenohedron** [comment]
Perhaps the problem is `SpellAbility` as a subclass of `ActivatedAbilityImpl`

**Comment by JayDi85** [comment]
[[The Enigma Jewel]]

**Comment by JayDi85** [comment]
Yes, it must use ability type check like mana does: AbilityType.ACTIVATED, not class compare. If that code copied from another places then it must be fixed too.

![IMG_9750](https://github.com/magefree/mage/assets/8344157/b4633de2-380c-4732-a1bc-b9de60256ce8)
