### ISSUE TITLE
Unable to connect to server

### ISSUE THREAD

**Issue by majicman79** [magefree/mage#1183]
When I updated this morning to version 1.4.3 I got the following message:

Unable to connect to server. Wrong client version 1.4.3V0, expecting version 1.4.2.v5.

Please download needed version from http:... etc etc.

I have uninstalled and started a fresh but it is not working no matter what i do ?

**Comment by emerald000** [comment]
The remote server you are connecting to has yet to be updated. Meanwhile, you can use Woogerworks server.

**Comment by majicman79** [comment]
Worked pal thanks ✌

**Comment by majicman79** [comment]
Well tHoughton it worked and sort off did, connected to server but it's is now saying (could not create player majicman79 as a human) ?

**Comment by LevelX2** [comment]
Fixed by restart.
