### ISSUE TITLE
Cases should have a hint indicating their solved status

### ISSUE THREAD

**Issue by PurpleCrowbar** [magefree/mage#11861]
Currently, when a case enchantment is solved there is no indicator to inform the player that this is the case (no pun intended).

**Comment by xenohedron** [comment]
Take a look at the existing `CaseSolvedHint` implemented in #11713

**Comment by PurpleCrowbar** [comment]
> Take a look at the existing `CaseSolvedHint` implemented in #11713

Ah the hint is implemented uniquely pertaining to each card's condition. I'll amend Case of the Shifting Visage now and assume all other cases have the appropriate case. Thanks
