### ISSUE TITLE
Show cards sorted alphabetically when searching opponent's deck (Slaughter Games issue?)

### ISSUE THREAD

**Issue by sumsarz** [magefree/mage#11874]
When you're searching a deck with for example Slaughter Games the window for the deck is seemingly randomized, making it hard to get an overview of the contents and quickly find the cards you want to click on (even possible to miss one).

I'd suggest changing to being sorted alphabetical to mirror MTGO behavior.

**Comment by JayDi85** [comment]
Are you talking about card selection windows like that?

![shot_240229_105326](https://github.com/magefree/mage/assets/8344157/02a3f018-9746-4322-8c46-e907673a3a91)

**Comment by JayDi85** [comment]
Choose card name and same dialogs uses auto-sorting:
![shot_240229_105234](https://github.com/magefree/mage/assets/8344157/78d5d466-c4ab-4776-9100-6763d377487e)

**Comment by sumsarz** [comment]
Yeah, that one. But I just noticed Surgical Extraction showed a sorted window, so maybe it's just Slaughter Games which is weird?

**Comment by sumsarz** [comment]
This how it looked when resolving [[Slaughter Games]], the deck in disarray.
![image](https://github.com/magefree/mage/assets/19838146/34db6356-f05a-4e49-bb18-99a79b43ecca)

**Comment by sumsarz** [comment]
Looks like the two cards are implemented differently. Slaughter Games uses `applySearchAndExile` which has does the graveyard:

`// cards in Library
                Cards cardsInLibrary = new CardsImpl();
                cardsInLibrary.addAllCards(targetPlayer.getLibrary().getCards(game));
                cardsCount = cardsInLibrary.count(filter, game);
                filter.setMessage("card named " + cardName + " in the library of " + targetPlayer.getLogName());
                TargetCardInLibrary targetLib = new TargetCardInLibrary(0, cardsCount, filter);
                if (controller.choose(Outcome.Exile, cardsInLibrary, targetLib, source, game)) {
                    controller.moveCards(new CardsImpl(targetLib.getTargets()), Zone.EXILED, source, game);
                }`

While Surgical implements it in the card itself:

` // cards in Library
                filterNamedCard.setMessage("card named " + nameToSearch + " in the library of " + owner.getName());
                TargetCardInLibrary targetCardInLibrary = new TargetCardInLibrary(0, Integer.MAX_VALUE, filterNamedCard);
                if (controller.searchLibrary(targetCardInLibrary, source, game, owner.getId())) {
                    List<UUID> targets = targetCardInLibrary.getTargets();
                    for (UUID targetId : targets) {
                        Card targetCard = owner.getLibrary().getCard(targetId, game);
                        if (targetCard != null) {
                            controller.moveCardToExileWithInfo(targetCard, null, "", source, game, Zone.LIBRARY, true);
                        }
                    }
                }`

I figure sorting the library is done differently in the implementations someshow.
