### ISSUE TITLE
[SLP] Secret Lair Showdown set missing (code included)

### ISSUE THREAD

**Issue by sumsarz** [magefree/mage#11880]
Seems Secret Lair Showdown (SLP) cards aren't implemented.

Card gallery: https://scryfall.com/sets/slp

**Comment by tiera3** [comment]
Feedback on the code you provided. (Note - I've only just stated fiddling with the code myself, so don't take my comments as gospel.)

There were two errors:
* Dragonlord Silumgar had the wrong collector number (19 vs 9)
* Valakut, the Molten Pinnacle had the wrong rarity (MYTHIC vs RARE)

Both these errors were picked up by Travis CI.

I've also noted (from other set files) that where the collector number is numeric, other sets specify it in their code as a number (ie without the surrounding quotes) so I made that change also.

**Comment by sumsarz** [comment]
Thanks for the code feedback, and good the issues were caught.

As for the missing cards, it seems those three have been added this past week. I also can't find a fourth one.
