### ISSUE TITLE
Activating Ugins Mastery Throws Exception

### ISSUE THREAD

**Issue by avaramis** [magefree/mage#11888]
When casting a morph creature and triggering ugins mastery it errored out.
Maybe because it's a split card?

Game error occurred: 

java.lang.IllegalArgumentException: Wrong code usage: can't create permanent card from split or mdf: Dusk // Dawn
Server version: 1.4.52-V7-beta7 (build: 2024-01-30 18:53)
Stack trace:
mage.game.permanent.PermanentCard.<init>(PermanentCard.java:53)
mage.game.ZonesHandler.maybeRemoveFromSourceZone(ZonesHandler.java:359)
mage.game.ZonesHandler.lambda$moveCards$0(ZonesHandler.java:107)
java.util.ArrayList.removeIf(ArrayList.java:1413)
mage.game.ZonesHandler.moveCards(ZonesHandler.java:107)
mage.players.PlayerImpl.moveCards(PlayerImpl.java:4682)
mage.abilities.effects.keyword.ManifestEffect.apply(ManifestEffect.java:78)
mage.abilities.AbilityImpl.resolveMode(AbilityImpl.java:192)
mage.abilities.AbilityImpl.resolve(AbilityImpl.java:176)
mage.abilities.TriggeredAbilityImpl.resolve(TriggeredAbilityImpl.java:172)
mage.game.stack.StackAbility.resolve(StackAbility.java:84)
mage.game.GameImpl.resolve(GameImpl.java:1751)
mage.game.GameImpl.playPriority(GameImpl.java:1671)
mage.game.turn.Step.priority(Step.java:67)
mage.game.turn.Phase.playStep(Phase.java:204)
mage.game.turn.Phase.play(Phase.java:90)
mage.game.turn.Turn.play(Turn.java:137)
mage.game.GameImpl.playTurn(GameImpl.java:1117)
mage.game.GameImpl.play(GameImpl.java:1024)
mage.game.GameImpl.start(GameImpl.java:1000)
mage.server.game.GameWorker.call(GameWorker.java:34)
mage.server.game.GameWorker.call(GameWorker.java:15)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)

**Comment by JayDi85** [comment]
[[Ugin's Mastery]]

**Comment by JayDi85** [comment]
Fixed by 11ddfa0087519b434eb594e20285c8fdba0744d9, part of #11873
