### ISSUE TITLE
Error: Could not find or load main class mage.client.MageFrame

### ISSUE THREAD

**Issue by adam17adam** [magefree/mage#1189]
whenever I try to load xmage after updating it with version 1.4.3 stating "Error: Could not find or load main class mage.client.MageFrame" I have had it for several months now and this is the first time this has happened. I have tried updating it again but to no effect.

**Comment by Dadupe** [comment]
I just updated my launcher and have the same mistake.

**Comment by Batil** [comment]
I have the same problem. Did you manage to fix it? I would really like to know how.

**Comment by adam17adam** [comment]
It fixed itself.



Sent from my Samsung device


-------- Original message --------

**Comment by Dadupe** [comment]
I disinstalled the graph cards and reinstalled it.

2016-01-15 13:32 GMT+00:00 Batil <notifications@github.com>:
