### ISSUE TITLE
Missing set: SCD - Starter Commander Decks

### ISSUE THREAD

**Issue by PurpleCrowbar** [magefree/mage#11893]
Link to set on Scryfall: https://scryfall.com/sets/scd

All cards are reprints so nothing to be implemented code-wise.

**Comment by xenohedron** [comment]
@theelk801 is this something you have a script for?

**Comment by tiera3** [comment]
I could use the same script I used to set up ANB.

**Comment by theelk801** [comment]
I can do this in the morning

**Comment by xenohedron** [comment]
I don't think #11897 implemented this properly - looks like it only includes cards starting with A through L...

**Comment by tiera3** [comment]
You are correct. It only added the first 175 cards (sorted alphabetically). I'll get onto this.

**Comment by tiera3** [comment]
My apologies but the above PR created an error with Travis.

[ERROR] Failures: 
[ERROR]   TokenImagesTest.test_FaceDown_LandWithMorph_MustGetDefaultImage:769->assert_FaceDownMorphImageNumber:360 server side expected:<[1, ]2, 3> but was:<[]2, 3>
[INFO] 
[ERROR] Tests run: 4835, Failures: 1, Errors: 0, Skipped: 82

I am not sure how to address this, so will need to leave it for someone else to complete.
