### ISSUE TITLE
Aspect of Manticore and Airtight Alibi not granting their "to end of turn" effects.

### ISSUE THREAD

**Issue by tiera3** [magefree/mage#11907]
Another player reported Aspect of Manticore not granting First Strike until end of turn.
I found Airtight Alibi had a similar effect and used different code, so asked him to check that, and he said that also didn't appear to grant Hexproof until end of turn.

![image](https://github.com/magefree/mage/assets/87589219/95cbd9a6-44b5-47c2-8abb-1eda443cd730)

**Comment by tiera3** [comment]
Just in case this is a more widespread problem, here is the scryfall search I used to find cards with similar effects. https://scryfall.com/search?q=t%3Aaura+o%3Awhen+o%3Aenters+o%3Aenchanted+o%3A%22end+of+turn%22&order=released&as=grid&unique=cards (Note - not all of them will be applicable.)

**Comment by xenohedron** [comment]
This feels like a regression - maybe related to change from 78612dd
