### ISSUE TITLE
Error reading config from http://xmage.de/xmage/config.json Possible causes:  Site is offline or internet connection is unavailable.

### ISSUE THREAD

**Issue by TheWitchKingedh** [magefree/mage#11906]
I already downloaded the new version and it worked but when i closed and re opened it it gave me this error again. how can i fix this so i can play online again?

**Comment by JayDi85** [comment]
You must download, unpack and run full client from http://xmage.today/

if not helps then open launcher and change settings:
![image](https://github.com/magefree/mage/assets/8344157/6dbe67a2-18f8-4ba8-81d0-a40e094a3851)

**Comment by TheWitchKingedh** [comment]
ok thank you, its working now that i unpacked it from the zipped file. thank you!
