### ISSUE TITLE
Casting a Megamorph creature reveals information

### ISSUE THREAD

**Issue by ssk97** [magefree/mage#11914]
![image](https://github.com/magefree/mage/assets/8648826/a038419f-645b-425d-9c57-4f7b0b70802e)
This line is in the game log for both players, revealing that the card was a Megamorph card and not a Morph card. Until the creature is unmorphed, the two must be identical.

> 702.37c To cast a card using its morph ability, turn it face down and announce that you’re using a morph ability.

You announce that it's "a" morph ability, not which particular morph ability you're using.

**Comment by tiera3** [comment]
Looking at the code, it also appears to differentiate by which token image it uses:

Mage/src/main/java/mage/abilities/effects/common/continuous/BecomesFaceDownCreatureEffect.java
        // image
        String tokenName;
        switch (faceDownType) {
            case MORPHED:
                tokenName = TokenRepository.XMAGE_IMAGE_NAME_FACE_DOWN_MORPH;
                break;
            case MEGAMORPHED:
                tokenName = TokenRepository.XMAGE_IMAGE_NAME_FACE_DOWN_MEGAMORPH;
                break;

**Comment by xenohedron** [comment]
This is a regression from the face down rework.
