### ISSUE TITLE
Norn's Decree drawing cards

### ISSUE THREAD

**Issue by ProfessorQu** [magefree/mage#11921]
I was playing a game when someone attacked someone else while the defending player had no poison counters. Despite that Norn's Decree still triggered and allowed the attacking player to draw a card. This is obviously unintended behaviour.

**Comment by xenohedron** [comment]
`AttackedPlayersPoisonedCondition` (only used for [[Norn's Decree]] ) is bugged, it uses `getDefenders()` incorrectly

![image](https://github.com/magefree/mage/assets/12538125/ac436c4a-fa09-446c-98bd-e3e36d2af8e9)

![image](https://github.com/magefree/mage/assets/12538125/fa731011-8a67-44ed-9de7-3f01000aeeb6)
