### ISSUE TITLE
Five minute timers

### ISSUE THREAD

**Issue by jdmagtibay** [magefree/mage#11925]
Hi. I am a fan of your awesome work. But I want to request a feature. Since you already add buffers, can you add five minute timers instead of ten minutes being the shortest option? Because it seems like you won't be adding the five minute kick, so this will be an alternative for that. I mean I can set a longer buffer so that everyone still can do what they want but only have time taken when they got idle for too long. I hope you can consider. There are just some players who just rope the games.

**Comment by jdmagtibay** [comment]
Ahm, is this saying that this will be implemented in the next update?

**Comment by xenohedron** [comment]
Yes, that's correct - whenever next beta releases, it will include this timer option

**Comment by jdmagtibay** [comment]
Thank you very much for the quick response. I should've done this a long time ago.
