### ISSUE TITLE
Tap Lands for mana and doesn't show in pool

### ISSUE THREAD

**Issue by cchron1907** [magefree/mage#1193]
My opponent tapped three lands and mana didn't show up in pool to use later in the phase. Help?

**Comment by markedagain** [comment]
do u have more details plz ? what cards were on board maybe the log? cant fix such a general statement of tapping mana did not work :(

**Comment by cchron1907** [comment]
From what I can tell I never got a log.

The cards on his side of the board were two Kiora's Follower and a Voyaging Satyr, and Thornwood Falls and a couple basic lands (two forests, I believe). He was trying to stock up the mana by tapping the three lands and then using voyaging satyr to untap them after untapping voyaging satyr with the kiora's follower. But even after tapping the lands the first time, I was watching his mana pool and the number never changed from zero.

**Comment by drmDev** [comment]
I've played against enough Tooth and Nail / Hypergenesis decks to confirm this issue is resolved. Issues with it will be user error, which is understandable since the UI isn't always the most intuitive.
