### ISSUE TITLE
Lara Croft, Tomb Raider as though ability maybe not properly scoped to controller

### ISSUE THREAD

**Issue by xenohedron** [magefree/mage#11945]
from discord:

> Someone just got to cast my [[Mithril Coat]] using my [[Lara Croft]] trigger lol, I think the ability might be given to everyone

not immediately obvious why that would be, so should get a unit test to investigate

**Comment by jeffwadsworth** [comment]
[[Mithril Coat]] [[Lara Croft, Tomb Raider]]

**Comment by catman123456** [comment]
> from discord:
> 
> > Someone just got to cast my [[Mithril Coat]] using my [[Lara Croft]] trigger lol, I think the ability might be given to everyone
> 
> not immediately obvious why that would be, so should get a unit test to investigate

Lara Croft ability works on any graveyard
