### ISSUE TITLE
Qarsi Deceiver mana doesn't count towards showing morph ability as playable

### ISSUE THREAD

**Issue by xenohedron** [magefree/mage#11956]
Another instance of the common bug with conditional mana and alternate costs.

[[Qarsi Deceiver]]

The mana works fine to cast a spell using morph but only if you would have had enough mana available without it.

**Comment by JayDi85** [comment]
Current code:

![IMG_0009](https://github.com/magefree/mage/assets/8344157/952cf41a-63d9-4291-a4b7-76b0fb153b14)

Maybe can help additional spell cast mode checking like that:

![IMG_0008](https://github.com/magefree/mage/assets/8344157/b92ab95d-8d91-4a6e-8b0b-eb304b3e15f0)

**Comment by ssk97** [comment]
Also, it seems like it's wrong in the checking `TurnFaceUpAbility` would also allow it to pay to flip Disguise or Cloak instead of only Morph and Manifest.
