### ISSUE TITLE
Cards exiled with Asmodeus the Archfiend can be seen by the owner

### ISSUE THREAD

**Issue by alexander-novo** [magefree/mage#11968]
![image](https://github.com/magefree/mage/assets/11657716/95c2cefe-4b3c-40ba-877f-b696c66402fa)

[[Asmodeus the Archfiend]] replaces card draws with exiling face down. Notably, it does not say that anyone is allowed to view those cards. The gatherer rulings have this to say:

> If a card is exiled face-down and no player has been given permission to look at it, no player is allowed to look at it as long as it remains exiled face-down. _(2021-07-23)_

**Comment by JayDi85** [comment]
Part of #11881
