### ISSUE TITLE
BUG: Chaos Dragon opponent rolls count towards the controller's "Whenever you roll a die" triggers

### ISSUE THREAD

**Issue by Kasaimaru** [magefree/mage#11976]
Example: I have both Mr. House, President and CEO and Chaos Dragon on the battlefield, when I go to combat I should be only able to get one Mr. House trigger off of the Chaos Dragon, but instead I get a trigger for each of the rolls with results over 4
![image](https://github.com/magefree/mage/assets/92060437/52f45225-2ab1-4ae3-82ef-267612204ba4) ![image](https://github.com/magefree/mage/assets/92060437/da558fee-966d-440b-9579-fb4609dda6f5)

**Comment by xenohedron** [comment]
There's an existing comment in `DieRolledEvent`:

> The target ID is used to keep track of the distinction between the player who controls the ability that started the dice roll and the player who does the rolling. The only times this distinction matters is for Chaos Dragon and Ricochet.

So I think it's just the trigger for Mr. House needs to check target id not player id

maybe @jimga150 can confirm and fix as the original author

**Comment by jimga150** [comment]
Yeah, that makes sense. I'll get a PR in

**Comment by xenohedron** [comment]
fixed by #11993
