### ISSUE TITLE
Cant close AI games

### ISSUE THREAD

**Issue by Bluehazel4** [magefree/mage#11998]
Since the last up date games against the AI are unplayable.
Old games I have left will not close and the AI take ages to do anything.
They now don't play lands meaning I cant play against them, you can see they are even discarding lands instead of playing them.
How do I fix this.
![games not closed](https://github.com/magefree/mage/assets/164752211/52eb546e-5d9c-4bb8-b4b7-c9ce88642bec)
![not play lands](https://github.com/magefree/mage/assets/164752211/54cd248a-8f98-4f25-9650-68ae54ba25ac)

**Comment by JayDi85** [comment]
1. Try to select another deck for AI. Current deck can contains some ai buggy card, so AI can’t play it. It can be related to your deck too - try change it. I recommends to generate R and/or G decks for AI, don’t use B or U;
2. Make sure you use mad ai as player type, not draft or monte carlo
3. Try to change ai skill level to min value;
4. Make sure no errors in server logs windows (black screen);

**Comment by Bluehazel4** [comment]
I just tried all of these with no errors but the AI still decides to discards lands instead of playing them. I also have about 6 games open that I can watch full of AI not doing anything and no way to close them.

**Comment by JayDi85** [comment]
This is a forced discard at the end of the round too keep hand size, not an AI decision. So AI can’t do anything in your use case.

![IMG_0041](https://github.com/magefree/mage/assets/8344157/02b7cdb4-4595-4861-b683-b7742fe5553b)

4 days game long. Looks like game exit with critical error, so server can’t do anything with it.

Open launcher/xmage/mage-server and open in text editor mageserver.log file. Copy here latest logs or try to find any ERRROR and WARN messages.

**Comment by Bluehazel4** [comment]
ERROR 2024-03-20 22:11:24,333 org.h2.jdbc.JdbcSQLException: General error: "java.lang.IllegalStateException: Reading from nio:H:/MTG/xmage/mage-server/db/cards.h2.mv.db failed; file length -1 read length 384 at 162083 [1.4.197/1]"; SQL statement:
SELECT * FROM `expansion` WHERE `code` = ? LIMIT 1 [50000-197]

I found this error a few times

**Comment by JayDi85** [comment]
> file length -1 read length 384 at 162083

Server catch memory overflow. It can be:
- you play too long, try to restart server from a launcher;
- ai or buggy cards: go to launcher and increase memory usage for a server app (find and edit “xmx” param from 512 to 1000 or 2000);

**Comment by jeffwadsworth** [comment]
What AI are you using?  The MAD one should be your reliable one.

**Comment by JayDi85** [comment]
It’s about ai freeze, not gui. Related issue: #10197
