### ISSUE TITLE
Tournament decks submitted aren't validated.

### ISSUE THREAD

**Issue by Simown** [magefree/mage#1199]
When testing AI drafting I noticed that most of the decks the AI generates are submitted with < 40 cards. As far as I know all tournament decks all have to be limited legal with 40 cards minimum. Testing with human drafting has the same effect, you can submit a tournament deck with all the cards in the sideboard, and then lose when you draw from an empty deck.

**Comment by Simown** [comment]
Is there any other limits to limited decks apart from the size? I don't think the banned or restricted list is relevant for limited tournament decks.

**Comment by LevelX2** [comment]
If you use the test mode to start the server, the deck validation is inactivated.
Maybe this is the cause for your observervations.

**Comment by Simown** [comment]
Ok, I didn't know that, thanks. I'll double check and close the issue if it works with test mode off.

**Comment by Simown** [comment]
Deck validation works for humans with test mode off, so closing this now.

Deck building is generally a bit strange for AI and they can submit decks with less than 40 cards and create virtually unplayable decks. Part of a bigger issue I'm working on so I'll not raise a bug on it now.
