### ISSUE TITLE
Fail to Trigger Spellstutter Sprite

### ISSUE THREAD

**Issue by LegionedintheDamned** [magefree/mage#12024]
I checked 3 times - I can't see what might have stopped me here.  There is nothing preventing ETB effects.

![image](https://github.com/magefree/mage/assets/82664393/d3c73e6e-d708-4b81-a708-595f4be9f911)

**Comment by ssk97** [comment]
Looks correct to me. You have 1 faerie on the battlefield, there are no spells with MV 1 or less on the stack. No valid target for the ability.
