### ISSUE TITLE
BUG The ability of [[Kairi, the Swirling Sky]] copy created with [[The Ever-Changing 'Dane]] triggered but nothing happened

### ISSUE THREAD

**Issue by TommasoClancione** [magefree/mage#12030]
Title. I choose the "return to the hand" ability on Shelob and payed the 2 for the ward. 
Log atatched
[20240330_140914_Commander Free For All_1.pdf](https://github.com/magefree/mage/files/14812231/20240330_140914_Commander.Free.For.All_1.pdf)

**Comment by Susucre** [comment]
[[Kairi, the Swirling Sky]]
[[The Ever-Changing 'Dane]]

**Comment by Susucre** [comment]
[[Shelob, Child of Ungoliant]]

**Comment by Susucre** [comment]
Issue was with the custom targetter.
Fixed in 8a6b39c912f7d5f174e6351341aff1ead8dc447e
