### ISSUE TITLE
Basandra, Battle Seraph doesn't prevent casting spells during combat

### ISSUE THREAD

**Issue by ethanaward** [magefree/mage#12043]
![Screenshot 2024-04-01 215851](https://github.com/magefree/mage/assets/17013620/266255e6-c293-4062-9299-f8b105283192)

I was able to cast [[Shelter]] during the blockers phase while my opponent had [[Basandra, Battle Seraph]] in play.

**Comment by Cguy7777** [comment]
I believe I fixed this with #11997 a bit ago, but the current beta release doesn't have the fix yet.

**Comment by xenohedron** [comment]
That explains why I didn't see anything wrong with the code when I looked at master
