### ISSUE TITLE
Game draw when opponent concedes?

### ISSUE THREAD

**Issue by Badaro** [magefree/mage#1205]
Gamelog: http://pastebin.com/i1rEDdY5

I was playing a Legacy game. The opponent conceded, the game log listed the following sequence of messages, then considered the game a draw and proceeded to the 4th game in the match:
- FG_cas has conceded.
- badaro has lost the game.
- FG_cas has won the game.

23:29: Turn 8 FG_cas  (20 - 22)
23:29: FG_cas  draws a card
23:30: FG_cas plays Polluted Delta [b5c]
23:30: FG_cas attacks with 0 creatures
23:30: Turn 9 badaro (20 - 22)
23:30: Grim Monolith [57a] doesn't untap during your untap step.
23:30: Grim Monolith [2fe] doesn't untap during your untap step.
23:30: badaro draws a card
23:30: badaro attacks with 1 creature
23:30: FG_cas has conceded.
23:30: badaro has lost the game.
23:30: FG_cas has won the game

**Comment by LevelX2** [comment]
Other reports:
http://www.slightlymagic.net/forum/viewtopic.php?f=70&t=17549&p=184358#p184344

**Comment by LevelX2** [comment]
It's not sinmply to reproduce while conceding during a player casts a spell.
I guess the process of casting has to be in a specific state.
The conceded invalidates the ongoing cast and that leads to a rollback of the spell casting. That undoes the conceded state of the conceding player and after that the game is handled as a draw.

Solution should be: Don't rollback a concede or player lost state by the automatic rollbacks during spell casting.

**Comment by fireshoes** [comment]
Other reports:
http://www.slightlymagic.net/forum/viewtopic.php?f=70&t=17365&p=182117&hilit=conceded+draw#p182117
http://www.slightlymagic.net/forum/viewtopic.php?f=70&t=17295&p=181543&hilit=conceded+draw#p181543
http://www.slightlymagic.net/forum/viewtopic.php?f=70&t=16910&p=178062&hilit=conceded+draw#p178062
http://www.slightlymagic.net/forum/viewtopic.php?f=70&t=16358&p=170186&hilit=conceded+draw#p170186

**Comment by LevelX2** [comment]
We will see if this update will fix the issue. Not 100% sure about.

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.
