### ISSUE TITLE
Ring of Evos Isle doesn't give equipped creature hexproof

### ISSUE THREAD

**Issue by alexander-novo** [magefree/mage#12079]
![image](https://github.com/magefree/mage/assets/11657716/2c992f1a-9d7d-4aa1-8746-53782b864c9f)
![image](https://github.com/magefree/mage/assets/11657716/600764d6-1a59-447f-8c4f-44b3467d81b5)
![image](https://github.com/magefree/mage/assets/11657716/91e65923-4da9-46a4-be0d-4c5283c4d962)

As you can see, after activating [[Ring of Evos Isle]], my Obeka doesn't get hexproof.

**Comment by Susucre** [comment]
Uh, so apparently all the aura/equipment giving temporary ability to the attached creature with new GainAbilityAttachedEffect are not working.

I did reproduce the same issue with half (can assume the others are also bugged) of:
https://scryfall.com/search?q=o%3A%2F%3A.*%28enchanted%7Cequipped%29.*gains%2F&unique=cards&as=grid&order=name

**Comment by Susucre** [comment]
Well I think that boolean check on affectedObjectsSet is wrong?

![image](https://github.com/magefree/mage/assets/34709007/efa25e56-f9a6-4223-85ba-cd4b93894e82)

**Comment by xenohedron** [comment]
Related: #11907
