### ISSUE TITLE
[LCI] The Ojer cycle is allowing non-transforming cards to return on copy effect

### ISSUE THREAD

**Issue by Susucre** [magefree/mage#12070]
Those 5 cards: https://scryfall.com/search?q=o%3A%22tapped+and+transformed%22&unique=cards&as=grid [[Ojer Axonil]] incorrectly allow copies not transforming dfc to return.

Ruling on that:
> If a card that isn't a transforming double-faced card is a copy of Ojer Axonil, Deepest Might, it won't return to the battlefield when it dies. (2023-11-10)

**Comment by JayDi85** [comment]
I think it must be part of etb code: if something trying to move card to battlefield tranformed, but it not transformable then move must be canceled.

**Comment by Susucre** [comment]
https://yawgatog.com/resources/magic-rules/#R71214

The CR relevant section:
> 712.14a. If a [spell](https://yawgatog.com/resources/magic-rules/#spell) or [ability](https://yawgatog.com/resources/magic-rules/#ability) puts a [transforming double-faced card](https://yawgatog.com/resources/magic-rules/#transforming_double-faced_cards) onto the [battlefield](https://yawgatog.com/resources/magic-rules/#battlefield) "transformed" or "converted," it [enters the battlefield](https://yawgatog.com/resources/magic-rules/#enters_the_battlefield) with its back [face up](https://yawgatog.com/resources/magic-rules/#face_up). If a [player](https://yawgatog.com/resources/magic-rules/#player) is instructed to put a [card](https://yawgatog.com/resources/magic-rules/#card) that isn't a [transforming double-faced card](https://yawgatog.com/resources/magic-rules/#transforming_double-faced_cards) onto the [battlefield](https://yawgatog.com/resources/magic-rules/#battlefield) transformed or converted, that [card](https://yawgatog.com/resources/magic-rules/#card) stays in its current [zone](https://yawgatog.com/resources/magic-rules/#zone).

**Comment by Susucre** [comment]
Fixed by #12072
