### ISSUE TITLE
Sacrificing Verrak, Warped Sengir to an ability that also costs life to activate triggers Verrack when it shouldn't.

### ISSUE THREAD

**Issue by Tharkon** [magefree/mage#12089]
When [[Verrak, Warped Sengir]] is sacrificed to [[Razaketh, the Foulblooded]], Verrak's ability triggers.
I don't believe this should happen because the ability is not activated before Verrak is sacrificed and Verrak is not on the battlefield after it is sacrificed. So at no point is Verrak on the battlefield when the ability is activated.

**Comment by alexander-novo** [comment]
I can confirm that the way the rules are written, Verrak shouldn't trigger in this situation.

**Comment by JayDi85** [comment]
Must be fixed, related test: `test_MustNotTriggerOnDiscardCost`
