### ISSUE TITLE
Extract A Confession - the card is missing

### ISSUE THREAD

**Issue by Elthz** [magefree/mage#12091]
The card
https://scryfall.com/card/mkm/84/extract-a-confession
results implemented
https://github.com/magefree/mage/issues/12011

Is currently not showing up or missing from the client, no matter how I write or look up for it, it won't show:
![1](https://github.com/magefree/mage/assets/33559707/44900a23-a01f-495a-a53e-553cb497702d)
![3](https://github.com/magefree/mage/assets/33559707/16434da1-5ee1-4176-a3de-063709a72ff9)
![21](https://github.com/magefree/mage/assets/33559707/9ff8b622-07ef-4916-9205-986a1d3f684e)
![44](https://github.com/magefree/mage/assets/33559707/52a8736a-8006-4482-bd33-80f3d1a4e8f7)

**Comment by Susucre** [comment]
Cards from the new set will be there next release.
