### ISSUE TITLE
Room Joining Error

### ISSUE THREAD

**Issue by cchron1907** [magefree/mage#1209]
I have tried to join several Two Player Duel rooms (modern format) today and when I join the window only has me in it as if I was hosting the room. then a player joins and asks to start but I don't have the start button. I did join a booster draft and showed up on the list just fine. I didn't have any updates today so I'm not sure what changed...

**Comment by LevelX2** [comment]
No idea yet. The problem persists for you?

**Comment by cchron1907** [comment]
Had an update today. Looks like it works.
