### ISSUE TITLE
Refactor batched triggered abilities to expose which part of batch event made them trigger.

### ISSUE THREAD

**Issue by Susucre** [magefree/mage#12095]
So with [[Felix Five Boots]] in #12074, we have an issue of Felix incrementing the trigger count for batch events, where the part of the batch Felix cares about has no common part with the part the batch trigger cares about.

I suspect this might occur in a variety of situations, but for now the one I can illustrate the problem with is the following:
- PlayerA has Felix, an Elite Vanguard equipped with [[Umezawa's Jitte]].
- PlayerA attacks with its 2 creatures.
- PlayerB blocks the creature with Jitte, but the other is not blocked.
- A `DAMAGED_BATCH_FOR_ALL `is triggered with all creatures dealing damage. There is two events in it: Felix dealing damage to playerB, and Elite Vanguard dealing damage to the blocker (there is also the playerB's blocker damage, but irrelevant here)
- Jitte's trigger is checking the trigger -> there is the creature dealing damage in it. Jitte's trigger does trigger on the batched event.
- Felix sees the Jitte's triggering with the `DAMAGED_BATCH_FOR_ALL`, there is the event for Elite Vanguard's damage in it, so it is increased by Felix. This is where the problem is. 

So to solve the problem, I think we need to improve TriggeredEvents to expose which part of events are relevant to them when they do trigger. For non-batched events, this is trivial, if it did trigger, then the event is what made the trigger triggers.

For Batch events, it is a on a case-by-case basis. For instance Jitte is using `DealsCombatDamageEquippedTriggeredAbility`:
![image](https://github.com/magefree/mage/assets/34709007/5fd4da68-97e7-4c2f-a309-e2ca790ad90b)

Here the part of the batch that are relevant are quite explicit:
```java
Permanent sourcePermanent = getSourcePermanentOrLKI(game);
if (sourcePermanent == null || sourcePermanent.getAttachedTo() == null) {
    return false;
}
((DamagedBatchAllEvent) event)
                .getEvents()
                .stream()
                .filter(DamagedEvent::isCombatDamage)
                .filter(e -> e.getAttackerId().equals(sourcePermanent.getAttachedTo()))
```
                
So I would be in favor of separating checkTrigger in two:
```java
@Override
public boolean checkEventType(GameEvent event, Game game) {
    return event.getType() == GameEvent.EventType.DAMAGED_BATCH_FOR_ALL;
}

@Override
public Stream<GameEvent> filterEvent(GameEvent event, Game game) {
    Permanent sourcePermanent = getSourcePermanentOrLKI(game);
    if (sourcePermanent == null || sourcePermanent.getAttachedTo() == null) {
        return Stream.empty();
    }
    return ((DamagedBatchAllEvent) event)
            .getEvents()
            .stream()
            .filter(DamagedEvent::isCombatDamage)
            .filter(e -> e.getAttackerId().equals(sourcePermanent.getAttachedTo()))
}

@Override
public boolean checkTrigger(GameEvent event, Game game) {
    int amount = filterEvent(event, game)
            .mapToInt(GameEvent::getAmount)
            .sum();
    if (amount < 1) {
        return false;
    }
    this.getEffects().setValue("damage", amount);
    return true;
}
```

I think that would help us going forward, as we introduce more batch events and new cards with various `one or more` triggers are more and more frequent.

To go back on Felix, the filtering for Felix would call filterEvent of the original trigger to have the relevant part of the batch, then do its own filtering to decide if it triggers.

**Comment by JayDi85** [comment]
Can you make reproducible test for master with wrong triggers?

**Comment by Susucre** [comment]
I don't think the current trigger-caring cards can cause issue at the moment.
Need the Felix text, of "If a creature you control dealing combat damage to a player causes a triggered ability of a permanent you control to trigger, ", which is looking at specifically batchs.

**Comment by Susucre** [comment]
There might be, but it needs to be a combination of one of those:
https://scryfall.com/search?q=o%3A%22causes+a+triggered+ability%22
And a batch triggers that filters a batch event in an disjoint way.

I didn't find the Jitte+Felix example quickly, so maybe there are actual exemple with current cards.

**Comment by Susucre** [comment]
I think this should be an affected case (blinking wizard + artifact with [[Naban, Dean]] + [[Ingenious artificer]]:
![image](https://github.com/magefree/mage/assets/34709007/d0c0a8ce-15d1-4cac-bb99-fba95ed06127)

But Naban is bugged and not looking at batchs:
![image](https://github.com/magefree/mage/assets/34709007/0e7a1d6b-ea7d-4ced-ad81-e3931e02c49d)

I'll try to find another with non-bugged card.

**Comment by Susucre** [comment]
[[Ingenious artillerist]]

**Comment by Susucre** [comment]
I have not looked at all of them, but the move zones "If [...] causes a triggered ability of [...] to trigger," all seem to not work on batch move events.
So the refactor I propose is even more needed to rework those cards.

**Comment by xenohedron** [comment]
Interesting find. Is the bug only applicable to NUMBER_OF_TRIGGERS?

**Comment by Susucre** [comment]
> Interesting find. Is the bug only applicable to NUMBER_OF_TRIGGERS?

I do think so. This should be the only meta-trigger?
