### ISSUE TITLE
Rollback of turn has players who have conceded that turn rejoin the match.

### ISSUE THREAD

**Issue by fireshoes** [magefree/mage#1210]
Perhaps this is not a bug, but an annoyance. A player quit the game but didn't leave xmage (there is no option to close a multiplayer game window when you lose before the match is over). Another player on the turn cycle requested a rollback, which brought the conceded player back. When his turn came back around, we had to wait 10 minutes for him to time out.

**Comment by LevelX2** [comment]
I guess the fix from yesterday aa1eb354efd02f548056eeebe5442d97fa71e92a will fix that.

**Comment by drmDev** [comment]
Not sure if this is resolved or not?
