### ISSUE TITLE
Halvar, God of Battle wrongly attaches to protection permanents

### ISSUE THREAD

**Issue by PurpleCrowbar** [magefree/mage#12108]
When using [[Halvar, God of Battle]]'s triggered ability to attach an equipment / aura to a creature, if the creature being targeted has protection from an attribute possessed by the attachment (i.e., the aura is blue and the creature has protection from blue), the attachment will attach to the permanent and then immediately be moved to the graveyard during state-based actions (due to the protection). In reality the attachment shouldn't be moved at all in such a case, as protection prohibits the act of enchanting, which means it shouldn't move. See the rule below:
>303.4j. If an effect attempts to attach an Aura on the battlefield to an object or player it can't legally enchant, the Aura doesn't move.

This issue likewise applies to equipment.

**Comment by Susucre** [comment]
That check in Halvar code is flawed:
![image](https://github.com/magefree/mage/assets/34709007/f0e15903-9327-4946-83f7-e101587121e0)

Should call `Permanent::cantBeAttachedBy` instead.
For instance on creating Role tokens, the check is this:
![image](https://github.com/magefree/mage/assets/34709007/f996b7e3-3af5-497c-8df7-a0e492894351)
