### ISSUE TITLE
CMD (Commander 2011) named just "Commander"

### ISSUE THREAD

**Issue by PurpleCrowbar** [magefree/mage#12110]
In the card viewer (and in the code), Commander 2011 is named just "Commander", presumably due to it being the original supplementary set for the Commander format. As more Commander sets were printed, "Commander" (the set) became "Commander 2011", to remain in line with "Commander 2013", "Commander 2014", etc. Users looking for Commander 2011 cards in the Card Viewer will find nothing unless they select the set simply named "Commander". Is there any reason for the set being named this way or can it be changed?

**Comment by Susucre** [comment]
Agree we could rename it. Should not be a problem.
