### ISSUE TITLE
Saga rendering applies to back side of flip sagas

### ISSUE THREAD

**Issue by ssk97** [magefree/mage#12129]
The changes in #11762 look awesome, but for the NEO flip sagas the back side retains the saga-style rendering when it should be swapped back to normal card rendering.

**Comment by Susucre** [comment]
It that helps, there is no issue on looking at the back of the card when it's not transformed:

![image](https://github.com/magefree/mage/assets/34709007/299fb0e0-d0a7-4df2-a54b-e3f6bb20df23)
![image](https://github.com/magefree/mage/assets/34709007/ae0fc914-167b-45a2-b9b9-e6338d2b80a8)

But once it gets transformed, it looks like this:

![image](https://github.com/magefree/mage/assets/34709007/c687f4d5-dbff-4af5-89fe-ed77c32c9926)
