### ISSUE TITLE
Future Sight

### ISSUE THREAD

**Issue by tiera3** [magefree/mage#12126]
I had Future Sight on the battlefield.
My opponent destroyed my enchantment.
At my next turn, I was still able to play the land from the top of my library.
However the card wasn't mentioned as revealed at the start of turn.

**Comment by alexander-novo** [comment]
The window will remain open, showing the last revealed card. As you draw that card, you will still be able to click it to play it.

**Comment by tiera3** [comment]
Oh - my mistake. I knew the top two cards were both forests, because I had previously cast Brainstorm.
