### ISSUE TITLE
NPE in triggered abilities upon concede

### ISSUE THREAD

**Issue by xenohedron** [magefree/mage#12137]
Error was thrown right as my opponent conceded, so might have to do with them leaving game, may not be critical.

java.lang.NullPointerException
Server version: 1.4.52-V7-beta9 (build: 2024-04-16 23:12)
Stack trace:
mage.abilities.TriggeredAbilities.lambda$processingEnd$2(TriggeredAbilities.java:163)
java.util.stream.ReferencePipeline$11$1.accept(ReferencePipeline.java:439)
java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384)
java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
mage.abilities.TriggeredAbilities.processingEnd(TriggeredAbilities.java:166)
mage.abilities.TriggeredAbilities.checkTriggers(TriggeredAbilities.java:117)
mage.game.GameState.handleEvent(GameState.java:945)
mage.game.GameState.handleSimultaneousEvent(GameState.java:803)
mage.game.GameState.processAction(GameState.java:661)
mage.abilities.AbilityImpl.resolveMode(AbilityImpl.java:226)
mage.abilities.AbilityImpl.resolve(AbilityImpl.java:180)
mage.game.stack.StackAbility.resolve(StackAbility.java:84)
mage.game.GameImpl.resolve(GameImpl.java:1766)
mage.game.GameImpl.playPriority(GameImpl.java:1689)
mage.game.turn.Step.priority(Step.java:67)
mage.game.turn.Phase.playStep(Phase.java:205)
mage.game.turn.Phase.play(Phase.java:91)
mage.game.turn.Turn.play(Turn.java:137)
mage.game.GameImpl.playTurn(GameImpl.java:1131)
mage.game.GameImpl.play(GameImpl.java:1038)
mage.game.GameImpl.start(GameImpl.java:1014)
mage.server.game.GameWorker.call(GameWorker.java:34)
mage.server.game.GameWorker.call(GameWorker.java:15)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:750)

**Comment by JayDi85** [comment]
Fixed in a9372e93ff0d955ed88cb4e3ae11c6bf408ae887
