### ISSUE TITLE
Phyrexian Ingester dies when owner of exiled creature leaves game

### ISSUE THREAD

**Issue by Zorkony** [magefree/mage#1213]
I was playing a multiplayer game when an opponent left, followed by my phyrexian ingester dying (that player was the owner of the creature I exiled with it).
This isn't supposed to happen, right?

**Comment by fireshoes** [comment]
Well, if it actually died (goes to graveyard), that isn't supposed to happen. But it is supposed to leave the game when they do. http://blogs.magicjudges.org/rulestips/2012/08/multiplayer-monday-what-happens-when-a-player-leaves-the-game/

**Comment by Zerrisx** [comment]
More specifically, the buff from their exiled creature should leave, which - if your creature had taken 3 or more damage - would kill it.  I'm guessing this is what happened, since I can't otherwise reproduce this.
