### ISSUE TITLE
[BUG] Xanathar, Guild Kingpin does not allow lands to be played from opponent's deck

### ISSUE THREAD

**Issue by Athanar90** [magefree/mage#12133]
Xanathar, Guild Kingpin's ability allows a player to select an opponent and play cards off the top of their deck. In practice, lands are unable to be played even though the card does not specify that only spells are allowed to be played in this manner.

Displayed in screenshot: Top card, Blooming Marsh, is unplayable. In hand, Crumbling Necropolis can be played, showing the player has a land drop remaining for the turn.

(Unrelated: Sinister Waltz being unplayable is correct due to lack of creatures in graveyard.)
![image](https://github.com/magefree/mage/assets/156782362/eac846d0-4d13-4eed-86ca-77988011a229)

**Comment by Susucre** [comment]
[[xanathar kingpin]]

**Comment by Susucre** [comment]
From a quick look this is not a direct regression from the 'you may play / you may cast' split.
