### ISSUE TITLE
Set maven-assembly-plugin version in the pom.xml

### ISSUE THREAD

**Issue by Susucre** [magefree/mage#12140]
So for the alpha server I'm setting up, I am currently trying to build and package xmage from a docker.

I figured most of the things out, but I got an error on "mvn assembly:assembly" for both Mage.Client & Mage.Server:
![image](https://github.com/magefree/mage/assets/34709007/bb72be52-90f7-4301-ad23-246a536271a2)

I checked my dev computer mvn version of `maven-assembly-plugin` is `2.2-beta-5`, and I've not issue with the `assembly` goal with that one. And once I've set it up to that version in the Docker build in both `pom.xml`, there was no issue anymore and I was producing the expected .zip out of the build-and-package.pl script.

What is the most appropriate version of `maven-assembly-plugin`, I am really no expert of maven builds, should we set the version to a working one in the `pom.xml` files, or maybe support the latest `maven-assembly-plugin`?

**Comment by JayDi85** [comment]
More details in #11599. Use assembly:single task instead.

**Comment by Susucre** [comment]
Alright, so the perl files in the repo are the ones being outdated then.

**Comment by JayDi85** [comment]
Yes, perl scripts are very old. 80% of that scripts are outdated and un-used (maybe @theelk801 uses some of it for issues generation).

last time I used perl scripts for de-server releases (build, version bump in pom files and new cards list gen).

There are makefile for “modern way” builds, so you can try to use it: https://github.com/magefree/mage/blob/master/Makefile

**Comment by theelk801** [comment]
the only perl script I use is the card generation one, the rest don't matter to me

**Comment by Susucre** [comment]
Uhm with `assembly:single` there are no .jar for Mage.Client and Mage.Server.
![image](https://github.com/magefree/mage/assets/34709007/70296a6d-2838-4ffb-9fed-2d622a261586)

I suspect I need to tweak the build-and-package.pl a little more to use its produced .jar for the alpha server.

**Comment by Susucre** [comment]
I'll try from the Makefile. Thanks for the help.

**Comment by Susucre** [comment]
Alright, that should works, was missing "package" in those commands too.
![image](https://github.com/magefree/mage/assets/34709007/ff05a588-0217-47f0-b9b6-8911fde66b30)

I'll try to start the alpha server with that build, just to confirm.
By the way my aim for this whole ordeal is a nightly alpha server, so need to make sure I can automate the build & package the whole way.

**Comment by Susucre** [comment]
Alright, I did succeed.
![image](https://github.com/magefree/mage/assets/34709007/d7dfce8e-e3eb-47ab-ad52-a9c518810533)

So I'll change the .pl build-and-package to call `mvn package assembly:single -DskipTests` instead of `mvn assembly:assembly`.
