### ISSUE TITLE
AI response to [[Disciple of Caelus Nin]] is to choose zero permanents

### ISSUE THREAD

**Issue by ShadyV** [magefree/mage#12151]
In response to the trigger of [[Disciple of Caelus Nin]] , the AI chooses zero permanents. Therefore, all of its permanents phase out. Are we able to at least make the AI select 5 random permanents it owns (or select all if total is 5 or less)? Thank you

**Comment by JayDi85** [comment]
Looks like card bugged and ask only controller without other players:

![shot_240420_051438](https://github.com/magefree/mage/assets/8344157/2817a9d2-99a5-4268-b272-85ea6220058e)
