### ISSUE TITLE
Razia, Boros Archangel

### ISSUE THREAD

**Issue by fireshoes** [magefree/mage#1216]
I was looking at implementing Carom and Captain's Manuever, and looked at Razia, Boros Archangel as a similar effect, but I noticed that Razia is coded to prevent the damage and then deal that damage to the other target creature. It is not actually a prevention effect though. The damage is redirected instead, so cards that says damage can't be prevented should have no effect (e.g. Skullcrack).

**Comment by LoneFox78** [comment]
At least Harm's Way and en-Kor creatures also have the same problem. Probably there are others.
In general, damage redirection effects need refactoring. There is a RedirectionEffect class, but it doesn't seem to be very useful on its own. Everything that uses it, extends it.
