### ISSUE TITLE
 Legate Lanius, Caesar's Ace not asking for correct number of creatures to be sacrificed.

### ISSUE THREAD

**Issue by zoot4life** [magefree/mage#12178]
Math is not calculating correctly for sacrificing creatures. Card asks for a tenth but there were 2 instances in-game where I had less than 10 creatures and the game asked for 2 creatures to be sac'd. the following turn Legate Lanius, Caesar's Ace entered again and i had 2 creatures and was prompted to sac 2. I would need to have 20 creatures to have to sacrifice 2 creatures. Any number less than 10 creatures should result in only 1 creature needing to be sacrificed.

**Comment by xenohedron** [comment]
@ssk97

**Comment by ssk97** [comment]
Oops, it's counting all the creatures on the battlefield, not just of the player. Will fix.
