### ISSUE TITLE
IllegalStateException: MDFC in wrong zone

### ISSUE THREAD

**Issue by zoot4life** [magefree/mage#12176]
this error popped up when resolving a deluvian primordial that was targeting akroma's vengeance and valuakut awakening. vengeance resolved properly but when resolving the awaking, i selected cards to put on bottom and then this popped up.

Game error occurred: 

java.lang.IllegalStateException: Wrong code usage: MDF card uses wrong zones - Valakut Awakening [e9c] (ModalDoubleFacedCard -> ValakutAwakening)
* main zone: exile zone
* left side: need exile zone, actual GRAVEYARD
* right side: need exile zone, actual GRAVEYARD
Server version: 1.4.52-V7-beta9 (build: 2024-04-16 23:12)
Stack trace:
mage.cards.ModalDoubleFacedCard.checkGoodZones(ModalDoubleFacedCard.java:187)
mage.cards.ModalDoubleFacedCard.setSideZones(ModalDoubleFacedCard.java:113)
mage.cards.ModalDoubleFacedCard.moveToZone(ModalDoubleFacedCard.java:119)
mage.cards.ModalDoubleFacedCardHalfImpl.moveToZone(ModalDoubleFacedCardHalfImpl.java:54)
mage.cards.CardImpl.moveToZone(CardImpl.java:403)
mage.players.PlayerImpl.moveCardToGraveyardWithInfo(PlayerImpl.java:4955)
mage.players.PlayerImpl.moveCardsToGraveyardWithInfo(PlayerImpl.java:4939)
mage.players.PlayerImpl.moveCards(PlayerImpl.java:4715)
mage.players.PlayerImpl.moveCards(PlayerImpl.java:4690)
mage.players.PlayerImpl.moveCards(PlayerImpl.java:4681)
mage.game.stack.Spell.resolve(Spell.java:319)
mage.game.GameImpl.resolve(GameImpl.java:1766)
mage.game.GameImpl.playPriority(GameImpl.java:1689)
mage.game.turn.Step.priority(Step.java:67)
mage.game.turn.Phase.playStep(Phase.java:205)
mage.game.turn.Phase.play(Phase.java:91)
mage.game.turn.Turn.play(Turn.java:137)
mage.game.GameImpl.playTurn(GameImpl.java:1131)
mage.game.GameImpl.play(GameImpl.java:1038)
mage.game.GameImpl.start(GameImpl.java:1014)
mage.server.game.GameWorker.call(GameWorker.java:34)
mage.server.game.GameWorker.call(GameWorker.java:15)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:750)

**Comment by Susucre** [comment]
[[deluvian primordial]]

**Comment by Susucre** [comment]
[[Diluvian Primordial]]
