### ISSUE TITLE
ratcatcher is missing

### ISSUE THREAD

**Issue by pseiler** [magefree/mage#1218]
Hi xmage developers, 

I love your client but I miss a card. It's the ratcatcher from Dissension Block.
Could please implement it. It's a tutor card to search for a rat card in your deck,
http://magiccards.info/di/en/52.html

Thank you

**Comment by jeffwadsworth** [comment]
Please make card requests at this website:

http://www.slightlymagic.net/forum/viewtopic.php?f=70&t=4554&start=330

Thanks.

**Comment by pseiler** [comment]
Thank you I will do it. I close it
