### ISSUE TITLE
Kaya Spirits' Justice

### ISSUE THREAD

**Issue by LegionedintheDamned** [magefree/mage#12193]
Morning,
Was playtesting.  I think based on my read that Kaya's static ability should only allow me to choose from my own creatures.  However, in using her -2 it is allowing me to choose anything I exiled of my opponents.
![image](https://github.com/magefree/mage/assets/82664393/20ec8bfb-0d5f-4ead-8236-0ca386f8b95e)

**Comment by Susucre** [comment]
Yup, noticed that bug when reworking the batch triggers and fixed it in a not-yet-merged PR #12173
