### ISSUE TITLE
Creatures sacrificed  don't trigger their own death triggers

### ISSUE THREAD

**Issue by alexander-novo** [magefree/mage#12195]
[[Industrial Advancement]]. I've noticed it several times. Here's an example of a log:

![image](https://github.com/magefree/mage/assets/11657716/d4f9fccb-4196-4a09-9b66-c24ec08a76b8)

I sacrificed my [[Junji, the Midnight Sky]] and its death trigger did not trigger. Here's a pic of the board state:

![image](https://github.com/magefree/mage/assets/11657716/443b8e4c-abf4-4982-aed6-db0a4b918ace)

**Comment by alexander-novo** [comment]
Another example:

![image](https://github.com/magefree/mage/assets/11657716/a6cb8cf7-c2e1-40c6-b984-8e2e627cf3d6)


![image](https://github.com/magefree/mage/assets/11657716/29066bf0-ce05-42cd-bf36-81c6588378fb)

Kogla had undying and no counters, but undying didn't trigger,

**Comment by alexander-novo** [comment]
Actually this might just be a general problem with sacrifice. Here's another log:

![image](https://github.com/magefree/mage/assets/11657716/03c01021-1f37-45de-8bb4-b5f5e94b1e07)

Here, I sacrifice Atsushi with [[Vivien on the Hunt]]'s +2 ability, and it doesn't activate Atsushi's death trigger.

**Comment by alexander-novo** [comment]
Sacrificing with [[Evolutionary Leap]] seems to work fine, though...

**Comment by alexander-novo** [comment]
![image](https://github.com/magefree/mage/assets/11657716/f4da04fb-83d5-4238-abb6-973846907054)

It seems it's only missing the triggers on the sacrificed permanent - in this example, The Skullspore Nexus triggers from the sacrifice, but not Protean Hulk itself.

**Comment by JayDi85** [comment]
1. Is it regression from last updates?
2. Is it affect cards with multiple modes only?

**Comment by alexander-novo** [comment]
> 1. Is it regression from last updates?
> 
>     2. Is it affect cards with multiple modes only?

It must be a regression... there's no way this has been broken for very long. Also it's not multiple modes - cards like [[Protean Hulk]] don't work and also cards with undying.

**Comment by alexander-novo** [comment]
Actually this may not be a regression...

I've tested on 229e8d3 and it also had the bug. Let me go back further

**Comment by sebastiandine** [comment]
I am also having this issue when sacrificing [[Su-Chi]] with [[Sage of Lat-Nam]]. I do not get the mana from Su-Chi in the pool.

**Comment by Susucre** [comment]
Couldn't reproduce the bug with the test suite (added two tests in 907ac5c3, each one not failing on 10k attempts)

It is either:
- Related to a part of the code (GUI, AI), that the test suite doesn't use.
- Has some condition to happen. (a card/effect, or maybe enough triggers overall for a weird race condition bug)

**Comment by JayDi85** [comment]
@Susucre can be realted to zcc too (same tests, but make blinks first);

**Comment by Susucre** [comment]
> @Susucre can be related to zcc too (same tests, but make blinks first);

Was worth a try, but not that either: 02f19d9

**Comment by xenohedron** [comment]
Can also try in unit test, add to hand and cast, rather than add to battlefield

**Comment by Susucre** [comment]
> Can also try in unit test, add to hand and cast, rather than add to battlefield

No replication either (4d076058bc7). I really think there is something outside of the pair `DiesTriggeredAbility`/`SacrificeTargetCost` that we are missing there.

**Comment by xenohedron** [comment]
I speculate it is related to isInUsableZone and short living lki

**Comment by JayDi85** [comment]
> I speculate it is related to isInUsableZone and short living lki

Then put on stack some spells like bolt and exec same test commands after it (without full stack resolve).

**Comment by Susucre** [comment]
No luck either. I'm not around to continue investigating until next week at the earliest.
One of you can try to find the cause from there. I don't have any clue, but feel like it is outside the Test Suite capabilities to replicate (unless we are missing a third card messing up the trigger somehow.).

**Comment by JayDi85** [comment]
Added reproducible test by e3ae00f69695fcafcf0e0ee132273072b6eb04a9. Real reason was in short LKI and move to battlefield code:

![shot_240508_063013](https://github.com/magefree/mage/assets/8344157/1a0aa6c4-780d-4ddb-881c-c3f4ec006eea)

Nothing to do with it until move or dies logic rework. Maybe I'll look at it again later.

P.S. call `processAction` in sacrifice code is not a real fix :)

**Comment by JayDi85** [comment]
As idea to try:

1 - It's very hard to move ApplyEffects/ProcessActions code from move to battlefield to effects/cards like other multi steps effect does (move to battlefield is a most used command and require changes in 100500 files);

2 - It's require less effort by still hard to add process action to each sacrifice and other related effects (dies trigger depends on any zoves to graveyard, not sacrifice only);

3 - Most perspective: replace short living LKI logic by zone change counter logic (ZCC) -- shortLKI used in dies triggers only, so it's can require much less changes and checks.
![shot_240508_064951](https://github.com/magefree/mage/assets/8344157/58b2c7c8-00c8-479e-abb1-ae9c95cf596a)
Only one global usage can be a problem and need to research:
![shot_240508_070429](https://github.com/magefree/mage/assets/8344157/4affd6fa-d9da-4355-a563-f01be7aa2387)

**Comment by alexander-novo** [comment]
Great work finding the root cause

**Comment by xenohedron** [comment]
I agree that the best solution is to remove the short living LKI logic and replace with standard ZCC logic. "Short Living LKI" has always sounded like a hack/workaround to me.
