### ISSUE TITLE
Allow display of SubAbilities on the same line as the main Effect.

### ISSUE THREAD

**Issue by Susucre** [magefree/mage#12208]
Split from #12205 

It should be possible for SubAbilities to display they rules on the same line as the main Ability, and have no line break between them:

![327101837-5a12b0b5-bbd5-4ca3-a7c4-a7290defe15c](https://github.com/magefree/mage/assets/34709007/82f9f991-9769-4607-a855-b87f5815f5f6)

[[Magma Pummeler]]

**Comment by JayDi85** [comment]
Nope, that’s wrong usage of subabilities. I’ll publish review later for original PR (related to subs, reflexive and other problems).
