### ISSUE TITLE
Blood Baron of Vizkopa only checks one opponent.

### ISSUE THREAD

**Issue by Tharkon** [magefree/mage#12204]
In a four-player game I noticed [Blood Baron of Vizkopa] did not buff itself even though one of the opponents had 6 life and the controller had 60 life. A quick scan of the code makes me think that the code returns false as soon as it determines that the first player in range has 11 or more life, or even if that player is not an opponent, like in a team game (in case those ever become available on XMage), without checking other opponents.

**Comment by Susucre** [comment]
[[Blood Baron of Vizkopa]]
