### ISSUE TITLE
fix HELIOS One and Chthonian Nightmare

### ISSUE THREAD

**Issue by xenohedron** [magefree/mage#12217]
ref:
* 6f5eb8788d1006c138f51c699e3a40f903b67726
* 36da47a64fb3228aec6928e9cfc068ecb55c9cfe
* ab99cfe1fddf15f127900ee6fce6cb44088bd0ab
* a2881362c100e574c574ec69e278a84930ff8606

Looks like the energy cost is not properly implemented as a variable cost. Need to make new `PayVariableEnergyCost` like `PayVariableLoyaltyCost`

**Comment by Susucre** [comment]
I don't want to work on that atm. You can just remove both cards as they are now entirely broken with your changes.
I'll use my version (not correct, I don't disagree on that) on alpha.

**Comment by JayDi85** [comment]
It's not fixed yet due tests comments -- not playable.

**Comment by Susucre** [comment]
This is the exact same as when you have a [[Deepfire Elemental]], there is one artifact of mana value 2 on the board, and you only have 3 mana available.

The ability will look like it is playable, but you can't actually activate it (X=0 or X=1 there is no valid target after adjustment, X=2 you can't pay, X>2 there is no target)

![image](https://github.com/magefree/mage/assets/34709007/0966a653-9ad3-42cd-b1a2-995f52fb01f3)

It is not "not playable". The UI could be improved.

**Comment by JayDi85** [comment]
ok, I see your problem: that’s activated ability has x cost and x targets. After X announce by bad value — no more valid X targets exists and activation process canceled by rollback. That’s correct behavior, nothing to do with: no valid targets, no spell activation.

Test can’t process rollback cause the last one will restore full data, including declared choices. That’s why it raise error on unused choice (it’s used, but rollbacked and restored). It’s a test framework limit, nothing to do with it.
