### ISSUE TITLE
Kinsbaile Borderguard

### ISSUE THREAD

**Issue by Qaeron** [magefree/mage#1221]
It has disappeared or has never been in the card database.

**Comment by jeffwadsworth** [comment]
It is there.



On Aug 23, 2015, at 8:46 PM, Qaeron <notifications@github.com<mailto:notifications@github.com>> wrote:


It has disappeared or has never been in the card database.

**Comment by Qaeron** [comment]
![asd](https://cloud.githubusercontent.com/assets/13936506/9431693/1665ea88-4a17-11e5-8f8d-06494c58f023.png)

Not here.

**Comment by jeffwadsworth** [comment]
No one has coded it yet.  So, it is not in the code base.  But it is in the card database site.

Sent from my iPad

On Aug 23, 2015, at 9:18 PM, Qaeron <notifications@github.com<mailto:notifications@github.com>> wrote:


[asd]<https://na01.safelinks.protection.outlook.com/?url=https%3a%2f%2fcloud.githubusercontent.com%2fassets%2f13936506%2f9431693%2f1665ea88-4a17-11e5-8f8d-06494c58f023.png&data=01%7c01%7cjeff%40delmarus.com%7cbaf3cfc6aec746e85aee08d2ac2a445f%7cec3c1d92de274cedb931a0694c170315%7c0&sdata=PcxrbkJRgDFYaE35BmSIArJ2BHIzUmba%2bvFz1f4XajY%3d>

Not here.

**Comment by Qaeron** [comment]
Oops, sorry then. The technical words just confuse me ^^ My point is: when you try to find him in the Deck Editor or Collection Viewer part of XMage, it doesn't show up in my case. Wanted to know if it's the same for all or just for me.

**Comment by jeffwadsworth** [comment]
A card must be coded for it to show up in the game client.  In the distant past, I believe the card would show up as "unimplemented" in the game client.  No longer the case.

Sent from my iPad

On Aug 23, 2015, at 9:26 PM, Qaeron <notifications@github.com<mailto:notifications@github.com>> wrote:


Oops, sorry then. The technical words just confuse me ^^ My point is: when you try to find him in the Deck Editor or Collection Viewer part of XMage, it doesn't show up in my case. Wanted to know if it's the same for all or just for me.
