### ISSUE TITLE
Displaced Dinosaurs bug?

### ISSUE THREAD

**Issue by catman123456** [magefree/mage#12219]
When my  equipment turned into a dinosaur by [[Displaced Dinosaurs]] I can't equip the to any creature. 

![image](https://github.com/magefree/mage/assets/64045003/e73e0405-8592-4b5f-96f6-55080e0feb29)

**Comment by Susucre** [comment]
I think a Creature Equipment can not be equipped. Let me find the exact CR.

**Comment by Susucre** [comment]
> 301.5c. An [Equipment](https://yawgatog.com/resources/magic-rules/#equipment) that's also a [creature](https://yawgatog.com/resources/magic-rules/#creature) can't [equip](https://yawgatog.com/resources/magic-rules/#equip) a [creature](https://yawgatog.com/resources/magic-rules/#creature) [unless](https://yawgatog.com/resources/magic-rules/#unless) that [Equipment](https://yawgatog.com/resources/magic-rules/#equipment) has [reconfigure](https://yawgatog.com/resources/magic-rules/#reconfigure) (see rule [702.151](https://yawgatog.com/resources/magic-rules/#R702151), "[Reconfigure](https://yawgatog.com/resources/magic-rules/#reconfigure)"). An [Equipment](https://yawgatog.com/resources/magic-rules/#equipment) that loses the [subtype](https://yawgatog.com/resources/magic-rules/#subtype) "[Equipment](https://yawgatog.com/resources/magic-rules/#equipment)" can't [equip](https://yawgatog.com/resources/magic-rules/#equip) a [creature](https://yawgatog.com/resources/magic-rules/#creature). An [Equipment](https://yawgatog.com/resources/magic-rules/#equipment) can't [equip](https://yawgatog.com/resources/magic-rules/#equip) itself. An [Equipment](https://yawgatog.com/resources/magic-rules/#equipment) that [equips](https://yawgatog.com/resources/magic-rules/#equip) an illegal or nonexistent [permanent](https://yawgatog.com/resources/magic-rules/#permanent) [becomes](https://yawgatog.com/resources/magic-rules/#becomes) unattached from that [permanent](https://yawgatog.com/resources/magic-rules/#permanent) but remains on the [battlefield](https://yawgatog.com/resources/magic-rules/#battlefield). (This is a [state-based action](https://yawgatog.com/resources/magic-rules/#state-based_actions). See rule [704.](https://yawgatog.com/resources/magic-rules/#R704)) An [Equipment](https://yawgatog.com/resources/magic-rules/#equipment) can't [equip](https://yawgatog.com/resources/magic-rules/#equip) more than one [creature](https://yawgatog.com/resources/magic-rules/#creature). If a [spell](https://yawgatog.com/resources/magic-rules/#spell) or [ability](https://yawgatog.com/resources/magic-rules/#ability) would cause an [Equipment](https://yawgatog.com/resources/magic-rules/#equipment) to [equip](https://yawgatog.com/resources/magic-rules/#equip) more than one [creature](https://yawgatog.com/resources/magic-rules/#creature), the [Equipment](https://yawgatog.com/resources/magic-rules/#equipment)'s [controller](https://yawgatog.com/resources/magic-rules/#control_controller) chooses which [creature](https://yawgatog.com/resources/magic-rules/#creature) it [equips](https://yawgatog.com/resources/magic-rules/#equip).
