### ISSUE TITLE
The defending player does not get priority after blockers are declared but before damage

### ISSUE THREAD

**Issue by BijanT** [magefree/mage#1222]
After blockers are declared, if the active player does not play any spells or activate any abilities, the defending player will not get priority and the game will go to combat damage.

**Comment by emerald000** [comment]
I assume you had one of the stop options (F keys or buttons to the bottom right) activated. Their purpose is to automatically skip priority until a certain point. If you wish to do something in a certain phase, you will have to disable them.

**Comment by BijanT** [comment]
Oh. Sorry about this post then.
