### ISSUE TITLE
Magar of the Magic Strings is not implemented

### ISSUE THREAD

**Issue by Balagog** [magefree/mage#12234]
Magar of the magic strings is a commander legal card and it is not implemented, there are cards with similar effects implemented on the software like the chipher cards

**Comment by Grath** [comment]
Face-down cards require a substantial rework, and I believe it is difficult or unwise to implement Magar until the face-down rework is done (or at the earliest, doing it as part of that rework.)

**Comment by JayDi85** [comment]
[[Magar of the Magic Strings]]

**Comment by JayDi85** [comment]
It's un-set's card (experimental set without official rules support). BUT there is same card from WHO set: [[Cyber Conversion]] -- I think game engine must support gain abilities for face down permanents:

> Each creature turned face down this way or put onto the battlefield this way is a 2/2 Cyberman artifact creature with no name and no color. (2023-10-13)

> If, for any reason, the face-down creature is turned face up, the effect making it a Cyberman ends. It will be whatever is printed on the card. (2023-10-13)

**Comment by Susucre** [comment]
> experimental set without official rules support

That is incorrect. Some of Unfinity has CR support and is legal in legacy/vintage/commander.

**Comment by JayDi85** [comment]
There are related PR #10797 from @theelk801 for "cyber" cards (see above). Not sure is it actual/ready or not.

**Comment by Balagog** [comment]
> It's un-set's card (experimental set without official rules support). BUT there is same card from WHO set: [[Cyber Conversion]] -- I think game engine must support gain abilities for face down permanents:
> 
> > Each creature turned face down this way or put onto the battlefield this way is a 2/2 Cyberman artifact creature with no name and no color. (2023-10-13)
> 
> > If, for any reason, the face-down creature is turned face up, the effect making it a Cyberman ends. It will be whatever is printed on the card. (2023-10-13)

Magar have as much official rule support as name sticker goblin, comet (dog planeswalker), saw in half

**Comment by theelk801** [comment]
well it sounds like you won't have any trouble implementing it yourself then

**Comment by xenohedron** [comment]
Yeah those manual face down creature effects are a hacky mess right now.

Anyway I'm closing this, we already have a set tracking for Unfinity at #8491
