### ISSUE TITLE
Fight or Flight separates all creatures instead of just the active player's.

### ISSUE THREAD

**Issue by Tharkon** [magefree/mage#12245]
With [Fight or Flight] on the battlefield during each opponents turn I have to separate all creatures into two piles including creatures not controlled by the active player. The piles as I select them also appear to that player as I select them, including creatures they don't own.
Any creatures in the chosen pile that are not controlled by the active player of course still can't attack as normal so there is not a big issue in normal play with human players except that it looks really weird. But AI players really trip up over it, choosing piles that only contain their opponents creatures.

**Comment by Svyatoslav28597** [comment]
I may be wrong, but I think thats a general problem with "two piles" cards
Do or Die, another card from Invasion also separates all creatures instead of target player ones

**Comment by xenohedron** [comment]
Report if any other cards have same bug. It's copy-pasted code, not shared class.

**Comment by Tharkon** [comment]
You already know about [Stand or Fall], which actually doesn't even have the correct text in the tooltip.
It also instead of only allowing the chosen pile to block it disallows the unchosen pile to block, which may be a relevant difference with control-changing effects or creatures entering the battlefield after resolution, the latter of which is not that uncommon. Any creatures controlled by the active player upon resolution of Stand or Fall's triggered ability and any creatures that enter the battlefield after that resolution, should also be unable to block for the rest of the turn even if they weren't in any of the piles.

This last part is also true for Fight or Flight, any creatures not in any piles, should be unable to attack.

Perhaps some effect similar to what is used in Festival but that can be overwritten by specific CanAttackEffects.
Or have the "Festival-effect" have a predicate to be in one of the piles.

I also tested [Bend or Break], [Make an Example] and [Whims of the Fates], and those seem to work fine.

**Comment by xenohedron** [comment]
Good catch. Fixed in ee9bb3b8 and 6fd6417d
