### ISSUE TITLE
Roiling Terrain doesn't work

### ISSUE THREAD

**Issue by lsd1991** [magefree/mage#1225]
When this card should have dealt 1 damage per land in the opponent's graveyard, it showed this error instead:
>An error has occurred on the MAGE server. Your last action will be rollbacked.
>Game exception occurred: java.lang.IllegalArgumentException: The provided sourceId is not connected to an object in the game

**Comment by nigelzor** [comment]
This was fixed in e5c667cca995c23a17451847eafae5fbd5f3b520
