### ISSUE TITLE
Marchesa, the Black Rose Commander

### ISSUE THREAD

**Issue by Stopsl** [magefree/mage#1226]
Hey guys i´m new in here so i dont know if you can help me or if i´m doin this right! 

On xMage i uplaoded my Marches, the Black Rose commander deck. But when i try to play there always comes an errror that i got an invalid deck. Marches, the Black Rose:Too many:2 (thats the error message!!!)

pls Help

Stopsl

**Comment by LevelX2** [comment]
Sounds like you have Marches twice in your deck. Maybe in maindeck and in the sideboard?

http://www.slightlymagic.net/forum/viewtopic.php?f=70&t=13632#p180219

**Comment by Stopsl** [comment]
Yes that was the Problem. Thx a lot!!
