### ISSUE TITLE
Transmutation Font causes a crash + rollback

### ISSUE THREAD

**Issue by Dualitas1** [magefree/mage#12301]
Attempting to use the first effect of transmutation font (create one of 3 tokens) causes a crash and a rollback. 
The other effect (3 mana, tap, sacrifice 3 different tokens) works fine.

<img width="548" alt="Screenshot 2024-05-26 at 13 52 54" src="https://github.com/magefree/mage/assets/170868586/85b632a4-a930-4f9a-aec9-9b7c86dad7e3">

**Comment by Susucre** [comment]
I think that one has already been resolved, and will work next Beta release.
https://github.com/magefree/mage/commit/095e481560b8b7b98d44ef906c816f888ec4a84d

**Comment by Dualitas1** [comment]
Ah, sorry, I didn't see that. Thank you!
Should I just close this issue?

**Comment by Susucre** [comment]
> Ah, sorry, I didn't see that.

Don't worry, it is better to have redundant bugs reports than having no reports.
