### ISSUE TITLE
PlayerView must use client side objects (miss counters field)

### ISSUE THREAD

**Issue by JayDi85** [magefree/mage#12315]
Client side data must not contains a server side objects

Wrong usage:
![shot_240527_225233](https://github.com/magefree/mage/assets/8344157/9230651b-a42f-4ff8-b067-8ce171b7ee82)

Good usage:
![shot_240527_225307](https://github.com/magefree/mage/assets/8344157/40b1f60e-1a04-442c-aa35-2f643c492e7f)

**Comment by Susucre** [comment]
If you want I can do that in the Izzet Generatorium, since the client-side view does exist for cards.
