### ISSUE TITLE
Transmutation Font

### ISSUE THREAD

**Issue by Jasuan** [magefree/mage#12311]
Game error occurred: 

java.lang.IllegalArgumentException: Can't use KeySet as param, use new LinkedHashSet<>(data.keySet()) instead
Server version: 1.4.52-V7-beta9 (build: 2024-04-16 23:12)
Stack trace:
mage.util.CardUtil.checkSetParamForSerializationCompatibility(CardUtil.java:2116)
mage.choices.ChoiceImpl.setChoices(ChoiceImpl.java:118)
mage.cards.t.TransmutationFontEffect.apply(TransmutationFont.java:98)
mage.abilities.AbilityImpl.resolveMode(AbilityImpl.java:193)
mage.abilities.AbilityImpl.resolve(AbilityImpl.java:180)
mage.game.stack.StackAbility.resolve(StackAbility.java:84)
mage.game.GameImpl.resolve(GameImpl.java:1766)
mage.game.GameImpl.playPriority(GameImpl.java:1689)
mage.game.turn.Step.priority(Step.java:67)
mage.game.turn.Phase.playStep(Phase.java:205)
mage.game.turn.Phase.play(Phase.java:91)
mage.game.turn.Turn.play(Turn.java:137)
mage.game.GameImpl.playTurn(GameImpl.java:1131)
mage.game.GameImpl.play(GameImpl.java:1038)
mage.game.GameImpl.start(GameImpl.java:1014)
mage.server.game.GameWorker.call(GameWorker.java:34)
mage.server.game.GameWorker.call(GameWorker.java:15)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:750)

**Comment by Susucre** [comment]
Already fixed, will be there next release. 
#12301
