### ISSUE TITLE
Niv-Mizzet, Guildpact doesn't gain life

### ISSUE THREAD

**Issue by TakeHeedStruggler** [magefree/mage#12329]
Upon dealing damage to a player with Niv-Mizzet, Guildpact, its ability triggers normally. Once it resolves, though, it deals X damage to any target and draws target player X cards, but it doesn't gain you X life.

**Comment by Susucre** [comment]
[[niv mizzet guildpact]]

**Comment by Susucre** [comment]
Actually the bug was it was dealing damage to both targets.
