### ISSUE TITLE
another potential bug in Tawnos's Coffin

### ISSUE THREAD

**Issue by xenohedron** [magefree/mage#12340]
noticed from #12332 and not very related so opening a separate issue - [[Tawnos's Coffin]] looks bugged if more than one creature exiled (perhaps if the ability is copied or the delayed trigger is stifled), as the game state values to note the counters/attachments are only stored under the source exile zone id.

**Comment by Susucre** [comment]
Indeed. Those old implementations of weird cards from early year have so many adhoc way to do things that may interact badly with other things.

**Comment by jeffwadsworth** [comment]
Yes, if you use something like [[Rings of Brighthearth]] and copy the activated ability and choose another target creature, the exiled creature will stay put.

**Comment by jeffwadsworth** [comment]
It works now.  Code upload tomorrow.  https://www.youtube.com/watch?v=hw6uiW4gmgs
