### ISSUE TITLE
Refactor: SacrificeTargetCost should restrict its filter to be FilterSacrifice

### ISSUE THREAD

**Issue by Susucre** [magefree/mage#12351]
Not sure how bad that refactor would be, `FilterSacrifice` is specifically there to make sure the proper predicates (controlled, can be sacrificed) are added.

**Comment by JayDi85** [comment]
You can add runtime check to catch wrong filter usage. No needs to change param type. Most usages come from a card constructor, so verify tests will catch it:
![shot_240531_143423](https://github.com/magefree/mage/assets/8344157/3afdf407-a46b-4895-bb3b-f95703cea9db)

There are possible a rare dynamic cost -- it will be catches in real game only:
![shot_240531_143618](https://github.com/magefree/mage/assets/8344157/6c6f4268-0b2a-4bfe-9db5-ae1d9e7b80c9)

**Comment by Susucre** [comment]
Well "Sacrifice a creature:" is in reality "Sacrifice a creature you control that can be sacrificed:", so VerifyTest will mostly not catch if there is a bug there.

**Comment by JayDi85** [comment]
What's card name?

**Comment by Susucre** [comment]
> What's card name?

That's mtg rule. If you have a cost with "sacrifice a creature" written, you can only sacrifice your own creatures to it, and if there is a "creatures can't be sacrificed" or similar effect, it will allow less sacrifice choices.

> And another solution from TargetSacrifice -- auto-add CanBeSacrificedPredicate to filter, so devs don't need to setup it manually.

That is exactly what `TargetSacrifice` does, so why not use it? It can be in the constructor chains of `SacrificeTargetCost` for ease of use.

![image](https://github.com/magefree/mage/assets/34709007/57c6b8da-e3d9-4260-b5e7-124318b77acd)

**Comment by JayDi85** [comment]
I don't understand what you trying to do. Explain with code and card example (before - problem - after).

**Comment by JayDi85** [comment]
[[Blessed Alliance]]

![shot_240531_151555](https://github.com/magefree/mage/assets/8344157/fd8ad070-6122-4ec4-ab9d-6c65b0197b39)

That's wrong card implementation -- spell require only a target player, not a target player that can sacrifice something.

**Comment by xenohedron** [comment]
This feels to me like a misunderstanding. The constructor should accept any `FilterPermanent` and ensure the necessary sacrifice predicates are added behind the scenes.
I'll take a look and fix if I missed something.

**Comment by Susucre** [comment]
> This feels to me like a misunderstanding. The constructor should accept any FilterPermanent and ensure the necessary sacrifice predicates are added behind the scenes.

Yeah that's it. Also, could avoid having some of the passed Filters with names to manually not include the "you control", that's a more tedious refactor, but not mandatory to do.

**Comment by xenohedron** [comment]
I refactored to remove all the "short text" filters in #12120 .

`TargetSacrifice.makeFilter()` performs all the necessary work. There's no such class as 'FilterSacrifice'. As far as I can tell there is nothing more to be done here.

**Comment by xenohedron** [comment]
Okay, I see dfe9390 now.

Best practice - use `TargetSacrifice.makeFilter(filter)` wherever you need it (in this case, that should be in the newly added constructor for EmergeAbility) rather than adding the predicates manually. Only other place to fix is Doom Foretold.

**Comment by Susucre** [comment]
> TargetSacrifice.makeFilter() performs all the necessary work. There's no such class as 'FilterSacrifice'. As far as I can tell there is nothing more to be done here.

Right I was confused in my explanations indeed. The issue is that SacrificeTargetCost doesn't currently call TargetSacrifice::makeFilter to make sure the filter is proper.

> Best practice - use TargetSacrifice.makeFilter(filter) wherever you need it (in this case, that should be in the newly added constructor for EmergeAbility) rather than adding the predicates manually. Only other place to fix is Doom Foretold.

Uhm okay I'll do that.

**Comment by Susucre** [comment]
Did some cleanup for the two instances of the Predicates: 31c772d3683e6f33a6a15d628e7d4a4ec3ebe8bd

**Comment by xenohedron** [comment]
> The issue is that `SacrificeTargetCost` doesn't currently call `TargetSacrifice::makeFilter` to make sure the filter is good to use as a sacrifice one.

As far as I can tell, it's getting handled by the constructors and there's no way to obtain a TargetSacrifice without the necessary predicates.
* SacrificeTargetCost takes a FilterPermanent
* It creates a TargetSacrifice using that FilterPermanent, stored in the cost
* TargetSacrifice makes a good filter using that FilterPermanent, stored in the target

Thanks for the cleanup - there are a couple other direct usages of `makeFilter` for counting permanents on the battlefield, that probably ought to use `canChoose` the way you did for Doom Foretold, which is a cleaner way I think.
