### ISSUE TITLE
Refactor: make a common effect for "[target's controller] gains [N] life"

### ISSUE THREAD

**Issue by Susucre** [magefree/mage#12364]
https://scryfall.com/search?q=o%3A%2Fcontroller+gains%2F

**Comment by xenohedron** [comment]
Common class added in 058ae26d, although I didn't attempt to refactor those with dynamic values.

**Comment by Susucre** [comment]
> Common class added in https://github.com/magefree/mage/commit/058ae26de7a9cbc44bcf666fa60bdc83c5f436c1, although I didn't attempt to refactor those with dynamic values.

Thanks! My current priority is to get cards in MH3 working, I plan to work on those small scope refactor once dust has settled on that.
