### ISSUE TITLE
Select window height is so big, that player can only see an empty part of the window.

### ISSUE THREAD

**Issue by LevelX2** [magefree/mage#1237]
End of opponents turn i cracked an Expedition Map, the search library window came up stretched beyond the height of the window yet empty. My timer was still running. No input would work to the program, couldnt chat, open right click menu, no F# buttons worked, the only way to get out of it was to quit the program completely. No error was thrown in the console log.

![mtcc1mn](https://cloud.githubusercontent.com/assets/2066790/9566299/ee1e29ac-4f00-11e5-8ef3-8b003df8f9c8.jpg)

Reports:
http://www.slightlymagic.net/forum/viewtopic.php?f=70&t=17549&p=184884#p184884
http://www.slightlymagic.net/forum/viewtopic.php?f=70&t=17549&p=185183#p185183
http://www.slightlymagic.net/forum/viewtopic.php?f=70&t=17664&p=185235#p185235
http://www.slightlymagic.net/forum/viewtopic.php?f=70&t=17902&p=189182#p189182
http://www.mtg-forum.de/topic/112585-xmage-magic-online-spielen/?p=1221467

2015-11-14 17:58: Adevas: I had attacked Skullclamp to Junk Diver, and when the window came up to select triggers itwas just a verticle gray box. I could resize it right to left but not up-down

http://www.mtg-forum.de/topic/112585-xmage-magic-online-spielen/?p=1269842

**Comment by LevelX2** [comment]
Cause is unclear. Problem can't be reproduced.

**Comment by fclarat** [comment]
It's happen to me, when before I tried to play a random booster draft. the  windows with all the sets cause    a problem with the height.

**Comment by goesta** [comment]
I'll close this issue because it seems to be outdated but feel free to create a new one if this problem still exists.
