### ISSUE TITLE
Chromatic Star dies trigger is not always triggering

### ISSUE THREAD

**Issue by Susucre** [magefree/mage#12385]
So this is from alpha server, after the latest short lived lki changes:

Chromatic Star sometimes do not trigger on sacrifices, and sometimes does:

![image](https://github.com/magefree/mage/assets/34709007/0c482e99-6a55-472f-8edd-fd5101c67f65)

I don't know enough about short lived lki to fix that for good, so could use advise/help on that.

**Comment by JayDi85** [comment]
If something call apply effects (process actions) after trigger then it will be fizzled due short lki logic. Example: something moved to battlefield.

**Comment by Susucre** [comment]
I literally casted Star on empty board and activated it in the screenshot above. No extra stuff, no other cards but Plains in play.

**Comment by Susucre** [comment]
It seems to be:
- If you have mana in pool, activating Star (either with auto mana or without, but using mana pool mana) to pay result in a trigger.
- If you do not have mana in pool, activating Star, deciding to tap a land to pay then, does not result in a trigger.

**Comment by jeffwadsworth** [comment]
[[Chromatic Star]]
