### ISSUE TITLE
Cryptoplasm seems to create multiple continuous effects

### ISSUE THREAD

**Issue by LevelX2** [magefree/mage#1239]
Cryptoplasm seems to create multiple continuous effects for the same copy effect

**Comment by Zerrisx** [comment]
Can you add some detail or an example to indicate what you mean?

**Comment by LevelX2** [comment]
I meant internal that the same effect is added multiple times to ContinuousEffects object.
I will check if this is (still) the case.

**Comment by LevelX2** [comment]
No problem, looks good.
