### ISSUE TITLE
Bug: Scholar of the Lost Trove doesn't exile instant/sorcery properly

### ISSUE THREAD

**Issue by Susucre** [magefree/mage#12396]
![image](https://github.com/magefree/mage/assets/34709007/e08aed41-1a2b-40c6-a8be-15dc4a839a5a)

[[Scholar of the Lost Trove]]

**Comment by jeffwadsworth** [comment]
The issue is with ThatSpellGraveyardExileReplacementEffect().  Looking at it today.

**Comment by jeffwadsworth** [comment]
Finally got around to looking at this.  Why is the +1 add to the zcc?  This will always be false.

**Comment by JayDi85** [comment]
For info: same target zcc code used in other places -- it can be bugged too

![shot_240605_003110](https://github.com/magefree/mage/assets/8344157/b556d39d-516e-4d4f-86d5-58d559423782)

**Comment by jeffwadsworth** [comment]
Yeah, those other usages relate to the exile->stack type play and the move has already taken place, etc.  But, it doesn't apply to this case.

**Comment by Susucre** [comment]
doesn't it just lack a `game.getState().processAction(game)` then? Inbetween the cast (that moves the card), and the `ThatSpellGraveyardExileReplacementEffect` `apply`.

**Comment by jeffwadsworth** [comment]
Whatever you change, just test it.  Works fine as is.
