### ISSUE TITLE
GUI: Tokens should not stack with non-tokens

### ISSUE THREAD

**Issue by Susucre** [magefree/mage#12395]
It can be hard to see which are the card and which are the tokens with current stacking:

![image](https://github.com/magefree/mage/assets/34709007/a5d97c7a-6962-474d-8365-e6c5f4c5e7d2)

![image](https://github.com/magefree/mage/assets/34709007/82505548-74a2-43f3-8b93-57e44272afbb)

![image](https://github.com/magefree/mage/assets/34709007/baf7633a-29a5-4dbe-b4bc-2a1be53e90a5)

**Comment by grimreap124** [comment]
Weird they shouldn't stack. I'll have a look this evening
