### ISSUE TITLE
Found broken files - but they work.

### ISSUE THREAD

**Issue by tiera3** [magefree/mage#12430]
The log displays that broken files were found, but the images are there and work. For example, the last one on the list is WAR\Swamp.257 and you can clearly see that it shows up in the card viewer.

![image](https://github.com/magefree/mage/assets/87589219/c073a030-d0f4-4a26-8b38-319d64bda9a2)

**Comment by JayDi85** [comment]
Too small images? Maybe improve a min size for break check.

**Comment by JayDi85** [comment]
![IMG_0479](https://github.com/magefree/mage/assets/8344157/c1cc568a-737c-4ac2-af0e-de0501155811)
