### ISSUE TITLE
Outcome inverse method doesn't account for AIDontUseIt

### ISSUE THREAD

**Issue by xenohedron** [magefree/mage#12436]
I'm pretty sure AIDontUseIt should mean that it should always be false/bad/detrimental, right?

https://github.com/magefree/mage/blob/f03a410b9e808e5aeeabea8ad6c18255fd865e10/Mage/src/main/java/mage/constants/Outcome.java#L42

https://github.com/magefree/mage/blob/f03a410b9e808e5aeeabea8ad6c18255fd865e10/Mage/src/main/java/mage/constants/Outcome.java#L69-L75

**Comment by Susucre** [comment]
I would expect the inverse of `Outcome.AIDontUseIt` to be `Outcome.AIDontUseIt`?

**Comment by xenohedron** [comment]
Yeah exactly, that's what I was trying to say haha

**Comment by JayDi85** [comment]
Yes and no. AIDontUseIt for activated abilities only -- whether or not the AI will use this ability.

Inverse logic for targeting. If AI take control of another player/ability -- it must use inverse logic. AI can't skip targeting, so AIDontUseIt can't be used in such use cases.

So you can't change `inverse` code to use AIDontUseIt -- it will brake AI targeting. Maybe two different methods can be used (if you plan to use it in other places) -- inverse and isItGoodForChoosingPlayer(sourceController, choosingPlayer) or like that.

**Comment by xenohedron** [comment]
Hm, okay. I'm not planning on making any changes myself since AI is not my area of expertise. Just wanted to bring it up since I noticed it.

**Comment by JayDi85** [comment]
Anyway that's "AI" targeting logic with manual choosing from targets list will be replaced someday with target simulations (after all bugs and stability problems fix -- current AI simulations sooo buggy)
