### ISSUE TITLE
Phantasmal Image doesn't trigger when targeted by modal spells

### ISSUE THREAD

**Issue by stevedavidmusic** [magefree/mage#12439]
I had an issue where Phantasmal Image doesn't trigger when targeted by a modal spell like Mystic Confluence. 

<img width="1280" alt="Screen Shot 2024-06-08 at 4 34 22 PM" src="https://github.com/magefree/mage/assets/45299811/744bf20d-1649-4de3-ae62-2be402260825">

Here the Phantasmal Image triggers just fine when targeted by a single-targeted non modal spell like Lightning Bolt.
<img width="1280" alt="Screen Shot 2024-06-08 at 4 33 30 PM" src="https://github.com/magefree/mage/assets/45299811/5705b4da-fb83-4877-9c92-0fab71f0d4d9">

**Comment by xenohedron** [comment]
Related to #11539
