### ISSUE TITLE
XMage is unusable on Mac  M1

### ISSUE THREAD

**Issue by danielfranke** [magefree/mage#12431]
Any mouse click in "Connect to Server" window causes XMage to hang (crash - spinning wheel on Mac).

MacBook Pro, 16 inch, 2021
Chip: Apple M1 Max
Memory 64 GB
MacOS Sonoma 14.5
Java 8 update 411

----- CRASH LOG ------

Date/Time:        2024-06-07 22:24:26.230 -0400
End time:         2024-06-07 22:24:45.991 -0400
OS Version:       macOS 14.5 (Build 23F79)
Architecture:     arm64e
Report Version:   49
Incident Identifier: 6C075C46-EF91-44F9-8710-6C394544173C
Share With Devs:  Yes

Data Source:      Stackshots
Shared Cache:     3406AD1B-2469-30EB-9863-5DCE861E6DEA slid base address 0x18fba4000, slide 0xfba4000 (System Primary)
Shared Cache:     03FF7F1F-0B2B-3DA3-9879-86BA9BC31444 slid base address 0x1916cc000, slide 0x116cc000 (DriverKit)
Shared Cache:     6F51A82C-C96C-3BC8-82CA-9C109185BD3C slid base address 0x7ff806ecc000, slide 0x6ecc000 (Rosetta)

Command:          mage.client.MageFrame
Path:             /Applications/XMageBeta/*/java
Codesigning ID:   net.java.openjdk.cmd
Team ID:          VB5E2TV963
Architecture:     x86_64 (translated)
Parent:           XMageLauncher-0.3.8 [1812]
Responsible:      JavaLauncher [1811]
PID:              1819
Time Since Fork:  461s

Event:            hang
Duration:         19.76s
Duration Sampled: 1.10s (process was unresponsive for 19 seconds before sampling)
Steps:            11 (100ms sampling interval)

Hardware model:   MacBookPro18,2
Active cpus:      10
HW page size:     16384
VM page size:     16384

Time Since Boot:  2849s
Time Awake Since Boot: 2849s
Time Since Wake:  n/a (machine hasn't slept)

Fan speed:        0 rpm
Total CPU Time:   1.338s (2.1G cycles, 2.4G instructions, 0.89c/i)
Advisory levels:  Battery -> 1, User -> 2, ThermalPressure -> 0, Combined -> 1
Free disk space:  3046.13 GB/3721.87 GB, low space threshold 3072 MB
Vnodes Available: 82.33% (216670/263168)

Preferred User Language: en-CA
Country Code:     CA
OS Cryptex File Extents: 1

**Comment by JayDi85** [comment]
As workaround until next update:
* Download fixed file from here: http://xmage.today/X/mage-client-1.4.50.jar
* Copy that file to `your_launcher_folder\xmage\mage-client\lib`

**Comment by danielfranke** [comment]
Workaround now provided access to the interface but Mac Client freezes when using mouse for most configuration windows (e.g.: Using drop down menus or clicking with mouse inside a pop-up window to change a setting). ** Work around is using keyboard only with tab + enter keys but this is not always possible for example when prompted to enter a value such as number of cards to draw during play.

**Comment by JayDi85** [comment]
@danielfranke did old versions (from last months) also not work on your mac due freeze on menu usage?

**Comment by danielfranke** [comment]
> @danielfranke did old versions (from last months) also not work on your mac due freeze on menu usage?

Previous versions did allow me to access the interface (unlike newest version) but freeze up regularly when using any kind of menu with drop down. Buttons when used alone worked as expected.

**Comment by JayDi85** [comment]
@danielfranke can you try that fix -- is it workable?

* http://xmage.today/X/v2/mage-client-1.4.50.jar

**Comment by danielfranke** [comment]
> @danielfranke can you try that fix -- is it workable?
> 
> * http://xmage.today/X/v2/mage-client-1.4.50.jar

Unfortunately, this version does not work. The client hangs before I can connect to any server. 
The previous version produced better results.

**Comment by calkno** [comment]
I'm running into (what appears to be) the same issue. Any updates on this? Glad to provide any info needed

**Comment by JayDi85** [comment]
Solutuion for users who raplaced java, but can't play on public servers -- now it can be compatible: #12768

**Comment by JayDi85** [comment]
Original problem was in wrong implementation of modal windows (xmage code for system events processing). Not actual anymore with non-blocking UI in last release #12825
