### ISSUE TITLE
Bug: Shifting Woodland keeps the copied type and color in the graveyard

### ISSUE THREAD

**Issue by Susucre** [magefree/mage#12433]
From the cube Discord:

[[Shifting Woodland]] copying [[Aftermath Analyst]] does not return itself when sacrificed with Analyst's ability.

![image](https://github.com/magefree/mage/assets/34709007/b31e3103-6dc7-4a33-939d-b3facaeab1e6)

It seems to keep the copied types (and color) in the graveyard.

![image](https://github.com/magefree/mage/assets/34709007/9ce122d2-0824-413a-a8e5-e309f7e6e759)

**Comment by Susucre** [comment]
[[Shifting Woodland]]

**Comment by Susucre** [comment]
Issue seems to be the LKI is kept for too long and the `CopyEffect` is not discarded at the right time:

![image](https://github.com/magefree/mage/assets/34709007/89666095-e826-4164-8a19-9edb2cdab44c)

**Comment by Susucre** [comment]
@xenohedron You might have an idea of how fixing this fits in your copy overhaul? #10801

**Comment by JayDi85** [comment]
If it need to keep only dies triggers work then use short living lki, not lki

**Comment by JayDi85** [comment]
Like “if permanent is null and not short living lki then discard”
