### ISSUE TITLE
Image path error - WC02/Fire - Ice

### ISSUE THREAD

**Issue by tiera3** [magefree/mage#12440]
Note these two cards are on different pages in the card viewer, I used a cut and paste. 
![image](https://github.com/magefree/mage/assets/87589219/dfe526f1-4959-43b5-9813-50a05cfb23e0)
It shows that the missing path for both is "WC02\Fire - Ice.full.jpg" however when checking Mage.Sets/src/mage/sets/WorldChampionshipDecks2002.java lines 47-48 are:
```
        cards.add(new SetCardInfo("Fire // Ice", "shh128", Rarity.UNCOMMON, mage.cards.f.FireIce.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Fire // Ice", "bk128", Rarity.UNCOMMON, mage.cards.f.FireIce.class, NON_FULL_USE_VARIOUS));
```
so I would expect the files to be "WC02\Fire - Ice.bk128.full.jpg" and "WC02\Fire - Ice.shh128.full.jpg" respectively.

When I check the downloaded files, those are the paths that have been downloaded.
![image](https://github.com/magefree/mage/assets/87589219/f0f84cc6-6c10-4b3e-98b8-28fb354e269d)

**Comment by JayDi85** [comment]
Fixed in #12430
