### ISSUE TITLE
Vaultborn Tyrant only triggering once with Flash

### ISSUE THREAD

**Issue by stevedavidmusic** [magefree/mage#12449]
Had a game where I cheated Vaultborn Tyrant into play with Flash. I didn't pay the extra cost so it saced itself, but I only got one ETB trigger when I should've had two. 

9:15 PM, T8.DA: The_Steve_Man casts Flash [e7a] 
9:15 PM, T8.DA: The_Steve_Man puts Vaultborn Tyrant [d15] from hand onto the Battlefield (source: Flash [e7a]) 
9:15 PM, T8.DA: The_Steve_Man sacrificed Vaultborn Tyrant [d15] (source: Flash [e7a]) 
9:15 PM, T8.DA: The_Steve_Man puts Flash [e7a] from stack into their graveyard 
9:15 PM, T8.DA: The_Steve_Man - Ability triggers: Vaultborn Tyrant [d15] - When Vaultborn Tyrant [d15] dies, if it's not a token, create a token that's a copy of it, except it's an artifact in addition to its other types. 
9:15 PM, T8.DA: The_Steve_Man creates a Vaultborn Tyrant [943] token 
9:15 PM, T8.DA: The_Steve_Man - Ability triggers: [943] - Whenever Vaultborn Tyrant [943] or another creature with power 4 or greater enters the battlefield under your control, you gain 3 life and draw a card. 
9:15 PM, T8.DA: The_Steve_Man gains 3 life (source: [943]) 
9:15 PM, T8.DA: The_Steve_Man draws a card 
9:17 PM, T8.DB: Attacker: Goldvein Hydra [d52] (4/4) unblocked 
9:17 PM, T8.DB: Attacker: Bristly Bill, Spine Sower [e1d] (5/5) blocked by Vaultborn Tyrant [943] (6/6) 
9:17 PM, T8.DB: Bronobo activates: double the number of +1/+1 counters on each creature you control. from Bristly Bill, Spine Sower [e1d]

**Comment by jeffwadsworth** [comment]
[[Vaultborn Tyrant]]  [[Flash]]
