### ISSUE TITLE
Couple of Cards need missing hints

### ISSUE THREAD

**Issue by Svyatoslav28597** [magefree/mage#12443]
Aether Revolt needs to show how many energy counters you got and how many damage It will deal
Saheeli, the Gifted needs a hint to show how many artifacts you control

**Comment by Susucre** [comment]
> Aether Revolt needs to show how many energy counters you got

Makes sense.

> and how many damage It will deal

Unlikely. The trigger is not aware of the replacement effects (including the one from Aether Revolt), and in case of multiple, will not be able to guess the order they'll be applied anyway.

> Saheeli, the Gifted needs a hint to show how many artifacts you control

Reasonable.

**Comment by Susucre** [comment]
![image](https://github.com/magefree/mage/assets/34709007/74708df9-e2ef-480f-bc14-c1c44a9dedbb)

![image](https://github.com/magefree/mage/assets/34709007/3bcb77c9-2ddb-4aaf-95a2-e6790465261c)

**Comment by Svyatoslav28597** [comment]
Looks great, thanks!

**Comment by Susucre** [comment]
9180e22
