### ISSUE TITLE
Arcane Bombardment needs to be able to choose spell order

### ISSUE THREAD

**Issue by alexander-novo** [magefree/mage#12454]
[[Arcane Bombardment]] needs a little bit of extra code so that the controller can order the spells that they're casting. See [[Mizzix's Mastery]]:

https://github.com/magefree/mage/blob/a8215efe1a6275f66112a733d9a6b80ca9178f2a/Mage.Sets/src/mage/cards/m/MizzixsMastery.java#L89-L95

**Comment by JayDi85** [comment]
Code looks correct - controller will choose card by card to cast (first selected go first to cast). Until cards list ends or user cancel it.

**Comment by Susucre** [comment]
> Code looks correct - controller will choose card by card to cast (first selected go first to cast). Until cards list ends or user cancel it.

Have you read the Arcane Bombardment code? Cards are added one by one each time it trigger, the copy order is by exileZone.getCards(game) order, which is not the issue there, as the player should be able to choose the order the copy are cast (and which are cast).

**Comment by JayDi85** [comment]
Sorry look at mizzix link and code

**Comment by Susucre** [comment]
Yeah that was a good example of when that effect (copy multiple, you may cast any number of copies) is implemented right. So Arcane Bombardment should be made the same.
