### ISSUE TITLE
ENHANCEMENT - It would be nice if "target opponent" autotargeted in 1v1.

### ISSUE THREAD

**Issue by tiera3** [magefree/mage#12466]
This comes up a lot with OTJ cards but there are a lot of old cards that would benefit from this also.

Example - [[quick draw]]

-----------

Of course if there is any card that allows "up to one target opponent" that shouldn't autotarget, but I don't know of any such cards off the top of my head.

**Comment by JayDi85** [comment]
It already must work for required choices (not up to xxx). Check your auto-choose settings in Preferences dialog.

**Comment by xenohedron** [comment]
I'm pretty sure this is in fact something that's bugged about auto-choices, even if fully enabled

**Comment by tiera3** [comment]
![image](https://github.com/magefree/mage/assets/87589219/d2528f30-694e-4753-845a-e2a7594b07b0)
Not sure what setting you are referring to, so here are my settings.
![image](https://github.com/magefree/mage/assets/87589219/60b936be-aa82-4054-9a70-58347fa69860)

When I need to select target creature or a target card in a graveyard, the client autotargets when there is only valid choice - which is what prompted me to make this suggestion. (Target opponent always requires me to manually target.)

**Comment by JayDi85** [comment]
![IMG_0519](https://github.com/magefree/mage/assets/8344157/30039af8-e132-4279-b769-14616f51ae94)

**Comment by xenohedron** [comment]
I suspect this has to do with something about TargetOpponent / FilterOpponent / `possibleTargets` not being properly implemented. Need some clear steps with simple cards/effects to reproduce when it consistently does or doesn't autotarget.

**Comment by xenohedron** [comment]
Alright, I figured it out.

It has to do with bad overloaded usage of "isRequired" in Target, exacerbated by the fix in #10557 (which did address a real bug, but not in the best way).

For UI purpose, if casting a spell or activating an ability, it is sensible to allow a "cancel" for human players when choosing targets. Currently it overwrites the target's "required" parameter to false, which prevents autochoose from working for all cast spells and activating abilities, defeating the point in many common scenarios.

This needs to instead use a separate "canBeCanceled" param, distinct from the "required" param used for e.g. Vendilion Clique. Autochoose method then needs to only autochoose if "required", but still autochoose even if "canBeCanceled".

https://github.com/magefree/mage/blob/dadc6775923f6330fd68e0731aece582bd890f89/Mage/src/main/java/mage/abilities/AbilityImpl.java#L390-L392

https://github.com/magefree/mage/blob/754b382e7802fdc45eacd1b8f0ce16666ff33a4f/Mage/src/main/java/mage/target/Targets.java#L90-L93

**Comment by xenohedron** [comment]
Or... another approach be to modify the targets that are explicitly "required = false" to instead use "minNumTargets = 0". This might be cleaner and more practical. Then autochoose logic wouldn't have to check it.

Existing implementation of "required" logic is very messy.
