### ISSUE TITLE
ENHANCEMENT - Would it be okay to add "draft matters" cards as vanilla creatures?

### ISSUE THREAD

**Issue by tiera3** [magefree/mage#12467]
We have played a few games where the draft was performed on draftmancer and [[Cogwork Librarian]] was included, but obviously caused an error when the resultant deck was imported into xmage.

I was wondering if it would be okay to implement this and similar cards as vanilla creatures, or creatures with just their gameplay abilities. (Would be even better if they could have a card hint in the draft panel to mention that the draft matters aspect doesn't work - for instances where they are included in a chaos or cube draft.)

Draft matters cards that could be implemented as vanilla creatures:
* Agent of Acquisitions
* Cogwork Librarian
* Leovold's Operative
* Lore Seeker
* Whispergear Sneak

Or with a gameplay ability (not their draft matters ability)
* Archdemon of Paliano
* Canal Dredger
* Cogwork Spy
* Deal Broker
* Illusionary Informant

**Comment by xenohedron** [comment]
I agree this is a sensible thing to do

**Comment by JayDi85** [comment]
I think it’s possible to implement some of the draft related effects. Same way as game replacement effects:
* booster cards manipulation possible:
  * Agent of Acquisitions
  * Cogwork Librarian
  * Leovold's Operative
* additional booster impossible due infinite draft problem GUI locked on boosters amount (maybe impossible, need additional research):
  * Lore Seeker
* boosters lookup possible:
  * Whispergear Sneak
* faceup/facedown manipulation - it’s need for paper only and can be replaced by related chat messages like “player xxx drafted card name” or “player xxx used yyy from card name”;

That’s all require support of server side GUI dialogs inside deck editor and draft. So not so easy

**Comment by xenohedron** [comment]
You can reference what Draftmancer has been able to do: https://github.com/Senryoku/Draftmancer/wiki/Conspiracy-cards-support

Seems difficult for xmage currently. Logic for drafting is not so robust, so need to be careful about any changes that affect it.

**Comment by JayDi85** [comment]
* Random choice possible:
  * Archdemon of Paliano
* Cards moving between players possible:
  * Canal Dredger
* Cards lookup possible:
  * Cogwork Spy
  * Illusionary Informant
* Cards exchange possible:
  * Deal Broker

**Comment by JayDi85** [comment]
Are all that cards important for draft experience? Is it popular?

**Comment by alexander-novo** [comment]
Cogwork librarian is a very popular cube card

**Comment by tiera3** [comment]
For reference, I left out all the cards that get changed based on the draft - eg [[Aether Searcher]] or [[Animus of Predation]] .

**Comment by xenohedron** [comment]
Original scope of issue is complete
