### ISSUE TITLE
Cannot load main class ..lib.mage-client-1.4.50.jar

### ISSUE THREAD

**Issue by chaoticmachinery** [magefree/mage#12481]
Hello,

I have been compiling Xmage alpha version for a while now and its been running fine. Recently, I compiled the latest version and I get the following error: Error: Could not find or load main class ..lib.mage-client-1.4.50.jar. The Xmage client does not start up. Watching the compile run, I don't see any errors.

Below is the where the error shows up:
# sh startMage.sh 
OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=384m; support was removed in 8.0
Error: Could not find or load main class ..lib.mage-client-1.4.50.jar
INFO  2024-06-16 16:19:50,349 Starting MAGE SERVER version: 1.4.52-V4-beta4 (build: 2024-06-16 20:09)                    =>[main] Main.main 
INFO  2024-06-16 16:19:50,351 Java version: 1.8.0_412                                                                    =>[main] Main.main

Thanks.

**Comment by JayDi85** [comment]
client start script fixed by last commits, must works fine now

**Comment by chaoticmachinery** [comment]
Thank you. Working fine now.
