### ISSUE TITLE
Induced Amnesia doesn't return exiled cards to owner's hand

### ISSUE THREAD

**Issue by brotendomtg** [magefree/mage#12486]
I've noticed in two commander games that Induced Amnesia doesn't return the cards exiled with its ability to their owner's hand when it (Induced Amnesia) goes to the graveyard.

In both scenarios, I played the Induced Amnesia, exiled my hand, and then sacrificed it to Barrin, Master Wizard's activated ability. 
![1](https://github.com/magefree/mage/assets/114497501/d4be792b-2965-4a46-803b-ad4056655b08)
![2](https://github.com/magefree/mage/assets/114497501/e5ba18a3-8c99-41b0-8ab7-8e07960c8f57)

**Comment by jeffwadsworth** [comment]
[[Induced Amnesia]] [[Barrin, Master Wizard]]
