### ISSUE TITLE
Add https support for xmage.today

### ISSUE THREAD

**Issue by JayDi85** [magefree/mage#12492]
Must support both http and https links for compatibility with old launchers (config.json).

**Comment by artemiswkearney** [comment]
If old launchers keep downloading over HTTP, that's still a security risk, especially if it's silent with no indicator that it should be changed. I'm not sure where the launcher gets its web user agent implementation, or if it'd respond properly to a 301 redirect to HTTPS followed by a [Strict-Transport-Security header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security); another option could be to serve an xmage "update" over HTTP with a message that informs users of the security concerns and tells them where/how to modify config.json.

**Comment by artemiswkearney** [comment]
I'm not sure what Java version people tend to run the launcher with. I launch it with my OS Java, so it should have up-to-date certs, but maybe some people are running it with the old version that it installs after the first run.

**Comment by alexander-novo** [comment]
The launcher doesn't install a different java version - just downloads it to run the client/server with it from the launcher. So people must have some version of Java installed separately.

I suspect most users are probably using whatever version of Java they installed for things like Minecraft ages ago.

**Comment by JayDi85** [comment]
https://xmage.today migrated to https.

Old launcher had some problems:
* redirects in files downloads are fine;
* redirects in config read are fail due wrong unsupported redirect -- it require some workarounds with nginx and http allow for `config.json` location https://github.com/magefree/Launcher/commit/623adfd63151b0667f15a6656cfa9a25de44a2c4
* different home settings works fine (example: xmage.today or beta.xmage.today).

Current site fully compatible with any launchers and home settings.

Current default home: `https://xmage.today`

**Comment by artemiswkearney** [comment]
Even after changing the home setting, I still see this in the launcher's logs:
```
New version of XMage available
Downloading XMage from http://beta.xmage.today/files/mage-update_1.4.54-dev_2024-09-25_13-04.zip
```

**Comment by JayDi85** [comment]
Yes, I know, download links will be upgraded with next release. It works
fine.

вс, 29 сент. 2024 г., 11:07 Artemis Kearney ***@***.***>:
