### ISSUE TITLE
It That Heralds the End's cost reduces ability benefits opponent.

### ISSUE THREAD

**Issue by HexOoze** [magefree/mage#12503]
It That Heralds the End's cost reduction ability benefits your opponent.

**Comment by ErtaiBlue** [comment]
This might be an issue with cost reduction and not just It That Heralds the End.
I played against someone who had a Ruby Mediallion and a Ral, Monsoon Mage//Ral, Leyline Prodigy on the board, and my red instants and sorceries had their cost reduced by 1.
