### ISSUE TITLE
Lightning Bolt could not target Planeswalker

### ISSUE THREAD

**Issue by h-taylor** [magefree/mage#1250]
Hey I just played a game where I could not target a planeswalker with lightning bolt.

Specifically I couldn't target Ugin, the Spirit Dragon.

It only has happened once. Should be checked vs other planeswalkers.

**Comment by LevelX2** [comment]
Lightning bolt can't target a planeswalker. You have to target the controlling player and to redirect the damage.

306.7. If noncombat damage would be dealt to a player by a source controlled by an opponent, that opponent may have that source deal that damage to a planeswalker the first player controls instead. This is a redirection effect (see rule 614.9) and is subject to the normal rules for ordering replacement effects (see rule 616). The opponent chooses whether to redirect the damage as the redirection effect is applied. #
