### ISSUE TITLE
Game exception occurred: java.lang.ClassCastException: mage.game.permanent.PermanentCard cannot be cast to mage.game.stack.StackAbility

### ISSUE THREAD

**Issue by AKPWebDesign** [magefree/mage#1251]
Game exception occurred: java.lang.ClassCastException: mage.game.permanent.PermanentCard cannot be cast to mage.game.stack.StackAbility
Server version: 1.4.4v0
mage.view.GameView.<init>(GameView.java:136)
mage.server.game.GameSessionPlayer.getGameView(GameSessionPlayer.java:239)
mage.server.game.GameSessionPlayer.select(GameSessionPlayer.java:103)
mage.server.game.GameController$18.execute(GameController.java:859)
mage.server.game.GameController.perform(GameController.java:1010)
mage.server.game.GameController.perform(GameController.java:1003)
mage.server.game.GameController.select(GameController.java:856)
mage.server.game.GameController.access$1100(GameController.java:97)
mage.server.game.GameController$2.event(GameController.java:240)
mage.server.game.GameController$2.event(GameController.java:224)
mage.game.events.EventDispatcher.fireEvent(EventDispatcher.java:56)
mage.game.events.PlayerQueryEventSource.select(PlayerQueryEventSource.java:67)
mage.game.GameImpl.firePriorityEvent(GameImpl.java:1859)
mage.player.human.HumanPlayer.priority(HumanPlayer.java:645)
mage.game.GameImpl.playPriority(GameImpl.java:1203)
mage.game.turn.Step.priority(Step.java:87)
mage.game.turn.Phase.playStep(Phase.java:210)
mage.game.turn.Phase.play(Phase.java:115)
mage.game.turn.Turn.play(Turn.java:152)
mage.game.GameImpl.playTurn(GameImpl.java:796)
mage.game.GameImpl.play(GameImpl.java:710)
mage.game.GameImpl.start(GameImpl.java:677)
mage.server.game.GameWorker.call(GameWorker.java:61)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
java.lang.Thread.run(Thread.java:745)

**Comment by LevelX2** [comment]
Exception was handled with b3eb6f5
