### ISSUE TITLE
Chromatic Star bug

### ISSUE THREAD

**Issue by Knaussgard** [magefree/mage#12518]
It appears that chromatic Star does not always draw a card when it is put into a graveyard from the battlefield

**Comment by xenohedron** [comment]
Already fixed by #12438

**Comment by Knaussgard** [comment]
I had this issue an hour ago today, 24 June

**Comment by xenohedron** [comment]
Yep. And you'll continue to have it as long as you're using a release that was built before the fix was merged. Whenever the next release happens, it'll be fixed.
