### ISSUE TITLE
Echoes of Eternity Triggering Itself?

### ISSUE THREAD

**Issue by jdmagtibay** [magefree/mage#12516]
Hi. As always I admire the work you put in the game. However, it turns out one of the new cards from MH3 is breaking games.
I am talking about Echoes of Eternity. 

> Echoes of Eternity
> {3}{C}{C}{C}
> Kindred Enchantment — Eldrazi
> 
> If a triggered ability of a colorless spell you control or **another colorless permanent you control triggers**, that ability triggers an additional time.
> 
> Whenever you cast a colorless spell, copy it. You may choose new targets for the copy. (A copy of a permanent spell becomes a token.)

Now someone cast this, and all hell broke loose. Hahaha! They cast a colorless spell that get copied **twice**, when I think it should only copy once. They cast Zhulodok, and same thing happened. So I think the problem lies with what triggers it. I hope you can resolve this. Thanks.

**Comment by xenohedron** [comment]
already fixed for next release by #12419

**Comment by jdmagtibay** [comment]
@xenohedron Question though. How is a pull request different from an issue? I didn't search there so I made a new issue here.

**Comment by xenohedron** [comment]
A pull request is for changing the code. An issue is just describing a bug or request.

**Comment by alexander-novo** [comment]
I apologize, I should have created an issue for organizational purposes.
