### ISSUE TITLE
A wrong react about Benevolent Blessing

### ISSUE THREAD

**Issue by Greasefang** [magefree/mage#12515]
When I played Duel commander usingLight-paws today, I cast Daybreak Coronet and using Light-paws' ability to search Benevolent Blessing.
As it enters, I choose white. It should give Light-paws protection from white and keep itself and other auras stay in the battlefield. But in this case, My fox becomes a 2/2 creature with NOTHING.
Plz fix it, it really matters to Light-paws.

**Comment by xenohedron** [comment]
duplicate of #11371
