### ISSUE TITLE
Xmage No Longer Allowing Choices for Order of Suspend Triggers

### ISSUE THREAD

**Issue by GamingG** [magefree/mage#1252]
When a player has multiple suspended spells, the suspend triggers on their upkeep should go onto the stack in the order of that player's choosing.  This was the previous behavior in xmage, but as of 1.4.4, this is no longer the case.

**Comment by kronau** [comment]
How about learn not to play a shit deck

**Comment by LevelX2** [comment]
Deactivate the option, that order of triggers with the same name is set automatically.
I'll check if the trigger text for different cards with Suspend is the same and add e.g. the card name if missing.
