### ISSUE TITLE
Cost tags info miss for stack abilities?

### ISSUE THREAD

**Issue by JayDi85** [magefree/mage#12522]
See example with evidence hint. If you collect evidence then it must show pay status but it miss that info (only card hint miss it, not real game):

![shot_240625_101443](https://github.com/magefree/mage/assets/8344157/9f51476e-2727-4f7a-81ec-8c8cb31c1ba4)

**Comment by ssk97** [comment]
At first glance I suspect the problem is that the hint is trying to find the tag inside the Collect Evidence static ability itself (which isn't an activated ability and thus does not have any tags), when it instead needs to be looking at the corresponding SpellAbility.

**Comment by JayDi85** [comment]
Real reason: cost tags duplicated for permanent only - that’s why it works with etb abilities, but miss on stack. I don’t like to find Spell ability from a source object but it can be the only one workable solution. Hmm.
