### ISSUE TITLE
failing test: TxtDeckImporterTest

### ISSUE THREAD

**Issue by xenohedron** [magefree/mage#12535]
> TxtDeckImporterTest.testImportWithBlankLineAboveSideboard:25 Card Plains was null

`CardRepository::findCards` is returning an empty list.

Commit dbdfef8e previously passed, but now fails. Clean local build of that commit also fails. So it would seem the recent implementation of DSK set without basic lands is a red herring.

**Comment by xenohedron** [comment]
![image](https://github.com/magefree/mage/assets/12538125/1dbda7e3-a555-4c0e-8eca-28276e94838c)

**Comment by JayDi85** [comment]
That test depends on cards db and somehow starting to execute by maven before game related tests (maven uses random and file names specific order). So cards db check and re-create by call `CardScanner.scan();` can fix it. Fixed in d7ac82efb356887810c1dd4dee38d712a1f802f3.
