### ISSUE TITLE
Some Activated Abilities No Longer Using Stack

### ISSUE THREAD

**Issue by GamingG** [magefree/mage#1253]
Selenia, Dark Angel's ability is "Pay 2 life: Return Selenia, Dark Angel to its owner's hand."  A player controlling Selenia should be able to retain priority while activating this ability any number of times (as long as that player has 2 or more life, of course).  This is how it behaved in previous versions of xmage, however, now it resolves immediately and asks to return Selenia to the command zone if Selenia is that player's commander.

**Comment by GamingG** [comment]
Upon further investigation, this might be due to the option to automatically pass priority on spell cast or ability activation being on despite the box not being checked in preferences.

**Comment by LevelX2** [comment]
Try to sitch on/off the option in the client preferences. It might be that the wrong state is shown and this can workaround this problem.
