### ISSUE TITLE
Arcbond effect is causing an exception and the game to halt

### ISSUE THREAD

**Issue by Greeneye0** [magefree/mage#1254]
Steps to duplicate:
1. Block an attacking creature
2. Cast Arcbond on your creature
3. Exception 

![image](https://cloud.githubusercontent.com/assets/11687236/9775251/1acd9dc2-570b-11e5-8ef6-7c70b45739c4.png)

**Comment by LevelX2** [comment]
Fixed with 5494f191b90851b9a9ac1723d62369ee826832b7
