### ISSUE TITLE
Omo, Queen of Vesuva everything counters interacting incorrectly with creature lands

### ISSUE THREAD

**Issue by QuinnActually** [magefree/mage#12558]
![image](https://github.com/magefree/mage/assets/55411824/c65d430e-6239-4f28-bd7a-4e0cffeac779)
Everything counters placed by Omo, Queen of Vesuva currently do not make creature lands act as every land type.

**Comment by QuinnActually** [comment]
![image](https://github.com/magefree/mage/assets/55411824/e705fc17-1583-430e-b6ce-9507f2449715)
![image](https://github.com/magefree/mage/assets/55411824/0282bcd6-e055-453d-a569-4895d751204b)
![image](https://github.com/magefree/mage/assets/55411824/e7ee03b2-0f6a-46c1-8837-6e8908abbf06)

Update: something about this boardstate somehow fixed the problem? I'm fairly certain it was either Planar Nexus or Copy Land that corrected things.

**Comment by jeffwadsworth** [comment]
[[Omo, Queen of Vesuva]]

**Comment by jeffwadsworth** [comment]
[[Ashaya, Soul of the Wild]]
