### ISSUE TITLE
Kira does not counter multi-modal spells.

### ISSUE THREAD

**Issue by Tharkon** [magefree/mage#12567]
When [[Kira, Great Glass-Spinner]], or another creature controlled by the same controller, is targeted by a modal spell that allows the selection of multiple modes, Kira does not seem to trigger.

Examples I tested are:
- [[Cryptic Command]] (mode 2, no other targets)
- [[Mystic Confluence]] (mode 2, no other targets)
- [[Prismari Command]] (mode 1, also targeting a player)
- [[Verdant Confluence]] (mode 1, no other targets, as well as targeting 2 different creatures with mode 1)

It does not seem to matter if the other modes are also targeted or if the mode targeting Kira is mode 1 or not.
It also does not expend the trigger, if Kira is targeted at a later point that turn, that is considered the first time and it will get countered.

A modal spell that allows a single mode, such as [[Boros Charm]] or [[Red Elemental Blast]] does get countered.

**Comment by xenohedron** [comment]
Already fixed by #12452, just waiting on next release
