### ISSUE TITLE
Sacrifice from evoke doesn't resolve when control of creature changes

### ISSUE THREAD

**Issue by duelcastermage** [magefree/mage#12582]
I had a [[Confusion in the Ranks]] out. I evoked an [[Ingot Chewer]], with the sacrifice from evoke on the bottom of the stack, resolving last of the 3 triggers. I exchanged control of the Chewer with one of my opponent's creatures, but the sacrifice never then happened once it was under their control.

**Comment by ssk97** [comment]
I believe that is correct behavior. You are the controller of the trigger that triggered when the Ingot Chewer enters. Control of the creature changes but the trigger does not.

> 701.17a. To sacrifice a permanent, its controller moves it from the battlefield directly to its owner's graveyard. **A player can't sacrifice something that isn't a permanent, or something that's a permanent they don't control**. Sacrificing a permanent doesn't destroy it, so regeneration or other effects that replace destruction can't affect this action.

**Comment by ssk97** [comment]
Oh wait, didn't read the Evoke rules properly. Yeah, looks like Evoke is implemented incorrectly.

> 702.74a. Evoke represents two abilities: a static ability that functions in any zone from which the card with evoke can be cast and a triggered ability that functions on the battlefield. "Evoke [cost]" means "You may cast this card by paying [cost] rather than paying its mana cost" and "When this permanent enters the battlefield, if its evoke cost was paid, **its controller sacrifices it**." Casting a spell for its evoke cost follows the rules for paying alternative costs in rules 601.2b and 601.2f-h.
