### ISSUE TITLE
Marneus Calgar missing draws

### ISSUE THREAD

**Issue by MrCMaccc** [magefree/mage#12588]
Marneus Calgar failed to draw cards under certain conditions. Opponnent made a copy of my Calgar then Gor Muldrak triggered creating 1 salamander token under my control as well as another 1 under theirs and neither of us drew a card from our respective Calgars

**Comment by jimga150** [comment]
[[Marneus Calgar]]
[[Gor Muldrak, Amphinologist]]

**Comment by jimga150** [comment]
Was the copy a token copy? I'm getting half the behavior you describe if i make a Maneus copy using [[Altered Ego]]. Both players make a toke, but only Gor Muldrak's controller drew a card.

**Comment by jimga150** [comment]
Turns out this is caused by a known issue documented in #11895
