### ISSUE TITLE
images only get downloaded in english, no other language 

### ISSUE THREAD

**Issue by Serasul1984** [magefree/mage#12599]
i choose DE
but i get some in DE, some in eng and some even in asian symbols

**Comment by JayDi85** [comment]
1. Use scryfall source and make sure it [really has DE images](https://scryfall.com/sets);
2. Xmage download only miss images. If you already has EN images then must enabled "force re-download" checkbox in download dialog;
3. Re-open deck or re-add cards in deck editor -- so they will use latest image version;
