### ISSUE TITLE
Handling of dependent effect (rule 613.7) .

### ISSUE THREAD

**Issue by LevelX2** [magefree/mage#1259]
http://magiccards.info/rule/613-interaction-of-continuous-effects.html

With commit https://github.com/magefree/mage/commit/fb965ebdd6e4b74fa40f06b5b618b7250d7763b6 I added a (workaround) solution to handle at least known dependencies between continuous functions.
I know this is no perfect solution, but couldn't come up with something better yet.
So anyone with ideas concerning this topic feel free to post here your thoughts.

**Implemented dependencies:**
[Necrotic Ooze is dependant to Yixlid Jailer.](http://www.mtgsalvation.com/forums/magic-fundamentals/magic-rulings/magic-rulings-archives/285211-yixlid-jailer-vs-necrotic-ooze)
[Conversion is dependant to Magus of the Moon](http://www.mtgsalvation.com/forums/magic-fundamentals/magic-rulings/magic-rulings-archives/286046-conversion-magus-of-the-moon)
Opalescence is dependant to Enchanted Evening
[Starfield of Nyx  is dependant to BecomesAuraSourceEffect and BestowTypeChangingEffect](http://www.slightlymagic.net/forum/viewtopic.php?f=70&t=17664&start=30#p185513)

**Emerald commented:**
That seems like the wrong way to solve this problem. I think a better way would be to have a method that returns the list of affected objects, and see if it changes depending on the ordering of effects. If it does, that means there is a dependency and the correct order is applied.

Also, there should probably be a parameter or something that should be set on effects where dependency could matter. That way you wouldn't have to check for every Giant Growth you cast.

**Comment by LevelX2** [comment]
> Also, there should probably be a parameter or something that should be set on effects where dependency could matter. That way you wouldn't have to check for every Giant Growth you cast.

The default method returns simply null if it's not overwritten, so this seems simple enough.

**Comment by LevelX2** [comment]
> That seems like the wrong way to solve this problem. I think a better way would be to have a method that returns the list of affected objects, and see if it changes depending on the ordering of effects. If it does, that means there is a dependency and the correct order is applied.

Does not sound easy and does not sound as it could be done very fast. Remember that in every even simple turn the applyEffects methods is easily executed more than 30 times.

**Comment by jeffwadsworth** [comment]
This functionality may be broken with commit 972ed6a3f294bd2a67d5c65b2b9b96ad4bc4451
Note the isDependentTo part of that commit.  I see that a Starfield of Nyx test is failing and that method is in the error log.

**Comment by ingmargoudt** [comment]
Then I suggest that the StarField of Nyx is going to be fixed, as I already fixed the Necrotic Ooze dependency as well.

**Comment by ingmargoudt** [comment]
They have an overload for the isDependentTo , if you return an empty set rather than null, then the tests pass again.
