### ISSUE TITLE
BUG: 2x Grim Initiate + Devouring Hellion fails to trigger amass.

### ISSUE THREAD

**Issue by alma555** [magefree/mage#12614]
In a game on the XDHS, sacrificed 2 Grim Initiate to Devouring Hellion, and both Grim Initiate's abilities were never put on the stack. There was already an Army token in play across the board, which may be relevant. 

Gamelog is attached. 
[gamelog.txt](https://github.com/user-attachments/files/16404697/gamelog.txt)

**Comment by xenohedron** [comment]
should be fixed by #12438
