### ISSUE TITLE
Any chance of a new release soon?

### ISSUE THREAD

**Issue by tiera3** [magefree/mage#12639]
I have been months since the last update so many newly coded cards are not implemented in the current beta distribution.

We recently did a draft including some of the new BLB and MH3 cards, expecting to be able to play it on the alpha server ... but that is unexpectedly unavailable for a couple of weeks.

Conversely if xmage updated the beta server, we would be able to play our decks there.

**Comment by JayDi85** [comment]
Yes, I'm almost finish GUI changes (you can monitor it in commits), so it will be soon released
