### ISSUE TITLE
{BUG} Kethek, crucible goliath cancelling death triggers

### ISSUE THREAD

**Issue by zoot4life** [magefree/mage#12652]
Problem with Kethek, crubile goliath. I sacrificed Treasure keeper to its ability and the death trigger from treasure keeper did not happen. 
The Kethek trigger resolved as it should but i did not reveal till a nonland cmc 3 or less when treasure keeper died.
Same thing happened Chaos defiler and with body lauderer being sacrificed to kethek's trigger. Other cards seeing death triggers are happening but the individual cards being sacrificed that have death triggers are not happening.

**Comment by xenohedron** [comment]
fixed two months ago by #12438 (wait for next release)
