### ISSUE TITLE
{BUG} Ulalek, Fused Atrocity not considered as colorless eldrazi by Eldrazi Temple

### ISSUE THREAD

**Issue by drownik** [magefree/mage#12656]
Ulalek, Fused Atrocity not considered as colorless eldrazi by Eldrazi temple (i don't know if that happens with other similar cards).

I had solring, Eldrazi Temple and Llanowar wastes in play. The game is telling me that I can cast the commander (colored in red), when I tap the Eldrazi Temple, select the second efect and the 2 colorless mana and the 2 colorless mana are directly thrown to the mana pool instead of discounting the commander cost. Even if I click the mana on the pool they're not discounting the commander cost required to cast it. This mana can't also be used to pay the commander trigger.

**Comment by ssk97** [comment]
This was fixed by #12429, wait for update.
