### ISSUE TITLE
BUG - Katilda, Dawnhart Prime looks at color identity instead of card colors for mana ability

### ISSUE THREAD

**Issue by Athanar90** [magefree/mage#12653]
As the title says, Katilda, Dawnhart Prime allows any Human you control to tap for any color in its color identity. Normally this isn't an issue because they match up, but I ran into the issue with Jodah, Archmage Eternal where it allowed me to add Black or Green mana when his mana cost is 1WUR.

**Comment by ssk97** [comment]
This seems nearly certain to have been fixed by #12429, wait for update.
