### ISSUE TITLE
Wrong rules generating for cards with pawprint symbols

### ISSUE THREAD

**Issue by xenohedron** [magefree/mage#12662]
~~Since {P} used to represent the phyrexian symbol but now represents the pawprint symbol, it renders incorrectly if the symbol was previously downloaded.~~

Also, the pawprints for each mode are not displayed correctly @jimga150 

![image](https://github.com/user-attachments/assets/c0ec6e6d-ca39-4507-a756-c81079799e51)

**Comment by jimga150** [comment]
Not sure what the right solution is to the P->H change for the symbols. How often do we expect this to occur? 
Should the image downloader start fetching image hashes and comparing them to detect changed ones for automatic redownloading? 
Or should a one-time "please redownload your symbols" memo be sent out (i think people would need to dig down into their client folder and delete the symbols directory right? there's no force redownload option?)

**Comment by JayDi85** [comment]
Symbols re-downloaded all the time. Card images re-downloaded in force mode only. I'll add additional hint about re-download in release notes. Nothing to do with it.

But rules generating must be fixed:

![shot_240815_091359](https://github.com/user-attachments/assets/3761818d-0bf5-402b-8cb4-13ac47c95a3e)
![shot_240815_091217](https://github.com/user-attachments/assets/a74ec736-9cb2-47f2-9bef-1891884b6bb1)
