### ISSUE TITLE
Halvar, God of Battle  --> SERVER - game error

### ISSUE THREAD

**Issue by Reya87** [magefree/mage#12678]
Hello,

When you try to move aura with Halvar, God of Battle ability, the game shows you this error and it's impossible to move aura from creature to another creature. 

Error type: SERVER - game error
Client version: 1.4.53-V1 (build: 2024-08-16 15:36)

Game error occurred: 

java.lang.NullPointerException
Server version: 1.4.53-V1 (build: 2024-08-16 15:36)
Stack trace:
mage.cards.h.HalvarGodOfBattleEffect.apply(HalvarGodOfBattle.java:131)
mage.abilities.AbilityImpl.resolveMode(AbilityImpl.java:222)
mage.abilities.AbilityImpl.resolve(AbilityImpl.java:206)
mage.abilities.TriggeredAbilityImpl.resolve(TriggeredAbilityImpl.java:205)
mage.game.stack.StackAbility.resolve(StackAbility.java:85)
mage.game.GameImpl.resolve(GameImpl.java:1804)
mage.game.GameImpl.playPriority(GameImpl.java:1727)
mage.game.turn.Step.priority(Step.java:67)
mage.game.turn.Phase.playStep(Phase.java:205)
mage.game.turn.Phase.play(Phase.java:91)
mage.game.turn.Turn.play(Turn.java:137)
mage.game.GameImpl.playTurn(GameImpl.java:1151)
mage.game.GameImpl.play(GameImpl.java:1058)
mage.game.GameImpl.start(GameImpl.java:1034)
mage.server.game.GameWorker.call(GameWorker.java:35)
mage.server.game.GameWorker.call(GameWorker.java:16)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)

**Comment by xenohedron** [comment]
was fixed by #12098
