### ISSUE TITLE
General error - ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by montegen10** [magefree/mage#12694]
Error type: General error - ArrayIndexOutOfBoundsException
Client version: 1.4.53-V1 (build: 2024-08-16 15:36)

3

Stack trace:
javax.swing.text.CompositeView.getView(CompositeView.java:160)
javax.swing.text.View.calculateUpdateIndexes(View.java:1184)
javax.swing.text.View.forwardUpdate(View.java:1144)
javax.swing.text.FlowView$LogicalView.forwardUpdate(FlowView.java:805)
javax.swing.text.View.removeUpdate(View.java:751)
javax.swing.text.FlowView.removeUpdate(FlowView.java:269)
javax.swing.text.View.forwardUpdateToView(View.java:1229)
javax.swing.text.View.forwardUpdate(View.java:1162)
javax.swing.text.BoxView.forwardUpdate(BoxView.java:240)
javax.swing.text.View.removeUpdate(View.java:751)
and other 45 lines

**Comment by xenohedron** [comment]
duplicate of #12816
