### ISSUE TITLE
Morph cannot be played from nonhand zone with nonhand zone casting enabled

### ISSUE THREAD

**Issue by jimga150** [magefree/mage#12693]
Looks like morph isnt working when able to cast the morph card from a non-hand zone.

Test: 
[[Zask, Skittering Swarmlord]] on the battlefield
[[Bane of the Living]] in the graveyard
4 swamps on the battlefield

Attempting to cast Bane of the Living does not provide morph choice.

**Comment by Dunkoro** [comment]
It's because a spell's characteristics determine its' castability or not.
When a Morph spell is on the stack, it's not an insect, hence it doesn't get the Zask "cast from graveyard" ability.
This seems to be Working as Intended.

**Comment by jimga150** [comment]
RIP my combo then. Thanks for pointing that out!
