### ISSUE TITLE
Spellskite says it is an invalid target but still is targeted

### ISSUE THREAD

**Issue by fireshoes** [magefree/mage#1269]
My opponent cast Lightning Bolt, targeting me. I redirected it to my Spellskite. The log window said Spellskite was an invalid target (though it should be valid). Spellskite still appeared to be targeted and took the damage, so just a log issue I guess.
![spellskite bug](https://cloud.githubusercontent.com/assets/8553747/9892558/9a4312f2-5bd5-11e5-9d1b-c8fefe4e1107.jpg)

**Comment by LevelX2** [comment]
Fixed.
