### ISSUE TITLE
Haktos the Unscarred needs hint to show which number was chosen.

### ISSUE THREAD

**Issue by tiera3** [magefree/mage#12707]
[[Haktos the Unscarred]]

After the card entered the battlefield, I hovered over it expecting to be able to find out which number it didn't have protection from - but there was no hint. I had to check the log column to find out.

**Comment by ssk97** [comment]
> [[Haktos the Unscarred]]
> 
> After the card entered the battlefield, I hovered over it expecting to be able to find out which number it didn't have protection from - but there was no hint. I had to check the log column to find out.

There definitely is a hint, maybe you just missed it? It's at the very bottom, "Chosen number: N". Onky visible on the battlefield, of course.

**Comment by tiera3** [comment]
Just did a test and it is there now. Odd. 
![image](https://github.com/user-attachments/assets/e43a7cc2-a524-4fa5-b79d-89a14a2a2280)

**Comment by JayDi85** [comment]
There are possible a diff between permanent and card popup.

Popup card hint can show:
* real object with all additional data and hints;
* original card only (without changes/actual rules and data).

It depends on the moment. As example: if permanent already moved to another zone then all card hints from that object (e.g. from game logs or triggers) can't find it and will show only original card.
