### ISSUE TITLE
Bandit's Talent ability is not implemented properly

### ISSUE THREAD

**Issue by N3utrn0** [magefree/mage#12701]
I want to report that It appears to me that the following Card [https://scryfall.com/card/blb/83/bandits-talent] was not implemented correctly.

The text says:

> When Bandit’s Talent enters, each opponent discards two cards unless they discard a nonland 

But I also have to do the same action.

**Comment by ssk97** [comment]
Thanks, fixed with 50940d6b4bf563f948fe764154a3d9fecb332da3, will be included in next update.
