### ISSUE TITLE
Launcher: Error: could not open...jvm.cfg'

### ISSUE THREAD

**Issue by evanmorici** [magefree/mage#1272]
Im trying to update Xmage because the launcher wouldnt load. When I went to update it, the update went fast. But the install, well lets just say, Ive been sitting here for an hour, and it hasnt even started yet.
This is the error message I get when I tried to open it at first: 
Error: could not open `C:\Users\Administrator\Downloads\java\jre1.7.0_75\lib\i386\jvm.cfg'

**Comment by hanasu** [comment]
Your path or your JVM version might be messed up. Can you run 'java -version' from the command line?

**Comment by BowOwner** [comment]
im having this same issue is there a fix yet?

**Comment by drmDev** [comment]
Isn't an issue with XMage, it's an issue with local installations of Java. See http://stackoverflow.com/questions/9051103/java-path-error-of-jvm-cfg for some ideas how to resolve.

**Comment by JayDi85** [comment]
How to fix:
1. delete `\xmage\java\` folder
2. open in `installed.properties` file in text editor
3. delete line `java.version=xxx` from that file and save
4. run launcher and press update again.
