### ISSUE TITLE
Missing Card?

### ISSUE THREAD

**Issue by astroavenger9** [magefree/mage#12735]
I believe Kemba's Outfitter is Missing.
![image](https://github.com/user-attachments/assets/196ec1ba-bb53-471c-a573-cd4c8d425a95)

**Comment by Grath** [comment]
Arena cards are only implemented on a case-by-case basis, and there is no current support for the "perpetually" mechanic.

**Comment by Svyatoslav28597** [comment]
Currently, but I can assure you that this hopefully won't be for too long
So I believe that Outfitter could be implemented until the end of this year

**Comment by astroavenger9** [comment]
> Arena cards are only implemented on a case-by-case basis, and there is no current support for the "perpetually" mechanic.

oh, didn't realize that was the case.

> Currently, but I can assure you that this hopefully won't be for too long So I believe that Outfitter could be implemented until the end of this year

sweet. looking forward to that.
