### ISSUE TITLE
Creating Skittering Skirge with gen-card causes 'set not found' error

### ISSUE THREAD

**Issue by hanasu** [magefree/mage#1275]
Output:

Enter a card name: Skittering Skirge
Files generated:
urzassaga.SkitteringSkirge
Set not found in known sets: Beatdown Box Set

**Comment by hanasu** [comment]
Storm Seeker has the same problem with Chronicles.

**Comment by drmDev** [comment]
considering both cards are implemented and this was an issue with the gen-card script, and this issue is over a year old - closing
