### ISSUE TITLE
Empty the Laboratory death triggers

### ISSUE THREAD

**Issue by skaspels** [magefree/mage#12770]
I have seen this happen in game several times, but am not 100% positive that it isn't functioning as designed;
During the resolution of the [[Empty the Laboratory]], it often happens that spell finds a zombie that cares about when zombies die, like [[Archghoul of Thraben]]. When this happens, the game places an [[archghoul of thraben]] trigger on the stack for each of the zombies I sacrificed to the spell - I had thought that the resolution of the spell, the entering zombies will not see the zombies that died, but I could be wrong.

**Comment by xenohedron** [comment]
probably missing processAction
