### ISSUE TITLE
Game error on usage Leonardo da Vinci (wrong filter settings for BoostControlledEffect)

### ISSUE THREAD

**Issue by elvarik** [magefree/mage#12774]
Error type: SERVER - game error
Client version: 1.4.53-V1 (build: 2024-08-16 15:36)

Game error occurred: 

java.lang.ClassCastException: mage.game.permanent.PermanentToken cannot be cast to mage.players.Player
Server version: 1.4.53-V1 (build: 2024-08-16 15:36)
Stack trace:
mage.constants.TargetController$PlayerPredicate.apply(TargetController.java:111)
mage.constants.TargetController$PlayerPredicate.apply(TargetController.java:101)
mage.filter.FilterPermanent.lambda$match$0(FilterPermanent.java:60)
java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1361)
java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499)
java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486)
java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
java.util.stream.ReferencePipeline.allMatch(ReferencePipeline.java:521)
mage.filter.FilterPermanent.match(FilterPermanent.java:60)
mage.game.permanent.Battlefield.lambda$getActivePermanents$10(Battlefield.java:249)
java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
java.util.Iterator.forEachRemaining(Iterator.java:116)
java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
mage.game.permanent.Battlefield.getActivePermanents(Battlefield.java:250)
mage.abilities.effects.common.continuous.BoostControlledEffect.init(BoostControlledEffect.java:80)
mage.game.GameImpl.addEffect(GameImpl.java:1949)
mage.abilities.AbilityImpl.resolveMode(AbilityImpl.java:238)
mage.abilities.AbilityImpl.resolve(AbilityImpl.java:209)
mage.game.stack.StackAbility.resolve(StackAbility.java:85)
mage.game.GameImpl.resolve(GameImpl.java:1804)
mage.game.GameImpl.playPriority(GameImpl.java:1727)
mage.game.turn.Step.priority(Step.java:67)
mage.game.turn.Phase.playStep(Phase.java:205)
mage.game.turn.Phase.play(Phase.java:91)
mage.game.turn.Turn.play(Turn.java:137)
mage.game.GameImpl.playTurn(GameImpl.java:1151)
mage.game.GameImpl.play(GameImpl.java:1058)
mage.game.GameImpl.start(GameImpl.java:1034)
mage.server.game.GameWorker.call(GameWorker.java:35)
mage.server.game.GameWorker.call(GameWorker.java:16)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:750)

**Comment by tomaszrybicki** [comment]
Issue occurred when playing recently added card's Leonardo da Vinci ability "Until end of turn, Thopters you control have base power and toughness X/X, where X is the number of cards in your hand.".

With 2 Thopters on the table, along with Sai Master Thopterist, Bident of Thassa, and several others.
