### ISSUE TITLE
Refactor needed for "second main phase"

### ISSUE THREAD

**Issue by theelk801** [magefree/mage#12788]
The phrases "precombat main phase" and "postcombat main phase" have been replaced with "first main phase" and "second main phase" respectively. This is a functional change in the latter case, as additional main phases won't trigger those abilities. However, this is further wrinkled by the fact that there is a partial reverting of this change that hasn't applied yet according to Matt Tabak. So some older cards will still say "postcombat main phase" but their oracle text hasn't been reverted yet and won't until Duskmourn releases.

**Comment by JayDi85** [comment]
DSK release notes published, so main phase changes can be fully researched now:
https://magic.wizards.com/en/news/feature/duskmourn-house-of-horror-release-notes

**Comment by JayDi85** [comment]
Related article about phase changes and card examples: https://mtgrocks.com/postcombat-main-phase-change/

* [x] Cards like [[Aggravated Assault]] must add additional main phases, not first/second (already supported). There are [8 cards](https://scryfall.com/search?q=o%3A%22additional+main+phase%22&unique=cards&as=grid&order=name) with additional main phase effects.

* [ ] Make sure cards like [[Chancellor of the Tangle]] trigger one time per game. Old rules text “first main phase” replaced with “first main phase of the game”. There is only one card with such texts and looks like it must be fixed.

I don’t think it requires any code renaming from precombat to first and post combat to second. Official rules still use it, see “505. Main Phase” (from blb update). Maybe will be changed in later rules release (with dsk).

**Comment by Grath** [comment]
> * [ ]  Refactor all triggers with EventType.POSTCOMBAT_MAIN_PHASE*  and EventType.PRECOMBAT_MAIN_PHASE* to check “not extra”.

Worth noting: Not everything is being changed away from "postcombat main phase", but they still haven't reverted the errata yet on Neheb to make it still function during extra main phases: 
https://x.com/WotC_Matt/status/1816524550433329385

So we still need to wait for them to finish up the Duskmourn updates to find out exactly which 11 cards, besides Neheb the Eternal, Brazen Cannonade, and Megatron, Tyrant, are still getting to work during extra postcombat main phases.

**Comment by theelk801** [comment]
Update: we now have a [list](https://scryfall.com/search?q=o%3Apostcombat) of all the cards that will still say "postcombat main phase"
