### ISSUE TITLE
Bug with custom targets of limited total value

### ISSUE THREAD

**Issue by xenohedron** [magefree/mage#12806]
Reported bugs with [[Call of the Death-Dweller]] and [[Nethroi, Apex of Death]] not functioning properly due to the ability fizzling.

Call targeting a single Kraken Hatchling (mv1) works. Targeting a Kraken Hatchling and a Fugitive Wizard (mv1+mv1) works. Targeting a single Seacoast Drake (mv2) does not. So it seems to me that somehow the targeting check is calling it again and then failing.

[Scryfall search for potentially impacted cards](https://scryfall.com/search?q=o%3A%22with+total%22+o%3A%22or+less%22&unique=cards&as=grid&order=name)

It looks like a similar issue with [[Kairi, the Swirling Sky]] was fixed in 8a6b39c.

Furthermore, these custom target classes aren't overriding `possibleTargets` and ought to.

Ideally some code could be shared instead of rewriting custom classes for each of these targets, though with the current inheritance hierarchy I can't think of a particularly clean way to do it.

**Comment by JayDi85** [comment]
Looks like an original problem in wrong target implementation -- it's try to simulate manual adding/removing ids instead all methods implementation like isLegal, etc.

![shot_240906_083926](https://github.com/user-attachments/assets/86786cd2-07ed-4f6f-b0c4-f8001d128dbf)

I'll look at it later -- must be compatible with legality checking, human's select/deselect and AI targeting/simulations.
