### ISSUE TITLE
Catch unknown error while downloading java.lang.IllegalArgumentException: Wrong code usage: scryfall used unique card numbers, but found duplicated: Spike Feeder/tpr/196/en - IllegalArgumentException

### ISSUE THREAD

**Issue by Jono-Moss** [magefree/mage#12817]
When Downloading card images, I get the following error:

Error type: Catch unknown error while downloading java.lang.IllegalArgumentException: Wrong code usage: scryfall used unique card numbers, but found duplicated: Spike Feeder/tpr/196/en - IllegalArgumentException
Client version: 1.4.53-V1 (build: 2024-08-16 15:36)

Wrong code usage: scryfall used unique card numbers, but found duplicated: Spike Feeder/tpr/196/en

Stack trace:
org.mage.plugins.card.dl.sources.ScryfallImageSource.createBulkImagesIndex(ScryfallImageSource.java:609)
org.mage.plugins.card.dl.sources.ScryfallImageSource.analyseBulkData(ScryfallImageSource.java:503)
org.mage.plugins.card.dl.sources.ScryfallImageSource.prepareDownloadList(ScryfallImageSource.java:253)
org.mage.plugins.card.images.DownloadPicturesService.run(DownloadPicturesService.java:645)
java.lang.Thread.run(Thread.java:748)

**Comment by JayDi85** [comment]
It's scryfall's broken data with duplicated records in bulk source:
* Oracle Cards source - not affected
* Unique Artwork source - not affected
* Default Cards source - not affected
* All Cards source - has duplicated BUG, file link (warning, 2 GB file): https://data.scryfall.io/all-cards/all-cards-20240906215102.json
* Rulings - non relevant

Spike Feeder, TPR
https://scryfall.com/card/tpr/196/spike-feeder

Scryfall id: 090a5f1f-9a1a-4e93-8c33-a0204c2917d5


Lines with duplicated records (it's fully identical lines):
17001
17002

![shot_240907_124750](https://github.com/user-attachments/assets/e022c65f-8ce6-49e6-a9f6-f3e6e1f44a11)
