### ISSUE TITLE
Issues with domains

### ISSUE THREAD

**Issue by Dunkoro** [magefree/mage#12812]
"Website" button in launcher points to xmage.de
xmage.de seems to be a domain that's available to be bought.
This could easily lead to some phishing attempts or whatnot.

http://rkfg.me/xmage/config.json also seems to not be a real link right now, the launcher is complaining about that.

**Comment by xenohedron** [comment]
The solution is to distribute an updated version of the launcher with the currently maintained website / config source. For whatever reason @JayDi85 is still distributing the old 0.3.8 launcher.

see https://github.com/magefree/Launcher/issues/23

**Comment by JayDi85** [comment]
@xenohedron Nope, it’s just old install files that was downloaded from de-site. I distribute good config from http://xmage.today/

**Comment by xenohedron** [comment]
You're wrong.

The launcher you distribute still has the hardcoded branches:
![image](https://github.com/user-attachments/assets/0ccfff74-7092-4ee3-9af1-8221e67cf595)

It's easy for a user to accidentally scroll on that dropdown when opening settings, and lose the good custom config for xmage.today.

Same thing with clicking the "Website" button in the launcher, it brings you to xmage.de.

That is what needs to be updated. You can find it in launcher repository, already has been updated, but you don't distribute latest version.

**Comment by xenohedron** [comment]
@JayDi85 why are you closing this issue? Are you going to start distributing an updated launcher?
