### ISSUE TITLE
Gisela, Blade of Goldnight's ability to prevent half of incoming damage does not function properly

### ISSUE THREAD

**Issue by apferran** [magefree/mage#12848]
I think the calculation for Gisela's second ability to prevent half of any incoming damage is rounding DOWN instead of UP when damage is received. If you deal 9 damage to Gisela, only 4 damage is received. Also, if a source would deal 1 damage to me, I receive no damage. I've tested this in a few different scenarios while testing a deck that I'm working on, and I'm confident that there are no other factors manipulating her ability.

**Comment by Dunkoro** [comment]
The prevented damage is rounded up, so those numbers seem correct.
[[Gisela, Blade of Goldnight]]
