### ISSUE TITLE
Evoke wont work

### ISSUE THREAD

**Issue by xariskaliakatsos** [magefree/mage#12843]
Tried to cast Nulldrifter (https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=662165) and the draw trigger never happened.

**Comment by JayDi85** [comment]
There was a bug with double alternative payment on Nulldrifter and similar cards. Fixed by 4bce1e0a9a72f829a0f94ac2c85e1ad6e7e951ee
