### ISSUE TITLE
Miss booster from REX - Jurassic World Collection

### ISSUE THREAD

**Issue by OmNomSnom** [magefree/mage#12854]
I'm not sure if this is even the right place to post this but could someone add the missing cards from the Jurassic world collection set?

**Comment by PurpleCrowbar** [comment]
Aren’t they all implemented? #11240

**Comment by JayDi85** [comment]
All cards implemented, but booster disabled/miss

https://mtg.fandom.com/wiki/Jurassic_World_Collection

**Comment by OmNomSnom** [comment]
Idk what that means. I just want to play my Indominus Rex, Alpha deck and
it doesn't exist on there as well as a few of the other ones from that
collection.

**Comment by xenohedron** [comment]
Cards are all implemented and can be seen in deck editor:

![image](https://github.com/user-attachments/assets/dcce73a2-29c4-44f4-9a42-939c8d7fdfbe)

REX does not have boosters, that's irrelevant.

**Comment by OmNomSnom** [comment]
Awesome, thanks!
