### ISSUE TITLE
unable to install xmage on windows 8.1

### ISSUE THREAD

**Issue by chameleonist** [magefree/mage#1287]
i am attempting to load xmage on my new laptop equipped with windows 8.1 and it doesn't know how to do it and neither do i. i had it on my laptop that was running windows 7, but i am having zero luck... any help would be greatly appreciated

**Comment by hanasu** [comment]
What about it doesn't work? How far did you get in the process? Do you see any specific error messages?

**Comment by chameleonist** [comment]
i have down;loaded from the site, but that is all it will allow me to do, i have tried unpacking it several times and for whatever reason, it only makes a file folder which brings me back to the source i used to unzip it... i am clueless as to how i am goin gto be able to actually get to use the program

**Comment by chameleonist** [comment]
any idea what "App" i should use to open it up?

**Comment by LevelX2** [comment]
You need to install java runtime environment on your system before you can use the Xmage Launcher.

It's point one on the list.
http://www.slightlymagic.net/forum/viewtopic.php?f=70&t=13632&sid=173895d0b804bb1354d54673e7ff32cc
