### ISSUE TITLE
Bruna won't allow attaching auras from the battlefield if it's equipped.

### ISSUE THREAD

**Issue by Tharkon** [magefree/mage#12874]
If [[Bruna, Light of Alabaster]] has an equal or greater number of equipments attached to it than the amount of auras on the battlefield that are not attached to Bruna, you are not allowed to attach any of those auras to Bruna.

This could be because of line 103 where it counts sourcePermanent.getAttachments().size() which I presume also counts equipments.

**Comment by xenohedron** [comment]
Nice find. Rather silly code there.
