### ISSUE TITLE
Echoing Deeps copying Urza's Saga causes saga ability to trigger twice

### ISSUE THREAD

**Issue by Cytocide** [magefree/mage#12887]
When using [echoing deeps](https://scryfall.com/card/lci/271/echoing-deeps) to copy an [urza's saga](https://scryfall.com/card/mh2/259/urzas-saga) in the graveyard, the saga immediately goes to the second chapter. More specifically, it seems to gain the first and second saga ability simultaneously, and twice, upon entering

**Comment by ssk97** [comment]
Duplicate issue, see #12475
