### ISSUE TITLE
Legion's Initiative is still not working

### ISSUE THREAD

**Issue by Reya87** [magefree/mage#12927]
Hello,

[[Legion's Initiative]] is not working as intended. I saw the last issue I created about this card was closed but the card is still not working. Your creatures stay in exile when you use the activated ability of the enchantment.

**Comment by ssk97** [comment]
Unless you're compiling from source and running your own server, you'll need to wait for the next update to go out for the fix to apply.

**Comment by Reya87** [comment]
But I thought it was fixed because we had an update after the issue was marked as closed

**Comment by ssk97** [comment]
> But I thought it was fixed because we had an update after the issue was marked as closed

The bug was fixed in 26fde06d1611b142d5bbd167b9d296a40e56125b, 2 days ago. The last release was 3 days ago.
