### ISSUE TITLE
The Mindskinner not milling

### ISSUE THREAD

**Issue by ParzivaLore** [magefree/mage#12957]
The Mindskinner has not been milling. I played multiple games and it never made any opponent mill. After the damage was prevented, the opponents were not milled at all, in the game history it said that the damage had been prevented and nothing else. It also incorrectly prevented damage assigned to a planeswalker.

**Comment by Grath** [comment]
Not milling was fixed by 554ba8739e93ce1c3b50bf6243906fd288d422d0 and it's preventing damage to creatures and planeswalkers; should have that fixed soon, and then it will work correctly after the next update.

**Comment by Grath** [comment]
Fixed by 3b433f9b359901c6a8b3e8a6b5959ed45c683645 - will be working properly after the next update.
