### ISSUE TITLE
Back side of Invasion of Fiora triggers improperly

### ISSUE THREAD

**Issue by Cytocide** [magefree/mage#12958]
The flip side of [Invasion of Fiora](https://scryfall.com/card/mom/114/invasion-of-fiora-marchesa-resolute-monarch) (Marchesa, Resolute Monarch) appears to trigger the combat damage clause incorrectly. You draw a card and lose the life if you have taken damage, not if you haven't. It is supposed to be the other way around.

**Comment by paasar** [comment]
Hi! I'm a new XMage user / software developer.

I made a fix to Marchesa, Resolute Monarch. You can find it here:
https://github.com/magefree/mage/pull/12994

Also, I had to update the `sqlite-jdbc` to be able to run it on my machine.
Its PR here:
https://github.com/magefree/mage/pull/12993
