### ISSUE TITLE
Nezumi Graverobber's pre-flip ability won't activate unless you exile at least 1 card from opponents graveyard

### ISSUE THREAD

**Issue by mixlunar** [magefree/mage#1297]
Specifically the Champions of Kamigawa card. I'm not sure if the Commander card has the same issue. I looked at the logic but couldn't figure out where it was going wrong. Maybe someone with more experience can figure it out.

**Comment by LevelX2** [comment]
Sounds like Nezumi Graverobber works as it should.
You can't activate the ability (so you can't flip it) if there is no card in an opponent's graveyard you can target.

http://www.mtgsalvation.com/forums/magic-fundamentals/magic-rulings/magic-rulings-archives/253846-nezumi-graverobber-quickie
