### ISSUE TITLE
Enduring Courage not working

### ISSUE THREAD

**Issue by RiskStar-RG** [magefree/mage#12980]
its main ability of giving creatures +2/+0 and haste when it enters is not triggering.

**Comment by Grath** [comment]
It doesn't do that. If gives +2/+0 and haste when something else enters.

**Comment by RiskStar-RG** [comment]
My enduring courage was on the battlefield. Another creature entered and did not gain the haste and +2/+0 the card says it gives when a creature enters

**Comment by xenohedron** [comment]
Was fixed by https://github.com/magefree/mage/commit/f690ddd4de7afc8479e312e41766d4f2587c96d9

Wait for next release
