### ISSUE TITLE
Request: save previous Local AI match player configs (Commander)

### ISSUE THREAD

**Issue by 4ndrewCox** [magefree/mage#12981]
For example: Commander Casual Free-For-All configs only seem to be saved after server restart for player1 (You) deck, but not for any other players past that (it instead defaults to random deck generation, which does not apply for Commander).

The previously selected skill level and deck should be set automatically for that player when a new match is created.

If possible please also default the skill level to 10 for the computer.
edit: never mind about the skill level default.

![image](https://github.com/user-attachments/assets/8180803d-73ad-492a-a918-c71c9c0cf302)

**Comment by jeffwadsworth** [comment]
Note that the 10 level is overkill in almost all cases.  2 is fine unless you have a ZX81.

**Comment by 4ndrewCox** [comment]
> Note that the 10 level is overkill in almost all cases. 2 is fine unless you have a ZX81.

Oh I wasn't aware of that. Sure, never mind on that.
