### ISSUE TITLE
refactor: "return all xxx from your graveyard to the battlefield"

### ISSUE THREAD

**Issue by xenohedron** [magefree/mage#12992]
These should be a common class

[scryfall search for potential cards in scope](https://scryfall.com/search?q=o%3A%22return+all%22+o%3A%22from+your+graveyard+to+the+battlefield%22&unique=cards&as=grid&order=name)

_Originally posted by xenohedron in https://github.com/magefree/mage/pull/12991#pullrequestreview-2363667449_

**Comment by JayDi85** [comment]
Looks like some cards are wrongly implemented — miss process action call after move to xxx and before move from xxx:

[[Angel of Glory's Rise]]

![IMG_0896](https://github.com/user-attachments/assets/ecd375bc-f74d-4f3b-9ab5-2447861c4e81)

**Comment by xenohedron** [comment]
yeah when I rewrite things like that to common effects that'll be fixed
