### ISSUE TITLE
Xmage keeps telling me to update

### ISSUE THREAD

**Issue by siaoidiot** [magefree/mage#1299]
Downloaded the update as usual, but a window keeps popping up after each time saying that a new version is available and I'm still using the old version.
If i reinstall xmage in a new folder, it doesn't download the client and the xmage folder is left empty.

**Comment by siaoidiot** [comment]
![ss 2015-10-05 at 12 43 47](https://cloud.githubusercontent.com/assets/14965840/10268940/2b384c9a-6afa-11e5-9ce8-0c77e0dd89f3.jpg)

**Comment by LevelX2** [comment]
Are you running the xmage client while updating?
Is there a  subfolder xmage in C:Users/Shaun/Desktop/Xmage/?
What written to the launcher log file?

**Comment by siaoidiot** [comment]
1) nope
2) yes and there's nothing inside
3) http://pastebin.ca/3181572

**Comment by Zerrisx** [comment]
This looks to have been resolved or abandoned; closing as such.
