### ISSUE TITLE
Triggered abilities of the night side on the stack are shown with the name and image of the day side. 

### ISSUE THREAD

**Issue by LevelX2** [magefree/mage#130]
Triggered abilities of the night side on the stack of transformable cards are shown with the name and image of the day side. Correct would be to show name and image of the night side.
![ScornedVillager](https://f.cloud.github.com/assets/2066790/141922/e0aa8912-7296-11e2-908f-5e20be365d35.jpg)
![ScornedVillager](https://f.cloud.github.com/assets/2066790/141925/f9f8de96-7296-11e2-9237-12f85ff5b3a6.jpg)

**Comment by emerald000** [comment]
Fixed in a past update. Closing.
