### ISSUE TITLE
minimum screen resolution

### ISSUE THREAD

**Issue by brobostigon** [magefree/mage#1300]
Is there a minimum screen resolution, linux or windows, that allows the showing of the whole board during a game.
i am on my eeepc which is 1024×600, and while a small screen and resolution, was expecting it to scale properly, not cutof half the board.
is there a solution to this?

**Comment by LevelX2** [comment]
I guess no. 
With 600 vertically you won't be able to see the scroll bars of hand and stack.
Don't expect a solution for your screen resolution.

**Comment by brobostigon** [comment]
ok, thank you.

**Comment by velusopensource** [comment]
levelx2 i would love to see a solution to thsi please
