### ISSUE TITLE
Enduring Courage Triggers Does Nothing on Resolution

### ISSUE THREAD

**Issue by TamJams** [magefree/mage#13013]
I was playing a game earlier and I had an Enduring Courage out, it hadn't died so it was still a creature.  I played my commander (Deathleaper, Terror Weapon but I don't think it is really relevant), the Enduring Courage triggered but on resolution did nothing.  Next I played You See a Pair of Goblins and chose the mode to create 2 goblin tokens.  They entered, Enduring Courage triggered twice, but again did nothing - they still had the chains around them representing summoning sickness and had no power buff.  

Neither of my opponents had anything to prevent my triggers, or to keep my creatures from getting the buff or anything, so I think the Enduring Courage resolution just doesn't work properly.  In the game log it even showed the ability trigger, but no log to show it resolve or anything.

**Comment by Grath** [comment]
Fixed by f690ddd4de7afc8479e312e41766d4f2587c96d9 - will be included in next release.
