### ISSUE TITLE
Unable to launch client OR server

### ISSUE THREAD

**Issue by ThanosIsKing** [magefree/mage#13025]
Getting an error whenever I launch the java part of the game. It reads:

"Reading config from http://xmage.de/xmage/config.json
Error reading config from http://xmage.de/xmage/config.json
Possible causes: Site is offline or internet connection is unavailable."

My internet is working fine and is stable. Any fixes please?

**Comment by Grath** [comment]
Go to your launcher settings and change them to this:
![image](https://github.com/user-attachments/assets/cfef9b25-d057-4616-98e2-966d71dfb1c4)

**Comment by ScamArtist123** [comment]
I am also experiencing this issue. I have set the launcher settings as recommended by Grath, but it does not seem to have made a difference. I continually receive the following error : 

"Reading config from http://xmage.today//config.json
Invalid config from http://xmage.today//config.json"

**Comment by xenohedron** [comment]
Don't put a trailing slash after xmage.today

Anyway, this is launcher config issue, no action for this codebase

**Comment by ScamArtist123** [comment]
I removed the slash several times and it auto adds it back. Nothing I can do to change that on my end unfortunately.

**Comment by JayDi85** [comment]
@ScamArtist123 go to https://xmage.today/ and follow instructions to download full client and run it by run-launcher file. Don't use old version.

**Comment by ScamArtist123** [comment]
I redownloaded xmage from https://xmage.today/ and ran the "run-launcher" file. This did fix the issue with the extra slash in the launcher settings, however it still presents the following error: 


"Error reading config from xmage.today/config.json
Possible causes:  Site is offline or internet connection is unavailable."


This time it does not have the extra slash in the error but it is still persisting.

**Comment by JayDi85** [comment]
Try to open that link in browser and show that you see: https://xmage.today/config.json

**Comment by ScamArtist123** [comment]
https://xmage.today/config.json loads the following page:

{
  "java": {
    "version": "1.8.0_201",
	"location": "http://xmage.today/java/jre-8u201-"
  },
  "XMage": {
    "version": "1.4.54-dev (2024-09-25 13-04)",
    "location": "http://beta.xmage.today/files/mage-update_1.4.54-dev_2024-09-25_13-04.zip",
    "locations": [],
	"full": "http://beta.xmage.today/files/mage-full_1.4.54-dev_2024-09-25_13-04.zip",
    "torrent": "",
    "images": "",
    "Launcher": {
      "version": "0.3.8",
      "location": "http://bit.ly/xmageLauncher038"
    }
  }
}


Image of page attached. 
![Xmage_json_config](https://github.com/user-attachments/assets/7ecf17c7-7017-49f0-8321-22fd82657c39)

**Comment by ScamArtist123** [comment]
After removing all files related to xmage, redownloading it, and opening via run-LAUNCHER.cmd, I receive a new error stating that the syntax for the JSON file is incorrect. I have attached an image of the console. 
![Xmage_JSON_Issue](https://github.com/user-attachments/assets/c4cd92d5-7cdb-4ce1-9913-f24bc82fe684)

**Comment by JayDi85** [comment]
Wrong json file — something wrong with your internet provider or network — it’s restrict you to download config file and return some kind of web page like access restriction by your organization. Ask your admin about network access.

As workaround you can download java manual, see instructions here: https://github.com/magefree/mage/issues/12768

You must unpack all java files to launcher/java/jre1.8.0_201 folder and edit install.properties file in launcher folder with text editor to insert java version as “1.8.0_201“ (instead empty value in fresh install). After that you can run client from a launcher.
