### ISSUE TITLE
Keen-Eyed Curator's static ability doesn't work

### ISSUE THREAD

**Issue by sd-jazz** [magefree/mage#13022]
Keen-Eyed Curator does not get +4/+4 and trample when it exiles 4 or more card types. When you hover over the card, the count for exiled card types is always 0. 

<img width="1280" alt="Screen Shot 2024-10-22 at 9 43 38 AM" src="https://github.com/user-attachments/assets/4ca23364-a43e-483c-aade-d05d1d1048fa">

**Comment by jeffwadsworth** [comment]
[[Keen-Eyed Curator]]

**Comment by JayDi85** [comment]
Real reason in diff effects with diff zcc:
- static abilities init from start of the game, e.g. zcc = 0
- activated abilities init on usage, e.g. zcc = 123

So keen's zone must be found from real object zcc, not effect's `getSourceObjectZoneChangeCounter`.

No needs in custom effect, `ExileTargetForSourceEffect` is fine. Simpler fix by c265e640bb74a28dfa458ec2b419183c2aff9d5d
