### ISSUE TITLE
Computer casting Famine damages Planeswalker.

### ISSUE THREAD

**Issue by Exolight** [magefree/mage#1304]
![b972990595e93261a528ea78038ef9ab](https://cloud.githubusercontent.com/assets/4651937/10333867/dd7a5cae-6ca3-11e5-841a-d6311cd89814.jpg)

As you can see from the box on the bottom right, the Computer was able to "redirect" loss of life from me to my planeswalker, Liliana Vess. It states that it redirected damage, but Famine did not actually deal any damage.

**Comment by LevelX2** [comment]
Famine deals 3 damage to each creature and each player.

306.7. If noncombat damage would be dealt to a player by a source controlled by an opponent, that opponent may have that source deal that damage to a planeswalker the first player controls instead. This is a redirection effect (see rule 614.9) and is subject to the normal rules for ordering replacement effects (see rule 616). The opponent chooses whether to redirect the damage as the redirection effect is applied.

As Famine deals damage to you the AI is able to redirect this damage to your planeswalker.
Sounds all correct to me. If I didn't got something let me know.
