### ISSUE TITLE
Come Back Wrong targeting a token causes a NullPointerException

### ISSUE THREAD

**Issue by sd-jazz** [magefree/mage#13056]
Got a NullPointerException when resolving Come Back Wrong targeting a token. Probably threw the error since it's looking for a creature card but didn't find one. 

<img width="1280" alt="Screen Shot 2024-11-02 at 10 33 23 PM" src="https://github.com/user-attachments/assets/4cf90518-ecfa-469f-abc6-e8786ff1c3b7">

**Comment by jeffwadsworth** [comment]
[[Come Back Wrong]]

**Comment by JayDi85** [comment]
@jeffwadsworth real error in null check typo — must check creature variable (copied cards also cease of exist in graveyard by sba like a tokens);

![IMG_0989](https://github.com/user-attachments/assets/1cf4132f-6c4b-4a49-bd5b-f930750fc9ae)
