### ISSUE TITLE
Marvel Secret Lair

### ISSUE THREAD

**Issue by OmNomSnom** [magefree/mage#13050]
Is anyone working on the new Marvel secret lair?
Also is there any hope for mutate to come to Xmage?

**Comment by JayDi85** [comment]
1. Yep, marvel cards will be added, just wait some time
2. Nope, mutate too hard (incompatible with current xmage game engine) and will be added someday in the future after double faced cards rework.

P.S. @theelk801 Secret Lair is global and constant updated set with diff themes inside. Maybe it’s better to add specific topics per each theme? E.g. new cards from marvel, new cards from pony, etc. It’s can help to control and find unimplemented cards https://magic.wizards.com/en/news/announcements/secret-lair-marvel-superdrop

**Comment by OmNomSnom** [comment]
Okay thank you

**Comment by Grath** [comment]
The new Marvel cards are all implemented, all the reprints are added (except the tokens), and will be available after the next update.
