### ISSUE TITLE
Enduring Courage Doesn't Buff Entering Creatures

### ISSUE THREAD

**Issue by JelloPiranha** [magefree/mage#13052]
Not sure if it works in creature form, but in enchantment form, Enduring Courage isn't giving entering creatures +2/+0 and haste. Maybe it's trying to give itself the buff, but it's not a creature? That's my best guess for why it isn't working, but I have no idea how this stuff actually functions. Thanks for all the work you guys do!

Update: Enduring Courage also buffs nothing while in creature form.

![EnduringCourage](https://github.com/user-attachments/assets/19c15330-844d-4f04-90c1-7c7a1fe04c9b)
Pictured: Mishra has just entered, and Enduring Courage has triggered, but nothing happens when the ability resolves. I know it isn't a targeted ability, but similar abilities like Ardoz, Cobbler of War do point at the newly entered creature.

**Comment by Grath** [comment]
Fixed by f690ddd4de7afc8479e312e41766d4f2587c96d9 and will be working properly after the next update.
