### ISSUE TITLE
Individual triggers on mass damage events can't be handled correctly

### ISSUE THREAD

**Issue by ciaccona007** [magefree/mage#13057]
There are a few permanents that trigger whenever another permanent deals damage. These include [Justice](https://scryfall.com/card/5ed/41/justice), [Noble Purpose](https://scryfall.com/card/8ed/31/noble-purpose), and new card in FDN [Quilled Greatwurm](https://scryfall.com/card/fdn/111/quilled-greatwurm).

Currently, these effects are implemented by checking a GameEvent and seeing if it is an instance of either `GameEvent.EventType.DAMAGED_PERMANENT` or `GameEvent.EventType.DAMAGED_PLAYER`. However, this means that when a creature deals damage to two permanents/players, the ability will trigger twice, when it should only trigger once.

Replicate with the following `init.txt`:
```
battlefield:Human:Noble Purpose:1
battlefield:Human:Grand Melee:1
battlefield:Human:Hill Giant:1
battlefield:Computer:Gray Ogre:2
```

In this scenario, Human attacks with Hill Giant, it's double blocked, and it deals 2 damage to the first Gray Ogre and 1 to the second. Noble Purpose should only trigger once and gain 3 life, but instead it triggers twice to gain 2 and 1 life in succession.

This is a pretty minor issue but it's a bit more noticeable with the new card Quilled Greatwurm, where players might care about the correct behavior. One example is abilities that care about the number of +1/+1 counters being added to permanents. An example is [Winding Constrictor](https://scryfall.com/card/aer/140/winding-constrictor) which will add too many counters to creatures that deal damage, if the current implementation is used.

I tried working around this issue using `GameEvent.EventType.DAMAGED_BATCH_FOR_ALL`, but I couldn't get it to work. Maybe I haven't dug deep enough though, so let me know if there's a better workaround!

**Comment by JayDi85** [comment]
> GameEvent.EventType.DAMAGED_BATCH_FOR_ALL, but I couldn't get it to work

What’s wrong with batch event usage? Double batches, miss event, etc?

**Comment by JayDi85** [comment]
`DAMAGED_BATCH_FOR_ONE_PERMANENT` -- all damages for one creature:

![shot_241105_012218](https://github.com/user-attachments/assets/fbf40cd0-c6ef-4abd-bb37-5cd4c081aeca)

**Comment by JayDi85** [comment]
ok, I see the problem. You need group damage events per attacking creature, not per target.

Justice:
> Whenever a red creature or spell deals damage, Justice deals that much damage to that creature’s or spell’s controller.

Oracle:
> If a single source does damage to multiple targets at once, Justice will add up all the damage done and deal damage to the source’s controller at one time (not multiple separate damagings). (2004-10-04)
> The damage done by Justice is done as a triggered ability, which is added to the stack just after the red creature or spell deals its damage. (2004-10-04)

So there are must be one trigger per triggered/attacking creature

**Comment by JayDi85** [comment]
Well, there are possible two solutions:
1. Recommended. Add new batch event and related code: `DAMAGED_BATCH_FOR_ONE_ATTACKER` -- same as `DAMAGED_BATCH_FOR_ONE_PERMANENT ` but group by attacker id;
2. Override `trigger` method to simulate multiple calls:
``` java
    @Override
    public void trigger(Game game, UUID controllerId, GameEvent triggeringEvent) {
        // simulate multiple triggers (damages collected on checkTrigger) 
        this.damages.forEach(damage -> {
            this.getEffects().clear();
            this.getEffects().add(new GainLifeEffect(damage));
            super.trigger(game, controllerId, triggeringEvent);
        });
    }
```

**Comment by xenohedron** [comment]
scope: https://scryfall.com/search?q=o%3A%2FWhenever+a.*+deals.*+damage%2C+%2F&unique=cards&as=grid&order=name
