### ISSUE TITLE
Deck builder piles

### ISSUE THREAD

**Issue by jonhwoods** [magefree/mage#1305]
Two suggestions for the deck editor piles:
- Make piles bigger then the vertical height "wrap around" and create an other pile
- When sorting by casting cost, do not put lands in the same pile as 0cc spells or X spells

Piling the main deck by casting cost and the sideboard by name is quite ergonomic, but these two things would improve it a lot.

Current issue:
![image](https://cloud.githubusercontent.com/assets/12401535/10354808/ea0bad4a-6d31-11e5-9650-3aa1d64fd67c.png)

**Comment by JayDi85** [comment]
Not actual
