### ISSUE TITLE
Blank Client Console

### ISSUE THREAD

**Issue by jestemwlodek** [magefree/mage#13051]
![image](https://github.com/user-attachments/assets/ec5772ae-f42e-4253-a185-eadfc9cc84b1)

![image](https://github.com/user-attachments/assets/d68426e9-7b05-4658-a932-8608606948d1)

![image](https://github.com/user-attachments/assets/158ab263-298e-43c6-8b72-2fd0788a6b87)

What do I do?

**Comment by JayDi85** [comment]
Something wrong with your network settings.

1. Make sure you are using run-launcher file to run app
2. Close all java apps and move launcher files to new folder, so you can run it and firewall will ask your network access again
3. Run launcher - settings - make sure no network/proxy settings there
4. If not helps then open http://xmage.today/config.json in your browser — it must show json settings, not a warning messages from your network admin

**Comment by jestemwlodek** [comment]
1. I am running that.
2. I moved the launcher to a new folder, firewall never asked me about nothing.
3. Here's the settings:

![image](https://github.com/user-attachments/assets/6981c945-7b07-4b35-bdd5-63b8c2c8b12e)

5. No warning messages here.

**Comment by JayDi85** [comment]
Well, it's restrict network access to your default java (launcher uses default, client/server inner java from download). You can write in command line "where java" to find installed path. Maybe java re-install from https://java.com/ will help. If not then try to find your firewall settings and delete or enable network access for java.exe

P.S. Not related to network problems, but do not put game in program files -- it need write access to launcher and app folders, and do not support to run under admin. Use any folder like c:\games\x Also do not put in user related paths (it's can be broken with non-ascii user names).

**Comment by JayDi85** [comment]
As alternative run:
1. Download zip and unpack it to any folder: https://adoptium.net/temurin/releases/?os=windows&arch=x64&package=jre
2. Open `run-launcher.cmd` in text editor
3. Replace `java` by full path to downloaded and unpacked java like: `D:\SOFT\JAVA\openjdk-21\bin\java.exe`
![shot_241031_232707](https://github.com/user-attachments/assets/24a98c2d-106d-4a34-a23f-1da66900e477)

**Comment by jestemwlodek** [comment]
Whitelisting java apps in the firewall settings changed nothing.
![image](https://github.com/user-attachments/assets/5596b4a3-0822-49a9-baf5-5e874c31b0a2)
I did the alternative run and it gave me the same result.
![image](https://github.com/user-attachments/assets/1f335e4a-ca62-48c6-854e-ef93a7eb0e7d)

**Comment by JayDi85** [comment]
You can try to run xmage same way from luncher/mage/client and launcher/mage/server running scripts too. It will use your default java. You can change it same way as run-launcher to setup another java version (public servers require java 8 or any other with additional params, see #12768. It can help skip step with update check and download (but I recommend  try to find a fix for your network problems with launcher).

**Comment by jestemwlodek** [comment]
When I run the client I get this:
![image](https://github.com/user-attachments/assets/09e89f19-dc3e-462b-a0dc-b69ea7a84b33)

**Comment by JayDi85** [comment]
You are trying to connect localhost — it allow to play with AI opponents, but you must run server app first (make sure it’s started and show “listening” in the logs window). Press “beta” button to connect to public server.

P.S. There are not any registration required servers, so just use any name to login on it without password.
