### ISSUE TITLE
Intercessors Arrest needs hint for cant activate

### ISSUE THREAD

**Issue by tiera3** [magefree/mage#13058]
![image](https://github.com/user-attachments/assets/079b41d3-e800-4ae8-a06b-23dfe3db51d4)
[[intercessors Arrest]]

**Comment by jeffwadsworth** [comment]
Hmm.  This would probably create too much clutter on the card.

**Comment by jeffwadsworth** [comment]
https://github.com/magefree/mage/pull/12166
