### ISSUE TITLE
How to help in getting new sets/cards in Xmage ? 

### ISSUE THREAD

**Issue by FrenchFrog-ops** [magefree/mage#13076]
Hi, 

How can I help the team here in adding new cards/sets in Xmage ? 

Cheers
RG

**Comment by PurpleCrowbar** [comment]
Start with [this guide](https://github.com/magefree/mage/wiki/Setting-up-your-Development-Environment) which will get you set up to start implementing cards. If you need any help with the process you can join the [Discord server](https://discord.gg/kZ5egVQ3hw) and ask for assistance there.
