### ISSUE TITLE
Can't cast Tear Asunder kicked in some situations

### ISSUE THREAD

**Issue by frikiluser** [magefree/mage#13081]
Can't cast [[Tear Asunder]] kicked when there is a creature on the battlefield but no artifacts/enchantments.

**Comment by frikiluser** [comment]
Example deck to reproduce the issue:

```
4 [ZEN:195] Adventuring Gear
4 [LEA:210] Llanowar Elves
4 [WOE:95] Hopeless Nightmare
4 [DMU:183] Tear Asunder
12 [LEA:294] Forest
12 [LEA:290] Swamp
```

Followed steps:
1. Create a "Constructed - Freeform" match.
2. Both players load same example deck.
3. Both players play lands and creatures only (at least 1 creature)
4. As soon as a player has the instant in hand and 4 mana available (at least one of each color) the bug is reproduced. Can't cast Tear Asunder kicked
5. A player enters an Artifact/Enchantment. The bug is fixed temporarily
6. Remove the Artifact/Enchantment
7. The bug is back

Hope it helps!

**Comment by xenohedron** [comment]
Was fixed a month ago by #12842, wait for next release

**Comment by frikiluser** [comment]
Hi @xenohedron ,

I can reproduce same issue with current master branch.

[a2ed52b](https://github.com/magefree/mage/commit/a2ed52b8de90297339542c32ab212c677719f240).

**Comment by JayDi85** [comment]
Is it really fixed or not in current master?

**Comment by xenohedron** [comment]
@ssk97 can you take a look?

**Comment by ssk97** [comment]
> @ssk97 can you take a look?

Just tested it, as far as I can tell it fine. Tear Asunder can be used if the only permanents on the battlefield are the Llanowar Elves and lands. Not sure what could've happened. Maybe @frikiluser tested with an updated client but without updating the server as well?

**Comment by frikiluser** [comment]
Sorry for the confusion.
Fix confirmed.

Thanks for your job!
