### ISSUE TITLE
Can't play instants during the turn of opponents like Grand Abolisher

### ISSUE THREAD

**Issue by Feedigiri** [magefree/mage#13099]
Tried to cast Consider where there was no such thing as a Grand Abolisher type of effect.

**Comment by JayDi85** [comment]
Is it worked fine in old version?

**Comment by Feedigiri** [comment]
Yes, before the update it worked perfectly fine.

**Comment by JayDi85** [comment]
Then it's related to #13089 and #13088 (it's changed some logic of triggered/static effects life cycle)

**Comment by jeffwadsworth** [comment]
[[Consider]] [[Grand Abolisher]]

**Comment by JayDi85** [comment]
Already fixed in current release by c6bec887b9fd99a1d9db43308a04183054dbdd56
