### ISSUE TITLE
SERVER - game error

### ISSUE THREAD

**Issue by abrahamdrinkin** [magefree/mage#13097]
Error type: SERVER - game error
Client version: 1.4.55-V1 (build: 2024-11-30 18:43)

Game error occurred: 

java.lang.NullPointerException
Server version: 1.4.55-V1 (build: 2024-11-30 18:43)
Stack trace:
mage.cards.p.PollywogProdigyPredicate.apply(PollywogProdigy.java:71)
mage.cards.p.PollywogProdigyPredicate.apply(PollywogProdigy.java:60)
mage.filter.FilterStackObject.lambda$match$0(FilterStackObject.java:42)
java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1359)
java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
java.util.stream.ReferencePipeline.allMatch(ReferencePipeline.java:454)
mage.filter.FilterStackObject.match(FilterStackObject.java:42)
mage.filter.FilterSpell.match(FilterSpell.java:33)
mage.abilities.common.SpellCastOpponentTriggeredAbility.checkTrigger(SpellCastOpponentTriggeredAbility.java:88)
mage.abilities.TriggeredAbilities.checkTrigger(TriggeredAbilities.java:243)
mage.abilities.TriggeredAbilities.checkTriggers(TriggeredAbilities.java:108)
mage.game.GameState.handleEvent(GameState.java:1042)
mage.game.GameImpl.fireEvent(GameImpl.java:3442)
mage.players.PlayerImpl.cast(PlayerImpl.java:1342)
mage.players.PlayerImpl.activateAbility(PlayerImpl.java:1650)
mage.player.human.HumanPlayer.activateAbility(HumanPlayer.java:2343)
mage.player.human.HumanPlayer.activateAbility(HumanPlayer.java:2364)
mage.player.human.HumanPlayer.priority(HumanPlayer.java:1405)
mage.game.GameImpl.playPriority(GameImpl.java:1712)
mage.game.turn.Step.priority(Step.java:67)
mage.game.turn.Phase.playStep(Phase.java:205)
mage.game.turn.Phase.play(Phase.java:91)
mage.game.turn.Turn.play(Turn.java:137)
mage.game.GameImpl.playTurn(GameImpl.java:1153)
mage.game.GameImpl.play(GameImpl.java:1060)
mage.game.GameImpl.start(GameImpl.java:1036)
mage.server.game.GameWorker.call(GameWorker.java:35)
mage.server.game.GameWorker.call(GameWorker.java:16)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)

**Comment by JayDi85** [comment]
Will be available with next hotfix update, not today's.

**Comment by JayDi85** [comment]
nvm, I rebuild release, so it will be in today's hotfix
