### ISSUE TITLE
format legality for MB2 playtest cards

### ISSUE THREAD

**Issue by xenohedron** [magefree/mage#13090]
Example: https://scryfall.com/card/mb2/303/wisedrafters-will from 12808184

This card is not eternal legal.

I propose that SetType.REMIX (used for MB1 and MB2 only so far) be excluded from eternal legality to account for this, since all the other cards in MB1 and MB2 are reprints, with only the MB2 playtest cards as new cards. (MB1 playtest cards are catalogued separately under CMB1.) Any objections?

**Comment by PurpleCrowbar** [comment]
Truth be told, I assumed this was how it already worked. Would this change cause users using MB2 versions of eternal legal cards to have to change those versions out for a "legal" printing or?

**Comment by xenohedron** [comment]
No, if any printing is legal in a format, all printings are legal
