### ISSUE TITLE
Gornog, the Red Reaper doesn't trigger (on attack).

### ISSUE THREAD

**Issue by Remed1e** [magefree/mage#13100]
I tried [[Gornog, the red reaper]] today after the FDN update. Unfortunately Gornog his attack trigger doesn't work. It never actually triggers.

**Comment by JayDi85** [comment]
Possibly wrong predicate (need controlled by predicate, not permanent). Just an idea.
![IMG_0984](https://github.com/user-attachments/assets/70cdd5a2-c580-4c0b-8f67-a397402acf45)

**Comment by JayDi85** [comment]
[[Gornog, the Red Reaper]]

**Comment by Remed1e** [comment]
This ticket seemed to have been closed but the issue persists (tested it today).

**Comment by Grath** [comment]
The code to fix it was merged, but won't be available until after the next update to XMage. Please wait to reopen unless it still happens after the next update.
