### ISSUE TITLE
Most cards with multiple targets and another target don't check that's another target

### ISSUE THREAD

**Issue by LevelX2** [magefree/mage#1311]
Cards:
Fate Transfer

**Comment by drmDev** [comment]
Unclear what this issue specifically is. Is it similar to issue #2106 ?

**Comment by Dilnu** [comment]
This is a different issue I think. #2106 is about this being fixed in the wrong way on some cards.

**Comment by Dilnu** [comment]
Also I was looking through this today. I think this issue can be closed as fixed unless I missed something in my search. http://gatherer.wizards.com/Pages/Search/Default.aspx?page=0&action=advanced&text=+%5B%22another%20target%22%5D

You can find relevant cards by finding cards that have the word target twice in their text.
