### ISSUE TITLE
Scrap Welder's activated ability does not work

### ISSUE THREAD

**Issue by ResidentCarcosa** [magefree/mage#13118]
When you tap scrap welder to activate its ability, the window to designate X pops up, but when you confirm, the window closes, and nothing happens

**Comment by PurpleCrowbar** [comment]
[[Scrap Welder]]

**Comment by xenohedron** [comment]
Can you please share the value for X, the intended artifact to be sacrificed, and the intended target to be returned?

**Comment by ResidentCarcosa** [comment]
Ok just checked and realised I had no legal target in my grave at the time my bad ill close this issue
