### ISSUE TITLE
Cannot add lands after draft portion of limited tournament

### ISSUE THREAD

**Issue by radiasian** [magefree/mage#13127]
I clicked the "lands" button and got this:

Error type: CLIENT - unhandled error in GUI - IllegalArgumentException
Client version: 1.4.55-V2 (build: 2024-12-01 17:48)

No set with basic land was found

Stack trace:
mage.client.dialog.AddLandDialog.showDialog(AddLandDialog.java:90)
mage.client.deckeditor.DeckEditorPanel.btnAddLandActionPerformed(DeckEditorPanel.java:1490)
mage.client.deckeditor.DeckEditorPanel.access$900(DeckEditorPanel.java:51)
mage.client.deckeditor.DeckEditorPanel$11.actionPerformed(DeckEditorPanel.java:1213)
javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
java.awt.Component.processMouseEvent(Component.java:6539)
and other 30 lines

restarting the client without closing the initial client fixed the issue.

**Comment by xenohedron** [comment]
We've had several reports of similar errors. The sets being drafted do have basic lands, it works fine for most players. Not sure what might be the root cause.

**Comment by JayDi85** [comment]
@radiasian are you having slow connection or disconnects while playing xmage?

**Comment by xenohedron** [comment]
got another today
![image](https://github.com/user-attachments/assets/f60bbe9a-079e-4e3e-9587-35107558f201)

does seem to be related to connection hiccups somehow

**Comment by JayDi85** [comment]
Looks like there are two places with related code and potential buggy use cases (only theory):
* server side error with tourney freeze:
  * play in non-test mode with deck validation or run with `-Dxmage.testMode=false`
  * draft with sets without lands, do not add lands manually on construction and wait timeout
  * tourney must freeze
* client side error:
  * draft with sets without lands and try to press add lands button on construction;

![shot_241214_094501](https://github.com/user-attachments/assets/8938973d-c451-42f0-a734-12a32a68c2fd)

I'm not sure how to run drafts with such sets without lands. Maybe some supplemental sets affected (some supplemental sets must take lands from a parent set, see related #10184).

P.S. There is possible a server side error with memory overflow and broken database -- so it can't find any lands or other cards. If you catch that land errors before server restart then it's a real reason.

P.P.S. Error is not related to miss lands button from other issues like #12731

**Comment by JayDi85** [comment]
Fast alternative solution -- if deck haven't sets with lands then use all possible sets/lands. It's compatible with mtg rules.

**Comment by JayDi85** [comment]
After some research -- client side error from topic starter related to memory problems on local machine. There are impossible any use cases with empty sets list on the client except memory:
![shot_241215_002725](https://github.com/user-attachments/assets/ffc83f42-df3a-4578-82d6-6acf9bee7498)

So potential server side error on timeout is under investigation.

**Comment by JayDi85** [comment]
Server side error can be catched on server's memory problems only (after database corruption). There are not any workable use cases in normal situation. Added related tests in 2955535927260c1e1a0f672a296095a3565c0df5 So topic can be closed.
