### ISSUE TITLE
Can't play (certain?) instants or counterspells

### ISSUE THREAD

**Issue by OfficiallyAsian** [magefree/mage#13161]
![{E2EF62D3-53F2-4DC9-A7B7-0349B7D143D9}](https://github.com/user-attachments/assets/1d197dd7-ee3d-46b7-aba5-4e9e9397b6fb)

Sometimes it works, sometimes it doesn't

Here, I should be able to play Horribly Awry as the spell meets the requirements (Cyclonic Rift only has a CMC of 2), but for some reason, I can't

![{E5BF1BF8-1604-4D2B-83E4-8F91C7E657C1}](https://github.com/user-attachments/assets/2ac58658-4716-4d2c-b210-2e00c3397e7b)

Here, Glarb has a CMC of 3, and only now can I play that same spell

rubs salt on the wound that I can only apparently counter my own spells

**Comment by JayDi85** [comment]
> should be able to play Horribly Awry as the spell meets the requirements

Nope, [[Horribly Awry]] needs "creature spell" to counter, but stack contains instant [[Cyclonic Rift]] (it's not a creature spell).

**Comment by OfficiallyAsian** [comment]
> > should be able to play Horribly Awry as the spell meets the requirements
> 
> Nope, [[Horribly Awry]] needs "creature spell" to counter, but stack contains instant [[Cyclonic Rift]] (it's not a creature spell).

Ah right my bad, I forgot, thanks
