### ISSUE TITLE
Myriad problems with Omniscience

### ISSUE THREAD

**Issue by ngenisis** [magefree/mage#1323]
Omniscience reads, "You may cast nonland cards from your hand without paying their mana costs."

Issue 1: If another effect (e.g. Future Sight) allows you to cast nonland cards from zones other than your hand, Xmage incorrectly lets you cast those cards without paying their mana costs. Omniscience only lets you cast spells from your hand without paying their mana costs.

Issue 2: If a nonland card is able to be cast with an alternate cost (e.g. Cyclonic Rift with Overload), Xmage incorrectly lets you cast them for that alternate cost without paying its mana cost. 117.9a Only one alternative cost can be applied to any one spell as it’s being cast. The controller of
the spell announces his or her intentions to pay that cost as described in rule 601.2b.

Issue 3: If a spell has an additional cost (optional or mandatory, e.g. Tooth and Nail), Omniscience incorrectly allows you cast the spell as if that cost had been paid without paying that spell's mana cost. 117.9d If an alternative cost is being paid to cast a spell, any additional costs, cost increases, and cost reductions that affect that spell are applied to that alternative cost. (See rule 601.2f.)

Issue 4: If a spell has an unpayable cost (e.g. Ancestral Vision, which has no mana cost), Omniscience should allow you to cast that spell without paying its mana cost. In the case of Ancestral Vision, for example, Xmage only gives you the option to suspend Ancestral Vision. 117.6a If an unpayable cost is increased by an effect or an additional cost is imposed, the cost is still unpayable. If an alternative cost is applied to an unpayable cost, including an effect that allows a player to cast a spell without paying its mana cost, the alternative cost may be paid.

Sorry if I should have submitted each of these as separate bugs, but it seems likely that there is something fundamentally wrong with how Omniscience is being implemented that is the root cause of all of these issues. My assumption is that Omniscience is waiting for the total cost of the spell to be finalized and then wipes it clean, which is why I submitted this is as one bug. This might affect other cards that let you cast spells without paying their mana costs.

**Comment by LevelX2** [comment]
Issue 1 was not reproducable. Maybe it was already fixed by earlier fixes but I'm not aware of such a fix.
Issue 2-4 are fixed now.

**Comment by LevelX2** [comment]
Should be ok now, I close it.
