### ISSUE TITLE
Clones incorrectly allowed to enter the battlefield as copies of permanents entering the battlefield at the same time.

### ISSUE THREAD

**Issue by ngenisis** [magefree/mage#1324]
This bug seems to effect all permanents that "may enter the battlefield as a copy of" another permanent on the battlefield, not just Clone. For instance, an opponent had a Terastodon, Sakashima's Student, and Dack's Duplicant all enter the battlefield as a copy of the Terastodon.

**Comment by LevelX2** [comment]
Fixed beyond 1.4.4v8
Was a lot of work.
