### ISSUE TITLE
Game Error when casting Outpost Siege

### ISSUE THREAD

**Issue by slipknotcc** [magefree/mage#1332]
Hello,

This error occurs every time I attempt to cast Outpost Siege naming Khans:

An error has occurred on the MAGE server. Your last action will be rollbacked.
Please post the following report here: http://www.slightlymagic.net/forum/posting.php?mode=reply&f=70&t=3116

Game exception occurred: java.lang.NullPointerException
Server version: 1.4.4v11
mage.abilities.effects.common.ChooseModeEffect.apply(ChooseModeEffect.java:84)
mage.abilities.effects.EntersBattlefieldEffect.replaceEvent(EntersBattlefieldEffect.java:130)
mage.abilities.effects.ContinuousEffects.replaceEvent(ContinuousEffects.java:855)
mage.game.GameState.replaceEvent(GameState.java:674)
mage.game.GameImpl.replaceEvent(GameImpl.java:2290)
mage.game.permanent.PermanentImpl.entersBattlefield(PermanentImpl.java:920)
mage.players.PlayerImpl.moveCards(PlayerImpl.java:3079)
mage.players.PlayerImpl.moveCards(PlayerImpl.java:3028)
mage.game.stack.Spell.resolve(Spell.java:267)
mage.game.GameImpl.resolve(GameImpl.java:1341)
mage.game.GameImpl.playPriority(GameImpl.java:1296)
mage.game.turn.Step.priority(Step.java:87)
mage.game.turn.Phase.playStep(Phase.java:210)
mage.game.turn.Phase.play(Phase.java:115)
mage.game.turn.Turn.play(Turn.java:152)
mage.game.GameImpl.playTurn(GameImpl.java:835)
mage.game.GameImpl.play(GameImpl.java:749)
mage.game.GameImpl.start(GameImpl.java:716)
mage.server.game.GameWorker.call(GameWorker.java:61)
java.util.concurrent.FutureTask.run(Unknown Source)
java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
java.lang.Thread.run(Unknown Source)

This error occurs when I cast Outpost Siege naming Dragons:

An error has occurred on the MAGE server. Your last action will be rollbacked.
Please post the following report here: http://www.slightlymagic.net/forum/posting.php?mode=reply&f=70&t=3116

Game exception occurred: java.lang.NullPointerException
Server version: 1.4.4v11
mage.abilities.effects.common.ChooseModeEffect.apply(ChooseModeEffect.java:84)
mage.abilities.effects.EntersBattlefieldEffect.replaceEvent(EntersBattlefieldEffect.java:130)
mage.abilities.effects.ContinuousEffects.replaceEvent(ContinuousEffects.java:855)
mage.game.GameState.replaceEvent(GameState.java:674)
mage.game.GameImpl.replaceEvent(GameImpl.java:2290)
mage.game.permanent.PermanentImpl.entersBattlefield(PermanentImpl.java:920)
mage.players.PlayerImpl.moveCards(PlayerImpl.java:3079)
mage.players.PlayerImpl.moveCards(PlayerImpl.java:3028)
mage.game.stack.Spell.resolve(Spell.java:267)
mage.game.GameImpl.resolve(GameImpl.java:1341)
mage.game.GameImpl.playPriority(GameImpl.java:1296)
mage.game.turn.Step.priority(Step.java:87)
mage.game.turn.Phase.playStep(Phase.java:210)
mage.game.turn.Phase.play(Phase.java:115)
mage.game.turn.Turn.play(Turn.java:152)
mage.game.GameImpl.playTurn(GameImpl.java:835)
mage.game.GameImpl.play(GameImpl.java:749)
mage.game.GameImpl.start(GameImpl.java:716)
mage.server.game.GameWorker.call(GameWorker.java:61)
java.util.concurrent.FutureTask.run(Unknown Source)
java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
java.lang.Thread.run(Unknown Source)

Thank you,
Cory

**Comment by fireshoes** [comment]
It is fixed for the next update.
