### ISSUE TITLE
Angel's Grace is bugged?

### ISSUE THREAD

**Issue by Badaro** [magefree/mage#1333]
Gamelog: http://pastebin.com/DvKC7JzQ

Not sure if it's triggered by just casting Angel's Grace or by casting it from an Isochron Scepter, but when the bug happens neither player is able to play spells or activate abilities anymore for the rest of the game.

Maybe something related to Split Second?

**Comment by LevelX2** [comment]
04:04: badaro
    has joined the game
: Match score:DarkAkantor
    - 0 winsDeckHash: 7597548616718637576badaro
    - 0 winsDeckHash: 6267321792675875607You have to win 1 game to
    win the complete matchGame has started
04:04: badaro
    shuffles his or her library.
04:04: DarkAkantor
    shuffles his or her library.
04:04: DarkAkantor
    won the toss
04:04: DarkAkantor
    chooses that he or she takes the first turn
04:04: DarkAkantor
    draws seven cards
04:04: badaro
    draws seven cards
04:04: DarkAkantor
    keeps hand
04:04: badaro
    keeps hand
04:04: Turn 1 DarkAkantor
    (20 - 20)
04:04: DarkAkantor
    puts Urborg, Tomb of Yawgmoth [e99]
    from hand onto the Battlefield
04:04: DarkAkantor
    plays Urborg, Tomb of Yawgmoth [e99]
04:04: DarkAkantor
    casts Inquisition of Kozilek [97e]
    targeting badaro 
04:04: badaro
    reveals Urza's Tower,
    Chromatic Star, Ancient
    Stirrings, Oblivion
    Stone, Wurmcoil
    Engine, Urza's Mine,
    Urza's Power Plant
04:05: badaro
    discards Oblivion Stone [8e3]
04:05: DarkAkantor
    puts Inquisition of Kozilek [97e]
    from stack into his or her graveyard
04:05: DarkAkantor
    attacks with 0 creatures
04:05: Turn 2 badaro
    (20 - 20)
04:05: badaro
    draws a card
04:05: badaro
    puts Urza's Tower [6dd]
    from hand onto the Battlefield
04:05: badaro
    plays Urza's Tower [6dd]
04:05: badaro
    casts Chromatic Star [5f1]
04:05: badaro
    puts Chromatic Star [5f1]
    from stack onto the Battlefield
04:05: badaro
    attacks with 0 creatures
04:05: Turn 3 DarkAkantor
    (20 - 20)
04:05: DarkAkantor
    draws a card
04:06: DarkAkantor
    puts Windswept Heath [aff]
    from hand onto the Battlefield
04:06: DarkAkantor
    plays Windswept Heath [aff]
04:06: DarkAkantor
    loses 1 life
04:06: DarkAkantor
    sacrificed Windswept Heath [aff]
04:06: DarkAkantor
    activates: search your library for a Forest or Plains and put it onto the
    battlefield. Then shuffle your library. from Windswept
    Heath [aff]
04:06: DarkAkantor
    searches his or her library
04:06: DarkAkantor
    loses 2 life
04:06: DarkAkantor
    puts Sacred Foundry [8ee]
    from library onto the Battlefield
04:06: DarkAkantor
    shuffles his or her library.
04:06: DarkAkantor
    attacks with 0 creatures
04:06: Turn 4 badaro
    (20 - 17)
04:06: badaro
    draws a card
04:06: badaro
    sacrificed Chromatic Star [5f1]
04:07: Ability triggers: Chromatic
    Star [5f1] - When Chromatic
    Star [5f1] is put into a graveyard from the
    battlefield, draw a card.
04:07: badaro
    draws a card
04:07: badaro
    casts Ancient Stirrings [e7f]
04:07: badaro
    puts a card from library into his or her hand
04:07: badaro
    reveals Relic of Progenitus
04:07: badaro
    puts a card from library to the bottom of his or her library
04:07: badaro
    puts a card from library to the bottom of his or her library
04:07: badaro
    puts a card from library to the bottom of his or her library
04:07: badaro
    puts a card from library to the bottom of his or her library
04:07: badaro
    puts Ancient Stirrings [e7f]
    from stack into his or her graveyard
04:07: badaro
    puts Urza's Tower [984]
    from hand onto the Battlefield
04:07: badaro
    plays Urza's Tower [984]
04:07: badaro
    casts Chromatic Sphere [53d]
04:07: badaro
    puts Chromatic Sphere [53d]
    from stack onto the Battlefield
04:07: badaro
    attacks with 0 creatures
04:07: Turn 5 DarkAkantor
    (20 - 17)
04:07: DarkAkantor
    draws a card
04:07: DarkAkantor
    puts Windswept Heath [aa2]
    from hand onto the Battlefield
04:07: DarkAkantor
    plays Windswept Heath [aa2]
04:07: DarkAkantor
    loses 1 life
04:07: DarkAkantor
    sacrificed Windswept Heath [aa2]
04:07: DarkAkantor
    activates: search your library for a Forest or Plains and put it onto the
    battlefield. Then shuffle your library. from Windswept
    Heath [aa2]
04:07: DarkAkantor
    searches his or her library
04:08: DarkAkantor
    puts Temple Garden [10b]
    from library onto the Battlefield
04:08: DarkAkantor
    shuffles his or her library.
04:08: DarkAkantor
    casts Lightning Bolt [bcd]
    targeting badaro 
04:08: badaro
    loses 3 life
04:08: DarkAkantor
    puts Lightning Bolt [bcd]
    from stack into his or her graveyard
04:08: DarkAkantor
    attacks with 0 creatures
04:08: Turn 6 badaro
    (17 - 16)
04:08: badaro
    draws a card
04:08: badaro
    puts Urza's Mine [999]
    from hand onto the Battlefield
04:08: badaro
    plays Urza's Mine [999]
04:08: badaro
    sacrificed Chromatic Sphere [53d]
04:08: badaro
    draws a card
04:08: badaro
    casts Ancient Stirrings [8b4]
04:08: badaro
    puts a card from library into his or her hand
04:08: badaro
    reveals Oblivion Stone
04:08: badaro
    puts a card from library to the bottom of his or her library
04:08: badaro
    puts a card from library to the bottom of his or her library
04:08: badaro
    puts a card from library to the bottom of his or her library
04:08: badaro
    puts a card from library to the bottom of his or her library
04:08: badaro
    puts Ancient Stirrings [8b4]
    from stack into his or her graveyard
04:08: badaro
    casts Relic of Progenitus [7ab]
04:08: badaro
    puts Relic of Progenitus [7ab]
    from stack onto the Battlefield
04:09: badaro
    casts Chromatic Star [8e9]
04:09: badaro
    puts Chromatic Star [8e9]
    from stack onto the Battlefield
04:09: badaro
    activates: Target player exiles a card from his or her graveyard. from Relic
    of Progenitus [7ab] targeting DarkAkantor
04:09: DarkAkantor
    moves Windswept Heath [aa2]
    from graveyard to the exile zone
04:09: badaro
    attacks with 0 creatures
04:09: Turn 7 DarkAkantor
    (17 - 16)
04:09: DarkAkantor
    draws a card
04:09: DarkAkantor
    casts Sylvan Scrying [3f9]
04:09: DarkAkantor
    searches his or her library
04:09: DarkAkantor
    puts a card from library into his or her hand
04:09: DarkAkantor
    reveals Godless Shrine
04:09: DarkAkantor
    shuffles his or her library.
04:09: DarkAkantor
    puts Sylvan Scrying [3f9]
    from stack into his or her graveyard
04:09: DarkAkantor
    puts Godless Shrine [feb]
    from hand onto the Battlefield
04:09: DarkAkantor
    plays Godless Shrine [feb]
04:09: DarkAkantor
    attacks with 0 creatures
04:10: Turn 8 badaro
    (17 - 16)
04:10: badaro
    draws a card
04:10: badaro
    puts Urza's Power Plant [cf4]
    from hand onto the Battlefield
04:10: badaro
    plays Urza's Power Plant [cf4]
04:10: badaro
    casts Wurmcoil Engine [1b1]
04:10: badaro
    puts Wurmcoil Engine [1b1]
    from stack onto the Battlefield
04:10: badaro
    casts Expedition Map [b3a]
04:10: badaro
    puts Expedition Map [b3a]
    from stack onto the Battlefield
04:10: badaro
    moves Relic of Progenitus [7ab]
    from battlefield to the exile zone
04:10: badaro
    activates: exile all cards from all graveyards. Draw a card. from Relic
    of Progenitus [7ab]
04:10: badaro
    moves Inquisition of Kozilek [97e]
    from graveyard to the exile zone
04:10: badaro
    moves Windswept Heath [aff]
    from graveyard to the exile zone
04:10: badaro
    moves Lightning Bolt [bcd]
    from graveyard to the exile zone
04:10: badaro
    moves Sylvan Scrying [3f9]
    from graveyard to the exile zone
04:10: badaro
    moves Oblivion Stone [8e3]
    from graveyard to the exile zone
04:10: badaro
    moves Chromatic Star [5f1]
    from graveyard to the exile zone
04:10: badaro
    moves Ancient Stirrings [e7f]
    from graveyard to the exile zone
04:10: badaro
    moves Chromatic Sphere [53d]
    from graveyard to the exile zone
04:10: badaro
    moves Ancient Stirrings [8b4]
    from graveyard to the exile zone
04:10: badaro
    draws a card
04:10: badaro
    attacks with 0 creatures
04:10: Turn 9 DarkAkantor
    (17 - 16)
04:10: DarkAkantor
    draws a card
04:11: DarkAkantor
    puts Sacred Foundry [8f9]
    from hand onto the Battlefield
04:11: DarkAkantor
    plays Sacred Foundry [8f9]
04:11: DarkAkantor
    casts Boros Charm [f5b]
    (mode 1) targeting badaro
04:11: badaro
    loses 4 life
04:11: DarkAkantor
    puts Boros Charm [f5b]
    from stack into his or her graveyard
04:11: DarkAkantor
    attacks with 0 creatures
04:11: badaro
    sacrificed Expedition Map [b3a]
04:11: badaro
    activates: search your library for a land card, reveal it, and put that
    card into your hand. Then shuffle your library. from Expedition
    Map [b3a]
04:11: badaro
    searches his or her library
04:11: badaro
    reveals Eye of Ugin
04:11: badaro
    puts a card from library into his or her hand
04:11: badaro
    shuffles his or her library.
04:11: Turn 10 badaro
    (13 - 16)
04:11: badaro
    draws a card
04:11: badaro
    puts Eye of Ugin [622]
    from hand onto the Battlefield
04:11: badaro
    plays Eye of Ugin [622]
04:12: badaro
    attacks with 1 creature
04:12: Attacker: Wurmcoil
    Engine [1b1] (6/6) unblocked
04:12: badaro
    gains 6 life
04:12: DarkAkantor
    loses 6 life
04:12: Turn 11 DarkAkantor
    (19 - 10)
04:12: DarkAkantor
    draws a card
04:12: DarkAkantor
    casts Isochron Scepter [f8a]
04:12: DarkAkantor
    puts Isochron Scepter [f8a]
    from stack onto the Battlefield
04:12: Ability triggers: Isochron
    Scepter [f8a] - Imprint &#8212; When Isochron
    Scepter [f8a] enters the battlefield, you may
    exile an instant card with converted mana cost 2 or less from your hand.
04:12: DarkAkantor
    moves Angel's Grace [abe]
    from hand to the exile zone
04:12: DarkAkantor
    attacks with 0 creatures
04:13: badaro
    activates: search your library for a colorless creature card, reveal it,
    and put that card into your hand. Then shuffle your library. from Eye
    of Ugin [622]
04:13: badaro
    searches his or her library
04:13: badaro puts a card from library into his or her hand
04:13: badaro reveals Ulamog, the Ceaseless Hunger
04:13: badaro shuffles his or her library.
04:13: Turn 12 badaro (19 - 10)
04:13: badaro draws a card
04:13: DarkAkantor activates: You may copy the exiled card. If you do, you may cast the copy
    without paying its mana cost. from Isochron Scepter [f8a]
04:13: DarkAkantor casts Angel's Grace [dc8]
04:13: badaro puts Ghost Quarter [535] from hand onto the Battlefield
04:13: badaro plays Ghost Quarter [535] 
04:14: badaro attacks with 1 creature
04:14: Attacker: Wurmcoil Engine [1b1] (6/6) unblocked
04:14: DarkAkantor loses 6 life
04:14: badaro gains 6 life
04:14: badaro sacrificed Chromatic Star [8e9]
04:14: Ability triggers: Chromatic Star [8e9] - When Chromatic Star [8e9] is put into a graveyard from the battlefield, draw a card.
04:14: badaro draws a card
04:15: Turn 13 DarkAkantor (25 - 4)
04:15: DarkAkantor draws a card
04:17: DarkAkantor attacks with 0 creatures
04:17: Turn 14 badaro (25 - 4)
04:17: badaro draws a card
04:18: badaro puts Urza's Mine [171] from hand onto the Battlefield
04:18: badaro plays Urza's Mine [171]
04:18: badaro attacks with 1 creature
04:18: Attacker: Wurmcoil Engine [1b1] (6/6) unblocked
04:18: badaro gains 6 life
04:18: DarkAkantor loses 6 life
04:18: DarkAkantor has lost the game.
04:18: badaro has won the game
