### ISSUE TITLE
Tooth and Nail doesn't work properly

### ISSUE THREAD

**Issue by RegurKenaid** [magefree/mage#1335]
After latest server update Tooth and Nail puts cards on the battlefield tapped. They should be untapped.

**Comment by RegurKenaid** [comment]
I sent pull request 1336 that should repair it.

**Comment by RegurKenaid** [comment]
Does 1.4.4v12 include this changes? Cause T&N still doesn't work.

**Comment by RegurKenaid** [comment]
Any update on this?

**Comment by LevelX2** [comment]
Fix will be included in the next update, because it's already merged.
