### ISSUE TITLE
Infinite Obliteration bug (version 1.4.4v11)

### ISSUE THREAD

**Issue by chrism778** [magefree/mage#1342]
There appears to be a bug with Infinite Obliteration, where if you use it against an opponent, it doesn't exile the creature cards from their library even if you chose them.  They don't show up in exile and they are still able to play them.  I had an opponent play an Ulamog, the Ceasless Hunger from his library after I had used Infinite Obliteration to exile it.   One thing to note is that he did not have Ulamog in his hand when I played Infinite Obliteration, so maybe the bug is tied to that fact.

**Comment by LevelX2** [comment]
Fixed beyond 1.4.4v12A
