### ISSUE TITLE
Download token images from new source

### ISSUE THREAD

**Issue by LevelX2** [magefree/mage#1347]
Add logic to allow download of token images from:
http://tokens.mtg.onl

**Comment by salyG** [comment]
boss, i still got 37 images left for download on xmage. but they cant be downloaded. (0 out of 37 cards finish).....

**Comment by fireshoes** [comment]
It's the tokens from Duel Decks Anthology, plus the new FilterLand Expeditions, which mythicspoiler has tagged as OGW instead of EXP (not high quality images anyway), plus a couple promos that aren't up on magiccards.info yet.
