### ISSUE TITLE
Awaken ability does not trigger hardened scales

### ISSUE THREAD

**Issue by Greeneye0** [magefree/mage#1348]
Expected results would be hardened scales would trigger once.

![image](https://cloud.githubusercontent.com/assets/11687236/10833436/7163168a-7e57-11e5-88bf-7f0710474469.png)

**Comment by fireshoes** [comment]
If you are targeting a land that is not a creature already, a spell with awaken doesn't cause an extra counter to be placed on the land from Hardened Scales. The spell resolves in the order it is written, so first the counters are put on the land, and then it becomes a creature. Here is the reminder text from Ruinous Path: (If you cast this spell for 5BB, also put four +1/+1 counters on target land you control and it becomes a 0/0 Elemental creature with haste. It's still a land.)

If your awaken target is a land that is already a creature (a previously Awakened land or an animated creature land like Shambling Vent), then Hardened Scales will put an extra counter on it.
