### ISSUE TITLE
Cant see hands or life since update

### ISSUE THREAD

**Issue by OutlawQc** [magefree/mage#1349]

**Comment by LevelX2** [comment]
Handled here: http://www.slightlymagic.net/forum/viewtopic.php?f=70&t=17849

Which operating system do you use? (e.g. windows xx).
Is the client updated to 1.4.4v12?
Does it happen in limited and constructed?
Does it happen with different decks?
Are there any related error message shown in the [xmageclient-folder]/mageclient.log file?

**Comment by LevelX2** [comment]
This should be solved with the update to 1.4.5v0 becuase it most probably was caused by different client versions. If not open a new ticket.
