### ISSUE TITLE
Can not resolve symbols

### ISSUE THREAD

**Issue by poixen** [magefree/mage#1356]
Within IntelliJ the following files can not be found:

```import mage.server.util.config.Config;```
```import mage.server.util.config.GamePlugin;```
```import mage.server.util.config.Plugin;```

I can not find these files either. Is this a known issue?

EDIT:
This is from ConfigSettings.java on a vanilla clone.

**Comment by LevelX2** [comment]
That are xjc sources that get generated while you build the server project.
So after generating that project the sources should be exist. At least I can confirm that for the netbeans IDE I  use.
