### ISSUE TITLE
Restoration angel and Fiend Hunter

### ISSUE THREAD

**Issue by OutlawQc** [magefree/mage#1359]
Hi i rencently play against an opponent that when i did the bounce ability with Restoration Angel to Fiend hunter to Exile Primeval Titan the first primeval titan that i exiled didnt came back into play.

**Comment by OutlawQc** [comment]
just to be sure i exile primeval titan the first time that fiend hunter came into play and i resto angel fiend hunter to exile another primeval titan

**Comment by thejayvm** [comment]
This could be a timing issue. If you flash in Resto Angel in response to the fiend hunters ETB trigger, the leaving the battle field will trigger and see nothing to return so that trigger resolves and does nothing.

**Comment by OutlawQc** [comment]
Fiend hunter was on the battlefield for 4-6 rounds. When Fiend hunter is
remove from the battlefield the exile ability is suppose lose his effect
and the first Titan is suppose to come back.

**Comment by LevelX2** [comment]
Fixed beyond 1.4.5v0
