### ISSUE TITLE
Deck save in deck editor is not working with double click

### ISSUE THREAD

**Issue by i4004** [magefree/mage#1364]
If you are saving your deck in deck editor and will click on a file in file selection window and then click "save" then it is working fine. But if you will just double click on a file then file selection window will just close without save.

I am using latest version of xmage, and OS is windows 8.1.

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed. (Testing in Win 10)

**Comment by i4004** [comment]
I checked that again, it works now.
