### ISSUE TITLE
Default avatar shown in game after client reopen (probably settings not saved to registry).

### ISSUE THREAD

**Issue by i4004** [magefree/mage#1365]
But in avatar selection window I have correct avatar selected.

**Comment by LevelX2** [comment]
Which client version do you use?

**Comment by fireshoes** [comment]
That happens for me in v12. When I start the coient, it's the default avatar. Open prefs and #2 is already highlighted, hit save and it switches to my custom avatar.

**Comment by i4004** [comment]
@LevelX2 version 1.4.4v12

**Comment by LevelX2** [comment]
This is the same for every Avatar you selct. Or does it only happen using a specific Avatar?

**Comment by i4004** [comment]
@LevelX2 no this is for any avatar.

**Comment by LevelX2** [comment]
I guess that all your setttings are not saved to the registry, because the user you run xmage with does not have the authority to change/create the needed node in the windows registry.
You're client log should contain a message about it.

**Comment by fireshoes** [comment]
Like this?

WARNING: Could not open/create prefs root node Software\JavaSoft\Prefs at root 0x80000002. Windows RegCreateKeyEx(...) returned error code 5.

**Comment by LevelX2** [comment]
Check here for possible solutions:
http://stackoverflow.com/questions/5354838/java-java-util-preferences-failing

**Comment by LevelX2** [comment]
Any new information or progress on that issue?

**Comment by i4004** [comment]
I added "Pref" directory in HKEY_LOCAL_MACHINE\SOFTWARE\JavaSoft\ with full permissions, "WARNING: Could not open/create prefs root node" message goes out. But still my avatar is default when i open the client :)

**Comment by fireshoes** [comment]
Same here.

**Comment by LevelX2** [comment]
You should check in the registry if the Id saved for the Avatar is changed as You change the Avatar Image in the preferences. So we can narrow down what causes this problem.

**Comment by fireshoes** [comment]
I'm not sure where I am supposed to look. I don't know much about the registry.

**Comment by LevelX2** [comment]
But other changes of the preferences are saved and stored correctly?

**Comment by fireshoes** [comment]
Yes, my Main preferences and Phases & Priority preferences are always remembered. My column order  in the game lobby and column width is saved correctly. The row height in the game lobby (separating active and completed matches) and deck editor (between searched cards, main deck, and sideboard) is never remembered, if those are supposed to be.

**Comment by i4004** [comment]
@fireshoes same to me. My preferences are saves correctly. And avatar selection is saves also :) Whenever i am going to avatar selection window after client reopen then avatar selected correctly, it just shows default avatar when game starts :)
