### ISSUE TITLE
Crash on startup on Mac OS X 10.11.1

### ISSUE THREAD

**Issue by ideocl4st** [magefree/mage#1366]
I don't know why I can't copy anything off the console, but here is the message:

![screen shot 2015-11-15 at 11 34 15 am](https://cloud.githubusercontent.com/assets/2484055/11166861/f5096380-8b8c-11e5-80d5-40659a209841.png)

Java version is 8u65 (AFAIK xMage uses its own Java so it shouldn't matter, right?)

**Comment by LevelX2** [comment]
1) Can you check, if in the [xmage directory]\xmage\mage-client\db directory the file cards.h2.mv.db does exist and which file size the file has.

2) If it does not exist try connecting to a public server (e.g. xmage.de), If the clinet connects to a server, the db files will be updated or created if neccessary.

3) It also can be a problem with authority for the existing db file I mentioned under 1). So a possible solution could also be to delete all existing files in the \db\ folder of the client and connect to a public server.

4) I remember some problems with Mac and installing xmage. Probably also related to authority problems. It started with the updates to the xmage installer after 0.3.1. Therefore (if all other things don't help) you can try to use the old installer 
Download here: http://xmage.de/xmage/XMageLauncher-0.3.1.jar
and set before any update the XMage Home in the launcher settings to 
http://xmage.de/xmage_mac
and restart the launcher to install xmage on your mac.

Please give some feedback if something worked for you.

**Comment by ideocl4st** [comment]
1) It exists, and it's 35,344,384 bytes (35.3 MB).
2) I can't do it because xMage crashes as soon as I press "Launch Client". I have no way to interact with the program at all :(
3) I've tried it, but it gives me the same error. the file that was in db folder is not being generated as well.
4) Same thing happens here too.

Interestingly, when I try launching it on terminal with startClient.sh it works perfectly. (Slightly inconvenient though)

I suppose it must be the launcher's problem?

**Comment by goesta** [comment]
I'll close this issue because it seems to be outdated but feel free to create a new one if this problem still exists.
