### ISSUE TITLE
Can't target opponent owned Mountains with Koth of the Hammer

### ISSUE THREAD

**Issue by jlin14** [magefree/mage#1369]
As implemented, you can only click Mountains you control.

3 Blood Moons were on the field (2 owned by opponent, 1 by me).

**Comment by Fiorden** [comment]
You mean mountains or non mountain lands affected by Blood Moon?

**Comment by jlin14** [comment]
Both basic Mountain and nonbasic lands turned into Mountain by Blood Moon, controlled by an opponent, were untargetable.

**Comment by quercitron** [comment]
Fixed.
