### ISSUE TITLE
Please Add Zirilan of the Claw

### ISSUE THREAD

**Issue by FearLandOctopi** [magefree/mage#1382]
One of my friends has downloaded Xmage to play with our play group and his commander is Zirilan of the Claw and it is not in the xmage data base. Could you add it please? 
![image](https://cloud.githubusercontent.com/assets/15969979/11325639/839bc80a-9118-11e5-9d4b-390d32219c4b.png)

**Comment by FearLandOctopi** [comment]
Could you add this too? 

![image](https://cloud.githubusercontent.com/assets/15969979/11325707/0e5e1cda-911a-11e5-9e27-d651c251fd5c.png)

**Comment by FearLandOctopi** [comment]
and these 
![image](https://cloud.githubusercontent.com/assets/15969979/11325820/956b9088-911d-11e5-9bf4-c0b78377674d.png)

![image](https://cloud.githubusercontent.com/assets/15969979/11325822/a970ce90-911d-11e5-8a0a-6c034e061488.png)

**Comment by emerald000** [comment]
Please request new cards over there: http://www.slightlymagic.net/forum/viewtopic.php?f=70&t=4554.

Thanks!

**Comment by FearLandOctopi** [comment]
Will do. Thank you very much!
