### ISSUE TITLE
All the new 2015 experience counter commander's are bugged.

### ISSUE THREAD

**Issue by defilier** [magefree/mage#1383]
So I noticed xmage finally updated for the new commander cards, Ive been dying to play around with mizzix and the new ezuri since announced. But when playing them with the new update firstly experience counters aren't shown on the card, how do I have any way to know how many counters they have unless I'm taking note of it. Secondly proliferate doesn't work with them either nor any counter doubling card. I presume the other experience counter commanders do this as well but only tried on both Ezuri and Mizzix

**Comment by emerald000** [comment]
Experience counters are currently not shown in the client, but they will be in the next version.

Also, the counters go to the player and not the creature that gained them. To proliferate them you need to target the player, and counter doubling cards have to be able to target players.

**Comment by LevelX2** [comment]
As emerald000 said the counters will be shown in the player tooltip beyond 1.4.5v0.

![playertooltip](https://cloud.githubusercontent.com/assets/2066790/11331362/05bf8c8a-91ba-11e5-853d-4bc1f4375ec5.gif)
