### ISSUE TITLE
Can't open the .JAR Launcher

### ISSUE THREAD

**Issue by HazenbergMTG** [magefree/mage#1387]
When i click on the "Xmage Launcher" JAR-file nothing happens.
I'm sure i chose Java to open it, but it doesnt work unfortunately.

I'm using Windows 10.

Thanks :-D

**Comment by LevelX2** [comment]
open a cmd window and set the directory of the xmage.jar as the current directory.
After that enter this and push return.
java -jar XMageLauncher-0.3.4.jar
It should either start the launcher, or show you the error preventing it from doing so.

**Comment by TBFCaptain** [comment]
This might seem like a dumb question, but I'm experiencing the same issue where I have the launcher downloaded but when I try to open it nothing happens, and I don't know how to set the directory of the command prompt window. Can you walk me through step-by-step?

**Comment by LevelX2** [comment]
http://www.cs.princeton.edu/courses/archive/spr05/cos126/cmd-prompt.html

**Comment by TBFCaptain** [comment]
I tried using the cd command but it tells me that it's either not a recognized command or that it cannot find the specified path.

**Comment by Fiorden** [comment]
Make shure you have JAVA installed: https://www.java.com/en/download/. Then open CMD and type java -jar and drag the launcher icon onto the black CMD screen then push enter

**Comment by Nautilus107** [comment]
I am unable to launch the launcher as well, it states there is an error in line 1. Could not parse launch file. See attached snip.
![capture](https://cloud.githubusercontent.com/assets/16112281/11522824/bd1e1092-9870-11e5-87c3-bae73ca1a2f0.PNG)

**Comment by LevelX2** [comment]
What's "java -version" in a command window showing?

**Comment by salyG** [comment]
lol the command prompt is really difficult to use. What am i suppose to type ? It starts of as C:\Users\woo>

**Comment by LevelX2** [comment]
Sounds like a possible memory problem. How much memory has the system?
Look for example here for possible solution:
http://www.tomsguide.com/faq/id-1761312/fix-create-java-virtual-machine-issue.html

**Comment by salyG** [comment]
thank you Boss. You are right. it is the memory problem.
