### ISSUE TITLE
chandra's phoenix will not trigger

### ISSUE THREAD

**Issue by Witneret** [magefree/mage#1394]
hi guys,

i just found a bug in xmage 1.4.5. chandra's phoenix is in mxy graveyard, i´m casting red instant spells and activate a red planeswalker to deal damage to my opponent. however the trigger skips and i can´t return phoenix to my hand. may you please fix that :) ?

thank you

**Comment by LevelX2** [comment]
Fixed check for source object.
But under normal circumstances the Phoenix returned.
I coudl see some problems with chnaged colors of objects doing damage or maybe if spellsor permanents were copied.
