### ISSUE TITLE
Build fails after Commit 46eb6c0525dcc59c65133e31fb85198539991616

### ISSUE THREAD

**Issue by LevelX2** [magefree/mage#1400]
![buildfail](https://cloud.githubusercontent.com/assets/2066790/11504805/5b0ac82e-9847-11e5-8ef7-5d5e3b77b5f4.jpg)

**Comment by LevelX2** [comment]
![doublestructure](https://cloud.githubusercontent.com/assets/2066790/11505498/ee829f0c-984a-11e5-951d-fc88480257f8.jpg)
![manatestfails](https://cloud.githubusercontent.com/assets/2066790/11505497/ee828e68-984a-11e5-9b80-f4c4c68897b8.jpg)

**Comment by poixen** [comment]
It feels like you need to set your module settings.
Due to the change, the root `mage` folder is no longer the src folder. The `java` folders in main and test are now the src folders.

**Comment by LevelX2** [comment]
Fixed now.
