### ISSUE TITLE
Monastery Siege doesn't work vs flashback/mode spells

### ISSUE THREAD

**Issue by Zorkony** [magefree/mage#1405]
Opponent had Monastery Siege on Dragons in Modern. 

When I cast a terminate on one of his creatures I had to pay 2BR (as I should). When I flashbacked that terminate with a snapcaster I only had to pay BR (it seemed I had to pay the flashback cost before choosing its target, so it didn't care about the Siege). 
When I cast cryptic command with the bounce/draw modes (casting it, targeting one of his permanents) it still only cost 1UUU, again not caring about the Siege.

**Comment by Zorkony** [comment]
*2BR, obviously

**Comment by drmDev** [comment]
Need to test this to confirm issue... will test later today if I remember

**Comment by drmDev** [comment]
Related to issue #1341

**Comment by drmDev** [comment]
Confirmed bug. Snapcaster targetting Terminate and then targetting an opponent's creature with Terminate still only required paying {B}{R}. I believe this is the same issue as #2114

**Comment by drmDev** [comment]
Monastery Siege now interacts correctly with modal spells (from commit 94e59e5ee7ee5b267416648321cb2bac70485f07 ). However, flashback spells remain an issue - the cost is not increased there as it should. JUnit tests doesn't support these types of targetting. Init file to reproduce:

hand:Human:Snapcaster Mage:1
graveyard:Human:Terminate:1
battlefield:Human:Island:2
battlefield:Human:Mountain:2
battlefield:Human:Swamp:2
battlefield:Computer:Icefall Regent:1

Cast Snapcaster targetting Terminate, cast Terminate targetting Icefall Regent. Should have to pay {2}{B}{R} but only have to pay {B}{R}. Init file would have to change slightly to test against Monastery Siege (player vs player testing to force selection of Dragons etc). The fix there will need to be on the determination of the cost of the spell at the time it is Flashbacked (perhaps just the FlashbackAbility class, but likely will involve some more framework modifications on Cost related classes).
