### ISSUE TITLE
Fetchlands are not working for me

### ISSUE THREAD

**Issue by frbattid** [magefree/mage#1410]
Both client and server are 1.4.5v0 (xmage.de server).

Fetchlands are not working for me. The sequece is:

1. I fetch in response to some opponent's event.
2. Then I pass the priority to the opponent.
3. The client console says "\<myusername\> is searching for a land" (or something like that), but the deck is not shown in order to search for the land. In fact, the app says "waiting for \<myopponentsname\>"
4. After talking with the opponent, he/she tells me he/she has accepted the fetching.

**Comment by Krebsy** [comment]
You probably figured this out by now, but for any others, usually when this happens to me, I simply click the ability (fetchland in this instance) on the stack, and the window appears to select a land. Hope this helps :)
