### ISSUE TITLE
Deck Editor Not Letting Me Add Or Remove Cards

### ISSUE THREAD

**Issue by GorgoPrimus** [magefree/mage#1414]
I can search for cards, load decks, save 'decks', etc. What I can't do is add cards or remove cards from either preexisting decks or new decks. Clicking on a card name does nothing, double clicking does nothing, none of the four add/remove buttons work, but I can add lands with the feature on the sidebar.

Help please...

**Comment by LevelX2** [comment]
Can you provide a screenshot what your xmage screen looks like?
Is there an error message posted to the client log?

**Comment by GorgoPrimus** [comment]
This is when I first open the deck editor: http://i.imgur.com/pLD0e9K.jpg
This is when I click New on the side:http://i.imgur.com/luGH0aW.jpg

Either way the above description holds true. 

My Log says: http://www.filedropper.com/mageclient

**Comment by LevelX2** [comment]
Thanks, the error in the log seems to cause the problem.
That helps me a lot.

**Comment by LevelX2** [comment]
Can you check if you change the deck and sideboard area to the image view, if adding cards works then?

**Comment by LevelX2** [comment]
Cause: Cards are sorted by Power/Toughness that causes that probelm.
Workaround:
1) Open Deck editor
2) Sort the card area by another column than P/T
3) Exit the deck editor
4) Open deck editor again
5) Adding cards should work
