### ISSUE TITLE
Spellskite and Kolaghan's Command

### ISSUE THREAD

**Issue by ee10bt** [magefree/mage#1419]
When Kolaghan's Command is cast for the "Destroy target artifact." and "Kolaghan's Command deals 2 damage to target creature or player." modes, and Spellskite is the target for the destroy artifact mode, it should be possible to also redirect the 2 damage to it before the Spellskite is destroyed. Currently when Spellskite's ability is activated targeting Kolaghan's Command, there is no choice in which ability to redirect. I assume the destroy artifact mode of Command is redirected, as it appears first on the card. This article discusses the ruling, quoted for your convenience,

http://www.starcitygames.com/article/32036_Modern-Rules-That-Are-Easy-To-Screw-Up.html

(Talking about Spellskite and it's various rulings/interactions...) "The one that comes up the most is Kolaghan's Command, and specifically how it differs from Electrolyze. For those not familiar with the confusion here, a Kolaghan's Command that targets Spellskite for the “Destroy target artifact” mode and something else for the “Deal 2 damage to target creature or player” mode can have the damage redirected to Spellskite. On the other hand, an Electrolyze that deals one to Spellskite and one to something else cannot have the second point of damage redirected to Spellskite. The difference here is in the number of times the word “target” is used on the card. Because Kolaghan's Command says “target” twice, it can be redirected. Electrolyze, Arc Lightning, and other similar effects only use it once." 

Thanks, and keep up the good work!

**Comment by drmDev** [comment]
Will need to test this interaction to see if still occurring. Will test later today if I remember

**Comment by drmDev** [comment]
Just tested and the interaction works fine. Had Kolaghan's Command in hand, Spellskite, and Matter Reshaper in play. Used K_command modes 2 and 3 to deal 2 to Reshaper and Destroy Spellskite, then redirected to Spellskite. Spellskite took 2 damage and then was destroyed and Reshaper remained on the battlefield.
