### ISSUE TITLE
Client disconnects from server

### ISSUE THREAD

**Issue by Jknott85** [magefree/mage#1420]
I have yet to complete a full match on the newest version of xmage. I keep disconnecting, usually sometime in the second game.

**Comment by LevelX2** [comment]
There were no changes in the new version concerning networ connection.
It's more dependent from server client network quality.
And for sure some old problems in the server code.

**Comment by goesta** [comment]
I'll close this issue because it seems to be outdated but feel free to create a new one if this problem still exists.
