### ISSUE TITLE
Soulbond didn't work for Lightning Mauler (half-solved)

### ISSUE THREAD

**Issue by Miryafa** [magefree/mage#1423]
---Solved---
I drafted Lightning Mauler in a Holiday Cube draft and soulbound it to another creature, but when I dropped a Phantasmal Image copying Sun Titan (the kind of creature you want to give haste), I didn't get the option to soulbond with it - the ability didn't even show up.

So to be clear:
1. I played Lightning Mauler and used its Soulbond ability
2. Lightning Mauler was on the field, and I played another creature
3. The triggered ability for Soulbond didn't appear (the bug)
---End of Solved---

In addition, when I looked at the text for Lightning Mauler, Soulbond read "You may pair this creature with another unpaired creature when it enters the battlefield" instead of "You may pair this creature with another unpaired creature when either enters the battlefield."

Please fix this, so I can give my Sun Titans haste.

**Comment by LoneFox78** [comment]
So the Mauler was already paired when you played the creature? Soulbond works only if both creatures are unpaired.

**Comment by hanasu** [comment]
702.92a. Soulbond is a keyword that represents two triggered abilities. "Soulbond" means "When this creature enters the battlefield, if you control both this creature and another creature and both are unpaired, you may pair this creature with another unpaired creature you control for as long as both remain creatures on the battlefield under your control" and "Whenever another creature enters the battlefield under your control, if you control both that creature and this one and both are unpaired, you may pair that creature with this creature for as long as both remain creatures on the battlefield under your control."

**Comment by hanasu** [comment]
As for the textual issue, I don't see a reason why that would be the case from the code. Can you provide a screenshot?

**Comment by Miryafa** [comment]
Ah, I feel silly. Of course soulbond only works when the creatures are unpaired, and it was simply my mistake.

As for the textual issue, I'll see if I can come up with a screenshot.
