### ISSUE TITLE
Swiss pairing does not work properly

### ISSUE THREAD

**Issue by LevelX2** [magefree/mage#1438]
In the third round there should be a pairing of the two players with 6 points.

![swisspairingwrong](https://cloud.githubusercontent.com/assets/2066790/12074353/7ace3e0a-b14e-11e5-8332-349d9befe4da.jpg)

**Comment by LoneFox78** [comment]
The other two remaining players already played against each other on round 1, so it's avoiding a re-match between them. So, technically this is not a bug, but I'm not sure if it's the right thing to do in this situation.
Also, we really should try to find a solution to this quitter problem...

**Comment by emerald000** [comment]
While it looks weird, that is the correct pairing. You should never pair two players together twice in a tournament.
