### ISSUE TITLE
Deck Editor - Allow to search for supertype (e.g. Legendary)

### ISSUE THREAD

**Issue by cow2** [magefree/mage#1439]

**Comment by LevelX2** [comment]
Can you give an example what legendary creatures are not returned?

**Comment by PeteV** [comment]
better to show you what results did return :D

search param:  Legendary Creatures

result:

Time of Need Green Sorcery - Uncommon CHK Sarkhan, the Dragonspeaker
Red Planeswalker
- Sarkhan - Mythic KTK Dark Depths Colorless Legendary Snow Land -
Rare CSP Eiganjo
Castle Colorless Legendary Land - Rare CHK Okina, Temple to the Grandfathers
Colorless Legendary Land - Rare CHK Shinka, the Bloodsoaked Keep
Colorless Legendary
Land - Rare CHK Shizo, Death's Storehouse Colorless Legendary Land - Rare
CHK Karakas Colorless Legendary Land - Uncommon JR Karakas Colorless Legendary
Land - Uncommon LEG Karakas Colorless Legendary Land - Rare ME3 Tomb of
Urami Colorless Legendary Land - Rare SOK Genju of the Realm Gold Legendary
Enchantment - Aura - Rare BOK Day of Destiny White Legendary Enchantment -
Rare BOK Ayumi, the Last Visitor Green Legendary Creature - Spirit 7/3 Rare
SOK Lazav, Dimir Mastermind Gold Legendary Creature - Shapeshifter 3/3
Mythic GTC Jalira, Master Polymorphist Blue Legendary Creature - Human
Wizard 2/2 Rare M15 Livonya Silone Gold Legendary Creature - Human Warrior
4/4 Rare LEG Livonya Silone Gold Legendary Creature - Human Warrior 4/4
Uncommon ME3 Sakashima the Impostor Blue Legendary Creature - Human Rogue
3/1 Rare SOK Iwamori of the Open Fist Green Legendary Creature - Human Monk
5/5 Rare BOK Tsabo Tavoc Gold Legendary Creature - Horror 7/4 Rare INV
Kiki-Jiki,
Mirror Breaker Red Legendary Creature - Goblin Shaman 2/2 Rare CHK Kiki-Jiki,
Mirror Breaker Red Legendary Creature - Goblin Shaman 2/2 Mythic FVL Kiki-Jiki,
Mirror Breaker Red Legendary Creature - Goblin Shaman 2/2 Mythic MMA Kiki-Jiki,
Mirror Breaker Red Legendary Creature - Goblin Shaman 2/2 Mythic MM2 Tuktuk
the Explorer Red Legendary Creature - Goblin 1/1 Rare C14 Tuktuk the
Explorer Red Legendary Creature - Goblin 1/1 Rare ROE Tolsimir Wolfblood
Gold Legendary Creature - Elf Warrior 3/4 Rare RAV Konda's Banner
Colorless Legendary
Artifact - Equipment - Rare CHK Tenza, Godo's Maul Colorless Legendary
Artifact - Equipment - Uncommon CHK Helm of Kaldra Colorless Legendary
Artifact - Equipment - Rare 5DN Helm of Kaldra Colorless Legendary Artifact
- Equipment - Special PTC Heroes' Podium Colorless Legendary Artifact - Rare
BNG Sword of the Chosen Colorless Legendary Artifact - Rare STH Goryo's
Vengeance Black Instant - Arcane - Rare BOK Blind with Anger Red Instant -
Arcane - Uncommon CHK Hero's Demise Black Instant - Rare BOK Mirrorweave
Gold Instant - Rare SHM Vassal's Duty White Enchantment - Rare CHK Kashi-Tribe
Elite Green Creature - Snake Warrior 2/3 Uncommon SOK Willow Satyr
Green Creature
- Satyr 1/1 Rare LEG Willow Satyr Green Creature - Satyr 1/1 Rare ME3 Konda's
Hatamoto White Creature - Human Samurai 1/2 Uncommon CHK Loyal Retainers
White Creature - Human Advisor 1/1 Special CMA Loyal Retainers White Creature
- Human Advisor 1/1 Uncommon ME3 Loyal Retainers White Creature - Human
Advisor 1/1 Uncommon PTK Kitsune Healer White Creature - Fox Cleric 2/2
Common CHK Djinn of Infinite Deceits Blue Creature - Djinn 2/7 Rare
C13 Woodland
Bellower Green Creature - Beast 6/5 Mythic ORI Champion's Helm
Colorless Artifact
- Equipment - Rare CMD Hero's Blade Colorless Artifact - Equipment -
Uncommon FRF Arena of the Ancients Colorless Artifact - Rare CHR Arena of
the Ancients Colorless Artifact - Rare LEG Arena of the Ancients
Colorless Artifact
- Rare ME3
selected all sets and all colors and types

hope this helps

**Comment by fireshoes** [comment]
It searches the rules text of the cards for the words legendary and creature, not the card types.

**Comment by PeteV** [comment]
can't you add a conditional that when creature type above is selected it
will return them?
if it's too time consuming too implement and test, guess I could ?

BTW : I think you guys have done a great job with Xmage, I love it!
keep it going
