### ISSUE TITLE
Java Errors

### ISSUE THREAD

**Issue by Slugggy** [magefree/mage#1441]
i've tried downloading Java numerous times, different types as well, and
the java checker says i do have java, but every time i try to run xmage an error message appears

**Comment by Slugggy** [comment]
![img_1857](https://cloud.githubusercontent.com/assets/16530529/12081500/c8b8c6b2-b22f-11e5-9457-e1d5db11b46c.JPG)

**Comment by goesta** [comment]
I'll close this issue because it seems to be outdated but feel free to create a new one if this problem still exists.
