### ISSUE TITLE
Just got a new computer

### ISSUE THREAD

**Issue by Jknott85** [magefree/mage#1443]
I just got a new computer with windows 8 and I cant seem to figure out how to make xmage work on it. I have java installed and the xmage launcher file downloaded and the icon shows that it should open with java, but when I try the screen blips a window for a tenth of a second and then nothing.

**Comment by Jknott85** [comment]
It's windows 10 though, thought it was 8

**Comment by Jknott85** [comment]
Alright, so I figured out how to bypass the launcher and am able to play, thank you for switching it to a launcher issue' it gave me the notion to try and search for the program without the launcher.

**Comment by larsvca** [comment]
I have the same problem, how did you bypass the launcher? Maybe make a step by step guide.

**Comment by Batil** [comment]
I am using windows 7 and have the same problem. Managed to run xmage by clicking on startMageWin7 and I could play. But then v1.4.7 arrived and I could not update because launcher still did not work. When I double click on launcher in says "could not find or load main class...". Anybody know how to fix my problem?

**Comment by Batil** [comment]
Is there maybe a way to update without the launcher?

**Comment by fireshoes** [comment]
You can download the zip file for the client in the release thread stickied in the xmage forum on slightlymagic.net.

**Comment by rollergo11** [comment]
Not sure if this is the issue, but make sure the launcher file is not somewhere that is read-only. Where do you have the launcher located?

**Comment by Batil** [comment]
Must admit that I know next to nothing about computer. The folder with xmage is on my desktop and when I right click and look at properties it does have a tick in the read only box. Not sure how to change this.

**Comment by Batil** [comment]
Thank you so much for all aboves help I will be playing xmage tonight. You all rock. Just downloaded the zip file in the end.

**Comment by rkfg** [comment]
Have you tried the newest launcher version? I've fixed several bugs in it, maybe your case is covered now.

**Comment by goesta** [comment]
I'll close this issue because there where no feedback for a long time but feel free to create a new one if this is still a problem.
