### ISSUE TITLE
Ruin In Their Wake and Null Caller

### ISSUE THREAD

**Issue by zachberglund** [magefree/mage#1459]
Both of these cards seem to be bugged. Ruin In Their Wake won't let the player search their library, while Null Caller tries to exile a creature you own on the battlefield rather than the graveyard.

**Comment by Fruglemonkey** [comment]
+1 affected by this too

**Comment by albuzs** [comment]
+1 affected by this too. will delete my thread

**Comment by albuzs** [comment]
any idea when might this get fixed?

**Comment by fireshoes** [comment]
Null Caller is fixed already for next update. Not sure on Ruin in their Wake.

**Comment by albuzs** [comment]
awww

thx Shoes :)

**Comment by LevelX2** [comment]
Ruin in Their Wake is fixed beyond 1.4.7v1
