### ISSUE TITLE
Press Into Service doesn't untap or give haste

### ISSUE THREAD

**Issue by Neatname** [magefree/mage#1472]
Press Into Service doesn't untap or give haste

**Comment by LevelX2** [comment]
Should be fixed with server running 1.4.7v1. So when and connected to which server did you notice this bug?

**Comment by fireshoes** [comment]
I checked it. It just gaining control. The second target pointer is just set on gain control, so I guess the untap and haste are still trying to use the Support targets.

**Comment by LevelX2** [comment]
Fixed beyond 1.4.7v1
