### ISSUE TITLE
Computer A.I. should be stronger

### ISSUE THREAD

**Issue by JazzJohannes** [magefree/mage#1474]
Enhancement: Me and my girlfriend constantly play against two computers (mad, level 10, serious game, Built-from-Scratch default deck - but also other very strong ones), and we always win, it would be nice if they could be made stronger to actually win themselves here and there or at least get our life counter down to like 2 or so.

**Comment by LevelX2** [comment]
I totally agree.
Here's the solution:
https://github.com/magefree/mage/wiki/Developer-Getting-Started
