### ISSUE TITLE
doesn't update

### ISSUE THREAD

**Issue by xenob8** [magefree/mage#1476]
trying to update to 1.4.7 but download stops at around 40% every time

**Comment by LevelX2** [comment]
But you can download from the sources?
http://bit.ly/xmage_1_4_7v1o
http://bit.ly/xmage_1_4_7v1w

**Comment by masonro** [comment]
i can't, also, when I update the launcher it is a corrupted file and I can't open it.

**Comment by goesta** [comment]
I'll close this issue because it seems to be outdated but feel free to create a new one if this problem still exists.
