### ISSUE TITLE
Save past match histories to compute user stats

### ISSUE THREAD

**Issue by menocar** [magefree/mage#1478]
Now that the basic password user authentication is implemented we can start doing interesting stuff like computing user stats (number of games played, rating, etc). For this purpose, I propose to store past match histories persistently, to build a foundation for the user stats computation.

Here's my initial attempt to convert match histories to a persistent format:

https://github.com/menocar/mage/commit/86dcd000b3f54af5df6456fc2d59d89283b04350

Which outputs protobuf messages like the following:

```javascript
tourney {
  booster_info: "3xOGW "
  players {
    name: "Computer Player 3"
    player_type: "Computer - mad"
  }
  players {
    name: "menocar"
    player_type: "Human"
    quit: DURING_ROUND
  }
  players {
    name: "Computer Player 4"
    player_type: "Computer - mad"
  }
  players {
    name: "menocar2"
    player_type: "Human"
    quit: DURING_DRAFFTING
  }
  rounds {
    round: 1
    matches {
      game_type: "Two Player Duel"
      deck_type: "Limited"
      games: 1
      draws: 0
      players {
        name: "menocar"
        wins: 0
        quit: QUIT
      }
      players {
        name: "Computer Player 3"
        wins: 1
      }
    }
    byes: "Computer Player 4"
  }
  rounds {
    round: 2
    matches {
      game_type: "Two Player Duel"
      deck_type: "Limited"
      games: 3
      draws: 0
      players {
        name: "Computer Player 4"
        wins: 2
      }
      players {
        name: "Computer Player 3"
        wins: 1
      }
    }
  }
}
game_type: "Booster Draft Elimination"
deck_type: "Limited"
controller_name: "menocar"
start_time_ms: 1453113031493
end_time_ms: 1453113339125
```

We can append the messages to per-day history files by following the same technique as: http://stackoverflow.com/questions/13756755/how-to-write-multiple-protocol-buffers-messages-into-an-a-appendable-compressed

Then, on each server start up we can read those files and compute per user stats. Here maybe some caching is necessary not to slow down the start up time too much.

Please let me know your thoughts on this plan, particularly:
* Any objections for using protobuf? What's the alternative you recommend?
* How should we save match histories? Do we want a DB for this?
* What information should be logged additionally to compute user stats? Please check result.proto to see what's captured right now.

**Comment by quercitron** [comment]
I like the idea of saving tournaments/matches history. Some thoughts:
> Then, on each server start up we can read those files and compute per user stats.

So with this approach we won't update stats in real time? As far as I know if everything is fine server is restarted not very often.
> Any objections for using protobuf? What's the alternative you recommend?

I have never worked with protobuf, so I cannot say anything against it. Is it better than storing in XML or JSON?
> How should we save match histories? Do we want a DB for this?

Yeah, it might be even better to store it in some DB.

**Comment by menocar** [comment]
> So with this approach we won't update stats in real time? As far as I know if everything is fine server is restarted not very often.

Not necessarily, we can run the same code and compute the latest stats on the fly.

> I have never worked with protobuf, so I cannot say anything against it. Is it better than storing in XML or JSON?

Serialized format is compact. 

> Yeah, it might be even better to store it in some DB.

Is there any particular reason to prefer that?

**Comment by LevelX2** [comment]
How about only writing the data to file or DB and create the process to calculate and show the player records as an independant process not directly integrated into XMage server.
Maybe the process writes some summary to a DB also accessed by the XMage Server that shows for a user only something like the win rating and a cancel/disconnect rating. 

All other information more than that can only be accessed by the browser  using some web sites?

**Comment by quercitron** [comment]
>> Yeah, it might be even better to store it in some DB.

> Is there any particular reason to prefer that? 

With DB we don't have to process full history for some particular requests (e.g. get stats of some specific player).

**Comment by menocar** [comment]
(Sorry I submitted my comment too early...)

quercitron,

> So with this approach we won't update stats in real time? As far as I know if everything is fine server is restarted not very often.

Not necessarily, we can run the same code and compute the latest stats on the fly.

> I have never worked with protobuf, so I cannot say anything against it. Is it better than storing in XML or JSON?

What's good about protobuf compared to those options is that it provides a simple scheme defining language (see result.proto), which protects us from writing wrong data processing code, by providing auto generated accessors. Also the serialized format is very compact.

> Yeah, it might be even better to store it in some DB.

Is there any particular reason to prefer having a DB? The data format is going to be deeply nested and it won't be mapped to a simple table, so we'd need to store the structure as a blob. Also for now we only need sequential access for calculating stats. That was the reason why I thought bare files are enough.

LevelX2,

I like the idea of having it separated from the XMage server process, which keeps the server simple. What do you think about the additional set up cost? You'd need to run the stats computation program in addition to the server process. Which is an additional step for everyone who runs their own XMage server.

**Comment by menocar** [comment]
> With DB we don't have to process full history for some particular requests (e.g. get stats of some specific player).

You can calculate simple stats, but in order to calculate things like ELO rating, you need to take into account other users' data also, which requires the stats computation program to process the whole data.

**Comment by menocar** [comment]
After some thoughts I got to this revised idea. We will have the following 2 DBs:

History DB: Two columns, match end time and serialized match proto message.
User stats DB: Two columns, serialized user stats proto message, plus the end time of the latest match that updated the row.

Then we add the following code:

* XMage server saves match histories to the history DB.
* XMage server periodically (say, once in a minute) runs stats computation code. That works as:
  * Looks up the latest match end time from the user stats DB.
  * Read all entries after the end time from the history DB.
  * For each history entry update the relevant entries in the user stats DB.

I think this is simple enough that it can still exist in the server code. What do you think?

**Comment by menocar** [comment]
I implemented it in the following pull request, please take a look.

https://github.com/magefree/mage/pull/1482

**Comment by menocar** [comment]
Closing this as the code is checked in now.
