### ISSUE TITLE
Krallenhorde Killer (transformed Wolfbitten Captive) shows on the stack for its triggering ability and image Wolfbitten Captive.

### ISSUE THREAD

**Issue by LevelX2** [magefree/mage#148]
The tooltip window should be the one of Krallenhorde Killer also the image.

![Wolfbitten Captive](https://f.cloud.github.com/assets/2066790/201436/6f6e39cc-80f3-11e2-95e9-c6216860085a.jpg)

**Comment by emerald000** [comment]
Fixed in a previous update. Closing.
