### ISSUE TITLE
Rollback prompt steals focus

### ISSUE THREAD

**Issue by fireshoes** [magefree/mage#1485]
If you are typing in chat and the other user requests a rollback, it steals focus and your keystroke will deny the rollback request.

**Comment by fireshoes** [comment]
Bump

**Comment by fireshoes** [comment]
Also having a problem with the other player getting a rollback, then for me it acts like I am F9'd even though nothing is selected. Hitting F3 does not help.

**Comment by filipebfs** [comment]
Is there an alternative solution to cancel skipping?

**Comment by JayDi85** [comment]
Nothing to do with it. New choose dialog get focus by design.
