### ISSUE TITLE
Kytheon, Hero of Akros Transformation Trigger

### ISSUE THREAD

**Issue by FastTadpole** [magefree/mage#1494]
Issue with Kytheon getting a transform trigger when attacking with 2 other attackers when brought into the field during declare attackers phase. E.G. with Alehsa, Who Smiles at Death when "..enters battlefield tapped and attacking". Perhaps XMage only counts attackers and/or Kytheon at the beginning of combat.

**Comment by emerald000** [comment]
This is correct. Per the Comprehensive Rules:

508.4. If a creature is put onto the battlefield attacking, its controller chooses which defending player or which planeswalker a defending player controls it's attacking as it enters the battlefield (unless the effect that put it onto the battlefield specifies what it's attacking). Such creatures are "attacking" but, for the purposes of trigger events and effects, they never "attacked."

**Comment by FastTadpole** [comment]
That's deep. Thanks for clearing that up emerald000
