### ISSUE TITLE
Swarm Surge not applying First Strike to Edlrazi Scion tokens

### ISSUE THREAD

**Issue by zdmeyers** [magefree/mage#1496]
Played a few games last night and I ended up playing a Swarm Surge and had some Scion tokens on the battlefield, among other colorless creatures. They all got the +1/+0 benefit, but the scions did not get the first strike benefit while the cards with Devoid did. Scion tokens are considered colorless and should have gotten both +1/+0 and first strike

**Comment by LevelX2** [comment]
Can't reproduce the problem.

By which source the Scion tokens were created?

**Comment by zdmeyers** [comment]
They were created either from Catacomb Sifter, Brood Butcher, or Carrier Thrall (or any combination of the three). It is possible that I did the math wrong after seeing the attack go through. My apologies if it is not really a bug.

**Comment by LevelX2** [comment]
Checked the mentioned cards. I can't see any problem. 
Btw Swarm Surge boosts for +2/+0. 
If the problem happens again reopen this issue.
