### ISSUE TITLE
Video to help new developer

### ISSUE THREAD

**Issue by spjspj** [magefree/mage#1502]
I've been developing in languages (mainly C/Delphi/Perl) other than java for around 22 years now (and in java for about 10 or so) but have always had trouble setting up IDEs (Java in particular) :(.  I've really tried but can't get it setup according to this resource (https://github.com/magefree/mage/wiki/Developer-Getting-Started).  Would it be possible to take a video of a new setup for Netbeans in particular, with it from opening the project to it compiling ok and running the server.  Git and getting the source downloaded from github is fine.  If there are any other resources to follow, am happy to take advice.  Would really like to be able to implement some cards (Cleansing Meditation, Reduce To Dreams appears to be bugged and Mana Web).

**Comment by icetc** [comment]
I followed the same guide a couple of days ago and if I remember it correctly I did some sidesteps to get it to work (though don't remember what). Perhaps it could be a good start to update the guide? How far did you get in setting up the project?

**Comment by LevelX2** [comment]
True it's a good idea. But it's quite a bit of work to craete it in a good qualitry.

So if you have specific questions were your installation fails, feel free to ask we we can help with the problem.
Best on https://gitter.im/magefree/mage
