### ISSUE TITLE
Blinking Dragonlord Silumgar with Brago's trigger does not remove existing control effect

### ISSUE THREAD

**Issue by ogier** [magefree/mage#1513]
What happened:

Dragonlord Silumgar entered the battlefield and took control of Chandra, Pyromaster. Then Dragonlord Silumgar's controller attacked his opponent and targeted Dragonlord Silumgar with Brago King Eternal's on-combat-damage effect. When Dragonlord Silumgar entered the battlefield as the trigger resolved, it took control of Freyalise Llanowar's Fury, and his controller did not lose control of Chandra Pyromaster.

What I expected:

Chandra should have returned to its owner's control when Brago blinked Dragonlord Silumgar.

**Comment by spjspj** [comment]
Have submitted a pull request and merge for this - problem was in Brago's Exile ability.
