### ISSUE TITLE
Missing card : Dismantle

### ISSUE THREAD

**Issue by CarlPoirier** [magefree/mage#1519]
Hi,

I stumbled upon this card which is missing. It would be nice if it was implemented.

Regards,

Carl

**Comment by KratosAurion** [comment]
You can report such cards here: http://www.slightlymagic.net/forum/viewtopic.php?f=70&t=4554&sid=ffba12b25b512bab92256579af5707c2

**Comment by CarlPoirier** [comment]
Thank you for the information, I will do so.
