### ISSUE TITLE
Enhance Pauper rarity check to be able to use a card from all sets independant in which set it was common

### ISSUE THREAD

**Issue by tomejorge** [magefree/mage#1521]
I can't start a pauper game because Walker of the Grove from MM2013 is wrongly recognized as uncommon. 
![xmage error](https://cloud.githubusercontent.com/assets/13402783/12875148/0358bc1c-cde4-11e5-8504-4ab3754e323b.png)

Thank you for your amazing work!

**Comment by spjspj** [comment]
Hi.  It was uncommon in Morningtide

**Comment by fireshoes** [comment]
The MMA version is set as common. The pauper legality check for xmage only
looks at the printing of the the specific version of the card in your deck,
so the MMA version should be ok. Make sure that's the version you are using.

**Comment by spjspj** [comment]
Could this become an enhancement (aka to check that any version of the card was at the correct rarity?
       ` if (!rarities.isEmpty()) {
            for (Card card: deck.getCards()) {
                if (!rarities.contains(card.getRarity())) {
                    invalid.put(card.getName(), "Invalid rarity: " + card.getRarity());
                    valid = false;
                }
            }    `

**Comment by tomejorge** [comment]
Thanks for the reply.

I double checked and it is the one from MMA 2013

![walker](https://cloud.githubusercontent.com/assets/13402783/12875340/47e58d0c-cde8-11e5-8917-3e994c5bd8e9.png)

**Comment by marthinwurer** [comment]
I'm working on this at the moment, it should be committed soon once I get a chance to test it.

**Comment by marthinwurer** [comment]
Fixed in #1559
