### ISSUE TITLE
[Deck Editor] Can't search for ANY card

### ISSUE THREAD

**Issue by Xusje** [magefree/mage#1525]
When I search for ANY card I get zero results.
This is the error I see in the console:

`Error during execution of card repository query statement           =>[AWT-EventQueue-0] CardRepository.findCards org.h2.jdbc.JdbcSQLException: 
General error: "java.lang.IllegalStateException: File corrupted in chunk 54, expected map id 11, got 2 [1.4.187/6]"; SQL statement: ...`

How to solve this?

**Comment by LevelX2** [comment]
Delete all files in the client db subdirectory and connect to a server after that.
That should renew the client db files that seemsvto be corrupted on your system.
