### ISSUE TITLE
Client unable to download images from magiccards.info

### ISSUE THREAD

**Issue by guifig** [magefree/mage#1536]
Since a couple of weeks ago the client became unable to download images from magiccards.info.

I've tried using windows XP, 7 and 10, and it doesn't seem to be related to the OS. XMage was reinstalled as well.

![error](https://cloud.githubusercontent.com/assets/17275479/13082707/fd99515c-d4b8-11e5-8486-b20eb7929519.PNG)

**Comment by quercitron** [comment]
Should be fixed with d139cd591c4f1b23bfe62ff3e18a78eaa05f9909
