### ISSUE TITLE
Stubborn Denial Ferocious

### ISSUE THREAD

**Issue by levysantanna** [magefree/mage#1543]
Ferocious of Stubborn Denial isn't countering. When I had a Thought-Knot Seer in the table Stubborn Denial should be able to counter a creature spell, it isn't working.

Thank you.

**Comment by thechucklingatom** [comment]
That isn't how that works. The ferocious part only refers to the target spell, which the card States is non creature

**Comment by Nightfirecat** [comment]
To be clear, when you have Ferocious, this is how the spell's effect reads:

> Counter target noncreature spell.
