### ISSUE TITLE
Wrong card in a sample edh deck

### ISSUE THREAD

**Issue by wendelscardua** [magefree/mage#1547]
On this deck: `sample-decks/Commander/Commander 2015/Wade into Battle (RW).dck`
It says: `1 [C15:303] Secluded Steppe`

But C15:303 is actually Scoured Barrens, making xmage say the deck is invalid for the Commander format. The number should be C15:337 instead.

**Comment by LevelX2** [comment]
Fixed. But is should be C15:304 I guess.

**Comment by wendelscardua** [comment]
Thanks, and sorry for my mistake...  I had looked it up on Gatherer, but I read the C14 number instead of C15 - also, I read the total number instead of the card number.
