### ISSUE TITLE
Choosing the order to resolve of two replacement effects of Coldsteel Heart should work automatically

### ISSUE THREAD

**Issue by LevelX2** [magefree/mage#1548]
Choosing the order to resolve of two replacement effects of Coldsteel Heart should work automatically

![coldsteelheart](https://cloud.githubusercontent.com/assets/2066790/13206015/089b0082-d8f6-11e5-8a7a-48cdbc19e369.jpg)

**Comment by emerald000** [comment]
Technically, you have to choose the order you apply the replacement effects, since they are not a special case (616.1a-c).

**Comment by Zerrisx** [comment]
Duplicate of #6676
