### ISSUE TITLE
Replenish with Auras not working

### ISSUE THREAD

**Issue by spjspj** [magefree/mage#1550]
Replenish returns the auras in a graveyard to the battlefield but doesn't allow them to be attached to anything (so they go straight back to the gy).

 *303.4f. If an Aura is entering the battlefield under a player's control by any means other than by resolving as an Aura spell, and the effect putting it onto the battlefield doesn't specify the object or player the Aura will enchant, that player chooses what it will enchant as the Aura enters the battlefield. The player must choose a legal object or player according to the Aura's enchant ability and any other applicable effects.*

**Comment by Nightfirecat** [comment]
:+1:

**Comment by spjspj** [comment]
Hmm, tried it again after fetching latest version of code and working now.
