### ISSUE TITLE
Client does nothing when launched

### ISSUE THREAD

**Issue by albuzs** [magefree/mage#1551]
Right after I downloaded 1.4.9v0 (2016-02-21), whenever I click on Launch Client, nothing happens. Usually the prompt that popped up showed some text (I guess what the client was doing?), but now it just stays black.

Java is up to date... any ideas on how to fix this?

**Comment by LevelX2** [comment]
Does the launcher log file (located in the dirtectory of the launcher) include some messages?

What OS do you use?

**Comment by albuzs** [comment]
It just shows black. I am running Windows 7 64 bit

**Comment by rkfg** [comment]
There were lots of Swing race conditions in the launcher that I probably fixed in [this pull request](https://github.com/magefree/Launcher/pull/2). If you can't compile it, I can promptly provide a build.

**Comment by cskau** [comment]
@albuzs, there have now been a couple of fixes to the launcher. Can you re-download the launcher from the website and confirm whether or not this fixes your issue?

**Comment by albuzs** [comment]
Hello,

@cskau I keep on getting "A Jave Exception has ocurred."

**Comment by cskau** [comment]
Thank you for giving it a try.
Do you have a stack trace or some other information to help identify the particular exception you're facing?

It does however sound like the original issue has been solve.

**Comment by albuzs** [comment]
Not sure what a stack trace is?

**Comment by LevelX2** [comment]
> Not sure what a stack trace is?

If after the update of the launcher yesterday to version 0.3.8 the problem still happens on your system open the file xmage_launcher.log located in the same directory as the launcher with a text editor or something similar. Than post the content of the file here (or at least the last part of the text) related to your last attempt to start the client.

**Comment by albuzs** [comment]
It works now, thanks! :D

**Comment by LevelX2** [comment]
Nice to hear.
