### ISSUE TITLE
eldrazi mimic effect

### ISSUE THREAD

**Issue by xenob8** [magefree/mage#1556]
is not working after last update

**Comment by markedagain** [comment]
i did not try the stable version, but worked np with the current master. Can you be more specific about what was issue ?

**Comment by xenob8** [comment]
playing another eldrazi activates the ability of eldrazi mimic but when you click on yes it remains a 2/1 and doesn't copy the base power and thoughness

**Comment by markedagain** [comment]
#7aa0ff1 yup, seems like same day a fix was done for this

**Comment by xenob8** [comment]
i've played like 2 minutes ago and it is still there..

**Comment by markedagain** [comment]
yes, the fix was done after the current release, i imagine a patch version should be going out any day!!

**Comment by LevelX2** [comment]
Best fix overview is alway available in last bug thread in forum
http://www.slightlymagic.net/forum/viewtopic.php?f=70&t=18297&sid=1de07cdc10bcc120362db78aea34ddf2
