### ISSUE TITLE
Hushwing Gryff tries to prevent ability of Ulamog, the Ceaseless Hunger

### ISSUE THREAD

**Issue by andyfries** [magefree/mage#1562]
Ulamog's cast trigger resolves as normal, but when he enters the battlefield the game log fills with messages stating that Hushwing Gryff prevented the ability on Ulamog, the Ceaseless Hunger.

**Comment by drmDev** [comment]
Unable to duplicate this issue. Game log did not fill with any messages as described.

Is this still occurring? Any logs to look into this further?
