### ISSUE TITLE
Spells targeting players continue resolving even when those players leave the game

### ISSUE THREAD

**Issue by ngenisis** [magefree/mage#1600]
If a spell or ability on the stack is targeting a player (or an object controlled by that player), and that player leaves the game, then the target becomes illegal and the spell or ability should be countered upon resolution (assuming that player or object is the only target of the spell). However, Xmage regularly continues resolving spells and abilities targeting players after that player concedes, which is a problem in multiplayer.

Example 1) Player A casts Tendrils of Agony with a storm count of 10 targeting Player B, who is at 10 life. After the first five copies of Tendrils resolve, player A will have gained 10 life and Player B will have lost 10 life, so player B should die as a state-based action before the remaining six copies resolve. In similar circumstances, Xmage has continued resolving the additional six copies, putting player B at -12 life and letting player A gain an additional 12 life inappropriately

Example 2) A player casts Timetwister while controlling Zur's Weirding, so before each card drawn each of my opponents was given the chance to pay 2 life to prevent that draw. After my first few draws were replaced, I conceded. Rather than losing the game because I conceded, Xmage removed my library from the game and continued making me draw cards, then I lost the game for drawing cards from an empty library.

**Comment by drmDev** [comment]
Unsure if problem still persisting since this was over a year ago
