### ISSUE TITLE
Unable to leave tournament

### ISSUE THREAD

**Issue by ngenisis** [magefree/mage#1601]
Today I was in a Swiss tournament for a Vintage Cube 2016 draft. I clicked the button to quit the tournament, and a confirmation box appeared and asked if I was sure I wanted to quit the tournament. I clicked yes and the box went away, but nothing changed and it kept me in the tournament. I tried multiple times to drop the tournament to no avail. If I closed the tournament window, then it reappeared when my next match began, and it continued to not let me drop the tournament even after conceding both games in the match.

**Comment by LevelX2** [comment]
In what stage the tournament was in?
You talk about which server?

Probably there were some issued with the server, not processing your requesats. Very hard to reproduce and fix.
