### ISSUE TITLE
Phyrexian mana with Trinisphere

### ISSUE THREAD

**Issue by emerald000** [magefree/mage#1617]
Choosing whether to pay phyrexian mana with life or mana is chosen in the second part of casting a spell (after putting it on the stack and before choosing targets). For Dismember, you choose if you want to pay {1}{B}{B}, {1}{B} + 2 life or {1} + 4 life. Trinisphere effect is only applied once you determine costs, much farther in the casting process. So it means it increases the cost to cast Dismember to either {1}{B}{B}, {2}{B} + 2 life or {3} + 4 life.

Currently, since you choose how to pay Phyrexian costs during the cost payment stage (after Trinisphere applies), you can pay {1} + 4 life to cast Dismember with a Trinisphere in play.

**Comment by drmDev** [comment]
Probably related to #2114 and #1405 - the casting costs of flashback or modal cards are not taking into account other effects on the battlefield.

**Comment by LevelX2** [comment]
Related post:
http://www.slightlymagic.net/forum/viewtopic.php?f=70&t=19510&p=206082#p206079
