### ISSUE TITLE
Moved Folder, Can't Delete | OSX

### ISSUE THREAD

**Issue by chryton** [magefree/mage#1621]
I moved the XMage folder and files from the initial installation location (my desktop) but it keeps recreating a folder called "xmage" on my desktop. The folder is always 20kb.

Is there a way to stop this?

**Comment by LevelX2** [comment]
Did you use the xmage launcher to install/start xmage?
What's inside the created folder?
The XMageLauncherx.x.x.jar file does create such an folder on startup in the directory it is located in.

So probably you have to move the launcher jar to the directory you moved the xmage and java folder to.

**Comment by chryton** [comment]
> Did you use the xmage launcher to install/start xmage?

Yes.

> The XMageLauncherx.x.x.jar file does create such an folder on startup in the directory it is located in.

The .jar file was moved to the new folder along with the rest of the files.

> What's inside the created folder?
This is what is in the folder: 
![screen shot 2016-03-14 at 12 09 03 pm](https://cloud.githubusercontent.com/assets/2627689/13750839/977eb026-e9dd-11e5-9307-23f7eb629277.png)

**Comment by rkfg** [comment]
It means the server is still running. Check the processes and kill it.

**Comment by chryton** [comment]
Killing the process that was named "java" is what finally allowed me to fix this. Is there any way to avoid this in the future? It seems a bit odd that I would need to kill a process after every time I close the program.

Thank you for your help.

**Comment by rkfg** [comment]
If you start the game from the launcher, it'll ask if you want to stop the running server when you close the launcher. If you leave it running and start to move the game files around, expect just anything. It's not supported for any program I heard about, not just XMage.
