### ISSUE TITLE
Client won't connect to server/start-up properly

### ISSUE THREAD

**Issue by GorgoPrimus** [magefree/mage#1630]
Mar 15, 2016 8:51:59 PM java.util.prefs.WindowsPreferences <init>
WARNING: Could not open/create prefs root node Software\JavaSoft\Prefs at root 0x80000002. Windows RegCreateKeyEx(...) returned error code 5.
INFO  2016-03-15 20:51:59,984 Starting MAGE client version 1.4.9v2                                                       =>[main] MageFrame.main 
INFO  2016-03-15 20:51:59,984 Logging level: INFO                                                                        =>[main] MageFrame.main 
INFO  2016-03-15 20:52:01,499 Loading plugins...                                                                         =>[AWT-EventQueue-0] Plugins.loadPlugins 
INFO  2016-03-15 20:52:01,546 [Game counter plugin, version 0.1] has been loaded.                                        =>[AWT-EventQueue-0] CounterPluginImpl.newPlugin 
INFO  2016-03-15 20:52:01,546 Done.                                                                                      =>[AWT-EventQueue-0] Plugins.loadPlugins 
INFO  2016-03-15 20:52:02,436 Client start up time: 2 
...

**Comment by GorgoPrimus** [comment]
I tried reinstalling it from scratch already; same error.

**Comment by LevelX2** [comment]
It's probably related to install executing user authority.

http://stackoverflow.com/questions/16428098/groovy-shell-warning-could-not-open-create-prefs-root-node

There's not much we can do about I guess.

**Comment by Zerrisx** [comment]
Looks like this was resolved and/or rendered obsolete.
