### ISSUE TITLE
jace architect of thought: bug when deciding order of cards to go to the bottom

### ISSUE THREAD

**Issue by tomejorge** [magefree/mage#1635]
Hi!

I  -2 Jace, choose the pile and then I am not able to move windows around or to click anywhere to chose the order of the cards to go to the bottom. 

Thanks for your awesome work!

**Comment by LevelX2** [comment]
After you have chosen the pile and more than 1 card goes to graveyard, there appears a window with focus where you have to chose the order the cards go to graveyard.
Sounds like this window was not shown to you.
It seems that under some circumstances that window can somehow be hidden. As far as I encountered this, it will reappear as you click on a card on the battlefield, stack or hand.

Was this the case or did I get your problem wrong?

**Comment by tomejorge** [comment]
Hi! Thanks! yeah, that was my problem. The window in focus did not show up to me. I did try to click on other areas such as my hand or the stack but I could not get the window to show. If this occurs again I'll try to triple check and get back with screenshots.

**Comment by LevelX2** [comment]
It can be forced using the CTRL-F6 key combination if a modal select window is visible.

Can this be the cause (accidently pushed) in your case?

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.
