### ISSUE TITLE
Allow players to specify preferred versions of basic lands.

### ISSUE THREAD

**Issue by spjspj** [magefree/mage#1641]
As a player I would like to be able to specify 'my preferred basic lands'.  These would be used to make up the deck from a draft or similar when basic lands are required to be added.

Probably best as a new tab in the client preferences (preferencesDialog.java?).  Something like:
...
updateCache ("preferredIsland", "[ZEN:254] Island");
updateCache ("preferredMountain", "[ZEN:243] Mountain");
...

**Comment by Simown** [comment]
I'd just put it as a drop-down box on the "Basic Land" dialog. Defaulting to the current set's basic lands but possible to change it.

**Comment by spjspj** [comment]
This has been done in the 'add lands' dialog.
