### ISSUE TITLE
GUI - Pushing CTRL-F6 while modal window (e.g. trigger order) locks Xmage

### ISSUE THREAD

**Issue by LevelX2** [magefree/mage#1645]
Pushing CTRL-F6 while a modal window is visible (e.g. trigger order) locks Xmage.
The modal window will go to background and the user can't select anything.

TODO:
Deactivate the Swing default kex STRG-F6 always or at least as long as a modal window is open.

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.
