### ISSUE TITLE
ground seal: can't use delve while ground seal is in play

### ISSUE THREAD

**Issue by cipherz** [magefree/mage#1646]
AFAIK, delve does not target and should work when ground seal is in play.

**Comment by drmDev** [comment]
Confirmed this still occurs at the moment. Also confirmed the ruling - Delve does not target:

http://www.mtgsalvation.com/forums/magic-fundamentals/magic-rulings/magic-rulings-archives/281956-ground-seal-and-delve

"Delve is an ability, but it doesn't target and is therefore unaffected by Seal."

**Comment by ImperatorPrime** [comment]
Fixed by d6e4ef793e5654ab3b6410cac25c2fa359868868
