### ISSUE TITLE
A new shortcut similar to F4 to say 'Skip to End Step of Active Opponent to my Right'

### ISSUE THREAD

**Issue by spjspj** [magefree/mage#1647]
In multiplayer, this would allow you to essentially F9 but then still do things on the end step just prior to your own turn.  It would ignore any extra turns that that player would have as that would make it too complicated.  

Some odd scenarios: 
If the player to your direct right was killed by the player to your next-to-right then you would get priority at the end of your next-to-right player (which would now be your directly right active player), if that makes sense.

**Comment by fireshoes** [comment]
I like this suggestion. Also skip until the Beginning of Combat would be great, so you can tap a creature down, etc before a declare attackers trigger can occur.

**Comment by drmDev** [comment]
Can close this one out with your latest change to it. Good work!
