### ISSUE TITLE
disrupting shoal: hardcast for 2 targeting 2 cmc spell did not counter

### ISSUE THREAD

**Issue by cipherz** [magefree/mage#1648]
My opponent was hardcasting a disrupting shoal targeting a 2 cmc spell, upon resolving nothing happened and my spell still resolved.

**Comment by drmDev** [comment]
Is this still occurring? Do you remember the scenario where this happened? Test for Disrupting Shoal hardcast for X=2 counters a 2 CMC spell:
https://github.com/magefree/mage/blob/master/Mage.Tests/src/test/java/org/mage/test/cards/abilities/oneshot/counterspell/DisruptingShoalTest.java#L41-L60

**Comment by drmDev** [comment]
we have a lot of Disrupting Shoal tests, and all of them are passing. Unable to duplicate the issue. Will re-open if confirmed occurs again.
