### ISSUE TITLE
Insufficient logging for Tempting Offer

### ISSUE THREAD

**Issue by fenhl** [magefree/mage#1658]
The choice made by each player should be shown in the log.

**Comment by LevelX2** [comment]
For which card exactly do you think the log is insufficient?

**Comment by fenhl** [comment]
Tempt with Vengeance.

**Comment by LevelX2** [comment]
Hmm there should be a message in the game log:
[Player name] puts a [Token name] token onto the battlefield.

That's not enough?
I don't like cluttering the log with redundant information.

**Comment by fenhl** [comment]
I'm certain there was no such message in the log. That or the APNAP rule is being disregarded.

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.
