### ISSUE TITLE
Brood Sliver implemented incorrectly

### ISSUE THREAD

**Issue by fenhl** [magefree/mage#1660]
It lets the controller of Brood Sliver choose whether or not the token is created, instead of the attacking Sliver's controller.

**Comment by drmDev** [comment]
Added test - did not duplicate the issue. Attacking sliver was not the controller of Brood Sliver and was given option of creating the token.

**Comment by drmDev** [comment]
In game testing shows something different (vs AI) - no choice for the "may" ability was presented, but the token was still created.

**Comment by drmDev** [comment]
confirmed test pass
