### ISSUE TITLE
Multi-table handling

### ISSUE THREAD

**Issue by drmDev** [magefree/mage#1662]
Some players like myself would like better handling of 2 tables at the same time. Right now it is extremely cumbersome to the point I pretty much never do it anymore - you have to go to the menu in the top right, click Windows, click the table name, and repeat ad nauseum. And you have to keep doing that every moment you can since there is no indication something on a table needs your response.

There's multiple ways around this, so perhaps can split this into different enhancement requests.

1) Allow the tables to have resizing and moving capabilities. For instance, if someone has multiple monitors they can just move the 2nd table to their second monitor. Or you can simply have the two tables stacked on top of each other at 50% height.

2) Make the tables a "tab" on the bottom of XMage that flashes/changes color when waiting for your response. Then you could for instance have joined 2 tables, and with the 1 table up do the actions and set the skips as needed. Then click the tab to swap to the next window and do the same thing. Then you continue playing until the tab flashes/changes colors to let you know your skip has completed or a response is needed otherwise.

3) Add preferences for Multiple Table Handling that automatically move and position the tables as you desire - say you want the 2nd table to appear on your 2nd monitor. Or you just want both tables opened on the same monitor, shrunk to 50%. Or you just want 1 table in front of you with the other as a clickable tab to swap between tables.

4) Add a keyboard shortcut to let you swap between Windows and/or tables. Maybe like CTRL+1 to go to Table 1 and CTRL+2 to go to Table 2. Or whatever makes sense there.

For examples of what I'm referring to, think of Poker software that lets you multi-table and move and resize tables. If you're unfamiliar they can look like this with 4 tables:
http://www.mosesbet.com/wp-content/uploads/2009/12/carbon-multi-table1.jpg

**Comment by spjspj** [comment]
@drmDev  I like the last suggestion the most as a quick/easy win for this (Ctrl+1, Ctrl+2).  I was thinking as well having something like 'Alt+q' or similar to cycle through all menu options in the Windows (For example: 'Tables', 'Deck Editor', 'Playing: A - B', 'Playing: A - C - D')  (And Alt+Shift+q for the reverse of this)

**Comment by JayDi85** [comment]
See actual tasks in #5431 (tabs toolbar) and #11726 (multi-monitor)
