### ISSUE TITLE
Can't crack Lion's Eye Diamond after spell is on the stack.

### ISSUE THREAD

**Issue by Cysec2k** [magefree/mage#1665]
Lion's Eye Diamond can't be used in the current version as I can't trigger it's ability once I've put a spell from my hand onto the stack.  I can crack it at any other time I have priority, which defeats the purpose as it wipes out my hand, thus negating having anything to spend the mana on.
[20160326_172942_Two Player Duel_1.txt](https://github.com/magefree/mage/files/190662/20160326_172942_Two.Player.Duel_1.txt)

**Comment by strigonLeader** [comment]
This appears to be a rules misunderstanding. Lion's eye diamond's ability cannot be activated as part of the cost of casting a spell, as it says that it can only be used any time that you could cast an instant.

http://blogs.magicjudges.org/rulestips/2013/01/all-about-lions-eye-diamond-yes-its-a-mana-ability-but-it-has-a-timing-restriction/

**Comment by Cysec2k** [comment]
Thank you very much for the timely response! The article was very
informative.
