### ISSUE TITLE
[SOI] Wolf of Devil's Breach incorrectly forces you to discard

### ISSUE THREAD

**Issue by draxdyn** [magefree/mage#1668]
It asks to discard before asking you whether you want to use the ability, and while you can choose not to pay 1{R} later, the card is already discarded and stays in the graveyard.

It should probably ask you to pay 1{R} first and only ask to discard if you pay.

**Comment by drmDev** [comment]
fixed but won't be available until at least April 5th release

**Comment by draxdyn** [comment]
Is DoIfCostPaid still needed now that the ability as a whole is optional?

**Comment by drmDev** [comment]
I didn't look it over too much - I just noticed the optional flag was mistakenly set to "false". DoIfCostPaid should still be tied in with the costs paid (mana costs and discard)

**Comment by drmDev** [comment]
Will close upon confirmation in new release after April 5th

**Comment by draxdyn** [comment]
I'm worried that the DoIfCostPaid might allow to discard a card but not pay the costs or trigger the ability, which is not allowed by the rules. Again, not really sure whether this is the case or not.

**Comment by drmDev** [comment]
Just tested it. There still is a bug here. The card is still discarded even if you select not to use the may ability.

**Comment by drmDev** [comment]
Reordered the costs - it asks to pay 1R, if you select Cancel then you do not have to select a card to discard. Now works as expected.

**Comment by drmDev** [comment]
Added tests for the two basic scenarios to the repo - attack and pay the cost, and attack and not pay the cost. Attack and not pay cost test is still failing. Card needs to be fixed still.
