### ISSUE TITLE
Tireless Tracker: Multiple Issues

### ISSUE THREAD

**Issue by deanboyj** [magefree/mage#1671]
First issue: Tireless Tracker is receiving investigate triggers both when you play a land and when opponent plays a land.

Second issue: Tireless Tracker is not gaining +1/+1 counters when sacrificing clue tokens.

**Comment by fireshoes** [comment]
Fix for this will be available with tomorrow's update.

**Comment by drmDev** [comment]
1st ability is fixed, but 2nd ability is not. Tireless Tracker is not getting +1/+1 counters upon sacrificing clues.

**Comment by drmDev** [comment]
2nd ability now fixed as well.
