### ISSUE TITLE
SOI Bugs

### ISSUE THREAD

**Issue by guizonatto** [magefree/mage#1676]
Tireless Tracker - triggering on every land (mine and opponent's) and not getting counter after sacrificing a clue.
Intrepid Provisioner - not triggering when comes into play.
Jace, Unraveler of Secrets - entering in the battlefield with 0 loyalty
Slayer's Plate - Only gives +2/+2 instead of +4/+2
Flameblade Angel - Not triggering when damage is dealt to the creatures I control.

**Comment by Jell** [comment]
Welcome to the fold - does not take control of target create
Erdwal Illuminator - not triggering on investigate
Ulvenwald Mysteries - not triggering on clues being sacrified

**Comment by fireshoes** [comment]
Ulvenwald Mysteries, Tireless Tracker, and Jace are all fixed for tomorrow's update. The others will not be available until after Apr 5 at earliest.

**Comment by drmDev** [comment]
Slayer's Plate, Ulvenwald Mysteries and Intrepid Provisioner fixed but won't be available until after April 5th.

**Comment by Zorkony** [comment]
You can get Scrounged Scythe as a card in your pool instead of the scarecrow

**Comment by drmDev** [comment]
Yeah that's part of someone mistakenly coding that card thinking it was single-sided. It's supported to be part of Harvest Hand. Right now its implemented as if it is a separate equipment card with no CMC. Another fix that won't be available until at least April 5th.

**Comment by Zorkony** [comment]
wolf of devil's breach doesnt give the option to discard, it just does. missing "may"?

**Comment by drmDev** [comment]
Wolf of Devil's Breach is fixed beyond this current version - won't be active until at least April 5th

**Comment by Zorkony** [comment]
erdwal illuminator doesnt give extra investigate

**Comment by drmDev** [comment]
Erdwal was already reported in this issue. Usually recommend creating separate issues for each individual issue so we can close them out as they are resolved.

**Comment by drmDev** [comment]
I am creating separate issues for each card mentioned here. Closing this thread. Create a separate issue for each individual card with a problem.

**Comment by drmDev** [comment]
Closing. Thanks for the reports. Look at the existing issues and create new ones for each individual one.
