### ISSUE TITLE
Laboratory Maniac incorrectly causes you to lose with limited range of influence

### ISSUE THREAD

**Issue by draxdyn** [magefree/mage#1681]
With limited range of influence in Commander (and non-eliminated players outside the range), drawing from an empty library causes you to lose the game even with Laboratory Maniac in play.

The reason appears to be that the state-based check for drawing from an empty library still applies.

However, Gatherer says that "If for some reason you can't win the game (because your opponent controls Platinum Angel, for example), you won't lose for having tried to draw a card from a library with no cards in it, because the draw was still replaced."

Instead, XMage sets the "isEmptyDraw" flag even if the draw was replaced, which seems incorrect.

The root cause seems to be that Laboratory Maniac is implemented wrong by having it replace an "empty draw" event and not replace the draw.

Instead, the "empty draw" event should be removed from XMage and Laboratory Maniac should just replace the draw event and have the replacement effect apply only when the library is empty, which appears to be the correct interpretation of the rules and the Gatherer resolution, and should fix the issue.

**Comment by drmDev** [comment]
Perhaps this test was made for this issue? https://github.com/magefree/mage/blob/master/Mage.Tests/src/test/java/org/mage/test/cards/replacement/WinLoseEffectsTest.java#L43-L66 

not sure if this issue still occurring
