### ISSUE TITLE
[SOI] Cult Of The Waxing Moon not creating wolf token after a transformation into non-human

### ISSUE THREAD

**Issue by tomejorge** [magefree/mage#1687]
Hi,

Cult Of The Waxing Moon is not giving the wolf token when a creature is transformed into a non-human.

Thanks!

**Comment by drmDev** [comment]
"It appears to trigger either when a non-human creature transforms OR when a creature transforms from a non-human into a human (as in when a werewolf flips back to the sun side), rather than when a creature transforms into a non-human, as is the intended function and wording of the card."

**Comment by drmDev** [comment]
Confirmed issue, added test: df1b931014f11814eb9ecf104077c7a4a05d2d5d

Haven't figured out the issue with the code yet. It looks at EventType.Transform for Subtype Not-Human. I tried EventType.Transform and it still has the same issue.
