### ISSUE TITLE
Jace, Unraveler of Secrets - entering in the battlefield with 0 loyalty

### ISSUE THREAD

**Issue by drmDev** [magefree/mage#1692]
Jace, Unraveler of Secrets - entering in the battlefield with 0 loyalty

Split from mega thread https://github.com/magefree/mage/issues/1676

Issue resolved, closing. just here for easier tracking.

**Comment by drmDev** [comment]
will close out upon confirmation in new release after April 5th

**Comment by fireshoes** [comment]
I confirmed the fix works using release 1.4.9v4 on xmage.de
v4 is available [here](http://bit.ly/xmage_1_4_9v4w)
