### ISSUE TITLE
[SOI] Prized Amalgam not triggered from Gravecrawler cast from grave

### ISSUE THREAD

**Issue by drmDev** [magefree/mage#1704]
"Whenever a creature enters the battlefield, if it entered from your graveyard **or you cast it from your graveyard**, return Prized Amalgam from your graveyard to the battlefield tapped at the beginning of the next end step. "

Not sure if an issue with Gravecrawler "You may cast Gravecrawler from your graveyard as long as you control a Zombie." or Amalgam. Handling might just be putting Gravecrawler into play instead of casting it.

**Comment by drmDev** [comment]
Reanimating a creature correctly triggers it still. Something specific to Gravecrawler perhaps?

**Comment by fireshoes** [comment]
Perhaps casting makes it not be seen as coming from the graveyard because it goes on the stack first?

**Comment by drmDev** [comment]
Additionally, Prized Amalgam appears to trigger for opponent's returning creatures from graveyard to battlefield.

"Prized Amalgam recursion ability was triggering with opponent's creatures returning from the graveyard ala Ojutai's Command."

**Comment by drmDev** [comment]
Resolved the bug with opponent's creature recursion triggering Prized Amalgam in commit 8ea813e7cdb02d09db938777ad2eb35688f99289

Added tests for Prized Amalgam there as well, including the remaining bug with Gravecrawler cast from grave not triggering it.

**Comment by drmDev** [comment]
With the latest change mentioned above, if an opponent returns a creature from your graveyard, it should trigger Amalgam, but does not. So the card still has two bugs:

Not handling "cast from graveyard" (i.e. Gravecrawler) properly, and not correctly triggering every time when a creature enters/cast from your graveyard.
