### ISSUE TITLE
[SOI] Eerie Interlude does not return all creatures back from exile

### ISSUE THREAD

**Issue by drmDev** [magefree/mage#1706]
"Eerie Interlude, new from SoI, will exile any number of creatures like it should, but at end step when it triggers to bring them all back, it only brings one creature back, leaving the rest in exile!"

**Comment by drmDev** [comment]
I believe the card Ghostway also is impacted since they work similarly.

**Comment by sjholden** [comment]
Ghostway certainly has the same behavior - with only one creature returning at end step.

**Comment by LevelX2** [comment]
Probably fixed with the changes to ReturnToBattlefieldUnderOwnerControlTargetEffect with ae932f9dd7ef886c2ee365dc3f40e36ecd6640fe.
Can someone test this?

**Comment by drmDev** [comment]
Tested both cards - correctly returned the creatures back from exile at the end step as intended now with the recent changes.
