### ISSUE TITLE
"Player joined/left" bubble doesn't pop up on windows 10

### ISSUE THREAD

**Issue by guifig** [magefree/mage#1720]

**Comment by Zerrisx** [comment]
What is/was this bubble - does somebody have a screen shot?

**Comment by JayDi85** [comment]
Try to use two clients and join one game. Table owner must receive popup message in windows task panel about game ready (if his client window is not active for him).

Just example:
![shot_200717_223514](https://user-images.githubusercontent.com/8344157/87819733-d0563800-c87d-11ea-8df2-54641c25ca32.png)

**Comment by Zerrisx** [comment]
Seems like it works to me.

![image](https://user-images.githubusercontent.com/59861365/87820381-9b24f800-c833-11ea-8add-590dca6ded08.png)
