### ISSUE TITLE
Declaration in Stone generatles clues on tokens

### ISSUE THREAD

**Issue by albuzs** [magefree/mage#1722]
Hello,

When you cast Declaration in Stone on a token, clues are generated. The card states that for each non token exiled this way, put a clue token.

**Comment by drmDev** [comment]
Duplicate issue. Already resolved. Will be available in release v5. See #1702 and commit with the code change: 582bd1b4bbfebe03ae5d0ef823d1a3d89c7d0263

**Comment by albuzs** [comment]
My apologies! I search before and nothing came up.

Thanks!

**Comment by drmDev** [comment]
No problem. Have to make sure the filter you're using when looking at the existing issues includes closed ones to find them (default is to only look at open issues)
