### ISSUE TITLE
Add 2016 MTGO Legendary Cube

### ISSUE THREAD

**Issue by draxdyn** [magefree/mage#1723]
It's significantly changed from the first 2015 version (which should be kept, since it's legendary-only and interesting in its own right).

Cardlist at http://magic.wizards.com/en/MTGO/articles/archive/legendary-cube-cardlist

**Comment by fireshoes** [comment]
It's on my to-do list, once I get my netbeans running again.

**Comment by spjspj** [comment]
I think this was uploaded?

**Comment by drmDev** [comment]
Added with commit 2778ae2381445b1848ce2fcf8503f789159e3d79
