### ISSUE TITLE
Constant disconnection after update

### ISSUE THREAD

**Issue by TheGreenMage14** [magefree/mage#1725]
After I've updated to the newest version of Xmage I am constantly booted from the program with no rhyme or reason. Disconnection happens about ever 5 minutes or less and makes it impossible to play games, let alone matches or tournaments. I don't know if it has to do with the server, the update, or the newest set, but it boots in the middle of everything no matter what set or structure it is.

**Comment by goesta** [comment]
I'll close this issue because it seems to be outdated but feel free to create a new one if this problem still exists.
