### ISSUE TITLE
[SOI] Welcome to the Fold and Slayer's Plate bugs

### ISSUE THREAD

**Issue by MABatista** [magefree/mage#1729]
Welcome to the Fold when case on a 6/2 failed to take control of the creature. 

Slayer's Plate when played on a 1/1 flier gave +2/+2 rather than +4/+2.

**Comment by MABatista** [comment]
Adding more details on the Slayer's Plate issue. The hover text on the card did read "+2/+2" though the text on the card itself reads otherwise.

**Comment by drmDev** [comment]
Both duplicate issues. Both resolved beyond v4.

Welcome to the Fold: #1695 
Slayer's Plate: #1693
