### ISSUE TITLE
[SOI] Jace enters with no loyalty counters?

### ISSUE THREAD

**Issue by strigonLeader** [magefree/mage#1730]
In a recent draft match my opponent's jace immediately died upon entereing the battlefield, I'm assuming this is caused by no loyalty counters being put onto him.

**Comment by drmDev** [comment]
Resolved beyond v4. Duplicate #1692 

Actually this one should even be resolved in v4 - the xmage.de server is the only one updated to v4. Woogerworks still is not (last I checked at least). That may be the issue here. Either way, tested and this issue is confirmed resolved with the current code.
