### ISSUE TITLE
[SOI] Graf Mole sacrificing clues does not trigger ability

### ISSUE THREAD

**Issue by strigonLeader** [magefree/mage#1733]

**Comment by drmDev** [comment]
Need more details. Which cards are you referring to? Tireless Tracker, Fleeting Memories, and Ulvenwald all have been fixed beyond v4. Are there are other cards you are referring to?

**Comment by dampete** [comment]
I remember Erdwall Illuminator wasn't WAI, but I'm coming from v3, not sure if it's fixed already in v4.

**Comment by drmDev** [comment]
Erdwall has a separate issue #1696 - still unresolved. It is not granting an extra Investigate. It's likely related to the fixes that had to be done for the cards mentioned. Will look into later.

**Comment by strigonLeader** [comment]
The triggered abilities belonged to Fleeting Memories and Graf Mole, the clues were produced by Drownyard Explorers, I believe.

**Comment by drmDev** [comment]
Graf Mole has not been reported yet, thanks. I updated the title to reflect that. Looking into the issue shortly. Might be an easy fix.

Fleeting Memories is fixed beyond v4.

**Comment by drmDev** [comment]
Graf Mole fixed beyond v4 in commit 5f956bb69dc0cde006d7a1a8d2a8ad030aa688bd 

Same issue as the other "Sacrifice a clue:" triggered ability cards. `SacrificeAllTriggeredAbility` did not catch the clues correctly in any of the cards.
