### ISSUE TITLE
Centaur Vinecrasher land hitting graveyard trigger not working

### ISSUE THREAD

**Issue by drmDev** [magefree/mage#1734]
Reported Bug
"Whenever a land card is put into a graveyard from anywhere, you may pay Green Green. If you do, return Centaur Vinecrasher from your graveyard to your hand."

Probably related to #1728 with Gitrog Monster not triggering from lands hitting grave either.

**Comment by drmDev** [comment]
This may have been resolved with the Gitrog Monster related fixed in #1728 and #1779

**Comment by drmDev** [comment]
This is still an issue in 1.4.10v1. When a land hits the graveyard, Centaur does not trigger.

**Comment by LevelX2** [comment]
Hmm code looks good at a first glance. 
How did you reproduce?

**Comment by drmDev** [comment]
Manual testing. Init file:

graveyard:Human:Centaur Vinecrasher:1
battlefield:Human:Evolving Wilds:1
battlefield:Human:Forest:2

When you crack Evolving Wilds to put it into the grave, no trigger occurs
