### ISSUE TITLE
[SOI] Jace, Unraveler of secrets emblem

### ISSUE THREAD

**Issue by deanboyj** [magefree/mage#1739]
The emblem was not countering my opponent's first spell.  They had cast oblivion sower there was never a trigger from the emblem to counter it.  It was his first spell

**Comment by drmDev** [comment]
Duplicated issue with ingame testing. After creating the emblem, the spell cast by the opponent next turn was not countered:

![jaceemblem](https://cloud.githubusercontent.com/assets/11060241/14226352/d87c56da-f8ad-11e5-95a5-61ee0f4fa9e5.png)

(relevant portions of) Game log:
8:33 AM: Human activates: You get an emblem with "[Whenever an opponent casts his or her first spell each turn, counter that spell.]" from Jace, Unraveler of Secrets [504]
8:33 AM: Human attacks with 0 creatures
8:33 AM: Turn 2 Computer (20 - 20)
8:33 AM: Computer draws a card
8:33 AM: Computer puts Razorverge Thicket [e80] from hand onto the Battlefield
8:33 AM: Computer plays Razorverge Thicket [e80]
8:33 AM: Computer casts Slippery Bogle [01e]
8:34 AM: Computer puts Slippery Bogle [01e] from stack onto the Battlefield

**Comment by devinallenaz** [comment]
This is not fixed it 1.4.10v1.
<img width="402" alt="screen shot 2016-04-12 at 9 25 31 am"   ##src="https://cloud.githubusercontent.com/assets/4226365/14467548/b7a68710-0090-11e6-809f-534aa47b377a.png">
