### ISSUE TITLE
Flickerwisp is bugged with multiple instances.

### ISSUE THREAD

**Issue by Synapsiz** [magefree/mage#1740]
Multiple instances of the same flickerwisp will break it's ability. (not sure about multiple instances of different flickerwisps). Can also be reproduced by using restoration angel during the end step.

When flickerwisp A enters the battlefield it's ability triggers.
_("When Flickerwisp enters the battlefield, exile another target permanent. Return that card to the battlefield under its owner's control at the beginning of the next end step.")_

I choose and exile _Target 1_.

Then I play **flickerwisp B** and exile **flickerwisp A**.

At the end of turn, 2 triggers enter the stack, 'Return _Target 1_', and 'Return **Flickerwisp A**'.
**Flickerwisp A** returns first, a new instance of it's ability enters the stack, and I exile _Target 2_.

Now the trigger 'Return _Target 1_ resolves', and instead of just returning _Target 1_ it returns both _Target 1_ and _Target 2_.

At the next end step, the 'Return _target 2_' trigger still works as intended, but as _target 2_ is already in play it doesn't do anything.

_edit: spelling and readability_

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.
