### ISSUE TITLE
[SOI] Archangel Avacyn damages herself when she transforms

### ISSUE THREAD

**Issue by cchike** [magefree/mage#1745]
She should just be damaging other creatures

**Comment by drmDev** [comment]
"When this creature transforms into Avacyn, the Purifier, it deals 3 damage to each other creature and each opponent."

**Comment by drmDev** [comment]
Duplicated issue - added automated test in latest commit showing the failure e7b80d95480f68453434d9ca2d9d26ebf72e10e1
