### ISSUE TITLE
It's easy to miss draft picks because the timer seems imprecise, the beep is too late, and it's easy to accidentally pick cards from the next pack

### ISSUE THREAD

**Issue by draxdyn** [magefree/mage#1755]
In draft, it seems that cards sometimes get autopicked when the timer shows that 3 seconds are still available.

In part due to this, the beep seems to happen too late to allow you to make a final decision in response to the beep.

Finally, since cards are locked in by a single click, it's easy to click and meanwhile have the card autopicked, and make the wrong pick from the next pack too as the click accidentally registers on a card from the next pack.

All this combines to make a drafting experience that can be at times disastrous.

Suggestions to fix:
1. Make the beep happen 5 seconds earlier than it does now
2. Adopt the MTGO interface where a single click selects and highlights the card, and only double clicking locks in and goes the next pack. When the timer runs out, the highlighted card is picked.
3. Figure out why the timer is imprecise and fix it

**Comment by halljared** [comment]
I like these suggestions. I've personally "double-picked" because the timer ran out as I was picking. I'll look into this issue.
