### ISSUE TITLE
Mental Misstep fails to counter copies of Flusterstorm

### ISSUE THREAD

**Issue by draxdyn** [magefree/mage#1761]
Mental Misstep seems to fail to counter copies of Flusterstorm, which seems probably due to the fact that XMage thinks that the CMC of the copy is 0.

Since it's a copy, it should have the same CMC, and several web sources seem to agree, although neither the rules or Gatherer resolution seem to explicitly state this for Storm copies.

It's possible that there is another reason, since it does let you target the copy, but does not counter it, and it should not even let you target it (but maybe it something thinks that the CMC of the storm copies is 1 on the Mental Misstep cast, but not on resolution?)

**Comment by ImperatorPrime** [comment]
Fixed by 95b2d76ab1b25b1a1c5cd7b96661253c8e1c953f
