### ISSUE TITLE
XMage installer needs Java to install Java.

### ISSUE THREAD

**Issue by CTimmerman** [magefree/mage#1762]
Why the redundancy and [bad English](https://www.facebook.com/photo.php?fbid=10206126863561652&set=a.1273801416204.2032216.1564999382&type=3&permPage=1)?

**Comment by halljared** [comment]
Well this is an aggressive way to report an issue. It took me a while but I assume you mean "it's" should be "its", which can be fixed. Downloading a separate version of java guarantees clients use a consistent version and that there is no outside interference with the host computer.

**Comment by drmDev** [comment]
When creating issues please be constructive and clear on the issue.

**Comment by CTimmerman** [comment]
More redundantly, the redundancy was about needing another Java, and the bad English also referred capitalization issues like "java" as seen in the linked screenshot.

What do you mean by "outside interference"? Java not being backwards compatible goes against its goal of writing apps once and running it everywhere (including machines with newer JVMs).

When commenting, please be constructive and clear on the issue.

**Comment by spjspj** [comment]
Thanks for notification of the issues.  The group of volunteer developers will get to them shortly.
