### ISSUE TITLE
The window that let me chose in what order abilities are gonna stack is unselectable if something else is on top of it.

### ISSUE THREAD

**Issue by zalkador** [magefree/mage#1763]
Had the graveyard open and i couldnt click anywhere to close it.
![xm](https://cloud.githubusercontent.com/assets/18101978/14234747/7d054504-f9f3-11e5-97b5-a7a7622c7430.jpg)

**Comment by drmDev** [comment]
Usually you can click your avatar image to retain focus.

**Comment by JayDi85** [comment]
No more actual
