### ISSUE TITLE
AI Opponent can't resolve Oath of Nissa

### ISSUE THREAD

**Issue by buddah3243** [magefree/mage#1767]
Game exception occurred: java.lang.IllegalStateException: Target wasn't handled. class:class mage.target.TargetCard
Server version: 1.4.9v3
mage.player.ai.ComputerPlayer.chooseTarget(ComputerPlayer.java:761)
mage.sets.oathofthegatewatch.OathOfNissaEffect.apply(OathOfNissa.java:127)
mage.abilities.AbilityImpl.resolve(AbilityImpl.java:199)
mage.abilities.TriggeredAbilityImpl.resolve(TriggeredAbilityImpl.java:98)
mage.game.stack.StackAbility.resolve(StackAbility.java:107)
mage.game.GameImpl.resolve(GameImpl.java:1347)
mage.game.GameImpl.playPriority(GameImpl.java:1298)
mage.game.turn.Step.priority(Step.java:87)
mage.game.turn.Phase.playStep(Phase.java:210)
mage.game.turn.Phase.play(Phase.java:115)
mage.game.turn.Turn.play(Turn.java:152)
mage.game.GameImpl.playTurn(GameImpl.java:836)
mage.game.GameImpl.play(GameImpl.java:750)
mage.game.GameImpl.start(GameImpl.java:717)
mage.server.game.GameWorker.call(GameWorker.java:60)
java.util.concurrent.FutureTask.run(Unknown Source)
java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
java.lang.Thread.run(Unknown Source)

**Comment by drmDev** [comment]
fixed with 0cf3ab9d789afe86b703b988e5656583b8afb774
