### ISSUE TITLE
On server restart, keep the old server also running until games end

### ISSUE THREAD

**Issue by draxdyn** [magefree/mage#1769]
Currently all games in progress at server restart are abrupty terminated, which is obviously very bad for those playing.

It would be nice if server restart would only cause the old server instance to stop accepting new connections, kill all games waiting for players or to start and stop allowing new games to be created, but still run until all games in progress have finished or until the server restart the next day.

The new server would meanwhile accept new connections and ideally the client could automatically reconnect once the user is not playing in any games on the old one.

Obviously this is going to use more RAM on the server to run two instances of the server simultaneously, but shouldn't otherwise be an issue, as long as the underlying datastore supports or can be adapted to simultaneous access from the two servers (if necessary, a quick fix could be to have the old server send any data update commands to the new one with a new protocol).

Technically, the simplest way to achieve this on Linux seems to have the server listen only on localhost on a new port and accept a shutdown command, then define two identical systemd services for the server; on restart, connect to the old server with nc on, send the command, wait for an ack (so the port is free) and restart one the systemd service instance that was not restarted the day before, so that the two services alternate between being the old and current server.

**Comment by fenhl** [comment]
An alternative would be to save running games and tournaments before the restart, then resume them after the restart.

**Comment by JayDi85** [comment]
XMage stores all info in binary format, so it's incompatible between app versions (example: restarts after update). Also restarts are rare use cases and most users do not affected by it (auto-restart on de-server goes in most lowest online).

The more easy solution: make message notification about server restarts (see #5353).
