### ISSUE TITLE
Permanents scaling down too much on small resolution screens

### ISSUE THREAD

**Issue by xFazy** [magefree/mage#1774]
[Example](http://imgur.com/a/L9RX6)
This is on Win7, 1366x768 laptop screen. It's very difficult to read and no amount of playing with GUI sliders helps. Is there a way to fix this or is this an actual issue?

[GUI Preferences](http://imgur.com/eh1CTyY)

**Comment by LevelX2** [comment]
Should be solved with the added permanent minimal size setting.
