### ISSUE TITLE
Eldrazi Obligator is triggering untap ability when cost is not paid

### ISSUE THREAD

**Issue by Greeneye0** [magefree/mage#1776]
I cast the Obligator and targeted Veteran Cathar. When the ability triggered it untapped that creature even though I didn't pay the 1C.

![image](https://cloud.githubusercontent.com/assets/11687236/14265900/74f3f0f2-fa81-11e5-98d3-cdfc5a9cfa90.png)

**Comment by drmDev** [comment]
I believe this is an issue with the DoIfCostPaid usage, similarly to the issue with Wolf of Devil's Breach - b80166664f7ff3978dcb986818c34c9a128a969d

**Comment by drmDev** [comment]
Obligator also was granting haste to the targetted creature incorrectly. Fixed with 5ab54142de71690d2d681cdd6a6f8f4c7827a9c5 and test for it added as well.
