### ISSUE TITLE
Please release an update as soon as possible

### ISSUE THREAD

**Issue by draxdyn** [magefree/mage#1780]
Standard and limited are broken due to too many SOI bugs in the released version.

Modern and Vintage are broken due to the new banlist not being in the released version.

Any potential new issues seem unlikely to be worse than the current situation.

**Comment by drmDev** [comment]
Unfortunately this part is bottlenecked by the main developer's time and availability to do this. He is the only one who can do the release and is just coming off vacation. I understand the importance to get a new version up soon, but from discussions with him, it isn't easy and will take a lot of time to get this up. He projects this weekend as a tentative release date for the next version.

**Comment by halljared** [comment]
I feel for the players here too, and for myself. Oh well there's still bugs to fix anyways.
