### ISSUE TITLE
prized amalgam is not on the program or wont download

### ISSUE THREAD

**Issue by todd1019** [magefree/mage#1787]
i cant find prized amalgam on any of the lists inside the program

**Comment by Nightfirecat** [comment]
It may not be implemented yet. [Be sure to submit your card requests here.](http://www.slightlymagic.net/forum/viewtopic.php?f=70&t=4554)

**Comment by halljared** [comment]
I've successfully played with amalgam. I was on the xmage.de server which may have newer code.

**Comment by fireshoes** [comment]
It was added with v4, which xmage.de was updated with but not woogerworks. It also has a known bug which will hopefuly be resolved with the v5 release in a few days.
