### ISSUE TITLE
[SOI] Gitrog Monster - Null Pointer Exception after Planar Outburst cast

### ISSUE THREAD

**Issue by drmDev** [magefree/mage#1796]
From bug report in forum, see screenshot at link here:

[http://imgur.com/GPIo1b7]

Game exception occurred: java.lang.NullPointerException
mage.sets.shadowsoverinnistrad.TheGitrogMonsterTriggeredAbility.checkTrigger(TheGitrogMonster.java:111)
mage.abilities.TriggeredAbilities.checkTrigger(TriggeredAbilities.java:126)
mage.abilities.TriggeredAbilities.checkTrigger(TriggeredAbilities.java:84)
....

**Comment by drmDev** [comment]
Likely related to recent changes to Zone Group Events from 1dfa801d1f1f84405e750d811fff652750b423bb

**Comment by halljared** [comment]
Just a lot of chained function calls. Probably a card in the mix without some data like a token or something. I'll fix asap.

**Comment by drmDev** [comment]
Can never be enough null checks... lol. Yeah the rest of the log does mention GameState.java which also was adjusted. Hopefully issue resolved. I'll do some more tests tomorrow on some different cases to see if I can reproduce the issue. Planar Outburst and Gitrog were mentioned at the very least. Try those with some mix of tokens and non-tokens, especially ones with unusual properties somehow.

**Comment by drmDev** [comment]
User in forums said shortly after opponent played Gitrog Monster, got this error (same?):

Game exception occurred: java.lang.NullPointerException
Server version: 1.4.10v0
mage.sets.shadowsoverinnistrad.TheGitrogMonsterTriggeredAbility.checkTrigger(TheGitrogMonster.java:111)
mage.abilities.TriggeredAbilities.checkTrigger(TriggeredAbilities.java:126)
mage.abilities.TriggeredAbilities.checkTriggers(TriggeredAbilities.java:84)
mage.game.GameState.handleEvent(GameState.java:681)
mage.game.GameState.handleSimultaneousEvent(GameState.java:669)
mage.game.GameImpl.playPriority(GameImpl.java:1289)
mage.game.turn.Step.priority(Step.java:87)
mage.game.turn.Phase.playStep(Phase.java:210)
mage.game.turn.Phase.play(Phase.java:115)
mage.game.turn.Turn.play(Turn.java:152)
mage.game.GameImpl.playTurn(GameImpl.java:836)
mage.game.GameImpl.play(GameImpl.java:750)
mage.game.GameImpl.start(GameImpl.java:717)
mage.server.game.GameWorker.call(GameWorker.java:60)

**Comment by drmDev** [comment]
Also... poster then stated:

Got the following bug a few turns after I got a bug about The Gitrog Monster (posted above):

Code: Select all
    Game exception occurred: mage.MageException: Iterated player priority after game exception too often, game ends!
    Server version: 1.4.10v0
    mage.game.GameImpl.playPriority(GameImpl.java:1328)
    mage.game.turn.Step.priority(Step.java:87)
    mage.game.turn.Phase.playStep(Phase.java:210)
    mage.game.turn.Phase.play(Phase.java:115)
    mage.game.turn.Turn.play(Turn.java:152)
    mage.game.GameImpl.playTurn(GameImpl.java:836)
    mage.game.GameImpl.play(GameImpl.java:750)
    mage.game.GameImpl.start(GameImpl.java:717)
    mage.server.game.GameWorker.call(GameWorker.java:60)

**Comment by LevelX2** [comment]
Should be fixed with 24faec3d12c63f3734e9196cbda9623034272389
