### ISSUE TITLE
[SOI] Clue Tokens and Tireless Tracker

### ISSUE THREAD

**Issue by KCAHT** [magefree/mage#1797]
Tireless Tracker, Graf Mole, and Fleeting Memories all have abilities that trigger when you sacrifice a Clue. These abilities do not actually trigger when their controller sacrifices a clue.

To balance out the loss of the +1/+1 counter ability, Tireless Tracker's first ability triggers when anyone plays a land, not just the person who controls tireless tracker.

**Comment by drmDev** [comment]
What version of XMage are you on right now?

**Comment by drmDev** [comment]
Confirmed issue is still resolved in this current release 1.4.9v10. Make sure you update to the latest version. Unit tests and manual tests confirm both landfall and sac clue triggers work correctly.

**Comment by fireshoes** [comment]
*release version 1.4.10v0
