### ISSUE TITLE
Missing Cards!

### ISSUE THREAD

**Issue by NagaNooch** [magefree/mage#1805]
Whipgrass Entangler

Card Name:Whipgrass Entangler
Mana Cost:2White
Converted Mana Cost:3
Types:Creature — Human Cleric
Card Text:
1White: Until end of turn, target creature gains "This creature can't attack or block unless its controller pays 1 for each Cleric on the battlefield."
Flavor Text:"Now that I have your attention, perhaps I can tell you of the Order."
P/T:1 / 3
Expansion:Legions (Common) Legions
Rarity:Common

Celestial Gatekeeper

Card Name:
Celestial Gatekeeper
Mana Cost:3WhiteWhite
Converted Mana Cost:5
Types:Creature — Bird Cleric
Card Text:
Flying
When Celestial Gatekeeper dies, exile it, then return up to two target Bird and/or Cleric permanent cards from your graveyard to the battlefield.
P/T:2 / 2
Expansion:Legions (Rare) Legions
Rarity:Rare

There might be more, but these two specifically are blatantly missing from all searches within XMage.

Please add them in! Legacy Clerics need love too!

**Comment by drmDev** [comment]
Card request thread is the place for these:
http://www.slightlymagic.net/forum/viewtopic.php?f=70&t=4554&start=510
