### ISSUE TITLE
in SOI draft boosters don't necessarily have 1 double faced card.

### ISSUE THREAD

**Issue by zalkador** [magefree/mage#1810]

**Comment by spjspj** [comment]
Sorry, I wasn't sure what you mean.
Do you mean they have more in the packs generated in xmage? 
Or do they have 0 double faced cards in some generated packs?

**Comment by zalkador** [comment]
Im not sure if they might generate more than 1, but some packs have 0 double faced cards.

**Comment by fireshoes** [comment]
Every pack of SOI should have 1 common or uncommon DFC. Every 8th pack should have a rare or mythic rare DFC.

**Comment by LevelX2** [comment]
From: http://magic.wizards.com/en/articles/archive/making-magic/odds-ends-shadows-over-innistrad-part-2-2016-04-18

> @maro254 will there be more than one double faced card per booster pack or a single card, similar to the first Innistrad block?
>     — Jason Luetke (@JasonL_346) March 25, 2016
> 
> Barring a weird anomaly (which does happen when you print cards), each booster pack should have at least one double-faced card, which will be a common or uncommon. Then about an eighth of the packs will have a second double-faced card, which will be a rare or mythic rare. The ratios of common to uncommon and rare to mythic rare match normal rarity ratios.
> 

The second double faced card replaces which slot? Of a common?

**Comment by LevelX2** [comment]
From: http://www.mtggoldfish.com/articles/the-expected-value-of-shadows-over-innistrad

> Second, double-faced Rares or Mythics will replace a Common rather than a card of their own rarity, so they are essentially free value (strengthening the comparison to Expeditions).

**Comment by LevelX2** [comment]
There are only 4 common and 20 uncommon double faced cards. So is the fixed double faced cards in most of the cases (10/15) one of this four common cards?  So you get this 4 very very often.

Or is there another distribution between common/uncommon in this packs for double faced cards?

**Comment by fireshoes** [comment]
I looked through my recent prize packs, and they had 13 common DFCs and 10 uncommons to give you an idea of the frequency.

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.
