### ISSUE TITLE
Error i got in SOI sealed

### ISSUE THREAD

**Issue by earthmix** [magefree/mage#1812]
Game exception occurred: mage.MageException: Iterated player priority after game exception too often, game ends!
Server version: 1.4.10v0
mage.game.GameImpl.playPriority(GameImpl.java:1328)
mage.game.turn.Step.priority(Step.java:87)
mage.game.turn.Phase.playStep(Phase.java:210)
mage.game.turn.Phase.play(Phase.java:115)
mage.game.turn.Turn.play(Turn.java:152)
mage.game.GameImpl.playTurn(GameImpl.java:836)
mage.game.GameImpl.play(GameImpl.java:750)
mage.game.GameImpl.start(GameImpl.java:717)
mage.server.game.GameWorker.call(GameWorker.java:60)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
java.lang.Thread.run(Thread.java:745)

**Comment by drmDev** [comment]
We need a game log or at least a basic summary of what you last saw before
this occurred. Game logs are in your Mage installation directory
/mage-client/gamelogs folder

**Comment by earthmix** [comment]
@drmDev here's the log [.](https://hackpad.com/log-1-IYcBS7qyz1g) this happened when Skin Invasion tried to transform

**Comment by drmDev** [comment]
Looked at the log and the issue is related to two things, Transformations as well as Blocking with insect tokens from Crawling Sensation #1819
