### ISSUE TITLE
Ability to "blacklist"/ignore a troublesome user

### ISSUE THREAD

**Issue by drmDev** [magefree/mage#1814]
Enhancement request from reddit post:
https://www.reddit.com/r/XMage/comments/4dsc98/request_for_a_blacklist_function/

We've discussed this before when we had someone spamming open tables on XMage:
http://www.slightlymagic.net/forum/viewtopic.php?f=70&t=18403

"A user specific ignore list, where you can add users to you want to ignore. So no chat messages or tables of the ignored user will be shown for you. The ignored users can't join tables or watch games the ignoring user had created."
- Reading messages or receiving messages from them
- Joining games where they host them
- Allowing them to join your games

**Comment by aastrand** [comment]
This should be resolved as of https://github.com/magefree/mage/commit/f68460603ac65cba99a2ae9e49d245436c90975f
