### ISSUE TITLE
yet another error

### ISSUE THREAD

**Issue by earthmix** [magefree/mage#1822]
Game exception occurred: mage.MageException: Iterated player priority after game exception too often, game ends!
Server version: 1.4.10v0
mage.game.GameImpl.playPriority(GameImpl.java:1328)
mage.game.turn.EndPhase.playStep(EndPhase.java:67)
mage.game.turn.Phase.play(Phase.java:115)
mage.game.turn.Turn.play(Turn.java:152)
mage.game.GameImpl.playTurn(GameImpl.java:836)
mage.game.GameImpl.play(GameImpl.java:750)
mage.game.GameImpl.start(GameImpl.java:717)
mage.server.game.GameWorker.call(GameWorker.java:60)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
java.lang.Thread.run(Thread.java:745)

**Comment by earthmix** [comment]
this one occured when i tried to transform Uninvited Geist
here's the log [https://hackpad.com/log-2-km9WHSTmETc](url)

**Comment by drmDev** [comment]
#1800 - same idea with these transform errors very likely. You see a long stream of repeating text at the end like:

**Whenever Uninvited Geist deals combat damage to a player, transform Uninvited Geist
Unimpeded Trespasser [89c] transforms into Unimpeded Trespasser
Unimpeded Trespasser [89c] transforms into Unimpeded Trespasser
Unimpeded Trespasser [89c] transforms into Unimpeded Trespasser**

There likely was another error shown than the "Iterated player priority", perhaps in the Client Console window. And very likely a Null Pointer Exception. I'll test it with Uninvited Guest, but latest code from #1800 should fix it.

**Comment by drmDev** [comment]
Fixed beyond 1.4.10v0 with commit fca3b9a42a955d6584254256d2fc9a19fb36bb5d
