### ISSUE TITLE
Phasing does not phase out the attached enchantments properly

### ISSUE THREAD

**Issue by drmDev** [magefree/mage#1829]
For instance with the recently implemented card Vanishing:  right now when the enchanted creature phases out, the Enchantment card Vanishing just "lingers" on the battlefield where the creature used to be. Then when the creature phases back in, the Enchantment is re-attached to it. I'm not sure if this is an issue requiring a change in handling for Phasing, or a change in handling for the card I coded in.

Rulings I found on this card and phasing:
`http://www.mtgsalvation.com/forums/magic-fundamentals/magic-rulings/magic-rulings-archives/279819-phase-out-more-specifically-vanishing`

"Enchantments attached to the creature will "phase out indirectly," and stay attached to it, even though it is phased out." 

"Enchantments and equipment phase in/out with the permanents they are associated with."

So it sounds like anything attached to the permanent should additionally phase out and then phase back in with it.

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.
