### ISSUE TITLE
Implement 'Rich Man's Draft' 

### ISSUE THREAD

**Issue by spjspj** [magefree/mage#1838]
There's a type of draft called Rich Man's Draft 'cos it requires a full booster box.  You get an unopened booster box. Then open up one booster. You pick one card from that booster and discard the rest. You then open the next booster and take a card from that. Until you have 36 cards (36 boosters / box). I'm not sure if this works for Modern Masters (I or II) as there were only 24 boosters per box. I'd be interested in trying it out on xmage.  Also, drafting it in Fallen Empires would be interesting (8 cards per booster I think but more boosters per box).

**Comment by fireshoes** [comment]
[Here](https://twitter.com/Marshall_LR/status/718984810698448896)'s a link to Marshall Sutcliffe's deck from this format. Looks pretty sweet!

**Comment by spjspj** [comment]
It would actually be a pretty useful way to get to know a format because you'd be evaluating what's good the whole time and you'd see a lot more cards as well (36*16 = 576).  And I'd love to get that deck in a draft - mind you everyone else's deck would be nutso as well.

**Comment by spjspj** [comment]
They seemed to do it differently on Marshall's channel.  They were opening everything and making a 40 card deck.  I think the one card a pack would be better to do and implement as well - have the normal 40 card deck so top 23 + 13 or so in sideboard.

**Comment by LevelX2** [comment]
Why is it limited to one set of booster?
Wouldn't it be nice if you could combine at least three different boosters set types for the 45 cards to draft? You're still able to select three times the same set. 

And It's only added as Elimination not as Swiss type.

Also crazy would be if you could set it to "random set" as you define the tournament . 
What would mean, that for every draft round a random set is choosen by the server.

**Comment by drmDev** [comment]
This enhancement request is completed, right? Checking through some existing issues - close out if done please. Thanks! :100:

**Comment by spjspj** [comment]
As @LevelX2  mentioned, I think a random booster draft of this would actually be kind of cool but will close for now.  The decks seem to be fairly degenerate from the games I've played!

**Comment by LevelX2** [comment]
Gonna have some problems with the expansion selection becuase of the size of the area now.

![tourn](https://cloud.githubusercontent.com/assets/2066790/15396046/a114881e-1dda-11e6-96a2-450df92dabe6.jpg)

**Comment by LevelX2** [comment]
Seems only to happen the first time you use the tournament type after starting the client.
If you switch to another tournament type and back, it's ok.

**Comment by JayDi85** [comment]
Richman was implemented long ago, auto-size bug was fixed in 1.4.34.
