### ISSUE TITLE
Can't reliably connect after new release

### ISSUE THREAD

**Issue by albuzs** [magefree/mage#1848]
I am getting the following error messages since the latest release:

FATAL 2016-04-11 17:48:09,028 Communication error                                                                        =>[pool-1-thread-1] SessionImpl.handleThrowable 
java.lang.NullPointerException
FATAL 2016-04-11 17:48:12,587 Communication error                                                                        =>[pool-1-thread-1] SessionImpl.handleThrowable 
java.lang.NullPointerException
INFO  2016-04-11 17:48:48,338 Starting MAGE client version 1.4.10v1                                                      =>[main] MageFrame.main 
INFO  2016-04-11 17:48:48,339 Logging level: INFO                                                                        =>[main] MageFrame.main 
INFO  2016-04-11 17:48:53,695 Loading plugins...                                                                         =>[AWT-EventQueue-0] Plugins.loadPlugins 
INFO  2016-04-11 17:48:53,742 [Game counter plugin, version 0.1] has been loaded.                                        =>[AWT-EventQueue-0] CounterPluginImpl.newPlugin 
INFO  2016-04-11 17:48:53,748 Done.                                                                                      =>[AWT-EventQueue-0] Plugins.loadPlugins 
INFO  2016-04-11 17:48:54,554 Client start up time: 6 seconds                                                            =>[AWT-EventQueue-0] MageFrame$6.run 
INFO  2016-04-11 17:48:54,558 Trying to connect to XMAGE server at xmage.woogerworks.info:17171                          =>[AWT-EventQueue-0] SessionImpl$5.run 
INFO  2016-04-11 17:49:23,742 connection to server lost - Could not connect to server!                                   =>[Thread-221] SessionImpl$ClientConnectionListener.handleConnectionException 
java.lang.Exception: Could not connect to server!
    at org.jboss.remoting.Client.notifyListeners(Client.java:1886)
    at org.jboss.remoting.LeasePinger.stopPing(LeasePinger.java:134)
    at org.jboss.remoting.MicroRemoteClientInvoker.terminateLease(MicroRemoteClientInvoker.java:434)
    at org.jboss.remoting.ConnectionValidator$WaitOnConnectionCheckTimerTask.run(ConnectionValidator.java:1108)
    at java.util.TimerThread.mainLoop(Unknown Source)
    at java.util.TimerThread.run(Unknown Source)
FATAL 2016-04-11 17:49:54,209 Communication error                                                                        =>[pool-1-thread-1] SessionImpl.handleThrowable 
java.lang.NullPointerException

It just freezes and does nothing ):

**Comment by goesta** [comment]
I'll close this issue because it seems to be outdated but feel free to create a new one if this problem still exists.
