### ISSUE TITLE
Cancelling the casting of a spell when choosing to pay mana freezes the client and disconnects

### ISSUE THREAD

**Issue by ianelletson** [magefree/mage#1857]
Win 10
Twice now when I've canceled a spell after (accidentally) choosing to cast it, the client freezes. Attempts to resize the window result in a black screen. After a minute or so of waiting, the client shows that I have been disconnected. Reconnecting does not work. I am also unable to rejoin the match.

This might just be related to the disconnects the xmage.de server is facing.

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.
