### ISSUE TITLE
Getting land variations from Gatherer may be broken

### ISSUE THREAD

**Issue by fenhl** [magefree/mage#1859]
I haven't tested this, but from looking at the [code](https://github.com/magefree/mage/blob/f6d26ea6567c6132c1e6750444de66208dde0184/Mage.Client/src/main/java/org/mage/plugins/card/dl/sources/WizardCardsImageSource.java#L336) and the website, it seems that it should be `a.variationLink` (capital L) instead of `a.variationlink`.

**Comment by LevelX2** [comment]
So if you checked, go for the fix.

**Comment by Zerrisx** [comment]
So... is this broken?  Is it fixed?  What's the status here?

**Comment by JayDi85** [comment]
Gatherer source were outdated since scryfall source implemented (2+ years ago). Even more it contains only low res images. Maybe someday gatherer support will be removed from xmage.
