### ISSUE TITLE
Myriad makes a copy for defending player

### ISSUE THREAD

**Issue by fenhl** [magefree/mage#1870]
When a creature with myriad attacks, the game should ask if token copies should be created for each opponent other than the defending player. Currently it also asks if a token copy attacking the defending player should be created.

**Comment by LevelX2** [comment]
Hmm, did check this in the past and was not able to reproduce. Seems not to happen all the time at least.

**Comment by drmDev** [comment]
Is this still occurring? I recall a recent commit on fixing Myriad after we noticed a couple JUnit tests on it failing.

**Comment by LevelX2** [comment]
Handled in #2420.
