### ISSUE TITLE
Delve abilities should highlight cards selected

### ISSUE THREAD

**Issue by drmDev** [magefree/mage#1876]
Delve, and similar keywords and effects that often require selecting multiple cards should highlight the cards selected to give a better visual indicator of which ones have been selected already.

Idea from feedback on forums:
"Something that popped up more when I was using more delve cards, but being able to highlight the cards selected while delving would be nice. Case in point, I was playing Empty the Pits and if I delved for 20 and missed a card, I had to go back through clicking each card to see which one I missed. It was annoying and took unnecessary time."

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.
