### ISSUE TITLE
Spells copied by Pyromancer's Goggles cannot be countered

### ISSUE THREAD

**Issue by mpale** [magefree/mage#1879]
In the last couple of days of testing I noticed in two different occasions that the copy of a spell produced by Pyromancer's Goggles cannot be countered. In the first occasion, my opponent had a morphed Stratus Dancer on the battlefield, I cast a Fiery Temper through Pyromancer's Goggles and copied it. As my opponent unmorphed Stratus Dancer targeting the copy of Fiery Temper, the ability resolved without countering the spell. A similar scenario occurred in a different game. I cast a red spell through the Goggles and put a copy on the stack and my opponent played Scatter the Winds targeting the copy. As in the previous case, the spell resolved without countering the copy.  I told my opponent to rollaback and counter the original spell and that worked fine.

Regards,

Marco

**Comment by ImperatorPrime** [comment]
Fixed by 95b2d76ab1b25b1a1c5cd7b96661253c8e1c953f
