### ISSUE TITLE
Conditional Continuous effects with 'Duration.WhileOnBattlefield' don't end when permanents are flickered

### ISSUE THREAD

**Issue by spjspj** [magefree/mage#1886]
I've made and am testing a new condition (SourceHasRemainedOnBattlefieldCondition) that has memory of how many times a permanent has changed zones (using game.getPermanent(permanentId).getZoneChangeCounter(game)) and then compares that to what it was when the condition was created for the permanent.  This was giving me headaches for working out why a card I'm implementing (Preacher) wasn't behaving as expected :(

For example, instants such as CloudShift on DragonLord Silumgar work ok (as CloudShift has 'applyEffectsAfter'), but using Ghostly Flicker on DL Silumgar doesn't release control of the controlled creature (using the current SourceOnBattlefield condition).

Current relevant bits of code for 'apply' in new condition is:
```
    public void setPermanentId(UUID permanentId) {
        this.permanentId = permanentId;
        timesChangedZones = -1;
    }

    @Override
    public boolean apply(Game game, Ability source) {
        if (permanentId != null && (game.getPermanent(permanentId) != null)) {
            if (timesChangedZones == -1) {
                timesChangedZones = game.getPermanent(permanentId).getZoneChangeCounter(game);
            }
            
            if (timesChangedZones == game.getPermanent(permanentId).getZoneChangeCounter(game)) {
                return true;
            }
        }
        
        return false;
    }
```

**Comment by LevelX2** [comment]
Maybe read this, because it's realted:
http://www.slightlymagic.net/forum/viewtopic.php?f=116&t=14516&p=158817&hilit=reference&sid=fbebca4f34c22e8e5efc78931a7232a4#p158817

**Comment by spjspj** [comment]
G'day LevelX2 - I've read it now - I can't say I fully understand it though :(  I've made a pull request #1887

**Comment by drmDev** [comment]
This is very late to the party, but with some recent bug fixes, changing the Duration from BATTLEFIELD to CUSTOM has resolved issues where there should be a continuous effect. Perhaps I misunderstand @LevelX2 explanation of when to use BATTLEFIELD instead of CUSTOM, so I'll let him try to clarify it here again.
