### ISSUE TITLE
Kindly Stranger does not allow destroying creature on transform

### ISSUE THREAD

**Issue by drmDev** [magefree/mage#1888]
Reported from reddit:
https://www.reddit.com/r/XMage/comments/4fbtv0/kindly_stranger_bugged/

When you have delirium and activate Kindly Stranger ability to transform her, you are not even given an option to destroy a target creature.

Example init file:
battlefield:Human:Kindly Stranger:1
graveyard:Human:Bronze Sable:1
graveyard:Human:Bitterblossom:1
battlefield:Human:Swamp:4
battlefield:Computer:Bronze Sable:1

Can create an automated test later if needed.

**Comment by LevelX2** [comment]
> Can create an automated test later if needed.

Always a good thing! :-)

**Comment by drmDev** [comment]
Added test in commit 7a3c15d8b892cf1d0b2ec2c3deea0d2bff263056
