### ISSUE TITLE
Jace, Telepath Unbound allows casting Ancestral Vision from grave

### ISSUE THREAD

**Issue by drmDev** [magefree/mage#1890]
A reddit user reported that Ancestral Visions can still be cast with flipped Jace:
https://www.reddit.com/r/XMage/comments/4f6dun/bug_with_av_und_lil_jace/

This is similar to an issue #1510 that fixed AV being able to be flashbacked. Jace Telepath Unbound does not actually give the spell "flashback" though, so this is slightly different.

Ruling on the interaction I found:
"It's [Ancestral Vision] a legal target, since Jace's ability only requires an "instant or sorcery card in your graveyard" as its target.

It would, however, be a waste of the ability's use, because you still cannot actually cast Ancestral Vision this way. Jace's ability essentially gives you permission to cast the targeted card from an unusual place (the graveyard) that you normally cannot cast cards from. But since the ability doesn't say anything about not paying the cost for the spell, you still have to pay normally. Paying normally involves paying the mana cost of the card. But since Ancestral Vision does not have a mana cost, you cannot pay it, and the end result is that you cannot cast it, for the same reason that you normally cannot cast it from your hand." (and suspending a card can only be done from hand)
http://www.mtgsalvation.com/forums/magic-fundamentals/magic-rulings/magic-rulings-archives/652878-jace-telepath-unbound-ancestral-vision

**Comment by spjspj** [comment]
These cards may be in a similar boat to jace:
 Abbot Of Keral Keep
 Chandra Pyromaster
 Daxos Of Meletis
 Dream Pillager
 Ire Shaman
 Jace Telepath Unbound
 Karador Ghost Chieftain
 Kheru Spellsnatcher
 Knacksaw Clique
 Minds Desire
 Narset Enlightened Master
 Ornate Kanzashi
 Prophetic Flamespeaker
 Psychic Intrusion
 Sins Of The Past
 Spelljack
 Stolen Goods

**Comment by ImperatorPrime** [comment]
Fixed by 11158d5fa4cea8e271a2442bffd75cd4bf4191da
