### ISSUE TITLE
Karador flicker bug

### ISSUE THREAD

**Issue by Brawler-1337** [magefree/mage#1893]
Karador's graveyard play for turn doesn't reset when you blink him. I tried giving him persist with a Cauldron of Souls after casting my first creature from my grave to cast another creature that turn, but the program wouldn't let me cast the second creature. I know this should work because it's listed on his last ruling:

> 9/22/2011: If you cast a creature card from your graveyard, then Karador leaves the battlefield, then returns to the battlefield, you may cast another creature card from your graveyard that turn. If you didn’t cast a creature card from your graveyard while Karador was on the battlefield the first time, you may still cast only one creature card from your graveyard when it returns to the battlefield.

**Comment by Zerrisx** [comment]
Verified still bugged.  Cloudshift-ing Karador doesn't let you play a second creature.

**Comment by awjackson** [comment]
Fixed and test added by https://github.com/magefree/mage/commit/89639f5e9b485a97e51e4d39abc9b7064dc8de6c
