### ISSUE TITLE
m15->The Chain Veil code Possible Typo or Meant To Be That Way | +a personal message

### ISSUE THREAD

**Issue by DrizzleRaine** [magefree/mage#1899]
At line 180 I noticed loyalty was labeled as Layalty maybe to achieve a certain effect in the condition.
It may be an error I thought I would point that out.
if (!watcher.activatedLayaltyAbility(source.getControllerId())) {
if (!watcher.activatedLoyaltyAbility(source.getControllerId())) {
(End of Issue)

edit:
I found out I don't have permission to sync commits to the codebase.
if anyone can give me a little direction via email that would be great.
plz put "xmage dev" + whatever you want in the mail title.
I want to help and know I got to work to get it.
end edit;

if you have links to share or documentation of some of the xmage source
give me a text at cwatkins3017@vgcc.edu  I want to expand this yet don't know how you all operate.

**Comment by LevelX2** [comment]
A simple type, I'll fix that.

Look here to check how best to contribute:
https://github.com/magefree/mage/wiki/Developer-Getting-Started
http://www.slightlymagic.net/forum/viewtopic.php?f=116&t=18345&p=193491&hilit=pull+requests#p193495
