### ISSUE TITLE
Installed Java without consent

### ISSUE THREAD

**Issue by fultonm** [magefree/mage#1902]
Downloading Java from http://download.oracle.com/otn-pub/java/jdk/7u75-b13/jre-7u75-windows-x64.tar.gz
Installing Java ...Done

I have a Java installation and properly configged PATH, why was this necessary?

**Comment by ivorcosta** [comment]
I don't think xmage installs Java, it downloads it and unpack into the folder xmage/java

**Comment by LevelX2** [comment]
Probably your Java environment was setup correctly.
But before we started to download and use the own java version we had a lot (and I mean really a lot)  more problems with systems that had no proper (or too old or too new( java versions installed.
So only experience let use us this approach.

**Comment by fultonm** [comment]
Fair enough, I was just getting familiar with this project and thought I had something useful to say :+1:
