### ISSUE TITLE
cmc of flipcards

### ISSUE THREAD

**Issue by cipherz** [magefree/mage#1904]
Had a flipped delver and my opponent activated an engineered explosives on 1, which did not kill my delver. I believe recent rule changes say that flip cards have the same cmc as the other side, thus the flipped delver should have died.

**Comment by drmDev** [comment]
Duplicate issue #1826 
Fixed in next release

**Comment by drmDev** [comment]
User on subreddit reporting:

So I was playing against utron with my delver deck and my opponent played engineered explosives with sunburst=1 and then he sacced it and it didn't kill the Insectile aberration. It used be that Insectile aberration cmc = 0, but isn't the new rule that it is 1? Xmage bugged?

---------

Added test for this scenario and unable to duplicate. Both Repeal and Engineered Explosives for X = 1 interact as expected on Insect.

**Comment by drmDev** [comment]
user updated:

Just read the log and apparently my opponent put 0 charge counters on EE. Sorry my bad. :) He just didn't know the rules/misplayed.
