### ISSUE TITLE
Allow Clients to Add an Arbitrary List (or Deck) of Cards as a Cube to draft. 

### ISSUE THREAD

**Issue by kodemage** [magefree/mage#1907]
**Enhancement Request**

**Add the ability to modify/add arbitrary lists of cards as a cube.** Currently only a select few cubes are available to choose from when creating a game. I'd like to, as a user not server operator, add additional cubes to that list. I'm fine if it takes editing a con fig file or even using the deck editor. 

Mostly I'd like a way, however you can swing it, to draft _my_ cube or any other cube I can find on a site like cubetutor.com.

**Comment by goesta** [comment]
I'll close this issue because it's a duplicate and the referenced issue is closed.
