### ISSUE TITLE
Initial setup failing

### ISSUE THREAD

**Issue by Badaro** [magefree/mage#1909]
Downloaded the launcher from xmage.de. Attempted to run, it started the initial setup but failed to download the xmage package.

> Reading  config from http://xmage.de/xmage/config.json
> XMage folder:  C:\Users\Filipe\Desktop\XMage
> XMage Launcher version installed:  0.3.8
> XMage Launcher version available:  0.3.4
> Java version installed:  
> Java version available:  1.7.0_75
> Java not found
> XMage version installed:  
> XMage version available:  1.4.4v11 (2015-10-21)
> XMage not found
> Downloading Java from http://download.oracle.com/otn-pub/java/jdk/7u75-b13/jre-7u75-windows-x64.tar.gz
> Installing Java ...Done
> Downloading XMage from http://bit.ly/xmage_1_4_4v11w
> Failed to download XMage from http://bit.ly/xmage_1_4_4v11w
> Downloading XMage from http://bit.ly/xmage_1_4_4v11w
> Java version installed:  1.7.0_75
> Java version available:  1.7.0_75
> XMage version installed:  
> XMage version available:  1.4.4v11 (2015-10-21)
> XMage not found
> Failed to download XMage from http://bit.ly/xmage_1_4_4v11w
> Downloading XMage from http://bit.ly/xmage_1_4_4v11o
> Failed to download XMage from http://bit.ly/xmage_1_4_4v11o

Both bit.ly redirects work, but I get a 404 from the download servers:

http://xmagemirror.optichosting.net/xmage_1.4.4v11.zip
http://xmage.woogerworks.info/xmage_1.4.4v11.zip

Also tried using the 0.3.4 launcher listed in http://xmage.de/xmage/config.json, but got the same problem.

**Comment by LevelX2** [comment]
It's fixed now.
