### ISSUE TITLE
Only one of the two Brothers Yamazaki available

### ISSUE THREAD

**Issue by fenhl** [magefree/mage#1914]
The card [Brothers Yamazaki](http://magiccards.info/query?q=%21Brothers+Yamazaki) has been printed in Champions of Kamigawa with two different images. Currently, only the image 160b is available in XMage. The other (160a) should also be implemented.

I believe that the rarity should work so that the card is as frequent as any other uncommon, with each brother effectively being twice as rare.

**Comment by LevelX2** [comment]
We have to decide, how to handle differemnt images in this cases generally.

The image download handling has to be adapted to download the two different images.
The handling for different available images for one card has to be added to card editor and game.
Some logic to handle the different images if as usual card number and expansion is used to determine a card.

There are also some other cards that have two different images.
#739

**Comment by fenhl** [comment]
See also: #1992, #1993, #1994.

**Comment by fwannmacher** [comment]
Maybe we could add an arbitrary card number for those cases and make a key:value property set like the image.url.properties. Something similar was done with the non-full art lands in ZEN, but without the need of a property set.

**Comment by fwannmacher** [comment]
Or we can just add a "String cardNumberVariant" on CardImpl and set it to "a" or "b". With that value we can find the image.

**Comment by fenhl** [comment]
Fixed in #2112. @fwannmacher to automatically close an issue when a commit is merged into master, include e.g. “Fixes #1914” in the commit message.
