### ISSUE TITLE
Regular-frame BFZ/OGW basics missing

### ISSUE THREAD

**Issue by fenhl** [magefree/mage#1915]
BFZ and OGW only had the full-art basic lands included in boosters and fat packs. However, other products like intro packs contained versions of the basic lands (including Wastes) with the regular card frame and a big mana symbol in the text box. These appear to be unavailable in XMage.

**Comment by fenhl** [comment]
Fixed for Plains, Island, Swamp, Mountain, and Forest, still an issue for Wastes.

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.
