### ISSUE TITLE
Silverfur Partisan not triggering off opponent's instant/sorcery

### ISSUE THREAD

**Issue by drmDev** [magefree/mage#1916]
Silverfur Partisan:
"Whenever a Wolf or Werewolf you control becomes the target of an instant or sorcery spell, put a 2/2 green Wolf creature token onto the battlefield."

A Wolf token is only created when Silverfur or another Wolf/Werewolf you control is targetted by a spell you cast. When an opponent casts an Instant/Sorcery targetting Silverfur/Wolf/Werewolf, it does not create the Wolf Token.

ex. Opponent casts Lightning Bolt targetting "Howlpack Wolf". Howlpack Wolf simply dies - no trigger occurs and no token created.

- Card looks to have the same code as Wild Defiance. Wild Defiance confirmed to also have this same issue - only triggers when you cast a spell targetting your own creatures.

**Comment by drmDev** [comment]
A separate issue, but the automated test does not replicate the in-game behavior for this card. Added automated tests and they both pass:
https://github.com/magefree/mage/commit/c34a5de186c4761743a74560011cfba14caa33fa

But in-game, only when targetted by own spells are Wolf tokens created. No wolf tokens are created when targetted by opponent's spells.

5:21 AM: Computer casts Lightning Bolt [75e] targeting Howlpack Wolf [7b9] 
5:21 AM: Lightning Bolt [75e] deals 3 damage to Howlpack Wolf [7b9]
5:21 AM: Computer puts Lightning Bolt [75e] from stack into his or her graveyard
5:21 AM: Howlpack Wolf [7b9] died
5:21 AM: Computer casts Path to Exile [a18] targeting Silverfur Partisan [72e] 
5:22 AM: Computer moves Silverfur Partisan [72e] from battlefield to the exile zone
5:23 AM: Computer puts Path to Exile [a18] from stack into his or her graveyard

Player targets:
![silverfur](https://cloud.githubusercontent.com/assets/11060241/14912589/489d991a-0dcb-11e6-807e-ccfe3ec41ef5.png)

Opponent targets::
![silverfur2](https://cloud.githubusercontent.com/assets/11060241/14912588/489908c8-0dcb-11e6-8ec6-84d550d6c269.png)

**Comment by drmDev** [comment]
Confirmed issue also occurs with Wild Defiance when an opponent targets a creature you control it does not trigger.

**Comment by LevelX2** [comment]
The problem only happens if the opponent is an AI player.
