### ISSUE TITLE
Dromoka's Command - Sacrifice enchantment

### ISSUE THREAD

**Issue by ps0512** [magefree/mage#1922]
If the player who casts Dromoka's command selects the option for "target player sacrifices an enchantment" and selects a target without an enchantment, the game is stuck on the opponent needing to select an enchantment to sacrifice. Without an enchantment to sacrifice, the only way to exit is a concede.

This has happened two times when the player casting Dromoka's has an enchantment on board, while the opponent does not have any. May be coincidence.

**Comment by drmDev** [comment]
Will re-open if able to reproduce.
