### ISSUE TITLE
Phyrexian Juggernaut: “attacks each turn if able” doesn't work if skip button is used

### ISSUE THREAD

**Issue by fenhl** [magefree/mage#1925]
I haven't tested what happens when no skip button is used.

**Comment by drmDev** [comment]
Unable to duplicate. Had F9 skip on and he attacks each turn if able. Is this issue still occurring? Can you reproduce it?

**Comment by drmDev** [comment]
Will re-open if confirmed occurring again. Could not duplicate in game with skips, and have plenty of tests for "attacks each turn if able" passing.
