### ISSUE TITLE
Dralnu's pet does not enter with +1/+1 counters.

### ISSUE THREAD

**Issue by kevinpirola** [magefree/mage#1944]
Hello everybody, I was playing with my new deck and I found probably a bug.

I have a Dralnu's Pet (http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=15144)
that has a Kicker ability, that means that if I pay 2 incolor + 1 black in addition to its mana cost (2 blue 1 incolor), and I discard any creature card, the Dralnu's Pet should enter the battlefield with as many +1/ +1 counters as the mana cost of the discarded creature.

According to this I used 2 blues and 4 blacks, discarding a Draco (16 incolor mana cost) and the Dralnu's Pet entered the battlefield but no counters were on it. It should had 16 +1/+1 counters.

Hope to be of help traking this issue

Have a nice one and thanks for this good app!

**Comment by ImperatorPrime** [comment]
Fixed by 4a416c7fbb90c83f3d0dde249b683ed77af8872e

**Comment by kevinpirola** [comment]
thank you very much for this fix, will you release a new version? Should I try it just compiling a new jar myself?
