### ISSUE TITLE
Enhancement to generation of commons in packs

### ISSUE THREAD

**Issue by spjspj** [magefree/mage#1950]
I've now seen a number of packs whilst doing Rich Man that lacked an entire colour.   This is a lot more noticeable than when I've opened actual boosters.  I probably open too many real boosters for the health of my wallet, but I don't notice the same level of colourless-ness in real boosters.  Implementing a similar pseudo-random code to what WOTC do would be an interesting challenge and hopefully lead to a more realistic drafting environment.

**Comment by quercitron** [comment]
There are some rumours in the internet about how boosters are created, about print runs and so on, but I cannot find a reliable source. It would be great to find trustworthy information that we could try to use for our booster generation.

As a simple workaround I can suggest just to discard boosters where some colour is absent (not sure if we should do it for artifact-heavy sets).

**Comment by LevelX2** [comment]
Here's some information:
http://magic.tcgplayer.com/db/article.asp?ID=6995
Read the text after the example of the Coldsnap printruns.

**Comment by fenhl** [comment]
Why was this closed? More detailed information has become available now, for example at <http://www.lethe.xyz/mtg/collation/>.

**Comment by spjspj** [comment]
Going through my old issues and closing stuff.  Haven't looked at it for more than 3.5 years :)

**Comment by fenhl** [comment]
I think it still makes sense to keep this open, in case someone wants to try to implement it.
