### ISSUE TITLE
Enhancement to show pictures of unopened booster packs

### ISSUE THREAD

**Issue by spjspj** [magefree/mage#1951]
At the moment I don't believe there is a very good indication of which pack you are opening in draft.  It will quickly fade into the background, but having pictures of the unopened booster pack would be kind of cool and interesting.  Could come up with custom art for cube packs as well.

One of the packs images from the following series for example:
http://65.media.tumblr.com/cb051107c35ffc0d087bc579823ffd75/tumblr_inline_o3opjaD71Z1t7hiz8_1280.png

**Comment by Zerrisx** [comment]
Indicator now exists:

![image](https://user-images.githubusercontent.com/59861365/87817009-cc9ac500-c82d-11ea-81c0-d056b2cbe8f9.png)

Although it's not great for Richman drafts, but that's a separate issue.
