### ISSUE TITLE
Clicking an active skip button should cancel the skip

### ISSUE THREAD

**Issue by fenhl** [magefree/mage#1964]
I just tried to cancel the skip to my turn when asked to declare blockers. Instead I simply lost the game.

**Comment by drmDev** [comment]
I've noticed this a few times too. I spam f3 and click cancel skips and
usually it turns off. It definitely isn't as responsive as it should be

**Comment by Zerrisx** [comment]
It still struggles sometimes when the system is lagging, but there's not a ton that can be done about that; clicks in general get funky.  Stopping skips is no worse than any other button.  Under normal performance I no longer see this issue.
