### ISSUE TITLE
magiccards.info severely throttling XMage downloads?

### ISSUE THREAD

**Issue by draxdyn** [magefree/mage#1966]
When downloading from magiccards.info using a 100mbps Internet connection, the first around 200 images are downloaded quickly, and then the process slows down to around an image per second or even slower, which makes downloading all the images extremely slow.

It looks like magiccards.info might have introduced some sort of throttling and it would perhaps be a good idea to see whether intentionally slowing down XMage downloads avoids it while keeping a decent speed, or whether it's possible to switch to some other way of getting the card images (e.g. downloading full or per-set archives of them from somewhere).

Visiting magiccards.info with a browser is also extremely slow while or just after having downloaded images from it with XMage, while other web sites work fine, lending weight to the intentional throttling hypotesis.

**Comment by drmDev** [comment]
When you're downloading images, there is a XMage console window that records what happens in the process. When I try to download images from magiccards.info although it appears that the first 200 some cards are "downloaded" quickly, what is really happening is a lot of quick 503/404 errors are being thrown in succession. Perhaps something changed with magiccards.info for retrieving cards from them. After the first 200 some cards, all the remaining image download attempts just slowly throw ConnectException: connect timed out.

**Comment by gnumast** [comment]
I think @draxdyn is right that there is a throttling. Looking at the console like @drmDev recommended, I get a batch of ConnectException for requests that are timing out on a 20 second interval. Looking at the download dialog (that shows "Downloading...") I can see that after a certain amount of downloaded files it'll stop, wait for 20 seconds, download 10 files then stop again.

The ConnectException are probably thrown since magiccards.info doesn't send a response back and the request times out.

Looks like magiccards.info will lock you out for a couple of seconds every 10-or-so images after a certain amount. Does that make sense?

**Comment by fwannmacher** [comment]
I have the same problem with magiccards.info. Here is the log http://pastebin.com/JGbxUsT3

**Comment by Tarantinofn23** [comment]
I too have a problem with magiccards.info

**Comment by fwannmacher** [comment]
magiccards.info is blocking multiples downloads. I'm adding a configuration to select the number of simultaneous image downloads. So, we'll be able to download the cards again.

**Comment by fwannmacher** [comment]
To work around issue, I've added an option to select the number of threads for image download. Just set it to 1 and you'll be able to download from magiccards again.

The change has been pushed in pull request #2097

**Comment by drmDev** [comment]
Pull request has been merged in. Can we confirm if this resolved the issue?

**Comment by drmDev** [comment]
It seems to work okay, but when I test it locally I'm not seeing the console spew out the information on what's happening behind the scenes. After release I'll give it a bigger shot and revisit this issue.

**Comment by fwannmacher** [comment]
The console only prints cards that failed on download. The way I did to test that was putting a new image location and downloading everything again.

It takes way more time, because it's using only one thread, but, at least, magiccards doesn't stop the downloads at all.
