### ISSUE TITLE
Deprive by Flashback using Snapcaster Mage

### ISSUE THREAD

**Issue by LevelX2** [magefree/mage#1967]
Seen a report about casting Deprive by Flashback using Snapcaster Mage does not need the payment of the addional costs returning a land to hand.

**Comment by ImperatorPrime** [comment]
This was fixed by 9e4442547df4f503e9afd4e8df967c0e8d738763. Does it still not work? My tests (including a unit test) indicated the problem was resolved.

**Comment by drmDev** [comment]
Tested in game - bug was fixed. Deprive still requires the additional payment of returning a land to hand.
