### ISSUE TITLE
Field of Souls game text is wrong

### ISSUE THREAD

**Issue by halljared** [magefree/mage#1968]
The internal text for Field of Souls says that "Whenever a nontoken creature dies, put a 1/1 white spirit creature token with flying onto the battlefield." When the creature is put into your graveyard, per the card text.

**Comment by harbingerofme** [comment]
It does have a typo, it says "Whenever nontoken creature dies, put a 1/1 white Spirit Creature token with flying onto the battlefield" (note the missing 'a' between 'whenever' and 'nontoken'. 

However, 
> 700.4. The term dies means “is put into a graveyard from the battlefield.”

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.
