### ISSUE TITLE
IntelliJ specific wiki documentation

### ISSUE THREAD

**Issue by gnumast** [magefree/mage#1971]
Does anybody use IntelliJ for development here or is Netbeans the popular option? I'm asking because the getting started documentation mentions Intelli J and I've been using other Jetbrains IDEs at work (I'm not much of a java guy) and have been having some issues getting stuff working properly.

If someone uses Intelli J and had some notes on best practices or just basic info to get started I surely would love to have them on the wiki. I think it might be useful for others as well. Maybe "translating" the current Netbeans instruction to IntelliJ would be good enough to get people started.

For instance, one of the issues I seem to be having with IntelliJ is missing dependencies. The Maven projects are all loaded but if I try to run any of the JUnit tests, I usually get complaints about `Logger` not existing or some other class.

**Comment by Simown** [comment]
I used IntelliJ and had to do a couple of extra steps to get mine working. Can you let me know exactly what you've done and what error you're getting and I'll try and point you in the right direction.

The wiki does need updating with IntelliJ specific documentation, but no one has got round to it yet. Very busy this week but I'll see what I can do this weekend.

**Comment by gnumast** [comment]
@Simown I'd be happy to put documentation together as soon as I figure out how to make it work. The first error I encounter is the following (including all steps to get there). Note that if I use the command line it works nicely (ie. `mvn clean install` then I can run a single test with `mvn test -Dtest=MyClasstest`)

1. Checkout the repository
2. From IntelliJ, File -> Open and select the checked out repository
3. This takes a couple of seconds as IntelliJ indexes files and so on, eventually on the Project panel (alt-1) I see [mage-root] with all the other Maven projects under it.
4. The Maven panel on the right also has all the projects properly organised
5. IntelliJ popup: Frameworks detected "Protobuf Facet and Web frameworks", click "Configure" and OK to close the popup.

At this point I get another IntelliJ notice: Output directory needed for Protocol Buffers facet. This has a "Configure" link which opens up the settings page. I'm sure this has to be set but I have no clue what the output directory should be. Root of the whole project?

I also eventually get the "Maven Projects need to be updated" popup. I enabled auto-import.

From the top menu, Build->Make Project gives the following error:

```
Error: No such file or directory
 PATH_TO_CHECKOUT\Mage\src\main\proto\result.proto
```

So clearly something is related to the Protocol Buffers configuration. I should mentioned that I have `protoc` installed and available in my `PATH` and the Google Protocol Buffers plugin for IntelliJ is installed and activated. I've also configured it to point to my `protoc` binary.

If I go to "Project Structure..." then "Modules" and expand "mage" I can see "Protocol Buffers facet" and select an output directory. I tried different things, mostly starting from the root of the checked out repository and rebuilding the project but each time I get 50+ errors similar to this one:

```
PATH_TO_CHECKOUT\Mage\src\main\java\mage\game\match\Match.java
Error:(42, 37) java: package mage.game.result.ResultProtos does not exist
Error:(116, 5) java: cannot find symbol
  symbol:   class MatchProto
  location: interface mage.game.match.Match
```

If I navigate to the file above (`Match.java`) there's an error on the following line:

`import mage.game.result.ResultProtos.MatchProto;`

"Cannot resolve symbol 'result'"

Let me know if you have some pointers! I'll keep trying to figure it out and document my process. I'll put it together nicely and update the wiki if I can figure it out. I'm used to the Jetbrains IDEs but not too familiar with Java so it is quite possible I'm missing something obvious here.

Thanks!

**Comment by Marco-Marin** [comment]
I believe there was a bit of info from another user, at the "join the
developers" thread of the forums.. you may have to roll a few pages back to
find it.

**Comment by Simown** [comment]
@gnumast Sure thing. One of us can do the wiki, it's whoever gets round to it first. Let's try and fix these issues initially. It's been a few months since I actually checked out a fresh copy, so let me see. 

I didn't do a "File > Open" from IntelliJ. If you do "File > New > Project from existing sources" and select the "pom.xml" file which is in the root directory of the checked out source, and import it that way. Clean and build with "mvn clean install -DskipTests" to start with. Does that work?

**Comment by Simown** [comment]
Another thing, that may be a non-issue now is that Mage.Server when run had several "ClassNotFoundExceptions". To fix this in IntelliJ:
- File > Project Structure
- Select mage.server
- Add jar or directory
- Add xmage.jar from xmage/Mage/target

**Comment by Simown** [comment]
@gnumast I never use IntelliJ to build. Not that it can't, it seems to run out of memory when I do it in the IDE, I just use maven on the command line to build the project and the IDE for the rest. Thankfully there is a terminal window you can access from inside IntelliJ, I forget the shortcut but it's somewhere. I have no idea about working the protocol buffers, sorry.

Are you making a launch configuration? It should look something like this for mage-client as an example:

![configuration](http://i.imgur.com/7qxSFMJ.jpg)

**Comment by gnumast** [comment]
@Marco-Marin Right, I found [this thread](http://www.slightlymagic.net/forum/viewtopic.php?f=116&t=10707#p133583) which I had to tweak just a bit. I created the 3 following configurations:

Application (called it Run Server)
Main class: mage.server.Main
Working Directory: <path to checkout>/Mage.Server
Use classpath of module: mage-server

Then I created the exact same one for the client, basically replacing all instances of "server" with "client". The "Working Directory" is what wasn't mentioned in the post I linked. Turns out it's mentioned a couple of posts down though.

I then created a 3rd configuration, this time "Maven":

Maven (called it Clean Build)
Working Directory: <root of the mage source>
Command line: clean install -DskipTests

From there I can build everything or run the server/client. It's working quite well. Next is to see if I can run tests properly.

@Simown Your replied showed up while I was posting this. Looks like I ended up creating a run configuration just like yours and it's working! Thanks!

**Comment by gnumast** [comment]
@Simown @Marco-Marin 

Added some notes on the wiki page, feel free to add/edit. https://github.com/magefree/mage/wiki/Developer-Getting-Started#intellij-idea

**Comment by gnumast** [comment]
Looks like editing .form files is still an issue -- Jetbrain products use .form for addons/plugin interfaces I think? Trying to open a form says:

> Form file is invalid: Not IntelliJ IDEA GUI designer form file

**Comment by Marco-Marin** [comment]
I'm glad it helped as I can't help more directly, it took quite a bit of
frustration to set up my Netbeans environment here (as that very thread may
have been witness : ) not a Java guy either) so I'll stick with that, at
least until it tries too much my patience (sometimes it gets pretty slow),
when would be great to have an alternative to run to, if you guys can
figure it out.

**Comment by Simown** [comment]
@gnumast I think .forms are a specialist Netbeans thing for editing the GUI and auto-generating code for it. I have not had any experience using them though.  Most <gui-element>.java has a corresponding <gui-element>.form in Mage.Client.

Do you only make with maven on have a "make" option on the "Before launch" panel too? I could never make with the GUI or it would eat all the memory and bail out.

**Comment by gnumast** [comment]
@Simown No, I don't have anything in "Before launch", all it does is run `mvn clean install -DskipTests`,  which I could run from the terminal anyways. 

![xmage-maven-conf](https://cloud.githubusercontent.com/assets/175920/15793213/8861456e-29b0-11e6-9e66-b1a15f0c4cbc.png)

**Comment by Simown** [comment]
Yeah, I do the same. I think "make" is in the "Before launch" by default when you create a configuration. I always do a "mvn clean install" when first pulling in new changes and then a "mvn install" (without the clean) seems to suffice for the rest of the time. Glad it's working now anyway.

**Comment by Simown** [comment]
Think this can be safely closed now. The wiki has been updated with IntelliJ specific documentation (https://github.com/magefree/mage/wiki/Developer-Getting-Started#intellij-idea)
