### ISSUE TITLE
Leech Bonder -1/-1 Tokens don't kill off enemy creatures

### ISSUE THREAD

**Issue by Infinity95** [magefree/mage#1975]
As the title says, the card Leech Bonder (or the token mechanic) doesn't seem to work quite as intended. If moving a -1/-1 counter from the Leech Bonder onto an enemy creature with 1/1 the creature stays as a 1/1 with the token being displayed on it. Going by the rules the creature should have 0/0 and thus be put into the graveyard.

**Comment by drmDev** [comment]
What do you mean by "the token mechanic"? Leech Bonder is just a creature that can move -1/-1 counters to another creature. I was able to duplicate that it does not actually apply the -1/-1 counter to the other creature when it should nonetheless.

**Comment by Infinity95** [comment]
I didn't look at how the card is implemented but the important thing is, that when moving -1/-1 counters from ones own creatures onto enemy ones, they aren't affected. Maybe this has something to do with ownership of tokens? But that's just speculation as i don't know the implementation like i said.

**Comment by drmDev** [comment]
The implementation of the card seems suspect and almost assuredly isn't right, so it isn't handling situations like this correctly. It should be determining the counter type it is moving from the first target, then applying that counter type to the second targetted creature. It is not moving the -1/-1 counters correctly so 1/1 creatures remain as 1/1s. I didn't do any tests with tokens, the bug happens without any tokens in play, so was just confused with that part of the issue.

**Comment by Infinity95** [comment]
With token mechanic i meant how the -1/-1 tokens are implemented ;)

**Comment by drmDev** [comment]
Those are -1/-1 counters, not tokens. That's where the confusion was. Tokens and Counters are quite different in many aspects, including their implementation in XMage.

**Comment by Infinity95** [comment]
Oh, yeah. You're right. Used the wrong word there lol.
