### ISSUE TITLE
Getting thrown Error:java: OutOfMemoryError: insufficient memory

### ISSUE THREAD

**Issue by wizardsambolton** [magefree/mage#1977]
When running the server and client

EDIT: btw I am using IntelliJ

**Comment by wizardsambolton** [comment]
Bump

**Comment by thechucklingatom** [comment]
While I am not using intelliJ for this project right now, I have no issue running both at the same time. Just out of curiosity what are your machine specs and a full stack trace of the error?

**Comment by wizardsambolton** [comment]
@thechucklingatom I have 16 gig ram 1tb storage and Intelli is being a bugger to me atm, but will give it u in the morn

**Comment by Marco-Marin** [comment]
For Netbeans there is 1 (or more) option to allow it to use more memory.
It's described in the getting started document (github I guess). Maybe
trying to search the equivalent on IntelliJ

**Comment by wizardsambolton** [comment]
@Marco-Marin @thechucklingatom Ok I have switched to intellij now, it works fine when running the client however when I run the server I get the following:

```
------------------------------------------------------------------------
BUILD FAILURE
------------------------------------------------------------------------
Total time: 11.676s
Finished at: Wed Jun 08 07:57:38 BST 2016
Final Memory: 9M/309M
------------------------------------------------------------------------
Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:exec (default-cli) on project mage-server: Command execution failed. Process exited with an error: 1 (Exit value: 1) -> [Help 1]
```

**Comment by wizardsambolton** [comment]
OK fixed that by allocating more memory, however now the build succeeds, but it says cant start mage server because its already running, even though its not

**Comment by wizardsambolton** [comment]
Ok so I restarted netbeans and now it cant get past:

`Loading cards`

**Comment by wizardsambolton** [comment]
OK working now thanks for y'alls help!

**Comment by wizardsambolton** [comment]
OK issue is back, the server gets to loading cards dosnt move on, and I cant connect to the server from the client.

**Comment by wizardsambolton** [comment]
Ok nailed it

**Comment by wizardsambolton** [comment]
Ok now the server is saying its listening however when I try and connect it says server is offline :/

**Comment by wizardsambolton** [comment]
sorry y'all it went to the fallback port.
