### ISSUE TITLE
Require confirmation before starting tournaments

### ISSUE THREAD

**Issue by draxdyn** [magefree/mage#1978]
Currently in XMage when someone joins a tournament that isn't full, he has to wait until it becomes full, potentially for several minutes, and in the meantime, the player will likely do something else and may even leave his computer.

At a random moment from his perspective, the tournament will then suddenly fire, and the person may very well miss it, resulting in missing the first draft picks and dropping out of the draft, worsening the draft experience for the whole table.

So I think it would be great if, when the tournament is full, it does not just suddenly start, but rather everyone gets a confirmation message with a 30 seconds timeout, and if a player doesn't confirm, he is removed from the table and the tournament doesn't start until it is full again (with another confirmation).

Summary of changes I'd propose:
1. There is no longer a "Start" button in the tournament window. Instead, when the full, the tournament automatically attempts to start.
2. When the tournament attempts to start, players (including the tournament creator) get a notification with sound, and are asked to confirm or cancel, with a 30 second timeout. If they cancel or timeout they are dropped from the table and the tournament goes back to the waiting to be full state.
3. If a player declined to confirm to start or timed out twice on the same tournament table, he is no longer allowed to join that specific table (this prevents someone continuously causing false starts)
4. If the tournament creator fails to confirm or otherwise leaves the table, the one who joined first among the remaining becomes the game host (or alternatively, there is no longer a concept of a tournament host at all)
5. If everyone leaves the tournament, the tournament ceases to exist

**Comment by JayDi85** [comment]
There are already sound plays, app icon blinks and app icon popup message about tourney ready/start. So no need in additional confirmation/notification.
