### ISSUE TITLE
Remove white corners on card images

### ISSUE THREAD

**Issue by spjspj** [magefree/mage#1979]
Xmage is able to display cards with rounded edges correctly.  However, at the moment, depending on the image that is downloaded for the card, they can have fairly ugly white corners on the cards.  These can be transparent by adding an alpha channel and converting the image to a png from a jpg for example.
Example of the white pips on the corners of a swamp:
![image](https://cloud.githubusercontent.com/assets/16917728/15898747/bf6bdda0-2ddc-11e6-8eac-15f55a4309eb.png)
Example of no-white corners on a vindicate:
![image](https://cloud.githubusercontent.com/assets/16917728/15898836/169e82bc-2ddd-11e6-821a-958c7e2fd682.png)

Would be nice to have a tool to automagically go through and fix the alpha issues on all cards that have been downloaded.  It would be possible to script something with say imagemagick but having that option from xmage itself would be more usable.

**Comment by GORE84** [comment]
Its possible to remove them with Imagemagick. Would be nice to have a script that removes on all cards. Here is a method but not good enough: https://www.reddit.com/r/XMage/comments/51ygba/imagemagick_method_for_getting_rid_of_white_pips/

**Comment by Zerrisx** [comment]
This no longer seems to be an issue with Scryfall images

![image](https://user-images.githubusercontent.com/59861365/87829874-7c2f6180-c845-11ea-85cc-3c7238ab4f1a.png)

**Comment by JayDi85** [comment]
There are special code to make round corners. So that issue is no more actual.
