### ISSUE TITLE
Once I have stopped the server (in netbeans) it says the port is still in use

### ISSUE THREAD

**Issue by UnbanTwin** [magefree/mage#1982]

**Comment by wizardsambolton** [comment]
bump

**Comment by wizardsambolton** [comment]
Bump

**Comment by fenhl** [comment]
Same here.

**Comment by LevelX2** [comment]
Stopping the server (in netbeans) means to cancel the process in the netbeans task bar in the bottom tooltbar?
And you get the message as you run again the server?

I never had a problem when I canceld the server task before.
Did you use the XMage server on the system without netbeans before?

**Comment by Dilnu** [comment]
I'm seeing this pretty consistently. Near as I can tell the server is somehow spawning two java processes and Netbeans only stops one of them.

**Comment by allentiak** [comment]
Is this still valid?

**Comment by JayDi85** [comment]
IntelliJ works pretty good with xmage, NetBeans only for GUI design (IntelliJ do not support old swing form files).
