### ISSUE TITLE
Legendary permanent gets deleted on rollback

### ISSUE THREAD

**Issue by mlgiraud** [magefree/mage#1983]
If a legendary permanent ist already on the battlefield, when playing another legendary permanent with the same name the game asks which to keep. If one now requests a rollback both legendarys disappear.

**Comment by drmDev** [comment]
Very likely related to all around rollback bugs. Parent issue now is #2072

**Comment by Infinity95** [comment]
Just want to add that this bug existed before the parent issue but it still might be related.

**Comment by LevelX2** [comment]
The first Legendary does not disappear, it goes to the graveyard after the rollback.
That's for sure not correct. It should stay on the battlefield.
