### ISSUE TITLE
Eye of the Storm possibly bugged

### ISSUE THREAD

**Issue by spjspj** [magefree/mage#1985]
When a player is removed from the game and has had instants/sorceries imprinted on Eye of the Storm, it can cause issues.

**Comment by spjspj** [comment]
Have made some changes to the code with a1f9a5745cf29a36fc1d9fc08ad659534ddb82eb 
 * Now checks in checkTrigger if it's an instant/sorcery
 * Checks if the owner of the imprinted spell is !null

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.
