### ISSUE TITLE
Server offline since yesterday?

### ISSUE THREAD

**Issue by albuzs** [magefree/mage#1997]
Is there something wrong on my end, or is the server down?

**Comment by drmDev** [comment]
Try XMage.de server. Woogerworks is temporarily down and beyond our control at the moment. See here for updates and details:

http://www.woogerworks.com/index.php/9-hosted-service-information/106-xmage-server-information

(Bottom-left in Recent Tweets section): So it appears the VPS provider that hosts our XMage server may be experiencing some issue's. We are looking into the matter.

Our XMage service appears to be Down, we hope to have it back up as soon as possible. (2016-06-12 20:23:10pm)
