### ISSUE TITLE
Arrows missing for entersTheBattlefieldTriggered ability of token that copies a creature with that ability.

### ISSUE THREAD

**Issue by LevelX2** [magefree/mage#200]
1a) Cast Archeomancer
1b) EntersTheBattlefieldTriggered ability is shown on the stack, showing arrow from Archeomancer to ability on the stack
1c) Select target in graveyard, additional arrow is shown from Stack to graveyard.
That's ok so far.

2a) Cast Rite of Replication targeting the Archeomancer.
2b) The copied token comes into play.
2c) EntersTheBattlefieldTriggered ability of the token is shown on the stack, the arrow from Archeomancer to ability on the stack is missing.
2d) Select target in graveyard, additional arrow from Stack to graveyard is also missing.

**Comment by emerald000** [comment]
Works correctly now. Closing.
