### ISSUE TITLE
Cannot play Constructed decks on XMage.de server

### ISSUE THREAD

**Issue by albuzs** [magefree/mage#2011]
Hello,

I can't start any game while having a card from OGW in my deck. I am on the xmage server. Is there a fix to this?

**Comment by drmDev** [comment]
This issue wasn't very clear, but I am seeing multiple people, including myself, have issues being able to play a constructed deck.

When I try to join a modern constructed game using my Bant Eldrazi deck, this is the message I am given:
![card-not-found](https://cloud.githubusercontent.com/assets/11060241/16132705/50b78d1c-33e2-11e6-8bbb-9597515c0967.png)

XMage.de server. Seems to be related to almost any card you can think of - people have reported it with Zulaport Cutthroat, Kozilek's Return, and likely many other cards (Windswept Heath in my case).

**Comment by albuzs** [comment]
Yes! I am sorry for not being clear. This is the exact error I am getting

**Comment by drmDev** [comment]
Resolved after server reboot

**Comment by LevelX2** [comment]
Sorry, was not aware of the problem to reboot the server.
