### ISSUE TITLE
Iptables, ping and "NEW" state

### ISSUE THREAD

**Issue by Smoolak** [magefree/mage#2012]
Im not completly sure about this but if the iptables of my server is configured to reject connection in the "NEW" state, xmage don't want to connect to my server.

I think as to do with the way xmage ping the server.

**Comment by m-terlinde** [comment]
Well, if you block "all new connections", you won't be able to connect to any service on your server.
According to [this](http://www.iptables.info/en/connection-state.html) the "NEW" state describes this packages:

> The NEW state tells us that the packet is the first packet that we see. This means that the first packet that the conntrack module sees, within a specific connection, will be matched. For example, if we see a SYN packet and it is the first packet in a connection that we see, it will match. However, the packet may as well not be a SYN packet and still be considered NEW. This may lead to certain problems in some instances, but it may also be extremely helpful when we need to pick up lost connections from other firewalls, or when a connection has already timed out, but in reality is not closed. 

You have to allow connections to your xmage port, if you want to connect to it. If your server would connect to somewhere else, your rule would be right.

Is it a bit clearer now?

**Comment by Smoolak** [comment]
Yes it is. I had a set of iptables rules that was working with my ssh, http, https server setup and not with the xmage server. By adding the NEW state in one of the rule the client was able to connect to the server. Im still not sure how it was possible to connect to the http server and not to the xmage server before, but thanks anyway.

**Comment by m-terlinde** [comment]
I think this one can be closed...
