### ISSUE TITLE
Archangel Avacyn transform trigger applies after she is removed and recast in Commander

### ISSUE THREAD

**Issue by Zeplar** [magefree/mage#2014]
If Archangel Avacyn is removed and recast from the Command Zone after its transform ability triggers, it will continue to transform. It should enter the game as a new object.

**Comment by LevelX2** [comment]
I was not able to recreate taht problem.

How and when exactly the Archangel Avacyn was removed. And when it was recast exactly?

Can you provide the game log?

**Comment by Zeplar** [comment]
Avacyn's ability triggers when a non-angel is killed and then again at the next upkeep.
A creature died during combat damage, Avacyn was removed with Karlov's exile ability in response to the first trigger, and recast next turn in response to the second trigger.

**Comment by Zerrisx** [comment]
Cannot reproduce.
