### ISSUE TITLE
Cards that care about exile and are able to use cards exiled from previous invocations

### ISSUE THREAD

**Issue by spjspj** [magefree/mage#2015]
These cards appear to have the issue in which a future invocation of the permanent is able to access cards exiled from a previous invocation:
1) Karn, Liberated
2) Fiend of the Shadows

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.   Karn doesn't carry over and Fiend of the Shadows _should_ carry over and does; that's not a bug.
