### ISSUE TITLE
Flipped Gideon has a cmc of 1

### ISSUE THREAD

**Issue by elliott-king** [magefree/mage#2022]
Repeal requires you to have x = 1, instead of x = 0, as it should be.

**Comment by thechucklingatom** [comment]
This was updated with the shadows over innistrad rules update. It states that a double faced card retains the CMC of the side that has the mana cost, you can read more about it [here](http://magic.wizards.com/en/articles/archive/feature/shadows-over-innistrad-mechanics)

**Comment by elliott-king** [comment]
Whoop aight
