### ISSUE TITLE
Brass Herald Broken

### ISSUE THREAD

**Issue by SmileycorpMC** [magefree/mage#2024]
Brass herald does not give creatures of the chosen type +1/+1, tested in mormir, not in other formats.

**Comment by LevelX2** [comment]
Cards using ChosenSubtypePredicate class do not work correctly if copied (e.g. Copy Artifact or Copy Enchantment) or a token is created for them.

Still not fixed:

- [ ] Traveler's Cloak
- [ ] Belbe's Portal

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.  Tested with Mythos of Illuna; copies of Cloak and Portal allowed you to choose new types, and functioned correctly with those types.
