### ISSUE TITLE
Aura Swap bug

### ISSUE THREAD

**Issue by Smoolak** [magefree/mage#2025]
There's a bug with activating the Aura Swap ability on Arcanum Wings.

Most of the time the spell goes on the stack and resolve without asking anything and Arcanum Wings stay in place. I was able to make it work correctly one time.

The bug as been observed when Arcanum Wings is attached to Academy Researchers and Slippery Bogle.

**Comment by spjspj** [comment]
I couldn't recreate this at the time.  But I didn't try putting it on Slippery Bogle so will have another look..

**Comment by jeffwadsworth** [comment]
Actually, this card works incorrectly anyway.  There should be no targeting once you select the aura card in your hand.  Looking at it now.
