### ISSUE TITLE
Add Planechase Free For All game type

### ISSUE THREAD

**Issue by fenhl** [magefree/mage#2038]
Since _Planechase Anthology_ releases in November, it would be nice to support this variant. With my very limited understanding of the codebase, I believe the following steps would be required:
- [ ] Implement planes and phenomena.
- [ ] Add support for ordered decks in the command zone. If done right, this will also be useful for Archenemy.
- [ ] Implement the start-of-game procedure (CR 901.4 and 901.5)
- [ ] Handle players leaving the game (CR 901.10)
- [ ] Implement the planeswalk keyword action.
- [ ] Implement the planar die.
- [ ] Add a new setting to match creation: planar decks, with the options: none, single, per player. This will allow Planechase to be combined with other variants like Commander.
- [ ] Add deck submission for planar decks.

**Comment by Zerrisx** [comment]
Duplicate of #4704
