### ISSUE TITLE
The [Done] buttone does not appear some times.

### ISSUE THREAD

**Issue by seedds** [magefree/mage#204]
The [Done] buttone does not appear some times.
I have to click somewhere in the table to make it appear.
![Untitled1](https://f.cloud.github.com/assets/3463322/402727/8ce5f7e6-a908-11e2-885a-1f070563ad9d.jpg)

![Untitled2](https://f.cloud.github.com/assets/3463322/402728/91aeb092-a908-11e2-8ff3-ec1be8713bf3.jpg)

**Comment by goesta** [comment]
I'll close this issue because it seems to be outdated but feel free to create a new one if this problem still exists.
