### ISSUE TITLE
Ability to remap function keys to other inputs

### ISSUE THREAD

**Issue by drmDev** [magefree/mage#2042]
From reddit:
"... it would be absolutely fantastic if we were able to map the auto passes to something other than the function keys."

Perhaps we just add another tab in Settings for Controls. Inside here we could make it so the user is able to remap whatever Function Keys (skips) to whatever inputs they want. They could for instance remap it to another key or key combination (Shift+1). Or they could remap it to some mouse buttons like Mouse Button 4, 5, etc on mouses with that many buttons. Or they could remap it to their USB gamepad (might be more difficult to implement - think of programs that do this like XPadder).

Also, this would be a great time to find a way to work in a key combination to be able to switch tables. See the issue on multi-table handling: #1662

**Comment by JayDi85** [comment]
Hotkeys with CTRL/SHIFT/ALT buttons:
https://stackoverflow.com/questions/42353939/how-can-i-detect-ctrlshiftany-key-using-a-keyadapter

**Comment by JayDi85** [comment]
Fixed via 10234d508f2ad888cda19fa9f0b13856563d2fd4
