### ISSUE TITLE
New UI Changes resulting in graphical issues/artifacts/overlaps

### ISSUE THREAD

**Issue by drmDev** [magefree/mage#2043]
There seems to be some bugs with the changes made to UI handling recently. See the screenshot below.

![ui issues](https://cloud.githubusercontent.com/assets/11060241/16540799/aa1ccec2-403e-11e6-8045-e0f755b55b0a.png)

**Comment by LevelX2** [comment]
Was the problem with the transformable cards.
Should be fixed now with the lastes commit..
