### ISSUE TITLE
Xmage Error reading config

### ISSUE THREAD

**Issue by VanHawk94** [magefree/mage#2049]
Anytime i open XMAGE to try and play, on the launcher it says: 
"Reading config from http://xmage.info/xmage/config.json
Error reading config from http://xmage/config.json
possible causes: Site is offline or internet connection is unavailable."

My internet connection is fine. Does anybody know a fix for this?

**Comment by LevelX2** [comment]
Go to Launcher Setting and change the XMage home.
You need to change your settings from "http://xmage.info/xmage" to "http://xmage.**de**/xmage".
And check if you use the latest launcher version 0.3.8 .

**Comment by VanHawk94** [comment]
I've done that and use the latest version, but didn't work

**Comment by LevelX2** [comment]
So what's happening now?

From "didn't work" is hard to guess the cause.

**Comment by VanHawk94** [comment]
The message is almost the same
"Reading config from http://xmage.de/xmage/config.json
Error reading config from http://xmage.de/config.json
possible causes: Site is offline or internet connection is unavailable."
