### ISSUE TITLE
MorbidCondition still triggering even with Leyline of the Void out.

### ISSUE THREAD

**Issue by spjspj** [magefree/mage#2053]
I was playing a game with Leyline of the Void out.
DeathReap Ritual which has a Morbid Condition was in play and they were drawing cards from it at end of turn. 
This shouldn't be triggering if only my opponent's creatures are leaving the BF and going to Exile? 
I think CreaturesDiedWatcher.java needs a further check to see if they are going to GY specifically.

**Comment by Hexadan** [comment]
The way Morbid triggers is if a creatures died that turn, it doesn't matter if it went to the graveyard or was exiled. So this is working properly.

**Comment by spjspj** [comment]
From the rules:
700.4. The term dies means "is put into a graveyard from the battlefield."
If a replacement effect such as lotv is in effect, morbid shouldn't trigger

**Comment by Hexadan** [comment]
Oh, my bad, I was at work and didn't have a chance to check the actual rules.

**Comment by spjspj** [comment]
Relevant files:
ZoneChangeEvent.java  - isDiesEvent
CreaturesDiedWatcher

**Comment by jeffwadsworth** [comment]
I just tested this and it worked correctly with LV and DR on MY battlefield.  Did someone else experience this bug?  In my case, I use Terror to destroy my opponent's Sage's Row Denizen during my main phase.  It exiled it correctly and no card was drawn during my end step.  I will test it with the cards on the opponents side next.

**Comment by jeffwadsworth** [comment]
Test added.  Fails.

**Comment by drmDev** [comment]
Test was created incorrectly. PlayerB always has a draw step so will draw a card. They originally had Murder in hand before their turn, then they have their draw step. Once that was fixed, test passes.

Test commit:
https://github.com/magefree/mage/commit/a0ab8e7a44980bc07fed309c5b97e79ca341e9cd

**Comment by spjspj** [comment]
Further info.  This was based on eldrazi scions(?) being sacced for mana (can't remember if from awakening zone or from beyond).  The replacement effect means they shouldn't ever be placed in the gy so no morbid condition should be seen.  I was able to reproduce it around when I assigned it to myself.  Hopefully getting da PC back online tomorrow

**Comment by drmDev** [comment]
Guess I'll pick it up. I'll add some more test scenarios like the one just described here.

**Comment by spjspj** [comment]
Sorry @drmDev I had assigned myself to this prior to my PC issues and it seemed like @jeffwadsworth  and you had done a fair bit more on it since then!

**Comment by drmDev** [comment]
Added tests involving Awakening Zone "Eldrazi Spawn" tokens and confirmed the bug is there.

**Comment by emerald000** [comment]
Tokens are not cards and thus not affected by Leyline of the Void. They should go the graveyard normally and trigger Morbid.

**Comment by fwannmacher** [comment]
@emerald000 is correct. Leyline only looks for cards, so tokens go to the graveyard and enable Morbid.

**Comment by Hexadan** [comment]
"Leyline of the Void’s second ability doesn’t affect token permanents that would be put into an opponent’s graveyard from the battlefield. They’ll be put into that graveyard as normal (causing any applicable triggered abilities to trigger), then they’ll cease to exist."

[http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=107682](source)

**Comment by drmDev** [comment]
Cool, well then I'll adjust the test and close this issue.
