### ISSUE TITLE
Grave Scrabbler madness ability does not bring card back to hand.

### ISSUE THREAD

**Issue by diogovk** [magefree/mage#2056]
To test, you gotta have a creature card in the graveyard.
You should discard and pay the madness cost of Grave Scrabbler.
You then select the card you want to have back to your hand.

What is expected:
The creature card returns back to hand.

What happens:
Nothing. The effect fizzles for no apparent reason.

**Comment by dylan1020** [comment]
Can confirm. I was trying out Tortured Existence and discarded Grave Scrabbler to the ability of TE. The Madness part worked perfectly and the Grave Scrabbler's ETB went on the stack and I could target a creature in the graveyard, but nothing happened when the ability resolved.

**Comment by drmDev** [comment]
I was just going through our git issues for some cleanup and tagging. I just marked "not confirmed" if no one else mentioned the issue and I haven't duplicated it myself. I'll remove the not confirmed tag. I'll look into this shortly.

**Comment by jeffwadsworth** [comment]
The issue looks to be related to the "madnessAbility.getCondition()".  Looking at it soon.

**Comment by jeffwadsworth** [comment]
You are correct.  It is the ConditionalTriggeredAbility().  Amazingly, we don't have any tests for that class.  Checking it out soon.

**Comment by dylan1020** [comment]
I really need to get my dev environment set up and start doing stuff, but from my initial observation with minimal knowledge of the codebase, the issue may be that the etb ability is set up differently from other creatures with madness.

` EntersBattlefieldTriggeredAbility ability = new EntersBattlefieldTriggeredAbility(new ReturnToHandTargetEffect(), true);` 

From [Grave Scrabbler](https://github.com/magefree/mage/blob/master/Mage.Sets/src/mage/sets/futuresight/GraveScrabbler.java), versus this

`Ability ability = new EntersBattlefieldTriggeredAbility(new DestroyTargetEffect(true));`

From [Big Game Hunter](https://github.com/magefree/mage/blob/master/Mage.Sets/src/mage/sets/planarchaos/BigGameHunter.java)

**Comment by jeffwadsworth** [comment]
Well, the condition just checks if MadnessTriggeredAbility is activated, not if the cost was paid.  Looking at it soon.  The condition is failing on a check right before resolution.

**Comment by jeffwadsworth** [comment]
Fixed.  Uploading soon.
