### ISSUE TITLE
Cannot find PreventAllDamageByAllEffect

### ISSUE THREAD

**Issue by Dilnu** [magefree/mage#2057]
Hi, it looks like someone deleted a class called PreventAllDamageByAllEffect. It's referenced in a few places within the repository but as far as I can tell it doesn't exist.

mage/sets/gatecrash/Hindervines.java:[34,37] cannot find symbol
  symbol:   class PreventAllDamageByAllEffect
  location: package mage.abilities.effects.common

**Comment by LevelX2** [comment]
It was renamed to PreventAllDamageByPermanentsEffect

**Comment by drmDev** [comment]
There still were 6 cards that had the old name of the effect. I changed them. Will be uploading changes shortly.
