### ISSUE TITLE
Xmage-only set(s)

### ISSUE THREAD

**Issue by drmDev** [magefree/mage#2059]
Based off Gitter discussion and reddit post ( https://www.reddit.com/r/XMage/comments/4nk88p/xmage_only_set/ )

"There is some interest (relatively embryonic at this stage) amongst some of the devs for implementing xmage only cards for use in either freeform or a new commander+xmage-only format. If folk have suggestions and high quality art for possible cards, limited to current mechanics implemented already on xmage, there may be a possibility to implement cards that are suggested and get rated highly on here."

I suggested implementing a custom set that has already been fully fleshed out so we already have the images and would make for a more cohesive drafting environment. The most popular custom set I can think of and am interested in is the Star Wars MTG set: http://www.mtgsalvation.com/forums/creativity/custom-card-creation/custom-set-creation-and/608696-swtg-star-wars-the-gathering-255-255-feedback

**Comment by Styxo** [comment]
I started to implement the set some time ago and have about 80 cards done (the easy ones :) but they are already tested and are working) but been busy lately.
It seems I will have some free time next week so I will try to finish the rest.

**Comment by drmDev** [comment]
Awesome! Let us know if there's anything you want us to work on to help out with it. See our Developer Talk forum http://www.slightlymagic.net/forum/viewforum.php?f=116 or join us on Gitter (using your Github account for login) in the Magefree channel.

**Comment by drmDev** [comment]
Star Wars set has been implemented successfully a while ago. Great work!
