### ISSUE TITLE
Hive mind and All Sun's Dawn interaction

### ISSUE THREAD

**Issue by debook454** [magefree/mage#2063]
I cast All Sun's Dawn with hive mind and it brought nothing back to my hand after everyone else had theirs resolve. It said it fizzled. May have something to do with other players changing the target of the copies.

**Comment by Dilnu** [comment]
How many other players were in this game? It seems odd to me that just the original spell would fizzle if all the other copies succeeded.

**Comment by debook454** [comment]
It was a 4 person commander game i belive

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.
