### ISSUE TITLE
Rollbacks may be bugged

### ISSUE THREAD

**Issue by spjspj** [magefree/mage#2072]
1.4.13v1 may have introduced bugs with rollbacks.  Possible changes that I can think of that broke it were the shrinking of the panel sizes (possible??) or possibly the Ctrl+Click (unlikely)

**Comment by dylan1020** [comment]
Rollbacks seem to be bugged right now. It doesn't roll back everything (like creatures no longer attacking and creatures that have died)

**Comment by spjspj** [comment]
fd60e43a03196a3164c357272e41b8b01a2eaa6e may have something to do with it.

**Comment by drmDev** [comment]
Another report on the forums regarding it:
"Rollback glitch when playing opponent (human NOT AI).
Person passed the turn, I had end step selected and it rolled right through my turn to the end and went to my opponent's turn. He then selected rollback to start of previous turn. It went back to the start of my turn, after my turn was over it skipped his turn and gave me another turn.

This has now happened with two different opponent's with at least one of us being skipped after a rollback occurs."

**Comment by drmDev** [comment]
Another report on reddit:
"I've encountered a very situational bug regarding Flagstones of Trokair. I cast Smallpox and sacced Flagstones of Trokair, but before the flagstones trigger resolved, my opponent requested a rollback. I accepted and when the rollback happened, my Flagstones was gone and the trigger was still on the stack, however, the computer didn't allow either of us to have priority."

**Comment by drmDev** [comment]
With Emrakul, the Promised End: "If you roll back once or twice during your opponent's controlled turn, the opponent will not get an extra turn for some reason. " #2168

**Comment by LevelX2** [comment]
Creature that dies during combat was not returned to battlefield after rollback to start of current turn after the combat..

**Comment by quercitron** [comment]
Could not reproduce locally any of rollback bugs using a trivial scenario (some creatures die, then rollback to the current/previous turn start). Any suggestions how it can be reproduced?

**Comment by LevelX2** [comment]
https://www.reddit.com/r/XMage/comments/638dnk/rollback_glitch_fix/

**Comment by tebo37** [comment]
Bump - this is definitely still happening. Upon rolling back, one player is unable to obtain priority ever again until the game ends. The reddit trick posted above did not work for us after 30+ attempts.

**Comment by JayDi85** [comment]
How to fix: remove all changeable data from `GameImpl` to `GameState`:
![shot_200615_230613](https://user-images.githubusercontent.com/8344157/84696018-df835680-af5c-11ea-81f3-a948a29488f1.png)

Suspicious data from GameImpl (can be moved to GameState, but need research):
* `checkPlayableState`
* `lki`
* `lkiCardState`
* `lkiExtended`
* `shortLivingLKI`
* `saveGame` - not used
* `permanentsEntering`
* `losingPlayer`
* `stateCheckRequired` - outdated and not used
* `infiniteLoopCounter` -- infinite loop check
* `lastNumberOfAbilitiesOnTheStack` -- infinite loop check
* `lastPlayersLifes` -- infinite loop check
* `stackObjectsCheck` -- infinite loop check
* `enterWithCounters`
* `concedingPlayers`

**Comment by JayDi85** [comment]
Not actual anymore
