### ISSUE TITLE
Poison counters not always applying.

### ISSUE THREAD

**Issue by Cysec2k** [magefree/mage#2073]
[20160713_161155_Two Player Duel_2.txt](https://github.com/magefree/mage/files/362416/20160713_161155_Two.Player.Duel_2.txt)
As can be seen in the attached log, my opponent should have been at 12 poison counters, yet the additional 7 did not apply, resulting in a game loss.

**Comment by drmDev** [comment]
Reviewed the game log, and the Become Immense spell is the one that shows it targetted the Inkmoth Nexus, but still only 1 damage went through instead of 7 on that turn. It's unclear what happened there. Will create JUnit test and test in game to see what happened here.

**Comment by drmDev** [comment]
Added a JUnit test that uses the same pump spells in this game, and the ending poison count is 12 as expected (also added a simple test with Become Immense alone leads to 7 poison counters as expected). Will need to test in-game to see what happened here.

**Comment by drmDev** [comment]
A possible explanation I can think of - combat damage was already applied, then Inkmoth Nexus was given +6/+6 by Become Immense. So only 1 poison damage went through during combat, then afterwards Inkmoth was pumped by Become Immense. The log isn't clear on when Become Immense was cast other than it was after Declare Blockers (attacker unblocked).

**Comment by Cysec2k** [comment]
It was applied after blockers, before damage.

**Comment by drmDev** [comment]
Also tested in game and could not reproduce the error. Opponent ended up with 12 poison counters and lost. Feel like we would be hearing more of these reports if this happened regularly. There still may be a bug somewhere but not enough information to go on from this. If it happens again we can re-open, but not seeing an issue and unable to duplicate.
