### ISSUE TITLE
Lose the game when Platinum Angel leaves the field with an empty library

### ISSUE THREAD

**Issue by sodaghost** [magefree/mage#2074]
My library was empty and I controlled Platinum Angel. I had already "drawn" from an empty library but hadn't lost due to the angel's effect. My opponent cast Set Adrift on the Angel, and I lost immediately when it resolved.

**Comment by drmDev** [comment]
Do you have a game log? Created a test for this and player with the Angel does not lose upon Set Adrift resolving.

**Comment by sodaghost** [comment]
I'm sorry, no. I'm pretty new to xmage. I got dumped from the game very
quickly so maybe I missed a detail, I could be wrong about this. Appreciate
you following up though!

**Comment by drmDev** [comment]
Also tested in game and did not lose the game upon Angel being sent to top of library. I was able to draw Angel for the next turn fine.
