### ISSUE TITLE
Coax from the blind eternities issue

### ISSUE THREAD

**Issue by albuzs** [magefree/mage#2075]
Hello,

If you own an exiled eldrazi, and another one on your sideboard, the card forces you to choose an eldrazi from your sideboard. This happens even if your chose the SB eldrazi.

**Comment by drmDev** [comment]
What happens when you select no to the prompt "Choose a Eldrazi card you own from outside the game (your sideboard), and put it into your hand?" . If you also control an Eldrazi in exile you should then be prompted to choose an Eldrazi in exile to put into play (after selecting NO to the first prompt - which only looks at your sideboard).

Perhaps the prompts can be worded differently.

**Comment by fwannmacher** [comment]
What do you think about making only one window with all cards? I mean, we can filter all Eldrazi cards from the sideboard and from the exile and show them together to the user.

**Comment by albuzs** [comment]
Yes! That option for choosing the eldrazi, regardless of being in exile or sb sounds good.

**Comment by fwannmacher** [comment]
@drmDev, @LevelX2 does that sound good for you?

**Comment by drmDev** [comment]
Sounds great - much more intuitive. In general if you have a way to make cards more intuitive to use or it fixes an issue with the card, go for it. If it is a change that affects the framework, just run the MAge.Tests project afterwards at least to have some more confidence it won't break much.

**Comment by fireshoes** [comment]
Can you make it clear where the Eldrazi is coming from when choosing it? Example, I have one World Breaker in my sideboard and one exiled to Stasis Snare. I would want to know which I am getting.

**Comment by fwannmacher** [comment]
I'll think in a way to do that.

**Comment by fwannmacher** [comment]
I've managed to show all cards in the same dialog and everything seems to be working. But, identifying the zone that card is coming from is a hassle. The player can see the card id and, based on that information, identify which one he/she wants to pick.

It's like when someone wants to exile a card in a graveyard that is target from a reanimation spell, for example.

**Comment by fwannmacher** [comment]
I've added the card zone to the "tooltip". What do you think about that?

![cardzone](https://cloud.githubusercontent.com/assets/1665660/17344869/0da336f8-58da-11e6-9a1e-9d937664df5a.jpg)

**Comment by fireshoes** [comment]
That looks good. Nice!

**Comment by drmDev** [comment]
awesome work as usual!
