### ISSUE TITLE
Damage wrong when Watcher in the Web blocking multiple creatures

### ISSUE THREAD

**Issue by drmDev** [magefree/mage#2076]
Reported on forums:

Not sure what card caused this particular weirdness, but I blocked all (four) attacking creatures with my watcher in the web, in this order:
Ulrich, Kessig Dire Swine (w/ trample), Howlpack wolf, Incorrigible youths. I misplayed, and deserved a full 6 trample damage from the swine instead of 1. But, for some reason, I took 7. Transcript below, screenshot as well.

05:38: AttackingPlayer attacks with 4 creatures
05:38: Attacker: Ulrich, Uncontested Alpha [f18](6/6) blocked by Watcher in the Web [48f](2/5) 
05:38: Attacker: Kessig Dire Swine [e6e](6/6) blocked by Watcher in the Web [48f](2/5) 
05:38: Attacker: Howlpack Wolf [f86](3/3) blocked by Watcher in the Web [48f](2/5) 
05:38: Attacker: Incorrigible Youths [910](4/3) blocked by Watcher in the Web [48f](2/5) 
05:38: Ulrich, Uncontested Alpha [f18] deals 6 damage to Watcher in the Web [48f]
05:38: **DefendingPlayer loses 7 life**
05:38: Howlpack Wolf [f86] deals 3 damage to Watcher in the Web [48f]
05:38: Incorrigible Youths [910] deals 4 damage to Watcher in the Web [48f]
05:38: Watcher in the Web [48f] deals 2 damage to Kessig Dire Swine [e6e]
05:38: Watcher in the Web [48f] died

-- How did he lose 7 life from this??

**Comment by jeffwadsworth** [comment]
I am making a test case for this.

**Comment by drmDev** [comment]
Test added : https://github.com/magefree/mage/commit/b81118a64dffbd82e32c84f24603705a4d7be01b

Test framework does not appear to support a single creature blocking multiple creatures, so the test fails but not for reasons related to the bug. It fails because it treats it as Watcher in the Web only blocking one creature. Test framework needs to be updated to support this.

**Comment by ogier** [comment]
Confirming this is an issue that still occurs with Night Market Guard from KLD draft. If any of multiple creatures blocked by a single creature have trample, all such creatures effectively do.

17:23: Player1 attacks with 2 creatures
17:23: Ability triggers: Aetherstream Leopard [597] - Whenever Aetherstream Leopard [597] attacks you may pay . If you do, it gets +2/+0 until end of turn.
17:23: Attacker: Gifted Aetherborn [aa6] (3/4) blocked by Night Market Guard [ed9] (3/1)
17:23: Attacker: Aetherstream Leopard [597] (4/3) blocked by Night Market Guard [ed9] (3/1)
17:23: Player1 gains 3 life
17:23: Gifted Aetherborn [aa6] deals 3 damage to Night Market Guard [ed9]
17:23: Player2 loses 6 life
17:23: Night Market Guard [ed9] deals 3 damage to Aetherstream Leopard [597]
17:23: Aetherstream Leopard [597] died
17:23: Night Market Guard [ed9] died

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.
![image](https://user-images.githubusercontent.com/59861365/82961953-652a6c80-9f84-11ea-9056-c99d216b180e.png)
