### ISSUE TITLE
Tamiyo's +1 does not turn off at the start of your turn

### ISSUE THREAD

**Issue by michaelstephendavies** [magefree/mage#2078]
This bug was reported on /r/xmage and I confirmed it's still there after the `triggerOnlyOnce` fix.

Tamiyo's +1 creates a `DelayedTriggeredAbility` and passes `Duration.UntilYourNextTurn` but it seems this isn't honoured. The delayed triggered ability sticks around for the rest of the game. I tried to instead use the technique from [Jace, Architect of Thought's +1](https://github.com/magefree/mage/blob/06ec3f16acbcddfe9a13ff0d4f71325d0d4ef921/Mage.Sets/src/mage/sets/returntoravnica/JaceArchitectOfThought.java#L124), and it seems to fix the problem but I didn't investigate that thoroughly. Here's the diff:

```diff
# This patch file was generated by NetBeans IDE
# It uses platform neutral UTF-8 encoding and \n newlines.
--- a/Mage.Sets/src/mage/sets/eldritchmoon/TamiyoFieldResearcher.java
+++ b/Mage.Sets/src/mage/sets/eldritchmoon/TamiyoFieldResearcher.java
@@ -143,7 +143,7 @@
                 creatures.add(new MageObjectReference(uuid, game));
             }
             if (!creatures.isEmpty()) {
-                DelayedTriggeredAbility delayedAbility = new TamiyoFieldResearcherDelayedTriggeredAbility(creatures);
+                DelayedTriggeredAbility delayedAbility = new TamiyoFieldResearcherDelayedTriggeredAbility(creatures, game.getTurnNum());
                 game.addDelayedTriggeredAbility(delayedAbility, source);
             }
             return true;
@@ -154,16 +154,19 @@
 
 class TamiyoFieldResearcherDelayedTriggeredAbility extends DelayedTriggeredAbility {
 
+    private int startingTurn;
     private List<MageObjectReference> creatures;
 
-    public TamiyoFieldResearcherDelayedTriggeredAbility(List<MageObjectReference> creatures) {
-        super(new DrawCardSourceControllerEffect(1), Duration.UntilYourNextTurn, false);
+    public TamiyoFieldResearcherDelayedTriggeredAbility(List<MageObjectReference> creatures, int startingTurn) {
+        super(new DrawCardSourceControllerEffect(1), Duration.Custom, false);
         this.creatures = creatures;
+        this.startingTurn = startingTurn;
     }
 
     public TamiyoFieldResearcherDelayedTriggeredAbility(final TamiyoFieldResearcherDelayedTriggeredAbility ability) {
         super(ability);
         this.creatures = ability.creatures;
+        this.startingTurn = ability.startingTurn;
     }
 
     @Override
@@ -183,6 +186,12 @@
     }
 
+    @Override
+    public boolean isInactive(Game game) {
+        return game.getActivePlayerId().equals(getControllerId()) && game.getTurnNum() != startingTurn;
+    }
+    
     public TamiyoFieldResearcherDelayedTriggeredAbility copy() {
         return new TamiyoFieldResearcherDelayedTriggeredAbility(this);
     }
```

**Comment by drmDev** [comment]
We have a few scenarios for Tamiyo in the Tests project from this commit 5754d53b3bd29a72f74eb84a5f89312251075bb5 . I'll add tests for additional turns like you mentioned here. Feel free to add more test scenarios. Then you can make these code changes and run the tests for an easy test if it broke anything with Tamiyo.

**Comment by drmDev** [comment]
I also read a report that Tamiyo +1 may not be working properly when it targets an opponents creatures. I'll add some test for that.

**Comment by drmDev** [comment]
Added tests for more scenarios as described above. Temporarily having issues with my dev environment so cannot confirm the tests results or not. Try the changes mentioned here by @michaelstephendavies  and then check the Tests for accuracy and run them with the Tamiyo changes

**Comment by drmDev** [comment]
@michaelstephendavies do you need any help with getting your dev environment to work right? You seem to be on the right track with coding these cards and always appreciate more contributors to the project. You can commit your changes and do a pull request for us to review and merge the changes into the master branch if you feel like it's working. Also let me know if you need help with using the Mage.Tests project - it's something I try to encourage all devs here to use more.

Now that I'm back home, I have my dev environment back up as needed (had to do a mvn clean install). Before doing your changes, all the tests pass except for the one where the effect persists beyond the next turn. After your changes, all the tests pass.

Thanks for your contributions! Again, let us know if you need any help getting more acclimated with contributing to this project more directly in the future.

**Comment by michaelstephendavies** [comment]
BTW if `DelayedTriggeredAbility` doesn't support certain `Duration`s then there should probably be something to stop this kind of bug from happening again. At least a comment, or perhaps the `DelayedTriggeredAbility` constructor should log a warning or even throw an exception if an unsupported `Duration` is passed.
