### ISSUE TITLE
Crop Sigil can't be activated without both a creature and land in the graveyard

### ISSUE THREAD

**Issue by fireshoes** [magefree/mage#2079]
The targets in Crop Sigil  seem to be correctly set for 'up to one' targeting, so perhaps it is a problem with ReturnToHandTargetEffect's multi-target handling.

**Comment by LevelX2** [comment]
Can't confirm that problem.
I could return a land without having a creature in the graveyard.
But because it's a Delirium ability you have to have four card type into the graveyard to use it.

**Comment by fireshoes** [comment]
I used the graveyard that was in the screenshot in the bug thread:
Aim High
Ulvenwald Captive
Bruna, the Fading Light
Geist of the Lonely Vigil
Extrictor of Sin
Field Creeper
Gryff's Boon

Tried to activate without success. Returned Gryff's Boon to the battlefield and put a forest into the graveyard, and then it worked fine. The card type count in the title bar of the open graveyard window showed 4 types in both instances.
