### ISSUE TITLE
Westvale Abbey + Cryptolith Rite

### ISSUE THREAD

**Issue by brunocc** [magefree/mage#2090]
When transform the Abbey and control the Rite can't attack with Abbey because just pump mana color selection.

**Comment by drmDev** [comment]
Are you saying with Cryptolith Rites in play, and a flipped Abbey, you cannot attack with the Abbey? When you try to, it instead taps for mana per Rites added ability on all creatures? Make sure you do not have the "automatically select first mana payment" option set. When you're in game, right click somewhere blank on the battlefield such as above or next to some card, you'll see the option for Mana Payments - make sure that option is unchecked.

**Comment by drmDev** [comment]
Tested in game, works fine. You likely had an option set to automatically default to using a lands first ability.
