### ISSUE TITLE
Sigarda, Host of Herons bug

### ISSUE THREAD

**Issue by bwoods89** [magefree/mage#2094]
In a 5 player EDH game, I put a merciless executioner in play as part of the resolution of Tempt With Immortality. An opponent who put Sigarda, Host of Herons into play from Tempt With Immortality, was forced to sacrifice her, even though her text says that that shouldn't happen.

**Comment by jeffwadsworth** [comment]
I will make a test for this case.

**Comment by drmDev** [comment]
Test commit confirms issue:
https://github.com/magefree/mage/commit/e71796816dfb9d3e1ada641db1a50aef1e52a341

**Comment by drmDev** [comment]
Test passes with new change
