### ISSUE TITLE
Tamiyo's +1 not ending EOT

### ISSUE THREAD

**Issue by albuzs** [magefree/mage#2095]
Hello,

If you target 2 creature of your opponent, you will draw cards for several turns in a row. The ability does not stop until your next turn, even if you do not +1 again.

**Comment by drmDev** [comment]
fixed with commit https://github.com/magefree/mage/commit/2ecadbc30b64dc79fec928a2ab707d94f9ec5982

confirmed with accompanying JUnit tests

Available beyond 1.4.13v2
