### ISSUE TITLE
Permeating Mass

### ISSUE THREAD

**Issue by hongkongohooey** [magefree/mage#2096]
If permeating mass dies from combat damage it's trigger goes on the stack but the creature(s) it damaged don't become copies upon resolution of the trigger.

**Comment by drmDev** [comment]
What was the scenario where it died from combat damage?

**Comment by hongkongohooey** [comment]
Anytime it dies from combat damage.  Example I blocked a Prized Amalgam. Damage happens Mass died trigger went on stack but the copy never happened.  I tested it and its repeatable.

**Comment by fireshoes** [comment]
When I made it, I didn't think it would be copyable if it died, so I just
had it get the permanent information, but it should use permanent or last
known information.

**Comment by hongkongohooey** [comment]
that's what I assumed had happened figured it would be an easy fix

**Comment by drmDev** [comment]
Should be fixed with commit: 99dbdef5ce22b8d14ec737ff0f20a2bb04ff6237

**Comment by drmDev** [comment]
Tested it and this issue is unresolved. When you block with Permeating Mass, the trigger goes on the stack, but the creature it dealt combat damage to did not become a copy of Permeating Mass.

**Comment by drmDev** [comment]
confirmed fix with commit bd70f923b7fd5b49f928ff01e7cda78c04de8da5

**Comment by FastTadpole** [comment]
Game error when creature dies and the ability of permeating mass is on the stack with no target, as it is dead. Creates infinite rollback loop to self correct.

`Game exception occurred: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
Server version: 1.4.14v0
java.util.ArrayList.rangeCheck(ArrayList.java:653)
java.util.ArrayList.get(ArrayList.java:429)
mage.abilities.effects.common.CopyEffect.apply(CopyEffect.java:107)
mage.abilities.effects.ContinuousEffectImpl.apply(ContinuousEffectImpl.java:124)
mage.abilities.effects.ContinuousEffects.apply(ContinuousEffects.java:898)
mage.game.GameState.applyEffects(GameState.java:540)
mage.game.GameImpl.applyEffects(GameImpl.java:1402)
mage.game.GameImpl.playPriority(GameImpl.java:1322)
mage.game.turn.Step.priority(Step.java:87)
mage.game.turn.Phase.playStep(Phase.java:210)
mage.game.turn.Phase.play(Phase.java:115)
mage.game.turn.Turn.play(Turn.java:152)
mage.game.GameImpl.playTurn(GameImpl.java:852)
mage.game.GameImpl.play(GameImpl.java:766)
mage.game.GameImpl.start(GameImpl.java:733)
mage.server.game.GameWorker.call(GameWorker.java:60)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
java.lang.Thread.run(Thread.java:745)
`
