### ISSUE TITLE
Imprisoned in the Moon incorrectly removes land subtypes

### ISSUE THREAD

**Issue by andyfries** [magefree/mage#2098]
If I control an Urza's Tower, Urza's Power Plant, and Urza's Mine with Urza's Mine enchanted with Imprisoned in the Moon, the Tower and Power Plant incorrectly tap for a single colorless mana. This is incorrect because the enchanted permanent is already a land and thus Imprisoned in the Moon does not remove the "Urza's" and "Mine" subtypes (it only removes other card types).

**Comment by drmDev** [comment]
Ruling on the card seems to confirm this:
" 	If the enchanted permanent is a land and has land types, it retains those types even though it loses any intrinsic mana abilities associated with them. For example, a Plains enchanted by Imprisoned in the Moon is still a Plains, but it can’t tap for {W}, only for {C}."

http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=414360

**Comment by fwannmacher** [comment]
drmDev, could you merge that test with master? That way I can fix the issue.

**Comment by drmDev** [comment]
It is in master already:
https://github.com/magefree/mage/commit/2733cc88a694736d7129a9c6d0656b078c5d6857

**Comment by fwannmacher** [comment]
OK, thanks

**Comment by drmDev** [comment]
test passes with new change
