### ISSUE TITLE
Nephalia Academy should only trigger from opponent's discard spell/ability

### ISSUE THREAD

**Issue by drmDev** [magefree/mage#2100]
From forum:
"Nephalia Academy - in game behaviour does not match printed text - it states "If a spell or ability an opponent controls causes you to discard a card..." but it triggers each time player discards a card (even in end step if player has too many card on hand).

Issue noticed in game vs. AI."

Confirmed bug with additional Nephalia Academy test:
0c7c6d57c314dd3902c26a4a03813de9975d98e6

**Comment by drmDev** [comment]
In the "applies" section there needs to be proper checking for the source of the discard spell/ability being from an opponent. Event.getPlayerId and source.getControllerId end up referencing the same player (the controller of Nephalia Academy) in this context, which is the typical way I see other cards determining if it was from an opponent. Only other thing I can think of is adding checks for if the discard was from a spell cast, to check stack objects and get the controller from there? Maybe I'm missing something simple.

**Comment by jeffwadsworth** [comment]
A discard event watcher that keeps tabs on what triggered it, etc.

**Comment by drmDev** [comment]
Test passes with new change.
