### ISSUE TITLE
Devotion and hybrid mana

### ISSUE THREAD

**Issue by fenhl** [magefree/mage#2105]
It seems that hybrid mana costs are not being counted toward devotion to a single color.

**Comment by drmDev** [comment]
added test 03b7c738eaf8bfc3c701627a911f6e2b562ce635 Purphoros was a creature with hybrid creature Boros Reckoner counting towards 3 of the devotion

**Comment by fenhl** [comment]
That's strange. In Momir Basic, all creatures are tokens. Perhaps that was part of the cause?

**Comment by fwannmacher** [comment]
I've added a test for tokens and it seems to be working.

**Comment by drmDev** [comment]
Unable to duplicate issue, tests are passing. Maybe only occurs in Momir Basic? Will re-open if issue is confirmed still occurring.
