### ISSUE TITLE
Bioshift and Blood Feud: Impossible state when selecting second target.

### ISSUE THREAD

**Issue by Dilnu** [magefree/mage#2106]
Hi, I was playing with Bioshift and I noticed that if you play it on a creature who's controller has no other creatures the game gets into an impossible state you can't escape from without conceding.

Specifically you can choose the first target just fine, but there is no valid second target and no way I can see to cancel having played the card. Optimally, I think it would be nice to always have a cancel button when choosing targets in addition to paying costs. 

Alternatively, cards like bioshift need to be modified so the first target checks that there will be a valid second target, which feels like a very cludgy fix that will need to change a lot of individual cards.

I'd be happy to take this on if someone could offer advice on how to make the change. I haven't messed with the UI at all so far and I'm not sure what it would mean to change FeedbackMode to FeedbackMode.CANCEL unconditionally on line 1190 of GamePanel.java

**Comment by drmDev** [comment]
confirmed bug. If I control just an Endless One with two +1/+1 counters and cast Bioshift on it, I am forced to try to select a second creature, and cannot. There is no way to cancel from this point, so the game is stuck in a state where it cannot continue forcing you to concede the game/match.

**Comment by Dilnu** [comment]
I discovered this because I was implementing a similar card, I'd expect that there are other cards with the same issue.

**Comment by Dilnu** [comment]
I just checked, the same thing happens with blood feud if there is only one creature on the field.

**Comment by Dilnu** [comment]
Carom interestingly enough does not have the same issue. Adapting that to blood feud is pretty easy but I'm running into issues with bioshift.

**Comment by drmDev** [comment]
Fixed with commit 218583ebf8c610c620e5dcd55c0dae81e712c800

New issue can be created if more cards are found with the issue.
