### ISSUE TITLE
Unable to reenter match after game crash/reload

### ISSUE THREAD

**Issue by NikitaSmall** [magefree/mage#2107]
Good day!
I am not sure that is an actual xmage bug (it is possible that the reason lies in my PC: I have a pretty cheap laptop with Ubuntu 14.04 x64), but here it is:
whenever I am forced to restart xmage (after it's own crash, or my needs, or after network short shutdown, when I am moved to enter screen) I cannot properly reenter the match. I hear 'Your match has started' and sounds of creatures (if in attack phase), but in general I see only battlefield background and enter window (emptied). After showing this the game freezes and only way out is `kill xmageProcessId`.

Again, I am sorry if this problem is only my own, but I need some help: I feel uncomfortably when I leave the battlefield as coward (in a eyes of my opponent).

**Comment by NikitaSmall** [comment]
To more clear description: after xmage restarting I saw this picture (original window was freezed after short network down):
![image](https://cloud.githubusercontent.com/assets/7057358/17082973/ed067538-5198-11e6-918b-387d30b6a003.png)

**Comment by goesta** [comment]
I'll close this issue because it seems to be outdated but feel free to create a new one if this problem still exists.
We also have a more recent issue open regarding reconnects.
