### ISSUE TITLE
Pulmonic Sliver trigger not occurring - slivers remain on battlefield instead of top of library or grave though

### ISSUE THREAD

**Issue by drmDev** [magefree/mage#2108]
edit: From reddit - https://www.reddit.com/r/XMage/comments/4uaxjz/pneumonic_sliver_crashes_the_game/

I think it's the "whenever a sliver would be put into a graveyard, you may put it on top of it's owner's library"-clause. either way - xmage doesn't support the trigger of it and won't let you do anything but concede (only possible in between the few seconds were the window which asks you what triggers you want to activate first disappears).

happened yesterday in a KTK - TSP - RAV draft.

**Comment by drmDev** [comment]
Cannot duplicate the "crashing" part - game is allowed to continue. However, Pulmonic Sliver makes it so no Slivers ever hit the graveyard. For instance, using Damnation with Pulmonic Sliver and Venom Sliver on board does not even trigger Pulmonic Sliver at all. Damnation just gets sent to the grave and both Slivers survive.

**Comment by drmDev** [comment]
Added tests to confirm the issue. Whether a single target spell or wrath effect, slivers remain on the battlefield with Pulmonic Sliver in play when the only options should be top of the library or grave.

**Comment by drmDev** [comment]
confirmed test pass. Thanks for your contributions @fwannmacher! You're doing awesome

**Comment by fwannmacher** [comment]
Just doing my part to help the xmage community :-D
