### ISSUE TITLE
Tamiyo bug- drawing extra cards

### ISSUE THREAD

**Issue by deanboyj** [magefree/mage#2109]
Tamiyo's +1 ability applies a buff to a creature that makes them draw cards when they deal combat damage.  However, that application does not appear to be falling off like it is supposed to.  If i apply it to a sylvan advocate twice over  two turns, then when it deals combat it draws 2 cards. The buff never falls off like it is supposed to.

**Comment by deanboyj** [comment]
Note: this is Tamiyo, Field Researcher from Eldrich moon.

**Comment by drmDev** [comment]
fixed with https://github.com/magefree/mage/commit/2ecadbc30b64dc79fec928a2ab707d94f9ec5982 available in next release.
