### ISSUE TITLE
Mind Shatter forces discard when X=0

### ISSUE THREAD

**Issue by skeate** [magefree/mage#2110]
Card is XBB - Target player discards X cards at random. Was cast for BB and I still discarded a card.

**Comment by drmDev** [comment]
Do you have a game log? Cannot duplicate. When you cast Mind Shatter you are first asked to provide a value for X. If you select (1) for X the casting cost becomes {B}{B}{1} and the card is uncastable with just tapping two swamps.  If you select (0) for X, the casting cost is {B}{B} but no cards are discarded by the opponent.

**Comment by skeate** [comment]
[Here's a game log.](http://pastebin.com/bAWFia7b)

and the relevant part in particular:

```html
<font color="#CCCC33">17:40: </font><font color="#20B2AA">SVenssonman</font><font color="White">
plays </font><a href="#Swamp"><font color="#B0C4DE">Swamp</font></a><font color="White">
[ac9]</font>
<font color="#CCCC33">17:40: </font><font color="#20B2AA">SVenssonman</font><font color="White">
announces a value of 0 for <img width="14" height="14" src="file:plugins/images//symbols/small/X.gif" alt="X"></font>
<font color="#CCCC33">17:40: </font><font color="#20B2AA">SVenssonman</font><font color="White">
casts </font><a href="#Mind Shatter"><font color="#696969">Mind Shatter</font></a><font color="White">
[810] targeting </font><font color="#20B2AA">lowpass</font><font color="White">
    </font>
<font color="#CCCC33">17:40: </font><font color="#20B2AA">lowpass</font><font color="White">
discards </font><a href="#Wooded Foothills"><font color="#B0C4DE">Wooded
Foothills</font></a><font color="White"> [781]</font>
<font color="#CCCC33">17:40: </font><font color="#20B2AA">SVenssonman</font><font color="White">
puts </font><a href="#Mind Shatter"><font color="#696969">Mind Shatter</font></a><font color="White">
[810] from stack into his or her graveyard</font>
```

**Comment by drmDev** [comment]
Very odd bug, another log would be helpful. You only having one card in hand shouldn't be relevant, but there may be some weird bug somewhere. With this one if I'm reading the log right he would have only ended up with a Rakdos Guildgate and Swamp in play when he casts Mind Shatter, so it has to be for X=0 (another swamp was played earlier here, but sacrificed as part of Smallpox effect).

**Comment by skeate** [comment]
[Here's the second game with the bug](http://pastebin.com/E54UwmVU) -- same opponent

```html
<font color="#CCCC33">17:54: </font><font color="#20B2AA">SVenssonman</font><font color="White">
announces a value of 0 for <img width="14" height="14" src="file:plugins/images//symbols/small/X.gif" alt="X"></font>
<font color="#CCCC33">17:54: </font><font color="#20B2AA">SVenssonman</font><font color="White">
casts </font><a href="#Mind Shatter"><font color="#696969">Mind Shatter</font></a><font color="White">
[e6e] targeting </font><font color="#20B2AA">lowpass</font><font color="White">
    </font>
<font color="#CCCC33">17:54: </font><font color="#20B2AA">lowpass</font><font color="White">
discards </font><a href="#Windswept Heath"><font color="#B0C4DE">Windswept
Heath</font></a><font color="White"> [e85]</font>
<font color="#CCCC33">17:54: </font><font color="#20B2AA">SVenssonman</font><font color="White">
puts </font><a href="#Mind Shatter"><font color="#696969">Mind Shatter</font></a><font color="White">
[e6e] from stack into his or her graveyard</font>
```

**Comment by drmDev** [comment]
Good catch - bug is reproducable if there is exactly one card in the opponent's hand. Added test for this. Investigating what could be causing this...

**Comment by drmDev** [comment]
Pretty sure I found the issue. In the PlayerImply.discard function, the first check it does includes if the hand size is 1 to just discard that player's hand. It doesn't check ahead of time for the amount of cards to be discarded. So with amount of 0, it still just discards that players entire hand. Now just re-running all the tests to confirm this change doesn't break anything else.

**Comment by drmDev** [comment]
Tests check out fine for this change and bug is fixed with it. Will be available upon next release. Thanks for letting us know and great catch remembering you had exactly 1 card in hand both times! Your opponent likely has been taking advantage of this bug for a while.
