### ISSUE TITLE
Error Reading Config

### ISSUE THREAD

**Issue by Averagesizeman** [magefree/mage#2116]
I Realize this seems to be a common problem, but I promise you I searched high and low for the answer and couldn't find the right answer. 

whenever i open the launcher I get the message:
Reading config from http://xmage.de/xmage/config.json
Error reading config from http://xmage.de/xmage/config.json
Possible causes:  Site is offline or internet connection is unavailable.

Iv tried several different xmage home address but nothing changed, Java is allowed through my firewall, in fact i even turned it off briefly to see if that changed anything but it did not. If anyone can walk me thought a fix i would be very appreciative.
 
edit: my launcher is version 0.3.8 is that an issue? i downloaded it today from the xmage site
Edit 2: So in messing around, if i open "Startmage" in the xmage1.4.13  zip file i can acually open the client, but it wont let me find a server. I can however type in Xmage.de and connect to it, and even play, although the gui seems a bit weird buggy. I Cannot download the images or symbols as i get an error. Is something blocking its ability to fetch the files maybe? or for some reason the client/launcher can't communicate outside itself.  I still cannot open the client via the launcher. Anyone  with a fix I'd appreciate it 

Edit 3: Success!! for anyone with a similar issue, the problem is Java trying to use IPv6 to connect. fix: Open command prompt, right click the top top and go to properties. Enable quick Edit mode
 Paste - (setx _JAVA_OPTIONS -Djava.net.preferIPv4Stack=true) into command prompt with out the () and hit enter. Problem solved.

[/code]

**Comment by drmDev** [comment]
Glad you found out the resolution to your issue! Sometimes it's caused by many things, haven't heard this one yet.
