### ISSUE TITLE
EntersTheBattlefieldTriggerTest possibly wrong?

### ISSUE THREAD

**Issue by fwannmacher** [magefree/mage#2121]
I think the test scenario EntersTheBattlefieldTriggerTest.testCopyNoxiousGhoul is wrong. The playerB's Carnivore Plant should be 1/2 and the playerB's Carnivore Plant should be -1/2. What do you think @drmDev?

**Comment by LevelX2** [comment]
I created that, and true, I was not sure, what's the correct values to check are because I was not sure about how the rules resolve here. 

So it's possible that the checked values are wrong. maybe add some comments and change to the correct values by rule.

**Comment by drmDev** [comment]
I defer to @LevelX2 here, not familiar with that test.
