### ISSUE TITLE
Reality Smasher targetted by spell and copied spell forces 3 cards to be discarded

### ISSUE THREAD

**Issue by drmDev** [magefree/mage#2123]
I've seen this interaction happen before with Pyromancer's Goggles, and we now have a report it has happened with Pyromancer Ascension as well. You should only need to discard two cards from Reality Smasher being targetted twice. I'll try to duplicate it with tests.

See attached for game log
[20160727_210757_Two Player Duel_1.txt](https://github.com/magefree/mage/files/388076/20160727_210757_Two.Player.Duel_1.txt)

**Comment by drmDev** [comment]
I must be missing something - cannot even get the basic tests to work right with Reality Smasher. Like in one of the tests I don't even have a card to discard and set the choice to No but Reality Smasher hits the grave still?!?

see commit 6eb9553e745a85a070f631878514439ce5fe7c59 for tests (take off the Ignore flag when trying to fix them)

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.
