### ISSUE TITLE
Mayor of Avabruck transform ability stays sometimes on the stack after the transformation

### ISSUE THREAD

**Issue by LevelX2** [magefree/mage#213]
![HowlpackAlpha](https://f.cloud.github.com/assets/2066790/435510/cd8dbe38-afe2-11e2-88c6-0fc048f92edb.jpg)

GameLog
8:53 AM Bandit: has joined
8:53 AM HolyHelicopter has joined the game
8:53 AM Bandit has joined the game
8:53 AM game has started
8:53 AM Bandit will start
8:53 AM Bandit draws 7 cards
8:53 AM HolyHelicopter draws 7 cards
8:53 AM Bandit mulligans down to 6 cards
8:53 AM Bandit draws 6 cards
8:53 AM Bandit keeps hand
8:53 AM HolyHelicopter keeps hand
 [Tips] :You may use hot keys to play faster: 
F2 - press Ok, Yes or Done
F4 - skip current turn but stop on declare attackers
F9 - skip everything until you next turn
F3 - undo F4/F9
8:53 AM Turn 1
8:54 AM Bandit plays Hinterland Harbor
8:54 AM Turn 2
8:54 AM HolyHelicopter draws 1 card
8:54 AM Cavern of Souls: HolyHelicopter has chosen Human
8:54 AM HolyHelicopter plays Cavern of Souls
8:54 AM HolyHelicopter casts Experiment One
8:54 AM Turn 3
8:54 AM Bandit draws 1 card
8:54 AM Bandit plays Hinterland Harbor
8:55 AM Bandit casts Avacyn's Pilgrim
8:55 AM Turn 4
8:55 AM HolyHelicopter draws 1 card
8:55 AM HolyHelicopter plays Stomping Ground
8:55 AM HolyHelicopter casts Lightning Mauler
8:56 AM HolyHelicopter attacks with 1 creatures
8:56 AM Turn 5
8:56 AM Bandit draws 1 card
8:56 AM Bandit plays Sunpetal Grove
8:56 AM Bandit casts Avacyn's Pilgrim
8:56 AM Bandit casts Pacifism targeting Experiment One 
8:56 AM Turn 6
8:56 AM HolyHelicopter draws 1 card
8:57 AM HolyHelicopter casts Mayor of Avabruck
8:57 AM HolyHelicopter attacks with 1 creatures
8:57 AM Turn 7
8:57 AM Bandit draws 1 card
8:57 AM Bandit plays Sunpetal Grove
8:57 AM Bandit casts Invisible Stalker
8:57 AM Bandit casts Rancor targeting Invisible Stalker 
8:58 AM Bandit attacks with 0 creatures
8:58 AM Turn 8
8:58 AM HolyHelicopter draws 1 card
8:58 AM HolyHelicopter casts Flinthoof Boar
8:58 AM HolyHelicopter attacks with 2 creatures
8:59 AM Turn 9
8:59 AM Bandit draws 1 card
8:59 AM Bandit attacks with 1 creatures
8:59 AM Turn 10
9:00 AM HolyHelicopter draws 1 card
9:00 AM HolyHelicopter plays Sunpetal Grove
9:00 AM HolyHelicopter casts Experiment One
9:00 AM HolyHelicopter casts Flinthoof Boar
9:00 AM HolyHelicopter attacks with 2 creatures
9:01 AM Turn 11
9:01 AM Bandit draws 1 card
9:01 AM Bandit casts Invisible Stalker
9:01 AM Bandit attacks with 1 creatures
9:02 AM Turn 12
9:02 AM HolyHelicopter draws 1 card

**Comment by emerald000** [comment]
No reports of this bug happening in over a year, so closing.
