### ISSUE TITLE
Identity Thief copying creature with +1/+1 counter gets P/T boost from it, but not counter

### ISSUE THREAD

**Issue by drmDev** [magefree/mage#2131]
Forum report:

"Using Identity Thief:

If I copy a creature with a +1/+1 counter on it, it copies the counter as well as the other stats. This should not be the case."

From my testing (see related test) I'm seeing that the +1/+1 counter itself is not copied, but Identity Thief gets an extra (1) Power and extra (1) Toughness from the copy effect. I'm not sure if this is correct or not.

Put a +1/+1 counter on a 2/3 creature. When copied by Identity Thief, he had 0 +1/+1 counters (good), but the copied creature stats was a 3/4.

There's a lot of rulings here on Thief - most relevant ones quoted below:
http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=414359

"Noncopy effects that have already applied to Identity Thief will continue to apply to it. For example, if Woodcutter’s Grit gave Identity Thief +3/+3 and hexproof earlier in the turn, Identity Thief will still have those bonuses after copying a creature."

"Identity Thief copies the printed values of the targeted creature, plus any copy effects that have been applied to that creature. It won’t copy other effects that have changed the targeted creature’s power, toughness, types, color, or so on. It also won’t copy counters on the targeted creature."

**Comment by emerald000** [comment]
The easiest way to figure out what gets copied is to imagine you place the card you copy in a photocopier. What you get out is what you are copied into. So continuous effects don't apply. Counters don't apply.

In the reported case, you should not copy the counter, and definitely not the power/toughness change it applies. My guess about the cause (without looking at any code), is that the copy effect is done in the wrong layer and is applied after P/T is calculated.
