### ISSUE TITLE
Clever Impersonator entering as an aura

### ISSUE THREAD

**Issue by debook454** [magefree/mage#2135]
When it enters as an aura you cant select a target for it. http://www.mtgsalvation.com/forums/magic-fundamentals/the-rumor-mill/new-card-discussion/rumored-card-rulings/570937-clever-impersonator
I tried to have it enter as a copy of dawn's reflection and it just sits there as a permanent not enchanting anything.

**Comment by drmDev** [comment]
I'll try to write some tests for this shortly

**Comment by drmDev** [comment]
Test confirms it does copy the aura. Will need to test manually to confirm if there is some other issue with how it interacts. May be similar to the issue of enchantments with phasing not appearing to be attached to the permanent anymore.

**Comment by drmDev** [comment]
I misunderstood the original issue. In game testing confirmed issue. It copies Dawn's Reflection but does not ask what to attach it to. Assuming this ruling is correct:
`You may have Clever Impersonator enter the battlefield as an Aura, and if you do, you'll choose a legal permanent that it can become attached to `

http://www.mtgsalvation.com/forums/magic-fundamentals/the-rumor-mill/new-card-discussion/rumored-card-rulings/570937-clever-impersonator

![cleverimp](https://cloud.githubusercontent.com/assets/11060241/23657338/9170febc-030b-11e7-9a5c-c126f33eb206.jpg)

Paging @emerald000  ??

**Comment by emerald000** [comment]
303.4f. If an Aura is entering the battlefield under a player's control by any means other than by resolving as an Aura spell, and the effect putting it onto the battlefield doesn't specify the object or player the Aura will enchant, that player chooses what it will enchant as the Aura enters the battlefield. The player must choose a legal object or player according to the Aura's enchant ability and any other applicable effects.

So yeah, you should choose something to attach it to as it is entering the battlefield.

PS: In your screenshot, the aura should not be staying on the battlefield without being attached to anything. It should go to the graveyard as a SBA. It might help the debug process.

**Comment by drmDev** [comment]
What would I do without you guy? Have to learn to read the rules myself :P

**Comment by debook454** [comment]
Lul the rulings link i attached is so crappy wow im a retard

**Comment by JayDi85** [comment]
Must be fixed by #5261
