### ISSUE TITLE
Counters on permanents appear garbled over time

### ISSUE THREAD

**Issue by drmDev** [magefree/mage#2137]
From reddit thread:
https://www.reddit.com/r/XMage/comments/4vgcgg/counters_on_permanents_dont_seem_to_work/

Whenever in a game of xmage, ad like one player casts a planeswalker (eg Elspeth Knight errant). The loyalty shows 4(nothing wrong here). But when she ticks up, the counter number tries to display the number 4 and 5 simultaneously, so I just see a weird jumbled-number abomination. It get really irritating as the game goes on and i lose track of what permanents have how many counters on them. Is there a fix for this?
Example (an aether vial that just ticked up to three): http://imgur.com/a/g9Ijz

**Comment by drmDev** [comment]
Additionally with many +1/+1 counters the text becomes unreadable:
![cattura](https://cloud.githubusercontent.com/assets/11060241/26762407/c03ac6fc-490f-11e7-8b43-63646d563160.JPG)

**Comment by Zerrisx** [comment]
Used to be an issue, but no longer seems to be; closing as fixed.

![image](https://user-images.githubusercontent.com/59861365/87830127-0b3c7980-c846-11ea-9485-9bcbee090c78.png)
