### ISSUE TITLE
Morph creatures cast face-down are revealed when a counterspell is played

### ISSUE THREAD

**Issue by drmDev** [magefree/mage#2138]
From reddit:
https://www.reddit.com/r/XMage/comments/4vnlus/morph_creatures_bug/

Targeting morph creatures with a counter spell will reveal the name of the creature in the game logs (bottom right section of screen). This was tested with Den Protector and Horribly Awry, but this may apply to other spells as well.

Edit: Just to clarify what happened, the morph creature was put on the stack. I cast Horribly Awry in response, then the game log showed "Username put Horribly Awry onto the stack targeting Den Protector"

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.
