### ISSUE TITLE
After Brisela dies, you cannot cast 3cmc or less spells for the remainder of the game

### ISSUE THREAD

**Issue by Celtic-Spike** [magefree/mage#2140]
if you kill a melded Brisela with the trigger from gilt leaf winnower it still thinks brisela in play. if you attempt to play a 3cmc or less spell it says you cannot because of Brisela

**Comment by drmDev** [comment]
Could you clarify the issue? It sounds like more generally, when Brisela, Voice of Nightmares leaves the battlefield (is killed in this case), you still are unable to cast 3cmc or less spells?

**Comment by Celtic-Spike** [comment]
so the sequence went like this.

Opponent casts Bruna
Gets Gisela from his grave.
goes to end step and meld happens
on my turn i cast gilt leaf winnower and kill brisela with trigger and pass
on opp turn he kills my winnower and plays another Gisela and passes
i have Liliana the last hope and grasp of darkness in hand. When i click
either i get a message along the lines of "you cant cast spells with cmc 3
or less. Brisela"

**Comment by drmDev** [comment]
Clarified title - it is a more general issue. Any time Brisela dies by any means, the opponent remains unable to cast <= 3 CMC spells.

Forum report of same issue "Guys Brisela is bugged..after i killed her, i keep couldn't cast any spell with cc3 or less!!!"

**Comment by drmDev** [comment]
Test added in commit 00b63278596246e1d1723307f8393e588fb1d961

**Comment by drmDev** [comment]
Still getting reports that Brisela's effect is persisting after death:

"Brisela, voice of nightmares even after it was killed it still thought we're all banned from playing 3 cost and under cards and its dead already."

**Comment by drmDev** [comment]
Tests passing now, unable to duplicate issue.
