### ISSUE TITLE
Using Future Sight to cast fused Wear/Tear from top of library crashes

### ISSUE THREAD

**Issue by andyfries** [magefree/mage#2146]
1. Have Future Sight on the battlefield and Wear/Tear on top of library
2. Click Wear/Tear in top of library window to cast
3. Select "Cast fused Wear/Tear"
4. Fuse option disappears, a new dialog appears with only "Destroy target artifact", "Destroy target enchantment", or "Cancel".
5. Select "Cancel"
6. "Game Error" dialog appears with this stack trace:

```
Game exception occurred: java.lang.NullPointerException
Server version: 1.4.13v3
mage.players.PlayerImpl.cast(PlayerImpl.java:1002)
mage.players.PlayerImpl.activateAbility(PlayerImpl.java:1210)
mage.player.human.HumanPlayer.activateAbility(HumanPlayer.java:1234)
mage.player.human.HumanPlayer.activateAbility(HumanPlayer.java:1261)
mage.player.human.HumanPlayer.priority(HumanPlayer.java:704)
mage.game.GameImpl.playPriority(GameImpl.java:1300)
mage.game.turn.Step.priority(Step.java:87)
mage.game.turn.Phase.playStep(Phase.java:210)
mage.game.turn.Phase.play(Phase.java:115)
mage.game.turn.Turn.play(Turn.java:152)
mage.game.GameImpl.playTurn(GameImpl.java:852)
mage.game.GameImpl.play(GameImpl.java:766)
mage.game.GameImpl.start(GameImpl.java:733)
mage.server.game.GameWorker.call(GameWorker.java:60)
java.util.concurrent.FutureTask.run(Unknown Source)
java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
java.lang.Thread.run(Unknown Source)

```

I'm guessing this might be a bug related to Fuse since it stipulates that the spell must be cast from your hand, but Future Sight allows casting it from the top of library. Casting either half individually works as expected.

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.  No longer able to cast with fuse.
