### ISSUE TITLE
Hanweir Garrison bounce before meld gives NullPointerException

### ISSUE THREAD

**Issue by diogovk** [magefree/mage#2161]
How to reproduce:
With Hanweir Garrison and Hanweir Battlements in your control put Hanweir Battlements' ability in the stack to transform(i.e. meld).
In answer to that, return to hand Hanweir Garrison.
Resolve Hanweir Battlements ability.

Expected result:
The ability fizzles.

Actual results:
A NPE error is lauched.

**Comment by LevelX2** [comment]
Fixed beyond 1.4.13v3
