### ISSUE TITLE
Launcher 0.3.8 just starting the old XMage version instread of the new 1.4.14v0

### ISSUE THREAD

**Issue by Deedosera** [magefree/mage#2165]
Since I've updated XMage to 1.4.14v0 the Launcher 0.3.8 doesn't work correctly.
When I press "launch client" in the launcher it somehow starts the old XMage 1.4.13v3, so I'm not able to connect to a server.
Manually I still can start the new XMage 1.4.14v0 running "startClient.bat" and connect to the server as usual.

**Launcher Console:**
_Reading config from http://xmage.de/xmage/config.json
XMage folder:  D:\Spiele\Magic The Gathering - xMage
XMage Launcher version installed:  0.3.8
XMage Launcher version available:  0.3.8
Java version installed:  1.7.0_75
Java version available:  1.7.0_75
XMage version installed:  1.4.14v0 (2016-08-13)
XMage version available:  1.4.14v0 (2016-08-13)_

It shows the right version, but is starting the wrong one. I don't know how to fix this issue, but would be nice if someone know it, since I love to use the Launcher.

**Comment by LevelX2** [comment]
Click update and confirm update. 
Look into the launcher log file, if any problems are reported and post it if any.

**Comment by Deedosera** [comment]
**My issue seems to be solved.**

What I've done:

I've tried to solve the issue by forcing an update yesterday. The launcher downloaded and installed the current version again. But the only change I got was, that the launcher was not starting anything by clicking on "launch client", not even the old version like before.

So I forced a downgrad to the old XMage 1.4.13v3w. Launcher was stil broken and not starting anything.
Than I updated again to current version 1.4.14v0, launcher kept failing.
The _xmage_launcher.log_ had some errors as you can see in the attached log file [xmage_launcher.txt](https://github.com/magefree/mage/files/417121/xmage_launcher.txt)

Today I just did what you said and forced the current update again. Now my launcher works like expected. There are also no errors in the log file.

I don't know if something was changed or if my system was the reason for the issue. Anyway, thanks for the help and all the work on XMage!! I really appreciate it.
