### ISSUE TITLE
UI Tearing randomly

### ISSUE THREAD

**Issue by Fr33dan** [magefree/mage#2166]
I just installed XMage yesterday using the launcher. I had this issue with 1.4.13v3 yesterday and also with 1.4.14 today. The UI randomly glitches and results in a screen that looks like this:
![mangled ui](https://cloud.githubusercontent.com/assets/4670572/17646670/1c4baf3e-61a2-11e6-8bd4-f6b4f2baa27c.png)

Sometimes it pops back in right for a moment but the game is basically unplayable after this has happened. If I restart the client it goes away but I can only play for a match or two before it happens again.

**Comment by drmDev** [comment]
Related to existing issue https://github.com/magefree/mage/issues/1514

See if any of the suggestions there help resolve the issue. Still haven't been able to find a common cause or resolution for these - but something there should help with narrowing it down.

**Comment by Fr33dan** [comment]
That looks much the same as my issue. Sorry I wouldn't have opened a new one had I seen that one.

**Comment by kester13** [comment]
Also same as my issue. The windows are tearing, starting with the previous version - about a few days prior to the 1.4.14 release. Same as the Fr33dan. Appears totally randomly it seems, during game or watching game or even in the tables.

**Comment by drmDev** [comment]
@kester13 see the related issue #1514 for the parent issue where there is discussion on possible causes and resolutions. Comment in there if you find something that helps the issue for you, or if you have similarities between others having the issue (OS, video card, drivers, monitor setup, resolutions, etc)

**Comment by Navyguy330** [comment]
its been worse and worse. and worse. now this new update its like 2 or 3 times PER MATCH.  really annoying.

**Comment by drmDev** [comment]
As this is a duplicate, this will be closed. The parent issue #1514 remains open and has this information included.

**Comment by Navyguy330** [comment]
Actually as it had been fixed in the past,. For some reason the update last
or before last caused it again.  Not sure why.  Nothing really changed in
my end.  The screen tearing is hella annoying
