### ISSUE TITLE
editting xmage in netbeans

### ISSUE THREAD

**Issue by kingbaruk** [magefree/mage#2167]
hey i followed the instructions for cloning xmage to netbeans. But I can't run it and I can't find the build with dependencies button. Whe i try to build it in the usual way i get this error 
/home/wout/NetBeansProjects/mage/JavaProject2/nbproject/build-impl.xml:1034: The following error occurred while executing this line:
/home/wout/NetBeansProjects/mage/JavaProject2/nbproject/build-impl.xml:329: Compile failed; see the compiler error output for details.
can you tell me what to do?

**Comment by Dilnu** [comment]
Hi there, I'm not sure what you mean by build the normal way. What you want to do is to right click on Mage Root and select the Build with Dependencies option. If that isn't present we can follow up with more advice.

**Comment by goesta** [comment]
I'll close this issue because there where no feedback for a long time but feel free to reopen it.
