### ISSUE TITLE
Emrakul extra turn bug

### ISSUE THREAD

**Issue by albuzs** [magefree/mage#2168]
Hello,

If you roll back once or twice during your opponent's controlled turn, the opponent will not get an extra turn for some reason. Has this been reported already?

**Comment by drmDev** [comment]
There are many bugs related to the rollback feature. I'll find the parent
issue for that and add this information to it. This isn't a bug specific to
Emrakul.

**Comment by Zerrisx** [comment]
Duplicate of #2088
