### ISSUE TITLE
CMC issues with Prowl ability and other creatures that reduce cost on field

### ISSUE THREAD

**Issue by drmDev** [magefree/mage#2169]
From forum report:

I attacked with my Goblin Warchief (no blocks) and attempted to cast an Earwig Squad (a Goblin creature) post combat. I chose to pay the prowl cost, and was asked to pay 2B. The correct cost would be 1B.

The appropriate ruling can be found on Frogtosser Banneret.

4/1/2008: The effect reduces the total cost of the spell, regardless of whether you chose to pay additional or alternative costs. For example, if you cast a Rogue spell by paying its prowl cost, Frogtosser Banneret causes that spell to cost {1} less.

**Comment by drmDev** [comment]
Added JUnit tests - don't believe I have it using the Prowl ability correctly in the tests. I mirrored it after how Bestow was used in the tests but that didn't seem to have any effect here. I'll dig a little more into the testing framework later to see if I can find a way to make Prowl work here if there isn't a simple thing I missed here. Or if it's a big feat, just @Ignore the tests for now.

**Comment by drmDev** [comment]
Ignored the tests for now: 9126f06b177019a1588fb287d4366cf81191a532

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.
