### ISSUE TITLE
Soul Separator interaction with Tree of Perdition not working right

### ISSUE THREAD

**Issue by drmDev** [magefree/mage#2174]
from reddit:

I used Soul Separator on my tree of perdition, meaning that the 1/1 spirit token has the ability "tap to exchange an opponent's life total with its toughness", meaning that it should bring the opponent down to 1 life. However, when I activated it, it only brought the opponent to 13 life as if it were regular tree of perdition. I lost the game because of that. :(

**Comment by drmDev** [comment]
I'll try to get a test for this in soon

**Comment by FastTadpole** [comment]
Also had issues when using Soul Separator on Ulamog. It creates a 10/10 spirit token with flying named Ulamog the Ceaseless Hunger along with the 10/10 Zombie.

**Comment by drmDev** [comment]
Added tests confirming the issue. Also commit to fix a couple lines of the test: ea3da9fb12b0a1492e6973439243c4b3ef6ae7e5 

The copy of the token is not properly getting its P/T set, causing the sorts of issues mentioned here where it still behaves as an 0/13 in the case of Tree or as a 10/10 in the case of Ulamog.

**Comment by drmDev** [comment]
Test is passing now, issue was resolved in an earlier commit.
