### ISSUE TITLE
Still having custom cube problems post 1.4.14

### ISSUE THREAD

**Issue by Krebsy** [magefree/mage#2176]
Stuck on the loading screen every time I try to make a custom cube game. I've been using sealed mostly, but it hasn't worked yet. I suppose it could be on my end, but every other sealed set works. Thanks for the support,
Nick.

**Comment by drmDev** [comment]
issue still occurring?

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.
