### ISSUE TITLE
Skinrender interaction with Hangarback Walker issue

### ISSUE THREAD

**Issue by drmDev** [magefree/mage#2181]
From forums:

**+1/+1 counters and -1/-1 counters don't seem to be canceling each other out, as per Rule 121.3. I cast Skinrender, putting 3 -1/-1 counters on a Hangarback Walker with 3 +1/+1 counters on it, but my opponent got 3 Thopters when Hangarback died.**

**Comment by Simown** [comment]
Looks like it's working correctly? If the -1/-1 counters killed it the page at http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=398572 says:

> If enough -1/-1 counters are put on Hangarback Walker at the same time to make its toughness 0 or less, the number of +1/+1 counters on it before it got any -1/-1 counters will be used to determine how many Thopter tokens you get. For example, if there are three +1/+1 counters on Hangarback Walker and it gets four -1/-1 counters, you’ll get three Thopter tokens. That’s because Hangarback Walker’s triggered ability checks the creature’s existence just before it leaves the battlefield, and it still has all those counters on it at that point

**Comment by beady** [comment]
Yeah, this is the correct behaviour. The thing that "cancels" the counters is a state based effect, however as the Hangerback Walker dies at the point where the State based effects are being checked, it looks to see how it was before the State Based effects were applied. In this case, it sees both the +1/+1 counters and the -1/-1 counters.

**Comment by spjspj** [comment]
From the rules, the creatures does die prior to the step in which +1/+1 counters are minused by -1/-1 counters
```
704.5f If a creature has toughness 0 or less, it’s put into its owner’s graveyard. Regeneration can’t replace this event.
......
704.5r If a permanent has both a +1/+1 counter and a -1/-1 counter on it, N +1/+1 and N -1/-1 counters are removed from it, where N is the smaller of the number of +1/+1 and -1/-1 counters on it.
```

**Comment by drmDev** [comment]
Never sure on the rulings, just listing the potential issues reported from the forums. Will update the forum and close this issue.
