### ISSUE TITLE
Mox Diamond not prompting to discard a land on ETB

### ISSUE THREAD

**Issue by drmDev** [magefree/mage#2182]
from forums:

"Opponent said Mox Diamond wasn't prompting him to discard a land - it just resolved and went to graveyard. Haven't confirmed myself."

**Comment by maxlebedev** [comment]
I failed to reproduce this with normal gameplay (with a land in hand). If there are no lands to discard then Mox Diamond does just go to the graveyard.

**Comment by drmDev** [comment]
Unable to confirm issue
