### ISSUE TITLE
Opening the Collection Viewer and Deck Editor breaks the Card Preview

### ISSUE THREAD

**Issue by stravant** [magefree/mage#2186]
Repro steps:
- Open up the deck editor
- Open up the collection viewer
- Go back to the deck editor
- Add a card to deck, and mouse over it
- Card preview pane does not show the hovered card
- Switching to the collection view, you will see that the card preview pane there was updated instead

Expected behavior:
- Each view updates it's own card preview pane.

**Comment by drmDev** [comment]
issue still occurring?

**Comment by stravant** [comment]
Presumably yes. 

When I was working on the card rendering I found out more about this. It stems from the fact that the card preview pane is set at the time of card view creation: When creating a card view you pass in the preview pane to use, and during construction the card view then updates the reference that the global app singleton holds to "what is the current card preview window".

It would probably be inadvisable to fix it without a full re-write of the card preview system, since that code is already a rather ugly tack-on and it would get even more ugly by fixing this without doing it properly.

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.
