### ISSUE TITLE
Adding transform cards for tests transform card on turn 1

### ISSUE THREAD

**Issue by JOAC69** [magefree/mage#2188]
Added Hinterland Logger to test and then executed some actions on turn 1. The card transformed at beginning of upkeep from no spells cast last turn trigger. That trigger should not fire for turn 1.

**Comment by drmDev** [comment]
Putting them directly on the battlefield is not the same as playing the card that turn. I believe what actually is happening with the way you set it up is the card is acting like it was there turn 0. Change the test to casting the card on turn 1 (add 2 forests to the battlefield, and Hinterland Logger to hand then cast it).
