### ISSUE TITLE
Italitization is wrong on the Equip ability

### ISSUE THREAD

**Issue by stravant** [magefree/mage#2190]
The italicization for the Equip ability's reminder text starts after the cost and colon (not including the first parenthesis), but extends until after the second parenthesis. Thus, you end up with:

```
({3}: <i>Attach to target creature ...)</i>
```

Instead of:

```
<i>({3}: Attach to target creature ... )</i>
```

**Comment by ingmargoudt** [comment]
fixed a while ago
