### ISSUE TITLE
Selvala, Explorer Returned's ability should be a mana ability

### ISSUE THREAD

**Issue by spjspj** [magefree/mage#2191]
Currently it's implemented as a SimpleActivatedAbility.  From the rulings though it's meant to be a mana ability.
http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=382357
5/29/2014   Selvala’s parley ability is a mana ability. It doesn’t use the stack and can’t be responded to.

**Comment by cg5-** [comment]
Can XMage deal with this situation from Gatherer rulings?

> If you activate Selvala’s ability while casting a spell, and you discover you can’t produce enough mana to pay that spell’s costs, the spell is reversed. The spell returns to whatever zone you were casting it from. You may reverse other mana abilities you activated while casting the spell, but Selvala’s ability can’t be reversed. Whatever mana that ability produced will be in your mana pool and each player will have drawn a card.

**Comment by Mekkiss** [comment]
Like Chromatic Sphere, xmage can set UndoPossible to false

**Comment by Mekkiss** [comment]
Since the latest update, Selvana's ability is now a mana ability, but it never generates mana or gains life, even when it should...

**Comment by LevelX2** [comment]
> Since the latest update, Selvana's ability is now a mana ability, but it never generates mana or gains life, even when it should...
That's already  fixed for the next update.

**Comment by Mekkiss** [comment]
There's a bug in Selvana at the moment, https://github.com/magefree/mage/blob/master/Mage.Sets/src/mage/cards/s/SelvalaExplorerReturned.java#L63
We can't use SimpleManaAbility as it calls getMana in order to determine getNetMana (which results in revealing the top card of the library). Would be better for getNetMana to return an empty list.
