### ISSUE TITLE
Spy Network card unavailable in deck builder 

### ISSUE THREAD

**Issue by eclectictaboo** [magefree/mage#2192]
![image](https://cloud.githubusercontent.com/assets/4218008/17954392/c74a05ee-6a48-11e6-9ca6-a8271530a709.png)

![image](https://cloud.githubusercontent.com/assets/4218008/17954424/f8838fa4-6a48-11e6-88b9-ad84363ecef2.png)

**Comment by eclectictaboo** [comment]
I run one of these in my U/R EDH deck and cannot seem to find the card when I search for it by name. The card is legal in legacy, multiplayer commander and vintage. http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=39444

**Comment by drmDev** [comment]
All cards are coded individually. Requests for new card implementations go on the official forum thread:
www.slightlymagic.net/forum/viewtopic.php?f=70&t=18876
