### ISSUE TITLE
Doubling Season does not cause double counters on planeswalkers

### ISSUE THREAD

**Issue by malloot** [magefree/mage#2197]
Doubling Season in play should double the counters given by a planeswalker + ability, however it does not. 

![image](https://cloud.githubusercontent.com/assets/10146639/18028438/a620a678-6c7f-11e6-98a7-d8dee416a9b8.png)

had used -1 the turn before to create a token, should have been at 4 after use, it does make 2 tokens when used so that works correctly

**Comment by emerald000** [comment]
No it should not. It doubles the counters if an **effect** should place counters. But activating a planeswalker ability and putting counters is a cost, not an effect.
