### ISSUE TITLE
Impact Tremors damage source should be itself, not the creature ETB

### ISSUE THREAD

**Issue by drmDev** [magefree/mage#2204]
Reported via reddit:

Impact tremors is dealing damage from the creature and as far as I am aware it should be the enchantment itself. Probably largely irrelevant but had a bad interaction today with impact tremors and gratuitous violence dealing 2 damage instead of one.

**Comment by cg5-** [comment]
I looked at gratuitous violence and it seems it doesn't check that the damage source was a creature, so even if Impact Tremors works correctly (which I suspect it does), the damage will still be doubled. I'm going to to reproduce gratuitous violence being broken.

**Comment by cg5-** [comment]
So GV is indeed broken - fix is [here](https://github.com/magefree/mage/pull/2208).

Whether Impact Tremors is broken as well remains to be seen.

**Comment by ImperatorPrime** [comment]
Impact tremors appears to be the source of the damage, not the creature. The GV issue was the root cause.
