### ISSUE TITLE
Rite of Ruin not forcing opponent to sacrifice correctly

### ISSUE THREAD

**Issue by drmDev** [magefree/mage#2210]
Reported from forums:

Rite of Ruin is still completely out of balance in terms of who has to sacrifice what. Selected 1 Artifact, 2 Creatures and 3 Lands. Computer had no artifacts, so nothing to sac there, then sacrificed only 1 of 2 creatures he had and ignored the land sac altogether even though there were more than enough lands to chose from. For me as the spell's controller everything worked as it was supposed to.

(2nd time the user has reported the issue)

**Comment by tcontis** [comment]
I have been unable to replicate this. It seems to have maybe been fixed?
