### ISSUE TITLE
Elemental Mastery's effect is creating wrong tokens

### ISSUE THREAD

**Issue by TechieJunk** [magefree/mage#2214]
It's creating X X/X Elemental tokens (Where X is enchanted creature's toughness), when it should be making X 1/1 Elemental tokens.

**Comment by Tinguely** [comment]
I haven't contributed to this yet, but would love to start. I can take this one if that is ok!

**Comment by LevelX2** [comment]
I had a look at the code. It looks ok for me.
Maybe you can confirm, that the card is working correct.

And checkout this if not already done: https://github.com/magefree/mage/wiki/Developer-Testing-Tools

**Comment by Tinguely** [comment]
Yes, I looked at the code and found nothing wrong I will give it a go and get back to you.
