### ISSUE TITLE
Vesuvan Shapeshifter issues interacting with echo

### ISSUE THREAD

**Issue by Mekkiss** [magefree/mage#2230]
precondition: Have Avalanche Riders on the battlefield.
1. cast Vesuvan Shapeshifter face-up copying Avalanche Riders
2. during your next upkeep, Vesuvan Shapeshifter's "turn face down" ability triggers

Expected behaviour - echo trigger should also occur

**Comment by spjspj** [comment]
Does the echo cost trigger if phyrexian metamorph copies riders?

**Comment by Mekkiss** [comment]
it doesn't appear to, no.

**Comment by elliott-king** [comment]
I am unable to replicate this. Vesuvan Shapeshifter, Phyrexian Metamorph, and Phantasmal Image all work correctly with Avalanche Riders. Perhaps this should be closed? 

My init.txt:

```
hand:Human:Avalanche Riders:1
battlefield:Human:Mountain:4
battlefield:Human:Island:10
hand:Human:Vesuvan Shapeshifter:1
hand:Human:Phantasmal Image:1
hand:Human:Phyrexian Metamorph:1
```

**Comment by drmDev** [comment]
I'll test it myself, and see if it's related to #2864 and whether or not that is still an issue.

**Comment by drmDev** [comment]
Also could not duplicate issue.
