### ISSUE TITLE
developing with jdk 1.8

### ISSUE THREAD

**Issue by ingmargoudt** [magefree/mage#2232]
Hi all,

I recently started digging through the code and make some fixes (see my latest PR), because I am looking for some hobby project in my spare time. I saw that in the dev notes you tell people to use either JDK 1.7 or 1.8, but in the code none of 1.8 functionality is present. I am particularly talking about the use of Optionals, to get rid of null references,  and streams, which make lists and maps so much easier. What are your thoughts of using JDK 1.8 functions? This does require the users to use JRE 1.8 obviously.

**Comment by LevelX2** [comment]
That would need to change the launcher to download the 1.8.x version of Java.
Now 1.7 is still downloaded. So we have to update that first.

There was sometimes a problem with UI client bugs and 1.8 Java.
Didn't had that bug for a longer time but I'm not sure if it's really gone.

**Comment by ingmargoudt** [comment]
So perhaps thats an idea to start working on? Java 1.8 has also a much better memory footprint (better heap management) and a smaller JVM.

**Comment by ingmargoudt** [comment]
Also, regarding performance, I am currently working on my own fork with quite a big overhaul in terms of references, so expect a big PR soon :)

**Comment by Dilnu** [comment]
May I invite you to our Gitter channel? I'd be interested to hear about what you're planning to change.

**Comment by goesta** [comment]
I'll close this issue as we are now using java 1.8 as far as i know.
