### ISSUE TITLE
Omen Machine interaction with Fuse cards results in NPE

### ISSUE THREAD

**Issue by drmDev** [magefree/mage#2233]
from reddit:

Unsure how to contact the devs about this, but when a fuse card is exiled with Omen machine, it can't tell which side, or both, to resolve. Here is the text that comes with it:

ame exception occurred: java.lang.NullPointerException Server version: 1.4.14v0 mage.players.PlayerImpl.cast(PlayerImpl.java:998) mage.sets.newphyrexia.OmenMachineEffect2.apply(OmenMachine.java:131) mage.abilities.AbilityImpl.resolve(AbilityImpl.java:197) mage.abilities.TriggeredAbilityImpl.resolve(TriggeredAbilityImpl.java:100) mage.game.stack.StackAbility.resolve(StackAbility.java:105) mage.game.GameImpl.resolve(GameImpl.java:1370) mage.game.GameImpl.playPriority(GameImpl.java:1321) mage.game.turn.Step.priority(Step.java:87) mage.game.turn.Phase.playStep(Phase.java:210) mage.game.turn.Phase.play(Phase.java:115) mage.game.turn.Turn.play(Turn.java:152) mage.game.GameImpl.playTurn(GameImpl.java:852) mage.game.GameImpl.play(GameImpl.java:766) mage.game.GameImpl.start(GameImpl.java:733) mage.server.game.GameWorker.call(GameWorker.java:60) java.util.concurrent.FutureTask.run(FutureTask.java:266) java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) java.lang.Thread.run(Thread.java:745)

**Comment by Dilnu** [comment]
If a Meld Card is being put into someone's library that's a problem. 

Hopefully this like a number of other Meld edge cases will be handled by the changes I'm working on for the Zone Change code. Also it's odd that any card has a null Spell Ability.

**Comment by emerald000** [comment]
Fuse = split cards like Far // Away.

**Comment by fireshoes** [comment]
Fuse only works when cast from hand, so there should not be an option to do that with Omen Machine. NPE is still valid, but the player should only be able to cast one half of the card.
