### ISSUE TITLE
screen smearing effect.  happens several times per game (even more for a full match)

### ISSUE THREAD

**Issue by Navyguy330** [magefree/mage#2239]
I cannot seem to replicate it on demand., but i know its a known issue with some people, randomly the screen will start smearing and making the game unplayable.  SOMETIMES if you are lucky you can CTRL-ALT-DEL and force close and re open but it is maybe 25% of the time you will not be connected back taking the game loss. 

please fix this.

**Comment by drmDev** [comment]
#1514 duplicate. Information preserved on main ticket.
