### ISSUE TITLE
Randomizer generates the same hands consistently

### ISSUE THREAD

**Issue by Dumeeperninja** [magefree/mage#2245]
This happens for at least commander and limited; it makes x-mage unplayable when you always know the hand you are getting.

**Comment by DelayedEffect** [comment]
I can verify this is happening. I have tried on multiple accounts and different decks.
The draws also remain in the same order until you shuffle again, after which the deck is randomized

This is speculation on my side but I think it may be that the seed used to randomize the shuffle pregame remains the same

**Comment by TheGreenMage14** [comment]
This was also the case for me. I was playing Modern and this same thing happened against separate opponents.

**Comment by Dilnu** [comment]
There was a recent change to the Random generation code. I'm testing a fix but if that doesn't work out I'll revert the changes.

**Comment by LevelX2** [comment]
I released a quick fix d0a570aeeecf6efa52edc73145a0f816a55477c4 that seems at least to handle the problem for deck shuffling.
But maybe there are other problems caused by the change of RND handling e2a479255a91c9fca9aa159cc1e12cb822f7c03c.
