### ISSUE TITLE
new version not opening

### ISSUE THREAD

**Issue by CELTICDADDY77** [magefree/mage#2246]
I have downloaded the new version 1.4.15v0 5 times, each time I click on upgrade on the server, and I get the following error message.

Unable to connect to server. Wrong client version 1.4.15v0,
expecting version 1.4.14v0. Please download needed version
from http://XMage.de or http://www.slightlymagic.net/viewforum.php?f=70

please help me resolve this

**Comment by internetjay** [comment]
I'm having the same issue!

**Comment by LevelX2** [comment]
Woogerworks still on the old version. 
Connect to xmage.de if you like to use the new version now.

**Comment by twogk** [comment]
It works now

**Comment by LevelX2** [comment]
Sure, I updated woogerworks server meanwhile.
