### ISSUE TITLE
Aetherworks Marvel

### ISSUE THREAD

**Issue by bvinson23** [magefree/mage#2255]
The wording for the card Aetherworks Marvel is wrong. Currently on Xmage, it says, "Whenever a permanent goes to the graveyard, gain one energy counter." It should say, "Whenever a permanent you control is put into the graveyard, you get an energy counter." It also triggers twice when the legendary rule is activated for itself.

**Comment by fireshoes** [comment]
I've made the change to controlled permanent instead of any permanent. Triggering twice due to the legend rule sounds correct, as the first copy sees the second one die and the second one sees itself die.

**Comment by albuzs** [comment]
The legend rule works, but yes the wording is wrong. :D

**Comment by LevelX2** [comment]
Fixed with 628b1a65737077cc350d823241273317d5209e97.
