### ISSUE TITLE
just installed newest verison and now i get Java platform SE has stopped???

### ISSUE THREAD

**Issue by Navyguy330** [magefree/mage#2256]
http://prntscr.com/chb4z6

**Comment by Navyguy330** [comment]
lol great job.  thanks for fixing the problem.  



#sarcasm

**Comment by LevelX2** [comment]
What os version you are using?

**Comment by Navyguy330** [comment]
windows 10  all current, legit. all drivers have been up to date long
before error

**Comment by LevelX2** [comment]
Which language version?

**Comment by Navyguy330** [comment]
Um, English lol

**Comment by Navyguy330** [comment]
english

**Comment by Navyguy330** [comment]
the screen smearing has been going on since the last 2 or so updates though but it didnt crash, although the crashing DOES save me a step in having to force close the app to open again

**Comment by LevelX2** [comment]
The screen smearing is not a bug of XMage imho.
It's caused in certain graphic cards / java / screen size combinations I guess.
Maybe also sometimes influenced in a fancy way by by the selected background image.

Did you test to remove / change background image from xmage play ground?

**Comment by Navyguy330** [comment]
Everything is default. And it's new.  It wasn't an issue forever until a
few updates ago,. And since those updates there has not been a driver
update.  So something that was changed in image caused it.  Weather in my
end or not.  It WAS fine and nothing was changed in my end.

**Comment by Navyguy330** [comment]
I also do not get scream smearing in any other program Java or not.

**Comment by Navyguy330** [comment]
http://www.java-forums.org/awt-swing/84779-graphics-smearing-jframe.html

**Comment by Navyguy330** [comment]
https://vue-forums.uit.tufts.edu/posts/list/1446.page

**Comment by Navyguy330** [comment]
can you make sure that it is 64 bit java?  was there a  change?  I use a 64
bit system as much as anyone else does.  perhaps maybe make it so it uses
the java on peoples system rather than some custom version

**Comment by drmDev** [comment]
#1514  duplicate . Information here preserved on main ticket.
