### ISSUE TITLE
why does the launcher show an older version of java when my system has a newer version ?1.8

### ISSUE THREAD

**Issue by Navyguy330** [magefree/mage#2257]

**Comment by Navyguy330** [comment]
get this in the log





Sep 12, 2016 6:43:55 PM java.util.prefs.WindowsPreferences <init>
WARNING: Could not open/create prefs root node Software\JavaSoft\Prefs at root 0x80000002. Windows RegCreateKeyEx(...) returned error code 5.
INFO  2016-09-12 18:43:55,171 Starting MAGE client version 1.4.15v1                                                      =>[main] MageFrame.main 
INFO  2016-09-12 18:43:55,176 Logging level: INFO                                                                        =>[main] MageFrame.main 
ERROR 2016-09-12 18:43:56,721 Couldn't rename mana symbols!                                                              =>[AWT-EventQueue-0] ManaSymbols.renameSymbols 
ERROR 2016-09-12 18:43:56,721 Error for symbol:0                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2016-09-12 18:43:56,721 Error for symbol:1                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2016-09-12 18:43:56,721 Error for symbol:10                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2016-09-12 18:43:56,721 Error for symbol:11                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2016-09-12 18:43:56,721 Error for symbol:12                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2016-09-12 18:43:56,721 Error for symbol:15                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2016-09-12 18:43:56,721 Error for symbol:16                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2016-09-12 18:43:56,721 Error for symbol:2                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2016-09-12 18:43:56,721 Error for symbol:3                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2016-09-12 18:43:56,721 Error for symbol:4                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2016-09-12 18:43:56,726 Error for symbol:5                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2016-09-12 18:43:56,726 Error for symbol:6                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2016-09-12 18:43:56,726 Error for symbol:7                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2016-09-12 18:43:56,726 Error for symbol:8                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2016-09-12 18:43:56,726 Error for symbol:9                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2016-09-12 18:43:56,726 Error for symbol:B                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2016-09-12 18:43:56,726 Error for symbol:BG                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2016-09-12 18:43:56,726 Error for symbol:BR                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2016-09-12 18:43:56,726 Error for symbol:G                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2016-09-12 18:43:56,726 Error for symbol:GU                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2016-09-12 18:43:56,731 Error for symbol:GW                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2016-09-12 18:43:56,731 Error for symbol:R                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2016-09-12 18:43:56,731 Error for symbol:RG                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2016-09-12 18:43:56,731 Error for symbol:RW                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2016-09-12 18:43:56,731 Error for symbol:S                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2016-09-12 18:43:56,731 Error for symbol:T                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2016-09-12 18:43:56,731 Error for symbol:U                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2016-09-12 18:43:56,731 Error for symbol:UB                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2016-09-12 18:43:56,731 Error for symbol:UR                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2016-09-12 18:43:56,731 Error for symbol:W                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2016-09-12 18:43:56,731 Error for symbol:WB                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2016-09-12 18:43:56,731 Error for symbol:WU                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2016-09-12 18:43:56,731 Error for symbol:WP                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2016-09-12 18:43:56,731 Error for symbol:UP                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2016-09-12 18:43:56,731 Error for symbol:BP                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2016-09-12 18:43:56,736 Error for symbol:RP                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2016-09-12 18:43:56,736 Error for symbol:GP                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2016-09-12 18:43:56,736 Error for symbol:X                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2016-09-12 18:43:56,736 Error for symbol:C                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2016-09-12 18:43:56,736 Error for symbol:0                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2016-09-12 18:43:56,736 Error for symbol:1                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2016-09-12 18:43:56,736 Error for symbol:10                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2016-09-12 18:43:56,736 Error for symbol:11                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2016-09-12 18:43:56,736 Error for symbol:12                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2016-09-12 18:43:56,736 Error for symbol:15                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2016-09-12 18:43:56,736 Error for symbol:16                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2016-09-12 18:43:56,736 Error for symbol:2                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2016-09-12 18:43:56,736 Error for symbol:3                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2016-09-12 18:43:56,741 Error for symbol:4                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2016-09-12 18:43:56,741 Error for symbol:5                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2016-09-12 18:43:56,741 Error for symbol:6                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2016-09-12 18:43:56,741 Error for symbol:7                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2016-09-12 18:43:56,741 Error for symbol:8                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2016-09-12 18:43:56,741 Error for symbol:9                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2016-09-12 18:43:56,741 Error for symbol:B                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2016-09-12 18:43:56,741 Error for symbol:BG                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2016-09-12 18:43:56,741 Error for symbol:BR                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2016-09-12 18:43:56,741 Error for symbol:G                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2016-09-12 18:43:56,741 Error for symbol:GU                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2016-09-12 18:43:56,741 Error for symbol:GW                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2016-09-12 18:43:56,741 Error for symbol:R                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2016-09-12 18:43:56,741 Error for symbol:RG                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2016-09-12 18:43:56,746 Error for symbol:RW                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2016-09-12 18:43:56,746 Error for symbol:S                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2016-09-12 18:43:56,746 Error for symbol:T                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2016-09-12 18:43:56,746 Error for symbol:U                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2016-09-12 18:43:56,746 Error for symbol:UB                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2016-09-12 18:43:56,746 Error for symbol:UR                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2016-09-12 18:43:56,746 Error for symbol:W                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2016-09-12 18:43:56,746 Error for symbol:WB                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2016-09-12 18:43:56,746 Error for symbol:WU                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2016-09-12 18:43:56,746 Error for symbol:WP                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2016-09-12 18:43:56,746 Error for symbol:UP                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2016-09-12 18:43:56,746 Error for symbol:BP                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2016-09-12 18:43:56,746 Error for symbol:RP                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2016-09-12 18:43:56,746 Error for symbol:GP                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2016-09-12 18:43:56,746 Error for symbol:X                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2016-09-12 18:43:56,751 Error for symbol:C                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
INFO  2016-09-12 18:43:57,398 Loading plugins...                                                                         =>[AWT-EventQueue-0] Plugins.loadPlugins 
INFO  2016-09-12 18:43:57,468 [Game counter plugin, version 0.1] has been loaded.                                        =>[AWT-EventQueue-0] CounterPluginImpl.newPlugin 
INFO  2016-09-12 18:43:57,483 Done.                                                                                      =>[AWT-EventQueue-0] Plugins.loadPlugins 
INFO  2016-09-12 18:43:58,948 Client start up time: 3 seconds                                                            =>[AWT-EventQueue-0] MageFrame$7.run 
INFO  2016-09-12 18:43:58,958 Trying to connect to XMAGE server at xmage.woogerworks.com:17171                           =>[AWT-EventQueue-0] SessionImpl$5.run 
INFO  2016-09-12 18:43:59,693 Connected to MAGE server at xmage.woogerworks.com:17171                                    =>[AWT-EventQueue-0] SessionImpl$5.run 
INFO  2016-09-12 18:43:59,693 Trying to log-in as Fieldsweeper to XMAGE server at xmage.woogerworks.com:17171            =>[AWT-EventQueue-0] SessionImpl$4.run 
INFO  2016-09-12 18:43:59,955 Logged-in as Fieldsweeper to MAGE server at xmage.woogerworks.com:17171                    =>[AWT-EventQueue-0] SessionImpl$4.run

**Comment by fwannmacher** [comment]
Because XMage downloads its own Java binary.

**Comment by Navyguy330** [comment]
So then why am I getting the Java binary has stopped working error all of a
sudden

**Comment by Navyguy330** [comment]
I can't get thru a single game with it crashing 3 times.  Sometimes even
while I'm at the lobby

**Comment by LevelX2** [comment]
I created a launcher config to use Java 8.
Set your Xmage Home to "http://xmage.de/xmage1.4.15v1J8" in the Launcher to update Java and check if you get any problems using XMage.

**Comment by Navyguy330** [comment]
thanks I will try that.   in the laucnher though the area where xmage home
is- is grayed out??

**Comment by Navyguy330** [comment]
never mind used custom version instead of stable / beta

**Comment by Navyguy330** [comment]
Nope didn't change anything, just got the same crash,  java binary stopped working etc.

**Comment by LevelX2** [comment]
It has something to to with authority of windows registry and the java installation.

http://www.slightlymagic.net/forum/viewtopic.php?f=70&t=17307&p=180956&hilit=Software%5CJavaSoft%5CPrefs#p180956

You user has admin rights as you install java?

**Comment by Navyguy330** [comment]
It does. But the couldn't save prefs never seems to be an issue.

**Comment by LevelX2** [comment]
At least the other errors you post are only the missing symbol files that you can download using the Symbols menu to the top right within xmage.

**Comment by Navyguy330** [comment]
I truely think the propblem arrises from the way the windows are being
drawn or something like that,  it SEEMS to be triggered with weird windows
open, however it CAN happen even when u are just sitting there.

**Comment by Navyguy330** [comment]
OK now it wont even start at all.  I uninstalled java and reinstalled. then tried to upgrade the launcher it took FOREVER and for some reason will not even launcher the actual xmage.

**Comment by Navyguy330** [comment]
ok nevermind, I tried changing the java.exe's to run as admin but I had to change it back. weird.

**Comment by goesta** [comment]
I'll close this issue because it seems to be outdated but feel free to create a new one if this problem still exists.
