### ISSUE TITLE
Cards not Found on Deck Load to Join Game

### ISSUE THREAD

**Issue by FastTadpole** [magefree/mage#2258]
`Server error: Card not found - [CardName - SetName] for deck - [DeckName] Possible reason is, that you use cards in your deck, that are only supported in newer versions of the server. So it can help to use the same card from another set, that's already supported from this server.`

Attempted rebuilding deck from scratch, replacing cards, no resolution.

**Comment by internetjay** [comment]
I'm also having this problem, as are several others in the chatbox and on reddit.  If you remove the offending card it just gives you an error for a different card the next time around, making the program effectively unusable.  Seems like a high-priority issue.

**Comment by LevelX2** [comment]
That can happen if problems/bugs cause memory problems. To fix that the server has to be restarted. That happens automatically with the daily restart or if server maintainer is aware of the problem he can restart the server manually.
