### ISSUE TITLE
An issue about Catch // Release.

### ISSUE THREAD

**Issue by seedds** [magefree/mage#226]
According to Wizards FAQ http://www.wizards.com/magic/magazine/article.aspx?x=mtg/faq/dgm :
If you control an artifact creature, a nonartifact creature, and no other artifacts or creatures, you must sacrifice both permanents. You must choose the artifact creature as the artifact and the nonartifact creature as the creature. The same is true for any combination of types—you sacrifice a number of permanents as close to five as possible.

**Comment by drmDev** [comment]
will test
