### ISSUE TITLE
Error when casting from groups of cards in exile

### ISSUE THREAD

**Issue by twogk** [magefree/mage#2269]
Getting an error that causes the game to roll back when selecting to cast a card from a group of cards in exile.
Current cards I know that can cause this to happen are: Knowledge Pool, Jeleva Nephalia's Scourge, and Narset Enlightened Master.

![new bitmap image 4](https://cloud.githubusercontent.com/assets/22122576/18525630/28a2570e-7a72-11e6-8510-a4651a3ba289.jpg)
![new bitmap image 5](https://cloud.githubusercontent.com/assets/22122576/18525639/2fb608f6-7a72-11e6-83fe-475a3b552297.jpg)

**Comment by twogk** [comment]
May help if I say this only started occurring after the update to 1.4.15v1

**Comment by LevelX2** [comment]
Fixed Knowledge Pool and Jeleva Nephalia's Scourge.
For Narset Enlightened Master I was not able to reproduce a problem.
Any hints how to produce the problem?

**Comment by twogk** [comment]
I'm unsure I saw the guy that I was playing with in the pictures make the comment. Thought I would add it to the list to check/confirm.

**Comment by twogk** [comment]
will there be a hot fix LevelX2?

**Comment by drmDev** [comment]
Issues with Narset were resolved recently (04afceebeb0a029bc48841d77a386cfc268bfdf3) and other cards mentioned were fixed as well.
