### ISSUE TITLE
Position of drawn block / attack arrows does not always fit

### ISSUE THREAD

**Issue by LevelX2** [magefree/mage#2276]
Position of drawn block / attack arrows does not always fit

![blockertargetsposition](https://cloud.githubusercontent.com/assets/2066790/18551804/55989302-7b5a-11e6-8407-6876a35c34e4.jpg)

**Comment by fenhl** [comment]
This is especially noticeable with large board states. Scrolling a player's battlefield does not update the arrows.

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.
