### ISSUE TITLE
Tooltip: Color of white object names not readable

### ISSUE THREAD

**Issue by LevelX2** [magefree/mage#2277]
Tooltip: Color of white object names not readable

![colorofrelatedobject](https://cloud.githubusercontent.com/assets/2066790/18551993/074a7d4a-7b5b-11e6-95ca-3d7b119e1fd0.jpg)

**Comment by stravant** [comment]
Fixed by 274bdfa33f1523ccee0ad2d6cd916f04266b4c4b

As far as I can tell the only place that those colors are used is in that tooltip, so just changing the color shouldn't create a problem somewhere else.
