### ISSUE TITLE
Card rendering: Add little icons for abilities

### ISSUE THREAD

**Issue by LevelX2** [magefree/mage#2278]
I would like to have some small round icons added (best within the image area) that indicate some abilities.

For example useful  would be "Flying" / "Hexproof" / "Haste" / "Trample".

**Comment by stravant** [comment]
I know that Duels of the Planeswalkers does this, but I personally really dislike it (I find it incredibly hard to actually "read" the symbols, at least the ones that DotP uses, it just ends up as noise), and I know other people that don't like it as well.

I'd like to hear some other people echoing that they want this before actually spending time on it. Please comment on whether you like those sort of symbols.

**Comment by LevelX2** [comment]
This would be a good thing that can be switched on/off on preferences.
At least a flyer symbol (wing) would be a good thing and alsp trample (mabe an elephant feet) I would like to have. If cards are below a certain size, the symbols are no longer shown, that's ok.

**Comment by fenhl** [comment]
The wiki has [an incomplete list](http://mtgsalvation.gamepedia.com/Category:Magic_keyword_images) of the images used by Duels.

**Comment by JayDi85** [comment]
Card icons implemented by #7467
