### ISSUE TITLE
 JAVA(TM) Platform SE binary has stopped working. 

### ISSUE THREAD

**Issue by Endymione** [magefree/mage#2291]
Good Evening,

Unfortunately I am having some issues with Xmage where after 5 minutes into any aspect of  Xmage be it an offline game, online game, or making decks the program will throw me back a JAVA(TM) Platform SE binary has stopped working error. 

Info: 

[Client Console Dump.txt](https://github.com/magefree/mage/files/477493/Client.Console.Dump.txt)

![image](https://cloud.githubusercontent.com/assets/22244730/18597625/b4cbc690-7c46-11e6-8489-5deb85dedf5b.png)

![image](https://cloud.githubusercontent.com/assets/22244730/18597671/eb0a3fa2-7c46-11e6-8ed1-e97ce3655b00.png)

![image](https://cloud.githubusercontent.com/assets/22244730/18597719/1e6bb484-7c47-11e6-8fc4-239dc51ddb87.png)

Any help you could offer would be a kindness. I'd love to be able to get back into playing some day soon.

Kind Regards,

Endymione

**Comment by Mirarn** [comment]
have the same problem any ide how to fix it?

**Comment by LevelX2** [comment]
Does it help or change something if you raise the memory given to XMage in the XMage Launcher Setting / Java, say to 1 GB?

**Comment by Endymione** [comment]
Seems to be working fine on the most recent patch, during the time when I had the issue changing the launcher settings up to 1gb didn't seem to effect it in the slightest. 

Kind regards,

Endymione
