### ISSUE TITLE
Noticed some missing Promo cards 

### ISSUE THREAD

**Issue by spjspj** [magefree/mage#2301]
In particular the Judge Reward Lands (Plains, Island, Swamp, Mountain, Forest) by Therese N.   Possibly some other ones that exist on http://magiccards.info/ don't exist as code in xmage.  Going through them all and matching them up to non existing ones in xmage should be fun ;)

**Comment by fireshoes** [comment]
The Terese Nielsen lands are in already implemented. Should be under jr/judge promos.

**Comment by spjspj** [comment]
oh, cool, I didn't notice them in the collection or in the code but will look again!!

**Comment by JayDi85** [comment]
No more actual. XMage's cards database synced with scryfall database (aka mtgjson). All missing promo cards implemented in PR #6190.
