### ISSUE TITLE
Unable to create IntelliJ running configurations

### ISSUE THREAD

**Issue by jorgep19** [magefree/mage#2314]
I was following the [Developer Getting Started Wiki](https://github.com/magefree/mage/wiki/Developer-Getting-Started), but when trying to setup the server configuration the `Mage.Server` is not listed as a module for this reason I'm unable to make `mage.server.Main` my Main class without getting a `ClassNotFoundException`.

Below the step from the Wiki:

>  **Running server and client** 
>  Pick 'Application' from the popup and name it 'Run Server'. Set mage.server.Main as the Main class. Click the '...' button next to Working directory and choose the root of the Mage.Server directory. Then, select mage-server from the Use classpath of module dropdown.

**Comment by Dilnu** [comment]
Yeah, so the wiki works or doesn't work depending on weird config issues. Some people seem to make things work just doing what the wiki said. I personally had to replace make with maven in the before launch tasks. WD: Mage.Server Command: install

**Comment by ingmargoudt** [comment]
In order to run in IntelliJ, I had to do a Maven build of the Root project, this will compile the proto dependencies.

**Comment by Simown** [comment]
I had this problem in IntelliJ a few months ago, not had the problem recently though. How I fixed it was to:

- Maven clean build the project (mvn clean install -DskipTests)
- File > Project Structure
- Select mage.server
- Add jar or directory
- Add xmage.jar from xmage/Mage/target

**Comment by goesta** [comment]
I setup my dev environment last week using the latest version of the guide.
I'll close this issue because it seems that the guide was updated since you postet the issue but feel free to reopen or create a new one if the problem still exists.
