### ISSUE TITLE
kaladesh forest1.java has wrong id

### ISSUE THREAD

**Issue by xmageForger** [magefree/mage#2319]
mage.sets.kaladesh/forest1.java has ID 261.  Should be 264

**Comment by spjspj** [comment]
thanks :) - I think this is the random forest coming up in decks bug people are mentioning

**Comment by spjspj** [comment]
fixed by #2322

**Comment by xmageForger** [comment]
No problem.  Happy to help.  Once I figure out GIT I will start making these changes myself.
