### ISSUE TITLE
Panharmonicon - Triggering for all players, not just controller of panharmonicon.

### ISSUE THREAD

**Issue by spjspj** [magefree/mage#2333]
Someone mentioned in chat that Panharmonicon (http://media.wizards.com/2016/bVvMNuiu2i_KLD/en_BNCoE3UEk8.png
) was triggering for opponents as well.

**Comment by fenhl** [comment]
If I'm reading the code right, it's not replacing the trigger event, but the etb event itself.

**Comment by FastTadpole** [comment]
I can confirm this is the behaviour when I was playtesting. Every triggered event for each player was replicated by Panharmonicon.

**Comment by emerald000** [comment]
Fixed with 120d7612f625662796f75c1647193709041549b2.
