### ISSUE TITLE
Constant crashes with 1.4.15v4 update

### ISSUE THREAD

**Issue by shaithan** [magefree/mage#2338]
I have totaly removed and reinstaled/downloaded Xmage 3 times within 24hours of lunch of 1.4.15v4 and it just keep on crashing, Stability issues has to be resolved

**Comment by albuzs** [comment]
error is with pretty much all cards... do we need to wait for a server reset?

**Comment by goesta** [comment]
I'll close this issue because it seems to be outdated but feel free to create a new one if this problem still exists.
