### ISSUE TITLE
Card Images Download Transactions

### ISSUE THREAD

**Issue by kiosso** [magefree/mage#2339]
This is an enhancement request.  Please inform me if this request is incorrectly formatted or can otherwise be made to work better for you.  

I am reinstalling xmage after not having used it for a few years.  

When I start the client, it wants to load the card images.  As discussed elsewhere, this takes approximately forever.  The program loads some number of thousands of images from magiccards.info until the computer shuts down from being idle for hours.  When I restart the client it starts downloading all the images, not just the remainder.  

I imagine that the card image database could be updated periodically to remember some of the previously downloaded cards to save time and allow the process to complete even though interrupted.

**Comment by spjspj** [comment]
It does this already.  It touches each file on your computer with a '-e' to see if it exists.  It will only attempt to download cards that aren't present.  Check your images directory to see if it downloaded any images.

**Comment by kiosso** [comment]
So there should be a file in the images directory for each card?  I see zip files for sets.  I changed the power saving settings on my computer so the image download could complete without power down, disk shut-off.  
The down load ran for over 12 hours before stalling at the point in the attached screenshot.  It's been like this for over 7 hours now.  I assume I need to kill the client and start over.  If I do, I'm pretty sure it will start downloading the cards from scratch.  
Now there are populated zip files for many sets, but no standard sets more recent than KTK. I have KTK open in the screenshot. 
![xmageimgdwnld](https://cloud.githubusercontent.com/assets/5104740/18673258/f9b6ec2e-7eff-11e6-88aa-e47f626e2153.png)

What do you advise?

**Comment by JayDi85** [comment]
Need to close that issue. In 2017 version all works fine:
 - download process continue after client restart (download only missing images);
 - also you can select sets to download.
