### ISSUE TITLE
Thousand year elixir does not enable Q: abilities to be used

### ISSUE THREAD

**Issue by Mekkiss** [magefree/mage#2349]
With Thousand Year Elixir in play, creatures with summoning sickness should be allowed to use abilities with the Untap symbol in them.

702.10c. If a creature has haste, its controller can activate its activated abilities whose cost includes the tap symbol or the untap symbol even if that creature hasn’t been controlled by that player continuously since his or her most recent turn began. (See rule 302.6.)

**Comment by LevelX2** [comment]
And this does not work, when the permanent with the {Q} ability is tappped?
I guess it has to be tapped.

**Comment by Mekkiss** [comment]
Correct. Even when the permanent is tapped, it can't be used.
