### ISSUE TITLE
Suggestion: More Player Interactions

### ISSUE THREAD

**Issue by Slimmo90** [magefree/mage#235]
1. The ability to "whisper" to players, which means basicly sending private messages and when a private message is sent to a player and that player does not have the MAGE client as the active window (tabbed out) the game flashes (just like when you have to do something during a duel and you are tabbed out).
2. Players in the player-list should have a status next to their name so you know exacly what their doing. For example "status texts" could be: Playing Game, Watching Game, AFK, Viewing Deck Editor. This would help other player so they know what their doing.
3. Creating private games that does not show in the game list or not simply able to join the game without an invitation from the host.

If you already are planning on putting these in the new client or something then thats cool but I put these up just in case :)

**Comment by goesta** [comment]
I'll close this issue because it's really old ;) and mostly implemented.
