### ISSUE TITLE
Can't use launcher

### ISSUE THREAD

**Issue by Horadrik** [magefree/mage#2350]
I'm having the issue with ''Xmage not found'' when I try to install xmage on my desktop, and if I try to execute the launcher from my Program Files that's what happens:
![xmage issue](https://cloud.githubusercontent.com/assets/22301244/18692117/74dbd892-7f6e-11e6-829d-b064cdb27ea1.jpg)

**Comment by goesta** [comment]
I'll close this issue because it seems to be outdated but feel free to create a new one if this problem still exists.
