### ISSUE TITLE
Game state freeze on Leovold, Emissary of Trest and Spirit of the Labrynth

### ISSUE THREAD

**Issue by marthinwurer** [magefree/mage#2360]
Leovold entered the battlefield, cast by AP. Spirit was on the battlefield controlled by Non-active player. AP selected done, game froze from both sides. AP attempted to concede, game logged concession, and did not close the game.

**Comment by LevelX2** [comment]
Sounds like a network problem caused game freeze.
Checked the code of Leovold, Emissary of Trest and did some cleanup, but there was no game stopping problem.
