### ISSUE TITLE
Costs involving {Q} are paid at the wrong time

### ISSUE THREAD

**Issue by Mekkiss** [magefree/mage#2383]
When announcing an ability that contains {Q}, the permanent in question untaps before mana is required to be paid.

Steps to reproduce:
1. Have Pili-pala, tapped, on the battlefield
2. Announce Pili-pala's ability

Result:
Pili-pala is untapped, you are prompted to pay {2}

Expected result:
Pili-pala is tapped, you are prompted to pay {2}. After paying {2}, Pili-pala should untap.

see:

601.2g. If the total cost includes a mana payment, the player then has a chance to activate mana abilities (see rule 605, “Mana Abilities”). Mana abilities must be activated before costs are paid.
601.2h. The player pays the total cost in any order.

**Comment by zsedcx22** [comment]
I don't see the problem, the untap is also part of the cost.

**Comment by Mekkiss** [comment]
The problem is that you are able to tap the permanent to provide mana to pay for the Q ability.

For instance, if you had a Springleaf Drum in play, you could use it and the Pili-Pala to pay for the {2} mana that Pili-Pala's Q ability requires.

**Comment by zsedcx22** [comment]
Ooooh, right, my bad.

**Comment by JayDi85** [comment]
Actual issue in #8003
