### ISSUE TITLE
Kaladesh booster generated without a rare

### ISSUE THREAD

**Issue by emerald000** [magefree/mage#2385]
![Booster](http://i.imgur.com/kE3Ym5Z.jpg)

**Comment by LevelX2** [comment]
Was not able to reproduce that problem yet.

**Comment by Simown** [comment]
Can't reproduce it either. Generated ~10000 Kaladesh boosters and each had either a Mythic or a Rare. I'll look in to it a bit more this weekend.

**Comment by Zerrisx** [comment]
Haven't seen or heard reports of this since in four years, closing as cannot reproduce.
