### ISSUE TITLE
Champion + bounce bug

### ISSUE THREAD

**Issue by skeate** [magefree/mage#2394]
Unless my interpretation of the rules is incorrect, the following should work: 
1. Play a creature with the Champion mechanic (e.g. Wren's Run Packmaster)
2. In response to the trigger, return the creature to your hand (e.g. with Wirewood Symbiote)
3. Choose not to exile another creature in response to the trigger. 

The creature should remain in your hand, since it can't be sacrificed anymore. I attempted this in a game and the game made me discard the WRP.

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.
