### ISSUE TITLE
New deck editor - observations

### ISSUE THREAD

**Issue by LevelX2** [magefree/mage#2407]
The new editor is a very great and shiny improvement of XMage.  Thanks for that piece of work.
I will gather here some observations what can be still improved.

Enhancements
- [x]  Would be nice if the current layout is saved and reloaded with the dck file.
- [ ] Filters that work on top of the hide mechanism (filter out all R/G/B for example).
- [x] Cumulative selection (have a card selected and then add more things to the selection by holding down shift + box or similar drawing a box with mouse)
- [x] You can't load deck variants during sideboarding, The button is not available if server is not in test mode.
- [x] Cards hidden during draft are also hidden as the deck edior opens after draft.
- [x] Need a good way to mass-add basic lands to a constructed deck now, since some people used the now gone list view for that.
- [x] An easy way to add multiple of one card to deck editor from pool (say 4/10 of Basic land). Or in deck build mode change directly the number of included cards (e.g. by right mouse menu item?).
- [x] How can we see the night side of a card in the deck editor?

Problems
- [x]  Missing sort by Color Identity and Card type.
- [x] The image quality in the card frame is worse (a lot) than the image of the complete card.
- [x] The card size selected is reset as the card editor reopens the next time during a match.
- [x] If window width is set to minimal size, buttons and sizer slider overlay each other. (Sort of fixed: Made the elements less likely to overlap, but Swing doesn't really offer a true elegant solution here)
- [x] Divider bar position is not saved. Position is always again rest to default next time.
- [x] Enlarged view sluggish / not working.
- [x] If I have two columns, I can't select the whole of column 2 and more it to column 3 (to have col 1, gap, col 3) (WONTFIX)

**Comment by stravant** [comment]
> Would be nice if the current layout is saved and reloaded with the dck file.

Can I add that to the file format? If so it's not too hard to add.

> You can simply load decks in between sideboarding phase of a match and play with the loaded deck.

Elaborate? Isn't that a desirable feature? (That you can save a sideboard configuration for a given matchup ahead of time and load it in rather than sideboarding manually for instance)

> The card size selected is reset as the card editor reopens the next time during a match.

The card size is simply a temporary modifier on top of the card size selected in the preferences. Do you think I should make the slider directly tied to the preference instead or save the slider value separately rather than just having it be a temporary adjust?

> Divider bar position is not saved. Position is always again rest to default next time.

Which one. Didn't they always do that?

**Comment by LevelX2** [comment]
> Elaborate? Isn't that a desirable feature? (That you can save a sideboard configuration for a given matchup ahead of time and load it in rather than sideboarding manually for instance)

No, you may not be allowed to change your card pool within a match. You may switch cards between main deck and sideboard.

**Comment by LevelX2** [comment]
> Can I add that new data to the file format? Or would you use a new file format? Recommendations? If so it's not too hard to add.

Sure, you can add it e.g. as some kind of special comment that includes the x,y position of the pile.
#pile 3,6
[card ref1]
[card ref2]
#pile 3,7
[card ref3]
[card ref4]
...

> Divider bar position is not saved. Position is always again rest to default next time.

No the positions of some (or most ) divider bars are saved and reused as the function is called again.

> The card size is simply a temporary modifier on top of the card size selected in the preferences. Do you think I should make the slider directly tied to the preference instead or save the slider value separately rather than just having it be a temporary adjust?

I would save it separately.

**Comment by spjspj** [comment]
- Add lands in the new deck builder seems slightly broken - it tried to make it up to 60 cards for a draft (40 card) deck. 
- Lacking filter (but that may just be in deck editor for draft?) 
- Doesn't have cumulative selection (have a card selected and then add more things to the selection by holding down shift + box or similar drawing a box with mouse)
- basic lands added in draft appeared to be added to the Sideboard instead of the main board
- if I have two columns, I can't select the whole of column 2 and more it to column 3 (to have col 1, gap, col 3)

**Comment by fireshoes** [comment]
Some symbol errors came up while in the deck editor. It didn't show in the client log right away, but appeared when loading my third deck.

`ERROR 2016-10-03 13:16:06,234 Error for symbol:WP                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2016-10-03 13:16:06,235 Error for symbol:UP                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2016-10-03 13:16:06,240 Error for symbol:BP                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2016-10-03 13:16:06,242 Error for symbol:RP                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2016-10-03 13:16:06,244 Error for symbol:GP                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2016-10-03 13:16:06,248 Error for symbol:C                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2016-10-03 13:16:06,249 Error for symbol:E                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages `

**Comment by stravant** [comment]
> if I have two columns, I can't select the whole of column 2 and more it to column 3 (to have col 1, gap, col 3)

This is probably a wontfix. If columns don't go away when empty, it introduces a new problem: How do you delete columns? MTGO just doesn't allow you to delete columns, so you have to manually pick up each stack of cards an move them over one at a time. I think that the insert-between-columns and delete empty columns approach is better though. I expect that most people will like it in the end, and it's mostly just being different than MTGO that makes it stick out at first.

**Comment by LevelX2** [comment]
Are the cards already hidden during the draft automatically hidden if the draft ends and the deck editor opens?

**Comment by stravant** [comment]
Fixed most of these issues.

* Still trying to decide exactly how to handle saving the card size slider. Various different views use the Drag & Drop card grid in different ways, and they all need to save it separately... probably? Or not? I'm not sure what would be ideal.

* Still undecided on if I want to add a filter. I'm leaning towards not (due to it being confusing combined with show/hide and not really necessary) and see how much people complain, but I already have some of the code for it if deemed necessary.

* Still need to make the draft view use the new drag & drop view / system. Currently it's only used in in the deck editor itself (for deckbuilding / sideboarding). 

> Some symbol errors came up while in the deck editor. It didn't show in the client log right away, but appeared when loading my third deck.

Also threw in a fix to this one. It wasn't actually related to the deck editor itself, but a problem with Gatherer being missing some symbols+sizes that we were trying to use.

**Comment by spjspj** [comment]
Has the new deck editor lost the ability to go to list (vs graphic display) mode?  This was handy for say adjusting the number of basics in your constructed decks to get the exact same land and increase it by say 2.

**Comment by stravant** [comment]
I didn't include it for simplicity of implementation (The code to enable both would have gotten extremely hairy once I start adding more complex concepts like hiding cards to the editor, and how to handle stuff like where cards should end up when you switch to list view, make edits, and switch back is pretty ugly)

> Has the new deck editor lost the ability to go to list (vs graphic display) mode? This was handy for say adjusting the number of basics in your constructed decks to get the exact same land and increase it by say 2.

As far as I can tell the *only* good reasons to use the list view were deficiencies of the old visual editor, which have been remedied. For the adding a lot of a basic land case I think that a better way to handle it. I could add a right click drop down "add 4 to maindeck / add 10 to maindeck" option to the Collection view entries to solve that case.

**Comment by LevelX2** [comment]
Concerning the hide/filter controversy:
Does hiding cards make really sense during constructed deck building? So during constructed deck building I wouldn't need filter nor hide functionality.
For me hiding makes most sense during the drafting, where I can't divide yet between sideboard and deck.
Also the filter I would not need for the deck area. Only for the pool area (= sideboard of sealed and draft decks).

**Comment by LevelX2** [comment]
Another thing I noticed. The enlarged view (mouse wheel down/up) while mouse pointer is located over a card image does not correctly work in the new deck editor. It needs sometimes a  very long time to show. Shows sometimes the wrong card or does not open at all.

**Comment by LevelX2** [comment]
After some testing the deck editor I got this error and cards in the pool are no longer shown correctly.
Pool was filtered on the Star Wars set, that includes transformable cards.
```
FATAL 2016-10-04 14:06:58,735 MAGE Client UI error                                                                       =>[AWT-EventQueue-0] EDTExceptionHandler.handle 
java.lang.NullPointerException
	at mage.client.util.TransformedImageCache.getRotatedResizedImage(TransformedImageCache.java:127)
	at mage.client.util.TransformedImageCache.getResizedImage(TransformedImageCache.java:119)
	at mage.client.util.ImageHelper.getResizedImage(ImageHelper.java:144)
	at org.mage.card.arcane.ManaSymbols.loadSymbolsImages(ManaSymbols.java:159)
	at org.mage.card.arcane.ManaSymbols.draw(ManaSymbols.java:219)
	at org.mage.card.arcane.ModernCardRenderer.drawBasicManaTextbox(ModernCardRenderer.java:830)
	at org.mage.card.arcane.ModernCardRenderer.drawRulesText(ModernCardRenderer.java:779)
	at org.mage.card.arcane.ModernCardRenderer.drawFrame(ModernCardRenderer.java:494)
	at org.mage.card.arcane.CardRenderer.draw(CardRenderer.java:206)
	at org.mage.card.arcane.CardPanelRenderImpl.renderCard(CardPanelRenderImpl.java:290)
	at org.mage.card.arcane.CardPanelRenderImpl.paintCard(CardPanelRenderImpl.java:259)
	at org.mage.card.arcane.CardPanel.paintComponent(CardPanel.java:354)
	at javax.swing.JComponent.paint(JComponent.java:1056)
	at org.mage.card.arcane.CardPanel.paint(CardPanel.java:346)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JLayeredPane.paint(JLayeredPane.java:586)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JViewport.paint(JViewport.java:728)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JSplitPane.paintChildren(JSplitPane.java:1047)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
```

**Comment by fireshoes** [comment]
For draft, can we just add the sideboard to the draft itself and drag unwanted cards over there, like how mtgo does it? Then no need to bother with the hiding at all.

**Comment by spjspj** [comment]
@stravant Try adding another land of the same art as you have in a deck at the moment - it's actually relatively painful with the current way.  Maybe a right click / duplicate option over the card or selected cards in the main board itself?  With the duplicate option being turned off for a fixed pool of cards?

**Comment by LevelX2** [comment]
During sideboarding, the diver bar is always set again to the most possible lower position. So probably some people will complain that thex can't access there sideboard, because they will not get aware that they have to pull the divider bar up.

**Comment by cg5-** [comment]
[So some people on /r/xmage really want the list view back.](https://www.reddit.com/r/XMage/comments/56gfgm/new_deck_editor/)

I did notice that the graphic view is useless if you have characteristic based rendering off and you turned off the option to display the card name.

**Comment by spjspj** [comment]
I'm thinking of doing something similar to the following:
http://i.imgur.com/8Jd0GYp.png
(New stuff mocked up in bottom right).  To basically analyse what's in the deck and be able to cumulatively select/de-select based on types.

**Comment by LevelX2** [comment]
Deactivating the enlarged view (activated with mous wheel spinning) while in deck editor (to allow panel scrolling) is no good solution in my opinion. I do all the time turn the mouse wheel to get the enlarged image in the deck editor.

**Comment by Mekkiss** [comment]
I would like to see an option to show only unique cards, so that one does not need to scroll down eighty different printings of Island.

**Comment by JayDi85** [comment]
All improves were made for deck editor. So no more actual.
