### ISSUE TITLE
Emeria Shepherd + Bruna, the Fading Light

### ISSUE THREAD

**Issue by B1zmark** [magefree/mage#2409]
Emeria Shepherd can't bounce Bruna to the table when a plains enters the battlefield.

**Comment by drmDev** [comment]
will test...

**Comment by Nightelfpala** [comment]
I can confirm this bug.
Steps to reproduce:
1. Emeria Shepard on the battlefield, Bruna, the Fading Light in my graveyard
2. Play basic Plains from hand (did not test with non-Plains lands)
3. Attempt to select Bruna with the Landfall trigger - it doesn't work, the trigger doesn't target the card, it's still waiting for a target to be chosen.
However, I could choose Implement of Improvement and Gisela, the Broken Blade.

If I remember correctly, this interaction worked properly around the release of AER, but I'm not 100% sure on this one.

**Comment by drmDev** [comment]
Added unit test - unable to duplicate with UT. Will need to test in game to confirm issue.

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.
