### ISSUE TITLE
[Implementing cards] - predicates and in-game text issues

### ISSUE THREAD

**Issue by Galatolol** [magefree/mage#2416]
I love XMage and I'd like to contribute to it, so I went through wiki articles for developers and coded five simple cards. After testing them on local server I realized that predicates don't work for me (I hope that's the right place to post such problems).

For example, an Aura called Conclave's Blessing ("Enchanted creature gets +0/+2 for each other creature you control.") in game gives +0/+2 for each creature you control (as though AnotherPredicate didn't work) and upon hovering it reads only "Enchanted creature gets +0/+2."

Code fragment:

```
    private static final FilterControlledCreaturePermanent filter = new FilterControlledCreaturePermanent("other creature you control");

    static {  filter.add(new AnotherPredicate()); }       /* ... */

        PermanentsOnBattlefieldCount value = new PermanentsOnBattlefieldCount(filter, 2);
        this.addAbility(new SimpleStaticAbility(Zone.BATTLEFIELD, new BoostEnchantedEffect(new StaticValue(0), value, Duration.WhileOnBattlefield)));

```

Two other cards with ColorPredicate don't care about color (both in text and in effects).

Auriok Siege Sled has two abilities concerning artifact creatures. They both work correctly but the in-game text of the first one lacks the word "artifact". The second one's doesn't. Of course filter is the same.

Do you have any idea why this happens?

**Comment by LevelX2** [comment]
> and upon hovering it reads only "Enchanted creature gets +0/+2."

You need to use the 
effect.setText("blah...");
to set a special text.

> as though AnotherPredicate didn't work

AnotherPredicate() filters out the sourceId object from the source ability. That's the enchantment, so all other creatures are counted.
You need an AnotherEnchantedPredicate. I added that predicate just now.
