### ISSUE TITLE
Myriad making too many copies of creatures

### ISSUE THREAD

**Issue by spjspj** [magefree/mage#2420]
Playing edh - only two opponents left but Herald of the host still made two copies.

![things19](https://cloud.githubusercontent.com/assets/16917728/19041128/95f1c4a6-89d2-11e6-8845-13e4cede0547.png)

**Comment by LevelX2** [comment]
Did the player die just during that turn or already before that turn?

**Comment by LevelX2** [comment]
Only logical cause could be, that the defending player was not returned from the combat method.
That would exactly lead to that problem. Added logger message for that case.

**Comment by spjspj** [comment]
@LevelX2 He died in the turn before my turn

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.
