### ISSUE TITLE
Overloaded Cyclonic Rift - waiting for opponent whose session expired

### ISSUE THREAD

**Issue by spjspj** [magefree/mage#2423]
![things21](https://cloud.githubusercontent.com/assets/16917728/19077207/631efd1c-8a97-11e6-8f60-4ae9584515c6.png)

**Comment by spjspj** [comment]
I can attempt to look at :)

**Comment by spjspj** [comment]
After the 10 minutes expired, there was the same thing (waiting).  Something about expired sessions vs just opponents who have conceded possibly.

**Comment by spjspj** [comment]
Not having much luck with recreating this.  I changed the boot function from the 'Mage Server Console' to instead Expire a session, did so in a 3-way match for a human but the same behaviour didn't occur on overloading rift.

**Comment by fireshoes** [comment]
I think it is something in general with a player leaving the game. I posted one in the forums about a conceded player's Confusion in the Ranks continuing to trigger.

**Comment by spjspj** [comment]
Got this again
When the dude just leaves (doesn't concede) leads to the issue it seems like.

**Comment by Zerrisx** [comment]
Duplicate of #4262
