### ISSUE TITLE
-2/-2 of collective brutality doesn't work

### ISSUE THREAD

**Issue by MartoEporedia** [magefree/mage#2437]
Hi,

i've an issue with collective brutality, the -2/-2 doesn't work and no kill the creatures.

Thanks

**Comment by fireshoes** [comment]
Fixed beyond 1.4.15v5.

**Comment by MartoEporedia** [comment]
This is the versions of client and server, but it doesn't work.
![xmage_ver](https://cloud.githubusercontent.com/assets/1846455/19190699/4a093ff4-8c9f-11e6-923f-e002e5158e8c.png)

**Comment by LevelX2** [comment]
Beyond

**Comment by MartoEporedia** [comment]
Ops, sorry :)

Thanks
