### ISSUE TITLE
Can't update

### ISSUE THREAD

**Issue by Navyguy330** [magefree/mage#2442]
Can't update, when I open the launcher it tells me there is a new version, I click update and it downloads but right after it says installing it says version installed (old version) and that I get a pop up saying new version available.

**Comment by fireshoes** [comment]
Did you try it since version 1.4.16v0 was released? My launcher had not been updating since 1.4.15v2, but it did successfully update with 16v0 this morning.

**Comment by Navyguy330** [comment]
Not sure what you mean. I open the launcher and it says new version
available.  It downloads it then pops the window up again still saying
there's an update available and that I have the old version. (tried
connecting and I definitely do have the older version

**Comment by spjspj** [comment]
An alternative way (if you're looking for it @Navyguy330):
Download direct from here: http://bit.ly/xmage_1_4_16v0o 
http://www.slightlymagic.net/forum/viewtopic.php?f=70&t=19248&p=203489#p203489 << This is the notification of release by LevelX2 
Then unzip the 120MB .jar file and run the 'startClient.bat' script under 'mage-client'

**Comment by slovenhjelm** [comment]
have had this issue since last patch. tried so many fixes and nothing works. gg xmage.

**Comment by goesta** [comment]
I'll close this issue because it seems to be outdated but feel free to create a new issue if this problem still exists.
