### ISSUE TITLE
Transformable cards can no longer turned over to the other side

### ISSUE THREAD

**Issue by LevelX2** [magefree/mage#2444]
Transformable cards can no longer turned over to the other side in deck editor by pushing the night/day button.
Image does not change.  By second click the animation freezes.

**Comment by cg5-** [comment]
Collection viewer has the same problem.

**Comment by JayDi85** [comment]
Now it turns fine by night/day button, fixed via 2f66e168ab90d88b9462612638fc9f119100debd
