### ISSUE TITLE
xmage not found

### ISSUE THREAD

**Issue by bmchafa** [magefree/mage#2445]
I cant get xmage to launch please help 

xmage launcher version installed 0.3.8
xmage launcher version available 0.3.8
java version installed _______ (...weird cuz i have the latest version of java installed)
java version available 1.8.0_102
java not found
xmage version installed  _______ (...weird cuz i was just playing xmage 4 hrs ago)
xmage version avaiable 1.4.16v2
removing previous versions...
dowloading java from...
installing xmage.....
xmage version installed....
xmage version available 1.4.16v2
xmage not found

**Comment by bmchafa** [comment]
I tried downloading the update directly from bit.ly two times. no dice
when i try to open the compressed file its says "...xmagevblahblah.zip is invalid"

**Comment by SilPiber** [comment]
I have the same problem and didn't find any solution :(

**Comment by bmchafa** [comment]
what solutions have you tried?

**Comment by LevelX2** [comment]
Added another primary download source. Give it a new try to update.

**Comment by bmchafa** [comment]
Properties > Unblock > fixed 

BC

**Comment by goesta** [comment]
I'll close this issue as it seems to be fixed but feel free to reopen it.
