### ISSUE TITLE
Infinite loop Snapcaster Mage

### ISSUE THREAD

**Issue by Raytek** [magefree/mage#2447]
I was testing a deck against the machine and when the AI uses the Flashback effect of Snapcaster Mage the program enters an infinite loop by not solving ability.

[Print Screen](https://drive.google.com/file/d/0B5do0k0jxYpTLVdtYmxGeTdnOEE/view?usp=sharing)

Sorry I used google translator.

**Comment by jborden** [comment]
I've had this exact same problem. The computer can play surprisingly strong with a  UW control deck but gets stuck in an infinite loop when choosing a card to flashback with Snapcaster mage. Please fix.
