### ISSUE TITLE
Images getting lost after update

### ISSUE THREAD

**Issue by albuzs** [magefree/mage#2449]
Hello,

After the most recent update, some of the older images got deleted. I have tried downloading all the images, but (most notably) the UNH basic land set will not come up.

Is there anything I can do on my end to make the images come up again?

**Comment by albuzs** [comment]
Any idea how to download the lost images? UNH still can't be downloaded... I can't even see the wastes from OGW

**Comment by spjspj** [comment]
albuzs - For a very (very) manual-ish way of downloading images directly - https://www.reddit.com/r/XMage/comments/4vg6cu/very_manual_download_of_images/:
The Download.bat file (can be broken into multiple parts and kicked off simultaneously):
http://www.filedropper.com/downloadimages  <<< Batch file that downloads GatherererID .jpg  to SET/Card Name.full.jpg
http://www.filedropper.com/cut   << Perl program

**Comment by goesta** [comment]
I'll close this issue because there where no feedback for a long time but feel free to create a new one if this is still a problem.
