### ISSUE TITLE
Angel of Jubilation prevents sacrifice of all kind of permanents instead of only creatures

### ISSUE THREAD

**Issue by LevelX2** [magefree/mage#245]
[Angel of Jubilation](http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=240120) prevents sacrificing of all kind of permanents instead of only creatures.
i.e. Horizon Canopy cant't be sacrificed if the Angel is on the battlefield.

**Comment by drmDev** [comment]
Issue still occurs. 

Needs to have more customized rule changing effects:

         for (Player player : game.getPlayers().values()) {
            player.setCanPayLifeCost(false);
            player.setCanPaySacrificeCost(false);
        }

**Comment by ImperatorPrime** [comment]
I should have a first pass at this in the next few days.

**Comment by ImperatorPrime** [comment]
Fixed by 43205b6f46e2031797ea6088e00d56bd02e2608c. I think my test suite covered everything.
