### ISSUE TITLE
Incorrect Rarities in Star Wars set

### ISSUE THREAD

**Issue by spjspj** [magefree/mage#2452]
The rarity in brackets at the end is the rarity indicated on the set symbol on the card (which I'm assuming is canon?)
- [x] Moisture Farm - Rare (Uncommon)
- [x]  Jedi Enclave - Uncommon (common)
- [x]  Smash to Smithereens - Common (Uncommon)
- [x]  Sith marauder - common (Uncommon)
- [x]  Rumor monger - common (Uncommon)
- [x]  Lightning bolt - common (Uncommon)
- [x]  Gundark- common (Uncommon)
- [x]  Force Scream- common (Uncommon)
- [x]  Zam Wessel (???) - (rare)
- [x]  No contest (???) - (common)
- [x]  Bib Fortuna - Uncommon (Rare)
- [x] Repair (reminder text in popup) has a typo - 'beggining' vs 'beginning'
- [x] Dark Decision: One can’t cast the exiled card (at least not by clicking on it in the exiled zone as one usually would).
- [x] Force Adapt: Can’t be cast, period. Opens a large error window.
- [x] Cloaking Device: Gives the enchanted creature unblockable but not does seem to lead to life loss as it is supposed to.
- [x] Capture: Cost in-game is (R) instead of the actual (2)(R).
- [x] Gungan Captain: Cost in-game is (3)(U) instead of the actual (2)(U).
- [x] Trade Federation Battleship: Is treated in-game as a 2/2 instead of 0/6.
- [x] Force Scream: Is treated as Instant despite being a Sorcery.
- [x] Force Lightning: Is treated as Instant despite being a Sorcery.
- [x] Battle Tactics: Is treated as Instant despite being a Sorcery.
- [x] Sith Marauder: Its Hate ability doesn’t trigger off of Vapor Snag (not sure which of the two is bugged).
- [x] Exogorth: Rule text is not clear; typo? Might or might not work as intended in-game.
- [x] Rumor Monger: Not really a bug but can someone clarify whether or not the bounty counter in question can be shifted from the dying creature? Or just from one of the remaining ones to another remaining one?

**Comment by spjspj** [comment]
Could custom sets allow cards otherwise not illegal in pauper become legal if they were at common in a new custom set where they were always uncommon or above in actual MTG sets?

**Comment by LevelX2** [comment]
> Rumor Monger: Not really a bug but can someone clarify whether or not the bounty counter in question can be shifted from the dying creature? Or just from one of the remaining ones to another remaining one?

Because dies means "is put into a graveyard from the battlefield" the dying creature is no longer on the battlefield but was put into the graveyard as the targets for the triggered abilities have to be selected. So IMHO it's not possible to move the counter from the dying creature.
