### ISSUE TITLE
Server Config Gets Set to Default When Updating

### ISSUE THREAD

**Issue by reverendj1** [magefree/mage#2453]
Just started using XMage last week, and with each update over the weekend, the config.xml was replaced with the default. I'm not 100% sure, but I believe the DB with wins/losses/rankings/etc for the server was overwritten as well. Is that expected behavior, and I should just know to back these up and copy them over when deploying an update, or is this a bug? I didn't see it mentioned in the server setup thread (http://www.slightlymagic.net/forum/viewtopic.php?f=70&t=15898&sid=dedc3681d4894470d9608e8bd3b06e37).

**Comment by Zerrisx** [comment]
Has this been resolved?

**Comment by JayDi85** [comment]
That's correct behaviour. Config changed to default after update. Reason: config contains all decks/modes/tourneys lists and users can't add it manually after each update.
