### ISSUE TITLE
Returning to your hand a creature you own but is controlled by an opponent doesn't let you replay it.

### ISSUE THREAD

**Issue by jgalrito-i9** [magefree/mage#2460]
Happened after I Aether Tradewinded my Rashmi that an opponent cast with Gonti, Lord of Luxury (the exile part could have something to do with this?). Then on my turn I couldn't replay it.

This might be a general case since a spectator on our game told us something similar had happened to him in an EDH game (with other cards I assume).

**Comment by spjspj** [comment]
I think I had the same thing with a PW Karn that entered under opponent's control, then got bounced by venser back to my hand where I couldn't cast it for the rest of the game.
