### ISSUE TITLE
Suggestions not Bugs

### ISSUE THREAD

**Issue by DrizzleRaine** [magefree/mage#2461]
First, I would like a list view or a button to toggle between list view and card view in the deck editor. I hate making a deck with card view.
Second, can you please hide all star wars or other cards from all other cards besides when a star wars block  / set is selected to view.
Third, a no-chat client so it's safe and would only display gameplay messages while another player uses a chat client or the no-chat client, it could be possibly a no chat version getting ready for android

**Comment by LevelX2** [comment]
> First, I would like a list view or a button to toggle between list view and card view in the deck editor. I hate making a deck with card view.

Will see.

> Second, can you please hide all star wars or other cards from all other cards besides when a star wars block / set is selected to view.

You can set the set filter to Vintage/Legacy to get only all non custom cards.

> Third, a no-chat client so it's safe and would only display gameplay messages while another player uses a chat client or the no-chat client, it could be possibly a no chat version getting ready for android

I guess I don't get the sense of that.

**Comment by goesta** [comment]
Thanks for your feedback but ill close this issue because it addresses multiple things. But feel free to continue the discussion or open a new issue for the deck editor improvement.
