### ISSUE TITLE
Possible NPE?

### ISSUE THREAD

**Issue by fireshoes** [magefree/mage#2463]
As I was choosing the cards to put on the bottom of my library with Glint-Nest Crane, the client froze up like I was going to be disconnected. After some lag, it continued asking me to put the cards on the bottom. I did, but the message stayed and I was unable to continue the game.

My client log showed this, indicating the game had been ended, but it was still the same game:
INFO  2016-10-13 13:29:06,710 Game aabf7bf5-fb82-491d-97e2-2c1b293a483a started for player f559cdfd-de9c-4941-a81f-354bc8ac8fc9 =>[AWT-EventQueue-0] CallbackClientImpl.gameStarted 
INFO  2016-10-13 13:33:33,275 Ending game...                                                                             =>[pool-7-thread-1] FeedbackPanel$1.run 
INFO  2016-10-13 13:34:28,917 Game 89b35a74-5c9a-4548-9d6e-82c27ae2056f started for player f559cdfd-de9c-4941-a81f-354bc8ac8fc9 =>[AWT-EventQueue-0] CallbackClientImpl.gameStarted

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.
