### ISSUE TITLE
FilterCreatureCard is constructed with "a creature..." instead of "creature" for some cards

### ISSUE THREAD

**Issue by wendelscardua** [magefree/mage#2476]
I noticed it when Recruiter of the Guard ability text on the stack said "(...) you may search your library for **a a** creature card with toughness 2 or less (...)"

Searching on Github reveals FilterCreatureCard is used both with "creature" and "a creature".

On the other hand, maybe the constructor should always receive "a creature" instead of adding the "a" automatically (to prevent problems with "a/an").

**Comment by ImperatorPrime** [comment]
Based on some looking around, I think we need a getMessageIndefiniteArticle for it to be consistently correct for different cases. 

For example "Whenever {this} or another " filter.getMessage + " dies" requires no indefinite article, whereas a lot of other cases (like recruiter and stoneforge) need the indefinite article.

If there is no issue with adding the indefinite article function, I'll take care of the issue.

**Comment by awjackson** [comment]
`addArticle` was added to CardUtil.java some time ago, so I'm closing this.
