### ISSUE TITLE
Mtgo's You Make the Cube 

### ISSUE THREAD

**Issue by spjspj** [magefree/mage#2480]
- [ ] [Mark of Eviction](https://www.google.com.au/search?q=intext:"Mark+of+Eviction"+mtg&source=lnms&tbm=isch)
- [ ] [Opal Titan](https://www.google.com.au/search?q=intext:"Opal+Titan+-+spjspj+working+on"+mtg&source=lnms&tbm=isch)
- [ ] [Temporal Aperture](https://www.google.com.au/search?q=intext:"Temporal+Aperture"+mtg&source=lnms&tbm=isch)
- [ ] [Tombstone Stairwell](https://www.google.com.au/search?q=intext:"Tombstone+Stairwell"+mtg&source=lnms&tbm=isch)
- [ ] [Ballot Broker](https://www.google.com.au/search?q=intext:"Ballot+Broker"+mtg&source=lnms&tbm=isch)
- [x] [Evangalize](https://www.google.com.au/search?q=intext:"Evangalize"+mtg&source=lnms&tbm=isch)

**Comment by Zerrisx** [comment]
The only unimplemented card on here - ballot broker - is tracked elsewhere in #2206.  Closing as fixed/duplicate.
