### ISSUE TITLE
[Bug] Daretti, Ingenious Iconoclast

### ISSUE THREAD

**Issue by synergize** [magefree/mage#2490]
Daretti's -1 ability for the card reads "You may sacrifice an artifact. If you do, destroy target artifact or creature." The card within XMage is leaving out the or clause and doesn't allow them to destroy non-artifact creatures. His ultimate also reads to create three copies of an artifact in the graveyard but the in-game version doesn't call it out.

**Comment by Simown** [comment]
Should be fixed already by commit 5009c2c14982e015deb5dc205e456b0798c5276 which will be available in the next release.
