### ISSUE TITLE
'Frontier' in Deck Editor doesn't show m15 cards.

### ISSUE THREAD

**Issue by PAK90** [magefree/mage#2495]
Building a Frontier deck, wanted to include Elvish Mystic and it didn't show up in the search with the format set to 'Extended'.

**Comment by fireshoes** [comment]
I can see Elvish Mystic when I filter by Extended, but not when I filter by Frontier, if that is what you mean. That is a new bug since the last release. It is not affecting M15 for Frontier deck legality, so it is a problem only with the deck editor.

**Comment by Plopman** [comment]
Fixed with 712565562e058493c31c4ac1899d9a0526905103
