### ISSUE TITLE
In EDH, when Brisela changes zones and Bruna is your commander, you don't get option to move Bruna to command zone

### ISSUE THREAD

**Issue by ghost** [magefree/mage#2502]
Didn't test it if the same happens when Gisela is commander, but I expect it to be the same.

**Comment by LevelX2** [comment]
712.4d If a melded permanent moves to another zone, both cards move to that zone. If multiple replacement effects could be applied to the zone change, applying one to one of the two cards affects both cards. If the melded permanent is a commander, it may be exempt from this rule; see rule 903.9a.

903.9. If a commander would be exiled from anywhere or put into its owner’s hand, graveyard, or library from anywhere, its owner may put it into the command zone instead. This replacement effect may apply more than once to the same event. This is an exception to rule 614.5.

903.9a If a commander is a melded permanent and its owner chooses to put it into the command zone this way, that permanent and the card representing it that isn’t a commander are put into the appropriate zone, and the card that represents it and is a commander is put into the command zone.

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.
