### ISSUE TITLE
Need a 'Pimp my deck' button

### ISSUE THREAD

**Issue by spjspj** [magefree/mage#2507]
Should go and upgrade all cards in a deck to the equivalent promo card (MGDC, PTC, APAC, EURO, JR etc)

**Comment by xenob8** [comment]
pf, signed foiled jappo/russian/korean card pls

**Comment by spjspj** [comment]
Given xmage has exclusively English cards at the moment, please feel free to contribute to the development of allowing foreign language cards in!

**Comment by spjspj** [comment]
Done hopefully with a4275ab6581d9db69294c677d7de408aa9c1ad97
