### ISSUE TITLE
[bug] Trading Post: Mode 3 exiles creature instead of putting in gy

### ISSUE THREAD

**Issue by arloft** [magefree/mage#2545]
When you activate Trading Post's #3 mode (1, tap, sacrifice a creature: return target noncreature artifact from your graveyard to your hand) it *exiles* the creature sacrificed instead of putting it in the graveyard.

Playtesting a deck in EDH: Activated Trading Post's Mode 3 (on my turn). Selected target artifact in graveyard, paid mana cost, selected creature on battlefield to be sacrificed. Xmage moved the sac'ed creature into Exile.

![trading post mode 3 exile bug screenshot]
(https://cloud.githubusercontent.com/assets/2423302/19907904/3d82399a-a057-11e6-8d02-0cccf3943202.png)

**Comment by LevelX2** [comment]
The AI has Anafenza, the Foremost in play that has the following static ability:
If a creature card would be put into an opponent's graveyard from anywhere, exile it instead.

Seems to me correct behaviour.
