### ISSUE TITLE
Clever Impersonator bug

### ISSUE THREAD

**Issue by DaLosar** [magefree/mage#2565]
I copied an Ephara, God of the Polis (http://magiccards.info/bng/en/145.html) that was on enchantment and belonged to an opponent using my Clever Impersonator (http://magiccards.info/ktk/en/34.html), however my impersonator didn't copy the triggered ability, so I drew no cards with my Ephara's copy the whole game. The impersonator did become an indestructible creature once my devotion was enough, though.

On a side note on the same day an opponent had a similar issue using Clone on another card, perhaps it might be related?

**Comment by LevelX2** [comment]
If you know the other card, please post it.

**Comment by LevelX2** [comment]
Fixed.
