### ISSUE TITLE
Bloodchief Ascension BUG

### ISSUE THREAD

**Issue by mjpirez** [magefree/mage#2566]
The text is rendered incorrect.

First ability should trigger each end step but is triggering only on controller's end step.

version 1.4.17V0

**Comment by LevelX2** [comment]
Can't reproduce a problem with the trigger nor the rule text.

**Comment by mjpirez** [comment]
For the rule text I have evidence, see attached.

But I figured out why it was "not working". I was trying to deal damage on the end of the opponent's turn. If I deal damage in the second main phase it triggers.

Sorry for the inconvenience.

<img width="516" alt="screen shot 2016-11-09 at 22 50 31" src="https://cloud.githubusercontent.com/assets/8882813/20160745/787fc51a-a6d0-11e6-8709-cbd32859fabf.png">
