### ISSUE TITLE
Heritage Druid should be able to tap Prowess of the Fair

### ISSUE THREAD

**Issue by skeate** [magefree/mage#2576]
Seems like it's expecting a creature, specifically: https://github.com/magefree/mage/blob/6f96ec5be542f4ff1c9f414ba1520f36c87d931c/Mage.Sets/src/mage/cards/h/HeritageDruid.java#L66

**Comment by use** [comment]
I think this can be closed? Not sure of the procedure.

https://github.com/magefree/mage/commit/0996a4d549a0661afb87753fb69270c2d2fc254d
