### ISSUE TITLE
Sidar Kondo typo

### ISSUE THREAD

**Issue by Scott-Crawford** [magefree/mage#2589]
In xmage, the card says creatures with power 2 or greater. It should be 2 or less.

**Comment by Scott-Crawford** [comment]
I think the correction should just be to this, but I'm not sure.

private static final FilterCreaturePermanent filter = new FilterCreaturePermanent("creatures with power 2 or less");

    static {
        filter.add(new PowerPredicate(Filter.ComparisonType.LessThan, 3));
    }

**Comment by spjspj** [comment]
Thanks.  Fixed with 12f046230030078e1550bb20052af843ae23c009
