### ISSUE TITLE
Doubling Cube does not double Cavern of Souls mana

### ISSUE THREAD

**Issue by fenhl** [magefree/mage#2598]
Activating [Doubling Cube](https://mtg.wtf/card/10e/321)'s mana ability does not double the special mana produced by [Cavern of Souls](https://mtg.wtf/card/avr/226).

The way it should work is that the abilitty simply adds mana with the same type (that being its color or lack thereof) as whatever is currently in your mana pool, but does not copy any restrictions or associated effects.

**Comment by ingmargoudt** [comment]
Fixed in #b0a6c76
