### ISSUE TITLE
Aluren allows Hypergenesis to be cast for free at instant speed.

### ISSUE THREAD

**Issue by andrew-todaro** [magefree/mage#2601]
Aluren, when on the field, is allowing Hypergenesis, a sorcery that can only be cast via suspension, to be cast for free any time the player could cast an instant. Aluren, for reference, should only allow creatures that cost less than 3 to be cast at instant speed. While this is only a guess, Aluren may need to be re-worked to check card type before cost; the card not actually having a proper mana cost may be causing a bug where the rest of the checks do not occur.

**Comment by Dilnu** [comment]
So it looks like the issue isn't specific to Aluren. I can also reproduce this with Kentaro, the Smiling Cat. I'm trying to look more closely into the issue.
