### ISSUE TITLE
march of the machines + Liquimetal coating combo

### ISSUE THREAD

**Issue by Otherheaven** [magefree/mage#2614]
Hi guys! 
I tried this combo on xmage but for some reason is not working on lands.
When i target with Liquimetal coating a land, it will become an Artifact creature land with power 0/0.
Am i wrong? or there's a bug with the combo?

**Comment by JRHerlehy** [comment]
Yes, lands should end up in their owners graveyard as a SBA when Liquimetal Coating targets them with March of the Machines out.  It appears that they currently do not get a P/T

**Comment by Dilnu** [comment]
Could one of you document more through repro steps? I just wrote up two more test cases for the March of the Machines Unit Test and they both pass.



```
    @Test
    public void testLandIsDestroyed() {
        addCard(Zone.BATTLEFIELD, playerA, "Island", 4);
        addCard(Zone.BATTLEFIELD, playerA, "Darksteel Citadel");
        addCard(Zone.HAND, playerA, "March of the Machines");

        castSpell(1, PhaseStep.PRECOMBAT_MAIN, playerA, "March of the Machines");

        setStopAt(1, PhaseStep.BEGIN_COMBAT);
        execute();

        assertPermanentCount(playerA, "Darksteel Citadel", 0);
        assertGraveyardCount(playerA, "Darksteel Citadel", 1);
    }


    @Test
    public void testLiquimetalCoatingLandIsDestroyed() {
        addCard(Zone.BATTLEFIELD, playerA, "Island", 4);
        addCard(Zone.BATTLEFIELD, playerA, "Forest");
        addCard(Zone.BATTLEFIELD, playerA, "Liquimetal Coating");
        addCard(Zone.HAND, playerA, "March of the Machines");

        castSpell(1, PhaseStep.PRECOMBAT_MAIN, playerA, "March of the Machines");
        activateAbility(1, PhaseStep.PRECOMBAT_MAIN, playerA, "{T}: Target permanent", "Forest");

        setStopAt(1, PhaseStep.BEGIN_COMBAT);
        execute();

        assertPermanentCount(playerA, "Forest", 0);
        assertGraveyardCount(playerA, "Forest", 1);
    }
```

**Comment by JRHerlehy** [comment]
The test cases seem to work even though it doesn't work in the game.
![lmc fail](https://cloud.githubusercontent.com/assets/5979124/20498019/5bdbc0bc-afe0-11e6-9dba-a91ffdb68ec1.jpg)

The Liquimetal Coating is animated, but targeting the island never gets it assigned a P/T and sent to the graveyard.

**Comment by JRHerlehy** [comment]
So after testing further, something that is an artifact interacts correctly with March of the Machines.  Also, something that is turned into an Artifact BEFORE March of the Machines enters the battlefield will interact correctly.  But once it stops being an artifact at EOT, it does not interact correctly again.

Seems to be a layers application issue with dependent abilities?

**Comment by Otherheaven** [comment]
I dont speak english very well. I just want to report it. If i can help with anything, i should be glad to do it!

**Comment by Dilnu** [comment]
Alright, after reading what you said and fiddling around a bit this test will reproduce the issue:
```
@Test
    public void testLiquimetalCoatingLandIsDestroyed() {
        addCard(Zone.BATTLEFIELD, playerA, "Island", 4);
        addCard(Zone.BATTLEFIELD, playerA, "Forest");
        addCard(Zone.BATTLEFIELD, playerA, "Liquimetal Coating");
        addCard(Zone.HAND, playerA, "March of the Machines");

        castSpell(1, PhaseStep.PRECOMBAT_MAIN, playerA, "March of the Machines");
        activateAbility(2, PhaseStep.PRECOMBAT_MAIN, playerA, "{T}: Target permanent", "Forest");

        setStopAt(2, PhaseStep.BEGIN_COMBAT);
        execute();

        assertPermanentCount(playerA, "Forest", 0);
        assertGraveyardCount(playerA, "Forest", 1);
    }
```
