### ISSUE TITLE
Divergent Transformations's exile effect not working right

### ISSUE THREAD

**Issue by JoshCrow1980** [magefree/mage#2625]
Divergent Transformations is supposed to exile two targets creatures and then it hunts for replacement creatures from the controller's library for each exiled creature. The second part works fine (replacement creatures appear as they should), but the original exile does something odd - it leaves the targeted creatures on the field (despite putting copies into exile). It was a little strange to see the same creatures in the exile pile and still on the field.

**Comment by jeffwadsworth** [comment]
This works fine in my testing.

**Comment by drmDev** [comment]
Unable to duplicate with manual or UT, closing. re-open if able to reproduce and have log or can confirm with test.
