### ISSUE TITLE
Clones of animated artifacts handled incorrectly

### ISSUE THREAD

**Issue by Mekkiss** [magefree/mage#2644]
Steps to reproduce:

Have Sol Ring on the battlefield
Use Tezzeret, Agent of Bolas to animate Sol Ring
Cast Clone, copying Sol Ring

Expected result: Clone enters the battlefield as an unanimated Sol ring.
Actual behaviour: Clone enters the battlefield as a 0/0 Sol Ring artifact creature that is put into the graveyard as an SBA.

This seems to have only started in 1.4.19V0.

**Comment by JRHerlehy** [comment]
I am unable to reproduce this following the scenario you provided. Do you have further documentation of the issue?

**Comment by MTGfan** [comment]
I'm also not able to reproduce using the scenario described.

**Comment by goesta** [comment]
I'll close this issue because it seems to be outdated but feel free to create a new one if this problem still exists.
