### ISSUE TITLE
Chat filter is too strict

### ISSUE THREAD

**Issue by fenhl** [magefree/mage#2650]
Messages containing the phrase “cumulative upkeep” are not being sent.

**Comment by JRHerlehy** [comment]
The regex string is looking for "cum" without filtering out if it is part of a larger word.

So the fix would be, what, '\bcum\b'?

**Comment by fenhl** [comment]
That would be a step in the right direction. Other things we could do to make the filter less annoying:

* Tell users why their messages are not being sent
* Replace the filtered word with stars instead of not sending the message at all
* Disable the chat filter in password-protected rooms
* Allow users to opt out of the filter (letting them see the original message)

**Comment by spjspj** [comment]
Fenhl - Which version are you using?  The filter specifically doesn't look at game log messages. 
* People can still whisper whatever they like as well
I'd argue that xmage isn't a democracy and I don't want whatever things some annoying person happens to feel like saying wrecking the civility of the chat which goes to 400+ people at times. I really haven't seen anyone in the actual chat annoyed that they can't be berated in a fashion that the person would probably be arrested for if they did it in public in the presence of a police officer.

Anyway, the 'Cumulative upkeep' comes through ok and isn't filtered (at least in test mode)  (image modified to reduce size..)
![image](https://cloud.githubusercontent.com/assets/16917728/20859063/3629d92c-b9a8-11e6-82ea-83d15df9915b.png)

**Comment by fenhl** [comment]
I am using 1.4.19V0. And I am not talking about the game log, I am talking about the chat. Try saying “cumulative upkeep” in the game chat; the message will simply not be sent. It will appear to be lost just like when the chat was having delay issues. Except now the message just never arrives.

I don't know what you're trying to argue for when you say that XMage “isn't a democracy” etc, but I'm fairly sure I wouldn't want to live in a jurisdiction where I can't talk about the Magic rules in a polite fashion with someone who has expressed interest in the topic. Implementing any of the 4 things I suggested would allow me to do this, but right now the various chat rooms are pretty much unusable because random messages will be filtered out with no indication whatsoever that the filtering was intentional and not caused by another network/memory error, or which word it was that triggered the filter.

**Comment by spjspj** [comment]
Fenhl - we are in furious agreement with regards to wanting polite conversation.  My 7yo son often wants to look at what's happening on the computer and I really don't want him exposed to whatever horribleness someone is spewing forth.  
* You can still whisper without it being filtered if it's a single person.  
* I think an underlying enhancement is being able to broadcast to a group of friends (or even having the concept of friends in xmage). 

I'll add the change suggested by JRHerlehy and put a word boundary around the shorter 3-letter words in the list.  I'd argue that it's fairly obvious which words would cause the filter to stop it being sent through.

**Comment by fenhl** [comment]
> I'll note that you can still whisper without it being filtered if it's intended to go to a single person.

This is unnecessarily complicated, especially in multiplayer games.

> I'd argue that it's fairly obvious which words would cause the filter to stop it being sent through.

It may be obvious to you, since you seem to have written the filter. I guarantee you it is not obvious to an average user, not with the way it is implemented currently.

**Comment by maxlebedev** [comment]
Using RegEx for censorship is never actually going to work. IDK how good the system is now, but the best case scenario is you will make sure nobody uses words the subset of "bad words" that you can think of in their messages. Worst case your chat is now semi-unusable because your censorship RegEx is not perfect. 

You can still flame pretty effectively, all this encourages is clever use of words/characters. Allowing people to vote to silence someone would be much more effective. You don't have to make decisions about what is or is not too offensive for the users, and there are no false positives. 

You can even be intelligent about it and give per-vote warnings to the offenders, or limit votes to prevent abuse of the feature.

**Comment by JRHerlehy** [comment]
So right now we have a clbuttic mistake with a Scunthorpe problem. Maybe look into if there's a good filtering engine already out there in java?

**Comment by spjspj** [comment]
Well, this is probably fixed now I guess.  The filter is optional and client side so less pain for the server.
