### ISSUE TITLE
Improvements to EDH Power Level calculations

### ISSUE THREAD

**Issue by jeacaveo** [magefree/mage#2660]
Awesome job with the EDH Power Level setting, but here a few suggestions as to what could change for the better:

1. Searching for basic lands shouldn't be considered a tutor effect, hence it shouldn't affect power level (examples: basic landcycling, Cultivate, Veteran Explorer).
2. Permanents that allow to return cards from graveyard to hand should add to the power level (examples: Eternal Witness, Archaeomancer).
3. Flicker and Flickerwisp effects should add to power level.
4. Evoke should add to power level.
5. ~~Showing the EDH Power Level of each card in the tooltip window or generating a text file with this information can help to know what to change when the power level is too high.~~ (See [comment](https://github.com/magefree/mage/issues/2660#issuecomment-265718139))

**Comment by spjspj** [comment]
https://redd.it/5h5cf5 and https://docs.google.com/spreadsheets/d/1GmTEAv50uxMtgWKL5K0eL5wA4wVGRVWswgNl7a_0zm0/edit?usp=sharing show the current power level assigned for each card implemented in xmage.

**Comment by jeacaveo** [comment]
1.4.19v1 included the required changes.
