### ISSUE TITLE
Card image popup/preview with MMB

### ISSUE THREAD

**Issue by milaq** [magefree/mage#2668]
Card image popup/preview is already accessible via mouse wheel.

For Notebooks and Tablets this poses an issue.
Alternatively, the middle mouse button could be utilised to zoom/popup card images in order to increase device compatibility.
In turn, hiding card preview images could then be triggered by the mouse leaving the canvas of the selected card instead.

Moreover, an option to show the preview image instead of the text popup could be made configurable for the user (with a fallback to preview text if no image is found).

Thanks for your efforts,
cheers

**Comment by JayDi85** [comment]
There are hotkeys to show card popup in image mode, infromation added to starting chat message by 
d016e4c4c38da73b804d3fc5a1e122ef51ec314a:
* hold <ALT+E> to force image
* press <ALT+D> to show/hide right card panel
