### ISSUE TITLE
Card images not bundled?

### ISSUE THREAD

**Issue by sotovdev** [magefree/mage#2698]
Are there any legal reason not to bundle card images?
Every player may download 1800mb and 28000+ images for himself, and forced to download Standart cards (is it even possible?). Maybe there is a way to store all these cards somewhere at our server, and download them as one archive, or just bundle in a client.

Trying to download even standart cards is somewhat a pain - player should choose server, 80% downloaded, 20% failed, he should pick another one, try it few times... It worsens gaming experience.

**Comment by MTGfan** [comment]
My guess is that this contains the answer you seek. My understanding of this is that as a user of xmage you have the right to obtain the images for your own personal use with it but by packaging them into the product even though it is a free application would become out of the scope of personal use. And probably is out of the scope of fan sites that have permission to provide the images for MTG players to view and use for their personal use. An example of a similar case is google and the google android apps. Users are free to download and use them within any android ROM official or unofficial but they can't be distributed with the ROMs.

> 6. Intellectual Property Ownership; Rights Granted to You. 
> 
> The Websites and Services (including all Wizards’ generated content residing thereon) are the sole property of Wizards, and are protected by copyright, trademark, and other intellectual property laws (Wizards’ Intellectual Property”). You are granted a limited, revocable, non-sub-licensable right to access and use Wizards’ Intellectual Property solely in connection with your personal and non-commercial use of the Websites and Services. Any use of Wizards’ Intellectual Property other than as specifically authorized by Wizards is strictly prohibited and will terminate the rights granted herein. All goodwill generated by your use of Wizards trademarks shall automatically inure to the benefit of Wizards.
> 
> Notwithstanding the foregoing, Wizards' various fan kits provide you with access and permission to use certain pre-approved images, logos, and other Wizards materials for limited purposes. Use of that content is permitted pursuant to the terms and conditions of the applicable fan kit.

**Comment by spjspj** [comment]
Additionally, the bandwidth of the server would be impacted negatively, keeping the images up-to-date would be painful, and people should be more gooderer at doing stuff on the internet (and this kind of forces them to do so after a fashion).  Also, people have and do modify the images they use (for example, all plains in all of my SET.zip's are a copy of the plains on the right of here http://imgur.com/0o0TVaQ so all plains in the games are a nice zendi basic without the white pips).

**Comment by sotovdev** [comment]
Thanks to your answer, MTGfan!
You if we are unable to bundle them in xmage client, we may improve image downloading to make this process more obvious?
Will it be fine, if image failed to fetch from one server will automatically try to be downloaded from other?

**Comment by spjspj** [comment]
I suspect a lot of people don't actually use the download tools.  There's a torrent on the xmage reddit site that people use already.

**Comment by sotovdev** [comment]
Wow. Where i can find this torrent?

**Comment by spjspj** [comment]
https://www.reddit.com/r/XMage/  search for xmage images
