### ISSUE TITLE
Prized Amalgam delayed trigger returning wrong object from graveyard

### ISSUE THREAD

**Issue by jeacaveo** [magefree/mage#2700]
Scenario:

1. Two Prized Amalgams (in graveyard) triggers at End Of Turn of player 1.
2. When first one enters the battlefield, the second one is still in the graveyard and creates a delayed trigger for the End Of Turn of player 2.
3. Second one enters the battlefield.
4. Second one dies before End Of Turn of player 2.
5. During End Of Turn of player 2, delayed trigger brings back the second Prized Amalgam.

The last step is wrong since the second Prized Amalgam that entered the battlefield and then died should be a different object than the one that created the delayed trigger while it was on the graveyard.

**Comment by Zerrisx** [comment]
This is... half fixed?  The Amalgam still triggers in step 5 - which is wrong - but it no longer gets returned to the battlefield.

**Comment by emerald000** [comment]
It is supposed to trigger in step 5. The delayed trigger was successfully created and will be placed on the stack even if it will do nothing once it resolves.

**Comment by Zerrisx** [comment]
Oh, right you are.  Had to think about that for a bit.  Okay, calling this fixed then.
