### ISSUE TITLE
Ezuri, Claw of Progress + Hardened Scales puts a counter with 0XP

### ISSUE THREAD

**Issue by sjholden** [magefree/mage#2707]
Have Ezuri, Claw of Progress in play, plus Hardened Scales and another creature in play with 0 XP counters on the player.

At beginning of combat a +1/+1 counter will be put on the creature when none should be.

Using 1.4.19V1.

I don't know you code base, but my laymans assumption would be that in https://github.com/magefree/mage/blob/master/Mage.Sets/src/mage/cards/h/HardenedScales.java:

    @Override
    public boolean replaceEvent(GameEvent event, Ability source, Game game) {
        int amount = event.getAmount();
        event.setAmount(amount + 1);
        return false;
    }

should be:

    @Override
    public boolean replaceEvent(GameEvent event, Ability source, Game game) {
        int amount = event.getAmount();
        if (amount >= 1) {
            event.setAmount(amount + 1);
        }
        return false;
    }

to match the card text.

**Comment by LevelX2** [comment]
Thanks for the information and fix suggestion. It's fixed now.
