### ISSUE TITLE
Removing Planeswalker by player concede after opponent creates an emblem

### ISSUE THREAD

**Issue by jackchen0226** [magefree/mage#2710]
Xmage throws an error involving an emblem unable to find the initial source if it has a proc. To reproduce, a Planeswalker was taken from an original player's control, such as using scrambleverse to shuffle Jace, Unraveler of Secrets, to a second player and then the second player uses Jace's ability to create an emblem ("Whenever an opponent casts his or her first spell each turn, counter that spell."). Then the original player concedes the game and removes the Planeswalker. Once it becomes an opponent of the original player's turn and that opponent plays a spell, Xmage throws an error and rollsback the turn. 

I don't have the actual error report on my due to negligence, but what I can recollect is that the error message was along the lines of  "The emblem cannot find the original source. This turn will be rolled back". This error message will always appear when an opponent tries to play a spell.

**Comment by LevelX2** [comment]
Should be fixed with 1.4.20V0
