### ISSUE TITLE
Can't update Xmage

### ISSUE THREAD

**Issue by albuzs** [magefree/mage#2712]
Ever since 1.4.19V1 became available, whenever the new version downloads, it just resets the download, and then it tells me there is a new version. I have tried downloading it several times, but nothing happens. Where can I download the new one?

**Comment by albuzs** [comment]
![capture](https://cloud.githubusercontent.com/assets/16671803/21484366/0f07da92-cb46-11e6-9011-97b4ec2b9990.JPG)


The issue is still going on ): it downloads, then just says that there is a new version available

**Comment by MTGfan** [comment]
Have you tried deleting the current install to do a clean install? You may backup the existing install into a zip file or any other means of backing up the existing folder before doing so to retrieve the downloaded images from. If it still doesn't install more information will be needed to diagnose the issue. If it does install at least there is a valid work around if the problem occurs again.

**Comment by albuzs** [comment]
Where do I find the current instal?

**Comment by MTGfan** [comment]
it should be a sub folder named xmage in the folder the launcher is located.
