### ISSUE TITLE
Enlisted Wurm issue

### ISSUE THREAD

**Issue by albuzs** [magefree/mage#2713]
Whenever Enlisted wurm is returned to hand, or was cast previously by an opponent's Gonti, after it is returned to my hand, it will not let me cast it.

**Comment by LevelX2** [comment]
I can't reproduce the problem. Can you describe detailed what needs to happen to reproduce that problem?

**Comment by albuzs** [comment]
Yes of course.

It was during a game of EDH with 3 players. One of the players casted his Gonti Lord of Luxury targeting me. He got the wurm and then casted it. When the wurm died and went to my graveyard, I then returned it to my hand. After this was done, the wurm was not castable. It did not appear as a castable option as the rest of the creatures in my hand for the rest of the game.

**Comment by albuzs** [comment]
It did not highlight, nor did anything when I clicked on it, even after priority was passed to me.

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.
