### ISSUE TITLE
Can't see images for specific sets

### ISSUE THREAD

**Issue by albuzs** [magefree/mage#2720]
![capture](https://cloud.githubusercontent.com/assets/16671803/21504486/404a9076-cc14-11e6-9da5-1a74a5eb42db.JPG)
Hello,

I can't see images for UNH lands during a match, but they do come up on the deck editor. Is there a way to make them come up?

**Comment by Dislaider** [comment]
This happen with UGL (Unglued) lands also.

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.
