### ISSUE TITLE
Praetor's Grasp and similar card stealing effects - owner can't cast if they regain card

### ISSUE THREAD

**Issue by ttamnedlog** [magefree/mage#2721]
Praetor's Grasp and Thada Adel, Acquisitor, and possibly other cards with similar effects cause the owner of stolen cards to be unable to cast those cards if they somehow reacquire them.

Specific examples I've encountered:

In two separate games with Thada Adel, Acquisitor, I stole a Sol Ring and cast it. After some board wipes and graveyard digging, the Sol Rings found their way back to their owners' hands. They were unable to cast them.

I stole a Spine of Ish Sah with Praetor's Grasp. After a board wipe, the Spine returned to its owner's hand and they were unable to cast it.

**Comment by JRHerlehy** [comment]
Likely related to #2713 

Looks like something is sticking itself to their code and not releasing correctly when the effect is done.

**Comment by LevelX2** [comment]
Added test for this but I can't reproduce yet.

What cards/effects were used for board whipes and getting the cards back to hand?

**Comment by ttamnedlog** [comment]
I'll try and do more testing to get some more specifics. All occurrences were during multiplayer EDH matches, so the details are hard to recall. I don't remember the details on the Sol Rings and how they got back to their owner's hands.

I do remember the Spine of Ish Sah though. I sacrificed it to Daretti, Scrap Savant and that simply sent it back to its owner's hand due to: "When Spine of Ish Sah is put into a graveyard from the battlefield, return Spine of Ish Sah to its owner's hand."

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.
