### ISSUE TITLE
Uba Mask Bug

### ISSUE THREAD

**Issue by nsfranklin** [magefree/mage#2733]
Uba Mask does not currently prevent you from casting cards that where exiled in previous turns.

**Comment by drmDev** [comment]
http://gatherer.wizards.com/Pages/Card/Details.aspx?name=uba+mask

`12/1/2004 	You can’t play cards you exiled with Uba Mask on previous turns.`

I'll take a quick look to see what could be causing this.

**Comment by jeffwadsworth** [comment]
Can anyone else play any of the cards in Exile?  Just confirming that it is broken or not.  Could be my client.

**Comment by jeffwadsworth** [comment]
Uba Mask appears to be bugged.  You can't play any cards from Exile.
