### ISSUE TITLE
Deflecting Palm incorrectly has controller select targets

### ISSUE THREAD

**Issue by brikr** [magefree/mage#2735]
Deflecting Palm has the target choosing code as part of the replacement effect, which means the controller chooses the target as the spell is resolving instead of at cast time. To fix this, we just need to use `this.getSpellAbility().addTarget(new TargetSource());` in the card class and make the `applies` method reference the target more like how Hallow or Awe Strike do.

**Comment by JRHerlehy** [comment]
The implementation is correct as is. 

>Deflecting Palm doesn't target any creature or player. You choose a source of damage as Deflecting Palm resolves.
2014-09-20, Gatherer Rulings
