### ISSUE TITLE
Experiment One from any available set gives error

### ISSUE THREAD

**Issue by martijnvanschie** [magefree/mage#2758]
When selecting a deck with Experiment One in it the following error popsup.

![image](https://cloud.githubusercontent.com/assets/8370550/21764073/7ef5ed28-d661-11e6-8a12-9808af243b93.png)

Counts for any ot the three available verions of experiment one.

**Comment by fireshoes** [comment]
The server was having issues and needed a restart. You can tell in the future if there are many tables that have 0/2 players waiting at it and there are many completed matches that say Cancelled.
