### ISSUE TITLE
Implement of Ferocity and Defiant Salvager broken

### ISSUE THREAD

**Issue by sotovdev** [magefree/mage#2763]
[https://www.reddit.com/r/XMage/comments/5mybtd/implement_of_ferocity_and_defiant_salvager_broken/](https://www.reddit.com/r/XMage/comments/5mybtd/implement_of_ferocity_and_defiant_salvager_broken/)

> Implement of Ferocity gives Unit counter instead of +1/+1. Defiant Salvager can't be activated at any time.

**Comment by sotovdev** [comment]
Can someone confirm this?

**Comment by Styxo** [comment]
i can confirm, that both bugs are fixed - see commits from yesterday

**Comment by JRHerlehy** [comment]
Issue resolved
