### ISSUE TITLE
Problem downloading the files?

### ISSUE THREAD

**Issue by RobotAF** [magefree/mage#2766]
Whenever i hit the "download Xmage button on the main home page it downloads a .jar file that opens using internet explorer and i cant figure out how to download the actual files or what to do please help

**Comment by fireshoes** [comment]
Another user having same issue here. Try the suggestions. Also check out the Guide to Install and play with Xmage under Announcements. Reply there with more questions.
http://www.slightlymagic.net/forum/viewtopic.php?f=70&t=19966&sid=c4934c3adb25a02262c0027bafbe6c53
