### ISSUE TITLE
Metallic Mimic Empty Selection if Blinked

### ISSUE THREAD

**Issue by mcockle23** [magefree/mage#2768]
If you blink Metallic Mimic, (in my case it was with Essence Flux) when it returns to the battlefield, the box used to select which type to name is empty and you can't cancel or select a type.

**Comment by mcockle23** [comment]
This might already be fixed in 1.4.20.  I tested it locally and it worked.

**Comment by mcockle23** [comment]
It seems like this can just happen occasionally.  I have no idea why, but I've seen it work and also seen it empty on occasion.

**Comment by jeffwadsworth** [comment]
I tested this several times and it worked fine in the latest version.  5ace1a9620107832b9f88a12b04e93b84216edb2

**Comment by drmDev** [comment]
If the issue re-surfaces let us know and we can re-open. Include a game log if possible.
