### ISSUE TITLE
Odd Issues with Dack's Emblem and Commanders

### ISSUE THREAD

**Issue by Badaro** [magefree/mage#2770]
I was playing a commander game where I had Dack Fayden's Emblem out. I targeted the opponent's commander with a Burn spell that would deal lethal damage. The stack resolved like this:

1) Burn spell is placed on the stack
2) Emblem's trigger fires and is placed on the stack
3) I get control of the opponent's commander
4) Burn spell resolves, opponent's commander dies

As far as I can tell, this is correct.

However, after this happened, any time the opponent would cast his commander, it would enter the battlefield directly under MY control every time.

**Comment by wxfnyu** [comment]
I ran into a similar issue as well with the Dack emblem, my opponent cast the sweeper that destroys all humans and reanimates all zombies.

When that resolved a Bloodghast I had  Lightning Bolt'd earlier while I had a Dack Emblem ETB'd under my control.

Ill upload the screenshots I took of the bug once I get home tonight.

**Comment by wxfnyu** [comment]
Screenshot as promised
![xmage glitch](https://cloud.githubusercontent.com/assets/25141234/22674363/993c3d24-ecad-11e6-96fa-62f4b9367baa.PNG)

**Comment by ImperatorPrime** [comment]
Fixed by dd0c89db1db86168c19614dfc0b42481651e934e.
