### ISSUE TITLE
Aether Revolt Bug (Felidar Cat)

### ISSUE THREAD

**Issue by noriyatsu** [magefree/mage#2773]
Felidar being able to target itself and make infinite blink by itself and decoction module will make infinite energy.. Ninth bridge patrol also get infinite power

"When Felidar Guardian enters the battlefield, you may exile **ANOTHER** target permanent you control, then return that card to the battlefield under it's owner's control.

_The loyalty of a felidar is hard won but worth the effort_"

**Comment by fireshoes** [comment]
Fixed beyond version 1.4.20v0.
