### ISSUE TITLE
Metallic Mimic can't select Servo as a creature type.

### ISSUE THREAD

**Issue by SevenDeadlySins** [magefree/mage#2776]
What the title says. Even though there are no actual Servo creatures that you can cast, you should be able to select Servo as the selected type in order to interact with Fabricate and other servo-generating spells and abilities.

**Comment by loetermann** [comment]
It's already fixed by this commit, should work with the next update
https://github.com/magefree/mage/commit/fa4cf8161dc1f5e343a26ed0b8695c727e034f84

**Comment by SevenDeadlySins** [comment]
Awesome, thanks.
