### ISSUE TITLE
Getting "Wrong password" message after clicking Join on a match

### ISSUE THREAD

**Issue by fireshoes** [magefree/mage#2784]
The "Wrong password" message occurs before any opportunity to enter a password or choose a deck.
![capture](https://cloud.githubusercontent.com/assets/8553747/21907741/77f6c8e0-d8d6-11e6-8c13-c07a4e73c42a.JPG)

**Comment by digitalDojoNZ** [comment]
yes im getting the same issue. it used to work for me though

**Comment by digitalDojoNZ** [comment]
update: this only seems to be a problem when trying to join a pwd protected limited game. constructed matches seems to work fine with the pwd field editable when joining

**Comment by fireshoes** [comment]
With a constructed match, the deck selection + password field come up after clicking Join, so possibly related to Limited tournaments.
