### ISSUE TITLE
Masterpieces/Expeditions should replace a common instead of a land

### ISSUE THREAD

**Issue by fireshoes** [magefree/mage#2787]
They are currently programmed to replace a basic land, but should replace a common like other foils.
Confirmation from [Aaron Forsythe](https://twitter.com/mtgaaron/status/646932611990859777?lang=en).

**Comment by Zerrisx** [comment]
Confirmed still bugged.
![image](https://user-images.githubusercontent.com/59861365/88823182-68132a80-d18a-11ea-9063-99a985e7dee8.png)

**Comment by awjackson** [comment]
This was fixed by 7926193e34cfea7802f2db2a727227452bb22950
