### ISSUE TITLE
Magma Sliver not applying affect

### ISSUE THREAD

**Issue by RedStoner** [magefree/mage#2789]
The magma sliver does not give its effect to any slivers, including itself. 
Tested in version : 1.4.20

**Comment by LevelX2** [comment]
Can't reproduce the problem.

![sliver](https://cloud.githubusercontent.com/assets/2066790/21948874/2ab0bd84-d9ee-11e6-9227-6c20c5730f95.jpg)

**Comment by RedStoner** [comment]
very odd, tested again just a moment ago, and its working as intended. Must've been a glitch in the matrix. Ty.
