### ISSUE TITLE
Cant Launch Xmage Windows 10

### ISSUE THREAD

**Issue by WTTV** [magefree/mage#2791]
I have java and windows 10 but i cant find that file that installs Xmage please help me

**Comment by JRHerlehy** [comment]
If java is installed correctly, xmage is installed by running the xmage launcher from xmage.de. Double clicking is all that is needed to launch; do not extract the jar file.

**Comment by goesta** [comment]
I'll close this issue because there where no feedback for a long time but feel free to create a new one if this is still a problem.
