### ISSUE TITLE
i get this every time i download xmage

### ISSUE THREAD

**Issue by WTTV** [magefree/mage#2792]
![untitled](https://cloud.githubusercontent.com/assets/25112194/21952004/9ea5a64a-d9d6-11e6-9729-058569ac5fdd.png)
cant get the launcher to install the game and have java on windows 8.1
please help

**Comment by JRHerlehy** [comment]
Please do not open multiple issues for the same issue.

The JAR is an EXECUTABLE file.  Do not open it in WinRAR.

It is possible that your system has associated WinRAR with the JAR file type.  Right click, open with Java should run it.  You may need to reset you system to default to using Java.
