### ISSUE TITLE
Card name panel won't go away

### ISSUE THREAD

**Issue by albuzs** [magefree/mage#2803]
This has happened to me a couple of times now. If at any time there is a disconnect while the text box is up, it will remain there even after you reconnect, and it will not go away.

![capture](https://cloud.githubusercontent.com/assets/16671803/21964425/a520fa26-db00-11e6-8740-f269928276b1.JPG)

**Comment by FastTadpole** [comment]
Ditto here. Only happened to me on disconnect as well. Restarting the client was the only was to resolve.

**Comment by JayDi85** [comment]
Fixed by ee2741c7a74e48f00769e61e0414050aab186b89
