### ISSUE TITLE
Issue with Hope of Ghirapur ability

### ISSUE THREAD

**Issue by albuzs** [magefree/mage#2808]
Hello,

There is a bug with the ability of this card.  If I am dealt damage, then my opponent sacrifices the artifact, but I Disallow the ability, he/she then brings it back with Renegade Rallier, as it stands, my opponent can still sacrifice the Hope to prevent me from casting non creature spells.

The opponent should not event be able to sacrifice the artifact, as there would not be a legal target for it to be sacrificed

The returned card should not be able to check past instances of the card that were on the battlefield, that did damage to me that turn.

**Comment by mcockle23** [comment]
While you are correct that the returned instance of Hope of Ghirapur should not be able to trigger the ability if they sacrifice it, they technically could still sacrifice it if they wanted to. The way the card is worded, you can sacrifice it whenever you want, you just wouldn't get the ability unless you had dealt combat damage to the opponent with it.

**Comment by albuzs** [comment]
Hi mcockle :)

I ran this by a judge, and you should not be able to. As there would not be a legal target. Maybe he was mistaken, but still the cards needs a bit of work first.

Cheers

**Comment by emerald000** [comment]
The targeting restriction is "target player who was dealt combat damage by Hope of Ghirapur this turn". Unless you can find such a player, you can't activate it and sacrifice it for no reason.

**Comment by mcockle23** [comment]
Yeah, I definitely could be wrong about it. But, iy seems the way it's worded, you could technically sacrifice it for no reason. When you sac it, the target player ability would go on the stack and fizzle because it has no legal target. Obviously, you would not want to do this 99% of the time, but, it is a free way to trigger revolt which is actually relevant.

**Comment by emerald000** [comment]
You are definitely wrong. You can't activate an ability/cast a spell unless you can choose a legal target for every target instance.

So you can't sacrifice if unless it actually did damage to a player.

**Comment by albuzs** [comment]
That's the thing man, you can't. You can't do something just because if the effect lacks a target. If it read "up to one player that was dealt damage", then sure, you could do it. That is why many planeswalker abilities read +1: Up to one creature... If it read +1: Target creature, many PW would be useless.

**Comment by mcockle23** [comment]
Alrighty then. Thanks for being so nice about it! Lol

**Comment by albuzs** [comment]
<3

So... can we get this fixed? :D
