### ISSUE TITLE
Layers (Starfield of Nyx + Humility)

### ISSUE THREAD

**Issue by skeate** [magefree/mage#2813]
I was playing a game with five enchantments in play under my control, which included Pharika, God of Affliction, Humility, and Starfield of Nyx (played in that order). I did not meet Pharika's devotion.

Opponent then played an Emrakul, the Aeons Torn which was a 15/15 with no abilities, and Pharika was a non-creature enchantment. This seems wrong.

* Layer 4: Pharika becomes a non-creature. Starfield of Nyx turns all my non-aura enchantments (other than itself) into creatures (Pharika becomes a creature again)

* Layer 6: Humility removes all abilities of all creatures, including itself (and Emrakul), but according to 613.5:
>If an effect starts to apply in one layer and/or sublayer, it will continue to be applied to the same set of objects in each other applicable layer and/or sublayer, even if the ability generating the effect is removed during this process.

* Layer 7b: Humility makes all creatures (including Emrakul) 1/1s. Starfield of Nyx makes all non-aura enchantments I control other than itself have P/T equal to CMC (humility becomes a 4/4, Pharika becomes a 3/3).

**Comment by jeffwadsworth** [comment]
Currently, the code does not treat the loss of Static Abilities in this manner (aka: as if it was a spell/activated ability with affected objects).

**Comment by skeate** [comment]
Every question/answer I can find about this kind of situation (usually Opalescence + Humility, but same idea) says the Humility effect turning everything into a 1/1 still happens. For example, this [L2 judge](https://blogs.magicjudges.org/ftw/l2-prep/rules-and-policy/continuous-effects/) (ctrl+f "Q: Amy casts Humility, then Opalescence. What happens?")
