### ISSUE TITLE
Champion of Lambholt triggered by all players

### ISSUE THREAD

**Issue by maribakumon** [magefree/mage#2814]
"Whenever another creature enters the battlefield under your control, put a +1/+1 counter on Champion of Lambholt."

Despite the card stating that it's only triggered by creatures entering the battlefield on its controller's side it's triggered by all creatures from any player's battlefield.

For instance if my opponent controls Champion of Lambholt and I play Increasing Devotion then each of the tokens that enter the battlefield on my side will still give my opponent's Champion 5 +1/+1 counters.

**Comment by LevelX2** [comment]
This was fixed with Release 1.4.21v0 (2017-01-15).
Champion of Lambholt - Fixed that the triggered ability also triggered for not controlled permanents.

Sure you still encounter this problem with 1.4.21v0 or later?

**Comment by maribakumon** [comment]
I've only encountered it in 1.4.21v0
I don't believe I ran the card in previous builds.
