### ISSUE TITLE
Update launcher version http://xmage.de/

### ISSUE THREAD

**Issue by kubikrubikvkube** [magefree/mage#2815]
Currently "Download X-mage" launcher button gives you 1.4.19 version of xmage, it can't be connected to any up-to-date server, please provider possibility of downloading 1.4.20 of xmage from xmage.de

**Comment by LevelX2** [comment]
What are you taking about?
Maybe you fixed your launcher to an old version in the settings?

The version the launcher downloads is defined here:
http://www.xmage.de/xmage/config.json
And uses 1.4.21V1
    "version": "1.4.21V1 (2017-01-24)",    
    "location": "http://bit.ly/xmage_1_4_21V1d",
    "locations": ["http://bit.ly/xmage_1_4_21V1d", "http://bit.ly/xmage_1_4_21V1w"],

**Comment by kubikrubikvkube** [comment]
My bad :)
