### ISSUE TITLE
Load token images from Gatherer.com

### ISSUE THREAD

**Issue by LevelX2** [magefree/mage#282]
It should be possible to download token  images also from Gatherer.com site.

Some examples of token images on Gatherer.com.
Hornet 
http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=209163

Minion 
http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=207998

Saproling 
http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=209162

Beast1,Beast2 
http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=201842

**Comment by JayDi85** [comment]
No more actual with scryfall source
