### ISSUE TITLE
Hivestone Issues

### ISSUE THREAD

**Issue by RedStoner** [magefree/mage#2823]
I have discovered 2 issues tonight with Hivestone. 
1. Hivestone applies the creature type "Slivers" to the creature instead of "Sliver" thus rendering any "All slivers have ...." effects.
2. Hivestone applies the creature type to all creatures on the battlefield when it should only apply to ones controlled by hivestones controller.

**Comment by ingmargoudt** [comment]
Looks fixed in 
https://github.com/magefree/mage/commit/2cf15830d752f6f56e09215739ad45a4654ea1d2

Will be in the next release
