### ISSUE TITLE
GUI Issues

### ISSUE THREAD

**Issue by DaMachinator** [magefree/mage#2831]
![Messed up card images](http://u.tylian.net/4xNm8Q)

Card images in the editor and game are messed up after I changed some GUI settings to try to get the cards to fit better on my laptop screen (since the stack and hand have no scrollbar - this has messed me up in a game before where i was not able to counter a spell properly because of all the triggered abilities stacking up).

The card icons, text and images in the play area are messed up in the same manner.

**This issue persists across reinstalls of XMage, _as does my user and server data_, despite redownloading the launcher and installing in a different directory.**

**Comment by cow2** [comment]
It might just be you dont have the right images dwnlded yet, it kinda looks
the same as when you don't.  Reload more images while logged in on xmage
with a good connection.

Hope this helps

**Comment by cow2** [comment]
Never mind it is still early for me and i misunderstood your issue my
apologies.

**Comment by spjspj** [comment]
https://www.youtube.com/watch?v=fwR3S0m1njY << check where xmage thinks your images are

**Comment by DaMachinator** [comment]
This behaviour appears to be associated with using the "fallback to image-based renderer" option in the settings menu. 

I do not know why instances of XMage in different folders are sharing configuration, user, and image data.

**Comment by JayDi85** [comment]
Old versions can't load all images on low memory limit. But after last releases and new cash system (see b18efe2fbf3e982a3c5b71c7a299c0ca67417d49) -- that was fixed. Now xmage gets client freeze on low memory, but don't lost images.
