### ISSUE TITLE
Athreos's trigger is not working

### ISSUE THREAD

**Issue by filipebfs** [magefree/mage#2832]
Athreos, God of Passage is on battefield, Cartel Aristocrat's abilitie has been activated. Athreos's trigger is not working.

**Comment by drmDev** [comment]
writing test for this...

**Comment by drmDev** [comment]
Unable to confirm bug with the unit tests (see commit referenced above). Will test manually when I return home. 

Do you have a game log or any additional information on this issue?

**Comment by filipebfs** [comment]
Unfortunately no

**Comment by drmDev** [comment]
Also could not confirm with in-game testing. Would need to see logs to dig in deeper.

```
7:50 AM: Human sacrificed Grizzly Bears [c23]
7:50 AM: Human activates: Cartel Aristocrat [6c9] gains protection from the color of your choice until end of turn. from Cartel Aristocrat [6c9]
7:50 AM: Ability triggers: Athreos, God of Passage [0ff] - Whenever another creature you own dies, return it to your hand unless target opponent pays 3 life. - targeting Computer 
7:51 AM: Computer loses 3 life
```
