### ISSUE TITLE
Spellskite + split damage

### ISSUE THREAD

**Issue by typhlosionjones** [magefree/mage#2834]
Spellskite and another creature were targeted with a Fiery Justice. The opponent activated Spellskite's activated ability to redirect Fiery Justice to Spellskite. When Fiery Justice resolved, 1 damage that had been originally assigned was dealt to the other creature, but no damage was assigned to the Spellskite.

**Comment by jeffwadsworth** [comment]
Yikes.  This bug has been around since at least Jan 1st 2016.  Interesting that no one reported it.  Working on it.

**Comment by jeffwadsworth** [comment]
Proposed fix.
http://www.slightlymagic.net/forum/viewtopic.php?f=116&t=20288

**Comment by drmDev** [comment]
@jeffwadsworth can you make that into a PR? easier to pull it down and test from that

**Comment by jeffwadsworth** [comment]
Fixed with 31ba751c66bae4b8b01a843796cd924a7538ebf2

**Comment by jeffwadsworth** [comment]
I see a test case that I need to fix.
