### ISSUE TITLE
Declaration In Stone Non funtional.

### ISSUE THREAD

**Issue by nsfranklin** [magefree/mage#2839]
Declaration In Stone Does is not functioning to exile the targeted creature. It comes up in the log as targeting and doesn't then exile the creature or make the clue.

**Comment by FastTadpole** [comment]
..confirmed multiple times

**Comment by Bokononist** [comment]
Confirmed. Opponent attempted to cast Declaration in Stone targeting Winding Constrictor. The Declaration resolved without exiling the Constrictor.

**Comment by FastTadpole** [comment]
Thanks for looking into that. Now, in the two instances I have seen it in action. My opponent targeted a servo token and it only exiled one servo token. Then, during the next turn he targeted a Toolcraft Exemplar and it only exiled one of the two I had on the field and only created one clue.

**Comment by LevelX2** [comment]
There was still a bug in the released version. It's fixed with the next update.
