### ISSUE TITLE
Game freezing when giving priority

### ISSUE THREAD

**Issue by marcovitch-MT** [magefree/mage#2850]
I had some problems with the priority switch last night :

I clicked on "OK" button to give priority, but the other player doesn't recieve it completly :
He can't do anything whereas the timer countdown is running very well.

In that situation, the game is freezed : impossible to do anything in the game.
Tchat is OK.
We tried both of us to click on a skip button to let the engine go on automatically.
but it did nothing.

only solution : restart the client. 

we observe the issue twice yesterday evening. 

Has anyone already observe that issue ?

Thanks

**Comment by Zerrisx** [comment]
There are a lot of issues similar to this, but there's not really enough information here.  This should be significantly improved by our new sound cues for priority passes, since it will now be more clear who the system thinks actually has priority.

**Comment by JayDi85** [comment]
All "priority freeze" and same bugs was fixed in that/last year. So all old issues (1+ year) can be closed. Except latest problem like drafts/tourney freeze (rare bug with disconnects in deck editor stage).

**Comment by Zerrisx** [comment]
> 
> 
> All "priority freeze" and same game freeze bugs was fixed in that/last year. So all old issues (1+ year) can be closed. Except latest problem like drafts/tourney freeze (rare bug with disconnects in deck editor stage).

A quick search shows the issues that look like they might fall under that umbrella are #683, #4262, #4349, #4413, #4472, #4609, #4847, #4951, #5219, #5289, #5482, #5650.

**Comment by Zerrisx** [comment]
Also #2005 and #3658

**Comment by JayDi85** [comment]
@Zerrisx I checked that issues list and closed already fixed. But some needs to be checked in actual version/gameplay (if it works fine then can be closed too).
