### ISSUE TITLE
nvm, not a bug, please delete

### ISSUE THREAD

**Issue by LaceyRosehips** [magefree/mage#2853]
I was attacking with Electrostatic Pummeler. My opponent had declared no defenders. I pumped him up with 3x Built to Smash (+3/+3), then paid 3 energy to double him up to what should have been 20/20. However, when I swung, I only dealt, I think, 11 damage. 

That's the best I can recall, hope it's enough!

**Comment by spjspj** [comment]
Did you stack them correctly and let them resolve? Sounds like it went 1/1   * 2  to get to a 2/2   then the 3 built to smash +3/3 +3/3 +3/3   to get to the final 11/11.

**Comment by LaceyRosehips** [comment]
Uuugh, yes, I'm a noob. I have a very poor understanding of the stack. I ended up figuring out how to do it right a few games later. >.<
