### ISSUE TITLE
Can't crew during combat phases?

### ISSUE THREAD

**Issue by LaceyRosehips** [magefree/mage#2862]
It should be instant speed, as far as I know, but I'm never able to crew during combat phases. =(

**Comment by CSDragon** [comment]
when exactly are you trying to crew? Even though it's instant you can't crew while declaring attackers or blockers. If you're trying to crew during the Beginning of Combat step, or after attackers have been declared but before blockers are declared and it's not working that's an actual problem.

**Comment by LaceyRosehips** [comment]
Cruuud. I thought it was just me at first, but I talked to someone else who was having the issue, which gave me confidence. Turns out we're both dumb.
