### ISSUE TITLE
Vesuvan Shapeshifter turn face up bug

### ISSUE THREAD

**Issue by jeffwadsworth** [magefree/mage#2864]
The rule:
If Vesuvan Shapeshifter is turned face up, the process of turning face up includes (optionally) choosing another creature on the battlefield. You’ll pay 1Blue (not the morph cost, if any, of the new creature), then Vesuvan Shapeshifter will turn face up as a copy of that creature, plus the triggered ability it gives itself. It won’t turn face up as a Vesuvan Shapeshifter and then change. If the copied creature has a “when this creature is turned face up” ability, it will trigger for Vesuvan Shapeshifter.

The well-known combo with Vesuvan Shapeshifter and Brine Elemental does not work correctly.  When Vesuvan Shapeshifter turns face up and becomes a copy of the targeted creature, it should still be in the state of "turning face up", thus triggering the ability of the Brine Elemental.

**Comment by spjspj** [comment]
Similar to issue #2230
