### ISSUE TITLE
Metallic Mimic + Hardened Scales interaction

### ISSUE THREAD

**Issue by jackmeagher** [magefree/mage#2872]
Metallic Mimic + Hardened Scales + Hangarback on X=1 gives a hangarback with 4 +1/+1 counters on it. Should be 3.

**Comment by jeffwadsworth** [comment]
Well, it depends on whether or not you gave the creature type of Construct to the Metallic Mimic or not.  If you did, and I bet you did, it would come in with 4 +1/+1 counters.

**Comment by emerald000** [comment]
This is incorrect. It should enter with 1 (initial value) + 1 (for Metallic Mimic) + 1 (for Hardened Scales). You don't apply a replacement effect twice to the same event.

**Comment by jeffwadsworth** [comment]
Hardened Scales code is looking for the event "Add_Counters".  The Metallic Mimic is looking for the event "Enters_The_Battlefield".  That is going to be extremely tricky.

**Comment by emerald000** [comment]
Here's the really technical explanation of what is happening:

1- As Hangarback Walker is entering the battlefield, an event is created saying "Hangarback Walker is entering the battlefield".

2- Two replacement effects apply to it.
2a- "Hangarback Walker enters the battlefield with one +1/+1 counter" from Hangarback Walker's own ability.
2b- "Hangarback Walker enters the battlefield with an additional +1/+1 counter" from Metallic Mimic.

3- Whichever replacement effect you choose to apply first makes no difference as both have the exact same consequence. The event becomes "Hangarback Walker is entering the battlefield with one +1/+1 counter". 

4- A new replacement effect can be applied: "If one or more +1/+1 counters would be placed on a creature you control, that many plus one +1/+1 counters are placed on it instead" from Hardened Scales. The other effect (2a or 2b) can still be applied.

5- You apply one of the remaining two replacement effects. The event becomes "Hangarback Walker is entering the battlefield with two +1/+1 counters".

6- The last replacement effect is applied. The event becomes "Hangarback Walker is entering the battlefield with three +1/+1 counters".

7- No other replacement effect applies anymore. The event "resolves" and puts the Hangarback Walker with three counters on the battlefield.

**Comment by drmDev** [comment]
Will create test for this

**Comment by drmDev** [comment]
test added confirming bug

**Comment by drmDev** [comment]
Unit tests continue to fail.

 testWithVigorMortis(org.mage.test.cards.replacement.entersBattlefield.HardenedScaleTest): (Battlefield) Counter counts are not equal (Silvercoat Lion:P1P1) expected:<3> but was:<4>
  hangarBackHardenedScalesMetallicMimicTest(org.mage.test.cards.replacement.entersBattlefield.HardenedScaleTest): (Battlefield) Counter counts are not equal (Hangarback Walker:P1P1) expected:<3> but was:<4>

 hangarBackHardenedScalesMetallicMimicTest(org.mage.test.cards.triggers.EntersTheBattlefieldTriggerTest): (Battlefield) Counter counts are not equal (Hangarback Walker:P1P1) expected:<3> but was:<4>
