### ISSUE TITLE
testThatBouncingACrewedVehicleWillUncrewIt fails for wrong reason

### ISSUE THREAD

**Issue by ingmargoudt** [magefree/mage#2873]
Mentioned test fails, but for the wrong reason.
Scenario:
in play: Smuggler's Copter, Speedway Fanatic
activateAbility: Crew 1, choice: Speedway Fanatic
CastSpell Evacuation.
CastSpell: Smuggler's Copter
Final assert: Smuggler's Copter is a creature, rather than an uncrewed vehicle.

By debugging through the test, I found out that during the resolution of Evacuation, the crew ability has not resolved yet, resulting only Speedway Fanatic to be returned to the hand. As Evacuation is an instant, I guess its placed on top of the stack on top of the crew ability. 
I changed the Evacuation for a Crush of Tentacles, and reran the test: The Crush of Tentacles returned both Speedway Fanatic and Smuggler's Copter back to the hand.
Recasting the Smuggler's Copter and Asserting it gave as result that it still was crewed, and thus a creature in addition to being an artifact.

Now my question is: Does this only affect the crew ability, or also other abilities that falsely remain active after being returned to the hand?

**Comment by goesta** [comment]
Maybe this discussion better fits in #2761 which is the original bug.

But regarding the test. Is there a test helper that allows us to skip the stack to prevent such problems? If not, what would be the best way to implement one?

**Comment by emerald000** [comment]
The way I do it usually is changing steps between everything to make sure the previous spell/ability resolved.

**Comment by goesta** [comment]
Good Point. 
When possible i've used multiple turns to prevent this issue but for the crew ability this was not possible.

**Comment by ingmargoudt** [comment]
Using multiple turns would change the scope of your test, as the crew ability has a duration UntilEndOfTurn, so if you are in a next turn and the crew ability wears off, you still dont know if it would wear of in the correct turn in your hand :)

**Comment by goesta** [comment]
I know. As emerald000 said using multiple steps would do the trick hier.

```
        addCard(Zone.BATTLEFIELD, playerA, "Smuggler's Copter", 1);
        addCard(Zone.BATTLEFIELD, playerA, "Speedway Fanatic", 1);
        addCard(Zone.BATTLEFIELD, playerA, "Island", 7);
        addCard(Zone.HAND, playerA, "Evacuation", 1);

        activateAbility(1, PhaseStep.PRECOMBAT_MAIN, playerA, "Crew 1");
        setChoice(playerA, "Speedway Fanatic");

        // Return all creatures to there owners hands
        castSpell(1, PhaseStep.BEGIN_COMBAT, playerA, "Evacuation");

        // (Re)Cast Smugglers Copter
        castSpell(1, PhaseStep.POSTCOMBAT_MAIN, playerA, "Smuggler's Copter");

        setStopAt(1, PhaseStep.END_TURN);
        execute();

        // Only crewed vehicles have card type creature
        assertNotType("Smuggler's Copter", CardType.CREATURE);
```

**Comment by goesta** [comment]
@ingmargoudt did you commit your fix for the test or should i update the test?

**Comment by ingmargoudt** [comment]
I did not update the test yet :) up to you ;)
