### ISSUE TITLE
Ashling's Prerogative always tap AND gives haste

### ISSUE THREAD

**Issue by CSDragon** [magefree/mage#2875]
Ashling's Prerogative is "Chose odd or even, creatures with CMC you chose gain haste, creatures without ETB tapped"

But instead, it's giving haste and tapping all creatures on ETB

**Comment by Plopman** [comment]
I can't reproduce this bug

**Comment by CSDragon** [comment]
Huh, it was reproducing 100% of the time when I reported the bug, but now it's not happening at all.
