### ISSUE TITLE
During registration receive "Can not find free port for use."

### ISSUE THREAD

**Issue by syphoxy** [magefree/mage#2883]
# Reproduction

1. Try to register
2. that's it

# What am I getting?

A message dialogue box stating "Can not find a free port for use."

# What do I expect?

To be able to proceed with registration.

# Screenshot

![2017-02-20-160344_1212x768_scrot](https://cloud.githubusercontent.com/assets/234569/23141804/90f94600-f786-11e6-83f0-b2534b5a7006.png)

**Comment by ingmargoudt** [comment]
This message is thrown by JBoss, rather than XMage itself, 

see http://www.slightlymagic.net/forum/viewtopic.php?f=70&t=14233&p=169801 and
https://www.reddit.com/r/XMage/comments/36511c/xmage_cannot_find_free_port_to_use/

**Comment by syphoxy** [comment]
this doesn't really help at all. I'm using `en_CA.UTF-8`. I don't have an anti-virus installed because I use Linux.

**Comment by spjspj** [comment]
Try connecting to http://xmage.de:17171/ from your browser.  I get 'jbs1{'.  Or possibly try ftp'ing to xmage.de on port 17171.  If you can do either of these, I don't think it's your firewall stopping connections.  I occasionally get this error in dev - a stop and restart of the client usually fixes it though.

**Comment by goesta** [comment]
I can't really say when this occurred for the first time but i have this issue to. For at least a month. But only when i try to connect over ethernet over wifi it works fine.
I am running macOS and thought it is a problem with my machine.

**Comment by DaMachinator** [comment]
I get this error on Win10 when I change wireless networks while connected. Restarting the client fixes it.

**Comment by DerGatt** [comment]
I get the same error, no problem connecting via website. I'm running arch Linux, installing it on Ubuntu mate in a VM on the same machine it works without a problem.

**Comment by JayDi85** [comment]
It's a client side problem -- restart client and/or machine. Also need to check firewall and router settings (ask your network admin).
