### ISSUE TITLE
Catch/Release bug

### ISSUE THREAD

**Issue by jeffwadsworth** [magefree/mage#2884]
Ruling:
http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=368982
If you cast Catch/Release as a fused split spell, you can sacrifice the permanent you just gained control of.

**Comment by Zerrisx** [comment]
This is - mostly - fixed.  You don't get the proper highlighting to *indicate* that you can sacrifice the newly stolen permanent, but you totally can.
