### ISSUE TITLE
Bug with any cards using attachTo code

### ISSUE THREAD

**Issue by jeffwadsworth** [magefree/mage#2885]
This bug was very recently introduced (within the last week or so).  Any card that uses an effect similar to Boonweaver Giant, Auratouched Mage is affected.  The following error is logged by the server:

Replacement effect without ability: mage.abilities.effects.AuraReplacementEffect@18d8b17f
=>[GAME e406fb5c-f681-4487-9ca4-79c55ef81b18] ContinuousEffects.getReplacementEffectsTexts

These cards usually deal with pulling an Aura card from a location other than the hand/stack and placing it onto the battlefield attached to a permanent.  A ReplacmentEffect window pops up with nothing in it and you cannot continue.  I know that commits on/before 899732c40343b87f3aee4836c0650c9db11869df work fine.  The changes made in some of the future commits were quite extensive in their scope.

**Comment by ingmargoudt** [comment]
I will check the commits as I did some rewrites in that class. All unit tests still passed

**Comment by ingmargoudt** [comment]
I checked my changes on AuraReplacementEffect, and the only thing I changed was modifying an .equals to a ==, I am looking through the rest of my commits as well

**Comment by jeffwadsworth** [comment]
Thanks for checking.

**Comment by ingmargoudt** [comment]
Please follow the discussion in the commit
