### ISSUE TITLE
Predicates.not issue

### ISSUE THREAD

**Issue by jeffwadsworth** [magefree/mage#2889]
Any card that uses Predicates.not is not playable.  Create a deck with any card that uses Predicates.not and try to start a game.  For example, Autumn's Veil or Encrust.  There are about 50 cards with this functionality and it amazes me that no user reported a problem yet.

`Caused by: java.lang.RuntimeException: Uncompilable source code - cannot infer type arguments for mage.filter.predicate.Predicates.OrPredicate<>
  reason: inference variable T has incompatible bounds
    upper bounds: mage.filter.predicate.Predicate<? super capture#2 of ? super T>,java.lang.Object
    lower bounds: mage.filter.predicate.Predicate<? super T>`

**Comment by ingmargoudt** [comment]
Are you on Netbeans? Googling this error message leads only to reports from netbeans caching old code

**Comment by jeffwadsworth** [comment]
I am.  Let me check that issue out.  Thanks.

**Comment by jeffwadsworth** [comment]
It was my client IDE.  Sorry about that.
