### ISSUE TITLE
InvalidPathException causing the client to not load

### ISSUE THREAD

**Issue by draculantern** [magefree/mage#2893]
I tried setting the file path for the card images to a custom folder. And now the client throws this exception on startup. When I run Xmage from the launcher, the console displays

java.nio.file.InvalidPathException: Illegal char <:> at index 29: C:\Users\matth_000\DocumentsC:\Users\matth_000\Documents\games\XMage\xmage\mage-client\IMAGES\symbols

Now clearly the issue is that somehow the image path got the "C:\Users\matth_000\Documents" portion of the file path in there twice. So I need to know if there is a way to manually set the image path outside the client.

Yes I have tried uninstalling and reinstalling it.

**Comment by spjspj** [comment]
Does it look anything like http://imgur.com/Wp2NAHE in your preferences?

**Comment by draculantern** [comment]
Yes, the image files that I have downloaded look like that, but that is not the issue. I cannot even load Xmage to change my preferences

Somehow the image path its trying to read from got set to an invalid file path. I need to know how to change it outside of the client, because that exception is persisting when I try to uninstall & reinstall it.

**Comment by emerald000** [comment]
It is saved in your registry at: HKEY_CURRENT_USER\SOFTWARE\JavaSoft\Prefs\mage\client.
The key is named: card/Images/Path.

**Comment by draculantern** [comment]
Thank you!
