### ISSUE TITLE
Ground Seal stops non-targeting abilities (e.g. Ichorid)

### ISSUE THREAD

**Issue by HansoRaptor** [magefree/mage#2906]
I play Ground Seal in my Legacy Dredge Sideboard against Surgical Extraction and Deathrite Shaman and it never stopped my Ichorid triggers ("you may exile a black creature card") because Ichorid does not target.
Today an opponent played Ground Seal against me and I was not able to use my Ichorids. Xmage said: "Cards cant be targeted in the Graveyard". So I guess this bug only occurs when Ground Seal is controlled by an opponent.

**Comment by JRHerlehy** [comment]
Resolved
