### ISSUE TITLE
All priority and turns being skipped

### ISSUE THREAD

**Issue by breaker1055** [magefree/mage#2924]
The game can enter a state where I cannot do anything, all phases and my turns are skipped. I've enabled all the stop options, f4 f5 f9 etc followed by f3 which does not fix the issue. Opponents have rolled the game back to what should have been my first turn and the same thing happens, it skips straight back to their turn.
It's happened to me a few times. I think it might be tied to enabling f9 before a mulligan decision.

The version is 1.4.21V2

**Comment by DaMachinator** [comment]
This happens to me or my opponent occasionally when we roll back the game while one or more of us still has skip enabled.

**Comment by jeffwadsworth** [comment]
Yes, I bet many of the rollback issues that come up are related to client-side phase settings, etc.  I have never had a issue with it.

**Comment by LevelX2** [comment]
I never was able to reproduce that problem.  Tried agian now, with using F6 before mulligan decision but had no luck again.

**Comment by fireshoes** [comment]
I've definitely had it occur after a rollback. Rollback kicks the Fx buttons off, but occasionally after the rollback is accepted, the game skips all priority for one player on all turns. There seems to be no way to "cancel" it.

**Comment by drmDev** [comment]
I feel like we should just have a parent thread for roll back related issues like we do the UI tearing one

**Comment by jackmeagher** [comment]
Ran into bug several times, all after rollback.

Latest was with both me and opponent on 1.4.23v4.

Bizarrely, if this happens to you, you don't even discard to hand size.

**Comment by JayDi85** [comment]
No longer relevant
