### ISSUE TITLE
Opponent disconnects while they have priority causes nullPointerException and game gets stuck

### ISSUE THREAD

**Issue by breaker1055** [magefree/mage#2925]
In multiplayer games, if an opponent disconnects while they have priority the game spits out a NPE and never moves on past their priority, their clock doesn't run down, everyone else is hosed.

**Comment by jeffwadsworth** [comment]
I will test this.

**Comment by drmDev** [comment]
I've heard about this and similar issues often. I actually haven't played multiple players in a long time to confirm this. Without more details going to close this out. We need actionable issues and it's been over two weeks without the log or full exception detail. Will re open if more information is available.
