### ISSUE TITLE
Xmage client doesn't start  

### ISSUE THREAD

**Issue by AllanPamplona** [magefree/mage#2927]
When i run the launcher and download everything, i run client, then a console is open and i get this:
FATAL 2017-03-05 19:54:41,766 MAGE Client UI error                                                                       =>[AWT-EventQueue-0] EDTExceptionHandler.handle 
java.lang.NullPointerException

I'm running it on linux.

**Comment by AllanPamplona** [comment]
I just changed my hosts and add my hostname.

**Comment by drmDev** [comment]
Do you have the full exception message? Usually indicates the classes and lines. And are you still having this issue or found a way to resolve?

**Comment by Zerrisx** [comment]
Without any response, I'm assuming this was resolved.  If not, feel free to re-open.
