### ISSUE TITLE
Add support for 93/94 (Old School) Format

### ISSUE THREAD

**Issue by rpgdude** [magefree/mage#2935]
Not sure how much work it would take to implement this, but the 93/94 format is a fun way to play with older cards and is gaining popularity. Probably the hardest thing to implement would be manaburn.

**Comment by spjspj** [comment]
I suspect that this would be a seriously large body of work.  Basically a completely different rule set: interrupts, mana burn, damage on the stack - the existing code base would require a *lot* of changes to existing code to handle properly.

**Comment by rpgdude** [comment]
For now, why not just add a new "Constructed - 93/94" format to the game, using the current rules engine (without mana burn, intetrrupts, etc.)?

**Comment by spjspj** [comment]
There is freeform which would let you do this already

**Comment by Zerrisx** [comment]
This format is now implemented (such as it will be).
