### ISSUE TITLE
Fight ability of Ulvenwald Tracker not resolving proprely

### ISSUE THREAD

**Issue by Seawee** [magefree/mage#2940]
Playing Momir basics, opponent activate Ulvenwald Tracker's ability at end of my turn targeting his Bloodhall Ooze (with 2 +1/+1 counters on it) and my Lightning Berserker. I respond by activating my Berserker's ability twice.

Upon resolution of the Traker fight ability, no damage were dealt.

![bug](https://cloud.githubusercontent.com/assets/26239535/23640061/30ffc312-02b9-11e7-9431-42e89b495d33.png)

**Comment by drmDev** [comment]
Don't have much time to look at it right now, but I imagine issue is related to Bloodhall Ooze power and toughness not set at the right layer? Will try to dig into a little more later today if unresolved still.

**Comment by jeffwadsworth** [comment]
Well, I tested this in several games and it always worked fine.  I see your log and it apparently the "fight" effect just disappeared.  If one of the targets is no longer valid, the Tracker will say it fizzled.  I tried fighting my own creatures/opponents and used different pumps/counters on the Ooze and Berzerker.

**Comment by emerald000** [comment]
Did you test with tokens?

**Comment by jeffwadsworth** [comment]
No, but I will test with that.

**Comment by jeffwadsworth** [comment]
I will close this unless someone can reproduce it.
