### ISSUE TITLE
Travis CI not enabled

### ISSUE THREAD

**Issue by ImperatorPrime** [magefree/mage#2949]
It seems like somewhere down the road the Travis CI got shut off. When I navigate to the page, I get the following message:

"This is not an active repository

You don't have sufficient rights to enable this repo on Travis. 
Please contact the admin to enable it or to receive admin rights yourself."

Can an admin have a look or give me the rights to have a look?

**Comment by JRHerlehy** [comment]
I have a Jenkins server up. Just need the bot account added with read/write if we want to go that way.

**Comment by JayDi85** [comment]
Travis works fine.
