### ISSUE TITLE
Selvala, Heart of the Wilds Draw Trigger

### ISSUE THREAD

**Issue by rudyards** [magefree/mage#2951]
Hey, reposting this from the forums:

Bug with Selvala, Heart of the Wilds. The ability should trigger whenever a creature enters the battlefield, whether it is the greatest power or not, and thus can be responded to with pump spells. Right now, the ability behaves as if there is an intervening "if clause", checking to see if it should trigger.

Additionally, if you could reformat Selvala, HotW mana ability to work more like how Manamorphose is programmed, that would be ideal. Right now, the color selection for each individual mana generated is time consuming and slows down games. The same issue exists with Xenagos

**Comment by jeffwadsworth** [comment]
The mana ability will be done shortly.  I will check up on the other part.

**Comment by rudyards** [comment]
As programmed, the ability will not trigger unless the creature has the highest power when it enters the battlefield, which the linked article shows is pretty clearly incorrect.

**Comment by jeffwadsworth** [comment]
Yes, I agree.  That is why I posted the clarification.  It will work as it should.
