### ISSUE TITLE
Hexproof targeting bug in regards to choosing a defender

### ISSUE THREAD

**Issue by jeffwadsworth** [magefree/mage#2952]
http://www.slightlymagic.net/forum/viewtopic.php?f=70&t=20014&p=210622#p210591
If a planeswalker has hexproof, they can't be selected (targeted in the code) by the attacking player.  Of course, this target type (TargetDefender) is not applicable to this restriction.

**Comment by ImperatorPrime** [comment]
Fixed by 495e20ae1a78531f32e9ab32be536a7712685c4d.
