### ISSUE TITLE
Verifying card data test

### ISSUE THREAD

**Issue by jeffwadsworth** [magefree/mage#2955]
Is this test valid?  The cost check is looking for *//* instead of */* on some of the cards.

**Comment by drmDev** [comment]
What is this about?

**Comment by jeffwadsworth** [comment]
The last test at the end of a build of the project...not the test suite for cards/effects.  Mage Verify.  Just build that, etc.

**Comment by Zerrisx** [comment]
Any updates here?

**Comment by JayDi85** [comment]
Verify test works fine. No more actual.
