### ISSUE TITLE
Elsewhere Flasks ability not resolving properly

### ISSUE THREAD

**Issue by Dralin** [magefree/mage#2956]
Whenever you sacrifice the flask and choose a land type this resolves properly. However if a land then enters the battlefield after this effect it gets affected by the flasks ability when it shouldnt.

**Comment by jeffwadsworth** [comment]
The effect is continuous until end of turn.  Any land you control is affected by the effect.  Do you have a ruling link for your version of the event?

**Comment by emerald000** [comment]
@Dralin is correct.

611.2c. If a continuous effect generated by the resolution of a spell or ability modifies the characteristics or changes the controller of any objects, the set of objects it affects is determined when that continuous effect begins. After that point, the set won't change. (Note that this works differently than a continuous effect from a static ability.) A continuous effect generated by the resolution of a spell or ability that doesn't modify the characteristics or change the controller of any objects modifies the rules of the game, so it can affect objects that weren't affected when that continuous effect began. If a single continuous effect has parts that modify the characteristics or changes the controller of any objects and other parts that don't, the set of objects each part applies to is determined independently.

**Comment by jeffwadsworth** [comment]
That is correct.  I will fix the card.
