### ISSUE TITLE
Hybrid mana symbols not displaying in deck editor

### ISSUE THREAD

**Issue by spjspj** [magefree/mage#2962]
The hybrid mana symbols aren't showing in the deck editor (see image).
![image](https://cloud.githubusercontent.com/assets/16917728/23828064/24eb7238-0719-11e7-8b01-abbefa356af9.png)

**Comment by spjspj** [comment]
I did re-download the symbols again in case I'd deleted some somehow but it didn't fix it.

**Comment by DaMachinator** [comment]
Try turning off "Fallback to image-based rendering" in the configs.

**Comment by spjspj** [comment]
It's not turned on.

**Comment by jeffwadsworth** [comment]
Hmm.  Works fine here.
