### ISSUE TITLE
Canadian Highlander - Doesn't have a deck type in server

### ISSUE THREAD

**Issue by spjspj** [magefree/mage#2963]
There is a game type of Canadian Highlander Two player Duel, just not a deck type.

I possibly didn't replicate a config setting to the Mage.Server/release/config/config.xml file.

    <gameType name="Canadian Highlander Two Player Duel" jar="mage-game-canadianhighlanderduel-${project.version}.jar" className="mage.game.CanadianHighlanderDuelMatch" typeName="mage.game.CanadianHighlanderDuelType"/>
    <deckType name="Constructed - Canadian Highlander" jar="mage-deck-constructed-${project.version}.jar" className="mage.deck.CanadianHighlander"/>
    <deckType name="Variant Magic - Canadian Highlander" jar="mage-deck-constructed-${project.version}.jar" className="mage.deck.CanadianHighlander"/>

**Comment by LevelX2** [comment]
Wha there are two deckType entries shown here?
Is that correct/needed?

**Comment by spjspj** [comment]
Hi @LevelX2 That's all that I could find it my local version of config.xml.  I think 'Variant Magic - Canadian Highlander' would be better actually.
