### ISSUE TITLE
Can't attack unless payment bug in regards to AI

### ISSUE THREAD

**Issue by jeffwadsworth** [magefree/mage#2964]
Simple test with Sphere of Safety.  The AI will freeze up with any payment restriction in regards to attacking.

**Comment by drmDev** [comment]
Probably related to https://github.com/magefree/mage/issues/3012 . Sphere of Safety and a couple other similar cards would cause NRE due to a bug resolved in a recent commit mentioned in that issue.

**Comment by drmDev** [comment]
Players still reporting this is an issue vs AI specifically. Works fine in non-AI games.

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.
