### ISSUE TITLE
Declaration in Stone not creating Clue tokens

### ISSUE THREAD

**Issue by DaMachinator** [magefree/mage#2966]
I targeted my opponent's single Gifted Aetherborn with a Declaration in Stone. It exiled the Aetherborn and did not give him a Clue token.

**Comment by jeffwadsworth** [comment]
Already fixed.  Check the code page.

**Comment by FastTadpole** [comment]
Code: https://github.com/magefree/mage/blob/66362aa797b97a20725f0a3a7be153a047be82b3/Mage.Sets/src/mage/cards/d/DeclarationInStone.java
