### ISSUE TITLE
Windows disapear

### ISSUE THREAD

**Issue by marthinwurer** [magefree/mage#2981]
A player that I was playing against had an issue where selection windows (like scry for serum visions or land selection for Hallowed Fountain) disappeared before a selection happened.

**Comment by drmDev** [comment]
this usually can be resolved by clicking on something like your portrait to bring back the window from my experience. it still is a GUI related bug

**Comment by Zerrisx** [comment]
Haven't seen this in forever; closing as CNR, but happy to re-open if anybody has a modern report of it.
