### ISSUE TITLE
Splice onto Arcane bug: Crack the Earth + Overblaze

### ISSUE THREAD

**Issue by Zzooouhh** [magefree/mage#2982]
Just recently I've tried to splice Overblaze onto Crack the Earth, and it just froze the game for me. It gave me the "Splice a card?" option, but after clicking Yes, the action never entered the stack, didn't allow me to tap lands, and neither rollback nor concede were working either. The chatbox was still working, as were the top bar buttons.

**Comment by LevelX2** [comment]
Can't reproduce this. I guess there was a connection issue just at that time.

![splice](https://cloud.githubusercontent.com/assets/2066790/24079525/2e65ba82-0c8a-11e7-8512-c8f1923ca474.jpg)

**Comment by drmDev** [comment]
Very likely a connection issue and unable to reproduce. Will reopen if can duplicate and with game log.
