### ISSUE TITLE
Skyfire Kirin bug: ability can target creatures with non-equal CMC

### ISSUE THREAD

**Issue by Zzooouhh** [magefree/mage#2983]
Self explanatory. Playing an Ore Gorger (5 CMC) with Skyfire Kirin out allowed me to steal Leovold (3 CMC). Didn't test it out on higher CMC creatures however.

**Comment by drmDev** [comment]
unit test duplicated issue. investigating

**Comment by drmDev** [comment]
Resolved in commit 6cde3d3
