### ISSUE TITLE
Multani + Pathbreaker Ibex (+?) bug: persistent trample, possible Shroud bug?

### ISSUE THREAD

**Issue by Zzooouhh** [magefree/mage#2984]
Played Multani in one turn, giving him haste via Hall of of the Bandit Lord. Next turn I've played Pathbreaker Ibex, giving him haste with Hall again, then attacked with both (giving Multani trample until end of turn). However it appears that the EOT trample effect never ended on him, since he kept trample well after that one turn passed and Ibex wasn't around anymore. Maybe a bug with Shroud? I've already had this happen twice.

**Comment by drmDev** [comment]
I'll get in a test for this. Log would help if you have it

**Comment by drmDev** [comment]
Confirmed bug with UT. It appears to be an issue with Pathfinder Ibex itself still granting trample beyond EOT.
