### ISSUE TITLE
Copy/Paste does not work in XMage macOS

### ISSUE THREAD

**Issue by jborden** [magefree/mage#2993]
I am unable copy a clipboard item to XMage in macOS. I cannot copy/paste a card name in the deck editor to search for cards, my password to login or a message to my opponent during a duel. 

```bash
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.12.3
BuildVersion:	16D32
```

**Comment by dalovar** [comment]
This is should be reopened. I experienced the same problem and found out you need to use CTRL + C instead of CMD + C. However, ideally, all shortcuts to manipulate text should be using CMD instead of CTRL if xmage is running on OSX

**Comment by JayDi85** [comment]
Java code example:
https://stackoverflow.com/questions/34767520/copy-paste-shortcuts-only-working-with-ctrl-key-in-osx-java-application

**Comment by Zerrisx** [comment]
Duplicate of #2994
