### ISSUE TITLE
Painter's Servant Functions While Imprisoned In The Moon

### ISSUE THREAD

**Issue by rudyards** [magefree/mage#2997]
If the Painter's Servant loses all abilities (such as due to Imprisoned in the Moon), it still colors everything. This is a bug, based on this thread:

http://www.mtgsalvation.com/forums/magic-fundamentals/magic-rulings/magic-rulings-archives/266491-humility-and-painters-servant

**Comment by emerald000** [comment]
This thread is 8 years old and incorrect now. Layers got changed in M10. 

Nowadays, color-changing effects apply in layer 5 and ability removing applies in layer 6. So even if Painter's Servant loses its ability, it was already applied.
