### ISSUE TITLE
Firecat Blitz flashback asks you to sacrifice mountains twice

### ISSUE THREAD

**Issue by drmDev** [magefree/mage#3002]
When you flashback Firecat Blitz you are asked "How many mountains to sacrifice" and after you select a number, you are then immediately afterwards asked again "How many mountains to sacrifice" and to select some mountains.

Only the response to the second prompt creates X creatures - the first prompt I have no good explanation for. See below where I announce 0 first, then announce 2 on the next prompt.

Possibly an issue with SacrificeXTargetCost in general? 6 cards use it.

7:52 PM: Human announces a value of 0 (Mountains to sacrifice)
7:52 PM: Human flashbacks Firecat Blitz [d21]
7:52 PM: Human sacrificed Mountain [069]
7:52 PM: Human sacrificed Mountain [212]
7:52 PM: Human announces a value of 2 (Mountains to sacrifice)
7:52 PM: Human casts Firecat Blitz [d21] from graveyard
7:52 PM: Human creates a Elemental Cat [fc9] token
7:52 PM: Human creates a Elemental Cat [b42] token
7:52 PM: Human moves Firecat Blitz [d21] from stack to the exile zone

**Comment by drmDev** [comment]
I'll get a test in for this.

**Comment by drmDev** [comment]
Added UT confirming issue ^

**Comment by jeffwadsworth** [comment]
The problem exists with Conflagrate also.  It appears to be related to the Flashback class.

**Comment by drmDev** [comment]
Suspected so much... `Possibly an issue with SacrificeXTargetCost in general? 6 cards use it.`

**Comment by drmDev** [comment]
fixed with https://github.com/magefree/mage/commit/c968a03ff8fb123811ae093beec97380b1cf35d4
