### ISSUE TITLE
Halimar Tidecaller not granting other land creatures flying

### ISSUE THREAD

**Issue by drmDev** [magefree/mage#3005]
Halimar Tidecaller from the Battle for Zendikar block should make all land creatures you control have flying, but this ability currently doesn't work and other creatures don't fly.

(from forums)

**Comment by emerald000** [comment]
By "land creatures", do they mean lands that happen to be creatures, or creatures that are on the land (aka. non-flying)?

**Comment by ingmargoudt** [comment]
A permanent with both the land and the creature subtype

**Comment by jeffwadsworth** [comment]
The code looks fine.  Tested screen uploaded.
![halimarworksfine](https://cloud.githubusercontent.com/assets/1496996/24222228/661764b6-0f1f-11e7-8003-7d3d0041e38f.jpg)

**Comment by drmDev** [comment]
Unable to duplicate with unit test either. Closing.
