### ISSUE TITLE
Genju of the Spires bug?

### ISSUE THREAD

**Issue by drmDev** [magefree/mage#3011]
When Genju of the Spires is recast onto a Mountain after the previous Spirit creature is killed, the new Mountain will become a creature even if the ability isn't used again. This was easily reproducible in a local match vs a computer.

(from forums)

**Comment by ingmargoudt** [comment]
Is this true for the other Genjus as well?

**Comment by ingmargoudt** [comment]
Sounds kinda similar to the crew bug from a while ago

**Comment by jeffwadsworth** [comment]
Confirmed.
