### ISSUE TITLE
Sphere of Safety not allowing payment to attack

### ISSUE THREAD

**Issue by drmDev** [magefree/mage#3012]
Went to attack with a creature and had one forest to pay to Sphere of Safety for my opponents one enchantment and it hung up and would not let me pay the 1 mana to attack. Ended the game because of it. :/

(from subreddit)

**Comment by drmDev** [comment]
from trying to create a test for it, I'm seeing a null ref exception in `PayCostToAttackBlockEffectImpl`, `manaCosts` is null in:

```
    private void handlePhyrexianManaCosts(ManaCosts<ManaCost> manaCosts, Player player, Ability source, Game game) {
        Iterator<ManaCost> manaCostIterator = manaCosts.iterator(); // NRE here
        Costs<PayLifeCost> costs = new CostsImpl<>();
```

**Comment by drmDev** [comment]
Not sure if this would work in the testing framework, but wanted to get some tests in if I could:

```
   @Test
    public void sphereOfSafetyPaidCostAllowsAttack() {        
        /*
        Sphere of Safety {4}{W}
         Enchantment
        Creatures can't attack you or a planeswalker you control unless their controller pays {X} for each of those creatures, where X is the number of enchantments you control.
        */
        String sphere = "Sphere of Safety";
        String memnite = "Memnite";
               
        addCard(Zone.BATTLEFIELD, playerA, memnite); // {0} 1/1
        addCard(Zone.BATTLEFIELD, playerB, sphere);
        addCard(Zone.BATTLEFIELD, playerA, "Forest");
        
        attack(1, playerA, memnite);
        setChoice(playerA, "Yes");
        
        setStopAt(1, PhaseStep.POSTCOMBAT_MAIN);
        execute();
        
        assertLife(playerB, 19); // took the hit from memnite
        assertTapped("Forest", true); // forest had to be tapped
    }
```

At the moment fails during execute() due to NRE mentioned above

**Comment by ingmargoudt** [comment]
I saw in the error logs that this happens quite often.

**Comment by drmDev** [comment]
When I test this manully, I see in the Mage Client logs this exception:
```
java.lang.InterruptedException: sleep interrupted
	at java.lang.Thread.sleep(Native Method)
	at mage.client.dialog.UpdateSeatsTask.lambda$doInBackground$0(TableWaitingDialog.java:426)
	at java.util.Optional.ifPresent(Optional.java:159)
	at mage.client.dialog.UpdateSeatsTask.doInBackground(TableWaitingDialog.java:422)
	at mage.client.dialog.UpdateSeatsTask.doInBackground(TableWaitingDialog.java:402)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

I believe @LevelX2 created an issue about this as well. Not sure if relevant to some of the changes @ingmargoudt did with optionals (isPresent here)

**Comment by drmDev** [comment]
Interesting note: Ghostly Prison does not cause issues but Sphere of Safety. Will need to dig a little further into the differences in code for the cards to see what's going on. That or handle null refs properly where the NRE is thrown with Sphere of Safety.

**Comment by ingmargoudt** [comment]
![doinbackground](https://cloud.githubusercontent.com/assets/4321008/24247776/50c60456-0fcd-11e7-9ab0-655637ba7ff0.jpg)

This is the change I made to this part of the code, left = original, right = changed.

**Comment by ingmargoudt** [comment]
As you can see, the thread sleep was always there, but since its now in the ifPresent block, I print the stacktrace. This did not happen in the original code

**Comment by drmDev** [comment]
Makes sense. Didn't think your code was causing the issue we're seeing.

**Comment by drmDev** [comment]
Dug in a little more, cards like Ghostly Prison are not affected because it directly passes in manaCosts. Cards that are affected are Sphere of Safety and Collective Restraint, both of which have variable calculations for how much needs to be paid and have an overriden method:
```
    @Override
    public ManaCosts getManaCostToPay(GameEvent event, Ability source, Game game) {
        int enchantments = game.getBattlefield().countAll(new FilterEnchantmentPermanent(), source.getControllerId(), game);
        if (enchantments > 0) {
            return new ManaCostsImpl<>("{" + enchantments + '}');
        }
        return null;
    }
```
Not sure how to resolve yet. handlePhyrexianManaCosts needs to be able to retrieve the mana costs calculated from the method above.

**Comment by ingmargoudt** [comment]
Returning null is evil ;)

**Comment by drmDev** [comment]
It wasn't returning null there. I have a fix for it I'm testing more at the moment. I'm sure there likely is a better way of handling this, but this does work.

**Comment by drmDev** [comment]
PR up for review to resolve issue. tested manually and via UTs and all pass.
