### ISSUE TITLE
Declaration in Stone does not allow the exile of more than one creature with the same name.

### ISSUE THREAD

**Issue by drmDev** [magefree/mage#3017]
Declaration in stone does not allow the exile of more than one creature with the same name.

(from forums)

--------------
escplan9: We've multiple bugs with Declaration in Stone recently as well as fixes for them. Do we not have many unit tests on these?

**Comment by drmDev** [comment]
Cannot duplicate with unit tests. Will need to test manually. Close if unable to reproduce.

**Comment by ingmargoudt** [comment]
I see that Declaration in Stone uses a Set of Cards. Should this perhaps be a list instead?

**Comment by emerald000** [comment]
Unless two UUIDs happen to collide (1/2^122), a set will work as well as a list.

**Comment by drmDev** [comment]
Tested manually as well, works as expected. Closing - cannot duplicate manually or through automation.
