### ISSUE TITLE
Game of Chaos bug

### ISSUE THREAD

**Issue by drmDev** [magefree/mage#3022]
Game of Chaos seems to be broken. I'm not sure exactly how the problem works but it looks like whoever wins the first toss will win all subsequent tosses. I've seen this happen twice in multiplayer EDH games.

(from forums)

http://gatherer.wizards.com/Pages/Card/Details.aspx?name=game%20of%20chaos

**Comment by drmDev** [comment]
I was pretty sure it was me who coded that card. Looking back at it 🙈  would not be surprised at all if there's a bug in there somewhere!

**Comment by drmDev** [comment]
Tested it manually and it certainly is a bug now. I know it worked originally when I committed the card. Code ideally should be:

1) Fixed bug
2) Refactor the code for easier maintainability
3) Make sure the message of who won/lost is displayed in the game.

**Comment by drmDev** [comment]
In testing this more, from what I'm seeing, it is not true that the winner of the first flip will always win them all. That will happen sometimes due to probabilities. Difficult card to test extensively. Not sure if I can unit test this.

**Comment by ingmargoudt** [comment]
In case you rewrite the code: turn it into a do-while loop ;)
