### ISSUE TITLE
Savage Ventmaw mana carrying over to next round

### ISSUE THREAD

**Issue by drmDev** [magefree/mage#3026]
Playing against AI in commander format and The Mana from Savage Ventmaw carried over from the last round and was usable (and used to cast Prismatic Omen and Moltensteel Dragon on turn one while having only one mountain) the ai to cast. I've also noticed before in a game vs another player that I would have the mana from Savage Ventmaw when I won the game last match with Savage Ventmaw but the other person started first so it went away when it went to my turn.

(from forums)

**Comment by drmDev** [comment]
haven't been able to duplicate in 2 player game yet.

**Comment by drmDev** [comment]
I imagine the issue is the bolded part below:

Whenever Savage Ventmaw attacks, add RedRedRedGreenGreenGreen to your mana pool. **Until end of turn, this mana doesn't empty from your mana pool as steps and phases end**.

When a win involves an attack from Ventmaw, perhaps there isn't proper cleanup at the end of the game to empty the mana pool? Or at the beginning of the game? Or Ventmaw is overriding that? I wasn't able to reproduce either way.

**Comment by LevelX2** [comment]
Fixed.
