### ISSUE TITLE
Casting Expropriate crashes the game ? 

### ISSUE THREAD

**Issue by drmDev** [magefree/mage#3028]
Final thing from that game, another player cast Expropriate and it crashed the game. Nobody could do anything, so everyone else ended up having to quit.

(from forums)

--------------------
sounds like was a 3-4 player EDH game

**Comment by drmDev** [comment]
In 2 player mode, game does not crash (tested manually).

**Comment by JRHerlehy** [comment]
I manually tested that card up to 4 players on localhost.  Not sure what the issue would be other than say the server near reset.

**Comment by drmDev** [comment]
Will re-open if game log is furnished.
