### ISSUE TITLE
Indomitable Creativity interacts incorrectly with Grafdigger's Cage

### ISSUE THREAD

**Issue by drmDev** [magefree/mage#3029]
Indomitable Creativity interacts incorrectly with Grafdigger's Cage. Creativity is worded so that it exiles the revealed artifacts and/or creatures, THEN puts them on to the battlefield, so they're not entering from the library. But I played a game where I cast Indomitable Creativity on my token, and the token was destroyed but Grafdigger's Cage stopped my creature from entering the battlefield.

Additionally (this problem wouldn't happen if the interaction was proper), I cast another Indomitable Creativity targeting my token and my opponent's Grafdigger's Cage. Here, even if Cage would stop the creatures from entering, it shouldn't stop them now because Cage has been destroyed before cards are revealed. However even after destroying the cage, neither me nor my opponent got a creature on to the battlefield from the cards we revealed.

(from forums)

**Comment by jeffwadsworth** [comment]
Yeah, the code for Indomitable Creativity does not first exile the card, it just puts them on the battlefield.  I will fix it.
