### ISSUE TITLE
Child of Alara not working correctly ? 

### ISSUE THREAD

**Issue by drmDev** [magefree/mage#3030]
there was a huge board when Child of Alara died, and one thing in play was Oblivion Ring, with a Tamiyo, Field Researcher under it. The child's death trigger destroyed both Tamiyo AND the Oblivion Ring and all the other non-land permanents.

(from forums)

**Comment by jeffwadsworth** [comment]
If anything, this is related to the Oblivion Ring.  I would surprised if that didn't work correctly.  Did they have the log?

**Comment by drmDev** [comment]
I'll get in a test for it as well then close this out if log is unavailable.
