### ISSUE TITLE
Nykthos, Shrine to Nyx does not calculate devotion correctly.

### ISSUE THREAD

**Issue by drmDev** [magefree/mage#3039]
Nykthos, Shrine to Nyx does not calculate devotion correctly.

Stronghold Assassin, Graf Harvest, Erebos, God of the Dead on field, tap Nykthos, pay two from swamps, get 1 black mana.

https://www.youtube.com/watch?v=_PehOWGfu8k

(from forums)

**Comment by ingmargoudt** [comment]
Lets make a UT for this case

**Comment by drmDev** [comment]
My thoughts exactly - should have UTs for all issues whenever possible. I've submitted my fair share and will add a couple for this if no one else does :P

**Comment by jeffwadsworth** [comment]
Tested and confirmed.

**Comment by drmDev** [comment]
Very odd... so there already are numerous tests on Nykthos. I added one for this specific scenario and the amount of black mana for the player shows as 0 in the test. Not 100% sure if I'm missing something in the test setup, but looks identical to the other tests and the other assertions seem to confirm everything was setup right. When I step into the code, I see the computed mana for Nykthos to be 4, so I'm at a loss how that becomes "0" as with my UT or "1" as the user demonstrated here.

**Comment by drmDev** [comment]
@LevelX2 updated the test 94f77675ecf87d4cd4fdaaf427e69c9ba216ec4a

**Comment by drmDev** [comment]
Tested manually, issue is resolved. Not sure what change resolved the issue ?
