### ISSUE TITLE
Library of Leng

### ISSUE THREAD

**Issue by DagonX** [magefree/mage#3047]
Library of Leng (http://magiccards.info/5e/en/387.html) clearly states that it only replaces discards caused by effects.
However, in Xmage, it also allows you to replace discards that were part of a cost (such as Cycling). Costs and effects are two fundamentally different things in MtG, and one can never be the other.

**Comment by drmDev** [comment]
"10/4/2004 	You can’t use the Library of Leng ability to place a discarded card on top of your library when you discard a card as a cost, because costs aren’t effects."
http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=202455

**Comment by JayDi85** [comment]
Fixed via 79d40754ed36f1148671bd3bad856ef781a63472
