### ISSUE TITLE
Vexing Devil damage not redirecting to planeswalkers with Furnace of Rath in play

### ISSUE THREAD

**Issue by drmDev** [magefree/mage#3048]
After my opponent played Vexing Devil while I had planeswalker, I chose Vexing Devil to deal damage to me, and opponent chose to redirect damage to the planeswalker. Also my opponent controlled Furnace of Rath. As the result I recieved 8 damage, and walker received none. Opponent said that he clicked "Redirect" when ability was resolving.

(from forums)

**Comment by jeffwadsworth** [comment]
This worked fine for me.

**Comment by drmDev** [comment]
Was pretty sure it was user error related. "Opponent said" not enough to go on obviously.

**Comment by drmDev** [comment]
<font color="#CCCC33">10:16: </font><font color="#20B2AA">Stephanommg</font><font color="White">
casts </font><font color="#FF6347"><a href="#Furnace of Rath">Furnace of
Rath</a></font><font color="White"> [546]</font>
<font color="#CCCC33">10:16: </font><font color="#20B2AA">Stephanommg</font><font color="White">
puts </font><font color="#FF6347"><a href="#Furnace of Rath">Furnace of
Rath</a></font><font color="White"> [546] from stack onto the Battlefield</font>
<font color="#CCCC33">10:16: </font><font color="#20B2AA">Stephanommg</font><font color="White">
..............................................................few turns later..............................................................................

<font color="#CCCC33">10:19: </font><font color="#20B2AA">Stephanommg</font><font color="White">
casts </font><font color="#FF6347"><a href="#Vexing Devil">Vexing Devil</a></font><font color="White">
[465]</font>
<font color="#CCCC33">10:19: </font><font color="#20B2AA">Stephanommg</font><font color="White">
puts </font><font color="#FF6347"><a href="#Vexing Devil">Vexing Devil</a></font><font color="White">
[465] from stack onto the Battlefield</font>
<font color="#CCCC33">10:19: </font><font color="White">Ability triggers: </font><font color="#FF6347"><a href="#Vexing Devil">Vexing
Devil</a></font><font color="White"> [465] - When </font><font color="#FF6347"><a href="#Vexing Devil">Vexing
Devil</a></font><font color="White"> [465] enters the battlefield, any
opponent may have it deal 4 damage to him or her. If a player does,
sacrifice </font><font color="#FF6347"><a href="#Vexing Devil">Vexing Devil</a></font><font color="White">
[465].</font>
<font color="#CCCC33">10:19: </font><font color="#20B2AA">quod</font><font color="White">
has chosen to receive 4 damage from </font><font color="#FF6347"><a href="#Vexing Devil">Vexing
Devil</a></font><font color="White"> [465]</font>
<font color="#CCCC33">10:19: </font><font color="#20B2AA">Stephanommg</font><font color="White">
redirects 4 damage to </font><font color="#90EE90"><a href="#Nissa, Worldwaker">Nissa,
Worldwaker</a></font><font color="White"> [82b]</font>
<font color="#CCCC33">10:19: </font><font color="#20B2AA">quod</font><font color="White">
loses 8 life</font>
<font color="#CCCC33">10:19: </font><font color="#20B2AA">Stephanommg</font><font color="White">
sacrificed </font><font color="#FF6347"><a href="#Vexing Devil">Vexing
Devil</a></font><font color="White"> [465]</font>

Game log furnished. Added UT - unable to reproduce issue still.
