### ISSUE TITLE
Gonti - Seasons Past interaction issue ?

### ISSUE THREAD

**Issue by drmDev** [magefree/mage#3055]
An opponent used a Gonti against me, and took my Ob Nixilis Reignited. He later played it, and I killed my Ob Nixilis. Then later, using Seasons Past, I got Ob Nixilis back in my hand. However, the Ob Nixilis was now uncastable. Has anyone else encountered this?

(from subreddit)

**Comment by drmDev** [comment]
A commenter also attested to seeing a similar issue with Gonti:
https://www.reddit.com/r/XMage/comments/63do2o/bug_with_gonti/
"yeah same thing happened to me the other week when I played against a gonti player but it was some other card instead of ob nix"

**Comment by jeffwadsworth** [comment]
The duration of the effect probably needs to be "WhileInExile".  I will test it out.

**Comment by LevelX2** [comment]
This was reported also in the past as a problem with Gonti, Lord of Luxury.
But it's not reproducable with that reported steps.
There seems to be another co-factor that causes the problem to occur.

Something like: rollbacks, using UI, other card in play.

**Comment by drmDev** [comment]
Would need game log to investigate further. Will re-open if can get a log with it.
