### ISSUE TITLE
Berserk ignores +1/+! counters.

### ISSUE THREAD

**Issue by drmDev** [magefree/mage#3061]
Berserk ignores +1/+! counters.

(from forum)

**Comment by emerald000** [comment]
This bug is because the power boost from Berserk isn't correctly locked in at resolution, but rather checked when it is applied in the layers. Setting the lockedIn flag of BoostTargetEffect should fix this.

**Comment by jeffwadsworth** [comment]
The bug is confined to +1/+1 counters and the like.  If an Aura is used that grants +1/+1, the Berserk works as expected.

**Comment by jeffwadsworth** [comment]
We need to make sure this doesn't affect -1/-1 counters.  That is quite prevalent in this set.

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.
