### ISSUE TITLE
platinum angel , < 0 life, no hand visible

### ISSUE THREAD

**Issue by ingmargoudt** [magefree/mage#3067]
With Platinum Angel in play, and zero or less life, the hand disappears, and no cards can be drawn and no spells can be played. 

(from forums: https://www.slightlymagic.net/forum/viewtopic.php?f=70&t=20299&start=45#p211566 )

**Comment by jeffwadsworth** [comment]
Works fine for me.

**Comment by jeffwadsworth** [comment]
Has anyone verified this one yet?  Still works here.
