### ISSUE TITLE
Urborg, Tomb of Yawgmoth and Blood Moon interaction

### ISSUE THREAD

**Issue by jeffwadsworth** [magefree/mage#3072]
Blood Moon should remove all abilities of the Urborg, but the subtype change is still active in Layer 4.

https://www.slightlymagic.net/forum/viewtopic.php?f=70&t=20299&start=45#p211571

**Comment by drmDev** [comment]
related issue:
https://github.com/magefree/mage/issues/2957

**Comment by jeffwadsworth** [comment]
Using LevelX2 fix for the layer 7 issue to test this.  It works, but currently doesn't play well with static abilities that have dependencies like Opalacense and Enchanted Evening.

**Comment by jeffwadsworth** [comment]
The following code (used in ContinuousEffects.java) fixes this issue (using the fix for Layer 7 that LevelX2 used recently) and works well with the UT's, but is hacky.  I am amazed at how insane the layer rules get.  Anyone have any thoughts on this?

`//The following code is needed for Blood Moon/Magnus of the Moon type cards interaction with Urborg, Tomb of Yawgmoth, etc
        //Tests are needed to verify that it doesn't slow things down too much
        layer = filterLayeredEffects(activeLayerEffects, Layer.TypeChangingEffects_4);
        for (ContinuousEffect effect : layer) {
            HashSet<Ability> abilities = layeredEffects.getAbility(effect.getId());
            for (Ability ability : abilities) {
                if (ability instanceof SimpleStaticAbility
                        && effect.getDependencyTypes().isEmpty()
                        && !(effect instanceof ConditionalContinuousEffect)) {
                    if (abilityActive(ability, game)) {
                        effect.apply(Layer.TypeChangingEffects_4, SubLayer.NA, ability, game);
                    }
                }
                else {
                    applyLayer(activeLayerEffects, Layer.TypeChangingEffects_4, game);
                }
            }
        }`

**Comment by jeffwadsworth** [comment]
A proposed fix.  I consider it hacky, but layers can be a real hellish place.

https://www.slightlymagic.net/forum/viewtopic.php?f=116&t=20475

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.
