### ISSUE TITLE
Mac client cannot connect to server running on windows.

### ISSUE THREAD

**Issue by KungRaseri** [magefree/mage#3079]
I am running an xmage server on my windows 10 desktop.  I have a private VPN that each of the computers are connect to.  The xmage clients on windows are able to connect to the server.  The mac client tries to connect, but eventually stops and just pops up with a message displaying the computer name that the server is running on. Which is the correct computer name, so it has clearly established at least a connection.

The xmage client and server versions all match.
I've tried connecting to the server with both an IP and a hostname. Both result in the message box.

Any help would be appreciated!

**Comment by magenoxx** [comment]
Is it still reproducible? Do you have server and client logs around?
Better to clean existing logs and start both server and client again with sending logs after errors happens.

**Comment by robbix1206** [comment]
I've got the same probleme with 2 Windows Computers,
It works on LAN but display the Computer Name when i try to connect to through internet, and no connection attempt on the servers console 😢

**Comment by nstephenh** [comment]
https://www.slightlymagic.net/forum/viewtopic.php?f=70&t=15898#p171796
This is a similar issue, and it may help solve the problem for you.

**Comment by JayDi85** [comment]
Server's host name must be accessible from client side. [Wiki page have instructions to setup LAN server](https://github.com/magefree/mage/wiki#running-local-server).
