### ISSUE TITLE
xmage.de server broken

### ISSUE THREAD

**Issue by xmagethrowaway** [magefree/mage#3082]
The xmage.de server gives "Server error: Card not found - Plains" errors (or similar for other cards), making it impossible to create or join any games.

**Comment by drmDev** [comment]
Usually this means the server needs a reboot. I'm able to connect, see games, and join games at the moment on xmage.de though. Are you still having this issue?

**Comment by drmDev** [comment]
Is this still ongoing? As mention before this almost always stems from server instability leading to the server needing to be restarted to resolve. Should be resolved upon restart every time.
