### ISSUE TITLE
"You can join a table only one time" Server in test-mode with two clients

### ISSUE THREAD

**Issue by drmDev** [magefree/mage#3083]
When trying to test human vs human on the latest from master, doing the usual

Mage-Server run in test mode
Two instances of mage-client with different user names
Both clients are able to see each other's name in the lobby

When you try to create a New Match ,once you click OK you are given the message "You can join a table only one time" and are unable to continue. You can switch the Other Players dropdown to Computer - Mad and that works fine, but are unable to test human vs human. I do not see any errors logged in Mage.Server or Mage.Client when this occurs. 

Not sure when this started happening - this worked fine a week or two ago.

See screenshot here:
https://i.gyazo.com/e58ce744deab5b107c83d0a2d55af86a.png

**Comment by drmDev** [comment]
Likely resolved with commit fea477dd04c69a0e08204ac7d78e16ea48e2320b ? Will test again later tonight

**Comment by ingmargoudt** [comment]
Correct, that commit should solve it.
