### ISSUE TITLE
Can't play cards with CMC 0 or activate abilities of certain cards

### ISSUE THREAD

**Issue by ThomasLerner** [magefree/mage#3084]
Cards like Lion's Eye Diamond cannot be cast on test server from master, also can't activate abilities of fetch lands or cards like lotus petal that have been put into play using the cheat button.

**Comment by drmDev** [comment]
Lotus Petal works fine for me, but fetches are unable to be activated no matter how they enter the battlefied (cheated on battlefield or played from hand).

**Comment by drmDev** [comment]
More detail: Cannot cast Lotus Petal from hand, but when Lotus Petal is on the battlefield, I can activate its ability (though it seems finicky sometimes having to click it multiple times??). I was able to cast Gitaxian Probe from hand, so casting cards with just Phyrexian Mana costs seems unaffected.

Issues so far:

Fetchlands cannot be activated on the battlefield
0 mana cards cannot be cast from hand

**Comment by ThomasLerner** [comment]
It seems my original post was slightly incorrect, your comment parallels my experience. Are you able to crack Lion's Eye Diamond while it's on the field?

**Comment by drmDev** [comment]
Fixed with commit: c22a8f717ea7ff00f463db49bb97b0b499f1a5f5

Also was affecting Planeswalkers and numerous activated abilities in general.
