### ISSUE TITLE
Greel, Mind Raker's activated ability not costed properly

### ISSUE THREAD

**Issue by DaMachinator** [magefree/mage#3085]
[Link to Gatherer page](http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=24619)

As implemented, the card has an activated ability of:

> {X}{B}, {T}: Target player discards X cards at random.

It should be:

> {X}{B}, {T}, Discard two cards: Target player discards X cards at random.

**Comment by drmDev** [comment]
Confirmed - needs to have additional cost to its ability on discarding two cards. Can possibly extend existing DiscardCardCost or just make a custom cost effect to resolve this for the card.

**Comment by drmDev** [comment]
haha I didn't realize it was going to be even easier than I thought
