### ISSUE TITLE
Leyline of Vitality+Rhys, the redeemed in a token deck

### ISSUE THREAD

**Issue by Dawncaller** [magefree/mage#3110]
If Leyline of Vitality is in your opening hand, you may begin the game with it on the battlefield.
Creatures you control get +0/+1.
**Whenever a creature enters the battlefield under your control, you may gain 1 life.**

My issue isn't necessarily with just this (non-infinite) combo, but with lots of stack effects that trigger with a may ability, I had 30 tokens and used Rhys' double tokens ability and got 30 tokens, but that also meant that I have to sit there for five minutes hitting yes, waiting five seconds for the prompt to appear again and repeating it, I think it would be nice to add an "all yes" or an "all no" option to this to speed up the game as it makes the game quite boring 

By the way, thanks for helping to make this awesome program for us! Keep up the good work!

**Comment by emerald000** [comment]
Have you tried right-clicking the Yes button? I think there should be a "Always yes" or something similar already implemented.

**Comment by Dawncaller** [comment]
I have not as I'm on a laptop, but I'll try, thank you!

**Comment by emerald000** [comment]
That option is bugged currently though it looks like. You might want to follow #3128 for developments.

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.
