### ISSUE TITLE
 'Right Click' menu 'Always Yes'/No buttons show are no longer working

### ISSUE THREAD

**Issue by drmDev** [magefree/mage#3128]
I think that the 'Right Click' menu to say 'Always Yes' when the yes or no choice buttons show are no longer working with 1.4.23 release. Can anyone confirm?

...
confirmed for cards such as Darien, King of Kjeldor, Suture Priest, Soul's Attendant, and Angel's Feather.

- from forums

**Comment by LevelX2** [comment]
![rmb_confirm](https://cloud.githubusercontent.com/assets/2066790/25097904/bed330d0-23a6-11e7-96ee-133f63f04248.jpg)

**Comment by SirPownzalot** [comment]
Hi LevelX2! Just want to point out I'm having the same issue. I used to have the ability to right click on the Yes or No to set a default choice, now nothing comes up if I right click the Yes or No. Did something change? Sorry if the image was supposed to explain it and I didn't get it ._.

**Comment by LevelX2** [comment]
@SirPownzalot 
The image was only to illustrate where the bug is located.
For Omnath you can also deactivate the mana in pool warning in preferences/main.
