### ISSUE TITLE
The card type Legendary seems to be missing on all Legendary Amonkhet cards.

### ISSUE THREAD

**Issue by drmDev** [magefree/mage#3142]
The card type Legendary seems to be missing on all Legendary Amonkhet cards.

**Comment by fireshoes** [comment]
I think there was a change in adding supertypes from a string. The gen-cards script was adding addSuperType("Legendary"), but that produced an error. Changed to addSuperType(SuperType.LEGENDARY) got rid of the error, but maybe something down the line is a problem.

**Comment by fireshoes** [comment]
It seems that all Legendary supertypes are missing.

**Comment by ingmargoudt** [comment]
I changed the supertype from string to enum in a PR a while ago. The gen file was not changed until later so a couple of generated cards would have had compile errors.

**Comment by ingmargoudt** [comment]
Ah it was a display bug apparently.
