### ISSUE TITLE
Currently no way to see your draft deck / sideboard whilst playing a match

### ISSUE THREAD

**Issue by spjspj** [magefree/mage#3146]
Need a way to be able to view your deck and sideboard whilst playing in say a match of 3 games.  
In paper you would only be able to see your sideboard.

This is currently doable via the deck editor whilst playing EDH or constructed but not in a limited draft format.  

Possible ways:
1) (very hacky)  Save the .dck file locally (in say one of ten known historical deck slots) and allow it to be opened via the deck editor as normal.  Maybe needs an additional button to say 'Open current draft deck' that would only be visible whilst in a draft.  Only xmage client changes would be required.
2) (cleaner solution)  Have a copy of the deck sent back for that given user for a given table similar to how it is now for sideboarding but allow it to be viewed only (would require changes to the Deck Editor modes that are available I believe).  Would require client, server and deck editor changes,

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.
