### ISSUE TITLE
Cannot update

### ISSUE THREAD

**Issue by Dawncaller** [magefree/mage#3149]
I've tried a few times now and it's been going for a good four hours now at least and it (the update bar) hasn't moved in at least two. I have 70 megabytes per second download and an upload of 15 so it isn't internet speeds. Anyone have a solution?
Thanks for the help!

**Comment by fireshoes** [comment]
Restart your computer, then open the launcher and click update. Don't do anything else.

**Comment by Dawncaller** [comment]
complete reboot?

**Comment by drmDev** [comment]
yes. full reboot.

**Comment by Dawncaller** [comment]
a day later, it went further than any before but still will not pass the update bar, I left it (the laptop) running overnight and it did not get very far, and when I got back home it had not moved anymore, so I decided to reboot and re-download it, and it is stuck there again

**Comment by Dawncaller** [comment]
update: I cannot even attempt to update now and all I get is this message

> Removing previous versions ...
Reading config from http://xmage.de/xmage/config.json
XMage folder:  /Users/SeverianGeerts/Downloads
XMage Launcher version installed:  0.3.8
XMage Launcher version available:  0.3.8
Java version installed:  1.8.0_102
Java version available:  1.8.0_102
XMage version installed:  1.4.22V0 (2017-03-11)
XMage version available:  1.4.23V1 (2017-04-18)
New version of XMage available
Reading config from http://xmage.de/xmage/config.json
XMage version installed:  1.4.22V0 (2017-03-11)
XMage version available:  1.4.23V1 (2017-04-18)
New version of XMage available
Downloading XMage from http://bit.ly/xmage_1_4_23V1o
Failed to download XMage from http://bit.ly/xmage_1_4_23V1o
Downloading XMage from http://bit.ly/xmage_1_4_23V1o
Java version installed:  1.8.0_102
Java version available:  1.8.0_102
XMage version installed:  1.4.22V0 (2017-03-11)
XMage version available:  1.4.23V1 (2017-04-18)
New version of XMage available
Failed to download XMage from http://bit.ly/xmage_1_4_23V1o
Downloading XMage from http://bit.ly/xmage_1_4_23V1w

**Comment by fireshoes** [comment]
There are direct downloads available in the release thread, if you would like to try doing that instead of the installer.
https://www.slightlymagic.net/forum/viewtopic.php?f=70&t=20439

**Comment by Dawncaller** [comment]
*sigh* in my few days of attempts I've caused more harm than good, and now I get this error while launching client and server, (I still have not done the update :frown) 

> Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=384m; support was removed in 8.0
Error occurred during initialization of VM
java/lang/NoClassDefFoundError: java/lang/Object
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=384m; support was removed in 8.0
Error occurred during initialization of VM
java/lang/NoClassDefFoundError: java/lang/Object
