### ISSUE TITLE
Trespasser's Curse never triggers

### ISSUE THREAD

**Issue by GrayedFox** [magefree/mage#3151]
The Trespasser's Curse now doesn't trigger (even with creatures).

I've only tested this inside a draft situation, but my gut tells me the bug is consistent.

Relevant commits/threads:

1. [Possible cause, but overwritten?](https://github.com/magefree/mage/pull/3118#discussion_r111850617)
2. [Other fix - currently on master](https://github.com/magefree/mage/commit/6156ebf5b668a7f6bdf235d3856d3678fcdba3f4)

**Comment by drmDev** [comment]
Is this still ongoing in 1.4.23v1 ? There was an issue on this closed out by commit addressing it.

**Comment by jeffwadsworth** [comment]
This card works fine.  Tested it multiple times before the fix and after.  Can anyone else verify?

**Comment by GrayedFox** [comment]
Hmm, I can confirm that last night (just after the release of Amonkhet) that it was not working, however it is possible it was fixed shortly after the release?

After work I will try and confirm again if the cards is working or not under various circumstances. Cheers

**Comment by drmDev** [comment]
There was a new version released very recently (v1) with many bug fixes including this one. In v0 it was bugged.

**Comment by GrayedFox** [comment]
I apologize!! 

I just opened my xmage client and was told there was an update! I must have made this report just as the update came out, or maybe moments before, as when I noticed the bug I had only time for one more game before going to sleep and then work (living in Berlin, guessing timezone difference between us maybe some hours!)

thank you for the speedy fix, looking forward to contributing

**Comment by GrayedFox** [comment]
Slightly off topic now - out of interest - do you have unit tests for any of the cards and effects? I'm thinking a good way to start learning Java a bit and getting involved might just be to start writing unit tests for the cards, particularly everything in standard - was thinking [JTest](https://www.parasoft.com/product/jtest/)?

**Comment by jeffwadsworth** [comment]
We have a test suite implemented.  Check https://github.com/magefree/mage/tree/master/Mage.Tests.

**Comment by drmDev** [comment]
We have many unit tests for many cards, see jeff's comment above. We heavily encourage tests for all new cards and issue fixes, but it isn't required. And with people's high demands for the new set to be released for early play, we usually let implementations slide for most cards and rely on people playing the cards to report them, then we add tests as issues arise.

Join us on gitter: https://gitter.im/apps if you want to chat with us in real time about anything development related to the project.

Also if you haven't checked yet, the DEveloper Getting STarted guide will bring you up to speed quickly:
https://github.com/magefree/mage/wiki/Developer-Getting-Started

**Comment by GrayedFox** [comment]
Thanks to both of you. Was just flicking through the tests... after reading through the developer and contribution guide, I'll take a closer look at what I can do to be a part of it. Cool 👍
