### ISSUE TITLE
Hapatra, Vizier of Poisons 2nd ability should only trigger on you placing the counters

### ISSUE THREAD

**Issue by drmDev** [magefree/mage#3157]
I had Hapatra, Vizier of Poisons in play when my opponent played Black Sun's Zenith. Hapatra's second ability triggered for each of my creatures in play. Is that correct? I think it shouldn't trigger when an effect controlled by an opponent puts the counters on creatures.

-- from forums

**Comment by jeffwadsworth** [comment]
Looking at this.
