### ISSUE TITLE
Harsh Mentor CMC Bugged

### ISSUE THREAD

**Issue by mcockle23** [magefree/mage#3158]
Harsh Mentor obly

**Comment by mcockle23** [comment]
Hmm, accidentally hit submit. Harsh Mentor only costs 1 right now but it should cost 1r.

**Comment by fireshoes** [comment]
Update to version 1.4.23v1.

**Comment by mcockle23** [comment]
Thank you. Sorry about that! I didn't see anything in the changelog for this fix so I wanted to make sure someone knew about it.
