### ISSUE TITLE
Couldn't Cast Aftermath Half From Graveyard

### ISSUE THREAD

**Issue by mcockle23** [magefree/mage#3159]
My friend was playing an aftermath card and it wouldn't let him cast the aftermath half from the graveyard. Insult//Injury was the specific card.

**Comment by magenoxx** [comment]
Tested: works as expected.

Please note that 2nd half requires two targets: player AND creature. If there is no legal creature to target then XMage won't allow you to play Injury from graveyard.

Closing as not reproducible.

**Comment by mcockle23** [comment]
Fair enough. I can't remember for sure, but it's entirely possible i didn't have a creature.
