### ISSUE TITLE
Interface bug: "Tables" lobby impossible to access a second time while deck editor is open

### ISSUE THREAD

**Issue by Zzooouhh** [magefree/mage#3161]
On version 1.4.23V0. Steps to reproduce:
1. start Xmage client
2. connect to server
3. disconnect
4. open Deck Editor (can also be done before step 3)
5. connect to server again while deck editor is open
RESULT: the Tables menu containing current games doesn't show up, and is impossible to access via the Switch Panels button (it only shows Deck Editor), although it shows that I'm connected to server. The only way to circumvent this is to disconnect, exit deck editor and connect afterwards (or restart the client obviously).

Strangely enough though, this doesn't happen if you first cancel the initial "Connect" prompt upon starting the client, then open deck editor, and then connect. It doesn't auto-switch to Tables, but it's accessible through the Switch Panels button in this case.

**Comment by magenoxx** [comment]
Confirm, had something similar today - was at the state when connected but no way to get to "Tables" (no options in Switch Panels button).

The only option was to reconnect.

**Comment by magenoxx** [comment]
Again had the same issue today and steps are similar: open Collection Viewer (the same with Deck Editor), then connect and you won't see 'Tables'

**Comment by Zzooouhh** [comment]
As of version 1.4.26V10, I'm not seeing this happen anymore (actually I haven't noticed it in a few version numbers prior), so I guess this can be closed now.
