### ISSUE TITLE
Cruel Reality gives player option when it shouldn't

### ISSUE THREAD

**Issue by skeate** [magefree/mage#3162]
>At the beginning of enchanted player's upkeep, that player sacrifices a creature or planeswalker. If the player can't, he or she loses 5 life.

My opponent had a JTMS out, and was apparently given the choice between sacrificing it and losing 5 life. As worded, he should have had to sac the Jace.

Excerpt from the game log:

> 21:11: Turn 9 Hummus (20 - 17)
> 21:11: Ability triggers: Cruel Reality [7cb] - At the beginning of enchanted player's upkeep, that player sacrifices a creature or planeswalker. If the player can't, he or she loses 5 life.
> 21:11: Hummus loses 5 life
> 21:11: Hummus draws a card
> 21:12: Hummus casts Sensei's Divining Top [08a]
> 21:12: Hummus puts Sensei's Divining Top [08a] from stack onto the Battlefield
> 21:12: Hummus activates: Draw three cards, then put two cards from your hand on top of your library in any order. from Jace, the Mind Sculptor [297]

**Comment by jeffwadsworth** [comment]
That is correct.  Checking it out.
