### ISSUE TITLE
Permeating Mass not functioning correctly vs creatures with */* P/T

### ISSUE THREAD

**Issue by drmDev** [magefree/mage#3167]
Permeating Mass seems bugged, when it damages a creatue with */* values like Dungrove Elder or Wayfaring Temple

the damaged creature should become a copy of Permeating Mass with 1/3 stats, but it keeps the stats from before

- from forums

**Comment by drmDev** [comment]
adding UTs...

**Comment by LevelX2** [comment]
The copy effect of  Permeating Mass is applied during the Layer.CopyEffects_1.
The problem is that the Dungrove Elder P/T effect is always later applied during the Layer.PTChangingEffects_7.

So to properly solve this I first need to understand the concerned rules. Where is our implementation wrong.

Any ideas from the rule gurus how this is handled by the rules exactly?

**Comment by Simown** [comment]
@drmDev does that unit test fail on purpose then? I think we should ignore failing tests and link the bug report to them, and have 100% pass rate in the dev end. Then restore the ignored test after the bug has been fixed to confirm. 

I was seeing a couple of flashback and cycling tests failing yesterday too - but I don't know if I'm the cause of those yet.

**Comment by jeffwadsworth** [comment]
@LevelX2 I will check with some MTG judges on this issue.

**Comment by drmDev** [comment]
@Simown you do not ignore a unit test because it is failing. The unit tests are there so we know if we broke something when we made a change, or if we resolved an issue by making a change. If the unit test is correctly setup (assuming the rules interpretation is correct, the assertion should be correct), then the issue is with the code handling it.

@emerald000 want to chime in on the ruling here?

**Comment by jeffwadsworth** [comment]
@LevelX2 Here is a chat log of the explanation.

<Hydra18> Hello.  I have a question concerning the correct interaction between Permeating Mass and Wayfaring Temple.  Does the Wayfaring Temple P/T become 1/3 if combat damage is dealt?
<luma> !permeating mass&wayfaring temple
<Datatog> Permeating Mass {G} |Creature -- Spirit| 1/3 Whenever Permeating Mass deals combat damage to a creature, that creature becomes a copy of Permeating Mass. · EMN-R · Vin,Leg,Mod,Std
<Datatog> Wayfaring Temple {1GW} |Creature -- Elemental| */* Wayfaring Temple's power and toughness are each equal to the number of creatures you control. / Whenever Wayfaring Temple deals combat damage to a player, populate. · MM3-U,RTR-R · Vin,Leg,Mod
<luma> Hydra18, yes, it becomes a copy of permeating mass
<Hydra18> @luma, ah.  We were wondering about the layers here.  The copy being layer 1 and the P/T being layer 7.
<Staunch> Hydra18: Permeating Mass's effect isn't a P/T modifying effect, it's a copy effect. It applies completely in Layer 1.
<luma> when the copy effect is applied in layer 1, wayfaring temple doesn't have any of its own text left
<luma> its name is permeating mass, its mana cost is G, it's a creature - spirit, it's 1/3, it has the ability of permeating mass

**Comment by LevelX2** [comment]
> Here is a chat log of the explanation.

Ok, thank you. That means we need to check during the resolution of continuous effects of layer PTChangingEffects_7 (and also other layers) if the object currently still has this ability the effect was produced by. This check is completely missing now.

**Comment by Simown** [comment]
@drmDev  I accept you shouldn't ignore a unit test that's failing, if you caused it to fail. But, if all the tests don't pass how do I know that my code broke one of the unit tests or someone just added a failing test? I propose at least commenting the failing test to broadcast the fact.

**Comment by drmDev** [comment]
Run the tests before your changes. Run the tests after your changes. This should be a separate discussion outside of this issue regardless.

**Comment by jeffwadsworth** [comment]
This issue appears to be the same one plaguing the Layer 4 type changing/ Layer 6 Add/Remove Abilities issue with Blood Moon and Urborg.  No check to verify that an effect has removed the ability, etc.
