### ISSUE TITLE
Seeker of Insight's activated ability is usable without casting a noncreature spell.

### ISSUE THREAD

**Issue by drmDev** [magefree/mage#3175]
Seeker of Insight's activated ability is usable without casting a noncreature spell.

- from forums

**Comment by jeffwadsworth** [comment]
Worked fine for me.

**Comment by drmDev** [comment]
additional log text from forum user:

2:44 AM: Turn 26 Computer Player 2 (3 - 23)
2:44 AM: Computer Player 2 draws a card
2:44 AM: Computer Player 2 casts Nef-Crop Entangler [d64]
2:44 AM: Computer Player 2 puts Nef-Crop Entangler [d64] from stack onto the Battlefield
2:44 AM: Ability triggers: Trespasser's Curse [8eb] - Whenever a creature enters the battlefield under enchanted player's control, that player loses 1 life and you gain 1 life.
2:44 AM: Computer Player 2 loses 1 life
2:44 AM: Raleth gains 1 life
2:44 AM: Computer Player 2 activates: draw a card, then discard a card. from Seeker of Insight [6b1]
2:44 AM: Computer Player 2 draws a card
2:44 AM: Computer Player 2 discards Commit // Memory [6cc]
2:44 AM: Computer Player 2 puts Island [aef] from hand onto the Battlefield
2:44 AM: Computer Player 2 plays Island [aef]

**Comment by jeffwadsworth** [comment]
Yes, I saw that and used a Trespasser's Curse on myself to enable it to trigger.  If a non-creature spell was not cast, I could not activate the ability.

**Comment by drmDev** [comment]
possible AI issue then?

**Comment by magenoxx** [comment]
Also couldn't reproduce but can be AI issue in case emulation affects watcher. Let me try it

**Comment by magenoxx** [comment]
No, couldn't reproduce - nether AI simulating cast, nor casting Shock causes an issue.
Everything works as expected.

**Comment by drmDev** [comment]
I know sometimes the AI has poor handling - like if you try to take over their turn, you are never given priority and the AI just continues to play their turn. Was thinking here the AI was somehow disregarding the clause on the card needing to be non-creature spell to activate the ability.

Unable to duplicate the issue either way...
