### ISSUE TITLE
Battle Screech flashback doesn't allow to cancel playing

### ISSUE THREAD

**Issue by magenoxx** [magefree/mage#3177]
In case you play Battle Screech flashback cost - tap 3 creatures, you have no option to cancel it.
UI suggests to tap 3 creatures with counter (0/3) and no button to cancel cast.

The same for Dread Return.

**Comment by drmDev** [comment]
I think we have this issue in multiple areas where we should be able to take back the move but cannot

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.
