### ISSUE TITLE
Glyph Keeper countering even when targetted twice

### ISSUE THREAD

**Issue by drmDev** [magefree/mage#3180]
In a game against another player (1v1 sealed), I had a Glyph Keeper on board (cloned with Vizier of many faces).

First I played a Soulstinger and targeted the Glyph Keeper, the ability was countered. Then on the same main phase I played a Cartouche of Strength targeting the Glyph Keeper, that was also countered. Only the first should have been countered.

-from forums

**Comment by drmDev** [comment]
Adding UTs...

**Comment by HanClinto** [comment]
Just tested this -- was not able to reproduce.  

I used a Soulstinger's triggered ability on my own Glyph Keeper, which properly countered the ability. 
 Then during the same main phase, I played Cartouche of Strength on my Glyph Keeper, and it was not countered -- it resolved and the fight trigger correctly resolved as well.

**Comment by drmDev** [comment]
reproduced via UT even without doing it on a clone of Glyph Keeper

**Comment by jeffwadsworth** [comment]
A Glyph Keeper that is copied by a Vizier of Many Faces does not work with the counter ability.  It will counter every targeted spell.

**Comment by drmDev** [comment]
the UT failing could possibly be from UT known issue with some targetting matters cards such as this and Reality Smasher. see https://github.com/magefree/mage/issues/3038 . surprised the two Bolt test passes still from it.

**Comment by jeffwadsworth** [comment]
Okay, I am just going to steal LevelX's code for the Kira, Great Glass Spinner and use it to implement the Glyph Keeper.  That works fine, except in regards to spells like Kolaghan's Command, which also doesn't work in Kira's case.
