### ISSUE TITLE
client/server won't launch

### ISSUE THREAD

**Issue by Dawncaller** [magefree/mage#3182]
Finally got the game to be in the right version, the only problem now is that when I try to launch it I get that error
> Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=384m; support was removed in 8.0
Error occurred during initialization of VM
java/lang/NoClassDefFoundError: java/lang/Object
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=384m; support was removed in 8.0
Error occurred during initialization of VM
java/lang/NoClassDefFoundError: java/lang/Object
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=384m; support was removed in 8.0
Error occurred during initialization of VM
java/lang/NoClassDefFoundError: java/lang/Object<

**Comment by drmDev** [comment]
How are you trying to launch this? Are you using the XMage launcher, where there's buttons for "Launch Client" amongst others at the bottom and selecting Launch Client? or something else entirely?

**Comment by Dawncaller** [comment]
drmDev, that's the terminal window that pops up when I hit the "launch client" or "launch server" in the launcher, I've been trying to update xmage and was messing with some files attempting to move everything to a thumb drive to redownload xmage, so I probably messed something up. Thanks for the help, you guys have been awesome. Keep up the good work

**Comment by drmDev** [comment]
I'm not sure from that error what that indicates - either an issue with Java or your XMage install. given how much messing around it sounds like you did with this issue and the one where you had troubles updating it's possible your install is busted. I think on the subreddit a user there wrote a more indepth guide for troubleshooting all sorts of XMage issues such as cleanly uninstalling and reinstalling Java and XMage

**Comment by drmDev** [comment]
Link to that guide:
https://drive.google.com/file/d/0B1n0u_Vny_add013ZDVuSGJwMWM/view

And our subreddit if you haven't seen:
https://www.reddit.com/r/XMage/

**Comment by ingmargoudt** [comment]
You can ignore the MaxPermSize warning. The error message seems to me telling that a wrong version of Java is installed (32/64 bits). It cant find java.lang.object class , which is the base of all java code :)

**Comment by ingmargoudt** [comment]
http://stackoverflow.com/questions/11808829/jre-1-7-returns-java-lang-noclassdeffounderror-java-lang-object

**Comment by JayDi85** [comment]
No longer relevant. It's a "java not install by xmage" error.
