### ISSUE TITLE
Cycling cards show as playable in hand without available mana to pay the cost

### ISSUE THREAD

**Issue by fireshoes** [magefree/mage#3187]
Cycling cards get a highlighted frame as though they can be used even without any mana available.

**Comment by magenoxx** [comment]
Just wanted to report the same: with Forest in play, Desert Cerotodon (Cycling R) was displayed as playable

**Comment by magenoxx** [comment]
The root cause is the same: CyclicAbility now has CyclingCost with generic mana=0

**Comment by magenoxx** [comment]
Connected issue: #3148

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.
