### ISSUE TITLE
Tooltip in Draft pick view stops cards from selecting

### ISSUE THREAD

**Issue by magenoxx** [magefree/mage#3193]
In draft: it's annoying to see tooltip window appearing all the time that stops you from clicking on card to select or pick.

Solution: either don't display tooltip in Draft pick view at all (we have image on the left bottom anyway) or add button to disable it or show it only when button (e.g. Ctrl) is pressed

**Comment by LevelX2** [comment]
You can change the duration in the preferences main how long it needs to show the tooltip.
You can set it to 0 to stop showing the tooltip.
Or you can set it to a value like 1000 ms or more, to not get bothered so often.

**Comment by magenoxx** [comment]
Yes, told me in gitter, works like a charm. But still need time to figure out it - so probably adding this information into draft view is good from UIX perspective.

**Comment by Zerrisx** [comment]
Looks like this was resolved, and also the tooltip handling feels much better these days than it used to in general.
