### ISSUE TITLE
Work towards publishing releases in torrents

### ISSUE THREAD

**Issue by magenoxx** [magefree/mage#3194]
Due to big traffic lots of players are not able to download new version.
One of the options to investigate is torrents but the question is how to connect it with our launcher.

fireshoes says:
The launcher already has an option for supporting that, iirc.

**Comment by LevelX2** [comment]
Yes, Betasteward has it build in the launcher.
I never tested if this works and how to initate the seed.
Problem is probably to have enough users to enable the torrent.

**Comment by JayDi85** [comment]
Noticed that in the latest release files was moved to github. Too big traffic is no more problem.
