### ISSUE TITLE
Combat Celebrant interaction 

### ISSUE THREAD

**Issue by ingmargoudt** [magefree/mage#3195]
"Combat Celebrant is apparently bugged. I had two of them, swung both, exerted one to untap the rest and get another combat. Second combat, swing with the other celebrant, exert it to untap the rest and get another combat. Third combat, swing everything and I get to exert the one which had already been exerted this turn." 

From forums : https://www.slightlymagic.net/forum/viewtopic.php?f=70&t=20440&sid=0a8b1786ac5a46578eb1e72e84af7401&start=45#p212001

Combat Celebrant might need an "IsExertedThisTurnWatcher" for this?

**Comment by jeffwadsworth** [comment]
I tested this and it worked fine.  Did you see something else in your testing?

**Comment by ingmargoudt** [comment]
ah the watcher is internal to the ExertAbility, makes sense.

**Comment by drmDev** [comment]
add tests

**Comment by drmDev** [comment]
Multiple users confirming this still is an issue. One mentioned possible interaction with Always Watching. Add unit tests.

**Comment by jeffwadsworth** [comment]
I literally tested this 4 times and it worked perfectly.  It took 2 minutes to test in a test server/client environment.  The Always watching just made the destruction that much sweeter and didn't interfere with anything.  I could not Exert a creature more than once a turn.  A log of what these guys are doing would be nice.

**Comment by jeffwadsworth** [comment]
![combatcelebrant](https://cloud.githubusercontent.com/assets/1496996/25320153/3185afe6-286a-11e7-9877-3f784ed800e2.jpg)

**Comment by drmDev** [comment]
Actually cannot unit test this specific scenario due to UT Framework issues with cards having the same name - unable to differentiate between Combat Celebrant #1 and Combat Celebrant #2 .Will need to ask users for game logs and go from there.

**Comment by drmDev** [comment]
![cc-always-watch](https://cloud.githubusercontent.com/assets/11060241/25414661/d4783af6-2a00-11e7-8b80-459618b7c0f6.png)
Was able to attack again with exerted Celebrant if Always Watching is on battlefield. Also able to reproduce by unit test. Was not able to have infinite combat phases with just one Celebrant, but there definitely is a bug. Doing more testing...

**Comment by drmDev** [comment]
Confirmed with 2 Celebrants + Always Watching you get infinite combat phases by attacking with one Celebrant then attacking with the other next time and repeat infinitely.
![cc-always-watch-inf](https://cloud.githubusercontent.com/assets/11060241/25414762/7728a394-2a01-11e7-9eb6-af50cd07f797.png)

**Comment by drmDev** [comment]
Also confirmed any sort of Untap Creature / Vigilance effect allows infinite combat phases.

**Comment by drmDev** [comment]
Update: I need to RTFC and rules better. Celebrant is allowed to attack again if he is exerted. Just not allowed to be exerted again on the same turn to grant additional combat phases. Not able to duplicate the issue then, just misunderstood the interactions here.

**Comment by drmDev** [comment]
I'm going to guess then the issue was the users misread the first line as Celebrant not being able to attack again while exerted. Will re-open if someone can produce a log demonstrating infinite turns with it exerting more than once a turn
