### ISSUE TITLE
Future Sight shows the second card of your library if you attempt to cast the top card of your library

### ISSUE THREAD

**Issue by spjspj** [magefree/mage#3196]
If I have Future Sight in play, and I go to play the top card (happens to be Merchant Scroll), I'm then seeing the next card underneath. I can then cancel casting merchant scroll, but I now have knowledge of my second card.

From gatherer:
6/8/2016 If the top card of your library changes while you’re casting a spell or activating an ability (perhaps because that top card is the card you’re casting) the new top card won’t be revealed until you finish casting that spell or activating that ability.

**Comment by HanClinto** [comment]
Likely related to #484
