### ISSUE TITLE
Glorious End cast, game hanged

### ISSUE THREAD

**Issue by fireshoes** [magefree/mage#3198]
I attacked with 4 creatures. My Gust Walker exert trigger went on the stack (after choosing to exert). Opponent cast Glorious End, but no effect seemed to occur. The end the turn text was in the in-game log, but Glorious End and the exert trigger still showed on the stack. My timer continues to count down. Attempted to rollback, but it did not do anything except switch to the opponent's timer counting down instead (still in attacks, etc).

**Comment by jeffwadsworth** [comment]
This looks like a nightmare to work out....with the extra combat steps, etc.

**Comment by drmDev** [comment]
Is this still occurring with the commit referenced in #3221 ?  commit 80beebc

**Comment by LevelX2** [comment]
The fix only concerns activated abilities. Never found a problem with spells ending the turn.

**Comment by LevelX2** [comment]
Should be fixed with 80beebccf58400ac1ee0118d76e4cddaa2fec422 (1.4.23V3).
