### ISSUE TITLE
Embalmed creatures use card art instead of token art

### ISSUE THREAD

**Issue by fireshoes** [magefree/mage#3201]
Each creature with embalm has an associated white Zombie creature token of itself, but the game displays the original card art instead. The rendered images of the token does change it to show it as a white Zombie token with no mana cost, zooming in on it shows the card instead of the token.

**Comment by grumble9684** [comment]
Yep, still happening as of October 2018. As far as I can tell the game doesn't call for a token image when using Embalm, just straight up copies the original image from /plugins/images/set

**Comment by JayDi85** [comment]
Fixed via 9df32a571be84079777ad9fa584ff369cec0757c
