### ISSUE TITLE
Ojutai's command, returning Baral + counter creature won't trigger baral's ability

### ISSUE THREAD

**Issue by everythingEzra2** [magefree/mage#3202]
In the following scenario baral's loot ability isn't triggered.

Baral, Chief of Compliance in my graveyard, opponent had a creature in the stack.
1) I cast Ojutai's Command with modes: Return creature from graveyard to battlefield (targeting Baral), and counter their creature spell.
2) Ojutai's command resolves, do the modes in the order they appear in the card. I put Baral onto the battlefield, and he is around to witness the creature be counted.
3) Baral's loot ability isn't triggered.

**Comment by jeffwadsworth** [comment]
Tested this and it worked fine for me.

**Comment by drmDev** [comment]
@everythingEzra2 do you have a game log? We are unable to duplicate the issue with automated or manual testing at this time.

**Comment by everythingEzra2** [comment]
Thanks guys.
I don't have a log.

I'll try to reproduce. And post steps here

**Comment by drmDev** [comment]
If you run into this again, find the log and let us know and we can re-open this for investigation. Game logs are found within "mage-client/gamelogs/"
