### ISSUE TITLE
Cabal Therapy flashback not working anymore

### ISSUE THREAD

**Issue by drmDev** [magefree/mage#3204]
"doesnt flashback from graveyard is glitched . :("

- from subreddit

not sure if just playing on old version or what... will need to test. think we only have tests for Dread Return and Battle Screech from recent changes.

**Comment by jeffwadsworth** [comment]
This was fixed.  Check https://github.com/magefree/mage/commit/9b5a04697cd6a7f4e546c4d2bec444901c2cd11b

**Comment by drmDev** [comment]
Wasn't sure if Cabal Therapy was specifically tested. I know we have automated tests in place for a few of the cards noted, but not Cabal Therapy in there. I can add automated tests later. Just confirming if it was tested manually with the changes in that commit. If so we can close this out. Just was reported very recently so wanted to double check.

**Comment by drmDev** [comment]
thought this fix made it in v1, that explains my confusion. that fix wasn't until next release v2

**Comment by skeate** [comment]
I'm on V2 and this still seems to be an issue.

**Comment by drmDev** [comment]
re-investigating...

**Comment by skeate** [comment]
I tried it on a local server and it worked, so now I'm not sure. Trying again on xmage.de

**Comment by drmDev** [comment]
Unit Tests still pass and testing on local server confirms this issue is resolved. If there still is an issue, it is a versioning related issue with the user's machine or the server they are playing on.

![bs-ct](https://cloud.githubusercontent.com/assets/11060241/25309619/e383ccf8-279f-11e7-8d0b-cfb02f83908b.png)
