### ISSUE TITLE
Decimator Beetle issues

### ISSUE THREAD

**Issue by drmDev** [magefree/mage#3212]
Decimator Beetle's ability to remove a -1/-1 counter from a creature I control, upon attacking, will not trigger when I declare the beetle as an attacker, and happens only when i have a creature on my board with a -1/-1 counter, and my opponent has no creatures on their side of the field. However, the ability works as intended in any other circumstance if my opponent has a creature on the battlefield. Furthermore, the card's second ability states that i choose 'up to one' target creature my opponent controls, however, I am required to choose target creature my opponent controls, when I should be able to resolve the ability without doing so. Should be noted that the second ability is not a redistribution of the counter, however two seperate events.

-- from forum

**Comment by jeffwadsworth** [comment]
Decimator Beetle’s second ability can target any creature you control, not just one with a -1/-1 counter on it. It’ll put a -1/-1 counter on the opponent’s creature even if there isn’t one to remove from your creature.
If one target of Decimator Beetle’s second ability becomes illegal, the other will still be affected.

http://gatherer.wizards.com/Pages/Card/Details.aspx?name=Decimator%20Beetle
