### ISSUE TITLE
ManaOptions.addManaWithCost iterates unwanted 

### ISSUE THREAD

**Issue by LevelX2** [magefree/mage#3219]
In some constellations ManaOptions.addManaWithCost iterates.
Probably some special lands are involved but I can't identify the causing permanents from the log.

![manaoptions addmanawithcost](https://cloud.githubusercontent.com/assets/2066790/25313354/1a5bb352-282d-11e7-99a7-b4817cdcb48a.jpg)

**Comment by jeffwadsworth** [comment]
Definitely any card with an activated mana ability involving non-mana costs.  Example, Nykthos, Shrine to Nyx.

**Comment by LevelX2** [comment]
Fixed recently.
