### ISSUE TITLE
Games locked in Iterating during EndTurnEffect

### ISSUE THREAD

**Issue by LevelX2** [magefree/mage#3221]
![endturn](https://cloud.githubusercontent.com/assets/2066790/25314363/ce8b12d6-2842-11e7-84b5-6ff4551a7dec.jpg)

![endturncpu](https://cloud.githubusercontent.com/assets/2066790/25314391/377e479a-2843-11e7-9f20-a7fc58ea7314.jpg)

Any ideas, what card(s) could cause the problem?

**Comment by fireshoes** [comment]
Glorious End from Amonkhet

**Comment by LevelX2** [comment]
180 second recording this morning before the restart:

![endturnproblem](https://cloud.githubusercontent.com/assets/2066790/25370739/f677cd7a-298c-11e7-903b-6377a8833d59.jpg)
