### ISSUE TITLE
AI able to cast Bone Picker first turn (morbid issues with AI?)

### ISSUE THREAD

**Issue by drmDev** [magefree/mage#3228]
I saw ai cast Bone Picker first turn from Swamp.
- from forums

I suspect if this is occurring the AI might be bugged on Morbid condition being met or not.

**Comment by drmDev** [comment]
user added logs:


https://www.dropbox.com/s/pk7x9nx3chghltk/log1.txt?dl=0
https://www.dropbox.com/s/ofv8pwc5ecsyst4/log2.txt?dl=0
https://www.dropbox.com/s/o80jszel2ibgq4k/log3.txt?dl=0

On game 3, I saw, casting Bone Picker first turn from Swamp.

I can't reproduse that...

**Comment by stravant** [comment]
Have you tried reproducing by having Morbid satisfied on the last turn of the previous game? Maybe it's a problem with the MorbidWatcher not being properly reset until the end of the first turn, rather than at the start of the game.

**Comment by ingmargoudt** [comment]
MorbidWatcher does not have a override reset method it seems
