### ISSUE TITLE
(From RRREnchant) - Add a Token / Emblem viewer into the Viewer

### ISSUE THREAD

**Issue by spjspj** [magefree/mage#3236]
More easily see all the different tokens and whether you have the images for them or not.

**Comment by LevelX2** [comment]
So the viewer would make at least a little bit of sense.

**Comment by spjspj** [comment]
Have made some progress on this.  However need to do further reorg of the tokens in particular for it to be usable.

**Comment by spjspj** [comment]
I believe this is done now.
