### ISSUE TITLE
Valakut, the Molten Pinnacle not triggering ? 

### ISSUE THREAD

**Issue by drmDev** [magefree/mage#3238]
Played scapeshift the Valakut, the Molten Pinnacle trigger does not activate after fetching the mountains, please double check.

- from forums

**Comment by jeffwadsworth** [comment]
There needs to be a checkStateAndTriggered() there.  Let me test.

**Comment by jeffwadsworth** [comment]
This worked for me.  Perhaps the player did not sacrifice at least 6 lands to grab at least 6 mountains.

**Comment by drmDev** [comment]
We also have 6 unit tests on this card and all passing. I'll ask for a game log and re-open if provided.
