### ISSUE TITLE
Gonti cards not casting properly

### ISSUE THREAD

**Issue by MasN2** [magefree/mage#3242]
Gonti cannot cast off-color cards off the ETB ability when cast using mana in the mana pool.

For example, I had 6 swamps. I cast Thran Dynamo, then used the Thran Dynamo and the remaining 2 swamps to cast gonti, exiling chain of vapor. Then, when I tried to cast chain of vapor, it wouldn't let me click the diamond in my mana pool.

**Comment by LevelX2** [comment]
Same cause as #2581

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.
