### ISSUE TITLE
Shadow of the Grave + New Perspectives cycling "count" incorrect

### ISSUE THREAD

**Issue by drmDev** [magefree/mage#3246]
summary: Shadow of the Grave cycle count interrupted by opponent cycle (?)

I'm not sure how xmage is handling discard/cycle count at the moment for Shadow of the Grave, but I was going off with New Perspectives and had cycled maybe 5 cards. Then my opponent cycled a dual land, presumably so that he could just F6 the rest of my turn. I had one more card to cycle before my Shadow of the Grave, but then it only returned that one card.

Forgot to take a screenshot, but here's a log if needed: https://pastebin.com/T8vG9WF4

edit: I start cycling on the pertinent turn on line 275 of the log

edit2: Shadow seems even more broken now on V3, I got maybe 7 cards back when I cycled over 25, and this is independent of any opponent action.

-- from forums

**Comment by jeffwadsworth** [comment]
The watcher was broken by this commit.  
https://github.com/magefree/mage/commit/79648eb7ea268a58b1de9afac350927bcce9595b

**Comment by drmDev** [comment]
https://github.com/magefree/mage/commit/576ccdb34ab027c7f15952b34eac6a5ae728dfc9 should fix it
