### ISSUE TITLE
Launcher update fails

### ISSUE THREAD

**Issue by RRRenchant** [magefree/mage#3249]
Now tried to make reinstall
Deleted manually folders java, xmage - and files installed.properties, xmage.dl, xmage_launcher.log, XMageLauncher-0.3.8.jar
Downloaded launcher from xmage.de, started it
It said "it looks that's the first time you running xmage bla-bla...", downloaded dedicated java, then started downloading update
Funny, but that download broke the same way
Launcher's black log contents:
Reading config from http://xmage.de/xmage/config.json
XMage folder: C:\1\XMage
XMage Launcher version installed: 0.3.8
XMage Launcher version available: 0.3.8
Java version installed:
Java version available: 1.8.0_102
Java not found
XMage version installed:
XMage version available: 1.4.23V3 (2017-04-25)
XMage not found
Downloading Java from http://download.oracle.com/otn-pub/java/jdk/8u102-b14/jre-8u102-windows-x64.tar.gz
Installing Java ...Done
Downloading XMage from http://bit.ly/xmage_1_4_23V3o
Installing XMage ...Java version installed: 1.8.0_102
Java version available: 1.8.0_102
XMage version installed:
XMage version available: 1.4.23V3 (2017-04-25)
XMage not found
installed.properties file contents:
---XMage Properties---
Wed Apr 26 14:29:25 MSK 2017
xmage.launcher.version=0.3.8
java.version=1.8.0_102
xmage.client.console=true
xmage.launcher.guisize=16
xmage.client.javaopts=-Xms256m -Xmx512m -XX\:MaxPermSize\=384m -XX\:+UseConcMarkSweepGC -XX\:+CMSClassUnloadingEnabled
xmage.home=http\://xmage.de/xmage
xmage.server.console=true
xmage.version=
xmage.server.javaopts=-Xms256M -Xmx1G -XX\:MaxPermSize\=384m
xmage.torrent.downrate=0
xmage.torrent.uprate=50
xmage.torrent.use=false
xmage_launcher.log file contents:
ERROR 2017-04-26 14:31:50,045 Error: =>[SwingWorker-pool-1-thread-2] XMageLauncher$UpdateTask.updateXMage
java.io.EOFException: Truncated ZIP entry: mage-client/lib/swingx-1.6.1.jar
at org.apache.commons.compress.archivers.zip.ZipArchiveInputStream.drainCurrentEntryData(ZipArchiveInputStream.java:619)
at org.apache.commons.compress.archivers.zip.ZipArchiveInputStream.closeEntry(ZipArchiveInputStream.java:583)
at org.apache.commons.compress.archivers.zip.ZipArchiveInputStream.getNextZipEntry(ZipArchiveInputStream.java:193)
at org.apache.commons.compress.archivers.zip.ZipArchiveInputStream.getNextEntry(ZipArchiveInputStream.java:338)
at com.xmage.launcher.DownloadTask.unzip(DownloadTask.java:208)
at com.xmage.launcher.XMageLauncher$UpdateTask.updateXMage(XMageLauncher.java:798)
at com.xmage.launcher.XMageLauncher$UpdateTask.doInBackground(XMageLauncher.java:716)
at com.xmage.launcher.XMageLauncher$UpdateTask.doInBackground(XMageLauncher.java:701)
at javax.swing.SwingWorker$1.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at javax.swing.SwingWorker.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
Windows Registry exported file contents:
Windows Registry Editor Version 5.00
[HKEY_CURRENTUSER\Software\JavaSoft\Prefs\mage\client]
"auto/Connect"="true"
"connect/Flag"="ru"
"table/Panel/Filter/Settings"="x--x----x--------xxxx-"
"table/Panel/Column/Width"="44,267,284,148,189,91,15,15,91,15,15,75"
"table/Panel/Column/Sort"="0,8,1,3,4,2,6,7,9,10,5,11"
"user/Panel/Column/Width"="15,104,15,15,15,15,15,15,15,15"
"user/Panel/Column/Sort"="1,0,2,3,6,4,5,7,8,9"
"editor/Horizontal/Divider/Location"="508"
"editor/Deck/Area/Settings"="(/C/A/R/D/T/Y/P/E,false,64)|(/C/A/R/D/T/Y/P/E,false,100)|965|0"
"server/Address"="xmage.de"
"server/Port"="17171"
"xmage.de\user/Name"="/Silver/Surfer"
"xmage.de\password"=".........." (I edited here when posting, for no one knows my precious password))
"xmage.de\email"="birki@mail.ru"
"gamepanel/Last/Size"="1600.0x1109.0"
"table/Panel/Divider/Location1"="1249"
"table/Panel/Divider/Location2"="964"
"table/Panel/Divider/Location3"="26"
"show/Tooltips/Delay"="0"
"show/Card/Names"="true"
"non/Land/Permanents/In/One/Pile"="true"
"show/Player/Names/Permanently"="true"
"show/Ability/Picker"="true"
"game/Allow/Request/Show/Hand/Cards"="false"
"game/Show/Storm/Counter"="true"
"game/Confirm/Empty/Mana/Pool"="true"
"game/Ask/Move/To/Grave/O/Rder"="true"
"game/Log/Auto/Save"="true"
"draft/Log/Auto/Save"="true"
"gui/Stack/Width"="15"
"gui/Card/Battlefield/Min/Size"="10"
"upkeep/You"="on"
"draw/You"="on"
"main/You"="on"
"before/Combat/You"="on"
"end/Of/Combat/You"="on"
"main2/You"="on"
"end/Of/Turn/You"="on"
"upkeep/Others"="on"
"draw/Others"="on"
"main/Others"="on"
"before/Combat/Others"="on"
"end/Of/Combat/Others"="on"
"main2/Others"="on"
"end/Of/Turn/Others"="on"
"stop/Declare/Attacks/Step"="true"
"stop/Declare/Blockers/Step"="true"
"stop/On/All/Main/Phases"="false"
"stop/On/All/End/Phases"="false"
"pass/Priority/Cast"="false"
"pass/Priority/Activation"="false"
"auto/Order/Trigger"="true"
"card/Images/Use/Default"="false"
"card/Images/Path"="/C://1///X/Mage//images"
"card/Images/Check"="false"
"card/Images/Save/To/Zip"="true"
"card/Images/Threads"="10"
"card/Images/Prefered/Image/Laguage"="en"
"background/Imaged/Default"="false"
"battlefield/Image/Default"="false"
"battlefield/Imagerandom"="false"
"card/Rendering/Fallback"="true"
"card/Rendering/Set/Symbol"="true"
"card/Rendering/Reminder/Text"="true"
"sounds/On"="true"
"sounds/Draft/On"="true"
"sounds/Skip/Buttons/On"="true"
"sounds/Other/On"="true"
"sounds/Match/Music/On"="false"
"sounds/Match/Music/Path"=""
"proxy/Type"="/None"
"proxy/Address"="localhost"
"proxy/Port"="17171"
"proxy/Username"=""
"proxy/Remember"="false"
"connection/U/R/L/Server/List"="http:\\/X/Mage.de\files\server-list.txt"
"control/Confirm"="113"
"control/Cancel/Skip"="114"
"control/Next/Turn"="115"
"control/End/Step"="116"
"control/Skip/Turn"="117"
"control/Main/Step"="118"
"control/Your/Turn"="120"
"control/Skip/Stack"="121"
"control/Prior/End"="122"
"selected/Id"="29"
"collection/Viewer/Format"="- /Modern"
"tournament/Panel/Divider/Location1"="230"
"tournament/Panel/Divider/Location2"="1177"
"tournament/Player/Panel/Column/Width"="30,150,150,60,400,100"
"tournament/Player/Panel/Column/Sort"="0,1,2,3,4,5"
"tournament/Match/Panel/Column/Width"="60,140,140,400,80"
"tournament/Match/Panel/Column/Sort"="0,1,2,3,4"
"big/Card/Toggled"="down"
"gamepanel/Divider/Location0"="1586"
"gamepanel/Divider/Location1"="1452"
"gamepanel/Divider/Location2"="1046"
"gen/Deck/Color"="ur"
"new/Deck/Generator/Deck/Size"="60"
"new/Deck/Generator/Set"="- /All /Sets"
"new/Deck/Generator/Creature/Percentage"="38"
"new/Deck/Generator/Non/Creature/Percentage"="21"
"new/Deck/Generator/Land/Percentage"="41"
"new/Deck/Generator/Singleton"="false"
"new/Deck/Generator/Colorless"="false"
"new/Deck/Generator/Advanced"="false"
"new/Deck/Generator/Advanced/C/M/C"="/Default"
"new/Deck/Generator/Artifacts"="false"
"new/Deck/Generator/Non/Basic/Lands"="false"
"last/Deck/Folder"="/C://1///X/Mage//decks//enc-azorius.dck"
"new/Table/Password/Join"=""
"new/Table/Name"="/Game"
"new/Table/Password"=""
"new/Table/Deck/Type"="/Constructed - /Modern"
"new/Table/Time/Limit"="3600"
"new/Table/Game/Type"="/Two /Player /Duel"
"new/Table/Number/Of/Wins"="3"
"new/Table/Rollback/Turns/Allowed"="/Yes"
"new/Table/Rated"="/No"
"new/Table/Number/Of/Free/Mulligans"="0"
"new/Table/Deck/File"="/C://1///X/Mage//decks//enc-azorius.dck"
"new/Table/Number/Players"="2"
"new/Table/Range"="1"
"new/Table/Attack/Option"="/Attack /Multiple /Players"
"new/Table/Skill/Level"="/Serious"
"new/Table/Quit/Ratio"="100"
"new/Table/Player/Types"="/Human"
"table/Waiting/Panel/Column/Width"="15,50,100,15,15,75"
"table/Waiting/Panel/Column/Sort"="1,2,5,4,3,0"
"table/Waiting/Panel/Width"="500"
"table/Waiting/Panel/Height"="405"
"collection/Viewer/Layout/Config"="big"
"last/Import/Folder"="/C://1///X/Mage//decks//artifs.txt"
"deck/Editor/Last/Sort"="/C/A/R/D/T/Y/P/E"
"deck/Editor/Last/Separate/Creatures"="false"
"base/Sort/Index"="7"
"base/Sort/Ascending"="1"
"default/Deck/Path"="/C://1///X/Mage//decks//enc-azorius.dck"
"gui/Table/Font/Size"="16"
"gui/Dialog/Font/Size"="14"
"gui/Chat/Font/Size"="13"
"gui/Enlarged/Image/Size"="46"
"gui/Feedback/Area/Size"="16"
"background/Image"="/C://1///X/Mage//wallpapers//xte-organic-spandex-jersey-knit-peppermint-90633992.jpg.pagespeed.ic.276_ip/Nstc_x1.png"
"battlefield/Image"="/C://1///X/Mage//wallpapers//royal-blue-nylon-lycra-6-x-4_3.png"
"gui/Card/Battlefield/Max/Size"="18"
"gui/Card/Editor/Size"="20"
"gui/Card/Offset/Size"="14"
"gui/Card/Hand/Size"="17"
"gui/Card/Other/Zones/Size"="29"
"gui/Tooltip/Size"="10"
"xmage.woogerworks.com\user/Name"="/Silver/Surfer"
"xmage.woogerworks.com\password"="..........." (I edited here when posting, for no one knows my precious password))
"xmage.woogerworks.com\email"="birki@mail.ru"
"localhost\user/Name"="/Silver/Surfer"
"localhost\password"=""
[HKEY_CURRENT_USER\Software\JavaSoft\Prefs\mage\client\ignore/List/String]
[HKEY_CURRENT_USER\Software\JavaSoft\Prefs\mage\client\ignore/List/String\localhost]
[HKEY_CURRENT_USER\Software\JavaSoft\Prefs\mage\client\ignore/List/String\xmage.de]
[HKEY_CURRENT_USER\Software\JavaSoft\Prefs\mage\client\ignore/List/String\xmage.woogerworks.com]

----------------------------------------------------------------------------------------------------

Now tried all the same but prior to that deleted "mage" Registry branch completely
No, the same happens - launcher is unable to install update after its download

----------------------------------------------------------------------------------------------------

Idea:
It would be great, if, when new version is released - that some one do the "minimal" installation of XMage on Windows (without images' database and so on), and then zips the installed XMage, and uploads it - so everyone can just download that, and then apply own Registry settings (merge that previously exported file into Registry)

----------------------------------------------------------------------------------------------------

what does procmon say when the program tries to hit a blocked .jar file?

RRRenchant @RRRenchant 16:39
@spjspj
"16:30:46,6940042","javaw.exe","7420","QueryDirectory","C:\1\XMage\xmage\mage-client\lib","SUCCESS","0: log4j-1.2.17.jar, 1: mage-1.4.23.jar, 2: mage-client-1.4.23.jar, 3: mage-common-1.4.23.jar, 4: mage-deck-constructed-1.4.23.jar, 5: mage-sets-1.4.23.jar, 6: mp3spi-1.9.5-1.jar, 7: ormlite-core-4.48.jar, 8: ormlite-jdbc-4.48.jar, 9: protobuf-java-3.0.0-beta-1.jar, 10: scala-library-2.11.5.jar, 11: slf4j-api-1.7.19.jar, 12: slf4j-log4j12-1.7.19.jar, 13: swing-layout-1.0.3.jar, 14: swing-worker-1.1.jar, 15: swingx-1.6.1.jar, 16: tritonus-share-0.3.7-1.jar, 17: tritonus_share-0.3.6.jar, 18: trove-1.0.2.jar, 19: trove4j-3.0.3.jar, 20: truecommons-annotations-2.4.jar, 21: truecommons-cio-2.4.jar, 22: truecommons-io-2.4.jar, 23: truecommons-key-console-2.4.jar, 24: truecommons-key-default-2.4.jar, 25: truecommons-key-spec-2.4.jar, 26: truecommons-logging-2.4.jar, 27: truecommons-services-2.4.jar"
"16:30:46,7359665","javaw.exe","7420","QueryOpen","C:\1\XMage\xmage\mage-client\lib\swingx-1.6.1.jar","FAST IO DISALLOWED",""
"16:30:46,7360215","javaw.exe","7420","CreateFile","C:\1\XMage\xmage\mage-client\lib\swingx-1.6.1.jar","SUCCESS","Desired Access: Read Attributes, Disposition: Open, Options: Open Reparse Point, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a, OpenResult: Opened"
"16:30:46,7360387","javaw.exe","7420","QueryEAFile","C:\1\XMage\xmage\mage-client\lib\swingx-1.6.1.jar","SUCCESS",""
"16:30:46,7360624","javaw.exe","7420","QueryNetworkOpenInformationFile","C:\1\XMage\xmage\mage-client\lib\swingx-1.6.1.jar","SUCCESS","CreationTime: 05.04.2016 22:55:44, LastAccessTime: 26.04.2017 16:24:42, LastWriteTime: 26.04.2017 16:24:42, ChangeTime: 26.04.2017 16:24:42, AllocationSize: 01.01.1601 3:00:00, EndOfFile: 01.01.1601 3:00:00, FileAttributes: A"
"16:30:46,7360686","javaw.exe","7420","CloseFile","C:\1\XMage\xmage\mage-client\lib\swingx-1.6.1.jar","SUCCESS",""
"16:30:46,7360774","javaw.exe","7420","IRP_MJ_CLOSE","C:\1\XMage\xmage\mage-client\lib\swingx-1.6.1.jar","SUCCESS",""
"16:30:46,7361599","javaw.exe","7420","CreateFile","C:\1\XMage\xmage\mage-client\lib\swingx-1.6.1.jar","SUCCESS","Desired Access: Write Attributes, Synchronize, Disposition: Open, Options: Synchronous IO Non-Alert, Open Reparse Point, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a, OpenResult: Opened"
"16:30:46,7361780","javaw.exe","7420","QueryEAFile","C:\1\XMage\xmage\mage-client\lib\swingx-1.6.1.jar","SUCCESS",""
"16:30:46,7362026","javaw.exe","7420","SetBasicInformationFile","C:\1\XMage\xmage\mage-client\lib\swingx-1.6.1.jar","SUCCESS","CreationTime: 01.01.1601 3:00:00, LastAccessTime: 01.01.1601 3:00:00, LastWriteTime: 01.01.1601 3:00:00, ChangeTime: 01.01.1601 3:00:00, FileAttributes: N"
"16:30:46,7362093","javaw.exe","7420","FileSystemControl","C:\1\XMage\xmage\mage-client\lib\swingx-1.6.1.jar","SUCCESS","Control: FSCTL_READ_FILE_USN_DATA"
"16:30:46,7362459","javaw.exe","7420","CloseFile","C:\1\XMage\xmage\mage-client\lib\swingx-1.6.1.jar","SUCCESS",""
"16:30:46,7362661","javaw.exe","7420","IRP_MJ_CLOSE","C:\1\XMage\xmage\mage-client\lib\swingx-1.6.1.jar","SUCCESS",""
"16:30:46,7363433","javaw.exe","7420","QueryOpen","C:\1\XMage\xmage\mage-client\lib\swingx-1.6.1.jar","FAST IO DISALLOWED",""
"16:30:46,7363977","javaw.exe","7420","CreateFile","C:\1\XMage\xmage\mage-client\lib\swingx-1.6.1.jar","SUCCESS","Desired Access: Read Attributes, Disposition: Open, Options: Open Reparse Point, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a, OpenResult: Opened"
"16:30:46,7364124","javaw.exe","7420","QueryEAFile","C:\1\XMage\xmage\mage-client\lib\swingx-1.6.1.jar","SUCCESS",""
"16:30:46,7364346","javaw.exe","7420","QueryBasicInformationFile","C:\1\XMage\xmage\mage-client\lib\swingx-1.6.1.jar","SUCCESS","CreationTime: 05.04.2016 22:55:44, LastAccessTime: 26.04.2017 16:24:42, LastWriteTime: 26.04.2017 16:24:42, ChangeTime: 26.04.2017 16:30:46, FileAttributes: N"
"16:30:46,7364407","javaw.exe","7420","CloseFile","C:\1\XMage\xmage\mage-client\lib\swingx-1.6.1.jar","SUCCESS",""
"16:30:46,7

----------------------------------------------------------------------------------------------------

(further details - are in gitter chat)

**Comment by magenoxx** [comment]
committed test that reproduces issue into Launcher repo: feature/enhance_downloader

to see the issue download xmage.dl from https://drive.google.com/open?id=0B1n0u_Vny_adbXNCZDVqNGtHUTA (real case xmage.dl that was downloaded by Launcher by player)
and put it into data folder

the exception you will see:
`
java.io.EOFException: Truncated ZIP entry: mage-client/lib/trove4j-3.0.3.jar
`

**Comment by JayDi85** [comment]
No longer relevant
