### ISSUE TITLE
Approach Of The Second Sun Win.. Fail

### ISSUE THREAD

**Issue by DerekMangrum** [magefree/mage#3250]
Just cast Approach twice from my hand and did not win. The second cast just gave me the 7 life. I was playing another human player.

**Comment by DerekMangrum** [comment]
Did a bit more testing. Played against the computer and won games casting the same card at two different times, and casting two different cards. So, the card seemed to work as intended when playing against the computer.

**Comment by Roboreaper** [comment]
i've encountered this aswell. you need to cast the Same Approach you casted the first time. if you cast Approach(A) and then Approach(B) it wont win the game. you need to cast (A) again to win the game.

this is the bug

**Comment by ingmargoudt** [comment]
It looks like each instance of the card has its own watcher, so it will work for the same Approach, but not for different instances as they only see themselves in the watcher.

**Comment by ingmargoudt** [comment]
There is a unit test for this scenario, with two different Approaches, which passes. Might need to look into it more.
