### ISSUE TITLE
Sepulchral Primordial's ETB doesn't trigger

### ISSUE THREAD

**Issue by Zzooouhh** [magefree/mage#3257]
On version 1.4.23V0.
Noticed it in two subsequent games - in the first a player reanimated Sepulchral Primordial from an opponent's graveyard, yet as it entered the battlefield, the reanimation ETB was completely skipped and didn't even enter the stack. The same thing happened in another game where I played it from my hand, and it didn't trigger. One thing to note is that in both cases these were in 4 player EDH games, and one opponent didn't have a creature in his graveyard (the other two did) - could it possibly be related?

**Comment by drmDev** [comment]
I remember a long time ago having an issue with Diluvian Primordial not triggering in a multiplayer game. Wasn't able to duplicate it though. We'll try a few different scenarios like the one you mentioned above.

**Comment by Zzooouhh** [comment]
Alright, so the issue persists, and I'm almost certain now about how this happens: when Sepulchral Primordial enters the battlefield, and there's at least one opponent without a creature in the graveyard, the ability doesn't trigger at all. It should trigger at least for the players with creatures in the yard.

**Comment by LevelX2** [comment]
The problem was that the check if a target with 0 to 1 targets is valid if no target is available always returned false instead of correctly true. So thanks for your detailed problem description.
