### ISSUE TITLE
Weird Animate Dead behavior (when reanimating multiple times)

### ISSUE THREAD

**Issue by Zzooouhh** [magefree/mage#3258]
On version 1.4.23V0.
Best illustrated by a practical example: what happened was that I used Animate Dead on a creature in my graveyard (Kagemaro) and sacrificed it using its ability. Animate Dead should have been put into my graveyard along with the creature, but instead it lingered on unattached, like a global enchantment. Afterwards I reanimated Kagemaro using Sheoldred's upkeep ability - when Kagemaro came back onto the battlefield, Animate Dead automatically reattached itself to him and gave him -1/0. This kept repeating even if Kagemaro got sacced again. Haven't tested it yet whether it also happens when the animated creature dies as a result of damage or a kill spell/effect.

**Comment by awjackson** [comment]
I can't reproduce this. Animate Dead correctly went to the graveyard when the enchanted creature was sacrificed.
