### ISSUE TITLE
Squandered Resources

### ISSUE THREAD

**Issue by MasN2** [magefree/mage#3259]
From all sources I have received, Squandered Resources's activated ability 
"Sacrifice a land: Add to your mana pool one mana of any type the sacrificed land could produce." is a mana ability. It doesn't target, it adds mana to your mana pool, and it is not a loyalty ability.

However, I played a game against Squandered Resources and the ability when on the stack as an activated ability.

**Comment by ingmargoudt** [comment]
Squandered Resources' ability is coded like a simpleActivatedAbility, I believe it should be a ActivatedManaAbility instead.
