### ISSUE TITLE
standard rotated prematurely

### ISSUE THREAD

**Issue by paragon249** [magefree/mage#3260]
standard is counting bfz and ogw cards as rotated out

**Comment by mox1** [comment]
The issue appears to be with Mage.Server.Plugins/Mage.Deck.Constructed/src/mage/deck/Standard.java#L59

That code only adds the 3 most recent "blocks", so as of today that is Amonkhet, Kaladash and Shadows over Innistrad.

I *think* if you just  change the < 3 to < 4, it will be correct.

**Comment by LevelX2** [comment]
@mox1 Thanks for your detailed comments.
