### ISSUE TITLE
Can't announce X when taking counters from storage lands

### ISSUE THREAD

**Issue by efmiglioranza** [magefree/mage#3270]
When I try to get mana back from storage lands the clients defaults my choice to 0 so I can't get it back (the dialog to inform X never shows).

![image](https://cloud.githubusercontent.com/assets/497897/25559866/969eb044-2d1a-11e7-993c-2c7d3644bdcc.png)

![image](https://cloud.githubusercontent.com/assets/497897/25559864/8643fa2e-2d1a-11e7-9508-5517f8111a7e.png)

**Comment by LevelX2** [comment]
Was fixed a while ago.
