### ISSUE TITLE
Prototype Portal allows you to pay an additional X

### ISSUE THREAD

**Issue by MasN2** [magefree/mage#3272]
When the activated ability is used, I was prompted to pay the chosen value of X plus the CMC of the artifact. Choosing X = 0 worked with no problems.

**Comment by spjspj** [comment]
X = the CMC of the imprinted artifact.  What was imprinted?  If it was a 0 CMC artifact that's legal.

**Comment by MasN2** [comment]
I had a smokestack imprinted, and then it instructed me to choose a value of X. I chose 4, and was instructed to pay 8. Then I clicked cancel, chose 0, and was instructed to pay 4.

**Comment by Zerrisx** [comment]
It shouldn't let you "choose" anything at all - the value of X is fixed, and determined by the card(s) currently imprinted; there's no choice involved.

**Comment by Zerrisx** [comment]
Duplicate of #6721
