### ISSUE TITLE
Rhystic Study does not allow you to choose what mana to pay.

### ISSUE THREAD

**Issue by MasN2** [magefree/mage#3273]
I had GCC in my mana pool when the trigger resolved. I clicked "Yes" at "Pay 1?" and it automatically took the green mana from my mana pool.

**Comment by spjspj** [comment]
This is changeable from your right-click-context menu. Right click in a game and make sure the highlighted option is checked
:
![image](https://cloud.githubusercontent.com/assets/16917728/25560673/70079aa2-2d9e-11e7-8f10-26cb9de13636.png)
