### ISSUE TITLE
Quicksilver Fountain

### ISSUE THREAD

**Issue by tarwyn** [magefree/mage#3279]
This card has a few problems:

- it allows you to select lands that you do not control (i.e. other players' lands) to apply its effects
- any player with only islands as lands will get stuck in their upkeep phase as the card insists on them selecting a non island land

Thanks.

**Comment by ingmargoudt** [comment]
See #3280

**Comment by tarwyn** [comment]
Thank you! Does the second problem still persist with this commit? If a player only has islands under their control their upkeep phase will get stuck. I believe the card is only applicable if a player actually controls any non-islands lands.

**Comment by ingmargoudt** [comment]
At least the first problem is solved, the second problem I can not deduce from the code. Perhaps that is solved as well with this commit :)
