### ISSUE TITLE
Make handling of Replacement and Triggered effects more comfortable

### ISSUE THREAD

**Issue by LevelX2** [magefree/mage#328]
FROM: http://www.slightlymagic.net/forum/viewtopic.php?f=70&t=11634&p=131805#p131694

One thing that's not really a bug but rather an annoyment, when multiple "replacement effects" or "triggered effects" happen at the same time you are forced to pick in which order they should happen. This was REALLY annoying in one game I played when my opponent had 2 Abyssal Persecutors in play and my life was below zero so I was "dead" but the Abyssal Persecutors prevented it and since it was 2 of them I had to "pick" the replacement effect of them preventing me from loosing almost constantly. As soon as anything changed like a phase or something got on the stack or whatever I had to choose the order, it was so annoying it became unplayable pretty much.

**Comment by JayDi85** [comment]
Implemented as remember answer checkbox, see details in https://github.com/magefree/mage/issues/6676#issuecomment-895016420
