### ISSUE TITLE
Trouble Implementing Leviathan

### ISSUE THREAD

**Issue by dustinroepsch** [magefree/mage#3283]
I apologize if this is the incorrect place to put this.

I've decided to start adding cards to this game in an attempt to never actually study for my finals, but I can't quite figure out why my implementation of Leviathan isn't working.

I've got all of the cards abilities working except for 

> Leviathan can't attack unless you sacrifice two Islands.

I've copied the relevant code bits below, but the full card implementation can be found [here](https://github.com/dustinroepsch/mage/blob/add-card-leviathan/Mage.Sets/src/mage/cards/l/Leviathan.java)

My implementation of this looks like

`this.addAbility(new SimpleStaticAbility(Zone.BATTLEFIELD, new CantAttackBlockUnlessPaysSourceEffect(
                new SacrificeTargetCost(new TargetControlledPermanent(2, 2, filter, true)),
                PayCostToAttackBlockEffectImpl.RestrictType.ATTACK
        )));`

where 'filter' is a static object declared as

`private static final FilterControlledLandPermanent filter = new FilterControlledLandPermanent("two Islands");

    static {
        filter.add(new SubtypePredicate("Island"));
    }`

When I attack with my Leviathan, it properly has me sacrifice islands the first time, but every turn following it will ask me if I want to sacrifice, and then untap Leviathan when I hit "yes".

Would anyone mind helping me figure out what I'm doing incorrectly?

**Comment by ingmargoudt** [comment]
Hi! We have a chatroom on gitter.im where you best can ask such coding questions. Thanks for contributing!

**Comment by dustinroepsch** [comment]
Thanks! I'll hop on there later :)
