### ISSUE TITLE
Platinum Emperion

### ISSUE THREAD

**Issue by Scott-Crawford** [magefree/mage#3290]
When Platinum Emperion is removed from the battlefield by spells that gives its controller life, no life is gained. For example, Swords to Plowshares exiles the card, but the controller doesn't gain 8 life.

**Comment by cappuccinocosmico** [comment]
Um, is this a bug? I dont know if it is

**Comment by Scott-Crawford** [comment]
The Emperion's ability stops applying at the moment it isn't on the battlefield. The instructions of Swords are followed in the order written, so this comes true strictly before you gain life.

**Comment by scmurray15** [comment]
@Scott-Crawford I am not certain this is how this is supposed to function.  We may need to verify with a lvl 2+ judge

**Comment by drmDev** [comment]
paging @emerald000 our go to L2 dev :)

**Comment by emerald000** [comment]
I feel like I posted that somewhere already, but @Scott-Crawford is right. Things happen in the order written on the card. 

PS: Adding applyEffectAfter to Swords to Plowshares will probably solve this.
