### ISSUE TITLE
Triumph of the Hordes gives all permanents trample and infect

### ISSUE THREAD

**Issue by MasN2** [magefree/mage#3292]
This guy just played triumph of the hordes, and his chromatic lantern has trample and infect.

**Comment by ingmargoudt** [comment]
Will make a test for this, the implemented card has a creature filter

**Comment by ingmargoudt** [comment]
unit test confirmed the issue

**Comment by ingmargoudt** [comment]
#3295

**Comment by ingmargoudt** [comment]
Resolved
