### ISSUE TITLE
Should not be able to cascade into Wear/Tear off Violent Outburst

### ISSUE THREAD

**Issue by drmDev** [magefree/mage#3293]
Playing living end in modern, cascaded off of violent outburst with wear / tear in the deck. Wear / Tear still hit as valid target even though in the latest rules updates split card cmc's were updated to be the total cost of both halves, meaning it should be 3 for wear / tear and not able to be cascaded into.

-- from forums

**Comment by ingmargoudt** [comment]
Resolved
