### ISSUE TITLE
Oracle's Vault not allowing cast spells with aftermath

### ISSUE THREAD

**Issue by drmDev** [magefree/mage#3297]
Oracle's Vault won't let you cast spells with aftermath. Expected to be able to play the top half. Experienced it with Oracle's Vault's second ability with both Heaven//Earth and Rags//Riches. The spell will be exiled, and sit there unable to be cast.

-- from forums

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.
