### ISSUE TITLE
Implement new MTGO Commander ban list

### ISSUE THREAD

**Issue by xmagethrowaway** [magefree/mage#3306]
MTGO has a new ban list intended for both 1v1 and multiplayer commander.

It is much better than the current one since it bans several Legacy-banned cards like Hermit Druid and Sol Ring that should obviously have been banned from the start.

It should probably be made the default since it prevents several degenerate turn 3-4 wins (Hermit Druid, Food Chain, Oath of Druids, etc.) that currently make the format unplayable in a serious fashion.

It can be found at http://magic.wizards.com/en/articles/archive/magic-online/1v1-commander-banned-list

There's also the possibility of making a more restrictive XMage-specific banlist. I would suggest simply constructing it as the union of the new MTGO, old Commander, Duel Commander, Vintage, Legacy, Modern and Standard banlists, which should remove pretty much all degenerate cards without needing to make specific controversial decisions.

**Comment by DaMachinator** [comment]
I'd like to point out that the new ban list is very controversial, and might be better off implemented as a new format like "MTGO Commander".

**Comment by fireshoes** [comment]
Yes, that is my thought as well. People will want the option to test using either the MTGO or paper formats with their respective banlists.

**Comment by Karador1995** [comment]
would be very convenient ... in the store where I play commander we use that list of banners for 1 vs1 ... and I have not been able to test my deck online ...

**Comment by fireshoes** [comment]
I'll take a look at it tomorrow. I actually added the format a couple months ago. Maybe I didn't add it into the menu. I've done that before... >_<

**Comment by JRHerlehy** [comment]
It is in the menus.  Perhaps it isn't turned on in the XML config for the specific server they are connecting to?

**Comment by fireshoes** [comment]
Oh, yeah, it is showing up in my 26v2 dev client, but it wasn't on the release client when I connected to woogerworks last night when I checked. I thought I had made sure it was working when I added it, so I was confused about the post about it not being there.

**Comment by Karador1995** [comment]
Hello, I connect to woogerworks on deck typeWhat should I choose? if I use duel commander it uses the french banlist not the MTO

**Comment by Karador1995** [comment]
then will the MTGO banlist be implemented?

**Comment by fireshoes** [comment]
I have not been active in developing, but after updating to v11 today, I notice the MTGO 1v1 Commander shows from the create match menu choices when I connect to woogerworks, but not when connected to xmage.de. However when creating a match on woogerworks, the open table does not show up for another player to join.

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.
