### ISSUE TITLE
Tasigur, the Golden Fang choice is not mandatory - clicking cancel

### ISSUE THREAD

**Issue by drmDev** [magefree/mage#3313]
Opponent (AI) activated Tasigur, the Golden Fang 's ability, i had to choose a nonland card from their graveyard, but it also let me just click "cancel" although there was a nonland card present. No card was returned to AI's hand.

-- from forums

**Comment by LevelX2** [comment]
Was not able to reproduce that problem against the AI. Had to select a nonland card from graveard. No cancel option available to me.

**Comment by drmDev** [comment]
unable to duplicate
