### ISSUE TITLE
Kaseto, Orochi Archmage interaction with Chameleon Colossus

### ISSUE THREAD

**Issue by drmDev** [magefree/mage#3316]
Kaseto, Orochi Archmage do not give Chameleon Colossus +2/+2 , even though Chameleon Colossus should have the "snake" type

-- from forums

likely a more general issue with changeling cards

**Comment by Simown** [comment]
Confirmed with a test. Kaseto's ability effects "Snake" creatures but not "Changeling" creatures.

**Comment by ingmargoudt** [comment]
fixed with #3366

**Comment by ingmargoudt** [comment]
this happens for all changeling cards it seems, which I will fix in another commit
