### ISSUE TITLE
Blood Moon doesn´t work

### ISSUE THREAD

**Issue by tilmtg** [magefree/mage#3318]
Played it yesterday and today, does not have any effect.

**Comment by drmDev** [comment]
Need more details. Anything specific in play? Game log?

**Comment by tilmtg** [comment]
I closed the state of the thread accidentally. Unfortunately i can't see any specific except i played it from my starthand on turn 3 in both games.
 Isn't it an issue? Aren't there other cases?
-- 
Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 07.05.17, 03:42, Derek M <notifications@github.com> schrieb:
Need more details. Anything specific in play? Game log?

**Comment by drmDev** [comment]
We haven't heard any recent reports of issues with it. There is known issue with it in very specific cases in terms of layering effects handling with cards like Urborg and possibly Spreading Seas: see
#3072 and #2957 . We have a variety of unit tests involving various interactions with the card and only specific ones involving Urborg are failing at the moment.

Tested it locally and need more detail on the issue you faced. See screenshot:
![blood moon](https://cloud.githubusercontent.com/assets/11060241/25781197/95856942-3304-11e7-8977-5ccfc4241c87.png)

The basics were the only ones able to tap for their regular mana. The rest only produced mountains.

**Comment by tilmtg** [comment]
Thank you for your detailed answer! I do remeber  that there was no Urborg in play yesterday. I will take screenshots if it happens again.
Best regards!
-- 
Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 07.05.2017, 15:07, Derek M <notifications@github.com> schrieb:
We haven't heard any recent reports of issues with it. There is known issue with it in very specific cases in terms of layering effects handling with cards like Urborg and possibly Spreading Seas: see
#3072 and #2957 . We have a variety of unit tests involving various interactions with the card and only specific ones involving Urborg are failing at the moment.
Tested it locally and need more detail on the issue you faced. See screenshot:

The basics were the only ones able to tap for their regular mana. The rest only produced mountains.

**Comment by drmDev** [comment]
Will re-open (or create new issue) if able to duplicate issue and have a log. Logs are found in  mage-client/gamelogs/
