### ISSUE TITLE
Mogg infestation on commander

### ISSUE THREAD

**Issue by MasN2** [magefree/mage#3321]
https://snag.gy/CYwsJA.jpg

Mogg infestation creates tokens "for each creature that died this way". When a commander is moved to a command zone, it doesn't "die", and thus should not create tokens.

**Comment by drmDev** [comment]
Commit possibly resolving ? https://github.com/magefree/mage/commit/0185bcb37e66c40e3c9c4d5e6e94bcfddd148a4f

@LevelX2 close out if all set here
