### ISSUE TITLE
New Perspectives - casting another New Perspectives while the first one is still in play freezes game

### ISSUE THREAD

**Issue by drmDev** [magefree/mage#3323]
New Perspective - If you cast a second copy of New Perspective while the first one is still in play, the client will freeze.

-- from forums

Was able to duplicate as long as upon playing the 2nd New Perspectives I already had 7+ cards in hand. It gave me the option of selecting the replacement effects but then passed priority and was unable to continue.

**Comment by drmDev** [comment]
@emerald000 brought up a very good point - "Why is it a replacement effect rather than a cost modification?" . Might just be the adjustment needed to resolve the issue.

**Comment by earther66** [comment]
I can confirm: I had to games freeze on me when I played a 2nd New Perspectives and had more than 7 cards in hand.

**Comment by drmDev** [comment]
confirmed by automated test as well. high priority to fix this but have not determined the cause yet.

**Comment by drmDev** [comment]
NOTE: issue only seems to occur when you already have 7+ cards in hand before casting the 2nd New Perspectives

**Comment by magenoxx** [comment]
Fixed. Reason was deadlock in game engine with replacement effects (not related to card New Perspectives).

For now pushing to feature/fix_new_perspectives_freeze, please checkout and test.

**Comment by drmDev** [comment]
Fixed with commit d5c75cd1b3ea324780aa328a4f0d6c4ddfb6633b
