### ISSUE TITLE
[BUG][AKH] Shadow of the grave not working

### ISSUE THREAD

**Issue by Averethel** [magefree/mage#3325]
I was trying a New perspectives + Shadow of the grave cycling combo deck.
I cycled through half of the deck, when I cast Shadow of the grave nothing happened. I should've gotten all my cycled cards back, shouldn't I?

**Comment by tawmas** [comment]
I was going to open the same bug. Latest X-Mage here (1.4.23v4).

**Comment by ingmargoudt** [comment]
The shadow of the Grave bug has been mentioned several times before. It was bugged in v3 and totally in v4. A fix is already implemented and will be there in the next release.

**Comment by drmDev** [comment]
https://github.com/magefree/mage/commit/576ccdb34ab027c7f15952b34eac6a5ae728dfc9 should fix it
