### ISSUE TITLE
Hexproof Planeswalkers can't be attacked

### ISSUE THREAD

**Issue by ZoeMoMo** [magefree/mage#3328]
So in a game of 4-player commander earlier, Sorin was out, and so was privileged position. So, Sorin was hexproof, which I thought didn't matter - but I wasn't able to attack Sorin. There was no popup saying "you can't attack this creature" or anything. It wasn't letting me, nor anyone, attack him. We could attack the player just fine. I'm positive it has something to do with PP being out.

**Comment by drmDev** [comment]
Which Sorin (full card name)?

**Comment by ZoeMoMo** [comment]
It was Sorin, Solemn Visitor. His other walkers couldn't be attacked either, one was Ugin I believe but I'm not sure.

**Comment by drmDev** [comment]
unable to duplicate by unit tests. will need to test in game.
