### ISSUE TITLE
Game can't detect draws

### ISSUE THREAD

**Issue by MasN2** [magefree/mage#3329]
https://snag.gy/XsCBAQ.jpg

So here I made a simple infinite loop with stuffy doll and pariah's shield, which should make the game a draw. But instead, it just keeps going...

**Comment by MasN2** [comment]
Also pictured in a screenshot is a jitte depicted as with 2 counters. But in reality it only has one. This visual glitch happens most notably with planeswalkers.

**Comment by drmDev** [comment]
Game does detect draws now such as the situation mentioned. New issue #3397 for improving its detection to have less false positives.
