### ISSUE TITLE
Martyr's Bond fails to force sacrifice against Shroud/protection

### ISSUE THREAD

**Issue by Sertaki** [magefree/mage#3332]
A sacrifice trigger from Martyr's Bond failed to force a sacrifice when one of the opponents had a Stormbreath Dragon on the battlefield as their only creature.
It was equipped with a Whispersilk Cloak.

I'm not sure whether the shroud or the protection from White caused the bug, but neither should have protected the creature.

**Comment by drmDev** [comment]
UT duplicates issue. Seems specific to Martyr's Bond. tests with Geth's Verdict work as expected.
