### ISSUE TITLE
Whirling Dervish doesn't get it's +1/+1 Counter anymore

### ISSUE THREAD

**Issue by danielweyers** [magefree/mage#3338]
As you can see in the log window on my screenshot, Whirling Dervish does not get a +1/+1 counter at the end of turn in which it damaged opponent.

Version: 1.4.23 V4

![image](https://cloud.githubusercontent.com/assets/28574672/25868722/0bb04e84-34fe-11e7-8308-4ed8b821556a.png)

**Comment by magenoxx** [comment]
Couldn't reproduce:
![image](https://cloud.githubusercontent.com/assets/1684275/26120768/8667f98e-3a7a-11e7-858f-9f7cfed58c58.png)

**Comment by drmDev** [comment]
unable to reproduce
