### ISSUE TITLE
Angelic Arbiter not working properly 

### ISSUE THREAD

**Issue by ZoeMoMo** [magefree/mage#3339]
So, during one game of 4 player commander, I had one angelic Arbiter out. Someone swung with oloro (they didn't cast spells in their precombat main) for four commander damage. Then, in their postcombat main after attacking, they were able to cast Planar Cleansing and wipe the board. Angelic Arbiter was there the entire time, so this is weird.

**Comment by Himsself1** [comment]
Discarding cards is part of the cost of flashing back. So they should remain in grave if the spell is cancelled
