### ISSUE TITLE
Steel Hellkite bug

### ISSUE THREAD

**Issue by ZoeMoMo** [magefree/mage#3340]
So, I was playing kaalia in a four player commander game. I swung at someone, and dropped Steel Hellkite which was tapped and attacking the same opponent. Steel Hellkite hit and did damage, then I paid 2 into it's secont ability in order to destroy the opponent who got hit's lightning greaves which have a CMC of 2. They didn't get destroyed, but they weren't indestructible or anything (they were currently attached to a Giant Adephage, but that's it).  It might have something to do with it not working due to it being dropped by kaalia but who knows.

**Comment by drmDev** [comment]
Feel like @ingmargoudt resolved an issue with Steel Hellkite fairly recently, not sure if it made it in v4 or if its done in v5

**Comment by ingmargoudt** [comment]
Correct, it is fixed but not yet released. The watcher for damage received was falsely Looking at lifeloss events.

**Comment by drmDev** [comment]
fixed with commit: a277aafbc5818ee6dc7197a8a85ee06de77f0ec9
