### ISSUE TITLE
Shadow of the Grave Bug

### ISSUE THREAD

**Issue by Shanok** [magefree/mage#3348]
https://www.slightlymagic.net/forum/viewtopic.php?f=70&t=20440

In this post it says the Shadow of the Grave issue was fixed, but just a few minutes ago I was in game, I had New Perspectives on the board, cycled about 8 cards or so, then played Shadow of the Grave and got back 1 card only.

I cycled a few cards on the 1st main phase, then went to combat (accidentally, didn't feel like rolling back, cycling is time consuming) so I went to 2nd main phase and kept cycling until I played Shadow of the Grave, so maybe it's because I went into other phases?

**Comment by ingmargoudt** [comment]
The card was wrongly returning 1 card in V3, and not returning any cards in V4. It will be resolved in V5.

**Comment by Shanok** [comment]
Thanks for the respone :)

**Comment by scmurray15** [comment]
When will V5 release?   This is a VERY important bug fix after seeing the PT

**Comment by ingmargoudt** [comment]
@scmurray15 I understand this is a gamebreaking bug. We are currently in the process of fixing and testing an issue around New Perspectives. I can not guarantee you a date, but I would expect a new release this week.
