### ISSUE TITLE
Can't pay alternative costs with Vizier of the Menagerie

### ISSUE THREAD

**Issue by exmage** [magefree/mage#3360]
I had a Vizier of the Menagerie on the battlefield. A Reckless Bushwhacker was the top card of my library. I play one creature, then try to Surge the Bushwhacker, but I can only click on it and pay its normal cost. According to the oracle "You may also pay alternative costs" http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=426894

**Comment by JayDi85** [comment]
Fixed by #6093
