### ISSUE TITLE
soul separator makes incorrect second token

### ISSUE THREAD

**Issue by ingmargoudt** [magefree/mage#3362]
Soul Separator second token is not being created accordingly, the first token is a spirit which is a copy of target creature from a graveyard except it is a 1/1, the second is a token that is a zombie with */* equal to the copied creature's toughness however the token is copying power and toughness respectively.

- Forums

**Comment by ingmargoudt** [comment]
Oracle text:

" Create a black Zombie creature token with power equal to that card's power and toughness equal to that card's toughness."

**Comment by drmDev** [comment]
so this was a non-issue? no changes made to code?
