### ISSUE TITLE
Unable to connect to local server since upgrading to 1.4.23V4

### ISSUE THREAD

**Issue by jfreitas25** [magefree/mage#3367]
My general MO after building a new deck is to play a bot or two to playtest and tweak as needed. But the past week or so, I've been running into this error:

INFO 2017-05-05 22:13:43,420 Trying to connect to XMAGE server at localhost:17171 =>[SwingWorker-pool-4-thread-2] SessionImpl$5.run WARN 2017-05-05 22:14:04,570 Cannot connect =>[SwingWorker-pool-4-thread-2] SessionImpl.handleCannotConnectException org.jboss.remoting.CannotConnectException: Error setting up client lease upon performing connect. at org.jboss.remoting.Client.connect(Client.java:1928) at org.jboss.remoting.Client.connect(Client.java:737) at mage.remote.SessionImpl$5.run(SessionImpl.java:391) at mage.remote.SessionImpl.handleRemotingTaskExceptions(SessionImpl.java:117) at mage.remote.SessionImpl.establishJBossRemotingConnection(SessionImpl.java:268) at mage.remote.SessionImpl.connect(SessionImpl.java:220) at mage.client.SessionHandler.connect(SessionHandler.java:48) at mage.client.MageFrame.connect(MageFrame.java:695) at mage.client.dialog.ConnectDialog$ConnectTask.doInBackground(ConnectDialog.java:426) at mage.client.dialog.ConnectDialog$ConnectTask.doInBackground(ConnectDialog.java:416) at javax.swing.SwingWorker$1.call(SwingWorker.java:295) at java.util.concurrent.FutureTask.run(FutureTask.java:266) at javax.swing.SwingWorker.run(SwingWorker.java:334) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) at java.lang.Thread.run(Thread.java:745) Caused by: java.lang.Exception: Error setting up client lease at org.jboss.remoting.MicroRemoteClientInvoker.establishLease(MicroRemoteClientInvoker.java:563) at org.jboss.remoting.Client.setupClientLease(Client.java:2070) at org.jboss.remoting.Client.connect(Client.java:1924) ... 15 more Caused by: org.jboss.remoting.CannotConnectException: Can not get connection to server. Problem establishing socket connection for InvokerLocator [bisocket://10.0.0.56:17171/?serializationtype=jboss] at org.jboss.remoting.transport.socket.MicroSocketClientInvoker.transport(MicroSocketClientInvoker.java:855) at org.jboss.remoting.transport.bisocket.BisocketClientInvoker.transport(BisocketClientInvoker.java:470) at org.jboss.remoting.MicroRemoteClientInvoker.invoke(MicroRemoteClientInvoker.java:169) at org.jboss.remoting.MicroRemoteClientInvoker.establishLease(MicroRemoteClientInvoker.java:529) ... 17 more Caused by: java.net.ConnectException: Connection timed out: connect at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method) at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:85) at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172) at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) at java.net.Socket.connect(Socket.java:589) at org.jboss.remoting.transport.socket.SocketClientInvoker.connect(SocketClientInvoker.java:293) at org.jboss.remoting.transport.socket.SocketClientInvoker.createSocket(SocketClientInvoker.java:210) at org.jboss.remoting.transport.bisocket.BisocketClientInvoker.createSocket(BisocketClientInvoker.java:477) at org.jboss.remoting.transport.socket.MicroSocketClientInvoker.getConnection(MicroSocketClientInvoker.java:1190) at org.jboss.remoting.transport.socket.MicroSocketClientInvoker.transport(MicroSocketClientInvoker.java:833) ... 20 more FATAL 2017-05-05 22:14:04,603 Error disconnecting ... =>[SwingWorker-pool-4-thread-2] SessionImpl.disconnect java.lang.Exception: Can not remove callback listener as remoting client is not connected to server. at org.jboss.remoting.Client.removeListener(Client.java:1466) at mage.remote.SessionImpl.disconnect(SessionImpl.java:489) at mage.remote.SessionImpl.establishJBossRemotingConnection(SessionImpl.java:416) at mage.remote.SessionImpl.connect(SessionImpl.java:220) at mage.client.SessionHandler.connect(SessionHandler.java:48) at mage.client.MageFrame.connect(MageFrame.java:695) at mage.client.dialog.ConnectDialog$ConnectTask.doInBackground(ConnectDialog.java:426) at mage.client.dialog.ConnectDialog$ConnectTask.doInBackground(ConnectDialog.java:416) at javax.swing.SwingWorker$1.call(SwingWorker.java:295) at java.util.concurrent.FutureTask.run(FutureTask.java:266) at javax.swing.SwingWorker.run(SwingWorker.java:334) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) at java.lang.Thread.run(Thread.java:745) INFO 2017-05-05 22:14:04,604 Disconnected ... =>[SwingWorker-pool-4-thread-2] SessionImpl.disconnect INFO 2017-05-05 22:14:04,605 DISCONNECTED (NO Event Dispatch Thread) =>[SwingWorker-pool-4-thread-2] MageFrame.disconnected

I've tried forcing an upgrade again in case the client and server were on different versions, and I've seen some people mention certain registry edits, but those aren't helping either. Any ideas would be great.

**Comment by jfreitas25** [comment]
I'm still seeing this after upgrading to V5.

**Comment by LevelX2** [comment]
Sounds like a problem of a local firewall or AV program.

**Comment by jfreitas25** [comment]
I can see the exception for it in Windows Firewall and tried fiddling with it. I couldn't find anything in my AV, but I'll take a look. It's weird because I never touched either of those around the time it stopped working.

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.
