### ISSUE TITLE
Mindbreak Trap only exiles the "real" spell instead of all copies of it

### ISSUE THREAD

**Issue by drmDev** [magefree/mage#3373]
Mindbreak Trap only seems to want to exile the "real" spell instead of all copies of it - kinda defeats the purpose of it against Storm and the like, don't you think?

Losing games to this sucks, but what would make up for it would be not having to lose any more to that with a good ol' bugfix. :p

-- from subreddit

**Comment by magenoxx** [comment]
Fixed: both UT test and in-game test worked.

Game logs also show that it works:

`
1:23 PM: Human casts Mindbreak Trap [f62] using alternative casting costs targeting Grapeshot [f89] Grapeshot [f89] 

1:23 PM: Human moves Grapeshot [f89] from stack to the exile zone

1:23 PM: Human moves Grapeshot [f89] (Copy) from stack to the exile zone
`

**Comment by drmDev** [comment]
fixed with commit b3eb89c6ea62165294bff84b8cc45a9e88562464
