### ISSUE TITLE
Blocker Ordering UI

### ISSUE THREAD

**Issue by MasN2** [magefree/mage#3375]
So i just ran into a Standard game today where I had 2 bristling hydras (4/3 creature that can get a +1/+1 counter for 3 energy) that were double blocking a 3/3 menace. I only had enough energy to pump one of them however, and XMage didn't tell me what order my blockers were ordered. My opponent was kind enough to tell me, but I'd like to ask that XMage prints to the game log which order blockers are ordered.

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.
