### ISSUE TITLE
Jeleva, Nephalia's Scourge ability not allowing casting instants during combat

### ISSUE THREAD

**Issue by drmDev** [magefree/mage#3378]
When attempting to cast Savage Beating using Jeleva, Nephalia's Scourge 's ability, you get the message that it can only be cast during combat, even though it is during combat.

-- from forums

**Comment by LevelX2** [comment]
Can't preproduce that problem.
Could cast it from exile with Jeleva without a problem.
![jeleva](https://cloud.githubusercontent.com/assets/2066790/26279633/4a9183a2-3db9-11e7-9b37-7dc6a10138ac.jpg)

**Comment by drmDev** [comment]
unable to reproduce

**Comment by drmDev** [comment]
Will add UTs and test again. User reports issue occurring still.

**Comment by drmDev** [comment]
Tested manually and just like LevelX2, unable to duplicate. As long as Savage Beating was one of the cards exiled by Jeleva upon it entering the battlefield, was able to be cast from exile while attacking.

**Comment by drmDev** [comment]
UT also unable to duplicate. See commit ref'd above.
