### ISSUE TITLE
Tsabo's Decree makes the game rollback whenever cast from hand

### ISSUE THREAD

**Issue by drmDev** [magefree/mage#3379]
Hi. Tsabo's Decree makes the game rollback and bug out every time I cast it from my hand. Thank you!

-- from forums

**Comment by magenoxx** [comment]
More information is needed.
For me it works, I cast it, choose 'Human', Human got destroyed on battlefield and was discarded from hand.

TC:
`
battlefield:Computer:Ignoble Soldier:1

hand:Computer:Ignoble Soldier:1

battlefield:Human:Swamp:6

battlefield:Human:Plains:2

hand:Human:Tsabo's Decree:1
`

**Comment by drmDev** [comment]
unable to reproduce
