### ISSUE TITLE
Cho Manno's Blessing should not remove itself

### ISSUE THREAD

**Issue by drmDev** [magefree/mage#3382]
Cho Manno's Blessing not supposed to remove itself if you choose white, but in XMage, it does.

-- from subreddit

**Comment by magenoxx** [comment]
Couldn't reproduce in local test game. But probably some hidden bug and can be related to all these hacks with ids remembered:
`if (notRemoveItself) {

                    protectionAbility.setAuraIdNotToBeRemoved(source.getSourceId());

                }`

**Comment by drmDev** [comment]
unable to reproduce

**Comment by WumpusEATSu** [comment]
This was submitted to Reddit by me. I can provide more information, and can repro. I have attached the deck that I was using when the issue appeared. I will try with other decks.
[Humble Rumble.dck.txt](https://github.com/magefree/mage/files/1030092/Humble.Rumble.dck.txt)

**Comment by WumpusEATSu** [comment]
Basically, I had Humility and Moat in play and an Avacyn Angel of Hope. I was playtesting to see if Cho Manno's Blessing => white would protect it from Humility and Moat, but it removed itself.

**Comment by WumpusEATSu** [comment]
OK, I just tried this with two different decks, and it repro'd. The deck with Cho Manno's Blessing is "Rancor Tog" and the opponent deck is "Familiar Drums". I've also attached screen shots. They have sequential numbers in the file names. The last shot shows my graveyard where Cho Manno's Blessing ended up after choosing White.
[Rancor Tog.dck.txt](https://github.com/magefree/mage/files/1030224/Rancor.Tog.dck.txt)
[Familiar Drums.dck.txt](https://github.com/magefree/mage/files/1030226/Familiar.Drums.dck.txt)
![chomannosblessing 2](https://cloud.githubusercontent.com/assets/28964620/26470625/43fcdf76-4153-11e7-9021-4c43a73dcdee.png)
![chomannosblessing 3](https://cloud.githubusercontent.com/assets/28964620/26470627/44105b96-4153-11e7-8bc7-328e2d3f3888.png)
![chomannosblessing 1](https://cloud.githubusercontent.com/assets/28964620/26470626/43fda7bc-4153-11e7-9c35-e0619c70d0da.png)

**Comment by drmDev** [comment]
Thanks for the additional details and reproduction steps. Will need to be looked into further.

**Comment by drmDev** [comment]
Do you have the game log? Check your xmage install directory / mage-client/gamelogs folder. The deck files won't be useful in troubleshooting this. We just need to replicate the situation with the cards that were on the battlefield at the time.

**Comment by drmDev** [comment]
![cho-manno1](https://cloud.githubusercontent.com/assets/11060241/26483423/e0c7adf6-41ba-11e7-838c-bfd56648fbe1.png)

Cho-Manno on Skyshroud Elf choosing White did not remove it for me. There must be some deeper interaction of other cards on the battlefield.

**Comment by WumpusEATSu** [comment]
OK, I'll get a game log, hopefully today.

**Comment by WumpusEATSu** [comment]
Log attached
[20170527_132012_Free For All_1.txt](https://github.com/magefree/mage/files/1033783/20170527_132012_Free.For.All_1.txt)
