### ISSUE TITLE
Game Crashes

### ISSUE THREAD

**Issue by KxnstiiAustria** [magefree/mage#3383]
Whenerver I start Xmage it crashes. It says "Java (TM) Platfrom SE binary doesnt function anymore".
I've already tried to reinstall it. And I am on the newest version. 
If anyone knows what's up, please let me know, because I kinda want to test some things for next saturday!

**Comment by magenoxx** [comment]
Did it work before?

Try and see here:
https://www.java.com/en/download/help/java_crash_video_driver.xml

**Comment by drmDev** [comment]
not really an XMage issue, this is a Java installation issue.

Googling for that error message gives numerous results, including the one linked by Magenoxx:
https://www.google.com/search?q=Java+%28TM%29+Platfrom+SE+binary+doesnt+function+anymore&ie=utf-8&oe=utf-8
