### ISSUE TITLE
Check message : invalid zone for card - BATTLEFIELD

### ISSUE THREAD

**Issue by LevelX2** [magefree/mage#339]
FATAL [2013-09-21 16:24 [37:784]] CardImpl[pool-2-thread-72]: invalid zone for card - BATTLEFIELD
FATAL [2013-09-21 16:27 [15:259]] CardImpl[pool-2-thread-72]: invalid zone for card - BATTLEFIELD

**Comment by emerald000** [comment]
I haven't heard of that one in a while, and it was most likely an error in another card. In any case, there isn't much to do with only this info, so closing.
