### ISSUE TITLE
Spirit Mirror not implemented correctly ?

### ISSUE THREAD

**Issue by drmDev** [magefree/mage#3391]
I've got an [[Unnatural Selection]] / [[Spirit Mirror]] deck that I'm playtesting, and noticed that I cannot activate the {0}: Destroy target Reflection ability of Spirit Mirror.

[Edit]: It will only target Reflection tokens that are created by Spirit Mirror, which is not correct. If I change any creature to a Reflection, I should be able to use the destroy ability.

-- from subreddit

**Comment by Simown** [comment]
I see the issue with Spirit Mirror - only targets tokens with the name "Reflection". Should target all Permanents with "Reflection" subtype. I am going to fix it and add tests with Unnatural Selection.

**Comment by Simown** [comment]
Ah issue with the targeting in the tests... can't seem to set creature type = "Reflection" in the choice dialog. Known issue with targeting though, which is pain.
