### ISSUE TITLE
Squelch causing ClassCastException

### ISSUE THREAD

**Issue by drmDev** [magefree/mage#3396]
I believe there may be a bug with the card SQUELCH.

Happened in Modern 1 on 1 game with me (username vfedetz) versus user Wicked_Akuba 5/19/2017 around 3:00 pm ET

Description: I tried to +1 Elspeth, Sun's Champion and my opponent tried to Squeltch in response targetting the Elspeth trigger and got this error. Note that I also attempted to Trasmute Tolaria West and when my oppoent tried to cast Squeltch in response to the trigger we also recieved an error (did not copy that one but assume it is a similar issue).

--

An error has occurred on the MAGE server. Your last action will be rollbacked.
Please post the following report here: http://www.slightlymagic.net/forum/posting.php?mode=reply&f=70&t=3116

Game exception occurred: java.lang.ClassCastException: mage.game.stack.StackAbility cannot be cast to mage.abilities.ActivatedAbility
Server version: 1.4.23V5
mage.target.common.TargetActivatedAbility.possibleTargets(TargetActivatedAbility.java:106)
mage.target.common.TargetActivatedAbility.possibleTargets(TargetActivatedAbility.java:98)
mage.player.human.HumanPlayer.chooseTarget(HumanPlayer.java:381)
mage.target.TargetImpl.chooseTarget(TargetImpl.java:329)
mage.target.Targets.chooseTargets(Targets.java:99)
mage.abilities.AbilityImpl.activate(AbilityImpl.java:341)
mage.game.stack.Spell.activate(Spell.java:141)
mage.players.PlayerImpl.cast(PlayerImpl.java:997)
mage.players.PlayerImpl.activateAbility(PlayerImpl.java:1172)
mage.player.human.HumanPlayer.activateAbility(HumanPlayer.java:1269)
mage.player.human.HumanPlayer.activateAbility(HumanPlayer.java:1283)
mage.player.human.HumanPlayer.priority(HumanPlayer.java:720)
mage.game.GameImpl.playPriority(GameImpl.java:1271)
mage.game.turn.Step.priority(Step.java:87)
mage.game.turn.Phase.playStep(Phase.java:210)
mage.game.turn.Phase.play(Phase.java:115)
mage.game.turn.Turn.play(Turn.java:153)
mage.game.GameImpl.playTurn(GameImpl.java:820)
mage.game.GameImpl.play(GameImpl.java:729)
mage.game.GameImpl.start(GameImpl.java:693)
mage.server.game.GameWorker.call(GameWorker.java:60)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
java.lang.Thread.run(Thread.java:745)

**Comment by ingmargoudt** [comment]
This line was changed in https://github.com/magefree/mage/commit/f5b4c4118870d1e318a47005203ee3cd7f8fd3f8

Deserves a UT. Sadly we did not catch this during testing. 

Other cards using this class are:
Voidmage Husher
Rimewind Cryomancer
Azorius Guildmage
Bind
