### ISSUE TITLE
Nest of Scarabs various issues

### ISSUE THREAD

**Issue by drmDev** [magefree/mage#3402]
Added 3 more tests for Nest of Scarabs. previous tests only were on counters placed on own creatures.

Tests failing at the moment:
1) Player with Scarabs out casts Black Sun's Zenith targetting 1 of own creature and 3 of opponents. Only getting 1 token.
2) Both players have Scarabs out, same scenario as above. The opponent is getting 3 tokens when they should be getting 0 and the caster of Zenith is only getting 1 token.
3) Infect damage is not triggering Scarabs.

**Comment by drmDev** [comment]
With Infect, `boolean weAreDoingIt = getControllerId().equals(game.getControllerId(event.getSourceId()));` event.getSourceId() is returning null here. Not sure how this is working with Hapatra with infect damage that was resolved with a similar change?

**Comment by drmDev** [comment]
forgot to link the tests commit: https://github.com/magefree/mage/commit/e7963de7c831ec36f0c187e5c3e4c46b3255121e

**Comment by drmDev** [comment]
There's also a report Nest of Scarabs is not triggering off Wither. will add test

**Comment by drmDev** [comment]
All tests are passing now. User on subreddit claims wither is not triggering. Will need to test manually.

**Comment by Zerrisx** [comment]
Confirmed still bugged; puncture blast gives no scarabs:
![image](https://user-images.githubusercontent.com/59861365/85929227-b0cc8080-b878-11ea-9e6e-fde23044a52f.png)

**Comment by Zerrisx** [comment]
Duplicate of #5886
