### ISSUE TITLE
Soul Conduit prompts "Select a target" twice, change it to "Select Target 1/2"

### ISSUE THREAD

**Issue by sirrion1** [magefree/mage#3414]
The card Soul Conduit does not exchange the players life.
I select a player, pay the cost, but it does nothing, only tapped the card.

**Comment by drmDev** [comment]
Was this a 1v1 game or multi-player? Any game log of what happened (see in your xmage install > mage-client/gamelogs)?

**Comment by drmDev** [comment]
Unable to duplicate in a 2 player game through manual or automated testing. You must target two players.

In screenshot below I cast "Live Fast" which forces me to lose 2 life (and draw 2 cards and gain 2 energy counters) bringing me to 18 life while my opponent still at 20 life. I then activated Soul Conduit and targetted myself and my opponent and our life totals were swapped as expected:

![conduit](https://cloud.githubusercontent.com/assets/11060241/26365649/3987016e-3fb6-11e7-9e90-7161c8ef90dc.png)

**Comment by sirrion1** [comment]
ok was my fault it works goo in commander type, the problem was selecting target 1 and 2 the text is the same "select a target" i think the best is modify the text to "select a target 1" and "select a target 2" or "select first target" and "select second target"

**Comment by drmDev** [comment]
I agree, should be improved to make it more clear what is happening. Very easy to mistakenly target the same player twice for instance.

**Comment by drmDev** [comment]
Renamed the title to make this an enhancement request - the prompts given should be "Select first player" "Select second player" or similar.
