### ISSUE TITLE
Narset, Enlightened Master trigger allows casting Cathartic reunion without discard cost

### ISSUE THREAD

**Issue by drmDev** [magefree/mage#3415]
Casting Cathartic Reunion off of Narset, Enlightened Master's attack trigger does not require you to discard cards as an additional cost to cast

**Comment by ingmargoudt** [comment]
code:

if (player != null) {
                    player.setCastSourceIdWithAlternateMana(objectId, null, null);
                    return true;
                }

The nulls are for manacosts and additional costs respectively, seems as an quick fix.

**Comment by ingmargoudt** [comment]
Issue resolved

**Comment by ev32018** [comment]
it seems this is still an issue with cathartic and narset as of v 1.4.36. Wild guess also has this issue with narsets trigger.
