### ISSUE TITLE
Can't connect to servers

### ISSUE THREAD

**Issue by Dawncaller** [magefree/mage#3420]
here's the error window thing, game itself booted fine
![screen shot 2017-05-23 at 4 36 25 pm](https://cloud.githubusercontent.com/assets/27569102/26375310/68b5b3f2-3fd6-11e7-809c-e10a17be9ac6.png)

**Comment by jholutiak216** [comment]
I am having the same problem.
![image](https://cloud.githubusercontent.com/assets/6502286/26381725/cc0fb236-3ff4-11e7-9ab8-1a65abd35b15.png)

**Comment by drmDev** [comment]
I hear Woogerworks is down and has been down for a little while. Try XMage.de or other servers available.

**Comment by Dawncaller** [comment]
I tried the England/Germany and American servers

**Comment by Zerrisx** [comment]
This is either fixed or long since irrelevant.
