### ISSUE TITLE
Decimator Beetle

### ISSUE THREAD

**Issue by Homnomz** [magefree/mage#3423]
I don't know why, because it was working last night, but I wasn't able to target my opponent's creatures at all when attacking with Decimator Beetle.

**Comment by drmDev** [comment]
Do you have a game log?

**Comment by Homnomz** [comment]
Here you go.
[20170524_135929_Two Player Duel_2.txt](https://github.com/magefree/mage/files/1025442/20170524_135929_Two.Player.Duel_2.txt)

**Comment by LevelX2** [comment]
13:59: Homnom has joined the game 
13:59: lili has joined the game : Match score:lili - 1 winDeckHash: -6514305658244243567Homnom - 0 winsDeckHash: -4654424518060657016Match is not ratedYou have to win 2 games to win the complete matchGame has started 
13:59: Homnom's library is shuffled 
13:59: lili's library is shuffled 
13:59: Homnom chooses that he or she takes the first turn 
13:59: Homnom draws seven cards 
13:59: lili draws seven cards 
13:59: Homnom decides to take mulligan 
13:59: lili decides to take mulligan 
13:59: Homnom's library is shuffled 
13:59: Homnom mulligans down to 6 cards 
13:59: Homnom draws six cards 
13:59: lili's library is shuffled 
13:59: lili mulligans down to 6 cards 
13:59: lili draws six cards 
13:59: Homnom decides to take mulligan 
13:59: lili keeps hand 
13:59: Homnom's library is shuffled 
13:59: Homnom mulligans down to 5 cards 
13:59: Homnom draws five cards 
14:00: Homnom keeps hand 
14:00: Homnom scries 1 
14:00: Homnom puts a card from library to the bottom of his or her library 
14:00: lili scries 1 
14:00: lili puts a card from library to the bottom of his or her library 
14:00: Turn 1 Homnom (20 - 20) 
14:00: Homnom puts Swamp [85e] from hand onto the Battlefield 
14:00: Homnom plays Swamp [85e] 
14:00: Homnom attacks with 0 creatures 
14:00: Turn 2 lili (20 - 20) 
14:00: lili draws a card 
14:00: lili reveals Plains 
14:00: lili puts Fortified Village [1c0] from hand onto the Battlefield 
14:00: lili plays Fortified Village [1c0] 
14:00: lili attacks with 0 creatures 
14:00: Turn 3 Homnom (20 - 20) 
14:00: Homnom draws a card 
14:00: Homnom puts Forest [220] from hand onto the Battlefield 
14:00: Homnom plays Forest [220] 
14:00: Homnom attacks with 0 creatures 
14:00: Turn 4 lili (20 - 20) 
14:00: lili draws a card 
14:00: lili puts Plains [741] from hand onto the Battlefield 
14:00: lili plays Plains [741] 
14:00: lili casts Channeler Initiate [5ed] 
14:00: lili puts Channeler Initiate [5ed] from stack onto the Battlefield 
14:00: Ability triggers: Channeler Initiate [5ed] - When Channeler Initiate [5ed] enters the battlefield, put three -1/-1 counters on target creature you control. - targeting Channeler Initiate [5ed] 
14:00: Channeler Initiate [5ed]: lili puts 3 -1/-1 counter on Channeler Initiate [5ed] 
14:00: lili attacks with 0 creatures 
14:00: Turn 5 Homnom (20 - 20) 
14:00: Homnom draws a card 
14:00: Homnom puts Forest [491] from hand onto the Battlefield 
14:00: Homnom plays Forest [491] 
14:00: Homnom attacks with 0 creatures 
14:00: Turn 6 lili (20 - 20) 
14:01: lili draws a card 
14:01: lili puts Westvale Abbey [e6a] from hand onto the Battlefield 
14:01: lili plays Westvale Abbey [e6a] 
14:01: lili casts Gideon, Ally of Zendikar [5f9] 
14:01: lili puts Gideon, Ally of Zendikar [5f9] from stack onto the Battlefield 
14:01: lili activates: create a 2/2 white Knight Ally creature token. from Gideon, Ally of Zendikar [5f9] 
14:01: lili creates a Knight Ally [048] token 
14:01: lili attacks with 0 creatures 
14:01: Homnom casts Splendid Agony [458] targeting Channeler Initiate [5ed](2) 
14:01: Homnom puts Splendid Agony [458] from stack into his or her graveyard 
14:01: Channeler Initiate [5ed] is put into graveyard from battlefield 
14:01: Turn 7 Homnom (20 - 20) 
14:01: Homnom draws a card 
14:01: Homnom puts Forest [637] from hand onto the Battlefield 
14:01: Homnom plays Forest [637] 
14:02: Homnom attacks with 0 creatures 
14:02: Turn 8 lili (20 - 20) 
14:02: lili draws a card 
14:02: lili puts Plains [1f3] from hand onto the Battlefield 
14:02: lili plays Plains [1f3] 
14:02: lili casts Always Watching [6b3] 
14:02: lili puts Always Watching [6b3] from stack onto the Battlefield 
14:02: lili activates: until end of turn Gideon, Ally of Zendikar [5f9] becomes a 5/5 Human Soldier Ally creature with indestructible that's still a planeswalker. Prevent all damage that would be dealt to him this turn. from Gideon, Ally of Zendikar [5f9] 
14:02: Homnom casts Appetite for the Unnatural [e39] targeting Always Watching [6b3] 
14:02: Always Watching [6b3] was destroyed 
14:02: Homnom gains 2 life 
14:02: Homnom puts Appetite for the Unnatural [e39] from stack into his or her graveyard 
14:03: lili attacks with 2 creatures 
14:03: Attacker: Gideon, Ally of Zendikar [5f9] (5/5) unblocked 
14:03: Attacker: Knight Ally [048] (2/2) unblocked 
14:03: Homnom loses 5 life 
14:03: Homnom loses 2 life 
14:03: Turn 9 Homnom (15 - 20) 
14:03: Homnom draws a card 
14:03: Homnom puts Aether Hub [e7b] from hand onto the Battlefield 
14:03: Homnom plays Aether Hub [e7b] 
14:03: Ability triggers: Aether Hub [e7b] - When Aether Hub [e7b] enters the battlefield, you get (an energy counter). 
14:03: Homnom casts Decimator Beetle [f29] 
14:03: Homnom puts Decimator Beetle [f29] from stack onto the Battlefield 
14:03: Ability triggers: Decimator Beetle [f29] - When Decimator Beetle [f29] enters the battlefield, put a -1/-1 counter on target creature you control. - targeting Decimator Beetle [f29] 
14:03: Decimator Beetle [f29]: Homnom puts 1 -1/-1 counter on Decimator Beetle [f29] 
14:03: Homnom attacks with 0 creatures 
14:03: Turn 10 lili (15 - 20) 
14:03: lili draws a card 
14:03: lili puts Canopy Vista [66a] from hand onto the Battlefield 
14:03: lili plays Canopy Vista [66a] 
14:03: lili casts Felidar Cub [250] 
14:03: lili

**Comment by LevelX2** [comment]
Code looks ok. Probably because the target is "up to 1" and therefore optional you clicked on "cancel" instead of selecting a target creature of defending player.

**Comment by Homnomz** [comment]
I ended up clicking on done because clicking on enemy creatures did nothing. Initially I wanted to target the Felidar cub, and when clicking on it did nothing, I tried the tokens to no avail. A reroll also didn't solve the problem.

I Don't have time today to test it, but will comment again after testing the beetle once more. Hopefully it was just a one time bug.

**Comment by drmDev** [comment]
Will add UT and test manually later tonight.

**Comment by drmDev** [comment]
UT added - works as expected.
