### ISSUE TITLE
Lambholt Pacifist can attack when you have an uncrewed vehicle with power 4 or greater

### ISSUE THREAD

**Issue by drmDev** [magefree/mage#3427]
Lambholt Pacifist can attack when you have a vehicle with power 4 or greater even if the vehicle has not been crewed. I've tested it with Heart of Kiran and Consulate Dreadnought

-- from forums

Heart of Kiran rulings:
`Each Vehicle is printed with a power and toughness, but it’s not a creature. If it becomes a creature (most likely through its crew ability, but the Kaladesh set includes other such effects), it will have that power and toughness.`
http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=423820

**Comment by drmDev** [comment]
Tested in-game and UT - confirmed bug.

**Comment by ingmargoudt** [comment]
Lambolt Pacifist is implemented to look at permanents, rather than creatures, easy and quick fix.
