### ISSUE TITLE
Multiple totem armor auras on creature issue

### ISSUE THREAD

**Issue by drmDev** [magefree/mage#3428]
When a creature dies with more than one totem armor aura on it, its controller is supposed to get to choose which aura to destroy. I don't know what method xmage uses to pick which one to destroy, but the player isn't prompted to choose.

-- from forums

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.
![image](https://user-images.githubusercontent.com/59861365/85934435-ca38f100-b8a7-11ea-9bc3-415858c709f4.png)
