### ISSUE TITLE
AI issue: Rhystic Study in play keeps the AI from playing anything but lands

### ISSUE THREAD

**Issue by ghost** [magefree/mage#3439]
Environment:
Local Game against AI opponents, Constructed Freeform, Free For All
Deck Attached

Repro:
1. Get Rhystic Study into play
2. Cycle thru turns

Expected:
The computer opponent(s) should continue playing cards and creatures and make the card draw choice that Rhystic Study presents

Actual:
The AI ceases to play anything at all except lands.
[Dominatrix.dck.txt](https://github.com/magefree/mage/files/1032875/Dominatrix.dck.txt)

**Comment by drmDev** [comment]
Known issue. AI is very dumb and will stop playing or bug out with certain cards. Recommendation: only give AI very basic tests and only test minor interactions with it. Play testing still needs to be done vs opponents

**Comment by SpikesCafe-google** [comment]
I believe this issue is now resolved.

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.
