### ISSUE TITLE
Eldrazi Temple + Doubling Cube interaction wrong

### ISSUE THREAD

**Issue by drmDev** [magefree/mage#3443]
I've encountered a 100% repeatable mana glitch.
When combining {Eldrazi Temple}'s second mana ability with {Doubling Cube}, it does not double that mana.
The second time it came to this I had {5} in my pool, including {2} from {Eldrazi Temple} as the only kind of special mana, aswell as 3 {g} (8 mana). With {Doubling Cube} on the field, it should give me ( 8 - 3 ) x 2 = 10 mana, but instead I only ever revieved {8} mana after tapping Cube.

-- from forums

**Comment by ingmargoudt** [comment]
it seems that doublingcube:97 ::
Mana mana = new Mana(redMana, greenMana, blueMana, whiteMana, blackMana, colorlessMana, 0, 0);
has the colorlessMana on the place of genericMana, and 0 for colorlessmana

**Comment by ingmargoudt** [comment]
fixed in PR 3457
