### ISSUE TITLE
Torrential Gearhulk NPE

### ISSUE THREAD

**Issue by drmDev** [magefree/mage#3448]
Game exception occurred: java.lang.NullPointerException
Server version: 1.4.23V5
mage.players.PlayerImpl.cast(PlayerImpl.java:965)
mage.cards.t.TorrentialGearhulkEffect.apply(TorrentialGearhulk.java:117)
mage.abilities.AbilityImpl.resolve(AbilityImpl.java:184)
mage.abilities.TriggeredAbilityImpl.resolve(TriggeredAbilityImpl.java:101)
mage.game.stack.StackAbility.resolve(StackAbility.java:101)
mage.game.GameImpl.resolve(GameImpl.java:1343)
mage.game.GameImpl.playPriority(GameImpl.java:1293)
mage.game.turn.Step.priority(Step.java:87)
mage.game.turn.Phase.playStep(Phase.java:210)
mage.game.turn.Phase.play(Phase.java:115)
mage.game.turn.Turn.play(Turn.java:153)
mage.game.GameImpl.playTurn(GameImpl.java:820)
mage.game.GameImpl.play(GameImpl.java:729)
mage.game.GameImpl.start(GameImpl.java:693)
mage.server.game.GameWorker.call(GameWorker.java:60)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
java.lang.Thread.run(Thread.java:745)

-- from forums

**Comment by Zerrisx** [comment]
As this is an old exception report with no additional information, closing as likely obsolete.
