### ISSUE TITLE
Error Reading http://xmage.de/xmage

### ISSUE THREAD

**Issue by MrBeef23** [magefree/mage#3458]
I seem to have the same issue, but slightly different. Mine is reading:
Reading config from http://xmage.de/xmage/config.json
Error reading config from http://xmage.de/xmage/config.json
Possible causes: Site is offline or internet connection is unavailable.
What should I do?

**Comment by LevelX2** [comment]
What happens if you click on the link  http://xmage.de/xmage/config.json using the same computer you try to start/update xmage?

**Comment by MrBeef23** [comment]
I open it up... And it works. :/

**Comment by LevelX2** [comment]
I guess you didn't add java to pass your windows firewall.

**Comment by drmDev** [comment]
It sounds like this issue is resolved then? @MrBeef23 opened a new issue now that he's connected.
