### ISSUE TITLE
Unable to download images and symbols

### ISSUE THREAD

**Issue by MrBeef23** [magefree/mage#3459]
When I try to download the card images, it goes up until all but 1 cards are finished, then goes back to "30478 cards remaining! Please choose another source!"
When I try to download the symbols, it says there is an exception caused by "address family not supported by protocol family: connect."
Why is this happening and what should I do?

**Comment by ingmargoudt** [comment]
https://stackoverflow.com/questions/16373906/address-family-not-supported-by-protocol-family-socketexception-on-a-specific

this message is specific to IP4 and IP6..

**Comment by Zerrisx** [comment]
Considering this no longer relevant; looks to be on the user's end rather than XMage's.
