### ISSUE TITLE
Carrion Feeder and Nim Deathmantle interaction bugged

### ISSUE THREAD

**Issue by drmDev** [magefree/mage#3480]
In a game against AI, Carrion Feeder and Nim Deathmantle showed some weird behavior. From the log:

---
    15:14: gisa sacrificed Carrion Feeder [e64]
    15:14: Ability triggers: Nim Deathmantle [ec2] - Whenever a nontoken creature is put into your graveyard from the battlefield, you may pay  . If you do, return that card to the battlefield and attach Nim Deathmantle to it.
    15:14: gisa activates: put a +1/+1 counter on Carrion Feeder [e64]. from Carrion Feeder [e64]
    15:14: gisa puts Carrion Feeder [e64] from graveyard onto the Battlefield
---

To clarify: Carrion Feeder was sacrificed to its own ability.
The Carrion Feeder ended up on the battlefield with a +1/+1 counter on it and the Deathmantle attached to it, but since it's a new permanent, the ability should have fizzled

-- from forums

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.
