### ISSUE TITLE
Bruna, Light of Alabester and shroud. 

### ISSUE THREAD

**Issue by MasN2** [magefree/mage#3484]
I enchanted Bruna with Alexi's cloak, giving it shroud. Then, it did not allow me to attach any auras with the triggered ability when I attacked with Bruna. Here is the ruling from the judges:

<Storm4> I have a bruna, light of alebaster with shroud. can i still attach auras to it by the triggered ability?
<Buyback13> Can Chandra, Torch of Defiance's +1 damage be redirected to a planeswalker?  Just asking because it says "each opponent"
*** Excalabur [~Adium@cpc1-sotn14-2-0-cust676.15-1.cable.virginm.net] has quit [Ping timeout: 260 seconds]
*** Buyback13 [adca5060@173-202-80-96.dyn.centurytel.net] has quit [Client Quit]
<jeramela> Storm4: Yes. If you're not casting an Aura as an Aura spell, you don't need to target. See !303.4f
<Datatog> 303.4f. If an Aura is entering the battlefield under a player's control by any means other than by resolving as an Aura spell, and the effect putting it onto the battlefield doesn't specify the object or player the Aura will enchant, that player chooses what it will enchant as the Aura enters the battlefield. The player must choose a legal object or player according to the Aura's enchant ...
<Datatog> ... ability and any other applicable effects.

**Comment by CMPUT301F14T02** [comment]
A note on this: the behavior with Bruna + shroud used to be correct (as of 2-3 months ago or so), since I've used her ability properly before while she had shroud.
