### ISSUE TITLE
Computer player somehow taps creatures during combat that are not attacking

### ISSUE THREAD

**Issue by ghost** [magefree/mage#3486]
ENVIRONMENT:
1.4.23V6
Local Free for All Constructed game vs. computer opponents

REPRO:
Play against the computer, and observe when the computer has board advantage but chooses not to attack
Usually, the creatures the computer has will become tapped somehow, even when there's nothing on the board that allows that

EXPECTED:
Creatures that aren't attacking or activating an ability that costs {T} shouldn't ever be allowed to be tapped

ACTUAL:
Invalid board states where the computer opponent is left vulnerable due to creatures somehow becoming tapped

**Comment by jeffwadsworth** [comment]
This was an issue long ago and I haven't seen it after the "fix" was applied many years ago.  These scenario's are incredibly difficult to test.

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.
