### ISSUE TITLE
?????

### ISSUE THREAD

**Issue by MasN2** [magefree/mage#3490]
https://snag.gy/W4tME2.jpg

**Comment by MasN2** [comment]
https://snag.gy/8yqpJS.jpg

These issues are happening periodically whenever I make a click.

**Comment by drmDev** [comment]
Very likely related to the general "UI Tearing" issue we haven't found a resolution or common cause for. See the discussion and try some of the suggestions there:
https://github.com/magefree/mage/issues/1514
