### ISSUE TITLE
Ward Sliver and Thorncaster Sliver effects not applying at right scope

### ISSUE THREAD

**Issue by drmDev** [magefree/mage#3495]
Ward Sliver is not applying to my opponent's slivers. Only mine got the protection from red.

Update: After my Ward Sliver dies, suddenly Thorncaster Sliver gave its ability to my opponent's slivers. It started fine with giving it to just my own.

-- from forums

**Comment by drmDev** [comment]
believe this commit by @ingmargoudt resolves it? https://github.com/magefree/mage/commit/940b44ef8185aea6711409638b629b690d4fc3f9

**Comment by ingmargoudt** [comment]
I only fixed Ward Sliver, 
Thorncaster Sliver needs to be fixed, it uses the static sliver filter, which also accounts for opponent's slivers.

**Comment by jeffwadsworth** [comment]
I could not recreate this issue.  It worked fine.
