### ISSUE TITLE
Feature request: Add scryfall.com as a source for card images

### ISSUE THREAD

**Issue by marlonrichert** [magefree/mage#3496]
In fact, you might as well make it the default source, in my opinion. It's like a better version of magiccards.info

They even [have an API for it](https://scryfall.com/docs/api-overview) and offer [high-res images](https://scryfall.com/changelog/high-resolution-png-images-119).

**Comment by fireshoes** [comment]
Seconded. magiccards.info is slow to update regular expansions and has completely stopped updating many promo cards.

**Comment by quercitron** [comment]
I can try to add it.
