### ISSUE TITLE
Urborg, Tomb of Yawgmoth not allowing land secondary abilities ?

### ISSUE THREAD

**Issue by drmDev** [magefree/mage#3502]
When an opponent has an Urborg, Tomb of Yawgmoth in play i could not activate the fetch ability of Marsh Flats. I believe this applies to many other land secondary abilities while an opponent has an Urborg.

-- from forums

**Comment by spjspj** [comment]
This sounds a lot like they had the 'Use first mana ability on'?

**Comment by drmDev** [comment]
exactly what I was thinking

**Comment by drmDev** [comment]
Confirmed that's all the issue is.

**Comment by sinsedrix** [comment]
It's closed but still problematic, is there a planned fix?

**Comment by spjspj** [comment]
https://i.imgur.com/sF8oGNq.png (Right click on the battlefield in a game, Mana payment -> Use first mana ability when tapping lands).  Toggle that setting.

**Comment by sinsedrix** [comment]
Why not providing a choice when other abilities are not mana abilities?

**Comment by spjspj** [comment]
You tapped it, so it will use the first mana ability.  This is to play quickly precisely to *not* get any choice dialogs up (aka when you're running out of time, mycosynth lattice is in play so color doesn't matter).  Put in a pull request if you want to change it.
