### ISSUE TITLE
Some cards with Energy do not show up when searching for Energy

### ISSUE THREAD

**Issue by drmDev** [magefree/mage#3504]
Probably not a fresh issue, but some Energy related cards (i.e. that produce Energy counters) does not show up when searching for "Energy" in the Deck Editor.
So far I have noticed this for Harnessed Lightning, Greenbelt Rampager, Empyreal Voyager, Rogue Refiner.
All of those have the "energy counters" text on the card but not in the hover-over tooltip.

-- from forums

**Comment by spjspj** [comment]
Use {E} and not energy.  I get 70 unique cards that way.
