### ISSUE TITLE
Remove/Revamp the Draw Feature

### ISSUE THREAD

**Issue by Hix360** [magefree/mage#3508]
I'm sick of losing to missclicking the "Is the game a draw?" prompt while trying to click "yes" on my "Return Sword of the Meek?"  There needs to be a better way to implement this than requiring combo players to add extra clicks into their combo.  Of which, if they click the wrong thing, the game ends.

**Comment by ruler501** [comment]
Pull request #3516 at least partially solves this problem for combo players

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.
