### ISSUE TITLE
Star Wars cards with duplicate numbers

### ISSUE THREAD

**Issue by OdeToJoyBy** [magefree/mage#3513]
2 sets of cards in this set have the same numbers thus not adding properly to a deck.

Jedi Inquirer - 17
Jedi Instructor - 17
Results in Jedi Inquirer being added to a deck instead of Jedi Instructor
There is also no card with the number 18 at all.

Carbonite Chamber - 170
Darth Maul - 170
Results in Carbonite Chamber being added to a deck instead of Darth Maul

**Comment by JayDi85** [comment]
Fixed by 22db12e5693ae67592762b068b506d951d223a5d
