### ISSUE TITLE
Jace, Vryn's Prodigy able to cast Ancestral Visions from graveyard

### ISSUE THREAD

**Issue by spjspj** [magefree/mage#3514]
Reported on the chat on xmage.de.

```
−3: You may cast target instant or sorcery card from your graveyard this turn. If that card would be put into your graveyard this turn, exile it instead.
```

**Comment by drmDev** [comment]
feel like this was an old bug that we may have reintroduced. will check later - might have some existing tests on this in place.

**Comment by jeffwadsworth** [comment]
Was this bug ever confirmed?

**Comment by ingmargoudt** [comment]
The code does not check if the card is castable (i.e. : has a casting cost)

**Comment by drmDev** [comment]
in manual testing, I can select Ancestral Vision from the grave, Jace loses 3 loyalty counters, but can never actually cast Ancestral Vision. With automated test, also cannot cast Ancestral Vision from grave, but Jace loyalty remained at 5? See PR https://github.com/magefree/mage/pull/3690
