### ISSUE TITLE
Planeswalkers BUG

### ISSUE THREAD

**Issue by skiztik** [magefree/mage#3517]
Planeswalkers are paying costs, then selecting targets.  Specifically, if I have a Nahiri, the Harbinger in play, and I activate her -2 ability, wanting to target something with protection from white, the actual game rules have me back up to the point before I attempted to make the illegal action, and I then have the option to use Nahiri to do something else.  However, in Xmage, if there is a valid target of Nahiri's ability on the battlefield, I must target it (my own enchantment, for example).  This is also the case with Leyline of Sanctity and Liliana of the Veil (I've had multiple opponents attempt to -6 me and have to target themselves).  Unlike how I've noticed spells be coded (I haven't used enough targeted abilities to notice), the cost (loyalty +/-) is paid first, and there is no "undo/cancel" option at that point.  This is not how planeswalkers function within the actual game of magic, and they should be brought into line.

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.
