### ISSUE TITLE
Forcing discard when 0 cards in hand causes exception

### ISSUE THREAD

**Issue by drmDev** [magefree/mage#3528]
I was playing a discard deck and forced my opponent to discard a card while he had 0 in his hand.

It made an illegal exception and crashed the game.
We had to draw because of infinite (loop detection).

-- from forums

**Comment by drmDev** [comment]
http://imgur.com/a/lSn0z screenshot of exception

**Comment by drmDev** [comment]
posted clarifies:

Cards were:
Guul Draz Specter
sedraxis specter
Cruel intimations

**Comment by jeffwadsworth** [comment]
Do you mean Cruel Ultimatum?

**Comment by Zerrisx** [comment]
Cannot reproduce with either Cruel Ultimatum or Dark Intimiations or either of the Specters; this appears to be fixed.
