### ISSUE TITLE
Any area's that need more test coverage?

### ISSUE THREAD

**Issue by keetron** [magefree/mage#3529]
For a living I write automated functional tests for use in a build pipeline. I would like to have more practise in writing java code and I figured a good way to start was to contribute unit tests to a java project and after I know the code a bit, try and solve bugs.

So I ended up here and it is a nice big codebase where master will not build when running `mvn clean install` , with the tests active. I did follow the instructions, using IntelliJ on OSX.

console says this:
```
Failed tests:   testBloodMoonAfterUrborg(org.mage.test.cards.continuous.LandTypeChangingEffectsTest): (Battlefield) card sub-type equal (Canopy Vista:Swamp)
  testBloodMoonBeforeUrborg(org.mage.test.cards.continuous.LandTypeChangingEffectsTest): (Battlefield) card sub-type equal (Canopy Vista:Swamp)

Tests run: 1978, Failures: 2, Errors: 0, Skipped: 25
```

Is this known or is this me?

Something else but did you guys ever consider using Sonarcloud or similar code coverage tooling? Another thing on my personal list of things I need to learn how to use, so I would be happy to contribute.

**Comment by ingmargoudt** [comment]
Hi Koen,

Yes those two tests are Currently failing and still need to be investigated. Blood moon layers are tough business ;) we are really interested in a Jenkins + Sonar / Jacoco pipeline that can be run on each git commit, yet it is a challenge to find that infrastructure. 
I am in testautomation as well ;)

**Comment by ingmargoudt** [comment]
Btw, I just looked into Sonar Cloud. That looks really promising, perhaps just what we are looking for :)

**Comment by drmDev** [comment]
There's many issues up that could use unit tests to confirm the issue and then confirm resolution of it. I've been contributing a lot by adding tests for those and resolving it when its something obvious :)

**Comment by keetron** [comment]
@ingmargoudt Fixing the tests is easy of course, just make them behave to become green. But if we go with the POV that the tests are correct and the code is not, how come this was ever merged into master? So should I fix the tests or fix the code?
WRT Sonar Cloud, I will see if I can set something up.

**Comment by ingmargoudt** [comment]
The test seem to be correct, it is a running defect that still needs investigation. I agree with you that it should not have entered into the master branch.

btw, we are also on gitter.im to chat on any related topic

**Comment by drmDev** [comment]
The reason we still have a test failing in master is because the defective code was already in master, and unit tests were added much later on to demonstrate the bug. The issue is still under investigation and so everyone is aware, the tests are still failing because we still have bugs in our code. Filter our github issues by bug and there are many more that still need to be fixed as well - we just don't have tests in to duplicate them yet.

To make these specific tests pass is not easy - the Urborg and Blood Moon interaction issue is very complicated and the code doesn't handle it right, that's why it still is an issue.

**Comment by keetron** [comment]
Before I go and look and draw wrong conclusions or look for something that is not there...
Is there a mechanism in place that signals which bugs do and which bugs don't have unit tests or should I really study the codebase before asking stupid questions?

**Comment by drmDev** [comment]
There is no mechanism in place yet. It is a manual venture. For the most part if there is an issue open with Bug label on it, it could use some unit tests to confirm the issue (and help resolve it quicker and confirm resolution). There may be some unit tests for the card itself already, just not for the specific scenario (ex. many Snapcaster Mage tests, but we have an issue with Snapcaster Mage that is not covered in a test yet.

**Comment by keetron** [comment]
Ok, thank you. I hope this thread inspires more people but me :-)
