### ISSUE TITLE
Norn's annex still not working

### ISSUE THREAD

**Issue by harbingerofme** [magefree/mage#3530]
Bug #3178 was never fixed.

**Comment by drmDev** [comment]
It was marked as fixed on master, but a new release has not come out yet to make it publically available.

**Comment by harbingerofme** [comment]
It is not an AI bug as the issue is labeled as.

**Comment by drmDev** [comment]
removed that label. The commit that resolved the issue was irrelevant to AI anyways, was on the card and its effects itself:
https://github.com/magefree/mage/commit/884a3af503ff3e481ce42120e9a22fed39a24c15

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.
