### ISSUE TITLE
collection viewer/deck editor bug

### ISSUE THREAD

**Issue by lilhomie96** [magefree/mage#3536]
theres an error with the 8th and 9th edition sets.

8th edition 
enormous baloth
vengeance
sea eagle
silverback ape
these cards dont show up in deck editor

9th edition 
coral eel
eager cadet
enormous baloth 
giant octopus
goblin raider
index
spined worm
vengeance
vizzerdrix
these cards share card number with other cards.

i found this information here https://github.com/magefree/mage/issues/93 it seems someone tryed to fix but didnt update old card numbers

**Comment by ingmargoudt** [comment]
box sets for 8th and 9th edition are added in #3546
