### ISSUE TITLE
Magewright's Stone does not untap certain creatures with activated abilities

### ISSUE THREAD

**Issue by drmDev** [magefree/mage#3537]
- Magewright's Stone ability doesn't seems to work to untap Rosheen Meanderer (yes, i used regular mana for that).

-- from forums

I'm thinking it might be from "mana ability" here causing the issue?

**Comment by jeffwadsworth** [comment]
The check is only looking for "Activated" abilities, so yeah, that is the issue.

**Comment by jeffwadsworth** [comment]
The "TapSourceCost" was not assigned to the ability.
