### ISSUE TITLE
Rosheen Meanderer not able to pay X=0 kicker costs

### ISSUE THREAD

**Issue by drmDev** [magefree/mage#3538]
- With Rosheen Meanderer, we should be able to cast Verdeloth the Ancient with a kicker cost X = 0 and thus the 4 colorless mana of Verdeloth the Ancient should be allowed to be paid with Rosheen Meanderer ability (so we can only paid GG + Rosheen Meandererability to have Verdeloth the Ancient and 0 token). In the same way, we should be able to pay 1GG + 4 of Rosheen Meandererability to have 7 mana and have Verdeloth the Ancient kicked one time (i did not try that one, maybe it works).

-- from forums

not sure on the ruling

**Comment by harbingerofme** [comment]
Ruling on Rosheen

> 5/1/2008: A “cost that contains {X}” may be a spell’s total cost, an activated ability’s cost, a suspend cost, or a cost you’re asked to pay as part of the resolution of a spell or ability (such as Broken Ambitions). A spell’s total cost includes either its mana cost (printed in the upper right corner) or its alternative cost (such as suspend), as well as any additional costs (such as kicker). Basically, if it’s something you can spend mana on, it’s a cost. If that cost includes the {X} mana symbol in it, you can spend mana generated by Rosheen on that cost.

**Comment by JayDi85** [comment]
Fixed via cc54a92daa910ade4a28a9a0bc041b21b2f649cf
