### ISSUE TITLE
Stinkdrinker Bandit applies bonus twice

### ISSUE THREAD

**Issue by harbingerofme** [magefree/mage#3542]
When a rogue attacks and isn't blocked, stinkdrinker triggers twice. This so far has always happened when I also had a pestermite on the field, but I've never had a stinkdrinker on the field without a pestermite.

**Comment by ingmargoudt** [comment]
I created a UT for this specific example, and I could not reproduce this

**Comment by drmDev** [comment]
@ingmargoudt I don't see your commit. Can you add it in? Was about to start adding some more tests for these many issues we have open

**Comment by ingmargoudt** [comment]
@harbingerofme Has this occured multiple times, or can you reproduce it?

**Comment by harbingerofme** [comment]
@ingmargoudt  I've had it happen twice during two different EDH games.

**Comment by ingmargoudt** [comment]
Because I can not reproduce it during a UT, was there anything else on the battlefield that could influence this?

**Comment by harbingerofme** [comment]
`
13:44: harb attacks with 17 creatures
13:44: Attacked player: Amarene
13:44: Attacker: Faerie Rogue [e36] (1/1) unblocked
13:44: Attacker: Faerie Rogue [b0d] (1/1) unblocked
13:44: Attacker: Faerie Rogue [a15] (1/1) unblocked
13:44: Attacker: Faerie Rogue [60d] (1/1) unblocked
13:44: Attacker: Faerie Rogue [f1b] (1/1) unblocked
13:44: Attacker: Faerie Rogue [5e7] (1/1) unblocked
13:44: Attacked player: Alexandre
13:44: Attacker: Pestermite [0ea] (2/1) unblocked
13:44: Attacker: Silent-Blade Oni [388] (6/5) blocked by Wood Elves [6df] (1/1) 13:44: Attacker: Stinkdrinker Bandit [b1f] (2/1) unblocked
13:44: Attacker: Faerie Rogue [bfd] (1/1) unblocked
13:44: Attacker: Faerie Rogue [8d6] (1/1) unblocked
13:44: Attacker: Faerie Rogue [214] (1/1) unblocked
13:44: Attacker: Faerie Rogue [d88] (1/1) unblocked
13:44: Attacker: Faerie Rogue [490] (1/1) unblocked
13:44: Attacker: Faerie Rogue [32e] (1/1) unblocked
13:44: Attacker: Faerie Rogue [9b7] (1/1) unblocked
13:44: Attacker: Faerie Rogue [33d] (1/1) unblocked
13:44: Ability triggers: Faerie Rogue [9b7] - Whenever a Rogue you control attacks and isn't blocked, it gets +2/+1 until end of turn.
13:44: Ability triggers: Faerie Rogue [5e7] - Whenever a Rogue you control attacks and isn't blocked, it gets +2/+1 until end of turn.
13:44: Ability triggers: Pestermite [0ea] - Whenever a Rogue you control attacks and isn't blocked, it gets +2/+1 until end of turn.
13:44: Ability triggers: Stinkdrinker Bandit [b1f] - Whenever a Rogue you control attacks and isn't blocked, it gets +2/+1 until end of turn.
13:44: Ability triggers: Faerie Rogue [490] - Whenever a Rogue you control attacks and isn't blocked, it gets +2/+1 until end of turn.
13:44: Ability triggers: Faerie Rogue [33d] - Whenever a Rogue you control attacks and isn't blocked, it gets +2/+1 until end of turn.
13:44: Ability triggers: Faerie Rogue [8d6] - Whenever a Rogue you control attacks and isn't blocked, it gets +2/+1 until end of turn.
13:44: Ability triggers: Faerie Rogue [214] - Whenever a Rogue you control attacks and isn't blocked, it gets +2/+1 until end of turn.
13:44: Ability triggers: Faerie Rogue [b0d] - Whenever a Rogue you control attacks and isn't blocked, it gets +2/+1 until end of turn.
13:44: Ability triggers: Faerie Rogue [f1b] - Whenever a Rogue you control attacks and isn't blocked, it gets +2/+1 until end of turn.
13:44: Ability triggers: Faerie Rogue [bfd] - Whenever a Rogue you control attacks and isn't blocked, it gets +2/+1 until end of turn.
13:44: Ability triggers: Faerie Rogue [32e] - Whenever a Rogue you control attacks and isn't blocked, it gets +2/+1 until end of turn.
13:44: Ability triggers: Faerie Rogue [e36] - Whenever a Rogue you control attacks and isn't blocked, it gets +2/+1 until end of turn.
13:44: Ability triggers: Faerie Rogue [d88] - Whenever a Rogue you control attacks and isn't blocked, it gets +2/+1 until end of turn.
13:44: Ability triggers: Faerie Rogue [60d] - Whenever a Rogue you control attacks and isn't blocked, it gets +2/+1 until end of turn.
13:44: Ability triggers: Faerie Rogue [a15] - Whenever a Rogue you control attacks and isn't blocked, it gets +2/+1 until end of turn.
13:44: Ability triggers: Faerie Rogue [5e7] - Whenever a Rogue you control attacks and isn't blocked, it gets +2/+1 until end of turn.
13:44: Ability triggers: Faerie Rogue [33d] - Whenever a Rogue you control attacks and isn't blocked, it gets +2/+1 until end of turn.
13:44: Ability triggers: Faerie Rogue [9b7] - Whenever a Rogue you control attacks and isn't blocked, it gets +2/+1 until end of turn.
13:44: Ability triggers: Faerie Rogue [490] - Whenever a Rogue you control attacks and isn't blocked, it gets +2/+1 until end of turn.
13:44: Ability triggers: Faerie Rogue [8d6] - Whenever a Rogue you control attacks and isn't blocked, it gets +2/+1 until end of turn.
13:44: Ability triggers: Pestermite [0ea] - Whenever a Rogue you control attacks and isn't blocked, it gets +2/+1 until end of turn.
13:44: Ability triggers: Stinkdrinker Bandit [b1f] - Whenever a Rogue you control attacks and isn't blocked, it gets +2/+1 until end of turn.
13:44: Ability triggers: Faerie Rogue [b0d] - Whenever a Rogue you control attacks and isn't blocked, it gets +2/+1 until end of turn.
13:44: Ability triggers: Faerie Rogue [f1b] - Whenever a Rogue you control attacks and isn't blocked, it gets +2/+1 until end of turn.
13:44: Ability triggers: Faerie Rogue [e36] - Whenever a Rogue you control attacks and isn't blocked, it gets +2/+1 until end of turn.
13:44: Ability triggers: Faerie Rogue [214] - Whenever a Rogue you control attacks and isn't blocked, it gets +2/+1 until end of turn.
13:44: Ability triggers: Faerie Rogue [32e] - Whenever a Rogue you control attacks and isn't blocked, it gets +2/+1 until end of turn.
13:44: Ability triggers: Faerie Rogue [bfd] - Whenever a Rogue you control attacks and isn't blocked, it gets +2/+1 until end of turn.
13:44: Ability triggers: Faerie Rogue [a15] - Whenever a Rogue you control attacks and isn't blocked, it gets +2/+1 until end of turn.
13:44: Ability triggers: Faerie Rogue [d88] - Whenever a Rogue you control attacks and isn't blocked, it gets +2/+1 until end of turn.
13:44: Ability triggers: Faerie Rogue [60d] - Whenever a Rogue you control attacks and isn't blocked, it gets +2/+1 until end of turn.
`

**Comment by ingmargoudt** [comment]
ok, so 16 faerie rogue tokens in play? I can put that in a test.

**Comment by harbingerofme** [comment]
Yes, I'll try and find the other log

**Comment by harbingerofme** [comment]
02:30: harb attacks with 4 creatures

02:31: Attacked player: Marble
02:31: Attacker: Pestermite [d68] (2/1) unblocked
02:31: Attacker: Inkfathom Witch [f93] (1/1) unblocked

02:31: Attacked player: faori
02:31: Attacker: Stinkdrinker Bandit [702] (2/1) unblocked
02:31: Attacker: Warden of Evos Isle [a7a] (2/2) unblocked

02:31: Ability triggers: Pestermite [d68] - Whenever a Rogue you control attacks and isn't blocked, it gets +2/+1 until end of turn.
02:31: Ability triggers: Stinkdrinker Bandit [702] - Whenever a Rogue you control attacks and isn't blocked, it gets +2/+1 until end of turn.
02:31: Ability triggers: Pestermite [d68] - Whenever a Rogue you control attacks and isn't blocked, it gets +2/+1 until end of turn.
02:31: Ability triggers: Stinkdrinker Bandit [702] - Whenever a Rogue you control attacks and isn't blocked, it gets +2/+1 until end of turn.

**Comment by ingmargoudt** [comment]
Thanks for the log! Looks like it triggers for the amount of opponents. Will test it and make a fix for it

**Comment by ingmargoudt** [comment]
I created a similar UT for this and can confirm this bug, will look for a fix
