### ISSUE TITLE
My operating system is win10 I did not find it in the downloaded package Mage series of catalog ah

### ISSUE THREAD

**Issue by BlackImpermanence** [magefree/mage#3547]
![image](https://user-images.githubusercontent.com/29396918/27580192-84a0db68-5b5c-11e7-85ba-22ba44534fb2.png)

**Comment by spjspj** [comment]
The launcher works on Windows 10 and there's ways of not using the launcher (https://www.slightlymagic.net/forum/viewtopic.php?f=70&t=20439&sid=c5d5b1ed459ae6d28cf2e2153a9c6a28 --> Download the .jar file directly from here).
