### ISSUE TITLE
Multiple sliver ability stack not working

### ISSUE THREAD

**Issue by mfalcier** [magefree/mage#3578]
Cards played (in this order):
* Gemhide Sliver
* Predatory Sliver
* Magma Sliver

When tapping Predatory Sliver it automatically ask me to chose between the 5 mana colors (Gemhide Sliver ability), but it doesn't allow me to chose between Gemhide Sliver ability and Magma Sliver ability (+1 / +0 to target sliver for each sliver in play).

Is it a bug?

**Comment by jeffwadsworth** [comment]
This worked fine in my testing.  Please upload your game log so that we can see what else was going on.

**Comment by allentiak** [comment]
Should this one be closed? It has been unconfirmed for almost three years...
