### ISSUE TITLE
"Manifest" card is displayed for generic face-down creatures

### ISSUE THREAD

**Issue by sobolews** [magefree/mage#3584]
When non-manifested cards are turned face-down, the Manifest token (http://i.tcgplayer.com/95263_200w.jpg) is used to represent it. This has been a source of confusion in several games for people who are not familiar with effects that turn cards face down, because the manifest token has reminder text saying that the creature may be turned face up for its mana cost, which is not true for non-manifested face-down creatures. This is only a cosmetic issue.

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.
