### ISSUE TITLE
Mycosynth Lattice + Crystalline Crawler

### ISSUE THREAD

**Issue by spjspj** [magefree/mage#3604]
Opponent played Crystalline Crawler for {W}{U}{B}{R} with lattice on the bf.  It entered with no counters.  I believe that it should have come in with 4 counters still.

**Comment by ingmargoudt** [comment]
I created a UT that confirmed this.

**Comment by ingmargoudt** [comment]
For some reason the manacost of Crystalline Crawler is changed to {1}{1}{1}{1} at runtime. debugging
