### ISSUE TITLE
Magidex image source creating empty jpegs

### ISSUE THREAD

**Issue by fireshoes** [magefree/mage#3610]
When attempting to download images from the magidex option in the menu, it creates 0 bytes jpegs for the images, which are invalid.

**Comment by JayDi85** [comment]
Magidex.com banned xmage app (it's can't download images anymore):

> The owner of this website (magidex.com) has banned your access based on your browser's signature (3caa07452677434c-ua21).

**Comment by JayDi85** [comment]
Was fixed in last versions by user-agent adding.
