### ISSUE TITLE
It told me to post this to slightlymagic, but I don't have an account there

### ISSUE THREAD

**Issue by MasN2** [magefree/mage#3611]
Game exception occurred: java.lang.NullPointerException
Server version: 1.4.23V6
mage.game.GameImpl.resolve(GameImpl.java:1343)
mage.game.GameImpl.playPriority(GameImpl.java:1293)
mage.game.turn.Step.priority(Step.java:87)
mage.game.turn.Phase.playStep(Phase.java:210)
mage.game.turn.Phase.play(Phase.java:115)
mage.game.turn.Turn.play(Turn.java:153)
mage.game.GameImpl.playTurn(GameImpl.java:820)
mage.game.GameImpl.play(GameImpl.java:729)
mage.game.GameImpl.start(GameImpl.java:693)
mage.server.game.GameWorker.call(GameWorker.java:60)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
java.lang.Thread.run(Thread.java:745)

**Comment by MasN2** [comment]
This is as the game started, so I didn't even take a mulligan yet. The done button on the prompt didn't work, and the disconnect button didn't work, so I had to click the X, then it asked me if I wanted to dc and I said yes.

**Comment by LevelX2** [comment]
Was it the second or third game of a match?
Or anything special (e.g. cards that act at start of first turn)?

**Comment by Zerrisx** [comment]
As this is an old exception report with no additional information, closing as likely obsolete.
