### ISSUE TITLE
Xmage update not working

### ISSUE THREAD

**Issue by plmnht1** [magefree/mage#3614]
I updated Xmage but when i tried to log in it said Wrong client version 1.4.24V0 expecting 1.4.23V6. I restarted Xmage restarted my computer and re downloaded Xmage 3 times and it still wont work pls help.

**Comment by angrybacon** [comment]
Unsure whether this is related but I can't update either.

    Reading config from http://xmage.de/xmage/config.json
    XMage folder:  C:\Program Files (x86)\XMage
    XMage Launcher version installed:  0.3.8
    XMage Launcher version available:  0.3.8
    Java version installed:  1.8.0_131
    Java version available:  1.8.0_131
    XMage version installed:  1.4.23V6 (2017-05-21)
    XMage version available:  1.4.24V2 (2017-07-09)
    New version of XMage available
    Reading config from http://xmage.de/xmage/config.json
    XMage version installed:  1.4.23V6 (2017-05-21)
    XMage version available:  1.4.24V2 (2017-07-09)
    New version of XMage available
    Downloading XMage from http://bit.ly/xmage_1_4_24V2w
    Failed to download XMage from http://bit.ly/xmage_1_4_24V2w
    Downloading XMage from http://bit.ly/xmage_1_4_24V2o
    Java version installed:  1.8.0_131
    Java version available:  1.8.0_131
    XMage version installed:  1.4.23V6 (2017-05-21)
    XMage version available:  1.4.24V2 (2017-07-09)
    New version of XMage available
    Failed to download XMage from http://bit.ly/xmage_1_4_24V2o
    Downloading XMage from http://bit.ly/xmage_1_4_24V2d
    Failed to download XMage from http://bit.ly/xmage_1_4_24V2d

I can file a that under a different issue if necessary.

**Comment by angrybacon** [comment]
I initially didn't want to bother with it, but I finally tried to run with administrator rights.

From a PowerShell with administrator rights:

    java -jar XMageLauncher-0.3.8

This successfully updated XMage.

**Comment by JayDi85** [comment]
XMage must have write access to application folder. If you place it to Program Files and activate UAC then you need to run it with admin access.
