### ISSUE TITLE
Nimble Obstructionist gets stuck when cycled with no legal ability to counter

### ISSUE THREAD

**Issue by tawmas** [magefree/mage#3615]
When you cycle Nimble Obstructionist and there is no legal target ability on the stack for its triggered ability, the UI gets stuck at the point where it asks to select a target ability to counter and there is no action the user can take to bypass this.

One should be allowed to cycle Nimble Obstructionst when there is no legal target ability and the UI should not get stuck. Relevant ruling:

> You can cycle a card even if it has a triggered ability from cycling that won’t have a legal target. This is because the cycling ability and the triggered ability are separate. This also means that if either ability is countered (with Disallow, for example, or if the triggered ability’s targets have become illegal), the other ability will still resolve. (http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=430729)

**Comment by LevelX2** [comment]
Fixed with 1.4.24V1
