### ISSUE TITLE
Macro Function Glitchy

### ISSUE THREAD

**Issue by MasN2** [magefree/mage#3638]
So I assembled extraplanar lens, palinchron, and 6 islands. I did the following steps:

Press F8
Tap 6 islands for 12 mana
Cast Palin
Untap 6 islands
Return Palin to my hand
Press F8
Choose 100 loops

What happened was I got nowhere, because Palin decided to alternate between untapping 5 and 6 islands. The macro function did work for the Archangel of Thune Spike Feeder combo before, so I'm not sure why the macro isn't working with this combo.

**Comment by Zerrisx** [comment]
Macro Button no longer exists
