### ISSUE TITLE
Solemnity is bugged

### ISSUE THREAD

**Issue by EllNubNub** [magefree/mage#3642]
the newly added card **Solemnity** that states "Players can't get counters. **Counters can't be put on artifacts, creatures, enchantments, or lands**" should work exactly like **Melira, Sylvok Outcast** which says "You can't get poison counters. **Creatures you control can't have -1/-1 counters placed on them.** Creatures your opponents control lose infect" in the way that using both Murderous Redcap (saying when it comes into play deal damage equal to its power to target player or creature and has **persist**) and Altar of Dementia (saying **sac a creature to mill someone for 2**) would kill your opponents and mill them out when either solemnity or Merlira are on the field. However Solemnity does not seem to work with persist, the -1/-1 counter was still placed on the creature as it came back from the graveyard. i have not tried this on undying yet, but i assume the same problem will occur.

**Comment by spjspj** [comment]
or.. Solemnity is bugged with persist creatures.

**Comment by spjspj** [comment]
Fixed with #3645
