### ISSUE TITLE
No Kaya subtype for Kaya planeswalker

### ISSUE THREAD

**Issue by spjspj** [magefree/mage#3647]
Just had a bug come up in a game where someone cast Kraya (ed: actually Kaya, Ghost Assassin) , Brago Killer :(  and a bug window came up about missing subtype.

**Comment by LevelX2** [comment]
what card/spell is Kraya, Brago Killer?

**Comment by spjspj** [comment]
Sorry LevelX2 - my attempts at humour are usually (equally as) bad.  I meant Kaya, Ghost Assassin. The game rolled back and I didn't get a screen shot

**Comment by ingmargoudt** [comment]
The Kaya subtype does indeed appear to be missing. Was there another card in play that looks for subtypes?

**Comment by jeffwadsworth** [comment]
It works fine for me.  We will have to see a log of the game.

**Comment by spjspj** [comment]
@jeffwadsworth I've pasted a slightly redacted copy here: https://pastebin.com/08WcUJFS  
I think if the subtype is added (as @ingmargoudt mentioned) it should be ok.  Interesting to find any other subtypes that aren't present :)

**Comment by ingmargoudt** [comment]
I will check the subtype list another time

**Comment by ingmargoudt** [comment]
There was another planeswalker in play as well, xmage then checks if both planeswalkers are of a different type, but as Kaya was not defined as a subtype, it raised an exception.

**Comment by ingmargoudt** [comment]
fixed in #3652 
The source I used was outdated.

**Comment by spjspj** [comment]
Nice work!
