### ISSUE TITLE
Thieves' Auction locks up the game if a player leaves while it's resolving

### ISSUE THREAD

**Issue by Zzooouhh** [magefree/mage#3648]
Self explanatory. Somebody casts Thieves' Auction in a 4 player game, somebody concedes while there are permanents he owns left to distribute. They disappear from the Auction pool and once the remaining permanents have been distributed, it continues to prompt from an empty pool forever with the only option available being "Cancel".

**Comment by jeffwadsworth** [comment]
I tested this scenario and it worked fine for me.  Perhaps someone else can check it out.

**Comment by Zzooouhh** [comment]
A wild guess, but maybe the conceding player being either active or inactive could matter for it to trigger?

**Comment by andrew-todaro** [comment]
Not a developer but I can definitely confirm this, have had two lockups from this so far. Once was when someone conceded/left right after the Auction had been cast but before anyone had selected a card, even all other players conceding didn't end the game. The other time was when the person who was next in line  to choose [but not currently choosing] conceded, which resulted in the loop of choosing from an empty pool mentioned above.
