### ISSUE TITLE
Kynaios and Tiro of Meletis (incorrectly) prompt oppponents to draw

### ISSUE THREAD

**Issue by Zzooouhh** [magefree/mage#3649]
> > At the beginning of your end step, draw a card. Each player may put a land card from his or her hand onto the battlefield, then each opponent who didn't draws a card.

The draw is clearly a forced action for every opponent, yet the Xmage implementation of the kings merely prompts the opponents: first it's "play a land? Y/N" and if the answer is no, then "draw a card? Y/N" - when there shouldn't be a "no" option for the card draw at all.

**Comment by spjspj** [comment]
Fixed with #3653
