### ISSUE TITLE
Solemnity & Undying incorrect interaction 

### ISSUE THREAD

**Issue by ChickenSquad** [magefree/mage#3655]
Today while playing my opponent had Solemnity & Geralfs messenger ( No 1+1 counter) on the field. My opponent sacced geralf with blasting station & the Geralf came back with a 1+1 counter. As far as i know it cannot have counters placed on it because of solemnity. 

Here is the log from when the Geralfs is sacced

14:32: ROLAND sacrificed Geralf's Messenger [55d]
14:32: Ability triggers: Geralf's Messenger [55d] - Undying (When this creature dies, if it had no +1/+1 counters on it, return it to the battlefield under its owner's control with a +1/+1 counter on it.)
14:32: ROLAND activates: Blasting Station [c17] deals 1 damage to target creature or player. from Blasting Station [c17] targeting 
14:32: ROLAND puts Geralf's Messenger [55d] from graveyard onto the Battlefield

**Comment by spjspj** [comment]
Fixed with #3645 (copy of #3642)
