### ISSUE TITLE
put a land onto the battlefield = play a land, which is incorrect

### ISSUE THREAD

**Issue by karlosss** [magefree/mage#3656]
Example situation:
River of Tears + fetchland, I fetch in my opponent's turn and River of Tears then gives me black mana, although it should give me blue

**Comment by Vuelos** [comment]
I think that this can be solved using a filter similar to the one used on [Lys Alana Huntmaster](http://gatherer.wizards.com/Pages/Card/Details.aspx?printed=true&multiverseid=139401) using CardType.LAND instead of Subtype.ELF.
