### ISSUE TITLE
Losing the game before it begins

### ISSUE THREAD

**Issue by SeymourBanano** [magefree/mage#3658]
I was playing a Cube match today. I had won G1 and we moved on to G2. They
 chose to go first so I pressed the "Your Turn" skip like I always do and waited for my hand to pop up to Keep/Mull. Instead I was greeted by the message in the picture and a game loss. My opponent hadn't milled me in the previous game, if that's relevant. And my Library count clearly shows I have 33 cards in it.
![screenshot 98](https://user-images.githubusercontent.com/29604629/28080480-724ccc22-666c-11e7-9e0d-899a764f380e.png)
![screenshot 99](https://user-images.githubusercontent.com/29604629/28080549-b30cee86-666c-11e7-9a88-3c16854d2c72.png)

**Comment by JayDi85** [comment]
Player's library can be empty on cheated deck (if user try to change deck cards list in sideboarding). Or it can be rare bug with disappeared cards after sideboard (I was able to randomly reproduce it with AI in old days, but it was random and very rare).

If someone finds good steps to reproduce then create new issue or reopen that.
