### ISSUE TITLE
Angel of Jubilation

### ISSUE THREAD

**Issue by ruler501** [magefree/mage#3663]
Angel of Jubilation should just prevent paying life for activating abilities, but currently when it is out the opponent is not prompted to choose whether or not to pay life for Athreos.

**Comment by jeffwadsworth** [comment]
That would be considered a "resolving" ability and should be allowed to pay the life.

5/1/2012 | Other things may still cause players to pay life or sacrifice creatures, such as a resolving spell or ability.
