### ISSUE TITLE
Solemnity does not interact with Metalic Mimic

### ISSUE THREAD

**Issue by omegaservo** [magefree/mage#3666]
Creatures are coming in with counters on them.

**Comment by C4R5TEN** [comment]
2 Solemnity out and still Geralfs-Messenger gets its undying counter.

![solemnity vs undying](https://user-images.githubusercontent.com/28264140/28206518-8301ca10-6886-11e7-99c2-d71d492cedfe.JPG)

Kitchen Finks also gets its persist counter with Solemnity out.

![solemnity vs persist](https://user-images.githubusercontent.com/28264140/28206700-377778c8-6887-11e7-8d29-7bfcc6969c62.JPG)

Phyrexian Unlife did not make me get Poison counters, that part works!

**Comment by jeffwadsworth** [comment]
I tested Undying and Persist.  Both worked fine on the current build.  Just wait until the next release.

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.
