### ISSUE TITLE
Kicked Rite of Replication interaction with Final Iteration (transofrmed Docent of Perfection)

### ISSUE THREAD

**Issue by tamaroth** [magefree/mage#3667]
XMage client: 1.4.23V6
XMage server: 1.4.23V6

When casting and resolving kicked Rite of Replication targeting Final Iteration I receive 5 tokens of Docent of Perfection instead of expected tokens of Final Iteration.

Best regards,
tamaroth

**Comment by jeffwadsworth** [comment]
Tested this and it worked fine with 1.4.24 V3.  Picture included.
![riteproof](https://user-images.githubusercontent.com/1496996/28284772-d3998a1c-6af7-11e7-8333-2f897dd32342.jpg)

**Comment by tamaroth** [comment]
Great,

if it happens in the future, I'll make sure to screencap to provide board state.

Thanks.
