### ISSUE TITLE
Weird Coat of Arms behavior - ignored somewhat by Mutavault? (and other quirks)

### ISSUE THREAD

**Issue by Zzooouhh** [magefree/mage#3670]
Played a test game against the AI and something doesn't quite add up in the bottom three pictures. 
http://i.magaimg.net/img/yrj.png
http://i.magaimg.net/img/yrk.png
http://i.magaimg.net/img/yrl.png

Mutavault receives the ability bonuses from Lord of Atlantis and Lord of the Unreal (+2/+2, hexproof and islandwalk), but only gets a mere +1/+1 from Coat of Arms due to Mistform Ultimus, and the bonuses in general seem inconsistently distributed (Mutavault is a 5/5 when it should be almost as big as the 13/13 Mistform Ultimus, there are four wizards and two changelings on the field yet Lord of Atlantis is a 5/5? etc. And still Mishra's Factory appropriately gets +2/+2). What strikes me as odd is that Mutavault's text box lists it as "Creature Land - All Creature Type", maybe it could be related? Something seems really messed up about Coat of Arms basically.

**Comment by jeffwadsworth** [comment]
Yes, that "All Creature Type" part is most probably related.  Can you imagine listing every creature type on the card?  :)

**Comment by ingmargoudt** [comment]
The issue here is that the BoostEffect by Lord of Atlantis and Lord of the Unreal does not take Changelings and the "All Creature Types" into account. There is currently a new branch awaiting approval that redefines the way subtypes are treated, including fixed changelings, creatures with all types, and coat of arms.

**Comment by ingmargoudt** [comment]
The fix is merged in, will be in the next major release
