### ISSUE TITLE
crashes after ~1h

### ISSUE THREAD

**Issue by sboosali** [magefree/mage#3672]
I tried two drafts with the latest version, both times it crashed within the first few games. nothing in particular caused it, as far as I can tell. the first time I clicked "yes" to the prompt "reconnect?", and the session was lost. the second time, I clicked "no, and after hanging for ten minutes (without notifying my opponent) and consuming like thirty five percent CPU, it did restore the session and I was able to continue.

**Comment by ichbestimmtnicht** [comment]
Without a detailed crash log nothing can be done. 
I am curious about " nothin particular caused it -> prompt to reconnect? A reconnection is a crash for me and your crash happend after the reconnect? As far as i can tell just close the game complete and restart to get a new session and you are fine.

**Comment by Zerrisx** [comment]
Without more information from the user, this can't be acted on.  Closing as such, though happy to re-open with any additional information.
