### ISSUE TITLE
Elvish Harbinger tutors for non-Elf cards instead of Elf cards

### ISSUE THREAD

**Issue by sobolews** [magefree/mage#3676]
Elvish Harbinger's first ability says:
When Elvish Harbinger enters the battlefield, you may search your library for an Elf card, reveal it, then shuffle your library and put that card on top of it.

Instead, its ability only lets me choose a non-Elf card from my library.

**Comment by jeffwadsworth** [comment]
Already fixed in the next release.  https://github.com/magefree/mage/issues/3646

**Comment by sobolews** [comment]
Thanks!
