### ISSUE TITLE
Mogis, God of Slaughter ignores damage prevention

### ISSUE THREAD

**Issue by Zzooouhh** [magefree/mage#3678]
> As long as your devotion to black and red is less than seven, Mogis isn't a creature.
> At the beginning of each opponent's upkeep, Mogis deals 2 damage to that player unless he or she sacrifices a creature.

The card states "damage", but in Xmage Mogis' effect goes over damage prevention effects, such as Glacial Chasm - perhaps he's coded to cause direct lifeloss instead of damage?

**Comment by jeffwadsworth** [comment]
The DamageTargetEffect method was set to disallow prevention.
