### ISSUE TITLE
Game starts incorrectly

### ISSUE THREAD

**Issue by SeymourBanano** [magefree/mage#3681]
Game 1 of a Booster Elimination Cube match. This happens:
![screenshot 103](https://user-images.githubusercontent.com/29604629/28239949-b66010aa-6977-11e7-8083-304e2e071b65.png)
We both started with zero cards in hand and my opponent kept passing turn without playing anything. When he got to 8 cards in hand he wasn't asked to discard and when I attacked him he lost no life. The game went on for 15 turns until I conceded. When game 2 started, my opponent said he'd stepped away from the computer before game one and when he came back the game was autoplaying. Game 2 and 3 were fine.

**Comment by Zerrisx** [comment]
@JayDi85 Looks similar to #3658?

**Comment by JayDi85** [comment]
@Zerrisx  it's look different. But it's a weird bug report with strange things like missing mulligan logs or player life "freeze".
