### ISSUE TITLE
Cabal Therapy not handling split cards / aftermath cards correctly

### ISSUE THREAD

**Issue by drmDev** [magefree/mage#3695]
It's probably impossible to discard aftermath cards with Cabal Therapy. I wanted to name Driven // Despair against my opponent, the only option i had to name was Driven - and when i did that, he didn't discard the card.

-- from forums

**Comment by jeffwadsworth** [comment]
Confirmed.  The full name is not handled correctly by the card repo.

**Comment by ingmargoudt** [comment]
708.4a Each split card has two names. If an effect instructs a player to choose a card name and the player wants to choose a split card’s name, the player must choose one of those names and not both. An object has the chosen name if one of its names is the chosen name.

I fixed Cabal Therapy to be able to handle Split Cards
