### ISSUE TITLE
Altered Ego copy of token not respecting current stats of token

### ISSUE THREAD

**Issue by drmDev** [magefree/mage#3696]
Altered Ego copied a Zombie token created by Scarad god. A 4/4 token that his original stats were 6/5.
Altered EGo as per the oracle rules copies the original stats of the token but in the game it copied the 4/4 stats.

Here is the official rules from the gatherer.

If the chosen creature is a token, Altered Ego copies the original characteristics of that token as stated by the effect that put the token onto the battlefield. Altered Ego isn’t a token.

Now if i understand wrong and what it says is it copies the 4/4 stats plz delete this topic.

Thanks.

-- from forums

**Comment by emerald000** [comment]
The Scarab God creates a token that is a 4/4 black Zombie instead of its normal text. So if you copy that token, you also get a 4/4 black zombie.
