### ISSUE TITLE
Nicol Bolas (HOU) card exiled and bounced unable to be replayed

### ISSUE THREAD

**Issue by drmDev** [magefree/mage#3697]
I could not cast a card that was taken by Nicol Bolas, God-Pharaoh today.

My opponent has Nicol Bolas, God-Pharaoh on the field. Uses the +2 to exile/cast my Stormchaser Mage. I then Unsummon the Stormchaser Mage to return it to my hand, where it is uncastable for the rest of the game.

-- from forums

**Comment by jeffwadsworth** [comment]
Tested this several times and it worked fine.

**Comment by drmDev** [comment]
Try to get a test in for this and if unconfirmed close it out at that point (if someone does it before me 👍 )

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.
