### ISSUE TITLE
Split / Aftermath cards freezing up games

### ISSUE THREAD

**Issue by drmDev** [magefree/mage#3703]
Anytime my opponent casts a split card the game on my screen freezes on the spot. I can keep hitting f9 and the game will progress but I can't make any plays, block, or see what cards I am drawing, the game stays locked wherever it was when the split card was put on the stack.

These have all been standard games and cards that have caused the issue are Dusk // Dawn, Insult // Injury, and Claim // Fame 

-- from subreddit

**Comment by drmDev** [comment]
Every aftermath card crashes the game.
-- from forums

**Comment by Alexx85** [comment]
Same issue for me.
Every aftermath card freezes the screen, but only for me. 
In the chat and for my opp, the game continues but i still have the aftermath card on the stack.

**Comment by LevelX2** [comment]
@Alexx85 which client version (see title bar) do you use?

**Comment by Alexx85** [comment]
Client 1.4.24V0

**Comment by LevelX2** [comment]
Update your client to V3!
Also with the next restart 25.V0 will go live, so you can also wait for that probably.

**Comment by Alexx85** [comment]
Thanks!
