### ISSUE TITLE
"Can no longer use activated mana abilities" dialog box popping up unexpectedly

### ISSUE THREAD

**Issue by drmDev** [magefree/mage#3715]
In the game that just happened, I was not able to pay for Condescend (X=1), even though I had 1 mana available. See screenshot with error message. This happened again later in the game with Mana Leak too.

-- from forums
<img width="1078" alt="2017 07 19 cant pay for condescend" src="https://user-images.githubusercontent.com/11060241/28461237-ad4fdec6-6de3-11e7-93b1-e7a663ffc9d8.png">

**Comment by drmDev** [comment]
Like the title says, when mana leak prompts me to pay 3 I get an error message when I try to tap lands that says its too late to activate mana abilities. Is this a bug or is it supposed to work that way. I've had multiple spells countered when I had more than enough mana to pay because once I'm given the prompt to pay there's no way to do it. Pressing cancel just counters the spell.

-- from subreddit

**Comment by andrew-todaro** [comment]
The same thing just happened to me with Collective Voyage.

**Comment by LevelX2** [comment]
Probably related to this commit
https://github.com/magefree/mage/commit/eb9a18c07af5b36f153b3d1ba4a2cb299fe773c1
