### ISSUE TITLE
Create Macro function can lead to forced keeps ?

### ISSUE THREAD

**Issue by drmDev** [magefree/mage#3716]
The create macro button is awesome, but there is a bug related to it. I used it to create a macro using Cartel Aristocrat to sacrifice Geralf's Messenger infinitely because I had Solemnity on the battlefield. It correctly looped through, draining my opponent for 2 each time until I won.

The bug was when the next game started. It did not allow me to choose whether or not to mulligan, it just kept my hand even though it was a very bad hand that I did not want to keep. Then it skipped past my whole first turn as well. It's almost like it had a skip to my turn set, even though I did not.

-- from forums

**Comment by Zerrisx** [comment]
Macro Button no longer exists
