### ISSUE TITLE
Invocations not saving layout correctly in deck editor

### ISSUE THREAD

**Issue by fireshoes** [magefree/mage#3719]
I've noticed a few cards don't retain the sorting I used when I saved the file. Examples: Use no sort in sideboard for one column sorted alphabetically, then save. When I reload the deck, Blood Moon invocations have moved from the top of the column to the bottom. Through the Breach invocation in the main deck now has an empty column to the left of it when it was saved sorted by CMC.

**Comment by JayDi85** [comment]
Fixed via 04cb20f46addb1ba42fc644fff0164d6f5a3db5a
