### ISSUE TITLE
Extensive Macro repeats likely to lock up the game

### ISSUE THREAD

**Issue by Zzooouhh** [magefree/mage#3723]
I've been experimenting with lengthy infinite combo macros in a game vs. the AI - I've equipped and de-equipped Angelic Protector with Lightning Greaves and made the macro repeat it about 80 times, then I've tried doing it again with a ~100 time repeat. For doing this, I was met with a "java.lang.OutOfMemoryError: GC overhead limit exceeded" which effectively froze the game. This has happened twice so far, I can try to conduct further testing.

**Comment by spjspj** [comment]
Sounds like it should not be an arbitrarily large iteration count allowed. Maybe 15 max or similar

**Comment by Zerrisx** [comment]
Macro Button no longer exists
