### ISSUE TITLE
You can undo blockers forced to block with Nemisis Mask

### ISSUE THREAD

**Issue by abueide** [magefree/mage#3729]
4 player FFA commander. simply attack when declaring blockers you press the undo button and you are no longer blocking with that creature

**Comment by drmDev** [comment]
I feel this bug has been reported before, but we were unable to duplicate it. This issue is still open and possibly related:
https://github.com/magefree/mage/issues/2645

Do you remember the creature with Nemesis Mask attached? And was this FFA commander format?

**Comment by drmDev** [comment]
This one actually is very easily reproducible. All the blockers are immediately declared at first, but hitting Undo just allows no blocks.

**Comment by abueide** [comment]
It was ffa commander 4 players nemisis attached to glissa.

**Comment by LevelX2** [comment]
@drmDev 
Can you check after my commit now, if you can still reproduce the problem?

**Comment by drmDev** [comment]
@LevelX2 sorry for delay, just tested it now with latest, and still an issue 
![undo-blocks](https://user-images.githubusercontent.com/11060241/28831681-4982f7e8-76a8-11e7-9b71-c200ddd7f84b.png)

Any cards that try to enforce "all creatures must block" at the moment can be undone (see Breaker of Armies in screenshot above)

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.
