### ISSUE TITLE
Xenic Poltergeist's ability lasts indefinitely and doesn't disable abilities (and is incorrectly labeled)

### ISSUE THREAD

**Issue by Zzooouhh** [magefree/mage#3731]
Xenic Poltergeist's ability should only last until the user's next upkeep, but it keeps lasting beyond that. To add to that, abilities appear to be still usable - a player tried to Equip a creature with an animated equipment, but the only reason it didn't work is because it was a creature (when the option shouldn't be available at all).

Also the ability is incorrectly worded in Xmage:
> Tap: Each noncreature artifact loses its abilities and is an artifact creature with power and toughness each equal to its converted mana cost.

Which appears to be copied from Titania's Song from what I can tell, but unlike Song the ability should have a single target and a finite duration. As per Gatherer:
> Tap: Until your next upkeep, target noncreature artifact becomes an artifact creature with power and toughness each equal to its converted mana cost.

**Comment by jeffwadsworth** [comment]
Also, it doesn't have to disable any of the artifacts abilities.

**Comment by Zzooouhh** [comment]
You're correct, I got that confused with Titania's Song.
