### ISSUE TITLE
Realtime XMage Dev Chat

### ISSUE THREAD

**Issue by abueide** [magefree/mage#3733]
Is there a realtime xmage development chat where we can hang out to ask questions about the code and have discussions about how to implement things that don't belong on github issues? If not, can we make one, I would really appreciate it. (new dev trying to get a hold of the code, have some random quick questions here and there)

I'd recommend riot.im or plain old irc for an open source solution, but many teams prefer slack maybe even discord for proprietary solutions.

**Comment by emerald000** [comment]
We have a Gitter room where most of the devs will hang around. You can access it at: https://gitter.im/magefree/mage

**Comment by abueide** [comment]
Thanks @emerald000 , Sorry if it was a dumb question I looked around the github and couldn't really find anything.
