### ISSUE TITLE
Fatal Push vs Eternalized creatures

### ISSUE THREAD

**Issue by albuzs** [magefree/mage#3747]
Fatal push's ability to kill a creature with CMC <2, cannot kill an eternalized creature without revolt. Eternalize reads "Exile this card from your graveyard: Create a token that's a copy of it, except it's a 4/4 black Zombie Naga Wizard with no mana cost. Eternalize only as a sorcery, which should let a regular fatal push kill the creature

**Comment by emerald000** [comment]
While at it, make sure Fatal Push cannot kill creatures with CMC > 4 that are brought back by God-Pharaoh's Gift, Hour of Eternity and The Scarab God. Those tokens do keep their mana cost. Yes this is confusing and I have no idea why Wizards printed both in the same set.

**Comment by LevelX2** [comment]
Tested this an it works as I guess it's correct.
You can destroy an Eternalized Steadfast Sentinel with Fatal Push without the need of Revolt.
So I can't reproduce a bug related to the origin issue.

202.3a The converted mana cost of an object with no mana cost is 0
