### ISSUE TITLE
Casting Cabal Therapy with Flashback and Veteran Explorer stacks trigger first, then spell

### ISSUE THREAD

**Issue by volrathxp** [magefree/mage#3748]
When casting Cabal Therapy by flashback, sacrificing Veteran Explorer, the trigger for Veteran Explorer goes on the stack first then Therapy.  Therapy should be going on the stack first then the Veteran Explorer trigger.

**Comment by LevelX2** [comment]
Fixed beyond 1.4.24V3. There was wrong event handling for sacrificing that is fixed now with this commit acf28d8aff7f54157bf872d249c62c697dbce1b6.
