### ISSUE TITLE
Bug. Mana Vault broken after Shared Fate & Cyclonic Rift

### ISSUE THREAD

**Issue by LevelX2** [magefree/mage#3753]
Bug. Mana Vault broken after Shared Fate & Cyclonic Rift

Postby Krallion » 23 Jul 2017, 22:20
As said, my mana vault was broken ( I can't cast it) after an opponent took it from be 'cause of shared fate and then someone cyclonic rifted. FYI, I killed the guy who had shared fate out.
https://prnt.sc/fzclr9
As you can see, I have enough mana to cast it, but it isn't being highlighted. Can't even put it on the stack. Been in my hand for 3 turns after the rift.

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.
