### ISSUE TITLE
Macro button bug

### ISSUE THREAD

**Issue by spjspj** [magefree/mage#3759]
From the forums: The Macro Toggle can cause a player to skip their turns indefinitely if it is broken by another player.  LevelX: Can you give an more detailed example, so that we can reproduce the problem?

I believe that this was the game that I played against original submitter.
Opponent had Mikaeus, the Unhallowed, Grimgrin, Corpse-Born and Deathbringer Thoctar and was running a macro to sacrifice Deathbringer Thoctar to Grimgrin, remove the undying +1/+1 counter from Mikaeus to do 1 damage to me only to sacrifice it, remove counter to do damage etc.  I had a Mirage Mirror out and Academy Rector.  I took priority, copied Grimgrin, sacced Academy Rector and searched library for Humility and placed it on the Battlefield.   The turn then seemed to end abruptly and pass to the second opponent.

**Comment by jeffwadsworth** [comment]
The macro button was removed.  Caused too many problems.

**Comment by spjspj** [comment]
I know.  This was part of the reason and a specific way to see reproduce at least one of the issues

**Comment by Zerrisx** [comment]
Macro Button no longer exists
