### ISSUE TITLE
Metallic Mimic

### ISSUE THREAD

**Issue by MJY71** [magefree/mage#3765]
After updating to 1.4.25v0, Metallic Mimic's 'Choose creature type' window no longer shows types in alphabetical order, making it take a very long time to find the desired creature type. Image attached.

![metallicmimic](https://user-images.githubusercontent.com/18260997/28792446-3f54f842-75f5-11e7-85af-6ae028342cbc.png)

**Comment by emerald000** [comment]
"Freyalise" isn't a creature type either.

**Comment by ingmargoudt** [comment]
Code to retrieve creature subtypes was incorrect, fixing the ordering issue now too
