### ISSUE TITLE
Path to Exile and Matter Reshaper

### ISSUE THREAD

**Issue by yharaskrik** [magefree/mage#3772]
It seems when Matter Reshaper is exiled with Path to Exile its ability triggers.

**Comment by theelk801** [comment]
Couldn't recreate this. Are you sure it happened?

**Comment by yharaskrik** [comment]
Yes, I am positive, it happened to my friend right after him and I finished playing. He was playing against an AI and the AI Path'd his matter reshaper. I will confirm the series of events and report back.

**Comment by yharaskrik** [comment]
I asked him and he said this: "I was playing an AI I was on eldrazi Tron it was on Bant Eldrazi and it went and pathed my reshaper and I had the triggle come up. I declined it because I thought it was a bug. It's Possible that it would have failed if I tried to search". Sorry I do not have anymore information. I will see if I can recreate it tonight.

**Comment by theelk801** [comment]
Sounds like he declined to search for a basic with path. The Matter Reshaper trigger isn't optional so he couldn't decline that.

**Comment by yharaskrik** [comment]
Ya but Matter Reshaper shouldn't trigger because: "When Matter Reshaper dies, reveal the top card of your library. You may put that card onto the battlefield if it's a permanent card with converted mana cost 3 or less. Otherwise, put that card into your hand." It is when it dies, not when it is exiled.

**Comment by yharaskrik** [comment]
You were right. I just confirmed with him, he was confused about how the triggers were displayed.

Sorry about that.

**Comment by JRHerlehy** [comment]
With that, I'll close this issue.
