### ISSUE TITLE
During/After Declare blockers cannot activate abilities

### ISSUE THREAD

**Issue by yharaskrik** [magefree/mage#3773]
Specifically playing affinity, once I declare a blocker I am not able to activate Arcbound Ravagers ability to sac it to itself and have the attacking creature swing "at air". Additionally and sorry if this is supposed to be a separate issue but I cannot activate Blinkmoth Nexus during declare blockers step (unless with the actual rules of magic I am supposed to activate it right before declaring blockers) little hazy on the absolute exact steps.

**Comment by theelk801** [comment]
Are you activating the ability while declaring blockers or after you've finished declaring blockers? Also, you can't activate the Blinkmoth Nexus while you're declaring blockers, you have to do it during the declare attackers step.
