### ISSUE TITLE
Kagemaro's -X/-X ability gets further influenced by your hand size after it resolves

### ISSUE THREAD

**Issue by Zzooouhh** [magefree/mage#3775]
1. play Kagemaro, First to Suffer and pop its ability
2. if at least one other creature survives, play another card from your hand in the same turn (while the -X/-X ability is active)
3. suddenly, the surviving creature(s) gets +1/+1, because your handsize got reduced by one.

According to the card's ruling this shouldn't be happening.
> 6/1/2005 | The value of X is determined as the ability resolves.

**Comment by theelk801** [comment]
Piggybacking here to say that this is actually an issue with many cards, including Accelerated Mutation, Akroan Hoplite, Appeal // Authority and many others. I'm gonna see if I can fix it but it'll take some doing.

**Comment by jeffwadsworth** [comment]
It is just coded incorrectly.  It uses a dynamic number to calculate the boost.

https://github.com/magefree/mage/blob/master/Mage.Sets/src/mage/cards/k/KagemaroFirstToSuffer.java

**Comment by theelk801** [comment]
Right, I saw that but I'm not sure how to fix it as I'm still familiarizing myself with how the game engine works.

**Comment by emerald000** [comment]
There is a lockedIn parameter to most BoostEffects that locks the buff/debuff at the number it was during resolution. It should only be a matter of setting it.

**Comment by theelk801** [comment]
Got it, somehow missed that before. Implementing the changes now.
