### ISSUE TITLE
Spreading Seas is not removing land types

### ISSUE THREAD

**Issue by Badaro** [magefree/mage#3787]
Version: 1.4.25V0
Server: xmage.de
Gamelog: https://pastebin.com/84EbX9cY

From [Spreading Seas's Gatherer Page](http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=190405)

> The enchanted land loses its existing land types and any abilities printed on it. It now has the land type Island and has the ability to tap to add (U) to its controller’s mana pool. Spreading Seas doesn’t change the enchanted land’s name or whether it’s legendary, basic, or snow.

However, after an opponent use Spreading Seas on an Urza's Tower its types were listed as "Urza's Tower Island".

**Comment by ingmargoudt** [comment]
Fixed in #3783. Will add another test to confirm
