### ISSUE TITLE
Issue while trying to connect to Xmage

### ISSUE THREAD

**Issue by albuzs** [magefree/mage#3794]
When trying to launch the app, I am getting the following error:

Reading config from http://xmage.de/xmage/config.json
Error reading config from http://xmage.de/xmage/config.json
Possible causes:  Site is offline or internet connection is unavailable.

How can I fix this?

**Comment by albuzs** [comment]
guys? :D

**Comment by albuzs** [comment]
I have now tried two separate computers, on different connections, and still not getting through

**Comment by emerald000** [comment]
This is probably an issue with a firewall/antivirus not letting the connection through, Can you load that URL in your browser?

**Comment by albuzs** [comment]
yep! but what exception should I add on the firewall?

**Comment by emerald000** [comment]
You will have to add whichever java.exe/javaw.exe you use to launch the XMageLauncher-0.3.8.jar. On Windows, this is often in system32, but can sometimes be in ProgramData or Program Files.

If you launch the launcher via console, you can control better which executable you use.

**Comment by Zerrisx** [comment]
This looks like it was resolved.
