### ISSUE TITLE
Odd behavior of Spreading Plague with 0/0s

### ISSUE THREAD

**Issue by Zzooouhh** [magefree/mage#3797]
I have a 0/0 colored token enter the battlefield while Spreading Plague is in play, so the token dies immediately (tried this only with tokens, not sure if nontoken creatures will also cause it or not). Spreading Plague's trigger for the token gets put on the stack, but doesn't destroy anything - as if it couldn't read the color identity of the (now dead) token anymore.

**Comment by theelk801** [comment]
I've fixed it, the commit might not pushed for a little while though.
