### ISSUE TITLE
BUG: Bring to Light when using mana out of the pool 

### ISSUE THREAD

**Issue by AricHaldan** [magefree/mage#3816]
When using mana out of the pool, as one does for example after using cascading cataracts for all 5 colors, it is not possible to fetch spells with converted mana cost 5. I believe the limit is 3 and might be because it doesn't count the UG that is already in it's mana cost. I have not tested what the case is with other converge spells when using mana from the pool.

**Comment by AricHaldan** [comment]
It doesn't seem to be the case for other convergence spells, but I've checked and bring to light still could not play an hour of devastation or fumigate after using one mana of any color, that was put in the mana pool by cascading cataracts.

**Comment by sobolews** [comment]
+1

Using mana already in my pool, I cast Bring To Light for 2WUR. It only lets me select 0-2 CMC cards from my library.

**Comment by Woogachaka** [comment]
Just tested this again, went to cast a peregrine drake after using all 5 colors and could not.
