### ISSUE TITLE
As foretold + alternative cards, that can be casted. - Not working.

### ISSUE THREAD

**Issue by AMetnik** [magefree/mage#3818]
So.
If I've As Foretold in play.
+1 Chandra, Torch of Defiance, reveal top card, you may cast this card. Then I should be able to cast it using Chandra. (Not working)

Also, Jace, Vryn's Prodigy's -3, can be cast through As foretold (Not tested)

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.
