### ISSUE TITLE
Custom Constructed Commander & Legality in Custom Constructed

### ISSUE THREAD

**Issue by DerpyMcDerpDerp** [magefree/mage#3819]
Currently, you can not make a commander FFA or Two Player Duel using Custom Constructed - Star Wars.
Along with adding that, I would also like to suggest that you add the ability to make it so that other sets are legal in Custom Commander. (I really want to make a tribal trooper EDH deck using Commander Cody, but would like to add regular magic cards (Like Urza's Incubator and Cavern of Souls) but this is currently not possible, even in regular 2 player duel)

**Comment by Zerrisx** [comment]
Looks to be fixed.
![image](https://user-images.githubusercontent.com/59861365/88832291-3738f280-d196-11ea-8c7a-dded1f05139f.png)
