### ISSUE TITLE
So I messed up (as per usual with new updates)

### ISSUE THREAD

**Issue by Dawncaller** [magefree/mage#3829]
For some reason I can never get the new update to work right the first time, so i end up attempting to delete xmage and use a new xmage. So I went to do this when xmage wasn't working, and I reinstalled it and now the "Launch Client" brings up a blank command terminal, the "launch client and server" does nothing, and the launch server does nothing as well. Thanks for spending time helping me with this issue.

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.
