### ISSUE TITLE
Attacking restriction plus requirement causes strange things

### ISSUE THREAD

**Issue by theelk801** [magefree/mage#3833]
If the computer controls three Crazed Goblins and you control a Crawlspace or Silent Arbiter, the computer will attempt to attack with all three and only be able to attack with one, but all three will end up tapped anyway. If they instead have Tormented Soul, they'll attack with one while the others stay untapped.

**Comment by ingmargoudt** [comment]
The AI is not developed well enough for such situations, and should only be used to goldfish decks.

**Comment by theelk801** [comment]
This still happens if you have the Crazed Goblins and they have the Crawlspace.

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.
