### ISSUE TITLE
Life loss not counted after player loses the game

### ISSUE THREAD

**Issue by connor-bracewell** [magefree/mage#3834]
Per http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=430793:

> If an opponent loses life and subsequently loses the game before your postcombat main phase, Neheb’s last ability counts that loss of life.

Currently, when a player loses the game, their life loss from that turn stops being counted, which can result in the ability providing less mana than expected.

I believe there are a few other cards with the same interaction, but I don't know of them off the top of my head to test.

**Comment by AricHaldan** [comment]
I can confirm that i've seen this bug as well. Someone lost an edh game because of this.

**Comment by connor-bracewell** [comment]
Hey, just ran into this in a game and was happy to see it was working as intended!
Thanks a lot for the quick fix.
