### ISSUE TITLE
OKagachi Vengeful Kami triggers for each attacker that deals damage

### ISSUE THREAD

**Issue by harbingerofme** [magefree/mage#3842]
This issue was reported as against AI.

**Comment by theelk801** [comment]
Can you elaborate?

**Comment by harbingerofme** [comment]
> I have Scion of the Ur Dragon, O-Kagachi and a bunch of other dragons on the field.
> I have Scion of the Ur Dragon clone the Hellkite that spawns 6/6 tokens when a dragon attacks.
> Combat phase, attack with all my dragons. Scion's effect activates for each attack, and that's right.
> Then after damage is dealt, O-Kagachi activates for each attack that hit the opponent, and that's not right.

**Comment by theelk801** [comment]
Oh, ok. Fixed.
