### ISSUE TITLE
Wrong card textures

### ISSUE THREAD

**Issue by DoctorPineapple** [magefree/mage#3846]
Might be just on my end, but is anybody else experiencing corrupted textures? Basic example of a few are in the linked album.

Album of bugged textures - http://imgur.com/a/hnda5

**Comment by dmichelin** [comment]
I have this problem as well

**Comment by derFeind** [comment]
I can not confirm this. For me it looks normal.
https://imgur.com/a/bb1zo
What did you do in detail? Fireup the client and go directly to the Deck Editor or did you something before this bug occured?

regards
dF

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.
