### ISSUE TITLE
Manipulate Fate (lack of) Shuffling

### ISSUE THREAD

**Issue by skiztik** [magefree/mage#3847]
I posted about this issue under a complaint about shuffling a few months ago, but I have found the exact bug I was having trouble with:  Manipulate Fate does not shuffle as part of the resolution.  I tested this via the following method:  make a deck with scroll racks and manipulate fates (and a bunch of singleton cards, for reasons that will be obvious in a second).  set up a scroll rack "set aside" of 7 cards.  Cast manipulate fate knowing the order of each card in the top 7 of my deck (not removing any of those cards, hence the singletons).  draw 7 cards.  The cards will be drawn in the "known" order.  I repeated this multiple times, the odds are astronomical that the order would remain the same, but it always did.  Conclusion: Manipulate Fate  is not shuffling as part of its resolution.

**Comment by ingmargoudt** [comment]
You were absolutely right, will be fixed!
