### ISSUE TITLE
Modal triggered abilities can't handle "one or more"

### ISSUE THREAD

**Issue by theelk801** [magefree/mage#3859]
I'm trying to implement Vindictive Lich, and to start I tried to make a version that doesn't have the targeting restriction. However, unlike a card like Clan Defiance, the mode choice dialog won't let me choose fewer than three modes. This seems to be due to it being a triggered ability rather than a spell ability. I tried to figure out how modes are handled but it's a bit unclear.

**Comment by LevelX2** [comment]
Fixed with 2880b324445a1deb2b65d86097df4c9ff3404184.
