### ISSUE TITLE
Rollback after tutoring causes infinite skipping for those who accept

### ISSUE THREAD

**Issue by zeflap** [magefree/mage#3866]
Rollback after tutoring causes infinite skipping for those who accept

I had this happen a few times playing Commander

**Comment by zeflap** [comment]
Just had this happen with a rollback after casting Fireball, so dialogs might be badness?

**Comment by LevelX2** [comment]
I never was able to reproduce the problem. So the more detail how to reproduce the better.

**Comment by Zerrisx** [comment]
Pretty sure this is a simple duplicate of #2072, specifically that rolling back in certain states results in the other players losing priority for the rest of the game.
