### ISSUE TITLE
Option menu from Ghoulcaller's chant doesn't work.

### ISSUE THREAD

**Issue by harbingerofme** [magefree/mage#3875]
Personally think this is a lag issue, or java, but reposting it here so it can be tested.

> my friend had a problem, casting a spell known as "ghoulcaller's chant"
> sorcery
> it won't go to the stack
> it says it's playable
> it brings up the menu to choose the option
> but it's glitched

**Comment by harbingerofme** [comment]
Quoting,
> so she wants to cast ghoulcaller's chant
because the game says you may cast it
but then the game glitch or something and ghoulcaller's chant wont go to the stack
but when you cancel/want to cast it brings up the option to cast

**Comment by jeffwadsworth** [comment]
Were valid targets in the graveyard?  It would help to have the game log.

**Comment by harbingerofme** [comment]
I'm just relaying the issue, the one who posted it is not responding.

**Comment by theelk801** [comment]
I asked, they didn't respond.

**Comment by Zerrisx** [comment]
No information; cannot reproduce
