### ISSUE TITLE
Request: Indicate if range is set in a multiplayer game

### ISSUE THREAD

**Issue by Zzooouhh** [magefree/mage#3878]
Currently the only person that knows whether a game with range is set is the game host. This can lead to frustrating situations where the host might unwittingly have range set to 1 and nobody realizing until they want to interact with the opposite side player. There could be some kind of a visual cue, like a person's cards, avatar and stats will have appear darkened and shadowy as long as he's out of range, or there could be a descriptor at the start about what range is set, or perhaps both.

**Comment by Zzooouhh** [comment]
As of XMage 1.4.26V8, range still isn't being displayed at the start of the game.

**Comment by LevelX2** [comment]
The range is shown in the list of games. So you can see it before you join.
