### ISSUE TITLE
Teferi's Protection doesn't prevent commander damage

### ISSUE THREAD

**Issue by Zzooouhh** [magefree/mage#3879]
Self explanatory. Got killed by a commander creature while under the effect of Teferi's Protection, which should otherwise prevent that damage due to protection from everything.

**Comment by theelk801** [comment]
While it's probably not what happened here, it should be noted that if an effect that keeps damage from being prevented would a commander can deal 21 points to a player with protection from everything and still kill them, even though their life total wouldn't change. Infect would work similarly.

**Comment by Zzooouhh** [comment]
Of course, but no such effect was in place. It was a WU voltron, which IIRC don't even have such effects accessible in the colors.
