### ISSUE TITLE
Xmage client freezes 

### ISSUE THREAD

**Issue by shadewarrior** [magefree/mage#3884]
when ever I try to launch Xmage I get the more cards need to download and if I choose not to or if I choose to download and cancel it it freezes and wont close I have tried reinstalling but it still does it.

**Comment by LevelX2** [comment]
Probably not related to card download but more to user lock on the server.

1) Deactivate image check on startup in the preferences.
2) Test with the 1.4.26V2 server version, if the problem still exists.
