### ISSUE TITLE
Viridian Revel & Liquid Metal Coating interaction

### ISSUE THREAD

**Issue by AndreasHald** [magefree/mage#3888]
When destroying a permanent that was made an artifact by liquid metal coating, viridian revel does not allow you to draw a card.

This is an incorrect interaction, as when the card enters the graveyard it is still a artifact, thus the player should be allowed to draw.

viridian revel: http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=194266
liquid metal coating: http://gatherer.wizards.com/Pages/Card/Details.aspx?name=liquimetal%20coating
See ruling: http://www.mtgsalvation.com/forums/magic-fundamentals/the-rumor-mill/new-card-discussion/rumored-card-rulings/238187-viridian-revel-liquimetal-coating

**Comment by Superkaj** [comment]
I think the error is it only checks the cards original type, rather than the type it was on the battlefield.
