### ISSUE TITLE
"Nazahn, Revered Blacksmith" cannot reveal "Hammer of Nazahn"

### ISSUE THREAD

**Issue by epikfaal** [magefree/mage#3889]
when you cast Nazahn, Revered Blacksmith and you search for hammer of nazahn It prompts if you want to put hammer of nazahn onto the battlefield. Wether you say yes or no, no card is revealed and nothing happens. http://puu.sh/xkHVi/fce6f528c3.jpg http://puu.sh/xkHVO/818edb633c.jpg

**Comment by theelk801** [comment]
Just fixed this
