### ISSUE TITLE
Vindictive Lich issue

### ISSUE THREAD

**Issue by theelk801** [magefree/mage#3895]
From Discord:
"Vindictive Live (C17) after it died in combat, it gave me the option to chose which effects i want and which effect target which player, but nothing happend after i selected it.
so noone throw cards away, noone lost life and noone had to sacrifice a creature"

**Comment by Zzooouhh** [comment]
I should note that this happened to me in a game where Vindictive Lich died and I had two opponents. Maybe it fizzles on less than three opponents?

**Comment by Zerrisx** [comment]
Duplicate of #4742
