### ISSUE TITLE
Teferi's Protection doesn't stop already targeted permanents from being destroyed

### ISSUE THREAD

**Issue by Zzooouhh** [magefree/mage#3897]
I got a Glacial Chasm targeted by Acidic Slime and I cast Teferi's Protection in response - the end result was that my permanents got phased out, but after resolving the Slime the Chasm still got destroyed. This kind of beats the whole point of Teferi's Protection, no?

**Comment by Zzooouhh** [comment]
And on the topic of Glacial Chasm - somehow it's possible to pay more life for it than you have, getting you into negative total.

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.
