### ISSUE TITLE
Issues when trying to log into any server

### ISSUE THREAD

**Issue by albuzs** [magefree/mage#3899]
I am getting the following:

![image](https://user-images.githubusercontent.com/16671803/29836532-592dec62-8caa-11e7-86b6-cb08b2b2e95e.png)

What can I do?

**Comment by albuzs** [comment]
guys? :D

**Comment by LevelX2** [comment]
You use the most recent client version?
Otherwise try to restart your system.

**Comment by albuzs** [comment]
Yes, that is the most recent version.

**Comment by spjspj** [comment]
Hopefully this is resolved.
