### ISSUE TITLE
Progenitor Mimic (possibly other clones?) stays on battlefield after their owner leaves/loses the gams

### ISSUE THREAD

**Issue by Zzooouhh** [magefree/mage#3916]
If I understand correctly, if a clone card gets stolen with Control Magic and the like, and the owner dies, it should disappear. Recently I've had a Progenitor Mimic stick around even after the owner conceded.

**Comment by theelk801** [comment]
So your opponent owned Progenitor Mimic and you had stolen it or it was your Progenitor Mimic and you copied your opponent's creature?

**Comment by Zzooouhh** [comment]
The former. Also it was the original Progenitor Mimic, not its token copies that stayed.

**Comment by LevelX2** [comment]
I guess this is no card specific problem but caused by errors that can happen during the player removing from the game.
Handled here: #3885

**Comment by Zerrisx** [comment]
Duplicate of #4472
