### ISSUE TITLE
Duplicant copying */* creatures issue

### ISSUE THREAD

**Issue by Zzooouhh** [magefree/mage#3925]
I've had an opponent exile my Rubblehulk which was a 9/9 at the time. The opponent's Duplicant stayed a 9/9 despite only having 6 lands at the time (and this value didn't change with further landdrops). Duplicant should inherit all the \*/\* modifiers of the original card, as per its ruling:

> 6/8/2016 | Abilities  that define a creature’s power and toughness apply while that card is  in exile, but abilities that add or subtract from it don’t. For example,  the ability of Battle Squadron applies to determine Duplicant’s power  and toughness, but the ability of Werebear doesn’t. Duplicant’s power  and toughness are constantly updated if the exiled card’s power and/or  toughness change.
> -- | --

**Comment by emerald000** [comment]
It is still your own Rubblehulk in your own exile zone. So it checks the number of lands you control for its power (and thus Duplicant power).

But if you play another land drop and Duplicant doesn't become a 10/10, then it is a bug.

**Comment by Zzooouhh** [comment]
I don't exactly remember how my landdrops changed, but you're right about it following my landdrops and I've misinterpreted the rule. I'll update this if I ever encounter it again.
