### ISSUE TITLE
Kess, Dissident Mage exiles cards returned to hand and cast via other means

### ISSUE THREAD

**Issue by SpikesCafe-google** [magefree/mage#3928]
I have Kess, Dissident Mage in play. I cast a spell from my graveyard (Gitaxian Probe) using her ability. It's exiled, correctly. I then exile Metallurgic Summonings from the battlefield, returning all the other spells in my graveyard to my hand. When I cast them and they resolve, Kess exiles them. As the spell resolves, I'm ending up with a massively long list of "Choose replacement effect to resolve first", all Kess. (This list also shows up for the spells I cast using Kess's ability, which is maybe the same bug, though it doesn't affect correctness there; just creates an annoying prompt.) If I draw other cards and cast them, Kess does not exile them, only the ones that I returned from my graveyard to my hand.

Another possibly related issue is that a spell cast with buyback using Kess's ability ends up in exile. Rather, it should end up in my hand. This is different from flashback. There's a chance I missed the option to return it to my hand on the long list of replacement effects, but I don't think it should get to the replacement effects layer.

Using 1.4.26V3.

**Comment by derlhurgoyf** [comment]
I can confirm this in 1.4.27V4b.

Also if you cast a spell with flashback from your graveyard and then play Kess, it won't let you play another spell using her ability.

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.
