### ISSUE TITLE
Grenzo, Havoc Raiser (likely) freezes the game!!!

### ISSUE THREAD

**Issue by Zzooouhh** [magefree/mage#3937]
Two games in a row, I attacked with Grenzo, Havoc Raiser (in the first game) or attacked with a creature while Grenzo was out (second one). Upon hitting a player, no trigger gets put on the stack, the game freezes at "play instants and sorceries", the client is still responsive and players can chat, but neither rollback nor concede works to move the game forward. Seeing how he normally triggered in the previous version, I'm very suspicious that this might be somehow related to the fixes that were supposed to address goad-related bugs like #3919 and #3891. What's important to note is that everybody in the game was up-to-date on the new V3 version.

**Comment by jeffwadsworth** [comment]
Please refrain from adding exclamation marks.  Thanks.

**Comment by LevelX2** [comment]
Fixed beyond 1.4.26V3
