### ISSUE TITLE
Atarka, World Render Issues

### ISSUE THREAD

**Issue by azdraik** [magefree/mage#3956]
When you cast Atarka, World Render and there is another dragon in play you receive the following message.
"Pay Kicker-Tap one Dragon you control ?"  Atarka, World Render has no kicker.

When attacking with Atarka, World Render his trigger "Whenever a dragon you control attacks, it gains double strike until end of turn." fails to trigger.

When attacking with another dragon while Atarka, World Render is on the battlefield, Atarka fails to trigger his "Whenever a dragon you control attacks, it gains double strike until end of turn." ability.

running 1.4.26V3 on a 1.4.26V3 server

**Comment by ingmargoudt** [comment]
The kicker ability was falsely added, its now removed so please wait for the next release. I can see in the code that Double Strike is not granted. Will be fixed in the next release as well./

**Comment by azdraik** [comment]
Thank you for your prompt response.   First time reporting any issue and did not know how often these are checked.

**Comment by ingmargoudt** [comment]
Actually after looking another time : the double strike clause is in the code, will make a Unit Test for this first to verify the bug

**Comment by theelk801** [comment]
Atarka has been reverted to before it was changed as part of the text change experiment.
