### ISSUE TITLE
Mairsil + Quicksilver Elemental interaction not working correctly

### ISSUE THREAD

**Issue by ben-hig** [magefree/mage#3963]
When Mairsil, the Pretender has a cage counter on a Quicksilver Elemental, he should be able to activate the effect of quicksilver elemental targeting himself to bypass the once per turn limitation on effects gained with cage counters. 
However, many effects are still limited to once per turn. I've encountered some activated effects on Mairsil that he can use more than once per turn after activating Quicksilver Elemental's effect, such when a cage counter is on Pili-Pala. An example of an effect that he could not activate more than once in a turn after Quicksilver Elemental's effect is that of Shauku, Endbringer. So possibly looking into whatever is inconsistent between those two effects could be a start.

![image](https://user-images.githubusercontent.com/12514402/30246583-5da3a156-95c4-11e7-9eaf-171221f7a7cd.png) ![image](https://user-images.githubusercontent.com/12514402/30246584-68ffa004-95c4-11e7-8c67-c706a65d34ac.png) 
![image](https://user-images.githubusercontent.com/12514402/30246610-df29d934-95c4-11e7-9045-0ede8c84d9e8.png) ![image](https://user-images.githubusercontent.com/12514402/30246607-d787f85a-95c4-11e7-800b-6883b21eb88e.png)

**Comment by ben-hig** [comment]
So here are some observations and thing's I've learned from testing that will hopefully help someone work on this. 

- The interaction with Pili-Pala is a bug, and Mairsil can probably Pili-Pala's effect more than once per turn without Quicksilver Elemental. This is probably because Pili-Pala's copy method isn't written correctly (I'm just assuming it isn't because it looks different from other cards' copy methods. I know nothing about this codebase).

- If the proper interaction between Quicksilver Elemental and Mairsil is going to be supported, the UI is going to quickly become pretty unfriendly since Mairsil should gain copies of all of the effects that he already had, so when you click on Mairsil to activate one of his effects, there should be two of each effect after a Quicksilver Elemental activation. The game would need to keep track of which instances of each effect have already been activated, and which instances can still be activated that turn. Also, with additional activations of the copies of Quicksilver Elemental's effect, the number of effects on Mairsil grows exponentially, since he copies all of the copied effects too. Going infinite could mean scrolling through hundreds of activated abilities on Mairsil looking for the ones that haven't been used yet that turn, with no indication until you click one that it has in fact been used already.

**Comment by theelk801** [comment]
This interaction should work correctly now, and unuseable abilities won't show up in the dialog anymore. Mana abilities like Pili-Pala's are also now working properly.

There's still gonna be a whole hell of a lot of abilities if you continue activating Quicksilver Elemental though.
