### ISSUE TITLE
Wave of Vitriol + Stranglehold interaction is bugged

### ISSUE THREAD

**Issue by Zzooouhh** [magefree/mage#3966]
I cast Wave of Vitriol while an opponent has Stranglehold in play. All nonbasic lands, enchantments and artifacts get sacced, but afterwards only Stranglehold's controller is capable of searching for lands. Stranglehold's effect however shouldn't be applying in this scenario at all, according to at least this source: http://www.essentialmagic.com/Combos/CommentsAndRatings.asp?ID=74341

**Comment by JRHerlehy** [comment]
Needs testing and Unit Test to confirm.
