### ISSUE TITLE
Arrows drawn over dialog windows

### ISSUE THREAD

**Issue by The0retico** [magefree/mage#397]
I create a table, but don't start the game yet, and I start to watch another game, the arrows (e.g. indicating a player being attacked) are drawn over the dialog with my table.

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.

**Comment by JayDi85** [comment]
It's a rare bug with other ingame elements drawing over lobby/tables window. It can be related to xmage's app icon on task panel -- if you move mouse over that icon then windows/screens can be somehow broken and a weird bugs can raise (in old days I used "mouse over icon" action to test wrong choose dialogs order -- it was able to broke the windows order and modal status).

Also it maybe related to "click-through" bug (#4181)

**Comment by JayDi85** [comment]
Fixed in e33a5f4861a6538456f13f3feec03b88005d5073
