### ISSUE TITLE
Get transparent corner image cards on Scryfall image source

### ISSUE THREAD

**Issue by nachazo** [magefree/mage#3970]
Scryfall API serves different format images. Actually XMage gets "normal" image. API provides better resources.

For example: https://api.scryfall.com/cards/hou/49
Actually XMage gets the "large" json value. There are two better options:
- border_crop: A new addition in their API that gets the same image but with no ugly white corner borders.
- png: The hq image with correct transparent borders. Bigger in size (like 1MB per image) but the high-quality.
I think the best could be use two image soruces: Scryfall plain JPG ("border_crop" value) and Scryfall HQ PNG ("png" value).

Any case, just change the actual jpg for "border_crop" value is less impact and images will looks much better.

**Comment by JayDi85** [comment]
Png images created from jpg scan source. It's the same quality but need x5 times more disk space.

It is better add to client's draw engine future to cut corners before rendering.

**Comment by JayDi85** [comment]
Added new round corner render in #4173 pull request. Issue can be closed.

![shot_171118_050548](https://user-images.githubusercontent.com/8344157/32975802-c5db2064-cc24-11e7-9d58-3b0d7770cfc0.png)
