### ISSUE TITLE
Issue with new phasing rules

### ISSUE THREAD

**Issue by Sertaki** [magefree/mage#3972]
Under the new phasing rules, any counters present on a permanent phase out with the permanent and it returns with the same number of counters.
This doesn't work correctly right now, counters are removed when a permanent phases in.

At least it happened to me, using Ramoz with several +1/+1 counters when I played Teferi's Protection. Ramoz returned with no counters.

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.
