### ISSUE TITLE
Xmage not loading when I launch java.

### ISSUE THREAD

**Issue by saraque1** [magefree/mage#3998]
When I download xmage off from the website, a java console window opens and closes, nothing else. It wont get to the point where I can open the folder. I have no idea how to fix this issue please help.

**Comment by Arc676** [comment]
You should have gotten a JAR file. You're saying that it crashes when you open the JAR file? Do you have Java installed?

Also, you should include your operating system so people have more information with which they can help you.

**Comment by spjspj** [comment]
Read the instruction manual (https://drive.google.com/open?id=0B1n0u_Vny_add013ZDVuSGJwMWM or on the sidebar of https://www.reddit.com/r/XMage/).

**Comment by saraque1** [comment]
So, that doesnt work, I have fresh installed java(running on windows 10) and the game file, moved it into a folder, and the same issue of when i try to  launch the jar file a blank console window pops up real fast and then closes.
