### ISSUE TITLE
Xmage not loading when jar file is launched

### ISSUE THREAD

**Issue by saraque1** [magefree/mage#4000]
Had a previous thread and was closed before I could respond with if it was fixed or not, So, The Manuel didn't help, I just redid things I was already doing, I have fresh installed java(running on windows 10) and the game file, moved it into a folder, and the same issue of when I try to launch the jar file a blank console window pops up real fast and then closes.

running java Version 8 Update 144
Os Windows 10
newest version of the xmage download off the home page

**Comment by spjspj** [comment]
* Have you tried doing it this way? https://www.youtube.com/watch?v=FL89GFJv0_A
* Start up a cmd prompt to run the batch file (Windows key + r then cmd) >> This way you will see what the error actually is
* You may not have ".jar" associated with "java" in windows. 
* Don't use the launcher.  It adds a further layer of complexity which isn't required.

**Comment by saraque1** [comment]
Let me try it real fast should take ~5 min

**Comment by saraque1** [comment]
How would I run a batch file in cmd?

**Comment by saraque1** [comment]
so i got the youtube method to work does that mean i would have to download the new version of that website evey update?

**Comment by saraque1** [comment]
seems to be something with java, do you know anything on how i would fix that, end of it?

**Comment by spjspj** [comment]
* C:\Users\spjspj>run_me.bat    <<<  How to run a batch file
 * The current server version is 1.4.26v4   (major version is 1.4.26, minor version is v4).  Mostly any client that is the same major version (aka 1.4.26vX) should be fine.  (But in the last two, some changes have occurred on the server that requires the latest client version.
