### ISSUE TITLE
Deathgorge Scavenger doesn't pump itself

### ISSUE THREAD

**Issue by AricHaldan** [magefree/mage#4005]
I attacked with Deathgorge Scavenger exiling an abrade with it's trigger and it didn't get +1/+1 until end of turn. Instead it remained a 4/3 (had a +1/+1 counter on it from savage stomp).

**Comment by theelk801** [comment]
This will be fixed in the next release (e15f020)

**Comment by AricHaldan** [comment]
ok thanks :)
