### ISSUE TITLE
Admiral Beckett Brass not triggering

### ISSUE THREAD

**Issue by mtgfuller** [magefree/mage#4006]
Hello, I'd just like to report that Beckett Brass didn't trigger at my end step. Though I'm unable to say whether this was just a one-off or a conistant bug.

**Comment by theelk801** [comment]
Can you give details on what happened, i.e. what you attacked/dealt damage with?

**Comment by mtgfuller** [comment]
I _believe_ I attacked (and dealt combat damage) with two **_Siren Stormtamers_** and a **_Storm Fleet Aerialist_**. Though one of those creatures might have been a **_Kitesail Freebooter_**. 

Sorry for being vague - this is my first bug report.

**Comment by mtgfuller** [comment]
The ''(I _believe_)'' is putting the creatures into question, not whether I attacked/dealt damage to player, btw.

**Comment by theelk801** [comment]
Thanks, I was able to figure out what the problem probably was. Should be fixed in the next release.
