### ISSUE TITLE
Enrage triggers multiple times from combat damage

### ISSUE THREAD

**Issue by theelk801** [magefree/mage#4015]
If a creature with enrage is dealt combat damage by more than one creature (such as being double blocked) then the ability should only trigger once but currently triggers for each creature that deals damage. It seems like an issue with how events are fired during combat but I don't want to mess anything up.

**Comment by theelk801** [comment]
This has been partially fixed, but Boros Reckoner can still target multiple things if dealt combat damage by multiple sources simultaneously.

**Comment by Zerrisx** [comment]
Since it's now just Boros Reckoner (which isn't even an enrage creature), can we rename and/or move this to a new issue?

**Comment by awjackson** [comment]
I believe this was fixed by #8017 . At any rate it's no longer an issue.
