### ISSUE TITLE
Entrancing Melody instant speed bug and others

### ISSUE THREAD

**Issue by mtgfuller** [magefree/mage#4019]
Hello,

https://i.gyazo.com/c677c7cf34a18dd236cd9b87767bb0ab.mp4 As you can see from this, **_Entrancing Melody_** seems to be acting (whether just occasionally or not) as an instant. (this recording is taken from an AI game)

Also, during a previous (non-AI) game I cast **_Entrancing Melody_** X=1 and it said there were no valid targets, even though my opponent had an **_Old-growth Dryads_**. The next game I was also unable to target my opponent's **_Walking Balista_** with the spell.

Thanks

**Comment by theelk801** [comment]
Is this the latest version that was released today? It's definitely not supposed to be an instant, which I can fix, but today's patch should have fixed the targeting issue.

**Comment by mtgfuller** [comment]
Yeah it was today after having updated it. I was able to target other creatures which were in play, just not the Ballista.

**Comment by theelk801** [comment]
I can't recreate this, are you sure you chose X=0?

**Comment by mtgfuller** [comment]
I'm fairly certain I did. It was also letting me target (though I don't know what would have happened) other creatures.

Me and my opponent pretended it had resolved with him pinging me with his ballista to kill it (as he would have done if it had worked) and me paying 2 mana on X=0, targeting my own 2CMC creature.

**Comment by theelk801** [comment]
You mean you cast it for x=2 and targeted a 2CMC creature? Your server's probably on the older patch since that was the issue before.

**Comment by mtgfuller** [comment]
Oh right. The game was on XMage.de 1 about 2 hours ago, btw.

**Comment by theelk801** [comment]
Based on another conversation, I'm pretty sure that it hasn't updated yet. I'm gonna say that this is dealt with.
