### ISSUE TITLE
Deadeye explorer

### ISSUE THREAD

**Issue by AricHaldan** [magefree/mage#4020]
Game exception occurred: java.lang.ClassCastException
Server version: 1.4.26V4
cannot activate the ability due to an error

**Comment by theelk801** [comment]
Is your server on the latest version? This is probably a bug that was already fixed.

**Comment by AricHaldan** [comment]
it seems there is a new update, but the server I was on was xmage.de, is that one not updated yet or ?

**Comment by theelk801** [comment]
Oh wait, it says 1.4.26V4 right there, which is the older one. I should learn to read. Yeah, this issue should be solved in V5.
