### ISSUE TITLE
Arcbound Slith currently triggers on any damage to a player, should trigger only on combat damage.

### ISSUE THREAD

**Issue by HanClinto** [magefree/mage#4026]
Arcbound Slith currently uses `DealsDamageToAPlayerTriggeredAbility`, which triggers any time damage is dealt to a player (I.E., using something like Viridian Longbow to tap and ping).  It should instead only trigger on _combat_ damage.  I think subbing in `DealsCombatDamageToAPlayerTriggeredAbility` should fix this.

**Comment by HanClinto** [comment]
Glass Asp is the same way -- should trigger only on combat damage, currently triggers on any damage.

**Comment by HanClinto** [comment]
Same with Nightveil Specter, Raven Guild Master, Diviner Spirit, and Rakdos the Defiler

These all currently use DealsDamageToAPlayerTriggeredAbility, and should use DealsCombatDamageToAPlayerTriggeredAbility instead.

**Comment by HanClinto** [comment]
@theelk801 Nice job finding Kheru Mind Eater -- not sure how I missed that one.  Well done!  👍

**Comment by theelk801** [comment]
I did a find usages search on `DealsDamageToAPlayerTriggeredAbility` and checked each one, wasn't too many to check. The embarrassing part is that it's a card I implemented.
