### ISSUE TITLE
pls,I can not see seven cards

### ISSUE THREAD

**Issue by wgcwgc0421** [magefree/mage#4031]
I play this game with mac pro  my screen is small. when I have seven cards in hand,I cant see last one becasue it under the another control

and I can not add card to deck because when I click add button it not work

**Comment by LevelX2** [comment]
The the size to show hand cards to a smaller size (menu - Preferences - GUI Sizes). That causes a bar to appear below the hand cards.
You need to use client 1.4.26V5 to prevent the problems with the card editor. Version is shown in the xmage title bar.

**Comment by Zerrisx** [comment]
This looks to be resolved.
