### ISSUE TITLE
Ixalan Territorial Hammerskull can not choose creature with summoning sickness

### ISSUE THREAD

**Issue by DerekMangrum** [magefree/mage#4033]
Territorial Hammerskull taps an opponent's creature when it attacks. I was not able to pick a creature with summoning sickness

**Comment by theelk801** [comment]
I couldn't recreate this. Do you have any other details on what happened?

**Comment by DerekMangrum** [comment]
Not too many other details.... I attacked with a Territorial Hammerskull.
The opponent had two creatures, one with summoning sickness. I tried
clicking on that creature to select it with the Hammerskull's effect. I
tried multiple times at multiple different places on the card. I was unable
to select it. I then clicked the second create (without summoning sickness)
and the effect triggered immediately.

I will try to re-create it locally and see if I can get any other details
that may be relevant.

Thank you.

**Comment by DerekMangrum** [comment]
Hello again.

I just tried it again locally and was able to tap a sickness creature. Not
sure if it might have been related to the targeted creature, or just a
fluke. I don't remember which creature I targeted yesterday.

I guess we can close this issue. Thanks for looking in to it! You all are
awesome!

**Comment by theelk801** [comment]
Weird, alright then.

**Comment by theelk801** [comment]
Weird, alright then.
