### ISSUE TITLE
Search for Azcanta sequencing is incorrect

### ISSUE THREAD

**Issue by aravance** [magefree/mage#4034]
What happens instead?
1. Would you like to use Search for Azcanta ability?
2. Would you like to put this card into the graveyard?
3. Transform without any question if yes to 1.

Search for Azcanta should do the following:
1. Look at the top card of library (not optional)
2. You may put that card in your graveyard.
3. Iff you have 7 or more cards in your graveyard, you may transform.

The sequencing of the questions and how it asks is incorrect. 1 should always happen 2 and 3 should be completely independent from 1 and from each other.

**Comment by theelk801** [comment]
This has been fixed for the next release.

**Comment by aravance** [comment]
May be fixed by 8586956552752fe2353e4bb0d190e658de8eb510

**Comment by theelk801** [comment]
Yeah, forgot to link it. That's where I fixed it.
