### ISSUE TITLE
Stuck on selecting a player to go first

### ISSUE THREAD

**Issue by blamblegam** [magefree/mage#4038]
Whenever I join a game it always gets stuck on selecting a player to go first. I will select a player to go, the log will say I draw seven cards but I can't see the cards I have drawn and It still asks me to select a player.

**Comment by LevelX2** [comment]
What client version do you use? Sounds like you use a client version < 1.4.26V4.
The client version is shown in the xmage title bar.
[Client version] - [server version]

**Comment by blamblegam** [comment]
I ended up just uninstalling then installomg again and it fixed the issue

**Comment by Zerrisx** [comment]
Issue was fixed. Lovely!
