### ISSUE TITLE
IXALAN card error

### ISSUE THREAD

**Issue by George7Walker** [magefree/mage#4044]
*Mavren Fein, Dusk Apostle (XLN)/2W. error: Crea una ficha vampiro en mi lado del campo aunque ataque un vampiro q controla mi oponente. Debe cumplirse solo si yo controlo el otro vampire atacante.
*Sunbird’s Invocation (XLN)/5R. Error.Error. No deja lanzar ningún hechizo después de que esta en el campo. Error. No se cumple el texto.

**Comment by emerald000** [comment]
Estos errores se resolverán en la próxima versión.

**Comment by George7Walker** [comment]
Usare este medio para notificarles otro error de las cartas:

XLN - Trove of Temptation (3R):  La primera regla No se cumple. "Debe"
atacar si se puede por supuesto pero No se cumple, el oponente decide No
hacerlo.
XLN - Verdant Sun's Avatar (5GG): No ganas vida si otra criatura entra al
campo bajo tu control.

2017-09-22 20:50 GMT-04:00 emerald000 <notifications@github.com>:
