### ISSUE TITLE
Excavation and "any player may activate this ability" ability controller issues

### ISSUE THREAD

**Issue by Zzooouhh** [magefree/mage#4047]
As currently implemented, the card Excavation, if used by somebody other than its controller, makes the user pay the ability's mana cost and sacrifice a land, but Excavation's controller is the one drawing a card as a result of the ability - when it instead should've been the player that activated it. This is probably part of a bigger issue concerning all sorts of targeted "any player may activate this ability" type effects (most of which are on cards that aren't implemented yet).

**Comment by theelk801** [comment]
Looks like the person who activates the ability isn't being properly set as the controller of the ability.

**Comment by theelk801** [comment]
Pretty sure I've fixed this, hopefully the fix will allow for targeting as well.

**Comment by Zzooouhh** [comment]
Yes, this works great! I've even tried it with Tidal Control and it fixed the targetting issue.

**Comment by theelk801** [comment]
Awesome, hopefully I didn't break anything.
