### ISSUE TITLE
Daxos of Meletis - spells cast/stolen by opponent can't be cast anymore if drawn again(?)

### ISSUE THREAD

**Issue by Zzooouhh** [magefree/mage#4048]
In testing, I've had an opponent's Daxos of Meletis exile my Black Lotus and a Timetwister. He sacrificed the Black Lotus to play the Timetwister, shuffliing those two into my new hand. However, I was unable to cast the two cards anymore during my turn - I've even tried having multiples of both Black Lotus and Timetwister in hand, and I was able to cast all of those cards but the two stolen copies. Haven't tested whether this principle also applies to similarily functioning effects (e.g. Thada Adel, Acquisitor) or even stolen lands when such an effect is applicable (maybe exile cards from library, into opponent's Oblivion Sower, into Sunder?).

**Comment by theelk801** [comment]
I've seen similar things reported (stole a card, cast it, ends up in owner's hand and can't be cast) but it's hard to figure out exactly why it happens. I think it may be the effect that allows it to be cast from exile sticking around.

**Comment by Zzooouhh** [comment]
Another fact I've recently noticed about this that might be of some note is that the stolen card's "unplayability from hand" persists even after a rollback.

**Comment by Zzooouhh** [comment]
Another fact I've recently noticed about this that might be of some note is that the stolen card's "unplayability from hand" persists even after a rollback.
