### ISSUE TITLE
Feature Request: Personal collection

### ISSUE THREAD

**Issue by Thedrummonger** [magefree/mage#4054]
Basically just a collection of cards that you can sort through when deck build. You could use it to reflect cards you own IRL or just a collection of essentials that should go in your commander decks for example. It would also solve an issue with cards that let you play cards you own outside the game. These cards currently don't work at all in commander since they pull from sideboard and commander has no side board. The rules for these cards mostly say the cards pull from your sideboard but most sources agree that in casual matches it perfectly fine to pull cards from your personal collection (See rule 1 here for example http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=414343). A personal collection would not only solve this but also provide a nice tool for deck building.
Thanks!

**Comment by JayDi85** [comment]
Choose card from outside uses card searching feature, it’s easy to use so no needs in additional lists or collections.
