### ISSUE TITLE
Wrong hint text format on stack card (active ability)

### ISSUE THREAD

**Issue by JayDi85** [magefree/mage#4057]
If you try to see stack card hint with mouse's middle button scrolls then you get 3 types of hint:
1. Original image only -- OK;
2. Text only -- OK (text format is good);
3. Original image with active ability's text -- WRONG (it do not apply card text formatting).

Example:
![shot_170925_034955](https://user-images.githubusercontent.com/8344157/30788233-d064eb32-a1a9-11e7-85d1-24ecd819075b.png)

**Comment by LevelX2** [comment]
Text formatting was added. 
Replacement of special signs (e.g. {G}) missing.

**Comment by JayDi85** [comment]
Example:
![shot_231127_015224](https://github.com/magefree/mage/assets/8344157/4fbda347-3383-4481-9b4a-1cc76d005cf0)
