### ISSUE TITLE
Verify test: add card numbers checking

### ISSUE THREAD

**Issue by theelk801** [magefree/mage#4073]
From the forums:
>As more cards have been implemented 5 cards have been missed that use alternate art within the same set; Phantasmal Fiend, Stench of Decay, Noble Steed and Foresight from Alliances (Foresight is also numbered incorrectly being placed within the artifacts) and Jace, Unraveler of Secrets in MBP.

Looking at the files and the card info text document, the numberings seem to be wrong for a lot of cards. Is there an intended numbering that's supposed to be used?

**Comment by Zzooouhh** [comment]
I personally adapt card numbering from magiccards.info, since that's the only site I can find with comprehensive numbering for the old sets.

**Comment by JayDi85** [comment]
@Zzooouhh scryfall have excellent card database and card numbers (look at url: https://scryfall.com/card/e02/42 ). They have [good API](https://scryfall.com/docs/api/sets) to query sets and cards data. Maybe someone can write script to check it out with game's database.

**Comment by xenohedron** [comment]
`VerifyCardDataTest` has `test_checkWrongCardsDataInSets()` and `test_checkMissingScryfallSettingsAndCardNumbers()` for this purpose, but both are currently ignored due to large number of errors (including false positives such as split cards, foils, alternate arts, promos, etc.)
