### ISSUE TITLE
Torpor Orb doesn't prevent Eminence

### ISSUE THREAD

**Issue by zeflap** [magefree/mage#4074]
as above, Edgar still makes vampires, Inalla gets to double up on Wizards, etc.

**Comment by theelk801** [comment]
Just tested this and it worked fine with Inalla. It wouldn't affect the other three anyway since none of them are abilities that trigger off a creature entering.

**Comment by Zerrisx** [comment]
Edgar also isn't affected; he triggers on cast not on ETB.  Closing this as not a bug.
