### ISSUE TITLE
Handle reset of changed attributes of cards (e.g. Painter's Servant)

### ISSUE THREAD

**Issue by Eligos09** [magefree/mage#408]
Static Ability of Painter's Servant: "All cards that aren't in play, spells, and permanents are the chosen color in addition to their other colors" working even if creature leaved battlefield

**Comment by Dilnu** [comment]
Hi there. Should Pull Request 2199 (Implementing Conspiracy) wait on this issue being fixed?

**Comment by Dilnu** [comment]
https://github.com/magefree/mage/pull/2199

**Comment by Dilnu** [comment]
Also Teferi, Mage of Zhalfir has nearly the same issue, so the final solution should be able to handle adding abilities as well.

**Comment by Dilnu** [comment]
Maybe this was the wrong thing to do but I'm trying to add subtype functionality. The change is getting rather large though.

**Comment by emerald000** [comment]
Yes, it is quite the undertaking. I started working on it a while back, but gave up after I realized what I was getting into.

PS: You may want to join our Gitter chat if you have questions. It's usually the best and fastest way to get an answer.

**Comment by Dilnu** [comment]
How do I get into that? Also I estimate I'm more than 50% done.

**Comment by LevelX2** [comment]
Should work now.
