### ISSUE TITLE
Morph/Manifest vs Undying Evil/Supernatural Stamina

### ISSUE THREAD

**Issue by Diego13pa** [magefree/mage#4080]
When I play a supernatural stamina/undying evil on a facedown creature, the card doesn't return to the battlefield, because the ability does not trigger
Step 1:

![bug report 1](https://user-images.githubusercontent.com/4550451/31059482-63cb8b54-a6d9-11e7-9a78-3fb8c13dc3e5.png)

Step 2:
![bug report 2](https://user-images.githubusercontent.com/4550451/31059525-efee8b36-a6d9-11e7-8d9e-bd618b6d825f.png)

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.
