### ISSUE TITLE
Supernatural Stamina / Undying Evil + "when {this} dies" trigger

### ISSUE THREAD

**Issue by Diego13pa** [magefree/mage#4081]
When I play a supernatural stamina/ undying evil on a creature with a "when {this} dies" trigger, both abilities are put in the stack, but xmage shows the same text for them (but the resolution was correct).

Text 1:
![bugtrigger1](https://user-images.githubusercontent.com/4550451/31059557-98144a4e-a6da-11e7-9ea2-d2290527836c.png)

Text 2:
![bugtrigger2](https://user-images.githubusercontent.com/4550451/31059563-b5ef3e70-a6da-11e7-8699-885ee83cc1cf.png)

**Comment by Zerrisx** [comment]
The hover image doesn't refresh if you mouse directly from one to the other, but if you mouse away then mouse back, they're both correct.  The issue as described doesn't seem to be a bug any more.
