### ISSUE TITLE
No option to Bestow from command zone (and command zone Aura oddities)

### ISSUE THREAD

**Issue by Zzooouhh** [magefree/mage#4083]
This one is a very low priority fix, seeing how there's no "official" legal choice for a commander with Bestow at the moment (nor is there much likelihood of one happening in the future), but I figured I should mention it anyway. I've been testing behavior of Chromanticore as a general in a vs. AI environment, and he can only be cast from the CZ for his regular casting cost as a normal creature. Bestow is an alternate cost, so it should be applicable for casting from the CZ too, just like something like Dash is. Also, commander tax would also add up to his Bestow cost.

Another closely related issue is that even if it was possible to cast as Bestow, it probably wouldn't even attach to anything. I've tried sticking Spirit Link in the command zone and casting it, and it came to the battlefield unattached, immediately getting sacrificed as a SBA - perhaps the CZ disallows the player from "targetting" the commander?

**Comment by Zerrisx** [comment]
Kestia, the Cultivator is now a commander with Bestow!  It happened!  And yes, it's slightly bugged.  Looks like the bestow costs are tracked correctly and you can bestow from the command zone... but the commander won't attached to the target you bestow on.  Wrote more concise issue to track this in #6763.
