### ISSUE TITLE
Urborg (second ability) is busted

### ISSUE THREAD

**Issue by Zzooouhh** [magefree/mage#4088]
I'm talking about the original Urborg from Legends. Its second ability ({tap}: Target creature loses first strike or swampwalk until end of turn) is very broken - not only can it only remove First Strike and there isn't an option for Swampwalk, but for some reason the textbox will continue asking to remove the ability several times whenever the Urborg's user gets priority or at the beginning of every phase for the remainder of the game - whenever I get priority or whenever a phase passes, the "What ability do you wish to remove?" window pops up up to seven times in a row! And from what I can tell, not every window actually affects the creature, probably only the last one does but I'm not sure.

What's important is that the windows keep popping up for the rest of the game, not only effectively making it possible to remove First Strike from a creature permanently, but also making the game virtually unplayable. Another flaw that Urborg features is that you can cancel the "remove ability" window, when the card isn't supposed to give the user that option.

**Comment by theelk801** [comment]
Looks like the ability is implemented as a continuous effect, when it should be a one-shot effect that sets up a continuous effect. It's the only card that uses that ability, so it's probably an easy fix.

**Comment by Zzooouhh** [comment]
It's also important since there are similar cards yet to be implemented, such as Hammerheim, that will most likely be using the same code.

**Comment by ingmargoudt** [comment]
Urborg has the wrong duration :  Duration.WhileOnBattlefield, while it should be Duration.EndOfTurn

**Comment by theelk801** [comment]
Alright, problem solved, at least for now.
