### ISSUE TITLE
Deck Editor search regression

### ISSUE THREAD

**Issue by Zzooouhh** [magefree/mage#4091]
Ever since the newest update to V7, it appears that the way the search function in Deck Editor was handled has changed - in the previous version, typing a multiple word phrase like "destroy all enchantments" would yield only results that feature all of the words (Back In Nature, Bane of Progress etc.). Currently however, it displays all cards featuring either "destroy", "all" or "enchantments" in either of the ticked search fields (so with rules ticked, it's a long list of cards including things like Wasteland), which is much more clunky in almost all uses in my opinion - it would be good to bring the old search back, or perhaps if this was a deliberate change, I'd very much like to at least see a button/tickbox/something to switch between the two modes of search.

**Comment by ingmargoudt** [comment]
Correct, the code for the text searching has changed. I will check how it is different now. Thanks for reporting.

**Comment by tawmas** [comment]
I also noticed this and I find it very annoying. Not only you can no longer filter by useful phrases, as already reported above, but often searching for an exact card name yields multiple results (at times, outright too many).

**Comment by ingmargoudt** [comment]
I reverted the change that caused this regression, closing issue.
