### ISSUE TITLE
Hostage Taker XLN

### ISSUE THREAD

**Issue by deciphering** [magefree/mage#4098]
The exiled artifact/creature should be able to be cast using any mana colour, but xmage still asks to pay the exact mana cost of the card.

**Comment by theelk801** [comment]
Are you trying to pay with mana already in your pool or are you tapping lands while paying costs? If the mana's already in your pool, then it's a known issue.

**Comment by deciphering** [comment]
Tapping lands while paying costs. It asks me to pay the exact converted mana cost of the exiled card.  



Original Quoted context has been removed as per policy

**Comment by theelk801** [comment]
I couldn't recreate this, what spell were you trying to cast?

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.
