### ISSUE TITLE
The Scarab God creates tokens with casting costs on them, making fatal push not interact

### ISSUE THREAD

**Issue by omegaservo** [magefree/mage#4099]

**Comment by JRHerlehy** [comment]
This is the correct rules interaction. Mana cost is a copyable value, and the effect states no where “except it has no manacost”.

See gather rulings for further clarification.
Unlike the tokens created by an eternalize ability, this token has the mana cost and thus converted mana cost of the card it's copying.
2017-07-14, Gatherer Rulings
