### ISSUE TITLE
Able to cast cards shown off of Gitaxian Probe

### ISSUE THREAD

**Issue by spjspj** [magefree/mage#4102]
Was playing on 1.4.26v7 edh 3way ffa.  Cast git probe targetting person directly on my left. I was then able to cast spells from the window that holds the revealed cards (specifically vampiric tutor)

**Comment by Zzooouhh** [comment]
This also appears to work with publically revealed cards (via Telepathy or similar effects)

**Comment by theelk801** [comment]
I know exactly what's causing this, and I'm gonna fix it right now.
