### ISSUE TITLE
Eye For An Eye does nothing

### ISSUE THREAD

**Issue by Zzooouhh** [magefree/mage#4103]
I tested around with the card Eye For An Eye which I wanted to base my code on. However, currently the card does absolutely nothing. I cast it and don't get prompted to select a damage source, all damage I receive normally, and Eye For An Eye itself inflicts no damage back.

**Comment by theelk801** [comment]
Yeah, it's a triggered ability for some reason, which wouldn't do anything. It should be more like a replacement effect, like Cho-Arrim Alchemist or Intervention Pact. I'd probably look at how prevention effects extend replacement effects and use that.
