### ISSUE TITLE
Cannot cast cards exiled with Gonti after Gonti leaves the battlefield

### ISSUE THREAD

**Issue by tawmas** [magefree/mage#4106]
In 1.4.26V7, once Gonti leaves the battlefield you lose the ability to cast the card exiled with it. You can still look at it, but you will no longer be allowed to cast it (clicking on it and answering "No" to "Do you want to look at the card?" will just do nothing).

You are supposed to be able to look at and cast the card for as long as it stays in exile, even if Gonti leaves the battlefield. Relevant ruling: "You may look at and cast that card (and spend mana as though it were mana of any type to do so) even if Gonti leaves the battlefield. If another player gains control of Gonti, that player can’t look at or cast the card, and you still can." (2016-20-09)

This happened to me twice while testing against the AI and I saw it happen once more today while watching a game.

**Comment by jeffwadsworth** [comment]
This card works fine in the latest build.

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.
