### ISSUE TITLE
AI does not follow game rules for goad

### ISSUE THREAD

**Issue by SpikesCafe-google** [magefree/mage#4115]
AI bug only? I haven't successfully goaded or been goaded by a human opponent yet.

Goad states, "Until your next turn, [a goaded creature] creature attacks each combat if able and attacks a player other than you if able."

Ignoring goad for now, the way the AI is implemented, in a multiplayer game, they pick an opponent at random at the start of the game. Until that player is dead, they only attack that opponent, then selects a new opponent at random. When I goad their creature in a multiplayer game, if I was the target of their attacks, they always illegally choose to not attack anyone. The one exception is when I have a planeswalker in play, they illegally choose to attack the planeswalker.

**Comment by SpikesCafe-google** [comment]
The AI also does not attack me with goaded creatures if all other opponents are dead. In that case, they should be forced to attack me.

**Comment by spjspj** [comment]
Noone is really working on the AI (and no-one has for at least the past 1.5 years or so).  I don't think that this will be fixed anytime soon.  The AI is purely there to goldfish against (aka give it a deck with 60 mystical tutors, no land, and then give it permanents via the cheat button if desired.  I would vote to close this and keep the bug list somewhat cleaner.

**Comment by SpikesCafe-google** [comment]
Thanks! I'm going to close this bug, because it's not really accurate anymore. Lately, the AI has been really good at never releasing priority, or allowing concession to end the game. Goad is just one of the ways that triggers this new bad AI behavior. Another way is forcing an attack, but the AI doesn't want to attack, so I think it just keeps fighting the must attack, resulting in an infinite loop.
