### ISSUE TITLE
Feature request: manual button to close popups

### ISSUE THREAD

**Issue by Zzooouhh** [magefree/mage#4121]
Sometimes for various reasons card rule popups (the ones that appear when hovering over a card) linger on and tend to even "shine through" across various game boards (if a game is running, I can access the deck editor, but I'll still be sometimes spawning popups on spots where the cards from the game are localized). These lingering popups however can only be undone by either hovering over the original card again (impossible if the game the card was from is already over) or by resetting the client, which is impractical. As a straightorward workaround for the issue, I'd like to see a tiny black X button in the top right corner of the card rule popup window that allows the user to close it manually in case it gets stuck.

**Comment by JayDi85** [comment]
@Zzooouhh is that issue actual (about non closable card popups)? There were bug with popups and it was fixed long ago.

**Comment by JayDi85** [comment]
Freeze card popup problem was fixed long ago. Now you need to move mouse over another card to unfreeze it.
