### ISSUE TITLE
Enchanting an aura with another aura causes display problems

### ISSUE THREAD

**Issue by theelk801** [magefree/mage#4123]
From the forums:
>In pauper vs Human opponent, they had a forest with both [[wild growth]] and [[utopia sprawl]] on it (in that order), I play [[quiet disrepair]] on their [[wild growth]]. Their forest then vanishes and the wild growth is in the same spot as the forest was, which essentially made disrepair into a 2 mana land destruction spell with an upside.

The land is definitely still there and returns if the second aura is removed, but the land is inaccessible otherwise.

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.

Looks weird, but functional.
![image](https://user-images.githubusercontent.com/59861365/86277614-9ce88d80-bb9c-11ea-9957-c029c7cf4b5f.png)
