### ISSUE TITLE
Cycling Decree of Justice empties user's mana pool

### ISSUE THREAD

**Issue by Zzooouhh** [magefree/mage#4130]
I floated 5 mana to pay for Decree of Justice's cycling cost, 3 of that mana I paid for the cycling itself. After the cycling ability resolves, it asks me to choose a cost for X - I choose 2, however all the remaining 2 floated mana in my mana pool is suddenly gone. Afterwards I have to cancel the ability due to being unable to pay for it, and the lost mana never comes back. Decree's regular (XX) casting mode works without issue however.

EDIT: Interestingly enough, the cycling ability empties the user's mana pool even after it gets paid - if I pay the aforementioned 2 mana by sacrificing a Black Lotus, I end up with 0 mana in my mana pool.

**Comment by Faxn** [comment]
This isn't unique to Decree of Justice, Flameblast Dragon does the same thing. I haven't tested other similar abilities yet though.
