### ISSUE TITLE
Add a 'Select All Permanents' button also a Highlight option for chosen Permanents

### ISSUE THREAD

**Issue by spjspj** [magefree/mage#4146]
Have a 'Select All Permanents' option added for cards such as Balancing Act (maybe also have it filterable for cards like Balance which cares about creatures / lands in particular).  

Also, have a way of highlighting them as they are chosen.

If the card is asking for 'N' permanents to select, then only allow the button to be shown if there are N or fewer permanents.

**Comment by Zzooouhh** [comment]
What about a "hold and drag mouse button" function for a selection box, similar to what already is included in the Deck editor?

**Comment by JayDi85** [comment]
[[Balancing Act]]

**Comment by JayDi85** [comment]
Hard to implement by additional button cause you must selects only part of the cards. Don’t care button can be more useful: #11919
