### ISSUE TITLE
Add in MTGO artid 

### ISSUE THREAD

**Issue by spjspj** [magefree/mage#4147]
Add an alternate way to render cards based on the 'ArtId' (aka the face-art picture (such as http://mtgoclientdepot.onlinegaming.wizards.com/Graphics/Cards/Pics/161922_typ_reg_sty_050.jpg for example)).  This I believe is similar to the way in which modo does it.

Steps:
1) Add the artid into the mtg-cards-data.txt for the artwork of a card in a given set.
2) Code similar card-render logic to how the existing 'new' rendering scheme does it (which currently builds the image based on full scans and then overlaying the M15 card frame over it).  
3) Example (https://files.gitter.im/xmage-devs/Lobby/wFt5/sword_of_f_f_investigation3.jpg)

**Comment by JayDi85** [comment]
Is that legal? MTGO resources is not available outside MTGO-application.

Look at https://scryfall.com/docs/api/images

They have `art_crop` param to get art only (they take card's full scan and crop it). Example:
 - full card: https://img.scryfall.com/cards/large/en/c16/143.jpg
 - cropped art: https://img.scryfall.com/cards/art_crop/en/c16/143.jpg

**Comment by spjspj** [comment]
Is that legal? MTGO resources is not available outside MTGO-application.
  >> We're not supplying the actual art at all.  
  >> The actual face image you show would be copyright.
  >> I think the distinction is that xmage didn't supply it to you or for you.
I'm aware of the cropped images that scryfall has but they aren't full art as for example the Grisela one is if you've been following it.
>> I've got a hybrid scheme going ('cos I like my full art lands to not have a border) on my local client build - https://imgur.com/8rBA33y  << May add it as a 'Hybrid M15/Plain Image rendering' option.

**Comment by spjspj** [comment]
Implemented.  (here: https://redd.it/7e0rpg)
