### ISSUE TITLE
Add new tokens source - scryfall

### ISSUE THREAD

**Issue by JayDi85** [magefree/mage#4174]
Old tokens source for images, http://tokens.mtg.onl , is not updated -- tokens from newly ixalan cards is missed, they haven't even kaladesh. Need to add new source for it -- scryfall.com is very good now.

I'm plan to work on it.

Site has excellent API and can sent tokens too:
1. Request all sets: https://api.scryfall.com/sets?pretty=true
2. Parse result. Scryfall has special sets for tokens and promos. See `"set_type": "token"` and `"search_uri"` for next api request. Found xgame set's code by `"parent_set_code": "xln"`
3. For each token's set send request to fetch token cards list: https://api.scryfall.com/cards/search?order=set&q=%2B%2Be%3Atxln
4. Parse result and found `image_uris -> large` field for image source
5. Download and save token image.

P.S. Alternative method:
1. Generate direct images and paste it to xmage;

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.
