### ISSUE TITLE
Add more info on on download sources and simplified it

### ISSUE THREAD

**Issue by JayDi85** [magefree/mage#4179]
Too many options -- it's confusing users. Need to add more info in front of each source. Like:
 - Wizards (low quality images, no tokens);
 - Scryfall (high quality images, tokens, icons - RECOMMEND);
 - Tokens.mtg.onl (only tokens);

I think after scryfall patches and fixes for tokens (see #4174) -- we can add one source by default for all cards, tokens, symbols, etc.

And after all application can join all downloading tasks (cards + symbols) in one launch button (window).

**Comment by Zerrisx** [comment]
This appears to have been implemented - do you agree?

**Comment by JayDi85** [comment]
Yep, it's done.
