### ISSUE TITLE
Gaze of the Gorgon end of combat bug

### ISSUE THREAD

**Issue by Zzooouhh** [magefree/mage#4199]
Gaze of the Gorgon's effect fizzles if the target creature leaves the battlefield after the spell resolves, but before the effect resolves - i.e. if I cast it on a blocked 1/1, which gets killed by a Terror (which makes it unable to regenerate), the blocking creature doesn't die.

**Comment by LevelX2** [comment]
I would:
1) Replace the CreateDelayedTriggeredAbilityEffect by an individual OneShotEffect.
2) In that effect give the target as MageObjectReference to the GazeOfTheGorgonEffect as parameter and call the CreateDelayedTriggeredAbilityEffect in the individual OneShotEffect with the triggered ability.
