### ISSUE TITLE
"Keeper of the Light", "Equinox" and "Spiritual Focus" cards are missing

### ISSUE THREAD

**Issue by spirius44** [magefree/mage#4211]
Hi, I would like add "Keeper of the Light" (Exode edition), "Equinox" (Legends edition) and "Spiritual Focus" (Mercadian Masques edition) but this cards are not in the DB of deck editor.

Thanks!

**Comment by spjspj** [comment]
https://www.slightlymagic.net/forum/viewtopic.php?f=70&t=20685&sid=529c982961552f871b5bb62bf41e46a1
Please request cards here
