### ISSUE TITLE
Feature request: option for "apply replacement effects automatically if all of them have identical properties"

### ISSUE THREAD

**Issue by Zzooouhh** [magefree/mage#4219]
Let's say I activate Nomads en-Kor 10 times, each time choosing the same target. Nomads en-Kor afterwards gets hit by damage, and the player is supposed to tediously click through a table of 10 replacement effects. Assuming that all the replacement effects applicable are identical (all share the same name, source, target and values at once, or maybe even some other properties I'm forgetting to mention?), wouldn't it make sense then to have a checkable option to just have resolve them automatically?

**Comment by JayDi85** [comment]
Implemented as remember answer checkbox, see details in https://github.com/magefree/mage/issues/6676#issuecomment-895016420

BTW Nomads en-Kor reworked long ago and allows only one replacement effect at a time.
