### ISSUE TITLE
Ongoing Investigation, Storm the Vault triggers at wrong time, wrong number of times

### ISSUE THREAD

**Issue by SpikesCafe-google** [magefree/mage#4222]
This fixed it:
https://github.com/magefree/mage/commit/954ebd165276ac4a6c8f0c6d59b7e03986a82328#diff-e60657925db5bbe942704b08f8b394d5

This broke it:
https://github.com/magefree/mage/commit/b2e3201ea452f7c7f94d43b54de2fc8c8372138d#diff-e60657925db5bbe942704b08f8b394d5

It seems to trigger at the beginning of my postcombat main, and even if I damaged two different opponents, it only triggers once. It should trigger during the combat damage step.

**Comment by SpikesCafe-google** [comment]
This issue also affects Storm the Vault.

https://github.com/magefree/mage/blob/b2e3201ea452f7c7f94d43b54de2fc8c8372138d/Mage/src/main/java/mage/abilities/common/ControlledCreaturesDealCombatDamagePlayerTriggeredAbility.java#L63

It's great that it keeps track of damaged players, but can checkTrigger fire multiple times, one for each player?

https://github.com/magefree/mage/blob/b2e3201ea452f7c7f94d43b54de2fc8c8372138d/Mage/src/main/java/mage/abilities/common/ControlledCreaturesDealCombatDamagePlayerTriggeredAbility.java#L89

It should trigger at the same time as combat damage, not during postcombat main.

https://github.com/magefree/mage/blob/b2e3201ea452f7c7f94d43b54de2fc8c8372138d/Mage/src/main/java/mage/abilities/common/ControlledCreaturesDealCombatDamagePlayerTriggeredAbility.java#L101

What does graveyard have to do with this trigger? I think this code can be deleted.

**Comment by awjackson** [comment]
This is long since fixed, I believe by f5499531c7e6404d524068440a4325676db054be
