### ISSUE TITLE
Bushido triggers multiple times on multiple blockers

### ISSUE THREAD

**Issue by Zzooouhh** [magefree/mage#4224]
Fumiko the Lowblood attacks while Invasion Plans is on the battlefield, I assign all blockers to her. What happens is that she gets Bushido X several times (equal to the number of blockers assigned to block), ending up similar to Rampage. The correct behavior should be that it triggers once if blocked, no matter how many blockers are blocking her. (i.e. the trigger check should be "After blockers are declared, am I blocked by anything? Y/N")

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.
