### ISSUE TITLE
Downloaded as a non-executable JAR file

### ISSUE THREAD

**Issue by Kusha1a** [magefree/mage#4229]
Basically exactly what the title says. I used the xmage.de link, went to try and run downloaded file, and it just didn't work. After checking a couple times I found that it downloaded as a regular JAR file as opposed to the executable JAR file that it needs in order to work properly. Anyone have any workarounds for that?

**Comment by JayDi85** [comment]
Try to run jar file from command line:
 - open xmage game folder (you can found XMageLauncher-0.3.8.jarin it);
 - add new text file and rename it to run.cmd - right click on it and select edit;
 - in text editor insert that text and save file: `javaw.exe -jar XMageLauncher-0.3.8.jar`;
 - now you can run launcher with that run.cmd file;
 - if it do not run, then you can edit run.cmd and add full path to your java folder. Example: `"C:\Program Files (x86)\Java\jre1.8.0_151\bin\javaw.exe" -jar XMageLauncher-0.3.8.jar`
