### ISSUE TITLE
BUG - Minion Reflector

### ISSUE THREAD

**Issue by EllNubNub** [magefree/mage#4239]
minion reflector does not ask if you want to pay the 2 mana or not. it simply forces you to pay for it. also it gives you an option at the end of the turn if you want to sacrifice the creature or not. which it should not even ask or allow you to keep the creature, it should automatically force you to "sacrifice that permanent".

**Comment by Alexsandr0x** [comment]
@EllNubNub I could replicate the bug:
* ability is not optional
* token has the ability with the "may" clause

both are solved in [my branch](https://github.com/Alexsandr0x/mage/tree/MinionReflector) and I will make a PR for this to be review.

**Comment by JayDi85** [comment]
Fixed in #4242
