### ISSUE TITLE
Add export deck button in deck editor

### ISSUE THREAD

**Issue by JayDi85** [magefree/mage#4243]
Need to export deck to different formats like dek, mtgo, arena or other popular formats.

1. [x] UI same as import: export to file or export to clipboard;
2. [x] MTGO Magic Online format, dek (main and sideboard without tags, empty line before sideboard):
```
1 Charging Monstrosaur
1 Deathgorge Scavenger
7 Forest

2 Grazing Whiptail
2 Imperial Aerosaur
```
3. [ ] [deckstats.net](https://deckstats.net) format (tags like `//sideboard`, `SB:`, ignore empty line):
```
//Mainboard
1 Sire of Stagnation
1 Stitcher Geralf
1 Szadek, Lord of Secrets
1 Undead Alchemist
1 Wight of Precinct Six

//Sideboard
SB: 1 Worn Powerstone
SB: 1 Wrexial, the Risen Deep
```
4. [x] MTG Arena format (with card numbers and sets like xmage, empty line before sideboard):
```
2 Savage Stomp (XLN) 205
1 Charging Monstrosaur (XLN) 138
1 Raging Swordtooth (XLN) 226

1 Wakening Sun's Avatar (XLN) 44
2 Ranging Raptors (XLN) 201
```

4. [ ] Another one potential support: `.cod` (Cockatrice), `.o8d` (OCTGN), `.mwDeck` (MWS)

**Comment by Roboreaper** [comment]
i would really like this feature as well.
just plain text would probably work for 99% of all the websites

**Comment by JayDi85** [comment]
@argonplatypus as a workaround you can save your deck to the file, open it with text editor and copy cards list from it. That's format support all basic mtg sites.
