### ISSUE TITLE
Is images's torrent download still works/alive in xmage?

### ISSUE THREAD

**Issue by JayDi85** [magefree/mage#4246]
From [reddit](https://www.reddit.com/r/XMage/comments/7jgr55/what_happened_to_the_image_torrent_on_the_sidebar/).

> What happened to the Image torrent on the sidebar? Used to be a link to a torrent to download the image files and now it's gone. I don't want to download the 50GB file of HQ images.
> Anyone still have this available?

And someone put a link to 2.4 GB file:
> magnet:?xt=urn:btih:m5jpe2ewx4jxaui76d32iwjnnarwuoi5&dn=xmage&xl=2465466661&fc=40841
> let me know if this works, i've never made a magnet link or a torrent before, but I think this is how it goes
> anyway copy that to search bar and hit enter
> filesize about 2.4g you can select which sets you want to download and all that good shiit i think it has all the cards supported on xmage
> just drag and drop the set folders to your existing images folder or choose this folder as your image folder in xmage
> I'll try to remember to keep my tixati on at most times

**Comment by invincibleparm** [comment]
this no longer has seeders

**Comment by Zerrisx** [comment]
This question looks to be answered and/or obsolete

**Comment by JayDi85** [comment]
Torrent downloads no more actual since scryfall download works great. Moreover I think torrents related code must be removed from [launcher](https://github.com/magefree/Launcher) too. Torrents are old and outdated things.
