### ISSUE TITLE
banishing light issue.

### ISSUE THREAD

**Issue by mindcloud69** [magefree/mage#4257]
I used Bribery to pull a creature out of my opponents graveyard. They then cast banishing light on it to exile it. I then returned banishing light to it owners hand. I should have regained control of the creature but it went to my opponents battlefield instead of returning to mine as it should have.

v1.4.26v9

**Comment by tracykarjala** [comment]
Bribery makes you the creature's owner. The text on Banishing Light says when it leaves the battlefield the permanent returns under it's owner's control, which is your opponent.  This worked as intended under Magic rules.

**Comment by mindcloud69** [comment]
Missed that sorry.
