### ISSUE TITLE
Reduce round corner image quantity or chance to do in options

### ISSUE THREAD

**Issue by nachazo** [magefree/mage#4264]
New feature introduced in 1.4.26V9 is very nice, but I think that rounded corner quantity it's a bit high and cards images are too rounded compared with a real card. Could be reduced a bit? Or maybe the "numeric" quantity option could be set-up from the options like the image-card size and so on.
Maybe is "Mage.Client/src/main/java/mage/client/constants/Constants.java" line 77 and 78 numbers?
Ty.

**Comment by JayDi85** [comment]
0.15 of card width settings (current):
![shot_171218_154042](https://user-images.githubusercontent.com/8344157/34106552-147281c2-e412-11e7-838d-4b7082408a54.png)

0.10 of card width settings:
![shot_171218_163807](https://user-images.githubusercontent.com/8344157/34106567-1f5a67a8-e412-11e7-8382-ce6300653ca6.png)

Can you tell sets with different round corner styles (or even withour round corners)?

**Comment by spjspj** [comment]
1.4.26v9 ugin:
https://imgur.com/a/Y8jTg  (https://i.imgur.com/bu1i8dJ.png)

**Comment by JayDi85** [comment]
Hmm... different card sources use different frames? I'm test cards with scryfall and they all have big black border.

[Ugin, the Spirit Dragon](https://scryfall.com/card/prm/55763) -- origin card from scryfall:
![shot_171218_181953](https://user-images.githubusercontent.com/8344157/34110432-124d0a12-e420-11e7-9e1f-4620225dc093.png)

**Comment by nachazo** [comment]
This is probably caused by the bug with image ratio size explained herencia: https://github.com/magefree/mage/issues/4028

**Comment by JayDi85** [comment]
No more actual.
