### ISSUE TITLE
New Blood not implemented correctly

### ISSUE THREAD

**Issue by DaMachinator** [magefree/mage#4269]
With the current implementation New Blood only changes the selected creature type to Vampire in the type line. It should be changing it in the rules text as well.

From the Gatherer rulings:
> New Blood changes the creature type each time it appears in the creature’s type line and/or rules text. It doesn’t change the name of the card or any instances of the word being used as part of a card’s name.

**Comment by spjspj** [comment]
This is an ongoing framework issue.
