### ISSUE TITLE
Vindictive Lich

### ISSUE THREAD

**Issue by MantaXIV** [magefree/mage#4279]
Yesterday I was play Commander, and when my Vindictive Lich died, I put the ability in to the stack, but nothing happened. My opponent doesn't discard two cards. Please, what can I do now to fix this?

**Comment by derlhurgoyf** [comment]
In a 4-way Commander game Vindictive Lich died and I select all three modes and all three opponents. However only one effect happened (sacrifice a creature). The other players were unaffected by discard and life loss.

**Comment by derlhurgoyf** [comment]
probably duplicate of #3895

**Comment by Zerrisx** [comment]
Duplicate of #4742
