### ISSUE TITLE
PTC Viewer Bug

### ISSUE THREAD

**Issue by ADude300** [magefree/mage#4282]
Not sure if this has been mentioned yet but, The Prerelease Set (PTC) is not visible in the viewer but the cards are found in deck editor.

*It Appears that some PTC cards are included in Media Inserts (MBP) as Media Inserts is supposed to only have 148 Cards

![ptc bug 2](https://user-images.githubusercontent.com/34827771/34334277-a16c56d2-e90a-11e7-857a-5e55dead3830.png)

![ptc bug](https://user-images.githubusercontent.com/34827771/34334229-525317e8-e90a-11e7-8d20-4de519888b25.png)

**Comment by JayDi85** [comment]
Duplicate #4220

**Comment by JayDi85** [comment]
You can wait next release or download [current developer version from here](https://yadi.sk/d/oLKb_rzG3PwE7n) (it's compatible with xmage.de and other servers -- [what's new in that version](https://github.com/magefree/mage/wiki/Features-and-fixes-not-released-yet)).
