### ISSUE TITLE
Vorinclex, Voice of Hunger: fire up two times on mana tap instead one

### ISSUE THREAD

**Issue by JayDi85** [magefree/mage#4288]
Added test proof in https://github.com/magefree/mage/commit/2d48e14960428d564020621c8e9797b8ba5cf5f5

[Vorinclex, Voice of Hunger](https://scryfall.com/card/ima/189) have ability:
> Whenever you tap a land for mana, add one mana to your mana pool of any type that land produced.

It's fire up two times on mana tap instead one. Affected lands with `ConditionalManaAbility` (River of Tears, Gemstone Caverns).

I'm search source and found that it was because trigger activation on TAPPED_FOR_MANA event -- that's event fire up two times for one mana tap: in `ManaEffect.java` and `AbilityImpl.java`.

Don't know what to do next and how to fix it.

**Comment by Zzooouhh** [comment]
Could you clarify what this bug does? I've used Vorinclex over and over and he always makes lands tap for 1 more (i.e. 2 mana in total from a basic land).

**Comment by JayDi85** [comment]
Yes, I can confirm. Use non basic lands to test, like [River of Tears](https://scryfall.com/card/ima/246):

![shot_171228_144145](https://user-images.githubusercontent.com/8344157/34408453-7e1422de-ebdd-11e7-8960-5546e320ce68.png)

See tests in VorinclexVoiceOfHungerTest.java or use try it manually in xmage test mode:

> battlefield:Human:Swamp:3
> battlefield:Human:Vorinclex, Voice of Hunger:1
> battlefield:Human:River of Tears:1

**Comment by JayDi85** [comment]
Hmm... I'm testing more... Results:
 - Basic lands is fine;
 - Non standard land (Abandoned Outpost) is fine;
 - Non standard land with ConditionalManaAbility (River of Tears) is bad :fire: ;
 - Non standard land with ConditionalManaAbility (Gemstone Caverns) is bad :fire: ;

May be it's a `ConditionalManaAbility` error?

**Comment by Zzooouhh** [comment]
Perhaps this is a River of Tears bug then? I've just tested Vorinclex with River of Tears, Plateau, Cavern of Souls (both modes), Rhystic Cave and Reflecting Pool (to sample some functionally varied lands) - all of them tap for 2 mana except for the River, which taps for 3 same-colored blue or black mana regardless of whether a land ETBed this turn or not.
