### ISSUE TITLE
Naga Vitalist: can't produce mana if enchanted land was created in same turn

### ISSUE THREAD

**Issue by JayDi85** [magefree/mage#4289]
Added tests proof in https://github.com/magefree/mage/pull/4283/commits/cdec4fe2805f4b7af1da90024a0609cc09e81cb0 (see ignored tests).
[
Naga Vitalist](https://scryfall.com/card/akh/176) have ability:
> {T}: Add to your mana pool one mana of any type that a land you control could produce.

If you create enchanted land to produce any color (see [Gift of Paradise](https://scryfall.com/card/akh/167)) then Naga Vitalist can't find that land and use {any} color production on fire up ability. It's do not work ONLY if you created enchanted land on same turn. If you enchant and cast in different turns then it's work fine. It's already mentioned in #3315.

I'm search source and found that enchanted land somehow reset it's new added ability with {any} color. And that's why Naga can't see it on mana types searching. `getManaTypes` on Naga trigger can't see that's new ability and count {any} mana.

It's maybe a testing framework problem? I'm out of my mind with that bug. Can someone fix that?

![shot_171228_032930](https://user-images.githubusercontent.com/8344157/34396028-732d8576-eb7f-11e7-9616-b8ac8e86e552.png)

**Comment by LevelX2** [comment]
I had a look and it seems to me that Naga Vitalist works correctly.

The problem of the test is, that it tries to produce the mana while the Gift of Paradise is still on the stack and has not yet resolved. So it's not possible to produce the requested mana color yet.

In an interactive local test game I was able to produce all kinds of mana directly after the Gift resolved. So this issue can be closed.

![naga vitalist](https://user-images.githubusercontent.com/2066790/34409034-80b82ac8-ebc7-11e7-8073-cd81c81ccd18.jpg)

**Comment by LevelX2** [comment]
Btw, nice new dialog for selecting the mana.

**Comment by JayDi85** [comment]
So, it's a test framework feature was. Ok.
