### ISSUE TITLE
Tezzeret, Agent of Bolas -1 doesn't work right on temporary artifacts.

### ISSUE THREAD

**Issue by Embrychi** [magefree/mage#4290]
Tezzeret's -1 ability is:

> −1: Target artifact becomes an artifact creature with base power and toughness 5/5.

Note, it says it becomes an artifact creature, not just gains the creature typing. When I used Tezzeret's -1 ability on a Mishra's Workshop turned into a 2/2 artifact creature, it turned into a 5/5 artifact creature as intended. However, at the end of the turn, it stayed a 5/5 creature but no longer was an artifact. Per the wording of the ability, it should have stayed both a creature _and_ an artifact.

**Comment by ingmargoudt** [comment]
Correct, the code for tezzeret only adds the Creature Cardtype , so in case of a temporary artifact this goes wrong obviously :)
