### ISSUE TITLE
Feature request: add "cancel" option for Morph costs

### ISSUE THREAD

**Issue by Zzooouhh** [magefree/mage#4294]
If you click on a creature with Morph in your hand, it asks you whether you want to cast it for its Morph cost or not. However, if you can't (or decide that you don't want to) pay its Morph cost and press "No", the game automatically places the unmorphed creature on the stack awaiting mana cost payment - spoiling what the Morph creature is in case you wanted to save it for later. It would be optimal if upon pressing "No" the game displayed another prompt asking whether to play the creature unmorphed or not at all (returning the card back to hand).

**Comment by skeate** [comment]
FWIW: You can already do this (kind of) by just clicking "Yes" when it asks if you want to play it as a Morph, and then just cancel out of the mana payment.
