### ISSUE TITLE
Auras returned with Nomad Mythmaker ask twice for target if the first target is a token

### ISSUE THREAD

**Issue by Zzooouhh** [magefree/mage#4297]
Nomad Mythmaker's ability asks for one Aura in graveyard target initially and one controlled creature target upon resolution. If I choose a nontoken creature for the second target, the Aura gets attached and that's it. However if I pick a token creature, the Aura itself asks me to select another (third) target during its ETB sequence - this target seems to be superfluous as far as I can tell, because the Aura will return attached (at least graphics-wise) to the token I picked as Mythmaker's second target. I'm not sure if this might break anything or not - any ideas?

Also, this third target seems to only appear if I pick an Aura that can enchant a creature, not when I pick a "wrong" Aura like an Enchant Land (which is a legal target for Mythmaker as per the rules) that gets SBA'd right back to the graveyard instead.

**Comment by emerald000** [comment]
https://github.com/magefree/mage/blob/04afe73f287ea683d13611dc223c93914db84bbc/Mage/src/main/java/mage/abilities/effects/AuraReplacementEffect.java#L101 is probably the issue. Since a token is not a PermanentCard, but a PermanentToken, it doesn't attach as set by the attachTo value and asks what to attach to.

**Comment by Zzooouhh** [comment]
Any particular reason why it's not just "object instanceof PermanentImpl"?

**Comment by emerald000** [comment]
Probably not.

**Comment by Zzooouhh** [comment]
Alright, I'll switch it then, as it appears to solve this issue.
