### ISSUE TITLE
Launcher doesn't start the game

### ISSUE THREAD

**Issue by Sunitram** [magefree/mage#4300]
Hi all,

For quite some time, every time I try to open Xmage through the Launcher, I get a window with the following message:

_Error: could not open `C:\Users\acer\Desktop\java\jre1.8.0_131\lib\amd64\jvm.cfg'_

Then I try to open it with startmage in the Xmage folder and it works fine. However, I'm afraid that I'll miss out on updates in the future. What to do?

**Comment by JayDi85** [comment]
Try to delete java folder and re-download it from launcher.

**Comment by Sunitram** [comment]
I deleted the java folder, but now the launcher still doesn't start the game, only now without a message. I also can't find any way in the launcher to download java. Downloading java from their own site didn't solve the issue.

**Comment by JayDi85** [comment]
If you press "force to updates" in launcher windows -- what kind of logs there are? You can do screenshot.

If that not help, then try to download current developer version [from here](https://yadi.sk/d/oLKb_rzG3PwE7n): download, unpack to any other folder and run launcher.

**Comment by Sunitram** [comment]
It works! Thnx sir!

**Comment by JayDi85** [comment]
Can you tell what was done: force update, new dev version?

**Comment by Sunitram** [comment]
I forced the update, it re-installed java and everything was fixed :)

**Comment by JayDi85** [comment]
It's a good.
