### ISSUE TITLE
Grave Scrabbler's conditional ETB ability fires even when cast normally

### ISSUE THREAD

**Issue by skeate** [magefree/mage#4307]
Grave Scrabbler has a unique effect that only fires if its madness cost was paid. Right now it gets triggered even when cast normally.

I'm trying to look into why. So far I have that the `MadnessAbility` doesn't actually have _any_ costs (regardless of how it's cast), so technically all costs are paid.

**Comment by LevelX2** [comment]
Fixed with 00dd941260e8f1fa79857d673ac38e4bc861c331.
