### ISSUE TITLE
M10 Pithing Needle disconnects you if you cast it

### ISSUE THREAD

**Issue by Sunitram** [magefree/mage#4308]
As the title says. The moment I have Pithing Needle (M10 version, should this be relevant) on the stack, the game disconnects. When I reconnect the artifact is already on the battlefield with no name chosen. I don't think this is a coincidence, since it happened to me 4 times in a row, with varying opponents.

**Comment by JayDi85** [comment]
I can't play that card at all in current version.

**Comment by Zzooouhh** [comment]
I'm testing the card on localhost (Xmage 1.4.26.10) and I can play it no problem. Could it be related to the new card selection dialog somehow?

**Comment by JayDi85** [comment]
Current xmage server is not updated yet -- it's may be a problem. Need to wait restart and reproduce.

I saw same bug in v9 version with one of the broken card (don't remember the name) -- on choose dialog there are was exception error -- it's now shown and player can't proceed to next step. Only disconnect/concede can help.

**Comment by Zzooouhh** [comment]
When I'm playing V10 on the V9 server, I get disconnected whenever I search my library, which is most likely related to this same problem.

**Comment by LevelX2** [comment]
This should be solved.
