### ISSUE TITLE
Rollback is broken

### ISSUE THREAD

**Issue by JayDi85** [magefree/mage#4309]
From xmage chats, TalentedPlayer:

Rollback are broken. Anytime you accept an opponents offer to rollback, you won't receive priority for the rest of the match

**Comment by JRHerlehy** [comment]
I think this is known. You need to have all skips off at the moment or else the rollback does weird things.

**Comment by LevelX2** [comment]
https://www.slightlymagic.net/forum/viewtopic.php?f=70&t=21724#p223130

Hello,
something happened twice today: my software stopped giving me control. Passing every phase, every priority to cast, block, attack. Clicking F3, F4, F5 never changed it back.
First game it happened after I was talking to my opponent(I think he asked for a rollback but not sure).
Second game it happened after an opponent asked for a rollback.
Each time it happened it started in opponent's turn, and I play 90%time with "go to end's turn" .

**Comment by duxbuse** [comment]
+1

**Comment by LevelX2** [comment]
@duxbuse 
You had the same rollback bug?
On which server?

**Comment by duxbuse** [comment]
us.xmage.today:17171

**Comment by LevelX2** [comment]
> us.xmage.today:17171

OK, the fixes for the rollback problems are only installed on the beta server yet. So it is expected that the problem will still occur on this server.

**Comment by JayDi85** [comment]
BTW rollback can't restore lose or leaved/disconnected player.

1.
Bug can be related to connection problem and `resetPlayerPassedActions` calls or another reset call code (if user got connection problem and leaved the game then he can't reset skip buttons on rollback):
![shot_200821_105151](https://user-images.githubusercontent.com/8344157/90861236-8260b280-e39c-11ea-8a0b-001a8eacd6a0.png)

Server logs show connection problems on 2020-08-21 04:02 for user Tusev -- @duxbuse if it your problem game then bug related to connection.
![shot_200821_105043](https://user-images.githubusercontent.com/8344157/90861541-f3a06580-e39c-11ea-863f-1500544cbfa5.png)

2. 
Another possible place -- `canRespond()` and `abort` state (`abort` helps to cancel/stop all choose dialogs for freezed player -- player leaved the game) -- abort state restored only in one place (manual rollback). If you look at [comment here](621d8c188df907a5778e149d5130baf524aba222) then you can see that abort reset code ignored on game exception rollback. It's not duxbuse's bug -- I can't see any errors in server logs.
![shot_200821_110448](https://user-images.githubusercontent.com/8344157/90862583-b1782380-e39e-11ea-9c01-ab3a78312b23.png)

**Comment by JayDi85** [comment]
Actual problems with reset moved to #11654
