### ISSUE TITLE
Errors loading JR cards in deck editor

### ISSUE THREAD

**Issue by Zzooouhh** [magefree/mage#4311]
When you load up a deck that contains cards from the Masterpiece Series Amonkhet edition in V10, you'll be greeted with an error message - "Errors while loading deck - founded problems with deck: Layout mismatch: Expected 4 cards, but got 1 in layout 'MAIN'". This was with a test dck file containing three MPS-AKH cards and one Kaladesh Masterpiece; the numbers in other deckfiles always correspond to the number of MPS-AKH cards (i.e. "99 cards, but got 98" in an EDH deck with one masterpiece).

The deck file after the error will load, but will present various graphical and possibly card database glitches - after sorting by card type, I've once had a card disappear, another time I've had a Land Tax swap for a Wall of Wood, and once the infringing masterpiece cards were sorted 3 columns away from everything else.

EDIT: Land Tax swapping for Wall of Wood is related to the numbering changes for 4th edition, not this bug.

**Comment by Zzooouhh** [comment]
This same issue happens for JR cards (Judge Rewards) as of version V11c.

**Comment by JayDi85** [comment]
Yeah, i will check.

**Comment by JayDi85** [comment]
Fixed via 5722b51d6e9e462fc67bb34ebd06ba7037aecb49
