### ISSUE TITLE
Skyshroud War Beast is broken

### ISSUE THREAD

**Issue by Zzooouhh** [magefree/mage#4317]
Tested in 4 player and 2 player EDH and happens in both. Any player trying to play anything (including lands) with Skyshroud War Beast in one of the player's decklists will have their drop rollbacked and an error message will pop up:

Game exception occurred: java.lang.NullPointerException
Server version: 1.4.26V10
mage.filter.predicate.permanent.ControllerIdPredicate.apply(ControllerIdPredicate.java:49)
mage.filter.predicate.permanent.ControllerIdPredicate.apply(ControllerIdPredicate.java:39)
mage.filter.predicate.Predicates$AndPredicate.apply(Predicates.java:172)
mage.filter.FilterImpl.match(FilterImpl.java:62)
mage.filter.FilterPermanent.match(FilterPermanent.java:76)
mage.game.permanent.Battlefield.lambda$count$1(Battlefield.java:109)
java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
java.util.Iterator.forEachRemaining(Iterator.java:116)
java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
java.util.stream.LongPipeline.reduce(LongPipeline.java:438)
java.util.stream.LongPipeline.sum(LongPipeline.java:396)
java.util.stream.ReferencePipeline.count(ReferencePipeline.java:526)
mage.game.permanent.Battlefield.count(Battlefield.java:111)
mage.abilities.dynamicvalue.common.PermanentsOnBattlefieldCount.calculate(PermanentsOnBattlefieldCount.java:65)
mage.cards.s.SkyshroudWarBeastEffect.apply(SkyshroudWarBeast.java:112)
mage.abilities.effects.ContinuousEffectImpl.apply(ContinuousEffectImpl.java:123)
mage.abilities.effects.ContinuousEffects.apply(ContinuousEffects.java:962)
mage.game.GameState.applyEffects(GameState.java:555)
mage.game.GameImpl.applyEffects(GameImpl.java:1465)
mage.players.PlayerImpl.moveCards(PlayerImpl.java:3350)
mage.players.PlayerImpl.moveCards(PlayerImpl.java:3296)
mage.players.PlayerImpl.playLand(PlayerImpl.java:1082)
mage.players.PlayerImpl.activateAbility(PlayerImpl.java:1187)
mage.player.human.HumanPlayer.activateAbility(HumanPlayer.java:1511)
mage.player.human.HumanPlayer.activateAbility(HumanPlayer.java:1525)
mage.player.human.HumanPlayer.priority(HumanPlayer.java:831)
mage.game.GameImpl.playPriority(GameImpl.java:1318)
mage.game.turn.Step.priority(Step.java:87)
mage.game.turn.Phase.playStep(Phase.java:210)
mage.game.turn.Phase.play(Phase.java:115)
mage.game.turn.Turn.play(Turn.java:153)
mage.game.GameImpl.playTurn(GameImpl.java:856)
mage.game.GameImpl.play(GameImpl.java:765)
mage.game.GameImpl.start(GameImpl.java:729)
mage.server.game.GameWorker.call(GameWorker.java:60)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)

**Comment by ingmargoudt** [comment]
The "problem" has 2 reasons: first Skyshroud war beast is programmed to have its static ability be active in all zones, which is correct, but a player has to be chosen for this to be true. The effect uses the controllerIdPredicate, which can throw a nullpointer exception if there is no controllerID set, as is the case with skyshroud warbeast (and many other cards...).
I updated the controllerId predicate to check for a null reference
