### ISSUE TITLE
Window display layers

### ISSUE THREAD

**Issue by LevelX2** [magefree/mage#4318]
The window to select a card in libraray is behind the graveyard window.
It should be the other way around.

![graveyardneedstobebehindlibrary](https://user-images.githubusercontent.com/2066790/34463200-9001fb5a-ee54-11e7-85e6-f34a2d04f634.jpg)

**Comment by JayDi85** [comment]
It's a global problem for MageDialog (see #4298 as example) -- JInternalFrame popup on wrong z-order (new windows must above old one). You can test it on connection dialog and flag search window:
![shot_171231_003550](https://user-images.githubusercontent.com/8344157/34463262-e892e2d8-ee6e-11e7-8afa-884198c1a478.png)

Somewhere must be checking: if modal show up then change zorder of that window to max + 1;

**Comment by JayDi85** [comment]
Fixed in 78d036b6bb29b8d3ddca490b767936f9a89e79f3, but need more to test. Report here any window layer problems:
 * if the new window popup behind the old one;
 * if the new window do not upper at all;
 * if your app is "freeze" and you can't press any buttons (modal window created, but do not show in foreground);

**Comment by JayDi85** [comment]
Knowing issue (not fixed yet) -- losing modal mode: 
 * open new tournament window;
 * select draft mode to show up packs list;
 * open fast search pack window;
 * a. or change focus to other app and wait some time;
 * b. or click to xmage icon and choose to open settings window;
 * then fast search window lost "modal" mode -- you can select parent new tournament and enter data to it;

**Comment by JayDi85** [comment]
All fixed in last year, no more reports about wrong windows position.
