### ISSUE TITLE
Fetch lands bugged. Window to search for a land doesn't pop up

### ISSUE THREAD

**Issue by Unehru** [magefree/mage#4320]
Hi,
I've encountered that issue using Polluted Delta and Flooded Strand. Window to search for a land doesn't pop up. I restarted client and it didn't help. Fix it or give me any advice, please.

Arid Mesa in different deck worked...

Window doesn't pop up in the same deck after Field of Ruin activation...

**Comment by Unehru** [comment]
Split card did it. It's working after removing it from the deck.

**Comment by JayDi85** [comment]
It's knowing issue: #4318 Works on it.

**Comment by JayDi85** [comment]
Please, try again with current xmage server. Is that still affected?

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.
