### ISSUE TITLE
Bug when combining Mycosynth Golem+ Mycosynth Lattice

### ISSUE THREAD

**Issue by shaithan** [magefree/mage#4336]
When you have both Mycosynth Lattice and Mycosynth Golem, all cards should get Affinity for artifacts, but they don't

**Comment by Zzooouhh** [comment]
Incorrect, Mycosynth Lattice doesn't turn cards in your hand into artifacts.

**Comment by shaithan** [comment]
"All cards that aren't on the battlefield, spells, and permanents are colorless." yes it does

**Comment by shaithan** [comment]
True have totaly missread that card like 4 ever
