### ISSUE TITLE
Karn Liberated's memory of exiled cards persists between zones

### ISSUE THREAD

**Issue by D3RPZ1LLA** [magefree/mage#4338]
When changing zones, Karn should be treated as a new object and memory of previously exiled cards should not persist.

How to recreate the error:
1. A Karn exiles `card A` (either ability)
2. Karn is returned to hand (i.e. Cryptic Command)
3. Karn is replayed
4. Karn ultimates
5. The game restarts with `card A` in play

**Comment by jeffwadsworth** [comment]
Karn does not use the correct Exile Zone technique.  I will check it out.
