### ISSUE TITLE
Gideon of the Trials and Harsh Mentor

### ISSUE THREAD

**Issue by LinusPhoenix** [magefree/mage#4340]
Hello,

I encountered the following bug:
1. I have Gideon of the Trials in play, my opponent has a Harsh Mentor on the battlefield.
2. I activate Gideon's first ability targetting Harsh Mentor, preventing all damage it would deal until my next turn.
3. The ability resolves, then I activate a fetchland.
4. Harsh Mentor ability triggers and deals 2 damage to me, my opponent redirected it to Gideon.

Since all damage that Harsh Mentor would deal is prevented, Harsh Mentor's ability should not actually deal any damage.

**Comment by WindyDelcarlo** [comment]
Yeah, no, that's actually a rules interaction, not a bug. Both the prevention and the redirection are replacement effects, therefore the Harsh Mentor can choose to redirect instead of prevent

**Comment by emerald000** [comment]
It's the owner of the permanent being affected or the player affected that chooses the order of replacement effects. So you have the choice to either prevent the damage, or give the option to your opponent to damage your planeswalker (the damage will still be prevented if it isn't redirected to your planeswalker).

**Comment by WindyDelcarlo** [comment]
Same result though, you stll have to choose correctly through xmage

**Comment by emerald000** [comment]
Just wanted to make clear who was choosing if damage was prevented or not.

**Comment by LinusPhoenix** [comment]
Whoops, you are correct. My bad!
