### ISSUE TITLE
GUI: Wrong priority / timer on choice actions

### ISSUE THREAD

**Issue by JayDi85** [magefree/mage#4349]
If you start to choice a color or a creature type from dialog then server give you priority to select, but inform about opponent waiting and activate his timer, not yours. You can start to select, go out from PC and wait for timer off -- and win. Affected all games (vs AI, vs human).

![shot_180107_143629](https://user-images.githubusercontent.com/8344157/34648725-d5ea1dfa-f3b8-11e7-9540-a7309c60c43e.png)

**Comment by SpeedProg** [comment]
This bug still exists, it is only a client updating bug through.
If you play a card like Icon of Ancestry, where after playing the priority switch happens and then the choose ability resolves. The client side is not updated about the timer pause/unpause on the server side, but the server actually handles it correctly. So as soon as you chose the type, the clients receives an update and the choosing sides clock shows the lost time, while the waiting sites clock is restored.

**Comment by JayDi85** [comment]
Not actual anymore. Maybe it was related to wrong order of game updates (fixed last year).
