### ISSUE TITLE
Function to show sideboard during game

### ISSUE THREAD

**Issue by LevelX2** [magefree/mage#435]
During a game, players may look at their own sideboard and the sideboard of any players they currently control (Mind Slaver). The sideboard must remain clearly distinguishable from other cards. 

http://rules.wizards.com/rulebook.aspx?game=Magic&category=Tournament%20Policy#4544

**Comment by drmDev** [comment]
With the new rules change, you do not gain access to the opponent's sideboard information anymore with mindslaver like effects. Will have to check again if you are legally allowed to look at your sideboard in the middle of a game.

**Comment by fireshoes** [comment]
You can still look at your own sideboard during the game.

**Comment by cow2** [comment]
is there someone triaging all these issues or bugs and closing them appropriately ? feel free to assign me some issues you think are first and foremost. I'm not a great programmer, but I have some insights in software development. I love the game and your efforts, I would like to contribute meaningfully to this project as everyones time is limited anyway.

**Comment by JayDi85** [comment]
No actual any more - own deck can be viewed by right click.
