### ISSUE TITLE
Bug - Unable to activate mana rocks

### ISSUE THREAD

**Issue by Magdargi** [magefree/mage#4353]
Attempting to activate Chromatic Star or Sphere causes it to be impossible to pay for the cost (lands don't tap, mana doesn't reduce from pool) and the cancel button does work correctly (the cards doesn't return to the battlefield, the interface is frozen).

**Comment by JayDi85** [comment]
That's bug with not shown choice window was in one of the developer version week ago (see base issue #4318). But was fixed. Now it works fine. Wait next v11 release or download [current v11 beta from here](https://yadi.sk/d/oLKb_rzG3PwE7n) (500 MB)
