### ISSUE TITLE
Unable to Launch

### ISSUE THREAD

**Issue by SirMrTheSir** [magefree/mage#4355]
So I have the Newest version of Java installed and I have the launcher selected to run off the "javaws" program in the java folder. Then when I try to tun the launcher, tilted "XMageLauncher-0.3.8", an error message appears and says "Unable to launch the application." Then there is an option to click "ok" or "details". When I click "details" it says "Error: Could not parse launch file. Error at line one." Below that are three tabs labeled "launch File", "Exception", and "Wrapped Exception". In "Launch File" there are the letters "PK" and nothing else. Under the Exception and Wrapped exception file there appear to be long lines of code. I did some research into this on my on and found a thread where you attempted to help someone with the same problem about year ago, but after you asked them what version of java they were running, the stopped responding, so the current version of java that i am using is "1.8.0_151-b12" if that helps at all. Thanks for the help.

**Comment by JayDi85** [comment]
Try to use command line to run launcher:
`java.exe -jar XMageLauncher-0.3.8.jar`
Save that text in command file  in launcher folder (example: run.cmd for windows and run.sh for linux). And run it.
