### ISSUE TITLE
How to make a new pull request?

### ISSUE THREAD

**Issue by SpikesCafe-google** [magefree/mage#4357]
I implemented a new card and tested it locally, but I have no idea how to commit/pull/any of those Git things. It seems like the commit is under my user/machine on my local network and not my Github user. Is there any good reading material about this part? The dev guide seems to kind of assume you know Git to some degree. Thanks!

![xmage-new-pull](https://user-images.githubusercontent.com/16656302/34654284-c184b5dc-f3c7-11e7-9da3-7d1b6f54b43c.jpg)

Also, if there's a different place I should be asking for help, please let me know.

**Comment by JayDi85** [comment]
Well, you can ask here if you have one question. If that's more -- then ask it on https://gitter.im/xmage-devs/Lobby

I'm recommends to read any basic materials about git (like [basic git](https://git-scm.com/book/en/v2/Getting-Started-Git-Basics) and [101 git](http://rogerdudler.github.io/git-guide/). And only then use netbeans tutorial ([official](https://netbeans.org/kb/docs/ide/git.html)).  As a deep lear you can read about branches, local, remote, commits, checkouts, pull, push, compare changes, history, merge.

**Comment by SpikesCafe-google** [comment]
Thanks! I'm in a little better shape now. However, when I try to push, I get an error. Anything about that look suspicious? Maybe something with SSL keys? Everything up to this point, committing and pulling, has worked fine.
https://SpikesCafe-google@github.com/magefree/mage.git/: git-receive-pack not permitted

![untitled-1](https://user-images.githubusercontent.com/16656302/34655164-7f9a6002-f3d3-11e7-9950-8eefd7fe8834.jpg)
![xmage-new-push](https://user-images.githubusercontent.com/16656302/34655165-8222c648-f3d3-11e7-9dfb-40d9a299f013.jpg)

**Comment by JayDi85** [comment]
Master repository have changes from your last pull request (from your last source download). You need to update your project (download latest commits) and merge changes from master to your code. After that github accept your request.

**Comment by SpikesCafe-google** [comment]
Thanks! It seems like github still doesn't like my push request:

```
==[IDE]== Jan 7, 2018 6:24:13 PM Fetching - mage
git fetch https://SpikesCafe-google@github.com/magefree/mage.git/ +refs/heads/*:refs/remotes/origin/*
Total 5077 (delta 3345), reused 3699 (delta 2102), pack-reused 0
Branch  : origin/customEffectDuration
Old Id : null
New Id : 8e895536b9f5c535e5d1816305a784a497099c8c
Result : NEW

Branch  : origin/phasingFix
Old Id : null
New Id : fdf3f831ca487bf0df8946f5d600f495d0691385
Result : NEW

Branch  : origin/MCTS_AI_Improvements
Old Id : null
New Id : a0085673be8e87ea5c03a998a49773060342b8fe
Result : NEW

Branch  : origin/feature/network_bandwidth
Old Id : null
New Id : 2256871540403acc9b81e31ff6eb8f3b97c33add
Result : NEW

Branch  : origin/staging
Old Id : null
New Id : d8ff28c7f7c97ba86b7aba6eedfe0589a019fab0
Result : NEW

Branch  : origin/Network_Upgrade
Old Id : null
New Id : 0007099eb3bb8ddc204ada6c9fc3b1d01763c134
Result : NEW

Branch  : origin/feature/3072_fix_for_BloodMoon_and_Urborg
Old Id : null
New Id : 9d256fc09b0afec8107308c0f949d4540763f4b3
Result : NEW

Branch  : origin/feature/fix_new_perspectives_freeze
Old Id : null
New Id : 2a366c4022061f417ae9001a9b0287f327aaabee
Result : NEW

==[IDE]== Jan 7, 2018 6:24:15 PM Fetching - mage finished.
==[IDE]== Jan 7, 2018 6:24:34 PM Pulling - mage
git remote -v
setting up remote: origin
git fetch https://SpikesCafe-google@github.com/magefree/mage.git/ +refs/heads/master:refs/remotes/origin/master
No update
==[IDE]== Jan 7, 2018 6:24:41 PM Pulling - mage cancelled.
==[IDE]== Jan 7, 2018 6:25:14 PM Pushing - mage
git branch
git remote -v
setting up remote: origin
git submodule status
git push https://SpikesCafe-google@github.com/magefree/mage.git/ refs/heads/master:refs/heads/master
==[IDE]== Jan 7, 2018 6:25:16 PM Pushing - mage finished.
```

**Comment by JayDi85** [comment]
You didn't direct access to xmage origin repository? Then do commits to your repo.

![shot_180108_040213](https://user-images.githubusercontent.com/8344157/34655777-eea2ab9e-f428-11e7-9f24-ba61f5f6016c.png)

[As you can see](https://github.com/SpikesCafe-google/mage) -- it's an old one. Open it and select pull request:
![shot_180108_040505](https://user-images.githubusercontent.com/8344157/34655792-2677b398-f429-11e7-8185-841d5aea443d.png)

Switch base to update code from xmage main repo to your:
![shot_180108_040531](https://user-images.githubusercontent.com/8344157/34655798-3fa307fa-f429-11e7-922b-9ff0def975d3.png)

Create and merge that pull:
![shot_180108_040636](https://user-images.githubusercontent.com/8344157/34655806-61625328-f429-11e7-9fc9-85194964a798.png)

Connect to your repo, fetch/download it and apply your old commits to it (rebase or simple copy-paste files). Then push that commits to your repo and create pull request by github (see above -- but now your repo would head).
