### ISSUE TITLE
Raging Regisaur is a 2/2 instead of 4/4

### ISSUE THREAD

**Issue by SpikesCafe-google** [magefree/mage#4358]
https://media.wizards.com/2017/rix/en_O6CxZz4CjO.png
https://github.com/magefree/mage/blob/c599a77f810d4db808c03f390796c900f3c0b355/Mage.Sets/src/mage/cards/r/RagingRegisaur.java

Also the in-game text only says "it deals 1 damage to target creature or player" with no mention of attacking.

**Comment by JayDi85** [comment]
Fixed in cd437ce8b8b5a416c5cc1342ec7d9aee3cd960c1
