### ISSUE TITLE
Launcher not downloading 1.4.26V11

### ISSUE THREAD

**Issue by arct1cf0x** [magefree/mage#4359]
I had to delete the files for xmage and after reopening the launcher the new version won't download. The progress bar shows no progress after 20 minutes

**Comment by JayDi85** [comment]
It's a servers downtime. Try later. Or you can download dev version [from here](https://yadi.sk/d/oLKb_rzG3PwE7nl) (same as release) and play with yours local server (while others is not working).

**Comment by LevelX2** [comment]
That's caused by too many download requests and will probably be faster over time.

If someone can provide a fast server to support download of new versions, let me know.

**Comment by JayDi85** [comment]
@LevelX2 Maybe [github.io](https://pages.github.com/) have tools to host website and files. And it's integrated with project repository e.g. can update pages by commits to repo. But need to split update to files (only [50-100 Mb files support](https://help.github.com/articles/working-with-large-files/)).
