### ISSUE TITLE
Shortcut for replacement effects is no longer available

### ISSUE THREAD

**Issue by tawmas** [magefree/mage#4360]
The old dialog box to choose which replacement effect to apply (up to 1.4.26V10) first allowed a shortcut to always choose the same effect. The new dialog box no longer offers this option.

Imagine having two Metallic Mimic set on the same creature type and casting multiple creatures of that creature type. With the new UI, you are prompted to choose a replacement effect each time, while the old UI allowed to set-and-forget for the rest of the game. While the new UI is friendlier, it would be nice to add back the old shortcut.

Thank you.

**Comment by JayDi85** [comment]
Is that was "auto complete" button in left bottom corner?

![shot_180108_035727](https://user-images.githubusercontent.com/8344157/34655733-0db4be88-f428-11e7-80f1-d2426f455763.png)

**Comment by Zzooouhh** [comment]
@JayDi85 Yes, it was the autocomplete button. It used to be rather buggy, but a recent commit 2564f611823ad60526fcc0dd22ea222385f1305f apparently addressed it.

**Comment by JayDi85** [comment]
Implemented in https://github.com/magefree/mage/issues/6676#issuecomment-895016420
