### ISSUE TITLE
Slaughter the Strong bugged?

### ISSUE THREAD

**Issue by JayDi85** [magefree/mage#4362]
[From CCGH forum](https://www.slightlymagic.net/forum/viewtopic.php?f=70&t=20974&sid=5dd219f292c3529aa893d68d7d2d65d8&p=221588#p221588):
Slaughter the Strong is bugged. I had a 4/5 and a 3/1 and when my opponent cast it, all my creatures died, with no chance to save even one of them.

![shot_180108_041423](https://user-images.githubusercontent.com/8344157/34655864-6b610076-f42a-11e7-98ea-654fa3ab81ca.png)

> Each player chooses any number of creatures he or she controls with total power 4 or less, then sacrifices the rest.

**Comment by JayDi85** [comment]
Another one report from reddit:

My opponent wasn't prompted to pick his creatures during the resolution of my Slaughter the Strong

**Comment by rhamilton281** [comment]
Can confirm, opponent played Slaughter the Strong and I was never prompted to select creatures even though I had a 1/1, 3/3, and 3/4 on the field. All three were sacrificed.
![captu2re](https://user-images.githubusercontent.com/3932329/34788977-0c7370a6-f602-11e7-8ea6-687156fe6013.PNG)

**Comment by stottymod** [comment]
Confirming also. I played Slaughter the Strong twice in two games, the first game I got to keep the creatures I chose, and opponent lost all of his, then in the second I picked mine, opponent lost his, then I lost the creatures I had picked.

**Comment by JayDi85** [comment]
It can be affected by "creature permanent filter" bug (#4402). If so, then if fixed already and will be deploy to servers on next update (v11e+)

**Comment by LevelX2** [comment]
Fixed with f528d556d62f436110bdfe580f1d5b20d42c7c6d

**Comment by bpburns8** [comment]
I experienced a bug with this last night where the dialog appeared telling me to select the creatures I wanted to keep, but after selecting them and clicking 'End Creature Selection', all my creatures died. Was this simply user error?
