### ISSUE TITLE
Pirate's Pillage coded as random discard instead of player choice

### ISSUE THREAD

**Issue by AwkwardCrow** [magefree/mage#4365]
The card just says discard, here's a screenshot of the hover text showing the client's rules saying random, and playing the card confirms it's random.

![bug](https://user-images.githubusercontent.com/11721827/34659715-06b7204e-f40a-11e7-82ef-c84c25078ef8.PNG)

**Comment by JayDi85** [comment]
Fixed in eb7166aa2fbc113c09914676f80a64daca84fa34
