### ISSUE TITLE
Spring // Mind - can't cast Mind from graveyard, aftermath ability is broken

### ISSUE THREAD

**Issue by JayDi85** [magefree/mage#4366]
From reddit:
Bug: Spring//Mind - Can't cast Mind from graveyard. Don't know if it applies to other aftermath cards too though.

**Comment by JayDi85** [comment]
Another one report to aftermath broken:

from forum:
1.4.26 Seems to have broken the aftermath Mechanic. When attempting to cast the Market part of Farm / Market from the GY, clicking on the card doesn't seem to provoke any interaction.

**Comment by jeffwadsworth** [comment]
It applies to all Aftermath cards.  By the way, casting from other zones, for example Exile, is still ok.

**Comment by jeffwadsworth** [comment]
I believe this may be the culprit commit.
https://github.com/magefree/mage/commit/1d2483c0fdc5c569ed40d5d84e0c0ea036507963

**Comment by jeffwadsworth** [comment]
https://github.com/magefree/mage/commit/f95b0e6c0a760cfa54011038b9ad9e9324e9dfc3#diff-2c24f51cdb981268f32e8ebcddc3a529

**Comment by LevelX2** [comment]
@jeffwadsworth 
You can revert the change to PlayerImpl.java.If possible add a test that detects the problem with Aftermath.
The fix was for casting split cards from exile, but was not finished anyways.

**Comment by jeffwadsworth** [comment]
https://github.com/magefree/mage/commit/7ade17595d111b189fd15b59c4cec4d5033cc896
