### ISSUE TITLE
1.4.26V11 CPU load problems

### ISSUE THREAD

**Issue by LevelX2** [magefree/mage#4367]
As often, after this update some cards cause new CPU consuming bugs.
I need to check the logs and/or use the Java Flight Recorder to identify the problems.

![xmage de](https://user-images.githubusercontent.com/2066790/34664298-7e0ffd0e-f45b-11e7-9dc3-784ada7fb46c.jpg)

**Comment by JayDi85** [comment]
Can it be AI loop on choices dialogs? I saw some potential loop code with it: e.g. if all choices will be delete somehow, then AI can't select and will be loop. E.g. destroying static lists and ruined other code, [real example](https://github.com/magefree/mage/commit/75cec526dcd47fe26e42b79c63179a8dd505c5c6)) .

**Comment by LevelX2** [comment]
AI can't be the problem. On the public server AI is deactivated.

Usually that are logic loops in cards or not checked exceptions that lead to that CPU usage.

**Comment by JayDi85** [comment]
Is that a draftbot AI? Found that active drafting match on broken xmage server today:

![shot_180109_081421](https://user-images.githubusercontent.com/8344157/34704811-382b0d0a-f515-11e7-8155-d7d970570627.png)


![shot_180109_081541](https://user-images.githubusercontent.com/8344157/34704837-75237f62-f515-11e7-9f05-458eec5c2af9.png)

**Comment by LevelX2** [comment]
If a player disconnects during a draft, it's replaced by a draftbot. That's ok.
