### ISSUE TITLE
Cherished Hatchling's gained EntersBattlefieldTriggered abilities do not work

### ISSUE THREAD

**Issue by LevelX2** [magefree/mage#4368]
1) Cherished Hatchling died.
2) Controller cast another Dinosaur in the same turn.
3) The by  Cherished Hatchling gained EntersBattlefieldTriggered  does not trigger for the cast Dinosaur..

**Comment by omaraa** [comment]
Also encountering the same issue. It looks like the ability is put on the stack, but it does not resolve.

**Comment by Sankluj** [comment]
Encountered that issue as well.

**Comment by zorkmead** [comment]
trigger for fight goes on stack but cannot choose to resolve it in v4b

**Comment by awjackson** [comment]
This card is still broken, even after the changes that were made to `GainAbilityTargetEffect` in order to implement Tyvar Kell's emblem.
