### ISSUE TITLE
Remove the land restriction on Limited?

### ISSUE THREAD

**Issue by JayDi85** [magefree/mage#4373]
From discord by flap:
Any chance of lifting the land restriction on Limited?
[you can only add lands from the sets that cards you drafted were from]
  
And from reddit by Alterus_UA:
A drawback: in Sealed, you can now only add basic lands from the sets that are in your pool. I don't think this limitation should be enforced. IRL, in a LGS, you can use lands from different sets in any available combinations, or bring your own lands for a Limited tournament.

**Comment by Alterus90** [comment]
Dear developers, please address this issue. It's an unmotivated drawback in player experience.
