### ISSUE TITLE
Angrath, the Flame-Chained, sacrified creature with mana cost greater than 3

### ISSUE THREAD

**Issue by mathieupouedras** [magefree/mage#4376]
xmage_1.4.26V11b

My opponent is playing A[ngrath, the Flame-Chained](https://mythicspoiler.com/rix/cards/angraththeflamechained.html), it takes control of [tali, Primal Storm ](http://mythicspoiler.com/rix/cards/etaliprimalstorm.html)
and then sacrificed it whereas its mana cost is 6 > 3

[20180108_165945_Two Player Duel_3.txt](https://github.com/magefree/mage/files/1612229/20180108_165945_Two.Player.Duel_3.txt)

**Comment by jeffwadsworth** [comment]
Fixed.  https://github.com/magefree/mage/commit/121c0ff89418244a1cc2e629e82e42737976d3cf
