### ISSUE TITLE
Enter the unknown does not trigger shadowed carvel

### ISSUE THREAD

**Issue by ds391** [magefree/mage#4377]
Enter the Unknown causes a creature to explore, but ShadowedCaravel does not gain a counter

**Comment by Zzooouhh** [comment]
Did Enter the Unknown reveal a land or nonland card?

**Comment by ds391** [comment]
Revealed a non-land

**Comment by maximusmaxy** [comment]
Enter the unknown is also bugged for similar triggers like Wildgrowth Walker and Lurking Chupacabra.

**Comment by LevelX2** [comment]
Fixed with 9a760670dd772f360924cae6a1153915ad5ead1d
