### ISSUE TITLE
Vigorous Charge card missing

### ISSUE THREAD

**Issue by PhilistineAu** [magefree/mage#4378]
Hi,
The "Vigorous Charge" card from the Invasion set seems to be missing.  I can not find it in the deck editor, including when I search for "Charge" and "Vigorous".

This is the link to the card on scryfall: https://scryfall.com/card/inv/222

Thank you!

**Comment by ingmargoudt** [comment]
Vigorous Charge is not implemented yet.

**Comment by PhilistineAu** [comment]
Yep.  I was hoping to use it in a Penny Dreadful mtg deck (cards that are 0.01 tix each) but couldn't find it.  Hopefully it isn't insanely difficult to code.

**Comment by spjspj** [comment]
https://www.slightlymagic.net/forum/viewtopic.php?f=70&t=20685 to ask for cards to be implemented.
