### ISSUE TITLE
Champion of Dusk :: Does Not Count Itself as a Vampire on ETB Effect

### ISSUE THREAD

**Issue by FastTadpole** [magefree/mage#4380]
ETB code must be set to other vampires you control rather than number of Vampires you control.

> When Champion of Dusk enters the battlefield, draw X cards and you lose X life, where X is the **number of Vampires you control**.

**Comment by ingmargoudt** [comment]
I created a unit test for this that confirmed it, looking for a fix.

**Comment by ingmargoudt** [comment]
Ability was coded as a static  rather than a triggered ability
