### ISSUE TITLE
Pride of Conquerors creatures you control get +1/+1

### ISSUE THREAD

**Issue by slindberg68** [magefree/mage#4390]
Card does not give your creatures +1/+1, when you do not have the city's blessing. 
Not sure if it works when Ascend is activated.

**Comment by mbenchim** [comment]
I can confirm the +2/+2 does work when you have ascend (at least yesterday it did).  Also had the same problem with no +1/+1.

**Comment by jeffwadsworth** [comment]
Fixed.  https://github.com/magefree/mage/commit/4f38939fc1f9acb15b749c14aa2d73fc39e65f60
