### ISSUE TITLE
Aftermath cards - Bottom half doesn't work

### ISSUE THREAD

**Issue by mbenchim** [magefree/mage#4393]
Already was reported for a specific card (Spring // Mind), but it seems that all aftermath cards are broken, i.e. can't cast the bottom half.  I've tested Dusk // Dawn, Driven // Despair, and Start // Finish.  Top half of all of them work, but the bottom half can't be cast from the graveyard like you could previously.

**Comment by jeffwadsworth** [comment]
This is already on the bug list.

**Comment by JayDi85** [comment]
Duplicate of #4366
