### ISSUE TITLE
Teferi's Protection no longer phases out lands and artifacts

### ISSUE THREAD

**Issue by Stafy1** [magefree/mage#4394]
This happened on multiple occasions. Teferi's Protection used to work properly before the full RIX launch but now doesnt work with land and artifacts.

**Comment by jeffwadsworth** [comment]
Worked fine for me in the latest build.  Please provide game logs if it happens again.

**Comment by LevelX2** [comment]
Becuase Teferi's Protection is using StaticFilters.FILTER_CONTROLLED_PERMANENT I guess this is also a problem of unproper StaticFilters usage. #4402

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.
