### ISSUE TITLE
Missing cards

### ISSUE THREAD

**Issue by FreddyHair** [magefree/mage#4397]
For some reason, some cards simply don't exist in the program (I found the issue specifically with [Sporogenesis](
http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5750), not sure if other cards have the same issue). I tried forcing database updates when connecting to my local server (with internet on, of course), but that didn't work.

(I tried looking through the issues and couldn't find anything like this, sorry if I missed it and this is a repeat)

**Comment by LevelX2** [comment]
https://github.com/magefree/mage/issues/4378
