### ISSUE TITLE
Having issues with the symbols

### ISSUE THREAD

**Issue by domcosta** [magefree/mage#4400]
Can't see all the symbols if I highlight a card
![symbols](https://user-images.githubusercontent.com/35345330/34840823-786c1592-f706-11e7-95fd-40a664cd1705.jpg)

**Comment by JayDi85** [comment]
Steps to fix:
 * Close app;
 * Move xmage folder and all files to another place (e.g. from download folder to c:\xmage);
 * Restart app and open symbols download (from main menu);
 * Restart app again;
 * Report errors if got it (see black window with text or "..\xmage\mage-client\mageclient.log" file).

**Comment by domcosta** [comment]
![symbols](https://user-images.githubusercontent.com/35345330/34873279-b91c5de8-f794-11e7-8313-984259c2dfcf.jpg)
Problem solved. Thanks for the answer!

**Comment by JayDi85** [comment]
Have a nice play.
