### ISSUE TITLE
 Daretti, Ingenious Iconoclast - wrong third text

### ISSUE THREAD

**Issue by JayDi85** [magefree/mage#4405]
[From reddit](https://www.reddit.com/r/XMage/comments/7pxomw/daretti_ingenious_iconoclast_incorrect_reminder/), errors with [Daretti, Ingenious Iconoclast](https://scryfall.com/card/cn2/74):
Third ability have incorrect text
Current:
![3ghvn8l4yn901](https://user-images.githubusercontent.com/8344157/34888617-5d0ee1ec-f7e4-11e7-8608-0860a48313d6.png)
Need: 
−6: Choose target artifact card in a graveyard or artifact on the battlefield. Create three tokens that are copies of it.

**Comment by Zzooouhh** [comment]
For 2., shouldn't the current implementation be correct? The ability isn't modal - you're supposed to choose one target, it's just that you're supposed to look for the target within two different zones.

**Comment by JayDi85** [comment]
Argth, my fault... It's the same artefact cards. Second issue is fine.
