### ISSUE TITLE
Lion's Eye Diamond

### ISSUE THREAD

**Issue by LiquidElf** [magefree/mage#4408]
hi,

holding priority and activating Lion's Eye Diamond seems to break the Game. the log shows that cards have been discarded but no prompt for mana creation comes up and the  program doesn't progress through the stack

**Comment by Zzooouhh** [comment]
What Xmage client version are you on?

**Comment by LiquidElf** [comment]
1.a.26

**Comment by JayDi85** [comment]
v10 have bug with pickup number dialogs (you don't see "enter number" window, e.g. after any color mana selection). Update to v11.

**Comment by LiquidElf** [comment]
okay thanks
