### ISSUE TITLE
Incorrect ordering of colors for M15 rendering

### ISSUE THREAD

**Issue by spjspj** [magefree/mage#4411]
For example: Breeding Pool should be Green then Blue (left to right) - not Blue Green 
![image](https://user-images.githubusercontent.com/16917728/34911360-338d22a4-f91d-11e7-9d45-3264ad439670.png)

**Comment by Zerrisx** [comment]
Where do you even find M15 rendering?  I can see XMage and MTGO rendering, both of which show the correct order of background color

**Comment by JayDi85** [comment]
M15 is MTGO render mode in current version:
* IMAGE render mode -- cards draws as images (if no images available then as simple text);
* MTGO render mode -- cards draws as full card with icons, text, background image, colors, etc. Moreover it have different render mode for different card types (split cards, full size lands, etc).

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.
