### ISSUE TITLE
Arcane Denial - broke the game on player concede

### ISSUE THREAD

**Issue by JayDi85** [magefree/mage#4413]
[From reddit](https://www.reddit.com/r/XMage/comments/7qc2zb/two_bug_reports_arcane_denial_blood_clock/):

[Arcane Denial](https://scryfall.com/card/c16/83):
When the draw ability goes on the stack during the next upkeep, if the player whose spell was countered did concede in the meantime (in our case, the player rage-quit), the player (who is not in the game anymore) still has priority for his draw trigger, and the only way to continue the game is to wait for the player to time out.

**Comment by jeffwadsworth** [comment]
This looks like the DelayedTrigger is not checking for the existence of the targeted player.  I will check it out.

**Comment by Zerrisx** [comment]
Did this ever get checked out?

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.
