### ISSUE TITLE
[UI] Sorting by Rarity should use Tiers not Alphabetical

### ISSUE THREAD

**Issue by apoapostolov** [magefree/mage#4414]
In Table vew, shorting by Rarity should use Rarity Tier (Common 1...Mythic 4) not Alphabetical

Right now the list sorts Common, Mythic, Rare, Uncommon rather than Common, Uncommon, Mythic, Rare

**Comment by JayDi85** [comment]
Done by 72d23bfe95f89c1b3f3f4e08c405c162feb4cb7a, will be available in next release.
