### ISSUE TITLE
Can't launch XMage JAR launcher from new server

### ISSUE THREAD

**Issue by rlombardelli** [magefree/mage#4416]
Hello everyone, 

Tonight I tried to launch the xmage client and it told me that my version wasn't up to date, and I couldnt update it.
I thought that my launcher wasn't up to date and downloaded the latest one. My problem is that now, I can't seem to launch the JAR at all.

I'm on the java version 1.8.0_151, and the error when I try to launch the jar from console is the following : 
```
Exception in thread "main" java.lang.ExceptionInInitializerError
Caused by: java.lang.RuntimeException: Uncompilable source code - package org.json does not exist
        at com.xmage.launcher.XMageLauncher.<clinit>(XMageLauncher.java:48)
```

If someone has any idea, It'd be welcome ! :) 
Thanks a lot, have a good day.

**Comment by JayDi85** [comment]
* Download [xmage launcher here](http://bit.ly/xmageLauncher038);
 * Place it to new folder;
 * Run it -- if can't then delete and [re-install java](http://java.com/);
 * Wait launcher download and install updates (java + xmage files), there are must be created new folders: xmage with mage-client and mage-server folder, and java folder;
 * Your xmage version must be 27v0 in launcher window;
 * Run client by launcher;
 * Report your error here.

Run client without launcher is not recommended.

**Comment by ngdrex** [comment]
I'm getting the same error running the same version of java on windows 8.1 except this is my first install. I have tired reinstalling java and i'm still getting the same error.

**Comment by mateuszwinnicki** [comment]
I have the same error.

```
Caused by: java.lang.RuntimeException: Uncompilable source code - package org.json does not exist
        at com.xmage.launcher.XMageLauncher.<clinit>(XMageLauncher.java:48)
```

It seems that .jar is corrupted? org.json is not included in classpath?

**Comment by rlombardelli** [comment]
Hey @JayDi85,

Thanks for the fast reply, I appreciate it :)

I'm stuck between step 3 and 4. I already deinstalled and reinstalled java several times, but I cannot seem to launch the launcher. Is it possible that I have a corrupted file somewhere ? I have no idea where this problem might come from.

Thanks again for trying to help me.

EDIT: oh, it seems that i'm not the only one. Let's see what's happening then. :)

**Comment by ConradTxK** [comment]
Same error. i think developer will upload new version of Xmage?

**Comment by JayDi85** [comment]
New xmage server have broken launcher file. Wait to fix it or download [old one from here](https://yadi.sk/d/MfI7oUrn3RTFWS).

**Comment by LevelX2** [comment]
The launcher from the old server can be downloaded here:
http://185.3.232.200/xmage/XMageLauncher-0.3.8.jar

**Comment by LevelX2** [comment]
Launcher File on new xmage.de server is updated and works again.

**Comment by rlombardelli** [comment]
Thanks a lot !
