### ISSUE TITLE
Warkite Marauder do not trigger on planewalker attack?

### ISSUE THREAD

**Issue by JayDi85** [magefree/mage#4422]
[From reddit](https://www.reddit.com/r/XMage/comments/7qomcr/warkite_marauder_bug/):

[Warkite Marauder](https://scryfall.com/card/rix/60)

My client and server is up to date. I played Warkite Marauder in cube today and attacked into a Gideon PWer (both manually and due to his +1 ability) a few times.
Everytime when Warkite Marauder attacked, its triggered ability does not trigger if he is attacking into a PWer.

**Comment by jeffwadsworth** [comment]
Was the Gideon Jura a creature at the time?  It has to use the ultimate to do this.

**Comment by ingmargoudt** [comment]
Which Gideon? As far as I know Gideon can change into a creature (token) until end of turn, so if an opponent used the ability, how can it be a creature as you attack into it ?

**Comment by Zerrisx** [comment]
Can we get more detail here?
