### ISSUE TITLE
Star Wars The Gathering full support?

### ISSUE THREAD

**Issue by JayDi85** [magefree/mage#4424]
Is that a current star wars set or the new one? May be need to support that too. There are release new [Last Jedi expansion](https://imgur.com/a/RPV5d).

http://www.starwarsthegathering.com/

Expansions:
  * The Last Jedi [19MB]
  * Rogue One [13MB]
  * The Force Awakens [12MB]

Base Set:
  * Base Set [266MB, torrent]

**Comment by LevelX2** [comment]
Star Wars: The Gathering Base Set 271/271 
http://imgur.com/gallery/vA4Ue EPVII: 

The Force Awakens expansion 15/15 
http://imgur.com/gallery/hdQOl

Rogue One expansion 17/17
https://imgur.com/gallery/DAGOw

Episode VIII: The Last Jedi expansion 25/25
https://imgur.com/a/RPV5d
