### ISSUE TITLE
Hardened Scales + Jadelight Ranger BUG

### ISSUE THREAD

**Issue by EllNubNub** [magefree/mage#4426]
it is a simple bug. hardened scales does not put an extra counter on jadelight when it explores (and it should do so twice if i get the nonland triggers) not sure if this happens with all explore cards but yeah. simple bug im sure easy fix, thanks guys!

**Comment by jeffwadsworth** [comment]
This worked fine for me in the latest build.  Please show the game logs if you see it again.
