### ISSUE TITLE
Animate Dead on an opponent's DL Atarka caused it to be sacrificed

### ISSUE THREAD

**Issue by spjspj** [magefree/mage#4428]
Log is below.  But animate dead targeted DL Atarka using mana from a swamp and karakas (only lands the player had).  Animate Dead was then put back into the GY immediately causing DL atarka to be sacced.

2:00 PM: Pream puts Swamp [965] from hand onto the Battlefield
2:00 PM: Pream plays Swamp [965]
2:00 PM: tryads reveals Dragonlord Atarka, Misty Rainforest, Swamp, Riftwing Cloudskate, Prairie Stream, Breeding Pool
2:00 PM: Pream puts Thoughtseize [d05] from stack into his or her graveyard
2:00 PM: tryads discards Dragonlord Atarka [a21]
2:01 PM: Pream puts Karakas [ef6] from hand onto the Battlefield
2:01 PM: Pream plays Karakas [ef6]
2:01 PM: Pream casts Animate Dead [d07] targeting Dragonlord Atarka [a21] 
2:01 PM: Pream puts Animate Dead [d07] from stack onto the Battlefield
2:01 PM: Ability triggers: Animate Dead [d07] - When Animate Dead [d07] enters the battlefield, if it's on the battlefield, it loses "enchant creature card in a graveyard" and gains "enchant creature put onto the battlefield with Animate Dead [d07]." Return enchanted creature card to the battlefield under your control and attach Animate Dead [d07] to it.
2:01 PM: Pream puts Dragonlord Atarka [a21] from graveyard onto the Battlefield
2:02 PM: Animate Dead [d07] is put into graveyard from battlefield
2:02 PM: Ability triggers: Animate Dead [d07] - When Animate Dead [d07] leaves the battlefield, enchanted creature's controller sacrifices it.
2:02 PM: Pream sacrificed Dragonlord Atarka [a21]

**Comment by spjspj** [comment]
None (apart from lands) and none.  No pws or creatures were controlled by opponents.  DL Atarka didn't have pro black and ended up in the gy as did animate dead.  It was a 3way ffa. Will see if I can recreate it.

**Comment by spjspj** [comment]
```
1:58 PM: ME has joined the game
1:58 PM: OPPONENT2's library is shuffled
1:58 PM: ME's library is shuffled
1:58 PM: OPPONENT1's library is shuffled
1:58 PM: OPPONENT2 won the toss
1:58 PM: OPPONENT1 draws seven cards
1:58 PM: OPPONENT2 draws seven cards
1:58 PM: OPPONENT2 chooses that OPPONENT1 takes the first turn
1:58 PM: ME draws seven cards
1:59 PM: OPPONENT1 keeps hand
1:59 PM: OPPONENT2 keeps hand
1:59 PM: ME keeps hand
1:59 PM: Turn 1 OPPONENT1 (20 - 20 - 20)
1:59 PM: OPPONENT1 puts Island [597] from hand onto the Battlefield
1:59 PM: OPPONENT1 plays Island [597]
1:59 PM: OPPONENT1 casts Gitaxian Probe [2cd] targeting ME 
1:59 PM: OPPONENT1 draws a card
1:59 PM: OPPONENT1 puts Gitaxian Probe [2cd] from stack into his or her graveyard
1:59 PM: OPPONENT1 attacks with 0 creatures
2:00 PM: Turn 2 OPPONENT2 (20 - 20 - 20)
2:00 PM: OPPONENT2 draws a card
2:00 PM: OPPONENT2 puts Swamp [965] from hand onto the Battlefield
2:00 PM: OPPONENT2 plays Swamp [965]
2:00 PM: OPPONENT2 casts Thoughtseize [d05] targeting OPPONENT1 
2:00 PM: OPPONENT1 reveals Dragonlord Atarka, Misty Rainforest, Swamp, Riftwing Cloudskate, Prairie Stream, Breeding Pool
2:00 PM: OPPONENT2 puts Thoughtseize [d05] from stack into his or her graveyard
2:00 PM: OPPONENT1 discards Dragonlord Atarka [a21]
2:00 PM: OPPONENT2 loses 2 life
2:00 PM: OPPONENT2 attacks with 0 creatures
2:00 PM: Turn 3 ME (18 - 20 - 20)
2:00 PM: ME draws a card
2:00 PM: ME plays Swamp [8fa]
2:00 PM: ME puts Swamp [8fa] from hand onto the Battlefield
2:00 PM: ME attacks with 0 creatures
2:00 PM: Turn 4 OPPONENT1 (18 - 20 - 20)
2:00 PM: OPPONENT1 draws a card
2:01 PM: OPPONENT1 plays Prairie Stream [cc7]
2:01 PM: OPPONENT1 puts Prairie Stream [cc7] from hand onto the Battlefield
2:01 PM: OPPONENT1 attacks with 0 creatures
2:01 PM: Turn 5 OPPONENT2 (18 - 20 - 20)
2:01 PM: OPPONENT2 draws a card
2:01 PM: OPPONENT2 puts Karakas [ef6] from hand onto the Battlefield
2:01 PM: OPPONENT2 plays Karakas [ef6]
2:01 PM: OPPONENT2 casts Animate Dead [d07] targeting Dragonlord Atarka [a21] 
2:01 PM: OPPONENT2 puts Animate Dead [d07] from stack onto the Battlefield
2:01 PM: Ability triggers: Animate Dead [d07] - When Animate Dead [d07] enters the battlefield, if it's on the battlefield, it loses &quot;enchant creature card in a graveyard&quot; and gains &quot;enchant creature put onto the battlefield with Animate Dead [d07].&quot; Return enchanted creature card to the battlefield under your control and attach Animate Dead [d07] to it.
2:01 PM: OPPONENT2 puts Dragonlord Atarka [a21] from graveyard onto the Battlefield
2:02 PM: Animate Dead [d07] is put into graveyard from battlefield
2:02 PM: Ability triggers: Animate Dead [d07] - When Animate Dead [d07] leaves the battlefield, enchanted creature's controller sacrifices it.
2:02 PM: OPPONENT2 sacrificed Dragonlord Atarka [a21]
2:02 PM: OPPONENT2 attacks with 0 creatures
```

**Comment by jeffwadsworth** [comment]
Finally got a chance to look at this.  I see what is going on and will test a fix.

**Comment by LevelX2** [comment]
I can't reproduce the problem.
I tested with Dark Hatchling  and Dragonlord Atarka, both with no available targets. 
It worked in both cases correctly.

**Comment by HR19** [comment]
I'm afraid I have no log, but I've had similar behavior twice from Animate Dead, most recently it was with Elesh Norn.

**Comment by Zzooouhh** [comment]
@HR19 Which version did this happen on?
