### ISSUE TITLE
Constant freezes on xmage.de server

### ISSUE THREAD

**Issue by Badaro** [magefree/mage#4434]
Having constant freezes when playing on this server on the recent days. 

They all follow the same pattern: At some point in the game, the clock keeps ticking but the affected player cannot see any buttons to pass priority. Skip buttons (F4-F11) have no effect. Sometimes it fixes itself after a few minutes, sometimes a rollback helps, other times it just stays stuck until someone conceces.

This usually happens on phase changes,  I don't think I've seen this happen on other actions. Might be lag related, I've noticed the overall performance has been rather bad recently.

Client is running 1.4.27V0.

**Comment by JayDi85** [comment]
Current workaround that can help -- close affected client (disconnect) and re-connect again to game.

**Comment by Badaro** [comment]
Happened again just now. Talking to the opponent, it seems it was showing a different state for both of us - one was "Waiting for <P1>", other was "Waiting for <P2>".

**Comment by JayDi85** [comment]
It was fixed in v1-v2 server versions (v3 will fix freeze on "other player concede the game"). If you got it again -- fill free to report about it.
