### ISSUE TITLE
Transformed cards don't count towards devotion

### ISSUE THREAD

**Issue by derlhurgoyf** [magefree/mage#4435]
In a game I had Liliana, Heretical Healer transformed and activated Nykthos, Shrine to Nyx, but it wouldn't add two black mana to my pool even though the rules state:

> 711.4b While a double-faced permanent’s back face is up, it has only the characteristics of its back face. However, its converted mana cost is calculated using the mana cost of its front face. If a permanent is copying the back face of a double-faced card (even if the card representing that copy is itself a double-faced card), the converted mana cost of that permanent is 0.

**Comment by emerald000** [comment]
The **converted** mana cost of a face down card is the converted mana cost of the front face. But its mana cost is still undefined and will not count for devotion.
