### ISSUE TITLE
Blood sun and enters the battefield effects

### ISSUE THREAD

**Issue by Origraena** [magefree/mage#4440]
Currently, if blood sun is on the battlefield, and a player puts a gemstone mine, it enters with counters, however, it should not.

**Comment by jeffwadsworth** [comment]
The rule change from Sept 2017 affects more than just Blood Sun.  It has not been implemented yet.

https://magic.wizards.com/en/articles/archive/news/ixalan-comprehensive-rules-changes-2017-09-28

**Comment by GAMEster52** [comment]
yeah i saw the same today. a land entered the battlefield tapped with blood moon on the battlefield. this needs an update.

**Comment by nstephenh** [comment]
Any progress on this? It does seem like a lot of work, but its important to the game.

**Comment by Zerrisx** [comment]
Duplicate of #4202
