### ISSUE TITLE
Slaughter the strong still bugged

### ISSUE THREAD

**Issue by Aflacducky** [magefree/mage#4453]
Changes done in Release 1.4.27V0 (2018-01-13) did not seem to fix the inability of opponents of the player casting Slaughter The Strong as players still cannot select any creatures right now (confirmed that I am using 1.4.27V0).

Is this possibly an interface issue because interface seems to ask player casting Slaughter The Strong to select creatures twice, e.g. when spell goes on stack:

1) Active player asked to select creatures
2) Active player clicks on "DONE"
3) Active player clicks on "END SELECTION"
4) After some delay (where it is assumed opponent is selecting creatures), (1) above repeats.
5) After selecting "DONE" again, then spell resolves and all opponent's creatures are sacrificed.

Please note that when I went through each step with an opponent after rollback, opp mentioned that they could not see the power count of creatures selected - they couldn't see any parentheses or the power count that's normally inside.

Thanks.

**Comment by JayDi85** [comment]
Slaughter the strong had bug with creature selection -- only card controller was able to select (controller try to select for ALL players instead for yourself). See #4436.

It was fixed and will be available on next release.
