### ISSUE TITLE
AI: comp use boost cards on defend stage without attackers

### ISSUE THREAD

**Issue by JayDi85** [magefree/mage#4458]
Computer cast boost card (+3/+3 by [Crash the Ramparts](https://scryfall.com/card/xln/182)) with no threat on defend stage (no one attacks it):

```
5:27: Turn 6 JayDi (20 - 20)
5:27: JayDi draws a card
5:28: JayDi sacrificed Treasure [ee9]
5:28: JayDi casts Headstrong Brute [185]
5:28: JayDi puts Headstrong Brute [185] from stack onto the Battlefield
5:28: JayDi attacks with 0 creatures
5:28: computer casts Crash the Ramparts [872] targeting Drover of the Mighty [c6a] 
5:28: computer puts Crash the Ramparts [872] from stack into his or her graveyard 
```

**Comment by jeffwadsworth** [comment]
Right now, the AI checks only what it can do in the current step.  There is no look-ahead.

**Comment by JayDi85** [comment]
@jeffwadsworth it's not a look-ahead action... Player already skipped attack phase, no one attacking... It's time to skip computer defend phase -- BUT it's use boost. There is must be check like: when defend phase and attack count is zero and card is boost then do not cast that card.

**Comment by Zerrisx** [comment]
Duplicate of #6839
