### ISSUE TITLE
[RIX] "As ~ etb" implemented like "When ~ etb" on some cards

### ISSUE THREAD

**Issue by MajorLazar** [magefree/mage#4460]
https://github.com/magefree/mage/blob/master/Mage.Sets/src/mage/cards/p/ProteanRaider.java
https://github.com/magefree/mage/blob/master/Mage.Sets/src/mage/cards/s/SwaggeringCorsair.java

I noticed on those cards (and probably some more) that "as ~ enters the battlefield" abilities are implemented like "enters the battlefield" triggers.

**Comment by LevelX2** [comment]
Fixed
