### ISSUE TITLE
Add logs cleanup

### ISSUE THREAD

**Issue by JayDi85** [magefree/mage#4462]
1000 MB logs size... Need to auto-cleanup logs (e.g. every day).

![shot_180129_121653](https://user-images.githubusercontent.com/8344157/35500020-4f2a3f2e-04ee-11e8-8b8d-ab51cc2788ba.png)

**Comment by sentania** [comment]
+1 been play for about a week and mine is 20 GB!

**Comment by sentania** [comment]
![image](https://user-images.githubusercontent.com/2688043/45455489-e5c01100-b6ac-11e8-9bfe-27cd4db3b0e5.png)

**Comment by JayDi85** [comment]
Logs clean up and rotate implemented by logs4j settings, see `\xmage\mage-server\config\log4j.properties` for example and docs.
