### ISSUE TITLE
(bug) Jace's Sentinel does not become unblockable when Jace is here.

### ISSUE THREAD

**Issue by Ncrpts** [magefree/mage#4468]
[http://gatherer.wizards.com/Pages/Card/Discussion.aspx?multiverseid=435444](http://gatherer.wizards.com/Pages/Card/Discussion.aspx?multiverseid=435444)

He do get the +1/+0 just fine, but he is still being blocked while he shouldn't.

tried with Jace, Ingenious Mind-Mage in play.

**Comment by Ncrpts** [comment]
![issuejacesentinel](https://user-images.githubusercontent.com/2747052/35591392-17299274-060a-11e8-8262-257ec040f01f.png)

attached is a screenshot of this happening,

i looked the code around but i couldn't pinpoint the issue, everything should work and when the card is hovered it clearly state "and can't be blocked." from JacesSentinel.java, could this be because my oponnent is a bot and he bypass some rules when making decisions ?

**Comment by JayDi85** [comment]
Fixed via 60eb9ff5cebee0efc0b59aa87b442a59c0116662
