### ISSUE TITLE
Cards not loaded - blue

### ISSUE THREAD

**Issue by Aszhular** [magefree/mage#4469]
I changed phasing and priority preferences a bit and then this happened:

![image](https://user-images.githubusercontent.com/35967758/35586767-b6126e22-05f3-11e8-9f55-b380fcf52f79.png)

and I can't find a way to undo it, how can I fix it?

**Comment by Ncrpts** [comment]
did you change the image folders? if you did you might have to manually move the images to the new folder, or alternatively (re)download them. default image folder is "xmage\mage-client\plugins\images" i think.

**Comment by JayDi85** [comment]
Checkout images folder in Preferences->Images tab. If you change that settings then you need to restart app for new settings apply.

**Comment by spjspj** [comment]
It's telling you what directory it's expecting to find your .zip files in.  I would suggest changing them to a dedicated directory (such as c:\xmage_images\) in your preferences (aka turn off the 'Use default location to save images' check box under Preferences -> Images).  Then move all your .zip files to that new directory.
