### ISSUE TITLE
Permanents of disconnected players are not removed and can freeze the game

### ISSUE THREAD

**Issue by derlhurgoyf** [magefree/mage#4472]
In a multiplayer game, if a player leaves through timeout or by force-close of xmage, his permanents aren't entirely removed from the battlefield. If one of these permanents is his commander and someone plays a boardwipe the game will get stuck indefinitely while it's waiting for the dead player to decide if his commander should go to the command zone.
Also global effects like Bane of Progress count dead player's permanents.

**Comment by derlhurgoyf** [comment]
In this context: a player had omen machine in play and then conceded. Visually all of his permanents disappeared. However nobody was able to draw a card.

**Comment by JayDi85** [comment]
Same as #4262

**Comment by derlhurgoyf** [comment]
duplicate bug.

**Comment by derlhurgoyf** [comment]
Unfortunately this bug was not fixed together with #4262 .
Please find attached a gamelog of a Multiplayer 4-way FFA, where one player played a Extraplanar Lens and later dropped/conceded. However his Lens was still granting the mana amplification effect.
[game-bc97eca3-60a3-4188-ac99-be106c249c83.json.zip](https://github.com/magefree/mage/files/1805511/game-bc97eca3-60a3-4188-ac99-be106c249c83.json.zip)

**Comment by derlhurgoyf** [comment]
[game-538de954-f170-45cd-8400-c275b8012838.json.zip](https://github.com/magefree/mage/files/1940883/game-538de954-f170-45cd-8400-c275b8012838.json.zip)
In this game an opponent with Brisela, Voice of Nightmares died, but Brisela's effect wouldn't let me cast spells.

Also Assault suite prevented an opponent from sac-ing a creature even though he also had other creatures that could be sacrificed.

**Comment by derlhurgoyf** [comment]
A new case where a player had his commander in game (Azusa) and then disconnected. Then after a few turns one player played a Decree of Pain and the game waited for the disconnected played to decide what to do with his commander. After 5 minutes he was conceded again, but game was still stuck.
[game-a30fba11-61e0-41ec-866e-b144c61469c4.json.zip](https://github.com/magefree/mage/files/2454306/game-a30fba11-61e0-41ec-866e-b144c61469c4.json.zip)

**Comment by JayDi85** [comment]
No more actual. Current version removes all permanents correctly.

**Comment by Zerrisx** [comment]
> 
> 
> No more actual. Current version removes all permanents correctly.

Did this also address #1929, or is that still an issue?

**Comment by JayDi85** [comment]
@Zerrisx I closed #1929 cause control effect fixed by levelx2 month ago (see 1e36b394345709ea31cde9c339471e5780de3422). Problem: xmage "forget" real controller and can't correctly process it (e.g. after player quit). It must works fine in current version.
