### ISSUE TITLE
Unable to connect to server. Server likely offline

### ISSUE THREAD

**Issue by Tankbull** [magefree/mage#4474]
It worked fine until a few days ago, then i couldn't connect anymore while i know it should be working since i played it at a friends house.

Yesterday i tried connecting to an american server instead of the one for europe, had to register for that server and it worked. Today nothing is working, it does all the normal stuff but cannot connect.  I have the latest version, forced an update, latest java,... I even tried reinstalling it, dissabled firewall and viruskiller, nothing changes...  

Please help if you have the answer,
much appreciated.

**Comment by JayDi85** [comment]
Current servers are down (offline). Try it later.

**Comment by LevelX2** [comment]
xmage.de restarted.
