### ISSUE TITLE
Greenwarden of Murasa

### ISSUE THREAD

**Issue by HR19** [magefree/mage#4475]
My opponent's Greenwarden of Murasa died, and then I exiled it with Mimic Vat before its 'dies' ability resolved.  Because it was no longer in the graveyard, its ability should not allow you to get back the targeted card, but my opponent was able to retrieve said card.

**Comment by rsromanowski** [comment]
Cards with similiar affect: Academy Rector, Gamekeeper, Iname as One, Iname, Life Aspect, Rooting Kavu.

There seems to be some incosistency in how these were implemented. But stealing a line from Rooting Kavu. Ability should resemble something like:

`this.addAbility(new DiesTriggeredAbility(new DoIfCostPaid(new RootingKavuEffect(), new ExileSourceFromGraveCost())));`
