### ISSUE TITLE
Armageddon Clock BUG

### ISSUE THREAD

**Issue by EllNubNub** [magefree/mage#4480]
Armageddon Clock does trigger on the controllers upkeep and the game logs show that a counter is put on the clock, however no counters are actually placed on the clock. then the next trigger for damage should happen on the upkeep too, but instead happens on draw phase and because there actually was no counter placed on it, it deals no damage but the game still logs it as having done so.
LOG:
11:24 PM: Ability triggers: Armageddon Clock [456] - At the beginning of your upkeep, put a doom counter on Armageddon Clock [456].
11:25 PM: EllNubNub puts 1 doom counter on Armageddon Clock [456]
11:25 PM: EllNubNub draws a card
11:25 PM: Ability triggers: Armageddon Clock [456] - At the beginning of your draw step, Armageddon Clock [456] deals 1 damage to each player.

**Comment by LevelX2** [comment]
Fixed that the counter was not added and the incorrect rule text of tool tip text.
That the second trigger takes place in the draw phase is correct.
