### ISSUE TITLE
Ponder putting cards on the bottom

### ISSUE THREAD

**Issue by dovefromhell** [magefree/mage#4484]
Ponder asks you to put on the bottom rather than the top

**Comment by JayDi85** [comment]
It was fixed in #4481 and will be available on next release (or next server's update).

**Comment by jeffwadsworth** [comment]
Also, FYI, if you use this bug forum, please learn to use the search tool.  It is exceptionally useful.

**Comment by JayDi85** [comment]
Ponder is very popular card. I prefer not to close that issue until next release (people must see it in active list while search).
