### ISSUE TITLE
AI Won't Alpha-Strike Through a Large Blocker

### ISSUE THREAD

**Issue by rampaging-poet** [magefree/mage#4486]
Currently the AI won't attack with creatures that could die without trading when they are blocked.  However, it seems to ignore the fact that most creatures can only block one other creature.  As a result a single large blocker can stall the AI entirely no matter how many smaller attackers they have.

If nothing else the AI should be able to alpha-strike for lethal if it has enough attackers to do so.  For example if the human player has a eight life and single Glint-Nest Crane while the AI has nine or more 1/1 Servo tokens, the AI should attack with all of its servos to try and close out the game.

**Comment by jeffwadsworth** [comment]
Being worked on.

**Comment by JayDi85** [comment]
Fixed via ae7623e118b0a629065111b0461788586ec0cb18
