### ISSUE TITLE
manamorphose, lions eye diamond window error

### ISSUE THREAD

**Issue by GAMEster52** [magefree/mage#4487]
i have and had several times problems when selecting the mana color for these spells. if there is an other window open (for example graveyard or act on impulse) the selecting window is behind these others and i can select nothing. ending up to just quit the program, chat is not working, nothing...

the last time the problem was that bigger description that is coming up automatically when the cursor moves over a card for example. there was one of these that didnt got away in front of my lions eye diamond.

would be nice if that could be fixed. thanks

**Comment by JayDi85** [comment]
Can confirm that:

![shot_180206_110055](https://user-images.githubusercontent.com/8344157/35845718-0f7470a8-0b2d-11e8-90ec-7e7a499ea215.png)

**Comment by JayDi85** [comment]
Works fine with last 34v0 release
