### ISSUE TITLE
Grim Flayer putting cards in the bottom

### ISSUE THREAD

**Issue by jpargonaut** [magefree/mage#4491]
When doing dmg with grim flayer, instead of putting the card on the top, they go to the bottom

**Comment by jeffwadsworth** [comment]
https://github.com/magefree/mage/commit/d1c5fe3f0fbac0c2624c0fd808dcbf281d299c44
This should fix that.

**Comment by jeffwadsworth** [comment]
This was fixed with https://github.com/magefree/mage/commit/d1c5fe3f0fbac0c2624c0fd808dcbf281d299c44
