### ISSUE TITLE
Split cards can't be cast from Exile

### ISSUE THREAD

**Issue by jeffwadsworth** [magefree/mage#4493]
Split cards like Claim//Fame etc,  can't be played/cast from the Exile Zone.

**Comment by Zwork101** [comment]
This isn't a bug, you can't cast those cards in exile.

**Comment by LevelX2** [comment]
For sure this issue means in combination with cards like 
**Etali, Primal Storm**
Whenever Etali, Primal Storm attacks, exile the top card of each player's library, then you may cast any number of nonland cards exiled this way without paying their mana costs.

**Comment by Zwork101** [comment]
Ah, I see
