### ISSUE TITLE
Curse of the swine BUG

### ISSUE THREAD

**Issue by EllNubNub** [magefree/mage#4495]
tried to cast it with multiple legal targets on board from multiple players and a message told me there were no valid targets. Similar to the previous simic manipulator bug that was reported last patch.

**Comment by AMWJ** [comment]
Simic Manipulator Bug: https://github.com/magefree/mage/issues/4479

**Comment by LevelX2** [comment]
I can't reproduce this problem. The message you mentioned appears, if the game can't find enough valid targets you defined for X.
Which value did you set for X?

So maybe there were creatures with protection or hexproof or players out of range if range was set to 1.

**Comment by EllNubNub** [comment]
it did not matter what value i defined for x, it simply would not cast.

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.
