### ISSUE TITLE
Ammit Eternal Afflict Trigger

### ISSUE THREAD

**Issue by Gigisant** [magefree/mage#4499]
As the title suggests, it seems Ammit Eternal's Afflict ability does not trigger on blocking (or perhaps double blocking)  I had it happen twice in two separate matches, both of which where it was double blocked. I did not capture the message log so I apologize. Just a note to check it out.

**Comment by LevelX2** [comment]
I was not able to reproduce that problem neither with single or double blocking.
Any more detail information what could cause the problem?

**Comment by Zerrisx** [comment]
Also cannot reproduce; need more detail.

**Comment by JayDi85** [comment]
Added test by 126898f70a30a67ae0b41f856093813b2ed93809, all works fine.
