### ISSUE TITLE
Bugs: Cast from YOUR hand; Arcane Adaptation; The Big Idea; Creature Types

### ISSUE THREAD

**Issue by Iwasrunningoutofnamesatthispoint** [magefree/mage#4501]
Here are a couple of bugs I have whitnessed:

 * [x] Sunbirds Invocation: It triggers when I cast from ANYONES hand, in example if I cast something with Sen Triplets or similar cards.

 * [x] Arcane Adaptation: Tokens that are created while Arcane Adaptation is on the field will keep the extra creature type after the Adaptation leaves the field.

 * [x] The Big Idea: His roll two die replacement effect does end at turns, but it should carry over untill it is used. (Thank you for adding it spjspj ;)

 * [x] Creature Types selection sheet: It is missing the UN- creature types like Brainiac etc

 * [x] Furthermore sometimes the skip buttons skip one done too far - i am not sure what caused this nor if it got fixed in the last two updates.

Thank you for fixing in advance :)

**Comment by jeffwadsworth** [comment]
I confirmed the Arcane Adaptation bug with tokens.

**Comment by JayDi85** [comment]
All fixed
