### ISSUE TITLE
RIX Tokens :: Elementals named the same

### ISSUE THREAD

**Issue by FastTadpole** [magefree/mage#4504]
Same path and filename for both the Tilonalli's Summoner Elemental Token and the Rekindling Phoenix Elemental Token.
I have the following in the TOK.zip /RIX folder
Elemental 1.full.jpg
Elemental 2.full.jpg

and the Elemental 1.full.jpg image is showing for both instances.

**Comment by LevelX2** [comment]
Fixed with c9603d1.
