### ISSUE TITLE
Add a No Spectators option for games

### ISSUE THREAD

**Issue by spjspj** [magefree/mage#4507]
Currently there is a no spectator option available for new tournaments.  Need a similar option for new games.

**Comment by Dahny** [comment]
Isn't this already added to the game?

![image](https://user-images.githubusercontent.com/5946394/37658560-1f834dd8-2c4e-11e8-8929-e2abfcc448b9.png)

**Comment by spjspj** [comment]
Yes, I did add it in for release 1.4.28v0 (or 1) ;)
