### ISSUE TITLE
Card Viewer - Token with "summoning sickness" symbol

### ISSUE THREAD

**Issue by LevelX2** [magefree/mage#4514]
If you show the tokens of a set and the fallback to plain image based rendering isn't activated, all the tokens are shown with the summoning sickness overlay image.

Also if you switch from 3x3 to 4x4 or vice versa, the current mode of showing tokens is not handled correctly.

![viewer](https://user-images.githubusercontent.com/2066790/36094181-832e030a-0fed-11e8-85a8-562199b41220.jpg)

**Comment by JayDi85** [comment]
Close via #4719
