### ISSUE TITLE
Consecrated Sphinx should not trigger when destroyed by Decree of Pain

### ISSUE THREAD

**Issue by derlhurgoyf** [magefree/mage#4516]
Player 1 has Consecrated Sphinx, Player 2 casts Decree of Pain. Sphinx triggers of the card draw, but shouldn't

**Comment by jeffwadsworth** [comment]
Why do you think that is the case?  Can you post a ruling on that?

**Comment by derlhurgoyf** [comment]
literally first hit on google: http://www.mtgthesource.com/forums/showthread.php?20367-Consecrated-sphinx-and-Decree-of-pain
