### ISSUE TITLE
Bugs: Kozileks return, Snickering Squirrel, Rollbacks, Player leaving the Match

### ISSUE THREAD

**Issue by Iwasrunningoutofnamesatthispoint** [magefree/mage#4517]
Some more bugs I came across last week:

- [x] Kozileks Return ----
Edit: That was a mistake on my side, 

- [x] Snickering Squirrel cant be activated, or at least I havent figured out how to use it.

- [x] Rollbacks dont work correct at all. Token made during the turn dont disappear, effects like "until end of turn buffs" stay, cards drawn stay drawn. **LevelX2: this works with rollback so far.**

- [ ] If a player leaves a FFA commander Table his permanents are still on the field, which causes a lot of issues like bordwhipes triggering the commander question and freezing the game.

**Comment by jeffwadsworth** [comment]
If you have logs of the games that would help.  The Snickering Squirrel worked fine for me.  If a die is rolled, you get a prompt to tap it, etc.  Kozilek's Return code looks okay to me.  Roll backs should work better in the next release.  The token issue was fixed.

**Comment by Iwasrunningoutofnamesatthispoint** [comment]
Sure, if you tell me how to add a game log I will do so.
And I was wrong about the return, seems like something ingame must have changed its color.

**Comment by LevelX2** [comment]
Snickering Squirrel works. Text improved by 832f1ebcd728ec9c7cb9a529bd41ca0513321104.

**Comment by Zerrisx** [comment]
Remaining issue is a duplicate of #4472
