### ISSUE TITLE
Server memory usage - object growing (memory leaks)

### ISSUE THREAD

**Issue by LevelX2** [magefree/mage#4520]
I took a 30 min JFR snapshopt this morning before the xmage.de server reset.
As I look at the object instance increase during this 30 minutes, I guess we get some clear hints, for what mage objects, the java memory freeing does not work. Probably because some references to the objects are not removed.

![memory](https://user-images.githubusercontent.com/2066790/36197964-a3fcc81c-1175-11e8-8dd2-cf00f2da5e61.jpg)

At least the number of this objects (maybe only Mode as at top of the hierachy)  do more increase than they should.  Over 30 minutes the increasing/decreasing should be more balanced.

mage.abilities.Mode
mage.target.Targets
mage.abilities.effects.Effects
mage.counters.Counters
mage.target.targetpointer.FirstTargetPointer
mage.abilities.effects.EntersBattlefieldEffect

Or what do you think?
Any good ideas how to check for such memory leaks?

**Comment by JayDi85** [comment]
GameStates in rollbacks data during active games?

**Comment by LevelX2** [comment]
> GameStates in rollbacks data during active games?

But as the game ends, the states should no longer be referenced. And over 30 minutes the ending and staring games should balance out the increase/decrease of classes.

**Comment by JayDi85** [comment]
It's still have memory leaks. No links between AI freezes and memory. Some stats and comments from beta server:

![shot_190112_170152](https://user-images.githubusercontent.com/8344157/51073560-1b412f00-168c-11e9-8c48-fdd0636a7445.png)

**Comment by JayDi85** [comment]
Game tables don't removes from server. See #6141

That's tables data contains real players list with all inner data:
![shot_200104_181604](https://user-images.githubusercontent.com/8344157/71766931-0e61bf00-2f1f-11ea-9368-ac9fb5195adc.png)

That's data can have ref to game state's data -- e.g. java's garbage collector (GC) can't remove it from memory after game finished. I thinks that's the main reason (if you remove tables from server then all other data will be dirty for GC and will be removed too).

PlayerImpl contains real objects from GameState:
![shot_200104_181731](https://user-images.githubusercontent.com/8344157/71766891-9eebcf80-2f1e-11ea-9597-e1de29b27cc5.png)

ComputerPlayer contains real objects from GameState:
![shot_200104_181310](https://user-images.githubusercontent.com/8344157/71766899-b1660900-2f1e-11ea-89ef-38e84f0bfae5.png)

**Comment by JayDi85** [comment]
Latest topic in #11285, current can be closed
