### ISSUE TITLE
Card pile to choose is unclickable.

### ISSUE THREAD

**Issue by tamaroth** [magefree/mage#4523]
Here's the situation:

You cast 'Fact or Fiction', you are shown a window with cards revealed by Fact or Fiction, the game is asking to select an opponent. Before you select an opponent you resize the window. You then select an opponent who separates the cards in two piles and a new window is shown. The shown window is ACTIVE window but is UNDER the Fact or Fiction window, which is now inactive. The active window can be only dragged by title bar, which is under an inactive window. The game essentially hangs as you cannot do anything.

Here's an example of how it looks like:
https://imgur.com/eUP3zXe

edit: you can press space to choose a pile, but you don't know which cards are in which pile anyhow...

**Comment by JayDi85** [comment]
Same as #4487

**Comment by JayDi85** [comment]
Must works fine with last 34v0 release
