### ISSUE TITLE
Some Kaladesh Inventions images are not being downloaded properly.

### ISSUE THREAD

**Issue by ackzf** [magefree/mage#4526]
Wrong Images: 
Aether Vial - Is the Iconic Masters version.
Chromatic Lantern - Is the Commander 2016 version.
Lightning Greaves - Is the Commander 2017 version.
Oblivion Stone - Is the Iconic Masters version.
Ornithopter - Is the Aether Revolt version.
Paradox Engine - Is the Aether Revolt version.
Planar Bridge - Is the Aether Revolt version.
Sol Ring - Is the Commander 2017 version.
Solemn Simulacrum - Is the Commander 2016 version.

Furthermore, it appears that instead of using the proper versions, the application is grabbing the latest version of the card image from gatherer.

**Comment by LevelX2** [comment]
Which image source did you use?

**Comment by ackzf** [comment]
wizards,com

**Comment by JayDi85** [comment]
Are you sure it's a download problem? If you import deck then xmage use latest cards -- same for games.

**Comment by ackzf** [comment]
I redownloaded it several times after deleting the archive. The image files themselves are wrong.

**Comment by JayDi85** [comment]
XMage do not have "Kaladesh Inventions" set. "MPS" used for masterpiece series.

![shot_180216_154254](https://user-images.githubusercontent.com/8344157/36306203-2c33308e-1330-11e8-8bdd-50ffdad98e81.png)

**Comment by ackzf** [comment]
The set's full name is Masterpiece Series: Kaladesh Inventions.

https://magic.wizards.com/en/articles/archive/feature/masterpiece-series-kaladesh-inventions-2016-09-12

It appears the other sets of the Masterpiece Series, Battle for Zendikar, is "EXP", whereas Amonkhet Invocations is "MPS-AKH".

In any case MPS-AKH (Amonkhet Invocations) is missing images period, Modern Masters 2017 (MM3) Damnation downloaded  the Amonkhet Invocations versions (again probably because it's the latest version), and some of its other cards are also wrong.

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.
