### ISSUE TITLE
Update version error.

### ISSUE THREAD

**Issue by ackzf** [magefree/mage#4528]
The current update json at http://xmage.de/xmage/config.json is still listing the version number as 1.4.27V4 (2018-02-14).

Consequently xmage cannot update from 1.4.27V4 (2018-02-14) to 1.4.27V4b (2018-02-15) using the stable branch.

Workaround: Custom branch with a modified local json.

**Comment by LevelX2** [comment]
You can simply force an update by the update button.
I didn#t change the json becaus no client update was needed and most of the people do not use the local server.
