### ISSUE TITLE
AI uses abilities that should be removed by continuous effects.

### ISSUE THREAD

**Issue by ArmyJM** [magefree/mage#4529]
Some spell effects that effect the use of mana abilities on lands are inoperative. Example Spreading Seas transforms enchanted land into an island and it loses all other abilities. The AI does not recognize this and is able to use all abilities of the enchanted land including all previous mana abilities and activated abilities, in addition to now also being an island due to Spreading Sea's effect.

**Comment by LevelX2** [comment]
I was not able to reproduce that problem. I tested with Kher Keep and Spreading Seas.

Which land card for example did you enchant that the AI used after that?

**Comment by Zerrisx** [comment]
Cannot reproduce.  The AI loves to use land abilities as often as possible, yet takes no actions on this board.
![image](https://user-images.githubusercontent.com/59861365/88756012-07530600-d128-11ea-936d-b4559458ad97.png)
