### ISSUE TITLE
Play sound if action is required while it's not your turn on F9/F11

### ISSUE THREAD

**Issue by derlhurgoyf** [magefree/mage#4543]
Play a blip/ding/whatever sound if you're required to make a selection or click ok while you're skipping to your turn.
This should speed up especially multiplayer matches to become aware when you're holding up the game even though you skipped to your turn.

Idea from reddit https://www.reddit.com/r/XMage/comments/7yqxk0/feature_request_add_a_sound_when_an_action_is/

**Comment by dperegolise** [comment]
My proposed change: https://github.com/magefree/mage/pull/6558

**Comment by Zerrisx** [comment]
Closing as fixed by #6558
