### ISSUE TITLE
Primal Wellspring wrong interaction with Caged Sun

### ISSUE THREAD

**Issue by derlhurgoyf** [magefree/mage#4544]
Player A had a Primal Wellspring (transformed from Primal Amulet) and Caged Sun in play on red and casts Incinerate. Xmage copies it twice, as if the additional mana from the Caged Sun had the same copying effect as the original from the wellspring. Correct would be original Incinerate plus one copy for a total of 6 damage.

Notice: If Mana Reflection was in play instead the above would have been correct (two copies).

Reference: https://www.reddit.com/r/magicTCG/comments/7za3uj/rules_question_primal_wellspring_caged_sun_double/

**Comment by jeffwadsworth** [comment]
Yes, Caged Sun is not a replacement effect due to the lack of the word "instead".

**Comment by derlhurgoyf** [comment]
The actual boardstate was a bit more complex. I also had a Thespian's Stage in play copying the wellspring.
but I'm 100% sure I ended up with more than two copies of the spell. Maybe the stage was adding a copy trigger to the original?
