### ISSUE TITLE
Can't launch client (UnknownHostException)

### ISSUE THREAD

**Issue by EthanKairos** [magefree/mage#4558]
Currently unable to launch the client at all. Console throws "UnknownHostException", and it stops immediately after output.

OS is Win10 x64.

![error](https://i.imgur.com/zOiaOrn.png)

**Comment by JayDi85** [comment]
Check your internet connection -- that's the problem. #4461 can help with auto-connection disable.

**Comment by EthanKairos** [comment]
Upon checking in regedit, I don't seem to have any registry values at all in the specified path. Creating the autoConnect string and setting it to false doesn't seem to work either.

Also, my internet connection seems to be okay. I'm able to play other online games just fine, and browsing on this PC is smooth.

**Comment by JayDi85** [comment]
search -> cmd -> run...

Enter:
 * `ping localhost`
 * `ping 127.0.0.1`

All commands must be OK. If not then open `..\Windows\System32\drivers\etc\hosts` file and add line at the end:
* `127.0.0.1 localhost`

**Comment by EthanKairos** [comment]
Both ping commands work completely.

![ping](https://i.imgur.com/eC0Uq9m.png)

I tried adding the line to the hosts file anyway, and it doesn't seem to be making a difference.

**Comment by JayDi85** [comment]
You have problem with PC name:
![shot_180301_133203](https://user-images.githubusercontent.com/8344157/36837147-f6f3fdc0-1d54-11e8-83e1-9c09b442932d.png)

Go to search -> system -> run system control panel -> find pc name settings and change it to normal English letters like "MYPC". Restart after changes:
![shot_180301_133527](https://user-images.githubusercontent.com/8344157/36837315-73e9977c-1d55-11e8-93cc-b09f9b59b658.png)

If not help, then try ping commands and report again like last comment.

**Comment by EthanKairos** [comment]
That fixed it. I didn't even know it was possible for the PC name to affect connection.

Thanks!
