### ISSUE TITLE
Extra useless splice prompt for flashback arcane spells.

### ISSUE THREAD

**Issue by ackzf** [magefree/mage#4560]
Reproduction Steps:
1. Have an arcane card in graveyard. (e.g. Lava Spike)
2. Have a card with splice onto arcane ability in your hand. (e.g. Desperate Ritual)
3. Give the arcane card in graveyard with flashback (e.g. with Snapcaster Mage)
4. Flashback the arcane card.

Expected Results: You're prompted to decide whether to splice onto arcane.
Actual Result: You're prompted to decide whether to splice onto arcane. That decision is then ignored and you receive a second prompt to decide whether to splice. If you've clicked yes the first time you will reveal the card you're splicing, but then clicking no in the second prompt results in no splice occuring.

**Comment by LevelX2** [comment]
Probably solved with 1.4.28V0 (redesign of flasback)

**Comment by ackzf** [comment]
The prompt no longer appears. Closing
