### ISSUE TITLE
Alhammarret, High Arbiter's ability doesn't work.

### ISSUE THREAD

**Issue by ackzf** [magefree/mage#4561]
Despite naming the damnation in my hand, i was able to cast it next turn without issue.

Logs:
4:46 PM: 22222 draws a card
4:46 PM: 22222 casts Alhammarret, High Arbiter [804]
4:46 PM: 11111 reveals Damnation, Verdant Catacombs, Bloodstained Mire
4:46 PM: The choosen card name is [Damnation]
4:46 PM: 22222 puts Alhammarret, High Arbiter [804] from stack onto the Battlefield
4:46 PM: 22222 puts Island [7ac] from hand onto the Battlefield
4:46 PM: 22222 plays Island [7ac]
4:46 PM: 22222 attacks with 0 creatures
4:46 PM: Turn 14 11111 (20 - 17)
4:46 PM: 11111 draws a card
4:46 PM: 11111 casts Damnation [653]
4:46 PM: Silburlind Snapper [dd6] died
4:46 PM: Alhammarret, High Arbiter [804] died
4:46 PM: 11111 puts Damnation [653] from stack into his or her graveyard

**Comment by LevelX2** [comment]
4:46 PM: Alhammarret, High Arbiter [804] died
Your opponents can't cast spells with the chosen name (**as long as this creature is on the battlefield**).

If Alhammarret, High Arbiter is no longer on the battlefield, Damnation can be cast again!
