### ISSUE TITLE
Undead Alchemist ability bugged

### ISSUE THREAD

**Issue by ShatteredSphere** [magefree/mage#4563]
I activated an Elixir of Immortality in response to several Undead Alchemist triggers, and after the cards had been shuffled into my library they were pulled out and exiled when they should have ceased to exist as far as the triggers knew.  Bolded lines below should not have occurred.

4:42 AM: Ability triggers: Undead Alchemist [2bb] - Whenever a creature card is put into an opponent's graveyard from his or her library, exile that card and create a 2/2 black Zombie creature token.
4:42 AM: Ability triggers: Undead Alchemist [2bb] - Whenever a creature card is put into an opponent's graveyard from his or her library, exile that card and create a 2/2 black Zombie creature token.
4:42 AM: Ability triggers: Undead Alchemist [2bb] - Whenever a creature card is put into an opponent's graveyard from his or her library, exile that card and create a 2/2 black Zombie creature token.
4:42 AM: Ability triggers: Undead Alchemist [2bb] - Whenever a creature card is put into an opponent's graveyard from his or her library, exile that card and create a 2/2 black Zombie creature token.
4:42 AM: me activates: You gain 5 life. Shuffle Elixir of Immortality [af1] and your graveyard into your library. from Elixir of Immortality [af1]
4:42 AM: me gains 5 life
4:42 AM: me puts Elixir of Immortality [af1] from battlefield to the top of his or her library
4:42 AM: me puts Adaptive Automaton [ede] from graveyard to the top of his or her library
4:42 AM: me puts Reflecting Pool [d58] from graveyard to the top of his or her library
4:42 AM: me puts Swamp [f19] from graveyard to the top of his or her library
4:42 AM: me puts Cavern of Souls [79b] from graveyard to the top of his or her library
4:42 AM: me puts Arcane Adaptation [d09] from graveyard to the top of his or her library
4:42 AM: me puts Hallowed Fountain [855] from graveyard to the top of his or her library
4:42 AM: me puts Anguished Unmaking [e9f] from graveyard to the top of his or her library
4:42 AM: me puts Unclaimed Territory [0aa] from graveyard to the top of his or her library
4:42 AM: me puts Fetid Pools [547] from graveyard to the top of his or her library
4:42 AM: me puts Command Tower [ed6] from graveyard to the top of his or her library
4:42 AM: me puts Temple of Deceit [245] from graveyard to the top of his or her library
4:42 AM: me puts Thought Vessel [e65] from graveyard to the top of his or her library
4:42 AM: me puts Aphetto Grifter [0f4] from graveyard to the top of his or her library
4:42 AM: me puts Ertai, Wizard Adept [18b] from graveyard to the top of his or her library
4:42 AM: me puts Irrigated Farmland [404] from graveyard to the top of his or her library
4:42 AM: me puts Imagecrafter [14d] from graveyard to the top of his or her library
4:42 AM: me puts Cyclonic Rift [49d] from graveyard to the top of his or her library
4:42 AM: me's library is shuffled
**4:43 AM: opponent moves Imagecrafter [14d] from library to the exile zone**
4:43 AM: opponent creates a Zombie [9d6] token
**4:43 AM: opponent moves Ertai, Wizard Adept [18b] from library to the exile zone**
4:43 AM: opponent creates a Zombie [8ac] token
**4:43 AM: opponent moves Aphetto Grifter [0f4] from library to the exile zone**
4:43 AM: opponent creates a Zombie [8f4] token
**4:43 AM: opponent moves Adaptive Automaton [ede] from library to the exile zone**
4:43 AM: opponent creates a Zombie [132] token

**Comment by Zerrisx** [comment]
Fixed by f489671
