### ISSUE TITLE
No Mercy kills a creature that changed zones

### ISSUE THREAD

**Issue by Zzooouhh** [magefree/mage#4574]
Probably a simple zoneChangeCounter tracking issue. I attacked a person that had a No Mercy on the battlefield with a Puppeteer Clique (with no -1/-1 counters). When the No Mercy trigger went on the stack, I sacrificed Clique to High Market, and it returned with a -1/-1 counter. Then the No mercy trigger resolves, and kills the newly reborn Clique.

**Comment by Zzooouhh** [comment]
So it appears that this issue will probably encompass many more effects than just No Mercy. I've tried equipping Puppeteer Clique with Hot Soup and dealing lethal damage to it; if you put the Hot Soup trigger before the Clique trigger, Clique will ETB and die when the trigger resolves.

**Comment by LevelX2** [comment]
This commit should fix the problem. Can you check?

**Comment by Zzooouhh** [comment]
Yes, this works well. Thank you.
