### ISSUE TITLE
Animate Dead and Dance of the Dead get destroyed on rollback

### ISSUE THREAD

**Issue by Zzooouhh** [magefree/mage#4578]
Very simple to reproduce - animate a creature with Animate Dead, then pass to next turn. During the next turn, roll back to the beginning of the turn. Animate Dead is destroyed and its LTB ability gets triggered to sacrifice the enchanted creature. Other forms of rollback, such as when undoing attackers, also cause Animate Dead to get destroyed as a state-based action. It seems that rolling back causes Animate Dead to lose track of the creature it's supposed to enchant somehow.

Dance of the Dead has the exact same issue. Notably, another other similar card, Necromancy, doesn't suffer from this however - probably owing to the fact that it isn't an Aura by default, but a global Enchantment.

**Comment by Zzooouhh** [comment]
Another ridiculous Animate Dead related issue - I've animated an opponent's Savage Ventmaw and killed him with it. I've rollbacked to the start of the turn, and I immediately won the game.

**Comment by LevelX2** [comment]
I can't reproduce the problem.

I guess it was fixed with this commt: https://github.com/magefree/mage/commit/fe2eec6553a7862094efcda9d7968129cc0d94cf

Can you check if you can reproduce the problem in the dev environment?

**Comment by Zzooouhh** [comment]
I've tried using the new CardImpl and now it's not happening anymore. I'll try checking on the second problem once I come across it again, but I guess that'll probably be better to open a separate issue for.
