### ISSUE TITLE
Some choices done now as the spell goes to stack instead correctly as the spell resolves 

### ISSUE THREAD

**Issue by LevelX2** [magefree/mage#458]
608.2d If an effect of a spell or ability offers any choices other than choices already made as part of casting the spell, activating the ability, or otherwise putting the spell or ability on the stack, the player announces these while applying the effect.
As a simple rule you can say:
**If it's not a mode (choose one, choose two) a target (uses the word target) or a value for X it's not chosen until resolution.**
See also here:
http://www.mtgsalvation.com/forums/magic-fundamentals/magic-rulings/magic-rulings-archives/266843-persecute-timing

Question is also does the choice check in AbilityImpl.activate() make sense anymore?

**_Cards that have to be checked:_**
Mage.Sets/src/mage/sets/apocalypse/IllusionReality.java
    63:  getLeftHalfCard().getSpellAbility().addChoice(new ChoiceColor());
DruidsRepository.java
    62:  ability.addChoice(new ChoiceColor());
MidvastProtector.java
    61:  ability.addChoice(new ChoiceColor());
MoonlitStrider.java
    62:  ability.addChoice(new ChoiceColor());
PetalmaneBaku.java
    88:  this.addChoice(new ChoiceColor());
AstralCornucopia.java
    68:  ability.addChoice(choice);
GoldToken.java
    52:  ability.addChoice(new ChoiceColor());
BlessedBreath.java
    55:  this.getSpellAbility().addChoice(new ChoiceColor());
KamiOfThePaintedRoad.java
    70:  ability.addChoice(colorChoice);
OrderOfSuccession.java
    66:  this.getSpellAbility().addChoice(new ChoiceLeftOrRight());
SpringjackPasture.java
    83:  ability.addChoice(new ChoiceColor());
FaithsShield.java
    67:  this.getSpellAbility().addChoice(new ChoiceColor());
PrimalClay.java
    61:  ability.addChoice(new PrimalClayChoice());
AngelicSkirmisher.java
    86:  ability.addChoice(abilityChoice);
QuirionSentinel.java
    59:  ability.addChoice(new ChoiceColor());
Void.java
    74:  this.getSpellAbility().addChoice(numberChoice);
WashOut.java
    66:  this.getSpellAbility().addChoice(new ChoiceColor());
BlackLotus.java
    55:  ability.addChoice(new ChoiceColor());
SyggRiverGuide.java
    77:  ability.addChoice(new ChoiceColor());
StaveOff.java
    55:  this.getSpellAbility().addChoice(new ChoiceColor());
GildedLotus.java
    54:  ability.addChoice(new ChoiceColor());
AvacynGuardianAngel.java
    83:  ability.addChoice(new ChoiceColor());
    91:  ability.addChoice(new ChoiceColor());
FoodChain.java
    65:  ability.addChoice(new ChoiceColor());
LionsEyeDiamond.java
    75:  this.addChoice(new ChoiceColor());
RiftElemental.java
    94:  ability.addChoice(targetChoice);
ApostlesBlessing.java
    68:  this.getSpellAbility().addChoice(new ChoiceColorOrArtifact());
ResilientWanderer.java
    71:  ability.addChoice(new ChoiceColor());
Shelter.java
    54:  this.getSpellAbility().addChoice(new ChoiceColor());
AkromasBlessing.java
    58:  this.getSpellAbility().addChoice(new ChoiceColor());
JarethLeonineTitan.java
    73:  ability.addChoice(new ChoiceColor());
VedalkenEngineer.java
  117:  this.addChoice(new ChoiceColor());
PrimalPlasma.java
    63:  ability.addChoice(new PrimalPlasmaChoice());
Terrarion.java
    65:  ability.addChoice(new ChoiceColor());
    66:  ability.addChoice(new ChoiceColor());
DeathriteShaman.java
    80:  ability.addChoice(new ChoiceColor());
ManaBloom.java
    76:  ability.addChoice(new ChoiceColor());
EmergeUnscathed.java
    56:  this.getSpellAbility().addChoice(new ChoiceColor());
MulDayaChannelers.java
    82:  manaAbility.addChoice(new ChoiceColor());
Manamorphose.java
    57:  this.getSpellAbility().addChoice(new ChoiceColor());
    58:  this.getSpellAbility().addChoice(new ChoiceColor());
GodsWilling.java
    56:  this.getSpellAbility().addChoice(colorChoice);
NykthosShrineToNyx.java
    65:  ability.addChoice(choice);
GemstoneCaverns.java
    69:  ability.addChoice(new ChoiceColor());
LotusBloom.java
    61:  ability.addChoice(new ChoiceColor());
MotherOfRunes.java
    63:  ability.addChoice(new ChoiceColor());
CarpetOfFlowers.java
    84:  this.addChoice(new ChoiceColor());
FertileGround.java
    86:  this.addChoice(new ChoiceColor());
Persecute.java
    59:  this.getSpellAbility().addChoice(new ChoiceColor());
HarabazDruid.java
    79:  this.addChoice(new ChoiceColor());
SejiriSteppe.java
    55:  ability.addChoice(new ChoiceColor());
BraveTheElements.java
    57:  this.getSpellAbility().addChoice(new ChoiceColor());
KhalniGem.java
    70:  ability.addChoice(new ChoiceColor());
LotusCobra.java
    56:  ability.addChoice(new ChoiceColor());

**Comment by Zerrisx** [comment]
Has this been addressed, or does it still need to be looked into?

**Comment by LevelX2** [comment]
I guess the choices are done during resolution (I checked color choice for Blessed Breath), so this seems ok for me.
But I didn't check it for all spells.

**Comment by Zerrisx** [comment]
Seems to be fixed.
