### ISSUE TITLE
image download estimate 

### ISSUE THREAD

**Issue by pwn0r** [magefree/mage#4580]
It appears that the download size is incorrect. When downloading one set at a time, the UI shows an estimate but the ZIP file in xmage subfolder is considerably larger.

examples:
JOU set download from scryfall.com -- estimate 14.5mb -- ZIP size on disk is 40.5mb
SOM set download from scryfall.com -- estimate 21mb -- zip on disk is 57mb.

**Comment by LevelX2** [comment]
True, the shown download size is calulated with a fixed estimated size per image.
So it can't be accurate.

**Comment by JayDi85** [comment]
Outdated. Images sizes depends on sets, images styles and hq versions. Current solution with avg sizes is fine.
