### ISSUE TITLE
Feature Request: AI Logs.

### ISSUE THREAD

**Issue by ackzf** [magefree/mage#4589]
In some game states the AI simply idles for some time before not doing anything. This state persists even for subsequent games with different decks.

Currently I've found no logs for the AI and thus it is impossible to determine what cards are causing the AI lockup. At the minimum, what cards the AI had in hand should be logged somewhere to make identification of problematic cards easier.

**Comment by JayDi85** [comment]
AI is not full implemented and ignore some hard skills. Also it's use different calcs to apply his decisions. Use server in testMode. It's have cheat button to show up opponent hand/library list ([more info here](https://github.com/magefree/mage/issues/4334#issuecomment-360669289)).

**Comment by LevelX2** [comment]
Also the AI always allows to look at its hand cards if you request it (no need for test mode).

**Comment by ackzf** [comment]
How do I request it?

**Comment by LevelX2** [comment]
Right mouse button menu in the battlefield "Request permission to see hand cards".
After that you can switch the shown hand with a button in the F-Buttons panel.

**Comment by LevelX2** [comment]
I fixed a AI bug with the new release. I guess that was the source of the AI beeing idle problem.
