### ISSUE TITLE
Feature Request: Disable Idle/Timeout/Disconnect for AI games.

### ISSUE THREAD

**Issue by ackzf** [magefree/mage#4590]
There's no reason for an idle to cause a game loss when playing against AI. The AI can wait.

Similarly, disconnecting or idling in an AI game shouldn't be logged against the player.

**Comment by JayDi85** [comment]
Not actual anymore. Local server can run in test mode - it disable some timeouts. [Wiki page](https://github.com/magefree/mage/wiki/Development-Testing-Tools) has instructions.
