### ISSUE TITLE
Fast build?

### ISSUE THREAD

**Issue by use** [magefree/mage#4592]
Any way to do a fast build when I just want to test a card implementation? I do run -Dskiptests but it still takes forever :)

**Comment by spjspj** [comment]
You can just rebuild say Mage.Sets and not touch any of the other packages.  It may just be me, but you can recompile-on-the-fly for some of the executables (say when you are modifying Mage.Client) but it doesn't seem to work for Mage.Server (I usually have to implement the card, rebuild Mage.Sets (with no tests), restart the Mage.Server and then reconnect from the Mage.Client (which doesn't need to be shut down).  If I'm working on something in Mage.Client though, a recompile on the fly (aka 'Apply Code Changes' button in netbeans) seems to work ok.

**Comment by JayDi85** [comment]
Use:
`compile -DskipTests` 

It's build very fast, used only changes files. Place xmage files to SSD or memory disk to improve performance. As example: it's takes only 10-15 secs to compile server or client after changes for me (well, 80% of that time are resources copy, not compile -- need to optimize that moment in POM files someday).

P.S. If you cleaned or deleted other files (e.g. by stopped "install" process) then run full build by:
`clean install -DskipTests`.

IntelliJ IDEA settings example:

1. Client start up:
![shot_180310_100758](https://user-images.githubusercontent.com/8344157/37238975-6ac075a6-244b-11e8-9118-6c96d79aca8f.png)

2. Server start up:
![shot_180310_100824](https://user-images.githubusercontent.com/8344157/37238971-3cf12292-244b-11e8-8e45-63ecdb3edb1f.png)

3. Full build/install (if something goes wrong):
![shot_180310_100848](https://user-images.githubusercontent.com/8344157/37238965-23b3101a-244b-11e8-9934-24ec70d9ef3a.png)
