### ISSUE TITLE
Implementing spoiled cards when we don't know the collector's number?

### ISSUE THREAD

**Issue by use** [magefree/mage#4593]
Any guidelines for implementing the newly leaked Dominaria cards, since we don't know the collector numbers yet? When I'm filling in Dominaria.java, should I just use made-up placeholder numbers?

**Comment by JayDi85** [comment]
Don't worry about collector numbers, use any unique like 1,2,3,4,5,6 -- I'll fix that automatic after real numbers show up and before xmage's dominaria release. You can recreate all cards by delete all db-card-files in server/client dirs.

BUT don't post new code to master repository yet, create pull request.

**Comment by JRHerlehy** [comment]
You can just add the cards to the cards package. The set only needs them to show them in the editor and do drafts and suck.

Also, doing the numbers isn’t too hard for now. There’s a good standard way they are done.
