### ISSUE TITLE
adding Verdant Succession  to xmage

### ISSUE THREAD

**Issue by goatmastiff** [magefree/mage#4595]
hi im new to github and would just like to ask anyone that can help if they can contact or help me add the 
 card verdant succession to the xmage player i would really appreciate it ive wanted to do a combo with it for  very long time and want to try it before buying the cards it shouldnt be unbalanced in the formats it would be played in since 2 of the 3 cards in the combo cost 5 mana thanks!

**Comment by LevelX2** [comment]
https://github.com/magefree/mage/wiki/Developer-Getting-Started

or

https://www.slightlymagic.net/forum/viewtopic.php?f=70&t=20685
