### ISSUE TITLE
Bug with Lure

### ISSUE THREAD

**Issue by ackzf** [magefree/mage#4598]
1. Have an opponent attack you with a creature enchanted with lure.
2. Have a creature able to block.
3. During declare blockers, your creature will be blocking the lure-enchanted creature.
4. Click "Undo"

Expected result: Nothing happens. The lure creature will be blocked by your creature.
Actual result: The block is canceled, despite lure requiring all creatures able to block do so.

This makes lure quite useless.

**Comment by Zzooouhh** [comment]
Was this on version 1.4.27V4b or 1.4.28V0? There were a few code changes regarding this in the new version.

**Comment by ackzf** [comment]
I was indeed using 1.4.27V4b, closing then.

**Comment by ackzf** [comment]
![sss](https://user-images.githubusercontent.com/3597435/37264516-efa9a916-256a-11e8-9e27-7261dad83369.png)

I was again able to cancel a block by clicking undo when opponent had a lure creature. This is reproduced on version 1.4.28V0.

Relevant Logs:
8:24 PM: 22222 casts Lure [51f] targeting Matsu-Tribe Decoy [07f] 
8:24 PM: 22222 puts Lure [51f] from stack onto the Battlefield
8:24 PM: 22222 attacks with 1 creature
8:24 PM: Attacker: Matsu-Tribe Decoy [07f] (1/3) unblocked

**Comment by ackzf** [comment]
Addendum: It appears when multiple blockers are assigned due to the effect of lure, only the last one assigned can be undone by "undo".

**Comment by Zzooouhh** [comment]
Strange, I've assumed that testing this with Invasion Plans out should be yielding the same results - but on the contrary, choosing blockers with Plans cares about Lure limitations and "regular" blocking doesn't. I'll have to take a closer look at this.

**Comment by jeffwadsworth** [comment]
I can't reproduce this in the latest build.  The UNDO button is not shown.
