### ISSUE TITLE
Bad color scheme

### ISSUE THREAD

**Issue by player-354764547** [magefree/mage#4602]
When I placed the cursor on the flag of the other player to read his stats, the box that opens has hard colors to see (background and font).

![xmage_prtscn](https://user-images.githubusercontent.com/37273663/37257202-c098e4f0-255d-11e8-9ab7-c79b4d420ae2.png)

**Comment by JayDi85** [comment]
XMage use standard colors from Operation System like all other java apps. Use OS settings to change it.

![shot_180312_002441](https://user-images.githubusercontent.com/8344157/37258137-705d067c-258c-11e8-8540-22ac712efa7e.png)
![shot_180312_002425](https://user-images.githubusercontent.com/8344157/37258138-7082ba7a-258c-11e8-8753-545f26737c94.png)
