### ISSUE TITLE
Game froze claiming to wait for player 4 while player 3's clock was ticking.

### ISSUE THREAD

**Issue by derlhurgoyf** [magefree/mage#4606]
This happened in a FFA 4-player multiplayer game on the first round.
Game log attached.
[game-34d2da09-10b0-40bf-90dc-c266094c2df4.json.zip](https://github.com/magefree/mage/files/1801374/game-34d2da09-10b0-40bf-90dc-c266094c2df4.json.zip)

**Comment by spjspj** [comment]
There is now the /game chat command that should let you know current stats about the game.

**Comment by Zerrisx** [comment]
Duplicate of #4534
