### ISSUE TITLE
"Join" button in "Action" column in main screen not present

### ISSUE THREAD

**Issue by spjspj** [magefree/mage#4610]
It may also happen for the new Tournaments.  But when the option 'Disallow Spectators' is on, you get a button with no text in the 'Action' column on the main game lobby.  This is ok when the game is under way (aka, you don't want it to have 'Watch') but it's probably ok to have 'Join' when you want people to join the game.

**Comment by spjspj** [comment]
Hi @LevelX2 it was more about the text in the button on the tables in the main forum.  It seemed to be an empty string if you have set the 'No spectators to watch' checkboxes in the new match window.  People could still join though, just that the text of 'Join' wasn't present.  It also seemed to be that way for new tournaments with the no spectators options on.  I can confirm it again though.

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.
