### ISSUE TITLE
deck builder shows only one copy of a card

### ISSUE THREAD

**Issue by LateLine** [magefree/mage#4612]
since the last update, If i try to build a deck and i search for a card name, for example, Day of Judgment,  it displays only one copy of from a set of that card (all search filters are off). Usually, i could choose between different sets and artworks of this card.

it happens for all cards i search even for basic land cards. How do i search for a different artwork of a card now?

![default](https://user-images.githubusercontent.com/1619495/37305410-9fc6e268-2634-11e8-9007-f3a995f6f6a2.PNG)

**Comment by LateLine** [comment]
i found a filter to regulate the search, and resolved the so-called "Problem" myself. sorry about that, next time i check better twice before i report a "bug".

**Comment by spjspj** [comment]
@LateLine Not sure if it was mentioned explicitly, but it's the new (in 1.4.28v0) 'Unique' checkbox (to the right of where you've typed in 'day of ju') that's causing the singleton search behavior.
