### ISSUE TITLE
Sunbird's Invocation + spring/mind appears to be bugged

### ISSUE THREAD

**Issue by albuzs** [magefree/mage#4620]
Hello,

What is the deal with these cards? If I cast Spring, and hit another spring, I should be able to cast the spring I reveal.

Am I missing something?

**Comment by ruler501** [comment]
Spring /// Mind is a 9cmc spell. Spring is a cmc spell so you won't be able to cast it.

**Comment by JRHerlehy** [comment]
The rules update that came with Amonkhet (I think that was the set) changed how split card CMCs are handled. In any zone but the stack, a split card is the CMC of the sums of the halves. So no Wear/Tear is a CMC 3 card, not a CMC 1 and CMC 2.

This interaction is correct.
