### ISSUE TITLE
Zealous Conscripts and Inspired interaction bugged

### ISSUE THREAD

**Issue by Zzooouhh** [magefree/mage#4627]
I gained control of an opponent's King Macar with Zealous Conscripts - a judge confirmed me right now that I should be picking the target for the Inspired ability, since I control it when the Inspired trigger goes off (and also, untapping the creature happens after I gain control of it as per Conscripts' rules text). What instead happens is that the opponent is picking the target for Macar's Inspired trigger.

**Comment by LevelX2** [comment]
Fixed beyond 1.4.28V0 with this commit 66bd5294e8332b1bb2a871ad1c25c316c3ef849c.
