### ISSUE TITLE
Horribly Awry

### ISSUE THREAD

**Issue by Jknott85** [magefree/mage#4633]
The card Horribly Awry is bugged. nothing happens when you click on it to cast it. Twice I tried to counter an opponent's Detention Sphere on two different turns and nothing, losing both my Mindsculptor and Gideon, obviously losing me the game.

**Comment by LevelX2** [comment]
What exactly means "nothing happens"?
You clicked on the card and no window was opened? 
And no spell went to the stack?

**Comment by GitHubMage** [comment]
https://magiccards.info/query?q=horribly+awry&v=card&s=cname
Horribly Awry counters a CREATURE spell.
The detention sphere is not a creature.
I think this can be closed.
