### ISSUE TITLE
skip too late in combat phase

### ISSUE THREAD

**Issue by pwn0r** [magefree/mage#4644]
The game stops too late with skip in combat phase.

If I understand correctly, it stops with skip in effect when attackers are declared, which is a good thing. However weirdly it stops on Declare Blockers step, which is too late. Of course that happens only if the stack remained empty during declare attackers step.

Most obvious usage case is Vehicles, but also can apply to other scenarios. During Declare blockers it is too late to crew Vehicles and you won't be able to assign them as blockers. Obviously can apply to other scenarios involving blockers eligibility linked to any instants or abilities. 

The best option would be to stop at "play instants and abilities" of Declare Attackers step, if any attackers were assigned by an opponent, of course.

**Comment by JayDi85** [comment]
Fixed in last 1.4.34 release.
