### ISSUE TITLE
Grey Window with mouse filling in everything

### ISSUE THREAD

**Issue by themagicpotat0** [magefree/mage#4651]
Whenever I start a game or use the deck editor, the window greys out. The only thing I can do is move my mouse over the window and the buttons where my mouse is reappear. 
![screenshot 1](https://user-images.githubusercontent.com/37667558/37783576-39654272-2dcc-11e8-95a9-9442892fe9d4.png)

**Comment by JayDi85** [comment]
Download "symbols" from main menu.
