### ISSUE TITLE
Adding "Brawl" as a game type

### ISSUE THREAD

**Issue by rkdnc** [magefree/mage#4653]
[Brawl Rules](https://magic.wizards.com/en/articles/archive/ways-play/join-brawl-2018-03-22)

Basically "Commander-lite" with Standard only and 60 cards, and *no commander damage* rule.

**Comment by spjspj** [comment]
https://magic.wizards.com/en/game-info/gameplay/rules-and-formats/rules
Maybe Brawl will be in the Dominaria comprehensive rules?  I don't think we can determine yet if it's actual color identity or if is only mana symbols as stated in the article.

**Comment by jack-the-BOSS** [comment]
Could we get an update on this? I know it was checked off the tracking issues list. Wondering if it's ready.

**Comment by spjspj** [comment]
An attempt was made to add it - 
730d231

**Comment by Dimanari** [comment]
will it be implemented?

**Comment by Dimanari** [comment]
and to clarify - it is actual color identity! 
Color identity is a concept expanding the color of cards. While in game play mechanics the color of a card is always determined exclusively by the colors used in its casting cost or its color indicator (which was retroactively applied to cards like Ancestral Vision, which previously specified it in the rule text), the color identity of a card is specified by all mana symbols that appear in its casting cost, color indicator, and rules text.
this is a less obvious way of saying look for every mana symbol on the card - the set of different mana symbols is the color identity of the card.
only exception is extort as it is in the reminder text and not part of the rules text.
also cards like Driad Arbor that have a small color indicator should take that indicator into consideration.
they left this thing out as there are no legal cards in standard that uses this thing(and if they do - it doesn't matter)

**Comment by spjspj** [comment]
@Dimanari  It's implemented in  730d231 
Color identity was established in: https://twitter.com/maro254/status/988194208015044608  from 23rd of April here - https://gitter.im/magefree/mage  (this was prior to the comprehensive rules update of 27th of April which contains no mention of brawl btw - nice one wotc 🥇)

**Comment by Spigushe** [comment]
When will it be available in the xmage client ?

**Comment by LevelX2** [comment]
1.4.29V4
