### ISSUE TITLE
Scryfall Card Image Downloader broken.

### ISSUE THREAD

**Issue by rkdnc** [magefree/mage#4654]
Reported by Sugar Pop#9535 on Discord

**Comment by JayDi85** [comment]
It's work fine.

**Comment by JRHerlehy** [comment]
Scryfall has an aggressive IP blacklister. Hit it too hard too fast, and it’ll stop working for a bit. 

As for pulling the wrong images for earlier sets, it’s a known issue. Not sure if that has been resolved. I thought it was.

**Comment by JayDi85** [comment]
Can you do more info on "IP blocking"? How many cards/threads need to download before block?

**Comment by JRHerlehy** [comment]
Maybe the IP throttling is for the API side. I know they mention it in the docs.
