### ISSUE TITLE
Duplicated cards on rollback

### ISSUE THREAD

**Issue by JayDi85** [magefree/mage#4655]
From user's report:

Cards in hand was "duplicated" on rollback:
![a4cg_i8one4](https://user-images.githubusercontent.com/8344157/37849413-fbf6d5c4-2ef0-11e8-9ba3-b873ea1457c0.jpg)

**Comment by LevelX2** [comment]
There is a “draws 3 cards“ message in the log.
I wonder where this comes from.

**Comment by JayDi85** [comment]
There were bug (fixed in 90a5a55a72fe8dd9f6c6168502e60ad222a961f2) -- if you store cards list in `CardsImpl` and calls `player.moveCards` then that's cards will be duplicated (cards moved to exile zone but still exists in battlefield too (`Winds of Abandon` example) -- cause move code checks `card instanceOf Permanent` to delete it from battlefield list).

I think it related to that issue too.
