### ISSUE TITLE
Using battlefield background image can cause graphical bugs like XMage is using only a subarea to display the client

### ISSUE THREAD

**Issue by LevelX2** [magefree/mage#466]
Selecting a background image greater than screen size causes graphical bugs in XMage.

**Comment by LevelX2** [comment]
Reports:
http://www.slightlymagic.net/forum/viewtopic.php?f=70&t=17951&start=45#p190676

**Comment by LevelX2** [comment]
Seems like changing the resoltion can be a workaround:
> I don't think this is wallpaper related anymore, it seems to be just resolution related as I've tried to change or even turn off the backgrounds and the bug still occurs. Furthermore, I've managed to get this in a lobby as well.

> I changed my screen resolution to 1600x900 and played few games without any problems. Would it be possible to somehow force the client to use a lower resolution in further updates? Fixing the issue whatever it is would be better obviously, but that would do for now.

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.
