### ISSUE TITLE
Add welcome setup dialog for first time startup with base settings select and hints

### ISSUE THREAD

**Issue by spjspj** [magefree/mage#4662]
A bug that I did has kind of highlighted the fact that a lot of people don't download the symbols.  There could be an enhancement such that the first time someone starts xmage, it could prompt them in a guide-through or wizard or similar (maybe a welcome dialog?) to download the symbols and the button to press to get them.  Also in the same one it could possibly point out where/how to get images.

**Comment by JayDi85** [comment]
Duplication of #6859
