### ISSUE TITLE
Mycosynth Lattice, a morphed den protector and unwinding clock

### ISSUE THREAD

**Issue by spjspj** [magefree/mage#4663]
The morph isn't an artifact and isn't untapping :( I think lattice was down before the morph in terms of time stamp.

**Comment by xenohedron** [comment]
I haven't tried to reproduce yet but I'm going to guess this is fixed by #11689

**Comment by xenohedron** [comment]
Didn't try the full game state but mycosynth lattice correctly adds the artifact type to morphs whether it is on the battlefield before or after, even before the layer 1b rework.
