### ISSUE TITLE
Conversion (the card) doesn't change mana that Mountains tap for

### ISSUE THREAD

**Issue by Zzooouhh** [magefree/mage#4664]
Conversion's continuous effect is "All Mountains are Plains." In Xmage however, it only changes the land's subtype, the mana Mountains tap for remains the same (i.e. Volcanic Island still taps for blue and red despite being a Plains with Conversion in play).

**Comment by jeffwadsworth** [comment]
That "fix" breaks the layer system for the card.

**Comment by jeffwadsworth** [comment]
Fixed with https://github.com/magefree/mage/commit/7f1267563b6569b1e149f1c7c53908a03d1d19c1
