### ISSUE TITLE
Help with implementing Jaya Ballard?

### ISSUE THREAD

**Issue by use** [magefree/mage#4665]
Hello, I was wondering if someone can help with implementing Jaya Ballard from Dominaria?

Card implementation:  
https://github.com/use/mage/blob/6f2a3ebb65c9e81497d96860191357fe000a0c63/Mage.Sets/src/mage/cards/j/JayaBallard.java

Branch I am working on:  
https://github.com/use/mage/tree/jaya-ballard-dev

She works correctly except for one thing: when her emblem is in play, and you cast an instant/sorcery from the graveyard, you have to choose from a bunch of copies of the replacement effect for some reason (screenshot below).

I copied a lot of the emblem code from Kess, Dissident Mage. So I tried out Kess, and **Kess has the same bug**.  
https://github.com/magefree/mage/blob/e18db3e0c77b9f6b39108bf81e791d5fb79b6bd7/Mage.Sets/src/mage/cards/k/KessDissidentMage.java

If I had to guess what is going on here, I am incorrectly adding the same replacement effect to each card in the graveyard many times. But I am not sure the correct way to do it.

init.txt to help with testing Jaya (sorry I don't know how to use init.txt to create the emblem):

hand:Human:Jaya Ballard:1
hand:Human:Lightning Bolt:1
graveyard:Human:Lightning Bolt:2
library:Human:Plains:11
library:Computer:Plains:11
graveyard:Computer:Plains:1
battlefield:Computer:Storm Crow:1

![screenshot 2018-03-25 15 16 34](https://user-images.githubusercontent.com/94230/37880738-e2c08b8e-3041-11e8-9b10-d8d92663f0b6.png)

**Comment by spjspj** [comment]
Yeah, I did Kess.  (which was copied a lot off of Karador and Gisa + Geralf).  I think if I was doing it again that the ability should only be with the permanent.  Implemented as an activated ability, once per turn on your turn, you can cast a non-targeted sorcery/instant/zombie card.  But it's not exactly the way that it's worded so it would break with things like linvala, keeper of silence out.   Noone's really been whinging about it so I've not touched it again.   There was a bug where Karador could cast something again on each turn (or Gisa/Geralf could).

**Comment by spjspj** [comment]
Also, was reminded again of the big yellow numbers looking at your pic :|  It would be cool if they faded out (say if you get hit they shine briefly as red prior to going down, or if you gain life they go slightly blue).

**Comment by use** [comment]
@spjspj In this case should I just submit a PR and hopefully someone can fix the "duplicate replacement effect" problem later?

**Comment by spjspj** [comment]
Hi @use Yeah, I think that is probably sensible :)  Just get it working for the time being.  It's probably something that should be looked at.  Similar to mana costs (like {3}{1}[2}{U} or similar being combined into {6}{U})

**Comment by RMFDEMON** [comment]
Hey man, it seemed like someone got it almost done, but her ultimate and emblem crashes when I try to play any instants or sorceries. Here's the bug I encountered:
![capture](https://user-images.githubusercontent.com/16737649/39078684-160e001a-44ca-11e8-8a62-ab4cdfba4fad.PNG)

**Comment by RMFDEMON** [comment]
When do you think there’ll be a fix?
