### ISSUE TITLE
Deck Editor seems to be bugging

### ISSUE THREAD

**Issue by afa7789** [magefree/mage#4670]
![image](https://user-images.githubusercontent.com/26887703/38000623-d6334fdc-31fe-11e8-931a-e898a8fead28.png)
this is my printscreen. I can add or remove cards, or do anything in the deck editor. It just bugs. screen freezes etc
[log.txt](https://github.com/magefree/mage/files/1854131/log.txt)

**Comment by afa7789** [comment]
I"ll try reinstall but it seems to be unable to deck edit , new or older decks maybe this has to do with the new version in my new notebook it doesn't work

**Comment by JayDi85** [comment]
It's a bug in 28v1... Download symbols from main menu and restart app.

**Comment by afa7789** [comment]
Gonna Try it i reinstalled to seem if it works

**Comment by afa7789** [comment]
Thnks men it's wroking now
