### ISSUE TITLE
Screen archiving and not showing anything

### ISSUE THREAD

**Issue by invincibleparm** [magefree/mage#4671]
Was working fine for a couple of days. Now, every time I get into a game the screen is mostly white. If I mouse over things it slowly reveals parts of the game board, but never more than one card in my hand. Then, mousing over the cards, they get their tooltip to come up and they stay and blot out the whole bottom of the screen. Changing resolution, etc, doesn't seem to work. 
I'm very new to xmage, so I don't know if this is a common issue or not. It has made the game unplayable now.

**Comment by JayDi85** [comment]
Download symbols from main menu and restart app.

**Comment by Zerrisx** [comment]
Looks like this was resolved.
