### ISSUE TITLE
Shortcuts (skip stack, end turn, end step) register even when chat input is focused

### ISSUE THREAD

**Issue by Kwon11** [magefree/mage#4676]
Change shortcut for "To Your Turn" to a commonly used letter (for example "g")
While in game, focus the chat and type ("Good play")
The "To Your Turn" button gets triggered.

Hotkeys should not trigger while chat input is focused

**Comment by JayDi85** [comment]
Fixed via 1dbf5ba1833df85d167cfe69694911ae02e6924d
