### ISSUE TITLE
Deep Analysis has no flashback cost reduction BUG

### ISSUE THREAD

**Issue by EllNubNub** [magefree/mage#4677]
[Deep Analysis ](http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=32237) does not have a reduced flashback cost when using [Mizzix of the Izmagnus](http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=405303)'s XP ability.

**Comment by spjspj** [comment]
11/4/2015 | The cost reduction can apply to alternative costs such as flashback costs.

The operative word is 'can' ;)
xmage says no.
There was a card recently implemented with an effect that reduces flashback (Catalyst Stone?).  Mizzix probably needs a rework to have something similar.
