### ISSUE TITLE
Assault Suite works incorrectly with Sheoldred BUG

### ISSUE THREAD

**Issue by EllNubNub** [magefree/mage#4678]
[Assault Suit](http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=430427) lets people ignore [Sheoldred's](http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=438674) sacrifice effect when the player has 2 or more creatures with the Assault Suit equipped by choosing that creature to be sacrificed instead.

**Comment by derlhurgoyf** [comment]
to be clear: Player N has Sheoldred. Player A has two creatures, one of them with assault suite equipped. At Player A's upkeep he can chose to sacrifice the equipped creature to Sheoldred's trigger, which doesn't happen.

Ruling: 11/7/2014 : If an effect instructs you to sacrifice a creature, and you control any creatures other than the creature equipped with Assault Suit, you must sacrifice one of them. You can’t try to sacrifice the equipped creature, fail, and therefore ignore the effect.

**Comment by Zerrisx** [comment]
Yep, still bugged.

**Comment by xenohedron** [comment]
must be fixed by #11587
