### ISSUE TITLE
Blood Sun works improperly

### ISSUE THREAD

**Issue by EllNubNub** [magefree/mage#4679]
the ruling on [Blood Sun](http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=439749) states "1/19/2018    If a land has an ability that causes it to enter the battlefield tapped, it will lose that ability before it applies. The same is also true of any other abilities of a land that modify how it enters the battlefield or apply “as” it enters the battlefield, such as the first ability of Unclaimed Territory." however the lands still enter tapped in xmage, please fix - thanks!

**Comment by jeffwadsworth** [comment]
#4202
