### ISSUE TITLE
Selected "Skip to your turn" after attempting to attack with Mogg Flunkies alone and got infinite dialog boxes

### ISSUE THREAD

**Issue by Kwon11** [magefree/mage#4685]
What I was doing
1. Mogg Flunkies (Mogg Flunkies can't attack or block alone.) on the game board
2. Play another creature card
3. Go to combat
4. Attack with Mogg Flunkies
5. Dialog box came up
6. Click ok to dismiss
7. Click done
8. Click "To Your Turn"
9. Box comes up, click ok, another box comes up, click ok (at this point they were coming up slowly)
10. Bunch of boxes coming up now too fast to dismiss. Client goes unresponsive

**Comment by JayDi85** [comment]
Fixed via 57283c3ccaba0c8b5e19b9c11f6be0c3c7c35cd4
