### ISSUE TITLE
Jhoira, Weatherlight Captain

### ISSUE THREAD

**Issue by zeflap** [magefree/mage#4690]
Would be essentially
https://github.com/magefree/mage/blob/master/Mage.Sets/src/mage/cards/v/VedalkenArchmage.java ,
but with the artifacts filter switched to a historic filter, implementation of which would probably aid with other DOM cards.
I have no idea of how to work the codebase, would otherwise implement myself.

**Comment by ingmargoudt** [comment]
Jhoira, Weatherlight captain is already implemented in commit bd4b5f6

**Comment by zeflap** [comment]
Ah, neat
