### ISSUE TITLE
Commander 2016 Entropic Uprising missing a mountain

### ISSUE THREAD

**Issue by rystan** [magefree/mage#4694]
Deck in sample library only has 99 cards total.  Reviewing the Wizards decklist includes 5 mountains, sample deck only has 4.

path to sample deck:
Mage.Client/release/sample-decks/Commander/Commander 2016/Entropic Uprising (UBRG).dck

Official decklist:
https://magic.wizards.com/en/articles/archive/news/commander-2016-edition-decklists-2016-10-28

**Comment by JRHerlehy** [comment]
Resolved in #4695
