### ISSUE TITLE
Importing .dec deck file not working.

### ISSUE THREAD

**Issue by DaveTheLeg** [magefree/mage#4701]
Hello.  I'm trying to import my .dec deck file, which is one of the extensions listed as being supported in the dialog window.  But when I select it and press open, nothing happens.  The cards don't populate into the deck editor and there is no error message, just nothing.

**Comment by spjspj** [comment]
Could you copy the failing .dec file as a comment below?

**Comment by JayDi85** [comment]
You need to look at black error log window.

**Comment by Zerrisx** [comment]
This appears to be resolved or obselete
