### ISSUE TITLE
Xmage failing to start

### ISSUE THREAD

**Issue by evathebaeva** [magefree/mage#4712]
Xmage hasn't been working today or yesterday; after trying to connect to a server, it will say it is trying to connect, but it never will. Cancelling the attempt is fine, but after trying to close the program it will ask me if I'm sure I want to disconnect, and when I click yes it will fail to close (needing to be closed by the task manager even though it's technically responding). I've tried deleting and redownloading Xmage, and Autoconnect is off (and was deleted as well at one point), but the issue persists.
![xbug1](https://user-images.githubusercontent.com/37966811/38281113-e2481dca-375d-11e8-8b75-e28aa3eb0091.PNG)
![xbug01](https://user-images.githubusercontent.com/37966811/38281085-bfeb9ca2-375d-11e8-81d1-391e3eeb0b64.PNG)
![xbug02](https://user-images.githubusercontent.com/37966811/38281091-c407c4f0-375d-11e8-9ac7-a651ea9a1bf7.PNG)

**Comment by evathebaeva** [comment]
This is perhaps just an issue with the US (and possibly German) server, since after some testing I was able to connect to the xmageplayermtg.ddns.net server.

**Comment by JayDi85** [comment]
Yes, it's a servers problem. us is done, de work fine.
