### ISSUE TITLE
Cards not showing properly and screen is all messed up

### ISSUE THREAD

**Issue by DzigiTech** [magefree/mage#4716]
Hey guys!
Upon joining the game, cards are not showing at the bottom at all and the screen is all messed up.
I am using the 1.4.28V1 version and accessing the xmage.de server.

![xmage_1](https://user-images.githubusercontent.com/30194587/38324155-bcbef8fc-383f-11e8-850c-f22bf6075d95.png)
![xmage_2](https://user-images.githubusercontent.com/30194587/38324158-be4a6c60-383f-11e8-9903-248a8c43b378.png)

Can you please help with this?

**Comment by JayDi85** [comment]
Download symbols from main menu and restart app.

**Comment by DzigiTech** [comment]
Downloading symbols resolved the problem. Thanks :)
