### ISSUE TITLE
Deck generator adds more than 4 of the same card to a generated deck

### ISSUE THREAD

**Issue by JayDi85** [magefree/mage#4717]
Deck type: Alara Reborn

On generate new deck, it's adding too many of the same card (more than 4)

![shot_180405_230125](https://user-images.githubusercontent.com/8344157/38386426-add7b004-3925-11e8-9d82-6d110da94192.png)

![shot_180405_230142](https://user-images.githubusercontent.com/8344157/38386431-b096b29a-3925-11e8-9d9a-e5ffdba42802.png)

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.  Looks like if the deck would fail and/or can't meet the requirements, it just doesn't generate it.
