### ISSUE TITLE
M15 render bug for small vehicle cards without images

### ISSUE THREAD

**Issue by JayDi85** [magefree/mage#4720]
![shot_180406_114605](https://user-images.githubusercontent.com/8344157/38409160-56049df8-3991-11e8-8c49-f197418b66bc.png)

**Comment by spjspj** [comment]
How is that a bug?  It's the background for vehicle.

**Comment by JayDi85** [comment]
It's like broken/erased image on battlefield.

Hmm...

From resources:
![background_texture_vehicle](https://user-images.githubusercontent.com/8344157/38417543-c988313c-39a9-11e8-885d-549fbbec42a0.png)

From xmage:
![shot_180406_145326](https://user-images.githubusercontent.com/8344157/38417672-4ad8e22c-39aa-11e8-8cd4-e441ee16d375.png)


Resize works bad with details and small cards are weird -- need to replace background image to another pattern without small details/lines.

**Comment by JayDi85** [comment]
Main topic: #12276
