### ISSUE TITLE
Twinning glass does not work with buyback BUG

### ISSUE THREAD

**Issue by EllNubNub** [magefree/mage#4721]
[Twinning glass](http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=143375) does not work with buyback cards, or atleast it does not work with a boughtback [reiterate](http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=109729).

**Comment by Zerrisx** [comment]
Looks like this is even more broken right now, see #6803

**Comment by JayDi85** [comment]
Twinning Glass works fine, additional tests added in d62cf1742226b5378e77dac0fb9bdca427d6e1dc
