### ISSUE TITLE
Stolen permanents being impossible to activate (after control is regained)

### ISSUE THREAD

**Issue by Zzooouhh** [magefree/mage#4727]
On Xmage 1.4.28V1, in a 4 player EDH FFA game, I had a tapped Gilded Lotus stolen by a Dack Fayden planeswalker. Before Dack's controller's next turn, I've cast a Brand (on my turn) and gained control of the Lotus again (I gained control of it in a tapped state). However, after another turn rotation when the Lotus got untapped, I was unable to activate it.

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.
