### ISSUE TITLE
Utils\gen-list-unimplemented.... issues with RIX set data

### ISSUE THREAD

**Issue by rystan** [magefree/mage#4739]
Based on mtg-cards-data.txt info, the perl script is reporting the following unimplemented non-"basic land" cards:
12|Luminous Bond  --> Luminous Bonds
43|Mist-Cloacked Herald --> Mist-Cloaked Herald
46|Return to the Wind --> Release to the Wind
58|Sworn Gaurdian --> Sworn Guardian
120|Tilonali's Crown --> Tilonalli's Crown
142|Path to Discovery --> Path of Discovery

^^ Left is  what is produced from the txt file, right is the lookup in gatherer

How does one go about generating a new mtg-cards-data.txt?  Is that the magefree/gatherer-crawler project?

**Comment by spjspj** [comment]
https://www.slightlymagic.net/forum/viewtopic.php?f=116&t=20957 to scrape a site.

There is also this kind of more man-draulic way from the code:
```
c:\xmage_release\mage\Utils>type get_spoiler_txt_ixa.bat
del x
del x2
del x3
del x4
del x5
del x6
del x7.bat
echo "" |  cut.pl stdin "http://mythicspoiler.com/ixa/" 0 wget > x
type x | cut.pl stdin "cards\/" "\n\n\ncards/" replace  > x2
type x2 | cut.pl stdin "^" "\nhttp://mythicspoiler.com/ixa/" replace  > x3
find x3 "http://mythicspoiler.com/ixa/" | find /v /i "jpg"  > x4
type x4 | cut.pl stdin "><.*" "" replace  > x5
type x5 | cut.pl stdin "^" "echo '''' | cut.pl stdin ''" replace  > x6
echo @echo off > x7.bat
type x6 | cut.pl stdin "$" " 0 wget_card_spoiler" replace | cut.pl stdin 0 0 uniquelines   | find  /I "cards" >> x7.bat
type x7.bat
```
