### ISSUE TITLE
Harmonic Sliver doesn't trigger when entering from Exile

### ISSUE THREAD

**Issue by derlhurgoyf** [magefree/mage#4740]
Just had a game with Harmonic Sliver being reanimated or blinked, but never triggered. Only when cast from hand.

**Comment by derlhurgoyf** [comment]
sorry, you're right from the graveyard.
In the game log attached around 12:59 you see the sliver in play.
At 1:02 I activate planar guide to blink all creatures.
Opponent casts a bunch of artifacts and 1:03 all creatures return, but there's no Sliver trigger.
[20180409_231136_Commander Free For All_1.txt](https://github.com/magefree/mage/files/1894366/20180409_231136_Commander.Free.For.All_1.txt)

**Comment by LevelX2** [comment]
Probably this is also fixed. Before the cards were moved one by one so the group that was moved could not be recognized. Now the correct methods to move groups of cards are used.

**Comment by derlhurgoyf** [comment]
@LevelX2 sorry to warm this up again, but I had a game yesterday where one of the creatures blinked by Planar Guide was an opponent's Thalia, Herethic Cathar. To my surprise some, but not all of my creatures returned tapped. While I'm unsure whether all or no creatures should be affected by Thalia, I'm sure the partial behaviour is wrong. Is this still related to Guide?
