### ISSUE TITLE
Sometimes Singleton EvasionAbility like Flying or Intimidate do not work

### ISSUE THREAD

**Issue by LevelX2** [magefree/mage#476]
Sometimes a creature can block a creature it should not be able to block.
E.g. a non flying creature can block a flying creature.

**Concerned abilities:**
Flying
Shadow
Intimidate
Fear
Reach

I added some new traces from the public server:

**What do we know or presume:**
* It's activated from some event happening. If so, the ability in the game stops working correctly.
* In other games the abilities work correctly.
* So probably something in the game classes is not correct.

**What can we do to find the cause of this bug:**
* Advance the trace to check possible reasons. Anyone ideas what to do?

**Possible causes**
Setting the Duration of the effect from "WhileOnBattlefield" to "EndOfGame" seems to reduce (or completely solve) the problem. Like the check if the permanent is on the battlefield is not always doen for the correct permanent, because the ability is a singleton it can't know the correct sourceId for sure.

**Comment by drmDev** [comment]
Over 2 years old and no reports of this in... since I started contributing. We have many tests that cover these types of scenarios as well
