### ISSUE TITLE
Commander 2017 (C17), Dominaria (DOM) tokens are missed

### ISSUE THREAD

**Issue by JayDi85** [magefree/mage#4763]
[C17](https://scryfall.com/sets/tc17), [DOM](https://scryfall.com/sets/tdom).

**Comment by FastTadpole** [comment]
Not sure on the file names of the the tokens for Dominaria in the DOM folder in the TOK.zip archive. Going to the viewer won't display them either, even as blanks with the dir\filename.full.jpg as the other sets do when selecting the tab with the display cards unchecked.

![xscreenieviewer](https://user-images.githubusercontent.com/13674016/39795845-40ed9aa8-5310-11e8-92a9-5c001127179a.jpg)

**Comment by rystan** [comment]
C17 images are available from tokens.mtg.onl and show up in xmage client.

However, the DOM token images aren't on tokens.mtg.onl yet.

**Comment by JayDi85** [comment]
I'm wrote to onl's owner to add new tokens. Hope he adds it on next days.
