### ISSUE TITLE
Missing cards

### ISSUE THREAD

**Issue by jal218** [magefree/mage#4801]
Hello, I`ve been wanting to make a color changing deck, but cards such as Glamerdye, Alter Reality or Whim of Volrath. Is there any way to make these cards available?
Thanks

**Comment by jack-the-BOSS** [comment]
Request cards here: https://www.slightlymagic.net/forum/viewtopic.php?f=70&t=20685 But, duly noted. I think the developers are mostly focused on the new cards right now.

**Comment by Zzooouhh** [comment]
Cards that alter card text happen to be beyond the limits of the current Xmage framework, so you probably shouldn't expect them to be implemented anytime soon.

**Comment by peter-thoenen** [comment]
Not sure why this was closed, is there a "bug" tracking Zzooouhhh comment?  This was two years ago and that mechanic even older; and it has to be hell of a lot easier to implement than the new champions.
