### ISSUE TITLE
Vicious Offering does not allow target selection

### ISSUE THREAD

**Issue by kahnyoudiggit** [magefree/mage#4805]
I cast Vicious offering, and selected no for the kicker option. Then I paid mana - and the spell was cast. Did not get to select targets, so the spell went right to the graveyard.

**Comment by jack-the-BOSS** [comment]
This issue is fixed and will be in the hotfix.

**Comment by kahnyoudiggit** [comment]
Is there a place I can see what fixes have already been made so I don't submit duplicate reports?

**Comment by jack-the-BOSS** [comment]
https://github.com/magefree/mage/commits/master

**Comment by LevelX2** [comment]
I update here the fixes not released yet:
https://github.com/magefree/mage/wiki/Features-and-fixes-not-released-yet
