### ISSUE TITLE
Knight of Malice buff applies to all creatures.

### ISSUE THREAD

**Issue by kahnyoudiggit** [magefree/mage#4806]
I cast a knight of malice on turn two, and a deathbloom thallid on turn three. The Thallid was a 4/2. Later I cast Baird, Steward of Argive, and it was a 3/4.

Seems like the +1/+0 buff is applying to all creatures and not just the knight.

I'd check knight of grace too.

**Comment by jack-the-BOSS** [comment]
Both were bugged. Knight of Malice is fixed; working on Grace.

**Comment by kahnyoudiggit** [comment]
Sweet, glad to hear it.
