### ISSUE TITLE
Cannot pay alternate cost on Torgaar, Famine Incarnate

### ISSUE THREAD

**Issue by edcarter** [magefree/mage#4815]
v1.4.29V1

I was unable to pay Torgaar, Famine Incarnate alternate casting cost of sacrificing a creature. I was able to use the normal casting cost however.

**Comment by LevelX2** [comment]
More information needed to reproduce the problem.
 
What was the exact situation?
What value did you define for creatures to sacrifice? 
What creatures were on the battlefield?

**Comment by edcarter** [comment]
>> What was the exact situation?
I was playing a Commander free for all match with Torgaar as my commander. I attempted to cast Torgaar from the command zone, but I wasn't given the option to sacrifice a creature.

>> What value did you define for creatures to sacrifice?
I was never given the option to pay an alternate cost

>> What creatures were on the battlefield?
1x Sengir Autocrat 
3x 0/1 black Serf creature tokens

**Comment by edcarter** [comment]
I'm guessing this is a problem when casting from the command zone?
