### ISSUE TITLE
XMage doesn't full support java 1.7 anymore to download updates

### ISSUE THREAD

**Issue by JayDi85** [magefree/mage#4818]
XMage doesn't support java 1.7 anymore? I've got some error reports about download problem by https links (github link in http://xmage.de/xmage/config.json). They are can't download it (see #4810 as example,  #4814 and #4822, reddit users have same trouble):
`javax.net.ssl.SSLException: Received fatal alert: protocol_version` 

[StackOverflow description and fixes](https://stackoverflow.com/a/33494593/1276632)

It's works fine before Dominaria and was hides by second download link in config.json (http). But with Dominaria update the second link was not updated (#4817) and compatibility problem rise up.

**Comment by Zerrisx** [comment]
Looks like all the linked issues were fixed, so I'm assuming this one was too.
