### ISSUE TITLE
The Antiquities War third ability affects artifacts played after it resolves

### ISSUE THREAD

**Issue by NULL1233** [magefree/mage#4819]
The ability should only affect artifacts in play when the ability resolves but it affects all artifacts played during the entire turn.

**Comment by JayDi85** [comment]
Oracle about that:

> The final chapter ability of The Antiquities War affects only artifacts you control at the time it resolves. Artifacts you begin to control later in the turn won’t become 5/5 creatures. (2018-04-27)
