### ISSUE TITLE
Launcher installs wrong version. 

### ISSUE THREAD

**Issue by kodemage** [magefree/mage#4822]
I've completely deleted my xmage folder and downloaded the launcher several times now. Every time I do it seems to be installing the wrong version of the client while reporting the correct version has been installed within the launcher. 

see: https://github.com/magefree/mage/issues/4814

**Comment by JayDi85** [comment]
Use [that instructions](https://github.com/magefree/mage/issues/4814#issuecomment-383000456) to fix it.

**Comment by kodemage** [comment]
@JayDi85 

I am not using java 1.7, the java version the launcher installed is 1.8.0_172

I am using the default settings on the launcher, if it is installing version 1.7.x of java and reporting that it is installing 1.8 then that is part of the bug. 

Please see this screen shot: https://user-images.githubusercontent.com/7217220/39027632-71b39478-4418-11e8-8605-4d05c3f2f2f0.jpg

It clearly says I am not using version 1.7 of java, but instead using version 1.8/ 

Again, this is a fresh install of both pieces of software downloaded directly from the website using only the default settings. I have changed nothing.

**Comment by kodemage** [comment]
xmage installs it's own version of java, the launcher tells you about this when it does so...
