### ISSUE TITLE
Knight of Malice does not get +1/+0 when i control a white permanent

### ISSUE THREAD

**Issue by mathieupouedras** [magefree/mage#4825]
Xmage 1.4.29V1 (2018-04-20)

Knight of Malice does not get +1/+0 when i control a white permanent

Thank you for this new set

Mathieu

**Comment by JayDi85** [comment]
Was fixed via e3750ad335b3daa9eb9d75f96daa5ff9bf62be35. Will be available with v2 hotfix.

**Comment by mathieupouedras** [comment]
Thanks good job
