### ISSUE TITLE
[Missing Card] Gustha's Scepter

### ISSUE THREAD

**Issue by zeflap** [magefree/mage#4826]
https://scryfall.com/card/me2/209

Gustha's Scepter {0}

Artifact

{T}: Exile a card from your hand face down. You may look at it for as long as it remains exiled.

{T}: Return a card you own exiled with Gustha’s Scepter to your hand.

When you lose control of Gustha’s Scepter, put all cards exiled with Gustha’s Scepter into their owner’s graveyard.

**Comment by LevelX2** [comment]
Please don't create issues about missing cards. Thanks.
