### ISSUE TITLE
Godo, Bandit Warlord's copies (Helm of the Host) don't untap when their attack triggers resolve

### ISSUE THREAD

**Issue by Zzooouhh** [magefree/mage#4827]
Trying out the silly new combo of Godo and Helm of the Host, and there's a bug related to it - Godo says "untap it and all Samurai you control"; the original Godo properly untaps himself when he's attacking, but the copies don't untap themselves when their own triggers resolve.

Note that this happened before I attacked with the original Godo, so it's not an issue of the tokens copying the "already attacked this turn" watcher state of the original Godo. I tested attacking with the original afterwards just to check, and it untaps properly with the trigger.

**Comment by use** [comment]
When I implemented Helm of the Host I found a similar bug with Aurelia the Warleader - I was testing a similar combo to that which you're testing with Godo:

https://github.com/magefree/mage/commit/eebd6b3af4d9ed43f45e7f080f3fe983b9c2bf93

I bet it's a similar thing - Godo's code is using getCardZoneString, which appears to only find cards. Tokens aren't cards, but they are permanents. So his ability probably needs to be changed to look for permanents similar to how Aurelia was fixed.

https://github.com/magefree/mage/blob/e18db3e0c77b9f6b39108bf81e791d5fb79b6bd7/Mage.Sets/src/mage/cards/g/GodoBanditWarlord.java#L121
