### ISSUE TITLE
Land that taps for more than one mana still produces that mana after being enchanted with Spreading Seas

### ISSUE THREAD

**Issue by Themagicman16** [magefree/mage#4834]
I was playing a match against Eldrazi Tron and the computer was able to cast a Thought-Knot Seer with three lands despite the Eldrazi Temple being enchanted by a Spreading Seas. The other lands were an Urza's Tower and a Sea Gate Wreckage. I did notice though when I let my cursor hover over the temple it displayed that it was an island that could only tap for blue mana.

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.
