### ISSUE TITLE
Bugs: Firesong and Sunspeaker, Grand Melee, Benediction of Moons

### ISSUE THREAD

**Issue by Iwasrunningoutofnamesatthispoint** [magefree/mage#4836]
Firesong and Sunspeaker:
The second abillity doesnt work with mulitcolored spells. In example lightning Helix doesnt trigger its second abillity at all.
Gatherer states: If a red and white spell you control deals damage and also instructs you to gain life, Firesong and Sunspeaker’s last ability triggers twice.

Grand Melee:
If being attacked by a creature with flying, while not having a valid blocker, the game enters a loop where it wants you to block but you cant.

Benediction of Moons:
It seems to have an issue counting players, as it never gains you any life.

**Comment by Zerrisx** [comment]
Cannot reproduce; these all appears to be fixed.
