### ISSUE TITLE
Issues with Yawgmoth's Vile Offering and Phyrexian Scriptures.

### ISSUE THREAD

**Issue by Manyfans** [magefree/mage#4839]
- [ ] - So, firstly, I've discovered that **Yawgmoth's Vile Offering** says for me to choose target creature or planeswalker to destroy, but tells me to target a _permanent_ card from a graveyard to return... The card reads _creature or planeswalker_.

- [x] - Secondly, **Phyrexian Scriptures**' third clause exiles all cards from _all_ graveyards... It reads all _opponents'_ graveyards.

I searched a bit through the Issues and didn't find one that covered specifically this, so I thought I'd post it. I hope this is helpful.

**Comment by JRHerlehy** [comment]
Yawgmoth is a text error. Code only lets you target creature or walker cards, I just forgot to ever put in the text. Just a text update there.

Looks like Scriptures does need a bit of an update.

**Comment by JRHerlehy** [comment]
Looks like the Scriptures was fixed in an update. Someone needs to touch Offering when they have a chance.

**Comment by theelk801** [comment]
I'm on it
