### ISSUE TITLE
Kwende does not work with enchantments that give first strike

### ISSUE THREAD

**Issue by AricHaldan** [magefree/mage#4846]
it seems kwende is bugged in xmage. apparently if the creature has first strike on its card it gives it double strike. but if it is enchanted with dub, it does not give double strike. I am unsure on the details but perhaps this is because an enchanted creature doesn't inherit the abilities in the code ?

**Comment by theelk801** [comment]
I just tested this and it works fine. Are you still having a problem with it?

**Comment by AricHaldan** [comment]
ah ok if it works in testing it's probably fine, I reported this for
someone else who didn't know how to report, thx for the good work !

**Comment by theelk801** [comment]
It was previously bugged, they may have encountered the issue before it was fixed.
