### ISSUE TITLE
Button to download Art

### ISSUE THREAD

**Issue by L0gi** [magefree/mage#4859]
Was there any discussion on implementing this in the client itself? Doesn't that open xmage up to potential legal copyright issues? AFAIK rules to a game themselves can not be patented nor put under copyright, but design and art can, which could open us up to close down the project (although card names and rules templates could then be argued to be intellectual property...). Now that xmage seems to be getting attracting more users and WotC is getting ready for a new digital product release, wouldn't it be a good idea to rethink how to "cover our bases" to reduce risk of potential legal issues?

**Comment by JayDi85** [comment]
XMage doesn't distribute any WotC arts or other copyright items. It's clean. But WorC can ban and close ANY digital products, e.g. it's unofficial ban xmage and other open source products from MTG store/streams.

**Comment by JRHerlehy** [comment]
Image and symbol download already exist in the client.

What’s the question?

**Comment by allentiak** [comment]
Should this one be closed?
