### ISSUE TITLE
Numerous Card Mechanic Issues

### ISSUE THREAD

**Issue by dethdodge** [magefree/mage#4863]
Issue: Keldon Marauders is able to deal damage to creatures
- Probably an issue with new target errata.

Issue: Reality Smasher ability triggers when any creature is targeted
- Triggered when AI used Abzan Charm 'exile' mode targeting my Breaker of Armies

Issue: Occasionally able to cast Fiery Temper with madness trigger without spending mana
- I can't remember which card I used to trigger this issue with, but here are the only possibilities: Insolent Neonate, Putrid Imp, Faithless Looting, Tormenting Voice.

**Comment by dethdodge** [comment]
Issue: Unable to cast Sydri, Galvanic Genius
- The card can be discarded as part of costs, but it cannot be played at all.
Issue: Mindslaver doesn't let me control AI turns
- I am able to switch hands and see what's in their hand, but I'm not able to control any of the AI's actions in any way.

**Comment by GitHubMage** [comment]
I could not reproduce the Reality Smasher issue. At least in test mode with two manually controlled human players. Maybe it is an issue when the AI is involved?

**Comment by dethdodge** [comment]
Issue: Sunforger does not work properly
- Unable to target some spells, such as Tithe to cast from the library.
- Unable to target spells such as Lightning Helix or Warleader's Helix resulting in fizzled spells.

**Comment by jeffwadsworth** [comment]
Sunforger worked fine in my tests using your examples.
