### ISSUE TITLE
Issue with new card from dominaria

### ISSUE THREAD

**Issue by damonnnnnnnnnnnn** [magefree/mage#4867]
I can't use Rat Colony to its full effect because Xmage won't let me use any amount of Rat Colonies as the card states. I believe it was just overlooked when put into the game with the new Dominaria set

**Comment by theelk801** [comment]
This will be fixed in the next release.

**Comment by spjspj** [comment]
^^ This has implications for Brawl as well?  I didn't add it in as a relentless rats type allowance into the brawl check deck.

**Comment by theelk801** [comment]
It was handled in db077d6
