### ISSUE TITLE
Sagas get sacrifices when the trigger goes on the stack not when it leaves 

### ISSUE THREAD

**Issue by Piet-G** [magefree/mage#4875]
From the Dominaria Mechanics article:

"The chapter ability matching that new number will trigger. After the last chapter ability has left the stack, you'll sacrifice the Saga. For all the Sagas in Dominaria, that's chapter III. Most often, the ability leaves the stack because it resolved, but sometimes it'll be countered or leave the stack in some other way. No matter how it happens, as soon as that last chapter ability isn't on the stack, you sacrifice the Saga immediately as a state-based action."

This doesn't happen on Xmage

**Comment by theelk801** [comment]
So I've been working on this on and off (been busy lately) and I can't figure out a good way to make sure the SBA applies when the trigger leaves the stack. The current implementation checks for the trigger before it's actually been put on the stack, so it immediately kills the saga. It should instead detect whether the trigger is on the stack, and if it isn't, whether it's going to be and just hasn't yet.

**Comment by emerald000** [comment]
You'll have to check in the SBA if there is a Saga trigger on the stack or in the pool of triggers waiting to be put onto the stack but haven't yet since SBAs are checked before triggers are put on the stack.

**Comment by theelk801** [comment]
Right, I'm trying to do that but it's getting hairy very quickly.
