### ISSUE TITLE
Starting up multiple clients from a script with a different user

### ISSUE THREAD

**Issue by spjspj** [magefree/mage#4878]
In order to startup multiple clients at the moment you have to run each one separately and then login with a different user for each.  This has been necessary for testing things like 3 way games with planechase/edh etc and is relatively painful.  It would be nice to be able to pass in the user's name on the command line/as an argument when connecting (or maybe have a 'duplicate session with <DIFFERENT_USER_NAME>' (similar to how putty has it) as an option in the client.

**Comment by LevelX2** [comment]
Sure it's no fun but not that hard. I use it quite often for hunting down bugs.

**Comment by spjspj** [comment]
Agreed :)  But still nice to be able to have 3 (or 4) separate clients come up ready for testing with a single script.

**Comment by spjspj** [comment]
Implemented with #4916
