### ISSUE TITLE
Add Ability to Customize Hotkeys

### ISSUE THREAD

**Issue by JeffHoogland** [magefree/mage#488]
This is a feature request, not a bug report. If this is posted in the wrong spot please remove it and direct me to the correct location.

Would it be possible to add "custom hotkeys" to preferences? I've been playing XMage on my Chromebook and it lacks F keys, so I keep having to right click to use the F4/F9 functions.

**Comment by LevelX2** [comment]
Added some time ago.

**Comment by UberGamer01** [comment]
how are you running Xmage on a chrome book?

**Comment by JeffHoogland** [comment]
@UberGamer01 you need to install a Linux operating system in a chroot or on the actual hardware.
