### ISSUE TITLE
Planeswalker Redirect Issues

### ISSUE THREAD

**Issue by Aeronomotron** [magefree/mage#4884]
I was playing a game of commander, and there was an interaction that was unusual. Log Below:

4:09 AM: Aeronomotron activates: target permanent you control gains protection from white until end of turn. from Eight-and-a-Half-Tails [6ac] targeting Elspeth Tirel [8b0] 
4:09 AM: Attacked player: Aeronomotron
4:09 AM: Attacker: Stoneforge Mystic [d93] (1/2) unblocked
4:09 AM: Attacker: Bastion Protector [846] (3/3) unblocked
4:09 AM: Stoneforge Mystic [d93] deals 1 damage to Elspeth Tirel [8b0]
4:09 AM: Bastion Protector [846] deals 3 damage to Elspeth Tirel [8b0]
4:09 AM: Elspeth Tirel [8b0] is put into graveyard from battlefield

Based on the log, it's as if planeswalker redirect is still being used. I assume this is probably being worked on, but I don't know if this was still a legal interaction pre-Dominaria. Since Elspeth had Protection from white, which includes preventing damage, and the source of damage being the white creatures,  then by that logic, the damage shouldn't have happened. If the official ruling is that the damage is no longer from a white permanent, because it gets redirected from the player, which has no color identity, then that makes more sense. Just seeing what's up with this. Thanks for the help, and thanks for bringing us Xmage!

**Comment by GitHubMage** [comment]
With the pre-Dominaria rules giving a planeswalker protection from a color prevents all damage from sources of that color. when damage is redirected the source's color will not change. So what you experienced is probably a bug.

However this will be irrelevant with the rules change. But I don't know if the new rules implementation is already in progress and what the status is. Maybe someone can clear this up for us.

**Comment by spjspj** [comment]
@Aeronomotron Was there a mycosynth lattice or other similar effect in play?  Or were they black from say being tokens made by the scarab god?  The damage from the direct attackers if they were white should have been prevented (as you said).

**Comment by Zerrisx** [comment]
Planeswalker Redirection is no longer a thing, so I'm considering this obsolete until re-reported.
