### ISSUE TITLE
Permanent Priority Skip

### ISSUE THREAD

**Issue by SuneEnough** [magefree/mage#4885]
Sometimes, in my experience, most commonly after a rollback, a player can lose the ability to hold priority, even on that player's own turn, for the rest of the game. I don't personally know how to track this down, and it seems to happen randomly.

**Comment by jack-the-BOSS** [comment]
Yep, known issue. It's in the tracking issues list for the current version and I think there are four more open issues about it. Not sure if anyone is working on it.

**Comment by LevelX2** [comment]
The problem is, there is no known way to reproduce it in dev environment.

**Comment by Zerrisx** [comment]
Duplicate of #4309
