### ISSUE TITLE
Dragging sideboard cards while sideboarding in the middle of a match creates duplications causing deck validity errors

### ISSUE THREAD

**Issue by tself55** [magefree/mage#4888]
<img width="2489" alt="screen shot 2018-04-30 at 2 50 25 pm" src="https://user-images.githubusercontent.com/38866471/39444740-be52335e-4c86-11e8-918c-0e8da863a793.png">

On the Mac client, dragging cards in the deck editor screen during side boarding can duplicate the card in your deck causing deck validity errors for too many cards in sideboard / too many copies of a single card in deck+sideboard.

**Comment by tself55** [comment]
0 acknowledgement from devs?

**Comment by JayDi85** [comment]
Can't reproduce that bug. All grabs works fine. Can you explain step by step?

**Comment by Zerrisx** [comment]
Have never seen this myself - dragging cards results in odd effects, but not outright duplication.  Closing without better steps to reproduce.
