### ISSUE TITLE
unable connect to server. server is likely offline

### ISSUE THREAD

**Issue by spocey** [magefree/mage#4889]
i have been getting this message for days and don't really know what to do have looked at forums to try to find out what to do any help?
logs below:

Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=384m; sup
port was removed in 8.0
INFO  2018-04-30 16:29:52,547 Starting MAGE server version 1.4.29V3
                                         =>[main] Main.main
INFO  2018-04-30 16:29:52,547 Logging level: INFO
                                         =>[main] Main.main
INFO  2018-04-30 16:29:52,877 Loading extension packages...
                                         =>[main] Main.main
INFO  2018-04-30 16:29:52,877 Done.
                                         =>[main] Main.main
INFO  2018-04-30 16:29:52,877 Loading cards...
                                         =>[main] Main.main
INFO  2018-04-30 16:30:06,301 DB: need to add 18 new cards
                                         =>[main] CardScanner.scan
INFO  2018-04-30 16:30:06,316 Done.
                                         =>[main] Main.main
INFO  2018-04-30 16:30:06,332 Updating user stats DB...
                                         =>[main] Main.main
INFO  2018-04-30 16:30:06,425 Done.
                                         =>[main] Main.main
INFO  2018-04-30 16:30:06,566 Config - max seconds idle: 600
                                         =>[main] Main.main
INFO  2018-04-30 16:30:06,566 Config - max game threads: 10
                                         =>[main] Main.main
INFO  2018-04-30 16:30:06,566 Config - max AI opponents: 15
                                         =>[main] Main.main
INFO  2018-04-30 16:30:06,566 Config - min usr name le.: 3
                                         =>[main] Main.main
INFO  2018-04-30 16:30:06,566 Config - max usr name le.: 14
                                         =>[main] Main.main
INFO  2018-04-30 16:30:06,566 Config - min pswrd length: 8
                                         =>[main] Main.main
INFO  2018-04-30 16:30:06,566 Config - max pswrd length: 100
                                         =>[main] Main.main
INFO  2018-04-30 16:30:06,566 Config - inv.usr name pat: [^a-z0-9_]
                                         =>[main] Main.main
INFO  2018-04-30 16:30:06,581 Config - save game active: false
                                         =>[main] Main.main
INFO  2018-04-30 16:30:06,581 Config - backlog size    : 200
                                         =>[main] Main.main
INFO  2018-04-30 16:30:06,581 Config - lease period    : 5000
                                         =>[main] Main.main
INFO  2018-04-30 16:30:06,581 Config - sock wrt timeout: 10000
                                         =>[main] Main.main
INFO  2018-04-30 16:30:06,581 Config - max pool size   : 300
                                         =>[main] Main.main
INFO  2018-04-30 16:30:06,581 Config - num accp.threads: 2
                                         =>[main] Main.main
INFO  2018-04-30 16:30:06,581 Config - second.bind port: -1
                                         =>[main] Main.main
INFO  2018-04-30 16:30:06,581 Config - auth. activated : false
                                         =>[main] Main.main
INFO  2018-04-30 16:30:06,581 Config - mailgun api key :
                                         =>[main] Main.main
INFO  2018-04-30 16:30:06,581 Config - mailgun domain  :
                                         =>[main] Main.main
INFO  2018-04-30 16:30:06,581 Config - mail smtp Host  :
                                         =>[main] Main.main
INFO  2018-04-30 16:30:06,581 Config - mail smtpPort   :
                                         =>[main] Main.main
INFO  2018-04-30 16:30:06,581 Config - mail user       :
                                         =>[main] Main.main
INFO  2018-04-30 16:30:06,581 Config - mail passw. len.: 0
                                         =>[main] Main.main
INFO  2018-04-30 16:30:06,581 Config - mail from addre.:
                                         =>[main] Main.main
INFO  2018-04-30 16:30:06,581 Config - google account  :
                                         =>[main] Main.main
INFO  2018-04-30 16:30:09,733 Started MAGE server - listening on 0.0.0.0:17171/?
serializationtype=jboss&maxPoolSize=300  =>[main] Main.main

**Comment by JayDi85** [comment]
It's a local server logs and it's fine. No need to fix it. What you want to do? 
 * If you want to connect to your local server then run client from launcher and connect to `localhost` (button `L`);
 * if you want to connect to official server (xmage.de) then run client and connect to it. No need to launch local server from launcher.

**Comment by spocey** [comment]
i cant connect to xmage.us shoulda made that more clear am i doing something wrong or is it just not working

**Comment by JayDi85** [comment]
[US server was closed](https://www.reddit.com/r/XMage/comments/8d1891/hey_guys_we_know_the_us_server_is_down_we_dont/). Use xmage.de. If you can't see connection dialog on client start up then need to disable auto-connect option. [Instruction to fix auto-connect](https://github.com/magefree/mage/issues/4461#issuecomment-361108597).

**Comment by spocey** [comment]
thanks that explains this
