### ISSUE TITLE
Xmage 'Can not find free port for use'

### ISSUE THREAD

**Issue by Joesalmon1985** [magefree/mage#4898]
I don't even know where to start with this error. I'm 100% sure it isn't my firewall as I've tried disabling it and setting up port forwarding to my xmage machine on ports 17171 and 17172 (those are the ones xmage uses right?) but it hasn't helped.

Xmage was running fine until last week, not long after the second update for Dominaria came out.

I do use Ubuntu and wonder if that could be causing the problem.

I've tried using nmap to scan which ports are free on my laptop which I run xmage on and get the following response 

Starting Nmap 7.01 ( https://nmap.org ) at 2018-05-04 11:18 BST
Nmap scan report for localhost (127.0.0.1)
Host is up (0.000047s latency).
Not shown: 989 closed ports
PORT     STATE SERVICE
22/tcp   open  ssh
80/tcp   open  http
110/tcp  open  pop3
139/tcp  open  netbios-ssn
143/tcp  open  imap
445/tcp  open  microsoft-ds
631/tcp  open  ipp
993/tcp  open  imaps
995/tcp  open  pop3s
3306/tcp open  mysql
9050/tcp open  tor-socks
Device type: general purpose
Running: Linux 3.X|4.X
OS CPE: cpe:/o:linux:linux_kernel:3 cpe:/o:linux:linux_kernel:4
OS details: Linux 3.8 - 4.0
Network Distance: 0 hops

**Comment by JayDi85** [comment]
Are you try connect to official servers? [US server was closed](https://www.reddit.com/r/XMage/comments/8d1891/hey_guys_we_know_the_us_server_is_down_we_dont/). Use xmage.de. If you can't see connection dialog on client start up then need to disable auto-connect option. [Instruction to fix auto-connect](https://github.com/magefree/mage/issues/4461#issuecomment-361108597) (it's have hints for windows and mac, but linux use same settings store).

**Comment by LevelX2** [comment]
https://www.slightlymagic.net/forum/viewtopic.php?f=70&t=16400&p=169617&hilit=Can+find+free+port+for+use#p169617

**Comment by Joesalmon1985** [comment]
Yeah using xmage.de

I think I've already looked at that thread but can't check from phone. I'm at work at the mo but will check Sunday
