### ISSUE TITLE
Leonin Arbiter & Wood Elves - ETB search allowed?

### ISSUE THREAD

**Issue by rystan** [magefree/mage#4907]
![2018-05-06 23_29_13-xmage client_ 1 4 29v4 server_ 1 4 29v4](https://user-images.githubusercontent.com/6609665/39684638-5083ec64-518b-11e8-966e-96caa0f0af99.png)

I had Leonin Arbiter (https://scryfall.com/card/c17/64) which prevents searching of libraries.

The computer AI had 3 forests in play, and cast Wood Elves (https://scryfall.com/card/cma/170) which has an ETB trigger to search for a forest and put into play tapped.  The AI did not have the mana available to pay the Arbiter's restriction bypass and yet it searched for and put into play a forest.

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.
