### ISSUE TITLE
If a modal spell has only one available mode show always ability picker when new option is set

### ISSUE THREAD

**Issue by magenoxx** [magefree/mage#491]
I just noticed that I can't choose a mode for Mizzium Mortars when opponent has creatures with hexproof only. So game engine suggests to pay overload cost immediately without going to "choose mode" dialog.
I thought at that time that was some sort of improvement  as previously (long ago) you could choose cast it without overload to just found out by yourself that there was no legal target on battlefield.

BUT just now I tried to play Hydroblast without any spell in the stack and it allows me to choose between modes, and among them "Counter target spell if it's red". How is that? What is the difference?

As for me I vote for being able to choose modes always. Mostly because of having "Cancel" mode among others. If we have a case like I had with Overload and Mortars, opponent would see my card immediately in the stack otherwise. And it also brings feeling of a bug as you need time to realise it is not because of no legal target for first mode of Mortars.

See screenshots:
![image 09-08-14 at 10 17](https://cloud.githubusercontent.com/assets/1684275/3865265/44614884-1f8d-11e4-96cc-97b8323c3d42.png)

![image 09-08-14 at 10 19](https://cloud.githubusercontent.com/assets/1684275/3865268/4f1a5f36-1f8d-11e4-8380-5ad0b3b69b7b.jpg)

**Comment by JayDi85** [comment]
No more actual (illegal modes hides from choice dialog).
