### ISSUE TITLE
Nullmage Shepherd is blocking the game when casted

### ISSUE THREAD

**Issue by mfalcier** [magefree/mage#4911]
I've played 2 game this evening, and both of them were ended up blocked, with no F2 option.

Here there are 2 screenshots of me casting **Nullmage Shepherd** and then an ability triggers.

Screen 1: https://gyazo.com/5a331b75727dba8cd7b5fd0d982232e3
Screen 2: https://gyazo.com/aa35907bf855708f15420dc1db120c90

I don't know if **Nullmage Shepherd** is the real problem or just him with a triggered ability.

**Comment by LevelX2** [comment]
I was not able to reproduce the problem yet. Nullmage Shepherd itself seems innocent.

The screenshots don't show all permanents on the battlefield. To know all permanents on the battlefield could help to find the cause of the problem.

**Comment by mfalcier** [comment]
Have you tried casting it with some permanent on the battelfield which trigger an ability?

**Comment by Zerrisx** [comment]
Cannot reproduce; not certain this is fixed, but it does need more information to track down.
