### ISSUE TITLE
Confusing Prompts for Vicious Offering

### ISSUE THREAD

**Issue by ruler501** [magefree/mage#4913]
Vicious offering asks you if you want to sac a creature for the kicker cost and then immediately asks you to Choose a creature without clarifying that you should be choosing target creature not the creature to sacrifice. Since this mistake will often not get caught till after mana is paid it isn't possible to cancel without a rollback.

**Comment by JayDi85** [comment]
Fixed via 23627dcbe58bafc05bd2a25d1114598f2c7602f5

![shot_190617_192350](https://user-images.githubusercontent.com/8344157/59617105-c623b080-9136-11e9-8470-723b60ed94c8.png)

![shot_190617_192332](https://user-images.githubusercontent.com/8344157/59617107-c6bc4700-9136-11e9-9ff2-438e4e255912.png)
