### ISSUE TITLE
Dire Fleet Daredevil : Legendary Sorcery Interaction

### ISSUE THREAD

**Issue by FastTadpole** [magefree/mage#4921]
Unable to cast stolen Legendary Sorcery from exile with Dire Fleet Daredevil, even with Legendary Creature. See attached image below for an instance of this. 

![xscreenie](https://user-images.githubusercontent.com/13674016/39795998-36b8dd9e-5311-11e8-94ed-64893613737e.jpg)

Also, not sure on this but Dire Fleet Daredevil could use Phyrexian mana and pay life as an option when casting cards from exile, e.g. Dismember not sure if that is how it is supposed to work. May be related to the following report.

>dire fleet daredevil + wizard's lightning: i cast wizard's lightning from opponent's graveyard with dire fleet daredevil (no other creatures, no wizards on board) and it cost R, like with cost reduction applied (reported by Rybsson / 2018-04-23 19:11:07.715).
https://github.com/magefree/mage/issues/4864

**Comment by emerald000** [comment]
I'm guessing xmage is checking your opponent's battlefield instead of your own.

And the Phyrexian mana part is correct. You have still have to pay the mana cost of Dismember and you can pay 2 life instead of Phyrexian mana.
