### ISSUE TITLE
Tyrant's Familiar not behaving properly

### ISSUE THREAD

**Issue by novadaemon1** [magefree/mage#4930]
Tyrant's Familiar should read "Lieutenant — As long as you control your commander, Tyrant's Familiar gets +2/+2 and has "Whenever Tyrant's Familiar attacks, it deals 7 damage to target creature defending player controls."

But it is bugged. It forces me to deal 7 damage to any creature. When my Scion is transformed into Tyrant's Familiar, the game forces my transformed Scion of the Ur Dragon to deal 7 damage to itself if no other creatures are on the field. It should not even be possible to do such a thing.

**Comment by theelk801** [comment]
fixed with 25b10c4
