### ISSUE TITLE
Mana Web doesn't tap land properly

### ISSUE THREAD

**Issue by ArtSabintsev** [magefree/mage#4937]
Mana Web's card text:

```
Whenever a land an opponent controls is tapped for mana, tap all lands that player controls that could produce any type of mana that land could produce.
```

I just played this land against a mono-green player, and they were able to tap more than one green-producing land afterwards because Mana Web's tap ability went on the stack instead of instantly tapping their other green-producing lands.

**Comment by ArtSabintsev** [comment]
This is the same problem that was reported in #4746

**Comment by emerald000** [comment]
Mana Web is supposed to go on the stack. There's even a ruling on Gatherer: The opponent can tap their lands for mana in response to Mana Web’s ability triggering. (2008-04-01)

**Comment by ArtSabintsev** [comment]
Oracle also says:

```
When a land an opponent controls is tapped for mana, this card checks which types of mana (white, blue, black, red, green, or colorless) that land could produce using any of its mana abilities, not merely the one the player just used. Then it checks which lands that player controls have abilities that could produce any of those types of mana. Then it taps those lands.
```

Which ones happens first?

**Comment by emerald000** [comment]
Mana Web's trigger goes on the stack. Both players get priority to cast instants/activate abilities (such as tapping more lands). Once the trigger resolves, the lands sharing a type all become tapped (the part you linked).

Closing this since it seems like it was a rules misunderstanding.
