### ISSUE TITLE
game gets stuck hard when trying to double-block

### ISSUE THREAD

**Issue by derlhurgoyf** [magefree/mage#4951]
In a 3-player FFA (one player dropped during mulligan) I was attacked by a swole Uril and tried to double-block to soak up some damage. However the game locked up hard and wouldn't let me conclude the second block. After that not even conceding would help it.
[game-10ff8096-347f-4fe5-9144-fee0d114fd85.json.zip](https://github.com/magefree/mage/files/2020030/game-10ff8096-347f-4fe5-9144-fee0d114fd85.json.zip)

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.
