### ISSUE TITLE
Casting Oblation on The Locust God shouldn't trigger its ability

### ISSUE THREAD

**Issue by derlhurgoyf** [magefree/mage#4959]
In a slightly strange game where I reanimated a Locust God from a player which then disconnected but for some strange reason got to keep the god, another opponent played oblation on it. I was able to draw to cards but also got two insects which shouldn't happen, as the god is shuffled into the library first.

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.
