### ISSUE TITLE
Sylvia and Khorvath seem bugged

### ISSUE THREAD

**Issue by Stafy1** [magefree/mage#4972]
I can't pin down the problem but I made a deck with them and I randomly get this error while playing a permanent. I've been able to reproduce this in three different games of commander.

https://imgur.com/a/QjEa46k

**Comment by theelk801** [comment]
Has it always been with Oath of Lieges around?

**Comment by Stafy1** [comment]
I don't remember if I had Oath on the first instance, but I got it on the other two. Do you want me to test the deck without it?

**Comment by theelk801** [comment]
No, I know what the problem is.

**Comment by Stafy1** [comment]
So was it caused by the Oath or it's something with the partners? I need to know if I can keep playing the deck for the time being. Thanks for the help.

**Comment by theelk801** [comment]
It's a problem with any card that references things your team controls. I was a lazy and didn't test that it worked when I implemented it.
