### ISSUE TITLE
Decks larger than 1001 cards cut off without warning

### ISSUE THREAD

**Issue by NoaGleason** [magefree/mage#4977]
I'm trying to make a deck with every card implemented on XMage for a fully random cube, but XMage seeming loads only 1001 cards from it, both in the deck viewer and when used as a cube. I could see all the cards when I was making the cube, but when I try to load it only 1001 get loaded, and it's seemingly clustered by set. I have 1 gig allocated so I'm pretty sure it's not a memory problem.

Here's the list: https://pastebin.com/R9tf1mX6

Support for 1001+ card decks would be great, but at least an error about the deck being too large would be nice.

**Comment by spjspj** [comment]
This was a deliberate decision made at about the same time people were spamming the server with long messages.  Too keep the use of resources on the server somewhat down, the possibility of people spamming the server with arbitrarily large decks was removed (changed to the 1000 you mentioned).

**Comment by NoahGleason** [comment]
Okay, that makes sense. Could I add an "all cards" option as one of the built-in cubes to get around this, or does that have the same problem of overloading the server?

**Comment by Zerrisx** [comment]
This seems like not a bug - there needs to be some limit; 1,000 is as good as any.
