### ISSUE TITLE
Neheb, the Eternal's ability breaks the game, requires rollback, creates infinite loop and forcefully ends game

### ISSUE THREAD

**Issue by AricHaldan** [magefree/mage#4982]
After Neheb the eternal attacks and it's ability triggers in the second main phase you get this error:

An error has occurred on the MAGE server. Your last action will be rollbacked.

Game exception occurred: java.lang.NullPointerException
Server version: 1.4.30V1
mage.watchers.common.PlayerLostLifeWatcher.getAllOppLifeLost(PlayerLostLifeWatcher.java:85)
mage.abilities.dynamicvalue.common.OpponentsLostLifeCount.calculate(OpponentsLostLifeCount.java:51)
mage.abilities.dynamicvalue.common.OpponentsLostLifeCount.calculate(OpponentsLostLifeCount.java:45)
mage.cards.n.NehebTheEternalManaEffect.produceMana(NehebTheEternal.java:103)
mage.abilities.effects.common.ManaEffect.getMana(ManaEffect.java:71)
mage.cards.n.NehebTheEternalManaEffect.apply(NehebTheEternal.java:95)
mage.abilities.AbilityImpl.resolveMode(AbilityImpl.java:199)
mage.abilities.AbilityImpl.resolve(AbilityImpl.java:186)
mage.abilities.TriggeredAbilityImpl.resolve(TriggeredAbilityImpl.java:102)
mage.game.stack.StackAbility.resolve(StackAbility.java:103)
mage.game.GameImpl.resolve(GameImpl.java:1424)
mage.game.GameImpl.playPriority(GameImpl.java:1374)
mage.game.turn.Step.priority(Step.java:87)
mage.game.turn.Phase.playStep(Phase.java:210)
mage.game.turn.Phase.play(Phase.java:115)
mage.game.turn.Turn.play(Turn.java:153)
mage.game.GameImpl.playTurn(GameImpl.java:883)
mage.game.GameImpl.play(GameImpl.java:792)
mage.game.GameImpl.start(GameImpl.java:756)
mage.server.game.GameWorker.call(GameWorker.java:60)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)

after the action is rollbacked you get the error again and you are asked by the client whether to draw the game by infinite looping, if you click no, you get this error: 

Game exception occurred: mage.MageException: Iterated player priority after game exception too often, game ends!
Server version: 1.4.30V1
mage.game.GameImpl.playPriority(GameImpl.java:1397)
mage.game.turn.EndPhase.playStep(EndPhase.java:67)
mage.game.turn.Phase.play(Phase.java:115)
mage.game.turn.Turn.play(Turn.java:153)
mage.game.GameImpl.playTurn(GameImpl.java:883)
mage.game.GameImpl.play(GameImpl.java:792)
mage.game.GameImpl.start(GameImpl.java:756)
mage.server.game.GameWorker.call(GameWorker.java:60)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)

and someone wins apparently at random. If you click yes, it sets it as a draw as normal.

**Comment by theelk801** [comment]
This was fixed with c8d58ef
