### ISSUE TITLE
Card info popup not closed and shown over the table view after timeout followed by reconnect 

### ISSUE THREAD

**Issue by Codingboy** [magefree/mage#4983]
I had internet problems, got a timeout and when I finally reconnected to the server the last infobox i was over did not close whatever I did. Even when switching to deckeditor:
https://gyazo.com/3345106fb86735fb06e5582562f4d08f

**Comment by JayDi85** [comment]
Fixed by ee2741c7a74e48f00769e61e0414050aab186b89
