### ISSUE TITLE
chrome mox adds additional mana in every phase

### ISSUE THREAD

**Issue by GAMEster52** [magefree/mage#4986]
when playing dragon stompy i recognized that chrome is adding random mana, every time you play something it adds a mana sometimes and also after a while it starts adding mana in every phase. see the screenshots.
first picture shows how i have mana in pool without that i tapped anyting, second one i have five mana in my pool after casting the dragon... i think that every action you do adds one mana, but not sure...
![mana bug](https://user-images.githubusercontent.com/36176270/40707558-4e21ffec-63f1-11e8-9739-6dbaf5af8a91.jpg)
![mana bug2](https://user-images.githubusercontent.com/36176270/40707563-505d1bc0-63f1-11e8-9d65-56125c54fdfd.jpg)

**Comment by LevelX2** [comment]
It's fixed with the next update.
