### ISSUE TITLE
Chrome Mox is Super Bugged

### ISSUE THREAD

**Issue by Aeronomotron** [magefree/mage#4989]
I was playing Chrome Mox in a commander game, and I noticed that when Chrome Mox is untapped, and something is put on the stack, it adds one color of the imprinted cards color to your mana pool.

Gatherer Link:  http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=420596

For example, I play Chrome Mox from in my hand, and I exile Dark Ritual. I then put a Sol Ring on the stack. The action of putting Sol Ring on the stack, for an unknown reason, adds a black mana to my mana pool when Chrome Mox is untapped. I then click the "Cancel" button, and can do this an unlimited amount of times, and produce any amount of black mana. This can, of course, be used to end games on turn one if someone takes advantage of this, because it is essentially cheating. Something else that causes this effect to trigger is changing phases. Even if the owner of the chrome mox doesn't take advantage of this mana, at the end of every phase, the user has to click "Yes" to pass the phase. This makes the game slow down, and makes auto-yielding awkward.

Thanks to the Programmers and Developers of Xmage! You guys are awesome!

**Comment by LevelX2** [comment]
Look at the list of not yet released fixes before you bother yourself with creating a detailed error ticket for altready fixed issues.
https://github.com/magefree/mage/wiki/Features-and-fixes-not-released-yet

**Comment by Aeronomotron** [comment]
Ok, I was unaware of this. Thanks for letting me know!
