### ISSUE TITLE
Toothy, Imaginary Friend doesn't work correctly with effects like Cloudshift

### ISSUE THREAD

**Issue by theelk801** [magefree/mage#4991]
The game doesn't properly store LKI when something changes zones more than once during resolution.

**Comment by starsignsvirgo** [comment]
+1

Toothy draw trigger doesn't draw cards for when it leaves the zone from Ghostly Flicker

**Comment by jeffwadsworth** [comment]
I didn't think that LKI worked either until I tested the code.  It actually works when called in a specific way.  Checking this card out.

https://www.slightlymagic.net/forum/viewtopic.php?f=70&t=23164&start=105#p230710
