### ISSUE TITLE
Goad not working properly when only 2 players left

### ISSUE THREAD

**Issue by edcarter** [magefree/mage#4999]
Steps to reproduce:

1. Start a multiplayer game (3 players)
2. One of the players looses or leaves the game
3. Have one player attack the other with Grenzo, Havoc Raiser
4. Grenzo controller goads a creature of the remaining opponent (off of Grenzo's damage trigger)
5. On the opponents turn they are unable to attack the Grenzo player with the goaded creature

If there are only 2 players left and a creature is goaded, it should be able to attack the player which did the goading since it is unable to attack any other player.

I haven't had the chance to reproduce with other goad cards, but I know for sure the bug is present with Grenzo.

Same: #5283

**Comment by edcarter** [comment]
Looking at https://github.com/magefree/mage/blob/36a9e12bfc7c8a7a313f602780f4d6f6c86e0d48/Mage/src/main/java/mage/abilities/effects/common/combat/GoadTargetEffect.java#L48

The assumption that the goaded creature cannot attack the player doing the goading is incorrect.

**Comment by edcarter** [comment]
There maybe should be a `CantAttackYouIfAble()` effect, which doesn't let the creature attack that player unless it has no other options?

**Comment by edcarter** [comment]
Just to further affirm: the rulings on disrupt decorum states:

`
If the creature doesn’t meet any of the above exceptions and can attack, it must attack a player other than the controller of the spell or ability that goaded it if able. It the creature can’t attack any of those players but could otherwise attack, it must attack an opposing planeswalker (controlled by any opponent) or the player who goaded it.
`

http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=433266

**Comment by Zerrisx** [comment]
Yep, still broken.  Ew.

**Comment by JayDi85** [comment]
@Zerrisx can you add steps to reproduce that bug or it's same as topic starter?

**Comment by Zerrisx** [comment]
Same as topic starter. Steps:

1) Start three person free-for-all game with range all 
2) give one of the AIs a Phage, instantly losing them the game
3) give the remaining AI a Grenzo, and myself a Flying Men
4) Grenzo attacks, chooses to goad Flying Men
5) on my turn, with flying men as my only creature, it skips my entire combat step and flying men does not attck

**Comment by Zerrisx** [comment]
Verified fixed by 335acd4
