### ISSUE TITLE
Card numbers in mtg-cards-data.txt are wrong

### ISSUE THREAD

**Issue by theelk801** [magefree/mage#5003]
So a lot of the older cards in mtg-cards-data.txt have the wrong numbers, not to mention incorrect oracle text. I'm gonna do a rebuild of the whole file, but I need to make sure I do it correctly and don't remove anything that shouldn't be removed.

**Comment by Zerrisx** [comment]
Should this be pulled out into a task list so we have a sense of how many more pieces there are to work on for this?

**Comment by JayDi85** [comment]
That's file uses for card code generation only and other old perl scripts (I think it uses for set implementation list like #6608 too). And it must be generated from scryfall or mtgjson data source. So there is nothing to fix manually.

**Comment by xenohedron** [comment]
@theelk801 Is this still relevant and/or planned?

**Comment by theelk801** [comment]
It should probably still be done, I've just never gotten around to it because most of the cards it impacts are already implemented

**Comment by JayDi85** [comment]
No needs to fully support `mtg-cards-data.txt` in actual state, only preview sets can be relevant. All other data can be extracted from mtgjson in verify tests.

**Comment by xenohedron** [comment]
There are still a small number of unimplemented cards from early sets, which don't have the right collector numbers. I don't know that the verify test catches that discrepancy, I think it just flags duplicate collector numbers, which is not quite the same thing.

Also, updates to oracle text mean that updating the file could still be valuable. There can occasionally be misleading templating, or mistakes on initial import from previewed spoilers.
