### ISSUE TITLE
Strange bugs with manual mana assignment

### ISSUE THREAD

**Issue by Zzooouhh** [magefree/mage#5009]
For example, I try to cast Godsire with 3 white, 3 red and 4 colorless floating in my mana pool (none are conditional): if I click the first red mana in my pool, what happens is that I assign 1 red and 1 colorless. If I click colorless afterwards, 2 colorless get assigned. The rest of the mana assignment works as normal. Also, other times I first clicked white and it assigned red instead, etc.

It seems to be a bug or several bugs causing the mana pool to incorrectly iterate through multiple mana types after unlocking one of them, even after the relevant mana type was already found - presumably because there's a missing check(s) for the unlocked mana's type somewhere, or the pool is getting locked too late, but I'm having trouble specifically locating the culprit.

An explanation, just for clarity's sake since it's probably not obvious at first - mana pool's unlocked mana is the type of mana you "clicked" in the game GUI under your avatar. If the mana is getting assigned automatically (tapping lands during paying a spell/ability's cost), it never gets unlocked.

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.
