### ISSUE TITLE
Bugs with removals and tapped creatures.

### ISSUE THREAD

**Issue by Imperialistmtg** [magefree/mage#5012]
Fatal push, abrade, fumigate etc are not working properly. Fatal push can't be cast, abrade can't target, fumigate didn't actually destroy!!

Creatures that enter the battlefield tapped, like Dread Wanderer, if you bring them back from graveyard to the battlefield they enter untapped!!

**Comment by DParkside** [comment]
Seems to be targeted removal period isn't working. Path to exile, Mind Sculpter's -1 ability, etc. No Hexproof was in play in the scenario's I encountered.

**Comment by jottunn** [comment]
played 2 games in which fumigate didn't destroy any creatures, in both cases the creatures were all white

**Comment by theelk801** [comment]
Did you control any creatures when Fumigate resolved or was it just opposing creatures?

**Comment by jottunn** [comment]
I did not

**Comment by theelk801** [comment]
Alright, that fits with the hypothesis that it's a static filter problem.

**Comment by LevelX2** [comment]
Entering not tapped is handled here:
#5010
Targeting problem herer:
#4984

So I close this issue.
