### ISSUE TITLE
Sagas and Forbidden Orchard

### ISSUE THREAD

**Issue by rilonian** [magefree/mage#5013]
There are 2 separate bugs:

- Sagas, when the last (3rd) ability triggers, go directly to the graveyard, which is incorrect: when the 3rd ability resolves, they go to the graveyard (if not, that system could be abused for example with Mending of Dominaria).
- Forbidden Orchard produces 2 triggers when it is tapped for mana.

**Comment by theelk801** [comment]
Which Saga was it?

**Comment by rilonian** [comment]
Mirari Conjecture is the one I know it doesn't work

**Comment by theelk801** [comment]
I couldn't recreate the issue with the Saga, the issue may have happened before the patch where I fixed it. Lemme know if it happens again though.
