### ISSUE TITLE
Uniformity in card distribution of boosters (print run emulation)

### ISSUE THREAD

**Issue by Sedictious** [magefree/mage#5015]
Disclaimer: I have no actual idea about how the game works, I'm just reporting a problem a non-programmer friend mentioned, so bare with me if I make any mistakes.

Now, it seems like the amount of each card type in any given booster is bounded, whereas in Xmage the choice is completely random (e.g. you can open a pack containing 8 green cards and no spells).

**Comment by JayDi85** [comment]
Yep, xmage use simple random unique cards to add too boosters of every rarity/land type:
https://github.com/magefree/mage/blob/36a9e12bfc7c8a7a313f602780f4d6f6c86e0d48/Mage/src/main/java/mage/cards/ExpansionSet.java#L201
https://github.com/magefree/mage/blob/36a9e12bfc7c8a7a313f602780f4d6f6c86e0d48/Mage/src/main/java/mage/cards/ExpansionSet.java#L175

Can you explain real life booster pack algorithm (someday I read about different pages and cut off it to randomize)?

**Comment by LevelX2** [comment]
The problem is there is not so much public available information how the booster cards are mixed together. So it's hard to create a accurate simulation of this. For some sets the print runs are known. But this alone makes it not easy to do it for this sets. 

Look this for Origins booster print run information.
https://www.reddit.com/r/lrcast/comments/3dkr40/magic_origins_anatomy_of_a_booster_pack_common/

**Comment by Sedictious** [comment]
I searched a little bit more on rarity distribution, and you are right in that most information is not public and even speculated to change across sets. That being said, there seems to be a pattern both concerning rarity and color, which is further verified by the information available on [print sheets](https://mtg.gamepedia.com/Print_sheet#Relation_between_print_sheets_and_booster_contents). 

Anyway, I'm not sure whether adding any sort of rules in booster openings is one of your concerns, but I could try to work on it.

**Comment by theelk801** [comment]
I've never drafted on Xmage so I've never been sure how well it emulates real life pack collation. The only thing I've really done with it is make sure that Dominaria packs always have a legend, and even that isn't necessarily implemented correctly with regards to how it's done in paper.

If you wanted to start working on something and open a pull request I'd be glad to look at it.

**Comment by JRHerlehy** [comment]
Yeah, we’d need to know the layout of sheets to implement simple collation emulation. Those usually don’t come out for a while with uncut sheets being the biggest source of information from GPs after the set releases.

**Comment by theelk801** [comment]
The thing is that we don't have to do much to improve upon it. Just finding ways to ensure things like every color being represented can go a long way.

**Comment by spjspj** [comment]
The biggest thing is probably not having foils though to be honest.

**Comment by rystan** [comment]
As a just throwing it into the discussion, I just bought some BBD packs over the weekend and it seems that at least with the new “Partner with” mechanic if you receive one of the partners in a pack, the partner is included as well.  Which makes total sense for the 2-headed giant format for drafting.

**Comment by theelk801** [comment]
I was planning on implementing the M19 land thing, I just hadn't gotten around to it yet. I'll do it now.

**Comment by quercitron** [comment]
I modified booster generation to reduce number of boosters with skewed color distribution (pull request #5169). With this modification we reject:

1. Boosters where some color is not represented.
2. Boosters where 3 or more uncommon/rare cards have the same color.

To make reads during a draft less obvious such boosters are not always rejected, but with a certain probability (currently 0.8 for both cases).

What do you think about this change?

**Comment by Zerrisx** [comment]
Looks like this was either resolved, or needs a more specific follow-up.  We could look into more specific analysis like https://www.reddit.com/r/lrcast/comments/3dkr40/magic_origins_anatomy_of_a_booster_pack_common/, but it seems the collation process has been changed often enough that you'd need to do that analysis for each set, which seems prohibitively difficult unless WotC officially releases their rules.

For now, I'm considering this good enough.

**Comment by theelk801** [comment]
There's actually a lot of information from [this website](https://www.lethe.xyz/mtg/collation/) that we could use, I may try and actually implement it at some point.

**Comment by Zerrisx** [comment]
> 
> 
> There's actually a lot of information from [this website](https://www.lethe.xyz/mtg/collation/) that we could use, I may try and actually implement it at some point.

Far enough - if we do that, probably worth creating a new full tracking enhancement issue and/or project for it.
