### ISSUE TITLE
Reconnect does not work correctly

### ISSUE THREAD

**Issue by LevelX2** [magefree/mage#502]
Currently the reconnect to games / tournaments does not work correctly.

If I test it local by killing a client it works.
But on public server it does not work.

It seems like connection lost is handled like a manual disconnect.

Any ideas / suggestions are welcome.

**Comment by LevelX2** [comment]
Another problem with reconnect I identified is that the for every reconnect the card db check for new cards is done. That slows down the server especially if multiple clients get disconnected at the same time and try to reconnect. Than the h2 db requests are probably a bottleneck.
And for the reconnects the db check can be skipped anyway. 
For normal connect I will add an option if the check should be done.

**Comment by goesta** [comment]
I'll close this issue because it seems to be outdated.
