### ISSUE TITLE
Xmage takes 10 minutes to load

### ISSUE THREAD

**Issue by HR19** [magefree/mage#5022]
If I rename the folder where I keep all the card images, it loads in a few seconds.  Then I rename the images folder back and everything works fine.  If I leave all the images as is, it takes over 600 seconds (according to the launcher) to start.  I tried redownloading all the card images, but it's the same story.  This problem started in April or so.  No problems before that.

**Comment by JayDi85** [comment]
It's your antivirus/antimalware (AV) software problem. Add xmage folder to exclusion's list in your AV software.

**Comment by HR19** [comment]
Well, between the latest update and changing my antivirus program, it works fine now.

**Comment by Zerrisx** [comment]
We resolved it.  Beautiful!
