### ISSUE TITLE
Non-replicable banding damage assignment bug vs AI only

### ISSUE THREAD

**Issue by Zzooouhh** [magefree/mage#5030]
I've attacked with a band against an AI opponent and he blocked with three creatures - his creatures assigned no damage (I didn't even get a choice to distribute the damage). I've tried it several times in the same game with two different bands (Gorm the Great + Benalish Hero, Savannah Lions + Benalish Hero) and neither combination made the damage assignment work. Replicating the same scenario with a human opponent, damage assignment worked as normal. Later I've started the same game again against a computer and damage assignment strangely works as proper again.

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.
