### ISSUE TITLE
Xmage says "Invalid auth token"

### ISSUE THREAD

**Issue by AC99MD** [magefree/mage#5038]
I forgot my account's password and I received an email in my inbox with an auth token to copy and paste in the section to reset password. Pasted it and wrote a new password twice as requested and every time Xmage says "Invalid Auth Token". I tried to write it manually and to copy it another time, but the game didn't accept it. Then I tried to click again "email a auth token", but when copied and pasted the new code it failed again, even the second time.... I don't know how to change my account's password then. Please help me. Thanks in advance

Problem solved.

**Comment by Zerrisx** [comment]
Problem Solved!  Hooray.
