### ISSUE TITLE
Somehow start on Ubuntu 18.04 is not possible

### ISSUE THREAD

**Issue by kohldampfer** [magefree/mage#5042]
I just downloaded the xmage launcher. Then, the first time, the program told me, that it seems that I startet xmage launcher for the first time on that computer and this was true. So, the xmage launcher downloaded some stuff. After that, the button "Launch Client" did not enable. So I closed the launcher and started again and now I see this:

![xmage-error-1](https://user-images.githubusercontent.com/20419801/41685884-48a8e948-74e2-11e8-8e28-699572dd68ac.png)

Here is the whole text in that black text box:

```
Reading config from http://xmage.de/xmage/config.json
XMage folder:  /home/......../xmage
XMage Launcher version installed:  0.3.8
XMage Launcher version available:  0.3.8
Java version installed:  
Java version available:  1.8.0_172
Java not found
XMage version installed:  1.4.30V4 (2018-06-10)
XMage version available:  1.4.30V4 (2018-06-10)

```

**Comment by spjspj** [comment]
Run the following in a new terminal:
```
cd ~/xmage 
  # Assuming this is the directory /home/......../xmage 
which java
 # if this has any results, note the results as 'step 2'
cd mage-client
  # Assuming you got results in step 2...
java -Xms256m -Xmx512m -XX:MaxPermSize=256m -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled -jar ./lib/mage-client-1.4.30.jar
```

**Comment by JayDi85** [comment]
Press `update` button in launcher to download xmage client. If you can't then report logs here.

**Comment by Zerrisx** [comment]
Looks like this was resolved and/or obsolete
