### ISSUE TITLE
bash: ./startMage.sh: /bin/sh^M: bad interpreter: no such file or directory

### ISSUE THREAD

**Issue by kohldampfer** [magefree/mage#5043]
When starting the file xmage/startMage.sh, I get this error message:

> bash: ./startMage.sh: /bin/sh^M: bad interpreter: no such file or directory

On Ubuntu, solution would be to run the command

`dos2unix xmage/startMage.sh`

**Comment by kohldampfer** [comment]
The same applies to the files

> xmage/mage-client/startClient.sh
> xmage/mage-server/startServer.sh

**Comment by Renegade1079** [comment]
Are you trying to play on PC or Mac

**Comment by kohldampfer** [comment]
@Renegade1079 Ubuntu 18.04

**Comment by TMiguelT** [comment]
I had the same issue on Ubuntu. It's weird, because I would have thought unix shell scripts should always use unix line endings!

**Comment by Zerrisx** [comment]
@JayDi85 @arcox 

Was this fixed by #6812?

**Comment by JayDi85** [comment]
Yes, it must fix that problem.
