### ISSUE TITLE
Is there a way to add a cancel action option?

### ISSUE THREAD

**Issue by Renegade1079** [magefree/mage#5044]
Is there any way to add a cancel action option? For instance when using Ashnod's Altar, if you mistakenly click on it you are forced to sacrifice a creature with no option to cancel it

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.
![image](https://user-images.githubusercontent.com/59861365/87175994-0eac8f80-c29f-11ea-9c6e-d9961b121441.png)
