### ISSUE TITLE
V6 bugs with Collective Brutality and Wear//Tear

### ISSUE THREAD

**Issue by BudzOnXmage** [magefree/mage#5070]
When Collective Brutality is cast with escalate no pop up shows opponents hand shows. Works fine when only using 1 mode.
Wear//Tear bugs opponents after being cast. They cannot see any pop up window nor any changes on the board, although the log still works.

**Comment by ingmargoudt** [comment]
Collective Brutality::59

 Effect effect = new DiscardCardYouChooseTargetEffect(filter, TargetController.ANY);
       
I am not sure if TargetController.ANY is correct.

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.
