### ISSUE TITLE
Vampire Neonate :: Both players lose 1 life when each player controls one on the field

### ISSUE THREAD

**Issue by FastTadpole** [magefree/mage#5071]
Happened. Works normally when one player controls a neonate but when another player has one too each activation of the ability that is supposed to drain ends up making both players lose 1 life.

**Comment by theelk801** [comment]
I couldn't recreate this, can you give any more details?

**Comment by FastTadpole** [comment]
Full game log:
[20180625_040956_Two Player Duel_1.txt](https://github.com/magefree/mage/files/2135289/20180625_040956_Two.Player.Duel_1.txt)

**Comment by theelk801** [comment]
I don't see any problems, it looks like it functioned correctly.

**Comment by FastTadpole** [comment]
You're right we both saw it happen but forgot about the Vashino trigger it seems thinking it was 20-20 then 19-19 but it was actually 18-20 then went 19-19. Sorry about the red herring.

**Comment by theelk801** [comment]
It's all good.
