### ISSUE TITLE
Vedalken Engineer pop up bug

### ISSUE THREAD

**Issue by EllNubNub** [magefree/mage#5076]
the menue that would pop up to ask what mana color you would like to produce when using the engineer seems to pop up every phase, ability, or spell that goes on the stack and is extremely annoying.

**Comment by 18ths** [comment]
The problem still exists in 1.4.31V4 and yep, it's really freaking annoying. Even tapping a single land to pay for other spells opens the popup. I also noticed Vedalken Engineer have to be untapped and not have summoning sickness.

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.
