### ISSUE TITLE
Foe-Razer Regent dies on entering battlefield, before fighting

### ISSUE THREAD

**Issue by SpikesCafe-google** [magefree/mage#5081]
6:04 PM: computerb casts Foe-Razer Regent [ba7]
6:04 PM: computerb puts Foe-Razer Regent [ba7] from stack onto the Battlefield
6:04 PM: Ability triggers: Foe-Razer Regent [ba7] - When Foe-Razer Regent [ba7] enters the battlefield, you may have Foe-Razer Regent [ba7] fight another target creature you don't control. - targeting Mentor of the Meek [734] 
6:04 PM: Foe-Razer Regent [ba7] died
6:04 PM: Foe-Razer Regent [ba7]: Fighting effect has been fizzled.

I've seen this happen a few times now, doesn't seem to be a fluke. It used to work. The only prior issue is it also used to get +1/+1 counters put on it even if it lost the fight and ended up in the graveyard.

**Comment by kevinwshin** [comment]
I couldn't reproduce this bug. Did it happen every time? Does it still happen?

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.
