### ISSUE TITLE
Hour of Promise didn't search but gave ETB triggers

### ISSUE THREAD

**Issue by HR19** [magefree/mage#5085]
So here's everything I know about what happened.  I cast Hour of Promise from my library with Sunbird's Invocation and it resolved perfectly.  Some time later I cast it again from my hand and copied it with Wort the Raidmother.  When both the copy and the original resolved this time, it didn't let me search my library, and it didn't get any new lands.  The log said that I moved two Mountains from the battlefield to the battlefield, and it triggered my relevant ETB abilities.

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.
