### ISSUE TITLE
installer not running

### ISSUE THREAD

**Issue by galenr150** [magefree/mage#5110]
download the installer, try to run it, computer just asks what you want program to open it with, none of which seem to actually run it :/ i've looked at a few other issues and cant find what i need to do to fix it. im on windows 10, and i dont have a whole lot of know how with technical stuff, so i'll need a step by step of what to do

**Comment by rkdnc** [comment]
Do you have Java installed?

**Comment by galenr150** [comment]
i assumed i did before i tried, but i installed it after it didnt work and that didnt seem to help

**Comment by galenr150** [comment]
i mean, i can try to reinstall it if ya think that would help

**Comment by rkdnc** [comment]
Reinstall Java, and run the .jar file with Java.

**Comment by galenr150** [comment]
not giving that as an option. i dont have any option to 'run' it, just 'open' and it gives me the following programs as options: internet explorer, notepad, paint, windows media player, word, wordpad, and office XML handler. it just doesnt let me run the jar in any way

**Comment by rkdnc** [comment]
[Try this](https://stackoverflow.com/questions/394616/running-jar-file-on-windows)

**Comment by JayDi85** [comment]
Create `run.cmd` in launcher folder with `java -jar XMageLauncher-0.3.8.jar ` and run it (that's folder must contain `XMageLauncher-0.3.8.jar` file, use text editor to create and edit `run.cmd`).
