### ISSUE TITLE
Blood Moon Superceding Spreading Seas

### ISSUE THREAD

**Issue by argonplatypus** [magefree/mage#5143]
Just played a match where a player cast a blood moon against me.  The next turn I cast a Spreading Seas on a non-basic land so I could have more blue sources.  Blood Moon was still effecting it and it only tapped for red.  Drew another Spreading Seas later and it acted the same way.

**Comment by csbrown09** [comment]
Although it loses it's other mana abilities and land types to Blood Moon, Blood Moon does not make the land a basic land. It is still a nonbasic land and will still be a mountain regardless of spreading seas interaction. If Blood Moon were to make it a basic land your thought process works. This is not what Blood Moon does however.

3/16/2018 | This effect doesn’t affect names or supertypes. It won’t turn any land into a basic land or remove the legendary supertype from a legendary land, and the lands won’t be named “Mountain.”
-- | --

**Comment by argonplatypus** [comment]
That's correct IF Blood Moon is played and a land already has Spreading Seas attached to it.  If you cast Spreading Seas to a land already affected by Blood Moon it becomes an Island and taps for blue.  The timestamp is what determines the effect.

https://www.mtgsalvation.com/forums/magic-fundamentals/magic-rulings/788692-spreading-seas-vs-blood-moon

**Comment by jeffwadsworth** [comment]
This will be fixed with https://github.com/magefree/mage/issues/6236.  Soon.  Lots to test.

**Comment by jeffwadsworth** [comment]
![FixedSoon](https://user-images.githubusercontent.com/1496996/73676250-ae734b00-4679-11ea-9031-cf7d84168332.jpg)

**Comment by JayDi85** [comment]
@jeffwadsworth is that fixed?

**Comment by Zerrisx** [comment]
Looks fixed to me.
