### ISSUE TITLE
Extra counters with Skyrider Patrol 

### ISSUE THREAD

**Issue by Unconquerable1** [magefree/mage#5148]
When using the ability of Skyrider Patrol it works correctly the first turn/first activation. However, on each subsequent turn you get an additional counter to distribute upon activation. (Example below)
![image](https://user-images.githubusercontent.com/41218786/42719480-f21d6f72-86e3-11e8-9171-fa73de9cf11e.png)

Example:
Turn 6: Cast Skyrider Patrol and pay GU at the beginning of combat for the triggered ability, triggered ability goes on the stack, select another creature to get the counter and flying, then that creature gets a single +1/+1 counter and flying until end of turn. 
Turn 7: pay GU at the beginning of combat for the triggered ability, triggered ability goes on the stack 2 times, select another creature to get the counter and flying, that creature gets a single +1/+1 counter and flying, select another creature (can be the same or different creature) to get the counter and flying, that creature gets a single +1/+1 counter and flying.
Turn 8: pay GU at the beginning of combat for the triggered ability, triggered ability goes on the stack 3 times...
Note: You still only have to pay the cost of GU once and it still triggers an additional time on each subsequent turn/activation. 
Hope this helps. Keep up the great work!

**Comment by theelk801** [comment]
this has been fixed
