### ISSUE TITLE
Swords to Plowshare made me lose life

### ISSUE THREAD

**Issue by spjspj** [magefree/mage#5149]
Had a shrieking drake which was a -16/1  
I lost 16 life when someone swords'd it :(

3/16/2018 | If the creature’s power is negative, its controller doesn’t lose or gain life.
-- | --

**Comment by ingmargoudt** [comment]
PlayerImpl.gainLife does not handle negative life properly, it just adds the negative value to the current life total...

**Comment by ingmargoudt** [comment]
`` if (!canGainLife || amount == 0) {
            return 0;
        }``
