### ISSUE TITLE
FlashbackAbility needs redesign

### ISSUE THREAD

**Issue by LevelX2** [magefree/mage#515]
Flashback needs to be redesignt as alternate casting costs. Currently it's not possible to cancel a modal spells cast with Flashback and getting tapped mana sources untapped. They stay tapped.
And the static ability that exiles a flashbacked spell has to be a replacement effect.

From the forum:
When I used Snapcaster Mage on my Cryptyc Command and canceled the mods, so Icould recast it my lands did not untap. Actually if you cancel any spell while using snapcaster on it (paying the cost of fashback) your lands don't untap and the manda is considerated as spent.

Because of the cast for noMana handling other problems are created:
#596

**Comment by ee10bt** [comment]
+1. Would this problem be resolved if you chose targets before paying mana, like for normal spells?
