### ISSUE TITLE
Java download from oracle website is broken

### ISSUE THREAD

**Issue by JayDi85** [magefree/mage#5173]
On windows with fresh install you can't download java from oracle website. It's require oracle account to download it:
https://www.oracle.com/technetwork/java/javase/downloads/java-archive-javase8-2177648.html

XMage launcher can't download it with error:
```
ERROR 2018-07-27 22:38:17,619 Error:
 =>[SwingWorker-pool-1-thread-2] DownloadTask.download
java.io.FileNotFoundException: http://download.oracle.com/otn-pub/java/jdk/8u172-b11/a58eab1ec242421181065cdc37240b08/jr
e-8u172-windows-x64.tar.gz?AuthParam=1532716827_acfc07862d1eb2dce914cdd4c049af40
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.lang.reflect.Constructor.newInstance(Unknown Source)
        at sun.net.www.protocol.http.HttpURLConnection$10.run(Unknown Source)
        at sun.net.www.protocol.http.HttpURLConnection$10.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
```

Fresh example and [instruction for manual java download](https://github.com/magefree/mage/issues/5172#issuecomment-408503860):
#5172

**Comment by JayDi85** [comment]
@LevelX2 must fix it by edit config.json on xmage.de

From discord channel by LunarNightShade:

> The Java download should be able to be fixed with a slight change to the URL in the http://xmage.de/xmage/config.json file if you can pass it along to update it.
> 
> Launcher URL:       http://download.oracle.com/otn-pub/java/jdk/8u172-b11/a58eab1ec242421181065cdc37240b08/jre-8u172-windows-x64.tar.gz
> Oracle's 8u172 URL: http://download.oracle.com/otn/java/jdk/8u172-b11/a58eab1ec242421181065cdc37240b08/jre-8u172-windows-x64.tar.gz
> 
> 
> They archived 8u172 on the release of 8u181. -pub just needs to be removed from the config.json file to stick with 8u172.
> 
> Or, this is the URL for 8u181.
> http://download.oracle.com/otn-pub/java/jdk/8u181-b13/96a7b8442fe848ef90c96a2fad6ed6d1/jre-8u181-windows-x64.tar.gz

**Comment by LevelX2** [comment]
Updated the config file to 8u181.
