### ISSUE TITLE
Black client console (can't download java)

### ISSUE THREAD

**Issue by Vi0l3** [magefree/mage#5180]
![xmage problems](https://user-images.githubusercontent.com/41849968/43363288-59acdddc-92c7-11e8-8806-1461011aff2e.PNG)
any way to fix this? please help!

**Comment by JayDi85** [comment]
Download java files manually. [Instructions](https://github.com/magefree/mage/issues/5172#issuecomment-408503860).

**Comment by Vi0l3** [comment]
i did download them manually, thats the only way i was able to start xmage

**Comment by JayDi85** [comment]
If that help or not? If not then report your logs from `xmage_launcher.log` and `..\xmage\mage-client\mageclient.log` files.

**Comment by Vi0l3** [comment]
im going to redo it. do i install the .exe or .gz?

**Comment by JayDi85** [comment]
You need gz, version 172 -- download it and UNZIP to launcher folder (follow link's instruction).

**Comment by Vi0l3** [comment]
it downloads as a white file. there is no option to unzip

**Comment by JayDi85** [comment]
Install 7Zip to work with archives:
https://www.7-zip.org

**Comment by Vi0l3** [comment]
![capture shit](https://user-images.githubusercontent.com/41849968/43363567-1d94845c-92cd-11e8-9b55-02d52c2649e0.PNG)

**Comment by spjspj** [comment]
Don't use the launcher :)  Next step: Don't use the f*#%ing launcher!  It's complex and weird.  Step 3: Watch https://www.youtube.com/watch?v=FL89GFJv0_A and then

**Comment by JayDi85** [comment]
Java download was fixed and it's work now.
