### ISSUE TITLE
Can't see library window for some abilities

### ISSUE THREAD

**Issue by dadrop42** [magefree/mage#5188]
hello people! i dont now why i have this things happening
many time when i have to look in the library (field of ruin, settle, fetch ecc) evrything block and i just cant click nothing but end of turn... 
sometimes with no reason in both the display of the players... both we are waiting for each other and no one can do nothing else...is that normal?
thanks

**Comment by JayDi85** [comment]
Nope, it's not normal. If need a library to choose then you must see library window. Try another deck with different cards. And ensure that's you use latest xmage version and play on official server (some old xmage clients contain that bugs with invisible windows).

**Comment by JayDi85** [comment]
All wrong windows order and incompatible version bugs are no more actual and GUI works fine.
