### ISSUE TITLE
Recast spells seem to keep their previous targets

### ISSUE THREAD

**Issue by Zzooouhh** [magefree/mage#5189]
I've cast Utter End via Sunforger, then later on I've shuffled Utter End from my GY back into my library via Elixir of Immortality. I cast Utter End again via Sunforger, but this time I don't get prompted to select a target - it keeps the old target, a permanent that's already in exile, and thus the recast Utter End fizzles.

**Comment by Zerrisx** [comment]
Presumably fixed by linked code changes
