### ISSUE TITLE
Xmage Black Screen, won't launch

### ISSUE THREAD

**Issue by jontang303** [magefree/mage#5190]
I don't know how to fix this problem. I tried JayDi85 manual download but it did not work out for me. Does anybody know how to fix this issue on Mac ?

![screen shot 2018-08-02 at 5 29 15 pm](https://user-images.githubusercontent.com/42047890/43619803-8eaab58e-969d-11e8-8f3d-f913f1153c83.png)

![screen shot 2018-08-02 at 5 27 42 pm](https://user-images.githubusercontent.com/42047890/43619768-6c9dd912-969d-11e8-8044-a23421678bdc.png)
![screen shot 2018-08-02 at 5 28 23 pm](https://user-images.githubusercontent.com/42047890/43619773-6e73e2c2-969d-11e8-9793-8f8352fbf2fe.png)
![screen shot 2018-08-02 at 5 29 53 pm](https://user-images.githubusercontent.com/42047890/43619778-71b6479a-969d-11e8-86c9-d3374459e236.png)

**Comment by jontang303** [comment]
Hey JayDi85, I don't know what I am doing wrong. I put the java in the java folder and changed installed.properties. 
![screen shot 2018-08-03 at 9 55 42 am](https://user-images.githubusercontent.com/42047890/43646802-e1e51bf2-9703-11e8-9ac5-f364bcc9f396.png)
![screen shot 2018-08-03 at 9 56 04 am](https://user-images.githubusercontent.com/42047890/43646807-e3d9645e-9703-11e8-9c53-7d3e3a898a8f.png)

**Comment by JayDi85** [comment]
Look at [instructions here](https://github.com/magefree/mage/issues/5172#issuecomment-408503860) (I've updated it). XMage uses it's own java version. That's why java must be in xmage folder.  Download 172 tar.gz file from java.com site (or use [that link for macos](https://yadi.sk/d/xNOgZNGm3ZhpiM)) and unzip it to `..\**xmage**\java\` folder (you must get `..\xmage\java\jre1.8.0_172.jre` file).

**Comment by jontang303** [comment]
Hey JayDi85, Thanks for your help. I have tried this process many times and it still has not worked. I had xmage working up until the last update. after the last update, my java in the java folder was removed. So now I did the manual process so Java is in the folder but that is not working
![screen shot 2018-08-03 at 11 56 05 am](https://user-images.githubusercontent.com/42047890/43652872-70b52b8c-9714-11e8-9f97-26359c6d0073.png)
. The screen is still black Is there something else that could be causing Xmage not to launch?

![screen shot 2018-08-03 at 11 43 52 am](https://user-images.githubusercontent.com/42047890/43652239-9b88b0b0-9712-11e8-8a72-f49a86c67d6a.png)
![screen shot 2018-08-03 at 11 33 19 am](https://user-images.githubusercontent.com/42047890/43652242-9d1635e2-9712-11e8-91eb-253b64bdf154.png)
![screen shot 2018-08-03 at 9 56 04 am](https://user-images.githubusercontent.com/42047890/43652243-9ef7576a-9712-11e8-83bd-f3f303124ed3.png)
![screen shot 2018-08-03 at 11 40 42 am](https://user-images.githubusercontent.com/42047890/43652248-a47c97fe-9712-11e8-8179-1753ba9e552d.png)
![screen shot 2018-08-03 at 11 56 05 am](https://user-images.githubusercontent.com/42047890/43652906-860a1e7a-9714-11e8-84b0-74cc3fdd2284.png)

**Comment by JayDi85** [comment]
Fix your `installed.properties`: it's must contain line `java.version=1.8.0_172`:

![shot_180803_200106](https://user-images.githubusercontent.com/8344157/43653047-fc53518a-9757-11e8-9197-3e9b8b1c56f1.png)

**Comment by jontang303** [comment]
I get what you mean now. I needed to put it under java. version line, sorry about that. I have it working now. Thank you very much for your time and help.
