### ISSUE TITLE
xmage launcher say the site is offline and the client won't start

### ISSUE THREAD

**Issue by GD1112** [magefree/mage#5191]
even manually starting from the files doesn't work, the log is as follows:
```
août 03, 2018 4:40:53 AM java.util.prefs.WindowsPreferences <init>
WARNING: Could not open/create prefs root node Software\JavaSoft\Prefs at root 0x80000002. Windows RegCreateKeyEx(...) returned error code 5.
INFO  2018-08-03 04:40:53,433 Starting MAGE client version 1.4.30V7                                                      =>[main] MageFrame.main 
INFO  2018-08-03 04:40:53,436 Logging level: INFO                                                                        =>[main] MageFrame.main 
org.h2.jdbc.JdbcSQLException: Exception opening port "0" (port may be in use), cause: "java.net.BindException: Address already in use: JVM_Bind" [90061-187]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.util.NetUtils.createServerSocketTry(NetUtils.java:194)
	at org.h2.util.NetUtils.createServerSocket(NetUtils.java:160)
	at org.h2.server.TcpServer.start(TcpServer.java:232)
	at org.h2.tools.Server.start(Server.java:474)
	at org.h2.engine.Database.startServer(Database.java:780)
	at org.h2.engine.Database.open(Database.java:636)
	at org.h2.engine.Database.openDatabase(Database.java:266)
	at org.h2.engine.Database.<init>(Database.java:260)
	at org.h2.engine.Engine.openSession(Engine.java:60)
```
thank you guys for at least reading!

**Comment by JayDi85** [comment]
It's a wrong localhost IP settings, PC name, etc:
 * Open `cmd` from command line and enter "ping localhost" -- you must get your computer name and ip = 127.0.0.1. Report that screen here.

**Comment by GD1112** [comment]
here is the screen i got 
![image](https://user-images.githubusercontent.com/42052680/43645489-5c9fc40e-9732-11e8-87fe-259300644e7d.png)

**Comment by JayDi85** [comment]
You need to add localhost address to `hosts` file:
 * Open `notepad` with admin access;
 * Open file from `C:\Windows\System32\drivers\etc\hosts` for edit;
 * If you can't see that file then copy and paste full path in `open` menu from notepad;
 * Add new line at the end: `127.0.0.1 localhost`;
 * Save and restart xmage.

![shot_180803_180040](https://user-images.githubusercontent.com/8344157/43646895-2a34e8a4-9747-11e8-8bd4-2cd866caf7c3.png)

**Comment by GD1112** [comment]
So i have done exactly what you told me but it still displays me the same error message, do you have any other potential fix?

**Comment by JayDi85** [comment]
Do the following to fix ipv6 in java:
 * Create `run.cmd` file in launcher folder;
 * Open it and insert line in text editor: `java -Djava.net.preferIPv4Stack=true -jar XMageLauncher-0.3.8.jar`;
 * Run launcher by that command file (double click on it);
 * Open settings menu, java tab and edit client java options: `-Xms256m -Xmx1024m -Djava.net.preferIPv4Stack=true`;
 * Run client and check.

![shot_180803_195030](https://user-images.githubusercontent.com/8344157/43652526-895ff602-9756-11e8-8c1a-0cbf2835e6e0.png)

**Comment by GD1112** [comment]
thanks a lot, thanks to you i can go back to spicy brewing ^^
