### ISSUE TITLE
Teferi's Protection/phasing during combat bug

### ISSUE THREAD

**Issue by Zzooouhh** [magefree/mage#5200]
I've attacked with a creature, opponent cast an overloaded Cyclonic Rift during my declare attackers step, I've cast Teferi's Protection in response. Opponent declared no attackers, but the one attacking creature (now phased out) still went on and dealt 2 damage to the opponent.

**Comment by Stafy1** [comment]
I can confirm, it just happened to me. Enemy alpha strikes me, I rift, he casts teferi's protection in response and still kills me

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.
