### ISSUE TITLE
No tables appear

### ISSUE THREAD

**Issue by sh3pard173** [magefree/mage#5204]
I recently had to manually install the xmage files because of the java not found thing.
Before I fixed it I could go through the statMageWin7.bat thing but I got no tables so I assumed the issue was that java wasnt found.
I updated to 1.8.0_181 and i though that would fix it but it didnt

https://docs.google.com/document/d/1fMefy571QqdJohS7b-ncGeJ_mU2KvFBN4MglGUpHRbk/edit?usp=sharing

here's a 39 page google doc of my launcher log and client log
https://docs.google.com/document/d/1fMefy571QqdJohS7b-ncGeJ_mU2KvFBN4MglGUpHRbk/edit?usp=sharing

help plx ;-;
also yeah i havnt downloaded images yet

[68747470733a2f2f692e6779617a6f2e636f6d2f62626462316432326132323466373732396232393630663832336165316164652e706e67](https://user-images.githubusercontent.com/42158727/43747449-a730a772-999e-11e8-8cb0-d5b4c0b5ce03.png)

chat was being toxic

**Comment by LevelX2** [comment]
I don't believe this is a java thing.

Did you try to activate all the filters at the top to see if open tables are shown then?

**Comment by Zerrisx** [comment]
This seems to be resolved and/or obsolete
