### ISSUE TITLE
Wildest Dreams claims there are no valid targets when valid targets exist

### ISSUE THREAD

**Issue by Woogachaka** [magefree/mage#5208]
[Wildest Dreams](https://scryfall.com/card/kld/174/wildest-dreams) Claims there are no valid targets in the graveyard even when cards are present. This message is given upon attempting to cast the spell

**Comment by jeffwadsworth** [comment]
Works fine for me in the latest build.  What did you choose for XX?

**Comment by Woogachaka** [comment]
I used 3 for X ( so 6 total), this was in the context of commander with Rosheen Meanderer as the commander and paying part of the cost

**Comment by jeffwadsworth** [comment]
Do you remember the cards in your graveyard?

**Comment by Woogachaka** [comment]
Sorry for the delay, Not totally sure, but I think they were [Beast Within](https://scryfall.com/card/bbd/190/beast-within), [Evolving Wilds](https://scryfall.com/card/cm2/249/evolving-wilds), and [Grow From the Ashes](https://scryfall.com/card/dom/164/grow-from-the-ashes)

**Comment by JayDi85** [comment]
Works fine.
