### ISSUE TITLE
Split Cards and library search

### ISSUE THREAD

**Issue by Nuxuas** [magefree/mage#5210]
If my deck has a split card (such as wear // tear or flesh // blood) when I try to fetch something from my deck (like using a fetch land) the deck window does not open. The same happens when I have a split card in the sideboard and use Glittering Wish.

**Comment by LevelX2** [comment]
Do you use the newest V7 client version?

Sometimes there are minor interface problems between client/server that can exactly cause such problems.

**Comment by Nuxuas** [comment]
@LevelX2  The top bar says I am running 1.4.30V7.

**Comment by JayDi85** [comment]
Works fine in current version
