### ISSUE TITLE
Sith Sorcerer logic is wrong

### ISSUE THREAD

**Issue by rkfg** [magefree/mage#5214]
Here's what the card looks like:
![Sith Sorcerer](http://i.imgur.com/Pq37iop.jpg)

But the text says something else: `Hate — When {this} enters the battlefield, if an opponent lost life from a source other than combat damage this turn, draw a card.`. There's another Sith Sorcerer looking like this:
![Sith Sorcerer 2](https://mtgcardsmith.com/view/complete/full/2017/11/7/1510085140142229.png)

But it has different mana cost and the effect is totally different (though it triggers when it enters the battlefield).

**Comment by xenohedron** [comment]
Custom sets really should have a json source text that can be checked as part of a verify test...
