### ISSUE TITLE
The Artifact Ward of Bones does not work

### ISSUE THREAD

**Issue by player-354764547** [magefree/mage#5216]
Ward of Bones rules text: "Each opponent who controls more creatures than you can't cast creature spells. The same is true for artifacts and enchantments. Each opponent who controls more lands than you can't play lands."

I had 0 creatures and XMage AI went on playing creatures again and again ...

**Comment by quercitron** [comment]
Cannot reproduce the problem. Probably it is some AI specific bug.

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.
