### ISSUE TITLE
Game asks to pick trigger order, but no window with triggers shows up and game freezes

### ISSUE THREAD

**Issue by derlhurgoyf** [magefree/mage#5219]
[20180814_163317_Commander Free For All_1.txt](https://github.com/magefree/mage/files/2288360/20180814_163317_Commander.Free.For.All_1.txt)
[game-0513dde0-f2d3-4e0d-9baa-062882219ed8.json.zip](https://github.com/magefree/mage/files/2288362/game-0513dde0-f2d3-4e0d-9baa-062882219ed8.json.zip)

I played Rise of the Dark Realms with a lot of creatures triggering on EtB, one of which is Gray Merchant, killing one opponent while many other abilities from his creatures are on the stack. I press F10 to empty the stack and after sacrificing a creature to Merciless Executioner the game stops, asking me to pick triggers.

**Comment by JayDi85** [comment]
No more actual
