### ISSUE TITLE
Blade of the Bloodchief incomplete card

### ISSUE THREAD

**Issue by andrew-todaro** [magefree/mage#5225]
Blade of the Bloodchief appears to be unfinished. Card text on hover in xmage reads "Whenever a Creature dies,
Equip 1"
and no effect triggers when something dies. Blade of the Bloodchief's proper effect is "Whenever a creature dies, put a +1/+1 counter on equipped creature. If equipped creature is a Vampire, put two +1/+1 counters on it instead."
Card appears literally unfinished.

**Comment by Rewyn** [comment]
The card itself works (or has worked before at least), just the tooltip seems to be missing.

**Comment by andrew-todaro** [comment]
That may be; this is a second hand report from someone else in a match who mentioned it, didn't find it on github issues search so I went ahead and made this after checking that the text matched what was described. I do not *know* if the weapon in question does or does not work, and this was the EU server so I had my suspicions about what the other player might *mean*, but I reported the issue as it was communicated to me.

**Comment by theelk801** [comment]
the card's text is just missing for some reason, I fixed it
