### ISSUE TITLE
Yuriko's ninjutsu

### ISSUE THREAD

**Issue by Iwasrunningoutofnamesatthispoint** [magefree/mage#5226]
Yuriko has normal ninjutsu instead of commander ninjutsu, please fix it :)

**Comment by mzavaleta** [comment]
Hey guys, made lot of testing around yuriko, and indeed, removing that simple line of code (described on the referenced issue above) yuriko is behaving as expected.

**Comment by Iwasrunningoutofnamesatthispoint** [comment]
I am testing Yuriko, and she is still bugged.
You cant put her on the field at the end of the dmg phase.
