### ISSUE TITLE
Xantcha, Sleeper Agent prevents all creatures you control from attacking its owner

### ISSUE THREAD

**Issue by ninthworld** [magefree/mage#5235]
I had a Daxos of Meletis on the battlefield and was given a Xantcha, Sleeper Agent. When combat began on my turn, I was asked to select a player or planeswalker for Xantcha to attack. I rightly could not select its owner, and was force to attack the other player in the game. When I selected Daxos to attack, I asked me to select a player or planeswalker to attack. When I selected Xantcha's owner, Daxos was left untapped and not attacking. When I selected Daxos to attack and picked the other player, Daxos was tapped and attacking.

In Xantcha's code, the XantchaSleeperAgentAttackRestrictionEffect is applied to the AttacksEachCombatStaticAbility ability, so the canAttack method should only apply to Xantcha. Could it be that the applies(Permanent permanent, Ability source, Game game) method needs to check the permanent against the ability source permanent before returning true?

**Comment by jesusjbr** [comment]
You hit the bull's-eye. Sorry for this mistake, I didn't tested that scenario and my understanding on the effects wasn't perfect (bad combination).

**Comment by JayDi85** [comment]
Fixed by #5236
