### ISSUE TITLE
Yuriko's commander ninjutsu not working correctly

### ISSUE THREAD

**Issue by mzavaleta** [magefree/mage#5237]
Scenario:
Attacking with one creature and not blocked
Try to play Yuriko from commander zone but nothing happen when click on it.

**Comment by mzavaleta** [comment]
@LevelX2 Saw you implement this card, I'm new at and tried to look at your code but i'm lost to be honest.
Let me know if you have any hint and / or if i can help some how

**Comment by mzavaleta** [comment]
I think i Found the problem:
mage/abilities/keyword/NinjutsuAbility.java:203

removing that line should work fine.
tried to do a branch and submit a merge request but i didn't succeed and it's abit late here.
Hope you find useful.

CC: @theelk801

**Comment by Rewyn** [comment]
https://github.com/magefree/mage/issues/5226

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.
