### ISSUE TITLE
Kestia, the Cultivator cannot be cast for Bestow cost

### ISSUE THREAD

**Issue by rkdnc** [magefree/mage#5238]
User Aust from the Discord states they could not cast Kestia, the Cultivator from the command zone for it's bestow cost, and the bestow cost does not appear when trying to cast.

**Comment by messuped** [comment]
Bump, as this just happened to me

**Comment by rkdnc** [comment]
> Bump, as this just happened to me

Please refrain from 'bumping' issues, that is now how GitHub Issues works

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.
