### ISSUE TITLE
Wrong-game bug with the new "double click" feature

### ISSUE THREAD

**Issue by Zzooouhh** [magefree/mage#5239]
Double clicking a game entry in a server table calls up the incorrect game. I haven't quite found out the pattern, i.e. which game is selected relative to the highlighted game (the one I double clicked), but I've tried watching a Commander game only to enter a Limited lobby, and the other time I tried joining limited only to be assigned to a Standard duel. Clicking the Join/Watch button in the table however works normally just as before.

**Comment by LevelX2** [comment]
Maybe the list was updated exactly before the moment you clicked on the entry?

So you clicked on the new table standing now on the position of the table you intended to clik.

**Comment by JayDi85** [comment]
Fixed via 2bd5d0ddf6fc0d79c58ffd76c5575e9996cac963
