### ISSUE TITLE
Client bug

### ISSUE THREAD

**Issue by trintin** [magefree/mage#524]
Hi,
I was disconnected by server and it asked me to reconnect. I confermed and client froze. I couldn´t cloze it normally so I did it by Task Manger. I reopened XMage to connect again. After about minute I canceled connecting, thinking it is my Internet connection fault and click connect again. Client froze again, but I was able to move the window, see picture below what happened.
![xmagebug2](https://cloud.githubusercontent.com/assets/7190628/3970318/4cbd0128-27c9-11e4-9ff5-585595e89db7.png)
Anyway, I tryed a few more times, but still nothing. Has anything like this happened to you or it is just me?

**Comment by goesta** [comment]
I'll close this issue because it seems to be outdated but feel free to create a new one if this problem still exists.
