### ISSUE TITLE
Patron of the Nezumi damages the controller instead of the owner

### ISSUE THREAD

**Issue by DfourC** [magefree/mage#5241]
During a duel against the computer, I used Nighteyes the Desecrator to control an opponent's Sakura-Tribe Elder while I controlled Patron of the Nezumi. I sacrificed Elder to search for a land and put it onto the battlefield, but when Elder was put into my opponent's graveyard, Patron's ability caused _me_ to lose 1 life instead of the opponent. Patron's ability reads "Whenever a permanent is put into an opponent's graveyard, _that player_ loses 1 life."

**Comment by LevelX2** [comment]
Fixed by pull request.
