### ISSUE TITLE
Constant Error - "Unable to connect to server. Server likely offline." 

### ISSUE THREAD

**Issue by thedarkskull43** [magefree/mage#5244]
I’m trying to connect and it just won’t run, I’ve reinstalled Java and the program several times and I’ve tried to use an already open issues to fix it but no matter what I do I can’t get the program to work

**Comment by thedarkskull43** [comment]
That didn’t help I don’t have that in my registry at all

**Comment by JayDi85** [comment]
@thedarkskull43 if you want resolve your problem then need more info:
 * Is xmage launcher works fine and it downloads updates to latest version (v1)?
 * Report your latest client logs from `..\xmage\mage-client\mageclient.log`;
 * Can you run local server and connect to it? Run server and client from launcher, connect to it by `localhost` address.

**Comment by FancyLadies** [comment]
has this been resolved? I am also having the same problem. I can't seem to connect to localhost anymore. This occurred after the recent update. I can connect to other servers without issue.

**Comment by JayDi85** [comment]
@FancyLadies you must start local server from launcher:
 * restart your machine;
 * open luancher;
 * run server;
 * run client and try connect to localhost (use L button);
 * if can't then report latest client logs from: `..\xmage\mage-client\mageclient.log`.

**Comment by FancyLadies** [comment]
@JayDi85 tried your suggestion and still no luck. I get an error message on my server console: **Error: Could not find or load main class mage.server.Main**

Thanks for responding.

**Comment by JayDi85** [comment]
@FancyLadies 

1. You are try connect to local server (error from client logs: Error setting up client lease upon performing connect). You need to start your server first from launcher or use official server.

2. If you got "**Could not find or load main class**" then you are missing server files from xmage folder. Check server folder `..\xmage\mage-server` -- it's must contain files. If you can't see files then try to update by launcher. 

3. If you can't download update (server folder still empty) then try [that instructions](https://github.com/magefree/mage/issues/5280#issuecomment-416222227) to run launcher with ipv4 fix. Run it by command file and try to update.

If that's not help then report `xmage_launcher.log` file too.
