### ISSUE TITLE
Tournaments don't end correctly - stay in list of active tables

### ISSUE THREAD

**Issue by LevelX2** [magefree/mage#526]
Sometimes mainly tournaments are not removed from the list of active tables.
Problem with the draw games was reduced by last update.

But still there are circumstances that lead to hanging tournaments:

Example:
![sealedtournament](https://cloud.githubusercontent.com/assets/2066790/4408793/09ea7c38-44d7-11e4-9eb8-476c008932c0.jpg)

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.
