### ISSUE TITLE
1.4.31V1 naming wrong in update config, xmage.de is down

### ISSUE THREAD

**Issue by davidmfritz** [magefree/mage#5275]
The release of 1.4.31V1 is with a lower case "V" which makes the client not find the file to download.

**Comment by davidmfritz** [comment]
xmage.de isn't actually down, it has just insane response times. Also the naming convention of releases has always been with an upper case "V" from what I see.

**Comment by LevelX2** [comment]
Download ref is changed now to the correct release name. Thanks for pointing out.
