### ISSUE TITLE
C18 Varchild token creation *still* bugged.

### ISSUE THREAD

**Issue by Kerrus** [magefree/mage#5277]
Varchild now creates tokens successfully when dealing damage to a player. She just creates them under her controller's control, rather than the damaged player's control as her card text states.

**Comment by kevinwshin** [comment]
That was all my fault. I just misread the card. The new fix should be all functional. Hopefully it actually is.

**Comment by Kerrus** [comment]
STILL BUGGED.

**Comment by kevinwshin** [comment]
Could you give me more details? What situation are you experiencing that is incorrect and what should be happening instead?

**Comment by theelk801** [comment]
It's already been fixed with cf67c27

**Comment by jeffwadsworth** [comment]
This is still bugged.  The token's are created and controlled by the defender, but the token's are placed on the wrong battlefield.  I will add a picture soon.

**Comment by awjackson** [comment]
I can't reproduce this.
