### ISSUE TITLE
Improve the graveyard window

### ISSUE THREAD

**Issue by emerald000** [magefree/mage#528]
Right now, the graveyard window is annoying to use. If you play a graveyard-based deck, you cannot see your whole graveyard at one time. You also cannot keep the graveyard open while you play the game. Even using a card like Snapcaster Mage is annoying to use. Cast Mage. Open graveyard. Choose card. Close graveyard. Click OK. Open graveyard. Cast spell.

I think the graveyard window should be similar to the "revealed" window. You would be able to have it always opened if needed, to put it in a corner of the screen and to resize it.

I am not a great UI designer, but there has something that can be done to make it less annoying to use.

**Comment by LevelX2** [comment]
Done beyond 1.4.1v3
