### ISSUE TITLE
Estrids -1 with Ajani's chosen present

### ISSUE THREAD

**Issue by Rewyn** [magefree/mage#5285]
Using Estrid's -1 ability, while also controlling Ajani's Chosen, crashes the game and triggers a rollback.

<details>
  <summary>Crash report</summary>
  Game exception occurred: java.lang.NullPointerException
Server version: 1.4.31V1
mage.cards.a.AjanisChosenEffect.apply(AjanisChosen.java:79)
mage.abilities.AbilityImpl.resolveMode(AbilityImpl.java:173)
mage.abilities.AbilityImpl.resolve(AbilityImpl.java:160)
mage.abilities.TriggeredAbilityImpl.resolve(TriggeredAbilityImpl.java:76)
mage.game.stack.StackAbility.resolve(StackAbility.java:77)
mage.game.GameImpl.resolve(GameImpl.java:1398)
mage.game.GameImpl.playPriority(GameImpl.java:1348)
mage.game.turn.Step.priority(Step.java:61)
mage.game.turn.Phase.playStep(Phase.java:184)
mage.game.turn.Phase.play(Phase.java:89)
mage.game.turn.Turn.play(Turn.java:127)
mage.game.GameImpl.playTurn(GameImpl.java:856)
mage.game.GameImpl.play(GameImpl.java:765)
mage.game.GameImpl.start(GameImpl.java:729)
mage.server.game.GameWorker.call(GameWorker.java:34)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)
</details>

**Comment by JRHerlehy** [comment]
It’s looking for a spell ability. Which the token doesn’t have. Hummm...

**Comment by JayDi85** [comment]
Fixed via 2d387801a2abc8435dca7e61933ccbe13ef1cba5
