### ISSUE TITLE
Players lose priority on using "cheat" button for a non-active player

### ISSUE THREAD

**Issue by Zzooouhh** [magefree/mage#5289]
Start a local server with testmode on and press the cheat button for another player. The cheat button's effect resolves, but all players lose priority afterwards. This does not happen if you press your own cheat button.

**Comment by JayDi85** [comment]
I think cheat button for other player is unusable at all and must be disabled (I don't remember details but someday founded dirty code with that). Users must use commands only from own cheat button.

P.S. Cheat commands is bugged for other non-priority players. You can get "random" concurrent exception error on commands execute (on non-playable step). Need more sync code and objects in xmage's engine.

**Comment by JayDi85** [comment]
If you want to call commands for another player then change command text with correct user name and call it from yourself. I removed cheat buttons from other player panels by 1045f352bc869ac7031c5c51556a5c68d74b6b6a.
