### ISSUE TITLE
Reality Scramble bypassed several cards with matching permanent types

### ISSUE THREAD

**Issue by SpikesCafe-google** [magefree/mage#5290]
I cast brainstorm and put Gisella, Blade of Goldnight and Worldspine Wurm on top of my library. I then cast Reality Scramble, targeting a Plant token from Khalni Garden. Instead of getting Gisella, as expected, many cards were revealed from my library until I hit Avenger of Zendikar. I took a quick glance at the code but didn't see the issue.
![capture](https://user-images.githubusercontent.com/16656302/44888505-8c64e480-ac9f-11e8-96ae-91e73e0297d1.PNG)

**Comment by Kerrus** [comment]
Might be looking at *card text* for matching permanent type instead of permanent type. That'd explain how a 0/1 plant got something that  makes 0/1 plants.
