### ISSUE TITLE
One with the Machine

### ISSUE THREAD

**Issue by DominusMaximus** [magefree/mage#5292]
This commit for One with the Machine has the 1.4.31v1 tag: 

https://github.com/magefree/mage/commit/b8d72b96190903718119da0ed7a9a14380ff9aba

Does this mean this fix was included in the latest release? If so, One with the Machine is still considering non-artifact permanents in determining the amount of cards drawn.

**Comment by quercitron** [comment]
You are right, there still was a bug.
