### ISSUE TITLE
Blackcleave Cliffs enters tapped under Blood Moon

### ISSUE THREAD

**Issue by karlosss** [magefree/mage#5293]
A player control 5 lands, Blood Moon and plays Blackcleave Cliffs. The land shall enter untapped, but enters tapped. This is quite a recent rules change.

Rules reference (614.12):
Some replacement effects modify how a permanent enters the battlefield. (See rules 614.1c-d.) Such effects may come from the permanent itself if they affect only that permanent (as opposed to a general subset of permanents that includes it). They may also come from other sources. To determine which replacement effects apply and how they apply, check the characteristics of the permanent as it would exist on the battlefield, taking into account replacement effects that have already modified how it enters the battlefield (see rule 616.1), continuous effects from the permanent's own static abilities that would apply to it once it's on the battlefield, **and continuous effects that already exist and would apply to the permanent.** 

And by the way, I am a L2 judge :)

**Comment by jmharmon** [comment]
This a known issue, you should really do your homework beforehand.
[https://github.com/magefree/mage/issues/4202](url)
[https://github.com/magefree/mage/issues/4625](url)
[https://github.com/magefree/mage/issues/4679](url)

**Comment by JRHerlehy** [comment]
Known issue.
