### ISSUE TITLE
Explosive Revelation lets the player reorder their library instead of just the revealed cards

### ISSUE THREAD

**Issue by Zibangarang** [magefree/mage#5302]
In a draft game I played earlier I had Explosive Revelation in my deck and instead of letting me put the revealed cards to the bottom of my library, it let me put all the cards in the library to the bottom of my library, essentially letting me reorder my entire library as I felt like.

**Comment by ingmargoudt** [comment]
I can see that. In the code the revealing does not stop after the land, letting you reveal your entire library. Fixed in #cef4789c30
