### ISSUE TITLE
Error in http://XMage.de/files/server-list.txt

### ISSUE THREAD

**Issue by LordNex** [magefree/mage#5310]
Hey guys, just wanted to say thanks for adding my server to the official list. Only problem is that there's a typo in the address which is throwing a "Wrong Data Format" error.

My guess would be the underscore before the address for mtg.powersofwar.com

http://XMage.de/files/server-list.txt

Thanks again and let me know if there is anything else I can do.

P.S.> Anyone happen to know of an Admin Console?

LoRd_NeX
[https://www.powersofwar.com](https://www.powersofwar.com)

**Comment by LevelX2** [comment]
Fixed.
