### ISSUE TITLE
Swiftwater Cliffs Enters the Battlefield Untapped

### ISSUE THREAD

**Issue by LeeSalt** [magefree/mage#5312]
Playing KTR Draft and this ETB tapped gain-land enters untapped. The others work as intended.

**Comment by ingmargoudt** [comment]
Swiftwater Cliffs is implemented correctly with an ETB tapped ability. Was there another card in play that could have effected it?

**Comment by LeeSalt** [comment]
This was a draft, so there's nothing else that would cause this to happen. This was against a bot (mad) if that matters. This was the only gain land that was doing this and it did it three times in three different games. The other gain lands worked as they should have.

**Comment by LeeSalt** [comment]
I will attempt to recreate.
