### ISSUE TITLE
Carpet of Flowers not activating correctly

### ISSUE THREAD

**Issue by zeflap** [magefree/mage#5315]
Just had a game where I started a turn with Carpet in play, then used its ability to add mana with which I cast a Bane of Progress. This destroyed the Carpet, and so when I used Regrowth to get the Carpet back and then played it, the new Carpet should have been able to add mana for the second main phase, being a new game object, but it didn't.

I asked a judge if it should have, and the answer was:
"Yeah, you'll get mana both times.
Because it's a new permanent, it doesn't count the ability as having been used yet."

**Comment by jeffwadsworth** [comment]
Think about what you are saying here.  What if you had 2 of these things out?  3?  4???  The "ability" is referencing the ability itself and not the card object.  So, you can only use this ability once per turn.

**Comment by zeflap** [comment]
@jeffwadsworth Please do not close issues that haven't actually been resolved.

Any amount of instances of Carpet would resolve by itself.
"this ability" is referring to that single instance, as it referring to some nebulous global version would break templating wildly.

**Comment by ingmargoudt** [comment]
@zeflap I agree.  “this ability” refers to that particular instance of the permanent. Since it was returned to play it counters as another instance

**Comment by JayDi85** [comment]
zeflap is right, Carpet of Flowers uses `originalId` for checks -- e.g. copies of that cards will have same originalId and will not triggers. It's wrong.
