### ISSUE TITLE
Niv-Mizzet, Parun - Exception/rollback on draw a card

### ISSUE THREAD

**Issue by sentania** [magefree/mage#5329]
Had a dual tonight where I drew a card as a result of the ability, the game threw an exception and issued a last action rollback.

Unfortunately didn't get a log capture.

Will try to repro.

**Comment by sentania** [comment]
Could have been this:
https://github.com/magefree/mage/issues/5331

I had Niv out a second time without issue, but the first time he was out and I got the excetion, my opponent used risk factor

**Comment by LevelX2** [comment]
I tested Niv-Mizzet, Parun and all seems to be ok. So probabaly it was caused from another card as you supposed.
