### ISSUE TITLE
Mentor doesn't let you choose how to stack the triggers

### ISSUE THREAD

**Issue by Stafy1** [magefree/mage#5332]
According to the spotlight video, you should be able to choose how to stack multiple mentor triggers to make the most out of it. Xmage does it automatically, making you lose some possible counters.

**Comment by AricHaldan** [comment]
I think you might be able to fix that simply by going into 'Preferences: Phases and Priority' and unchecking the box "Set order for triggers automatically if all have the same text"

**Comment by Stafy1** [comment]
Yup, that fixed it. Thanks.

**Comment by AricHaldan** [comment]
no problem :) glad to help
