### ISSUE TITLE
Couple of bugs I have noticed in Izzet Guild cards

### ISSUE THREAD

**Issue by AricHaldan** [magefree/mage#5333]
1: Beacon Bolt doesn't seem to allow the player to choose a target and does nothing when it resolves
2: my Jump-started cards got countered when I casted the from the graveyard but didn't get exiled. I know for sure this issue happened with Chemister's Insight at the least
3: Arclight Phoenix: does not return from the graveyard when 3 instants have been cast.

**Comment by theelk801** [comment]
The other two have already had fixes pushed.
