### ISSUE TITLE
Experimental Frenzy Bug

### ISSUE THREAD

**Issue by dayton228** [magefree/mage#5338]
Experimental Frenzy allows you to play out of hand, but not out of the graveyard. I specifically was unable to jump-start.

**Comment by themogwi** [comment]
I also just experienced this bug. Though, I was able to play a couple lands over 2 turns, but when I went to play "Integrity // Intervention" it would not allow me to. I also noticed I could also still play from hand.

[Boardstate](https://imgur.com/a/H0sNhrw)

I may have time to take a look at the card class some time through the week.

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.
