### ISSUE TITLE
Error pop-up resolving Chainwirler's ETB to kill Tajic (GRN)

### ISSUE THREAD

**Issue by majaldm** [magefree/mage#5342]
This error report popped up instead of executing Goblin Chainwirler's ETB, the creature returned to hand and the lands that had been tapped to cast it were untapped, the game log still logged the casting and the ETB effect.

XMage version installed:  1.4.31V3 (2018-09-23)

`Game exception occurred: java.lang.ClassCastException: mage.player.human.HumanPlayer cannot be cast to mage.game.permanent.Permanent
Server version: 1.4.31V3
mage.filter.FilterPermanent.match(FilterPermanent.java:21)
mage.abilities.effects.common.PreventAllNonCombatDamageToAllEffect.applies(PreventAllNonCombatDamageToAllEffect.java:51)
mage.abilities.effects.ContinuousEffects.getApplicableReplacementEffects(ContinuousEffects.java:371)
mage.abilities.effects.ContinuousEffects.replaceEvent(ContinuousEffects.java:735)
mage.game.GameState.replaceEvent(GameState.java:704)
mage.game.GameState.replaceEvent(GameState.java:697)
mage.game.GameImpl.replaceEvent(GameImpl.java:2673)
mage.players.PlayerImpl.doDamage(PlayerImpl.java:1929)
mage.players.PlayerImpl.damage(PlayerImpl.java:1915)
mage.abilities.effects.common.DamagePlayersEffect.apply(DamagePlayersEffect.java:72)
mage.abilities.AbilityImpl.resolveMode(AbilityImpl.java:173)
mage.abilities.AbilityImpl.resolve(AbilityImpl.java:160)
mage.abilities.TriggeredAbilityImpl.resolve(TriggeredAbilityImpl.java:76)
mage.game.stack.StackAbility.resolve(StackAbility.java:77)
mage.game.GameImpl.resolve(GameImpl.java:1398)
mage.game.GameImpl.playPriority(GameImpl.java:1348)
mage.game.turn.Step.priority(Step.java:61)
mage.game.turn.Phase.playStep(Phase.java:184)
mage.game.turn.Phase.play(Phase.java:89)
mage.game.turn.Turn.play(Turn.java:127)
mage.game.GameImpl.playTurn(GameImpl.java:856)
mage.game.GameImpl.play(GameImpl.java:765)
mage.game.GameImpl.start(GameImpl.java:729)
mage.server.game.GameWorker.call(GameWorker.java:34)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)`

**Comment by theelk801** [comment]
Was there a Tajic, Legion's Edge in this game?

**Comment by theelk801** [comment]
Alright, I've already fixed this with 32fd543

**Comment by majaldm** [comment]
Thanks, man
