### ISSUE TITLE
Jumpstart Cards don't exile on Counter

### ISSUE THREAD

**Issue by FastTadpole** [magefree/mage#5343]
"A spell with jump-start that was cast from your graveyard can still be countered, and if it has targets, it won't do anything if all its targets disappear or otherwise become illegal. After a spell with jump-start cast from your graveyard resolves, is countered, or leaves the stack in any way, it's exiled."
https://magic.wizards.com/en/articles/archive/feature/guilds-ravnica-mechanics-2018-09-04

Noticed once in a match when I countered a Direct Current it went back to graveyard instead of going to exile as it should have.

><font color="#CCCC33">11:02 PM: </font><font color="#20B2AA">grumpymanu</font><font color="White"> casts </font><font color="#FF6347"><a href="#Direct Current">Direct Current</a></font><font color="White"> [e32] with jump-start from graveyard targeting </font><font color="#20B2AA">FastTadpole</font><font color="White"></font>
<font color="#CCCC33">11:02 PM: </font><font color="#20B2AA">FastTadpole</font><font color="White"> casts </font><font color="#87CEFA"><a href="#Sinister Sabotage">Sinister Sabotage</a></font><font color="White"> [db9] targeting </font><font color="#FF6347"><a href="#Direct Current">Direct Current</a></font><font color="White"> [e32] </font>
<font color="#CCCC33">11:02 PM: </font><font color="#20B2AA">grumpymanu</font><font color="White"> puts </font><font color="#FF6347"><a href="#Direct Current">Direct Current</a></font><font color="White"> [e32] from stack into their graveyard</font>
<font color="#CCCC33">11:02 PM: </font><font color="#FF6347"><a href="#Direct Current">Direct Current</a></font><font color="White"> [e32] is countered by </font><font color="#87CEFA"><a href="#Sinister Sabotage">Sinister Sabotage</a></font><font color="White"> [db9]</font>
<font color="#CCCC33">11:02 PM: </font><font color="#20B2AA">FastTadpole</font><font color="White"> surveils 1</font>
<font color="#CCCC33">11:02 PM: </font><font color="#20B2AA">FastTadpole</font><font color="White"> puts </font><font color="#B0C4DE"><a href="#Island">Island</a></font><font color="White"> [1ca] from library into their graveyard</font>
<font color="#CCCC33">11:02 PM: </font><font color="#20B2AA">FastTadpole</font><font color="White"> puts </font><font color="#87CEFA"><a href="#Sinister Sabotage">Sinister Sabotage</a></font><font color="White"> [db9] from stack into their graveyard</font>

**Comment by LevelX2** [comment]
Fixed with 61b1b1ba0509edd2ce6af5ef1ee325218e0f0e4c.
