### ISSUE TITLE
Can't run client from startClient bat file

### ISSUE THREAD

**Issue by Jadpo** [magefree/mage#5348]
When I try to run the startClient bat file, I get this error

```Error: Unable to access jarfile .\lib\mage-client-${project.version}.jar```

**Comment by JayDi85** [comment]
Try to run launcher `XMageLauncher-0.3.8.jar` and start client by that app. You can run launcher by command:
 * `java -Djava.net.preferIPv4Stack=true -jar XMageLauncher-0.3.8.jar`

**Comment by JayDi85** [comment]
* Place downloaded `XMageLauncher-0.3.8.jar` to any folder like `d:\game\xm`
 * Create new file `run.cmd` and edit it with text editor;
 * Enter that line into it: `java -Djava.net.preferIPv4Stack=true -jar XMageLauncher-0.3.8.jar`
 * Run that command file `run.cmd` by double click;

**Comment by Jadpo** [comment]
I created it, it ran as a batch file, and still accomplishes nothing. I have downloaded the jar file from the website as well as the entire github repository

**Comment by JayDi85** [comment]
You need only jar-file from xmage.de

Open `run.cmd` file and insert second line to it: `pause`

Run it and report black window here.

**Comment by Jadpo** [comment]
a pause command doesn't seem to change anything? Is my batch file wrong?

```java -Djava.net.preferIPv4Stack=true -jar XMageLauncher-0.3.8.jar
PAUSE```

**Comment by Jadpo** [comment]
The prompt window still only appears for a half of a second or so

**Comment by JayDi85** [comment]
Yep, if you can't see black window then you are done something wrong.

After run bat-file you must see black window with logs (`pause` command pause and do not close it):

Example:
![shot_180930_004533](https://user-images.githubusercontent.com/8344157/46250356-3d4ed280-c44a-11e8-9fd0-6e87e515f3fa.png)

**Comment by Jadpo** [comment]
I understand that that is the way it should appear, but it doesn't seem to stop.  Do you see an error in the code posted above?

**Comment by Jadpo** [comment]
[run.txt](https://github.com/magefree/mage/files/2431001/run.txt)

**Comment by Jadpo** [comment]
yes, i do have a .cmd version, but I can't post that

**Comment by JayDi85** [comment]
Yes. You try run command file from downloaded github source files. It's a source and haven't real executable files. 

You need to run launcher and update/download all other files from it.

**Comment by Jadpo** [comment]
I'm running it in a folder with just the launcher from the website and the .cmd file.

**Comment by JayDi85** [comment]
Try this:
 * open folder with downloaded `XMageLauncher-0.3.8.jar` file;
 * create `run.cmd` file and insert to it: `java -Djava.net.preferIPv4Stack=true -jar XMageLauncher-0.3.8.jar`
 * create `run-runner.cmd` file and insert to it: `run.cmd > logs.txt`
 * run `run-runner.cmd`, find `logs.txt` file in folder and report it here.

**Comment by Jadpo** [comment]
![folders](https://user-images.githubusercontent.com/43709612/46250460-600cc700-c409-11e8-85ce-a7ae150c3c91.PNG)
![run](https://user-images.githubusercontent.com/43709612/46250461-626f2100-c409-11e8-9b65-991a48a0c8ad.PNG)
![runrunner](https://user-images.githubusercontent.com/43709612/46250464-64d17b00-c409-11e8-9294-379e88fce8c6.PNG)
These are the files. I ran the runner batch file, and got no .txt file, as you can see

**Comment by JayDi85** [comment]
It's write access problem (by default users can't write data to program files without UAC request). Do not place files to program files. Make another folder like `d:\games\xm` or `c:\games\xm` and place launcher to it.

**Comment by Jadpo** [comment]
Moved the files to ```c:\games\XM``` and ran them, same problem. Moved them to Downloads, still nothing

**Comment by JayDi85** [comment]
Move to c:\games\xm and try run-runner step. Report it here (logs.txt or nothing). Also show up popup menu on run.cmd file (right click on it and make screenshot).

**Comment by Jadpo** [comment]
Still no .txt file

![image](https://user-images.githubusercontent.com/43709612/46250544-eaa1f600-c40a-11e8-92d7-c8781fbb867d.png)

**Comment by JayDi85** [comment]
Try run it as admin. If can't help then I can try remotely connect to your PC by https://www.teamviewer.com/en/ (download it, run once without install and send me connect codes to email jaydi85@gmail.com ).

**Comment by JayDi85** [comment]
All done. There were many problems like:
 * need to save cmd files by text editor in ANSI format, not unicode;
 * need to setup `hosts` file with 127.0.0.1 localhost
 * need to disable ipv6 priority to ipv4 ([use that fix](https://support.microsoft.com/en-gb/help/929852/guidance-for-configuring-ipv6-in-windows-for-advanced-users) -- download file "Prefer IPv4 over IPv6 in prefix policies", run it and restart pc.
