### ISSUE TITLE
Angel of Sanctions bugged in EDH

### ISSUE THREAD

**Issue by MasN2** [magefree/mage#5354]
When an Angel of Sanctions exiles a commander and the commander is placed in the command zone, it fails to return the commander when removed from the battlefield.

See the Banishing Light ruling: https://www.reddit.com/r/magicTCG/comments/40b032/banishing_light_ruling_on_commanders/

**Comment by MasN2** [comment]
Probably duplicate of #5278

**Comment by Zerrisx** [comment]
Probably was a duplicate, but also no longer a bug due to the rules change in https://www.hipstersofthecoast.com/2020/06/rules-change-dies-triggers-will-work-for-commanders/.
