### ISSUE TITLE
Jace, Architect of Thought Ultimate functioning incorrectly

### ISSUE THREAD

**Issue by MasN2** [magefree/mage#5357]
When resolving Jace, AoT's -8 ability, Xmage prompts you to first look through your library, pick a card, then do the same for each other player in order. However, according to the rulings:
"For each library, the search is complete only when you explicitly say it is. For example, you can look through one player’s library, set that library down, look at another player’s library, choose a nonland card in the first library, then choose a nonland card in the second library. Don’t reveal any cards from those libraries to any other player until you exile them."
This is relevant because sometimes you want to see what cards are in other libraries before deciding which one you want from your own.

**Comment by mooretc2** [comment]
So after looking at the code for a bit, my intuition is that I'm not going to be able to do this without concurrency, and I'm not seeing any other cards that work concurrently. I'm going to move forward with using a SwingWorker helper class. If that is bad for some reason, or if I missed a prior implementation of a similar effect, please let me know.

**Comment by mooretc2** [comment]
I have it working now where it will spawn the panels revealing the decks at the same time, but if you select from the decks in the wrong order, the client hangs. Not sure how to proceed from this point, so I'm going to set it aside for now. If someone wants the code I've written to build off of or has thoughts on how to solve this, please let me know.

**Comment by theelk801** [comment]
You can open a pull request if you want.

**Comment by emerald000** [comment]
The easy way to do so would simply to show reveal windows of all the decks before the search begins. The harder way would be to have a flow similar to this:

Show a deck. If you choose a card, great! That deck is done. Restart with the next one if there is one. If you cancel, ask to either search the next deck still unchosen or finish the search.

That way, you will loop through all the decks until you get a card from every one of them or until you decide to stop searching. But honestly, I think this method is too complex for no reason and the easy way is the way to go.

**Comment by mooretc2** [comment]
Just updated my branch with a new strategy. I made a new method in Player/PlayerImpl called lookAtAllLibraries that reveals the cards in all libraries to the source's controller, then added a call to it in JAOT's -8 effect before card selection occurs. I tested it in human vs human and the decks weren't revealed to the other player which was my biggest concern.

If I've missed something anywhere please let me know. I'm obviously a bit new to this codebase and would welcome any thoughts/input!

**Comment by JayDi85** [comment]
@mooretc2 two tips:
 * You must inform other players about looking libraries like game.informPlayers();
 * You can check opponents count and skip lookAtAll on single opponent;
 * You can ask player to look at all or not by `if (chooseUse(Outcome.Benefit, "Look at all opponents libraries before ?", null, game)) { }`;

**Comment by mooretc2** [comment]
I'll get on informPlayers and chooseUse and push sometime later today. Regarding skipping lookAtAll with a single opponent, I was thinking it would be more correct to display the controller's library also since they are included in "For each player...", but maybe we should assume the player already knows their own decklist. Could be relevant with cards like Bomat Courier or Pyxis of Pandemonium that exile face-down though.

Another thing I forgot to ask about - the cards currently display side-by-side in a window instead of the typical library view. Is there an easy way to use the library view instead?
