### ISSUE TITLE
Missing Users and Tables

### ISSUE THREAD

**Issue by LordNex** [magefree/mage#5358]
Not sure if this is the right place to post so let me know if i need to post elsewhere.

For the past 2 versions after several hours of running, i start noticing people talking in chat that are not in the list of active players. I can verify this as some have joined tables and are still not listed as connected. I've also seen these "Ghost" users attempt to create a table and the user who created it can see it, but no one else can. 

Restarting the XMage server temporarily fixes the issue, but usually after around 12 hours later if I come back, its happened again. I'm attaching a screenshot. Please let me know if there are any logs or anything i can provide that will help. Im just starting to learn Java, but im an IT Veteran and pretty tech savvy so feel free to hit me up. Thanks again guys!

![image](https://user-images.githubusercontent.com/9270948/46317562-0a672480-c599-11e8-8d75-0865e9ec9912.png)

LoRd_NeX
[www.powersofwar.com](url)

**Comment by LordNex** [comment]
Just seen this happen again. Doesn't seem to keep the server from running but it makes it hard for users to find other users or tables that are in use. Modifying the view filters doesn't seem to change anything either. Disconnecting and Reconnecting also does not update the lists. It seem that shutting down the XMage Server and Restarting it is the only resolution at this point. Just thought id update this issue

**Comment by LordNex** [comment]
Yes I just went in and was able to start a new games table with the AI and successfully start the game. Its currently running list this but I may restart the server before my peak hours. But if you want to logon and test it your welcome too.

mtg.powersofwar.com:17171

**Comment by JayDi85** [comment]
Try to disable computer-mad (AI) on your server by remove that line in server's config: `<playerType name="Computer - mad..."`

It's a buggy and can freeze some code/games/server.

**Comment by LordNex** [comment]
Id hate to do that if possible. Since the server is new and doesn't get a whole lot of traffic yet. Id like to be able to allow my users some access to AI in case there isn't anyone else to play with. 

Would decreasing the amount of available AI bots help or is it just too possible for the AI to cause a loop and get stuck? If its the only way to resolve this so be it, id just prefer not to have to disable AI.

**Comment by LordNex** [comment]
Ok I disabled the "mad--bot" out of the config. I'll run this and see how it does. But i know its going to hard for my player base to play in some cases. 

I have the server set to auto reboot every 24 hours, Might try changing that to every 12 hours and see if that helps clear the bugs when they occur. It seems like it takes a while before it occurs. I expect its probably a specific card combo or something that causes the AI to loop, thus causing errors on the server.

Anyway, let me know if there is anything I can do to help. I'm going to attach the service log for the last day for you to look at, if there is something more you need, just let me know.
[service-20181014T224150.137.log](https://github.com/magefree/mage/files/2476936/service-20181014T224150.137.log)

**Comment by LordNex** [comment]
I added the AI back in and will continue to monitor it. If either bug surfaces, i'll try and get logs and screenshots and post them. If there is anything else I can do to help, just let me know. your welcome to come and test on my server as well. Its a Windows Server 2016 Instance in VMWare on a Paid Host so its scaleable and on a very fast connection

**Comment by LordNex** [comment]
OK i logged in and noticed there was alot of people on the server, i connected on the admin side and im not seeing near as many users. Screenshots below. Let me know if there are any logs that would help.

![missing_users1](https://user-images.githubusercontent.com/9270948/47058525-0c310a80-d18b-11e8-8d59-fee021012dee.JPG)
![missing_users2](https://user-images.githubusercontent.com/9270948/47058527-0cc9a100-d18b-11e8-8120-12535e97b9c3.JPG)

**Comment by JayDi85** [comment]
Lobby’s players list updates with timeout, so after massive disconnects it can show outdated list. Same for massive reconnects. Wait few minutes to make it fully visible.

Origin of the topic starter problem: memory leaks after hours of work #11285. Database can be broken (closed) on no more free memory. So cards/sets/users repository will be closed too and any related db code will find nothing for sql queries (but server logs will show details errors). See here for examples and father improves with auto-restart: #8130 

So nothing to do with it. Only server restart or full garbage collector call can help.

**Comment by JayDi85** [comment]
Real reason: server's data lock and infinite code, see here for details: https://github.com/magefree/mage/issues/11285#issuecomment-2011326865 (not related to memory leaks).
