### ISSUE TITLE
3rd Quick Connect Button?

### ISSUE THREAD

**Issue by LordNex** [magefree/mage#5359]
Hey guys, I was wondering of you could add a 3rd Quick Connect button similar to the VaporMTG Server.

One of the only response back about the server negatively is that it just has a low population. Which for being new is understandable. But I think that would help the population climb, and give people a few more options in case of outages or connection issues. Either way thanks for everything!

www.powersofwar.com

**Comment by Khyrberos** [comment]
Good idea.

**Comment by JayDi85** [comment]
Vapor server don't work (was closed?). Changed default USA server to power now.

![shot_181118_041349](https://user-images.githubusercontent.com/8344157/48667122-e2039d00-eae8-11e8-9c2a-82355d69612d.png)

**Comment by Zerrisx** [comment]
Does this server still exist?

**Comment by LordNex** [comment]
I was running it. I had some RL things come up and at the time it Didn't really get any traffic and just got expensive and time consuming to keep going. I thought about setting it back up though. Had several people even email me asking me to put it back up and they would help. I don't know. What do you guys think?  It's a Hostwinds virtual server not just some box in my house. Just cost about $30-60 a month to run depending on traffic and storage.

**Comment by JayDi85** [comment]
VaporMTG/power servers were replaced by official US server year ago after they shut downed. So xmage already have us base server (in NYC).

New servers can be useful on users stats/top lists implemented (some dev working on it) with specific community (e.g. with special tourneys or events). The main problem to keep people online.

So if you want add new server then it useless. If you want make some community with events/tourney/top-lists then it can be useful.
