### ISSUE TITLE
EDH Power Levels

### ISSUE THREAD

**Issue by MasN2** [magefree/mage#5365]
I've taken a look at the EDH power level list, and I believe it is inaccurate from a competitive standpoint. (For example, it puts points for each sliver, and slivers are actually pretty weak.)
I propose the following list, which is much shorter, but should hit most of the decks in the top end without hitting too many casual decks. I might have missed some cards, but it's a start:

Food Chain - 3
Paradox Engine - 1
Mind's Desire - 1
Power Artifact - 1 (I suggest this instead of monolith to prevent collateral damage)
Winter Orb - 3
Back to Basics - 2
Static Orb - 1
Necropotence - 1
Ad Nauseum - 1
Doomsday - 3
Protean Hulk - 3
Timetwister - 1
Wheel of Fortune - 1
Demonic Tutor - 1
Mana Crypt - 2
Sol Ring - 1
Mana Drain - 1
Yagmoth's Will - 1
Mind's Desire - 1
The Chain Veil - 3 (either this or teferi PW as commander)
Armageddon - 1 (and Ravages of War)
Tangle Wire - 2
High Tide - 1
Candelabra of Tawnos - 1
Cursed Totem - 1
Mana Web - 1
Trinisphere - 1
Sphere of Resistance - 1
Hikori, Dust Drinker - 1
Rising Waters - 1
Thalia, Guardian of Thraben - 1
Transmute Artifact - 1
Windfall - 1
Mystical Tutor - 1
Angel of Glory's Rise - 1 (Again, this over Lab Man to avoid collateral damage.)
Wirewood Symbiote - 1
Slyvan Safekeeper - 1
Temur Sabertooth - 1
Ruination - 1
Jokulhaups - 1
Boonweaver Giant - 2

Perhaps after something like this is created, you could multiply these numbers by 10 and start giving smaller numbers for other 'annoying' effects such as time warp effects and such. As stands though, I don't see the point of a list that marks slivers as a higher rating than a cEDH combo deck.

**Comment by spjspj** [comment]
Many combo pieces are counted explicitly and given the highest rating (7 from memory).  Then it's basically categories of cards which affect the board more broadly (extra turns, tutors, mass removal, mass return to hand etc).  Slivers are just a very strong deck in general (although weak by themselves - hence the low rating for each individual one).  You can sort by edh power level in the deck editor actually.  Alternatively, if you have examples of decks that are strong, would be helpful to have more examples.  I created the strongest deck I could at the time by essentially infinite turn narset (using eye of the.... STORM!).  Interesting that people seem more interested in the concept now though and happy to revisit the code...

**Comment by MasN2** [comment]
Narset combo is the quintessential "Pub-stomper" deck - it's often believed to be the most powerful deck, but it there's actually a lot of decks that are stronger than it, but uses more innocuous cards. This list (http://tappedout.net/mtg-decks/list-multiplayer-edh-generals-by-tier/) is pretty well-maintained, but I'll highlight some examples:

Decks that are strong in cEDH either tend to be fast combo or stax. If you want to get a taste of cEDH, I suggest starting with food chain tazri, as the plan is quite linear and it's a very strong deck:
http://tappedout.net/mtg-decks/food-chain-tazri/
That said, food chain abuse is not limited to general tazri. There is also food chain prossh, and food chain sidisi brood tyrant. 
Another fast combo deck is storm. Jeleva tends to head grixis storm, and a list is as follows:
http://tappedout.net/mtg-decks/i-hate-all-of-you-2/
There's also Protean Hulk combo:
http://tappedout.net/mtg-decks/walkingball/
And Doomsday:
http://tappedout.net/mtg-decks/ad-nauseam-zur/

Chain Veil Teferi is probably my favorite among the cEDH decks, because it threatens a 1.5 card combo with Chain Veil, but can also play stax and control to fight against faster combo decks:
http://tappedout.net/mtg-decks/chain-veil-teferi/

The 'new hotness' as far as competitive Stax goes is blood pod:
http://tappedout.net/mtg-decks/tana-and-tymna-blood-pod-primer/
That said, older Stax decks do exist such as Brago, Derevi, and Ruric Thar.

Also, this list is far from exhaustive. Mono-G selvala is also a very fast combo deck (when the opponent doesn't have disruption, a decent amount of time it can go t1 mana dork, t2 selvava, t3 win) and of course Narset can pick up a win from time to time, it's just slower, less consistent, and more vulnerable to disruption than the stronger combo decks in the format. And something like slivers might beat casual players, but it doesn't stand a chance against a real competitive EDH deck. So I just want a tier list that first addresses the top decks before moving down. (In addition, at the more casual levels, having a good manabase/ramp is generally more important to a deck's success than the payoff cards, whether they be slivers, dragons, eldrazi, big omnath, etc.)

Disclaimer: I do not advise playing these strong combo decks in xmage, unless the table is specifically marked as serious or competitive. Some of them are practical issues: for example, nobody wants to click a food chain or teferi 200 times. Macros might help, but these are buggy. That said, there are combo decks such a doomsday, storm, or stax, (or Narset turns) that are playable on xmage, but you'll just get a quick game and a few upset EDH players, which doesn't really help anyone.

**Comment by MasN2** [comment]
Here's some commentary I quickly wrote on the existing code:
`if (extraTurns) {
            thisMaxPower = Math.max(thisMaxPower, 7); // This is definitely not deserving of this type of rating. It's garbage in competitive, can beat casuals, but probably deserves 2 at most for that.
        }
        if (buyback) {
            thisMaxPower = Math.max(thisMaxPower, 6); // Capsize, Forbid, Constant Mists, Reiterate.. these are the only ones I can think of, and none deserve points
        }
        if (tutor) {
            thisMaxPower = Math.max(thisMaxPower, 6); // Finally the first one that's actually reasonable. Some tutors like diabolic tutor or ring of 3 wishes is quite fair, but there are a lot of strong ones and i understand not listing them all out
        }
        if (annihilator) {
            thisMaxPower = Math.max(thisMaxPower, 5); // If my opponent's big ramp payoff is OG eldrazi, I'm not scared. The only half-decent one is kozilek. Other possibility: they are playing Jhoria, but still..
        }
        if (cantUntap) {
            thisMaxPower = Math.max(thisMaxPower, 5); // This is half-reasonable.
        }
        if (costLessEach) {
            thisMaxPower = Math.max(thisMaxPower, 5); // In theory this effect would be strong, but turns out in EDH not really. Like there's Emmy 2.0, Karador.. and they're strong but not that good. A far scarier cost reduction ability is Delve
        }
        if (infect) {
            thisMaxPower = Math.max(thisMaxPower, 5); // I'd give this a -1 if I could, because this proves that the deck is trying to win through damage, and infect isn't nearly as strong as people make it out to be. Turns out that even if you only need 10, it's a lot harder to get a critical mass. And that's ignoring the life payment that's common in commander.
        }
        if (overload) {
            thisMaxPower = Math.max(thisMaxPower, 5); // You're thinking of just cyclonic rift here, right? This is a needless false positive for mizzium mortars. I guess mizzix's mastery can be strong, but still..
        }
        if (twiceAs) {
            thisMaxPower = Math.max(thisMaxPower, 5); // The only really strong card here is doubling season, and that's just superfriends. Also, the way it's coded, "twice that much" get's literally only mana reflection (while missing the stronger mirari's wake, extraplanar lens, etc.)
        }
        if (cascade) {
            thisMaxPower = Math.max(thisMaxPower, 4); // Maelstrom Wanderer and Ydris mostly? Turns out 'strong' cascade cards like shardless agent and bloodbraid elf kinda suck in EDH
        }
        if (doesntUntap) {
            thisMaxPower = Math.max(thisMaxPower, 4); // Monoliths and goblin sharpshooter? Well, I guess?
        }
        if (each) {
            thisMaxPower = Math.max(thisMaxPower, 4); // There's >3000 cards with this word. The first of which is "Abandon reason". Well then,
        }
        if (exileAll) {
            thisMaxPower = Math.max(thisMaxPower, 4); // These cards tend to be 'fair' cards, and cards like relic of progenitus that keeps graveyard strategies in check. Unless you were looking for cards like tainted pact specifically, though I get the feeling you weren't.
        }
        if (flash) {
            thisMaxPower = Math.max(thisMaxPower, 4); // ???
        }
        if (flashback) {
            thisMaxPower = Math.max(thisMaxPower, 4); // Snapcaster mage? That's all I can think of. I mean, I can think of Think Twice, but there's no reason for this card to be on the list
        }
        if (flicker) {
            thisMaxPower = Math.max(thisMaxPower, 4); // There's less strong flicker enablers than you might think, and the strong flicker decks (eg. Brago Stax) use fewer enablers
        }
        if (gainControl) {
            thisMaxPower = Math.max(thisMaxPower, 4); // Gilded Drake and Treachery. The other control magic effects are reasonably fair. And also, you'll hit homeward path effects.
        }
        if (lifeTotalBecomes) {
            thisMaxPower = Math.max(thisMaxPower, 4); // I guess this was targeted at sorin and magister sphinx. ..while missing Axis of immortality, and hitting eternity vessel. Besides, the set-to-10 cards might be unfun among casual groups, but aren't that strong.
        }
        if (mayCastForFree) {
            thisMaxPower = Math.max(thisMaxPower, 4); // In theory, I guess..
        }
        if (preventDamage) {
            thisMaxPower = Math.max(thisMaxPower, 4); // ???
        }
        if (proliferate) {
            thisMaxPower = Math.max(thisMaxPower, 4); // ???
        }
        if (protection) {
            thisMaxPower = Math.max(thisMaxPower, 4); // ??? I mean if you just wanted to hit the swords, then you shouldn't use a criteria that hits a million other things.
        }
        if (putUnderYourControl) {
            thisMaxPower = Math.max(thisMaxPower, 4); // Okay?
        }
        if (returnFromYourGY) {
            thisMaxPower = Math.max(thisMaxPower, 4); // The false positive ratio on this tho
        }
        if (sacrifice) {
            thisMaxPower = Math.max(thisMaxPower, 4); // ???
        }
        if (skip) {
            thisMaxPower = Math.max(thisMaxPower, 4); // did you even search what cards have 'skip' in them?
        }
        if (storm) {
            thisMaxPower = Math.max(thisMaxPower, 4); // Mind's desire and that's it. The next-best storm card is aetherflux, and that doesn't even get hit.
        }
        if (unblockable) {
            thisMaxPower = Math.max(thisMaxPower, 4); // ???
        }
        if (whenCounterThatSpell) {
            thisMaxPower = Math.max(thisMaxPower, 4); // Okay?
        }
        if (wheneverEnters) {
            thisMaxPower = Math.max(thisMaxPower, 4); // I mean, you hit reclamation sage and not nature's claim, and I'd think the instant is more powerful
        }
        if (xCost) {
            thisMaxPower = Math.max(thisMaxPower, 4); // ???
        }
        if (youControlTarget) {
            thisMaxPower = Math.max(thisMaxPower, 4); // Well.. uh.. at least you're consistent with these
        }
        if (yourOpponentsControl) {
            thisMaxPower = Math.max(thisMaxPower, 4); // Assymetric effects tend to have proportionate costs
        }
        if (anyNumberOfTarget) {
            thisMaxPower = Math.max(thisMaxPower, 3); // ??? If you actually search it up, the cards there are mostly fair. (Though Ad Nauseum is the first result)
        }
        if (createToken) {
            thisMaxPower = Math.max(thisMaxPower, 3); // ???
        }
        if (destroyAll) {
            thisMaxPower = Math.max(thisMaxPower, 3); // This is a sign of a healthy meta.
        }
        if (dredge) {
            thisMaxPower = Math.max(thisMaxPower, 3); // Fine. But really, the only one is dakmor in gitrog.
        }
        if (hexproof) {
            thisMaxPower = Math.max(thisMaxPower, 3); // Fine.
        }
        if (shroud) {
            thisMaxPower = Math.max(thisMaxPower, 3); // As above.
        }
        if (undying) {
            thisMaxPower = Math.max(thisMaxPower, 3); // Mikeus is the only one I can think of, and it's not that good.
        }
        if (persist) {
            thisMaxPower = Math.max(thisMaxPower, 3); // ???
        }
        if (cantBe) {
            thisMaxPower = Math.max(thisMaxPower, 2); // If you do a gatherer search, it's mostly weak evasion abilities
        }
        if (evoke) {
            thisMaxPower = Math.max(thisMaxPower, 2); // ???
        }
        if (exile) {
            thisMaxPower = Math.max(thisMaxPower, 2); // Um...
        }
        if (menace) {
            thisMaxPower = Math.max(thisMaxPower, 2); // ??? 
        }
        if (miracle) {
            thisMaxPower = Math.max(thisMaxPower, 2); // There's some decent miracle cards, but what card are you even thinking of?
        }
        if (sliver) {
            thisMaxPower = Math.max(thisMaxPower, 2); // WTF
        }
        if (untapTarget) {
            thisMaxPower = Math.max(thisMaxPower, 2); // Um, okay?
        }
        if (copy) {
            thisMaxPower = Math.max(thisMaxPower, 1); // I'm not sure it's even worth the effort to put a 1 here
        }
        if (counter) {
            thisMaxPower = Math.max(thisMaxPower, 1); // You know, counters are weak in EDH. Except mana drain. And force of will. And flusterstorm in cEDH. And spell pierce in cEDH..
        }
        if (destroy) {
            thisMaxPower = Math.max(thisMaxPower, 1); // Removal is a sign of a healthy format
        }
        if (drawCards) {
            thisMaxPower = Math.max(thisMaxPower, 1); // Same for this
        }
        if (exalted) {
            thisMaxPower = Math.max(thisMaxPower, 1); ???
        }
        if (retrace) {
            thisMaxPower = Math.max(thisMaxPower, 1); ???
        }
        if (trample) {
            thisMaxPower = Math.max(thisMaxPower, 1); ???
        }
        if (tutorBasic) {
            thisMaxPower = Math.max(thisMaxPower, 1); // If you want to go after these, hit the signets first.
        }





if (cn.equals("ancient tomb") // fair
                || cn.equals("anafenza, the foremost") // ???
                || cn.equals("arcum dagsson") // fair
                || cn.equals("armageddon") // fair
                || cn.equals("aura shards") // it's a strong card, but a sign of a non-cEDH deck
                || cn.equals("azami, lady of scrolls") // ??? 
                || cn.equals("azusa, lost but seeking") // ???
                || cn.equals("back to basics") // Just a 5?
                || cn.equals("bane of progress") // ???
                || cn.equals("basalt monolith") // This is either broken with power artifact/rings, or a very fair card
                || cn.equals("blightsteel collossus") // This is quite expensive, and polymorph decks aren't that strong
                || cn.equals("blood moon") // Fair
                || cn.equals("braids, cabal minion") // Banned
                || cn.equals("cabal coffers") // This means the deck is reasonably fair
                || cn.equals("captain sisay") // 5 actually doesn't do anything since it gets caught by the tutor thing
                || cn.equals("celestial dawn") // This was only ever used in zedruu, and that was before the BFZ rules update
                || cn.equals("child of alara") // ???
                || cn.equals("coalition relic") // ???
                || cn.equals("craterhoof behemoth") // I mean it's an okay card, I guess 5 is pretty reasonable
                || cn.equals("deepglow skate")
                || cn.equals("derevi, empyrial tactician")
                || cn.equals("dig through time")
                || cn.equals("edric, spymaster of trest")
                || cn.equals("elesh norn, grand cenobite")
                || cn.equals("entomb") // same for all of these up to here
                || cn.equals("force of will") // here even, though this could be a bit higher
                || cn.equals("food chain") // this deserves at least a 30
                || cn.equals("gaddock teeg")
                || cn.equals("gaea's cradle")
                || cn.equals("grand arbiter augustin iv")
                || cn.equals("grim monolith")
                || cn.equals("hermit druid")
                || cn.equals("hokori, dust drinker")
                || cn.equals("humility")
                || cn.equals("imperial seal")
                || cn.equals("iona, shield of emeria") // ???
                || cn.equals("jin-gitaxias, core augur") // ???
                || cn.equals("karador, ghost chieftain")
                || cn.equals("karakas")
                || cn.equals("kataki, war's wage")
                || cn.equals("knowledge pool") // I mean this is only broken with teferi
                || cn.equals("linvala, keeper of silence") // This is more of an anti-comp card, and it's not that strong
                || cn.equals("living death")
                || cn.equals("llawan, cephalid empress") // um what?
                || cn.equals("loyal retainers")
                || cn.equals("maelstrom wanderer")
                || cn.equals("malfegor") // WHAT?
                || cn.equals("master of cruelties") // i know it frustrates people, but it's not actually that good
                || cn.equals("mana crypt") // just a 5?
                || cn.equals("mana drain")
                || cn.equals("mana vault")
                || cn.equals("michiko konda, truth seeker") // WHAT?
                || cn.equals("nath of the gilt-leaf")
                || cn.equals("natural order")
                || cn.equals("necrotic ooze")
                || cn.equals("nicol bolas") // WHAT?
                || cn.equals("numot, the devastator") // I mean it's a sign their on LD, but this isn't even the best LD commander.
                || cn.equals("oath of druids")
                || cn.equals("pattern of rebirth")
                || cn.equals("protean hulk") // Needs at least a 20
                || cn.equals("purphoros, god of the forge")
                || cn.equals("ravages of war")
                || cn.equals("reclamation sage") // UM
                || cn.equals("sen triplets") // UH
                || cn.equals("serra's sanctum") // well then
                || cn.equals("sheoldred, whispering one") // did you decide to put every praetor on this list?
                || cn.equals("sol ring")
                || cn.equals("spore frog") // okay I guess?
                || cn.equals("stasis")
                || cn.equals("strip mine")
                || cn.equals("the tabernacle at pendrell vale")
                || cn.equals("tinker") // banned
                || cn.equals("treasure cruise")
                || cn.equals("urabrask the hidden") // if any praetor doesn't deserve to be on this list, it's this one in paticular
                || cn.equals("vorinclex, voice of hunger") // but still, none of them do
                || cn.equals("winter orb") // this is a far stronger stax card than the likes of hikori, also you missed tangle wire
                || cn.equals("zur the enchanter")) {
            thisMaxPower = Math.max(thisMaxPower, 5);
        }

        // Parts of infinite combos
        if (cn.equals("animate artifact") || cn.equals("animar, soul of element") // did you even test your code?
                || cn.equals("archaeomancer") // i mean it's a part of an infinite, and a very weak infinite at that
                || cn.equals("ashnod's altar") || cn.equals("azami, lady of scrolls")
                || cn.equals("aura flux") // this is not an infinite piece
                || cn.equals("basalt monolith") || cn.equals("brago, king eternal")
                || cn.equals("candelabra of tawnos") || cn.equals("cephalid aristocrat")
                || cn.equals("cephalid illusionist") || cn.equals("changeling berserker")
                || cn.equals("consecrated sphinx")
                || cn.equals("cyclonic rift") // same here
                || cn.equals("the chain veil")
                || cn.equals("cinderhaze wretch") || cn.equals("cryptic gateway") // i mean so many of these infinites are clunky enough they don't deserve points, not going to point out them all
                || cn.equals("deadeye navigator") || cn.equals("derevi, empyrial tactician")
                || cn.equals("doubling season") || cn.equals("dross scorpion")
                || cn.equals("earthcraft") || cn.equals("erratic portal")
                || cn.equals("enter the infinite") || cn.equals("omniscience")
                || cn.equals("exquisite blood") || cn.equals("future sight")
                || cn.equals("genesis chamber")
                || cn.equals("ghave, guru of spores")
                || cn.equals("grave pact")
                || cn.equals("grave titan") || cn.equals("great whale")
                || cn.equals("grim monolith") || cn.equals("gush")
                || cn.equals("hellkite charger") || cn.equals("intruder alarm")
                || cn.equals("hermit druid")
                || cn.equals("humility")
                || cn.equals("iona, shield of emeria") // this doesn't make it on power nor is an infinite piece
                || cn.equals("karn, silver golem") || cn.equals("kiki-jiki, mirror breaker")
                || cn.equals("krark-clan ironworks") || cn.equals("krenko, mob boss")
                || cn.equals("krosan restorer") || cn.equals("laboratory maniac")
                || cn.equals("leovold, emissary of trest") // banned
                || cn.equals("leonin relic-warder") || cn.equals("leyline of the void")
                || cn.equals("memnarch") || cn.equals("memnarch")
                || cn.equals("meren of clan nel toth") || cn.equals("mikaeus, the unhallowed")
                || cn.equals("mindcrank") || cn.equals("mindslaver")
                || cn.equals("minion reflector") || cn.equals("mycosynth lattice")
                || cn.equals("myr turbine") || cn.equals("narset, enlightened master")
                || cn.equals("nekusar, the mindrazer") || cn.equals("norin the wary")
                || cn.equals("notion thief")
                || cn.equals("opalescence") || cn.equals("ornithopter")
                || cn.equals("paradox engine")
                || cn.equals("purphoros, god of the forge")
                || cn.equals("peregrine drake") || cn.equals("palinchron")
                || cn.equals("planar portal") || cn.equals("power artifact")
                || cn.equals("rings of brighthearth") || cn.equals("rite of replication")
                || cn.equals("sanguine bond") || cn.equals("sensei's divining top")
                || cn.equals("splinter twin") || cn.equals("stony silence")
                || cn.equals("sunder")
                || cn.equals("storm cauldron") || cn.equals("teferi's puzzle box")
                || cn.equals("tangle wire")
                || cn.equals("teferi, mage of zhalfir") || cn.equals("teferi, mage of zhalfir")
                || cn.equals("tezzeret the seeker") || cn.equals("time stretch")
                || cn.equals("time warp") || cn.equals("training grounds") // quite inconsistent to hit time warp but not temporal manip or capture
                || cn.equals("triskelavus") || cn.equals("triskelion") // funny to see this and not walking ballista. arguable this goes inf with mik while ballista doesn't, but ballista does with mik and a sac outlet and is better for protean hulk stacks
                || cn.equals("turnabout") || cn.equals("umbral mantle")
                || cn.equals("uyo, silent prophet") || cn.equals("voltaic key")
                || cn.equals("workhorse") || cn.equals("worldgorger dragon")
                || cn.equals("worthy cause") || cn.equals("yawgmoth's will")
                || cn.equals("zealous conscripts")) {
            thisMaxPower = Math.max(thisMaxPower, 12);
        }

        if (cn.equals("animar, soul of element") // again, spellchecking
                || cn.equals("azami, lady of scrolls") // there's so much duplicate code here
                || cn.equals("braids, cabal minion") // and so much for it for stuff already banned
                || cn.equals("child of alara") // or which don't deserve points
                || cn.equals("derevi, empyrial tactician") // excercise for the reader: find another card in this section that is already banned
                || cn.equals("edric, spymaster of trest")
                || cn.equals("gaddock teeg")
                || cn.equals("grand arbiter augustin iv")
                || cn.equals("hokori, dust drinker")
                || cn.equals("iona, shield of emeria")
                || cn.equals("jin-gitaxias, core augur")
                || cn.equals("kaalia of the vast")
                || cn.equals("karador, ghost chieftain")
                || cn.equals("leovold, emissary of trest")
                || cn.equals("linvala, keeper of silence")
                || cn.equals("llawan, cephalid empress")
                || cn.equals("memnarch")
                || cn.equals("meren of clan nel toth")
                || cn.equals("michiko konda, truth seeker")
                || cn.equals("narset, enlightened master")
                || cn.equals("nekusar, the mindrazer")
                || cn.equals("norin the wary")
                || cn.equals("numot, the devastator")
                || cn.equals("sheoldred, whispering one")
                || cn.equals("teferi, mage of zhalfir")
                || cn.equals("zur the enchanter")) {
            thisMaxPower = Math.max(thisMaxPower, 12);
        }

        if (cn.equals("anafenza, the foremost")
                || cn.equals("arcum dagsson")
                || cn.equals("azusa, lost but seeking")
                || cn.equals("brago, king eternal")
                || cn.equals("captain sisay")
                || cn.equals("elesh norn, grand cenobite")
                || cn.equals("malfegor")
                || cn.equals("maelstrom wanderer")
                || cn.equals("mikaeus the unhallowed")
                || cn.equals("nath of the gilt-leaf")
                || cn.equals("prossh, skyraider of kher")
                || cn.equals("purphoros, god of the forge")
                || cn.equals("sen triplets")
                || cn.equals("urabrask the hidden")
                || cn.equals("vorinclex, voice of hunger")) {
            thisMaxPower = Math.max(thisMaxPower, 10);
}

Also I didn't mention all of the cards that are stronger than cards on this list, but you didn't assign any points to. Mono-G selvala for a start, but I'm sure you'll find a lot more.
Or categories that are more indicative of a deck's power. For example, 1 cost mana dorks are more indicative than exalted, but I'm sure you'll again find others.`

**Comment by theelk801** [comment]
I don't have much to say about the rankings (I'm just not super opinionated on EDH power level) but it seems like the code could definitely be cleaned up from being a bunch of if and or statements.
