### ISSUE TITLE
Keep getting put into the wrong type of games

### ISSUE THREAD

**Issue by sentania** [magefree/mage#5371]
I have a filter set up to show only standard games for me to join.
![image](https://user-images.githubusercontent.com/2688043/46514668-dbfd7980-c824-11e8-9f9b-c2da14e92264.png)

However i regularly get sent into modern or legacy games and get my ass beat.

What am I missing in setting up the filter so I only get into the games I want to play?

**Comment by JayDi85** [comment]
Your screenshot is fine -- only standard games are shows.

**Comment by ingmargoudt** [comment]
I think what Sentania tries to report, is that he selects a Standard Constructed match, but it opens up into another Constructed Type instead. Could there perhaps be a mix up in list indices?
Besides that: You can see the player of the table you are joining, do you still see that when you have joined the table (but not in the match yet?)

**Comment by sentania** [comment]
This is correct.

I get sent into a game that I did not "select", I'll check the next time it happens if the opponant is correct.

**Comment by Zzooouhh** [comment]
I believe #5239 could be related to this.

**Comment by JayDi85** [comment]
Fixed via 2bd5d0ddf6fc0d79c58ffd76c5575e9996cac963
