### ISSUE TITLE
Assault // Battery split card bug

### ISSUE THREAD

**Issue by luzaasta** [magefree/mage#5372]
"Assault // Batery" card from "Invasion" set has implementation error.

The Assault part is using "mage.target.common.TargetAnyTarget" class to resolve targets, but it should instead use "mage.target.common.TargetCreatureOrPlayer" class.

**Comment by ingmargoudt** [comment]
The Oracle text of Assault is : 

**Assault deals 2 damage to any target.**

http://gatherer.wizards.com/Pages/Card/Details.aspx?printed=false&multiverseid=20580

**Comment by rystan** [comment]
@luzaasta, in March they eliminated the Planeswalker redirect damage rule that changed all "target creature or player" to "any target":

https://magic.wizards.com/en/articles/archive/news/dominaria-frame-template-and-rules-changes-2018-03-21
