### ISSUE TITLE
XMage with another Client

### ISSUE THREAD

**Issue by JoseEduardo** [magefree/mage#5373]
Hi, I have a personal project.
This project is just to increase my knowledge, this project is a client for XMage using Engine Unity.

I'm having some problems establishing a TCP connection between the server and the Unity project.

I would like to ask if someone could help me with the login messages that the Client sends to the Server.
I do not have much experience in the project, that makes it difficult, I saw that the connection is TCP, but I do not know how the Client sends the login data to the server.

Can anybody help me? I could not post to the forum, sorry if this is not the correct location.

**Comment by JayDi85** [comment]
It's uses binary protocol with objects transfer, you can't emulate it. See [JBoss network engine](www.jboss.org/jbossremoting/documentation/v2.html).

But there were attempts to replace that engine with modern. Like graphql. You can [find discussion](https://github.com/magefree/mage/issues/4515) and some [test code with implemented graphql](https://github.com/magefree/mage/pull/4575) for read only mode.

**Comment by c4dr01d** [comment]
You can try React Native, it can call native code using interfaces, and it can be more easily to build mobile platforms app.
