### ISSUE TITLE
Nature's Will doesn't tap opponent's lands

### ISSUE THREAD

**Issue by spjspj** [magefree/mage#5383]
Or it didn't appear to in a game of edh multiple times.

**Comment by Zerrisx** [comment]
This works correctly the first time, but gets broken by rollbacks.  After you rollback, the second time, it won't tap your opponent's lands.

**Comment by LevelX2** [comment]
I was not able to reproduce it after the rollback rework.
@Zerrisx Can you confirm?

**Comment by xenohedron** [comment]
Could not reproduce on latest master.
