### ISSUE TITLE
EventType.TAPPED_FOR_MANA is fired way more than necessary

### ISSUE THREAD

**Issue by Zzooouhh** [magefree/mage#5385]
EventType.TAPPED_FOR_MANA is being fired all the time, even when I'm not tapping any lands for mana. Maybe related to #5144? Best way to test this is to have two replacement abilities for EventType.TAPPED_FOR_MANA on the battlefield at the same time, I've tried Mana Reflection + Ritual of Subdual. Instead of when tapping a land for mana, I get asked every single time I gain priority, for every single land I control, to choose which replacement effect to apply - which makes the game virtually unplayable.

Also probably as a result of this, Harvest Mage when tapped to use its ability will actually give you one mana of any color for each land you control, every single time you gain priority, until end of turn. I remember the card working as proper back when I tested it for implementation, so there must've been a change to the event firing sometime later than that.

**Comment by jeffwadsworth** [comment]
https://github.com/magefree/mage/commit/2649435071881ceace780a1b8e81cc9e143c1136
