### ISSUE TITLE
Kicker + Flashback doesn't work properly

### ISSUE THREAD

**Issue by Harry-Truman** [magefree/mage#5389]
Reproduce: Cast snapcaster mage targeting burst lightning. Cast burst lightning. No "Pay Kicker?" prompt appears.

Expected: Flashback from any source should prompt you to pay any optional additional costs, force you to pay any mandatory additional costs, and not allow you to pay alternative costs.

**Comment by jeffwadsworth** [comment]
This appears to be a case of having to rewrite Flashback to handle optional additional costs.  Right now, it just creates a copy of the spellAbility of the source card and doesn't add the optional additional costs.

**Comment by Harry-Truman** [comment]
Thanks for the reply. It's a fringe case that probably doesn't come up much, but it's the only serious mechanics problem I've noticed playing competitive modern besides the big blood moon/blood sun ETB problem.

**Comment by jeffwadsworth** [comment]
Looking into a refactor of this keyword.

**Comment by JayDi85** [comment]
Fixed via fe28c9c7d9fd43fb9f304e29310b1b788a181270
