### ISSUE TITLE
New Java Version Released

### ISSUE THREAD

**Issue by LunarNightShade** [magefree/mage#5391]
Same issue and procedure as before in issue #5173. 8u181 has been archived and 8u191 has been released. @LevelX2 will need to update the config file.

Java 8u191 download URL for reference: http://download.oracle.com/otn-pub/java/jdk/8u191-b12/2787e4a523244c269598db4e85c51e0c/jre-8u191-windows-x64.tar.gz

**Comment by LevelX2** [comment]
Done!
