### ISSUE TITLE
Portcullis does not set up a delayed trigger for each creature it exiles.

### ISSUE THREAD

**Issue by shujinpantsu** [magefree/mage#5392]
When Portcullis leaves the battlefield, a sperate trigger for each creature it exiled should be created.

**Comment by jeffwadsworth** [comment]
It is not a delayed trigger.  But, the return ability should not be reliant on the Portcullis still having the ability when it does leave the battlefield.  So the card is not coded correctly in this respect.  I will check it out.

http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=5202

**Comment by shujinpantsu** [comment]
Portcullis does create a delayed trigger for each creature it exiles. See CR 603.7.

Yes, Portcullis has two abilities when it should have one.

I believe Portcullis may target as well because i had a game with Psychic Battle on the field and Portcullis' trigger would trigger Psychic Battle. Though that could have been a singular bug.

**Comment by jeffwadsworth** [comment]
The card "Heal" is an example of a delayed trigger.  At least in regard to the code.  If the second ability, bringing the card back from exile when Portcullis leaves the battlefield is a delayed trigger, than almost every trigger would qualify.

http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=201291

**Comment by theelk801** [comment]
Yeah, Portcullis should have a separate delayed trigger for each creature it exiles. The delayed trigger should be created by the ETB trigger resolves.

**Comment by jeffwadsworth** [comment]
Delayed triggered abilities are created by spells and abilities (and some replacement effects). They are unique in that **they wait** around for a bit and then trigger at an appropriate **time**.
Source: https://blogs.magicjudges.org/rulestips/2011/09/delayed-triggered-abilities/
