### ISSUE TITLE
Commander ninjistu not working

### ISSUE THREAD

**Issue by mtgfuller** [magefree/mage#5395]
Quite simple. Upon paying the ninjustu cost, nothing happens.

 (my attacker was a Hypnotic Siren in this case)

**Comment by garypwn** [comment]
I've had this happen as well, and I'll add that it's only happened when ninjutsuing out of the command zone, I've been able to do it from my hand consistently. I've also had it work from the command zone before. There seems to be no pattern to it. I've had it both work and fail from the command zone in the same game. After paying the mana cost, nothing happens and the mana is refunded. The trigger never goes on the stack. If I can figure out what's causing it I'll submit a PR.
