### ISSUE TITLE
Thief of Sanity doesn't allow you to cast the exiled card.

### ISSUE THREAD

**Issue by MasN2** [magefree/mage#5398]
It can attack, and choose a card to exile as normal.
Clicking the exiled card gives an option to look at that card, but not to cast it.
I had enough lands to cast it, but they were the wrong color.

**Comment by MasN2** [comment]
Never mind. I was told that I was supposed to say 'no' when asked whether to look at the card. This could be made more intuitive though.

**Comment by jeffwadsworth** [comment]
The card is exiled upside-down, thus the prompt.  You would have to look at it before casting it.
