### ISSUE TITLE
Playability check doesn't account for phased out lands

### ISSUE THREAD

**Issue by Zzooouhh** [magefree/mage#5400]
"Playability check" in this case is what I call the blue highlight around a card when you have enough mana and the proper timing to play it. This highlight however happens even if the sufficient amount of mana comes from a phased out land - such as when Teferi's Isle is phased out, I have a double blue mana spell and no other mana sources. Word of Command also uses the check and could potentially get broken because of it.

**Comment by LevelX2** [comment]
I can't reproduce this problem.
