### ISSUE TITLE
Server continuosly kicks me out

### ISSUE THREAD

**Issue by DanielMT57** [magefree/mage#5404]
Hello, it is a really annoying situation im experiencing.

![imagen](https://user-images.githubusercontent.com/12564540/47623368-b7708680-dade-11e8-97cc-abe823042f0e.png)

The rest of log says nothing that can address that problem im having.

**Comment by Zerrisx** [comment]
Is there any information to be gathered from this, or it is obsolete?

**Comment by LevelX2** [comment]
obsolete
