### ISSUE TITLE
Conversion to Mobile?

### ISSUE THREAD

**Issue by LordNex** [magefree/mage#5406]
Ive been slowly wandering down the road of learning programming and came across this tool from adobe. I’m a IT Vet but never got too much into heavy application coding. Has anyone tried porting XMage to Android/iOS? If not this might be an easy way to do it. It also free for all open source applications and has an API into GitHub already.

[Adobe PhoneGap](https://build.phonegap.com/)

Also, for someone starting into programming coming from an Microsoft/Cisco background, what would be the best language to learn? Ive done PowerShell and batch scripts and worked on countless routers, switches, and firewalls so I’m ok reading code. It just seems like there are so many flavors Java, JavaScript, JavaFX, Python, Swift, C#
Thanks in advance.

**Comment by JayDi85** [comment]
It's about web client. If you got web client then you can got it to any desktop and mobile platforms. BUT xmage server haven't API for web client at all. API must be implemented first. You can read father here: #5373
