### ISSUE TITLE
Grip of Chaos Force of Will

### ISSUE THREAD

**Issue by MasN2** [magefree/mage#5409]
Just came up in an EDH the other day.
Grip of Chaos was on the battlefield.
Ugin was cast on an empty stack, then a Force of Will was cast targetting it.
Grip of Chaos made the FoW fizzle.
See: https://www.mtgsalvation.com/forums/magic-fundamentals/magic-rulings/magic-rulings-archives/299171-grip-of-chaos-counterspell

**Comment by spjspj** [comment]
Nice, was going to put in an issue report for this :)
