### ISSUE TITLE
Upgrade mtgjson support to v4

### ISSUE THREAD

**Issue by JayDi85** [magefree/mage#5415]
Mtgjson released new version (old version still works until end of the 2018): 
https://mtgjson.com/v4/

It's have many braking changes:
https://mtgjson.com/v4/changelog.html

Needs to upgrade xmage's verify tests to use new version (download and load json data from new v4 source).

**Comment by ingmargoudt** [comment]
I can pick this up if you want @JayDi85

**Comment by JayDi85** [comment]
@ingmargoudt yes, you can do that.
