### ISSUE TITLE
Cubes question

### ISSUE THREAD

**Issue by pmbarrett314** [magefree/mage#5418]
Is there a procedure for when cubes get added to Xmage? I was thinking about adding a couple of the recent MTGO ones that aren't up (it's pretty easy to scrape the lists on the website), but I didn't want to step on toes if the project typically waits until some period after they go off of MTGO or something like that.

**Comment by JayDi85** [comment]
Cubes adds/updates by months/years. All new cubes can be added as single file in `Mage.Server.Plugins/Mage.Tournament.BoosterDraft/src/mage/tournament/cubes` folder ([example](https://github.com/magefree/mage/blob/0c2f478ee41fd2c72ed7018c9e5614678432b140/Mage.Server.Plugins/Mage.Tournament.BoosterDraft/src/mage/tournament/cubes/VintageCubeJune2018.java)).

You can add it by yourself or upload cards list here (for missing/updated cubes) and I will add it.

**Comment by Zerrisx** [comment]
This appears to be answered.
