### ISSUE TITLE
Changes in code not being recognized

### ISSUE THREAD

**Issue by jmharmon** [magefree/mage#5419]
Sometimes I know that I made a mistake in the code for a card I'm trying to implement, but when I change it and restart the server and client it does not get recognized at all. I'm running the server in test mode.

**Comment by JayDi85** [comment]
If you make changes by IDE then all will be fine. I'm uses maven `compile` before run client or server.

Don't forget about client/server databases -- it's contain cards and sets info (name, stats, types). If change it then you must delete all `cards*.db` files from client and server dir to refresh local databases.

Example config to run from IntelliJ IDEA:
![shot_181108_095931](https://user-images.githubusercontent.com/8344157/48180488-20f16000-e33d-11e8-99ff-af3a73231f97.png)

**Comment by jmharmon** [comment]
This could be another issue altogether. I did add what you showed above.
![image](https://user-images.githubusercontent.com/37360760/48181779-b6f59e00-e2dd-11e8-883d-ac55dff37b0d.png)

**Comment by JayDi85** [comment]
Try to re-import maven dependencies and make full build:

1.
![shot_181108_104309](https://user-images.githubusercontent.com/8344157/48182021-34072e80-e343-11e8-8411-4964cce54112.png)


2.
![shot_181108_104430](https://user-images.githubusercontent.com/8344157/48182066-5436ed80-e343-11e8-9c71-b50a15f4ae28.png)

**Comment by jeffwadsworth** [comment]
Which IDE do you use, if any?  Netbeans here and a video could be made to demo the process when making changes to the card code, etc.

**Comment by jmharmon** [comment]
Intellij

**Comment by JRHerlehy** [comment]
If you're just changing cards and sets stuff, you can run a different maven goal so your system doesn't need to build the whole project.

install -pl org.mage:mage-sets -am -DskipTests

Tie this together in IntelliJ with running the batch file that purges the cards DB, and you have something that should let you rebuild in maybe 10-15 seconds rather than 2-3 or more minutes that a full rebuild takes.

**Comment by jeffwadsworth** [comment]
In Netbeans, I just make changes to the card code and save it.  Right-click the "Mage Sets" folder and select Build.  After modifying code of the other classes (Effects/Abilities/Conditions, etc); Right-click the "Mage" folder under "Mage Root" and select Build.  The key is having the fastest SSD you can get.  Saves loads of time.
