### ISSUE TITLE
Chancellor of the Annex bugged

### ISSUE THREAD

**Issue by wbrooksga** [magefree/mage#5421]
Chancellor when revealed in your opening hand will counter the first spell you play even when it's only supposed to affect opponents.

**Comment by jeffwadsworth** [comment]
The card works fine for me in testing.  It would help if you had a log of the game.

**Comment by wbrooksga** [comment]
Where do I find the log?

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.
