### ISSUE TITLE
Muldrotha

### ISSUE THREAD

**Issue by Ysukai** [magefree/mage#5422]
This bug was closed before but is still present if you recast the original Muldrotha.

Have Muldrotha already cast, cast Lion's eye diamond sac for blue, then phantasmal image sac to legend rule so far so good, with the new Muldrotha, cast Lion's eye diamond sac for black then reanimate dead the original Muldrotha, after that you cant cast anything.

Tested a few times,At one point it broke after the first phantasmal image.

Repeat for infinite mana.

**Comment by jeffwadsworth** [comment]
I tested this multiple times and it worked fine.  Make sure you can actually cast something from your graveyard.  It only allows one type per turn!

**Comment by Ysukai** [comment]
I'm currently uploading the video on youtube. I will post the link one it done processing.

**Comment by jeffwadsworth** [comment]
I will test it again following those exact steps in your video and get back.

**Comment by jeffwadsworth** [comment]
I am unable to recreate the issue.  Works fine here.  Perhaps someone else can do it.  Pic attached.  Note the mana in the pool.  
![proof](https://user-images.githubusercontent.com/1496996/49383832-49bc0980-f6df-11e8-9125-52ead6fea0b9.jpg)

**Comment by Ysukai** [comment]
Im playing in Commander.

Can this be related?

**Comment by jeffwadsworth** [comment]
Perhaps.  I never play Commander mode.
