### ISSUE TITLE
wrong text on Machinate (missing "top X")

### ISSUE THREAD

**Issue by cappert** [magefree/mage#5423]
the card text on Gatherer is:

> Look at the top X cards of your library, where X is the number of artifacts you control. Put one of those cards into your hand and the rest on the bottom of your library in any order.

The text in XMage:
> Look at **the** top card of your library. Put one of them into your hand. Put the rest on the bottom of your library in any order.
 
I think it is autogenerated from the code?

https://github.com/magefree/mage/blob/0c2f478ee41fd2c72ed7018c9e5614678432b140/Mage.Sets/src/mage/cards/m/Machinate.java#L31-L33

I'm not sure but I think the code is wrong too (`new StaticValue(1)`)

**Comment by JayDi85** [comment]
It's work fine:
* artifactsOnControl -- number to look (it's dynamic);
 * new StaticValue(1) -- number to pick.

But text must be fixed.

**Comment by JayDi85** [comment]
Fixed via 20fe92b98becc76b3a97b78851b59cadb7bbe154
