### ISSUE TITLE
the text on Spell Contortion is missing Multikicker

### ISSUE THREAD

**Issue by cappert** [magefree/mage#5424]
Spell Contortion is missing Multikicker in the card text.

maybe because of the GetRules override?

https://github.com/magefree/mage/blob/0c2f478ee41fd2c72ed7018c9e5614678432b140/Mage.Sets/src/mage/cards/s/SpellContortion.java#L46-L50

**Comment by JayDi85** [comment]
Yep, you are right. It's a wrong getRules text.

Fixed via fe3eda494489c5fd3ff73c1b3669c485187e3250
