### ISSUE TITLE
Experimental Frenzy

### ISSUE THREAD

**Issue by DominusMaximus** [magefree/mage#5428]
When you click on the top card of your library in order to cast it, the card below it is immediately revealed, even though you haven't payed any costs, and can undo casting the card you just clicked. 

From one of the rulings on Experimental Frenzy:

"If the top card of your library changes while you’re casting a spell or activating an ability, you can’t look at the new top card until you finish casting that spell or activating that ability. This means that if you cast the top card of your library, you can’t look at the next one until you’re done paying for that spell."

**Comment by FastTadpole** [comment]
I also found there was an issue with casting split cards from the top of deck. I had a deep desire to cast the flower end of Flower // Flourish and it was just a dead click.

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.
