### ISSUE TITLE
Remember draft/sets settings in new game/tournament dialogs

### ISSUE THREAD

**Issue by JayDi85** [magefree/mage#5432]
From forum:

Would love it if the last used settings for the Chaos Draft (Random Booster Draft) Packs Selector remembered the last chosen packs from the previous draft you created. As is stands you have to uncheck a bunch of sets each time which is time consuming and annoying. Thanks!

**Comment by Zerrisx** [comment]
I think this has been addressed - it seems to remember my last picked sets (in addition to having two saves at the bottom).
