### ISSUE TITLE
Mnemonic Betrayal AsThoughEffect Not working

### ISSUE THREAD

**Issue by HCrescent** [magefree/mage#5433]
Mnemonic betrayal is supposed to have a spend mana as though it were of any color effect but when playing commander vs the AI It was forcing me to use white mana for white spells

**Comment by jeffwadsworth** [comment]
It would help to have the log of the game.

**Comment by HCrescent** [comment]
You don't need a log, the game log does not even show that you tried to play a spell but couldn't due to not having the right mana because no action happens, AND you have all the info needed save for the exact name of the function which is MnemonicBetrayalAnyColorEffect. I have already reproduced the bug several times before posting to be sure it was not just an odd game state causing the issue. I also discovered that it lets you play your opponents lands as if this were Yawgmoth's will which is also wrong. If I have time, ill just take care of this myself, but it may be a while before I can sit down to work it out. In the meantime if somebody else wishes to tackle this they are free to do so, I will get to it eventually.
