### ISSUE TITLE
Angel of Serenity ability only triggers once with Panharmonicon on battlefield

### ISSUE THREAD

**Issue by SpikesCafe-google** [magefree/mage#5434]
Angel of Serenity's ETB ability should probably inherit from EntersBattlefieldTriggeredAbility instead of OneShotEffect.

https://github.com/magefree/mage/blob/0c2f478ee41fd2c72ed7018c9e5614678432b140/Mage.Sets/src/mage/cards/a/AngelOfSerenity.java#L109

The bug is that it only triggers once when there is a Panharmonicon in play.

> 6:43 PM: SpikesCafe2 casts Angel of Serenity [bff]
> 6:43 PM: SpikesCafe2 puts Angel of Serenity [bff] from stack onto the Battlefield
> 6:43 PM: Ability triggers: Trostani, Selesnya's Voice [523] - Whenever another creature enters the battlefield under your control, you gain life equal to that creature's toughness.
> 6:43 PM: Ability triggers: Trostani, Selesnya's Voice [523] - Whenever another creature enters the battlefield under your control, you gain life equal to that creature's toughness.
> 6:43 PM: Ability triggers: Angel of Serenity [bff] - When Angel of Serenity [bff] enters the battlefield, you may exile up to three other target creatures from the battlefield and/or creature cards from graveyards. - targeting Dragon [41b] Dragon [7e0] Atarka, World Render [312]

**Comment by jeffwadsworth** [comment]
It is because the Pan is checking specifically for Enters_The_Battlefield triggers and the Angel is using a ZoneChangeTriggeredAbility, which is a variant.  Checking it out.
