### ISSUE TITLE
Must attack not working when more than 2 players

### ISSUE THREAD

**Issue by jeffwadsworth** [magefree/mage#5435]
The "must attack" effect is bugged when there are more than 2 players.
Test example: Goblin Spymaster token in play.  3 or more players.  Only 1 or a few attackers are forced.  May be related to the targeting code in Combat.java.  Checking it out.

**Comment by JayDi85** [comment]
Related with must attack: 
 * #4999 -- have source code researching;
 * #5283

Same problem with must block:
 * #4496

**Comment by jeffwadsworth** [comment]
The Goad stuff is due to insufficient situational checking and should be fixed soon.

**Comment by JayDi85** [comment]
It was multiplayer's RangeOfInfluence settings. Range.ALL -- "must attacks" affects to all, but RangeOfInfluence.ONE -- "must attacks" affects to 1-2 players, not all.

Returned old code for AI to select multiple targets, not select only first (4288e45c2385f1dbcb1e700d54fd52d6a286a600) -- it's not improved gameplay (AI for `TargetDefender` uses planeswalker as priority and can't distribute the attackers between different targets), but it can be useful for father improvements.
