### ISSUE TITLE
XMage disconnects from server every 30 secs

### ISSUE THREAD

**Issue by JayDi85** [magefree/mage#5444]
@LevelX2 There are disconnection issues on xmage.de after update to 32v0 -- every 30 secs players and watchers disconnected from server by error (only if they join/watch game). I can't reproduce that problem with local server. It's can be xmage.de issue only.

```
INFO  2018-11-27 00:00:53,476 Watching game 2336b16a-d606-4956-9069-0ddd3158eebb                                         =>[AWT-EventQueue-0] CallbackClientImpl.watchGame 
INFO  2018-11-27 00:01:15,749 connection to server lost - Could not connect to server!                                   =>[Thread-10585] SessionImpl$ClientConnectionListener.handleConnectionException 
java.lang.Exception: Could not connect to server!
	at org.jboss.remoting.Client.notifyListeners(Client.java:1886)
	at org.jboss.remoting.LeasePinger.stopPing(LeasePinger.java:134)
	at org.jboss.remoting.MicroRemoteClientInvoker.terminateLease(MicroRemoteClientInvoker.java:434)
	at org.jboss.remoting.ConnectionValidator$WaitOnConnectionCheckTimerTask.run(ConnectionValidator.java:1108)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
INFO  2018-11-27 00:01:15,750 RECONNECT - Connected: true                                                                =>[Thread-10585] SessionImpl.reconnect 
INFO  2018-11-27 00:01:15,750 DISCONNECTED (NO Event Dispatch Thread)                                                    =>[Thread-10585] MageFrame.disconnected 
INFO  2018-11-27 00:01:16,229 DISCONNECT (still connected)                                                               =>[AWT-EventQueue-0] SessionImpl.disconnect 
INFO  2018-11-27 00:01:16,307 Disconnected ...                                                                           =>[AWT-EventQueue-0] SessionImpl.disconnect 
INFO  2018-11-27 00:01:16,307 DISCONNECTED (Event Dispatch Thread)   
```

**Comment by LordNex** [comment]
Cool, thanks

Let me know if there's anything I can do to help

**Comment by JayDi85** [comment]
It's not me... LevelX2 is server's admin and releaser. You was able to update your server to new version and checks disconnects. But it's late after rollback. Waiting info from LevelX2.

**Comment by LordNex** [comment]
No i don't think i ever got the newer version. I think by time I got home the rollback had already happened. It wasn't until I started looking at the version numbers and then checking here that I seen there was a issue. Thanks man, I'll keep an eye out for it to re-release

**Comment by LevelX2** [comment]
Anyone any idea which commit/change yould have influence on network stability and so causing the disconnects?

**Comment by JayDi85** [comment]
There were some threads dependency code for AI rating in drafts (read data from resources) -- but it have synchronized code and only for drafts: 6f93abfd5ad7f4dd3630f2eab093cb62ddd546f5

**Comment by LevelX2** [comment]
[mageserver.log](https://github.com/magefree/mage/files/2621055/mageserver.log)

**Comment by jeffwadsworth** [comment]
Since it works fine locally, perhaps the issue is related to the account management.  I only use a test server setup myself.

**Comment by JayDi85** [comment]
@LevelX2 there were same problems with old versions long ago ([search](https://github.com/magefree/mage/issues?q=is%3Aissue+LeasePinger+is%3Aclosed)). 

Look at #586 -- it's have your recommend settings for public server BUT your current config is DEFAULT (see server logs -- it's store different settings from your recommendations at #586). At your logs server works find 5 minutes but start to disconnecs. It's can be too more users online and too low server settings.

**Comment by JayDi85** [comment]
New v33 works fine. I'm founded the disconnects reason -- server's start script don't copy original config on new version install and uses default one from ...neu1 folder.
