### ISSUE TITLE
Kicked Fight with Fire & Primal Wellspring

### ISSUE THREAD

**Issue by DominusMaximus** [magefree/mage#5445]
I copied a kicked Fight with Fire by paying for it with Primal Wellspring. For the original Fight with Fire I chose 3 targets: 5 damage to a creature, 1 damage to another creature, and 4 damage to the opponent. For the copy, I wanted to deal all 10 damage to the opponent. When it was time to choose targets for the copy, the client first asks me if I want to change the original 5 damage target (one of the creatures). I click yes, but when I choose the opponent, it says the opponent was an original target and if I want to reset the target to the original. If I choose no from here, it will simply ask me again where I want to redirect those 5 damage. If I choose yes, it will once again target the creature with those 5 damage. 

I also tried dealing all 10 damage to the player with the original Fight with Fire so that I can then choose the 3 different targets with the copy, but this didn't work either. I was able to select all 3 targets without issue, but when the copy resolved, it didn't seem to register all 3 targets, as it would only deal 5 damage to 1 creature.

**Comment by ruler501** [comment]
When you copy a spell all choices such as number of targets, modes, and distributions must stay the same, the only thing that's allowed to change are targets.
Mage shouldn't allow you to add targets to the copy and if it does that's a bug that should be fixed

**Comment by JayDi85** [comment]
It's an UI bug -- xmage allows to change number of targets (but must didn't -- see above), but actual targets and damage will be correct. Example: first spell have 2 targets, for copied spell you select 4 targets with different damage -- but xmage will use only 2 new selected targets).

**Comment by DominusMaximus** [comment]
I understand now. Thank you.

**Comment by Zerrisx** [comment]
This looks to be resolved and/or a UI bug different from the one being described here which should have its own issue.
