### ISSUE TITLE
about:create a tournament, if the submitted time is inconsistent (about 1-2 minutes), it will easily cause the game to be lost and cannot match.

### ISSUE THREAD

**Issue by siyiye** [magefree/mage#5447]
example:
create a tournament, if the submitted time is inconsistent (about 1-2 minutes), it will easily cause the game to be lost and cannot match.

Now only the decks are formed, and the public channel is ordered to click and submit together - can you guarantee the time of the group (15 minutes for example), i can submit it at any time?

**Comment by Zerrisx** [comment]
Pretty sure this is a duplicate of #5555.  If it's not, can you provide additional clarification?
