### ISSUE TITLE
Xmage doesn't update properly to 1.4.32V1

### ISSUE THREAD

**Issue by Stafy1** [magefree/mage#5449]
Trying to update Xmage to the latest version, but it fails to do so. It stays to 1.4.31V4.

The game version in the launcher is 1.4.32V1OLD while both the server and the console say 1.4.31V4. I don't have access to UMA or the new Guilkits.
![screenshot_125](https://user-images.githubusercontent.com/35297448/49339176-a44d5b00-f636-11e8-8be2-c9e2fd18747f.png)
![screenshot_126](https://user-images.githubusercontent.com/35297448/49339177-a6171e80-f636-11e8-8be2-a891d367c401.png)
![screenshot_127](https://user-images.githubusercontent.com/35297448/49339179-a9120f00-f636-11e8-80cb-f729bf2af798.png)

**Comment by JayDi85** [comment]
That's ok, xmage was rollbacked to old version due [server disconnects](https://github.com/magefree/mage/issues/5444). Wait next releases.
