### ISSUE TITLE
World rule SBA not implemented

### ISSUE THREAD

**Issue by emerald000** [magefree/mage#545]
The "world rule" state-based action is currently not implemented.

704.5m. If two or more permanents have the supertype world, all except the one that has had the world supertype for the shortest amount of time are put into their owners' graveyards. In the event of a tie for the shortest amount of time, all are put into their owners' graveyards. This is called the "world rule."

The only currently implemented World enchantment is Nether Void. (Working on The Abyss right now)

**Comment by fireshoes** [comment]
I'm adding Concordant Crossroads today and noticed this.

**Comment by LevelX2** [comment]
Fixed with ccae89e181423694b0643f4592cf311388618c11.

**Comment by LevelX2** [comment]
Take care of range if influence for checking.

**Comment by Zerrisx** [comment]
Fixed with recent range of influence changes.
