### ISSUE TITLE
Small log output errors

### ISSUE THREAD

**Issue by GORE84** [magefree/mage#5459]
Noticed two cards are outputting the log in wrong order.
Typically it is [timestamp] [user] [action] [card]
14:22 qwerty casts Serum Visions

Found on two cards that the order are wrong:
Serum Powder, Firemind's Foresight

I wrote a fix for them already:
**Firemind's Foresight**
`game.informPlayers(player.getLogName() + " chose " + card.getName + " with " + sourceCard.getName());`

**Serum Powder**
`game.informPlayers(controller.getLogName() + " exiles hand and draws " + cardsHand + " card(s) using " + sourceCard.getLogName() +"'s ability");
`

**Comment by GORE84** [comment]
Also Rest in Peace, Leyline of the Void and Dryad Militant handle the exile wrong.
Right now the owner of for example Rest in Peace handle all the exile cards which is wrong. It's a game action and not player action.
Maybe change `return controller.moveCardToExileWithInfo` to  `card.moveToExile` and `game.informPlayers`

**Comment by GORE84** [comment]
Noticed also on Path to Exile have same issue. According to game log the player who cast it also moves the target to opponents exile zone. This is sort of wrong. A player doesn't move a card to exile zone. It's a mandatory action that neither player has agency on.

**Comment by RaneWallin** [comment]
HI Tom, please consider submitting a pull request for your update.
