### ISSUE TITLE
Rakshasa Vizier error

### ISSUE THREAD

**Issue by jmharmon** [magefree/mage#5475]
From Gathering rulings, playing a card with delve while Rakshasa Vizier in play should only cause its ability to trigger once. Currently it triggers once for each card delved.

![image](https://user-images.githubusercontent.com/37360760/50425751-77552800-0831-11e9-9935-76f0b90ca409.png)

**Comment by theelk801** [comment]
This is actually mentioned in the code for the card. I think I can fix it though.
