### ISSUE TITLE
Yuriko Commander Ninjutsu not working as it should

### ISSUE THREAD

**Issue by Ischyro-V** [magefree/mage#5481]
After playing a commander came with Yuriko, the Tiger's Shadow I noticed that when trying to activate her commander ninjutsu at the end of the declare blockers step (When a creature is not blocked) the ability is put on the stack and you are asked to pay for it, yet when you do it untaps your lands/refunds your mana and the ability is removed from the stack without resolving. I looked up when the ability should be activated on X-mage and found nothing, Am I using it wrong for the program, or is the ability still not working?

**Comment by Ischyro-V** [comment]
Turns out the ability works fine. If you pay for it with basic lands. Using mana from a mana rock, dual land, or command tower seems to not work from my testing.

**Comment by jeffwadsworth** [comment]
Make sure you check the colored mana indicators on the left.

**Comment by Ischyro-V** [comment]
I thought that's what it was at first after I got it to work, but then it happened when using a dimir signet or two dual lands after using the ability.

**Comment by Ischyro-V** [comment]
It is no longer working at all, I have no Idea how I got it to work three days ago.
(The issue also happens against opponents who aren't using Island Sanctuary or Ghostly Prison)
![testing_yuriko](https://user-images.githubusercontent.com/46231669/50571746-00ef8300-0d67-11e9-8b3c-1db3a8621a6d.gif)
![testing_yuriko_2](https://user-images.githubusercontent.com/46231669/50571747-077dfa80-0d67-11e9-9b09-a857949ce3e4.gif)

**Comment by Zerrisx** [comment]
Duplicate of #5237
