### ISSUE TITLE
Extra ETB trigger from Grinding Station?

### ISSUE THREAD

**Issue by Qonfused** [magefree/mage#5484]
After Grinding Station first enters the battlefield, I am prompted to choose whether to untap it or not, though no other Grinding Station had already been in play. Doesn't really make much sense as to how this happens... I'm running it on XMage 1.4.32V1OLD (2018-11-26).

**Comment by theelk801** [comment]
This is how it's supposed to work, it "sees itself" enter the battlefield and triggers its ability.
