### ISSUE TITLE
Grave Betrayal doesn't work properly.

### ISSUE THREAD

**Issue by Stafy1** [magefree/mage#5488]
![screenshot_128](https://user-images.githubusercontent.com/35297448/50691439-61b5de80-1039-11e9-9698-9bb6a49f0291.png)

My Markov Blademaster was reanimated by it with only 1/1 counter on it without being black and a zombie.

**Comment by jeffwadsworth** [comment]
I have recently noted some inconsistent behavior with effect.setTargetPointer().  It used to work fine.
