### ISSUE TITLE
Wish Type cards dont work in Commander formats.

### ISSUE THREAD

**Issue by GertrudeRoyale** [magefree/mage#5494]
Burning Wish and (there i a blue wish card i cant remember) dont have any card pool to search from as you cant have any side board cards in Commander.

**Comment by Zzooouhh** [comment]
There's a wish card for every color plus a GW one. No sideboards in commander and Wish cards having no effect is as per the official (i.e. recommended) rules of commander. See http://mtgcommander.net/rules.php
