### ISSUE TITLE
UI: add extra colored hints in card text

### ISSUE THREAD

**Issue by JayDi85** [magefree/mage#5497]
Some cards uses watchers and filters to calculate conditions -- e.g. deal damage equals to lands count or activate ability after creature dies.

It's can be useful to add extra hints to ability texts (e.g. show land counts, show raid condition and etc). Some cards and abilities have that dynamic texts already, but it's manually created. MTG Arena have same hints too.

Example 1 (good/bad icon):
![shot_190205_130001](https://user-images.githubusercontent.com/8344157/52263120-bf468f00-2947-11e9-8dd0-1044ebaf6e3c.png)

Example 2 (look at green colored text):
![shot_190108_160538](https://user-images.githubusercontent.com/8344157/50830036-eec1a600-135f-11e9-83f2-6cf89b19dd91.png)

Example 3 (multiple hints per card):
![shot_190205_232724](https://user-images.githubusercontent.com/8344157/52299240-5fc79e00-299e-11e9-9d0e-4d45dc28757b.png)

And code example: 
```
  Ability ability = new SimpleStaticAbility(...);
  this.addAbility(ability
      .withHint("Gate cards", new PermanentsOnBattlefieldCount(filter))
  );
```

TODO:
 * [x] hints are UI and gameplay only (e.g. don't show it in logs/deck editor);
 * [ ] add scrolls for popup hints (big rules and hints with big font need more space);
 * [ ] ?hints can be disabled in preferences?;
 * [ ] ?hints are independent from rules text?;
 * [x] multiple hints for ability (one hint per line);
 * [ ] ?insert hint marks in rules text (deck editor ignores it, but game will replace with icons/text);
![shot_190205_131754](https://user-images.githubusercontent.com/8344157/52263393-78a56480-2948-11e9-918d-b1e51517b531.png)
 * [x] style hint: name - value ("some value", 123);
 * [x] style hint: condition ("activated", "not activated", condition);
 * [x] style hint: icons condition ("good/bad icon with text", condition);
 * [x] style hint: ~~formatted text with dynamic values ("Some %d have %d and %d", [val1, val2, val3]);~~ Just override `getText`.

Ability specific TODO:
* [ ] add card hint for `ActivateIfConditionActivatedAbility`; 
  * [ ] remove my turn condition from cards construction;
  * [ ] test condition texts (add alternative texts to donditions like getHintText?);
  * [ ] add auto-capitalize of first symbol;
  * [ ] add support of compound conditions;
* [ ] add card hint for `LimitedTimesPerTurnActivatedAbility`;
* [ ] add card hint for `CastOnlyDuringPhaseStepSourceAbility`;

**Comment by jeffwadsworth** [comment]
@JayDi85 I would like to attach your conditional hint on a targeted card.  For example, regeneration.  It works great for something like Drudge Skeletons, but I would like to use it for the target of Rushwood Herbalist (https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=19622)
![Regeneration Shield InActive](https://user-images.githubusercontent.com/1496996/89079291-bae81000-d34b-11ea-82a7-5973caf4d3db.jpg)
![Regeneration Shield Active](https://user-images.githubusercontent.com/1496996/89079306-c63b3b80-d34b-11ea-81de-f75229d019dd.jpg)

.  Example of its use with Drudge Skeletons attached.

**Comment by JayDi85** [comment]
@jeffwadsworth I improved regeneration abilities by c7595ca476a10bb97ce5c8b46d0a105eea785dc2 Now it shows regen shield status as your screenshots.

If you want to use temporary card hint for permanents (until duration or while conditional) then use:
* For constant text: `InfoEffect.addInfoToPermanent`
* For dynamic card hint: `InfoEffect.addCardHintToPermanent`

![shot_200801_210407](https://user-images.githubusercontent.com/8344157/89106950-77ba9980-d43e-11ea-81b1-3923b6bd0617.png)
![shot_200801_210243](https://user-images.githubusercontent.com/8344157/89106952-79845d00-d43e-11ea-9539-6029af31a646.png)
