### ISSUE TITLE
Bug with Layer 6 land converters

### ISSUE THREAD

**Issue by jeffwadsworth** [magefree/mage#5500]
While testing Conversion, I noticed that Phantasmal Terrain has the same layer 6 issue.  Looking for a work-around for these two cards as well as Glacier.  The layer 4 part is fine, but the layer 6 ability is not.

**Comment by jeffwadsworth** [comment]
I am going to pull in Glacier and make the adjustments to get Layer 6 going.

**Comment by jmharmon** [comment]
![image](https://user-images.githubusercontent.com/37360760/51012425-d7c2b580-1511-11e9-9be1-e92e522423ef.png)
Can confirm it works. Also shouldn't Magus of the Moon be changed, since you changed Blood Moon?

**Comment by jeffwadsworth** [comment]
Yes, doing that now.
