### ISSUE TITLE
Certain selectable cards don't get yellow frames

### ISSUE THREAD

**Issue by Ebola16** [magefree/mage#5505]
I'm new to Magic so forgive me if I'm overlooking something obvious.

It seems all the "Sword of *" from Masterpiece Series: Kaladesh Inventions don't get yellow frames when they are selectable. This may apply to the rest of the set too.

![2019-01-11 copy](https://user-images.githubusercontent.com/17330088/51031378-67944e00-156a-11e9-9938-bff38aa0e7a5.png)

**Comment by JayDi85** [comment]
Fixed via d1e2fc860d89af927334ee063b45895a9ca3196c
