### ISSUE TITLE
The fused option for Far // Away needs to be selected twice

### ISSUE THREAD

**Issue by Ebola16** [magefree/mage#5506]
I'm new to Magic so forgive me if I'm overlooking something obvious.

The fused option for Far // Away is at the bottom of the possible options when casting the card. If I select it, the option jumps to the top and I need to select it again. I should probably only need to select the fused option once.

~~I also can't select the order of Far or Away. Far is always first. Perhaps after selecting the fused option, I should be asked which one I want to happen first?~~

**Comment by jmharmon** [comment]
On fused cards, the left side always happens first.

**Comment by Ebola16** [comment]
Ok thanks. Ignore that part but the other issue remains.

**Comment by JayDi85** [comment]
Fixed via 63dbf5f40b2b83daa53215beb0c0c0280c43416b
