### ISSUE TITLE
Damage handling of creatures getting first strike after first strike damage dealing step

### ISSUE THREAD

**Issue by LevelX2** [magefree/mage#551]
http://www.slightlymagic.net/forum/viewtopic.php?f=70&t=15076&start=45#p159239
I had an Altac Bloodseeker and Frost Lynx attack my opponent. Opponent blocked the Lynx and I gave it first strike with Crowd's Favor to kill the block. Altac triggered to get +2/0 and gain first strike, but did not deal damage in the regular combat damage step. Since it did not have first strike when first strike combat damage was dealt, it should have dealt the damage in the regular combat step.

702.7c. Giving first strike to a creature without it after combat damage has already been dealt in the first combat damage step won't prevent that creature from assigning combat damage in the second combat damage step. Removing first strike from a creature after it has already dealt combat damage in the first combat damage step won't allow it to also assign combat damage in the second combat damage step (unless the creature has double strike).

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.
