### ISSUE TITLE
Colored frames missing from some selectable cards if Command Tower is in play

### ISSUE THREAD

**Issue by Ebola16** [magefree/mage#5511]
The commander in the match below was Lazav, Dimir Mastermind.

Cyclone Rift and Grim Tutor should have a purple frame here:
![capture](https://user-images.githubusercontent.com/17330088/51070239-25234d80-160c-11e9-8c2f-72ed26a71faa.PNG)

Expected behavior without Command Tower:
![crapture](https://user-images.githubusercontent.com/17330088/51070252-46843980-160c-11e9-93a2-361309aa9230.PNG)

And for some reason the problem occurs with this mana base too:
![captureggg](https://user-images.githubusercontent.com/17330088/51070267-6a477f80-160c-11e9-8d0f-4436bed828e2.PNG)

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.
