### ISSUE TITLE
Cross platform xmage to Android

### ISSUE THREAD

**Issue by ghost** [magefree/mage#5512]
Hi, there. I saw lot of issues for android platform support, I have idea: Facebook came out a new mobile development engine: React Native, developers can use React Native to write android and iOS platforms app. How our developers think?

**Comment by JayDi85** [comment]
It's about new client-server API support. See #5373

**Comment by c4dr01d** [comment]
React Native can call java code using React Native Interface. so....

**Comment by Zerrisx** [comment]
Duplicate of #5406
