### ISSUE TITLE
Error/Forced Rollback with Regal Behemoth

### ISSUE THREAD

**Issue by Rewyn** [magefree/mage#5537]
EDH 3 player game.
Opponent controlled a Regal Behemoth, that was owned by me, with me also being the Monarch.
He killed me (via extort, was at 1 life). Sadly I didn't quite pay attention to whom the monarch went afterwards. Game rollbacked after I died and opponent who previously controlled my Regel Behemoth (which went away with my death) tried to tap a land for mana.

<details>
  <summary>Crash report</summary>
Game exception occurred: java.lang.NullPointerException
Server version: 1.4.33V0 (build: 2019-01-16 13:57)
mage.choices.ChoiceColor.<init>(ChoiceColor.java:41)
mage.abilities.effects.mana.AddManaOfAnyColorEffect.produceMana(AddManaOfAnyColorEffect.java:73)
mage.abilities.effects.common.ManaEffect.getMana(ManaEffect.java:45)
mage.abilities.effects.mana.AddManaOfAnyColorEffect.apply(AddManaOfAnyColorEffect.java:57)
mage.abilities.AbilityImpl.resolveMode(AbilityImpl.java:171)
mage.abilities.AbilityImpl.resolve(AbilityImpl.java:158)
mage.abilities.TriggeredAbilityImpl.resolve(TriggeredAbilityImpl.java:72)
mage.game.GameImpl.addTriggeredAbility(GameImpl.java:1713)
mage.abilities.TriggeredAbilityImpl.trigger(TriggeredAbilityImpl.java:48)
mage.abilities.TriggeredAbilities.checkTrigger(TriggeredAbilities.java:98)
mage.abilities.TriggeredAbilities.checkTriggers(TriggeredAbilities.java:51)
mage.game.GameState.handleEvent(GameState.java:706)
mage.game.GameImpl.fireEvent(GameImpl.java:2682)
mage.abilities.AbilityImpl.activate(AbilityImpl.java:410)
mage.abilities.ActivatedAbilityImpl.activate(ActivatedAbilityImpl.java:288)
mage.players.PlayerImpl.playManaAbility(PlayerImpl.java:1184)
mage.players.PlayerImpl.activateAbility(PlayerImpl.java:1281)
mage.player.human.HumanPlayer.activateAbility(HumanPlayer.java:1566)
mage.player.human.HumanPlayer.activateAbility(HumanPlayer.java:1580)
mage.player.human.HumanPlayer.playManaAbilities(HumanPlayer.java:1113)
mage.player.human.HumanPlayer.playManaHandling(HumanPlayer.java:1006)
mage.player.human.HumanPlayer.playMana(HumanPlayer.java:987)
mage.abilities.costs.mana.ManaCostsImpl.pay(ManaCostsImpl.java:127)
mage.abilities.keyword.ExtortEffect.apply(ExtortAbility.java:80)
mage.abilities.AbilityImpl.resolveMode(AbilityImpl.java:171)
mage.abilities.AbilityImpl.resolve(AbilityImpl.java:158)
mage.abilities.TriggeredAbilityImpl.resolve(TriggeredAbilityImpl.java:72)
mage.game.stack.StackAbility.resolve(StackAbility.java:84)
mage.game.GameImpl.resolve(GameImpl.java:1404)
mage.game.GameImpl.playPriority(GameImpl.java:1354)
mage.game.turn.Step.priority(Step.java:61)
mage.game.turn.Phase.playStep(Phase.java:184)
mage.game.turn.Phase.play(Phase.java:89)
mage.game.turn.Turn.play(Turn.java:127)
mage.game.GameImpl.playTurn(GameImpl.java:858)
mage.game.GameImpl.play(GameImpl.java:767)
mage.game.GameImpl.start(GameImpl.java:731)
mage.server.game.GameWorker.call(GameWorker.java:34)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)
</details>

**Comment by jeffwadsworth** [comment]
Please include the game log.  I am unable to recreate the issue.  I used Donate/Flicker to pass control of the RB around and it worked with no issues.

**Comment by jeffwadsworth** [comment]
Re-open this issue if this occurs again.  Tested it extensively with multiple players, passing it around via Donate and removing the controlling player from the game.

**Comment by Rewyn** [comment]
https://pastebin.com/pmajwD26
This is the log meant I assume? It's pretty much right at the end, since the game was basically over when I died (and the forced rollback did weird things like me not being dead yet, but not having any handcards).
