### ISSUE TITLE
In Bolas's Clutches & Treasure Map

### ISSUE THREAD

**Issue by DominusMaximus** [magefree/mage#5538]
I took control of an opponent's Treasure Map that had 2 counters with an In Bolas's Clutches. I activated the Treasure Map, resulting in the 3rd counter and transformation. Once transformed, clicking on the Treasure Cove would do nothing. I couldn't even tap it for mana. It appears my opponent was now in control of the Treasure Cove, since he could tap it for mana even though it was still on my side of the board and In Bolas's Clutches was still attached to it. 

I couldn't find a ruling for this. Is this how it's supposed to work?

**Comment by Breadamonium** [comment]
I asked on the IRC Judge chat and it seems that you are still supposed to be in control of the permanent as In Bola's Clutches is still attached and it still counts as the same permanent even though it is transformed. Therefore, this is a bug if it is reproducible. See picture attachments below:
![treasuremapinbolasclutches](https://user-images.githubusercontent.com/8561230/51515514-01b58b00-1de2-11e9-938b-32e2fbdf5d02.PNG)
![treasuremapinbolasclutches2](https://user-images.githubusercontent.com/8561230/51515517-0417e500-1de2-11e9-8c42-841bc3227824.PNG)

**Comment by jeffwadsworth** [comment]
Interesting.  I would have thought this type of interaction would have been exposed long before this time.  I will take a look at it.
