### ISSUE TITLE
RNA: Biomancer's Familiar cost reduction affects non-creature abilities

### ISSUE THREAD

**Issue by rystan** [magefree/mage#5541]
![image](https://user-images.githubusercontent.com/6609665/51435764-8c18b600-1c4d-11e9-8245-8830dcdee6f7.png)

Triggering ability of "Simic Ascendancy" which is an Enchantment prompts for the amount of cost reduction.  See included screen capture.

**Comment by ingmargoudt** [comment]
Fixed, thanks for logging the issue!
