### ISSUE TITLE
Forced Rollback when trying to play As Foretold

### ISSUE THREAD

**Issue by Rewyn** [magefree/mage#5542]
Game exception occurred: java.lang.NullPointerException
Server version: 1.4.33V0 (build: 2019-01-16 13:57)
mage.cards.a.AsForetoldAddAltCostEffect.apply(AsForetold.java:167)
mage.abilities.effects.ContinuousEffects.apply(ContinuousEffects.java:1009)
mage.game.GameState.applyEffects(GameState.java:573)
mage.game.GameImpl.applyEffects(GameImpl.java:1530)
mage.players.PlayerImpl.moveCards(PlayerImpl.java:3547)
mage.players.PlayerImpl.moveCards(PlayerImpl.java:3493)
mage.game.stack.Spell.resolve(Spell.java:293)
mage.game.GameImpl.resolve(GameImpl.java:1404)
mage.game.GameImpl.playPriority(GameImpl.java:1354)
mage.game.turn.Step.priority(Step.java:61)
mage.game.turn.Phase.playStep(Phase.java:184)
mage.game.turn.Phase.play(Phase.java:89)
mage.game.turn.Turn.play(Turn.java:127)
mage.game.GameImpl.playTurn(GameImpl.java:858)
mage.game.GameImpl.play(GameImpl.java:767)
mage.game.GameImpl.start(GameImpl.java:731)
mage.server.game.GameWorker.call(GameWorker.java:34)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)

3man edh game, tried to play As Foretold. game rollbacked with the error report when it went onto the stack

**Comment by jeffwadsworth** [comment]
Closing this for now.  If the issue comes up again, please re-open.
