### ISSUE TITLE
"Set Code *** already exists"

### ISSUE THREAD

**Issue by biggreen10** [magefree/mage#5543]
I'm getting an error starting a server where it pulls up each set as part of "Loading Cards", but each set says "Set Code XYZ already exists"

At the end, the server doesn't start. I have played Xmage since the update, so I'm not sure what the issue is.

**Comment by JayDi85** [comment]
It's wrong files in server's folder. You can delete `mage-server` folder at all and force to update again from launcher (if that's old server then take `config` and `db` backup before clean).

**Comment by biggreen10** [comment]
Looks like that worked! Thanks
