### ISSUE TITLE
Continuous effects do not discards after player left the game

### ISSUE THREAD

**Issue by JayDi85** [magefree/mage#5544]
From discord, Stayfrosty310:
> When ever an opponent has an effect that applies to the board, such as stony silence, and they leave before the game is over with a d/c or a concession, the effects still continue. Ive only had it happen to enchanments so far.

**Comment by zeflap** [comment]
Yeah, sounds like a case of "player's gone but board persists"
Easily spotted by the scrollbar that appears for such a player.

**Comment by Zerrisx** [comment]
Duplicate of #4472
