### ISSUE TITLE
Xantcha, Sleeper Agent first ability

### ISSUE THREAD

**Issue by jeffwadsworth** [magefree/mage#5545]
https://www.slightlymagic.net/forum/viewtopic.php?f=70&t=23164&p=229428#p229428
The first ability is a replacement effect.

**Comment by jeffwadsworth** [comment]
I thought this would be non-trivial, but it turned out to be just that.

**Comment by JayDi85** [comment]
From gitter by theelk801:
> @jeffwadsworth I can't comment on issue #5545 for some reason but I had already fixed it

**Comment by jeffwadsworth** [comment]
Wrote a note on gitter about it really needing to be a replacement effect.
