### ISSUE TITLE
Couldn't Cast Thief of Sanity Face-Down Cards

### ISSUE THREAD

**Issue by DominusMaximus** [magefree/mage#5546]
1.4.33V1b

I exiled a Goblin Motivator through Thief of Sanity, but was unable to cast it while it was face-down. Normally I'd click 'No' when prompted to look at the card in order to cast it, but doing so wouldn't bring up the cast prompt. I also tried looking at the card first, but this didn't change anything. I also exiled a creature that wasn't a Goblin Motivator, as well as an instant, but couldn't cast those either.

**Comment by Ebola16** [comment]
Probably related, I couldn't cast cards in exile from Hostage Taker either.

**Comment by Stafy1** [comment]
while on this, I couldn't cast artifacts exiled with Thada Adel, Acquisitor.

**Comment by jeffwadsworth** [comment]
A recent fix for the Aftermath ability apparently had some side-effects.  Thanks for the reports.
