### ISSUE TITLE
Import xmage to eclipse error

### ISSUE THREAD

**Issue by c4dr01d** [magefree/mage#5557]
I forked xmage project to my github account, when I cloned project at my workstation and import to eclipse. At configure the maven project, the eclipse show: Blocked: The user operation is waiting for background work to complete.
How to solve this?

**Comment by JayDi85** [comment]
It's can be eclipse indexing process (xmage have 30k files and it's need some time to analyse).

**Comment by c4dr01d** [comment]
QAQ, the indexing process let me waiting a very long time.

**Comment by c4dr01d** [comment]
And, I want to contribute the code for xmage, have something help or hinting for me?

**Comment by JayDi85** [comment]
I'm recommend to use IntelliJ IDEA -- it's a free IDE and the easiest way to work with xmage (most devs uses it). Netbeans IDE uses for GUI developing.

Start from that wiki-page -- it's have first steps and instructions:
https://github.com/magefree/mage/wiki/Developer-Getting-Started

**Comment by c4dr01d** [comment]
emm, idea for enterprise and community version is to heavy to me, my laptop running idea very slow, so I use eclipse.

**Comment by c4dr01d** [comment]
@JayDi85 If i want porting xmage to other platform, like android, can I create project name like Mage.Client.Android?

**Comment by JayDi85** [comment]
You can make your own project/fork with any name. It's open source. If you success with that then your project/code can be added to official xmage repo. Feel free to ask/request tech support and xmage changes for your purposes.

P.S. I recommends to search/read issues about android and third party client supports. As example: [graphql](https://github.com/magefree/mage/issues?utf8=%E2%9C%93&q=is%3Aissue+graphql)

**Comment by c4dr01d** [comment]
Ok, I will

**Comment by JayDi85** [comment]
Eclipse setup instruction was added to wiki page:
https://github.com/magefree/mage/wiki/Developer-Getting-Started#eclipse
