### ISSUE TITLE
Maven package not found

### ISSUE THREAD

**Issue by c4dr01d** [magefree/mage#5559]
I clone my fork at idea, the idea raise the error: com.googlecode.jspf:jspf-core:0.9.1 not found.

**Comment by ingmargoudt** [comment]
Did you do a clean install of Mage.root ?

**Comment by c4dr01d** [comment]
no, I clone the project at my downstream repository and open it.After configured maven, the idea show this error at a lot of many source file.

**Comment by Orochi4268** [comment]
![image](https://user-images.githubusercontent.com/18334835/51899380-d805f080-23ed-11e9-81a3-b2863225cb0e.png)

**Comment by JayDi85** [comment]
You must import project sources as maven project and selects java 1.8 (if you haven't that then you must install it first).

![shot_190129_135309](https://user-images.githubusercontent.com/8344157/51899885-61f19180-23cd-11e9-892e-46a17240d930.png)

After that open project and create new maven configuration with root folder and `clean install -DskipTests` commands. It's compile and build all files, also it's generates new source files (e.g. to process config files). After that you can run any projects by maven or by IntelliJ itself by run (see wiki for run configuration examples).

![shot_190129_135555](https://user-images.githubusercontent.com/8344157/51900069-c7de1900-23cd-11e9-901a-b18d6a790e91.png)

**Comment by Orochi4268** [comment]
> You must import project sources as maven project and selects java 1.8 (if you haven't that then you must install it first).
> 
> ![shot_190129_135309](https://user-images.githubusercontent.com/8344157/51899885-61f19180-23cd-11e9-892e-46a17240d930.png)
> 
> After that open project and create new maven configuration with root folder and `clean install -DskipTests` commands. It's compile and build all files, also it's generates new source files (e.g. to process config files). After that you can run any projects by maven or by IntelliJ itself by run (see wiki for run configuration examples).
> 
> ![shot_190129_135555](https://user-images.githubusercontent.com/8344157/51900069-c7de1900-23cd-11e9-901a-b18d6a790e91.png)

![image](https://user-images.githubusercontent.com/18334835/51900822-32ed1700-23f1-11e9-8c81-853689aaa4f9.png)

`[ERROR] Failed to execute goal on project mage-common: Could not resolve dependencies for project org.mage:mage-common:jar:1.4.33: The following artifacts could not be resolved: com.googlecode.jspf:jspf-core:jar:0.9.1, jboss:jboss-serialization:jar:1.0.3.GA: Failure to find com.googlecode.jspf:jspf-core:jar:0.9.1 in http://120.79.243.165:8081/repository/hmf-maven-group/ was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :mage-common`

**Comment by Orochi4268** [comment]
![image](https://user-images.githubusercontent.com/18334835/51901198-0ede0580-23f2-11e9-9380-72e8608a303d.png)
![image](https://user-images.githubusercontent.com/18334835/51901210-143b5000-23f2-11e9-8bf3-fb431c94630e.png)

**Comment by JayDi85** [comment]
Check your connection to JBoss repository (can you open that link?):
https://repository.jboss.org/nexus/content/groups/public

**Comment by c4dr01d** [comment]
@JayDi85 We can connect to JBoss repository
