### ISSUE TITLE
Xmage skipping over the select blockers step when planeswalkers are being attacked.

### ISSUE THREAD

**Issue by MxTulip** [magefree/mage#5572]
Additional information: The planeswalkers in question were lilliana of the veil and sorin, lord of innistrad. Issue occurred several times during a match, when we rolled back and my opponent attacked me instead the select blockers step was not skipped. Issue occured with multiple different opposing creatures, and different prospective blocking creatures as well. It's possible a one of sorins vampire tokens was present each time, but so where other creatures, bitterblossom tokens ect.
Logs:
[20190203_034235_Canadian Highlander Two Player Duel_1.txt](https://github.com/magefree/mage/files/2825187/20190203_034235_Canadian.Highlander.Two.Player.Duel_1.txt)
[20190203_041247_Canadian Highlander Two Player Duel_2.txt](https://github.com/magefree/mage/files/2825188/20190203_041247_Canadian.Highlander.Two.Player.Duel_2.txt)

**Comment by MxTulip** [comment]
looks like this:
![prefscreen](https://user-images.githubusercontent.com/45216236/52179882-e5511f80-27df-11e9-919c-8987aeef0d44.png)

**Comment by jeffwadsworth** [comment]
This appears to be caused by a commit I made to fix Curse of Opulence.  https://github.com/magefree/mage/commit/cd2312566498642df14a0da63d6a5e89f39e5f42
I will check it out.
