### ISSUE TITLE
"Restless Dreams" doesn't work

### ISSUE THREAD

**Issue by OttosethBis** [magefree/mage#5577]
With "Restless Dreams", the first line work: "As an additional cost to cast this spell, discard X cards.",
It's possible to discard card in hand,

But, the second line: "Return X target creature cards from your graveyard to your hand.", doesn't work, it's like if the second line doesn't exist on Xmage, the card can enter in the stack, but when the effect is resolved, nothing's happening, and the card is put into the graveyard,

Thanks for reading my bad english, 😅 

And I love Xmage ! Thanks for this !

**Comment by jeffwadsworth** [comment]
It was missing a target adjuster.  It will be fixed in the next release.
