### ISSUE TITLE
Thousand-Year storm watcher effect issue

### ISSUE THREAD

**Issue by HCrescent** [magefree/mage#5578]
The implementation for Thousand-year storm(TYS) is incorrect in cases where you cast more instants and sorceries before you let the TYS trigger resolve.  The current implementation would be correct if the card read "copy it for each other instant and sorcery spell you’ve cast this turn" but it actually reads "copy it for each other instant and sorcery spell you’ve cast BEFORE IT this turn" which means it remembers how many that was by the time the trigger would resolve. Currently you can cheat by getting many copies of spells that shouldn't get copies made.

**Comment by jeffwadsworth** [comment]
I will check this out.
