### ISSUE TITLE
 Domri, Chaos Bringer - saves +1 mana's trigger for next turns

### ISSUE THREAD

**Issue by JayDi85** [magefree/mage#5582]
Domri, Chaos Bringer's bug can accumulate +1 mana's triggers turn by turn. E.g. player can add 1, 2, 3+ riot abilities for one creature cast.

init.txt code:
```
[test domri]
battlefield:Human:Mountain:6
battlefield:Human:Domri, Chaos Bringer:1
hand:Human:Burning-Tree Vandal:3
```

Steps to reproduce:
 * use domri +1 to add red mana;
 * skip creature cast and go to your next turn;
 * use domri +1 to add red mana;
 * cast red creature -- it's will get 3 riot (1 from card, 2 from domri).

**Comment by jeffwadsworth** [comment]
This looks like an issue related to continuous effects not being cleared correctly.  Perhaps related to the duration "end of step" being buggy.  Doing some tests on this.
