### ISSUE TITLE
Karador and Dryad Arbor

### ISSUE THREAD

**Issue by propri** [magefree/mage#5586]
Karador, Ghost Chieftain should not be able to play Dryad Arbor from the graveyard. Dryad Arbor cannot be cast, and Karodor only allows to **cast** creatures from the graveyard.

**Comment by ingmargoudt** [comment]
Looks like Karador only filters the graveyard on creatures and not on “castable” creatures. Good catch!

**Comment by jeffwadsworth** [comment]
If no one else fixes it, I will in the morning.

**Comment by ingmargoudt** [comment]
go for it @jeffwadsworth

**Comment by jeffwadsworth** [comment]
Ran into an interesting card in testing.  Zoetic Cavern.  It is a land but can be cast with Morph.  
Good thing we have the test suite.
