### ISSUE TITLE
Rhystic Study can broken AI game

### ISSUE THREAD

**Issue by JayDi85** [magefree/mage#5595]
[From reddit](https://www.reddit.com/r/XMage/comments/aqbccx/botai_not_playing_any_cards/):

> In the past I have noticed that if i put a Rhystic Study in play against AI while I am playtesting a deck, the AI will no longer cast any spells. Have you considered that you may have started playing a new card that wrongly suggests to the AI that under no circumstances it should ever cast a spell again? When I playtest now, if i draw a study i just dont play it and consider it a dead draw so that game continues more realistically.
> 
> Edit: this is only one example of a card that I have found to throw off the AI. I dont think the AI has ever cast sword to plowshares or path to exile on me because of the beneficial effect when they have been in decks I loaded for the AI to use against me.

And another comment:

> Any time theres an effect on the board that could be beneficial to you, the ai chooses to avoid it. For example Taurean mauler and the like. Anything that says "whenever a player casts a spell" or "whenever an opponent casts a spell"

**Comment by jeffwadsworth** [comment]
I can't recreate this.  It works fine for me with multiple or single AI's.

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.
