### ISSUE TITLE
Question - Hosts file configuration

### ISSUE THREAD

**Issue by smadigan91** [magefree/mage#5597]
Hello,

I have been trying to figure out how to have remote friends join my local XMage server, but have not been able to figure out how yet.

Currently, without modifying my hosts file, when friends try to join using my public IP address, they see a window pop up that just says "Sean-PC" (my computer name) and they are unable to join. I am not really sure what this means. I am able to join using my public IP address using another computer in my house, but it is on the same network so I think that's why.

I am wondering, what entries need to be made in the /etc/hosts file on my computer vs. my friends computers?

My computer's name / host name: "Sean-PC"
My computer's public IP address: "139.68.81.23"
My computer's private IP address: "192.168.0.25"

Should I be adding any of this information to my / their hosts files? Or do I just need to add `127.0.0.1 localhost` to my hosts file and have my friends include the `-Djava.net.preferIPv4Stack=true` argument for their client?

Thank you  for your help.

**Comment by JayDi85** [comment]
On your server:
 * add to host file: `192.168.0.25 Sean-PC`
 * change config `\xmage\mage-server\config\config.xml`:
   * serverAddress="Sean-PC";
   * port="17171";
   * secondaryBindPort="17179"

On your router:
 * you must setup port forward from router to 192.168.0.25 (ports 17171 and 17179);

On friends machines:
 * add to host file: `139.68.81.23 Sean-PC`
 * connects to `Sean-PC` server address.

**Comment by smadigan91** [comment]
So I tried this, and my friends tell me when they click connect, a window pops up that says 'Sean-PC' and they click 'OK' but nothing happens. Any idea what might have gone wrong?

**Comment by JayDi85** [comment]
Upload errors logs from clients to https://pastebin.com/ (`\xmage\mage-client\mageclient.log`). Also check xmage client on server side too (can you connects to own server by Sean-PC name AND by ip 139.68.81.23 -- enter it in connect dialog).

**Comment by smadigan91** [comment]
https://pastebin.com/MsEU8Gwp

and yes, I can join at both 139.68.81.23 and Sean-PC on from my own machine

**Comment by smadigan91** [comment]
Ah we figured out the issue, he had an antivirus program that kept reverting his changes to his hosts file. Once he closed it we were able to play. Thanks!
