### ISSUE TITLE
UI Suggestion: Please add Windows notification for "Your match has started" (esp. rounds 2 & 3 of draft)

### ISSUE THREAD

**Issue by duelcastermage** [magefree/mage#5598]
I would love it if another Windows notification alert was added to signal the start of matches being ready to play. We already have notifications for "A player has joined the table" and "Pick the next card", which are super useful, but no such notification for matches starting. I realize there is an audio alert, but for various reasons I can't always play with my sound on.

I've been on both sides of this many times and have lost matches because of it. It's especially a problem in draft when you have a bye and are sitting around for a long time, or if you finish your match early and are waiting a long time for others to finish.

Thanks!

**Comment by xenohedron** [comment]
Added in 2ec532b :)
