### ISSUE TITLE
Support alternative mulligan rules, such as the London Mulligan

### ISSUE THREAD

**Issue by hitch17** [magefree/mage#5600]
> For Mythic Championship II in London, we're going to be trying out a new mulligan rule that we have been playtesting internally for some time. We believe the new rule smooths out opening hand decisions even more, though it certainly has some implications for formats like Modern.
>
> The rule we'll be testing in London is as such: When you mulligan for the Nth time, you draw seven cards, then put N cards on the bottom of your library in any order.
>
> So, for example, let's say you're taking your second mulligan of a game, what we often call a mulligan to five. You would draw seven cards, select two, and place those two on the bottom of your library in any order. Then you would decide whether to keep or mulligan again.

https://magic.wizards.com/en/articles/archive/competitive-gaming/mythic-championship-ii-format-and-london-test-2019-02-21

**Comment by JayDi85** [comment]
Other mulligan types: https://mtg.gamepedia.com/Mulligan
