### ISSUE TITLE
 Wurmcoil Engine generates wrong token images

### ISSUE THREAD

**Issue by JayDi85** [magefree/mage#5604]
From facebook (card generates different tokens with same image, but must use different images):

> Alright guys I need help. I am working on cleaning up some of my images on xmage. One think that really bothers me is the images that xmage generates for tokens. Even though I go into card viewer and it shows me that I have the correct images for tokens, what xmage actually generates for tokens seems pretty random. The biggest frustration is with wurmcoil engine. Ive messed around with all of the versions of wurmcoil engine in xmage, but every one when it dies, the system generates two lifelink tokens and no deathtouch ones, making it hard to know which one is which. I have images for deathtouch ones, they just dont generate. Anyone know how to fix this?

Must be:
![shot_190226_030232](https://user-images.githubusercontent.com/8344157/53374840-063a0a00-3973-11e9-961d-e07de707d8dd.png)

**Comment by jeffwadsworth** [comment]
The lifelink wurm token is fine for me, but I can't find a good token for the deathtouch version via the download manager.  It may have to be grabbed manually.

**Comment by JayDi85** [comment]
Fixed via f2f1abd0f394c81b5874c9bd55675617a34216e9
