### ISSUE TITLE
Icatian Store bug

### ISSUE THREAD

**Issue by jeffwadsworth** [magefree/mage#5606]
Trying to play this card freezes the game.  It may be related to SkipUntapOptionalAbility but I am still testing other cards.  For example, when you use the ability of Ashnod's Battle Gear, the game will freeze before you can finish paying for the activated ability.

**Comment by JayDi85** [comment]
It's a restriction effect limitation -- some rare effects make user interaction on effect checks. As example: canBeUntapped asks user tap or untap permanent ever check call. That's cause overflow/infinite error on card hints.

Will try to fix it by workaround. But that restriction design is weird and must be rewritten, e.g. make user interaction only once and saves results for other check calls (or don't use user interaction at all on check effect).

**Comment by JayDi85** [comment]
As example, `UnwindingClock.java` have workaround to call untap checks only once until turn end.

![shot_190227_223530](https://user-images.githubusercontent.com/8344157/53513977-102d4b80-3ae0-11e9-849d-1a138ef5440b.png)

**Comment by JayDi85** [comment]
Fixed via 6846db75f42e919c53258ca6d89fcf91e7b3bb39
