### ISSUE TITLE
Doesn't receive email for registration

### ISSUE THREAD

**Issue by Grappy123** [magefree/mage#5608]
Hi,
Just to tell you, I tried to create two accounts for XMage.DE and never got any email to activate those accounts. I can't even connect in.

Thanks!

**Comment by JayDi85** [comment]
Gmail sends confirm emails too long (hours). Try use another email service or wait from gmail (if you don't get email before server restart [6:00 CET TIME](https://time.is/CET) then you must register again.

You can also try US or [BETA server](http://xmage.today/) without registration (fill only username field before connects).
