### ISSUE TITLE
UI: drag and drop image file from explorer to card viewer to save/replace image

### ISSUE THREAD

**Issue by JayDi85** [magefree/mage#5611]
Some people wants replace card images and upload missing one. Card viewer can helps with that -- users must be able to drag and drop new image from explorer to card viewer (card control) to replace it.

TODO:
 * [ ] drag and drop image file from explorer: save/replace image;
 * [ ] drag and drop image url from browser: download and save/replace image.

**Comment by hitch17** [comment]
I think you can reuse this for DnD if you'd like (maybe renamed): [see DnDDeckTargetListener](https://github.com/magefree/mage/pull/5612/commits/13efdd5b0bb586a3db0d77b03c6ea18fc02e8629#diff-a1a74ea813445e765d862a68c241e94eR15)

**Comment by JayDi85** [comment]
Yes, it's will be very useful.

**Comment by JayDi85** [comment]
Too complicated feature. Also it will hide the missing image problems instead of users reporting them.
