### ISSUE TITLE
Sword of the Meek does not trigger when Thopter Foundry token ETB

### ISSUE THREAD

**Issue by JayDi85** [magefree/mage#5613]
[From reddit](https://www.reddit.com/r/XMage/comments/ax34ob/sword_of_the_meek_does_not_trigger_when_thopter/):
After activating Thopter Foundry and sacrificing Sword of the Meek, the sword does not trigger and come back on the 1/1 Thopter that is created. Included picture with chat log and graveyard open. I tried this in 3 bot games with the same result.

XMage version installed: 1.4.33V4b (2019-03-04)
![t5yy83lq81k21](https://user-images.githubusercontent.com/8344157/53720103-57696280-3e79-11e9-80c9-465d2d328742.png)

**Comment by emerald000** [comment]
There's a Torpor Orb in play.
