### ISSUE TITLE
Thousand-Year storm bug

### ISSUE THREAD

**Issue by WangoMango** [magefree/mage#5620]
Thousand year storm does not make copies of spells as it should. Tested for 1, 2, 3, 4, 5 spells and no copies were made.

**Comment by jeffwadsworth** [comment]
Please post your game log.  Worked fine when tested a month ago.

**Comment by jeffwadsworth** [comment]
Tested it with multiple cards.  Worked fine in the latest build.

**Comment by WangoMango** [comment]
![1](https://user-images.githubusercontent.com/48334115/54056273-90793e00-41bd-11e9-8a5d-194564fd5fac.JPG)
![2](https://user-images.githubusercontent.com/48334115/54056279-93742e80-41bd-11e9-85f3-72bdb81aee09.JPG)
![3](https://user-images.githubusercontent.com/48334115/54056281-953df200-41bd-11e9-9221-c8d5e057336d.JPG)
![4](https://user-images.githubusercontent.com/48334115/54056284-97a04c00-41bd-11e9-8cae-508fa959052c.JPG)
![5](https://user-images.githubusercontent.com/48334115/54056285-97a04c00-41bd-11e9-8e38-ed52315d308e.JPG)
![6](https://user-images.githubusercontent.com/48334115/54056286-97a04c00-41bd-11e9-8ce8-0159b18c6c8a.JPG)
![7](https://user-images.githubusercontent.com/48334115/54056287-97a04c00-41bd-11e9-9fa7-8aecc5ba7ec7.JPG)
![8](https://user-images.githubusercontent.com/48334115/54056288-97a04c00-41bd-11e9-8781-96a52aaf6587.JPG)
![9](https://user-images.githubusercontent.com/48334115/54056289-9838e280-41bd-11e9-95e3-dcbcb90ef3a7.JPG)

The screenshots are shown in sequence in a game against ai so I could easily get the storm out but the same thing happened xmage.de

**Comment by WangoMango** [comment]
Hey what do you know I tried it later on xmage.de later and the problem must have either been on my end or been fixed, I still want to make sure it consistently works though

**Comment by WangoMango** [comment]
![13](https://user-images.githubusercontent.com/48334115/54057277-7a20b180-41c0-11e9-9686-8d7922ace547.JPG)
![14](https://user-images.githubusercontent.com/48334115/54057278-7ab94800-41c0-11e9-9db6-e2175221f343.JPG)
![15](https://user-images.githubusercontent.com/48334115/54057279-7ab94800-41c0-11e9-917d-a2df6accb747.JPG)
![16](https://user-images.githubusercontent.com/48334115/54057280-7ab94800-41c0-11e9-95fa-5b0fec836c33.JPG)
![17](https://user-images.githubusercontent.com/48334115/54057281-7ab94800-41c0-11e9-94b3-495b878ee2f3.JPG)

As I feared the bug struck again in game 2 and thousand-year storm failed to make any copies

**Comment by WangoMango** [comment]
As you can see in the log I only draw 2 cards one time as no copies are made. If this is not clear enough I can try to get some more screenshots

**Comment by WangoMango** [comment]
All I know is this problem has plagued me recently for about two weeks and the bug has happened every time I have played except for two times (one of them being the last post).

**Comment by WangoMango** [comment]
Tried again and it worked, no clue anymore

**Comment by jeffwadsworth** [comment]
I never play on the public servers and this may be a problem on those setups.  This was tested locally.  It may be a bigger problem.

**Comment by JayDi85** [comment]
@WangoMango you can try to fix wrong priority (game freeze) by enter `/FIX` command in game's chat. Try it next time and report here -- is that helps or not to you.

**Comment by JayDi85** [comment]
The problem was in stack -- if storm was in stack then all other casts ignores (not counts for future copies).

**Comment by JayDi85** [comment]
Fixed via 23271d9b9b61815495e7f4b27e7d5c865b3602f7
