### ISSUE TITLE
Silent-Blade Oni highlights cards in attacker's hand

### ISSUE THREAD

**Issue by Ebola16** [magefree/mage#5627]
Although the cards in the attacker's hand are not selectable, they are highlighted.
![Capture](https://user-images.githubusercontent.com/17330088/54135391-17adf800-43f0-11e9-8c1d-1c5b1a475a4d.PNG)

**Comment by JayDi85** [comment]
I can't reproduce your use case. Current beta server/client works fine -- ori highlights cards from select dialog, not from any hand (your or opponent).

Opponent hand:
![shot_190311_195132](https://user-images.githubusercontent.com/8344157/54137593-5c10b680-4437-11e9-8097-2c93a27f3b0c.png)

Own hand:
![shot_190311_195616](https://user-images.githubusercontent.com/8344157/54137801-be69b700-4437-11e9-898d-83509b4bc7cf.png)

**Comment by Zzooouhh** [comment]
Was the Silent-Blade Oni stolen by some control magic effect before this happened, by any chance?

**Comment by Ebola16** [comment]
No, Silent-Blade Oni was never stolen. I can reproduce this in 1.4.33V4b.

**Comment by Ebola16** [comment]
Fixed in 1.4.34V0
