### ISSUE TITLE
Jack-in-the-Mox bug

### ISSUE THREAD

**Issue by jeffwadsworth** [magefree/mage#5628]
This appears to be related to the rolldice method.
https://www.slightlymagic.net/forum/viewtopic.php?f=70&t=23164&start=105#p230517

**Comment by jeffwadsworth** [comment]
This is a weird one.  I thought it was possibly related to the AI simulation, but that does not appear to be the case.

**Comment by JayDi85** [comment]
Reason: `produceMana` calls multiple time to calculate possible mana in AI plays, in auto-pay, etc. In old version it must use `boolean netMana`, in current version it must override `getNetMana` to process mana calculations without apply/effect.
