### ISSUE TITLE
AI targeting illegal targets which also incorrectly leads to fizzles

### ISSUE THREAD

**Issue by iRoxor** [magefree/mage#5630]
[From reddit by ChaoMing:](https://old.reddit.com/r/XMage/comments/aud90m/bug_ai_targeting_something_with_hexproofshroud/)

> Say you are protected with a Leyline of Sanctity providing you with Hexproof. The AI is still able to target you with, say, the +1 ability of a [[Liliana Vess]]. The only legal target here should be the owner of the Liliana as they do not have Hexproof/Shroud protection, however, the AI is still capable of targeting you and [the gamelogs say that the ability has fizzled](https://i.imgur.com/1qO0zbp.png), but this is not a case that can logically play out in a real game of Magic as it should have been impossible for you to be targeted in the first place.
> 
> [The only case where fizzling can occur is when the target of a spell or ability is no longer a legal target while said spell/ability is on the stack and before it resolves.](https://mtg.gamepedia.com/Fizzle)  Let's say your opponent uses the +1 ability of the Liliana to target you to discard, but then you (somehow) Flash in a Leyline of Sanctity. The Leyline resolves first and is now a permanent on the battlefield, and then the Liliana ability on the stack resolves, which should then fizzle because you are no longer a legal target.
> 
> I don't know if something like this can happen in a Human vs. Human match on XMage so it would be greatly appreciated if someone who has come across this situation could share in this post.

**Comment by jeffwadsworth** [comment]
I noticed that same while testing Crown of Doom.

**Comment by jeffwadsworth** [comment]
[[Leyline of Sanctity]] [[Liliana Vess]]
