### ISSUE TITLE
Cavern of Souls not adding Green mana for Elves

### ISSUE THREAD

**Issue by redkaio** [magefree/mage#5635]
Not sure if it is problem related exclusively to Elves but it did not allow me to generate green mana for them. Tried to automatically turn the land after selecting the creature and afterwards generating it before selecting the creature but with no success. Tried to do it with different elves creatures. Not sure if it worth mentioning but the selected creature type displayed on Cavern of Souls was "Elves". 
Xmage Launcher version 0.3.8
Xmage Version: 1.4.33V4b

**Comment by jeffwadsworth** [comment]
I tested this with multiple elves (example Sunblade Elf) and it worked fine.  Perhaps if you had a log or more information.

**Comment by redkaio** [comment]
First of all, thanks for the quick reply! 
I figured out that the problem was in the "Elves" itself. I tried choosing "Elf" as you did and everything worked like a charm. My picture shows that you can choose either "Elf" or "Elves". I'm not sure why we have "Elves" but from now on I will pick the right type. 
Thanks again!
<img width="960" alt="elves_1" src="https://user-images.githubusercontent.com/38678725/54499209-e94b8380-48ed-11e9-8ff2-b6b2bb315840.png">

**Comment by emerald000** [comment]
"Elves" is the creature type of Elvish Impersonator (https://scryfall.com/card/ugl/56/elvish-impersonators).
