### ISSUE TITLE
Where is Kithkin Armor

### ISSUE THREAD

**Issue by sinsedrix** [magefree/mage#5642]
I can't find Kithkin Armor in the deck editor even if it's implemented.
https://scryfall.com/card/wth/19/kithkin-armor
I can see it in package mage.cards.k.KithkinArmor.java
Is there a problem in the database?

**Comment by jeffwadsworth** [comment]
You probably have an old version.  Kithkin Armor is quite new.

**Comment by JayDi85** [comment]
It's will be available with next release. Also it's can be playable on [BETA server](http://xmage.today/) from beta client now.

**Comment by sinsedrix** [comment]
ok, i'll wait
