### ISSUE TITLE
Apply to join China server to Online status, THX

### ISSUE THREAD

**Issue by siyiye** [magefree/mage#5646]
Server Name：XMage China
Server Address：xmage.vip:17171

THX！

**Comment by JayDi85** [comment]
Server is down:
* `ping xmage.vip` is not work;
* `telnet xmage.vip 17171` can't connects;

**Comment by siyiye** [comment]
The domain is registered today, and the DNS is still being refreshed. It should be OK tomorrow.

**Comment by siyiye** [comment]
> Server is down:
> 
> * `ping xmage.vip` is not work;
> * `telnet xmage.vip 17171` can't connects;

sever is OK

please check and Apply it ,THX

**Comment by JayDi85** [comment]
Server works fine. Added it to servers list.

**Comment by siyiye** [comment]
> Server works fine. Added it to servers list.

Unable to view on “xmageservers.online” ...........

**Comment by JayDi85** [comment]
I'm added it to official client (`others...` button in connection dialog). http://xmageservers.online/ is third party service, I don't have access to it -- but I'm informed admin about new server. It's will be added later.

**Comment by Zerrisx** [comment]
Appears to be resolved/fixed; China server is now visible in all described locations.
