### ISSUE TITLE
Arcane Denial - game freeze

### ISSUE THREAD

**Issue by JayDi85** [magefree/mage#5650]
From [facebook](https://www.facebook.com/groups/XmagePlayers/permalink/2309361292722043/):

Has anyone else had problems with Arcane Denial? Im testing a deck for a friend before he invests in it, and Ive had upkeep triggers hang with it. If I had either Black Vise(for opponents upkeep) or Ancestral Vision(my upkeep) triggers on the stack with an Arcane Denial cast on the previous turn, only the Vise or Visions triggers would appear on the stack and then the game would hang...

**Comment by jeffwadsworth** [comment]
This is related to this issue: #5437

**Comment by JayDi85** [comment]
Duplicate of #5437
