### ISSUE TITLE
Set default AI skill level to 10

### ISSUE THREAD

**Issue by Ebola16** [magefree/mage#5657]
Is there a reason we don't set the default AI skill level to 10? I think most people would want the AI to make the best possible plays by default.

**Comment by JayDi85** [comment]
It's performance issue. More skill level -- more time needs to calc all possible actions. As example: skill level 7  = AI will search best combination of 7 actions to do.

**Comment by Ebola16** [comment]
I haven't tested levels below 10 too thoroughly but level 10 seems to be acceptably fast for my purposes. Feel free to close this if you think the performance gains of a lower level justify it as being the default.

**Comment by jeffwadsworth** [comment]
There really shouldn't be any levels for the AI.  It doesn't consider anything more than plays it can make on a particular phase.  It isn't Magarena AI by any measure.

**Comment by JayDi85** [comment]
Limits are actual for late game only with big amount of cards on battlefield. XMage's AI gets 3 seconds for each skill (e.g. 7 skill level * 3 = 21 seconds per step/priority).

Sometime there are crazy moments like that (possible mana combination):
![shot_190212_223148](https://user-images.githubusercontent.com/8344157/55000750-9d36c800-4fec-11e9-8e94-b7ebce2e4cfa.png)

**Comment by JayDi85** [comment]
>  It isn't Magarena AI by any measure.

It's uses same min/max method -- get all possible actions, simulate it and calc final results.

P.S. AI cpu usage on beta server:

![shot_190326_173745](https://user-images.githubusercontent.com/8344157/55001481-1a167180-4fee-11e9-90fe-2ac50fe71ef3.png)

**Comment by Zerrisx** [comment]
Seems like this was decided to be an unnecessary adjustment.
