### ISSUE TITLE
Graveyard view scroll bar covers bottom of cards

### ISSUE THREAD

**Issue by Ebola16** [magefree/mage#5659]
If a scroll bar is needed in windows such as the graveyard view, the bottom of cards will be covered.
![Capture](https://user-images.githubusercontent.com/17330088/54993151-929e1380-4f97-11e9-9737-0428414dccd8.PNG)

Extend the default window height to show the entire card with the scroll bar.
![Capture2](https://user-images.githubusercontent.com/17330088/54993186-a8abd400-4f97-11e9-81a9-9899e2e9c603.PNG)

**Comment by JayDi85** [comment]
@Ebola16 can you show your GUI size settings?

Open search, enter `regedit` and find that path `HKEY_CURRENT_USER\Software\JavaSoft\Prefs\mage\client`.

It's have `gui/*` params.

Example:
![shot_190328_170237](https://user-images.githubusercontent.com/8344157/55159807-4e6b6880-517b-11e9-8c49-9f33ff890b76.png)

**Comment by Ebola16** [comment]
I don't have any registry values that match `gui/*`

![Capture](https://user-images.githubusercontent.com/17330088/55160405-a4b7b780-5139-11e9-85c7-868ebf6d42f3.PNG)

**Comment by JayDi85** [comment]
Fixed via 16efc350b40c5db8fd772229a483c6b023c515e9
