### ISSUE TITLE
Client cannot connect to localhost server - 1.4.34V0 (2019-03-29)

### ISSUE THREAD

**Issue by dracoix** [magefree/mage#5663]
Steps to reproduce:

Default settings for server config

Launch launcher
"Launch Client and Server"
(Wait several seconds for both server and client to be online)
Client "Connect to server" set to localhost 17171
"Connect to server"
First Error: "Unable to connect to server. Probably the server version is not compatible with the client"
Second Error: "The connection to the server was lost. Reconnect?" -Yes
Third Error: Ping Failed

SERVER LOG (important bits):

INFO  2019-03-29 10:04:56,300 Starting MAGE server version 1.4.34V0 (build: 2019-03-29 15:34)                            =>[main] Main.main
INFO  2019-03-29 10:04:56,302 Logging level: DEBUG                                                                       =>[main] Main.main
INFO  2019-03-29 10:04:56,501 Loading database...                                                                        =>[main] RepositoryUtil.bootstrapLocalDb
INFO  2019-03-29 10:05:01,708 Done.                                                                                      =>[main] Main.main
INFO  2019-03-29 10:05:01,708 Loading extension packages...                                                              =>[main] Main.main
INFO  2019-03-29 10:05:01,709 Done.                                                                                      =>[main] Main.main
INFO  2019-03-29 10:05:01,709 Loading cards...                                                                           =>[main] Main.main
INFO  2019-03-29 10:05:08,527 DB: need to add 33 new cards                                                               =>[main] CardRepository.lambda$saveCards$0
INFO  2019-03-29 10:05:08,558 Done.                                                                                      =>[main] Main.main
INFO  2019-03-29 10:05:08,558 Updating user stats DB...                                                                  =>[main] Main.main
INFO  2019-03-29 10:05:08,677 Done.                                                                                      =>[main] Main.main

...snip...

INFO  2019-03-29 10:05:08,898 Config - max seconds idle: 600                                                             =>[main] Main.main
INFO  2019-03-29 10:05:08,898 Config - max game threads: 10                                                              =>[main] Main.main
INFO  2019-03-29 10:05:08,899 Config - max AI opponents: 15                                                              =>[main] Main.main
INFO  2019-03-29 10:05:08,899 Config - min usr name le.: 3                                                               =>[main] Main.main
INFO  2019-03-29 10:05:08,899 Config - max usr name le.: 14                                                              =>[main] Main.main
INFO  2019-03-29 10:05:08,899 Config - min pswrd length: 8                                                               =>[main] Main.main
INFO  2019-03-29 10:05:08,899 Config - max pswrd length: 100                                                             =>[main] Main.main
INFO  2019-03-29 10:05:08,899 Config - inv.usr name pat: [^a-z0-9_]                                                      =>[main] Main.main
INFO  2019-03-29 10:05:08,899 Config - save game active: false                                                           =>[main] Main.main
INFO  2019-03-29 10:05:08,899 Config - backlog size    : 200                                                             =>[main] Main.main
INFO  2019-03-29 10:05:08,899 Config - lease period    : 5000                                                            =>[main] Main.main
INFO  2019-03-29 10:05:08,899 Config - sock wrt timeout: 10000                                                           =>[main] Main.main
INFO  2019-03-29 10:05:08,899 Config - max pool size   : 300                                                             =>[main] Main.main
INFO  2019-03-29 10:05:08,899 Config - num accp.threads: 2                                                               =>[main] Main.main
INFO  2019-03-29 10:05:08,900 Config - second.bind port: -1                                                              =>[main] Main.main
INFO  2019-03-29 10:05:08,900 Config - auth. activated : false                                                           =>[main] Main.main
INFO  2019-03-29 10:05:08,900 Config - mailgun api key :                                                                 =>[main] Main.main
INFO  2019-03-29 10:05:08,900 Config - mailgun domain  :                                                                 =>[main] Main.main
INFO  2019-03-29 10:05:08,900 Config - mail smtp Host  :                                                                 =>[main] Main.main
INFO  2019-03-29 10:05:08,900 Config - mail smtpPort   :                                                                 =>[main] Main.main
INFO  2019-03-29 10:05:08,900 Config - mail user       :                                                                 =>[main] Main.main
INFO  2019-03-29 10:05:08,900 Config - mail passw. len.: 0                                                               =>[main] Main.main
INFO  2019-03-29 10:05:08,900 Config - mail from addre.:                                                                 =>[main] Main.main
INFO  2019-03-29 10:05:08,900 Config - google account  :                                                                 =>[main] Main.main
INFO  2019-03-29 10:05:12,036 Started MAGE server - listening on 0.0.0.0:17171/?serializationtype=jboss&maxPoolSize=300  =>[main] Main.main
DEBUG 2019-03-29 10:05:17,004 Reading server messages...                                                                 =>[pool-7-thread-1] ServerMessagesUtil.reloadMessages
DEBUG 2019-03-29 10:06:01,217 DISCONNECT  Disconnected - sessionId: 5c4o1k1-xpdgi0-jtudnic9-1-jtudnidw-4                 =>[WorkerThread#0[25.12.248.240:52205]] SessionManager.lambda$disconnect$1
DEBUG 2019-03-29 10:07:01,189 Start Check Expired                                                                        =>[pool-8-thread-1] UserManager.checkExpired
DEBUG 2019-03-29 10:07:01,190 Users to remove 0                                                                          =>[pool-8-thread-1] UserManager.checkExpired
DEBUG 2019-03-29 10:07:01,194 End Check Expired                                                                          =>[pool-8-thread-1] UserManager.checkExpired
DEBUG 2019-03-29 10:07:01,199 DISCONNECT  Disconnected - sessionId: 5c4o1k1-xpdgi0-jtudnic9-1-jtudodih-e                 =>[WorkerThread#1[25.12.248.240:52215]] SessionManager.lambda$disconnect$1
DEBUG 2019-03-29 10:08:01,187 Start Check Expired                                                                        =>[pool-8-thread-1] UserManager.checkExpired
DEBUG 2019-03-29 10:08:01,187 Users to remove 0                                                                          =>[pool-8-thread-1] UserManager.checkExpired
DEBUG 2019-03-29 10:08:01,187 End Check Expired                                                                          =>[pool-8-thread-1] UserManager.checkExpired

CLIENT LOG (important bits):

INFO  2019-03-29 10:04:56,400 Starting MAGE client version 1.4.33V4 (build: 2019-03-04 03:12)                            =>[main] MageFrame.main 
INFO  2019-03-29 10:04:56,402 Logging level: INFO                                                                        =>[main] MageFrame.main 
INFO  2019-03-29 10:04:57,630 Loading database...                                                                        =>[AWT-EventQueue-0] RepositoryUtil.bootstrapLocalDb 
INFO  2019-03-29 10:04:58,898 Loading symbols...                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadImages 
INFO  2019-03-29 10:05:00,422 Loading plugins...                                                                         =>[AWT-EventQueue-0] Plugins.loadPlugins 
INFO  2019-03-29 10:05:00,459 [Game counter plugin, version 0.1] has been loaded.                                        =>[AWT-EventQueue-0] CounterPluginImpl.newPlugin 
INFO  2019-03-29 10:05:00,467 [Card plugin, version 0.7] has been loaded.                                                =>[AWT-EventQueue-0] CardPluginImpl.newPlugin 
INFO  2019-03-29 10:05:00,469 [Theme plugin, version 0.5] has been loaded.                                               =>[AWT-EventQueue-0] ThemePluginImpl.newPlugin 
INFO  2019-03-29 10:05:00,470 Done.                                                                                      =>[AWT-EventQueue-0] Plugins.loadPlugins 
INFO  2019-03-29 10:05:01,564 Client start up time: 5 seconds                                                            =>[AWT-EventQueue-0] MageFrame.lambda$new$2 
INFO  2019-03-29 10:05:22,601 Trying to connect to XMAGE server at localhost:17171                                       =>[SwingWorker-pool-4-thread-2] SessionImpl$5.run 
INFO  2019-03-29 10:05:22,930 Connected to MAGE server at localhost:17171                                                =>[SwingWorker-pool-4-thread-2] SessionImpl$5.run 
INFO  2019-03-29 10:05:22,931 Trying to log-in as dracoix to XMAGE server at localhost:17171                             =>[SwingWorker-pool-4-thread-2] SessionImpl$4.run 
ERROR 2019-03-29 10:06:01,188 Ping failed: dracoix Session: 5c4o1k1-xpdgi0-jtudnic9-1-jtudnidw-4 to MAGE server at localhost:17171 =>[pool-1-thread-1] SessionImpl.ping 
FATAL 2019-03-29 10:06:01,190 Server error                                                                               =>[pool-1-thread-1] SessionImpl.handleMageException 
mage.MageException: Ping failed
	at mage.remote.SessionImpl.ping(SessionImpl.java:1593)
	at mage.client.SessionHandler.ping(SessionHandler.java:35)
	at mage.client.MageFrame.lambda$new$1(MageFrame.java:252)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
INFO  2019-03-29 10:06:01,207 DISCONNECT (still connected)                                                               =>[pool-1-thread-1] SessionImpl.disconnect 
INFO  2019-03-29 10:06:01,240 Disconnected ...                                                                           =>[pool-1-thread-1] SessionImpl.disconnect 
INFO  2019-03-29 10:06:01,287 DISCONNECTED (NO Event Dispatch Thread)                                                    =>[pool-1-thread-1] MageFrame.disconnected 
INFO  2019-03-29 10:06:03,030 Trying to connect to XMAGE server at localhost:17171                                       =>[AWT-EventQueue-0] SessionImpl$5.run 
INFO  2019-03-29 10:06:03,125 Connected to MAGE server at localhost:17171                                                =>[AWT-EventQueue-0] SessionImpl$5.run 
INFO  2019-03-29 10:06:03,125 Trying to log-in as dracoix to XMAGE server at localhost:17171                             =>[AWT-EventQueue-0] SessionImpl$4.run

**Comment by JayDi85** [comment]
Your client is not updated. Maybe you are running xmage while got update:
 * Close all xmage apps;
 * Close all `java.exe` apps by task manager;
 * Run launcher and press update button to download all files again.

That's must help.

**Comment by dracoix** [comment]
Ya I know, it kept saying 1.4.33V4 even though all the client files had 3/29 and even the client jar was modified on 3/29. It was bizare.

Closed all java.exe in taskmanager (as before)
Opening xmage launcher...

Reading config from http://xmage.de/xmage/config.json
XMage folder:  G:\LIVESTOR\PERMA\Downloads\xmage
XMage Launcher version installed:  0.3.8
XMage Launcher version available:  0.3.8
Java version installed:  1.8.0_201
Java version available:  1.8.0_201
XMage version installed:  1.4.34V0 (2019-03-29)
XMage version available:  1.4.34V0 (2019-03-29)
Reading config from http://xmage.de/xmage/config.json
XMage version installed:  1.4.34V0 (2019-03-29)
XMage version available:  1.4.34V0 (2019-03-29)
Removing previous versions ...
Downloading Java from http://download.oracle.com/otn-pub/java/jdk/8u201-b09/42970487e3af4f5aa5bca3f542482c60/jre-8u201-windows-x64.tar.gz
Installing Java ...Done
Downloading XMage from https://github.com/magefree/mage/releases/download/xmage_1.4.34V0/xmage_1.4.34V0.zip
Removing previous versions ...
Installing XMage ...Done
Java version installed:  1.8.0_201
Java version available:  1.8.0_201
XMage version installed:  1.4.34V0 (2019-03-29)
XMage version available:  1.4.34V0 (2019-03-29)

Force update complete.

CLIENT LOG:

INFO  2019-03-29 10:48:30,059 Starting MAGE client version 1.4.34V0 (build: 2019-03-29 15:32)                            =>[main] MageFrame.main 
INFO  2019-03-29 10:48:30,061 Logging level: INFO                                                                        =>[main] MageFrame.main 
INFO  2019-03-29 10:48:31,322 Loading database...                                                                        =>[AWT-EventQueue-0] RepositoryUtil.bootstrapLocalDb 
INFO  2019-03-29 10:48:31,639 DB: creating cards database                                                                =>[AWT-EventQueue-0] MageFrame.<init> 
INFO  2019-03-29 10:48:37,371 DB: need to add 221 new sets                                                               =>[AWT-EventQueue-0] ExpansionRepository.lambda$saveSets$0 
INFO  2019-03-29 10:48:46,549 DB: need to add 36654 new cards                                                            =>[AWT-EventQueue-0] CardRepository.lambda$saveCards$0 
INFO  2019-03-29 10:48:51,978 Done.                                                                                      =>[AWT-EventQueue-0] MageFrame.<init> 
INFO  2019-03-29 10:48:51,985 Loading symbols...                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadImages 
INFO  2019-03-29 10:48:53,646 Loading plugins...                                                                         =>[AWT-EventQueue-0] Plugins.loadPlugins 
INFO  2019-03-29 10:48:53,694 [Game counter plugin, version 0.1] has been loaded.                                        =>[AWT-EventQueue-0] CounterPluginImpl.newPlugin 
INFO  2019-03-29 10:48:53,703 [Card plugin, version 0.7] has been loaded.                                                =>[AWT-EventQueue-0] CardPluginImpl.newPlugin 
INFO  2019-03-29 10:48:53,706 [Theme plugin, version 0.5] has been loaded.                                               =>[AWT-EventQueue-0] ThemePluginImpl.newPlugin 
INFO  2019-03-29 10:48:53,706 Done.                                                                                      =>[AWT-EventQueue-0] Plugins.loadPlugins 
ERROR 2019-03-29 10:48:54,973 Wrong news page cookies                                                                    =>[JavaFX Application Thread] WhatsNewDialog$PersistentCookieStore.loadFromPrefs 
java.lang.NullPointerException
	at mage.client.dialog.WhatsNewDialog$PersistentCookieStore.loadFromPrefs(WhatsNewDialog.java:203)
	at mage.client.dialog.WhatsNewDialog$PersistentCookieStore.<init>(WhatsNewDialog.java:188)
	at mage.client.dialog.WhatsNewDialog$3.run(WhatsNewDialog.java:268)
	at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
	at java.lang.Thread.run(Thread.java:748)
INFO  2019-03-29 10:48:55,041 Client start up time: 24 seconds                                                           =>[AWT-EventQueue-0] MageFrame.lambda$new$2 

But it opens...
Connecting...

Connected.

That was a trip. Thanks jay :D
