### ISSUE TITLE
Ajani's Pridemate NPE when targeted with Estrid's Mask

### ISSUE THREAD

**Issue by Zzooouhh** [magefree/mage#5668]
Not sure if it applies to other Auras yet.

**Comment by jeffwadsworth** [comment]
We are going to need your game log.  Worked fine with the latest version.

**Comment by JayDi85** [comment]
It's not Ajani's Pridemate error, there are another cards to raise that error. 

Reason: Estrid's Mask put token enchantment aura without SpellAbility() -- there are many cards without `getSpellAbility() != null` checks. See example: #5285 (todo with regexp search and fix in #5471).
