### ISSUE TITLE
Collective Brutality discarding Emrakul, can't respond to trigger

### ISSUE THREAD

**Issue by Tmsio82** [magefree/mage#5670]
If i cast Collective Brutality discarding Emrakul, The Aeons Torn, i can't respond to Emrakul's Trigger to reanimate him from Graveyard.
No probs with Faithless Looting or Lightning Axe

**Comment by jeffwadsworth** [comment]
What are you "reanimating" the Emrakul with?  I was able to use Corpse Dance just fine in response to the trigger.

**Comment by Tmsio82** [comment]
I'm using Goryo's Vengeance, but i cannot respond to the trigger cause it resolves

**Comment by jeffwadsworth** [comment]
Worked fine for me.
![proof](https://user-images.githubusercontent.com/1496996/55819864-6322f700-5abf-11e9-95e1-ac9084291f7f.jpg)

**Comment by ketsuban** [comment]
There's a setting which automatically passes priority when putting a spell or ability onto the stack; does that make a difference here?

**Comment by jeffwadsworth** [comment]
It very well may.

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.
