### ISSUE TITLE
UI Suggestion: Rich Man Draft Improvements

### ISSUE THREAD

**Issue by duelcastermage** [magefree/mage#5672]
I have some ideas for various improvements to Rich Man drafts. Some of these apply to "Chaos" (Random) drafts as well:

1) XMage doesn't remember which booster packs are selected to be drafted once you quit the program. You have to manually re-adjust every time you want to start a new tournament, which is quite annoying now that there about 50+ MTG sets released as of 2019. Please keep these selections in memory (**most important**)

2) The packs aren't randomized if there are fewer than 36 sets selected. They just go down in order from most recent to oldest, with no option to randomize. I feel like the default behavior should be to randomize the sets even if there are fewer than 36 selected, or at least have that option.

3) Please have an option (probably even defaulted) for to have the same amount of draft pick time for each pack. There are always a full 15 cards to look at, yet the timer gets shorter and shorter as the draft progresses.

**Comment by JayDi85** [comment]
1. Added;
2. Fixed;
3. @duelcastermage look at new time limits in that commit: 98f29f7c8afef2366d2518ee48e3eac172373c5f (75->25 to 70->40) -- is that ok?

**Comment by duelcastermage** [comment]
Awesome, thank you so much! Yes, 70 -> 40 seems good (or even 60 -> 40) because toward the end of the draft you should have your colors solidified, which makes selecting a card easier.
