### ISSUE TITLE
Choose name window bug

### ISSUE THREAD

**Issue by jeffwadsworth** [magefree/mage#5674]
![example](https://user-images.githubusercontent.com/1496996/55493111-fced2e80-55fd-11e9-9fb1-5ee64f1462d8.jpg)
From Discord:
Cabal Therapy - This didn't just happen to me now, but I've found on several occasions that backspacing while you're naming a card with Cabal Therapy basically crashes your client. If you rejoin, Therapy has resolved on...nothing. Same goes for Pithing Needle, actually (discord, Ganymede, 2019-03-04);

**Comment by JayDi85** [comment]
It's compatibility issue with java, macos and third party apps (app freezes on text edit fields). Another example: #5674
