### ISSUE TITLE
Island Sanctuary effect not lingering after being removed

### ISSUE THREAD

**Issue by Rewyn** [magefree/mage#5676]
3 player EDH game.
Opponent A had Island Sanctuary on the field, didn't draw a card during draw step to use it's effect.
Opponent B played Return to Dust on Island Sanctuary (and another enchantment), then proceeded to attack with his Sidisi, Undead Vizier (no flying/islandwalk, not from external effects either).

According to the ruling on gatherer, the effect should linger until the next turn, even if the enchantment gets removed.
http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=4136

**Comment by jeffwadsworth** [comment]
![Untitled](https://user-images.githubusercontent.com/1496996/55573023-8835f500-56ce-11e9-91d6-eb5b6b0918b0.jpg)

**Comment by jeffwadsworth** [comment]
This is truly a strange effect.  Fortunately, it just affects this card.  Still looking at it, though.
