### ISSUE TITLE
Support Oathbreaker format

### ISSUE THREAD

**Issue by ketsuban** [magefree/mage#5678]
[Oathbreaker](https://weirdcards.org/oathbreaker) is starting to gain traction and I'd like to see it in Xmage since it fixes some problems I have with Commander as a format and adds an interesting new dimension in the form of the signature spell.

Oathbreaker is a singleton format. All cards must be Vintage-legal (i.e. Conspiracies, silver-bordered cards, dexterity cards and ante cards are all banned) and not on the [shortish banlist](https://weirdcards.org/oathbreaker-ban-list) maintained by the Oathbreaker Rules Committee. It's otherwise a variant of Commander, but...
* Your deck is 60 cards instead of 100, and your life total starts at 20 instead of 40.
* Commander damage isn't a thing.
* Instead of a legendary creature, your commander is a planeswalker card. For each commander, you must also put a "signature spell" (an instant or sorcery card matching that commander's colour identity) into the command zone.
* Signature spells obey rule 903.8. ("commander tax") and can only be cast from the command zone if you control the commander corresponding to that signature spell. If a signature spell would leave the stack, it returns to the command zone instead of going anywhere else.

The Oathbreaker website hosts the [full rules](https://weirdcards.org/oathbreaker-rules) and a set of [frequently asked questions](https://weirdcards.org/oathbreaker-faq) which addresses some corner cases.

**Comment by freestylerof911** [comment]
I would love to see Oathbreaker on xMage. Playing it with my Playgroup already.

Unsolved Format, like commander but with aggro/burn and mill being viable options and until now we didn´t manage to break the game as much as you can break commander due to natural color restrictions.

**Comment by JayDi85** [comment]
TODO:
 - [ ] Add support of `Commander Storm Ability` (it's must use commanders count, not signature spells);

**Comment by JayDi85** [comment]
Added. Will be available with next release.
