### ISSUE TITLE
Aminatou's Augury still broken

### ISSUE THREAD

**Issue by timcarroll761** [magefree/mage#5683]
The last patch partially repaired Aminatou's Augury, but not all the way. It still does not always allow you to cast cards that should be castable.
Steps to reproduce:
1. Cast Augury, let it resolve
2. put a land on the field (likely doesnt matter, but that what I did)
3. In the window of cards exiled by it, select a spell to cast
4. In the window to confirm casting the spell, hit cancel
5. Attempt to cast the same spell again
The spell can no longer be selected once it has been cancelled on the casting confirmation popup.

**Comment by jeffwadsworth** [comment]
I would suggest making sure that you actually want to play the card before selecting it.

**Comment by LevelX2** [comment]
Fixed with 783239e79e57bfc8b9079f69c900bbad57e4018e.
