### ISSUE TITLE
silent gravestone BUG

### ISSUE THREAD

**Issue by EllNubNub** [magefree/mage#5686]
Silent gravestone prevents non targeted effects as well. when i cast The Mimeoplasm it specifically reads chose on the gatherer [http://gatherer.wizards.com/Pages/Card/Details.aspx?name=the%20mimeoplasm] so the gravestone should not prevent the mimeoplasm from exiling the creatures and becoming a copy of one of them.

**Comment by ketsuban** [comment]
It looks like Xmage has a few different cards which implement "choose a card in a graveyard" effects with `TargetCardInGraveyard` - in addition to The Mimeoplasm there's also [Dawnbreak Reclaimer](https://scryfall.com/card/cm2/24/dawnbreak-reclaimer), [Gruesome Menagerie](https://scryfall.com/card/grn/71/gruesome-menagerie) and [Tariel, Reckoner of Souls](https://scryfall.com/card/cma/194/tariel-reckoner-of-souls). My expectation is these also exhibit this bug. This might require a new event type.

**Comment by ketsuban** [comment]
Can't believe I managed to completely overlook `setNotTarget`. Doy.
