### ISSUE TITLE
UMA box topper cards cause Layout mismatch on load in deck editor

### ISSUE THREAD

**Issue by luziferius** [magefree/mage#5688]
When loading a deck (that has a manual layout?), I get the following error on load, if and only if the deck contains a [PUMA](https://scryfall.com/sets/puma) card. Replacing all PUMA cards with the same card from the [UMA](https://scryfall.com/sets/uma) set resolves it.
Message box:
```
Error while loading deck

Found problems with deck:
Layout mismatch: Expected 99 cards, but got 98 in layout `MAIN`

[Ok]
```
Nothing shows up in the client console log.

The `got` value is 99 minus the number of PUMA cards in the deck.

I tried and succeeded to reproduce it on my Linux system. I got the inital report from a friend running Win7. 

I tried it with these cards, and all of them trigger this:
- Karn Liberated
- Snapcaster Mage
- Balefire Dragon
- Maelstrom Pulse
- Vengevine

This is a simple test case. A deck containing one Engineered Explosives and a Mana Vault.
Not working, using box topper cards:
[PUMA-test-bugged.dck.txt](https://github.com/magefree/mage/files/3051705/PUMA-test-bugged.dck.txt)
Working, using the UMA printing:
[PUMA-test-working.dck.txt](https://github.com/magefree/mage/files/3051706/PUMA-test-working.dck.txt)

**Comment by JayDi85** [comment]
Fixed via cf072f0b1a5a9a354198b34420ce567a0dc14a1f
