### ISSUE TITLE
Nahiri, Storm of Stone tooltip mistake.

### ISSUE THREAD

**Issue by Stafy1** [magefree/mage#5689]
The new Nahiri from war has a small mistake within the tooltip. It should says "deals X damage to target tapped creature"
![Screenshot_144](https://user-images.githubusercontent.com/35297448/55687746-48466a80-5979-11e9-92ee-5ab1bc038b00.png)

**Comment by JayDi85** [comment]
Fixed via 04bb0fa75007862df5adf258b74f4e5144f4a0cf
