### ISSUE TITLE
Xmage client freezes when trying to download images

### ISSUE THREAD

**Issue by willdfonseca** [magefree/mage#5693]
Hi,

Xmage (1.4.34V0 + jre1.8.0_201) client freezes when trying to download images from any source.
It starts and goes up to a small number like 6 and stops. I have to use the task manager to close it (because it is freezed).

![image](https://user-images.githubusercontent.com/31637394/55692231-4336ea80-597c-11e9-912b-bf0ea3cb610d.png)

The console message is

> INFO  2019-04-07 21:48:16,612 Started download of 3539 images from source: scryfall.com, language: en                    =>[Thread-620] DownloadPicturesService.run 

Is that a commom problem? Is it a Windows related problem (I am using 10)?
Any help/hint is very welcome.

**Comment by JayDi85** [comment]
[Try that instructions](https://www.reddit.com/r/XMage/comments/agmcjf/new_xmage_release_with_ravnica_allegiance_rna/) (steps 1-8).

**Comment by willdfonseca** [comment]
@JayDi85 I tried the instructions... 

1. On the fisrt try but same behavior...

It created RNA.zip (0 KB), downloaded 3 cards (in downloading folder) and freezed.

![image](https://user-images.githubusercontent.com/31637394/55722730-6e055b00-59dd-11e9-91a2-871651c2ad71.png)

![image](https://user-images.githubusercontent.com/31637394/55722755-7a89b380-59dd-11e9-9fbb-30a816e0f14f.png)

2. On the second try it downloaded the cards, the interface is not freezed... but the "Downloading images" is not closing (RNA.zip is still 0 KB). The command window is attached.

[ConsoleError.txt](https://github.com/magefree/mage/files/3054179/ConsoleError.txt)

![image](https://user-images.githubusercontent.com/31637394/55723141-95105c80-59de-11e9-8882-56083c0cfb65.png)

3. Third try (and others)... all freezed (again).

**Comment by JayDi85** [comment]
Download https://www.teamviewer.com/ run it and send me connect ID and password (email: jaydi85@gmail.com ) -- I'll connects to your machine and checks all settings.

**Comment by goesta** [comment]
I'll close this issue because there where no feedback for a long time but feel free to create a new one if this is still a problem.
