### ISSUE TITLE
/fix is broken

### ISSUE THREAD

**Issue by spjspj** [magefree/mage#5709]
Kind of ironic, but the '/fix' command is still broken (I didn't figure out a way at the time I added it to make it work reliably).  It can make a person who has left the game lose the game, but if they still have priority (say when damnation is resolving and they're being asked 'do you want to move your commander to the command zone') then the game is unfinishable.

**Comment by JayDi85** [comment]
It's works fine in current versions for disconnected players. But doesn't work if player ignore game and play another one on server (e.g. he is online).
