### ISSUE TITLE
CopySpellForEachItCouldTargetEffect must be removed/rewritten

### ISSUE THREAD

**Issue by JayDi85** [magefree/mage#5727]
Cards with abilities like "copy the spell for each ... that spell could target" have special effect -- `CopySpellForEachItCouldTargetEffect`. It's replaces card's targets with special mock object (original target + additional filter to restrict target's select). Only 4 cards uses it (Ink Treader Nephilim, Mirrorwing Dragon, Precursor Golem and Radiate -- related issue: #2175):
![shot_190418_125214](https://user-images.githubusercontent.com/8344157/56350631-45027880-61dc-11e9-8902-992b4002f8c3.png)

XMage uses `target instanceof TargetClass` approach all around the code and it's can't catch real target type behind `TargetWithAdditionalFilter` (e.g. some cards will be broken after copy effect applies):
![shot_190418_131434](https://user-images.githubusercontent.com/8344157/56350496-f523b180-61db-11e9-9a76-88f36e3b0c0c.png)

There is special call to workaround that problem -- `target.getOriginalTarget()`. AI uses it. BUT card abilities and other code don't use.

There are two possible solution:
* Easy: remove/rewrite `CopySpellForEachItCouldTargetEffect` without mock object;
* Hard: replace all code `target instanceof TargetClass` by `target.getOriginalTarget instanceof TargetClass` (it's hard and can't be controlled in future).

**Comment by Tychology** [comment]
Curiously Zada, Hedron Grinder has a "copy the spell for each ... that spell could target", but doesn't use `CopySpellForEachItCouldTargetEffect` in its implementation. And the implementation of Zada is not consistent with the rulings-- related issue: #6096

**Comment by xenohedron** [comment]
This was completed in #7662
