### ISSUE TITLE
Bug: Challenger Troll allows double blocks on your 4+ power creatures

### ISSUE THREAD

**Issue by duelcastermage** [magefree/mage#5730]
New WAR card Challenger Troll still allows double blocks. Tested with a separate 4-power creature, not the Troll itself.

**Comment by jeffwadsworth** [comment]
This works fine.  After you declare blockers, it will check and tell you that only one can block it.  You simply choose one blocker.

**Comment by drmDev** [comment]
added Unit Tests which confirm the end result behavior is correct:
https://github.com/drmDev/mage/commit/e333aa2d45057ca10f3f9587ed62e71b2e35cab2
