### ISSUE TITLE
BUG - Ashiok, Dream Render

### ISSUE THREAD

**Issue by SteToe57** [magefree/mage#5733]
"Ashiok, Dream Render" -1 ability doesnt allow you to target a player and doesnt mill anyone.

**Comment by antoni-g** [comment]
Working on figuring out the solution. Ashiok, Dream Renderer seems correctly implemented, so I'll drive into the code and see what is happening. I suspect it is to do either with the coupling of the mill and exile ability, or a problem with the mill ability itself.

**Comment by antoni-g** [comment]
Fixed the issue, pushed changes to my open pull request.
