### ISSUE TITLE
amass miss check zombie army creature controller

### ISSUE THREAD

**Issue by CCTV-1** [magefree/mage#5734]
when a player control a zombie army creature,other player can't create a 0/0 black zombie army creature token,can only put a +1/+1 counter to already exist zombie army creature.

**Comment by CCTV-1** [comment]
`Mobilized District ` now can only add {C} ,can't becomes creature.

**Comment by JayDi85** [comment]
Fixed by 73f7855e4d234c661380495ef2b9b259ca019828 and 6f045ec81a1ce298255313c8d63a910e244f9f93
