### ISSUE TITLE
Long as my turn, prevent all damage that would be dealt to Gideon Blackblade don't work

### ISSUE THREAD

**Issue by CCTV-1** [magefree/mage#5738]
game log:
```
AM 10:37: Attacker: Gideon Blackblade [fa8] (4/4) blocked by Wardscale Crocodile [c7b] (5/3) 
AM 10:37: Gideon Blackblade [fa8] deals 4 damage to Wardscale Crocodile [c7b]
AM 10:37: Wardscale Crocodile [c7b] deals 5 damage to Gideon Blackblade [fa8]
AM 10:37: Wardscale Crocodile [c7b] died
```

**Comment by mooretc2** [comment]
This is also true for non-combat damage for what it's worth. Possibly something to do with static prevent damage effects not interacting with loyalty counters correctly?

**Comment by JayDi85** [comment]
[It's ok -- planeswalkers aren't affected by indestructible](https://mtg.gamepedia.com/Indestructible):

Planeswalkers with indestructible will still have loyalty counters removed from them as they are dealt damage. If a planeswalker with indestructible has no loyalty counters, it will still be put into its owner's graveyard, as the rule that does this doesn't destroy the planeswalker.

**Comment by JayDi85** [comment]
Fixed via f25f7a0f68005c08df27c5335b2338ea899632f0

**Comment by mooretc2** [comment]
This isn't quite right either. His ability is "As long as it's your turn, Gideon Blackblade is a 4/4 Human Soldier creature **with indestructible** that's still a planeswalker."

He should have both indestructible and damage prevention.

**Comment by JayDi85** [comment]
It's interesting bug -- conditional effects do not used for prevention checks (`ConditionalPreventionEffect` is not implemented in code). There are more than 15 cards with wrong effect types (e.g. their effects aren't works). I'll rework it.

**Comment by JayDi85** [comment]
Conditional effects improved. Now it works fine.
