### ISSUE TITLE
Nicol Bolas, Dragon-God

### ISSUE THREAD

**Issue by ddoggdall** [magefree/mage#5744]
When Bolas uses his +1 and the opponent chooses to sacrifice a permanent (land, creature, enchant, artifact). The card chosen is not exiling and stays on the Battlefield completely usable. His +1 is working correctly for the draw and exiling a card from the opponents hand. It is not properly exiling a sacrificed permanent however.

**Comment by jeffwadsworth** [comment]
Actually, the "exiled" permanent is not usable, but it does remain on the battlefield.  Checking it out.

**Comment by jeffwadsworth** [comment]
Fixed.  Just testing.

**Comment by ddoggdall** [comment]
Awesome thank you very much, will test it myself asap.
