### ISSUE TITLE
Bug: Game completely rolled back on attempted cast of Protective Sphere

### ISSUE THREAD

**Issue by duelcastermage** [magefree/mage#5746]
Here is the log:

> Game exception occurred: java.lang.NullPointerException
Server version: 1.4.34V0.1 (build: 2019-03-30 06:24)
mage.cards.p.ProtectiveSphereEffect.<init>(ProtectiveSphere.java:67)
mage.cards.p.ProtectiveSphereEffect.copy(ProtectiveSphere.java:73)
mage.cards.p.ProtectiveSphereEffect.copy(ProtectiveSphere.java:52)
mage.abilities.effects.Effects.<init>(Effects.java:26)
mage.abilities.effects.Effects.copy(Effects.java:31)
mage.abilities.Mode.<init>(Mode.java:36)
mage.abilities.Mode.copy(Mode.java:44)
mage.abilities.Modes.<init>(Modes.java:45)
mage.abilities.Modes.copy(Modes.java:67)
mage.abilities.AbilityImpl.<init>(AbilityImpl.java:114)
mage.abilities.ActivatedAbilityImpl.<init>(ActivatedAbilityImpl.java:57)
mage.abilities.common.SimpleActivatedAbility.<init>(SimpleActivatedAbility.java:38)
mage.abilities.common.SimpleActivatedAbility.copy(SimpleActivatedAbility.java:43)
mage.abilities.common.SimpleActivatedAbility.copy(SimpleActivatedAbility.java:15)
mage.abilities.AbilitiesImpl.<init>(AbilitiesImpl.java:35)
mage.abilities.AbilitiesImpl.copy(AbilitiesImpl.java:41)
mage.abilities.AbilitiesImpl.copy(AbilitiesImpl.java:20)
mage.MageObjectImpl.<init>(MageObjectImpl.java:72)
mage.cards.CardImpl.<init>(CardImpl.java:126)
mage.cards.p.ProtectiveSphere.<init>(ProtectiveSphere.java:43)
mage.cards.p.ProtectiveSphere.copy(ProtectiveSphere.java:48)
mage.cards.p.ProtectiveSphere.copy(ProtectiveSphere.java:30)
mage.game.stack.Spell.<init>(Spell.java:102)
mage.game.stack.Spell.copy(Spell.java:695)
mage.game.stack.Spell.copy(Spell.java:45)
mage.game.stack.SpellStack.<init>(SpellStack.java:30)
mage.game.stack.SpellStack.copy(SpellStack.java:127)
mage.game.GameState.<init>(GameState.java:131)
mage.game.GameState.copy(GameState.java:220)
mage.game.GameStates.save(GameStates.java:24)
mage.game.GameImpl.saveState(GameImpl.java:524)
mage.game.GameImpl.bookmarkState(GameImpl.java:645)
mage.players.PlayerImpl.playManaAbility(PlayerImpl.java:1180)
mage.players.PlayerImpl.activateAbility(PlayerImpl.java:1278)
mage.player.human.HumanPlayer.activateAbility(HumanPlayer.java:1686)
mage.player.human.HumanPlayer.activateAbility(HumanPlayer.java:1700)
mage.player.human.HumanPlayer.playManaAbilities(HumanPlayer.java:1194)
mage.player.human.HumanPlayer.playManaHandling(HumanPlayer.java:1087)
mage.player.human.HumanPlayer.playMana(HumanPlayer.java:1067)
mage.abilities.costs.mana.ManaCostsImpl.pay(ManaCostsImpl.java:127)
mage.abilities.AbilityImpl.activate(AbilityImpl.java:382)
mage.abilities.ActivatedAbilityImpl.activate(ActivatedAbilityImpl.java:288)
mage.game.stack.Spell.activate(Spell.java:134)
mage.players.PlayerImpl.cast(PlayerImpl.java:1095)
mage.players.PlayerImpl.activateAbility(PlayerImpl.java:1281)
mage.player.human.HumanPlayer.activateAbility(HumanPlayer.java:1686)
mage.player.human.HumanPlayer.activateAbility(HumanPlayer.java:1700)
mage.player.human.HumanPlayer.priority(HumanPlayer.java:952)
mage.game.GameImpl.playPriority(GameImpl.java:1248)
mage.game.turn.Step.priority(Step.java:61)
mage.game.turn.Phase.playStep(Phase.java:184)
mage.game.turn.Phase.play(Phase.java:89)
mage.game.turn.Turn.play(Turn.java:127)
mage.game.GameImpl.playTurn(GameImpl.java:850)
mage.game.GameImpl.play(GameImpl.java:759)
mage.game.GameImpl.start(GameImpl.java:723)
mage.server.game.GameWorker.call(GameWorker.java:34)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)

**Comment by jeffwadsworth** [comment]
Apparently, some required null checks were removed after this card's creation.  I am putting those back.
