### ISSUE TITLE
Bug: Vivien, Champion of the Wilds doesn't let you look at the face down card for her -2

### ISSUE THREAD

**Issue by duelcastermage** [magefree/mage#5752]
Basically just the title. The cards from her -2 just stay face down.

**Comment by JayDi85** [comment]
It's works fine:

![shot_190424_224603](https://user-images.githubusercontent.com/8344157/56685353-cf6a4100-66e2-11e9-9ae8-8760d4996c95.png)

![shot_190424_224624](https://user-images.githubusercontent.com/8344157/56685352-cf6a4100-66e2-11e9-8dff-524a01a8103d.png)

**Comment by jeffwadsworth** [comment]
Tested this as well and it worked fine.  Creatures/artifacts/instant/sorcery.

**Comment by duelcastermage** [comment]
Ok I think I expected the face-down card to behave like a morph or manifest on the battlefield, where I could just hover over it and mouse wheel down to see what was underneath. Clearly that's not the case here (which I think is a bit unintuitive....I feel like by clicking on the cards in this zone I'm either going to straight up cast them or at least reveal them to my opponent). Thanks.
