### ISSUE TITLE
Chandra, Fire Artisan losing loyalty counters doesnt trigger

### ISSUE THREAD

**Issue by drmDev** [magefree/mage#5754]
Opponent had Teyo, the Shieldmage in play,
I had Chandra, Fire Artisan

He attacks Chandra with Vraska's Finisher but I am not given the option to damage Teyo after Chandra loses 3 loyalty. I know the opponent has hexproof, but I should be able to damage Teyo. There was no trigger recorded in the logs even.

**Comment by mooretc2** [comment]
I'm actually running into this without Teyo. With Chandra out, I Lightning Bolt her, and no ability triggers.

Can someone else confirm?

**Comment by theelk801** [comment]
This'll take some work to fix but I see where the issue is. It's the first card to trigger off of multiple counters being removed so there were some unforeseen issues.

**Comment by jeffwadsworth** [comment]
Yeah, the events "COUNTER_REMOVED" and "COUNTERS_REMOVED" are not fired in some instances.  Paying a cost works fine, but not damage.

**Comment by theelk801** [comment]
Yeah, that's what I noticed. I'll fix it.

**Comment by theelk801** [comment]
I'm still planning to fix this but I'm busy until Sunday at the earliest so I'm un-assigning myself for now.

**Comment by jeffwadsworth** [comment]
If you are too busy, I can look at this.

**Comment by JayDi85** [comment]
Fixed via ec5134a6631f699ccef8a065b32a13f8ec7267f9
