### ISSUE TITLE
"Freeform Commander" not allowing "Freeform Commander Free for All" as a game type

### ISSUE THREAD

**Issue by mooretc2** [magefree/mage#5755]
From #5665 

> There is a minor issue with Freeform Commander, in order to get the game going You have to choose "Commander Free for All" as the game type, instead of the "Freeform Commander Free for All" version (chat, Whisper from Hoac);

Should the only allowable game type for a Freeform Commander deck be Freeform Commander Free for All, or should you also be able to select from the other commander variants?

**Comment by Stafy1** [comment]
It's been like this for some time. A workaround is just using commander free for all game type
