### ISSUE TITLE
[Bug] Teferi Time Raveler

### ISSUE THREAD

**Issue by MoralityShift** [magefree/mage#5759]
Does not keep Instant speed through Multiplayer games. Only through the next players turn. Once they end he loses his "Instant Speed" effect. (Already Reported in In-Game Client)

EDIT: To be more clear, in a Multiplayer format his Instant Speed effect fizzles after the person after you goes instead of until you start your next turn.

**Comment by jeffwadsworth** [comment]
The "UntilYourNextTurn" duration has some problems.  Good to see another case of it.

**Comment by JayDi85** [comment]
UntilYourNextTurn was broken, I'm works on it.

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.
