### ISSUE TITLE
Dovin, Hand of Control exception when artifact played

### ISSUE THREAD

**Issue by drmDev** [magefree/mage#5768]
After I resolved Dovin, my opponent's next turn tried to play the artifact Mana Geode. Every time opponent tries to cast it, exception is raised:

Game exception occurred: java.lang.ClassCastException: mage.abilities.common.EntersBattlefieldTriggeredAbility cannot be cast to mage.abilities.SpellAbility
Server version: 1.4.35V1 (build: 2019-04-24 19:17)
mage.cards.d.DovinHandOfControlEffect.apply(DovinHandOfControl.java:71)
mage.abilities.effects.ContinuousEffects.costModification(ContinuousEffects.java:608)
mage.abilities.AbilityImpl.activate(AbilityImpl.java:371)
mage.players.PlayerImpl.triggerAbility(PlayerImpl.java:1314)
mage.game.GameImpl.checkTriggered(GameImpl.java:1729)
mage.game.GameImpl.checkStateAndTriggered(GameImpl.java:1687)
mage.game.GameImpl.playPriority(GameImpl.java:1238)
mage.game.turn.Step.priority(Step.java:61)
mage.game.turn.Phase.playStep(Phase.java:184)
mage.game.turn.Phase.play(Phase.java:89)
mage.game.turn.Turn.play(Turn.java:127)
mage.game.GameImpl.playTurn(GameImpl.java:850)
mage.game.GameImpl.play(GameImpl.java:759)
mage.game.GameImpl.start(GameImpl.java:723)
mage.server.game.GameWorker.call(GameWorker.java:34)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)

**Comment by drmDev** [comment]
Looking at the section in the stack trace for Dovin:
```
    @Override
    public boolean apply(Game game, Ability source, Ability abilityToModify) {
        SpellAbility spellAbility = (SpellAbility) abilityToModify;
        CardUtil.adjustCost(spellAbility, -1);
        return true;
}
```
The artifact Mana Geode has an ETB ability (scry 1). `mage.abilities.common.EntersBattlefieldTriggeredAbility cannot be cast to mage.abilities.SpellAbility`

**Comment by jeffwadsworth** [comment]
https://github.com/magefree/mage/issues/5758
