### ISSUE TITLE
Error: "Freeform Commander needs Freeform Commander game type" (when trying to play 1v1)

### ISSUE THREAD

**Issue by duelcastermage** [magefree/mage#5771]
1v1 Freeform Commander is no longer working. I know this was possible just 1 or 2 updates ago, so something must have changed.

![image](https://user-images.githubusercontent.com/46700039/56897633-53c81580-6a8f-11e9-8524-a2f28fc605ec.png)

This is very unfortunate as I was going to run a 1v1 Freeform Commander tournament starting Thursday but now it seems impossible :(

**Comment by JayDi85** [comment]
As workaround you can use v1 client for that games on de-server (v1 can create, v2 can join):
http://xmage.de/files/xmage_1.4.35V1.zip

**Comment by duelcastermage** [comment]
@JayDi85 Thanks that might work in the short term. Will be fixed for the next release though? 

Also any chance of being able to modify the starting life total for these matches?

**Comment by JayDi85** [comment]
Starting life is hard coded in game types, it's need some rework to add that option. Maybe in future.

**Comment by mooretc2** [comment]
Definitely related to #5755. I didn't get any discussion on either the issue or PR that I put out, so Freeform Commander decks are currently only able to be used in Freeform Commander Free For All games and vice versa. 

Should it be opened up to any Commander decks/game types? If not, could someone maybe put a list of which specific decks/types should be allowed for either?

**Comment by JayDi85** [comment]
Added two player duel as new game type in last update:

![shot_190430_163111](https://user-images.githubusercontent.com/8344157/56967238-e50fb880-6b71-11e9-902f-7104ba278871.png)
