### ISSUE TITLE
Just installed Xmage on a new pc, White screens without connecting.

### ISSUE THREAD

**Issue by Fenrir1987** [magefree/mage#5780]
So i installed xmage, everything upto date. I click launch client. The console opens, then the brown hat symbol appears as a new window ready to connect but instead just stays as a white screen and reads at the top server not connected. Below is the code that reads in the console after being left 10mins to try and connect.

INFO  2019-05-04 20:46:18,453 Starting MAGE client version 1.4.35V4 (build: 2019-05-04 05:13)                            =>[main] MageFrame.main 
INFO  2019-05-04 20:46:18,456 Logging level: INFO                                                                        =>[main] MageFrame.main 
INFO  2019-05-04 20:46:19,976 Loading database...                                                                        =>[AWT-EventQueue-0] RepositoryUtil.bootstrapLocalDb 
INFO  2019-05-04 20:46:20,373 DB: creating cards database                                                                =>[AWT-EventQueue-0] MageFrame.<init> 
INFO  2019-05-04 20:46:25,909 DB: need to add 221 new sets                                                               =>[AWT-EventQueue-0] ExpansionRepository.lambda$saveSets$0 
INFO  2019-05-04 20:46:35,049 DB: need to add 37067 new cards                                                            =>[AWT-EventQueue-0] CardRepository.lambda$saveCards$0 
INFO  2019-05-04 20:46:41,978 Done.                                                                                      =>[AWT-EventQueue-0] MageFrame.<init> 
INFO  2019-05-04 20:46:41,986 Loading symbols...                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadImages 
WARN  2019-05-04 20:46:42,013 Symbols can't be load for size 15: SVG fails - 52, GIF fails - 52                          =>[AWT-EventQueue-0] ManaSymbols.loadSymbolImages 
WARN  2019-05-04 20:46:42,021 Symbols can't be load for size 25: SVG fails - 52, GIF fails - 52                          =>[AWT-EventQueue-0] ManaSymbols.loadSymbolImages 
WARN  2019-05-04 20:46:42,027 Symbols can't be load for size 50: SVG fails - 52, GIF fails - 52                          =>[AWT-EventQueue-0] ManaSymbols.loadSymbolImages 
INFO  2019-05-04 20:46:42,228 Loading plugins...                                                                         =>[AWT-EventQueue-0] Plugins.loadPlugins 
INFO  2019-05-04 20:46:42,294 [Game counter plugin, version 0.1] has been loaded.                                        =>[AWT-EventQueue-0] CounterPluginImpl.newPlugin 
INFO  2019-05-04 20:46:42,316 [Card plugin, version 0.7] has been loaded.                                                =>[AWT-EventQueue-0] CardPluginImpl.newPlugin 
INFO  2019-05-04 20:46:42,324 [Theme plugin, version 0.5] has been loaded.                                               =>[AWT-EventQueue-0] ThemePluginImpl.newPlugin 
INFO  2019-05-04 20:46:42,330 Done.                                                                                      =>[AWT-EventQueue-0] Plugins.loadPlugins 
INFO  2019-05-04 20:46:43,897 Client start up time: 25 seconds                                                           =>[AWT-EventQueue-0] MageFrame.lambda$new$2 
INFO  2019-05-04 20:46:43,898 Auto-connecting to xmage.de                                                                =>[AWT-EventQueue-0] MageFrame.autoConnect 
INFO  2019-05-04 20:46:44,155 Connect: connecting to server xmage.de:17171                                               =>[SwingWorker-pool-6-thread-2] SessionImpl$5.work 
INFO  2019-05-04 20:46:44,632 Connect: DONE                                                                              =>[SwingWorker-pool-6-thread-2] SessionImpl$5.work 
INFO  2019-05-04 20:46:44,636 Logging: as username Fenrir1987 to server xmage.de:17171                                   =>[SwingWorker-pool-6-thread-3] SessionImpl$4.work 
INFO  2019-05-04 20:46:44,779 Logging: FAIL                                                                              =>[SwingWorker-pool-6-thread-3] SessionImpl$4.work 
ERROR 2019-05-04 20:47:43,106 Ping failed: Fenrir1987 Session: 5c4o08-smcc7w-jv9x4itq-1-jv9x4iw4-4 to MAGE server at xmage.de:17171 =>[pool-1-thread-1] SessionImpl.ping 
FATAL 2019-05-04 20:47:43,107 Server error                                                                               =>[pool-1-thread-1] SessionImpl.handleMageException 
mage.MageException: Ping failed
	at mage.remote.SessionImpl.ping(SessionImpl.java:1654)
	at mage.client.SessionHandler.ping(SessionHandler.java:42)
	at mage.client.MageFrame.lambda$new$1(MageFrame.java:263)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by JayDi85** [comment]
Disable auto-connect by [that instructions](https://github.com/magefree/mage/issues/4461#issuecomment-361108597).

**Comment by Fenrir1987** [comment]
Thank you very much it has worked for me.
