### ISSUE TITLE
Standard Bearer target checks can broke spell

### ISSUE THREAD

**Issue by JayDi85** [magefree/mage#5784]
From [reddit](https://www.reddit.com/r/XMage/comments/biodfn/bug_standard_bearer_river_heralds_boon/):
> My opponent controlled a [[Standard Bearer]], I controlled two Merfolk creatures and played [[River Herald's Boon]]. Of course I target the Standard Bearer with the first part and one of my Merfolks with the second, which should put a counter on each of them. Instead, nothing happened as the spell resolved and no counters were placed, not even on the Standard Bearer which would have been the mandatory part of the effect.
> 
> I haven't had the opportunity to check this with other multi-target cards, so I don't know if the problem was Boon with the half mandatory, half optional effect, or the Bearer.
> 
> For anyone interested in how this situation came to be (or why anyone would even play River Herald's Boon), I played UG Pauper Merfolk, my oppponent was on Sprout Swarm/Midnight Guard combo and sided the Standard Bearer for game two.
> 

```
[test retarget]
battlefield:Computer:Standard Bearer:1
battlefield:Human:Coral Merfolk:2
hand:Human:River Heralds' Boon:5
```

It's a real life proof of old problem with inner rollbacks -- xmage uses rollbacks all around -- for some spells/checks/actions and that's can broke objects refs (see #4407 for more details and examples).

As example: `Standard Bearer` uses `TargetsHaveToTargetPermanentIfAbleEffect` -- that's effect checks targets and shows error message on wrong conditions. That's replacement event calls by `Ability->Targets->chooseTargets` method and uses rollbacks (don't known why -- maybe some targets needs extra payment like sacrifice and needs rollbacks too, hmm). 
![shot_190506_003046](https://user-images.githubusercontent.com/8344157/57199950-3535b300-6f96-11e9-95ed-abe3d5f5e5b5.png)

`Targets->chooseTargets` saves selected targets to yourself. The big problem here -- ability with selected targets is part of the game state object. And that's objects copy on rollbacks... E.g. after rollback your current `Targets` will be outdated and contains old refs from old state -- and that's outdated refs will be used for next choosing -- but real game will use empty targets list from actual refs. That's reason of Standard Bearer's bug.

**Comment by Zerrisx** [comment]
This should be fixed by the associated commit.
