### ISSUE TITLE
Nissa, Who Shakes the World interaction with Nicol Bolas, Dragon-God

### ISSUE THREAD

**Issue by jeffwadsworth** [magefree/mage#5792]
https://www.slightlymagic.net/forum/viewtopic.php?f=70&t=23344&p=235330#p235332

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.

![image](https://user-images.githubusercontent.com/59861365/87446351-cc48c280-c5be-11ea-81eb-0b8113b991ec.png)
