### ISSUE TITLE
Teferi, Hero emblem interaction with Jace, Mind Scupltor brainstorm

### ISSUE THREAD

**Issue by DParkside** [magefree/mage#5794]
Hi,

Was just playing a game where I emblemed Teferi, Hero to exile a permanent opponent controls  then used Jace, Mind Scupltor brainstorm ability. The game drew the three cards, I put back two, then it froze. It gave a fatal null pointer exception in the console.

Quitting and reloading the client did not fix the issue.

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.
