### ISSUE TITLE
easy way to add new bulk of cards?

### ISSUE THREAD

**Issue by evasoft** [magefree/mage#5801]
is ther a way to add 1000 new cards easily?
is a private server for a new game, cards dont need to activate abilities.
thanks

**Comment by JayDi85** [comment]
You can add [custom cards with any abilities](https://github.com/magefree/mage/commit/dc04092fce2c7968f33167318e5014cef5770892#commitcomment-33336376) to the game without creating real cards/code.

Give me more details about your task (what you want to do?).

**Comment by evasoft** [comment]
add a new set with 1000 cards for play a non magic game online, we can activate abilities manual, 
we add pictures .zip in xmage\mage-client\plugins\images. are a easy way to add it to Mage.Sets/src/mage/cards/?

**Comment by evasoft** [comment]
game is https://www.gobiernoyprestigio.com, we want to make a free server for all, 
the authors of the game authorized us to make it.

**Comment by JayDi85** [comment]
[That's game](https://www.gobiernoyprestigio.com/doradas) contains cards with abilities -- it's requires custom code (e.g. one java file per card). Wiki pages have [howto instructions](https://github.com/magefree/mage/wiki/Developer-HOWTO-Guides#add-new-card)  about adding new cards (there are also special perl script to create new STUB file from card's description, but it can create only simple cards, all abilities must be coded manually).

All this will require a lot of work, but can be implemented in xmage (see example with [Star Wars set](https://github.com/magefree/mage/blob/50c7aadcc82a02dbf3d37f024003c30d50b35814/Mage.Sets/src/mage/sets/StarWars.java)). I can't research full cards set (don't know Spanish language) but if that game have simple cards with simple/standard abilities then thare are possible to create special text file with all cards data and generate cards from that file (see example with perl scripts above).

![shot_190518_081659](https://user-images.githubusercontent.com/8344157/57964409-2364f000-7946-11e9-9d7d-9e3e4c093e91.png)
![shot_190518_081605](https://user-images.githubusercontent.com/8344157/57964410-2364f000-7946-11e9-9a8e-b5ba926e1801.png)

**Comment by evasoft** [comment]
for know i need to add pictures and cards to deck editor without abilities in a easy way, i will add abilities later one by one.
thank you for your time.

**Comment by JayDi85** [comment]
Then you can use the instructions from the wiki-pages (see link above).
