### ISSUE TITLE
Pir, Imaginative Rascal and Doubling Season with Planeswalkers' Plus Abilities

### ISSUE THREAD

**Issue by ManaLocked** [magefree/mage#5802]
It was originally thought that Pir+Doubling Season would not affect the plus abilities of Planeswalkers since it is a cost to activating the ability. Recently, however, it has been proven that Pir being a replacement _effect_ for that casting cost makes it both an effect and a cost, so Doubling Season will affect it.

+1 ability is now a +4
+2 ability is now a +6
(basically, +n = 2^(n+1) now)

Here are the rules that verify this:

614.1 Some continuous effects are replacement effects. Like prevention effects (see rule 615), replacement effects apply continuously as events happen—they aren’t locked in ahead of time. **Such effects watch for a particular event that would happen and completely or partially replace that event with a different event.** They act like “shields” around whatever they’re affecting.

614.16. Some replacement effects apply “if an effect would create one or more tokens” or “if an effect would put one or more counters on a permanent.” These replacement effects apply if the effect of a resolving spell or ability creates a token or puts a counter on a permanent, and they also apply if another replacement or prevention effect does so, **even if the original event being modified wasn’t itself an effect.**

**Comment by ManaLocked** [comment]
I am a programmer too, so I'm trying to not just explain the problem, but find the solution. Sorry if this is at all redundant or not helpful, but I'll try to find any sections of interest, and maybe even make a merge request if I see the whole solution.

Relevant links:
[Pay Loyalty Cost](https://github.com/magefree/mage/blob/master/Mage/src/main/java/mage/abilities/costs/common/PayLoyaltyCost.java#L41)

**Comment by JayDi85** [comment]
Nope, that cards works fine. [Double Season doesn't trigger for +1 ability, but Pir's does](https://www.reddit.com/r/magicTCG/comments/8kdmqe/bbd_pir_imaginative_rascal/). I'v tested it with current dev version and all works fine.

Maybe you had other cards on the battlefield with double effects.

**Comment by JayDi85** [comment]
Nevermind, you are right -- [Pir+Double must works together](https://www.reddit.com/r/mtgrules/comments/aql1it/doubling_season_and_pir_imaginative_rascal/).

**Comment by JayDi85** [comment]
Fixed via ffbd5d373b13466f9087d15191d42c4b098d4cfa
