### ISSUE TITLE
M15 render of cards

### ISSUE THREAD

**Issue by spjspj** [magefree/mage#5803]
Would be nice to have an option for modo/M15 rendering to render permanents/cards with the old style border.
https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=283&type=card

Also, for dual mana producing lands (say a plains with Urborg out) would be nice to have the concentric rectangles ala Scrubland.

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.
