### ISSUE TITLE
Bestow partially active after enchanted creature returns to battlefield

### ISSUE THREAD

**Issue by SpikesCafe-google** [magefree/mage#5806]
I bestowed a Nighthowler onto my Golgari Thug. Next turn, I sacrificed the thug to Disciple of Bolas, so Nighthowler became a creature. I later got back my Golgari Thug and recast it, upon which the Nighthowler moved awkwardly like an Aura under the Disciple of Bolas, which should not happen. I can attack with the Nighthowler, which is correct, but it's also granting the +X/+X bestow stats to the Golgari Thug, which is wrong. There's probably a bug in Nighthowler, or more likely Bestow, that remembers the enchanted creature ID after it has left the battlefield.

![Capture](https://user-images.githubusercontent.com/16656302/57990655-9d949200-7a76-11e9-9285-d1dc99a724de.PNG)

**Comment by Zerrisx** [comment]
Yep, still happens.

1) Cast Golgari Thug, bestow Nighthowler onto it
2) Terminate Golgari Thug, put it on top of your deck
3) Recast Golgari Thug

![image](https://user-images.githubusercontent.com/59861365/87569331-92de8880-c68c-11ea-8e58-c3fe26eb5dda.png)

**Comment by jeffwadsworth** [comment]
#8157
