### ISSUE TITLE
Mana Web incorrectly applies to all opponents

### ISSUE THREAD

**Issue by Ebola16** [magefree/mage#5809]
This card is implemented incorrectly and does not match Mana Web's text. Mana Web should only apply to target opponent but it applies to all opponents in Commander Free For All.
![2019-05-23 (1)](https://user-images.githubusercontent.com/17330088/58272544-ce1d4a00-7d5c-11e9-9946-3614a75208f1.png)

**Comment by spjspj** [comment]
From gatherer it is any opp not target opp
1/04/2008 	When a land an opponent controls is tapped for mana, this card checks which types of mana (white, blue, black, red, green, or colorless) that land could produce using any of its mana abilities, not merely the one the player just used. Then it checks which lands that player controls have abilities that could produce any of those types of mana. Then it taps those lands.
1/04/2008
