### ISSUE TITLE
korean translation

### ISSUE THREAD

**Issue by namjisu** [magefree/mage#5813]
Hello! I am a Korean who is interested in this program. 
It is sad that there is no Korean translation version as a Korean.
If you are interested in the Korean version, I will help you translate it into Korean. 
I'd appreciate it if you could be positive about the proposal.

**Comment by JayDi85** [comment]
It's impossible -- xmage engine supports only English and can't support other languages (UI, messages, dialog texts).

But you can download Korean's images for cards (scryfall images source and mtgo render mode in preferences).

**Comment by JRHerlehy** [comment]
This would be a big rework of the engine, likely needing to pull the generation of text off of abilities and effects and going to some kind of l10n system ala MinecraftForge. Maybe could use something like MTGJSON as a primary source for full text, with additional stuff for keywords.
