### ISSUE TITLE
Bug:Yawgmoth, Thran Physician does not draw cards

### ISSUE THREAD

**Issue by Nkaiser50** [magefree/mage#5820]

**Comment by jgray1206** [comment]
Is this still happening? I am unable to reproduce this.

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.

**Comment by Nkaiser50** [comment]
this bug was from 2019

**Comment by Zerrisx** [comment]
Yep, I know. I'm in the middle of a project to recheck every issue in github to see which are still broken and which have been fixed.
