### ISSUE TITLE
Merfolk Trickster vs Tibalt Devils death trigger

### ISSUE THREAD

**Issue by Akagy** [magefree/mage#5825]
Merfolk Trickster is supposed to remove all abilities from a creature, still the WAR Tibalt's tokens still do damage when they die when targeted by Trickster. I don't know if this is a bug for all creatures that have deathtriggers or just the Devil tokens.

**Comment by drmDev** [comment]
Added some unit tests - think they confirm this is a bug. See the PR referenced above. Trickster vs Footlight Fiend worked correctly there, but not Trickster vs Devil token produced. I'm thinking it might have to do with Tokens then? I'll leave it up to the more experienced XMAGE devs to look at the PR and take a dive into it.
