### ISSUE TITLE
MH1 Basic Lands in Limited

### ISSUE THREAD

**Issue by denkibob** [magefree/mage#5828]
Hello!
There is a problem with the basic lands, that can be added to limited decks in Modern Horizons. The tournament rules state, that one can only use the basic snow lands that are in your pool (page 33 in: https://wpn.wizards.com/sites/wpn/files/attachements/mtg_mtr_21jan19_en.pdf). But in XMage you can add as many as you like, what makes the snow-based synergies much stronger...

**Comment by JayDi85** [comment]
Fixed via 77e92d9186f37642d93202740836a2aa8a552c35
