### ISSUE TITLE
Blood speaker upkeep trigger doesn't check if sacrificed

### ISSUE THREAD

**Issue by derlhurgoyf** [magefree/mage#5833]
When Blood Speakers upkeep trigger goes on the stack and and opponent's Call to the Grave is on top, making me sacrifice Blood Speaker,  it will still let me search for a demon creature card even though I didn't sacrifice it to its own ability.

**Comment by JayDi85** [comment]
Fixed via 40ce1201f66a4ce1b3e8f3371f275e8c02ba8213
