### ISSUE TITLE
Recruit the Worthy's buyback costs do not work

### ISSUE THREAD

**Issue by ValentinPerret** [magefree/mage#5835]
[[Recruit the worthy]] goes to graveyard even after paying buyback cost.

**Comment by theelk801** [comment]
seems to be affecting all buyback

**Comment by JayDi85** [comment]
Same -- works fine as single card.

**Comment by derlhurgoyf** [comment]
Also Demonic Collusion goes to the graveyard when buyback costs are paid.

**Comment by JayDi85** [comment]
Fixed via dc7ccc6c4ee67c1f70ad93dec1eb7be52754ad1b
