### ISSUE TITLE
Walk the Aeons buyback not working

### ISSUE THREAD

**Issue by brookeburkett** [magefree/mage#5836]
After paying the cost (sacrificing 3 islands) it goes to the graveyard.
![image](https://user-images.githubusercontent.com/3799253/59100109-160ea600-88f3-11e9-94c2-295c911fc798.png)

**Comment by theelk801** [comment]
related to #5835

**Comment by JayDi85** [comment]
I'v tested it and it works fine (goes to hand). There are possible another card.

**Comment by JayDi85** [comment]
Fixed via dc7ccc6c4ee67c1f70ad93dec1eb7be52754ad1b
