### ISSUE TITLE
Server error card not found after upgrade to v36V2

### ISSUE THREAD

**Issue by brampat** [magefree/mage#5840]
Hi,
This occasionally happens to me and happened again after the most recent upgrade to 1.4.36V2. I think I upgrade from the most recent version before that, so it should have been introduced by only the latest code.

When I create a match with a deck, I get a message with "Server error card X not found". See 
this screenshot:
![Screen Shot 2019-06-09 at 16 40 48](https://user-images.githubusercontent.com/3624563/59160372-752c1080-8ad5-11e9-84dc-19863b3ea769.png)

Removing and re-adding the card fixes the problem for this single card, only to give a new error on the next card. This essentially forces me to re-create my decks, where they used to be just fine.

I've tried to restart both client and launcher. Also tried other decks. Nothing helps to fix the issue.

**Comment by brampat** [comment]
Looks like this issue:
https://github.com/magefree/mage/issues/669

**Comment by JayDi85** [comment]
It's server memory leaks (need restart).

**Comment by brampat** [comment]
Okay, it is fixed now
