### ISSUE TITLE
Mana abilities - net mana calculation don't work for double mana effects like Mana Flare

### ISSUE THREAD

**Issue by LevelX2** [magefree/mage#585]
Some mana producing abilities produce different amount of mana depending on a choice (which color).
So this abilities need to return a set of alternate netmana amounts depending on the choosen color.

Example:
Nykthos, Shrine to Nyx

**Comment by LevelX2** [comment]
Netmana calculation was improved.
Netmana is used to show the usable spells and abilities.
Still missing:
Support of mana doubling effects like Mana Flare.

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.

**Comment by JayDi85** [comment]
Nope, it's still actual for mana duplication effects like Mana Flare (xmage can't see double mana, so AI can't use it and GUI can't highlights available actions). See comments with some ideas to fix:
![shot_200518_045200](https://user-images.githubusercontent.com/8344157/82164801-7f4cb680-98c3-11ea-97cc-ea882cdbb88c.png)
