### ISSUE TITLE
Oathbreaker: indomitable creativity doesn't target

### ISSUE THREAD

**Issue by AricHaldan** [magefree/mage#5852]
I was casting indomitable creativity as my signature spell, however the spell did not allow me to target any creatures or artifacts and resolved without doing anything. I have tried it out afterwards on local server against AI and got the same result. This could potentially be a problem with other x mana, x target signature spells as well, but I haven't tested any of those yet.

Edit: the spell works perfectly when cast from hand. Tested this as well.

**Comment by JayDi85** [comment]
Fixed via 75e5ad3d7b96d2c1d8137460a6424a3e601f161d
