### ISSUE TITLE
Watcher For Tomorrows bugged

### ISSUE THREAD

**Issue by linniput** [magefree/mage#5854]
When i blink Watcher for Tomorrows with a soulherder and a naban on the Battlefield, i wont get the Cards, i exiled with his Hideaway Ability Earlier
Linus

**Comment by Aeronomotron** [comment]
Same issue. I have found that when it is exiled from the battlefield, you don't get the card, but when it dies, you do get the card. I am assuming it was programmed in as a death trigger, when it should be a leaves the battlefield trigger.

**Comment by enklave** [comment]
I just had the same issue when I tried to blink it with Ephemerate. Didn't get the card that was hidden away. Version 1.4.38V0

**Comment by jeffwadsworth** [comment]
The Hideaway exile is done incorrectly.  It will be fixed in the next release.
