### ISSUE TITLE
Affinity doesn't properly discount signature spells in Oathbreaker

### ISSUE THREAD

**Issue by brookeburkett** [magefree/mage#5856]
I cast Thoughtcast twice, making the tax 4. Casting it a third time with 13 artifacts on the battlefield reduced it to {U}, but then it added the commander tax ontop making it 4{U}.

![image](https://user-images.githubusercontent.com/3799253/59552409-88673200-8f54-11e9-891b-0deb58e2cf60.png)

**Comment by JayDi85** [comment]
Fixed via 6e5ba7a44606eda4d432a7a4a7d6d00b7a234c5b
