### ISSUE TITLE
HashMap is not thread safe. The existing synchronized(map) is too small, should be extended to cover the surrounding code.

### ISSUE THREAD

**Issue by paulward24** [magefree/mage#5864]
The current 

```synchronized (map) {```

https://github.com/magefree/mage/blob/master/Mage.Client/src/main/java/mage/client/util/gui/ArrowBuilder.java#L118-L126

does not also protect

```map.containsKey()``` and ```map.get()```

https://github.com/magefree/mage/blob/master/Mage.Client/src/main/java/mage/client/util/gui/ArrowBuilder.java#L115-L117

```map``` is a ```HashMap```, which is not thread-safe.

The ```synchronized (map)``` should be extended to cover
```map.containsKey()``` and ```map.get()``` too.

# Pull Request

https://github.com/magefree/mage/pull/5863

# Testing Done

```mvn test```

passed

**Comment by ingmargoudt** [comment]
#5863 was merged a while ago
