### ISSUE TITLE
Lightning Skelemental / Canadian Highlander

### ISSUE THREAD

**Issue by Akamayu** [magefree/mage#5866]
Hello,

I looks like Lightning Skelemental was mistakenly added in the point list of Canadian Highlander, as I can't play any Canadian Highlander deck containing it (reason : too many points). Lightning Skelemental is actually not in the point list. 

Thanks a lot for the correction !

**Comment by JayDi85** [comment]
Lightning Skelemental is not in points list. It's can be another card. Report full dech here or error message screenshot.

**Comment by Akamayu** [comment]
My bad, this was actually a mistake on my side, sorry for the confusion !
