### ISSUE TITLE
Aether Rift not working properly BUG

### ISSUE THREAD

**Issue by EllNubNub** [magefree/mage#5868]
Aether rift fails to bring the creature discarded to the battlefield. thats the bug.

**Comment by Zerrisx** [comment]
Sure doesn't.  Gave the AI a Platinum Emperion so it couldn't pay, and the ability just did nothing.

![image](https://user-images.githubusercontent.com/59861365/87571384-94f61680-c68f-11ea-8127-ac116a995907.png)
