### ISSUE TITLE
Misuses of cryptographic APIs

### ISSUE THREAD

**Issue by mhp0rtal** [magefree/mage#5878]
Hi
The following lines have cryptographic API misuses. <br> File name => Mage.Updater/src/main/java/com/magefree/update/helpers/ChecksumHelper.java: Line number => 20: API name => MessageDigest:First parameter (with value "SHA1") should be any of {SHA-256, SHA-384, SHA-512}<BR> File name => Mage.Updater/src/main/java/com/magefree/update/helpers/ChecksumHelper.java: Line number => 30: API name => MessageDigest:<BR>

**Comment by JayDi85** [comment]
It was outdated code with old files updater. Removed it.
