### ISSUE TITLE
Marrow-Gnawer cannot sacrifice itself (I think I found the reason for this bug)

### ISSUE THREAD

**Issue by scith** [magefree/mage#5879]
Hello,
I bring Marrow-Gnawer back from the graveyard with Goryo's Vengeance
I then try to sacrifice itself to put it back in the graveyard and create tokens.
XMage acknowledges the action in the log, but does not resolve it.

Is that a bug indeed? I don't see anything in the rules thay may prevent such action.
**EDIT: I think this is a bug related to how XMage entered the card's text. See my response below**

Thanks

**Comment by Maugerim2** [comment]
Do you have other rats on the field, because if it is just Marrow Gnawer, then when it resolves there will be no rats in play, so no rats are made.

**Comment by scith** [comment]
> Do you have other rats on the field, because if it is just Marrow Gnawer, then when it resolves there will be no rats in play, so no rats are made.

Hi, yes I do. I think I found the bug: Marrow-Gnawer's text, as printed on the card, is:
> Tap, **Sacrifice a Rat**: Create X 1/1 black Rat creature tokens, where X is the number of Rats you control.

However, on XMage, Marrow-Gnawer's text is:
> **Sacrifice a Rat**, Tap: Create X 1/1 black Rat creature tokens, where X is the number of Rats you control.

XMage doesn't let Marrow-Gnawer sacrifice itself because "Sacrifice a Rat" is put before the tap (contrary to the original text).

I think this explains the bug.
