### ISSUE TITLE
Cards preventing use of abilities do not work (bot only)

### ISSUE THREAD

**Issue by luzaasta** [magefree/mage#5890]
When playing against mad-bot on my localhost, when I use either "Prison Term" or "Faith's Fetters" card on "Yawgmoth, Thran Physician", the bot was still able to use his ability to pay 1 life, sack. creature and draw a card.
It works correctly when playing against a player.
I've had multiple connection breakdowns because of my firewall (which prevents any network connections for some Java programs and have to be disabled every 5 or so minutes), when playing against the bot, so maybe the reconnect has caused this?

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.
