### ISSUE TITLE
AI gives beneficial buffs with Retreat to Hagra to opponent's creatures

### ISSUE THREAD

**Issue by Ebola16** [magefree/mage#5909]
The AI should not use the first effect of Retreat to Hagra on opponent's creatures. If the AI doesn't control any creatures, it should always pick the second effect.

**Comment by Ebola16** [comment]
Condensed into #5705

**Comment by JayDi85** [comment]
Each card/ability/effect have special settings for AI (is it good or bad). That's why it's ok to inform about problem cards.

**Comment by Ebola16** [comment]
Ok, I'll reopen if it makes problems easier to track.

**Comment by Zerrisx** [comment]
Duplicate of #6838
