### ISSUE TITLE
Incorrect interaction between Bolas's Citadel and split-cards

### ISSUE THREAD

**Issue by Mekkiss** [magefree/mage#5912]
Bolas's citadel requires you to pay mana instead of life for a split card on top of library.

Steps to reproduce:

- Bolas's Citadel in play, Revival//Revenge on top of library.
- Cast Revenge, choose target
- receive prompt to pay 4WB.

Expected outcome
- No prompt for mana payment, payment of six life instead.

**Comment by JayDi85** [comment]
Fixed by #6093
