### ISSUE TITLE
Ulamog, the Ceaseless Hunger and Gargos

### ISSUE THREAD

**Issue by DerpyMcDerpDerp** [magefree/mage#5918]
Ulamog's cast trigger is an ability and should not trigger Gargos's fight ability, but that's what happened when I tried to target one of his creatures with the cast trigger. I cast ulamog for free with fist of suns and morophon, in commander, targetted the guy's Kalonian hydra.

**Comment by jeffwadsworth** [comment]
The Gargos fight trigger is specifically triggered by a "spell" that targets a creature you control.

**Comment by jeffwadsworth** [comment]
Works fine in my tests.
![Works](https://user-images.githubusercontent.com/1496996/71739758-fd7e5400-2e1f-11ea-8ffd-1be0de022e4c.jpg)
