### ISSUE TITLE
Ludevic, Necro-Alchemist

### ISSUE THREAD

**Issue by Akamayu** [magefree/mage#5921]
Hi ! I had an issue today with Ludevic, Necro-Alchemist (Duel Commander game) : I was the controller of Ludevic, dealt damage to my opponent, but Ludevic's ability didn't trigger at my end step. However, as my opponent lost life during his turn, the ability did trigger at the beginning of his end step, and he got to draw a card, as expected. Looks like the bug only concerns Ludevic's ability during its controller's end step. Thanks !

**Comment by Akamayu** [comment]
Ok I played Ludevic again today and notice something : the bug only occurs when I use the F5 shortcut (to end step). Everything works fine if I use F4 or F9.

**Comment by JayDi85** [comment]
Works fine:

![shot_191223_112359](https://user-images.githubusercontent.com/8344157/71342746-1f055300-2577-11ea-8ed5-795f9e26e1a5.png)
