### ISSUE TITLE
Yennett, Cryptic Sovereign - Triggered ability should draw card on declining action

### ISSUE THREAD

**Issue by cascadetime** [magefree/mage#5926]
This ruling for Yennett, Cryptic Sovereign is not properly implemented (specifically bold part)

> 7/13/2018 | If the revealed card doesn’t have an odd converted mana cost **or if that card does but you choose not to cast it**, you draw a card. Keep in mind that revealing a card doesn’t cause it to change zones. This means that the card you draw will be the card you revealed.

Rulings source: https://gatherer.wizards.com/Pages/Card/Details.aspx?name=Yennett%2C+Cryptic+Sovereign

I believe the fix would be to add an else-statement with  `player.drawCards(1, game);` to this if-statement https://github.com/magefree/mage/blob/master/Mage.Sets/src/mage/cards/y/YennettCrypticSovereign.java#L93

**Comment by ingmargoudt** [comment]
You are correct, in the current implementation you only draw a card if the converted mama cost is not odd. Adding the extra else should suffice.
