### ISSUE TITLE
Where is the grave yard? Sorry.

### ISSUE THREAD

**Issue by Innomen** [magefree/mage#5927]
I tried hard to figure this out, I even used a search engine to crawl the forum for the word and I found nothing useful.

Playing vs two AI. (it doesn't seem to let me play vs one?)

I can't see any graveyard, I don't see a hotkey for it, or a button or anything. It might be hidden off screen? The avatar panel won't scroll all the way down and I can't resize that window, maybe related? Thanks, sorry again, all this is very complex, not even sure I'm posting in the right place.

**Comment by JayDi85** [comment]
There are icons with numbers under avatar -- that's the player panel. Press on that icons to open graveyard and other zones. Example:

![shot_190806_093300](https://user-images.githubusercontent.com/8344157/62513465-32fd2200-b82d-11e9-8d57-0426d22f8a4b.png)

**Comment by Innomen** [comment]
Ohhhh ok thanks, XD A hotkey for that is needed imo.
