### ISSUE TITLE
Jeskai Infiltrator Combat Damage Trigger : crashes game (and server ?)

### ISSUE THREAD

**Issue by cpttrvs** [magefree/mage#5932]
When a Jeskai infiltrator deals combat damage to a player, the trigger where it shuffles itself and the top card of the deck crashes the game. When trying to reconnect, the server seems off. It happened twice (12/08/2019 00:52 GMT+1 last time)

**Comment by ingmargoudt** [comment]
I looked at the code of Jeskai Infiltrator. It looks like there is an infinite loop that in turn causes a memory exception (it makes an “infinite” amount of tokens). Should be easy to fix.

**Comment by JayDi85** [comment]
@ingmargoudt is it was fixed in a979bbfdaee02f87d6aaa025e6e093208153d944 ?

**Comment by jeffwadsworth** [comment]
https://github.com/magefree/mage/commit/a979bbfdaee02f87d6aaa025e6e093208153d944
