### ISSUE TITLE
Icon of Ancestry allows choosing creatures of non-matching types

### ISSUE THREAD

**Issue by SpikesCafe-google** [magefree/mage#5933]
Client/server 1.4.37V4.

6:45 PM: SpikesCafe2 casts Icon of Ancestry [1e8]
6:46 PM: Icon of Ancestry: SpikesCafe2 has chosen Dragon
6:46 PM: SpikesCafe2 puts Icon of Ancestry [1e8] from stack onto the Battlefield
6:46 PM: SpikesCafe2 activates: look at the top three cards of your library. You may reveal creature card of the chosen type from among them and put it into your hand. Put the rest on the bottom of your library in any order. from Icon of Ancestry [1e8]
6:46 PM: SpikesCafe2 puts a card from library into their hand
6:46 PM: SpikesCafe2 reveals Dragonlord's Servant

Dragonlord's Servant, which is a Goblin Shaman, does not get a boost from this ability, but should not be able to be chosen.

**Comment by jeffwadsworth** [comment]
Finally got around to this.  Fix coming soon.
