### ISSUE TITLE
Mana reflection issue

### ISSUE THREAD

**Issue by tdmorrin** [magefree/mage#5935]
Mana reflection is giving 4x mana instead of 2x mana from permanents with counters on them or just extra mana from them. Example Marwyn, The nurturer with 7 counters and total of 8 power gives me 32 mana when it should give me 16 and gyre sage with 2 counters on them gives me 8 mana when it should only give me 4.

**Comment by jeffwadsworth** [comment]
https://github.com/magefree/mage/commit/2649435071881ceace780a1b8e81cc9e143c1136
