### ISSUE TITLE
Vivien, Arkbow Ranger +1 Ability

### ISSUE THREAD

**Issue by DominusMaximus** [magefree/mage#5956]
1.4.37V4 (2019-07-13)

Currently Vivien's +1 ability cannot be activated if there are no creatures on the battlefield. From Vivien's rulings:

"You can activate Vivien’s first ability without choosing any target creatures. The counters won’t be put on anything. This is a change from previous rules regarding distributing counters."

**Comment by theelk801** [comment]
Trying to figure out a fix for this, not sure what to do.

**Comment by LevelX2** [comment]
Seems fixed.
