### ISSUE TITLE
WAR gods not losing their dies/exile trigger

### ISSUE THREAD

**Issue by mememan65** [magefree/mage#5969]
If you strip WAR gods (Kefnet, Bontu etc) from their abilities with Kasmina's Transmutation, Merfolk Trickster or equivalent and then they die or are put in to exile their  "dies or is put into exile from the battlefield, you may put it into its owner’s library third from the top." will still trigger instead of not triggering as it should.

**Comment by jeffwadsworth** [comment]
I assume you are referring to God-Eternal Oketra and its ability.
