### ISSUE TITLE
Card Database not Complete?

### ISSUE THREAD

**Issue by TheSmallAvali** [magefree/mage#5970]
I'm having trouble with some of the Warlock, Food, and Mouse cards included as a part of Throne of Eldraine. Here's the issue the command script spits at me for Alela, Artful Provocateur. It spits similar error sequences for Chittering Witch, Bake Into A Pie, Gilded Goose, and Enchanted Carriage.
![8b7a50f15db7527e4e5d24a3511c62bc](https://user-images.githubusercontent.com/55161418/64647290-9864a580-d3cd-11e9-8564-ef43e9cf684d.png)

**Comment by JayDi85** [comment]
There were problem with xmage update (maybe it running while updating from launcher):
1. Close all `java.exe` apps (or restart machine);
2. Find and delete `xxx\xmage\mage-client\db` folder;
3. Find and delete `xxx\xmage\mage-server\db` folder;
4. Run launcher and press button to update.

**Comment by TheSmallAvali** [comment]
That seems to have worked! Thank you.
