### ISSUE TITLE
how can I backup user data and rate data?

### ISSUE THREAD

**Issue by siyiye** [magefree/mage#5972]
The server is ready to reload, how can I backup user data and rate data?

**Comment by JayDi85** [comment]
You can backup `db` folder.

Full list of files to backup:
* Database (safe for updates): `/mage-server/db/*`
* Config (**rewrite on update**): `/mage-server/config/*`
* Info/messages (**rewrite on update**): `/mage-server/server.msg.txt`
* Logs (safe for updates): `/mage-server/mageserver.log`

**Comment by siyiye** [comment]
OK，THX!!!
