### ISSUE TITLE
ELD: Second card drawn only triggers once per game (trigger abilities do not  resets correctly)

### ISSUE THREAD

**Issue by IBashar** [magefree/mage#6001]
In mage.abilities.common.DrawSecondCardTriggeredAbility, the trigger is never reset.
We should add this code at the beginning of checkTrigger(GameEvent event, Game game):
if (event.getType() == EventType.END_TURN_STEP_POST) {
     reset(game);     
     return false;
}

![Where to add code to DrawSecondCardTriggeredAbility](https://user-images.githubusercontent.com/9640419/65577907-0cc64980-df75-11e9-8e36-b800875c6a86.png)

**Comment by JayDi85** [comment]
Tested it and it's bugged (not works on opponent turn). 

BUT it's not END_TURN_STEP_POST -- reset works fine and calls every end turn. It's "**object state problem**". If you want to store some value between calls then you must use game state, not local variables (xmage objects copies all around before and after execute).

More details:
https://github.com/magefree/mage/issues/4407#issuecomment-502472713

![shot_190925_115735](https://user-images.githubusercontent.com/8344157/65580946-ac8ed200-df8b-11e9-990b-d61da5eab1c6.png)

**Comment by JayDi85** [comment]
Hmm, something wrong with reset code/triggered abilities. I'll research it later, but as workaround you can return END_TURN_STEP_POST check or use game state values (as above).

![shot_190925_120842](https://user-images.githubusercontent.com/8344157/65581839-430fc300-df8d-11e9-9e91-90b654586601.png)

**Comment by IBashar** [comment]
So, I've played with it on a local build. The solution I proposed earlier works fine, with two caveats:
- checkEventType only accepts EventType.DREW_CARD, should also accept END_TURN_STEP_POST
- the watcher looks fishy so I've added a watcher.reset() after the reset(game);
See the attached DrawSecondCardTriggeredAbility.txt (initially .java)
[DrawSecondCardTriggeredAbility.txt](https://github.com/magefree/mage/files/3654752/DrawSecondCardTriggeredAbility.txt)

Note: Just started looking at this project today, I'm not ready to do any commits. Yet.

**Comment by theelk801** [comment]
This is the same basic concept as Deathless Knight, so both abilities are relatively similar.

**Comment by IBashar** [comment]
Oh I see. So the game calls reset on all active abilities at the end of each turn? Then the problem with DrawSecondCardTriggeredAbility lies within the watcher. It is actually not needed, the number of cards drawn could be handled by the ability.

**Comment by theelk801** [comment]
Yeah, I had a different implementation before but @JayDi85 suggested the change to using the `reset` method

**Comment by theelk801** [comment]
I've reverted it for now

**Comment by jeffwadsworth** [comment]
Does this still need some attention?

**Comment by rystan** [comment]
It seems to work as expected.  Before the last update, Improbable Alliance and Irencrag Pyromancer only triggered once a game, now they work as expected any turn with more than one draw in the current released version.

**Comment by jeffwadsworth** [comment]
Excellent.  I will close this unless something else comes up.
