### ISSUE TITLE
Watcher for Tomorrow and Ephemerate/Soulherder

### ISSUE THREAD

**Issue by Aitrusx** [magefree/mage#6004]
When you flicker a watcher for tomorrow you don't get the exiled card back regardless of how you stack the triggers. 

Watcher for tomorrow: When this ETB look at top 4 cards exile one. When this leaves the battlefield put the exiled card into your hand. 

Ephemerate/Soulherder: Exile target creature you control then return it to the battlefield under your control. 

I would imagine what happens is xmage sees the flickered watcher as a new object and fails to find the exiled card as a result - but thats really just a guess,

**Comment by jeffwadsworth** [comment]
https://github.com/magefree/mage/commit/792af6d3311f4287449d82256efa0f7adad41d8a
