### ISSUE TITLE
Kenrith, the Returned King black ability is wrong

### ISSUE THREAD

**Issue by rystan** [magefree/mage#6007]
![image](https://user-images.githubusercontent.com/6609665/66098027-dbe6a580-e56e-11e9-9d8f-d46ceb52388a.png)

Black ability should read: "4{B}: Put target creature card from a graveyard onto the battlefield under its owner's control" and the ability doesn't work that way currently either.

**Comment by annell** [comment]
Why is this closed? The problem is still there on kenrith.

**Comment by spjspj** [comment]
Annell - The change is in the *latest* version of the code (which only exists in github or on the xmage.today server perhaps)  You're seeing the released version of the code on xmage.de (possibly) which won't have the fix in it.
