### ISSUE TITLE
"Replenish" card does not return "Enchantment Creature" types from graveyard

### ISSUE THREAD

**Issue by luzaasta** [magefree/mage#6011]
I had a game against AI when I put several Enchantment cards and Enchantment Creature cards on purpose to graveyard (two of them was eg. NyleaGodOfTheHunt and Nylea's Colossus). Replenish returned plain Enchantment cards, but not those which had also Creature type. There were no cards  in play which would affect global gameplay or any triggers. Worth mentioning is that Enchanted Evening card was also in graveyard and made it to the board (possibly before those Creature typed).

**Comment by jeffwadsworth** [comment]
I tested this multiple times and it worked fine.  Perhaps if you had a game log that would help.  Also, the Nylea's Colossus fired the correct number of times to double a target creature's power and toughness.  That is a pretty deadly combo.
