### ISSUE TITLE
Wrong Client Version

### ISSUE THREAD

**Issue by drlawsoniii** [magefree/mage#6019]
I'm getting an error below. I've deleted and reinstalled the full launcher package to no avail. Any help would be appreciated!

![image](https://user-images.githubusercontent.com/57042979/67622842-7f347e80-f7ec-11e9-9b04-be66622c869d.png)

**Comment by JayDi85** [comment]
You are run beta client. It's inmcompatible with de and us servers. Download and run launcher from http://xmage.de/ (put that file to any folder like d:\games\xmage\de\)

**Comment by drlawsoniii** [comment]
Thank you that helped tremendously!
