### ISSUE TITLE
Beta and local servers don't work. So how can I test without a bot?

### ISSUE THREAD

**Issue by pandarama92** [magefree/mage#6023]
I have tried both servers but neither of them work. I continue getting messages like "Remote task error. Wrong client version."
Then it says "Your version: 1.4.39V0 Server version: 1.4.39V1"

So I'm not sure what to do. How do I fix this or at least update it correctly? 
![Error server](https://user-images.githubusercontent.com/57148170/67790719-9bcef180-fa4c-11e9-80ea-f2fca863378c.PNG)

**Comment by JayDi85** [comment]
1. Create two folders:
 * `d:\games\xmage\de\`;
 * `d:\games\xmage\beta\`;
2. Download launcher file from http://xmage.de/ and put it to `d:\games\xmage\de\`;
3. Run that launcher and download all all other files by it -- it's will be release version (for de and us servers);
4. Download full beta client from http://xmage.today/ and unpack it to `d:\games\xmage\beta\`;
5. Run beta launcher by `run-LAUNCHER.cmd` and download all files by it -- it's will be beta version (for beta server).
6. Don't use auto-connect checkbox in connection dialog.
7. Now you can run de-version and beta-version.

BTW, ai games available on release version too (just run local server from launcher).

**Comment by pandarama92** [comment]
Hello and thanks for replying. So I did the steps as suggested, however, still no luck. It will not connect to the beta nor the local AI. I'm stuck.

**Comment by JayDi85** [comment]
From your screenshot -- you are running release version (de), you can't connect from that version to beta-server.

How do you run xmage (what's you click to run it)?

**Comment by JayDi85** [comment]
@pandarama92 is problem fixed?

**Comment by Zerrisx** [comment]
This looks like user error, and also resolved.  Closing as such.
