### ISSUE TITLE
Login fail as username

### ISSUE THREAD

**Issue by HighNoonUrgot** [magefree/mage#6024]
When i try to connect to xmage i get this:
INFO  2019-10-29 20:20:20,813 Connect: connecting to server xmage.de:17171                                               =>[SwingWorker-pool-6-thread-5] SessionImpl$5.work 
INFO  2019-10-29 20:20:21,292 Connect: DONE                                                                              =>[SwingWorker-pool-6-thread-5] SessionImpl$5.work 
INFO  2019-10-29 20:20:21,293 Logging: as username HighNoon to server xmage.de:17171                                     =>[SwingWorker-pool-6-thread-4] SessionImpl$4.work 
INFO  2019-10-29 20:20:21,442 Logging: FAIL    

and then it freezes. How do i fix it?

**Comment by JayDi85** [comment]
I can't see you in server's logs -- it's client side connection problem. Check:
1. Client version must be 1.4.39V0;
2. Internet must be works;
3. xmage.de website works fine from your machine;
4. Xmage's launcher can check updates and show current version;
5. Images or symbols download must be works (if not then you will see error messages in logs).

**Comment by goesta** [comment]
I'll close this issue because there where no feedback for a long time but feel free to create a new one if this is still a problem.
