### ISSUE TITLE
Cannot run or debug unit tests from within VSCode 3

### ISSUE THREAD

**Issue by jthemphill** [magefree/mage#6036]
I can run unit tests from the terminal with

```
mage/Mage.Tests % mvn '-Dtest=LicidAbilityTest' test
```

But I can't use VSCode's test runner integration to run tests. I'd like to have access to the VSCode debugger here...

# Repro:

1. Set up VSCode with Mage as specified in README.md:

```
// .vscode/launch.json
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "java",
            "name": "Debug (Launch) - Current File",
            "request": "launch",
            "mainClass": "${file}"
        },
        {
            "type": "java",
            "name": "Run Client",
            "request": "launch",
            "mainClass": "mage.client.MageFrame",
            "projectName": "mage-client",
            "cwd": "${workspaceFolder}/Mage.Client"
        },
        {
            "type": "java",
            "name": "Run Server",
            "request": "launch",
            "mainClass": "mage.server.Main",
            "projectName": "mage-server",
            "cwd": "${workspaceFolder}/Mage.Server"
        }
    ]
}
```

```
// .vscode/settings.json
{
    "files.exclude": {
        "**/.classpath": true,
        "**/.project": true,
        "**/.settings": true,
        "**/.factorypath": true
    },
    "java.configuration.updateBuildConfiguration": "interactive"
}
```

2. Click the "Run Test" link above LicidAbilityTest. Nothing happens...
3. View "Java Test Runner" output console, see

```
org.mage.test.cards.abilities.activated.LicidAbilityTest.Failed to parse the message: %ERROR  1
```

4. Change `MageTestPlayerBase` to extend `junit.framework.TestCase`
5. Rename `CopyGameStatePerformanceTest.run` to `CopyGameStatePerformanceTest.go` to avoid the name conflict and fix the build
6. Click "Run Test" above LicidAbilityTest. Now the test runs, but it doesn't initialize `playerA` and we get a `NullPointerException`...

**Comment by JayDi85** [comment]
You don't need to change any code. Try to research first error. It's can be missing database files (game test needs db files). Run full tests from maven command line (it's will create all missing db) or copy-paste db folder from `\Mage.Server\db` or `\Mage.Client\db` folder to `\Mage.Tests\db` (or any other folder like `\Mage.\Verify\db` -- it's depend on your test).

**Comment by JayDi85** [comment]
Also you can run junit tests as normal java app (command line). I'm using that code:

`\Mage.Tests\src\test\java\org\mage\test\executor.java`:
```
package org.mage.test;

import org.junit.runner.JUnitCore;
import org.junit.runner.Result;
import org.junit.runner.notification.Failure;

/**
 * Tests executer to run tests as jar app (useful for profilers)
 *
 * @author JayDi85
 */
public class executor {
    public static void main(String[] args) {
        Result result = JUnitCore.runClasses(org.mage.test.AI.basic.TargetPriorityTest.class);
        for (Failure failure : result.getFailures()) {
            System.out.println(failure.toString());
        }
    }
}
```

Running config for IntellJ (you can call same params in vscode):
![shot_191110_042334](https://user-images.githubusercontent.com/8344157/68536785-e1a38800-0371-11ea-8fb0-b8f63743d504.png)

**Comment by jthemphill** [comment]
I've been able to run the command line, and I do have a db:

```
Mage.Tests % ls -l db
total 196128
-rw-r--r--  1 jhemphill  staff    96M Nov  9 21:24 cards.h2.mv.db
-rw-r--r--  1 jhemphill  staff    13K Nov  9 13:56 cards.h2.trace.db
```

I tried creating an executor class and running it from VSCode. It doesn't run the test:

```
cd /Users/jhemphill/oss/github/mage ; /Library/Java/JavaVirtualMachines/jdk-10.0.1.jdk/Contents/Home/bin/java -agentlib:jdwp=transport=dt_socket,server=n,suspend=y,address=localhost:50959 -Dfile.encoding=UTF-8 @/var/folders/71/zgwr_k2d5gldp8hg0r9g2444w7xzl1/T/cp_8hrzl6siio75oaue456s358ct.argfile org.mage.test.executor 
org.mage.test.AI.basic.TargetPriorityTest: null
```

I then made `MageTestPlayerBase` extend `junit.framework.TestCase`, and it did run the test. I do think that we should be extending the JUnit test class if we want to run tests with JUnit.

**Comment by JayDi85** [comment]
There is something else in vscode's config, not in xmage's code -- junit works without class extend.

**Comment by JayDi85** [comment]
OK, I'm tested vscode and it works fine with xmage's code (no needs in code editing).

Build Instruction ([as wiki](https://github.com/magefree/mage/wiki/Developer-Getting-Started#visual-studio-code-vsc)):
1. Prepare vscode with all plugins (see wiki);
2. Copy clean sources;
3. Open root folder in vscode and wait until build/index completed (see wiki);
4. Run maven full build by `mvn install -DskipTests` (see wiki);

Test instruction:
1. If you try to run test then you get missing files error:
![shot_191111_153149](https://user-images.githubusercontent.com/8344157/68584899-3e9a5d80-049a-11ea-8ecd-be613d8ebf07.png)
2. All tests must be run from `${workspaceFolder}/Mage.Tests` folder:
 * Go to File -> Preferences -> Setttings;
 * Search `java.test`, select Java Test Runner and press `edit in settings.json`;
![shot_191111_154742](https://user-images.githubusercontent.com/8344157/68585076-9fc23100-049a-11ea-92c9-94010da0c715.png)
 * add that config ([help with all commands](https://github.com/Microsoft/vscode-java-test/wiki/Run-with-Configuration)):
``` json
    "java.test.config": {
        "name": "xmage test run",
        "workingDirectory": "${workspaceFolder}/Mage.Tests"
    }
```
![shot_191111_154926](https://user-images.githubusercontent.com/8344157/68585166-db5cfb00-049a-11ea-9d2b-704c3acb37d0.png)
3. Now you can run tests with custom config and all will be works fine:
![shot_191111_155125](https://user-images.githubusercontent.com/8344157/68585238-1fe89680-049b-11ea-8353-4981a6c730d4.png)

**Comment by jthemphill** [comment]
Thanks, works for me!
