### ISSUE TITLE
Gift of Doom

### ISSUE THREAD

**Issue by goesta** [magefree/mage#6045]
The implementation of "Gift of Doom" has currently multiple issues.
As @JayDi85 already mentioned in https://github.com/magefree/mage/issues/5923

>  Gift of Doom - does literally nothing btw... you untransform it and it immediately dies (reddit);
> 
>   Gift of Doom (from Commander 2019) seems to be bugged. Once you've sacrificed your creature as a cost it doesn't resolve or ask you a target for the enchantment and it goes directly in the graveyard (forum).

This is what I discovered so far:
- You can't cast it facedown without having a creature on the battlefield.
- When casting face down you have to select a creature
- When you sacrifice the selected creature to pay for its morph ability it immediately goes to the graveyard with that card 

I couldn't find another card with morph which enchants a target creature. So this might be a new problem.
Has anyone an idea how to fix this?

**Comment by jeffwadsworth** [comment]
Working on it.
