### ISSUE TITLE
Destroyed Skullclamp still draws cards

### ISSUE THREAD

**Issue by propri** [magefree/mage#6047]
I destroyed the Skullclamped equipped to an opponents creature in response to a boardwipe. The Skullclamp draw ability still triggered, even though it was destroyed.

![Bildschirmfoto vom 2019-11-16 11-49-00](https://user-images.githubusercontent.com/38747561/68992121-6fe2a700-0867-11ea-9849-ea47141924c2.png)

**Comment by jeffwadsworth** [comment]
The Skullclamp test was wrong as well.  Pernicious Deed and many others were not destroying all filtered objects at the same time, but via a loop.
