### ISSUE TITLE
Can't Connect To LocalHost - All servers work fine though

### ISSUE THREAD

**Issue by rickpress** [magefree/mage#6048]
Hi I get told this when I try to connect to localhost for deck testing against the AI: - 

INFO  2019-11-19 19:44:21,800 Connect: connecting to server localhost:17171                                              =>[SwingWorker-pool-6-thread-10] SessionImpl$5.work 
WARN  2019-11-19 19:44:22,038 Cannot connect                                                                             =>[SwingWorker-pool-6-thread-7] SessionImpl.handleCannotConnectException 
org.jboss.remoting.CannotConnectException: Error setting up client lease upon performing connect.
	at org.jboss.remoting.Client.connect(Client.java:1928)
	at org.jboss.remoting.Client.connect(Client.java:737)
	at mage.remote.SessionImpl$5.work(SessionImpl.java:412)
	at mage.remote.SessionImpl$RemotingTask$1.doInBackground(SessionImpl.java:95)
	at mage.remote.SessionImpl$RemotingTask$1.doInBackground(SessionImpl.java:91)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.Exception: Error setting up client lease
	at org.jboss.remoting.MicroRemoteClientInvoker.establishLease(MicroRemoteClientInvoker.java:563)
	at org.jboss.remoting.Client.setupClientLease(Client.java:2070)
	at org.jboss.remoting.Client.connect(Client.java:1924)
	... 10 more
Caused by: org.jboss.remoting.CannotConnectException: Can not get connection to server. Problem establishing socket connection for InvokerLocator [bisocket://192.168.31.143:17171/?serializationtype=jboss]
	at org.jboss.remoting.transport.socket.MicroSocketClientInvoker.transport(MicroSocketClientInvoker.java:855)
	at org.jboss.remoting.transport.bisocket.BisocketClientInvoker.transport(BisocketClientInvoker.java:470)
	at org.jboss.remoting.MicroRemoteClientInvoker.invoke(MicroRemoteClientInvoker.java:169)
	at org.jboss.remoting.MicroRemoteClientInvoker.establishLease(MicroRemoteClientInvoker.java:529)
	... 12 more
Caused by: java.net.SocketException: Permission denied: connect
	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:85)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.jboss.remoting.transport.socket.SocketClientInvoker.connect(SocketClientInvoker.java:293)
	at org.jboss.remoting.transport.socket.SocketClientInvoker.createSocket(SocketClientInvoker.java:210)
	at org.jboss.remoting.transport.bisocket.BisocketClientInvoker.createSocket(BisocketClientInvoker.java:477)
	at org.jboss.remoting.transport.socket.MicroSocketClientInvoker.getConnection(MicroSocketClientInvoker.java:1190)
	at org.jboss.remoting.transport.socket.MicroSocketClientInvoker.transport(MicroSocketClientInvoker.java:833)
	... 15 more
INFO  2019-11-19 19:44:22,043 Disconnecting DONE                                                                         =>[SwingWorker-pool-6-thread-7] SessionImpl.disconnect 
INFO  2019-11-19 19:44:22,043 Disconnected from user mode                                                                =>[SwingWorker-pool-6-thread-7] MageFrame.disconnected 

I can connect to Xmage.de and any other server fine and play online fine but not locally. I browsed some of the help threads and tried the IPV4 or IPV6 thing and editing the hosts file to be what you guys say but it still doesn't connect. Any idea what is wrong? 

I have tried uninstalling and reinstalling Java with the latest version and also uninstalling and reinstalling xmage. 

Any advice be really appreciated. 

Rick

**Comment by JayDi85** [comment]
192.168.31.143 -- is that your machine ip? Or is it router?

> 19 нояб. 2019 г., в 15:48, rickpress <notifications@github.com> написал(а):
> 
> 192.168.31.143

**Comment by rickpress** [comment]
SSID:	920
Protocol:	Wi-Fi 4 (802.11n)
Security type:	WPA2-Personal
Network band:	2.4 GHz
Network channel:	6
IPv4 address:	192.168.31.143
IPv4 DNS servers:	192.168.31.1
Manufacturer:	Intel Corporation
Description:	Intel(R) Dual Band Wireless-AC 7265
Driver version:	19.51.16.2
Physical address (MAC):	F8-94-C2-43-0C-B0

My normal IP is 27.38.17.151
Shenzhen, Guangdong, China 

So I just wonder maybe that IP is from using NordVPN?

Not sure if it is my router IP. 

Wait this came back from IP Config on CMD.exe

(c) 2019 Microsoft Corporation. All rights reserved.

C:\Users\user>ipconfig

Windows IP Configuration


Ethernet adapter Ethernet:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . :

Ethernet adapter Ethernet 2:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . :

Wireless LAN adapter Local Area Connection* 1:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . :

Wireless LAN adapter Local Area Connection* 2:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . :

Ethernet adapter Ethernet 3:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . :

Wireless LAN adapter Wi-Fi:

   Connection-specific DNS Suffix  . :
   IPv4 Address. . . . . . . . . . . : 192.168.31.143
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Default Gateway . . . . . . . . . : 192.168.31.1

Ethernet adapter Bluetooth Network Connection:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . :

Not sure what's happening. The first time I ran Xmage everything worked then it stopped working in Localhost mode. 


That's what I get from my WIFI network on Windows 10 when selecting properties.

**Comment by rickpress** [comment]
Thank you for the help :)

**Comment by rickpress** [comment]
I think that is my router IP.

**Comment by rickpress** [comment]
![Screenshot (56)](https://user-images.githubusercontent.com/57946004/69164100-4f963f00-0b2a-11ea-9322-86fd95d3155b.png)

**Comment by rickpress** [comment]
![Screenshot (57)](https://user-images.githubusercontent.com/57946004/69164957-cb44bb80-0b2b-11ea-82f3-3417af6ecebd.png)

**Comment by jeffwadsworth** [comment]
If you ping localhost, you should get a 127.0.0.1.  Otherwise, just enter (in your case) 192.168.31.143.

**Comment by JayDi85** [comment]
Your ip: 192.168.31.143
You are connected by wi-fi to router: 192.168.31.1

XMage tries connect to local machine by IP: 192.168.31.143 -- that's must works in normal use cases (as well as connect to `localhost` or `127.0.0.1`).

What to do:
1. Check command `ping localhost` -- your must see 127.0.0.1 (if you can't see then follow [`host` file instructions](https://github.com/magefree/mage/issues/5191#issuecomment-410263225));
2. Check server startup logs -- you must see `listening messages` at the end, not errors.

**Comment by rickpress** [comment]
![Screenshot (58)](https://user-images.githubusercontent.com/57946004/69166873-ebc24500-0b2e-11ea-9ff1-96e42b9c1a1a.png)

**Comment by rickpress** [comment]
Do I need to change the host file to my IP address Jeff?

**Comment by rickpress** [comment]
![Screenshot (60)](https://user-images.githubusercontent.com/57946004/69167130-668b6000-0b2f-11ea-9166-9f843e5da45d.png)

**Comment by JayDi85** [comment]
It's ok, you don't need to change it (you can use localhost or 127.0.0.1). Run server from launcher and show last logs from it.

**Comment by rickpress** [comment]
Ok wait  . . . . thanks so much for the help btw

**Comment by rickpress** [comment]
![Screenshot (61)](https://user-images.githubusercontent.com/57946004/69169248-039bc800-0b33-11ea-885e-5d55cfd725b8.png)
![Screenshot (63)](https://user-images.githubusercontent.com/57946004/69169249-039bc800-0b33-11ea-8403-97a9adf2e1c2.png)

**Comment by rickpress** [comment]
This is what I got after clicking launch server not launch client and server.

**Comment by rickpress** [comment]
This is what came back it won't connect . . . .

**Comment by rickpress** [comment]
![Screenshot (65)](https://user-images.githubusercontent.com/57946004/69169573-8de42c00-0b33-11ea-84a7-22e047f5d33a.png)
![Screenshot (67)](https://user-images.githubusercontent.com/57946004/69169576-8f155900-0b33-11ea-81d7-fd18163a9f68.png)
![Screenshot (68)](https://user-images.githubusercontent.com/57946004/69169581-90df1c80-0b33-11ea-8976-ea0132dd9be3.png)

**Comment by JayDi85** [comment]
Logs fine too (timeout error).

It's firewall problem. If you don't know how to setup it -- just move files to new folder and run it from it (firewall will ask you about network access again).

**Comment by rickpress** [comment]
I'm pretty sure when I have checked the Windows 10 Firewall that Xmage JAVA is allowed to run through both public and private networks (explains how the internet servers work). 

How do I tell Windows 10 Firewall to allow local network connections?

I'm going to have to search around on the web.

**Comment by rickpress** [comment]
Thanks ever so much for all the help. It's really appreciated. I'll see if what you says works when I get home from work. 

Thanks again.

**Comment by rickpress** [comment]
Hi guys I tried doing what you said but it doesn't seem to be working. I gave Xmage permission on both public and private networks and copied the files from C:/xmage to C:/xmage1

I am not having any success.

![Screenshot (71)](https://user-images.githubusercontent.com/57946004/69232810-b5d09f80-0bc6-11ea-8640-f89414891459.png)
![Screenshot (72)](https://user-images.githubusercontent.com/57946004/69232812-b701cc80-0bc6-11ea-876f-357f9ceb3413.png)
![Screenshot (73)](https://user-images.githubusercontent.com/57946004/69232814-b79a6300-0bc6-11ea-9428-910cd52708d0.png)
![Screenshot (74)](https://user-images.githubusercontent.com/57946004/69232825-bb2dea00-0bc6-11ea-85bc-cd924cc37071.png)
![Screenshot (75)](https://user-images.githubusercontent.com/57946004/69232827-bcf7ad80-0bc6-11ea-824c-52d1813a3368.png)
![Screenshot (76)](https://user-images.githubusercontent.com/57946004/69232832-c254f800-0bc6-11ea-9c33-13fec0ef671e.png)

**Comment by JayDi85** [comment]
1. Make sure you allowed full access to xmage java files -- open that settings and enable full access. App paths must be like `\xmage_launcher_dir\java\jre1.8.0_201\bin\java.exe`:
![shot_191120_161203](https://user-images.githubusercontent.com/8344157/69238104-99296d00-0bb0-11ea-9454-dad43571b7ca.png)
2. Close all `java.exe` apps (xmage client and server);
3. Delete client logs file: `\xmage\mage-client\mageclient.log`;
4. Delete server logs file: `\xmage\mage-server\mageserver.log`;
5. Run xmage launcher, run server and client from that launcher;
6. Wait 1 minute after server start;
7. Try to connect to `localhost`;
8. If not works then close client and server;
9. Upload both log files here or to https://pastebin.com/ -- `mage-client\mageclient.log` and `mage-server\mageserver.log`.

**Comment by rickpress** [comment]
[mageclient.log](https://github.com/magefree/mage/files/3869204/mageclient.log)

[mageserver.log](https://github.com/magefree/mage/files/3869208/mageserver.log)

**Comment by rickpress** [comment]
I've tried it and allowed all the java stuff access to both public and private in the firewall - unless there was something else you meant? I still can't connect. :(

**Comment by JayDi85** [comment]
> Caused by: java.net.SocketException: Permission denied: connect

1. Close xmage apps;
2. Open launcher -> preferences -> java;
3. Add `-Djava.net.preferIPv4Stack=true` to both server and client command lines;
4. Press done button and run client and server, try to connect;
5. If not works then upload client logs again from `mage-client\mageclient.log`.

![shot_191120_164622](https://user-images.githubusercontent.com/8344157/69240195-62098a80-0bb5-11ea-8310-5c5b55c32c5e.png)

**Comment by rickpress** [comment]
When you say give full access you mean make sure both boxes are ticked for public and private network access right? I can't see any other options on there.

**Comment by JayDi85** [comment]
Yes, both checkboxes must be enabled. Is `-Djava.net.preferIPv4Stack=true` helps?

**Comment by JayDi85** [comment]
BTW open host file too and search for `192.168.31.143`... if you find it then remove. You must have only one localhost line:
* '127.0.0.1 localhost'

**Comment by rickpress** [comment]
![Screenshot (77)](https://user-images.githubusercontent.com/57946004/69240944-90e52800-0bd8-11ea-8dfb-8abcc212fc04.png)
Do you mean here? Put that option in here?

**Comment by JayDi85** [comment]
Yes, put it in both fields. Look at [my screenshot above](https://github.com/magefree/mage/issues/6048#issuecomment-555989827).

**Comment by rickpress** [comment]
![Screenshot (78)](https://user-images.githubusercontent.com/57946004/69241162-22549a00-0bd9-11ea-8760-80ec3fea1c77.png)
I checked the hosts file but cant find what you said. It doesn't seem to be there.

**Comment by rickpress** [comment]
![Screenshot (79)](https://user-images.githubusercontent.com/57946004/69241302-7bbcc900-0bd9-11ea-8380-fa80720494f3.png)
This is how my java settings look now. Is that okay?

**Comment by rickpress** [comment]
Tried it now that doesn't work.

**Comment by rickpress** [comment]
Really sorry for bothering you guys with these problems and really appreciate the help.

**Comment by rickpress** [comment]
![Screenshot (80)](https://user-images.githubusercontent.com/57946004/69241764-66946a00-0bda-11ea-9fe7-7fd0e9f5fa69.png)
I just tried it with these settings - copied yours - still doesn't work

**Comment by JayDi85** [comment]
Ok...

1. Download [Process Explorer](https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer);
2. Run xmage server;
3. Run process explorer and find java.exe (move mouse over file name to see full path -- it's must be server with your command lines):
![shot_191120_171543](https://user-images.githubusercontent.com/8344157/69242051-7cddfe00-0bb9-11ea-8978-a7d73ed06a2a.png)
4. Double click on it and open TCP/IP tab;
5. Make screenshot with resolve checkbox enabled and with disabled:
![shot_191120_171735](https://user-images.githubusercontent.com/8344157/69242191-c3335d00-0bb9-11ea-9ec4-6ba78f196079.png)
![shot_191120_171843](https://user-images.githubusercontent.com/8344157/69242215-d0e8e280-0bb9-11ea-9ff4-acf668b1544c.png)

**Comment by rickpress** [comment]
Ok here we go

**Comment by rickpress** [comment]
![Screenshot (81)](https://user-images.githubusercontent.com/57946004/69243554-46ff4080-0bde-11ea-9a70-76a98e18d368.png)
![Screenshot (82)](https://user-images.githubusercontent.com/57946004/69243558-48306d80-0bde-11ea-9a7c-23183cba05f6.png)
![Screenshot (83)](https://user-images.githubusercontent.com/57946004/69243559-49fa3100-0bde-11ea-89b7-b3180b7a69d5.png)
![Screenshot (84)](https://user-images.githubusercontent.com/57946004/69243562-4a92c780-0bde-11ea-9b4f-cae4568d31b7.png)
![Screenshot (85)](https://user-images.githubusercontent.com/57946004/69243564-4b2b5e00-0bde-11ea-83d2-797f7481017d.png)

**Comment by rickpress** [comment]
Is that okay? Screen shot wise?

**Comment by JayDi85** [comment]
It's ok... Server running fine with correct port. But server can't find client's IP address -- it's uses `192.168.31.143`. I think you switch off your wi-fi network.

OK. There is workaround (if you don't want to enable wi-fi to play xmage):
1. Close all xmage apps;
2. Open host file;
3. Add line at the end (localhost line must be too):
* `127.0.0.1 LAPTOP-L2PRS201` (it's your computer name)
4. Run launcher, run client and server;
5. Now you must connect to it by localhost. If not then upload client logs file `mageclient.log`

**Comment by rickpress** [comment]
The WiFI network is running all the time I only ever use the WIFI for internet access - no ethernet cable here.

![Screenshot (89)](https://user-images.githubusercontent.com/57946004/69247759-ed027900-0be5-11ea-8dfe-4ae1c9291d81.png)

Should my hosts file look like this. I've tried it like this and also like: - 
![Screenshot (86)](https://user-images.githubusercontent.com/57946004/69247809-03a8d000-0be6-11ea-9765-2e106fb53af1.png)

I tried connecting to my computers name and got this


![Screenshot (87)](https://user-images.githubusercontent.com/57946004/69247849-158a7300-0be6-11ea-88f8-01775621bce1.png)

And got this when trying to connect to "localhost"

![Screenshot (88)](https://user-images.githubusercontent.com/57946004/69247870-220ecb80-0be6-11ea-9235-d639a6ea2bc1.png)

Thanks so much for the help but still not connecting.

**Comment by JayDi85** [comment]
Download https://www.teamviewer.com/ , run it and send me ID and password to jaydi85@gmail.com -- I'll connect to your PC and test it.

**Comment by rickpress** [comment]
Ok I've sent the email over.

**Comment by JayDi85** [comment]
The problem was in broken IP address (computer can't see/connect to own IP 192.168.31.143 -- I don't known the reason -- it's can be firewall, antivirus, tcp/ip stack problem and much more). 

BUT there were workaround to ignore broken network:
1. Open server's config by text editor `\mage-server\config\config.xml`
2. Change `serverAddress="0.0.0.0"` to `serverAddress="127.0.0.1"` (it's allows to use only one network instead all available)
3. Run xmage server -- it's must shows in logs `listening on 127.0.0.1:17171`
4. Run xmage client and connect to `127.0.0.1` instead 'localhost'

**Comment by spjspj** [comment]
@rickpress  - have a check of https://studio.youtube.com/video/wvkwG8ojLU4
