### ISSUE TITLE
Repeated Reverberation with Loyalty Abilities

### ISSUE THREAD

**Issue by DominusMaximus** [magefree/mage#6049]
1.4.39.dev_2019-10-16_22-45

If I cast Repeated Reverberation and then activate a Planeswalker ability that results in that Planeswalker going to the graveyard (because it has run out of loyalty counters), the Reverberation will not create copies. I tested this with Chandra, Novice Pyromancer's deal 2 damage ability when it has only 2 loyalty counters, and Chandra, Awakened Inferno's -X ability (using all remaining loyalty counters).

**Comment by jeffwadsworth** [comment]
Confirmed with Chandra, Torch of Defiance ultimate as well.
