### ISSUE TITLE
Warden of Evos Vale AI Bug / Observation

### ISSUE THREAD

**Issue by rickpress** [magefree/mage#6050]
AI Bug - Warden of Evos Vale

Warden of Evos Vale has an ability whereby when the creature card is in play on the battlefield any creatures with flying cost one colourless mana (1 generic mana less) to cast. The computer played a neat move on me to remove all my creatures but since Warden of Evos Vale vale was removed back to my hand I could still cast creatures to my observation for one less colourless mana (the ability for Warden of Evos Vale is still in play despite the creature not being on the battlefield). 

![Screenshot (92)](https://user-images.githubusercontent.com/57946004/69348559-57ccb680-0cb1-11ea-9a14-230897d60a56.png)

**Comment by rickpress** [comment]
Awesome program btw. This and Forge are both awesome. Thanks for making it.

**Comment by jeffwadsworth** [comment]
The card works for me using a Sengir Vampire.  I also tested sending the Warden of Evos Isle to the graveyard and hand.  The effect was correctly removed and the Vampire was full cost.
