### ISSUE TITLE
M20 Leyline of Abundance adds mana to your pool when the enemy uses a creature's mana ability.

### ISSUE THREAD

**Issue by luziferius** [magefree/mage#6052]
M20 card Leyline of Abundance in part reads »Whenever you tap a creature for mana, add an additional {G}.«

So what I expect is: »Whenever you tap a creature for mana, add an additional {G}.«
As seen in the oracle text, here:
https://scryfall.com/search?q=!%22Leyline+of+Abundance%22

But XMage currently implements: »Whenever a player taps a creature for mana, add {G}.«
I get a green mana when my opponent taps a creature for mana.

Note 1: This ability is not mentioned in the log.

Note 2: This seems to be a very similar issue to https://github.com/magefree/mage/issues/201

**Comment by apetresc** [comment]
You're right @luziferius :) Reproduced and fixed in #6054.

**Comment by luziferius** [comment]
Seemed to be a simple fix by looking at the diff ;)
Thank you for fixing!
