### ISSUE TITLE
Cannot cast Spectacle cost from Chandra, Torch of Defiance +1. 

### ISSUE THREAD

**Issue by JustinDao** [magefree/mage#6056]
I cast Fiery Temper on an opponent (dealing 3 damage to them), then activated Chandra, Torch of Defiance's +1 ability, revealing Rix Maadi Reveler. I was not able to cast Rix Maadi Reveler for the Spectacle cost. 

Please let me know if I can provide any more info!

**Comment by jeffwadsworth** [comment]
Are any of the devs familar with the operation of something like:
`game.fireGetChoiceEvent(controller.getId(), "What does this do?", sourceObject, card.getAbilities(game).getPlayableAbilities(Zone.HAND));`

If so, could we use that to allow the controller to choose ability of the card in exile?
