### ISSUE TITLE
K'rrik does not allow you to pay extort costs using Phyrexian mana

### ISSUE THREAD

**Issue by zeflap** [magefree/mage#6058]
K'rrik's rulings mention how "If a cost contains a mana symbol that may be paid in multiple ways, such as {B/R}, {B/P}, or {2/B}, you choose how you’ll pay it before you do so. If you choose to pay {B} this way, K’rrik’s ability allows you to pay life rather than pay that mana. (2019-08-23)".
As such, Extort should also allow itself to be paid with 2 life, as it does on other platforms.

**Comment by jeffwadsworth** [comment]
A fix for this has to be tested.

**Comment by jeffwadsworth** [comment]
Fixed with https://github.com/magefree/mage/commit/e437577b5ace93ec22cb8b44f2cff8b3e3534851
