### ISSUE TITLE
Scourge of the Throne - additional combat phase does not trigger

### ISSUE THREAD

**Issue by ochilly** [magefree/mage#6065]
Scourge of the Thrones additional combat phase trigger does not go on the stack. No extra combat phase is granted and attacking creatures do not untap.

I tried multiple times over separate games, meeting the correct requirements each time.

The card reads:

Scourge of the Throne {4}{R}{R}
Creature — Dragon

Flying
Dethrone (Whenever this creature attacks the player with the most life or tied for most life, put a +1/+1 counter on it.)

Whenever Scourge of the Throne attacks for the first time each turn, if it’s attacking the player with the most life or tied for most life, untap all attacking creatures. After this phase, there is an additional combat phase.

5/5

**Comment by jeffwadsworth** [comment]
The conditional trigger was not set up to access the watchers associated with the primary triggered ability.  Fix coming soon.
