### ISSUE TITLE
Replace banned Trade Secrets in Political Puppets deck

### ISSUE THREAD

**Issue by Ebola16** [magefree/mage#6066]
Since Trade Secrets is banned, we should replace it with another card. Perhaps Standstill?
See also: https://www.reddit.com/r/EDH/comments/26m116/political_puppets_what_to_replace_trade_secrets/

**Comment by Zerrisx** [comment]
The official list still seems to include it, so we should as well.  Replacements would be done at user's discretion, or they could play in a freeform mode where the card isn't banned.
