### ISSUE TITLE
Brimstone Volley condition issues.

### ISSUE THREAD

**Issue by jbfitz** [magefree/mage#6079]
As of c482fade, a number of damage conditions changed their wordings. However, over the course of this change, Brimstone Volley was accidentally changed from a MorbidCondition card to a Hellbent Condition card.

Further, Brimstone Volley now defaults to 5 damage and deals 3 damage on its condition.

Brimstone Volley should deal 3 damage normally, and deal 5 damage with the Morbid condition active.

**Comment by fenhl** [comment]
99c50d041a53bf970552dde936f5e97825291691 doesn't fix this since the effects are still reversed. There's a pending PR, #6080, which fixes this and other instances of this bug.

**Comment by fenhl** [comment]
Fixed in #6080.
