### ISSUE TITLE
Bloomtender taps for mana equal to color identity instead of color

### ISSUE THREAD

**Issue by ssouders412** [magefree/mage#6083]
With "Sisay, Weatherlight Captain" and "Bloomtender" on the board, "Bloomtender" taps for {W}{U}{B}{R}{G} instead of {W}{G}. This is consistent with permanents' color identity instead of the expected permanents' color.

XMage version: 1.4.40V1a

**Comment by Maugerim2** [comment]
In the game of Magic, there is a distinction between color identity and color(s) of a card. I was looking around in the code, and I believe it lumps the two into one variable. You would have to rewrite FilterMana to make a distinction between the two. In the case of Bloom Tender, you would want to get a permanent's color(s), where as a card like Command Tower, you would want your Commander's color identity.

**Comment by LevelX2** [comment]
I can't reproduce that problem.

If you have any more hints about how to reproduce that problem, please report and reopen.
