### ISSUE TITLE
Thousand-Year Storm Not Copying Spells

### ISSUE THREAD

**Issue by jaboink** [magefree/mage#6085]
When you cast the first spell, the second spell that you cast should be copied once. It does not do that. It will show Thousand-Year Storm on the stack, then will not actually do anything

**Comment by jeffwadsworth** [comment]
We have this discussion all the time.  Here are some screenshots of tests.
![Example1](https://user-images.githubusercontent.com/1496996/70631597-000bd600-1bf3-11ea-9326-b75fe8e4f45d.jpg)
![Example2](https://user-images.githubusercontent.com/1496996/70631603-026e3000-1bf3-11ea-99ec-59080e3aac82.jpg)
![Example3](https://user-images.githubusercontent.com/1496996/70631610-0437f380-1bf3-11ea-8aed-4a56bc8888ba.jpg)

**Comment by JayDi85** [comment]
@jaboink it's can be rollback problem. Pay attention when card stops working.
