### ISSUE TITLE
Equipping Bloodthirsty Blade in 1v1 prevents the game from progressing

### ISSUE THREAD

**Issue by ssouders412** [magefree/mage#6086]
Starting at the select attackers menu:
- click a creature to attack (or All Attack)
- click the player to attack
- the interface reverts to the select attackers menu

If you instead click Done, a window pops up informing you of the creature that must attack. There is no way to skip past combat.

**Comment by ssouders412** [comment]
This is a duplicate issue of #4999 and #5283.

**Comment by jeffwadsworth** [comment]
The Goad thing is tricky.  I recall fooling around with trying to fix the "2 player" part of it a while back.

**Comment by JayDi85** [comment]
I tested Bloodthirsty Blade with two and multiplayer games -- it works fine. If you haven't target for enchanted creature (e.g. another player died or it two player game) then you can't attacks and it ignores (creature is not marked as attackable and you can't choose target for it).

**Comment by Alex-Vasile** [comment]
I believe this can be closed. I just tested and it works properly. The effect was re-implemented with Goad in 23582b4a09066934a4df9596ae64b36c6797d59f.
