### ISSUE TITLE
Zada, Hedron Grinder stack order

### ISSUE THREAD

**Issue by Tychology** [magefree/mage#6096]
I noticed that Zada, Hedron Grinders triggerd abillity doesn't let you choose the order the copies are put onto the stack, which is in contractiction with the ruling:
"You control all the copies. You choose the order the copies are put onto the stack."

**Comment by JayDi85** [comment]
Maybe it's can be rewritten to use `CopySpellForEachItCouldTargetEffect` (it's support to choose copies order).

**Comment by jeffwadsworth** [comment]
Fixing the issue with Silverfur Partisan.

**Comment by jeffwadsworth** [comment]
Just fixing the CopySpellTest.  The AI needs to target the Silverfur Partisan, whereas before it was automatic.

**Comment by JayDi85** [comment]
Use that two extra commands all the time for broken tests -- 50% of xmage tests are false positive (ai releated, not developer's commands):

```
setStrictChooseMode(true);
setStopAt(..);
execute();
assertAllCommandsUsed();
```

**Comment by jeffwadsworth** [comment]
Will something like this work when the targets are chosen?

`@Test
    public void ZadaHedronSilverfurPartisan() {

        // {2}{G}
        // Trample
        // Whenever a Wolf or Werewolf you control becomes the target of an instant or sorcery spell, put a 2/2 green Wolf creature token onto the battlefield.
        addCard(Zone.BATTLEFIELD, playerA, "Silverfur Partisan"); // 2/2 Wolf Warrior

        // Whenever you cast an instant or sorcery spell that targets only Zada, Hedron Grinder, copy that spell for each other creature you control that the spell could target. Each copy targets a different one of those creatures.
        addCard(Zone.BATTLEFIELD, playerA, "Zada, Hedron Grinder", 1);

        // Target creature gets +3/+3 until end of turn.
        addCard(Zone.HAND, playerA, "Giant Growth", 1); // {G}
        addCard(Zone.BATTLEFIELD, playerA, "Forest", 3);
        addCard(Zone.BATTLEFIELD, playerA, "Mountain", 3);

        castSpell(1, PhaseStep.PRECOMBAT_MAIN, playerA, "Giant Growth", "Zada, Hedron Grinder");
        setStrictChooseMode(true);
        setStopAt(1, PhaseStep.BEGIN_COMBAT);
        execute();
        assertAllCommandsUsed();

        assertGraveyardCount(playerA, "Giant Growth", 1);
        assertPowerToughness(playerA, "Silverfur Partisan", 5, 5);
        assertPowerToughness(playerA, "Zada, Hedron Grinder", 6, 6);
        assertPermanentCount(playerA, "Wolf", 1); // created from Silverfur ability
    }`
