### ISSUE TITLE
Mindshriek - AI targets itself not the other player for card discard / mill

### ISSUE THREAD

**Issue by rickpress** [magefree/mage#6099]
![Screenshot (113)](https://user-images.githubusercontent.com/57946004/70925188-c6f5ba80-2065-11ea-9190-5debec5b06b6.png)
![Screenshot (114)](https://user-images.githubusercontent.com/57946004/70925197-c9581480-2065-11ea-8ceb-e4beb0783c76.png)

Sorry this was an AI mistake - the Ai plays Mindshriek and targets itself and discards its own cards to the graveyard when it should do it to the opponent /s and mill them. Apologies if you don't need observations like this but saw other people post similar things about the AI.

**Comment by JayDi85** [comment]
Yes, that's was wrong target settings in card's code (AI thinks that it's a positive target and chooses yourself). Fixed via d228486cc7d0279c98fca0b16b2044cc381403e8. Feel free to report another AI bugs.
