### ISSUE TITLE
AI doesn't play lands, even discards them

### ISSUE THREAD

**Issue by BlackBeltBob** [magefree/mage#610]
I've just noticed that the AI player (level 1) sometimes doesn't play a single spell or permanent. I decided to bide my time to see what the AI player would do. It turned out that it simply discards a card on each of its turns. It cycled through its own deck like this the entire game. It discarded lands that it required to play spells.

**Comment by drmDev** [comment]
not sure if this is still occurring? I've played many games vs AI in testing cards and they play out their lands.
