### ISSUE TITLE
Command Tower tapping for too much mana with mana "doublers" present

### ISSUE THREAD

**Issue by Rewyn** [magefree/mage#6102]
Command Tower taps for 3 mana, instead of 2, when any of the following cards are present: Zhur-Taa Ancient, Nikya of the Old Ways, Zendikar Resurgent, Dictate of Karametra, Mana Flare, Mirari's Wake.
It does not happen with Caged Sun. With that one it's just the intended 2.
Not tested with any other cards.

**Comment by jeffwadsworth** [comment]
https://github.com/magefree/mage/commit/2649435071881ceace780a1b8e81cc9e143c1136
