### ISSUE TITLE
Nekrataal's ability doesn't trigger if only own creatures could be targeted

### ISSUE THREAD

**Issue by propri** [magefree/mage#6104]
Following scenario:

Player A: Kenrith, the Returned King with equipped Lightning Greaves (white)

Player B: Alesha, Who Smiles at Death. (red)

Player B casts Nekrataal. "When Nekrataal enters the battlefield, destroy target nonartifact, nonblack creature. That creature can’t be regenerated." His ability never triggers in the above scenario, even though it should.

If Player A's Kenrith does not have shroud, Nekrataal triggers as normal.

Xmage Client: 1.4.40V1, Server: 1.4.40V1

**Comment by jeffwadsworth** [comment]
![worksHere](https://user-images.githubusercontent.com/1496996/71211993-fe3ab600-2275-11ea-9bd7-56fb6e9b2547.jpg)
