### ISSUE TITLE
Incubation Druid with Leyline of Abundance

### ISSUE THREAD

**Issue by DominusMaximus** [magefree/mage#6106]
1.4.40.dev_2019-12-18_19-10

With a Leyline of Abundance under my control, my Incubation Druid would tap for 3 mana while it didn't have a +1/+1 counter on it, and would tap for 5 mana when it did.

**Comment by jeffwadsworth** [comment]
As mentioned in a pull request, the EventType.TAPPED_FOR_MANA is fired twice, thus putting double the green mana into the pool.  This affects any card similar to Leyline of Abundance.

**Comment by jeffwadsworth** [comment]
The pull request https://github.com/magefree/mage/pull/5943 fixes this issue.  Just have to test the AI with it.

**Comment by jeffwadsworth** [comment]
Fixed with: https://github.com/magefree/mage/commit/2649435071881ceace780a1b8e81cc9e143c1136
