### ISSUE TITLE
Monte Carlo Tree Search AI Question

### ISSUE THREAD

**Issue by MaxGagnon11** [magefree/mage#6114]
Hey all,

I noticed there is a chunk code code devoted to a Computer Player (AI) that uses MCTS. Is there a way to activate this in the game? If not, does anyone know what still needs to be done to get this feature/AI working? I'm interested in taking a look at it.

Thanks!

**Comment by JayDi85** [comment]
I added MCTS by 98cbf42a1193221233571c7d46ea9873a85a5349 -- you can enable it by server's config file `\Mage.Server\config\config.xml` (after full build):

![shot_191223_225322](https://user-images.githubusercontent.com/8344157/71375275-1e040e00-25d7-11ea-84d7-18d5ea706a6b.png)

BUT it was used in 2015 last time, I don't think it's works fine now (It works too slow and with some errors).

**Comment by jeffwadsworth** [comment]
It works, but it plays nonsense as far as I could tell when testing it a long time ago.

**Comment by MaxGagnon11** [comment]
Thanks guys!!

**Comment by Meerkov** [comment]
Why is it not available by default on the most recent build? Is it because the AI doesn't play very strong?

**Comment by jeffwadsworth** [comment]
Just a side-note.  The monte-carlo code does not actually simulate any games.  That is pretty much core to the whole thing.  I reverted it back to its earliest stages and same thing.
