### ISSUE TITLE
Token Image Files Wrong Pathway

### ISSUE THREAD

**Issue by rickpress** [magefree/mage#6129]
Hi 

Some of the Throne of the Eldraine tokens are already packaged / downloaded by Xmage and are stored in a different ZIP file to where they actually are: - 

The pathway Xmage is looking for by default for some tokens is: - 

tok.zip/celd 

When the actual directory the tokens are in is

tok.zip/eld

Just a simply typo I think but if changed by someone would make more tokens work by default rather than having to manually add them into a CELD tok zip which you need to create yourself. 

![Screenshot (134)](https://user-images.githubusercontent.com/57946004/71583128-1d73f600-2b48-11ea-9504-d8492614d717.png)
![Screenshot (133)](https://user-images.githubusercontent.com/57946004/71583130-1ea52300-2b48-11ea-9793-be7263b473ad.png)
![Screenshot (132)](https://user-images.githubusercontent.com/57946004/71583132-1fd65000-2b48-11ea-8a1a-3173c6e612a0.png)
![Screenshot (131)](https://user-images.githubusercontent.com/57946004/71583134-21077d00-2b48-11ea-8791-f16f6b25f388.png)

This seems to concern the tokens generated by Outlaws Merriment.

**Comment by JayDi85** [comment]
ELD and CELD sets were combined to one set, so no more actual.
