### ISSUE TITLE
Monocolored hybrid mana costs interacting incorrectly with cost reduction

### ISSUE THREAD

**Issue by Creatureten** [magefree/mage#6130]
Playing commander with Reaper King as my commander, having already been cast once and therefore his cost should be {2}{2/W}{2/U}{2/B}{2/R}{2/G}, which behaves as expected. However, if I have a Mycosynth golem and 3 other artifacts out, making him cost {4} less, his cost becomes both sides of the hybrid mana added up and then reduced by {4} afterwards, resulting in the cost to cast my commander being {8}{W}{U}{B}{R}{G}, instead of the expected {2/W}{2/U}{2/B}{2/R}{2/G} reduced by 2, which would make it so I can in effect cast him with 4 mana of distinct colors (as cost reduction occurs after I chose which cost I wish to pay with hybrid mana). It's also worth noting that the icon claimed I could cast him despite having no way to get 13 mana.

**Comment by JayDi85** [comment]
Improved monohybrid mana cost support by b5acf6477214d200917a3f2bdbd047e7a7613f8e
 * fixed wrong manually pay by mana pool (it pays generic cost instead colored part of monohybrid);
 * fixed not working cost reduction effects (now monohybrid cost will be reduced correctly);

But there are some limitation in xmage -- hybrid mana uses workaround to pay (it uses auto-pay for colored/generic part instead cost part announce on cast). So it can reduce only one hybrid cost after another (from left to right, you can't choose cost to reduce).

So your example will work fine in 80% and will not work if you missed colors from right side of the cost:
* 0 reduce -- {2/W}{2/U}{2/B}{2/R}{2/G}
* 1 reduce -- {1/W}{2/U}{2/B}{2/R}{2/G}
* 2 reduce -- {W}{2/U}{2/B}{2/R}{2/G}
* 3 reduce -- {W}{1/U}{2/B}{2/R}{2/G}
* 4 reduce -- {W}{U}{2/B}{2/R}{2/G}
* and etc.
