### ISSUE TITLE
Varchild doesn't give me non-token survivors

### ISSUE THREAD

**Issue by TiesWestendorp** [magefree/mage#6134]
Making Varchild leave the battlefield doesn't cause me to gain control of all my opponent's creatures after having cast Standardize naming Survivor or after Shields of Velis Vel targeting my opponent.

**Comment by jeffwadsworth** [comment]
![WorkedFine](https://user-images.githubusercontent.com/1496996/71734846-7aa2cc80-2e12-11ea-9bc4-3270fb8e7b33.jpg)

**Comment by LevelX2** [comment]
Should be fixed with next update by this commit 12c4bacc07e73f6dd78ec14757640657ba04d1c6

**Comment by jeffwadsworth** [comment]
Actually, it is still bugged.  I stupidly targeted the opponents creatures for the  test.  When I targeted my own creatures, the trigger fires.  Checking it out.

**Comment by jeffwadsworth** [comment]
> 
> 
> Should be fixed with next update by this commit [12c4bac](https://github.com/magefree/mage/commit/12c4bacc07e73f6dd78ec14757640657ba04d1c6)

Yes, it looks fine to me.
