### ISSUE TITLE
Computer can play Time Wipe without having permanents in play to return to hand

### ISSUE THREAD

**Issue by rickpress** [magefree/mage#6139]
The AI can play Timewipe without having to return a permanent to hand and remove all creatures when it needs to have a permanent in play to do so. 

Timewipe - https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=461150

Card Name:
Time Wipe
Mana Cost:

Converted Mana Cost:
5
Types:
Sorcery
Card Text:
Return a creature you control to its owner's hand, then destroy all creatures.
Flavor Text:
"To comprehend the full answer requires years of temporal study. In short, they were now never born in the first place."
—Teferi
Expansion:
 War of the Spark 
Rarity:
Rare
Card Number:
223
Artist:
Svetlin Velinov

![Screenshot (135)](https://user-images.githubusercontent.com/57946004/71733987-d0fd2300-2e85-11ea-8ddf-af9370b18c95.png)

**Comment by emerald000** [comment]
You don't need a creature to play Time Wipe. If you don't have one, you just destroy all creatures.
