### ISSUE TITLE
Murderous Rider didn't get shuffled into the deck upon death

### ISSUE THREAD

**Issue by Ebola16** [magefree/mage#6146]
Desert Twister destroyed my Murderous Rider. Murderous Rider remained in the graveyard but it should have been shuffled into my deck.

Possible duplicate of #6117

**Comment by jeffwadsworth** [comment]
Are you using a version of the software that includes the fix?  If not, you have to wait for the new release.

**Comment by jeffwadsworth** [comment]
I just tested the specific case mentioned by Ebola16 and it worked fine in the latest build.

**Comment by JayDi85** [comment]
Duplicate #6117, will work with next release
