### ISSUE TITLE
AI - AI returns Man'O'War to it's own hand instead of an opponents creature.

### ISSUE THREAD

**Issue by rickpress** [magefree/mage#6154]
![Screenshot (136)](https://user-images.githubusercontent.com/57946004/71898440-44f43f80-3194-11ea-854e-fc79757cec5f.png)
The AI will return Man O War to it's own hand rather than an opponents creature if the opponent has no creature in play. Wrong targeting. 

Card - Man 'O'War

**Comment by JayDi85** [comment]
That's ok -- you haven't any creatures so computer target own creature to return.

Also:

> If there are no other creatures on the battlefield when Man-o’-War enters the battlefield, its ability must target itself. (2019-06-14)
