### ISSUE TITLE
Aether Gust - AI plays it on it's own cards but for no benefit

### ISSUE THREAD

**Issue by rickpress** [magefree/mage#6159]
![Screenshot (137)](https://user-images.githubusercontent.com/57946004/72092569-8c71fb80-334d-11ea-9a62-68893cb3b484.png)

The AI seems to play Aether Gust on it's own cards for no real benefit - having a 4/4 on the battlefield then returning it to it's owners hand doesn't make sense would be better to target on the opponents creatures.

**Comment by jeffwadsworth** [comment]
It won't do that in the next release.

**Comment by rickpress** [comment]
You guys do such an amazing job on this mtgo clone. Can I ask is there any plans for adding chump blocking some way down the line with the AI?

**Comment by JayDi85** [comment]
@jeffwadsworth ups, I don't see your assign, outcome fixed in d7e123bbe6b08f2149a2367dc56da2987b1a9140.

@rickpress chump blocking is hard but possible to implement (issue #4485)
