### ISSUE TITLE
Suggest Linux settings for high performance on the wiki

### ISSUE THREAD

**Issue by resolritter** [magefree/mage#6161]
Hi! I've found that enabling some Java flags for the client makes the game run A LOT faster than what I was expecting. I don't see this being disclosed anywhere at all in this project, to the point where I had to wonder and Google for it on my own out of curiosity - I did not know if it was possible.

Example: `-Dsun.java2d.opengl=true` ([from this link](https://docs.oracle.com/javase/8/docs/technotes/guides/2d/flags.html#opengl)) enables OpenGL, which is disabled by default. That means GPU users on Linux are not benefitting from this, currently.

I am open to writing about what I found on those settings, but where should I put it? Can we create a "Performance tweaks" page on the wiki? Or would you prefer it in the README or something?

**Comment by JayDi85** [comment]
Good find!

It can be in readme after that:
![shot_200110_094833](https://user-images.githubusercontent.com/8344157/72129053-615bcc00-338e-11ea-9f7a-b195da19de70.png)

There are also [`-Dsun.java2d.d3d=false` for buggy drivers](https://github.com/magefree/mage/issues/4626#issuecomment-374640070) and memory settings.

You can make PR with that or I'll add it later.

**Comment by resolritter** [comment]
I am editing it right now and will submit a PR soon.
