### ISSUE TITLE
Mandate of peace

### ISSUE THREAD

**Issue by Akamayu** [magefree/mage#6162]
Looks like Mandate of peace is bugged, the game gets stuck in combat phase after it resolves.

**Comment by jeffwadsworth** [comment]
Works in my testing against the AI, but I haven't tested it again other human players.  Please try it again if you get the chance and report back.

**Comment by Akamayu** [comment]
Yes same issue against another human player, could be related to F-keys shortcuts/phases skipping ? Thanks for your help

**Comment by JayDi85** [comment]
Mandate of Peace uses `game.getStack().counter(`, but that call uses conter replace event (e.g. it will not removes spell that can't be countered). Maybe that's the reason. As example: `Leyline of Lifeforce` do not allows to counter creature spells and uses that replace event.

![shot_200111_100024](https://user-images.githubusercontent.com/8344157/72199720-3b4f2e00-3459-11ea-998e-e50619eb00ce.png)
