### ISSUE TITLE
Sagas aren't disappearing after they get enough lore counters.

### ISSUE THREAD

**Issue by JayDi85** [magefree/mage#6164]
From [reddit](https://www.reddit.com/r/XMage/comments/emojtw/bug_theros_beyond_death_cards/)

**Comment by jeffwadsworth** [comment]
Works for me.

**Comment by JayDi85** [comment]
Maybe related issue from server's feedback:
* [ ] The birth of meletis - The bith of meletis --> after III the enchantement no sacrify (Toshenko, 2020-01-09 18:11:10)

**Comment by jeffwadsworth** [comment]
Ok, The Birth of Meletis is definitely not working correctly.  Must be just certain Saga's.  Checking it out.

**Comment by varaghar** [comment]
Trying to implement King Narfi's Betrayal and it doesn't disappear after the third counter and I got here. Did you find anything?
