### ISSUE TITLE
Bug with the Escape ability in regards to cards with targeting

### ISSUE THREAD

**Issue by JayDi85** [magefree/mage#6166]
From [reddit](https://www.reddit.com/r/XMage/comments/emq5e2/bug_brain_freeze_with_escape/):

> When playing [[Brain Freeze]] from [[Underworld Breach]], game doesn't ask me to pick a target for Brain Freeze. As a result, no cards get milled.

![NCKCFUN](https://user-images.githubusercontent.com/8344157/72159752-807e4c00-33d6-11ea-87d9-bf569f560873.png)

**Comment by Tychology** [comment]
As far as I can tell, other instants and sorceries don't work as well:
![Unbenannt](https://user-images.githubusercontent.com/38350366/72170572-655d0d80-33d1-11ea-8f75-97702a2e0bb3.PNG)

On the other hand, Lion's Eye Diamond and Lotus Petal do work correctly

**Comment by JayDi85** [comment]
Maybe related issue from server's feedback:

* [ ] Underworld Breach - Spells cast with escape using underworld breach do not resolve. Spells that ask for targets give no opportunities to target. This may just be an issue with breach or it may be with all escape cards. I am nor sure. (crazymagicman, 2020-01-10 04:29:27)

**Comment by jeffwadsworth** [comment]
Tested and confirmed as a bug.
