### ISSUE TITLE
Seasoned Pyromancer trigger ability

### ISSUE THREAD

**Issue by RandleRaynes** [magefree/mage#6173]
Hi, just tried Seasoned Pyromancer and when it triggers and i press the "done" button a window opens and my land comes back to my hand and i´m in the next phase of the game. 
![Seasoned](https://user-images.githubusercontent.com/59766973/72204871-d6a5ca80-347c-11ea-922c-dffd9cc32a0a.JPG)

**Comment by JayDi85** [comment]
Fixed via 5f5d9046f9adde68eef6eb9f43fbffcd01fa5021

**Comment by RandleRaynes** [comment]
Ok thanks, so tomorrow at 08:00 MEZ when the servers are restarted, it will be ok?

**Comment by JayDi85** [comment]
Nope... You must wait next release/update, not server restart.

**Comment by RandleRaynes** [comment]
Oh, thanks!
