### ISSUE TITLE
Game Day Promo set inconsistent

### ISSUE THREAD

**Issue by luziferius** [magefree/mage#6180]
I’m currently matching promotional cards (~1000 missing images, according to the XMage image downloader) against Scryfall to fix missing card images. 

During the process, I noticed some inconsistencies with the Game Day promo set.

- `Suture Priest`:
  According to [Scryfall](https://scryfall.com/search?as=grid&order=released&q=%21%22Suture+Priest%22&unique=prints) and [cardmarket.com](https://www.cardmarket.com/en/Magic/Products/Singles/New-Phyrexia/Suture-Priest) there is no promotional printing of that card.
https://github.com/magefree/mage/blob/0c51e622f3376b229736de7a38881d6270f9ce91/Mage.Sets/src/mage/sets/GameDay.java#L74

- `Hall of Triumph`:
  There is this promo card, but it does not look like it really is a Game Day card. https://scryfall.com/card/thp3/162/hall-of-triumph
  https://github.com/magefree/mage/blob/0c51e622f3376b229736de7a38881d6270f9ce91/Mage.Sets/src/mage/sets/GameDay.java#L41

- These cards are listed as being Game Day promo cards by scryfall (https://scryfall.com/search?q=is%3AGameday), but not present in this set. I did a quick query in the client and it seems that these promotional printings are missing entirely.
https://scryfall.com/card/proe/49/deathless-angel
https://scryfall.com/card/pgrn/168/emmara-soul-of-the-accord
https://scryfall.com/card/pzen/35/emeria-angel
https://scryfall.com/card/prix/130/ghalta-primal-hunger
https://scryfall.com/card/pwwk/38/hada-freeblade
https://scryfall.com/card/pm10/28/mycoid-shepherd
https://scryfall.com/card/pwwk/39/kalastria-highborn
https://scryfall.com/card/pm10/29/naya-sojourners
https://scryfall.com/card/pzen/34/nissas-chosen
https://scryfall.com/card/proe/48/staggershock

**Comment by JayDi85** [comment]
Some old promo sets in xmage contains multiple sets/cards in one (from different releases/dates). It must be rewritten due scryfall sets structure (e.g. one xmage promo set per one scryfall promo set).

**Comment by luziferius** [comment]
I’ve noticed that. Is rewriting that even possible without breaking existing deck files?

**Comment by JayDi85** [comment]
Yes, it's possible. You must load deck by deck editor -- it will replace all missing cards with new one from newest set and show information window about changes. You can test that feature -- try to change card number or set in deck file by text editor and load that deck.
