### ISSUE TITLE
Soulfire Grand Master + Fire/Ice

### ISSUE THREAD

**Issue by jgalrito** [magefree/mage#6182]
Activated SGM ability, cast Fire/Ice and it didn't return to my hand. Would win me the match but I eventually timed out while arguing with my opponent for a rollback to try to do it again. Gotta love honest players.

**Comment by jeffwadsworth** [comment]
Split-cards are not being noted as instances of spells.

**Comment by LevelX2** [comment]
If an instant split-card spell or an instant adventure spell is cast from hand it goes back to hand  if it was not countered. 

Correct?
