### ISSUE TITLE
Suggestion: Sound for each main phase or when a new player turn begins

### ISSUE THREAD

**Issue by rickpress** [magefree/mage#6206]
Could we get a sound to play each time we hit each of the main phases or each time there is a new turn similar to how v4 of MTGO does it? 

Would help to keep track of the game rather than having to focus on the buttons on the right which are a bit small. Can these be made bigger or scalable?

**Comment by Zerrisx** [comment]
Does #6558 cover your needs, or would it be insufficient?

**Comment by Zerrisx** [comment]
Closing as fixed by #6558
