### ISSUE TITLE
Myriad Landscape Bug

### ISSUE THREAD

**Issue by jeffwadsworth** [magefree/mage#6208]
Myriad Landscape not able to fetch Wastes - Myriad landscape ability wouldn't let me fetch for 2 wastes

**Comment by ovenmittromney** [comment]
This is not a bug. Wastes do not have a land type, and can not be fetched.

**Comment by jeffwadsworth** [comment]
https://www.mtgsalvation.com/forums/magic-fundamentals/magic-rulings/magic-rulings-archives/668185-myriad-landscape-wastes
