### ISSUE TITLE
Catalyst Stone Bug

### ISSUE THREAD

**Issue by Zechr** [magefree/mage#6220]
When Catalyst Stone is in play and any flashback card is in your graveyard, the game crashes and resets to the beginning of the turn, saying something about a Java Null Pointer Exception.

**Comment by jeffwadsworth** [comment]
What specific card did you use?  Worked with another Flashback card for me.
![WorkHere](https://user-images.githubusercontent.com/1496996/72910687-7f1a2100-3cfe-11ea-9a5e-f2371e911cf4.jpg)

**Comment by Zechr** [comment]
I used Lingering Souls and Battle Screech.

**Comment by jeffwadsworth** [comment]
Ok, those cards caused the null pointer error.  Checking it out.
