### ISSUE TITLE
Essence of the Wild bug

### ISSUE THREAD

**Issue by jeffwadsworth** [magefree/mage#6222]
https://www.slightlymagic.net/forum/viewtopic.php?f=70&t=29223&p=241154#p241153
![bugged](https://user-images.githubusercontent.com/1496996/72943235-27e67180-3d3b-11ea-9870-360f783ce526.jpg)

**Comment by jeffwadsworth** [comment]
The 2nd token should have entered as a copy of the Essence of the Wild.  The 1st one entered the battlefield correctly.

**Comment by Tharkon** [comment]
I think it has something to do with the game not allowing copy-effects to be copied.
Which means the 2nd token enters the battlefield as a copy of the first, but does not copy the copy-effect that is on the first.
As long as you make sure the original Essence is the last to trigger this is fine, but this doesn't work if it is no longer on the battlefield.

**Comment by Zerrisx** [comment]
Pretty sure this was resolved by eecaa23, though god is the interface horrific.

![image](https://user-images.githubusercontent.com/59861365/87582186-aba46980-c69f-11ea-9102-0022629955c9.png)
