### ISSUE TITLE
Thassa's Oracle has the wrong rule text

### ISSUE THREAD

**Issue by jeffwadsworth** [magefree/mage#6223]
The correct text:

When Thassa's Oracle enters the battlefield, look at the top X cards of your library, where X is your devotion to blue. Put up to one of them on top of your library and the rest on the bottom of your library in a random order. If X is greater than or equal to the number of cards in your library, you win he game.

**Comment by JayDi85** [comment]
Fixed via 36b309df6bf09f445f83e87723f36eb899a95fa4
