### ISSUE TITLE
Hateful Eidolon bug

### ISSUE THREAD

**Issue by jeffwadsworth** [magefree/mage#6230]
If Hateful Eidolon is controlled by someone other than the owner, the draw effect fails.

**Comment by JayDi85** [comment]
That fix do nothing (just replace source to target effect). I tested eidolon and it works fine in current version. Real bug was fixed in #6205

**Comment by intuited** [comment]
> If Hateful Eidolon is controlled by someone other than the owner, the draw effect fails.
The issue I was having was a bit different than what's described here.  Hateful Eidolon was both owned and controlled by the same person.  The draw effect was failing when the creatures owned by a different player died (while being enchanted by Auras controlled by Hateful Eidolon's controller).

**Comment by JayDi85** [comment]
@intuited in latest v3 version all problems with Hateful Eidolon was fixed.

**Comment by intuited** [comment]
Can confirm.  Okay, I guess the top comment was just misphrased.
