### ISSUE TITLE
Layering bugs

### ISSUE THREAD

**Issue by jeffwadsworth** [magefree/mage#6236]
For example, the following cards are cast in this order:
Conspiracy -> pick Advisor for the creature type
Opalescence -> non-aura enchantments become creatures
Enchanted Evening -> all permanents become enchantments
Some lands in play, Serra Angel, etc
Conspiracy is dependent on Opalescence
Opalescence is dependent on Enchanted Evening
So regardless of the timestamp, the effects' order should be Enchanted Evening -> Opalescence -> Conspiracy
What should the board look like?  Check temp testing code in the attachment.
Right now, the dependency code works for only one interaction, so it fails in a case like this.
![ThisShouldBeCorrect](https://user-images.githubusercontent.com/1496996/73393194-e278f580-42a0-11ea-8eec-d4f9a2815af0.jpg)

**Comment by jeffwadsworth** [comment]
![Nice](https://user-images.githubusercontent.com/1496996/73675409-f5604100-4677-11ea-8d7e-2aabbd84667c.jpg)

**Comment by jeffwadsworth** [comment]
![worksSpreadingSeasHumility](https://user-images.githubusercontent.com/1496996/73677026-0d858f80-467b-11ea-9879-60f61808712b.jpg)

**Comment by jeffwadsworth** [comment]
![stormtideAndIllusionaryTerrain](https://user-images.githubusercontent.com/1496996/73688931-b8ee0e80-4692-11ea-81c5-4c5be828558d.jpg)

**Comment by JayDi85** [comment]
Please, if you rework layer system then try to add unit tests for important use cases -- there are useful checks like checkAbility, checkType, checkSubType, etc.

**Comment by JayDi85** [comment]
@jeffwadsworth can you confirm that all mana abilities must be added on layer TypeChangingEffects_4 (with land type adds), not in AbilityAddingRemovingEffects_6?

I found cards with different layers using -- are this cards need fixes? Example: [Sealock Monster](https://scryfall.com/card/mb1/481/sealock-monster)
* When Sealock Monster becomes monstrous, target land becomes an Island in addition to its other types.

![shot_200506_104932](https://user-images.githubusercontent.com/8344157/81145401-489fa380-8f87-11ea-8be9-6595c19d18a8.png)

**Comment by emerald000** [comment]
Basic land types abilities are intrinsic to the subtype and not added by the layer system. So when a land gains/loses a type, the ability immediately pops into existence.

305.6. The basic land types are Plains, Island, Swamp, Mountain, and Forest. If an object uses the words "basic land type," it's referring to one of these subtypes. An object with the land card type and a basic land type has the intrinsic ability "{T}: Add [mana symbol]," even if the text box doesn't actually contain that text or the object has no text box. For Plains, [mana symbol] is {W}; for Islands, {U}; for Swamps, {B}; for Mountains, {R}; and for Forests, {G}. See rule 107.4a. See also rule 605, "Mana Abilities."
