### ISSUE TITLE
Gadwick, the Wizened does not draw any card.

### ISSUE THREAD

**Issue by WickdDavid** [magefree/mage#6239]
As the title says, the pay X draw X interaction does not work.
The text says:

**Mana cost:** {X}{U}{U}{U}
"When Gadwick, the Wizened enters the battlefield, draw X cards. Whenever you cast a blue spell, tap target nonland permanent an opponent controls."

It simply does not work. 
Paying 1, 5, 1000, infinite mana does not give you any card.

**Comment by jeffwadsworth** [comment]
Try the beta server.

https://github.com/magefree/mage/commit/9deaa4c2270d6aacfe37b6a4b772b619db01d639

**Comment by WickdDavid** [comment]
Seems not working there as well.
![gadwick](https://user-images.githubusercontent.com/18442485/73501320-c753d600-43c5-11ea-9778-25dd95f67d9a.png)

**Comment by JayDi85** [comment]
It's not on beta, wait next release for fix.
