### ISSUE TITLE
Feaster of Fools devour ability not triggering Blood Artist type triggers properly

### ISSUE THREAD

**Issue by vonuberoydawg** [magefree/mage#6254]
After casting Feaster of Fools and using the Devour ability, causing me to have the option to sacrifice creatures, while sacrificing Zulaport Cutthroat and Cruel Celebrant the (when this creature or other creatures you control Die) triggers are not triggering properly, however, some other triggers are, such as Stitcher's supplier, still triggering its self mill effect.

Example: I cast Feaster of Fools convoking 5 creatures and tapping one mana.  Feaster of fools enters the Battlefield and I choose to Devour(2) all 5 creatures, A Stitcher's Supplier, a Viscera Seer, 2 Zulaport Cutthroats and a Cruel Celebrant.  The Stitcher's supplier triggers, causing me to place the top 3 cards of my library into my graveyard, but there is was no drain trigger, which should have triggered all 3 of those effects 5 times each, for a total of 15 damage to the opponent and a life gain of 15 for me.  Though the Feaster of fools did get all 5(x2) +1/+1 counters and resulted in a proper 13/13 power/toughness.  Any help would be appreciated, as I have experienced this issue on multiple occasions with various board states.

**Comment by JayDi85** [comment]
Fixed via 85083a4433a25b07fd4b9340b1c195cc8e32f426

Topic's use case now works fine:

![shot_200619_214431](https://user-images.githubusercontent.com/8344157/85165820-74e15c00-b277-11ea-9515-70edf006dcc3.png)
![shot_200619_215140](https://user-images.githubusercontent.com/8344157/85165839-790d7980-b277-11ea-8b2f-b7b280372384.png)
