### ISSUE TITLE
Replace "ParameterizedTypeImpl" Java class (not present in OpenJDK 11)

### ISSUE THREAD

**Issue by allentiak** [magefree/mage#6256]
Part of #6197

The problematic class is:
`mage.watchers.Watcher` (uses the deleted class `sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl`)

The problematic commit is https://github.com/magefree/mage/commit/1a8723697ec547f4c9659dc61a0dc876f05dcf90

According to https://winterbe.com/posts/2018/08/29/migrate-maven-projects-to-java-11-jigsaw/, it could be that PrameterizedTypeImpl could be well replaced by its interface, ParameterizedType. Finally, according to [the official Migration Guide](https://docs.oracle.com/en/java/javase/11/docs/api/jdk.javadoc/jdk/javadoc/doclet/package-summary.html#migration), the replacement for this class is javax.lang.model.type.DeclaredType.

@ingmargoudt Whereas I am not very experienced in this, the class switch does not seem too difficult. I could try implementing the switch myself, if I can get some mentoring.

```
% jdeps --jdk-internals mage-1.4.42.jar
mage-1.4.42.jar -> java.base
   mage.watchers.Watcher                              -> sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl JDK internal API (java.base)

Warning: JDK internal APIs are unsupported and private to JDK implementation that are
subject to be removed or changed incompatibly and could break your application.
Please modify your code to eliminate dependence on any JDK internal APIs.
For the most recent update on JDK internal API replacements, please check:
https://wiki.openjdk.java.net/display/JDK8/Java+Dependency+Analysis+Tool

JDK Internal API                         Suggested Replacement
----------------                         ---------------------
sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl Removed. See http://openjdk.java.net/jeps/260
```

**Comment by JayDi85** [comment]
Maybe @ingmargoudt can help with code update in watchers (#5690).

**Comment by ingmargoudt** [comment]
@allentiak @JayDi85 I am looking into it right now :)

**Comment by allentiak** [comment]
@ingmargoudt Any news regarding this?

**Comment by allentiak** [comment]
@ingmargoudt Ping?

**Comment by ingmargoudt** [comment]
Hi, I am sorry, I started to look at it but could not find a solution yet to migrate this, and I could not find information on DeclaredType. Feel free to make the switch yourself. I can try to help you out.

@allentiak

**Comment by allentiak** [comment]
@ingmargoudt Thanks for your reply.
Unfortunately, I am currently working on another project... I may return to this later on.

**Comment by jzinedine** [comment]
Thank you for the information shared on this ticket! My problem got resolved. 👍🏼
