### ISSUE TITLE
UI breaks when interacting with a card popup

### ISSUE THREAD

**Issue by ag0r** [magefree/mage#6266]
When playing against another player (this didn't seem to happen playing against AI) any time a popup window displays, for example after searching the deck for a card, the UI breaks spectacularly after interacting with that window in any way other than moving or minimizing it. Closing the window, hovering over the card in the window, clicking the card in the window... All break the UI. After this breakage happens, any time the mouse moves over an interactive item on screen the whole UI redraws relative to the position of that item. Technically the game is still playable at this point; clicking things still works if you can find them.

**Comment by JayDi85** [comment]
1. Delete logs file `\xmage\mage-client\mageclient.log`;
2. Run game and reproduce that bug;
3. Upload logs to https://pastebin.com/ or send me on email: jaydi85@gmail.com

It can be:
1. Errors with images (broken archives -- find and delete all zero size files from `\xmage\mage-client\plugins\images` folder);
2. Old graphic card drivers (try to update it and/or run client with extra command `-Dsun.java2d.d3d=false`, look [here](https://github.com/magefree/mage/issues/1514#issuecomment-368220596)).

**Comment by ag0r** [comment]
I am marking this as closed because after following the steps above I was no longer able to reproduce the issue. I'm unfortunately not sure which of the steps resolved it though.
