### ISSUE TITLE
The card "Faces of the Past" does not prompt for user choice, always chooses to tap all creatures that share a type

### ISSUE THREAD

**Issue by ag0r** [magefree/mage#6277]
Link to card for convenience: https://scryfall.com/card/scg/35/faces-of-the-past

Any time this card activates it chooses to tap all creatures that share a type, there is no prompt for a choice.

**Comment by jeffwadsworth** [comment]
That is because if you choose no on the first option, it automatically does the second option.

**Comment by ag0r** [comment]
There is no option to choose at all, it just automatically taps all creatures that share a type. The only prompt is the standard "Done" button for finishing the stack.

**Comment by ag0r** [comment]
Attaching screenshot of the card on the stack with no prompt to select which option to choose, followed by another screenshot after pressing done with all wizards tapped. Is there anything else I can do to help track the issue?

![image](https://user-images.githubusercontent.com/11788442/74208382-f0d3f380-4c48-11ea-9ff5-68a6d00cda67.png)



![image](https://user-images.githubusercontent.com/11788442/74208420-1d880b00-4c49-11ea-8286-d6196496747b.png)

**Comment by jeffwadsworth** [comment]
![TriggeredOne](https://user-images.githubusercontent.com/1496996/74244252-bb5df300-4ca6-11ea-9029-fe9c1b1d48d2.jpg)
![TriggeredTwo](https://user-images.githubusercontent.com/1496996/74244270-c44ec480-4ca6-11ea-9fb4-4a95519cf24b.jpg)
