### ISSUE TITLE
Stinging Lionfish

### ISSUE THREAD

**Issue by DominusMaximus** [magefree/mage#6279]
1.4.42.dev_2020-02-01_10-01

Currently the Lionfish is able to target lands with its triggered ability. It should only be able to target nonland permanents.

**Comment by jeffwadsworth** [comment]
It works fine for me.

**Comment by DominusMaximus** [comment]
![Stinging Lionfish](https://user-images.githubusercontent.com/21368033/74389902-b6479380-4dcd-11ea-8dee-402eeb76b4c3.jpg)

Here I've targeted the 1/5 with a Stern Dismissal during my opponent's turn, triggering the Lionfish. All lands are highlighted as valid targets. If I choose any one of them, the trigger will either tap or untap it.

**Comment by JayDi85** [comment]
Was fixed by #6255
