### ISSUE TITLE
Cost-increasers (Thalia, God-Phaoroh's Statue, Grand Arbiter Augustine IV, etc) cause games to lost sync and crash

### ISSUE THREAD

**Issue by Mekkiss** [magefree/mage#6284]
I've noticed that shortly after having these cards resolve, the game will hang, with no player having priority.

**Comment by AncientSion** [comment]
can confirm, happened in two games where i had true thalia out.
Great update, loving it.

**Comment by JayDi85** [comment]
Fixed via bd0974eecd7c5c1948c8dba704610e286c03102f
