### ISSUE TITLE
Add a personal blacklist

### ISSUE THREAD

**Issue by AncientSion** [magefree/mage#6287]
I play a lot and so far i have some "members" on the server whom i really dont want to play with. Some use bad language, some refuse to rollback upon hitting the wrong stop.

I really really want to have a blacklist where i can put certain usernames and those guys are unable to join my public games.

**Comment by JayDi85** [comment]
It's already implemented. Use `\ignore` command in main lobby's chat (see hint about that command on startup). If you add player to ignore list then he can't join your new games and you can't see his messages.
