### ISSUE TITLE
Sunlit Hoplite

### ISSUE THREAD

**Issue by DominusMaximus** [magefree/mage#6288]
1.4.42.dev_2020-02-15_12-26

The Hoplite wasn't receiving the +1/+0 buff even though I controlled an Elspeth, Undaunted Hero. The Hoplite's card hint window also recognized I controlled an Elspeth planeswalker.

**Comment by jeffwadsworth** [comment]
![works](https://user-images.githubusercontent.com/1496996/74884450-d381e200-5338-11ea-82b7-e5b384dcb13a.jpg)

**Comment by DominusMaximus** [comment]
![01](https://user-images.githubusercontent.com/21368033/74886037-0fbb3f80-5345-11ea-9988-4c401e40b554.jpg)
![02](https://user-images.githubusercontent.com/21368033/74886042-13e75d00-5345-11ea-9a25-0850082d89bb.jpg)

**Comment by DominusMaximus** [comment]
Tested the issue in the latest Beta release (1.4.42.dev_2020-02-21_08-48) and it still occurs.

**Comment by JayDi85** [comment]
There are possible another permanent or effect with -1/0 applied to Sunlit Hoplite.

**Comment by DominusMaximus** [comment]
To test I made a deck with only Plains, Hoplites and Elspeths and played the deck on both sides:

![hoplite](https://user-images.githubusercontent.com/21368033/75049659-97fe2980-5498-11ea-9dc4-cb15b067d6f7.jpg)

**Comment by JayDi85** [comment]
Must be fixed with next update by 3047a8bd76e2b42870af004dfc70afeffc893140
