### ISSUE TITLE
UI: mana pool value hides on 10+

### ISSUE THREAD

**Issue by JayDi85** [magefree/mage#6290]
From [reddit](https://www.reddit.com/r/XMage/comments/f775a4/mana_count_cut_off/):

> I have noticed that the mana pool gets cut off when you go above a single digit in any one color, is there a way to fix this?

![a85286b3283d56f2c6f3e8c2d8a6f2be](https://user-images.githubusercontent.com/8344157/75088311-e5e06380-5564-11ea-850a-2711f8c7d162.png)

**Comment by LevelX2** [comment]
Seems to be fixed.

Or are there settings that infuence the size of the player status are?

![grafik](https://user-images.githubusercontent.com/2066790/84503842-3538d400-acbb-11ea-9c0a-a3ff857ddf18.png)
