### ISSUE TITLE
beta, ai server issue

### ISSUE THREAD

**Issue by crapsoda13** [magefree/mage#6294]
Trying to start a game on the beta, ai server to test some decks against the computer. When I first went to start a new game I got an error that read "server error: Card not found - Asceticism". So removed that card and replaced it with a land thinking that would resolve my issue. Now I still get a "server error: Card not found" but this time for Beast Whisperer. I have a feeling if I remove that then it will have another card that it's unable to find. So I am unable to even start a new game for my tests

**Comment by JayDi85** [comment]
Missing card is standard error for broken server (it need restart).

Beta restarted and works fine now.
