### ISSUE TITLE
[Anger of the Gods] and death triggers [Zulaport Cutthroat]

### ISSUE THREAD

**Issue by drogskol79** [magefree/mage#6295]
When [Anger of the Gods] was played by the opponent, the creatures I had in play were all exiled, however the death triggers of [Zulaport Cutthroat] still went through (I gained life, they lost life).
The death of my creatures should have been replaced with exiling instead.

**Comment by jeffwadsworth** [comment]
![works](https://user-images.githubusercontent.com/1496996/75164025-c45ab580-56e5-11ea-95da-ba8b063867c8.jpg)
Works when cast by the controller.  Testing when cast by the opponent next.

**Comment by LevelX2** [comment]
I was not able to reproce a problem.
