### ISSUE TITLE
Palisade Giants and replacement effects

### ISSUE THREAD

**Issue by jeffwadsworth** [magefree/mage#6298]
From slightlymagic:

when you have two Palisade Giants in play and your opponent deals you damage, the damage is applied to both of them rather than allowing you to choose which replacement effect applies (as it should). I experienced this multiple times in games vs the A.I.

**Comment by jeffwadsworth** [comment]
This is due to some "convenience" code that dis-allows the player from choosing a replacement effect if multiple versions of the same type fire at the same time.  There is already a preference setting that automatically chooses for the player in the event of multiple replacement effects.
Check from line 351 of HumanPlayer.java

**Comment by LevelX2** [comment]
At least the damage was applied randomly and it was not possible to select a specific Giant. But there was no redundant applying.
Now the object id is added to the select text for the replacement effect and so you can identify which replacement effect belongs to which permanent if they have the same name.
