### ISSUE TITLE
While working on my deck IE trying to manually add these cards the engine crashed

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [magefree/mage#6306]
[Navigation In The Dark.txt](https://github.com/magefree/mage/files/4259236/Navigation.In.The.Dark.txt)

Some realavent information - I afked and came back. More realavent information - my java usage is set to 4G by the way. 

Client -Xms256m -Xmx4G -XX:MaxPermSize=384m -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled

Server -Xms256M -Xmx4G -XX:MaxPermSize=384m

**Comment by P3rf3ctXZer0** [comment]
Oh yeah and I tried to import an exported mtgarena deck too before afking

**Comment by spjspj** [comment]
Clean it up thusly and try importing it again.
```
4 Golgari Guildgate
4 Jungle Hollow
10 Swamp
10 Forest
4 Vampire of the Dire Moon
1 Moss Viper
1 Charity Extractor
1 Giant Growth
1 Savage Gorger
2 Knight of the Ebon Legion
1 Duress
1 Bloodthirsty Aerialist
1 Mantle of the Wolf
1 Doom Whisperer
1 Voracious Hydra
4 Season of Growth
1 Vivien, Arkbow Ranger
2 Gravewaker
2 Oakenform
1 Arasta of the Endless Web
1 Shadowspear
1 Mirror Shield
1 Field of Ruin
1 Hydra's Growth
1 Gate Colossus
1 Roving Keep
1 Ugin, the Ineffable
1 Ferocious Pup
1 Root Snare
1 Scuttlegator

Sideboard
1 Inspire Awe
1 Gargos, Vicious Watcher
1 Aggressive Mammoth
1 Gnarlback Rhino
1 Prized Unicorn
1 Feral Invocation
1 Generous Stray
1 Gift of Paradise
```

**Comment by P3rf3ctXZer0** [comment]
thank you.

**Comment by spjspj** [comment]
aka> Import, From Clipboard (new deck) after selecting and copying to your clipboard.

**Comment by spjspj** [comment]
:
