### ISSUE TITLE
Can't spend mana of Thran Turbine on Cycling

### ISSUE THREAD

**Issue by Mifune-MTG** [magefree/mage#6307]
I don't know if this is the right place and form to report this, but i ran into the following problem:

I'm running **Thran Turbine** in a deck with **Nimble Obstructionist**, **Fetid Pools**, **Ancient Excavation** and **Decree of Pain**.
Whenever i'm in my upkeep and add the mana to my pool i'm not able to spend it on any of these cycling abilities. Other non-cycling activated abilities of creatures and artifacts have worked flawlessly so far.
Would be great to see a fix for this soon-ish.

Keep up the great work!

Regards, Mifune

**Comment by jeffwadsworth** [comment]
I can't reproduce this.  Works fine in my build.

**Comment by jeffwadsworth** [comment]
Thran Turbine is coded incorrectly.
