### ISSUE TITLE
Declare Blockers step skips on "STOP skip on any blocker" option disabled

### ISSUE THREAD

**Issue by DominusMaximus** [magefree/mage#6308]
1.4.42.dev_2020-02-21_08-48

If the setting that reads "STOP skips on declare blockers if ANY blockers are available" is unchecked, XMage will skip the beginning of the declare blockers step even if there are no stops in place and there are blockers available. When the defending player manually passes priority during the declare attackers step, the game will skip straight to the spell portion of the declare blockers step.

**Comment by JayDi85** [comment]
That's correct and it's about combination skip button and available blockers:
* if STOP option enabled then you will be stopped on pre and blockers steps ALL the time (even with activated skip buttons);
* if STOP option disabled then you will be stopped ONLY with skip button off;

**Comment by DominusMaximus** [comment]
That's what I understood, but what I'm saying is that with that STOP option disabled (your 2nd example), XMage _always_ skips. In my case all skip buttons were off and blockers were available, but it still skips. I rollbacked several times to test.

**Comment by DominusMaximus** [comment]
This is the setup I was testing: 
![settings](https://user-images.githubusercontent.com/21368033/75563409-4e718980-5a18-11ea-8262-9b2fe0a1ad30.jpg)

**Comment by JayDi85** [comment]
All works fine -- defending player gets priority on declare attackers and declare blockers steps. Use DONE button to go to next step, not skip buttons. I think there were cards with can't be blocked, can't block, must be blocked by 2+ creatures and etc.

With defender creature priorities:
![shot_200228_200224](https://user-images.githubusercontent.com/8344157/75564637-ee093900-5a65-11ea-8872-cc8984b5a49a.png)
![shot_200228_200258](https://user-images.githubusercontent.com/8344157/75564650-f2cded00-5a65-11ea-8d8b-801f94e5776d.png)

With instant priorities:
![shot_200228_200444](https://user-images.githubusercontent.com/8344157/75564691-011c0900-5a66-11ea-998b-d2b4e069031f.png)
![shot_200228_200517](https://user-images.githubusercontent.com/8344157/75564699-05482680-5a66-11ea-8451-da0e26bb695a.png)

**Comment by DominusMaximus** [comment]
I think your example above shows my issue. Were you able to choose the Grizzly Bears as a blocker? Your first picture shows the step: "Play instants and activated abilities. Computer's Turn / Declare Attackers." And your next image jumps right into  "**Play instants and activated abilities**. Computer's Turn / Declare Blockers." It's skipping the part where you choose blockers, before you are able to play instants and activate abilities.

**Comment by DominusMaximus** [comment]
Here's a GIF against a computer player. I'm unable to block the Grizzly Bears because it skips that part and goes right into the instants and activated abilities part of the blockers step.

![combat block](https://user-images.githubusercontent.com/21368033/75576626-550afb80-5a2e-11ea-8cc3-33fabe96d7ee.gif)

**Comment by JayDi85** [comment]
Thanks, I've got what are you talking about.

**Comment by JayDi85** [comment]
Fixed via ca9542d3deae9323f9bb5e429b4f430c62eaecac
