### ISSUE TITLE
Custom Card Banlist

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [magefree/mage#6309]
https://imgur.com/hQK8sfx

this occured.

https://imgur.com/sZH04YO

I was defeated in 3 turns - I would like a custom banlist because this is whack.

**Comment by spjspj** [comment]
Ermm, this is really unspecific.  You can create custom cubes for example.  The formats presented in xmage are pretty much how WoTC have set them up.

**Comment by P3rf3ctXZer0** [comment]
When I make a room I want to be able to have custom banned cards using the deck editor export feature.

**Comment by P3rf3ctXZer0** [comment]
Basically a text file that named - BANNEDCARDS and basically if a user joins the room it says "This room does not allow the following cards. Please remove them for your deck and rejoin."

**Comment by JayDi85** [comment]
It's the legacy format -- it have many fast win conditions or combos. You can find feature request about black and white cards list with more details here #4256
