### ISSUE TITLE
Atris, Oracle of Half-Truths AI issue

### ISSUE THREAD

**Issue by jeffwadsworth** [magefree/mage#6310]
From slightlymagic:
Atris, Oracle of Half-Truths not showing cards on ETB.
Only "Face Down" option brings cards to hand.
"Face Up" sends the 3 unknown cards to graveyard.

**Comment by Zerrisx** [comment]
This isn't a bug, though the UI is a bit confusing - the AI always puts all three cards in the face down pile, so you never see anything.  If you choose said face down pile you get the three cards.  If you choose the face up pile (which is empty), you get nothing.  Atris doesn't show the cards beforehand in any circumstance, unlike Fact or Fiction.
