### ISSUE TITLE
Should "Enters the battlefield wtih/as" go on the stack?

### ISSUE THREAD

**Issue by sinsedrix** [magefree/mage#6324]
When a permanent enter the battlefield tapped or with a counter, should it goes on the stack?
I don't understand why I need to choose between multiple effects of this type.
For example, with Lanowar Reborn, I shouldn't have to choose between "Enter the battlefield tapped" and "Enters the battlefied with a +1/+1 counter" as they are not triggered and are not concurrent.

Any explanation / fix  welcome.

**Comment by emerald000** [comment]
When multiple replacement effects apply to the same event, the controller of the affected permanent has to choose the order of application of replacement effects. It usually has no impact for Llanowar Reborn as the replacement effects don't affect each other, but it can matter in other cases.
