### ISSUE TITLE
Inferno Titan issue with the AI

### ISSUE THREAD

**Issue by copperfield42** [magefree/mage#6330]
After several instances of games against the AI that for no apparent reason as soon as it arrive at its main phase the game freeze over alongside my whole machine and devouring all my memory too, it finally happen that one game that almost freezes could resolve normally revealing the card that the AI was trying to play: _Inferno Titan_.

Therefore I arrive to the conclusion that _Inferno Titan_ was the cause of this problem.

I guess is that the part were you can choose to divide its damage as you choose that makes it particularly hard for the AI to choose in multiplayer.

In this last instance, a 4 player game of 3 AI and myself, the board looked like this:
Is around turn 4 or 5
I have a 2/4
AI 1 have no creatures
AI 2 have a 2/2
AI 3 after a while and I'm about to kill the server, finally resolve a _Inferno Titan_ and choosing to kill the 2/2 and deal the last point to me.

All other instances the board was more complex

**Comment by JayDi85** [comment]
Off-topic: you can limit memory usage by local server -- use same memory startup command as client does (`-Xmx512M` -- see main menu hint over memory stats for instructions). That's can protect your machine from freeze on too much memory usage.

**Comment by JayDi85** [comment]
Inferno Titan works fine in current version with AI (maybe fix #6330 helped). Additional tests added by 796c8fb22e834cc11bd00d7324dc31cc1b96d44c.

**Comment by copperfield42** [comment]
cool, I look forward to test it in the next beta

**Comment by JayDi85** [comment]
@copperfield42 beta updated to latest version

**Comment by copperfield42** [comment]
@JayDi85 it didn't work, the game still freezes over and/or get several disconnected errors while freezes and put all cpu to 100%

![001 freeze game](https://user-images.githubusercontent.com/4504719/103100376-a5200380-45e8-11eb-8b37-44d2f36f729a.PNG)

this one all AI are using the same deck, it also freeze for what I assume is that at least one of them have it in hand


![001 freeze game 2](https://user-images.githubusercontent.com/4504719/103100344-80c42700-45e8-11eb-96bb-e5a156395ed5.PNG)

In this one, one of the AI try to cast it and then freeze.

If I give the all the AI the same deck but without the titan there is no problem.


The next 2 I'm the one trying to cast it

![001 freeze game 3](https://user-images.githubusercontent.com/4504719/103100354-8cafe900-45e8-11eb-85fa-bad05a2c2dd2.PNG) 
![001 freeze game 4](https://user-images.githubusercontent.com/4504719/103100366-99ccd800-45e8-11eb-908c-ee35171c5aeb.PNG)

Although there was one or two games were I could use Inferno Titan with no problem, on one of the first games with this beta version in fact, but playing some more I start to get those freeze games...

**Comment by JayDi85** [comment]
There were a problem with cards that uses target amount. 

AI generated too much target variations for games simulations (tries to target each permanent with each possible amount and calcs result). So it freeze the game with big amount of permanents on battlefield. Well, it takes 20+ seconds to unfreeze, depends on AI skill level -- you can try to set skill level to a minimum as workaround.

It was fixed today by 64e948e4b382a5db3725c2983b63446bfa24f98d. Also I updated the beta server to that fix now

**Comment by copperfield42** [comment]
cool, I look forward to test it it in the new beta

**Comment by copperfield42** [comment]
I still got one freeze game
![001 game freeze](https://user-images.githubusercontent.com/4504719/103190082-d1b47380-48a5-11eb-81c7-23691051e0c9.PNG)

but overall now it work much better, I got a couple of game that looked that they were going to freeze where either I or the AI played Inferno Titan 

![001 game freeze 2](https://user-images.githubusercontent.com/4504719/103190059-bfd2d080-48a5-11eb-9e4a-97e732e784b2.PNG)
![001 game freeze 2 no](https://user-images.githubusercontent.com/4504719/103190044-b0ec1e00-48a5-11eb-98e9-57a728b3835f.PNG)

but after a disconnect error they proceeded normally.
