### ISSUE TITLE
Using Icon of Ancestry makes owner not draw on draw step.

### ISSUE THREAD

**Issue by Fubs** [magefree/mage#6333]
Using Icon of Ancestry's ability makes owner not draw on their draw step for the rest of the game. Happened to me during a match, and I was able to reproduce it on local server. The cards in library counter goes down by 1 on the next draw step like it should, but the card is not put into hand. Also, if you use the ability but fail to find a creature of the right type, the bug does not happen and you will draw normally.

![screenshot1](https://user-images.githubusercontent.com/17634481/76158141-3664ce80-60d8-11ea-8aa3-827ea09af3b1.png)

![screenshot2](https://user-images.githubusercontent.com/17634481/76158154-51374300-60d8-11ea-9da4-cca0ded98679.png)

**Comment by jeffwadsworth** [comment]
Worked fine for me.  Tried multiple hands as well.

**Comment by SpeedProg** [comment]
This actually happens consistently for me 30s video of it https://youtu.be/S9iFYoldI-U
The Amount of cards on the deck does not change when you get the Card into your hand from Icon of Ancestry so I assume it is actually still on the top of your deck and then you draw it ....

**Comment by SpeedProg** [comment]
I am gonna try my hand at fixing this. The code actually doesn't remove the card from the library.
And also it codes it's own effect while it could probably just use LookLibraryAndPickControllerEffect like Adventurous Impulse.
