### ISSUE TITLE
AI: Shielded by Faith is attached to any creature that enters the battlefield

### ISSUE THREAD

**Issue by Ebola16** [magefree/mage#6335]
Shielded by Faith is attached to any creature that enters the battlefield (even opponent's creatures). Perhaps Shielded by Faith's AI code should be restricted to only the controller's creatures?

**Comment by Zerrisx** [comment]
Duplicate of #6838

**Comment by Ebola16** [comment]
Since the mass issue-closing has been partially undone and this issue still occurs, please re-open.
