### ISSUE TITLE
AI: Player targets its own creatures with Control Magic

### ISSUE THREAD

**Issue by Ebola16** [magefree/mage#6340]
Opponent creatures should be targeted with Control Magic.

**Comment by jeffwadsworth** [comment]
Yes, I noticed this while testing another card.  A simple fix.

**Comment by JayDi85** [comment]
Not so easy, see `TargetOpponentsChoicePermanent`. I'm looking at "broken" test.

**Comment by JayDi85** [comment]
AI's gain control was broken by my January commit bb59cedbd9d3242eb81bfb7bf93ce7930261d0b1. Fixed by 14ddb6eb289e9ab1bdf1af2e97579bce7c892ae3

**Comment by jeffwadsworth** [comment]
Yes, I noticed that.
