### ISSUE TITLE
Cascade and escape

### ISSUE THREAD

**Issue by nev01b** [magefree/mage#6342]
Example: _Bloodbraid Elf_ can get _Kroxa, Titan of Death's Hunger_ on a table for its escape costs (needs only to exile 5 cards from graveyard). 

As far as I know it should not be possible because cascade casts spell from exile and not from graveyard.

**Comment by boulderelf** [comment]
![image](https://user-images.githubusercontent.com/80125225/110161663-549e0100-7df6-11eb-91ef-81f7b69eb4e4.png)
 can verify

**Comment by JayDi85** [comment]
Fixed with 6bc5a00e8ac604bd98e927bd88f03486830126a8
