### ISSUE TITLE
Biomancer's Familiar with Finale of Devastation

### ISSUE THREAD

**Issue by DominusMaximus** [magefree/mage#6343]
1.4.42.dev_2020-03-09_11-17

I had a Biomancer's Familiar on the battlefield and cast a Finale of Devastation for x = 2. I chose an Incubation Druid and encountered a window with the following error as soon as I confirmed the choice:

`Game exception occurred: java.lang.NumberFormatException: null
Server version: 1.4.42V7-beta1 (build: 2020-03-09 11:17)
java.lang.Integer.parseInt(Integer.java:542)
java.lang.Integer.parseInt(Integer.java:615)
mage.cards.b.BiomancersFamiliarCostReductionEffect.apply(BiomancersFamiliar.java:100)
mage.abilities.effects.ContinuousEffects.costModification(ContinuousEffects.java:660)
mage.players.PlayerImpl.canPlay(PlayerImpl.java:3059)
mage.players.PlayerImpl.getPlayableFromNonHandCardSingle(PlayerImpl.java:3349)
mage.players.PlayerImpl.getPlayableFromNonHandCardAll(PlayerImpl.java:3263)
mage.players.PlayerImpl.getPlayable(PlayerImpl.java:3445)
mage.players.PlayerImpl.getPlayableObjects(PlayerImpl.java:3528)
mage.server.game.GameSessionPlayer.getGameView(GameSessionPlayer.java:192)
mage.server.game.GameSessionWatcher.lambda$update$0(GameSessionWatcher.java:52)
java.util.Optional.ifPresent(Optional.java:159)
mage.server.game.GameSessionWatcher.update(GameSessionWatcher.java:52)
mage.server.game.GameController.updateGame(GameController.java:758)
mage.server.game.GameController.lambda$init$3aa0d15c$1(GameController.java:120)
mage.game.events.EventDispatcher.fireEvent(EventDispatcher.java:28)
mage.game.events.TableEventSource.fireTableEvent(TableEventSource.java:39)
mage.game.GameImpl.fireUpdatePlayersEvent(GameImpl.java:2387)
mage.game.GameImpl.playPriority(GameImpl.java:1317)
mage.game.turn.Step.priority(Step.java:61)
mage.game.turn.Phase.playStep(Phase.java:184)
mage.game.turn.Phase.play(Phase.java:89)
mage.game.turn.Turn.play(Turn.java:126)
mage.game.GameImpl.playTurn(GameImpl.java:889)
mage.game.GameImpl.play(GameImpl.java:798)
mage.game.GameImpl.start(GameImpl.java:762)
mage.server.game.GameWorker.call(GameWorker.java:34)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)`

The game rolled back to the board state right before the play. I tested Finale with other creatures and the error also occurs when choosing a Growth-Chamber Guardian, Passwall Adept or Spectral Sailor. I thought this meant the error would always occur when choosing a creature with an activated ability, however the error doesn't occur when choosing a Gilded Goose or another Biomancer's Familiar. Maybe this means the activated ability needs to have at least 2 colorless in its cost, or not have the tap symbol.

**Comment by LevelX2** [comment]
Fixed with 1ef8aeb7ba688d05174c9ccc629e8398f801856c.
