### ISSUE TITLE
Inconsistent collector numbers of double-faced cards in the code

### ISSUE THREAD

**Issue by luziferius** [magefree/mage#6346]
The collector numbers of double-faced cards are inconsistent. There are at least three different styles. What is the current "best practice"?

Core Set 2019: Both faces have the same number:
https://github.com/magefree/mage/blob/63df5d89a4b1bf109a751ed20fa8b1731c32b6a5/Mage.Sets/src/mage/sets/CoreSet2019.java#L226-L227

Same with Ixalan:
https://github.com/magefree/mage/blob/63df5d89a4b1bf109a751ed20fa8b1731c32b6a5/Mage.Sets/src/mage/sets/Ixalan.java#L48 https://github.com/magefree/mage/blob/63df5d89a4b1bf109a751ed20fa8b1731c32b6a5/Mage.Sets/src/mage/sets/Ixalan.java#L247

Rivals of Ixalan: Uses `<number>a` and `<number>b`
https://github.com/magefree/mage/blob/63df5d89a4b1bf109a751ed20fa8b1731c32b6a5/Mage.Sets/src/mage/sets/RivalsOfIxalan.java#L106-L107

Innistrad: Uses offset `<number>+1000` for the back
https://github.com/magefree/mage/blob/63df5d89a4b1bf109a751ed20fa8b1731c32b6a5/Mage.Sets/src/mage/sets/Innistrad.java#L175-L176

The Wiki says that the Innistrad way is correct:
https://github.com/magefree/mage/wiki/Implementing-Double-Faced-Cards
But then we now have Mystery Boosters, which contains > 1000 cards, causing this workaround to fail and become ambiguous. The offset should have been 1 million or 1 billion to be safe.

**Comment by JayDi85** [comment]
Current card number style for double faced cards: use same number for both sides. All sets uses it now.
