### ISSUE TITLE
A few issues i've caught

### ISSUE THREAD

**Issue by FangTheBrave** [magefree/mage#6349]
1. Divine Visitation turning Smothering Tithe treasure tokens into angels.
2. Rienne, Angel of Rebirth not triggering if she dies at the same time as other creatures, if you send her to the command zone. It works fine if you send her to the graveyard.

**Comment by luziferius** [comment]
>     1. Divine Visitation turning Smothering Tithe treasure tokens into angels.

Hmm…
![Divine Visitation](https://user-images.githubusercontent.com/2143820/77792775-3fa6e280-7069-11ea-95f3-c9ac44da6af0.png)

**Comment by LevelX2** [comment]
1. not reproducable.

2. Behaviour is correct according the current rules.
It will be changed soon with M21 rule cahnges.
https://www.mtgsalvation.com/forums/magic-fundamentals/the-rumor-mill/817641-edh-rule-change-when-m21-hits
But that needs an own issue.
