### ISSUE TITLE
Yarok, the Desecrated: Copy of Copy doesn't trigger cause additional triggers

### ISSUE THREAD

**Issue by propri** [magefree/mage#6351]
I have a Yarok (my commander) on the field, and a Spark Double copying Yarok. A Clone copies the Spark Double copy of Yarok, so I have three Yaroks on the battlefield, two non-legendary.

But the Clone of the Spark Double copy does not cause additional triggers. A creature entering the battlefield should cause 4 triggers to occur, but only three do trigger.

With only Yarok and the Spark Double copy on the battlefield, there are three copies of every ability, as it should be.

(In the screenshot: On the left the original Yarok, to the right the Spark Double copy, second from the right the Clone of the Spark Double Yarok. Only three of each of Cloud of the Faeries and Soul of the Harvest triggers.)

![Bildschirmfoto vom 2020-03-18 22-04-23](https://user-images.githubusercontent.com/38747561/77007825-3466ff00-6965-11ea-8496-499e6c82da04.png)

**Comment by Zerrisx** [comment]
Fixed by eecaa23
