### ISSUE TITLE
Can’t access specific graveyard, if multiple players have the same name

### ISSUE THREAD

**Issue by luziferius** [magefree/mage#6359]
Steps to reproduce:
- Create a multiplayer match with multiple AI opponents. Leave their name at the default `computer`
- Wait until some cards are in graveyards
- Try to view the different graveyards

Result:
Only the graveyard of one opponent is shown, regardless of which opponent’s GY symbol is clicked.

Proposed solutions:
- Create a reference from the player panel to the appropriate GY, so that the GY can be resolved even with name clashes
- Or number the AI opponents like `computer 1`, `computer 2`, `computer 3` by default. This will hide this issue, as there won’t be clashes by default any more.

The latter should be done anyways, as that’ll make playing with multiple AIs much cleaner.

XMage version: 1.4.42V6

**Comment by LevelX2** [comment]
AI players are numbered now.
