### ISSUE TITLE
Kozilek doesn't have an activated ability

### ISSUE THREAD

**Issue by mattelonian** [magefree/mage#6364]
[pic](https://cdn.discordapp.com/attachments/598268180607270912/691230501167693855/unknown.png)

I don't know if it's an interaction between it and vedalken orrery or what but kozilek refused to do anything when clicked, which is a bit of a major problem in a kozilek deck

**Comment by mattelonian** [comment]
pic related is of me being unable to counter a commander despite having 4 cmc. i had spam clicked kozilek and nothing happened, /fix and repeatedly clicking my life total did nothing either

**Comment by spjspj** [comment]
Was it a range-limited game?  You can't interact in any way with player diagonally opposite you if you have a range of 1 on.

**Comment by mattelonian** [comment]
never mind. maker initially said it wasn't but when i asked them to check they said it was. thanks!
