### ISSUE TITLE
Triggered ability triggered twice (should be once)

### ISSUE THREAD

**Issue by Meerkov** [magefree/mage#6367]
1) Play against MCTS AI
2) Attack with Nessian Board (opponent has 1 Arena Trickster in play)
3) During declare blockers, AI has a null ptr exception... Must "undo" action.
4) Player must "Select Blockers"
5) Choose Arena Trickster (only option)
6) Two triggers go on the stack (expected 1)
7) Opponent draws 2 cards (expected 1)

![xmagebug](https://user-images.githubusercontent.com/8139496/77255944-43310880-6c28-11ea-90d1-d6ed7eb4dcf4.png)
![xmagebug](https://user-images.githubusercontent.com/8139496/77255965-63f95e00-6c28-11ea-9b22-76850b0dcbd0.png)

Expected Result:
One trigger goes on the stack. One card is drawn.

Actual Result:
Trigger happened twice. This does not look like an AI bug, but an engine bug. Perhaps the exception during step (3) means that the Undo wasn't properly performed, and the game thinks nessian board was blocked twice?

**Comment by JayDi85** [comment]
Fixed by a5fb946fb3db62e47d07abba94829a4cd9d39534
