### ISSUE TITLE
Server connection fails, if the server hostname is not a globally resolvable domain name

### ISSUE THREAD

**Issue by luziferius** [magefree/mage#6368]
XMage version: 1.4.42V6

Edit: Seems to be a duplicate of #4190.

I tried to set up an XMage server on host with hostname `xmage`, reachable globally via `myhostname.duckdns.org`.
Some additional details here: https://gitter.im/xmage-devs/Lobby?at=5e779889dca65f4b20e3ccea

I was able to telnet to the server from a remote server via `telnet myhostname.duckdns.org 17171`.
The telnet connection shows a prompt `jbs1{`, indicating that the server is ready to accept JBoss JSON data. So the Server is clearly reachable. But any attempt to connect shows this in the client log:

```
Connect: unknown IO error               =>[SwingWorker-pool-5-thread-5] SessionImpl.doRemoteWorkAndHandleErrors 
java.net.UnknownHostException: xmage
```

The XMage server process exposes my _internal_ server’s hostname to the outside world and the XMage client tries to ping the server using the reported value.
But as it is not a resolvable FQDN, the server ping fails, causing clients to fail connecting.

Suggested fix:
1. Do not transfer the internal hostname from the server to the client.
2. Use the server address entered by the user to perform the PING test.

**Comment by matoro** [comment]
I've just run into this issue.  I think this should be reopened, since it's clearly still the current behavior.

**Comment by luziferius** [comment]
This is a duplicate of #4190, which is still open.

**Comment by JayDi85** [comment]
@matoro nope, it's fine -- you can open launcher/mage-server/config/config.xml and change the serverAddress from 0.0.0.0 to your public server name -- that's name will be exposes to other clients on connect (but be careful -- if your server under router like 99% user computers then must add same name and inner ip to system's host settings, so server will see inner ip for public address -- if you don't add host settings then server can't startup).
