### ISSUE TITLE
Combat Damage Assignment is wrong

### ISSUE THREAD

**Issue by Meerkov** [magefree/mage#6369]
Attacker has 11 power
Blocker has 3 toughness

It is illegal to assign only 1 damage to the blocker, but somehow it let me do it anyway?

![xmagebug](https://user-images.githubusercontent.com/8139496/77256428-65785580-6c2b-11ea-87c5-a3c6f77c29bb.png)

**Comment by LevelX2** [comment]
I can't reproduce  this behaviour in the current dev version.

![grafik](https://user-images.githubusercontent.com/2066790/86408486-5fc4ee00-bcb7-11ea-9222-d8f78727d217.png)
