### ISSUE TITLE
Card Viewer: Memory leak (loaded images are never freed)

### ISSUE THREAD

**Issue by luziferius** [magefree/mage#6375]
XMage version: 1.4.42V6

The Card Viewer never releases loaded images, growing memory requirement as you browse the card images. Especially prominent on large sets, like the Mystery Booster set.

Attaching VisualVM and performing a manual GC does not clear the memory.

Suggested caching behaviour: Preload and keep the current page ± 1 additional page. This way, the next pages load faster when opening the next page while at the same time it will reduce the memory requirement and keep XMage stable.

Additionally, drop all cached images, if the Card Viewer is closed.

**Comment by JayDi85** [comment]
It works as it should.

XMage uses google's cache engine for images -- cache automaticity load and release outdated images (example: it will use additional memory until limit reached -- after that it can remove some outdated images from cache).

P.S. XMage renders and stores unique image for every card (even with different size, text or other attributes -- all gets own rendered image).

**Comment by luziferius** [comment]
@JayDi85 This actually crashed the client with OOM exceptions, even after assigning full 16GB RAM to the JVM.
It never removed images from the cache. That's why I reported this in the first place.

**Comment by JayDi85** [comment]
@luziferius open `launcher -> preferences -> java -> client options` and copy your command line here. Also write your OS version.

I tested it with Mystery Booster pages and no errors in logs:
* 250 MB -- all works fast;
* 2500 MB -- freezing on max limit, but after some pages switch it's fast again.

**Comment by luziferius** [comment]
It seems to not happen in the latest version. The memory usage still hovers at about 99% (4050MB/4096MB) after browsing the card viewer, but it seems to not hang the client any more. I think this can stay closed without further changes.

**Comment by JayDi85** [comment]
Good. I'll add more limits to cache -- it can help to not use all available memory (example: limit maximum cached size from infinite to 1000 images).
