### ISSUE TITLE
Remote task error in Linux systems

### ISSUE THREAD

**Issue by mihan69rus** [magefree/mage#6379]
My friends started local server on Windows system. And all players, who use Windows system, can connect to this server, but i and all players, who use Linux systems can't connect with message "Remote task error. WIN-EOE9EF9FEJ5". Can you help us with this problem? Clients and server use the latest version of xmage(1.4.42V6 (2020-03-04)).

Client log:

ava HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=384m; support was removed in 8.0
INFO  2020-03-28 01:18:16,527 Starting MAGE client version 1.4.42V6 (build: 2020-03-04 17:17)                            =>[main] MageFrame.main 
INFO  2020-03-28 01:18:16,533 Logging level: INFO                                                                        =>[main] MageFrame.main 
INFO  2020-03-28 01:18:20,255 Loading database...                                                                        =>[AWT-EventQueue-0] RepositoryUtil.bootstrapLocalDb 
INFO  2020-03-28 01:18:21,040 DB: creating cards database                                                                =>[AWT-EventQueue-0] MageFrame.<init> 
INFO  2020-03-28 01:18:35,920 DB: need to add 233 new sets                                                               =>[AWT-EventQueue-0] ExpansionRepository.lambda$saveSets$0 
INFO  2020-03-28 01:19:08,619 DB: need to add 38925 new cards                                                            =>[AWT-EventQueue-0] CardRepository.lambda$saveCards$0 
INFO  2020-03-28 01:19:24,903 Done.                                                                                      =>[AWT-EventQueue-0] MageFrame.<init> 
INFO  2020-03-28 01:19:24,963 Loading symbols...                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadImages 
INFO  2020-03-28 01:19:30,314 Loading plugins...                                                                         =>[AWT-EventQueue-0] Plugins.loadPlugins 
INFO  2020-03-28 01:19:30,516 [Game counter plugin, version 0.1] has been loaded.                                        =>[AWT-EventQueue-0] CounterPluginImpl.newPlugin 
INFO  2020-03-28 01:19:30,553 [Card plugin, version 0.7] has been loaded.                                                =>[AWT-EventQueue-0] CardPluginImpl.newPlugin 
INFO  2020-03-28 01:19:30,575 [Theme plugin, version 0.5] has been loaded.                                               =>[AWT-EventQueue-0] ThemePluginImpl.newPlugin 
INFO  2020-03-28 01:19:30,578 Done.                                                                                      =>[AWT-EventQueue-0] Plugins.loadPlugins 
Gtk-Message: 01:19:34.362: Failed to load module "canberra-gtk-module"
WARN  2020-03-28 01:19:38,019 SystemTray is not supported                                                                =>[AWT-EventQueue-0] MageTray.install 
INFO  2020-03-28 01:19:38,526 Client start up time: 81 seconds                                                           =>[AWT-EventQueue-0] MageFrame.lambda$new$2 
INFO  2020-03-28 01:19:47,656 Connect: connecting to server 25.101.167.180:17171                                         =>[SwingWorker-pool-5-thread-4] SessionImpl$5.work 
FATAL 2020-03-28 01:19:59,944 Connect: unknown IO error                                                                  =>[SwingWorker-pool-5-thread-3] SessionImpl.doRemoteWorkAndHandleErrors 
java.net.UnknownHostException: WIN-EOE9EF9FEJ5
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at java.net.Socket.<init>(Socket.java:434)
	at java.net.Socket.<init>(Socket.java:211)
	at org.jboss.remoting.transport.bisocket.BisocketServerInvoker$2.run(BisocketServerInvoker.java:403)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.jboss.remoting.transport.bisocket.BisocketServerInvoker.createControlConnection(BisocketServerInvoker.java:395)
	at org.jboss.remoting.transport.bisocket.BisocketClientInvoker.transport(BisocketClientInvoker.java:459)
	at org.jboss.remoting.MicroRemoteClientInvoker.invoke(MicroRemoteClientInvoker.java:169)
	at org.jboss.remoting.Client.invoke(Client.java:2084)
	at org.jboss.remoting.Client.addCallbackListener(Client.java:2153)
	at org.jboss.remoting.Client.addListener(Client.java:1258)
	at org.jboss.remoting.Client.addListener(Client.java:1144)
	at org.jboss.remoting.Client.addListener(Client.java:1127)
	at mage.remote.SessionImpl$5.work(SessionImpl.java:419)
	at mage.remote.SessionImpl$RemotingTask$1.doInBackground(SessionImpl.java:95)
	at mage.remote.SessionImpl$RemotingTask$1.doInBackground(SessionImpl.java:91)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
INFO  2020-03-28 01:20:00,055 Disconnecting...                                                                           =>[SwingWorker-pool-5-thread-3] SessionImpl.disconnect 
INFO  2020-03-28 01:20:00,734 Disconnecting DONE                                                                         =>[SwingWorker-pool-5-thread-3] SessionImpl.disconnect 
INFO  2020-03-28 01:20:00,735 Disconnected from user mode                                                                =>[SwingWorker-pool-5-thread-3] MageFrame.disconnected

**Comment by JayDi85** [comment]
You must find server's IP address (router's IP to connect) and add that IP to your `\etc\hosts` file (example: `1.1.1.1 WIN-EOE9EF9FEJ5`).

**Comment by luziferius** [comment]
> java.net.UnknownHostException: WIN-EOE9EF9FEJ5

Your system can’t resolve the hostname of the server system, which is currently a crucial part of the server connection process. The other windows systems probably use a proprietary protocol built into Windows to discover each other and resolve the host names.

But non-windows users are out of luck in this case. You need a working DNS in your network.

You have two choices:
- Either get your server windows system to properly register it’s host name in your local DHCP/DNS server (running on your router). Then using `ping -c 4 WIN-EOE9EF9FEJ5` on the terminal should work and XMage client should be able to connect.
- Or place the hostname and IP in `/etc/hosts`, as @JayDi85 already mentioned.


@JayDi85 I’ve written some steps regarding server hosting in the Wiki, as I tripped over similar issues. https://github.com/magefree/mage/wiki/Hosting-an-XMage-server You may want to have a look.

**Comment by mihan69rus** [comment]
The problem was sold by adding ip in /etc/hosts. Thank you very much!

**Comment by Zerrisx** [comment]
Resolved.
