### ISSUE TITLE
trying to make a server on computer and its not working

### ISSUE THREAD

**Issue by ckg6616** [magefree/mage#6381]
hi ive been trying to make a server on my oc so that me and a bunch of people can play magic during the corona outbreak and it not working got any clue what im doing wrong im ported to 17171 on my xfinity router

  <server serverAddress="67.185.178.241"
            serverName="demolay-mage-server"
            port="17171"
            secondaryBindPort="-1"
            backlogSize="200"
            numAcceptThreads="2"
            maxPoolSize="300"
            leasePeriod="5000"
            socketWriteTimeout="10000"
            maxGameThreads="10"
            maxSecondsIdle="600"
            minUserNameLength="3"
            maxUserNameLength="14"
            invalidUserNamePattern="[^a-z0-9_]"
            minPasswordLength="8"
            maxPasswordLength="100"
            maxAiOpponents="15"
            saveGameActivated="false"
            authenticationActivated="false"
            googleAccount=""
            mailgunApiKey=""
            mailgunDomain=""
            mailSmtpHost=""
            mailSmtpPort=""
            mailUser=""
            mailPassword=""
            mailFromAddress=""

**Comment by JayDi85** [comment]
1. setup secondaryBindPort to 17172
2. serverAddress must be visible by server and all other clients too (server must see own IP, clients -- router's IP);
2. Follow [that instructions ](https://github.com/magefree/mage/issues/5597#issuecomment-465647095) (port forward, firewall enable/disable, host file edit if you use router).

**Comment by leestran1995-daugherty** [comment]
Is there an issue that exists for this? I feel like users that are attempting to connect shouldn't have to edit their hosts file if they already have the IP they're meaning to connect to.

**Comment by JayDi85** [comment]
@leestran1995-daugherty there are many instructions to setup server on [github welcome page](https://github.com/magefree/mage/wiki#running-local-server).

Yes, it's possible to use settings without user's host file modification:
1. You can assign real domain name for server;
2. You can use fake domain main from IP like https://nip.io/ services:
 * On server side: use that domain name `magic-67.185.178.241.nip.io` as `serverAddress` (there `67.185.178.241` is your [public IP](https://www.whatismyip.com));
 * On server side: edit host file to map that domain name `magic-67.185.178.241.nip.io` to your local IP;
 * On client side use normal domain name `magic-67.185.178.241.nip.io`;
