### ISSUE TITLE
Card Bug: Oko, Thief of Crowns

### ISSUE THREAD

**Issue by ModestTG** [magefree/mage#6382]
I discovered a bug with Oko, Thief of Crowns today while playing 4 player Commander. Oko, Thief of Crowns used his 2nd ability to turn an artifact into a 3/3 Elk with no abilities. When Oko, Thief of Crowns left the battlefield due to combat damage, the artifact returned to the normal artifact, and was no longer a 3/3 Elk without abilities. Per the first ruling regarding Oko, Thief of Crowns, the 3/3 Elk ability is permanent. 

> The effects of Oko’s second and third abilities last indefinitely. They don’t expire during the cleanup step or if you or Oko leave the game. Oko’s third ability doesn’t expire if the creature you take has its power raised above 3 later.
> (2019-10-04)

Let me know if you have any questions.

**Comment by vvankershim** [comment]
Additionally, I found that when playing a multiplayer game, if player x turns player y's creature into an elk (it was a Ruric Thar), when player x dies, player y's creature returns to normal

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.
