### ISSUE TITLE
Bug to roll back turns

### ISSUE THREAD

**Issue by EstebanJoaquinIgnacio** [magefree/mage#6383]
Well it was like that. The opponent asked me to roll back (I don't remember exactly how many turns ...) and I accepted it. We went back and after that I don't let ANYTHING DO ANYTHING. All the phases passed me without letting me play, I got to have more than 7 cards and did not ask me to discard. I do not allow myself to be blocked. When an opponent threw discard effects at me, he didn't discard anything.
It looked like Phase Out was there.

**Comment by kflan42** [comment]
I hit this tonight several times in 4-5 player commander, it would skip everyone's actions except one (either the host or the rollback initiator, I'm not sure). Rolling back a few times in a row fixed it once. The next game we decided to avoid rollbacks, though while we're still figuring out the interface they're useful.

**Comment by EstebanJoaquinIgnacio** [comment]
It is good that they can be unlocked with more RollBack, but if that bug can be avoided it is better XD.

**Comment by SpeedProg** [comment]
if you have a skip in, you need to remove it before rolling back, or you need to cancel skip after the rollback. Because your skip basically is still there, even if it doesn't them anymore.

**Comment by LevelX2** [comment]
Duplicate of #2072.

**Comment by EstebanJoaquinIgnacio** [comment]
Thanks LevelX2, now i will close the issue. 

Let's use the previous thread [#2072](https://github.com/magefree/mage/issues/2072)

Thank you all guys
