### ISSUE TITLE
Always loading

### ISSUE THREAD

**Issue by DrFiiish** [magefree/mage#6387]
After start from the launcher, can not enter the start menu, stuck at the loading part.
[mageclient.log](https://github.com/magefree/mage/files/4412712/mageclient.log)

**Comment by JayDi85** [comment]
Error logs show that it can't load card plugin file.

Are you running xmage from launcher? If not then check your running script -- it must run from java 1.8 (openjdk 1.8).

**Comment by DrFiiish** [comment]
I do run xmage from the launcher, and my jdk version is 12.0.1. Does my java version cause this problem?

**Comment by JayDi85** [comment]
Launcher downloads own oracle java to `launcher\java` folder and uses it for xmage. Try to move launcher to newer folder and update from scratch.

**Comment by DrFiiish** [comment]
It is fixed after i reinstall my java, thanks a lot
