### ISSUE TITLE
Cleint Freezes when trying to Download Pictures (MAC OS)

### ISSUE THREAD

**Issue by Benjamin-haegler** [magefree/mage#6398]
Hi everyone

I have some Problems trying to download the pictures and tokens for the cards on my Mac. I've tried to only download the Cards first and then the tokens but the client crashes while using the dropdown. Is this a Problem only apple faces or is there a Solution? I tried to find manual links and found a reddit post where it said there would be a link for the complete package on the side bar of r/Xmage but I didn't anything.

Thanks in Advance and stay save

Ben

**Comment by Benjamin-haegler** [comment]
Here's the error from the command line Client
![Screenshot 2020-04-06 at 23 17 44](https://user-images.githubusercontent.com/54842378/78606189-34b83300-785d-11ea-83df-eb4e9c5fcabd.png)

**Comment by JayDi85** [comment]
If you cant choose from dropbox (client freeze) the it's can be Magnet, Contexts or other third party software compatibility issue with java. Related to #4920

If you start to download but it stops after some time then open preferences and change max images download threads from 10 to 2 (scryfall can ban IP for active downloads).

If you cant download at all (e.g. cant see any images) then use that instructions:
https://www.reddit.com/r/XMage/comments/agmcjf/new_xmage_release_with_ravnica_allegiance_rna/

**Comment by Benjamin-haegler** [comment]
Hi Jay

Thanks a lot, worked perfectly!
The Download's a little slow but thats fine.
