### ISSUE TITLE
BUG: Casting cards without paying mana

### ISSUE THREAD

**Issue by trucnar** [magefree/mage#6399]
Issue has resurfaced (#4524 and #4538)

Play a spell, cancel instead of paying the cost and the card will be put into play.

![image](https://user-images.githubusercontent.com/50281468/78620075-ffa3e480-784c-11ea-9799-3c9bd93912c9.png)

XMage version installed:  1.4.42V6 (2020-03-04)

**Comment by LevelX2** [comment]
Is fixed.
