### ISSUE TITLE
Dreadhorde Arcanist trigger and Remand

### ISSUE THREAD

**Issue by filipebfs** [magefree/mage#6418]
Spell (It did cast by Dreadhorde Arcanist trigger) does come back to owner hand instead go to exile, when it was countered by Remand.
1.4.42V6

**Comment by emerald000** [comment]
That is correct. Dreadhorde Arcanist says to exile it if it would go to the graveyard. But Remand puts it into the hand, not the graveyard. It's different from Flashback that exiles it wherever it goes.
