### ISSUE TITLE
Jegantha ruling? bugged?

### ISSUE THREAD

**Issue by SmokinDice** [magefree/mage#6424]
Hey, I made a Sliver deck on xmage using the first sliver as a commander with Jegantha as companion.

I am PRETTY sure that none of my 99 cards have a double symbole of any color in their cost.. so jegantha should work.. still I get an error massage saying it is an invalid deck for it.
![sliver](https://user-images.githubusercontent.com/40409851/79509058-14495f00-803b-11ea-97fd-67b7e751419b.png)

am I missing something? this should work right?

**Comment by theelk801** [comment]
fixed with 8e8b256

**Comment by SmokinDice** [comment]
thanks! when will this change be applied to the client?

**Comment by theelk801** [comment]
It should go live on the beta server within a few hours, not sure when the next release will be.

**Comment by JayDi85** [comment]
@SmokinDice I updated beta server to latest version -- you can download it from launcher or from http://xmage.today/

**Comment by SmokinDice** [comment]
awesome! you guys do a great job! really appricate all the work you do! :)
