### ISSUE TITLE
Cradle of Vitality does not give the option of not putting +1 counters on creatures

### ISSUE THREAD

**Issue by dashosa** [magefree/mage#6428]
![image](https://user-images.githubusercontent.com/63882410/79617375-53c48980-80d5-11ea-863e-756cf618c05c.png)

**Comment by emerald000** [comment]
A target has to be chosen when you put the trigger on the stack. On resolution, you then choose to pay or not.

So unless there is no option given on resolution, this is correct.

**Comment by dashosa** [comment]
When I do select a target it forces me to pay mana, and since I did not have enough I was unable to proceed.

**Comment by ciaccona007** [comment]
When it asks you to pay mana there should be a "cancel" button and if you click that you shouldn't have to pay.

**Comment by dashosa** [comment]
I did not, thanks for looking into this theelk801!!!
