### ISSUE TITLE
Weird replacement effect (was not supposed to happen)

### ISSUE THREAD

**Issue by Blitkun** [magefree/mage#643]
Was playing a match, while having multiple Life from the Loam on my graveyard, a window popped asking me to order replacement effects after "Auto Select"ing the Loam effects. It asked me to order a replacement effect that was not on the battlefield, which was really weird.
Also, I couldn't make it go away, either by "OK", "Auto Select" or "Cancel". That caused me to quit the match, without even being able to chat with my opponent.

I'll add a printscreen. No Gamelog file was generated.

![bug01](https://cloud.githubusercontent.com/assets/9158612/5427545/0c27da86-8389-11e4-80eb-d8134936b81a.PNG)

**Comment by LevelX2** [comment]
Seems to be the same problem here:
http://www.slightlymagic.net/forum/viewtopic.php?f=70&t=16910&p=177481#p177451

**Comment by Blitkun** [comment]
Yes, it looks like the same problem - thanks, Level :D

**Comment by LevelX2** [comment]
Another report:
http://www.slightlymagic.net/forum/viewtopic.php?f=70&t=17186&p=180059#p180057

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.
