### ISSUE TITLE
Regarding mystery booster images

### ISSUE THREAD

**Issue by dougisacat** [magefree/mage#6436]
They require url to download, which I was wondering if there is a way to shortcut do that, or do I need to copy/paste individual urls for 1800 cards. Nobody really wants that. I'm wondering why the old artwork can't just be used, and why the set isn't available for download through the normal methods when a set is released(scryfall, magidex, etc.) Im super looking forward to drafting the set, but no one wants to do it without images. Thank you guys so much for your hard work, I really enjoy the platform. So if the set can be set so the existing images of the cards can be used, or if the way to download the images was added to the scryfall option in images download that would be great.

**Comment by JayDi85** [comment]
It was missing from scryfall download. Fixed with next hotfix by 1468f89ce6cbdd21878ca4b3839ee16bb5d1cd7e

**Comment by dougisacat** [comment]
Thank you so much! Also very impressive that you guys coded the pack structure, that's so cool.
