### ISSUE TITLE
Qasali Ambusher ability not working correctly

### ISSUE THREAD

**Issue by jmharmon** [magefree/mage#6439]
The ability is not coded properly, so it's alternate casting can't be done with paying mana

**Comment by LevelX2** [comment]
Correct, you may not cast it with flash using mana.

https://tappedout.net/mtg-questions/can-you-cast-an-uncounterable-qasali-amusher-with-the-second-ability/

**Comment by jmharmon** [comment]
I think wrote my initial comment too quickly. The only way to cast it for its alternate cost still involves spending the mana. So its alternate cost doesn't work properly at all.

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.  There's a new different bug, but it's not this one.
