### ISSUE TITLE
can't updata the last version

### ISSUE THREAD

**Issue by bernardopaixao** [magefree/mage#6440]
I'm trying yo update, but the bar is not growing

**Comment by JayDi85** [comment]
1. Close all java.exe apps or restart computer;
2. [Download](http://xmage.today/X/run.zip) and unpack run.zip file to folder with launcher;
3. Run launcher file and try update again.

**Comment by bernardopaixao** [comment]
I'm in Mac, Already restarted the computer.

Is not only click in update in the launcher?

But i downloard the run but i cannot open

**Comment by bernardopaixao** [comment]
![Captura de Tela 2020-04-19 às 17 48 05](https://user-images.githubusercontent.com/63951493/79684687-f57ae080-8265-11ea-9308-2c70cad04db7.png)

**Comment by JayDi85** [comment]
Are you using proxy or vpn?

**Comment by bernardopaixao** [comment]
No vpn! what is proxy?

**Comment by JayDi85** [comment]
Can you download that file?

https://github.com/magefree/mage/releases/download/xmage_1.4.42V7/xmage_1.4.42V7a.zip
