### ISSUE TITLE
Port Changes with update?

### ISSUE THREAD

**Issue by ekoesling** [magefree/mage#6442]
Quick question. Since the update, I have not been able to connect to xmage except for locally on my server. I have ports forwarded on my router and the Windows Firewall on the server open for 17171 and 17172. 

Everything was working with this setup.

When I turn off my windows firewall completely, everything works.
Ive tried removing the rules and reading them, but no luck.

Just making sure there are no new ports needed for connection to the xmage server from the client outside of the default 17171 and 17172.

Thanks for everything you do, especially during these challenging times.

**Comment by JayDi85** [comment]
Nope, nothing change. You can check ports in server's `config.xml` file:
![shot_200417_025604](https://user-images.githubusercontent.com/8344157/79699194-06941380-829f-11ea-9f9c-6053e0fbe150.png)

Also you can move xmage folder (launcher and all files) to new folder and run from it (firewall can ask you network access again).

If you run server from launcher then you must enable access for:
* `\launcher_folder\java\jre1.8.0_201\bin\java.exe`

If you run server by own script then check your java from that script (it can be default system java, so your paths will be different).

**Comment by ekoesling** [comment]
Update: So I figured out (and see that JayDi85 would have pointed me in the right direction).

Two things to note when updating (Im new and this was my first update)

1. Your Config file gets overwritten, so you need to update your Server Address if externally hosted
2. The 'secondaryBindPort' is set to ="-1" which didn't work for me and I had to change it to 17172

Here was a the article I used before I saw JayDi85s note above.
https://www.reddit.com/r/XMage/comments/edbhjl/guide_xmage_remote_task_error_machine_name_fix/

Thanks all! We are back online.
