### ISSUE TITLE
Beta client incompatible with stable client

### ISSUE THREAD

**Issue by Gottschkopf** [magefree/mage#6449]
Trying to use a deck in the beta client made with the stable version gives this error for every single card:

![Neue Bitmap (2)](https://user-images.githubusercontent.com/24585791/79778965-dc436400-8339-11ea-8dd8-1966689932fa.jpg)

Also cardimages downloaded with stable can't be used with beta.

**Comment by JayDi85** [comment]
Missing card is standard error with server restart needs. Now it works fine.
