### ISSUE TITLE
Aether Vial vs Mana Leak

### ISSUE THREAD

**Issue by Mikalinn777** [magefree/mage#6456]
Just played a match against a computer opponent to test out my Modern Control Deck so I played it against a humans deck. The computer casted Thalia, so I immediately went to counter the spell with Mana Leak, but the computer paid for it by tapping their Aether Vial... I imagine the code just treats Aether Vial like adding mana to the pool and it made for a weird effect here

**Comment by Mikalinn777** [comment]
![Screenshot 2020-04-21 at 4 11 39 PM](https://user-images.githubusercontent.com/24897878/79919399-8fb86100-83eb-11ea-82f4-8656a300ccd9.png)
And just a screenshot of the game right here

**Comment by emerald000** [comment]
From the screenshot, it sounds like computer activated Aether Vial in response to Mana Leak, put nothing in play, then paid 3 mana from their lands. Is this what happened? And if not, do you have a full game log?

**Comment by Mikalinn777** [comment]
On the contrary, the bot had only 3 lands in play and no Noble Hierarch's up. Paid two of them for the Thalia. And I looked through my logs and apparently I have none for the last two days for some reason.
