### ISSUE TITLE
AI issues + card function bugs

### ISSUE THREAD

**Issue by lehandroz** [magefree/mage#6461]
- [ ] I am playing with AI to decktest my EDH decks. 3v1 AI always whales on you even though there is clearly a lower HP opponent w/o blockers, and will always one-sidedly counter your spells, use strip mine/wasteland on your lands, etc. It feels like Archenemy instead of EDH, honestly.

- [x] Also, why were there changes made to Muldrotha? She now works as if "you may play ONE card from your graveyard per turn" instead of "one card PER PERMANENT TYPE". 

- [ ] Torchling's change target ability doesn't seem to work properly as well. I've tried it several times using Mairsil but it doesn't show as an option to respond to even though the removal spell was targeted ONLY on Mairsil.

- [x] Memnarch's abilities also do not work properly. They do target properly, but the permanent targeted is never changed into an artifact, so the control ability doesn't work as intended. 

- [ ] Lastly, Aminatou's Augury does not work. After you select the land to play, everything else is stuck in exile and cannot even be selected to cast.

**Comment by arketec** [comment]
I have noticed the same issues with Muldrotha, both in the release version and the beta version when playing against AI

**Comment by Zerrisx** [comment]
First and last issues are duplicates of #5040 and #5683 respectively.  Third issue appears to be fixed.  Closing this issues overall as fixed/duplicate.

**Comment by Stuff-n-Such** [comment]
I'm finding that I can't test Commander decks in a multi-player game without getting agressively ganged up upon.  It's not helpful for testing to play a game where you are constantly out matched despite playing against some pretty dumb AI.
