### ISSUE TITLE
Generic Text Corrections

### ISSUE THREAD

**Issue by Zerrisx** [magefree/mage#6465]
- [ ] Warren-Scourge Elf: Goblin > Goblins
![image](https://user-images.githubusercontent.com/59861365/83664590-d3c48700-a58f-11ea-9cfb-3d80772d009a.png)

- [ ] Broken Ambitions: missing text
![image](https://user-images.githubusercontent.com/59861365/83664673-e8088400-a58f-11ea-9289-9dd6c2935663.png)

- [ ] Aven Trailblazer: type > types
![image](https://user-images.githubusercontent.com/59861365/83060255-c6a01900-a020-11ea-9cf1-b9aae72d2ab7.png)

- [ ] Dragon's Grip: missing ferocious text
![image](https://user-images.githubusercontent.com/59861365/83060542-3adabc80-a021-11ea-94b5-53419d0dca99.png)

- [ ] Woebringer Demon: missing "player's"
![image](https://user-images.githubusercontent.com/59861365/83060851-b472aa80-a021-11ea-8795-e2bd9de25bd2.png)

- [ ] Sorin, Vengeful Bloodlord: vampire should be capitalized
![image](https://user-images.githubusercontent.com/59861365/83033769-2258ab00-9ffd-11ea-822f-8891bfdd4c36.png)

- [x] Together Forever: remove other; this isn't a creature
![image](https://user-images.githubusercontent.com/59861365/80264008-3739cb80-8658-11ea-9cf8-ad0b0623d4f0.png)

- [ ] When picking between piles, it would be nice if the chat confirmation was the same punctuation/spacing as the choice - i.e. make these the same:
![image](https://user-images.githubusercontent.com/59861365/82282026-78bc4e80-9958-11ea-9d32-c3a9c7e18f7d.png)

- [ ] Some modal cards use capitals in the on-the-stack hover text, while some don't.  Looks like it's all the CCC Commands that are in lowercase.
![image](https://user-images.githubusercontent.com/59861365/82266690-fae44d00-992f-11ea-9dcf-955f5a0a5d8f.png)
![image](https://user-images.githubusercontent.com/59861365/82266705-0899d280-9930-11ea-81e8-e59ba07c9be9.png)

- [x] The Tabernacle at Pendrell Vale needs an ending quote
![image](https://user-images.githubusercontent.com/59861365/80155324-1eadb080-8587-11ea-8108-1aa1d32a38e2.png)

- [x] Showstopper has an extra period
![image](https://user-images.githubusercontent.com/59861365/80155290-0b9ae080-8587-11ea-9d87-f6b5c740c707.png)

- [x] Furystoke Giant shouldn't have a period inside the quotes
![image](https://user-images.githubusercontent.com/59861365/80155423-4ef54f00-8587-11ea-9128-4458a6b6d0a9.png)

- [x] Pontiff of Blight shouldn't have quotes around the second Extort ability
![image](https://user-images.githubusercontent.com/59861365/80155464-62a0b580-8587-11ea-9481-0818b5e731a9.png)

- [x] Vraska, Scheming Gorgon's +2 should be until end of turn
![image](https://user-images.githubusercontent.com/59861365/80155497-70563b00-8587-11ea-9a3a-920a4f4eaae7.png)

- [x] Four of the banding lands (Cathedral of Serra, Mountain Stronghold, Seafarer's Quay, and Unholy Citadel) all need to have 'legend' in lower case and a period added at the end
![image](https://user-images.githubusercontent.com/59861365/80155535-8237de00-8587-11ea-8b00-8f4fa00cf6ce.png)

- [x] Adventurer's Guildhouse, however, needs some quotes added along with 'legend' in lower case
![image](https://user-images.githubusercontent.com/59861365/80155556-8f54cd00-8587-11ea-84cf-a1065073b8e4.png)

- [x] Frenzy Sliver has a dangling extra quote at the end that shouldn't be there
![image](https://user-images.githubusercontent.com/59861365/80155597-a72c5100-8587-11ea-985a-6971168d8b85.png)

- [x] Armor Sliver, Barbed Sliver, Lavabelly Sliver, Spectral Sliver, Tempered Sliver, and Mnemonic Sliver all have a bad substitution going on in their granted ability
![image](https://user-images.githubusercontent.com/59861365/80155618-b4e1d680-8587-11ea-9273-24925e32e0b7.png)

- [ ] Retaliation has a similar issue, made funnier by it being an enchantment and not even a creature
![image](https://user-images.githubusercontent.com/59861365/80155647-c1fec580-8587-11ea-9398-75ac5d0d911c.png)

- [x] Rishkar should say 'has' instead of 'you control have' here
![image](https://user-images.githubusercontent.com/59861365/80155669-ccb95a80-8587-11ea-8e79-44a5e1367d01.png)

- [ ] Magma Sliver's ability is confused
![image](https://user-images.githubusercontent.com/59861365/80155679-d642c280-8587-11ea-8aaa-d665b3d01250.png)

- [x] Vivien Reid shouldn't have a period here, and trample should be lower case
![image](https://user-images.githubusercontent.com/59861365/80156030-8b757a80-8588-11ea-919c-98ae9b37a555.png)

- [ ] Shredded Sails' text when cast doesn't format the bullets properly
![image](https://user-images.githubusercontent.com/59861365/80156685-2589f280-858a-11ea-8199-f870d42f5c8b.png)

- [x] When cast, all(?) modal spells default to lower case sentences when they should be uppercase
![image](https://user-images.githubusercontent.com/59861365/80156863-8c0f1080-858a-11ea-8e24-198781298502.png)

- [ ] Shark Typhoon's Cycling should be X1U instead of 1XU
![image](https://user-images.githubusercontent.com/59861365/80157383-b0b7b800-858b-11ea-9485-0604310dffe5.png)

- [x] Winota, Joiner of Forces should have 'a' instead of 'ana'
![image](https://user-images.githubusercontent.com/59861365/80157624-376c9500-858c-11ea-8524-7ac5cff5b86f.png)

- [x] Glaive of the Guildpact should say +1/+0 instead of +X/+0
![image](https://user-images.githubusercontent.com/59861365/80262132-22f2d000-8652-11ea-91d5-23736018026c.png)

- [x] Sarkhan Vol's second ability allows multiple targets, which it shouldn't; they all apply to the same creature
![image](https://user-images.githubusercontent.com/59861365/80262192-533a6e80-8652-11ea-8162-6cd546dab86a.png)

- [ ] Hedron Blade: Equipped creature > it
![image](https://user-images.githubusercontent.com/59861365/80271362-26537f00-8685-11ea-9db4-5f913c3dd084.png)

- [ ] Clot Sliver: Clot Sliver > this permanent
![image](https://user-images.githubusercontent.com/59861365/80271980-4128f200-868b-11ea-9eed-87b2a3e891ee.png)

- [ ] Necromantic Summons: has two extra "s
![image](https://user-images.githubusercontent.com/59861365/80272025-92d17c80-868b-11ea-883f-8b4790d4a744.png)

- [ ] Sunbringer's Touch: reminder text in the wrong place
![image](https://user-images.githubusercontent.com/59861365/80298366-0d180480-8751-11ea-86ac-5b36fa6a1f6f.png)

- [ ] Break Open: Face-down > face-down
![image](https://user-images.githubusercontent.com/59861365/80314014-459cfa00-87b4-11ea-9d57-42b4e5440d45.png)

- [ ] capital offense: Target > target
![image](https://user-images.githubusercontent.com/59861365/80314047-7bda7980-87b4-11ea-95a0-d74f428516a6.png)

**Comment by ThomasArb** [comment]
If I remembre correctly, there is also a missing word in the « Blast zone »

**Comment by ThomasArb** [comment]
- [ ] Blast Zone : put > with
![image](https://user-images.githubusercontent.com/18098698/80578130-52b22700-8a08-11ea-9977-d0622e27850a.png)

**Comment by ThomasArb** [comment]
- [ ] Hunter's Insight
<img width="414" alt="Capture d’écran 2020-04-30 à 14 16 03" src="https://user-images.githubusercontent.com/18098698/80709387-7d29e000-8aed-11ea-911c-ee174d307382.png">
<img width="414" alt="Hunter's insight" src="https://img.scryfall.com/cards/large/front/a/8/a85d0ca4-551c-4e23-b35b-e49b89ce86bd.jpg?1586298022">

**Comment by ThomasArb** [comment]
- [ ] Marrow-Gnawer

![Capture d’écran 2020-05-05 à 13 26 23](https://user-images.githubusercontent.com/18098698/81064874-be016a80-8eda-11ea-860a-ec75db8dc6d3.png)

**Comment by Grath** [comment]
Breya, Etherium Shaper - Activated ability reads "2, Sacrifice two two artifacts" when it should only say "two" once.

**Comment by Grath** [comment]
Winged Temple of Orazca - Says "It" rather than "Target creature you control" on the non-mana ability.

**Comment by ThomasArb** [comment]
> - [x] Breya, Etherium Shaper - Activated ability reads "2, Sacrifice two two artifacts" when it should only say "two" once.
> 
> 
> 
> ![](https://i.imgur.com/txfAUvO.png)

**Comment by ThomasArb** [comment]
Winged Temple of Orazca and Breya are done.

**Comment by ThomasArb** [comment]
The text should be in one sentence : “Creatures you control have double strike, trample, hexproof and haste”

![image](https://user-images.githubusercontent.com/18098698/81694679-e8ff3780-9461-11ea-8d70-eb8ffa572be8.png)

**Comment by jgod** [comment]
Nice work

**Comment by ThomasArb** [comment]
- [ ] The text in the trigger doesn't reference the target.
<img width="510" alt="Capture d’écran 2020-05-21 à 12 01 07" src="https://user-images.githubusercontent.com/18098698/82554163-b510ca00-9b65-11ea-9975-ecee2badc033.png">


- [ ] Duplication of the ability text.
<img width="416" alt="Capture d’écran 2020-05-21 à 11 49 20" src="https://user-images.githubusercontent.com/18098698/82554141-a9bd9e80-9b65-11ea-8970-c9c89a3189f6.png">
<img width="416" alt="Capture d’écran 2020-05-21 à 11 49 20" src="https://img.scryfall.com/cards/large/front/4/8/48fd52d0-0e41-48d5-b96f-4c6409788c18.jpg?1561825513">

**Comment by Zerrisx** [comment]
Added another correction to this issue chain, so that I can close the C20 one

**Comment by ThomasArb** [comment]
[ ] Olivia Voldaren : text duplication


![image](https://user-images.githubusercontent.com/18098698/83517991-20e62180-a4da-11ea-8d86-9673856a48bc.jpeg)

[ ] Liliana, dread horde general : missing space
![image](https://user-images.githubusercontent.com/18098698/83518066-4410d100-a4da-11ea-9105-15a5f5c77b65.jpeg)

**Comment by ThomasArb** [comment]
@Zerrisx Clot Sliver and Warren-Scourge Elf are done.

**Comment by Zerrisx** [comment]
- [ ] Scorching Lava: the kicker isn't being required to get the kicker effect
![image](https://user-images.githubusercontent.com/59861365/84729986-a1853300-af5a-11ea-8d3e-e002472a0d15.png)

- [ ] Life Matrix: it refers to removing a counter from the wrong permanent
![image](https://user-images.githubusercontent.com/59861365/84730182-19ebf400-af5b-11ea-81e2-1a6abfe94d44.png)

**Comment by Zerrisx** [comment]
Duplicate of #6654
