### ISSUE TITLE
Add websockets as a connection medium

### ISSUE THREAD

**Issue by marthinwurer** [magefree/mage#6468]
Currently Jboss is used for all comms. This poses issues when servers are hosted behind NATs. Websockets are way more supported by basically everything; there's even a pure java library by the eclipse foundation that supports them. This would also open up the client to be implemented in other languages and frameworks. 

SSL could also be used for encrypted communications, and legitimate certificates could be obtained using something like acme4j and let's encrypt.

These probably aren't pressing concerns, but they would be improvements.

**Comment by JayDi85** [comment]
JBoss uses own two way socket connections. See tasks to change network engine to more modern (#5373, etc).
