### ISSUE TITLE
Possible issue with Snapcaster Mage and split/fuse cards

### ISSUE THREAD

**Issue by Blepsis** [magefree/mage#6470]
Targeted a Wear//Tear in my graveyard with Snapcaster Mage's ability. The Wear//Tear had the purple outline that a castable/activatable card has when I had priority, but when I tried to click on the card to cast it, nothing happened. 

https://imgur.com/a/q7BCnNL
Cap of the boardstate at the time, showing the highlight on Wear//Tear.

**Comment by Zerrisx** [comment]
I think this is flashback in general - my opponent in a vintage cube match was unable to flashback Fire//Ice with either Snapcaster Mage or Past in Flames.

**Comment by Zerrisx** [comment]
Duplicate of #6549

**Comment by JayDi85** [comment]
Fixed via b94344341bf47968fcfa2018aa418547da25917e
