### ISSUE TITLE
Add support for importing/exporting decks in mtgjson.org's JSON format

### ISSUE THREAD

**Issue by allentiak** [magefree/mage#6475]
This would allow XMage to profit from the crowdsourced deck list from mtgjson.org

JSON deck file example:
[AirForces_WTH.json.txt](https://github.com/magefree/mage/files/4532260/AirForces_WTH.json.txt) (.txt extension added to allow upload)
Source: https://www.mtgjson.com/json/decks/AirForces_WTH.json

I chose this example because it also includes the internationalized names for the cards (to be ignored when importing the data).

More decks:
https://mtgjson.com/downloads/all-files (look for "AllDeckFiles")

**Comment by timhae** [comment]
I guess this can be closed now
