### ISSUE TITLE
Particularly Weird Text Issues

### ISSUE THREAD

**Issue by Zerrisx** [magefree/mage#6476]
- [x] Jandor's Ring
![image](https://user-images.githubusercontent.com/59861365/80270389-1637a180-867d-11ea-8b31-84d556bd4c23.png)

- [x] Belbe's Armor
![image](https://user-images.githubusercontent.com/59861365/80270402-2ea7bc00-867d-11ea-9298-4ccb555278d8.png)

- [x] Anya, MercilessAngel
![image](https://user-images.githubusercontent.com/59861365/80270411-4e3ee480-867d-11ea-9756-72c8a6e62fe9.png)

- [x] Skirk Alarmist
![image](https://user-images.githubusercontent.com/59861365/80270378-ff914a80-867c-11ea-9fc7-b00319983304.png)

- [x] Break Open
![image](https://user-images.githubusercontent.com/59861365/80270373-ea1c2080-867c-11ea-8272-3990af1f965d.png)

- [x] capital offense
![image](https://user-images.githubusercontent.com/59861365/80270426-7b8b9280-867d-11ea-99fd-2a2e4d04d757.png)

- [x] Ixidor, Reality Sculptor
![image](https://user-images.githubusercontent.com/59861365/80270430-8ba37200-867d-11ea-888e-c55999f84e7c.png)

**Comment by theelk801** [comment]
Should Ieave this open so you can add more to it?

**Comment by Zerrisx** [comment]
Nah - this is all the ones of this type, at least.
