### ISSUE TITLE
Keywords in quotes

### ISSUE THREAD

**Issue by Zerrisx** [magefree/mage#6477]
The following cards have keywords in quotes, and should not:

"Deathtouch"

- [x] Basilisk Collar
- [x] Gift of Doom
- [x] Gorgon Flail
- [x] Gorgon's Head
- [x] Hedron Blade
- [x] Quietus Spike

"Defender"

- [x] Dragon Throne of Tarkir
- [x] Gelid Shackles
- [x] Guard Duty
- [x] Peregrine Mask
- [x] Sky Tether
- [x] Zephyr Net

"Double Strike"

- [x] Battle Mastery
- [x] Fireshrieker
- [x] Grappling Hook
- [x] Rageform

"Fear"

- [x] Corrupting Licid
- [x] Dragon Shadow
- [x] Fear
- [x] Mask of Riddles
- [x] Sleeper's Guile
- [x] Sleeper's Robe

"First Strike"

- [x] Aggression
- [x] Asha's Favor
- [x] Aspect of Manticore
- [x] Bladed Pinions
- [x] Chariot of Victory
- [x] Claws of Valakut
- [x] Ethereal Armor
- [x] Galvanic Arc
- [x] Helm of Kaldra
- [x] Hyena Umbra
- [x] Indrik Umbra
- [x] Kamahl's Desire
- [x] Lance
- [x] Lashknife
- [x] Lightsaber
- [x] Moonsilver Spear
- [x] No-Dachi
- [x] Peregrine Mask
- [x] Quickening Licid
- [x] Reflexes
- [x] Shadow Lance
- [x] Sharpened Pitchfork
- [x] Sparring Collar
- [x] Surestrike Trident
- [x] Unscythe, Killer of Kings

"Flanking"

- [x] Agility

"Flying"

- [x] Aboshan's Desire
- [x] Air Bladder
- [x] Angelic Armaments
- [x] Angelic Gift
- [x] Angelic Reward
- [x] Arcanum WIngs
- [x] Armored Ascension
- [x] Asha's Favor
- [x] Bladed Pinions
- [x] Buoyancy
- [x] Cloudform
- [x] Cobbled Wings
- [x] Dragon Wings
- [x] Drake Umbra
- [x] Elder Mastery
- [x] Ephara's Enlightenment
- [x] Fallen Ideal
- [x] Fleetfeather Sandals
- [x] Flight
- [x] Flight of Fancy
- [x] Ghostly Possession
- [x] Gift of Orzhova
- [x] Gliding Licid
- [x] Illuminated Wings
- [x] Launch
- [x] Lightform
- [x] Magefire Wings
- [x] Neurok Hoversail
- [x] Nimbus Wings
- [x] Pemmin's Aura
- [x] Peregrine Mask
- [x] Phantom Wings
- [x] Pollenbright Wings
- [x] Shimmering Wings
- [x] Skinwing
- [x] Snow Devil
- [x] Soaring Hope
- [x] Spectral Flight
- [x] Spirit Away
- [x] Stratus Walk
- [x] Wings of Hubris
- [x] Zephyr Net

"Haste"

- [x] Dragon Breath
- [x] Enraging Licid
- [x] Fleetfeather Sandals
- [x] Lightning Greaves
- [x] Lightning Prowess
- [x] Mark of Fury
- [x] Necropouncer
- [x] Obsidian Battle-Axe
- [x] Primal Visitation
- [x] Prophetic Ravings
- [x] Ring of Valkas
- [x] Shifting Shadow
- [x] Strider Harness

"Hexproof"

- [x] Alpha Authority
- [x] Ring of Evos Isle
- [x] Starlit Mantle
- [x] Swiftfoot Boots

"Indestructible"

- [x] Darksteel Plate
- [x] Gift of Doom

"Infect"

- [x] Corrupted Conscience
- [x] Glistening Oil
- [x] Grafted Exoskeleton
- [x] Phyresis

"Intimidate"

- [x] Executioner's Hood
- [x] Grisly Transformation
- [x] Gruesome Deformity
- [x] Nim Deathmantle

"Phasing"

- [x] Cloak of Invisibility
- [x] Teferi's Curse

"Poisonous"

- [x] Snake Cult Initiation

"Protection"

- [x] Artifact Ward
- [x] Guildscorn Ward
- [x] Holy Mantle
- [x] Mask of Law and Grace
- [x] Shield of Duty and Reason
- [x] Spectra Ward
- [x] Spirit Mantle
- [x] Sword of Feast and Famine
- [x] Sword of Fire and Ice
- [x] Sword of Light and Shadow
- [x] Tattoo Ward
- [x] Unquestioned Authority

"Provoke"

- [x] Hunter Sliver

"Reach"

- [x] Frog Tongue
- [x] Spider Umbra
- [x] Spidersilk Net
- [x] Strandwalker
- [x] Web
- [x] Whip Silk

"Shroud"

- [x] Alexi's Cloak
- [x] Aspect of Mongoose
- [x] Diplomatic Immunity
- [x] General's Kabuto
- [x] Mystic Veil
- [x] Neurok Stealthsuit
- [x] Pemmin's Aura
- [x] Protective Bubble
- [x] Relic Ward
- [x] Robe of Mirrors
- [x] Whispersilk Cloak

"Trample"

- [x] Aggression
- [x] Bestial Fury
- [x] Dragon Fangs
- [x] Epic Proportions
- [x] Fists of Ironwood
- [x] Keldon Mantle
- [x] Messenger's Speed
- [x] Mob Mentality
- [x] Oni Possession
- [x] Primal Frenzy
- [x] Ring of Kalonia
- [x] Savage Hunger
- [x] Vorrac Battlehorns

"Vigilance"

- [x] Accorder's Shield
- [x] Asha's Favor
- [x] Batterskull
- [x] Cathar's Shield
- [x] Dragon Scales
- [x] Eternal Warrior
- [x] Gleam of Authority
- [x] Mammoth Umbra
- [x] Ocular Halo
- [x] Ring of Thune
- [x] Shield of the Righteous
- [x] Soul-Strike Technique
- [x] Stamina
- [x] Triclopean Sight
- [x] Vigilance

**Comment by timhae** [comment]
I think this might be solved by applying this
```
diff --git a/Mage/src/main/java/mage/abilities/effects/common/continuous/GainAbilityAttachedEffect.java b/Mage/src/main/java/mage/abilities/effects/common/continuous/GainAbilityAttachedEffect.java
index 1b6395382b..b9fc862152 100644
--- a/Mage/src/main/java/mage/abilities/effects/common/continuous/GainAbilityAttachedEffect.java
+++ b/Mage/src/main/java/mage/abilities/effects/common/continuous/GainAbilityAttachedEffect.java
@@ -102,7 +102,7 @@ public class GainAbilityAttachedEffect extends ContinuousEffectImpl {
         } else {
             sb.append("gains ");
         }
-        sb.append('"').append(ability.getRule("this creature")).append('"');
+        sb.append(ability.getRule("this creature"));
         if (!duration.toString().isEmpty()) {
             sb.append(' ').append(duration.toString());
         }
```
but I am not able to build at the moment due to #6185 will try once I can test
