### ISSUE TITLE
Creature type glitch - Zacama

### ISSUE THREAD

**Issue by Nloch** [magefree/mage#6480]
Not sure if this was intentional or not but Zacama does not count as a "Dinosaur" for enchantment or artifact cards ("Creatures of the selected type cost X less", "Creatures of the seleceted type get +1/+1", etc). It's segregated specifically as an "Elder Dinosaur".

Can this be adjusted?

**Comment by theelk801** [comment]
Can you give an example of a card that it didn't work with?

**Comment by Nloch** [comment]
Yes of course - I should have provided that before - with Huatli, Dinosaur
Knight +2 and -3 abilities.

**Comment by Nloch** [comment]
Actually I think both of the Huatli Planeswalkers didnt work with him

**Comment by theelk801** [comment]
I just tested Dinosaur Knight and it worked fine, and Warrior Poet doesn't interact with Dinosaurs so I'm not sure what the issue is there.

**Comment by Nloch** [comment]
Correct, it's just the Dinosaur Knight, I just tried using the -3 again and it still wont work. Granted I've only tried it twice - could just be a glitch with me.. idk

**Comment by Nloch** [comment]
It wont let me select Zacama as the dinosaur I control.

**Comment by theelk801** [comment]
Is there anything else on the battlefield?

**Comment by Nloch** [comment]
I had Bellowing Aegisaur and Kinjalli's Sunwing - the opponent had some knights out. It would only allow me to select the Aegisaur or Sunwing.

**Comment by theelk801** [comment]
has this happened in more than one game?

**Comment by Zerrisx** [comment]
Cannot reproduce.
