### ISSUE TITLE
Out of order types

### ISSUE THREAD

**Issue by Zerrisx** [magefree/mage#6483]
The following card types are always out of order:

- [ ] Creature Enchantment > Enchantment Creature
- [ ] Legendary Creature Enchantment > Legendary Enchantment Creature
- [ ] Enchantment Tribal > Tribal Enchantment
- [ ] Sorcery Tribal > Tribal Sorcery
- [ ] Instant Tribal > Tribal Instant
- [ ] Artifact Tribal > Tribal Artifact

**Comment by jmharmon** [comment]
Can confirm this. Duplicate of #6055. Pictures to show.

**Comment by Zerrisx** [comment]
Closing as duplicate.
