### ISSUE TITLE
Painter Servant Ability Delayed?

### ISSUE THREAD

**Issue by dganev234** [magefree/mage#6487]
Hello, this is my first time reporting an issue. I was playing mtg and had a Painter's Servant on the board, naming blue. A player tried to cast a green sun's zenith, it was targeted by pyroblast and in response the painter was exiled but the zenith was still countered.

01:31, T21.M1: dganev casts Green Sun's Zenith [572]
01:31, T21.M1: DTSG casts Red Elemental Blast [512] (mode 1) targeting Green Sun's Zenith [572] 
01:31, T21.M1: dganev casts Swords to Plowshares [8d5] targeting Painter's Servant [58e] 
01:32, T21.M1: DTSG gains 1 life
01:32, T21.M1: dganev puts Swords to Plowshares [8d5] from stack into their graveyard
01:32, T21.M1: dganev puts Green Sun's Zenith [572] from stack into their graveyard
01:32, T21.M1: Green Sun's Zenith [572] is countered by Red Elemental Blast [512]

**Comment by spjspj** [comment]
From gatherer: https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=413684

10/4/2004 | The  decision to counter a spell or destroy a permanent is a decision made  on announcement before the target is selected. If the spell is  redirected, this mode can’t be changed, so only targets of the selected  type are valid.
-- | --
6/8/2016 | Pyroblast can target any spell or permanent, not just a blue one. It checks the color of the target only on resolution.

Shouldn't have been countered.

**Comment by dganev234** [comment]
Yeah, I'm aware of it.

**Comment by jeffwadsworth** [comment]
This is just an issue with checking the target upon resolution.  I will check it out tomorrow.
