### ISSUE TITLE
Bug with bloodmoon and shock lands

### ISSUE THREAD

**Issue by hudsouza** [magefree/mage#6488]
I had a problem few weeks ago.

My opponent was with a blood moon in play and I tried to play a shockland.

The game asked if i wanted to pay 2 life for it and I clicked no because it shouldn't make a difference with blood moon in play.

When I didn't pay the life, it entered the battlefield tapped and as a mountain.

**Comment by hudsouza** [comment]
I had the issue with a shockland, but I assume it'll happen with any nonbasic land that enters tapped

**Comment by mikebryant** [comment]
According to https://blogs.magicjudges.org/rulestips/2013/04/how-blood-moon-works-with-shocklands/ this is the correct behaviour.

**Comment by jmharmon** [comment]
> According to https://blogs.magicjudges.org/rulestips/2013/04/how-blood-moon-works-with-shocklands/ this is the correct behaviour.

That article very out of date.

> If a nonbasic land has an ability that triggers “when” it enters the battlefield, it will lose that ability before it triggers.
(2018-03-16)

> If a nonbasic land has an ability that causes it to enter the battlefield tapped, it will lose that ability before it applies. The same is also true of any other abilities that modify how a land enters the battlefield or apply “as” a land enters the battlefield, such as the first ability of Cavern of Souls. This is a change from previous rulings.
(2017-09-29)

**Comment by mikebryant** [comment]
Oh, my mistake. Thanks for pointing that out

**Comment by theelk801** [comment]
We know about this issue but at the moment we haven't been able to fix it. See #4202.
