### ISSUE TITLE
Thalia increases spliced costs

### ISSUE THREAD

**Issue by Dragas** [magefree/mage#6493]
It seems that presence of Thalia, Guardian of Thraben requires that you pay the spliced costs twice, rather than once. According to 702.46a splice is an additional cost, rather than a casting cost.

**Comment by Zerrisx** [comment]
Pretty sure this is a more generic bug, in that things that combine spells consider costs separately before combination - I.e. Thalia also increases costs of fused cards by {2}.

**Comment by JayDi85** [comment]
Fixed via a75d08283fb8f9ea143363bda0940167dc0ca504

**Comment by Dragas** [comment]
Will this be included with ikoria release?
