### ISSUE TITLE
Required condition for effects: "for as long as you control {this}"

### ISSUE THREAD

**Issue by NorthFury** [magefree/mage#65]
Cards currently affected: **Aegis Angel**; **Dungeon Geists**; **Master Thief**; **Olivia Voldaren**.

**Aegis Angel** and **Dungeon Geists** are currently implemented correctly.
It would be best if we could extract this in a common behavior.

PS: **Roil Elemental** could also be easily implemented as part of this task.

**Comment by emerald000** [comment]
Fixed in the past. Closing.
