### ISSUE TITLE
Golos appears to now be 5 colored

### ISSUE THREAD

**Issue by spjspj** [magefree/mage#6506]
As in not colourless, and it gets exiled with a -5 of ugin :(

**Comment by laaksoma** [comment]
I hope it's ok to jump in; I tried to recreate this bug with EDH decks to see whether it's just Golos or other colorless cards with colored color identities, too. 
In the following setting, -9 with Ugin, The Spirit Dragon only exiled Dockside Extortionist and Guardian Project. Golos, Ramos, all devoid creatures, tokens and keyrunes where left alone. The game was on an online server against another human player. 

<img width="825" alt="Golos_bug" src="https://user-images.githubusercontent.com/29295540/81717805-b1a18280-9483-11ea-9f37-4a8b0e4aa335.png">

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.
