### ISSUE TITLE
Improbable Alliance didn't trigger when taken control of...

### ISSUE THREAD

**Issue by DominusMaximus** [magefree/mage#6511]
1.4.43.dev_2020-05-01_00-38

Through Winota, Joiner of Forces triggers, two Agent of Treachery entered the battlefield from my library and took control of an Improbable Alliance and The Royal Scions. After combat, I activated The Royal Scions I took control of (+1: Draw a card, then discard a card). At this point, the Improbable Alliance did not trigger, even though this was my 2nd draw for the turn. On my following turn, drawing off of The Royal Scions correctly triggered the Improbable Alliance. It continued working correctly from that point on.

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.
