### ISSUE TITLE
Cabal Therapy

### ISSUE THREAD

**Issue by plelelelelelele** [magefree/mage#6515]
When Cast from graveyard, a window opens to name a card, etnering a name nad clicking choose does not do anything. palyed twice in a row.
After canceling, hand is shown.
Downloaded 2 weeks ago, so newest version.

**Comment by emerald000** [comment]
Do you have a game log or a clip of what you experienced? Things seem to work correctly over here.

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.
