### ISSUE TITLE
Prized Amalgam

### ISSUE THREAD

**Issue by plelelelelelele** [magefree/mage#6517]
After Entering the Battlefield at the end of turn and the stack is cleared, the triggered ability goes on the stack again even though the card is not in the graveyard anymore.

**Comment by theelk801** [comment]
Were there any other copies still in your graveyard?

**Comment by jeffwadsworth** [comment]
I can't recreate this.  Works fine for me.

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.
