### ISSUE TITLE
Kaheera, the Orphanguard

### ISSUE THREAD

**Issue by catman123456** [magefree/mage#6519]
in the beta is not counting as my companion

**Comment by emerald000** [comment]
Can you give the decklist you used?

**Comment by catman123456** [comment]
1 Adorned Pouncer
1 Ajani, Caller of the Pride
1 Alms Collector
1 Ancient Den
1 Ancient Tomb
1 Arid Mesa
1 Ash Barrens
1 Aura Shards
1 Balan, Wandering Knight
1 Berserk
1 Bountiful Promenade
2 Brimaz, King of Oreskos
1 Brushland
1 Cavern of Souls
1 Chord of Calling
1 Chrome Mox
1 Command Tower
1 Dryad Arbor
1 Duelist's Heritage
1 Eladamri's Call
1 Eldritch Evolution
1 Enlightened Tutor
1 Felidar Sovereign
1 Flagstones of Trokair
1 Fleecemane Lion
1 Flooded Strand
5 Forest
1 Fortified Village
1 Grafted Exoskeleton
1 Greater Good
1 Green Sun's Zenith
1 Hall of the Bandit Lord
1 Hammer of Nazahn
1 Heroic Intervention
1 Horizon Canopy
1 Idyllic Tutor
1 Inkmoth Nexus
1 Leonin Arbiter
1 Leonin Shikari
1 Leonin Warleader
1 Loam Lion
1 Lost Leonin
1 Loxodon Warhammer
1 Mana Crypt
1 Marsh Flats
1 Mirri, Weatherlight Duelist
1 Misty Rainforest
1 Mutavault
1 Nature's Lore
1 Nazahn, Revered Bladesmith
1 Path to Exile
1 Pendelhaven
2 Plains
1 Pride Sovereign
1 Prowling Serpopard
1 Qasali Pridemage
1 Rancor
1 Razorverge Thicket
1 Reflecting Pool
1 Regal Caracal
1 Sacred Cat
1 Savannah
1 Skullclamp
1 Skyhunter Skirmisher
1 Sol Ring
1 Steelshaper's Gift
1 Sunpetal Grove
1 Survival of the Fittest
1 Swiftfoot Boots
1 Sword of Feast and Famine
1 Sword of Fire and Ice
1 Swords to Plowshares
1 Sylvan Library
1 Sylvan Tutor
1 Talisman of Unity
1 Teferi's Protection
1 Temple Garden
1 Three Visits
1 Tree of Tales
1 Triumph of the Hordes
1 Umezawa's Jitte
1 Verdant Catacombs
1 Windswept Heath
1 Wooded Bastion
1 Wooded Foothills
1 Worldly Tutor
1 Yavimaya Hollow
1 Bronzehide Lion
1 King of the Pride
1 Keeper of Fables
1 Jazal Goldmane
1 Jedit Ojanen of Efrava
1 Jareth, Leonine Titan

1 Arahbo, Roar of the World
1 Kaheera, the Orphanguard

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by catman123456** [comment]
after taking out the dryad arbor it works now

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by emerald000** [comment]
Dryad is not on the list of accepted of creatures types, so all seems good here.
