### ISSUE TITLE
Demonic Pact Allows Pass by Hitting "Cancel"

### ISSUE THREAD

**Issue by dougr-code** [magefree/mage#6524]
There is an option at the bottom of **Demonic Pact** effect selection that allows a player to just hit **cancel** and continue playing. Tested  multiple times with the controller down to the last selection and they could always just pass it by hitting cancel.

Image of issue: https://imgur.com/a/ZNNwhwF

**Comment by JayDi85** [comment]
Fixed via 771d54aa39dd90d5a3642f31c348c5372dd93da9
