### ISSUE TITLE
Rielle, the Everwise misfunctions on discarding hand

### ISSUE THREAD

**Issue by BenGels** [magefree/mage#6529]
Rielle only draws you one card if you've discards your hand no matter how many cards you've discarded. It says "Whenever you discard one or more card for the first time each turn, draw that many card.

So when I discard 5, I should also draw 5, but it only draws me one card

**Comment by Zerrisx** [comment]
What specific effect resulted in you discarding your hand? I'm guessing this was fixed or documented in recent changes, see #6532.

**Comment by BenGels** [comment]
Can remember that happening with Lion's Eye Diamond, Windfall and Wheel of Fortune

**Comment by Zerrisx** [comment]
Yep, those all work now.  Addressed by 75577cdbe977948cd2f681a1082098e322290f99.
