### ISSUE TITLE
Can not play Fury of the Horde for free with Narset, Enlightened Master or Ommiscien

### ISSUE THREAD

**Issue by Steve-Python** [magefree/mage#6534]
When I play with computer with commander. I find that I can not play Fury of the Horde for free with Narset, Enlightened Master or Ommiscien.

**Comment by 18ths** [comment]
Cannot reproduce. I've tried casting Fury of the Horde with Narset, Omniscience, Omnispell Adept and Wildfire Eternal, each time I was able to cast the spell. Are you sure there wasn't something else preventing you to play it?

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.
