### ISSUE TITLE
Mistblade Shinobi's Ability Triggers for Other instances of Mistblade Shinobi

### ISSUE THREAD

**Issue by mandieck** [magefree/mage#6535]

**Comment by 18ths** [comment]
Can you give me more details? From what I understand of this short description, two of your Shinobis dealt combat damage to a player, each of them triggered each other, so you had 4 triggers of returning a creature to hand, right? 

I've tried this scenario and to be honest, I cannot reproduce it. I tried even some additional scenarios like putting clones to my 23 Shinobi deck, playing Shinobi mirror (making sure you can't trigger off of your opponents Shinobis).
