### ISSUE TITLE
Qasali Ambusher bug

### ISSUE THREAD

**Issue by LoganFlame** [magefree/mage#6540]
When I click on the card to play it with flash as per its ability, I'm not able to click the ability marked as 2. I can try and cast it with flash but it asks me to pay for its mana cost.

**Comment by 18ths** [comment]
Not sure why it was closed, because it definitely wasn't fixed yet.

**Comment by JayDi85** [comment]
I reopen it until PR #6573 merge or someone confirm that it not actual and all works fine.
