### ISSUE TITLE
Feature Request: F9 style auto- accept/no pay for cards like Rhystic Study

### ISSUE THREAD

**Issue by etpalmer63** [magefree/mage#6542]
Clicking through the Rhystic Study dialog box can become tedious. Creating an F9-style option to automatically draw a card would make things quicker. On the other hand, an auto-"no pay" for the tax, would also save dialog boxes and clicks.

**Comment by emerald000** [comment]
You can right click the Yes option and choose to always Yes that ability.

**Comment by etpalmer63** [comment]
Didn't know that. Thanks!
