### ISSUE TITLE
When hosting a match on linux client crashes on other client join

### ISSUE THREAD

**Issue by zaggynl** [magefree/mage#6550]
Log shows:

[xcb] Unknown sequence number while processing queue 
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called 
[xcb] Aborting, sorry about that. java: xcb_io.c:260: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.

**Comment by zaggynl** [comment]
Note: also happened if I joined as a second person in a 3 person match, no crash if I'm last player joining.

**Comment by zorkmead** [comment]
Experiencing the same issue after upgrade from Ubuntu 16.04 to 18.04. It is intermittent. Never experienced it under 16.04.

**Comment by JayDi85** [comment]
Problem related to graphic cards, see details [here](https://github.com/magefree/mage/issues/7594#issuecomment-782738119).
