### ISSUE TITLE
Range of Influence bugs

### ISSUE THREAD

**Issue by Zerrisx** [magefree/mage#6553]
Looks like Range of Influence is still handled incorrectly for:

- [x] World Enchantments are interacting even outside range of influence #545

- [x] Laboratory Maniac #1681

- [x] Jace, Wielder of Myseries (likely also #1681)

- [x] Casting Approach of the Second Suns twice in a four player game with range one results in both you and the player opposite you winning the game, when the game should instead continue with both of you playing (CR 801.14)

**Comment by 18ths** [comment]
are you sure about #545? I wanted to fix this issue, but I wasn't able to reproduce the issue both by writing unit test to this case and by hosting 4 player game with various Range settings. In both cases world enchantments worked correctly.

**Comment by Zerrisx** [comment]
I created a deck with all the world enchantments in it and played in a four person range 1 free-for-all with three AIs; the enchantments I played killed off those of both adjacent players, but not the player opposite me.  I forget which exact ones, but I could fairly easily go get a screenshot of an example if you'd like.

**Comment by Zerrisx** [comment]
> 
> 
> are you sure about #545? I wanted to fix this issue, but I wasn't able to reproduce the issue both by writing unit test to this case and by hosting 4 player game with various Range settings. In both cases world enchantments worked correctly.

Figured it out; I just wasn't thinking straight.  Specifically, the rule is:

_801.12 The “world rule” (see rule 704.5k) applies to a permanent only if other world permanents are within its controller’s range of influence._

Whereas currently, any world enchantment is causing any other world enchantment to go to the graveyard, _including ones outside the range of influence_, which is the bug.
