### ISSUE TITLE
IKO cards

### ISSUE THREAD

**Issue by PandaBionico** [magefree/mage#6559]
can i import Cunning Nightbonder, and slitherwisp since they are finished and do not use new mechanics? if so, how would i do it? thank you

**Comment by gp66** [comment]
Most IKO cards are available to play on the beta server. 
[http://xmage.today/](url)

**Comment by superwill123** [comment]
> Most IKO cards are available to play on the beta server.
> [http://xmage.today/](url)

The link does not bring you to any kind of page that you can download the beta client from, are you sure this is the right link?

**Comment by JayDi85** [comment]
@superwill123 page have "download full beta client"

![shot_200531_095503](https://user-images.githubusercontent.com/8344157/83345507-e8511700-a324-11ea-9ccd-e12d505bbbcd.png)

**Comment by superwill123** [comment]
This is the page that I am brought to when I click on the link. where would one go to get to this beta client page? 
![image](https://user-images.githubusercontent.com/64988489/83345562-8a9bdb00-a2e2-11ea-8d52-b094078c591f.png)

**Comment by JayDi85** [comment]
@superwill123 I see. There were error in gp66's comment -- fixed it now.

**Comment by superwill123** [comment]
That's the correct link, thanks a million!

**Comment by Zerrisx** [comment]
Resolved
