### ISSUE TITLE
Cards with two triggered abilities that trigger at the same time do not specific which trigger is which when placing on the stack

### ISSUE THREAD

**Issue by dylan1020** [magefree/mage#656]
This has happened with both Seeker of the Way and Jeskai Ascendency. This is not always relevant, but I am sure there is a corner case where it is relevant the trigger order, especially with Jeskai Ascendency.

**Comment by Alchus** [comment]
The tooltip explains the effect associated with each trigger, even if the triggers have the same name.
![screenshot 2015-01-03 23 51 09](https://cloud.githubusercontent.com/assets/10366239/5604913/98f19040-93a3-11e4-884b-7948c1aeee65.png)

**Comment by dylan1020** [comment]
Thank you, I have the tooltips turned off so that is why.
