### ISSUE TITLE
BETA CLIENT - Server Error: Card not found

### ISSUE THREAD

**Issue by Francy333** [magefree/mage#6560]
Hello, me and my friends keep getting this error on the beta server when we try to create a game.

Server error: card not found.

This errors happens with any card from any set.

Every now and then it's back to normal, but lately this errors appears most of the time, preventing us from creating any games.

ps: client version is up to date.

![1](https://user-images.githubusercontent.com/56952748/82437206-52e99380-9a97-11ea-8e37-4933d744ef2d.PNG)

**Comment by JayDi85** [comment]
Server restarted

**Comment by Francy333** [comment]
Hi, could you please restart it again? The bug just came back :)

**Comment by JayDi85** [comment]
Restarted

**Comment by Francy333** [comment]
Thanks!

**Comment by Francy333** [comment]
Hello JayDi85, sorry to bother you again, but would it be possible to restart the server? Thanks!

**Comment by JayDi85** [comment]
Beta server updated to latest developer version and restarted.

**Comment by Francy333** [comment]
Could you kindly restart the server? Thanks!

**Comment by JayDi85** [comment]
Restarted
