### ISSUE TITLE
Inner Flame Igniter does not give first strike on third resolution

### ISSUE THREAD

**Issue by dashosa** [magefree/mage#6562]
![image](https://user-images.githubusercontent.com/63882410/82510988-0b382b80-9ada-11ea-864a-fea4bdf95320.png)

**Comment by emerald000** [comment]
On which version did this happen? The card went through changes since the last release and should work correctly in the beta version.

**Comment by dashosa** [comment]
Hi, this was in the beta, the newest version.

**Comment by dashosa** [comment]
I noticed that the same thing happens with Ashling, the Igniter and Incandescent Soulstoke in the beta

**Comment by emerald000** [comment]
Just noticed the Beta version is before the latest patch to those cards. I tested on master and they work as expected.
