### ISSUE TITLE
Zirda does not Reduce Tilonalli's summoner ability by 2

### ISSUE THREAD

**Issue by dashosa** [magefree/mage#6563]
![image](https://user-images.githubusercontent.com/63882410/82579279-90aff000-9b5b-11ea-885d-41a67c5378f5.png)
![image](https://user-images.githubusercontent.com/63882410/82579325-a1606600-9b5b-11ea-855d-55db02537858.png)
![image](https://user-images.githubusercontent.com/63882410/82579392-bc32da80-9b5b-11ea-8434-9f2342efb49b.png)

**Comment by emerald000** [comment]
Tilonalli's Summoner has a triggered ability, not an activated ability.
