### ISSUE TITLE
Cards that alter card text

### ISSUE THREAD

**Issue by peter-thoenen** [magefree/mage#6565]
"Cards that alter card text happen to be beyond the limits of the current Xmage framework, so you probably shouldn't expect them to be implemented anytime soon.

_Originally posted by @Zzooouhh in https://github.com/magefree/mage/issues/4801#issuecomment-382822616_"

Is there a bug or feature number tracking this?  It's an ancient mechanic and has to be way easier to implement than the new champions.    Also it comes up enough as see in the latest "card request" on the forum: https://www.slightlymagic.net/forum/viewtopic.php?f=70&t=20685&sid=77d8ea4b941d1abc103e98ffeb166f3e&start=315#p243166

It really hurts decks that use Painter or want to do clever things with Choke, Karma, Blood Moon, etc.

**Comment by Zerrisx** [comment]
As far as I can tell from a quick search, #2082 #4202 #4440 #6413. (Not counting the times it shows up in collected issues by version)

I'll probably group these into a master issue when I get to them in my old issue clean-up project that I'm working on.

**Comment by peter-thoenen** [comment]
Ahh i missed #2082 completed, your seasrch foo better than mine. Will close this one and subscribe to that one.
