### ISSUE TITLE
setCastSourceIdWithAlternateMana allows casting without additional non-mana costs

### ISSUE THREAD

**Issue by etpalmer63** [magefree/mage#6580]
For several cards with exile and allow casting without paying mana costs, additional non-mana costs such as discard or sacrifice, are not required to cast spells. So far, I have tested and found it applies to cards: Narset, Englightened Master  and Golos, Tireless Pilgrim. I suspsect that many cards using the code:
`setCastSourceIdWithAlternateMana(objectId, null, card.getSpellAbility().getCosts());`
may have similar issues. I will do additional testing and follow-up with a longer list. 

In the game log in the  images you can see that the discard for Cathartic Reunion, and the sacrifice a permanent for Angelic Purge, were not required. 
![XMageIssue-1](https://user-images.githubusercontent.com/24531086/83056885-fcd29e00-a00a-11ea-980f-6fc39981ec39.png)
![XMageIssue-2](https://user-images.githubusercontent.com/24531086/83056894-ffcd8e80-a00a-11ea-9da6-af9539a894d8.png)

**Comment by etpalmer63** [comment]
It works in Bolas's Citadel. Looks like its an issue of how its implemented and I will need to check each card with the code individually.

**Comment by JayDi85** [comment]
It can be related to different `applies` call and overrides in that cards (with affectedAbility and without it).

![shot_200608_232958](https://user-images.githubusercontent.com/8344157/84072616-83f71d00-a9e0-11ea-9b8e-88c563f27cfd.png)

**Comment by etpalmer63** [comment]
The following cards have bugs:

- [ ] Fallen Shinobi 
In the second log, when Tormenting Voice is cast first, the discard was required. In the first log, when it was cast after Angelic Purge the discard was not required. 
![FallenShinobi1](https://user-images.githubusercontent.com/24531086/84174751-d9104e80-aa33-11ea-84da-113cd4a72792.png)
![FallenShinobi2](https://user-images.githubusercontent.com/24531086/84174764-e0375c80-aa33-11ea-93c5-763c2c904376.png)


- [ ] Ignite the Future
Tormenting Voice and Cathartic Reunion are not requiring discard. The order doesn't seem to matter. The sacrifice required for Angelic Purge seems to work correctly in all instances. 
![IgniteTheFuture3](https://user-images.githubusercontent.com/24531086/84175219-82574480-aa34-11ea-8f8d-f681d4dffac7.png)
![IgniteTheFuture1](https://user-images.githubusercontent.com/24531086/84175223-83887180-aa34-11ea-81dd-2579cd115a4c.png)
![IgniteTheFuture2](https://user-images.githubusercontent.com/24531086/84175224-83887180-aa34-11ea-9f8a-ab8364d042e2.png)

**Comment by etpalmer63** [comment]
- [ ] Sins of the Past
Casting Cathartic Reunion did not work correctly, discard was not required. 
![SinsOfThePast](https://user-images.githubusercontent.com/24531086/84577263-b356b280-ad6f-11ea-9f03-d0694271fde1.png)

- [ ] Spelljack
Casting Cathartic Reunion did not work correctly, discard was not required. 
![Spelljack](https://user-images.githubusercontent.com/24531086/84577314-25c79280-ad70-11ea-860e-a2172c49858f.png)

- [ ] Temporal Aperture
Demon of Catastrophes was cast without requiring a sacrificed creature. 
![TemporalAperture](https://user-images.githubusercontent.com/24531086/84577335-47c11500-ad70-11ea-9a62-47b2f664b5f1.png)
 

I quickly checked the following cards and found them all working as they should. 
 

- IntetTheDreamer
- KheruSpellsnatcher 
- MagusOfTheMind
- MindsDesire  
- NarsetEnlightenedMaster 
- NicolBolasGodPharaoh 
- OraclesVault
- PlaneswalkersMischief
- ReleaseToTheWind 
- ScourgeOfNelToth 
- StolenGoods 
- UrzaLordHighArtificer
- WorldheartPhoenix

**Comment by LevelX2** [comment]
@etpalmer63 
If possible please test if all problems are resolved.
