### ISSUE TITLE
Goad forgets who controlled goading source

### ISSUE THREAD

**Issue by SpikesCafe-google** [magefree/mage#6581]
In a game of commander, my opponent gained control of Marisi, Breaker of Coils (until end of turn) and did combat damage to another player. This caused the creatures damaged by Marisi's controller to be goaded. However, when the goaded creatures went to attack, they could not attack me but could attack the (former) controller of Marisi. 

https://github.com/magefree/mage/blob/f6826506509e9c0aed230ab4ec805528bd628441/Mage/src/main/java/mage/abilities/common/GoadAttachedAbility.java#L70

**Comment by jeffwadsworth** [comment]
I was testing Marisi, Breaker of Coils today and used Donate to pass control of it to an opponent.  When that opponent attacked me with Marisi, Breaker of Coils (undefended), the trigger gave both of my test creatures goad.  During my turn, I was unable to attack the  new controller of Marisi, Breaker of Coils (correct behaviour), but I was forced to attack another opponent.  So, this all worked correctly.  I will test with other control spells tomorrow.  What was used to gain/pass control of the Marisi, Breaker of Coils?

**Comment by SpikesCafe-google** [comment]
Thanks for investigating! It was some sort of Threaten effect where the "gains control" effect ended at end of turn. It seems like goad evaluates who the source's *current* controller is, rather than the source's controller at the time of the goading event.

**Comment by jeffwadsworth** [comment]
Yes, definitely a bug.  Used Act of Treason.  I have a fix, just testing.
