### ISSUE TITLE
 Itlimoc, Cradle of the Sun bug

### ISSUE THREAD

**Issue by DJKoVid** [magefree/mage#6584]
1. Itlimoc, Cradle of the Sun doesn't tap for # creatures, it just taps for one. 
2. Emrakul, the Promised End can't access the opponents hand.

Thank you.

**Comment by jeffwadsworth** [comment]
![WorksFine](https://user-images.githubusercontent.com/1496996/84154539-dbbb7580-aa2c-11ea-9682-a2dcb1c07766.jpg)

**Comment by DJKoVid** [comment]
Thank you!

**Comment by jeffwadsworth** [comment]
The target opponent's turn control ability works for me as well.
![WorksFine](https://user-images.githubusercontent.com/1496996/84155143-9a779580-aa2d-11ea-8a4e-07b3c3baa0d2.jpg)

**Comment by jeffwadsworth** [comment]
![WorksFine](https://user-images.githubusercontent.com/1496996/84155342-dad71380-aa2d-11ea-9d38-dc976988e9ad.jpg)

**Comment by jeffwadsworth** [comment]
I played the Swamp for the opponent, etc.

**Comment by DJKoVid** [comment]
It still just taps for 1. am i missing an update?

**Comment by Zerrisx** [comment]
Emrakul issue is a duplicate of #2088, and the Cradle issue is fixed.
