### ISSUE TITLE
Torbran not triggering extra damage off Kumano's ping ability

### ISSUE THREAD

**Issue by kozelk** [magefree/mage#6589]
With Torbran on the field, I activated Kumano's ping ability and it didn't trigger the 2 additional damage from Torbran.

**Comment by johnmeat** [comment]
Were there any other effects in play? Can you recreate this issue?
I tried this and it worked as expected:

![image](https://user-images.githubusercontent.com/64497504/83654093-8575af00-a5b4-11ea-8935-8ed8f7f72387.png)

**Comment by kozelk** [comment]
No. I was targeting a zombie copy created by scarab God, but no effects
that should have reduced damage.

**Comment by johnmeat** [comment]
Still worked on a zombie created by Scarab God:
![image](https://user-images.githubusercontent.com/64497504/83656249-38dfa300-a5b7-11ea-9fbe-e47d08e0669a.png)

**Comment by kozelk** [comment]
I'll go back through the decks and see if I missed something
