### ISSUE TITLE
Scale text size on abilities with preview image size

### ISSUE THREAD

**Issue by JeffHoogland** [magefree/mage#659]
Small enhancement request. When the preview is large, the text on ability previews is still small. Would be ideal if it scaled a bit. See image below for example.

![image](https://cloud.githubusercontent.com/assets/3093360/5591081/ffcd464e-910d-11e4-99b7-57eee81223ab.png)

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.
