### ISSUE TITLE
Companion cards do not work and other Card Issues

### ISSUE THREAD

**Issue by Makaveli69** [magefree/mage#6591]
- [x] Ability of Spell Queller does not trigger when coming into play.
    LevelX: Can't reproduce, works fine in my test. Any special conditons?

- [x] Companion cards do not work.

- [x] Card The Ozolith is missing.
    LevelX: Don't create issues for card implementation demands.

**Comment by LevelX2** [comment]
Tested now companion cards and they work in dev environment.
