### ISSUE TITLE
Cards not disappearing from battlefield

### ISSUE THREAD

**Issue by emerald000** [magefree/mage#660]
Here is a weird one. Two of my creatures died to Inferno Titan ETB ability. Somehow, the card images didn't disappear from the battlefield:

![Bug1](http://i.imgur.com/MyUAc4n.jpg)

Notes:
* My opponent said it was looking correctly from his point of view.
* The cards appeared normally in the graveyard.
* The images on the battlefield stayed for the whole game, but weren't there anymore in the next game.
* I could not interact with the cards in any way (attack, block). They didn't untap either. It's like they were "burned" in the background.
* The battlefield layout didn't care about those cards. Here's an image taken later in the game:

![Bug2](http://i.imgur.com/ydLozju.jpg)

I am confused about what could have happen, as it is the first time I hear something similar.

**Comment by LevelX2** [comment]
Seems not to happen again, so I close this now.

**Comment by fireshoes** [comment]
I'm not sure if related, but for some time, I have been seeing a syncing issue. Like if there is a wrath, the creatures go to the graveyard momentarily, then at least some show back up on the battlefield until we go to the next phase and then they disappear again.

**Comment by LevelX2** [comment]
How to reproduce?
