### ISSUE TITLE
Combined Spell Cost Bugs

### ISSUE THREAD

**Issue by Zerrisx** [magefree/mage#6603]
When two spells are cast as a single spell (Fuse, Splice), total cost should be determined first before taxes and discounts are applied.  Currently, this is not the case, and taxes/discounts are applied to each piece individually.  This results in a few bugs, including the following:

- [x] Council of the Absolute (and equivalent cost reducers) don't act on the full spell.  If you name "Armed", a fused Armed//Dangerous *should* cost just 2RG, but Council only discounts the Armed half of the cost, so it charges 3RG instead.  If you name Thoughtseize and then splice Everdream onto it, you *should* only have to pay BU, but instead you get charged 2BU.
#227, mentioned in #6549

- [x] Thalia, Guardian of the Thraben (and equivalent taxes) add {1} to each piece of the spell - if you fuse something, you have to pay {2}.  If you splice a card, you pay {2}.  If you splice two cards, you pay {3}.  It *should* always just add {1}.
#6493, mentioned in #5155 and #6549

- [x] Trinisphere is getting applied to each piece of a fused card or spliced card, when it *should* only apply afterwards if the total cost is still under {3}.
#2242

**Comment by JayDi85** [comment]
Fixed via https://github.com/magefree/mage/commit/b38ac2f575c3da161f98ac3fdc2048c9fc446169 and https://github.com/magefree/mage/commit/a75d08283fb8f9ea143363bda0940167dc0ca504

If you found bug with splice/fused then report here. Potentially bugged (need to test):
* split-fused and spliced cards with additional cost like sacrifice/pay life and cost modification effect (is cost applied, is spell ask to pay additional cost).
* split-fused and spliced cards with target adjusters (search source code for `implements TargetAdjuster`).
