### ISSUE TITLE
Can't draft sealed with new set

### ISSUE THREAD

**Issue by zachlloyd01** [magefree/mage#6610]
Drafting is broken

**Comment by Mikalinn777** [comment]
Sorry but that isn't very descriptive. If you could elaborate on your issue I'm sure someone could help.

**Comment by thedocdoctor** [comment]
When I tried to draft sealed, both players only received the non-basic lands found in the pool. 4-6 lands usually. Ikoria. Didn't try anything else.

**Comment by emerald000** [comment]
Ikoria isn't implemented yet on the main release. Try the beta version.

**Comment by thedocdoctor** [comment]
I'm on the beta

**Comment by JayDi85** [comment]
@thedocdoctor show your "new draft sealed" settings dialog

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.
