### ISSUE TITLE
Carpet of Flowers, academy ruins 

### ISSUE THREAD

**Issue by DJKoVid** [magefree/mage#6621]
1. Carpet of flowers should generate mana on both main phases but only generates on main phases 1. 

2. Academy ruins' tap to return artifact to top of library ability cannot be activated.

**Comment by jeffwadsworth** [comment]
Carpet of Flowers works fine.  Note, you can only use it once per turn.
Academy Ruins works fine.  Tested with multiple artifacts in the graveyard.  Note, if you don't have a legal target, it can't be activated.
