### ISSUE TITLE
Always use the standard order for displaying mana colors

### ISSUE THREAD

**Issue by allentiak** [magefree/mage#6628]
Currently, activated and land mana abilities that support choosing any (one) mana color use a non-standard order (GUBRW) for displaying their options. However, they should use the standard mana color order (CWUBRG).
_(See https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=476232.)_
![Mana Ability--Incorrect Color Order](https://user-images.githubusercontent.com/1922297/84341976-d2402380-ab7a-11ea-8be0-aab3cc8ba668.png)

**Comment by hitch17** [comment]
I'm not sure where else this is used, but if it's only the one place in the PR, I think this can be closed.

**Comment by allentiak** [comment]
Thanks, @hitch17 !
