### ISSUE TITLE
Time display in game log not displayed correctly.

### ISSUE THREAD

**Issue by LevelX2** [magefree/mage#6633]
Latest master shows the turn log time a little bit strange extended!

![grafik](https://user-images.githubusercontent.com/2066790/84491942-a66d8c80-aca5-11ea-9b7d-252ffe39ce3f.png)

**Comment by JayDi85** [comment]
What you mean by "not correctly"?

T1, T2 is turn/step for event/message. It can be disabled by preferences.
T0 for events before game started (that's not correctly?)
Time format must depended on user system's time settings (24 or 12 hours format).

**Comment by LevelX2** [comment]
You're right, it's no bug it's a feature.  :-)
I was not aware of yet.
