### ISSUE TITLE
Can't cast Karn's Temporal Sundering when exiled with Golos, Tireless Pilgrim

### ISSUE THREAD

**Issue by Kwhorstkamp** [magefree/mage#6635]
Can't cast Karn's Temporal Sundering when exiled with golos etb trigger,

**Comment by LevelX2** [comment]
I guess you mean the activated ability instead of the etb trigger that can only search for land.

**Comment by LevelX2** [comment]
Can't reproduce the problem.
Any more information about the situation?

**Comment by jeffwadsworth** [comment]
![WorksFine](https://user-images.githubusercontent.com/1496996/84662939-15cfc000-aee2-11ea-9393-24529b436764.jpg)

Works fine here.
