### ISSUE TITLE
Computer Players should be Selectable only in Compatible Game Types

### ISSUE THREAD

**Issue by allentiak** [magefree/mage#6647]
Whereas I might be wrong on the specifics, I think the following examples apply:
- "Computer - Draftbot" should be selectable only in Draft games.
- "Computer - mad" should be selectable only in Non-Draft games. (Although I think it should be used during gameplay once a deck has been created in Draft and Sealed games with the previous AI.)

As a player, I have made the mistake of selecting "Draftbot" for Constructed games (which results in an error, BTW). I shouldn't have been able to select such AI at all.

**Comment by JayDi85** [comment]
Nope. 
* Draftbot is simpler AI realization -- he can't think and play, only choose cards (e.g. for draft part only). Also it uses for real players replace in drafts after disconnects (to complete draft). In real game it will be loose the game immidiatly;
* Mad and other are full AI realization with card play and other choose dialogs compatible.

Players can choose draft AI to train draft games (draft part only).

**Comment by allentiak** [comment]
> As a player, I have made the mistake of selecting "Draftbot" for Constructed games (which results in an error, BTW). I shouldn't have been able to select such AI at all.

@JayDi85 This still holds true...
