### ISSUE TITLE
Some Wiki pages renamed

### ISSUE THREAD

**Issue by allentiak** [magefree/mage#6648]

**Comment by allentiak** [comment]
Relevant to #6197

**Comment by allentiak** [comment]
@JayDi85  As a first step, I am trying to update the project dependencies, but it's such a huge work...

**Comment by allentiak** [comment]
BTW: I updated the [Developer Notes](https://github.com/magefree/mage/wiki/Developer-Notes), but there is still room for improvement.

**Comment by allentiak** [comment]
@JayDi85 I mean: I _overhauled_ the main Wiki pages (but there is still room for improvement).

**Comment by JayDi85** [comment]
@allentiak don't change wiki pages links anymore. All links to devs pages are broken. Also you are wipe out all pages change history. That's very bad.

**Comment by allentiak** [comment]
I've just fixed the links.

**Comment by allentiak** [comment]
@JayDi85  In case you find any other broken links, just let me know and I'll fix them.

**Comment by allentiak** [comment]
The pages were outdated and/or redunndant.

**Comment by JayDi85** [comment]
You should have update existing ones, not delete them.

**Comment by allentiak** [comment]
I did. (In fact, I renamed some of them, and that's why they appear as
new.) Shall we continue this discussion over email?

**Comment by JayDi85** [comment]
Rename basic pages to old one. This is "external links" (landing pages) and they should work:
* Developer-Getting-Started
* Developer-HOWTO-Guides

**Comment by allentiak** [comment]
Where are the broken links, exactly? If you point me to them, I can fix them.

**Comment by allentiak** [comment]
The only incoming link from XMage's website I could find is https://github.com/magefree/mage/wiki/Release-changes, and it works.
Are you referring to a link from another website? Could you please point me to it?

**Comment by allentiak** [comment]
I have fixed a couple of broken links in https://github.com/magefree/mage/wiki/Setting-up-your-Development-Environment#where-to-go-from-here and in https://github.com/magefree/mage/wiki/Development-HOWTO-Guides.
Please, do let me know if you find any other.

**Comment by JayDi85** [comment]
See my comment above -- that's basic links/pages uses in issues and outside of github (reddit, discord, gitter) to redirect people to developer page.

What you must do:
1. Rename two basic pages to old names:
* `Setting-up-your-Development-Environment` to `Developer-Getting-Started`;
* `Development-HOWTO-Guides` to `Developer-HOWTO-Guides`
2. Open each developer pages (can start from getting started page) and checks all links in it. It must works. Example:
![shot_200616_071352](https://user-images.githubusercontent.com/8344157/84727824-f8156000-afa0-11ea-9a9b-6ef740a55d38.png)

**Comment by allentiak** [comment]
What about pointing to the Wiki home page? That page name won't change,
ever. Whereas any other page will, eventually.

**Comment by allentiak** [comment]
Fixed.

**Comment by allentiak** [comment]
Almost.

**Comment by JayDi85** [comment]
Dozens of reddit's posts, github and forum comments contains broken links now and you can't change all of them.

I'll rename and fix wiki-pages by myself today. After that you can continue to edit it.

**Comment by allentiak** [comment]
3'

**Comment by allentiak** [comment]
Sorry. I didn't know there were external links that pointed to those pages. I've created placeholders so people can go to the correct page names.
I strongly suggest you to make all external links to point to the wiki Home, as that page name will likely never, ever change. (The other pages are very likely to change, and any other contributor can end up exposing the bug, just like me.)

**Comment by allentiak** [comment]
Fixed.

**Comment by allentiak** [comment]
@JayDi85 And thank you for your patience! :-)
