### ISSUE TITLE
Visual: Blocking arrows sometimes have gaps

### ISSUE THREAD

**Issue by Zerrisx** [magefree/mage#6658]
When I attack in the following manner
![image](https://user-images.githubusercontent.com/59861365/84938445-e1efc880-b0a2-11ea-95d5-37beae95f55a.png)

And then activate Coils of the Medusa, killing both the Flying Men, the attack arrow on the right-hand wall of wood gets redrawn incorrectly:
![image](https://user-images.githubusercontent.com/59861365/84938543-0a77c280-b0a3-11ea-9a14-529ddbbe5a1c.png)

I also get it with the following blocks:
![image](https://user-images.githubusercontent.com/59861365/84939237-a6a1c980-b0a3-11ea-85d5-cc51520f0ca5.png)

**Comment by JayDi85** [comment]
@xenohedron is that visual bug with arrows still actual?

**Comment by JayDi85** [comment]
It’s from 2020. Arrow code changed after that, so it can be already fixed.

Bugged cards (declared and targeted) must be put at the same visual column, so no “free space” for full arrow rendering:

![IMG_0797](https://github.com/user-attachments/assets/c9b35813-c804-49af-8764-def8374d20c3)
![IMG_0798](https://github.com/user-attachments/assets/c17ec6d0-058b-4f00-9a55-4637e8b87959)

**Comment by xenohedron** [comment]
I haven't seen this bug anytime recently. But if it still exists, it might only be reproducible in specific scenarios depending on size of battlefield permanents / precise location of blocking arrows.
