### ISSUE TITLE
Choking Vines doesn't block things properly

### ISSUE THREAD

**Issue by Zerrisx** [magefree/mage#6659]
I tried to block a variety of creatures with Choking Vines, and it seems to block some of them... sometimes.  But not most.

Here's a full attack:
![image](https://user-images.githubusercontent.com/59861365/84940906-2e88d300-b0a6-11ea-9d66-b1ea51cb70a4.png)

These creatures are, respectively, Trample (6), First strike (4), Lifelink (3), Doublestrike (1, 1), and Unblockable (1).  Since they all have different power, it's relatively easy to track them in the combat log.  Note that the unblockable creature should still be able to be blocked, per Choking Vines' 10/4/2004 ruling.  The trample creature should hit for full damage.

As a result, I expect to take 6 damage.

![image](https://user-images.githubusercontent.com/59861365/84940866-1fa22080-b0a6-11ea-8d7f-7be747b06c59.png)

Instead, I've taken hits from every single one of them except the Benthic Infiltrator.

**Comment by arcox** [comment]
Thanks, I'll look into it.
