### ISSUE TITLE
Fate Reforged boosters may only have basic lands if those cards are foil.

### ISSUE THREAD

**Issue by Alchus** [magefree/mage#666]
Looking at http://magic.wizards.com/en/articles/archive/feature/fetching-look-fate-reforged-2014-12-24
The text at the bottom says
"Other languages will typically not contain basic lands"
But FRF does have its own basic lands: http://magic.wizards.com/en/articles/archive/arcana/fate-reforged-basically-2015-01-05
We know that when seeding a booster, a foil replaces a common unless it is a foil basic land, in which case it replaces the land slot. I believe we should interpret this to mean that the land slot in FRF boosters can contain exactly one of {nonfoil gainland, nonfoil fetchland, foil basic}. Foil nonbasics take up a common slot.

I don't know if the current booster seeding algorithm calculates foil probabilities, and even if it does, this will probably be a unique case, as Dragon's Maze did not have foil basics in booster packs.

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.
