### ISSUE TITLE
Morph put face up ability assigned twice

### ISSUE THREAD

**Issue by LevelX2** [magefree/mage#6663]
Seems like the Morph put face up ability is assigned twice to the permanent.
At least for Kheru Spellsnatcher.

![grafik](https://user-images.githubusercontent.com/2066790/85037558-d4f7d580-b185-11ea-8a0f-6259c2dc3e93.png)

**Comment by jeffwadsworth** [comment]
It occurs on all Morph cards when cast with the Morph ability.
