### ISSUE TITLE
UX Enhancement: Automatically order self-contained replacement effects

### ISSUE THREAD

**Issue by Zerrisx** [magefree/mage#6676]
The cards listed below will *always* trigger two replacement effects simultaneously.  These replacement effects can never (as far as I know) be dependent on each other, so the order is irrelevant, but it still results in the player having to deal with the ugly / annoying replacement effects dialogue box every time they cast them.

![image](https://user-images.githubusercontent.com/59861365/85174281-ac7de300-b23a-11ea-8ea7-aa83066fcbab.png)

For these cards (and any future cards with ETB tapped and an as-enters effect), if their self-contained replacement effects are the only ones that are applying, we should order them automatically without player input.

Notably, the Vivid lands and Sphere of the Suns already do this properly, so you could check their code to see how it's done.

- [ ] Arixmethes, Slumbering Isle

- [ ] Coldsteel Heart

- [ ] Hickory Woodlot 

- [ ] Peat Bog

- [ ] Remote Farm

- [ ] Sandstone Needle

- [ ] Saprazzan Skerry

- [ ] Thriving Bluff

- [ ] Thriving Grove

- [ ] Thriving Heath

- [ ] Thriving Isle

- [ ] Thriving Moor

**Comment by JayDi85** [comment]
Implemented in c9ab896d2490382ed9c0d768431aa81ce683aecf.

Use "remember answer" checkbox in choose replacement effect dialog to save it.
![shot_210809_111035](https://user-images.githubusercontent.com/8344157/128672486-f4d2e81e-c7c5-4ab9-9c5e-c54635a1e58d.png)

Two remember modes possible:
* remember different answers for each object (object + text - you can save different answers for different objects);
* remember for same objects (text - you can save one answer for all objects with same name).

Remember modes can be changed in Preferences dialog. If you call it by "step button" then it will be applied immediately in the game (as all other priority settings, etc):
![shot_210809_111159](https://user-images.githubusercontent.com/8344157/128672749-fdf479cc-f99f-4c88-9987-29befde4fb20.png)

All replacement answers can be reset by battlefield menu (right click on your battlefield to see popup menu).
