### ISSUE TITLE
Format check is not working always 

### ISSUE THREAD

**Issue by LevelX2** [magefree/mage#668]
Sometimes the format check while joining a table does not work correctly.
So players are able to join a table with cards that are now allowed for the format of the table.

It's no new bug because I can remember that this happens sporadic already for a long time.

http://www.slightlymagic.net/forum/viewtopic.php?f=70&t=16358&start=105#p170835
http://www.slightlymagic.net/forum/viewtopic.php?f=70&t=16358&start=90#p170528
http://www.slightlymagic.net/forum/viewtopic.php?f=70&t=16358&p=170586#p170770

Any hints when and why this happens are welcome.

**Comment by emerald000** [comment]
At the very least, you can add a Judge Promo Noble Hierarch to your standard deck and pass the legality check.

It might have something to do with the 2-4 letters set code.

**Comment by LevelX2** [comment]
I can't reproduce the Noble Hierarch problem:
![standardnoble](https://cloud.githubusercontent.com/assets/2066790/5635961/fede5928-95ed-11e4-90cf-d9eb80a92ea1.jpg)

**Comment by emerald000** [comment]
My bad. I was adding JR cards to a deck on v7, but didn't realize those cards weren't getting saved.

No idea what happens then. Is the check done server-side or client-side? If client-side it would be possible to accept all decks before compiling your own version.

**Comment by troyready** [comment]
I think this falls under the same issue here, but I'm unable to use certain promo cards (all?) in formats that they are legal in. I've specifically tried the Memnite promo from set MGDC, which gives me an 'must contain at least 60 cards' error.

**Comment by fireshoes** [comment]
troyready, that is an issue with loading cards from sets with 2 or 4 letter abbreviations. The fix is applied for the next update.

**Comment by troyready** [comment]
Ah, great, thanks!

**Comment by fireshoes** [comment]
Saw Seifer using Decree of Pain and Cabal Coffers in a modern match today. This was after another user commented about him using cards that weren't standard legal in their match that had just ended.

**Comment by emerald000** [comment]
I created a Standard game and somebody arrived with a full Modern deck. I saw the following illegal cards:

Bloodchief Ascension
Arid Mesa
Blood Crypt
Hellspark Elemental
Blightning
Volcanic Fallout
Scalding Tarn

I double-checked on the Tables view and it was indeed a Constructed - Standard match.

**Comment by emerald000** [comment]
Spent some time looking into this problem today after I saw Seifer playing some more random illegal cards. 

My guess was that there could be some differences between the deck validator and the deck loader. But when you join an event, your deck is load directly from file, then checked for validation, then loaded into the game. So nowhere for the deck to change.

Otherwise, I am quite confused how this possibly happens. It would be great if somebody else could also check about this, as I am running out of ideas.

**Comment by LevelX2** [comment]
I also checked this more than once.
I don't see a way how to cheat this.

So I guess it's caused by some bug.

Maybe we can add some logging that can help to find the reason.

**Comment by fireshoes** [comment]
Seifer joined my standard match. I Thoughtseized him on turn one. He had 2 Wooly Thoctar, Vexing Devil, Loam Lion, Jungle Shrine, and Sacred Foundry in hand. Attached gamelog in case there is anything to be gained by it.

<html>
  <head>
    
  </head>
  <body>
    <font color="#CCCC33">07:40: </font><font color="Orange">fireshoes has 
    joined the game</font>
<font color="#CCCC33">: </font><font color="Orange"><br><b>Match score:</b><br>fireshoes 
    - 0 wins<br>Seifer - 0 wins<br><br>You have to win 2 games to win the 
    complete match<br><br>Game has started<br><br></font>
<font color="#CCCC33">07:40: </font><font color="White">Seifer shuffles his or 
    her library.</font>
<font color="#CCCC33">07:40: </font><font color="White">fireshoes shuffles his 
    or her library.</font>
<font color="#CCCC33">07:40: </font><font color="White">fireshoes won the toss</font>
<font color="#CCCC33">07:40: </font><font color="White">fireshoes chooses that 
    he or she takes the first turn</font>
<font color="#CCCC33">07:40: </font><font color="White">fireshoes draws seven 
    cards</font>
<font color="#CCCC33">07:40: </font><font color="White">Seifer draws seven 
    cards</font>
<font color="#CCCC33">07:40: </font><font color="White">fireshoes keeps hand</font>
<font color="#CCCC33">07:40: </font><font color="White">Seifer keeps hand</font>
<font color="#CCCC33">07:40: </font><font color="Orange">Turn 1 fireshoes (20 
    - 20)</font>
<font color="#CCCC33">07:40: </font><font color="White">fireshoes plays Swamp</font>
<font color="#CCCC33">07:40: </font><font color="White">fireshoes casts 
    Thoughtseize targeting Seifer </font>
<font color="#CCCC33">07:40: </font><font color="White">Seifer reveals Sacred 
    Foundry, Vexing Devil, Woolly Thoctar, Woolly Thoctar, Forest, Loam Lion, 
    Jungle Shrine</font>
<font color="#CCCC33">07:40: </font><font color="White">fireshoes loses 2 life</font>
<font color="#CCCC33">07:40: </font><font color="White">Seifer discards Vexing 
    Devil</font>
<font color="#CCCC33">07:47: </font><font color="White">Seifer has won the game</font>
<font color="#CCCC33">07:47: </font><font color="White">fireshoes has lost the 
    game.</font>
  </body>
</html>

**Comment by LevelX2** [comment]
Checked if there is a way to cheat if you manipulate the dck file or the client.
But I think it's not possible this way.
Only set code and cardnumber are used to get the card from server db.
And the setcode and name of the card found in server db is used to format check.
So no idea yet.

**Comment by LevelX2** [comment]
Reports of this problem:
http://www.slightlymagic.net/forum/viewtopic.php?f=70&t=17365&p=182496#p182496

**Comment by Zerrisx** [comment]
Have we seen this issue at all in recent times?  I think it might be resolved, but is difficult to test for.

**Comment by JayDi85** [comment]
There were fix for cards search and promos 1-2 years ago (some players was able to use some rare illegal cards). But I don't remember the details. I think it was related for this issue (reports that some players saw illegal cards).

So it must be fixed.
