### ISSUE TITLE
Hogaak, Arisen Necropolis - can't pay convoke

### ISSUE THREAD

**Issue by JayDi85** [magefree/mage#6680]
Bug report from forum:

Hello, I was playing against a human in legacy and I couldn't cast Hogaak, Arisen Necropolis from my graveyard at any point. I tried in my main phase, both pre and post combat, to click on it to delve and convoke with my creatures but the click didn't show any prompt to do so. I played it yesterday too and it was working fine. (I had 2 untapped black creatures and plenty of cards in the graveyard)

**Comment by Zerrisx** [comment]
Duplicate of #6698

**Comment by JayDi85** [comment]
Fixed via cd624b2158ed00dca7f676e26bb8134a67864b84
