### ISSUE TITLE
Reyhan exiles itself before going to command zone, thereby not transferring counters

### ISSUE THREAD

**Issue by dashosa** [magefree/mage#6688]
Reyhan exiles itself before going to command zone, thereby not transferring counters

![image](https://user-images.githubusercontent.com/63882410/85217047-4c7e5e00-b35a-11ea-8af3-9c2285730875.png)

**Comment by LevelX2** [comment]
Probably cause for the problem:

63851b73a1608b4410563e0970c530bcaaf7c975 - Evan Kranzler <theelk801@gmail.com> 12.06.2020
Updated commander zone change rules (ready for review) (#6620)

**Comment by LevelX2** [comment]
Explained here in video ~ 17:00
https://articles.edhrec.com/the-command-zone-major-rules-change-commander-dies-triggers-the-command-zone-334-magic-the-gathering/?utm_source=MTGNexus&utm_medium=CommunityHub
