### ISSUE TITLE
Elite Scaleguard does not trigger creatures with +1 counters to tap opponents creatures

### ISSUE THREAD

**Issue by dashosa** [magefree/mage#6689]
![3](https://user-images.githubusercontent.com/63882410/85217057-8bacaf00-b35a-11ea-8c7e-995f3be99408.PNG)

**Comment by dashosa** [comment]
![image](https://user-images.githubusercontent.com/63882410/85217152-aaf80c00-b35b-11ea-9603-a26ab7676cde.png)

Second test, same result

**Comment by dashosa** [comment]
Here's an animated gif of the current interaction as of right now: 

![ezgif-3-695cec6682c8](https://user-images.githubusercontent.com/63882410/85231554-0b239800-b3c6-11ea-809f-45b731dfd076.gif)

**Comment by dashosa** [comment]
Hi @LevelX2  

I just tested it again and it worked perfectly the first turn, and then on the second turn it didn't trigger at all

![ezgif-2-efceef376e64](https://user-images.githubusercontent.com/63882410/85300146-31a00c80-b474-11ea-8e71-5338b7735097.gif)

**Comment by LevelX2** [comment]
You tested with the current dev version?

**Comment by JayDi85** [comment]
@dashosa 
Current beta version/server don't have that fix.

**Comment by dashosa** [comment]
Ah makes sense, thanks
