### ISSUE TITLE
Booster Draft Sealed Elimination (Cube) not working

### ISSUE THREAD

**Issue by JoshuaCochran** [magefree/mage#6694]
On the new live update 1.4.42V0 during Booster Draft Sealed Elimination (Cube) the client freezes after submitting your deck. It unfreezes after everyone in the tournament has submitted their decks, but every play besides the last to submit has a deck size of 0 and instantly concedes. During sideboarding they are shown to have 0 cards in their deck and sideboard.

This was tested with 2 players 6 bots and 1 player 7 bots. Settings are attached.
![cube settings](https://user-images.githubusercontent.com/8288695/85233903-c0525200-b3be-11ea-9d24-ca42137d0699.PNG)

**Comment by Zerrisx** [comment]
Are you sure?  I can't even set that up.

![image](https://user-images.githubusercontent.com/59861365/89546374-2443a500-d7ca-11ea-8788-04ca26316504.png)
