### ISSUE TITLE
Oathbreaker format - option to pick first player is not presented at the start of the game

### ISSUE THREAD

**Issue by fearphage** [magefree/mage#6695]
The game starts and all the players are present, but no one is giving the option to pick the starting player so the game never starts. Tested on the EU and US servers.

**Comment by LevelX2** [comment]
- [x] Endless loop on game start (braking the game).
- [ ] The signature spell does not return to the command zone.
- [ ] Add a unit test that start a Oathbraker game and cast Planeswalker and signature spell.

**Comment by LevelX2** [comment]
The signature spell does not return to the command zone.

![grafik](https://user-images.githubusercontent.com/2066790/85307228-ed326200-b4af-11ea-89fa-0e006627132f.png)

**Comment by fearphage** [comment]
FYI the Oathbreaker format is unplayable until this fix releases.

**Comment by fearphage** [comment]
FYI this is a regression.
