### ISSUE TITLE
Wear / Tear does not cast with flashback (Snapcaster Mage)

### ISSUE THREAD

**Issue by MIW1** [magefree/mage#670]
To replicated:
Wear / Tear in graveyard
Cast Snapcaster and select Wear / Tear

After the trigger resolves you can click Wear / Tear. It will correctly prompt you to cast either Wear, Tear or Cancel. However if you click Wear or Tear option the dialog will close and nothing will happen.
It will not ask for mana nor targets.

**Comment by sgtgold** [comment]
So I've found some more information on this bug, but haven't found a fix yet. Wear // Tear will only exhibit this behavior if there is only a target for one of the sides. For example it will break if there is only an artifact and no enchantment to target and vice versa. If there is an artifact and an enchantment (or an enchantment artifact like Whip of Erebos) Wear // Tear flashes back normally. Hope this helps, I will keep working on the fix.
