### ISSUE TITLE
wrong Delirium count

### ISSUE THREAD

**Issue by copperfield42** [magefree/mage#6704]
![descend upon the sinful](https://user-images.githubusercontent.com/4504719/85336659-f968f000-b4ac-11ea-9f95-a5044f6f3413.PNG)
The card _Descend upon the Sinful_ (and by extension I suppose the rest of the delirium card too) count subtypes of creatures for the delirium clause, but that is wrong according to the [rules](https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=482714) and thus I got the angel token when I shouldn't because I only had 3 cards types, namely land, enchantment and creature when I play it.

`The card types in Magic are artifact, creature, enchantment, instant, land, planeswalker, sorcery, and tribal (a card type that appears on some older cards). Supertypes (such as legendary and basic) and subtypes (such as Human and Equipment) are not counted.`

**Comment by Zerrisx** [comment]
It's actually even simpler than that - Delirium is currently counting *cards*, not *card types* - any four cards in the graveyard gets you delirium right now.
![image](https://user-images.githubusercontent.com/59861365/85345665-aa28bc80-b4b8-11ea-8ce4-4fd8a30f9baf.png)
