### ISSUE TITLE
Bug Report: Fumiko the Lowblood

### ISSUE THREAD

**Issue by Simisays** [magefree/mage#6718]
When Fumiko the Lowblood is on the table in a multiplayer game, during my opponents combat phase, they must attack a player but somehow they can't attack anyone. Causing the game to freeze (unless rolled back)

**Comment by jeffwadsworth** [comment]
What else was on the battlefield?  Works fine in my simple test with Memnites.

**Comment by Simisays** [comment]
There were 3 people left. I had a Ghostly Prison. Het tried to attack my other opponent with 4 creatures but after he declared attackers the game said that he coudn't attack. After we rolled back and I conceded the problem was gone.

**Comment by jeffwadsworth** [comment]
Well, that Ghostly Prison would surely make a difference here.  I will test with that.

**Comment by jeffwadsworth** [comment]
Still worked fine.
