### ISSUE TITLE
Redundant copies of Menace

### ISSUE THREAD

**Issue by Zerrisx** [magefree/mage#6720]
Multiple instances of both Haste and Menace are redundant, but Sethron, Hurloon General seems to give a ton of extra copies of Menace if activated multiple times.  Unsure if the root cause is Menace or Sethron, but either way it should probably only give Menace once.

![image](https://user-images.githubusercontent.com/59861365/85804746-046f8a80-b710-11ea-9b46-c3a57be1f4cd.png)

**Comment by emerald000** [comment]
While redundant copies of the Menace ability are useless, they are still gained. So there is no bug here.

**Comment by Zerrisx** [comment]
Then why aren't redundant copies of haste gained?

**Comment by 18ths** [comment]
I agree, this makes no sense in this context, only clutters the view. This might matter though - prowess, exalted, extort are stackable and should be able to be gained several times.

**Comment by JayDi85** [comment]
That's wrong behaviour. Singleton abilities must be added one time.

**Comment by JayDi85** [comment]
OK, current MenaceAbility is not singleton, so it added multiple times as normal abilities do (that's ok).

Devs already tried to change it to singleton in 2015, but reverted by @LevelX2 due many bugs. Related discussion from b83e12f51c3b8ab0ee0f93ab78ebcfebb049923f
> The added effect of Menace needs the source ability which is not available for Mage Singletons.
> The related permanent is retrieved from the source.getSourceId().

I don't know what it all means (I can't see any code in MenaceAbility or CantBeBlockedByOneEffect that can be potentially broken). BUT current MenaceAbility also have settings to show or hide ability hint (see #6728). 

So multiple instance of MenaceAbility are not a bug until:
* ensure what it can works as singleton;
* implement different hint settings for singleton keyword abilities (see #6728);
