### ISSUE TITLE
Brisela, Voice of Nightmares doesn't like to change zones after Rollback

### ISSUE THREAD

**Issue by Zerrisx** [magefree/mage#6723]
Brisela, Voice of Nightmares ignores some cards that really should cause it to change zones after rolling back a previous zone change.  For example, you can exile it with Swords to Plowshares, but if you rollback to the start of the turn, now it...

- [ ] Ignores getting destroyed by Doomblade or Murder
![image](https://user-images.githubusercontent.com/59861365/85817910-ea946e80-b734-11ea-820c-6ffefa458a12.png)

- [ ] Ignores being dealt lethal damage by Star of Extinction (although this did freeze the game with the AI not responding, so... that's something?)
![image](https://user-images.githubusercontent.com/59861365/85818279-e288fe80-b735-11ea-96e3-5018e9cfdd33.png)

- [ ] Ignores being returned to hand with Unsummon
![image](https://user-images.githubusercontent.com/59861365/85817926-f7b15d80-b734-11ea-833b-2198b7707950.png)

- [ ] Ignores being shuffled into library with Chaos Warp
![image](https://user-images.githubusercontent.com/59861365/85817977-1e6f9400-b735-11ea-90ed-2a02017a4508.png)

**Comment by jeffwadsworth** [comment]
Hmm.  It worked just fine with Doom Blade.
![worksFine](https://user-images.githubusercontent.com/1496996/86161384-cb019b00-bad2-11ea-8b05-57674a3006a3.jpg)

**Comment by jeffwadsworth** [comment]
Star of Extinction froze the AI in my session as well.  Checking it out.

**Comment by jeffwadsworth** [comment]
Unsummon worked as well.  The melded cards were returned to my hand versus going to the graveyard via a destroy effect.

**Comment by jeffwadsworth** [comment]
Chaos Warp worked fine as well.

**Comment by Zerrisx** [comment]
Ah - I figured it out.  There's an extra step.

1) Have Brisela meld (I did this with Bruna as my commander, unsure if relevant)
2) Have Brisela change zones in any way, i.e. with Doom Blade
3) Roll back to start of turn
4) Brisela will no longer change zones from any effect

So it looks like a Rollback bug, likely interacting badly with meld.
