### ISSUE TITLE
Price of fame is still bugged

### ISSUE THREAD

**Issue by rexelallan** [magefree/mage#6737]
![image](https://user-images.githubusercontent.com/42716000/85932204-920fcd80-b8fc-11ea-8c44-038b6447a1ed.png)

**Comment by LevelX2** [comment]
Duplicate of #6698.

**Comment by rexelallan** [comment]
They said it was fixed, but no it was not. Dont tag as duplicate this is new issue since bug is not yet fixed as they claimed to be

**Comment by Zerrisx** [comment]
The fix is only on beta servers right now. If you're on the release server, it'll still be bugged until the next patch. What client/server were you using?

**Comment by rexelallan** [comment]
I see. Im using the live server and not beta. Thanks!

**Comment by Zerrisx** [comment]
No worries!  Yeah, we typically mark things fixed as soon as the fix goes into beta, but it can take a few weeks to make it to live.
