### ISSUE TITLE
Invigorate can be cast from the graveyard

### ISSUE THREAD

**Issue by Zerrisx** [magefree/mage#6739]
Nothing else fancy going on, otherwise empty battlefield - cast Invigorate on a creature, pay the gain 3 alternate cost... and you can then cast Invigorate again from the graveyard.  And you can keep doing this endlessly.
![image](https://user-images.githubusercontent.com/59861365/85935255-52bd8e80-b8b4-11ea-87ff-78d0815f1ff5.png)
![image](https://user-images.githubusercontent.com/59861365/85935266-741e7a80-b8b4-11ea-9462-9b2c7fc11759.png)
![image](https://user-images.githubusercontent.com/59861365/85935276-8ac4d180-b8b4-11ea-8f39-2b2a728dc941.png)

**Comment by copperfield42** [comment]
same with Snuff Out, the AI use it several times that way
![snuff out 1](https://user-images.githubusercontent.com/4504719/85961141-66312e00-b976-11ea-90cf-b4381a6606c0.PNG)
