### ISSUE TITLE
Glacial Crevasses does not prevent Torbran, Thane of Red Fell damage

### ISSUE THREAD

**Issue by copperfield42** [magefree/mage#6740]
![glacial crevasses 1](https://user-images.githubusercontent.com/4504719/85956555-720bf880-b954-11ea-96c2-0c2e9b3e0a38.PNG)

Exactly what it said in the tittle, AI attack with Torbran, Thane of Red Fell, activate Glacial Crevasses and I still took 2 damage (iirc I choose Glacial Crevasses effect to apply first, but I think the order should be irrelevant in this case).

Playing in latest beta.

[Torbran, Thane of Red Fell ruling:](https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=473109)

> If another effect modifies how much damage your red source would deal, including preventing some of it, the player being dealt damage or the controller of the permanent being dealt damage chooses an order in which to apply those effects. __If all of the damage is prevented, Torbran, Thane of Red Fell effect no longer applies.__

**Comment by jeffwadsworth** [comment]
It doesn't prevent the 2 extra damage from the replacement effect.
