### ISSUE TITLE
Opponent or AI can use my Bolas Citadel

### ISSUE THREAD

**Issue by copperfield42** [magefree/mage#6741]
![bolas citadel 1](https://user-images.githubusercontent.com/4504719/85961575-56671900-b979-11ea-87eb-c8a284e3a3cc.PNG)
![bolas citadel 2](https://user-images.githubusercontent.com/4504719/85961590-6a127f80-b979-11ea-8bad-17244a6c88ca.PNG)

The AI manage play a land and cast a couple of cards paying life as if it have Bolas Citadel, but I'm the one that have it.

Playing in the beta.

**Comment by JayDi85** [comment]
Fixed via d1ccb621a1535c9533be5771798d3028f02316ec
