### ISSUE TITLE
Suggestion: Better way to view face-down morphs at game end

### ISSUE THREAD

**Issue by duelcastermage** [magefree/mage#6749]
As it stands, it is basically impossible to tell what the front side of your opponent's face-down morph cards are at the end of the game, since XMage kicks immediately to the sideboarding screen. This should be revealed at the end of a game per MTG rules. Maybe a short pause to show face-down morphs at the end of a game if this issue comes up? Or a way to 'view battlefield and log' (similar to MTG Arena) while sideboarding, so you can reference the game log to see what the morphs are?

**Comment by Zerrisx** [comment]
Duplicate of #4635
