### ISSUE TITLE
[DEV] Validation of penny dreadful deck generates NullPointerException

### ISSUE THREAD

**Issue by 18ths** [magefree/mage#6750]
Not really found in the wild, because I cannot figure out how do I create a table with Penny Dreadful match. I found it during testing PR #6437. The null pointer is caused by missing file pennydreadful.properties. I'd add the file myself, if only I knew what should it contain ;)

**Comment by JayDi85** [comment]
Check sources more careful. It's have that file:

![shot_200629_200158](https://user-images.githubusercontent.com/8344157/86028900-8b3fa280-ba43-11ea-97cd-287815d1b732.png)
