### ISSUE TITLE
Using unique/special new event type for taking special actions

### ISSUE THREAD

**Issue by LevelX2** [magefree/mage#6753]
Special actions are not activated abilities.

> 116.1. Unless a spell or ability is instructing a player to take an action, which player can take actions at any given time is determined by a system of priority. The player with priority may cast spells, activate abilities, and take special actions.

So xmage should send a special event type for taking special actions. Currently ACTIVATE_ABILITY and ACTIVATED_ABILITY are used.
This should be something like TAKE_SPECIAL_ACTION and TAKEN_SPECIAL_ACTION to be able to proper distingish between the special actions and activated abilities.

This would solve problems like that Phyrexian Revoker in the current implementation does also prevent special actions from beeing taken.

I'm not sure where are ACTIVATE_ABILITY and ACTIVATED_ABILITY events used to get information about taking a special action.

What are possible candidates, that have to be checked/changed?

Current code from PlayerImpl.java
```
    protected boolean specialAction(SpecialAction action, Game game) {
        //20091005 - 114
        if (!game.replaceEvent(GameEvent.getEvent(GameEvent.EventType.ACTIVATE_ABILITY,
                action.getSourceId(), action.getId(), playerId))) {
            int bookmark = game.bookmarkState();
            if (action.activate(game, false)) {
                game.fireEvent(GameEvent.getEvent(GameEvent.EventType.ACTIVATED_ABILITY,
                        action.getSourceId(), action.getId(), playerId));
                if (!game.isSimulation()) {
                    game.informPlayers(getLogName() + action.getGameLogMessage(game));
                }
                if (action.resolve(game)) {
                    game.removeBookmark(bookmark);
                    resetStoredBookmark(game);
                    return true;
                }
            }
            restoreState(bookmark, action.getRule(), game);
        }
        return false;
    }

```

**Comment by JayDi85** [comment]
Xmage uses special action mechanic for own purpose (special button on priority panel). There are many abilities with it:
![shot_200630_153610](https://user-images.githubusercontent.com/8344157/86121693-803e4e00-bae7-11ea-956b-b72de4ccd444.png)

So if you want to change events then it must be special param like specialActionTiming (ABILITY, SPECIAL_ACTION). And that's can be used to send events (ability or mtg's special action), check playable state, etc. So after changes some xmage's special actions will be activated ability as old version (e.g. it can be stopped to use by some restriction effect), and another actions will be real mtg's special action (like companion) and can't be stopped by another restrictions.

**Comment by LevelX2** [comment]
@JayDi85 
Thanks for your response. Just using this issue to collect the information.

### Questions are:
- Is the ACTIVATE_ABILITY event somwhere replaced (I don't think so) or used in watcher or effect as information. 
- And were do we now use special actions but by the rules it shouldn't be a special action.

### 115.2. There are eightspecial actions:
- 115.2a **Playing a land** is a special action. To play a land, a player puts that land onto the battlefield from the zone it was in (usually that player’s hand). By default, a player can take this action only once during each of theirturns. A player can take this action any time they havepriority and the stack is empty during a main phase of theirturn.See rule 305, “Lands.”
- 115.2b Turning a **face-down creature face up** is a special action. A player can take this action any time they havepriority. See rule 707, “Face-Down Spells and Permanents.”
- 115.2c Some effects **allow a player to take an action at a later time**, usually to end a continuous effect or to stop a delayed triggered ability from triggering. Doing so is a special action. A player can take such an action any time they have priority, unless that effect specifies another timing restriction, for as long as the effect allows it.
- 115.2d Some effects from static abilities allow a player to take an action to **ignore the effect from that ability for a duration**. Doing so is a special action. A player can take such an action any time they have priority.
- 115.2e One card (Circling Vultures) has the ability “You may discard **Circling Vultures** any time you could cast an instant.”Doing so is a special action. A player can take such an action any time they havepriority.
- 115.2f A player who has a card with **suspend** in their hand may **exile that card**. This is a special action. A player can take this action any time they havepriority, but only if theycould begin to cast that card by putting it onto the stack. See rule 702.61, “Suspend.”
- 115.2g In a Planechase game, **rolling the planar die** is a special action. A player can take this action any time they havepriority and the stack is empty during a main phase of theirturn. Taking this action costs a player an amount of mana equal to the number of times they havepreviously taken this action on that turn.Note that this number won’t be equal to the number of times the player has rolled the planar die that turn if an effect has caused the player to roll the planar die that turn. See rule 901, “Planechase.”
- 115.2h In a Conspiracy Draft game, **turning a face-down conspiracy card in the command zone face up** is a special action. A player can take this action any time they havepriority. See rule 905.4a


### AbilityType
We already have the AbilityType as an attribute to the Ability class.
So it's not strict by the rules to have PLAY_LAND and SPECIAL_ACTION as different types because playing a land is also a special action.

- PLAY_LAND("Play land", true),
- MANA("Mana", false),
- SPELL("Spell", true),
- ACTIVATED("Activated", false),
- STATIC("Static", false),
- TRIGGERED("Triggered", false),
- EVASION("Evasion", false),
- LOYALTY("Loyalty", false),
- SPECIAL_ACTION("Special Action", false);

**Comment by LevelX2** [comment]
@emerald000 or @anyone
What kind of ability is the "Until end of turn, you may pay {1} any time you could cast an instant. If you do, prevent the next 1 damage that would be dealt to that permanent or player this turn." part og Guardian Angel?

**Comment by LevelX2** [comment]
Added now new GameEvents for special actions and the special mana payment abilities (no activated abilities).
So preventing effects that check for the event will do automatically a correct selection.

### SPECIAL_ACTION => Event: TAKE_SPECIAL_ACTION, TAKEN_SPECIAL_ACTION 
LicidAbility 116.2c
CompanionAbility 116.2g	
TurnFaceUpAbility 116.2b
SuspendAbility 116.2f 
VolrathsCurseSpecialAction 116.2d
LeoninArbiterSpecialAction 116.2d
DampingEngineSpecialAction 116.2d 
CirclingVulturesSpecialAction 116.2e
UnlessPaysDelayedEffect 116.2c

GuardianAngelAction => Is still coded as special action (confirmation if this is correct would be nice).

### SPECIAL_MANA_PAYMENT => Event: TAKE_SPECIAL_MANA_PAYMENT, TAKEN_SPECIAL_MANA_PAYMENT
AssistAbility
ConvokeAbility
DelveAbility		
ImproviseAbility
Channel (card)

**Comment by emerald000** [comment]
Guardian Angel creates a special action:

116.2c. Some effects allow a player to take an action at a later time, usually to end a continuous effect or to stop a delayed triggered ability from triggering. Doing so is a special action. A player can take such an action any time they have priority, unless that effect specifies another timing restriction, for as long as the effect allows it.
