### ISSUE TITLE
Chainer, Nightmare Adept issues

### ISSUE THREAD

**Issue by copperfield42** [magefree/mage#6757]
Chainer, Nightmare Adept does not get haste when cast from the Command Zone or is reanimated, it also gives haste to creatures cast from the hand.

Casting from Command Zone.
![chainer 1](https://user-images.githubusercontent.com/4504719/86189128-a9260980-bb0e-11ea-89aa-21ce80d3a0fb.PNG)

Casting a creature from the Hand Zone in steps:
![chainer 2 1](https://user-images.githubusercontent.com/4504719/86189163-c6f36e80-bb0e-11ea-8e15-92cd5ab2bc8b.PNG)
![chainer 2 2](https://user-images.githubusercontent.com/4504719/86189203-e38fa680-bb0e-11ea-9187-9f2bb853a107.PNG)
![chainer 2 3](https://user-images.githubusercontent.com/4504719/86189228-f904d080-bb0e-11ea-996a-362ef15f28fa.PNG)

**Comment by jeffwadsworth** [comment]
Why would Chainer, Nightmare Adept gain Haste after being cast from anywhere?  It gives Haste to non-token creatures not cast from the hand, not itself, if it is in play.
It correctly did not give Haste to creatures cast from the hand in my testing.

**Comment by copperfield42** [comment]
> Whenever a nontoken creature enters the battlefield under your control, if you didn’t cast it from your hand, it gains haste until your next turn.

Chainer would gain haste himself with his trigger ability because is a ETB, he himself is a nontoken creature that enter from the CZ or whatever

[Chainer ruling (23/08/19):](https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=470585)
> Chainer’s last ability triggers if Chainer enters the battlefield without being cast from your hand.

**Comment by jeffwadsworth** [comment]
That feature is not implemented in the code and will probably never get done, sadly.  See Blood Moon, etc.

**Comment by jeffwadsworth** [comment]
https://github.com/magefree/mage/issues/4202

**Comment by copperfield42** [comment]
for what understand Chainer isn't like Blood Moon that modify how thing would enter the battlefield and there is some dark magic that under the current implementation make it impossible to do... 

Chainer does not modify how thing would enter, the thing already enter and only need to check if the condition of it entering was right to trigger or not, it already does it for normal or for mass re-animator like Living Dead, so it shouldn't be too difficult to make it look at itself entering, right?

Looking at the code it looks like is implemented as it was _another_, but the _another_ part is wrong.
![image](https://user-images.githubusercontent.com/4504719/86320328-a3125480-bc04-11ea-820b-53f617c53d20.png)

**Comment by jeffwadsworth** [comment]
You are correct.  Easy fix in that case.
