### ISSUE TITLE
Request: Quick start 4-player game button on test server/client

### ISSUE THREAD

**Issue by Zerrisx** [magefree/mage#6770]
I'd like a fourth button, right about here:
![image](https://user-images.githubusercontent.com/59861365/86309386-3afe4700-bbe1-11ea-8600-3f5bfe65275f.png)

That allows me to start a four-player game where each player uses a copy of test.dck, so that I can jump into situations that enable commander multiplayer testing easier, i.e. effects like Inniaz, the Gale Force.

**Comment by JayDi85** [comment]
BTW you can use cheat button (`init.txt`) in any game, just change player names in commands. It's also support commands re-use, so no need to setup same cards all the time. Example:
```
[test bug 123]
@init
@init computer 2
@init computer 3
@init computer 4
commander:Human:Tasigur, the Golden Fang:1
graveyard:Human:Grizzly Bears:20

[init computer 2]
battlefield:Computer 2:Forest:5
battlefield:Computer 2:Plains:5
battlefield:Computer 2:Mountain:5
battlefield:Computer 2:Swamp:5
battlefield:Computer 2:Island:5

[init computer 3]
battlefield:Computer 3:Forest:5
battlefield:Computer 3:Plains:5
battlefield:Computer 3:Mountain:5
battlefield:Computer 3:Swamp:5
battlefield:Computer 3:Island:5

[init computer 4]
battlefield:Computer 4:Forest:5
battlefield:Computer 4:Plains:5
battlefield:Computer 4:Mountain:5
battlefield:Computer 4:Swamp:5
battlefield:Computer 4:Island:5
```

**Comment by Zerrisx** [comment]
Oh for sure; my issue is just that it takes me an extra minute or two to set up a real four person game, set it to free for all, set it to one match win, and give everybody decks - and then change all those settings back next time I play a non-testing game.
