### ISSUE TITLE
Spells with multiple choices should resolve them in card order, not the order they were chosen by the player

### ISSUE THREAD

**Issue by Zerrisx** [magefree/mage#6771]
Spells with multiple choices, like Sublime Epiphany or Cryptic Command, should always resolve their choices in the order listed on the card.

Currently, they instead resolve in the order the player clicks them, which results in buggy (and inconsistent) behavior.

For example, Cryptic bouncing Narset and drawing should always draw the card.  But currently, it won't if you pick the draw choice first, because Narset will still be on the battlefield.
![image](https://user-images.githubusercontent.com/59861365/86317104-3727f000-bbf4-11ea-84d6-23f1ca35b8ac.png)

Similarly, using Sublime Epiphany to bounce and clone the same creature should never result in the old creature seeing the token enter the battlefield.  But it does, if you select the token mode before the bounce mode.
![image](https://user-images.githubusercontent.com/59861365/86270962-b801d000-bb91-11ea-8556-50ac4d9eaed2.png)

These cards should always do their effects in card order - and it might also be helpful to have a UI to communicate that to the player, so that they don't think it will be in choice order.

**Comment by LevelX2** [comment]
**JayDi85 replied here 2a31e8063b0886f888f1cb4ad68d14c213bfc1c4

Not full fix. `AbilityImpl` must use same order. As example: target choose. Search code for `getModes().setActiveMode`. Even more some effect uses `getSelectedModes` to create new targets list and other actions (search code by `getSelectedModes`).

I recommends to change `getSelectedModes` itself to return already sorted list. And fix some code usage to normal methods:
* `getSelectedModes().clear` -> `clearSelectedModes()`
* `getSelectedModes().add` -> `addSelectedMode(UUID)`

Also new methods can fix some other potential bugs (wrong usage). As example -- broken selected mode clear (cause it must clear duplicated list too):
![shot_200702_194435](https://user-images.githubusercontent.com/8344157/86382152-bbcf4880-bc9e-11ea-955c-682a254d60f2.png)
![shot_200702_200357](https://user-images.githubusercontent.com/8344157/86383475-31d3af80-bc9f-11ea-88d4-b247353f403a.png)

Example potential problems:

1. Wrong modes order for tests (it allows choose modes by index):
![shot_200702_195307](https://user-images.githubusercontent.com/8344157/86381475-727ef900-bc9e-11ea-8fce-3218b20be409.png)

2. Wrong AI possible actions generating:
![shot_200702_194824](https://user-images.githubusercontent.com/8344157/86381514-7c086100-bc9e-11ea-9761-ea0e1cf1c555.png)

3. Wrong selected modes clear on user choose cancel:
![shot_200702_194637](https://user-images.githubusercontent.com/8344157/86381581-8b87aa00-bc9e-11ea-9a0e-10560f7f3a18.png)

**Comment by JayDi85** [comment]
@LevelX2 there are more places to fix selectedModes. I have it and can upload if you want.

**Comment by LevelX2** [comment]
Also it has to be checked if multiple selection of the same mode does still work correctly.

@JayDi85 
Sure if you already changed/fix code commit it.
Don't know when I have the time to check/handle it.

**Comment by JayDi85** [comment]
Fixed by da4a44445bfe638b5bdc37a0009edc0c2ccd8760
