### ISSUE TITLE
Amplify allows selecting self when put onto battlefield from hand

### ISSUE THREAD

**Issue by SpikesCafe-google** [magefree/mage#6776]
Using [The Ur-Dragon](https://scryfall.com/card/c17/48/the-ur-dragon)'s attack trigger, I selected [Kilnmouth Dragon](https://scryfall.com/card/ddg/59/kilnmouth-dragon) to put on the battlefield. As its Amplify ability was resolving, I was able to select Kilnmouth Dragon in addition to other Dragons in my hand. This allows it to come in with 3 more +1/+1 counters than it should be able to.

![Resolving amplify ability](https://user-images.githubusercontent.com/16656302/86483458-19f13f80-bd22-11ea-89ac-b81817165ddb.PNG)

![Results of selecting all 4 dragons](https://user-images.githubusercontent.com/16656302/86483492-2bd2e280-bd22-11ea-97c8-b1a410e14b10.PNG)

Amplify works correctly if the creature enters the battlefield from the stack.

**Comment by JayDi85** [comment]
Fixed via 49f4e54aaa2853e9ee7d15528883e37b818301e8
