### ISSUE TITLE
Configure Travis CI to work with OpenJDK11

### ISSUE THREAD

**Issue by allentiak** [magefree/mage#6779]
Travis CI only supports Oracle's JDK8. Without an OpenJDK option, it is impossible to properly test PRs such as #6703 .

**Comment by JayDi85** [comment]
That's wrong. [Travis supports](https://docs.travis-ci.com/user/languages/java/#overview) many JDKs:

![shot_200704_092505](https://user-images.githubusercontent.com/8344157/86505628-4ebfce00-bdd8-11ea-8cde-f4188d5cd4de.png)

**Comment by allentiak** [comment]
You're right, I expressed myself incorrectly: Travis _does_ support this. What needs to be changed is Travis' _config_ so the build can be tested under OpenJDK11.

**Comment by Alex-Vasile** [comment]
Closed by #6703
