### ISSUE TITLE
Coal Golem - Activation cost not reduced by Heartstone or Training Grounds

### ISSUE THREAD

**Issue by Zerrisx** [magefree/mage#6790]
It should be reduced from {3} to {2} (or {1}, for Grounds), since it's an activated ability of a creature.

![image](https://user-images.githubusercontent.com/59861365/86663387-4b346e80-bfb3-11ea-95ac-5e1e8f10845a.png)
![image](https://user-images.githubusercontent.com/59861365/86664215-1c6ac800-bfb4-11ea-8b78-9c235abcecc7.png)

**Comment by jeffwadsworth** [comment]
This is related to that other issue.  The mana ability is not being considered an "activated ability".

**Comment by Zerrisx** [comment]
Yep; I was looking for other cards that might get caught by that.

**Comment by jeffwadsworth** [comment]
The Coal Golem is sacrificed.  In the case of the Heartstone, it is not checking for LKI on it, thus it fails to note it.

**Comment by Zerrisx** [comment]
Removed Zirda from the list.
