### ISSUE TITLE
Helm of Obedience is not working properly

### ISSUE THREAD

**Issue by rexelallan** [magefree/mage#6791]
It milled a Planeswalker Chandra, Flamecaller, and I countered it with Memory Lapse. Knowing it will be drawn next turn, I used Helm of Obedience to mill it out. And I know that it should be "safe" not to be sacrificed because Chandra, Flamecaller is a Planeswalker and not a creature. But no, it got sacrificed!
![Untitled](https://user-images.githubusercontent.com/42716000/86679021-bde32f80-c02f-11ea-82d9-9337d9552ab1.jpg)

**Comment by jeffwadsworth** [comment]
![worksFine](https://user-images.githubusercontent.com/1496996/86796222-fd137f80-c033-11ea-937e-e2884f3d33a0.jpg)

**Comment by jeffwadsworth** [comment]
The beta version is fixed via 6fd304e
If you don’t have the beta version, you will have to wait for the new release.
