### ISSUE TITLE
Token copies of Auras don't get to enchant anything and go straight to the graveyard

### ISSUE THREAD

**Issue by Zerrisx** [magefree/mage#6798]
Examples:

Fractured Identity cast on Psychic Possession (enchant player):
![image](https://user-images.githubusercontent.com/59861365/86821802-7751fd00-c050-11ea-8d2e-7a02181d6e6e.png)

Mythos of Illuna cast on Flight (enchant creature)
![image](https://user-images.githubusercontent.com/59861365/82957262-36a69480-9f78-11ea-824a-9ff04a8db94b.png)

**Comment by jeffwadsworth** [comment]
303.4f If an Aura is entering the battlefield under a player’s control by any means other than by resolving as an Aura spell, and the effect putting it onto the battlefield doesn’t specify the object or player the Aura will enchant, that player chooses what it will enchant as the Aura enters the battlefield. The player must choose a legal object or player according to the Aura’s enchant ability and any other applicable effects.

**Comment by jeffwadsworth** [comment]
Have you tried this with another user?  The AI may not be able to handle this situation.

**Comment by Zerrisx** [comment]
Broken vs Human as well
![image](https://user-images.githubusercontent.com/59861365/87206446-59460000-c2cf-11ea-9be6-d648ab6ed460.png)

**Comment by jeffwadsworth** [comment]
The token object will have to be expanded to allow attaching to permanents and players.

**Comment by JayDi85** [comment]
Is it ever worked in previous version (copy of auras on battlefield)?

**Comment by JayDi85** [comment]
Never mind, it's old issue. So it doesn't work.

**Comment by JayDi85** [comment]
See `CopyPermanentEffect` -- it have workaround to re-target copied auras. Maybe that code must be extracted and used for all copy effects too.
