### ISSUE TITLE
Goblin Rabblemaster's goblins not forced to attack if you F9

### ISSUE THREAD

**Issue by dylan1020** [magefree/mage#680]
This happened to me a few times tonight. Quite annoying as Flamewake Phoenix actually attacks when you F9.

**Comment by ydgmms** [comment]
Also saw this issue, but did not need to F9.
 See sscreen shot.

![untitled3](https://cloud.githubusercontent.com/assets/10151151/5791695/958e2748-9eb5-11e4-9abb-8ccf93289a42.png)

**Comment by LevelX2** [comment]
Fixed.
