### ISSUE TITLE
Server: migrate websites to https

### ISSUE THREAD

**Issue by serokellcao** [magefree/mage#6801]
Ditto.

It's trivial to set it up using EFF's letsencrypt.

**Comment by allentiak** [comment]
As of 2021.04.18, both websites show this problem.
- With Firefox, www.xmage.today can be accessed (accepting the risk), but 
www.xmage.de cannot.
- With Chromium, whereas both websites can be accessed, the "unsafe" symbol is displayed.

**Comment by JayDi85** [comment]
Done by https://github.com/magefree/mage/issues/12492#issuecomment-2380648340
