### ISSUE TITLE
Lack of instructions for building `master` version

### ISSUE THREAD

**Issue by serokellcao** [magefree/mage#6802]
Ditto.

Sometimes necessary for playtesting when the bugged cards are recently updated.

**Comment by JayDi85** [comment]
Check [wiki pages](https://github.com/magefree/mage/wiki), it's have many useful instructions. As example: 
* [how to build and run project from sources](https://github.com/magefree/mage/wiki/Setting-up-your-Development-Environment);
* [how to test cards](https://github.com/magefree/mage/wiki/Development-Testing-Tools)

**Comment by Zerrisx** [comment]
Has this been resolved?
