### ISSUE TITLE
Twinning Glass doesn't check if a spell with the same name has already been cast

### ISSUE THREAD

**Issue by Zerrisx** [magefree/mage#6803]
1) Cast Twinning Glass
2) Activate Twinning Glass
3) You can pick any non-creature spell in your hand, regardless of what you've cast this turn

![image](https://user-images.githubusercontent.com/59861365/86837846-1ed92a80-c065-11ea-8444-c4d97789df8a.png)

**Comment by jeffwadsworth** [comment]
This is related to that TargetCardInHand issue.

**Comment by Zerrisx** [comment]
This appears to still be broken
![image](https://user-images.githubusercontent.com/59861365/87170488-03edfc80-c297-11ea-901c-c6cc7b13f8b4.png)

**Comment by jeffwadsworth** [comment]
Make sure you have the latest version.  You should not even be able to choose the Lightning Bolt from your hand if you haven't cast it before.

**Comment by jeffwadsworth** [comment]
I see what you mean.  I went to my next turn and all the cards are select-able.  That may be an issue with the watcher not resetting.  Checking it out.
