### ISSUE TITLE
Wrong file line endings for run scripts (need to upgrade build script)

### ISSUE THREAD

**Issue by Dragas** [magefree/mage#6805]
Shell scripts in the launcher directory for both server and the client contain windows based line endings rather than unix ones, as a result, causing the shell scripts to fail to start up due to

 ```
bash: ./startClient.sh: /bin/sh^M: bad interpreter: No such file or directory
```

Workaround for this is to run the file through `dos2unix` utility. Consider fixing this at repository level by changing the file line endings from windows to unix for bash script files.

**Comment by Zerrisx** [comment]
Fixed by f517406

**Comment by JayDi85** [comment]
The real reason: I builds distribution files on Windows system so the git automaticity replace line endings to system dependents (use CRLF after download and use LF before upload).

So the real fix: add `dos2unix` step to build script.

**Comment by JayDi85** [comment]
Fixed with next release
