### ISSUE TITLE
ETB Trigger Problem

### ISSUE THREAD

**Issue by rexelallan** [magefree/mage#6806]
When I flicker Baleful Strix initially controlled by opponent with Aminatou, the Fateshifter, it comes into play under my control.
Therefore, ETB effect of drawing a card should be mine?

However, the one who draw the card is the opponent.

![image](https://user-images.githubusercontent.com/42716000/86904562-79e14f00-c143-11ea-9893-1c246a5fe10c.png)

**Comment by 18ths** [comment]
This Treachery (I see it in logs) was your opponents spell, attached to Baleful Strix you formely controlled?

**Comment by rexelallan** [comment]
> This Treachery (I see it in logs) was your opponents spell, attached to Baleful Strix you formely controlled?

Yes it is.

**Comment by jeffwadsworth** [comment]
The draw card ability on the Baleful Strix still has the wrong controller set (via the discarded Treachery effect) after it enters the battlefield from the Exile Zone, whereas the permanent itself has the correct controller.

**Comment by jeffwadsworth** [comment]
Turns out that ControlEnchantedEffect was coded incorrectly.  Fix coming soon.
