### ISSUE TITLE
OpenJDK11+: replace old 'org.w3c.dom' classes

### ISSUE THREAD

**Issue by allentiak** [magefree/mage#6809]
I've tried to do it while working on #6703, with no avail.
Help is more than welcome.

Problematic class: `mage.client.dialog.WhatsNewDialog`

Problematic line: [WhatsNewDialog#L17](https://github.com/magefree/mage/blob/fe2e9389f2c451da9cc8ea31af8f4ea10c44abeb/Mage.Client/src/main/java/mage/client/dialog/WhatsNewDialog.java#L17)

Problematic method: [WhatsNewDialog#L286](https://github.com/magefree/mage/blob/fe2e9389f2c451da9cc8ea31af8f4ea10c44abeb/Mage.Client/src/main/java/mage/client/dialog/WhatsNewDialog.java#L292)

**Comment by allentiak** [comment]
I think we should try Jakarta XML Binding, but I haven't tried it yet.

https://eclipse-ee4j.github.io/jaxb-ri/

https://www.javaguides.net/2020/01/java-jaxb-example-tutorial-java-11.html

```
 <dependencies>
            <dependency>
                <groupId>jakarta.xml.bind</groupId>
                <artifactId>jakarta.xml.bind-api</artifactId>
                <version>2.3.3</version>
            </dependency>
        </dependencies>
```

**Comment by JayDi85** [comment]
Standard library must be on priority. Replace it if it was deprecated/outdated/removed only. Just use correct dependency (java.xml)

**Comment by allentiak** [comment]
> The Standard library must have priority.

We agree on that :-)

Again: I haven't tried to solve this problem yet, and I don't know whether
I will have time to do it in the next few days or not. I opened this ticket
so that it can be used as a reference by whoever implements this (either me
or someone else).

**Comment by allentiak** [comment]
Workaround: https://github.com/magefree/mage/pull/6703/commits/1764f13b96e64a8db8a553a037d65a3eabd72129 (See #6703)

**Comment by JayDi85** [comment]
No needs to replace
