### ISSUE TITLE
Improve pack collation

### ISSUE THREAD

**Issue by theelk801** [magefree/mage#6811]
Currently packs are generated randomly and don't really reflect paper boosters very well. There is [information available](https://www.lethe.xyz/mtg/collation/) on how boosters are actually collated and I think we can use it to improve what we have. I'm gonna see what I can do with this.

**Comment by JayDi85** [comment]
> The method used is primarily to watch lots of YouTube videos of pack openings and analyze the results.

1. That's secret info -- no official data about sheets printing and it's can't be confirmed.
2. That's info depends on one author and can be stopped at any time (e.g. when the author resigns);
3. It's not available for all sets and it's not available on release;
4. Hard to implement and support.

It can be as *additional mode or setting*. Don't remove current booster generation logic on card's stats (it's open, easy to support and always available).

**Comment by JayDi85** [comment]
Pack collation was implemented
