### ISSUE TITLE
Ice Cauldron crashes when cast

### ISSUE THREAD

**Issue by Zerrisx** [magefree/mage#6815]
See title.
![image](https://user-images.githubusercontent.com/59861365/87103510-e11e0280-c21a-11ea-8bb3-356743bc0b45.png)

**Comment by JayDi85** [comment]
Rollback error fixed via 4598d7efb01efa7b2e0f8d9754071a522feca13e, but I didn't test if cards works as it should (it maybe bugged).

**Comment by Zerrisx** [comment]
Looks at least close enough to right - exiles the card properly, lets you pay mana properly, lets you cast it from exile with or without the cauldron.  Could be more subtle bugs, but it at least seems to perform basic functionality.
