### ISSUE TITLE
Jumpstart tournament games don't show up in the main pane

### ISSUE THREAD

**Issue by Zerrisx** [magefree/mage#6816]
Tournaments created as Jumpstart Elimination or Jumpstart Swiss don't show up (to yourself or anybody else)

![image](https://user-images.githubusercontent.com/59861365/87106193-75d82e80-c222-11ea-9890-c2255263f492.png)
![image](https://user-images.githubusercontent.com/59861365/87106226-90aaa300-c222-11ea-92cc-a2e234ac86e8.png)

**Comment by JayDi85** [comment]
Fixed via c011ff92ad5506605505494cdaa775e97df2f169
