### ISSUE TITLE
Add in the concept of comparing decks into the deck editor.

### ISSUE THREAD

**Issue by spjspj** [magefree/mage#6819]
Similar to a text file diff, would be nice to be able to visually compare two decks and get which cards are different between them.  This would allow different versions of the same deck to be more easily compared.  I've done a mockup of what I mean in the following image.  I guess comparing sideboards would be similar (maybe as part of a choice radio dialog that said
 1) "Compare Maindecks" 
 2) "Compare Sideboards"
https://i.imgur.com/uLIzh4J.png

**Comment by spjspj** [comment]
Another way to achieve something similar to what I would like may be to add a 'Singleton' option to the Select By in the deck editor.  Then you could smoosh together two similar decks, pick the singletons in the combined results and then select those as the differences between the two decks.  There's currently the 'multiples' option that picks out ones that have more than one of the same name..

**Comment by JayDi85** [comment]
Useless and hard to implement. Can be replaces by export + text diff tools from outside of the app.
