### ISSUE TITLE
Soulshriek keeps updating throughout the turn instead of being fixed on resolution

### ISSUE THREAD

**Issue by Zerrisx** [magefree/mage#6821]
Soulshriek's +X should be locked in when it resolves, but if more creatures go to the yard, X will change.

Giving +1/+0 with one creature in the yard
![image](https://user-images.githubusercontent.com/59861365/87175097-c04ac100-c29d-11ea-903a-62e198ef7d36.png)

A few more creatures go to the yard
![image](https://user-images.githubusercontent.com/59861365/87175140-d3f62780-c29d-11ea-8f4d-1ae3e326bad5.png)

**Comment by jeffwadsworth** [comment]
How is this different than Nightmare in this regard.  Please post a rule so that it can be noted.

**Comment by emerald000** [comment]
Nightmare is a characteristic-defining ability creating a continuous effect. This is a one-shot effect and thus is locked in at the time of resolving.

**Comment by jeffwadsworth** [comment]
610.1. A one-shot effect does something just once and doesn’t have a duration. Examples include dealing damage, destroying a permanent, creating a token, and moving an object from one zone to another.

**Comment by jeffwadsworth** [comment]
Rule posted for clarity.
