### ISSUE TITLE
Welcome message displaying wrong version

### ISSUE THREAD

**Issue by rystan** [magefree/mage#6828]
Title bar shows version 1.4.44V0:
![image](https://user-images.githubusercontent.com/6609665/87213534-b6ec4380-c2f3-11ea-962b-119d121ba53b.png)
Footer message says 1.4.3:
![image](https://user-images.githubusercontent.com/6609665/87213525-a8059100-c2f3-11ea-91e5-4c5a3dacab64.png)

**Comment by JayDi85** [comment]
Fixed via https://github.com/magefree/mage/commit/165d7362b006285f6dc3cddba4633db33c9311d2
