### ISSUE TITLE
All of my turns skipped, clock carried over from previous match

### ISSUE THREAD

**Issue by fireshoes** [magefree/mage#683]
In the second round of a draft, my opponent quit match. It seemed very sudden, like the server kicked them, because they were performing other game actions right before. The third round of the draft started with my opponent playing first. I F9'd and looked away for a second and when I looked back he had played a second land. I though maybe I had absent-mindedly pressed F9 on my turn as well, but when he finished his second turn, it went back to him again. My cards briefly lit up at the end of the turn, but otherwise I didn't click anything or have the chance to play anything. The cleanup step was also skipped, so I did not discard due to hand size. After his third turn, it went back to him directly for a fourth turn, so I conceded the game.
   After sideboarding, the second game started and I could take turns normally. I then noticed my clock had continued from where it was in the previous match. However it was during my priority, yet my opponent's clock was running down instead of mine. It seemed to somewhat correct itself after that, other than when I was F9'd a few seconds would run off my clock between phases, then those seconds would be added back to where it was before. Attached a pic showing my very low clock. Had a pic of the turn skipping too but then printscreened the other one over it before I saved it. Oops.
![clockbug](https://cloud.githubusercontent.com/assets/8553747/5810280/55e3e682-a009-11e4-8c1f-88578c34e182.png)

**Comment by JayDi85** [comment]
There were bug with rollback/cancel -- player's skip buttons restored too. It can be related to that bug. No more actual.
