### ISSUE TITLE
Kindred Boon not able to target Blood Baron Vizkopa

### ISSUE THREAD

**Issue by ersimont** [magefree/mage#6831]
The effect for Kindred Boon is able to target any of my vampires _except_ Blood Baron Vizkopa, as you can see in the screenshot below:

![image](https://user-images.githubusercontent.com/8042088/87227989-5baa6780-c36c-11ea-93ec-c5f18a53f350.png)

**Comment by emerald000** [comment]
It has protection from white.

**Comment by LevelX2** [comment]
The Baron has protection from white.

**Comment by ersimont** [comment]
🤦 Thank you and sorry.
