### ISSUE TITLE
Enthralling Hold not blocked by Hexproof

### ISSUE THREAD

**Issue by Zerrisx** [magefree/mage#6834]
See battlefield and chatlog
![image](https://user-images.githubusercontent.com/59861365/87236879-1dd13180-c3b4-11ea-9fb3-65161b69bbff.png)
![image](https://user-images.githubusercontent.com/59861365/87236876-11e56f80-c3b4-11ea-95e0-b6b7f7216926.png)

**Comment by jeffwadsworth** [comment]
This is probably related to the target not being checked again as legal upon resolution.

**Comment by jeffwadsworth** [comment]
Somehow, the check for Hexproof for permanents is dependent on the asThough hexproof being present as well.  How this never got reported is bizarre.
