### ISSUE TITLE
Fervent Champion equip cost reduction not working correctly.

### ISSUE THREAD

**Issue by Magik0722** [magefree/mage#6843]
I tried to equip both sword of fire and ice and feast and famine to a fervent champion when I had no mana but was unable to do so.

**Comment by Zerrisx** [comment]
This is another case of #6698

**Comment by MediaInBrain** [comment]
I had similar issues here:
https://github.com/magefree/mage/issues/6901

**Comment by Zerrisx** [comment]
Fixed (on beta) with 82dfd76.  Will be in next release.
