### ISSUE TITLE
suggestion: regenerate hints

### ISSUE THREAD

**Issue by copperfield42** [magefree/mage#6846]
It would be nice to add a hint after a player use a regenerate effect on a permanent, and as stack up one per use or indicate somehow how many regeneration are remaining if used more than one in the same permanent.

**Comment by Zerrisx** [comment]
Sounds like an excellent suggestion.

**Comment by jeffwadsworth** [comment]
There are some other issues with regeneration.  If a permanent with a regeneration shield is flickered, it retains the effect incorrectly.  Working on this as well.  Replacement effects are quite different to work with.

**Comment by jeffwadsworth** [comment]
This request was partially completed by JayDi in this commit.  The only thing left is to add the number of Regeneration Shields.
https://github.com/magefree/mage/commit/c7595ca476a10bb97ce5c8b46d0a105eea785dc2

**Comment by copperfield42** [comment]
Cool

**Comment by JayDi85** [comment]
Ohh, I see. It need a different approach for amount calcs. I'll deal with it.

**Comment by JayDi85** [comment]
There is possible bug with attached regens.

[Regeneration](https://scryfall.com/card/10e/290/regeneration)
> Enchantment — Aura 
> Enchant creature (Target a creature as you cast this. This card enters the battlefield attached to that creature.)
> {G}: Regenerate enchanted creature. (The next time that creature would be destroyed this turn, it isn’t. Instead tap it, remove all damage from it, and remove it from combat.)

Rules:
> 701.15a If the effect of a resolving spell or ability regenerates a permanent, **it creates a replacement effect that protects** the permanent the next time it would be destroyed this turn. In this case, “Regenerate [permanent]” means “The next time [permanent] would be destroyed this turn, instead remove all damage marked on it and tap it. If it’s an attacking or blocking creature, remove it from combat.”

So ability "Regenerate enchanted creature" must be `OneShotEffect` with new replacement effect creating to fixed target. Not ReplacementEffectImpl. Current "bug":
* Attach Regeneration to permanent;
* Activate regeneration shield;
* Attach aura to another permanent by [Aura Finesse](https://scryfall.com/card/roe/54/aura-finesse);
* Regen shield will be "moved" with aura. But that's wrong. First permanent must have shield forever.

Am I right?

**Comment by emerald000** [comment]
That is correct.

**Comment by JayDi85** [comment]
Improved by 00411b4a9bddf045f4772c31709d31dbf2930b55 (shown regeneration shields amount):

![shot_200802_133634](https://user-images.githubusercontent.com/8344157/89120656-17246e80-d4c9-11ea-89d3-4a3e1b11a165.png)

**Comment by copperfield42** [comment]
Cool.
One little thing about the message, it need a "of": permanent will be regenerated instead **of** destroy

**Comment by Zerrisx** [comment]
> 
> 
> Cool.
> One little thing about the message, it need a "of": permanent will be regenerated instead **of** destroy

I think I'd go with "permanent will be regenerated instead ***of*** destroy***ed***".
