### ISSUE TITLE
Arcbond

### ISSUE THREAD

**Issue by endqwerty** [magefree/mage#685]
Arcbond on a Seeker of the Way is not correctly dealing lifelink damage. The damage is dealt, but the life which was supposed to be gained is not. (the normal lifelink from combat damage worked)

**Comment by LevelX2** [comment]
What card/effect exactly do you mean with "Arcbound on"?

**Comment by endqwerty** [comment]
Arcbond targeting seeker. Seeker takes damage.

**Comment by LevelX2** [comment]
Ahh thanks I somehow misread Arcbond to Arcbound. It's clear now.
I will take a look.

**Comment by LevelX2** [comment]
Fixed.
