### ISSUE TITLE
Auditory need feedback indicator should be configurable

### ISSUE THREAD

**Issue by dperegolise** [magefree/mage#6853]
Regarding auditory priority indicator implemented in PR #6558

**Comment by dperegolise** [comment]
Comments from issue #6848 : 

> Perhaps sound package should also be a part of a theme.



> The new priority da-ding noise should have some settings to control it - specifically, at minimum I think it should have the following:
> 
> 1. On
> 2. On only when XMage is _not_ the active window
> 3. Off
> 
> Where it seems like 2 is the use case that got requested a lot, 3 satisfies people who hate everything new, and 1 is handy for people with a lot of lag trying to figure out what's going on.



> > It must dings on inactivity only (e.g. you don't react after few seconds). It uses mouse clicks and button presses to check activity/inactivity.
> 
> Then perhaps the issue is that the time check for "inactive" is too short, since I feel like I was playing pretty normally while not doing anything else, and got them multiple times per minute.



> How about 10 seconds instead of 2? It should be long enough time to click through priority and is short enough to reprimand people with looking at their phones.



> As an alternative - can we have it start a timer each time you receive priority, and then only trigger after you've held priority for X seconds without acting? Because I feel like I was getting it a lot when I did nothing, then received priority _and_ immediately got a ding. I didn't actually have any reason to be taking actions while it wasn't my turn, so I feel like that'll happen a lot.

**Comment by dperegolise** [comment]
> How about 10 seconds instead of 2? It should be long enough time to click through priority and is short enough to reprimand people with looking at their phones.

@18ths Before we try that, I think we should add the option to play the sound only if the window is inactive and see if that solves the problem. The issue @Zerrisx seems to be having is that the indicator sound is playing even though he is actively playing the game without being tabbed out. If we increase from 2>10 seconds, I personally will be caught tabbed out on priority any time the other player takes less than 10 seconds....I tab out for reddit/discord often (casual player).

> As an alternative - can we have it start a timer each time you receive priority, and then only trigger after you've held priority for X seconds without acting?

@Zerrisx that is a good idea, but the two issues I have with it are 1) it would drive me crazy when I'm trying to think through my turn (like every turn) and 2) the indicator was supposed to be a 'YOUR TURN' sound (like many games have), not necessarily a 'the other player has been waiting for x seconds' sound. It's supposed to *prevent* the other player from waiting.

**Comment by JayDi85** [comment]
No needs to add 3 options -- it can be simple checkbox (enable or disable "need feedback sound") under game sound settings.

Inactive code example:
``` java
        if (!MageFrame.getInstance().isActive()) {
            MageTray.instance.displayMessage("Pick the next card.");
            MageTray.instance.blink();
        }
```

Find game panel code example:
``` java
GamePanel gamePanel = getGame(userRequestMessage.getGameId());
```

**Comment by JayDi85** [comment]
That's code examples can help to implement correctly sound feedback without press/clicks events workaround (current implementation) and will works with another active app and another active game use cases.

If someone want to implement it then report here. Otherwise I'll take to fix it later.

**Comment by dperegolise** [comment]
> That's code examples can help to implement correctly sound feedback without press/clicks events workaround

One of the things accomplished by tracking the user's clicks is to prevent the sound from being spammed on auto-skip. Technically, during skip, the user gets priority many times. Something to keep in mind for whoever ends up implementing this enhancement.

**Comment by JayDi85** [comment]
All skips are server side, users didn't get feedback requests. You search `FEEDBACK_COLORIZING_MODE` or `gameNeedFeedback` for feedback require/usage example (it changes color on feedback require -- sound timer start can be here).

**Comment by JayDi85** [comment]
After sound notification improved by 610baac6abd773bd591fe1b60b9eb613e6fcf1a5 -- no needs in any settings. Current version plays sound immediately and correctrly:
* if game is not active (e.g. user play another game or chatting in global lobby);
* if app is not active (e.g. user works in other app like browser).

Beta client updated to latest version too.

BUT sound notification is short and quiet. If user skips it one time then he will not receive it again (e.g. does not know about turn waiting). Maybe it **must be repeated** (e.g. play it every 10 seconds until user open game panel)?
