### ISSUE TITLE
Deck Validator improvements

### ISSUE THREAD

**Issue by Zerrisx** [magefree/mage#6854]
Regarding the deck validator implemented in PR #6558

**Comment by Zerrisx** [comment]
Comments from issue #6848:

> 
> 
> The ordering on the validator seems a bit arbitrary:
> ![image](https://user-images.githubusercontent.com/59861365/87821926-3f0fa300-c836-11ea-9379-61456e341db2.png)
> 
> I'd start with the most supported 60-card formats in chronological order (Standard, Pioneer, Modern / Legacy, Vintage, Pauper) followed by the supported and commonly played multiplayer formats next to each other (Commander, Oathbreaker, Brawl) and then the weird more rarely played ones (Frontier, Hist. Type II, Penny). Remove the rest for being clutter. I can't tell you what Eternal is despite fifteen years of playing MTG, I don't think anybody has played Tiny Leaders as anything other than a joke since its inception, and Momir doesn't really need a validator.
> 
> _Edit: I have been told this is "Historical Type Two", which should probably be renamed something that fits in the box (Hist. Type II)? And makes sense as the last slot, since it does get played some, and validation for it is super handy._

**Comment by JayDi85** [comment]
* [ ] Label's hint must be restricted by max size with word wraps:
![shot_200718_230401](https://user-images.githubusercontent.com/8344157/87860044-280ea500-c94b-11ea-8cf2-044f4a7c86da.png)
 * Possible solution (if can't restrict and words wrap enable): limit error "lines" by 60-100 symbols and show full errors list window on label click (same deck validator window on game start/join).

**Comment by JayDi85** [comment]
* [ ] Deck size error must be yellow/warning color, not red (if no other errors found). Problem: you will see "all reds" on deck building until finished, but it can be useful to see cards legality in the middle of the building.
* Possible legality and color states:
  * Cards bad, deck bad (size, commander in sideboard, etc) -- red;
  * Cards ok, deck bad -- yellow;
  * Cards bad, deck ok -- red;
  * Cards ok, deck ok -- green;

**Comment by copperfield42** [comment]
another improvement to the validator can be the option to removed it once you done with it without needing to close the deck editor
![deck validate 1](https://user-images.githubusercontent.com/4504719/89110073-f3075580-d414-11ea-90a4-1359ceeea44b.PNG)
