### ISSUE TITLE
Obsidian Fireheart ability stops working when owner leave the game

### ISSUE THREAD

**Issue by SpikesCafe-google** [magefree/mage#6855]
[Obsidian Fireheart](https://scryfall.com/card/e01/55/obsidian-fireheart) has the ability to put blaze counters on lands such that the land deals 1 damage to its controller on their upkeep for as long as that blaze counter remains. Unfortunately, in a multiplayer game, when Obsidian Fireheart's owner loses the game, the blaze counters remain, but the land stops dealing damage.

Here's a couple decks I used to reproduce it against the AI using "Freeform Unlimited Commander" and 2 AI opponents. Just play as Obsidian Fireheart deck yourself, put a blaze counter on an opponent's land, watch it do at least one damage, then concede and watch it stop doing damage.

[xmage bug decks.zip](https://github.com/magefree/mage/files/4942262/xmage.bug.decks.zip)

**Comment by jeffwadsworth** [comment]
The duration should be WhileOnBattlefield.  Right now it is Custom.
