### ISSUE TITLE
AI: token doesn't enter attacking when it should

### ISSUE THREAD

**Issue by copperfield42** [magefree/mage#6860]
![brimaz 1](https://user-images.githubusercontent.com/4504719/87864191-44064c80-c933-11ea-9e46-2bc49cedb5fd.PNG)

When the AI attack with _Brimaz, King of Oreskos_, the token doesn't enter attacking most of the time, unless there is a planeswalker and enter attacking it. 

Same with _Leonin Warleader_, and probably with other cards that put tokens attacking

**Comment by jeffwadsworth** [comment]
I can't recreate this.  It works fine for me.
