### ISSUE TITLE
Helm of Obedience bug

### ISSUE THREAD

**Issue by rexelallan** [magefree/mage#6862]
Opponent uses Mystic Snactuary.

Of course I want the card he put on top of his library removed, Merchant Scroll.

But my Helm of Obedience was sacrificed.

![image](https://user-images.githubusercontent.com/42716000/87868836-c8f17480-c9cc-11ea-91a5-f5998057d05e.png)

**Comment by Zerrisx** [comment]
Didn't we recently close #6791 as not reproducible, with roughly the same bug report?  And... also submitted by you.  Huh.  Okay, I'm real curious now what you specifically are doing that's triggering this.  Any other permanents of note or similarities between the two games?  Any chance you have a gamelog you could include?

**Comment by rexelallan** [comment]
Yes, last time it was Chandra, flamecaller. You said that it is not reproducible. So i thhought that maybe it was a glitch.
But it happened again. The gamelog is seen in the chatbox. I just activated it like before.
