### ISSUE TITLE
Shark Typhoon Bugged

### ISSUE THREAD

**Issue by CarterBeebe** [magefree/mage#6864]
Shark Typhoon doesn't allow me to cast it as an enchantment, only as a cycling card.

**Comment by LevelX2** [comment]
I had no problem to cast the card during my test as enchantment as long as I had the mana to cast it.
Anymore context why you think it does not work as intended?

**Comment by CarterBeebe** [comment]
My apologies, maybe I was not casting it correctly then. I was in my 1st main phase and I had enough mana but every time I clicked on it it just told me to set a value for x and cycle it. I had tried floating mana as well and it wouldn’t let me do that either. I will try it again and see if it lets me cast it as an enchantment again. Thanks for the quick response and all the work you guys do!

**Comment by Zerrisx** [comment]
I'm guessing this is a subset of #6698 - what mana sources did you have to cast it with?  Anything besides basic lands?

**Comment by CarterBeebe** [comment]
Yes, I can’t quite remember what all I used but I know I used a sol ring, a dimir signet, and a couple lands. I think a couple of them were a watery grave and a cephalid coliseum
