### ISSUE TITLE
Commanders don't cause death triggers to fire if the commander is put into the command zone

### ISSUE THREAD

**Issue by ketsuban** [magefree/mage#6866]
Rule 903.9 has changed since the [`CommanderReplacementEffect`](https://github.com/magefree/mage/blob/master/Mage/src/main/java/mage/abilities/effects/common/continuous/CommanderReplacementEffect.java) was written. The old replacement effect still exists for commanders which are put into their owner's hand or library, but commanders go to their owner's graveyard or exile as normal (and thus cause triggers to fire) before the owner is given the option of putting them into the command zone as a state-based action.
> 903.9. A commander may return to the command zone during a Commander game.
> 903.9a If a commander is in a graveyard or in exile and that card was put into that zone since the last time state-based actions were checked, its owner may put it into the command zone. This is a state-based action. See rule 704.
> 903.9b If a commander would be put into its owner’s hand or library from anywhere, its owner may put it into the command zone instead. This replacement effect may apply more than once to the same event. This is an exception to rule 614.5.
> 903.9c If a commander is a melded permanent or a merged permanent and its owner chooses to put it into the command zone using the replacement effect described in rule 903.9b, that permanent and each component representing it that isn’t a commander are put into the appropriate zone, and the card that represents it and is a commander is put into the command zone.

**Comment by Grath** [comment]
CommanderReplacementEffect should be cleaned up to reflect that the rules are already correct, and possibly clean up the code some to make it more clear that the rules are correct if possible. That said, this rule change has already been implemented.

**Comment by LevelX2** [comment]
@ketsuban 
As said generally this rule change is already implemented.
Do you have any specific case that did not work for you?

**Comment by ketsuban** [comment]
The specific case was one brought up on Discord - a commander dying will trigger Fecundity, but won't always draw a card even if you say yes.

**Comment by Grath** [comment]
Which is a bug with Fecundity not working if it's an actual creature card which leaves the graveyard before Fecundity's trigger resolves - I reported separately as https://github.com/magefree/mage/issues/6867
