### ISSUE TITLE
Oathbreaker: Signature spell not returned to command zone

### ISSUE THREAD

**Issue by fearphage** [magefree/mage#6870]
I'm not sure if this is specific to the [Time Spiral](https://scryfall.com/card/usg/103/time-spiral) spell or a general issue with spells that exile themselves on resolution, but once cast it goes into permanent exile.

## Repro

1. Time Spiral as signature spell.
2. Cast Time Spiral and let the spell resolve.

## Expected Result

Spell is returned to command zone... to allow it to be cast with appropriate commander tax.

## Actual Result

Spell stays in permanent exile.

Here's a screenshot of the issue:

![image](https://user-images.githubusercontent.com/23887/88092503-3086fb80-cb56-11ea-9998-46b18955c8ce.png)

### Notes

@LevelX2 previously worked on a fix for the oathbreaker format referencing spells not returning to the command zone in a recent ticket (#6695).

**Comment by fearphage** [comment]
@LevelX2 Looking at the code for the fix, it references the graveyard, battlefield, and now exile.

What about spells that would go to the library like Seasons Past?

![image](https://user-images.githubusercontent.com/23887/88114874-7bb30580-cb7a-11ea-8c70-3673d22a0886.png)

**Comment by LevelX2** [comment]
@fearphage library and hand are already handled in the switch above because this is also done for normal commander cards.

**Comment by fearphage** [comment]
FYI this is a regression.
