### ISSUE TITLE
Regression: Domri, Chaos Bringer - riot doesn't trigger

### ISSUE THREAD

**Issue by fearphage** [magefree/mage#6872]
## Steps to Reproduce

1. Uptick `Domri, Chaos Bringer`
1. Use the mana to cast a creature spell.

## Expected Result

Riot should trigger and present the option of giving the creature a +1/+1 counter or haste.

## Actual Result

There is no trigger. Nothing takes place.

### Notes

Confirmed that riot works on creatures that have riot built in (nothing to do with Domri). `Rhythm of the Wild` also worked. It seems specific to Domri instead of the riot mechanic.

Here's a screenshot showing 2 of 3 riot triggers in action:

![image](https://user-images.githubusercontent.com/23887/88155770-21439480-cbce-11ea-8803-32e31883ba34.png)

**Comment by fearphage** [comment]
FYI this is a regression.

**Comment by JayDi85** [comment]
What's your IDE?
