### ISSUE TITLE
Deck editor hides scrollbars in small screens

### ISSUE THREAD

**Issue by copperfield42** [magefree/mage#6881]
![deck editor 1](https://user-images.githubusercontent.com/4504719/88404793-5e5d8180-cd9c-11ea-9fd4-5225071907e0.PNG)
the image doesn't fully show and horizontal scroll bar is missing

**Comment by JayDi85** [comment]
Your screenshot size is 1366px × 730px (standard screen size is 1366 × 768). So I think you are using auto-hide taskbar feature. 

How to use:
* Move mouse from taskbar to hide it -- you will see scrollbars from xmage's app;
* Move mouse to the scrollbar, but not to the very edge of the screen.

How to fix:
* Disable auto-hide taskbar ([windows 10 settings example](https://www.thewindowsclub.com/auto-hide-taskbar-windows))

**Comment by copperfield42** [comment]
I don't use auto hide, my taskbar is always up (and its size is of course the different in those sizes, I use [recortes](https://user-images.githubusercontent.com/4504719/88444536-a1931100-cdeb-11ea-8ad1-6b4eba0103b1.png) or however is called in english for my screenshot), and this wasn't issue for me before. 
Later I will check if the non-beta is the same.

If anything the problem I have for not using autohide is that the avatar don't show up in gameplay as you might had notice for my other screenshots in other topics. I try it once a long time ago, but the annoyance of the poping up taskbar when I move the mouse too close to the bottom to move the scroll or something to check the cards in my hand is greater than a missing avatar.

**Comment by JayDi85** [comment]
1. Make full screen screenshot (with taskbar visible) and report it here.
2. Player's avatar hides for too small screens (if app's height lower than 720px);

**Comment by copperfield42** [comment]
> Make full screen screenshot (with taskbar visible) and report it here.

Normal
![deck editor 1](https://user-images.githubusercontent.com/4504719/88446567-1456b900-cdf9-11ea-8ec5-0f2f7abbe7e7.png)
with validator:
![deck editor 2](https://user-images.githubusercontent.com/4504719/88446575-305a5a80-cdf9-11ea-8a56-285d7429ebf7.png)


> Player's avatar hides for too small screens (if app's height lower than 720px)

if that is the case why I don't get it then? mine is around 730px

**Comment by JayDi85** [comment]
Horizontal scrollbar fixed by 24aacaafe8da01306b5ba42fffb52d7cb6d440ab.

Avatar's render mode checking size of game panel (<= 720px) -- panel height without window header and toolbar:
![shot_200725_153019](https://user-images.githubusercontent.com/8344157/88456070-c50d9880-ce8b-11ea-90e6-4cc80ef38b46.png)

**Comment by copperfield42** [comment]
> Avatar's render mode checking size of game panel (<= 720px) -- panel height without window header and toolbar:

I see. Is there way to include support for that on small screen? even if it mean adding an additional scroll bar or a full screen mode?
a full screen mode it would be nice, sometime I end up opening some program by mistake.

**Comment by JayDi85** [comment]
It's can't be used without full screen mode or special compact mode (with small icons/font). Full screen mode is [hard to implement](https://stackoverflow.com/questions/11570356/jframe-in-full-screen-java), but compact mode is possible in the feature. 

I created related issue #6887 about small screen supports. You can add your bug reports or additional info to those issue.

Current player panel:
![shot_200725_191542](https://user-images.githubusercontent.com/8344157/88460200-956e8880-ceab-11ea-8095-11160e57abd1.png)

Compact mode example (small sizes):
![shot_200725_194502](https://user-images.githubusercontent.com/8344157/88460752-8d184c80-ceaf-11ea-92a2-3ca7b8529ffd.png)
