### ISSUE TITLE
GUI: improve small screens support (compact mode, pre-defined settings)

### ISSUE THREAD

**Issue by JayDi85** [magefree/mage#6887]
Additional issue from #6881 (see those discussion for more info). Small screen: 1366 × 768.

TODO:
* [x] optimize player panel (rework icons list, support dynamic sizes, e.g. small, normal, big)
* [x] check battlefield and hand zone sizes in small screen (I saw reports that users can't setup it to useful sizes by preferences);
* [x] check hand zone and horizontal scroll in small screens (see #5605);
* [x] add pre-defined size settings in preferences window (example: combobox with small, normal/default, big options to select);
* [x] add scrolling battlefield panels by mouse wheel (e.g. scrolls stack or hand zone by mouse wheel instead mouse click and move).

**Comment by copperfield42** [comment]
that compact version sound nice to finally have the avatar in gameplay, which with everything at minimum looks like this:
![game area 1](https://user-images.githubusercontent.com/4504719/88469203-d327dd00-cebc-11ea-8c24-7353cf799d68.png)

I could have some extra space by auto-hide the taskbar, but that come with a set of annoyances that outweigh a missing avatar.

Additionally, notice all that wasted space below the big card, it could be better use by putting the log there for example, so then one can close the chat and gain a little extra horizontal space, that at least playing with the AI the chat serve no purpose, or combine the big card with the chat and log and then the user can adjust them to their taste/needs.

**Comment by JayDi85** [comment]
@copperfield42 you can hide big card panel by little arrow:

![shot_200726_064136](https://user-images.githubusercontent.com/8344157/88470232-14df7480-cf0b-11ea-85bb-84daa2773567.png)

**Comment by copperfield42** [comment]
yes, I know I can do that, but I like the big card panel and hiding the chat also hide the log, and I don't want to hide the log, that is why I have it in that particular arrangement. 

I would like something like this:
![game-area-proposal](https://user-images.githubusercontent.com/4504719/88470713-dc6d7580-cecd-11ea-8361-7fa44e99bc40.png)
more space in the game area, and no more wasted space and all elements are present. 
And by letting them be adjustable (like the chat vs log are) the user can find their prefer arrangement
