### ISSUE TITLE
Testing Tools - cheat engine put permanents onto the battlefield without effects/init code (no counters bug)

### ISSUE THREAD

**Issue by Zerrisx** [magefree/mage#6888]
For example, Pillar of Origins will give no choices and enter with creature type "null", and Scrounging Bandar will enter with no counters and immediately die.  This is inconsistent, but most of the time the effect fails to trigger.  Probably 80% of the time or so.

Casting the cards normally - even if you cheated them into your hand - always seems to work, and flickering them with Felidar Guardian didn't cause any issues, so this is likely just a testing tools bug.

![image](https://user-images.githubusercontent.com/59861365/88471675-84d10900-ced1-11ea-8828-66b0f7e2b8d0.png)
![image](https://user-images.githubusercontent.com/59861365/88471678-8ac6ea00-ced1-11ea-9552-f4dccd541c8c.png)
![image](https://user-images.githubusercontent.com/59861365/88471664-5c490f00-ced1-11ea-9d67-870097bbf98d.png)

**Comment by JayDi85** [comment]
Try to use cheats on your turn. If you call it on opponent's turn -- it can be bugged (e.g. raise rollback error).

**Comment by JayDi85** [comment]
Fixed via 96155ec7993e3b5786c364cf10bfb948cbffc477. Now cheat engine puts cards to battlefield with all effects and other staff like counters. Works same as test framework (for battlefield putting).
