### ISSUE TITLE
Madness and Bag of Holding interaction

### ISSUE THREAD

**Issue by johnmeat** [magefree/mage#6889]
Playing Anje Falkenrath EDH.

Discarding a madness card with Bag of Holding on the battlefield. Layer the triggers so that the madness trigger resolves first:
![image](https://user-images.githubusercontent.com/64497504/88480854-5e9e7e00-cf50-11ea-862b-46d545f98594.png)

Resolve the madness trigger and select no to casting the card, so the madness card goes to the graveyard:
![image](https://user-images.githubusercontent.com/64497504/88480894-8ab9ff00-cf50-11ea-9682-e409b2fcd947.png)

Next when resolving the bag of holding trigger, nothing happens:
![image](https://user-images.githubusercontent.com/64497504/88480909-a32a1980-cf50-11ea-9b38-13571b15efa6.png)
i.e. the madness card is still in the graveyard, when it should be exiled by the bag of holding.

The below reddit post quotes the relevant rule:
https://www.reddit.com/r/magicTCG/comments/co9w83/bag_of_holding_does_not_trigger_for_cards_with/

"400.7i After resolving a madness triggered ability (see rule 702.34), if the exiled card wasn’t cast and was moved to a public zone, effects referencing the discarded card can find that object."

**Comment by jeffwadsworth** [comment]
I will check it tomorrow.  Should be a simple fix.

**Comment by jeffwadsworth** [comment]
`@Test
    public void testMadnessAndBagOfHolding() {
        addCard(Zone.BATTLEFIELD, playerA, "Bag of Holding", 1); // if card is discarded, exile it from the graveyard
        addCard(Zone.HAND, playerA, "Voldaren Pariah", 1); // creature with Madness
        addCard(Zone.HAND, playerA, "Raven's Crime", 1); // target player discards a card
        
        addCard(Zone.BATTLEFIELD, playerA, "Swamp", 1);  // pay for Raven's Crime
        
        castSpell(1, PhaseStep.PRECOMBAT_MAIN, playerA, "Raven's Crime", playerA);
        setChoice(playerA, "Voldaren Pariah");  // choose the madness card to discard to trigger Bag of Holding
        
        // choose the Bag of Holding trigger to be first on the stack, thus the Madness trigger fires first off the top
        setChoice(playerA, "Whenever you discard a card, ");
        setChoice(playerA, "No");  // choose not to use the Madness ability of Voldaren Pariah
        
        setStrictChooseMode(true);
        setStopAt(1, PhaseStep.POSTCOMBAT_MAIN);
        execute();
        assertAllCommandsUsed();
        
        assertExileCount(playerA, "Voldaren Pariah", 1);  // the card is found in the graveyard and exiled
        assertGraveyardCount(playerA, "Voldaren Pariah", 0);
        
    }`
