### ISSUE TITLE
Color == Color Identity

### ISSUE THREAD

**Issue by meetaig** [magefree/mage#6890]
Alesha, Who Smiles at Death triggers Demon's Horn

**Comment by LevelX2** [comment]
My tests do not confirm that here exists a problem.

Any special circumstances? 
Was Alesha the commander or s.th other special to mention?

**Comment by meetaig** [comment]
Hi, thanks for the quick reply. :)
Yes Alesha was the Commander and had been played out of the command zone if I remember correctly. It was a standard 4 player game.
