### ISSUE TITLE
Lands and mana dorks tapping for automatically correct color

### ISSUE THREAD

**Issue by fireshoes** [magefree/mage#690]
Mana dorks like Sylvan Caryatid and painlands don't currently tap for the necessary color automatically, even if just colorless mana is needed. It can be cumbersome to click each one and then click the appropriate color option. I've noticed some things do tap with automatic color selection though, like Noble Hierarch. It would be nice to streamline this option.

**Comment by fireshoes** [comment]
Can't wait to try it out!

**Comment by fireshoes** [comment]
Can you make the painlands (e.g. Battlefield Forge, Llanowar Wastes) default to colorless mana if that is all the spell needs to cast? Also possibly black mana from Urborg, Tomb of Yawgmoth when one is in play? :8ball:

**Comment by fireshoes** [comment]
With the changes that were made with the addition of colorless mana costs, would it be possible to take a look at the painlands and other lands being able to tap automatically for colorless? Or at least default to colorless if only generic mana payment is needed?

**Comment by Nightfirecat** [comment]
It would probably be better to open that as a new issue, not reopen this one.

**Comment by spjspj** [comment]
I was thinking about this as well.  With say Urborg, Tomb of Yawgmoth out, you get two options for a swamp ("Tap for {B}" and "Tap for {B}").   Having a hot-key to press while you tap the land could let you tap the land for the first available colour/colourless mana ability of the land if the user knows it's for generic mana.

**Comment by Zerrisx** [comment]
Cannot reproduce; this appears to be fixed.
