### ISSUE TITLE
Fervent champion reduction cost doesn't operate

### ISSUE THREAD

**Issue by MediaInBrain** [magefree/mage#6901]
Dear all,

I tried to equip a Fervent Champion with either a Batterskull (paying for the remaining equip cost) or Sword of Feast and Famine or a Sunforger. I did this trying to add mana in pool and without and randomly the equip did not work / but sometimes did. At least the equipment appear sometimes to have no activated ability, it could not be selected and this happened over the course of 4 different games.
I don't think it is a big issue but nonetheless the card Fervent Champion is not as such playable.

Thanks for helping fixing the issue.

PS: Shout out to the team for the xmage project you are doing a great job, many many thanks to all of you!!!!!

Cheers,

Mathieu

**Comment by Zerrisx** [comment]
Pretty sure this is also a duplicate of #6698; we don't correctly calculate the mana cost, and we won't let you equip if you have less than the un-reduced mana cost available.

**Comment by Zerrisx** [comment]
Fixed (on beta) with 82dfd76.  Will be in next release.

**Comment by MediaInBrain** [comment]
Thanks for taking care af this so rapidly
