### ISSUE TITLE
Jegantha, the Wellspring mana ability can pay for generic costs

### ISSUE THREAD

**Issue by bruhmomenthaver** [magefree/mage#6903]
Title. Tapping Jegantha, the Wellspring can pay for any type of mana cost.

**Comment by jeffwadsworth** [comment]
Hmm.  Right now, the mana condition passes in the "costToPay" and you can check things like "contains {G}", etc.  Also, a check for the current mana left to pay on a cost is not updated in the method.  If it were, you could just check the current mana left to pay string ie: get(0) and note whether it is a mana symbol or not.

**Comment by xenohedron** [comment]
See f0ca05e
