### ISSUE TITLE
Rakdos, Lord of Riots no longer works for colorless spells after latest update.

### ISSUE THREAD

**Issue by Kwhorstkamp** [magefree/mage#6917]
I had dealt a total of 11 damage to my opponents and attempted to cast Ulamog, the Infinite Gyre but it was not highlighted. Clicking on it does nothing.  Other creatures were cast-able, so long as they had a colored mana symbol in the casting cost.

**Comment by jeffwadsworth** [comment]
![Works](https://user-images.githubusercontent.com/1496996/89347921-437aef00-d671-11ea-820d-0102bed76594.jpg)
How did you do the damage?

**Comment by emerald000** [comment]
Make sure you do not have the full 11 mana available when trying to cast it.

**Comment by jeffwadsworth** [comment]
![Just 2 mana available still fires](https://user-images.githubusercontent.com/1496996/89348260-df0c5f80-d671-11ea-81b0-f499ca795096.jpg)
Still works.

**Comment by jeffwadsworth** [comment]
Works with direct damage (Lightning Bolt) as well.
