### ISSUE TITLE
Casting Tooth and Nail off of Praetor's Grasp does not allow proper selection of modes

### ISSUE THREAD

**Issue by SpikesCafe-google** [magefree/mage#6919]
If I exile [Tooth and Nail](https://scryfall.com/card/mma/170/tooth-and-nail) using [Praetor's Grasp](https://scryfall.com/card/nph/71/praetors-grasp) and attempt to cast it, I'm having issues picking the mode. Last night, even though I could produce 9 mana with lands and artifacts I controlled, it would only let me pick one mode and did not give an option to use the "Entwine" ability. When I attempted to recreate it today, it did not give me an opportunity to choose to cast it *without* Entwine, of which [I recorded a video](https://youtu.be/wmIfjmah9rs). Here's some freeform decks you can use to recreate against the AI. [xmage bug decks.zip](https://github.com/magefree/mage/files/5010885/xmage.bug.decks.zip)

**Comment by jeffwadsworth** [comment]
Yes, it is missing the correct code for that situation.

**Comment by jeffwadsworth** [comment]
This bug is related to the "owner" check done for the PLAY_FROM_NOT_OWN_HAND_ZONE effect.
