### ISSUE TITLE
Regarding memory usage

### ISSUE THREAD

**Issue by SofiaAViesti** [magefree/mage#6921]
I have a consistent issue where every in-game action takes longer and longer to respond, the longer the match take place. Today, I had to do a task manager shutdown as it just stopped completely.

>EDH multiplayer game (3 players total), vs CPU only

>Stay in a match for long enough until each task iteration starts to become really slow

>Have a Karn Liberated on the board and restart the game

>Early game tasks that should take far less than a second can take literally up to minutes (as it would in any 30 minutes+ match). Tried shutting down the server manually and restart, but had to force task manager to do it for me.

**Comment by JayDi85** [comment]
It's ok for AI games. Some situations or cards can generate too much variations for computer -- so it takes a long time to calculate all of it. Max freeze time between AI step priorities is 20-25 seconds and it depends on AI level in game settings (each level gives +3 seconds for calculations).
