### ISSUE TITLE
[[Bug]] Casting Overloaded Cyclonic Rift with Isochron Scepter

### ISSUE THREAD

**Issue by Simisays** [magefree/mage#6925]
This should not be possible, You can't pay two alternate costs for the same thing.

**Comment by jeffwadsworth** [comment]
Ruling:
If you cast a spell “without paying its mana cost,” you can’t choose to cast it for any alternative costs. You can, however, pay additional costs. If the card has any mandatory additional costs, those must be paid to cast the spell.

**Comment by johnmeat** [comment]
Cast by rebound also allows to play it overloaded. Taigum, Ojutai Master in EDH for example.

**Comment by JayDi85** [comment]
Fixed by 6bc5a00e8ac604bd98e927bd88f03486830126a8
