### ISSUE TITLE
Nantuko Monastery

### ISSUE THREAD

**Issue by Strategikon** [magefree/mage#693]
There is no Nantuko Monastery

**Comment by Strategikon** [comment]
no Coalition Victory too

**Comment by fireshoes** [comment]
Please leave requests for cards [here](http://www.slightlymagic.net/forum/viewtopic.php?f=70&t=14062&sid=c8ce32e64437724c7abedc323a33898f)

**Comment by Strategikon** [comment]
Didn't know, thanks! :)
