### ISSUE TITLE
Nissa, Nature's Artisan ultimate implementation affects non-creatures, has wrong text

### ISSUE THREAD

**Issue by SpikesCafe-google** [magefree/mage#6930]
In XMage, [Nissa, Nature's Artisan](https://scryfall.com/card/kld/270/nissa-natures-artisan) has:

> -12: Creatures you control get +5/+5. Permanents you control gain trample until end of turn.

It should be:

> -12: Creatures you control get +5/+5 and gain trample until end of turn.

True to the wording, Nissa's ultimate gives trample to non-creature permanents, but it should only give trample to creatures. Untrue to the wording, the +5/+5 ability does correctly end at end of turn.

**Comment by acabaca24** [comment]
Sugestion, on line:
https://github.com/magefree/mage/blob/e95b9f145cd4dcea52a4c09722c5fa01070ec4d5/Mage.Sets/src/mage/cards/n/NissaNaturesArtisan.java#L55

Change to:
`ability.addEffect(new GainAbilityControlledEffect(TrampleAbility.getInstance(),Duration.EndOfTurn,StaticFilters.FILTER_PERMANENT_CREATURES;`

source:
https://github.com/magefree/mage/blob/e95b9f145cd4dcea52a4c09722c5fa01070ec4d5/Mage.Sets/src/mage/cards/o/Overrun.java#L27-L30
