### ISSUE TITLE
Bug allows all Delve, Convoke, Improvise, and Assist cards to be cast for free 

### ISSUE THREAD

**Issue by Zerrisx** [magefree/mage#6937]
_Checked - this is broken in release as well as beta._

The following steps **for Delve**:

1) Have a delve card in your hand that you can currently put on the stack
![image](https://user-images.githubusercontent.com/59861365/89216595-46ea7980-d590-11ea-9d82-5593651bb769.png)

2) Float a mana of any color
![image](https://user-images.githubusercontent.com/59861365/89216617-536ed200-d590-11ea-88be-dccfa03441ac.png)

3) Cast the spell and click Special, so it asks what you'd like to delve
![image](https://user-images.githubusercontent.com/59861365/89216668-6bdeec80-d590-11ea-9983-d4677d444aaf.png)

4) Delve nothing, click Done, so it asks to pay with regular mana
![image](https://user-images.githubusercontent.com/59861365/89216694-7d27f900-d590-11ea-85ca-e030f304d0cf.png)

5) Click Cancel
![image](https://user-images.githubusercontent.com/59861365/89216725-8b761500-d590-11ea-8c3b-0aeb507ac807.png)

6) Click Done
![image](https://user-images.githubusercontent.com/59861365/89216752-992b9a80-d590-11ea-942b-5759216f2794.png)

Congratulations, you're still floating that one mana you floated in step 2 and you delved zero cards, but you cast your delve spell.  Whoops!

**For Convoke**, follow the same steps, except you'll need to tap at least *one* creature for convoke before canceling.  Same **for Improvise**; select at least one artifact.

**For Assist**, float a mana, then Special: choose another player before canceling and clicking done.

Hey look, we can cast March of the Multitudes for X=50 off two plains, a forest, and an Ornithopter:
![image](https://user-images.githubusercontent.com/59861365/89218192-3ee00900-d593-11ea-8460-6c7b7ffba1a7.png)

**Comment by Zerrisx** [comment]
@18ths @LevelX2 @JayDi85 I don't think I have the ability to pin issues, but somebody should likely pin this until it's fixed; it's pretty bad.

**Comment by JayDi85** [comment]
It's a rollback error (xmage somehow lost rollback state, so restores to wrong game state). I added unit test for that bug by f69477d8d5a934cb29848b9c8e628fb0dc186048 

Also server logs shown missing game state:
```
ERROR 2020-08-04 It was not possible to do the requested undo operation (bookmark 2 does not exist) context: draw three cards. =>[GAME xxx] GameImpl.restoreState 
INFO  2020-08-04 Saved states: [0, 1] =>[xxx] GameImpl.restoreState
```

**Comment by JayDi85** [comment]
Well, that bug must be fixed by bb148c9cb5ad6c716de4e958b7f07b591d987405 (tested it with delve and all works fine now). 

BUT that changed cast/activate canceling logic:
* old version: cancel button can restore mana tapped before and after card cast;
* new versions: cancel button can restore mana tapped after card cast only (so if you tapped mana for mana pool before cast then you can't reset it on cast cancel button).

If that new logic is not user friendly (I think it's ok) then rollback system must be reworked to store game states refs as UUID instead numbers.

**Comment by Zerrisx** [comment]
I think that's okay for now.  Worked for me with all four kinds of cards, so the fix looks good.

**Comment by JayDi85** [comment]
Bug details and bookmark logic for future generations:
* xmage uses global bookmark per user -- it helps to reset all tapped mana and other actions by rollback/cancel button;
* xmage uses local bookmark in effects/dialogs/engine -- it helps to reset some actions and returns to some point in the time;
* cancel or game restore process -- xmage take saved bookmark, find game state for it, restore it and delete all outdated bookmarks (all game states after restored point).
* put on stack logic uses bookmarks -- xmage create bookmark, put spell on stack and try to pay/activate it -- if something goes wrong then it reset saved bookmark (e.g. restore state to "empty" stack);
* global bookmark creates on first mana usage;
* some choose dialogs and cards can "close" global bookmark. It's a workaround to hide cancel button after some critical actions. As example: if player saw top library card then he can't cancel it. It uses `resetStoredBookmark` call to do that.
* the problem: that code (`resetStoredBookmark`) destroy all game states and all bookmarks after some point in time (example: all game states saved after first tapped mana will be lost)
* so after game states destroyed -- xmage can't find it for another cancel actions like "put on stack fail" -- and spell are keeps in stack (it's like it was cast for free). That's the current issue bug.


Steps to reproduce:
* activate something to put it on stack: ability (fixed), spell (fixed, tested), triggered (not fixed, not tested);
* tap card for mana (it will create save point -- e.g. "save" current stack);
* do some bad actions (game must cancel it somehow);
* stack restored to starting point (on first mana usage) -- it's important: object will be on stack, but all chosen targets or pays will be reset;

Potentially cheats/benefits:
* cast without payments;
* resolve ability without or unchanged targets;

Potentially bugged cards (that can broke game state), search by `resetStoredBookmark`
![shot_200804_224059](https://user-images.githubusercontent.com/8344157/89334783-23b2ed80-d6a8-11ea-875e-f6cd65ffd68e.png)

**Comment by Zerrisx** [comment]
Anything else we need to do here, or is this issue resolved, pending future enhancements?  (Also, I might copy your post above into a new enhancement/refactoring issue and link it to the rollback project)

**Comment by JayDi85** [comment]
It fixed and can be closed. I saw same bug reports before but can't find it in issues list. Just create new issue on new bug report.
