### ISSUE TITLE
Source code question - where is the deck import code?

### ISSUE THREAD

**Issue by use** [magefree/mage#6939]
Hello, was just wondering if someone can point me towards the code that performs the deck import? I found the [dialog box](https://github.com/magefree/mage/blob/857d888b767ac4ef70d39c0c443f400e4e212c93/Mage.Client/src/main/java/mage/client/deckeditor/DeckEditorPanel.java) but couldn't determine what happens after the buttons are clicked.

This is a feature I use a lot, and so I wanted to see how it works, and maybe even think of improvements some day - because it's pretty slow.

**Comment by JayDi85** [comment]
Look at `DeckEditorPanel->btnLoadActionPerformed`.

Cards import from text file (xmage read text file line by line and uses only valid records/cards -- it's fast):
* `DeckImporter.importDeckFromFile(...)`

Cards loading (xmage uses local cards database to load basic card info, database automaticity caches queries -- so first load will be slow, but second load will be fast):
* `Deck.load(...)`

Cards rendering/showing (It's the most slowing part of whole process. Xmage loads card images from disk and generates/draws it. Each generated image stores in images cache, so first render will be slow but second must be fast. BUT images cache eats many memory, so it can't store all cards and needs to clean up sometimes. Memory settings can help to increase it and improve loading performance. SSD or memory disk can help with performance too):
* `refreshDeck(...)`
