### ISSUE TITLE
Error with negative life and Fire Covenant, game enter error state

### ISSUE THREAD

**Issue by sourcenix** [magefree/mage#6942]
Hi,

I've found a small situational bug which causes a game to enter an error state. Once the bug is active you can no longer progress through the turn and the timer eventually runs out.

It seems to be related to paying life when the player is on negative life 

**To reproduce**

1. Have Platinum Angel on the battlefield
2. Be on negative life
3. Have Fire Covenant in hand
4. Click on Fire Covenant to cast it
5. Get an error message "Error: (Minimum = Value = Maximum) is false"
6. From this point on you can no longer interact with the board state or continue your turn

**What should happen**
When you try to cast Fire Fire Covenant or any spell with a cost of X where X is life (While on negative life). The player should be told that they cannot pay more than 0.

The game should continue.

**Notes**
In the specific scenarios in the pictures I was on negative life for multiple turns without problems. But once i drew Fire Covenant and click on the spell I got the error.

![xMage-Bug](https://user-images.githubusercontent.com/17862484/89498952-7b904800-d7bf-11ea-8696-f21f568eb562.PNG)
![xMage-Bug-Example2](https://user-images.githubusercontent.com/17862484/89498993-8d71eb00-d7bf-11ea-9449-0279d3f67d7e.PNG)

**Comment by Alex-Vasile** [comment]
[[Platinum Angel]], [[Fire Covenant]]
