### ISSUE TITLE
Bug: Meld doesn't work properly with protection

### ISSUE THREAD

**Issue by duelcastermage** [magefree/mage#6945]
I had Bruna, the Fading Light and Gisela, the Broken Blade both in play. Bruna had protection from white from a temporary effect. I go to my end step, and the two creatures do not meld on XMage (they stay separate). I checked with mtg judge chat IRC and they confirmed that the two creatures should in fact still meld.

**Comment by jeffwadsworth** [comment]
I tested this after giving them both Protection from White individually and it worked fine.  Stave Off was used for the protection.

**Comment by jeffwadsworth** [comment]
![WorksFine](https://user-images.githubusercontent.com/1496996/90288623-dd942180-de3f-11ea-862e-49ccda2c5b2a.jpg)

**Comment by Alex-Vasile** [comment]
It's been two years and not reproduced. Closing this as stale. If it happens again, or someone can reproduce it then it will be re-opened
