### ISSUE TITLE
Helm of Obedience is bugged in regards to Planeswalkers

### ISSUE THREAD

**Issue by rexelallan** [magefree/mage#6948]
![Untitled](https://user-images.githubusercontent.com/42716000/89729512-03e54600-da69-11ea-9dd6-f524efb7026a.jpg)

**Comment by jeffwadsworth** [comment]
How so?  Can you explain the issue?  Screenshot of my test attached.
![testWorkedFine](https://user-images.githubusercontent.com/1496996/89971118-faeaa500-dc1f-11ea-9c0a-937f9751f2be.jpg)

**Comment by rexelallan** [comment]
it happened to me 2x already. if it flipped a walker, like Ugin on my image, it got sacrificed.

**Comment by rexelallan** [comment]
x =1. and ugin is exactly on top. it continue on your testing because elspeth location is not equal to value of x

**Comment by jeffwadsworth** [comment]
The beta version is fixed via 6fd304e
If you don’t have the beta version, you will have to wait for the new release.

**Comment by Zerrisx** [comment]
Duplicate of #6862
