### ISSUE TITLE
Can't connect to server

### ISSUE THREAD

**Issue by seedds** [magefree/mage#695]
Got this error many times.
Restart the server usually fix this, but sometimes it doesn't work, and I don't know what to do.

![untitled](https://cloud.githubusercontent.com/assets/3463322/5890841/80bdbe7c-a4ab-11e4-9fe3-e90eebcbe872.png)
![untitled](https://cloud.githubusercontent.com/assets/3463322/5890847/dc37aa42-a4ab-11e4-9ddc-2def73c1e214.png)

**Comment by LevelX2** [comment]
Maybe the cards database file of the server can be corrupted.
Try to delete the .../[mage-server]/db/cards* files and restart the server.

**Comment by LevelX2** [comment]
Did some changes to the cards data comparison for the next release. Let's see if this does help for this problem. Because the getMissingCardsDara will be only executed if needed, not like now, every time a user connects to the server.

**Comment by goesta** [comment]
I'll close this issue because there where no feedback for a long time but feel free to create a new one if this is still a problem.
