### ISSUE TITLE
Ghostly Pilferer gives draw trigger from your own casts from command zone

### ISSUE THREAD

**Issue by JeremyTheMiner** [magefree/mage#6951]
During an EDH game, an opponent cast his own Oona, Queen of the Fae from the command zone with a Ghostly Pilferer in play.  He then got a draw trigger from it.  There were no other copies of Ghostly Pilferer in play.  Chat log follows.

12:39 PM, T29.M1: Sea_Pancake casts Oona, Queen of the Fae [feb]
12:39 PM, T29.M1: Ability triggers: Ghostly Pilferer [27a] - Whenever an opponent casts a spell from anywhere other than their hand, draw a card.
12:39 PM, T29.M1: Sea_Pancake draws a card
12:39 PM, T29.M1: Sea_Pancake puts Oona, Queen of the Fae [feb] from stack onto the Battlefield

**Comment by acabaca24** [comment]
The same happens when you cast cards from your graveyard. It's not filtering for opponents only. I'm having a look at that
