### ISSUE TITLE
Once Upon A Time Bug

### ISSUE THREAD

**Issue by jasonywang0** [magefree/mage#6954]
Once Upon A Time may not always be cast as the first spell of a player's turn. The bug seems to be intermittent. Attached are screenshots showing the bug live on the .de server. The second screenshot is the opponent's hand.
<img width="1280" alt="Screen_Shot_2020-08-09_at_9 38 12_PM" src="https://user-images.githubusercontent.com/59207918/89761867-2e082980-daa4-11ea-8a64-daf9a361f003.png">
<img width="610" alt="Screen_Shot_2020-08-09_at_7 39 45_PM" src="https://user-images.githubusercontent.com/59207918/89761912-437d5380-daa4-11ea-87a7-664f00c2d372.png">

**Comment by LevelX2** [comment]
The code seems in order.

Is it possible that inadvertently the first displayed query to cast the spell without mana cost was denied?

**Comment by THUNDERWANG** [comment]
This bug still occurs in tournaments. I tested it again recently. If you have 4 players join a sealed tournament with decks just consisting of Once Upon a Time, at least one of the players will not be able to cast it for free in a round.

**Comment by theelk801** [comment]
This is a bug that's hard to test for but I think I may have found a solution to it, we'll see if it keep coming up.

**Comment by JayDi85** [comment]
> at least one of the players will not be able to cast it for free in a round.

Looks like Range of Influence game settings. Table owner enabled it accidentally so one player ignored by effects or visibility from another one.

**Comment by theelk801** [comment]
I don't think it's a multiplayer game, just a four player tournament. I think the issue is because of how watchers get copied and shared between games since this watcher doesn't reset the way other ones do.

**Comment by awjackson** [comment]
According to @theelk801 on Discord, this should have been fixed by f9571398b560efebb0e9b3ff5d85f343dfccf8db ..
