### ISSUE TITLE
Jadelight Ranger oracle text inaccuracy

### ISSUE THREAD

**Issue by acabaca24** [magefree/mage#6958]
The text **", then it explores again."** is being replaced by **".(Reveal the top card of your library. Put that card into your hand if it’s a land. Otherwise, put a +1/+1 counter on this creature, then put the card back or put it into your graveyard. Then repeat this process.) It explores."** only when the card is on the field and the trigger is in the stack.
Doesn't happen anywhere else(that I have tested).

In deck editor:
![deckeditor](https://user-images.githubusercontent.com/61804801/89913278-72521180-dbeb-11ea-9447-6da40c33f390.png)
In hand:
![inhand](https://user-images.githubusercontent.com/61804801/89913296-7847f280-dbeb-11ea-8cd1-cf0979cae868.png)
In the stack
![instack](https://user-images.githubusercontent.com/61804801/89913313-7bdb7980-dbeb-11ea-8f55-00c655d29f5e.png)
On the field:
![infield](https://user-images.githubusercontent.com/61804801/89913354-885fd200-dbeb-11ea-9840-3335f28dd1bf.png)
Trigger in the stack:
![trigger](https://user-images.githubusercontent.com/61804801/89913384-90b80d00-dbeb-11ea-9fb0-2e61679a4c9c.png)

**Comment by JayDi85** [comment]
Fixed by 615fba5a72882f99f9aa1aacc34788ed01eec9eb
