### ISSUE TITLE
Missing Interaction with Hooded Blightfang

### ISSUE THREAD

**Issue by scien30** [magefree/mage#6959]
an interaction between Hooded Blightfang and Ohran Frostfang/Bow of Nylea.

508.1k. Each chosen creature still controlled by the active player becomes an attacking creature. It remains an attacking creature until it's removed from combat or the combat phase ends, whichever comes first. See rule 506.4.

508.1m. Any abilities that trigger on attackers being declared trigger.

so Bow and Ohran say "attacking creatures you control have deathtouch" as a state based action prior to triggers being checked for. so every attacking creature should trigger Hooded Blightfang if it and at least one of Ohran Frostfang or Bow of Nylea are out.

**Comment by jeffwadsworth** [comment]
![WorksHere](https://user-images.githubusercontent.com/1496996/90072388-fa541c00-dcbc-11ea-9b67-c8ca1c9d8d2c.jpg)

**Comment by scien30** [comment]
then is it specifically with Ohran Frostfang? could also have been that specific game got its layering messed up during the match.
