### ISSUE TITLE
 Auto-lose with certain commanders 

### ISSUE THREAD

**Issue by catman123456** [magefree/mage#6960]
The client sometimes causes me to auto-lose with certain commanders and cards combos. K'rrick + Vilis, Broker of Blood + Bolas's Citadel is one of the combos

**Comment by JayDi85** [comment]
What's lose reason (life, cards in library)? Can you show steps to reproduce that bug (what's cards, targets, choices to use)?

**Comment by catman123456** [comment]
With Vilis, Broker of Blood + Bolas's Citadel combo it seems to happen when paying life.

**Comment by catman123456** [comment]
It seems not to be happening in free form commander.

**Comment by catman123456** [comment]
Here is a example of the Bolas's Citadel auto lose condition with the error report.
<img width="1920" alt="Untitled" src="https://user-images.githubusercontent.com/64045003/90014634-6f036800-dc75-11ea-9e4f-e61a30d36c76.png">

Game exception occurred: java.lang.NullPointerException
Server version: 1.4.44V0 (build: 2020-07-10 15:51)
mage.players.PlayerImpl.restore(PlayerImpl.java:349)
mage.game.GameState.restore(GameState.java:219)
mage.game.GameImpl.restoreState(GameImpl.java:712)
mage.game.GameImpl.playPriority(GameImpl.java:1369)
mage.game.turn.Step.priority(Step.java:61)
mage.game.turn.Phase.playStep(Phase.java:184)
mage.game.turn.Phase.play(Phase.java:89)
mage.game.turn.Turn.play(Turn.java:126)
mage.game.GameImpl.playTurn(GameImpl.java:893)
mage.game.GameImpl.play(GameImpl.java:802)
mage.game.GameImpl.start(GameImpl.java:766)
mage.server.game.GameWorker.call(GameWorker.java:34)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)

**Comment by Zerrisx** [comment]
This looks very similar to #6738; I suspect it's a duplicate (though perhaps you can provide more information to help track it down?)

**Comment by JayDi85** [comment]
Nope, it's a different bug. If game catches too much errors then it will be closed.

**Comment by Zerrisx** [comment]
> Here is another one I cast Aetherflux Reservoir and my hand disappear and lost the game. Vilis is the commander this time.

from 6738:

> Huh - this was also reported in the Discord by Merv, who said that his library/graveyard kept disappearing in multiplayer commander games, often in response to K'rrik, Son of Yawgmoth / Vilis, Broker of Blood interactions, and resulting in him immediately decking and losing the game. He also had a video as evidence, it was very strange.

Those were the parts I was referring to.  The eventual crash is different, though that might just be a downstream consequence.

**Comment by catman123456** [comment]
<img width="1920" alt="Untitled" src="https://user-images.githubusercontent.com/64045003/90555616-a38b8e00-e165-11ea-9627-ba8661ae6719.png">
Kess is my commander when I sacked the wooden foothills my hand disappear and I lost the game.

**Comment by Alex-Vasile** [comment]
This was though to be a copy of #6738. That issue was closed. I am marking this as unconfirmed until someone tests it and can reproduce.
