### ISSUE TITLE
helm of obedience , seriously bugged.

### ISSUE THREAD

**Issue by rexelallan** [magefree/mage#6963]
![image](https://user-images.githubusercontent.com/42716000/90110177-66975400-dd7f-11ea-83dc-cbded141057f.png)

**Comment by jeffwadsworth** [comment]
The beta version is fixed via https://github.com/magefree/mage/commit/6fd304ec5ff39a6ad619819ccef00c4211d5b7e5
If you don’t have the beta version, you will have to wait for the new release.

**Comment by Zerrisx** [comment]
Closing as fixed, pending next release.  (There aren't any code changes we can make to resolve this faster)
