### ISSUE TITLE
Constant disconnects

### ISSUE THREAD

**Issue by aastrand** [magefree/mage#697]
I keep disconnecting all the time. Often without being able to reconnect, thus timing out the game.
Lately I have been unable to finish a single game, it has certainly gotten worse.
Seems to happen 20-30 minutes in to a constructed game or draft tournament, which makes it even more annoying.

Xmage is close to unplayable for me. How can I help? What can we do?

**Comment by Falcon108** [comment]
Me too...been happening bad all day for me, and ppl I have been playing with.  Can't even get through a whole game most of the time.

**Comment by LevelX2** [comment]
Indeed, Yesterday was no good day of the server.
Thanks for your feedback. Issue is generally handled here:
https://github.com/magefree/mage/issues/662
