### ISSUE TITLE
Vedalken Orrery Missing

### ISSUE THREAD

**Issue by XVicarious** [magefree/mage#698]
This card is missing from Fifth Dawn and Conspiracy: http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=382398

Vedalken Orrery (4)
Artifact
You may cast nonland cards as though they had flash.

**Comment by LevelX2** [comment]
We are aware of missing cards. They have to be implemented concerning there abilities.

You can add your demands here:
http://www.slightlymagic.net/forum/viewtopic.php?f=70&t=14062&sid=b2d78ac0d7d13ea13b4bb8ec955edd82
http://www.slightlymagic.net/forum/viewtopic.php?f=70&t=4554&sid=b2d78ac0d7d13ea13b4bb8ec955edd82
