### ISSUE TITLE
Possibility of accessing game logs and states

### ISSUE THREAD

**Issue by alecvn** [magefree/mage#6982]
Hi

I was just wondering what the possibility would be of accessing the game logs and/or states of games played (anonymised of course) on at least the main (.de) Xmage server.  Are these things being recorded and kept in a database or in log files?

I've been building an AI tool which tries to estimate the viability of any given card based on a given meta of decks.  The tool is quite accurate but as soon as new mechanics are brought in the AI is understandably not sure how this interacts with other cards.  I've been thinking of training it on game actions or board states in addition to tokenised oracle text and types - the latter of which I'm currently using to train already - but then I obviously need access to large amounts of game data.

Would the maintainers be willing to collaborate on this?  Should I rather email someone about it?

**Comment by JayDi85** [comment]
XMage don't store any game logs or game states on server side. Only final game results without any data like decks.

There are possible special server mode with game states history in json format (see #4554 and #4515), but it's outdated and not tested/completed. Also you can try to search some related discussions by [graphql](https://github.com/magefree/mage/issues?q=is%3Aissue+graphql+).

You can write your requirements and examples: what you want to do and what you want to get from servers. If it possible to implement then I can add it to servers (e.g. collects useful data for analyse).

**Comment by JayDi85** [comment]
If you have any other questions or requests then write it here or create new issue. I'll close current topic until discussion's continue.
