### ISSUE TITLE
Either Golos, Tireless Pilgrim or spreading plague is bugged

### ISSUE THREAD

**Issue by samsonicus** [magefree/mage#6984]
Golos got destroyed by spreading plague when a player played a red creature, and all colored creatures got destroyed when golos got played.

**Comment by acabaca24** [comment]
I'm guessing that has something to do with #6890

**Comment by samsonicus** [comment]
> I'm guessing that has something to do with #6890

Yeah, this were also a commander game with golos as commander. So might be an issue with cards tagged as commander returning their color identity instead of their color.

**Comment by JayDi85** [comment]
All works fine (Spreading Plague uses object's color, not color identity). Added related test by 4aeb94b41c2325339cecd4a1416bfcb09a299e71
