### ISSUE TITLE
Earthcraft and Arbor Elf suggestion

### ISSUE THREAD

**Issue by Beroestheenvoy** [magefree/mage#6988]
When using Earthcraft or Arbor Elf there is a prompt that pops up and asks to choose option to activate when using theese cards. Sometimes with large amount of creatures it would be much faster if the prompt didn't pop up and user of Earthcraft could select a basic land right away. It would work like skull clamp, because when user clicks on skullclamp it asks to seleck a creature to equip without prompt showing asking to select equip option.  For Arbor Elf it would be just quicker because it would work more like other elves that just tap for mana.

**Comment by LevelX2** [comment]
That's controlled by a preference setting to prevent accidental use of abailities.
You can turn the option off to be able to play faster.

![grafik](https://user-images.githubusercontent.com/2066790/103221212-5e047c00-4922-11eb-856c-e0e6f1eb9419.png)
