### ISSUE TITLE
Continuous effects in multiplayer

### ISSUE THREAD

**Issue by brunolustosa** [magefree/mage#6997]
Some continuous effects should stay in play even after the player that set them leaves the game.
Example:

Player A: Casts Vorinclex, Voice of Hunger
Player B: Taps all lands and do stuff (lands shouldn't untap during his next untap step)
Player C: Kills Player A
Player B: Lands untapped normally, though they shouldn't

This happened playing commander against 3 AIs. One of the AIs played Vorinclex, I tapped all my lands during my turn to do stuff. Next AI killed the one that had Vorinclex. When the game got to my turn, my lands untapped normally.

**Comment by jeffwadsworth** [comment]
Yes, some effects must be separated from the source card/ability so that they continue after the source is gone.  I you see other cards like this, please note them here.

**Comment by JayDi85** [comment]
@LevelX2 can you look at `AffinityEffect` example? It uses `Custom` duration, but don't have code with `discard` call or `inactive` method. So is it possible to spam game by effects from `Mycosynth Golem` by `GainAbilityControlledSpellsEffect(new AffinityForArtifactsAbility()...)`?
