### ISSUE TITLE
FilterControlledCreaturePermanent must be checked and replaced in some cards

### ISSUE THREAD

**Issue by JayDi85** [magefree/mage#7008]
Bug related to #7006

Many abilities contains only type name in rules -- so filter must search permanent, not creatures. But xmage uses `FilterControlledCreaturePermanent` for permanents search, so it can be bugged in some situations.

Example: [Elvish Archdruid](https://scryfall.com/card/jmp/391/elvish-archdruid)
* `Other Elf creatures you control get +1/+1.` - search creatures
* `{T}: Add {G} for each Elf you control.` - search permanents

Search code: 
* `new FilterControlledCreaturePermanent(`
* All filters without `creature` text in name must be checked and fixed (replace with `FilterControlledPermanent`):
![shot_200826_201214](https://user-images.githubusercontent.com/8344157/91328867-85163a00-e7d8-11ea-8c39-cedc2149f6c3.png)

**Comment by theelk801** [comment]
Yeah, I knew this was gonna need more work when I fixed the other one.
