### ISSUE TITLE
Historic matches not shown in the list

### ISSUE THREAD

**Issue by Revan2000** [magefree/mage#7009]
When I create a Historic match it doesn't appear in the matches list, so other players can't join.

![Historic game](https://user-images.githubusercontent.com/36141078/91329816-d9dc9500-e785-11ea-9ee4-7cc0ba26eea8.png)

**Comment by JayDi85** [comment]
Fixed via 40fe3b137e52805dce19f8ae7db6167feb134c8d, will be available with next hotfix/release (soon).
