### ISSUE TITLE
Torment of Hailfire against AIs

### ISSUE THREAD

**Issue by brunolustosa** [magefree/mage#7011]
Playing against 2 AIs, I cast Torment of Hailfire for X=25.
Was expecting a swift end to the game, but each AI only sacrificed a couple permanents. No discard, no loss of life.
This was the log:

1:58 PM, T21.M1: XLust announces a value of 25 for  {X}
1:58 PM, T21.M1: XLust casts Torment of Hailfire [1b2]
1:58 PM, T21.M1: Ability triggers: Saheeli, Sublime Artificer [fd8] - Whenever you cast a noncreature spell, create a 1/1 colorless Servo artifact creature token.
1:58 PM, T21.M1: Ability triggers: Young Pyromancer [9f9] - Whenever you cast an instant or sorcery spell, create a 1/1 red Elemental creature token.
1:58 PM, T21.M1: XLust creates a Elemental [053] token
1:58 PM, T21.M1: XLust creates a Servo [218] token
1:58 PM, T21.M1: Computer 3 sacrificed a creature without name
1:58 PM, T21.M1: Computer 2 sacrificed Otherworld Atlas [4c9]
1:58 PM, T21.M1: Computer 3 sacrificed Vraska, Golgari Queen [5ee]
1:58 PM, T21.M1: Computer 3 sacrificed Evolutionary Leap [220]
1:58 PM, T21.M1: XLust puts Torment of Hailfire [1b2] from stack into their graveyard

This is a screenshot of their boards after Torment resolving.

![2020-08-26-1598461327](https://user-images.githubusercontent.com/13102277/91334026-c68cf200-e7a4-11ea-98a9-1ccc5d5cc4d7.jpg)

**Comment by brunolustosa** [comment]
Ignore the part about Pyromancer's Goggles, forgot Torment isn't a red spell.

**Comment by brunolustosa** [comment]
Just to add: when it got to the AI's turn, it decked out (bug #6738 apparently) and lost. Then, as soon as it got to the other AI's turn, it also decked out.

**Comment by copperfield42** [comment]
I also got something similar, I cast a Torment of Hailfire X=30 against 3 AI, they sacrifice everything they have, but of notice was that they have like to much life points, but I didn't give to much thought to it at the moment, and finish one of them with commander damage, them the rest immediately lost in their turn

**Comment by LevelX2** [comment]
Source code of Torment of Hailfire looks ok.
In a quick test game card worked agains AIs like expected.

Guess it's caused by AI players already bugged from #6738 state.
