### ISSUE TITLE
Problems running the server from IntelliJ for the first time

### ISSUE THREAD

**Issue by Ezekieru** [magefree/mage#7013]
Hi!
I ran into this problem when trying to run the server

Exception in thread "main" java.lang.NullPointerException
    at mage.server.util.ConfigSettings.isAuthenticationActivated (ConfigSettings.java:106)
    at mage.server.Main.main (Main.java:84)

Process finished with exit code 1

I followed the steps outlined at https://github.com/magefree/mage/wiki/Setting-up-your-Development-Environment for IntelliJ IDEA, double-checked them, and also made sure I have the latest branch. I haven't touched anything in the code yet, so I think there must be some detail in the configuration that I'm missing.

**Comment by acabaca24** [comment]
I might not be the best person to answer this, but did you compile the project with maven before running?

**Comment by JayDi85** [comment]
Also after maven's full install you must check working folder. I think server can't find `config/config.xml` file -- so it can be wrong working directory:

![shot_200828_002719](https://user-images.githubusercontent.com/8344157/91491539-401c0180-e8c5-11ea-8b6c-f91dc5b42495.png)

**Comment by Ezekieru** [comment]
> Also after maven's full install you must check working folder. I think server can't find `config/config.xml` file -- so it can be wrong working directory:
> 

Thank you, this was the problem, I was up and running the server and the client.
