### ISSUE TITLE
Game error when casting Treasure Cruise using Delve

### ISSUE THREAD

**Issue by brunolustosa** [magefree/mage#7023]
Got an exception. Was playing commander against a human.

Game exception occurred: java.lang.ClassCastException: mage.game.stack.Spell cannot be cast to mage.game.stack.StackAbility
Server version: 1.4.45V1 (build: 2020-08-29 20:13)
mage.cards.r.RingsOfBrighthearthTriggeredAbility.checkTrigger(RingsOfBrighthearth.java:69)
mage.abilities.TriggeredAbilities.checkTrigger(TriggeredAbilities.java:94)
mage.abilities.TriggeredAbilities.checkTriggers(TriggeredAbilities.java:51)
mage.game.GameState.handleEvent(GameState.java:733)
mage.game.GameImpl.fireEvent(GameImpl.java:2771)
mage.players.PlayerImpl.specialAction(PlayerImpl.java:1383)
mage.players.PlayerImpl.activateAbility(PlayerImpl.java:1444)
mage.player.human.HumanPlayer.activateAbility(HumanPlayer.java:1924)
mage.player.human.HumanPlayer.activateSpecialAction(HumanPlayer.java:1915)
mage.player.human.HumanPlayer.playManaHandling(HumanPlayer.java:1249)
mage.player.human.HumanPlayer.playMana(HumanPlayer.java:1220)
mage.abilities.costs.mana.ManaCostsImpl.pay(ManaCostsImpl.java:136)
mage.abilities.AbilityImpl.activate(AbilityImpl.java:382)
mage.abilities.ActivatedAbilityImpl.activate(ActivatedAbilityImpl.java:256)
mage.game.stack.Spell.activate(Spell.java:129)
mage.players.PlayerImpl.cast(PlayerImpl.java:1226)
mage.players.PlayerImpl.activateAbility(PlayerImpl.java:1450)
mage.player.human.HumanPlayer.activateAbility(HumanPlayer.java:1924)
mage.player.human.HumanPlayer.activateAbility(HumanPlayer.java:1947)
mage.player.human.HumanPlayer.priority(HumanPlayer.java:1093)
mage.game.GameImpl.playPriority(GameImpl.java:1339)
mage.game.turn.Step.priority(Step.java:61)
mage.game.turn.Phase.playStep(Phase.java:184)
mage.game.turn.Phase.play(Phase.java:89)
mage.game.turn.Turn.play(Turn.java:126)
mage.game.GameImpl.playTurn(GameImpl.java:879)
mage.game.GameImpl.play(GameImpl.java:791)
mage.game.GameImpl.start(GameImpl.java:776)
mage.server.game.GameWorker.call(GameWorker.java:34)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)

**Comment by JayDi85** [comment]
It can be fixed in last commits by x2 from #6753 (special action logic were replaced by special triggers instead ability triggers).

**Comment by JayDi85** [comment]
Fixed last year in #6753
