### ISSUE TITLE
Asterisk (*) card numbers messing up 10E, WAR images

### ISSUE THREAD

**Issue by duelcastermage** [magefree/mage#7027]
After the 1.4.45 update, some sets got populated in the deck editor that are duplicates and have asterisks next to the card image.  So far I have only noticed 10E and WAR, but there may be others. The image downloader cannot find the proper pictures for these and games I've played have had missing images as a result. See attached pic and highlighted row in the table area.
![WAR 10E bad images](https://user-images.githubusercontent.com/46700039/91659430-b12f0500-eacf-11ea-90c9-06d98bebdad0.png) 
![image](https://user-images.githubusercontent.com/46700039/91659437-c3a93e80-eacf-11ea-95bb-125ae7872671.png)

**Comment by JayDi85** [comment]
Follow instructions from #7020 to enable utf-8 character set in launcher and download missing images. Maybe you need to re-download broken set.
