### ISSUE TITLE
Dance of the Dead and Animate Dead are bugged

### ISSUE THREAD

**Issue by johnmeat** [magefree/mage#7031]
To recreate, have Balduvian Bears in the graveyard, play Dance of the Dead targeting the Bear. Dance of the Dead appears on the battlefield, as its ability resolves it just disappears and then says Dance of the dead was put into a graveyard, therefore the Bear is sacrificed.

![image](https://user-images.githubusercontent.com/64497504/91728442-fec47400-eb9a-11ea-8538-fdc4cf12ac1d.png)

**Comment by jeffwadsworth** [comment]
Narrowed it down to some update done between July 1st and August 1st of this year.  It shouldn't take too much longer to find the culprit.
