### ISSUE TITLE
KLD Islands all have the same image

### ISSUE THREAD

**Issue by Ebola16** [magefree/mage#7038]
Example of an incorrect image:
![2020-09-02](https://user-images.githubusercontent.com/17330088/91931627-ff036300-ecb1-11ea-9887-d900227f8bca.png)

**Comment by JayDi85** [comment]
It's old images from one of the old version. Current version works fine. Use re-download checkbox and download KLD again.

![shot_200902_121655](https://user-images.githubusercontent.com/8344157/91956915-64893b00-ed16-11ea-90c6-325ce7cb1c5a.png)
