### ISSUE TITLE
Race condition with automatic reconnects

### ISSUE THREAD

**Issue by aastrand** [magefree/mage#704]
I've been having an issue now with all the disconnections:
When I've been reconnected I have gotten the "Connection to server was lost, reconnect"  JPOptions panel sometimes, but having actually automatically reconnected somehow (I guess through the automatic option in the connect panel?). Clicking no here disconnects you if you're already connected.

It seems to me like one could omit the else {session.disconnect()} statement to avoid this, but is it there for some other reason? Perhaps not show the JPoption if automatic reconnects are on. It's kind of annoying :)

I'll submit a PR if you think its a good idea.

**Comment by LevelX2** [comment]
I know there are some flaws in the current implementation.
But it's hard to test, because one can't easily produce the disconnects that happen on public serv er.

Sure make a pull request with the change you have in mind, I will have a look.

**Comment by goesta** [comment]
I'll close this issue because it seems to be outdated.
