### ISSUE TITLE
Fae of Wishes and Omniscience bug : Possibly related to #6698

### ISSUE THREAD

**Issue by Drampadario** [magefree/mage#7040]
When I have Omniscience on my field, I cannot use my fae's second effect "granted". With Omniscience on the field, I can only cast Fae of Wishes as a creature spell.

**Comment by jeffwadsworth** [comment]
![WorksFine](https://user-images.githubusercontent.com/1496996/92128333-e84f3000-edc7-11ea-9426-eed47ed355b4.jpg)
![worksFine2](https://user-images.githubusercontent.com/1496996/92128362-ec7b4d80-edc7-11ea-9443-fee516703bd4.jpg)

**Comment by acabaca24** [comment]
@jeffwadsworth I went to give it a try and it only asks you if want to cast granted, if you have enough mana to cast it.
If you just have omniscience in play with no lands, it doesn't ask you and only casts fae.
I'm guessing this as something to do with #6698

**Comment by JayDi85** [comment]
Fixed by #7152
