### ISSUE TITLE
Price of Glory causes a huge streak of triggers when it shouldn't

### ISSUE THREAD

**Issue by Beroestheenvoy** [magefree/mage#7042]
When a card Price of Glory is played it triggers randomly, even though no lands were tapped for mana. Every land tapped for mana causes a huge streak of triggers that destroy it's controler's lands, even those that were not tapped for mana.

**Comment by Beroestheenvoy** [comment]
I tested it today also and it seems to trigger during each player's upkeep for every untapped land their opponents control and destroys those lands. When a land is destroyed this way it triggers again for every untapped land they control and destroys them. This process continues until they no longer have untapped lands.

**Comment by jeffwadsworth** [comment]
Works fine for me.

**Comment by Beroestheenvoy** [comment]
Tested it today again and still works not properly. I'll try providing screenshots from the game.

**Comment by JayDi85** [comment]
That card were fixed by 546e129d511624e22ba8a2504a0809805d3adb47 (random triggers on mana calculations), but that fix in [beta client](http://xmage.today/) only. Will be available in next release.
