### ISSUE TITLE
Sets with double faces cards can have wrong booster ratio

### ISSUE THREAD

**Issue by JayDi85** [magefree/mage#7043]
From [here](https://github.com/magefree/mage/commit/c2e801341f4be79640bb9cb97f20a62c3bed3822). XMage uses different booster ratio for some kind of cards. Example: if booster must contains 5 common cards then xmage search all common cards from set and take 5 random cards from that list. 

Problem: some double faces cards can be duplicated in set's list (as normal/face card and as second side face). So that sets gets 2x ratio for double faces cards. It's not a critical error, but wrong and must be fixed someday.

TODO:
* [ ] find sets with duplicated double faces cards (set contains both sides);
* [ ] add ignore second side in boosters generation code;

What can be checked -- if card have second/another side card then search it in set's list -- if set contains it then booster code must be fixed:
   * [ ] split, aftermath, fused
   * [ ] flip
   * [ ] transform
   * [ ] adventure

**Comment by awjackson** [comment]
> split, aftermath, fused

Split cards are a special kind of card object where the two halves are not treated as separate cards for set list purposes. For example `Invasion.java` contains a single card named "Assault // Battery", not two separate cards "Assault" and "Battery".

> flip

The secondary sides of flip cards are not treated as real cards for set list purposes. For example `ChampionsOfKamigawa.java` contains a card named "Akki Lavarunner" but does not contain a card named "Tok-Tok, Volcano Born". In fact the flipped sides of flip cards seems to be treated by xmage as a special kind of _token_ and not as a card at all.

>adventure

Similarly to split cards, adventure cards and modal DFCs are special kinds of card object and the secondary side does not exist as a distinct card. 

>transform

Unlike the rest of these, the back sides of transforming DFCs _do_ exist as separate cards in set lists. However, `buildQuery` in `CardCriteria.java` specifically excludes transformed sides of TDFCs (`nightCard`) ahead of any other criteria:

```
    public void buildQuery(QueryBuilder qb) throws SQLException {
        optimize();

        Where where = qb.where();
        where.eq("nightCard", false);
        where.eq("splitCardHalf", false);
```

Booster generation issues do not exist for any of the named categories of cards and this issue should be closed.
