### ISSUE TITLE
Helptext hints are a little bit blinding in neon green

### ISSUE THREAD

**Issue by Zerrisx** [magefree/mage#7047]
We might wish to tone down the color choice a bit; perhaps to a more forest-y green shade.
![image](https://user-images.githubusercontent.com/59861365/92333893-9966fc00-f04e-11ea-8306-6777b0f8d32e.png)

**Comment by JayDi85** [comment]
Fixed by 01c7ed3e70dc9b2c0241de9b6dc953d293ffd92b
