### ISSUE TITLE
Card Types hints

### ISSUE THREAD

**Issue by Zerrisx** [magefree/mage#7050]
Cards that depend on how many types of cards are in the yard (Tarmogoyf, Nighthawk Scavenger) would benefit from a hint explaining what the current types across all graveyards are, so that you know if a new type you're going to add will cause them to grow or not without needing to check those graveyards.

**Comment by theelk801** [comment]
Not sure if there are others so I'll leave this open for now.

**Comment by Zerrisx** [comment]
The other cards that might benefit from such hints, per a scryfall search, are:

- [ ] Emrakul, the Promised End

- [ ] Happily Ever After

- [ ] Muldrotha, the Gravetide (though this one might be tricky)

And the Delirium Mechanic itself, which probably isn't worth it, but up to you.

**Comment by theelk801** [comment]
Delirium already has a hint but I could definitely update it.

**Comment by JayDi85** [comment]
Add types amount, not list only. Also sorting by name can be be good.

Example: 
* Types in graveyard: 3 (type1, type2, type3)
* Types in graveyard: 0

**Comment by theelk801** [comment]
Yeah I just updated it to sort but I can add the number too.

**Comment by theelk801** [comment]
I'm not gonna do the other ones right now, if anyone wants to then please be my guest

**Comment by Zerrisx** [comment]
Tarmogoyf, Emrakul, and delirium have a weird Optional[ ] included
![image](https://user-images.githubusercontent.com/59861365/93292241-b6b46c80-f7aa-11ea-9ccc-f8359d2683a6.png)

And Nighthawk Scavenger's hint doesn't seem to show up
![image](https://user-images.githubusercontent.com/59861365/93292276-d055b400-f7aa-11ea-9b15-4e61b6686158.png)

**Comment by Zerrisx** [comment]
I don't think Muldrotha needs one, so I'm closing this as fixed.
