### ISSUE TITLE
Treasure Nabber steals all mana rocks on each occassion.

### ISSUE THREAD

**Issue by luziferius** [magefree/mage#7058]
In the screenshot, the Treasure Nabber triggers 3 times for each artifact when the opponent played a land.
![treasure_nabber_xmage](https://user-images.githubusercontent.com/2143820/92622256-24512c00-f2c5-11ea-918b-9260a018e613.png)

[Game log](https://github.com/magefree/mage/files/5196384/20200909_164409_Commander.Free.For.All_1.txt)

The Nabber also triggered on Mana rock ETB, stealing the untapped artifact.

**Comment by LevelX2** [comment]
Fixed with 546e129.
