### ISSUE TITLE
Card Practised Tactics no creature on board kills Hagra Constrictor

### ISSUE THREAD

**Issue by adesst** [magefree/mage#7061]
Sets: ZNR
Game: Limited

- Player Human (myself),
  had Hagra ETB with 2 +1/+1 counters on
- attacking Computer

- Computer respond cast Practised Tactics
  target Hagra, while no creature on Computer's board

- Practised tactics resolved with 0 dmg and killed Hagra

**Comment by theelk801** [comment]
Did it say that it dealt 0 damage or did it deal more than 0?
