### ISSUE TITLE
Midnight Reaper triggers when dies face down

### ISSUE THREAD

**Issue by johnmeat** [magefree/mage#7063]
Ixidron has turned Midnight Reaper and Balduvian Bears face down:
![image](https://user-images.githubusercontent.com/64497504/92901426-617a0300-f418-11ea-8c03-e071243532b7.png)

Killing the face down Bear correctly doesn't trigger Midnight Reaper:
![image](https://user-images.githubusercontent.com/64497504/92901747-a1d98100-f418-11ea-82d5-a5c970276f85.png)
![image](https://user-images.githubusercontent.com/64497504/92901776-ad2cac80-f418-11ea-8b41-825ce269bcdf.png)

However bolting the face down Midnight Reaper triggers it's ability:
![image](https://user-images.githubusercontent.com/64497504/92902418-2af0b800-f419-11ea-9d8e-a8b17556f2a3.png)
![image](https://user-images.githubusercontent.com/64497504/92901988-d2b9b600-f418-11ea-8aa6-a8271854d9d6.png)

https://boardgames.stackexchange.com/questions/9592/do-face-down-creatures-with-death-trigger-activate-normally#:~:text=Short%20answer%3A%20Yes%2C%20if%20it,than%20afterward%20%5B603.3d%5D.

**Comment by jeffwadsworth** [comment]
#6214
