### ISSUE TITLE
QoL improvement: Don't ask to select card to discard from empty hand

### ISSUE THREAD

**Issue by Grath** [magefree/mage#7064]
I'm getting forced to discard once every turn in this Commander game, so my hand is always empty. It still prompts me to choose a card to discard when there is no card.

**Comment by theelk801** [comment]
What's forcing you to discard?

**Comment by Grath** [comment]
Liliana's Specter https://scryfall.com/card/pca/34/lilianas-specter being looped with Liliana, Defiant Necromancer's ult and a sac outlet.

**Comment by theelk801** [comment]
Thanks for pointing that out, should be better now
