### ISSUE TITLE
Grand Abolisher stops morphs from been able to be flipped over

### ISSUE THREAD

**Issue by johnmeat** [magefree/mage#7067]
Opponent had Grand Abolisher and was their turn, I couldn't flip a morph as this was stopped by Grand Abolisher, from my understanding this isn't an activated ability and what I can find online this isn't correct, if I am wrong please close (and forward any rulings on this please thanks?! )
![image](https://user-images.githubusercontent.com/64497504/93366334-e8791200-f842-11ea-9cdb-b24dd0d444b9.png)

https://gamefaqs.gamespot.com/boards/2000397-collectible-card-games-magic-the-gathering/72400626

https://gamefaqs.gamespot.com/boards/2000397-collectible-card-games-magic-the-gathering/71888266

https://www.reddit.com/r/magicTCG/comments/4v6cxi/a_morph_question/d5vvpcr/

**Comment by LevelX2** [comment]
Fixed by 75c4ff7d8ecf4fc40de5902425786fa1c276e30f.
