### ISSUE TITLE
Sen Triplets doesn't appear to allow playing cards from opponents' hands

### ISSUE THREAD

**Issue by Grath** [magefree/mage#7068]
I'm currently playing a Sen Triplets EDH deck, and while I can see my opponent's hand and get highlights on their cards as though I should be able to play them, I'm not actually able to play any of them. The highlights went away when I played my land for the turn (from my hand) or used up mana, but clicking on the cards in their hand didn't allow me to play them.

**Comment by Grath** [comment]
Friendly ping that this is still bugged, which is a major bummer because I really like my Sen Triplets EDH deck (and it's utterly impossible to play it over Zoom.)

**Comment by jeffwadsworth** [comment]
Tried a build for June 1, 2020 and it worked at that time.  It will take some time to locate the change that broke it.

**Comment by Grath** [comment]
Any progress on this? It would be nice if my deck actually functioned, since Sen Triplets (and playing my opponents' win conditions) is the core of the deck.
