### ISSUE TITLE
Confirmation for emptying mana pool at phase end

### ISSUE THREAD

**Issue by LevelX2** [magefree/mage#707]
http://www.slightlymagic.net/forum/posting.php?mode=quote&f=70&p=172628
I feel it misses a confirmation window if you wanna empty your mana pool, in case you have some, while attempting to skip phases. Sometimes I float a ton of mana, have a high storm count and accidentally skip my main phase, which empties it. I made it a lot of times and it's kinda frustrating.

**Comment by emerald000** [comment]
I think current MTGO behavior could be good. If you have floating mana, get priority even if you don't have a stop set for that phase. Then if you pass priority, have a pop-up to confirm you really want to do so.

That also prevents losing mana if you float it in a phase you don't have a stop set. If you get Wasted during the opponent's main phase (which you probably don't have a stop for), the normal action is to float mana in response to the Wasteland and pass priority. If the opponent passes priority after the Wasteland resolves, it won't automatically skip the phase and empty your pool but rather give you a chance to use your mana before losing it.
