### ISSUE TITLE
Gift of Doom destroyed by Horobi, Death's Wail when an aura

### ISSUE THREAD

**Issue by johnmeat** [magefree/mage#7073]
Target face down Gift of Doom with Kenrith's P1P1 counter ability so Horobi triggers:
![image](https://user-images.githubusercontent.com/64497504/93722091-37e57800-fb8c-11ea-9b04-6af86d86eb8d.png)

In response sacrifice the Bear to flip Gift of Doom (aura now on Kenrith):
![image](https://user-images.githubusercontent.com/64497504/93722112-5f3c4500-fb8c-11ea-8e6b-7feb5134bb5c.png)

When Horobi's trigger resolves Gift of Doom is still destroyed:
![image](https://user-images.githubusercontent.com/64497504/93722133-75e29c00-fb8c-11ea-86d4-7f7614a1575c.png)

**Comment by jeffwadsworth** [comment]
https://mtg.gamepedia.com/Resolving_spells_and_abilities

**Comment by LevelX2** [comment]
It seems to me according to rule 608.2j correct if Gift of Doom is still destroyed even after it ceases to be a creature.


> 608.2j If an ability’s effect refers to a specific untargeted object that has been previously referred to by that ability’s cost or trigger condition, it still affects that object even if the object has changed characteristics.
> 
> Example: Wall of Tears says “Whenever Wall of Tears blocks a creature, return that creature to its owner’s hand at end of combat.” If Wall of Tears blocks a creature, then that creature ceases to be a creature before the triggered ability resolves, the permanent will still be returned to its owner’s hand.
