### ISSUE TITLE
Light Up the Stage + Bonecrusher Giant

### ISSUE THREAD

**Issue by DominusMaximus** [magefree/mage#7074]
1.4.46.dev_2020-09-15_20-14

When my Bonecrusher Giant was exiled through Light Up the Stage, I was unable to cast it as an Adventure. I was only given the option to cast it as a creature.

**Comment by alanmarkdm** [comment]
This is not a bug.

Ruling on Gatherer:
If you cast an adventurer card as an Adventure, use only its alternative characteristics to determine whether it’s legal to cast that spell. **For example, if Giant Killer is exiled with the last ability of Vivien, Champion of the Wilds, you can’t cast it as Chop Down.**

**Comment by DominusMaximus** [comment]
That's because Vivien, Champion of the Wilds specifically mentions "...you may cast it **if it’s a creature spell**." Casting it as an adventure would mean casting it as a noncreature spell. 

The concept I'm referring to in my bug report also pertains to Escape to the Wild. When a card with an adventure is exiled through Escape to the Wilds, you may cast it as an adventure or creature. You can see this executed here at the 21:04 mark: 

https://youtu.be/YDPlZxsBeKI?t=1264

Brazen Borrower is exiled through Escape to the Wilds, and is soon cast as an adventure.

**Comment by weirddan455** [comment]
OP is correct.  Adventures should be castable off these cards (and indeed Escape to the Wilds was bugged too.)  PR #7154 should have this fixed.
