### ISSUE TITLE
Spellskite and multiple targets interaction

### ISSUE THREAD

**Issue by acabaca24** [magefree/mage#7078]
Sooo, I was playing modern with spellskite and my opponent had a Samut, the Tested -2 ability on the stack and I wondered if spellskite was working properly, cauz I couldn't see Samut targets on the stack.

**Forget about the fireball part, it was tested with the wrong AI**
**Care only about the Samut bug**

I jumped in an AI match and testet spellskite with fireball. This happenned:

1. I chose two targets for the fireball(human and computer):
![Screenshot from 2020-09-23 16-41-02](https://user-images.githubusercontent.com/61804801/94036766-92fdb180-fdbc-11ea-9e22-4843afcdcdc4.png)

2. Used Spellskite ability to change one target to itself:
![Screenshot from 2020-09-23 16-41-18](https://user-images.githubusercontent.com/61804801/94036953-c2acb980-fdbc-11ea-8cd3-f7a0cec1848e.png)

![Screenshot from 2020-09-23 16-41-21](https://user-images.githubusercontent.com/61804801/94037064-e243e200-fdbc-11ea-8716-fc3c0e2677e5.png)

3. Let fireball resolve:
![Screenshot from 2020-09-23 16-41-34](https://user-images.githubusercontent.com/61804801/94038021-e0c6e980-fdbd-11ea-9761-21bbb6e1e8fd.png)

This is the fireball error:

Game exception occurred: java.lang.NullPointerException
Server version: 1.4.45V1 (build: runtime)
mage.player.ai.ComputerPlayerMCTS.calculateActions(ComputerPlayerMCTS.java:98)
mage.player.ai.ComputerPlayerMCTS.getNextAction(ComputerPlayerMCTS.java:111)
mage.player.ai.ComputerPlayerMCTS.priority(ComputerPlayerMCTS.java:77)
mage.game.GameImpl.playPriority(GameImpl.java:1339)
mage.game.turn.Step.priority(Step.java:61)
mage.game.turn.Phase.playStep(Phase.java:184)
mage.game.turn.Phase.play(Phase.java:89)
mage.game.turn.Turn.play(Turn.java:126)
mage.game.GameImpl.playTurn(GameImpl.java:879)
mage.game.GameImpl.play(GameImpl.java:791)
mage.game.GameImpl.start(GameImpl.java:776)
mage.server.game.GameWorker.call(GameWorker.java:34)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)

**Samut bug starts here**

After it, I tested with Samut and if there is only one target chosen, the ability fizzles.
![image](https://user-images.githubusercontent.com/61804801/94037469-4bc3f080-fdbd-11ea-8056-89192545023f.png)
![image](https://user-images.githubusercontent.com/61804801/94037492-51b9d180-fdbd-11ea-9ec9-73f45fc66a4c.png)
![image](https://user-images.githubusercontent.com/61804801/94037506-55e5ef00-fdbd-11ea-9162-e68aedd3aaa3.png)

**Samut worked fine with 2 targets and then changing them**

Feel free to ask questions, I'll test and answer them asap!

**Comment by jeffwadsworth** [comment]
It appears you are using the Monte Carlo AI.  Use the regular AI for this test.

**Comment by acabaca24** [comment]
I didn't even notice that! Thank you for mentioning! Tested it with fireball and it looks fine! Still have the issue with Samut tho.
I'm going to edit the post to emphasize on the Samut bug and say Fireball was a my problem.

By the way, what's the difference between the AIs?

**Comment by jeffwadsworth** [comment]
The default AI works well, while the Monte Carlo barely works at all.

**Comment by LevelX2** [comment]
I was not able to reproduce any problem with Samut -1 ability.
