### ISSUE TITLE
Cavers of Souls and lands that require choosing when they enter give excessive messages in game log

### ISSUE THREAD

**Issue by Beroestheenvoy** [magefree/mage#7079]
When Cavers of Souls or other lands that require choosing when they enter (some creature type for example) give multiple messages that they produced something (it's a box in client) when they controler takes arbitrary actions, even when those actions don't include any of those lands. This has no influece on the game and they work properly, they just gice that spammming message in game log.

**Comment by jeffwadsworth** [comment]
A picture is worth a thousand words.  Please take one and post it here for reference.

**Comment by Fubs** [comment]
Here's a screenshot of the bug.

![cavernbugscreenshot](https://user-images.githubusercontent.com/17634481/94467191-2ef63700-0188-11eb-9aef-95da84e4ba4a.png)

**Comment by alanchengg** [comment]
This bug is also present with Unclaimed Territory.

**Comment by weirddan455** [comment]
Fixed in https://github.com/magefree/mage/commit/98235ba57fcda84e600e2f70a5ac90c6a16aa343
