### ISSUE TITLE
Valakut Exploration not working as expected

### ISSUE THREAD

**Issue by Scapegoat-Tom** [magefree/mage#7080]
Cards exiled with Valakut Exploration are not moving into the graveyard at the beginning of the end step and damage is not being assigned to opponents.

**Comment by Zerrisx** [comment]
Pretty sure this was fixed by aa08d22

**Comment by Alex-Vasile** [comment]
Can confirm this works correctly now. Can someone please close this.

**Comment by Zerrisx** [comment]
Done.
