### ISSUE TITLE
Scion of the Ur-Dragon + Utvara Hellkite = Double trigger bug

### ISSUE THREAD

**Issue by eduardosteps** [magefree/mage#7083]
When Scion of the Ur-Dragon is transformed into Utvara Hellkite, it should create ONE single token during the attack, but xmage thinks there are two dragons attacking and creates **TWO tokens**.

![image](https://user-images.githubusercontent.com/56098141/94311080-0801f000-ff51-11ea-8947-9ecc996bf623.png) ![image](https://user-images.githubusercontent.com/56098141/94311106-0e906780-ff51-11ea-8974-28b03e8603eb.png)

Here is the bug explained step-by-step: https://youtu.be/pO2DWU4QJzI

**Comment by theelk801** [comment]
I can't recreate this, are you sure there wasn't anything else going on?

**Comment by eduardosteps** [comment]
Yeah 100% sure. 
Take a look at this video that I've made to reproduce the bug.
https://youtu.be/pO2DWU4QJzI

**Comment by theelk801** [comment]
Ok, so it looks like it only happens when you attack with all, not sure why though. I'll look into it.

**Comment by eduardosteps** [comment]
> Ok, so it looks like it only happens when you attack with all, not sure why though. I'll look into it.

Even if you click on the creature to attack alone, sometimes it creates two, three or even four tokens. It's a random number. I have no idea what is going on, but it should create only one token, because it's Scion transformed into Utvara. Only one creature after using his ability. Please make this bug report to reach the entire dev community. Thanks a lot.

**Comment by eduardosteps** [comment]
Could you guys please tell me when this bug fix is gonna be on the official release and working on xmage? So I can test it and post the thanks results here. =)
