### ISSUE TITLE
OSX - Can't play (i don't know what i'm doing wrong)

### ISSUE THREAD

**Issue by voy3voda** [magefree/mage#709]
So i followed the steps in the *5 steps guide* and then when i launched *startClient.command* this message appears:
![screen shot 2015-02-08 at 3 09 06 pm](https://cloud.githubusercontent.com/assets/4458830/6098445/9cae2c12-afa4-11e4-8849-7f39209b5b99.png)

SPECS:
OS: MAC OS X Yosemite 10.10.2
![screen shot 2015-02-08 at 3 12 38 pm](https://cloud.githubusercontent.com/assets/4458830/6098482/a9338e04-afa5-11e4-8aad-3e83038016a2.png)

**Comment by PeteV** [comment]
are you trying to just connect the client to an existing server? If so you do click on find it will list several ones that will show up for you to choose from and join. Hope this helps.

**Comment by jeffwadsworth** [comment]
The server must be started before the client can attempt to connect to it.

Sent from my iPad

On Feb 8, 2015, at 3:13 PM, "J. Treviño" <notifications@github.com<mailto:notifications@github.com>> wrote:


So i followed the steps in the 5 steps guide and then when i launched startClient.command this message appears:
[screen shot 2015-02-08 at 3 09 06 pm]<https://cloud.githubusercontent.com/assets/4458830/6098445/9cae2c12-afa4-11e4-8849-7f39209b5b99.png>

And when i try startServer.command terminal get stuck in here:
[screen shot 2015-02-08 at 3 01 00 pm]<https://cloud.githubusercontent.com/assets/4458830/6098448/b89c75d2-afa4-11e4-8f84-f21d7ec6a116.png>

SPECS:
OS: MAC OS X Yosemite 10.10.2
[screen shot 2015-02-08 at 3 12 38 pm]<https://cloud.githubusercontent.com/assets/4458830/6098454/f54d3728-afa4-11e4-897b-4edbe7eb9837.png>

**Comment by PeteV** [comment]
Like Jeff says a client needs to connect to a server, localhost is your computer and will only work if your server is locally running. cheers

**Comment by voy3voda** [comment]
This means that is running, right?

**Comment by jeffwadsworth** [comment]
It is listening, so it appears to be okay.  I do not use Mac's, though.

________________________________

**Comment by LevelX2** [comment]
> This means that is running, right?

This only means that a webserver is listening on port 80. This has nothing to do with the XMage server.
You have to start it successful before you can connect with a clinet.

Did you use the XMage launcher (http://xmage.info)to install and start XMage. It's normally easier than to do all steps manually (as you did). There you have simple buttons to start client and server.

Could you connect to a public server (use the find button to select one)?

**Comment by voy3voda** [comment]
I did what you said; i used only the launcher without the manual steps and it worked. Thanks!
