### ISSUE TITLE
Unsettled Mariner Double Triggers

### ISSUE THREAD

**Issue by Themagicman16** [magefree/mage#7094]
Unsettled Mariner's ability triggers twice when something is targeted. This happens when both players or permanents are targeted.

![Double Mariner](https://user-images.githubusercontent.com/38578380/94639087-69a3c080-02a9-11eb-8de9-8b3788765984.png)

**Comment by goesta** [comment]
I was not able to reproduce this on the master.

**Comment by Themagicman16** [comment]
Strange, I was just able to do it again. I'm using the most recent version, I'll force an update and see if that fixes it.
