### ISSUE TITLE
Luncher error Invalid config on MacOs Catalina

### ISSUE THREAD

**Issue by Jakub41** [magefree/mage#7102]
Hello,

Recently I'm unable to start Xmage version 0.3.8 

what I see when I start the launcher is as follow  

```
Reading config from http://xmage.de/xmage/config.json
Invalid config from http://xmage.de/xmage/config.json
```

A few days ago was still working but now not anymore and I would like to know a possible solution to the problem.

My OS
Catalina 10.15.6

Please help me with the steps to resolve this :)

Thank you

**Comment by JayDi85** [comment]
Check your internet connection. Also try to disable firewall/antimalware. You must able to open config link in any browser to see json data: http://xmage.de/xmage/config.json

Example:
![shot_201002_185257](https://user-images.githubusercontent.com/8344157/94937510-b8876b00-04e0-11eb-9330-71d84f0760ce.png)
