### ISSUE TITLE
[ELD] 'Charming Prince' Bug 

### ISSUE THREAD

**Issue by Clipper70** [magefree/mage#7108]
Charming prince won't allow me to target a creature I own but don't control.  Perhaps it's coded to "exile target creature you control" instead of what it's supposed to be "Exile target creature you OWN"?  No coding experience so IDK, sorry I can't be of more help.

**Comment by weirddan455** [comment]
Not able to reproduce this one.  I started a test game (using 2 clients so I could control both players), cast Grizzly Bears as player 1, stole it with Entrancing Melody as player 2, then cast Charming Prince as player 1 and was able to target Grizzly Bears, blinking it out and returning it to player 1's control at end step as expected.

**Comment by awjackson** [comment]
I can't reproduce this either. Tested using [[Switcheroo]] to exchange control of two creatures with opponent. Charming Prince's third mode correctly *could* target the creature I owned but did not control, and *could not* target the creature I controlled but did not own.
