### ISSUE TITLE
[STH] Burgeoning should only trigger for played lands.

### ISSUE THREAD

**Issue by propri** [magefree/mage#7109]
Ruling for Burgeoning from Gatherer:

> Playing a land will trigger it, but putting a land onto the battlefield as part of an effect will not.

Burgeoning triggered from a land put into play due to Path to Exile.

**Comment by propri** [comment]
Upload to github did not work, here is a screenshot:

https://i.imgur.com/9FEfo2x.png

**Comment by Alex-Vasile** [comment]
[[Burgeoning]]

**Comment by awjackson** [comment]
I can't reproduce this, and the card is correctly programmed to trigger on `EventType.LAND_PLAYED` (it's using an unneccessary custom ability class, but at least it's checking the correct event type).
