### ISSUE TITLE
Treasure Nabber gets control just by casting the artifact

### ISSUE THREAD

**Issue by propri** [magefree/mage#7114]
https://i.imgur.com/sJPWOD8.png

A Treasure Nabber is on the battlefield under control of an opponent. I cast a Rakdos Signet, and as soon as it resolves, the Treasure Nabber causes my opponent to gain control of it. It was not tapped for mana.

Then, when my turn comes again, and I should get control of the Signet back, Treasure Nabber immediately triggers again.

https://i.imgur.com/hOztRz8.png

**Comment by theelk801** [comment]
fixed with 546e129
