### ISSUE TITLE
Sundial of the Infinite and Gesit of Saint Traft

### ISSUE THREAD

**Issue by ETALOS1** [magefree/mage#7119]
Sundial of Infinite should, I believe, allow the 4/4 Angel created by Saint Traft's attack to stay on the field until it is removed by, well, anything other than Saint Traft's ability.

Currently in XMage, however, a "Sundialed" Traft Angel only stays until the end of an opponent's combat. Then it disappears, presumably due to XMage enacting Traft's effect at the end of an opponent's combat. This does not appear to be the intended effect per the card nor most rulings and discussions surrounding the interaction. 

Thank you.

**Comment by emerald000** [comment]
If you activate Sundial of the Infinite in response to the "Angel gets exiled" trigger, it should not trigger anymore and you'll get to keep the angel.

If you activate Sundial of the Infinite before the "Angel gets exiled" trigger is put on the stack (probably in the combat damage step), it will trigger at the next relevant time (probably in your opponent end of combat step).

In short, the "Angel gets exiled" delayed trigger should trigger exactly once. If that one trigger fails to resolve, you get to keep the angel.

Can you confirm you activated the Sundial with the delayed trigger on the stack? Thanks!

**Comment by ETALOS1** [comment]
I could have sworn I tried it both ways just to make sure, but I will check again tonight and provide an update. Thank you!

**Comment by Alex-Vasile** [comment]
[[Sundial of the Infinite]] and [[Gesit of Saint Traft]]
