### ISSUE TITLE
Price of Glory triggering incorrectly

### ISSUE THREAD

**Issue by johnmeat** [magefree/mage#7120]
Some lands and Price of Glory in play only:
![image](https://user-images.githubusercontent.com/64497504/95510144-61383d80-09ad-11eb-82cf-95587865120d.png)

On the AIs upkeep Price of Glory triggers for no reason:
![image](https://user-images.githubusercontent.com/64497504/95510211-7ca34880-09ad-11eb-8bdc-77023986011e.png)

Seemingly more triggers go off as the triggers are resolved:
![image](https://user-images.githubusercontent.com/64497504/95510405-c0964d80-09ad-11eb-833f-61037ef5e048.png)

**Comment by theelk801** [comment]
fixed with 7a78be8
