### ISSUE TITLE
Randomly not getting back in to sideboarded games

### ISSUE THREAD

**Issue by dylan1020** [magefree/mage#713]
I have been having a bug that I am unable to get into sideboarded games. It seems to have no rhyme or reason as to replicating it. It seems to also only effect me as nobody has ever had it happen to them. I wish I could give you guys more help tracking it down.

**Comment by LevelX2** [comment]
1) That means you see your sideboard and change something or not.
2) You submit the deck.
3) You see the main lobby.
4) You never get into the next game of the match.

Some questions:
How often does it happen?
The games opens for your opponent?
The game is not in the Window Items to the top right?
Which OS do you use?

**Comment by dylan1020** [comment]
Correct.

It happens with some regularity. It seems it happens more after the first one happens in a night.

The games do open for my opponent. The game shows up as "dueling", but I do not get back into it.

That is correct. They do not appear in the top right.

This only seems to happen on Windows. I don't play as often on Linux so it may happen on Linux as well.

**Comment by fireshoes** [comment]
I saw someone else mention this in the main lobby chat today.

23:07: Kusir has joined
23:07: Mikeee: game didn't take me to sidboarding?
23:07: TheFailsafe has joined

**Comment by dylan1020** [comment]
That is the first time I've heard of it happening to anyone else.

**Comment by LevelX2** [comment]
Seems to be no longer a problem.
