### ISSUE TITLE
Omniscience doesn't let you cast Adventures from your hand for free

### ISSUE THREAD

**Issue by Zerrisx** [magefree/mage#7130]
With Omniscience in play and a Fae of Wishes in hand, you are asked if you want to cast it for free.

- "Yes" casts Fae as a creature for free
- "No" asks you to pay 1U

There's no way to choose the adventure half.

**Comment by acabaca24** [comment]
This was already reported in #7040

**Comment by JayDi85** [comment]
Fixed by #7152
