### ISSUE TITLE
Omnath, Locus of Rage bugs

### ISSUE THREAD

**Issue by Sharkovichus** [magefree/mage#7133]
Hello, we found a few bugs with Omnath, Locus of Rage:
1. When Omnath, Locus of Rage dies, put his ability to stack targeting creature. Opponent cast instant which give protection from color (green or red) to that creature. Ability of Omnath, Locus of Rage resolves normally, and deal 3 damage to that creature.
2. When I control Omnath, Locus of Rage and opponent controls Whip of Erebos, triggered ability of Omnath, Locus of Rage (3 damage) has lifelink too, when ability resolves Omnath, Locus of Rage deals 3 damage to target creature or player and I get 3 life.

Thank you for this project!

**Comment by LotusWalker** [comment]
Your opponent’s Whip of Erebos would only give his own creatures lifelink though.

**Comment by theelk801** [comment]
I can't recreate the first one and I added a test to confirm it. Let me know if it happens again. I also fixed Whip of Erebos.

**Comment by Sharkovichus** [comment]
Hello!
There are screenshots of color protection problem:
![1](https://user-images.githubusercontent.com/38747091/96163510-6b20ea00-0f33-11eb-9edc-264d4c070466.png)
![2](https://user-images.githubusercontent.com/38747091/96163549-74aa5200-0f33-11eb-889b-9c11838cee3a.png)
![3](https://user-images.githubusercontent.com/38747091/96163556-783dd900-0f33-11eb-8342-07a4de775b0b.png)
![4](https://user-images.githubusercontent.com/38747091/96163568-7c69f680-0f33-11eb-9375-4b1048a53b7d.png)

**Comment by theelk801** [comment]
That's really weird, I can't recreate this at all.
