### ISSUE TITLE
Firesong and Sunspeaker's ability isnt being fully suppressed.

### ISSUE THREAD

**Issue by majlagspike** [magefree/mage#7137]
Have done a search and the only reference to this issue is marked as resolved.

When you attach an effect onto [Firesong and Sunspeaker](https://scryfall.com/card/pz2/68076/firesong-and-sunspeaker) that suppresses its abilitys, such as [Lignify](https://scryfall.com/card/gvl/16/lignify), it still triggers on board wide affects like [Star of Extinction](https://scryfall.com/card/xln/161/star-of-extinction). Ssingle target spells seem unaffected.

PvP game.

**Comment by theelk801** [comment]
Are you saying that it still gives lifelink and the ability still triggers on the life gain?

**Comment by majlagspike** [comment]
That is correct

**Comment by majlagspike** [comment]
> 
> 
> Are you saying that it still gives lifelink and the ability still triggers on the life gain?

That is correct

**Comment by weirddan455** [comment]
I am able to reproduce the bug (using the latest source from git master branch) but it's a little different than how you described it.  Functionality of the card without Lignify on it works as expected.  When I put Lignify on the creature:

Lightning Bolt gains life.
Star of Extinction gains life.
Revitalize no longer triggers the deal 3.

So I'm seeing that the first ability incorrectly keeps happening when it shouldn't (regardless of single target or AoE) and the 2nd ability is correctly muted.  I'm digging into the code now for a fix.
