### ISSUE TITLE
Newest Update Not Updating

### ISSUE THREAD

**Issue by TheRealistPT** [magefree/mage#7139]
Hi,
I am having trouble getting the newest version to update on Xmage. I have tried force updating through the launcher. That did not work. I have tried deleting the files al together and reinstalling. That did not work. I am very frustrated because I have not been able to play Zendikar Rising. I am from New Jersey does that have something to do with it? Is the update not available yet in the Northeast? I still have the August 29th patch. Thank you. my email is henri2861@yahoo.com if you would like to email me instead. Regards,
Pat Trainor

**Comment by thedocdoctor** [comment]
wtf

**Comment by JayDi85** [comment]
@TheRealistPT try beta version [from here](http://xmage.today/) (it have your set).

**Comment by TheRealistPT** [comment]
> @TheRealistPT try beta version [from here](http://xmage.today/) (it have your set).

Hey man! Thank you but I tried that and its still givingme the version from August 29th
