### ISSUE TITLE
Valakut Exploration 

### ISSUE THREAD

**Issue by catman123456** [magefree/mage#7143]
Valakut Exploration is not putting the cards in the graveyard and doing the damage.

**Comment by weirddan455** [comment]
I'm not able to reproduce this.  Can you post a screenshot or log output of an example where it's not working correctly?  For me, it appears to be working on the latest beta version:

1:15 PM, T11.M1: Ability triggers: Valakut Exploration [271] - Landfall — Whenever a land enters the battlefield under your control, exile the top card of your library. You may play that card for as long as it remains exiled.
1:15 PM, T11.M1: Human moves Mountain [309] from library to the exile zone
1:15 PM, T11.DA: Human attacks with 0 creatures
1:15 PM, T11.ET: Ability triggers: Valakut Exploration [271] - At the beginning of your end step, if there are cards exiled with Valakut Exploration [271], put them into their owner's graveyard, then Valakut Exploration [271] deals that much damage to each opponent.
1:16 PM, T11.ET: Human puts Mountain [309] from exile zone into their graveyard
1:16 PM, T11.ET: Computer loses 1 life

**Comment by catman123456** [comment]
It got fixed in the update
