### ISSUE TITLE
Morphs seem to be visible on the stack momentarily

### ISSUE THREAD

**Issue by JohnPetfield** [magefree/mage#7145]
A player today told me they saw what my morph was whilst it was on the stack. This is the second game where this has happened. I would say both games have been where pretty laggy with one player having a fairly poor ping.

![image](https://user-images.githubusercontent.com/64497504/97086113-56baac80-1619-11eb-8b14-374f40c0725e.png)

**Comment by NekoNL** [comment]
i have noticed this as well in some games which were laggy

**Comment by Alex-Vasile** [comment]
There is a similar issue (github issue) opened for the fact that cards are visible before their mana has been paid. I think the two could be solved in a similar way

**Comment by JayDi85** [comment]
Fixed after morph rework in #11178
