### ISSUE TITLE
Initial install is stalled

### ISSUE THREAD

**Issue by ChukCG81** [magefree/mage#716]
I keep trying to install on my laptop and will not complete. Ive rebooted, uninstalled all java then reinstalled, still nothing, what else can I do? I run Windows 7
![xmage](https://cloud.githubusercontent.com/assets/10986788/6181702/012fbf1c-b305-11e4-91d9-16d449ca984d.jpg)

**Comment by LevelX2** [comment]
Did you solve your problems or are they still present?

**Comment by ChukCG81** [comment]
they are still present, i cannot get the install to work

**Comment by LevelX2** [comment]
And the install process hangs always while downloading the java file like shown on your screen shot?

One alternate could be to install Xmage without the launcher.
1) Install newest java 8 version.
2) Downlaod the XMage zip and unzip it.
3) Call the client start bat file to start the client.

**Comment by ChukCG81** [comment]
where can I find the zip file out?

**Comment by LevelX2** [comment]
http://www.slightlymagic.net/forum/viewtopic.php?f=70&t=16905&p=175032#p175032

**Comment by markedagain** [comment]
@ChukCG81 closing ticket for now, if u still have issues please simply reopen ticket, thank you!
