### ISSUE TITLE
Missing cards

### ISSUE THREAD

**Issue by catman123456** [magefree/mage#7164]
Lithoform Engine and Verazol, the Split Current is not in the beta of xmage
<img width="1920" alt="Untitled" src="https://user-images.githubusercontent.com/64045003/97999421-4775f480-1db9-11eb-866e-0ec8c87d7cd7.png">

**Comment by jeffwadsworth** [comment]
It may have been added by mistake.  A work-in-progress issue perhaps.  Checking it out.

https://github.com/magefree/mage/commit/7647a3d8f0ae0b6c555c345a3d89aa041e76a796

**Comment by theelk801** [comment]
Permanent spell copies aren't completely implemented yet, I think @JayDi85 removed them until he has them working.
