### ISSUE TITLE
Hive Mind + Chalice of the Void

### ISSUE THREAD

**Issue by xtekirux** [magefree/mage#717]
This actually cost me a game.

The Amulet Bloom deck in Modern has a few wincons, one of them being that the Bloom player resolves a Hive Mind, then casts a Pact. The Hive Mind copies it so the opponent also casts a Pact. 

If the opposing player has a Chalice set on ZERO, it will counter both copies which it should NOT DO because Hive Mind puts a copy onto the stack, not 'cast'. So while the Bloom player's copy is countered, the opponent will still cast and have to pay during their upkeep. 

Please fix this. :( I'm now scared to play the deck since this bug stops an issue that originally shouldnt happen.

**Comment by ImperatorPrime** [comment]
Fixed by ac1b4ab7b954bd82b1e441aee5e9c5ae1ed32d41

**Comment by LevelX2** [comment]
Hive Mind did now work for countered spells but no longer for not countered spells. :-)
Fixed that and added some tests.

**Comment by ImperatorPrime** [comment]
Whoops, thanks.

**Comment by xtekirux** [comment]
Thanks you guys! Now I feel comfortable playing Hive Mind again. It's a
super tilt when you know you won the game but the system doesnt. :)
