### ISSUE TITLE
ZNR DFMC [Glasspool Mimic] interaction with Aether Vial

### ISSUE THREAD

**Issue by Clipper70** [magefree/mage#7174]
Tried to vial in Glasspool Mimic and it gave me this error:
<img width="1789" alt="Screen Shot 2020-11-07 at 11 52 41 pm" src="https://user-images.githubusercontent.com/29809519/98441816-d2a61000-2154-11eb-8104-63962964e625.png">

**Comment by JayDi85** [comment]
Fixed by cff67085b7045d2dba5dd66fe914dad0f0a908ee
