### ISSUE TITLE
Kazandu Mammoth // Kazandu Valley Triggering as Land

### ISSUE THREAD

**Issue by THUNDERWANG** [magefree/mage#7180]
When played as a land, subsequent lands will trigger the landfall ability twice. It shouldn't even be triggering.
![bug](https://user-images.githubusercontent.com/59207918/98773642-32432c00-239e-11eb-93d0-1a2d7b31f236.PNG)

**Comment by JayDi85** [comment]
Fixed by 656653f38b0deb6e2796ba318443ad240f4d9cfa
