### ISSUE TITLE
Riverglide Pathway / Lavaglide Pathway is not working as intended

### ISSUE THREAD

**Issue by dihimono** [magefree/mage#7188]
Just found out in game that no matter which side I played it always produces red mana.

https://github.com/magefree/mage/blob/2109f60e4d76506e5148be0764ce8912498ee31d/Mage.Sets/src/mage/cards/r/RiverglidePathway.java#L28

I think this is the root cause.

**Comment by JayDi85** [comment]
Fixed by 35b6239e924b54dc758a7c0b13fb475784b76bb3
