### ISSUE TITLE
Can't download java: java.com isn't working anymore

### ISSUE THREAD

**Issue by copperfield42** [magefree/mage#7189]
I needed to re-start with my computer and when come around to re-install java to play in xmage again I come across this

![image](https://user-images.githubusercontent.com/4504719/99321298-e3850e80-2843-11eb-924e-e9952f2d10ab.png)

And it looks like its been like that for some time now even before I needed it, and it have been a month now since I first came across it...

long story short I end using java from https://jdk.java.net/ (first link from reddit r/java) but that isn't like the old installation and can only be used from console, that or there is some way to make it like the old one that isn't immediately apparent that I'm unaware off, regardless because I'm programming savvy I can manage with some .vbs scripts to execute the .jar launcher, and the rest is the usual.

But as the average user can't be expected to be programming savvy, I think that an update to the installation guide is necessary

**Comment by JayDi85** [comment]
Oracle's website works fine. It redirects to page: https://java.com/en/download/

![shot_201117_044921](https://user-images.githubusercontent.com/8344157/99325679-456b6580-2890-11eb-8cb5-440d0fa17ed0.png)

**Comment by copperfield42** [comment]
not for me
![image](https://user-images.githubusercontent.com/4504719/99326083-f69cdc00-284d-11eb-99e8-2e6b05fc5e88.png)

maybe is some sort of region lock?

**Comment by JayDi85** [comment]
That page tries to find out your OS version -- maybe browser's user agent is wrong or something else. So it can't find your OS and shows the error.

**Comment by copperfield42** [comment]
the one I usually use is Chrome
but is the same with Edge
![image](https://user-images.githubusercontent.com/4504719/99326796-f0f3c600-284e-11eb-8f92-9b4e6beb4a2d.png)

**Comment by JayDi85** [comment]
Other users have [same problems](https://forum.minimserver.com/showthread.php?tid=4422&pid=38509#pid38509). Possible fixes:
1. Use another DNS server in your network/router configs (google's DNS: `8.8.8.8`);
2. Use VPN/Proxy from another country.

**Comment by copperfield42** [comment]
I already use google dns.
I just test it with the requests module in python and I get 403, so yeah, block by something I guess...

And about VPN/Proxy, any recommendation for those?

**Comment by JayDi85** [comment]
You can use any free proxy from google search -- it's a one time download. If you have problem with that then report your os version (windows/linux/mac and 32/64) - I can upload installer to another hosting.

**Comment by copperfield42** [comment]
done, I could download it.
