### ISSUE TITLE
Sen Triplets is the last ARB card to be implemented, please do it? <3

### ISSUE THREAD

**Issue by Zorkony** [magefree/mage#719]
Alara Reborn is 99.31% finished, with Sen Triplets being the last unfinished card. I know a lot of people who would like to play her, and her implementation seems not that hard:

It's basically a beginningofupkeepriggeredability with an effect until end of turn that makes target opponent play with his hand revealed and you can play his cards while he can't, which, to me, seems like a combination of effects used already in cards like Telepathy, Act On Impulse and Grand Abolisher.

I (and undoubtedly a lot of other players) would REALLY appreciate it if someone could take some time to implement this awesome card. I don't really know Java syntax or the way XMage is built up, or I would do it myself :(

Thank you so much in advance!

**Comment by jeffwadsworth** [comment]
Of course we all love the Sen Triplets, but its implementation is not trivial.

Sent from my iPad

On Feb 15, 2015, at 8:07 AM, "Zorkony" <notifications@github.com<mailto:notifications@github.com>> wrote:


Alara Reborn is 99.31% finished, with Sen Triplets being the last unfinished card. I know a lot of people who would like to play her, and her implementation seems not that hard:

It's basically a beginningofupkeepriggeredability with an effect until end of turn that makes target opponent play with his hand revealed and you can play his cards while he can't, which, to me, seems like a combination of effects used already in cards like Telepathy, Act On Impulse and Grand Abolisher.

I (and undoubtedly a lot of other players) would REALLY appreciate it if someone could take some time to implement this awesome card. I don't really know Java syntax or the way XMage is built up, or I would do it myself :(

Thank you so much in advance!

**Comment by Zorkony** [comment]
I figured it wasn't that easy, because otherwise it would've been implemented long ago. Which part of the effect makes it so complicated, though? To me, it seems the effects 'Opponent(s) can't play cards in your turn', 'Opponent(s) play with hand revealed', and 'Play-cards-not-in-hand' have all been used in some way?

**Comment by Kaidyr** [comment]
Yes, please implement this card. Is there a way to know whether something like this is being actively considered/worked on?

**Comment by jeffwadsworth** [comment]
The only real issue is coding up the viewing of the target opponents hand so that the controller can play them.  To my knowledge, no one is working on it.

**Comment by Zorkony** [comment]
I myself am a programmer (though not in Java, and currently I don't have enough time to spend on learning it and the XMage-syntax) so I'm trying to pseudo-think a way to implement it, hoping that someone can work off of my ideas and translate it into working code :)

I feel like all of Sen Triplet's effects have already been implemented in some way, just not the combination of all of them in one card.

- Silence has been implemented, which stops opponents from playing spells this turn, can you narrow that effect to one opponent?

- Telepathy is already implemented, and that shows your opponent's hands permanently. Maybe it's possible to make that effect temporary (one turn) for one opponent? 

Now for the hard part, playing cards from their revealed hand. As far as I can find, there are already a couple of effects that allow you to play cards that are not in your hand.
- Nightveil Spectre and Act on Impulse let you play cards from exile
- Yawgmoth's Agenda and Yawgmoth's Will let you play cards from your graveyard
- Magus of the Future lets you play the top card of your library
- Bribery even lets you put a card from an opponent's library under your control

Isn't it possible to change any of these effects to play cards from opponent's hands? 
I'm just trying to think out loud :) Thanks for your time and effort!

**Comment by Kaidyr** [comment]
A friend and I were thinking the exact same things Zorkony. 

We are potentially interested in giving it a shot ourselves, but we are tied up for at least a month and a half.

**Comment by LevelX2** [comment]
Sun Triplets is implemented now. So I close this.
