### ISSUE TITLE
Gilanra, Caller of Wirewood ocasionaly draws you two cards

### ISSUE THREAD

**Issue by mwuaha** [magefree/mage#7191]
On the current version of beta Gilanra ocasionaly draws you two cards instead of one. I coulnd't figure out if it is random or there is a specific set of circumstances that causes it.
[20201116_233245_Commander Free For All_2.txt](https://github.com/magefree/mage/files/5560122/20201116_233245_Commander.Free.For.All_2.txt)

**Comment by JayDi85** [comment]
Steps to reproduce:
* turn 1: activate mana ability, but don't use;
* turn 3: activate mana ability and use -- two triggers raise.

**Comment by JayDi85** [comment]
Fixed by aeb2d31d47de7cef51a41f2d5647c494f8334e7c
