### ISSUE TITLE
MDFC can't be played from the top with i.e. Radha as intended

### ISSUE THREAD

**Issue by Denovar123** [magefree/mage#7200]
Hi guys,

I tried out the new modal double faced cards in a commander deck and noticed, that I couldn't play the land parts from anywhere other than my hand. In the release notes it is explained:

"If an effect allows you to play a land or cast a spell from among a group of cards, you may play or cast a modal double-faced card with any face that fits the criteria of that effect. For example, if Sejiri Shelter / Sejiri Glacier is in your graveyard and an effect allows you to play lands from your graveyard, you could play Sejiri Glacier. That effect doesn't allow you to cast Sejiri Shelter."

(https://magic.wizards.com/en/articles/archive/feature/zendikar-rising-release-notes-2020-09-10)

Therefore I could just play a land side mdfc from the top if I would have Radha, Heart of Keld or from the graveyard if I would have Crucible of Worlds. I tested both interactions and they don't work. I would be glad if you could fix this, because I want to use a deck in a xmage tournament, which uses those interactions. :D
Thanks in advance, you guys are doing a great job!!

Denovar

**Comment by JayDi85** [comment]
Fixed by c1e7a08c6855424eb4c2fb5c46a70963f61df9c3
