### ISSUE TITLE
Negan, The Cold Blooded Sacrifice effect triggering on own creatures being sacrificed, not opponents.

### ISSUE THREAD

**Issue by jholstein** [magefree/mage#7207]
Happened with some friends a bit ago, played dockside extortionist, and then sacrificed it with phyrexian tower. The trigger went off and I got a treasure. On both battlefield entries this game so far, there have been no triggers despite the first part of his text going off. There was a Rayami and a Mimic vat on the field that also interacted with death.

**Comment by jholstein** [comment]
Source of the issue seems to be this snippet.

> this.addAbility(new SacrificeAllTriggeredAbility(
                new CreateTokenEffect(new TreasureToken()),
                StaticFilters.FILTER_PERMANENT_A_CREATURE,
                TargetController.OPPONENT, false
        ));

**Comment by JayDi85** [comment]
Fixed by 513609b12a9c797de75ee7426ac24b126cecb79b
