### ISSUE TITLE
Riverglide Pathway // Lavaglide Pathway only giving red mana

### ISSUE THREAD

**Issue by acabaca24** [magefree/mage#7208]
In game, Riverglide Pathway // Lavaglide Pathway, gives the option to choose, but Riverglide Pathway is giving red mana, instead of blue.

 Riverglide Pathway :
![image](https://user-images.githubusercontent.com/61804801/100430834-3904bb00-308f-11eb-9cca-c590bffa4c68.png)

 Lavaglide Pathway :
![image](https://user-images.githubusercontent.com/61804801/100430880-44f07d00-308f-11eb-9eb2-c730469c8ff7.png)

Also, but a bit unrelated, When you play a pathway it gives you 3 choices, two of the front one and one of the back. Don't know if this issue happens with other modal faced cards.

**Comment by JayDi85** [comment]
Double lands fixed in related #7197 and will be available with next release.

**Comment by acabaca24** [comment]
Thank you for the quick reply!
