### ISSUE TITLE
[CMR] Akroma, Vision of Ixidor

### ISSUE THREAD

**Issue by catman123456** [magefree/mage#7209]
Akroma, Vision of Ixidor is not adding any +1 counter to my creatures
<img width="1920" alt="Untitled" src="https://user-images.githubusercontent.com/64045003/100498817-d238dd80-3132-11eb-8032-2906564acafc.png">

**Comment by JayDi85** [comment]
Fixed by 64821a50d3f63f8e68d50a60a6399daf24072f6e
