### ISSUE TITLE
XMage server flight recording -  analysis garbage collection and other issues

### ISSUE THREAD

**Issue by LevelX2** [magefree/mage#721]
This issue can be used to discuss XMage server profile data (jfr files). It's a sequel issue of #662

To open the files you can use the jmc.exe (Java Mission Control), that is included in the JDK.

Objectives are:
1) To improve GC duration
2) To identify potential problems
3) To find areas that are worth to optimize
4) Whatever may be useful to improve XMage

I added two new recordings to the folder that were made with XMage 2014-02-07v6 version.
recordingXMage1_2014-02-14_2000-2100.zip
recordingXMage1_2014-02-15_0800-0900.zip
https://drive.google.com/folderview?id=0B8wbcD9SRksbcmF6cXlvWnRsejg&usp=sharing

The high CPU load seems to be solved with this version. GC times are also very short in this recordings.I will create longer recordings in the future to be able to analyse longer periods.

**Comment by LevelX2** [comment]
I added a new recording to the folder (recordingXMage1_2015-02-15_2100-0000.zip) over 3 hours.
The GC stays very moderate with <  3 seconds for the bug GC happening about once an hour.

But there are still some problems with cpu load. That increased at some point to currently about 100% CPU usage (of a possible max (set by limit) of 200% for XMage 1) . The server itself has 3 CPUs so a max of 300 % is possible.

![cpu-day](https://cloud.githubusercontent.com/assets/2066790/6209362/85236694-b5c5-11e4-8ee5-99dad593cf7f.jpg)

**Comment by aastrand** [comment]
Shame that didnt get into the recording .. 
Iirc there is a way to trigger a recording from the outside using the "jcmd" tool that ships with the same JDK as JFR.  This way you could get a recording of an already running JVM that is exhibiting problematic behaviour without restarting.
Check if it's supported in the version you use, the latest at least does:

jcmd <pid> JFR.start duration=<dur>s filename=myrecording.jfr

http://docs.oracle.com/javacomponents/jmc-5-4/jfr-runtime-guide/run.htm

You *could* set up a script that checks cpu load over time and triggers a recording if its over some limit.
Or run it by hand if you see a problem.

**Comment by aastrand** [comment]
The GC pattern in the very large file (3 hour run) actually looks pretty OK.
If it always looked like that, testing CMS could be a viable option to remove to long pauses.

**Comment by Plopman** [comment]
UUID.randomUUID() uses java.security.SecureRandom and /dev/urandom to generate random number. UUID doesn't need to be a cryptographically strong random number. Use java.util.concurrent.ThreadLocalRandom to generate UUID is more efficient.

**Comment by fireshoes** [comment]
The server did not reboot at 19:00 cet tonight. It just kept going uninterrupted.

**Comment by LevelX2** [comment]
> Iirc there is a way to trigger a recording from the outside using the "jcmd" tool that ships with the same JDK as JFR. This way you could get a recording of an already running JVM that is exhibiting problematic behaviour without restarting.
> Check if it's supported in the version you use, the latest at least does:
> 
> jcmd JFR.start duration=s filename=myrecording.jfr

Worked like a charm. Recorded today a 3 minute period after the cpu load went up.
recordingXMage1_2015-02-19_1053-1055.jfr (added to the folder)
So I could easily identify the problem creating card. Was a while loop with player choice that went on after the player conceded, because it was not checked that the player is still in play.
[Committed fix](https://github.com/magefree/mage/commit/d204af0b553898aa4b79baf24dde18d4ede4910f)

Thanks a lot, that jfr is of enormous help to get those bugs identified and fixed.

**Comment by aastrand** [comment]
That's awesome!

For what its worth the server stability has really improved a lot from what I've seen.
Looking forward to more to come.

**Comment by LevelX2** [comment]
> UUID.randomUUID() uses java.security.SecureRandom and /dev/urandom to generate random number. UUID doesn't need to be a cryptographically strong random number. Use java.util.concurrent.ThreadLocalRandom to generate UUID is more efficient.

Did you see in the flight recording the load randomUUID() did create?
 
So you suggest to use instead  java.util.concurrent.ThreadLocalRandom to create e.g. a long random and use some helper class to create a UUID from this?
Found this example:
https://github.com/junit/sb-framework/blob/master/sb-commons/common-utility/src/main/java/org/chinasb/common/utility/UUIDUtility.java

BUt there are a lot of UUIDs that are used not thread local (e.g. users games, controllers).
So I guess it could/should be used only for game specific UUIDs.

Any opinions on this?

**Comment by LevelX2** [comment]
One thing that needs fix is that a lot of game threads won't be canceled correctly after the game ends or whatever happens at end of game.
Currently (CET 13:00) there are a difference of 14 between active games and active game threads (one game thread was handling sideboarding so it's not included in the list of active games).
![threads](https://cloud.githubusercontent.com/assets/2066790/6266163/5cf85b84-b836-11e4-8b48-7e6fb507d98a.jpg)
Probably this game threads should run forever.

**Comment by LevelX2** [comment]
I added the GC log from yesterday to the jfr folder.

Tonight (3:00 CET) there was a short period (5 minutes) the server was unavailable. The server itself had no restart or something. It seems to be a network problem/change of the provider I guess.
At least after that period there are some changes to the network behaviour if I look at the munin graphs. Maybe they upgraded some network hardware, because the changes look like improvements. But time will tell.

![tcpdelayedack-day](https://cloud.githubusercontent.com/assets/2066790/6284422/1e181318-b8f0-11e4-8658-c01b9b3378e7.png)
![tcpqueueing-day](https://cloud.githubusercontent.com/assets/2066790/6284423/1e1a59c0-b8f0-11e4-93b1-6ea333a1b938.png)
![tcpsyncookies-day](https://cloud.githubusercontent.com/assets/2066790/6284424/1e1ab2f8-b8f0-11e4-95d4-916675f169ad.png)
![open_files-day](https://cloud.githubusercontent.com/assets/2066790/6284425/1e1bbd4c-b8f0-11e4-817a-977dcda9d226.png)
![load-day](https://cloud.githubusercontent.com/assets/2066790/6284426/1e1d8f64-b8f0-11e4-9253-0930c5893280.png)

**Comment by fireshoes** [comment]
There was a server problem tonight at around 7:16pm est. I got kicked off and couldn't log in for a few minutes. It looked like 15-20 matches were ended then. Attached the message I got when trying to log back in.
![serverdied](https://cloud.githubusercontent.com/assets/8553747/6475667/7d8ee82c-c1d2-11e4-8b42-83f9e019ee12.jpg)

**Comment by aastrand** [comment]
Seems there are problems happening again. Any analysis available?

**Comment by jeffwadsworth** [comment]
LevelX already gave the reason on the forum.

**Comment by LevelX2** [comment]
I setup a new server (xmage.de), that's probably more stable.
The current problems of Xmage.info are caused by the provider.
He changed something concerning the virtual server.

**Comment by goesta** [comment]
I'll close this issue because it seems to be outdated.
