### ISSUE TITLE
Exiling ZNR MDFC Should Return to the Battlefield as the Front Side

### ISSUE THREAD

**Issue by THUNDERWANG** [magefree/mage#7212]
In the following picture, I used Flickerwisp to exile the land. It should return as a creature, not as a land.

![exile](https://user-images.githubusercontent.com/59207918/100554440-80cf4200-3249-11eb-89ed-51dae6cae410.PNG)

**Comment by JayDi85** [comment]
Fixed by fde24f349f44f3334a9757b0a34f96208333e88e
