### ISSUE TITLE
Hans Eriksson triggered fight ability doesn't work.

### ISSUE THREAD

**Issue by ignitaxiom** [magefree/mage#7219]
hans fight ability doesn't work. also i'm quite certain that hans ability of putting a creature into play and fighting resolves all at once. there is no breaks in the text which usually means it isn't a separate triggered ability.

**Comment by emerald000** [comment]
Hans ability is a reflexive triggered ability.

603.12. A resolving spell or ability may allow or instruct a player to take an action and create a triggered ability that triggers “when [a player] [does or doesn’t]” take that action or “when [something happens] this way.” These reflexive triggered abilities follow the rules for delayed triggered abilities (see rule 603.7), except that they’re checked immediately after being created and trigger based on whether the trigger event or events occurred earlier during the resolution of the spell or ability that created them. If the trigger event or events occur multiple times during that time, the reflexive triggered ability will trigger once for each of those times.
