### ISSUE TITLE
Game Error after selecting permanents to place on battlefield from casting Genesis Ultimatum

### ISSUE THREAD

**Issue by foryayfan** [magefree/mage#7220]
Error Message:
An error has occurred on the MAGE server. Your last action will be rollbacked.

Game exception occurred: java.lang.NullPointerException
Server version: 1.4.46V0 (build: 2020-11-10 09:24)
java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
java.util.Iterator.forEachRemaining(Iterator.java:116)
java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
mage.cards.g.GenesisUltimatumEffect.apply(GenesisUltimatum.java:81)
mage.abilities.AbilityImpl.resolveMode(AbilityImpl.java:179)
mage.abilities.AbilityImpl.resolve(AbilityImpl.java:166)
mage.game.stack.Spell.resolve(Spell.java:230)
mage.game.GameImpl.resolve(GameImpl.java:1424)
mage.game.GameImpl.playPriority(GameImpl.java:1371)
mage.game.turn.Step.priority(Step.java:61)
mage.game.turn.Phase.playStep(Phase.java:184)
mage.game.turn.Phase.play(Phase.java:89)
mage.game.turn.Turn.play(Turn.java:126)
mage.game.GameImpl.playTurn(GameImpl.java:890)
mage.game.GameImpl.play(GameImpl.java:802)
mage.game.GameImpl.start(GameImpl.java:787)
mage.server.game.GameWorker.call(GameWorker.java:34)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)

[example deck that caused error.txt](https://github.com/magefree/mage/files/5633631/example.deck.that.caused.error.txt)

**Comment by LevelX2** [comment]
I was not able to reproduce the problem but I guess after the change it should no longer be possible that this exception happens.
