### ISSUE TITLE
Commanders seem to be colourless after Mycosynth Lattice has left the bf

### ISSUE THREAD

**Issue by johnmeat** [magefree/mage#7229]
I have Volrath, the Shapestealer as my commander in the command zone:
![image](https://user-images.githubusercontent.com/64497504/101334966-75df6780-3870-11eb-9ccf-67c14b255903.png)

Play Mycosynth Lattice:
![image](https://user-images.githubusercontent.com/64497504/101335026-8b549180-3870-11eb-87c4-6617012d71f2.png)

Putrefy Mycosynth Lattice:
![image](https://user-images.githubusercontent.com/64497504/101335125-ad4e1400-3870-11eb-8658-79bb694e86cd.png)
![image](https://user-images.githubusercontent.com/64497504/101335162-bb9c3000-3870-11eb-859f-23041b55c85d.png)

Commander still greyed like an artifact after lattice is destroyed:
![image](https://user-images.githubusercontent.com/64497504/101335248-dbcbef00-3870-11eb-96e4-648806f1bf89.png)

Casting him correctly does require the appropriate colours:
![image](https://user-images.githubusercontent.com/64497504/101335329-f43c0980-3870-11eb-89d8-d1db89fb5b6e.png)

However Volrath is now unaffected by All Is Dust:
![image](https://user-images.githubusercontent.com/64497504/101335448-1f265d80-3871-11eb-934d-a9d54a86b0e1.png)
![image](https://user-images.githubusercontent.com/64497504/101335493-2fd6d380-3871-11eb-90b4-dba983c87d27.png)

**Comment by JayDi85** [comment]
Works fine in current version. I think it was fixed in start of the year by that commit: c67ce93ec4b1170bc53b1b9d321a731dfbdf1bc1
