### ISSUE TITLE
Manifest an MDFC land with Scroll of Fate becomes a non-creature permanent

### ISSUE THREAD

**Issue by JohnPetfield** [magefree/mage#7230]
Once Scroll of Fate has manifested Clearwater Pathway, it becomes a permanent that isn't a creature:
![image](https://user-images.githubusercontent.com/64497504/101339624-97435200-3876-11eb-891b-830e1c115867.png)

i.e. it isn't a creature, putrefy can't target it:
![image](https://user-images.githubusercontent.com/64497504/101339795-c8238700-3876-11eb-8c72-b4e5fe7f4253.png)

**Comment by copperfield42** [comment]
I also see this, my simic Pathway got manifested from the top of my deck with Reality Shift, I later was able to bounce it to my hand with a bounce land

**Comment by JayDi85** [comment]
Fixed in #11873 and related commits
