### ISSUE TITLE
[CMR] Armix, hans and eligeth aren't working correctly from commander legends

### ISSUE THREAD

**Issue by ignitaxiom** [magefree/mage#7234]

**Comment by JayDi85** [comment]
Armix, Filigree Thrasher fixed by 9f67765e2d04015f2a51415155f194936326976b

**Comment by JayDi85** [comment]
Hans Eriksson works fine (put card to hand or creature to battle with selected target). Related tests added by a50f3c5416cf02d5d4f4e6c69db7681378ba8d6a

**Comment by JayDi85** [comment]
Eligeth, Crossroads Augur fixed by a1ed8e01b3af9afcfd60f0d5b541eaa70087f1d6
