### ISSUE TITLE
Blim, Comedic Genius second half of combat damage trigger doesn't do anything 

### ISSUE THREAD

**Issue by wwwood-ua** [magefree/mage#7238]
Hello,
I was just playing 1v1 commander and I dealt combat damage to my opponent with Blim. After the damage, I gave my opponent a pentad prism with zero charge counters on it. My opponent gained control of the prism, but didn't discard or lose life.
I can provide any other information needed if need be.

Xmage client version: 1.4.47V0-beta3
Server: beta.xmage.today

**Comment by jeffwadsworth** [comment]
![works](https://user-images.githubusercontent.com/1496996/103434283-c8d4e200-4bc4-11eb-839e-69d545a55764.jpg)
