### ISSUE TITLE
[CMR] Breeches error

### ISSUE THREAD

**Issue by ignitaxiom** [magefree/mage#7240]
Game exception occurred: java.lang.ClassCastException: mage.game.events.DamagedCreatureBatchEvent cannot be cast to mage.game.events.DamagedPlayerBatchEvent
Server version: 1.4.47V0-beta3 (build: 2020-11-30 02:35)
mage.cards.b.BreechesBrazenPlundererTriggeredAbility.checkTrigger(BreechesBrazenPlunderer.java:75)
mage.abilities.TriggeredAbilities.checkTrigger(TriggeredAbilities.java:94)
mage.abilities.TriggeredAbilities.checkTriggers(TriggeredAbilities.java:51)
mage.game.GameState.handleEvent(GameState.java:761)
mage.game.GameState.handleSimultaneousEvent(GameState.java:734)
mage.game.GameImpl.checkStateAndTriggered(GameImpl.java:1808)
mage.game.GameImpl.playPriority(GameImpl.java:1343)
mage.game.turn.Step.priority(Step.java:61)
mage.game.turn.CombatDamageStep.priority(CombatDamageStep.java:31)
mage.game.turn.Phase.playStep(Phase.java:184)
mage.game.turn.Phase.play(Phase.java:89)
mage.game.turn.Turn.play(Turn.java:126)
mage.game.GameImpl.playTurn(GameImpl.java:893)
mage.game.GameImpl.play(GameImpl.java:805)
mage.game.GameImpl.start(GameImpl.java:790)
mage.server.game.GameWorker.call(GameWorker.java:34)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)

**Comment by JayDi85** [comment]
Fixed by d39575c24ec2b7eb54b968007b400e9f1b5dde88 in #7241
