### ISSUE TITLE
Path of Ancestry

### ISSUE THREAD

**Issue by NekoNL** [magefree/mage#7245]
Path of ancestry triggered twice and once even 3 times on a single cast. Later in the game it only triggered once per cast so I am not sure what caused this.

**Comment by johnmeat** [comment]
I have seen this multiple times playing online although I can't seem to replicate this in test mode.

**Comment by JayDi85** [comment]
Steps to reproduce "accumulation bug": generate mana, but don't use it. On next usage it will use two effects. It was fixed by fef30de3f021b00f9ca4c174754fdac43f16ddb8
