### ISSUE TITLE
Cavern of souls and blood sun ("blood moon" problem)

### ISSUE THREAD

**Issue by acabaca24** [magefree/mage#7246]
Didn't have time to take a screenshot, but recently my opponent played a blood sun and the cavern of souls that he put into play after had a "chosen creature type" which they shouldn't.

Source: https://boardgames.stackexchange.com/questions/40299/how-does-blood-sun-interact-with-cavern-of-souls

Obs: 

- The caverns that were played before blood sun kept their "chosen creature type" which they should.

- Needs to be tested with alpine moon too

**Comment by jeffwadsworth** [comment]
This type of interaction will never happen unless a coder overhauls the system to conform to the "new" rules.
See:
https://github.com/magefree/mage/issues/4202

**Comment by JayDi85** [comment]
It related to main topic about blood moon problem
