### ISSUE TITLE
[CMR] Promise of Tomorrow error

### ISSUE THREAD

**Issue by ignitaxiom** [magefree/mage#7250]
Game exception occurred: java.lang.ClassCastException: mage.game.command.Commander cannot be cast to mage.cards.Card
Server version: 1.4.47V0-beta3 (build: 2020-11-30 02:35)
mage.abilities.effects.common.ExileTargetForSourceEffect.apply(ExileTargetForSourceEffect.java:80)
mage.abilities.AbilityImpl.resolveMode(AbilityImpl.java:179)
mage.abilities.AbilityImpl.resolve(AbilityImpl.java:163)
mage.abilities.TriggeredAbilityImpl.resolve(TriggeredAbilityImpl.java:81)
mage.game.stack.StackAbility.resolve(StackAbility.java:86)
mage.game.GameImpl.resolve(GameImpl.java:1427)
mage.game.GameImpl.playPriority(GameImpl.java:1374)
mage.game.turn.Step.priority(Step.java:61)
mage.game.turn.Phase.playStep(Phase.java:184)
mage.game.turn.Phase.play(Phase.java:89)
mage.game.turn.Turn.play(Turn.java:126)
mage.game.GameImpl.playTurn(GameImpl.java:893)
mage.game.GameImpl.play(GameImpl.java:805)
mage.game.GameImpl.start(GameImpl.java:790)
mage.server.game.GameWorker.call(GameWorker.java:34)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)

**Comment by JayDi85** [comment]
Bugs fixed by 3f44d9eef359c6f84b6a0e43e5a7d7a3f408adb2
