### ISSUE TITLE
Neither build is allowing Localhost play

### ISSUE THREAD

**Issue by Bdett151** [magefree/mage#7253]
Hello,

After the Beta update yesterday, I could not use the localhost server in that client. I downloaded the official release build and that will also not allow me to use the localhost server. Both builds have an error that states the localhost server is the wrong version. Any help would be appreciated.
![Xmagebetabuild](https://user-images.githubusercontent.com/76190939/102565060-ae6e1500-40aa-11eb-8f16-bc56434da2f9.PNG)
![XmageOfficialBuild](https://user-images.githubusercontent.com/76190939/102565061-af06ab80-40aa-11eb-882a-6f0ee140c4dc.PNG)

**Comment by JayDi85** [comment]
You must close all java apps or restart computer. Then run launcher from beta and update again. It fix problem with old files.
