### ISSUE TITLE
Attacking with Rakshasa Debaser

### ISSUE THREAD

**Issue by Razeick** [magefree/mage#7254]
Game exception occurred: java.lang.ClassCastException: mage.filter.predicate.ObjectPlayer cannot be cast to mage.filter.predicate.ObjectSourcePlayer
Server version: 1.4.47V0-beta4 (build: 2020-12-16 23:35)
mage.filter.predicate.permanent.DefendingPlayerOwnsCardPredicate.apply(DefendingPlayerOwnsCardPredicate.java:11)
mage.filter.predicate.Predicates$AndPredicate.lambda$apply$0(Predicates.java:152)
java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1359)
java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
java.util.stream.ReferencePipeline.allMatch(ReferencePipeline.java:454)
mage.filter.predicate.Predicates$AndPredicate.apply(Predicates.java:152)
mage.filter.FilterCard.match(FilterCard.java:60)
mage.target.TargetCard.canTarget(TargetCard.java:224)
mage.player.human.HumanPlayer.chooseTarget(HumanPlayer.java:606)
mage.target.TargetImpl.chooseTarget(TargetImpl.java:320)
mage.target.Targets.chooseTargets(Targets.java:89)
mage.abilities.AbilityImpl.activate(AbilityImpl.java:346)
mage.players.PlayerImpl.triggerAbility(PlayerImpl.java:1500)
mage.game.GameImpl.checkTriggered(GameImpl.java:1853)
mage.game.GameImpl.checkStateAndTriggered(GameImpl.java:1811)
mage.game.GameImpl.playPriority(GameImpl.java:1345)
mage.game.turn.Step.priority(Step.java:61)
mage.game.turn.Phase.playStep(Phase.java:184)
mage.game.turn.Phase.play(Phase.java:89)
mage.game.turn.Turn.play(Turn.java:127)
mage.game.GameImpl.playTurn(GameImpl.java:895)
mage.game.GameImpl.play(GameImpl.java:807)
mage.game.GameImpl.start(GameImpl.java:792)
mage.server.game.GameWorker.call(GameWorker.java:34)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)

**Comment by Razeick** [comment]
Hello!

Best summary I can describe is: I was trying to attack with Rakshasa Debaser. The effect that lets me take control of creature in opponents graveyard triggered. I tried to click on the creature I wanted and then the crash happened.

**Comment by JayDi85** [comment]
Fixed by c13d07b73d4673c96f03fc5441279b39baa0f461
