### ISSUE TITLE
"Landfall" triggering (twice) on MDFC lands

### ISSUE THREAD

**Issue by duelcastermage** [magefree/mage#7258]
This may only apply to Kazandu Mammoth, but if the card is first played as a land, future lands played will trigger it's landfall ability even though that should never happen. These also trigger twice for each land.

The double trigger might be a separate issue that happens even if the Mammoth is played as a creature, I'm not sure. See pic.

<img width="812" alt="Landfall on land mdfcs" src="https://user-images.githubusercontent.com/46700039/102694837-dd5bc680-4223-11eb-8fe4-8c17cda2a78b.png">

**Comment by JayDi85** [comment]
Double mdf triggers were fixed by 656653f38b0deb6e2796ba318443ad240f4d9cfa from #7180
