### ISSUE TITLE
Vivien, Monsters' Advocate Doesn't Make Vigilance Counter

### ISSUE THREAD

**Issue by stevedavidmusic** [magefree/mage#7264]
Had an issue in game where Vivien, Monsters' Advocate did not make a vigilance counter on a token it created.

**Comment by stevedavidmusic** [comment]
Testing out this bug, actually what hapepned was that somebody hit the cancel button. Perhaps there should be a cancel / search functionality?

**Comment by weirddan455** [comment]
The choice for that ability needs to be made mandatory.  It should not be possible to cancel and create a token without a counter.  I'm about to put a pull request in with a fix.
