### ISSUE TITLE
Odric, Master Tactician doesnt do anything

### ISSUE THREAD

**Issue by randomsuspect** [magefree/mage#7266]
If i m not missing something crucial, Odric, Master Tacticians ability doesnt let you choose the blockers in the declare blockers step. It apparently doesnt do anything at all; my opponents could block as usual. It happened in 2 matches, in both i attacked with more than 4 creatures, Odric's ability went on the stack and resolved.

**Comment by weirddan455** [comment]
I'm not able to reproduce this bug.  In a 1v1 against the AI, I attacked with 4 creatures and it let me choose the blocks.
![xmage-odric](https://user-images.githubusercontent.com/8128047/103357630-44c21380-4a79-11eb-834a-06c117b98039.jpg)

**Comment by weirddan455** [comment]
Actually, scratch that.  I was able to reproduce the bug between two human players.  The card only works correctly against the AI for some reason...

**Comment by weirddan455** [comment]
I've got a fix.  About to send a PR.
