### ISSUE TITLE
[Rollback bug] Expedition Map doesn't sac itself, or cost anything. 

### ISSUE THREAD

**Issue by tyler274** [magefree/mage#7271]
Playing on the latest beta server and client (12-19-2020), Expedition Map was tapped 3 times without paying or sacking itself. 

Sol Ring and Expedition Map also were able to be played without paying mana this game, costs seem bugged? maybe I misconfigured something but I thought they were mostly default.  
in the server log:
```
ERROR 2020-12-21 03:43:58,535 It was not possible to do the requested undo operation (bookmark 2 does not exist) context: {U/R}, {T}: Add {U}{U}. =>[GAME 95437ed2-d085-4d49-9c30-9857a6f185c1] GameImpl.restoreState 
```

**Comment by tyler274** [comment]
duplicate of bookmark bugs

**Comment by tyler274** [comment]
[20201221_023510_Commander Free For All_1.txt](https://github.com/magefree/mage/files/5726614/20201221_023510_Commander.Free.For.All_1.txt)

Here is the game log of the event.

**Comment by JayDi85** [comment]
I can't reproduce your bug with free cost of Expedition Map. Please provide step by step instruction.

**Comment by tyler274** [comment]
Even with the log?

**Comment by JayDi85** [comment]
Game logs don't show your real actions and results -- some data or changes can be miss from it. Example: game logs don't show mana taps -- if you look at related issue then will see that's mana tap order is important for that type of error.

Your server logs shows different rollback "errors" with different card usage (look at "context").

**Comment by tyler274** [comment]
Could those details be added to the logs with a config option? I don't
remember enough details and it was the player who triggered the bug's first
game, nor do they remember. Thanks.

**Comment by JayDi85** [comment]
Nope, you can't add mana taps to logs by option.

**Comment by tyler274** [comment]
Well, since it's currently causing bugs could we add those taps to logs to
make tracking these bugs down easier?

**Comment by JayDi85** [comment]
Nope. There is a lot of mana in the game and it will greatly inflate the logs with unnecessary information for the user. Moreover it's not a real error -- it's just a "cheat" in game engine. And it's a rare situation (rare combo).

Maybe it will be useful to inform other game's players about "cheating".

**Comment by tyler274** [comment]
But why not add it as a config option for more verbose logs?

**Comment by tyler274** [comment]
Excuse me but why not add a verbose logging option to track down this real
bugs?

**Comment by tyler274** [comment]
A cheat that gives you infinite mana is a bug since the game breaks at that point.
