### ISSUE TITLE
Mana from Jeweled Lotus can't be used for commanders

### ISSUE THREAD

**Issue by hunz-dev** [magefree/mage#7272]
Sacrificing Jeweled Lotus adds mana to my pool, however it isn't auto-applied to the cost of casting Kozilek, nor can I use the generated mana when selecting it manually. Curious if it has something to do with consuming mana of a different color that's not in the identity of the commander, but AFAIK it should still be able to be used.

**Comment by JayDi85** [comment]
Fixed by 347a3b1e1a5ef5acfdcb0f7416bf57e9cd7a1d04
