### ISSUE TITLE
Sublime Epiphany rollback

### ISSUE THREAD

**Issue by catman123456** [magefree/mage#7273]
When I play sublime epiphany this happens

Game exception occurred: java.lang.NullPointerException
Server version: 1.4.47V0 (build: 2020-12-19 20:00)
mage.target.targetpointer.FirstTargetPointer.getTargets(FirstTargetPointer.java:50)
mage.view.CardView.lambda$addTargets$2(CardView.java:746)
java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
mage.view.CardView.addTargets(CardView.java:748)
mage.view.CardView.<init>(CardView.java:479)
mage.view.CardView.<init>(CardView.java:226)
mage.view.CardView.<init>(CardView.java:125)
mage.view.CardsView.<init>(CardsView.java:121)
mage.server.game.GameController.lambda$target$18(GameController.java:822)
mage.server.game.GameController.perform(GameController.java:954)
mage.server.game.GameController.perform(GameController.java:947)
mage.server.game.GameController.target(GameController.java:821)
mage.server.game.GameController.lambda$init$3aa0d15c$2(GameController.java:188)
mage.game.events.EventDispatcher.fireEvent(EventDispatcher.java:28)
mage.game.events.PlayerQueryEventSource.target(PlayerQueryEventSource.java:72)
mage.game.GameImpl.fireSelectTargetTriggeredAbilityEvent(GameImpl.java:2457)
mage.player.human.HumanPlayer.chooseTriggeredAbility(HumanPlayer.java:1191)
mage.game.GameImpl.checkTriggered(GameImpl.java:1856)
mage.game.GameImpl.checkStateAndTriggered(GameImpl.java:1812)
mage.game.GameImpl.playPriority(GameImpl.java:1345)
mage.game.turn.Step.priority(Step.java:61)
mage.game.turn.Phase.playStep(Phase.java:184)
mage.game.turn.Phase.play(Phase.java:89)
mage.game.turn.Turn.play(Turn.java:127)
mage.game.GameImpl.playTurn(GameImpl.java:895)
mage.game.GameImpl.play(GameImpl.java:807)
mage.game.GameImpl.start(GameImpl.java:792)
mage.server.game.GameWorker.call(GameWorker.java:34)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)

**Comment by JayDi85** [comment]
Can you provide steps to reproduce that bug? I think there were a disconnect/lose or non started game. Sublime Epiphany works fine.

**Comment by catman123456** [comment]
Well I turn off my firewall and the error stop happening.

**Comment by JayDi85** [comment]
I found potentially bugged code with missing game data (related to pile choose dialog and triggers/abilities on the stack with targets). Maybe it was called somehow from normal game situation. Fixed by a87c0b1ff671305495b72aadb30f85c0e810e8f2.
