### ISSUE TITLE
[Bug] Archive trap alternate cost

### ISSUE THREAD

**Issue by jathanasiou** [magefree/mage#7274]
The alternative cost of [Archive Trap](https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=197538) seems to be bugged.

I just had opponent search their library and I could not put the Trap on the stack when I received priority. This was on turn1 so I don't believe any effects messed with that as no permanents were in the field at all.

EDIT: confirmed this happening across multiple games.

**Comment by JayDi85** [comment]
Fixed by aa7226a1af7b89d469e77ebcf834f098414c6e8b
