### ISSUE TITLE
Forced Rollback on Genesis Ultimatum

### ISSUE THREAD

**Issue by MonoRayJak** [magefree/mage#7275]
I cast Genesis Ultimatum and hit five permanents, which I put into play, the five being:
- Solemn Simulacrum
- Simic Signet
- Hullbreacher
- Maelstrom Colossus
- Riverglide Pathway//Lavaglide Pathway

Afterwards, the game immediately rerolls and gives me the following error:

Game exception occurred: java.lang.NullPointerException
Server version: 1.4.47V0 (build: 2020-12-19 20:00)
mage.players.PlayerImpl.moveCardToHandWithInfo(PlayerImpl.java:4197)
mage.players.PlayerImpl.moveCards(PlayerImpl.java:4117)
mage.players.PlayerImpl.moveCards(PlayerImpl.java:4069)
mage.players.PlayerImpl.moveCards(PlayerImpl.java:4062)
mage.cards.g.GenesisUltimatumEffect.apply(GenesisUltimatum.java:85)
mage.abilities.AbilityImpl.resolveMode(AbilityImpl.java:179)
mage.abilities.AbilityImpl.resolve(AbilityImpl.java:166)
mage.game.stack.Spell.resolve(Spell.java:234)
mage.game.GameImpl.resolve(GameImpl.java:1430)
mage.game.GameImpl.playPriority(GameImpl.java:1376)
mage.game.turn.Step.priority(Step.java:61)
mage.game.turn.Phase.playStep(Phase.java:184)
mage.game.turn.Phase.play(Phase.java:89)
mage.game.turn.Turn.play(Turn.java:127)
mage.game.GameImpl.playTurn(GameImpl.java:895)
mage.game.GameImpl.play(GameImpl.java:807)
mage.game.GameImpl.start(GameImpl.java:792)
mage.server.game.GameWorker.call(GameWorker.java:34)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)

**Comment by MonoRayJak** [comment]
Upon a bit more testing, the issue is being caused by either the colossus or pathway land. After casting ultimatum again and choosing the other three it worked fine.

**Comment by MonoRayJak** [comment]
its the pathway, colossus worked fine

**Comment by JayDi85** [comment]
Fixed by 10cf9c4a4e03f709c9989d3299edb486ccb06ead
