### ISSUE TITLE
Dividable Burn Can't Target Planeswalkers

### ISSUE THREAD

**Issue by stevedavidmusic** [magefree/mage#7276]
The following cards cannot target planesewalkers:

- Inferno Titan
- Arc Lightning
- Flames of the Firebrand
- Forked Bolt
- Twin Bolt

The following dividable burn spells CAN target planeswalkers:

- Shatterskull Smashing
- Arc Trail

**Comment by JayDi85** [comment]
Fixed by 255c2921040ee73faaf669444a0a6237dbb10b53. Also it can improve/change AI targeting for cards that can choose creature or planeswalker in one spell).
