### ISSUE TITLE
Archelos, Lagoon Mystic bugged

### ISSUE THREAD

**Issue by duelcastermage** [magefree/mage#7283]
Archelos is bringing up both replacement effects for me to choose whenever a new permanent enters the battlefield (whether he's tapped or untapped). Basically I can choose whether a permanent ETBs tapped or untapped, contrary to the effect of the card.

Also my opponent's lands at least were also entering untapped when Archelos was tapped.

**Comment by duelcastermage** [comment]
Update: it seems that entering tapped or untapped is kind of random, despite choosing a consistent order on the choose replacement effect order dialog box.

**Comment by JayDi85** [comment]
Fixed by 6f34d514f99a9e0e19563f63e4b4c45c16e579f1
