### ISSUE TITLE
Option to grant infinite mana / alternate cost of 0 instead of manually executing infinite combos

### ISSUE THREAD

**Issue by lolfran123** [magefree/mage#7284]
Apologies if this is the wrong place to post this.
I'm wondering is it possible to implement an option to grant a player temporary infinite mana / some sort of omniscience emblem to shortcut an infinite mana combo?

With Cedh gaining traction I think it might be a convenient idea to implement

**Comment by JayDi85** [comment]
There are a special test mode -- you can add any cards and construct any combo. Read more details on [wiki page](https://github.com/magefree/mage/wiki/Development-Testing-Tools) how-to start a local server in test mode and how-to execute cheat commands.

**Comment by ldeluigi** [comment]
What about using the combo database to check for infinite combo wins

OR

what about a "record" button that memorizes a loop of triggers and actions and then repeats it if other players agree?

**Comment by JayDi85** [comment]
@ldeluigi 

Nope, xmage do not support infinite combos and it can't be implemented by game engine. That situations must be process by players. 

Xmage have special mechanism to stop automatic infinite combo on the stack (example: if one resolve would generates new triggers and vice versa -- so the players can't make any decisions and game asks to draw).

**Comment by JayDi85** [comment]
For some triggers/effects you can right click in choose dialog to save your choose for next time. Macro recording can be implemented in the feature (it was disabled few years ago due rollback bugs, #2147).
