### ISSUE TITLE
[BUG] Jeweled Lotus + Krrik

### ISSUE THREAD

**Issue by ldeluigi** [magefree/mage#7288]
![image](https://user-images.githubusercontent.com/44567586/103138624-a7f82280-46d4-11eb-83c4-3d1cd587cb3c.png)
I can't cast Krrik. I tried to flood jeweled lotus first but nothing.
Krrik doesn't highlight

**Comment by JayDi85** [comment]
Jeweled Lotus was fixed by 347a3b1e1a5ef5acfdcb0f7416bf57e9cd7a1d04 from #7272 issue
