### ISSUE TITLE
How can I help you?

### ISSUE THREAD

**Issue by demenor** [magefree/mage#729]
I'm a JAVA coder(full-time job) and also a Designer. Would love to improve XMage. Would you guys be interested in some free help?

**Comment by jeffwadsworth** [comment]
Join the team.  LevelX2 is the person to get in touch with.

**Comment by emerald000** [comment]
We are always interested in some new talent! You can find a guide to get started here: https://github.com/magefree/mage/wiki/Developer-Getting-Started

**Comment by LevelX2** [comment]
Hello demenor,

of course I see a lot to do for a java experienced designer.
The UI has still a lot of areas where improvements can take place. I hope you also know a bit about swing. It would be very nice to have someone that has some talent in the UI area. 

As emerald already pointed out clone the repository and get the environemnt working. If you have any questions use the developer sub forum of slightlymagic.
I guess there is some time needed to get a bit familar with the XMage code.
I think you already used XMage to play magic, so you probably have already some ideas yourself to enhance the UI. 
 
If that's a direction you like to go we can also gather some ideas what's best to improve and talk about it in the developer forum. 


*Some examples of useful UI changes that come to my mind:*
* A color selector that looks nice (showing the 5 colors of magic).
* Improve handling of top card of library is face up.
* Embellish and improve tournament panel.

Probably harder to do:
* A new way to handle cards in the graveyard (more permanent access).
* [New phase bars](http://www.slightlymagic.net/forum/viewtopic.php?f=70&t=14960&sid=e0181c299805398b197653d1becca5d0)
* Redesign of message and button area to be able to show longer texts.

regards
There are a lot more.

**Comment by demenor** [comment]
Hello LevelX2, 

I'm setting up my development environment right
now, and I'm really happy to be able to help you guys in this project.


Is there any way we can chat directly via Skype or anything like that?


regards, 
-- 

 		Mateus Carvalho Gonçalves

 		DESENVOLVEDOR

 		(11)
2157-2170

 		(11) 996311-4998

 		www.orgm.com.br [1] | [2] | [3] 




Links:
------
[1] http://www.orgm.com.br/
[2]
https://www.facebook.com/pages/ORGMIt
[3] https://twitter.com/ORGM_ITS

**Comment by LevelX2** [comment]
Hello demenor,

I rarely use Skype or other tools like this. So let us best go on with discussion in the forum here:
http://www.slightlymagic.net/forum/viewtopic.php?f=116&t=16776&p=173555#p173555

If discussion by Skype is needed later we can arrange something by forum PM.
I guess you're located in Brazil?

Regards
