### ISSUE TITLE
Wheel of Misfortune Bug

### ISSUE THREAD

**Issue by meetaig** [magefree/mage#7292]
Just played WoM in a game of commander with 2 other players. I chose 2, everyone else 0. I lost 2 life, didnt get the weel and nothing else happened. 

![bug_wheel_of_misfortune](https://user-images.githubusercontent.com/18595989/103142184-86f8f700-46ff-11eb-84a9-a51d5c60375a.png)

**Comment by JayDi85** [comment]
Fixed by 7753ca305e2c96f9acc85204cb03a2d119d8ce6a
