### ISSUE TITLE
[Question] Ngrok server configuration

### ISSUE THREAD

**Issue by ldeluigi** [magefree/mage#7293]
Please, could you provide a configuration that works with [ngrok](https://ngrok.com/), in the Wiki? I can't make it work, I tried lots of settings combination but I keep getting a Remote Task Error from the clients.

**Comment by JayDi85** [comment]
I think you can try to make same settings as ports forward do for local server behind NAT: https://github.com/magefree/mage/issues/5597#issuecomment-465647095

IF not helps then I'll look at ngrok tomorrow for more details.

**Comment by ldeluigi** [comment]
I think the issue is that tcp traffic through port 17171 isn't enough because ngrok forwards only that port, not 17172, which I assume it's needed.
But I don't know if there is a solution.

Anyway, the idea with ngrok is to avoid setting a static IP, a DDNS or any port forwarding. With ngrok set up, the xmage server "thinks" to serve localhost, while ngrok manages a tunnel that allows traffic (only TCP) to be forwarded from ngrok servers to your pc, and then from your pc to the xmage server, as if it came from localhost.
