### ISSUE TITLE
[Feature request] Client side bots on server

### ISSUE THREAD

**Issue by ldeluigi** [magefree/mage#7294]
Given that mad boits aren't available on the server, why don't you make a mode where a client can leave to a bot the playing so that AI computations are on the client side?

My idea of use of this feature:

2 friends want to play EDH in 4, so each starts two clients. One client, for each player, is put in mad bot mode, while the other is put in human mode. Then, each of the 4 clients connects to a server and joins the same match. Then it's much like playing with 2 mad bots from configuration, but bot decisions are computed by the clients, leaving the server weight-free.

**Comment by JayDi85** [comment]
XMage is full client-server app (all data and calculations processing on the server side). It helps from cheating or data manipulation on client side. 

Current AI implementation (mad bot) uses server side logic and data. It can't be run on client side -- client app gets only "visible" information for current player, not full game data.

Maybe in the feature someone can write a client side AI with machine learning that would able to play as normal human player on any server -- technically xmage support that type of bots.

**Comment by ldeluigi** [comment]
I understand it now. Thanks for answering.
