### ISSUE TITLE
Jhoira's Suspend seems to be broken.

### ISSUE THREAD

**Issue by dylan1020** [magefree/mage#730]
I suspended Boom // Bust with Jhoira and the suspend upkeep trigger never triggered for a number of turns. The time counters get on the card fine, it just doesn't trigger suspend on my upkeep.

**Comment by drmDev** [comment]
will test

**Comment by tcontis** [comment]
Tested and the suspend trigger works on upkeep for Boom // Bust w/ Jhoira. I know this is an old issue, just trying to close those already fixed.
