### ISSUE TITLE
Cannot register or access servers, even at localhost

### ISSUE THREAD

**Issue by liambrownweb** [magefree/mage#7304]
Running OpenSuSE Tumbleweed, up to date as of last week. I keep getting the infamous "can not find free port for use" message when trying to register an account. This applies to every server including my localhost. I have tried the following to no avail:

* Disabling firewall
* Enabling port forwarding on the router (not that I would expect this to affect localhost, but at least other servers it might)
* Restarting the computer

It's probably not the character thing mentioned in some of the threads I've followed, because my system is using US English (which I seem to recall is one of the languages recommended for solving the character bug).

**Comment by JayDi85** [comment]
If you get "can't find free port" then restart then client (close all java apps) -- it can help to fix that problem.

Also you need registration only for xmage.de server -- localhost, eu and us is no registration -- you must enter any username with empty password to login.

Xmage uses inner java from "launcher's folder\java\" (if you run it by launcher, not script). So if you setup firewall manually then you must add rules for that app `launcher_folder\java\jre1.8.0_201\bin\java".

My recommendation:
1. Close all java apps;
2. Run launcher and start client and server;
3. Wait 1 minute to server load (you must see "... listening..." log in server's logs window;
4. Try connect to server logs.
