### ISSUE TITLE
Austere command doesn't destroy all player's artifacts?

### ISSUE THREAD

**Issue by Zorkony** [magefree/mage#732]
in a multiplayer game of EDH with 4 players, one person didn't have his artifacts destroyed while the rest of us did.. no they were not indestructible or anything :)

**Comment by Zorkony** [comment]
edit: perhaps because of range of influence ONE

**Comment by fireshoes** [comment]
The Range of Influence may have been set to only allow effects to each player one seat away.

**Comment by Zorkony** [comment]
probably correct :) my bad, I never play with limited RoI :$

**Comment by LevelX2** [comment]
So I close this.
