### ISSUE TITLE
Manifested basic lands

### ISSUE THREAD

**Issue by JohnPetfield** [magefree/mage#7320]
If an opponent manifests basic lands Xmage shows you that the manifest is a land with the basic land frame, symbol and colour:

XLN basics in test.dck:
![image](https://user-images.githubusercontent.com/64497504/103440517-412bb980-4c3e-11eb-9b54-9f372469720d.png)

THB Islands:
![image](https://user-images.githubusercontent.com/64497504/103440550-8bad3600-4c3e-11eb-96dc-5d3588079292.png)

**Comment by JayDi85** [comment]
Fixed in #11873 and related commits
