### ISSUE TITLE
CPU not sacrificing highest power creature to Szat's Will

### ISSUE THREAD

**Issue by catman123456** [magefree/mage#7321]
When I used mode 1 on Szat's Will the CPU sacs a token

https://user-images.githubusercontent.com/64045003/103440927-d5cef100-4c17-11eb-9b94-5d7fc8e48e52.mp4

**Comment by jeffwadsworth** [comment]
![Szat's Will Bug](https://user-images.githubusercontent.com/1496996/103578908-02476f00-4e9d-11eb-8044-e3d10772ab43.jpg)
A filter bug.
