### ISSUE TITLE
Landwalking bug

### ISSUE THREAD

**Issue by acabaca24** [magefree/mage#7323]
Landwalking of any type is broken.
To aid term searching:
Islandwalk
Swampwalk
Forestwalk
Mountainwalk
Plainswalk

**Comment by T-and-Em** [comment]
Myself and others experienced this in a game earlier today. Bog Wraiths was unblockable by a player who had no swamps.

**Comment by sprangg** [comment]
Could it be this commit from 17 days ago? https://github.com/magefree/mage/commit/a307e5934f850b8936774a95787d4978d69ee179#diff-75a9ccc52ad403d9ef99f585c3bc56e1e913cb5730cfb77a7ae0feafea21c8e1

**Comment by JayDi85** [comment]
@sprangg that code added full filter checking. So if some card's filter broken then it doesn't work now. I need card example and what's wrong description for research.

**Comment by sprangg** [comment]
Ok results so far: When there are no swamps on the battlefield swampwalkers can be blocked, but when either me or the opponent has a swamp, they cannot be blocked.

I tested with a deck full of different swampwalkers, and so far these all have worked in the same way described above:
Street Wraith
Bog Wraith
Quag Vampires
Zodiac Rat
Whispering Shade
Filth
Zodiac Snake
Witch Engine
Plague Beetle

This should be enough of a sample size of cards? I'll test other landwalks next.

**Comment by sprangg** [comment]
Did a quick test with mountainwalk and forestwalk. Both work consistently with the above swampwalk test: if I have the mountain/forest on the battlefield, the opponent can't block any of my landwalking creatures.

The forestwalk test deck had snow-covered forests, and Rime Dryad (snow-covered forestwalker) was also unblockable.

It didn't matter whether the creature gained the landwalk through an ability - they were still unblockable. Tested this with Enslaved Scout and Elvish Pathcutter. If I didn't give them the landwalk, the AI blocked them.

Mountainwalkers tested:
Canyon Wildcat
Enslaved Scout
Goblin Scouts (creates 1/1 mountainwalk tokens, worked similarly as nontokens)

Forestwalkers tested:
Unseen Walker
Mirri, Cat Warrior
Elite Cat Warrior
Vine Dryad
Somberwald Dryad
Zodiac Tiger
Heartwood Treefolk
Zendikar Farguide
Leaf Dancer
Zodiac Monkey
Emerald Oryx
Rushwood Dryad
Scarwood Bandits
Willow Dryad
Lynx
Shanodin Dryads
Cat Warriors
Zodiac Rabbit
Elvish Pathcutter
Jukai Messenger
Rime Dryad

**Comment by sprangg** [comment]
Looks like this was fixed by https://github.com/magefree/mage/commit/5f80dba107f566bce801b7b5e81de6b44945fbca

Thank you so much theelk801!
