### ISSUE TITLE
Odric, Master Tactician definitly bugged

### ISSUE THREAD

**Issue by randomsuspect** [magefree/mage#7328]
I already opened this once, but the bug get tested in singleplayer and was apparently not existing. Since the bug always appeared in Multiplayer EDH, it has something to do with the Multiplayer Setup. 

After Trigger resolves nothing happens and you can not choose blockers. Blockers can be declared as usual by the opponents.

**Comment by weirddan455** [comment]
Have you tested this bug with a build from git?  https://github.com/magefree/mage/commit/de37ad1da1b2017efd7dd9c321509a391a60e9a6 should have fixed this but it hasn't made it into a beta release yet.

**Comment by jeffwadsworth** [comment]
Yes, if you aren't using the latest "build" from this site, you won't have the fix.

**Comment by jeffwadsworth** [comment]
Tested it again and it worked beautifully with the new build.  Just wait for the next release.
