### ISSUE TITLE
Odric Master Tactician, Multiplayer Bug

### ISSUE THREAD

**Issue by randomsuspect** [magefree/mage#7329]
I will reapeat this Threat since it got deleted somehow: In a Multiplayer Match , I am not able to declare blockers after Odric triggered and I attacked with enough other creatures. My opponents are able to block as usual. 

This is very annoying for me, since it s one of my Key-Cards in my favourite EDH Deck.

I am pretty sure I am not doing something wrong, i have 1300 matches on Xmage, so pls take a look on this bug again if you can. Thank you.

**Comment by emerald000** [comment]
The fix ill be available in the next version.

**Comment by JayDi85** [comment]
@randomsuspect new release will be available in next 2-3 days.
