### ISSUE TITLE
Suggestion: "add x Mana in any combination of" change select screen

### ISSUE THREAD

**Issue by CaioACorrea94** [magefree/mage#7330]
Cards with the ability to "add x Mana in any combination of" (Axebane guardian as an example) requests you to choose one by one the Mana you desire.

My suggestion is to pop a screen specifying how many is "x" and you can distribute it between the available colors. This way you can choose the desired colors in only one screen.

**Comment by copperfield42** [comment]
I also made the same suggestion some time ago #6865
