### ISSUE TITLE
Syr Konrad, the Grim bug

### ISSUE THREAD

**Issue by catman123456** [magefree/mage#7334]
when I exiled the opponent graveyard that has creatures in it with Tormod's Crypt the opponent takes no damage.

**Comment by weirddan455** [comment]
That is the correct interaction.  Syr Konrad says "or a creature card leaves **your** graveyard."  If you were to target yourself with Tormod's Crypt, opponent would take damage (assuming you have creatures in your graveyard.)

**Comment by catman123456** [comment]
Ah I Just checked and your right.
