### ISSUE TITLE
Jace, Telepath Unbound did not let me Flashback the Spell?

### ISSUE THREAD

**Issue by yak300** [magefree/mage#7340]
Activated the -3 Ability on **Jace, Telepath Unbound** (Flipped side of Jace, Vryn's Prodigy) to flashback a Goryo's Vengeance in the graveyard. However, i was unable to actually cast the spell from the graveyard; the card was not highlighted. The only other card interacting with the graveyard at the time was a "Leyline of the Void" but the targeted card was already there before the leyline. So it would not interact with the ability at all.

**Comment by jeffwadsworth** [comment]
![works](https://user-images.githubusercontent.com/1496996/103972836-861a8900-5133-11eb-92e4-132699b5d6b1.jpg)


Did you have a Legendary creature card in the graveyard to target?

**Comment by jeffwadsworth** [comment]
Closing for now.  Re-open if the issue is seen again.  It worked fine for me.

**Comment by yak300** [comment]
I encountered the issue several times during play on xmage.de. I did recreate the issue on the localhost to get pictures, I hope this is acceptable. This was with the most current build (1.4.47V1). Please see the attached screenshots for clarification and the log.

When I activate Jace, Telepath unbound negative (-3) ability on Goryo's Vengeance in the graveyard, **the card is not being highlighted as castable**. In the picture you can see that there are valid targets for Goryo's as well as enough mana to cast it. When i move to Mainphase 2, the card suddenly gets highlighted and can be cast as intended. This however, is not how Jaces negative 3 ability should work. This makes Goryo's Vengeance unusable in thhis deck as the brought back creature is unable to attack (as the attack step was already skipped).

Img 1: Jace before activation (Main 1).
![Jace_before_activation](https://user-images.githubusercontent.com/77124678/104386416-6e794100-5535-11eb-9115-9bd560660a7a.jpg)

Img 2: after Jace activation. Gory's Vengeance is not highlighted as castable and cannot be cast.
![Jace_after_activation](https://user-images.githubusercontent.com/77124678/104386492-9c5e8580-5535-11eb-8c27-abac04f2c2cb.jpg)

Img 3: Mainphase 2 after Jace activation (same turn as Img 2).
![Jace_after_activation_Main2](https://user-images.githubusercontent.com/77124678/104386647-e6476b80-5535-11eb-87aa-1e43f4ac6019.jpg)

**Comment by jeffwadsworth** [comment]
![SelectedMinus3Ability](https://user-images.githubusercontent.com/1496996/104795546-ed0ff180-5774-11eb-9ef1-a071649c7dac.jpg)
![SelectTargetedGoryo'sRevenge](https://user-images.githubusercontent.com/1496996/104795549-f00ae200-5774-11eb-9466-0319923c8c04.jpg)
![HighlightedReadyForCasting](https://user-images.githubusercontent.com/1496996/104795553-f305d280-5774-11eb-9087-63e5079bd4c1.jpg)
![WorksFine](https://user-images.githubusercontent.com/1496996/104795556-f4cf9600-5774-11eb-902d-70e644a483ed.jpg)

**Comment by jeffwadsworth** [comment]
Works perfectly fine for me.

**Comment by yak300** [comment]
I think I see what the issue is here, it is probably not a bug. Now i feel kinda embarassed.

When activating Jace, Telepath unbound, there is no "ability token" shown on the stack once you have chosen the targets. This seems different to front face only planeswalkers e.g. Liliana of the Veil, where her abilities create a "ability token" on the stack. I guess I misunderstood the boardstate and assumed passing priority would mean already going to the beginning of combat already. So when you activate Jace, Telepath unbound it seems like the stack is empty immediately after choosing the targets!

In reality, the first passing of priority only lets the jace activation resolve. After that, everything is working as inteded. So the "error" I reported was when the (-3) ability of Jace did not even resolve yet, but the stack was visually empty already.
Sorry to cause you unnecessary effort!
