### ISSUE TITLE
Druid's Call

### ISSUE THREAD

**Issue by catman123456** [magefree/mage#7355]
I targeted Jared with court of ire and no squirrel tokens are made

<img width="1920" alt="Untitled" src="https://user-images.githubusercontent.com/64045003/104108372-15d64980-5292-11eb-8ec3-a2092ce2c12a.png">

**Comment by ciaccona007** [comment]
In this photo, you are the monarch, so Jared's second ability prevented the damage and no Squirrel tokens were made. As far as I can tell this is the correct behavior

**Comment by jeffwadsworth** [comment]
It appears that this issue has been resolved.  If not, just re-open it.

**Comment by JayDi85** [comment]
@catman123456 BTW, you can open main menu -> preferences -> sizes to change cards and other GUI size -- it can help with too small images on big screens. Another way: as Windows compatible mode (see more details in [that video](https://www.youtube.com/watch?v=jHFwqYoWiqM)).
