### ISSUE TITLE
Haldan Bug report

### ISSUE THREAD

**Issue by HenriLamarre** [magefree/mage#7358]
Haldan does not allow you tu use mana of any color to pay costs

![image](https://user-images.githubusercontent.com/59838556/104111135-c8b3a100-52ac-11eb-8e11-aea780c7f1af.png)
In This scenario, my friend (Bruj) could not cast my merciless eviction with his aldan

**Comment by jeffwadsworth** [comment]
https://github.com/magefree/mage/issues/7122
Fixed already but not yet in the "release' version.
