### ISSUE TITLE
Bug Report: MDFCs disappear from hand when reversed in hand

### ISSUE THREAD

**Issue by spcphd1976** [magefree/mage#7361]
On two occasions, I have clicked on a MDFC card in my hand to play its other side and it immediately disappeared from my hand. One card was a pathway land and the other was Emeria's call. I'm play on Mac OS X Big Sur with the newest version of Xmage of this date.

**Comment by JayDi85** [comment]
What's your xmage client version?

![shot_210110_100759](https://user-images.githubusercontent.com/8344157/104115729-c7758900-532b-11eb-906d-4b1b45a0afd6.png)

**Comment by JayDi85** [comment]
BTW, if you click on the other side (after transform button click) then you will play it without side choose dialog. If you can't play one side then you will play another side without side choose dialog.

So check your game logs -- you may play that land side immediately.

**Comment by LevelX2** [comment]
Had this also twice. Very irritating.

**Comment by forsureitsme** [comment]
Happenned to me in windows with 1.4.47V1 build

**Comment by brbcoffee** [comment]
occurred with glasspool mimic today (1.4.47V1 build). thank you for taking a look.

**Comment by The-Grand-Calcutron** [comment]
Can confirm. I'm also playing on 1.4.46V1. It occurred when Jace, Vryn's Prodigy was flipped in hand.

**Comment by THUNDERWANG** [comment]
Can confirm. I'm playing on 1.4.46V1 and it occurred when flipping Jace, Vryn's Prodigy in hand.

**Comment by JayDi85** [comment]
Improved by 5077a82585cf2757b24e94b9cefabd78d2655f9a
