### ISSUE TITLE
Cards with A and B images to download

### ISSUE THREAD

**Issue by fireshoes** [magefree/mage#739]
I uploaded Ertai, the Corrupted today. However the art is not downloading correctly for it. There are 2 different images available for it. On magiccards.info, they are card number 107a and 107b. I saw the split and flip cards use an a and b side also, so maybe Ertai could be integrated into that logic. I am not sure how to do that though.

Edit: I noticed myersn024's implementation of Skyship Weatherlight is also affected by this.

postby LevelX » 20 Feb 2015, 04:53
Yes, this cards have another artwork for the premium foil version of the card.

I guess it would be some work to get this going so you can select the one or the other. At least if you select the HQ image source, the normal image will be downloaded and used correctly.

Easier would probably be to make a workaround in magiccards.info downloader class to get only the "a" image, so you can also download from this source.

Best you add an issue about this enhancement to the github, so we don't loose track of it.

**Comment by LevelX2** [comment]
Fixed.
