### ISSUE TITLE
CMR - Can't play cards exiled by Opposition Agent after death

### ISSUE THREAD

**Issue by Danziir** [magefree/mage#7405]
I'm opening this issue because I haven't seen it mentioned anywhere, but you cannot play cards exiled by Opposition Agent if he is removed.
It's a bit of a weird rule, but it's explained in this reddit post, his ability continues to work even if he is removed. 
https://www.reddit.com/r/mtgrules/comments/jnda2c/two_questions_about_opposition_agent_from/ 
Thank you in advance.

**Comment by dosfod** [comment]
Hi, 

this is still happening.

Just a reminder.

Thanks

**Comment by dosfod** [comment]
Hi, 

any updates on this issue?

Thanks!!

**Comment by JayDi85** [comment]
Sorry, no news for it. Please, try new version later and report here -- is it actual or not.

**Comment by dosfod** [comment]
Will do, thanks!

**Comment by stevedavidmusic** [comment]
The bug is still happening

**Comment by spjspj** [comment]
Still happening  -- https://mtg.fandom.com/wiki/Ability

Pretty sure if they've been exiled by opp agent, even if that iteration of opp agent is no longer on the BF, you should still be able to cast the exiled cards.

113.7a Once activated or triggered, an ability exists on the stack independently of its source. Destruction or removal of the source after that time won’t affect the ability. yada yada

**Comment by jeffwadsworth** [comment]
[[Opposition Agent]]

**Comment by jeffwadsworth** [comment]
Fix for this coming soon.
