### ISSUE TITLE
Imoti, Belebrant of Bounty doesn't cascade when casting X spells with cmc 6 or greater on the stack

### ISSUE THREAD

**Issue by Minothilos** [magefree/mage#7409]
I have Imoti, Belebrant of Bounty out in a 4-player commander game and cast Finale of Devastation with X=9. Spell resolves without cascading.

**Comment by jeffwadsworth** [comment]
Ruling: For spells with Variable Colorless in their mana costs, use the value chosen for X to determine the spell’s converted mana cost.
