### ISSUE TITLE
Polukranos, Unchained + Release to the Wind

### ISSUE THREAD

**Issue by DominusMaximus** [magefree/mage#7415]
1.4.48.dev_2021-01-16_18-44

An opponent exiled my attacking Polukranos, Unchained with Release to the Wind. During the post-combat main phase, I was unable to cast Polukranos from exile. Clicking the card from the normal exile window or the Release to the Wind exile window would not allow me to cast it.

**Comment by weirddan455** [comment]
I can confirm this bug.  It doesn't have anything to do with Polukranos as far as I can tell.  I was unable to cast a Grizzly Bears after exiling with Release to the Wind.  I submitted PR #7416 as a potential fix to this.

**Comment by JayDi85** [comment]
Fixed by 2d96d36ec8c24344b6219e72fe68d1df24b8a773
