### ISSUE TITLE
Rielle, The Everwise + cycling + transmute (bug)

### ISSUE THREAD

**Issue by appleatingoat** [magefree/mage#7418]
Rielle doesn't work with cycling or transmute. I'm playing commander and Rielle is on the battlefield, I activate the transmute ability of Tolaria west (also tested with drift of phantasms). I fetch a card, but Rielle does not trigger or draw. The same thing happened when I cycled ash barrens and lonely sandbar. I fetched a land (or drew a card) but Rielle did not activate. I did not discard any other cards that turn. I played theses abilities on my opponents end step, and/or my main phase, respective to their activation limits.

**Comment by jeffwadsworth** [comment]
There is a report on this already.  https://github.com/magefree/mage/issues/7368

**Comment by JayDi85** [comment]
Fixed in #7436
