### ISSUE TITLE
Verazol, the Split Current not copying multikicker of Everflowing Chalice

### ISSUE THREAD

**Issue by marvinlenk** [magefree/mage#7431]
Today, on version 1.4.47V1, I had a game with Verazol and casted a multikicked Everflowing Chalice, which got copied but entered with zero counters. The original version entered with three counters. As far as I understand, Verazol should also copy the multikicker on the card.

**Comment by JayDi85** [comment]
Fixed by f38639e1db4bd1f972ad1063ed9db62f79a13206
