### ISSUE TITLE
Verazol, the Split Current doesn't copy ETB effects for kicked permanents.

### ISSUE THREAD

**Issue by Necamijat** [magefree/mage#7433]
When casting a kicked permanent spell, and using Verizol's triggered ability to copy it, the copied permanent does not count as kicked for its ETB effects Replacement effects still apply.

**Comment by JayDi85** [comment]
Related to #7431

**Comment by JayDi85** [comment]
Fixed by f38639e1db4bd1f972ad1063ed9db62f79a13206
