### ISSUE TITLE
Inkwell Leviathan Unblockable even without controlling Islands

### ISSUE THREAD

**Issue by Pandosity** [magefree/mage#7435]
Pretty much what the title says: trying to block Inkwell Leviathan just caused me to pop up the error message "This creature can't be blocked" even though I controlled no islands. For reference, my opponent did control Islands, I had an island in my graveyard and an animated Lumbering Falls. I also had a Gaea's cradle and a Mox Diamond, in case that is connected.

Good luck debugging,

Panda

**Comment by jeffwadsworth** [comment]
Probably related to #7323

**Comment by theelk801** [comment]
fixed with 5f80dba
