### ISSUE TITLE
Foretold cards that have been returned from graveyard to hand still allow you to pay Foretell cost

### ISSUE THREAD

**Issue by weirddan455** [magefree/mage#7442]
To reproduce:

1. Foretell a card (ex. Behold the Multiverse)
2. On your next turn, cast the Foretold card from exile.
3. Return the card from your graveyard to your hand (ex. with Recollect)
4. Cast the card from your hand.  It gives you the option to pay the Foretell cost when you should have to pay the card's normal cost.

**Comment by jeffwadsworth** [comment]
2 birds with one stone in regards to the 2 bugs.
