### ISSUE TITLE
Expansion Copying Expansion Stack

### ISSUE THREAD

**Issue by DominusMaximus** [magefree/mage#7443]
1.4.48.dev_2021-01-16_18-44

My question concerns the infinite combo with Ral, Storm Conduit and two Expansions. In the GIF below I've targeted the black creature with the blue instant. I then target that instant with an Expansion in order to copy it. With Expansion still on the stack, I cast a 2nd Expansion in order to copy the 1st one. I allow the 2nd Expansion to resolve. At this point is where my question is. Why is the image of the 2nd Expansion still visible on the stack once it resolves and the copy is created? As you can see, there are now 3 Expansion images visible on the stack. Once the 2nd Expansion resolves (copying the 1st one), shouldn't that card image be immediately removed from the stack? I bring this up since, when the client requests a target for the Expansion copy (the 3rd Expansion image), the client is considering that resolved Expansion (the middle one) to be a legal target for the copy. I demonstrate this in the 2nd loop of the infinite by picking that middle Expansion image. The loop understandably ends since that middle Expansion should no longer even be on the stack. Am I understanding this correctly?

![expansion on stack](https://user-images.githubusercontent.com/21368033/105650927-626d7780-5e83-11eb-8e32-56f0ebe1c3b7.gif)

**Comment by emerald000** [comment]
The 2nd expansion is only removed from the stack once it has finished resolved. You to make the copy and choose its new target before it fully resolves. From what I can see, this happens correctly in your GIF.

**Comment by DominusMaximus** [comment]
> 
> 
> The 2nd expansion is only removed from the stack once it has finished resolved. You have to make the copy and choose its new target before it fully resolves. From what I can see, this happens correctly in your GIF.

I understand what you're saying, but shouldn't the client prevent you from choosing that middle image? Expansion requires a spell as a legal target. How can the copy choose the Expansion that created it?

**Comment by emerald000** [comment]
I agree it is weird, but it is still a spell on stack and can be chosen as a valid target. You probably don't want to, but you are allowed to.

**Comment by DominusMaximus** [comment]
> 
> 
> I agree it is weird, but it is still a spell on stack and can be chosen as a valid target. You probably don't want to, but you are allowed to.

I just watched a video of the combo being performed on Arena, and you're right, the copy is allowed to target the 2nd Expansion. Thanks for the clarification.
