### ISSUE TITLE
Brutal Hordechief activation doesn't work

### ISSUE THREAD

**Issue by DrP3nda** [magefree/mage#745]
Brutal Hordechief's activated ability that allows the player that controls Brutal Hordechief to make all the opponent's creatures block and choose blockers doesn't work.  I've had 2 opponents activate the ability and when it goes to blockers I'm still able to select a blocker and choose which creature it blocks.

**Comment by blistering12** [comment]
Can confirm.

**Comment by fireshoes** [comment]
Fixed beyond v6.
