### ISSUE TITLE
Error: null Popup

### ISSUE THREAD

**Issue by DominusMaximus** [magefree/mage#7455]
1.4.48.dev_2021-01-27_06-35

![aura draw bug](https://user-images.githubusercontent.com/21368033/106019887-23147600-6091-11eb-8359-4319862b5f48.png)

On that turn I attached Curious Obsession and Sixth Sense to the Bronzehide Lion. The window pops up as soon as the damage is dealt. No cards are drawn. Something odd is that on a previous turn I had attacked and drawn without issue (with 2 auras attached). After getting this error, I wasn't able to reproduce that even with rollbacks.

**Comment by JayDi85** [comment]
Look at client and server logs for more info (it must contains full error message and logs):
* `..\xmage\mage-client\mageclient.log`
* `..\xmage\mage-server\mageserver.log`

If that files too big then you can delete that files, run game again to repeat the error and open logs with text editor.

**Comment by DominusMaximus** [comment]
In this game the error occurred as soon as I attached a third aura to the creature _before_ attacking. I was able to attack and draw without error several times while it had two auras. 

[01.txt](https://github.com/magefree/mage/files/5882987/01.txt)

In this game the error occurred after dealing damage with a creature that had three auras attached to it.

[02.txt](https://github.com/magefree/mage/files/5883018/02.txt)

**Comment by JayDi85** [comment]
Fixed in last beta build. If you catch new error then report a new issue with it.
