### ISSUE TITLE
Kardur, Doomscourge does not force creatures to attack and attacking creatures that die do not trigger the drain effect

### ISSUE THREAD

**Issue by varaghar** [magefree/mage#7456]
Hello, I tried testing the new Kardur, Doomscourge implementation.

Scenario 1:
Opponent controls 2x Goblin Guide.
I cast Kardur, Doomscourge and pass turn.
Next turn the Goblin Guides controlled by my opponent don't attack me.
https://imgur.com/a/Q0q9L2b

Scenario 2:
Opponent controls 2x Goblin Rabblemaster.
I control Kardur, Doomscourge.
On opponents turn it declares 4 attackers. 
I bolt a Rabblemaster. Rabblemaster dies without a new drain trigger from Kardur. 
I cast Divine Verdict on a goblin token. Goblin token dies without a new drain trigger from Kardur. 
I block the remaining Rabblemaster with Kardur and they both die without a trigger.
https://imgur.com/a/pUSdX7f

**Comment by Alex-Vasile** [comment]
This was fixed in https://github.com/magefree/mage/commit/43dbaf405b9bae3cc54772345db10d5c1aa79eec
