### ISSUE TITLE
attack arrow out of alignment 

### ISSUE THREAD

**Issue by copperfield42** [magefree/mage#7457]
![006 flechas desalineadas](https://user-images.githubusercontent.com/4504719/106087968-6d324180-60fb-11eb-852b-fae93c52a0c3.PNG)
![006 flechas desalineadas 2](https://user-images.githubusercontent.com/4504719/106182019-af4b9980-6174-11eb-847b-11f6151e2d45.PNG)
![006 flechas desalineadas 3](https://user-images.githubusercontent.com/4504719/106182069-bd011f00-6174-11eb-8b70-33565a630200.PNG)

the first 2 from the same game, in the other I also notice an bunch of 

```
ERROR 2021-01-28 14:02:24,296 Bad &...; sequence `mdash If ` in rule.                                                    =>[AWT-EventQueue-0] TextboxRuleParser.parse 
```
in the client console log that goes on forever

[full client console log.txt](https://github.com/magefree/mage/files/5889383/006.flechas.desalineadas.-.client.console.log.txt)

**Comment by JayDi85** [comment]
Wrong blocker arrows, wrong card texts and redundant logs fixed in newest beta build.

**Comment by copperfield42** [comment]
cool, I look forward to it :)
