### ISSUE TITLE
Pre-2018 Sets Missing Card Requests

### ISSUE THREAD

**Issue by kmcgeejr** [magefree/mage#7459]
Hello! I am currently working through converting all Magic theme decks into XMage Deck files, but some of the older cards are missing. My plan is to keep all my requests for missing cards I come across in this thread, but if I need to split them up, just let me know.

Mirage:
 - Dream Fighter (Done)
 - Meddle (Done)
 - Wall of Corpses (Done)

I was told on Discord that Dream Fighter and Meddle were already being implemented.

**Comment by kmcgeejr** [comment]
Shadowbane (from Mirage) is also missing.

**Comment by kmcgeejr** [comment]
Ekundu Cyclops (from Mirage) is also missing.

**Comment by kmcgeejr** [comment]
Sealed Fate (from Mirage) is also missing.

**Comment by kmcgeejr** [comment]
Ogre Enforcer (from Visions) and Unerring Sling (from Mirage) is also missing.

**Comment by kmcgeejr** [comment]
Ertai's Meddling (from Tempest) is also missing.

**Comment by jeffwadsworth** [comment]
Levelx2 had painstakingly put up card lists of many sets in the past.  I did a few but many are so bad and just downright silly that I couldn’t stay motivated to finish them.   The card designers from 20+ years ago sucked.

**Comment by kmcgeejr** [comment]
> 
> 
> Levelx2 had painstakingly put up card lists of many sets in the past. I did a few but many are so bad and just downright silly that I couldn’t stay motivated to finish them. The card designers from 20+ years ago sucked.

I don't disagree - not looking to complete EVERYTHING myself, just what is required for these theme decks.

**Comment by jbureau-qc** [comment]
reflect damage is also missing from Mirage

**Comment by jeffwadsworth** [comment]
https://github.com/magefree/mage/issues?q=implementation+tracker

**Comment by brusil30** [comment]
Can you please add the cards?
Bargaining Table from Mercadian Masques
Chromatic Armor from Ice Age

**Comment by kmcgeejr** [comment]
Zombie Boa (from Apocalypse) is also missing.

**Comment by kmcgeejr** [comment]
Emblazoned Golem (from Apocalypse), and Captain's Maneuver (also from Apocalypse) are missing.

**Comment by kmcgeejr** [comment]
Carrion Rats (from Torment) is also missing.

**Comment by kmcgeejr** [comment]
Carrion Wurm (from Torment) is also missing.

**Comment by kmcgeejr** [comment]
Flaming Gambit (from Torment) is missing.

**Comment by kmcgeejr** [comment]
Crown of Suspicion (from Onslaught) is also missing.

**Comment by kmcgeejr** [comment]
Quick question - How do we go about getting card images for newly implemented cards? I tried re-running the "Images" button, but it didn't find "Meddle".

**Comment by kmcgeejr** [comment]
Crown of Vigor (from Onslaught) is also missing.

**Comment by kmcgeejr** [comment]
Rock Jockey (from Scourge) is also missing.

**Comment by kmcgeejr** [comment]
This one is odd - Skirk Commando seems to be implemented, but only the Archenemy Version. The Onslaught version does not appear.

**Comment by JayDi85** [comment]
@kmcgeejr

Add here only most wanted cards. There are a special unit test in Verify to show all missing/unimplemented cards, so devs can find missing cards automatically.

**Comment by kmcgeejr** [comment]
That is what I'm doing - I made my goals clear at the beginning of the thread. I'm putting together all the official theme decks, and each card I mention here is missing from one of those theme decks.

**Comment by JayDi85** [comment]
Meddle implemented in Mirage and Onslaught sets. You must see that card in Deck Editor. If you see it then go to images dialog and download Mirage set from scryfall. Restart xmage to apply images (sometimes its necessary to see the image).

**Comment by kmcgeejr** [comment]
RE: Meddle - the restart took care of it. Thanks!

**Comment by kmcgeejr** [comment]
Orochi Eggwatcher // Shidako, Broodmistress (From Champions of Kamigawa) is missing.

**Comment by kmcgeejr** [comment]
Bushi Tenderfoot // Kenzo the Hardhearted (from Champions of Kamigawa) is missing.

**Comment by kmcgeejr** [comment]
Initiate of Blood // Goka the Unjust (from Champions of Kamigawa) is missing.

**Comment by kmcgeejr** [comment]
Student of Elements // Tobita, Master of Winds (from Champions of Kamigawa) is missing. (Are all the "flip" cards missing?)

**Comment by kmcgeejr** [comment]
Nezumi Graverobber // Nighteyes the Desecrator (from Betrayers of Kamigawa) is missing.

**Comment by kmcgeejr** [comment]
Budoka Pupil // Ichiga, Who Topples Oaks and  Faithful Squire // Kaiso, Memory of Loyalty (both from Betrayers of Kamigawa) are missing.

**Comment by kmcgeejr** [comment]
Rune-Tail, Kitsune Ascendant // Rune-Tail's Essence (from Saviors of Kamigawa) is missing.

**Comment by Grath** [comment]
None of these are missing, they're just listed under the non-flipped card name.

**Comment by kmcgeejr** [comment]
That explains why the text import didn't work. Thanks!

**Comment by kmcgeejr** [comment]
Kjeldoran Elite Guard (from Ice Age and Coldsnap theme Decks) and Scars of the Veteran (from Ice Age and Coldsnap Theme Decks) are both missing.

**Comment by JayDi85** [comment]
If import can't find existing card then there are bug possible and it must be fixed. Please make bug report with examples.

**Comment by kmcgeejr** [comment]
The import didn't recognize the card name with both names on the same line, separated by a slash (as I was posting them here). Not sure if that's a bug or not?

**Comment by JayDi85** [comment]
Well, xmage can be improved to support left card names searching in import. Related issue #7723

**Comment by kmcgeejr** [comment]
Orcish Conscripts (from Ice Age) is missing.

**Comment by Akira4712** [comment]
The cards from Ikoria with the mutate mechanic are missing, I tried making a mutate deck, but there doesn't seem to be any cards with the mutate mechanic from Ikoria added.

**Comment by Grath** [comment]
@Akira4712 The Mutate cards are all (or almost all) implemented, but the mutate mechanic itself is not yet possible in XMage.

**Comment by kmcgeejr** [comment]
I cannot find "Assault//Battery" from the Planechase set, though it is implemented in two other sets.

**Comment by Alex-Vasile** [comment]
All cards mentioned above.
**Unimplemented**
- [ ] Shadowbane (from Mirage)
- [ ] Ekundu Cyclops (from Mirage)
- [ ] Ogre Enforcer (from Visions)
- [ ] Ertai's Meddling (from Tempest)
- [ ] Reflect Damage
- [ ] Bargaining Table from Mercadian Masques
- [ ] Chromatic Armor from Ice Age
- [ ] Emblazoned Golem (from Apocalypse)
- [ ] Carrion Rats
- [ ] Carrion Wurm
- [ ] Flaming Gambit
- [ ] Crown of Suspicion
- [ ] Crown of Vigor
- [ ] Rock Jockey
- [ ] Kjeldoran Elite Guard
- [ ] Arcum's Weathervane
- [ ] Orcish Conscripts

**Implemented**
- [x] Assault // Battery
- [x] Skirk Commando
- [x] Zombie Boa

**Comment by TheFrogster** [comment]
cemetery illuminator from crimson vow seems to be missing

**Comment by stevedavidmusic** [comment]
Comet, Stellar Pup from Unfinity if there aren't any technical hurdles.

Thanks!

**Comment by TheFrogster** [comment]
Comet, Stellar Pup from Unfinity if there aren't any technical hurdles.

Message ID: ***@***.***>

think you got the wrong adress homie. ive requested a card on some page once, thats the only relation i have to this.

greetings

**Comment by VinylNix** [comment]
Will it be possible for Gluntch, the Bestower to be added in the near future?

**Comment by lLennardl** [comment]
Runadi, Behemoth Caller from jumpstart 2022 is missing :)

**Comment by vascooooo** [comment]
Any chance we can get Triumph of Saint Katherine and Comet, Stellar Pup?
Many thanks!

**Comment by TragicJo** [comment]
Jon irenicus from CLB and exchange of words from unfinity are missing, is it possible to add them.
Thanks a lot regardless :)

**Comment by Grath** [comment]
I would anticipate that Exchange of Words is completely impossible in XMage at this time, and Jon Irenicus won't work right until the work in #9586 is finished.

**Comment by VinylNix** [comment]
Has gluntch made the cut

**Comment by evandsokol** [comment]
Would like to request Anrakyr the Traveller, thanks!

**Comment by Susucre** [comment]
@evandsokol this issue is for requesting old cards that might not have a per-set Issue.
Newer sets all have one, for 40K it is https://github.com/magefree/mage/issues/8954.
