### ISSUE TITLE
Question: How to create new server plugins

### ISSUE THREAD

**Issue by JRHerlehy** [magefree/mage#746]
I'm interested in trying to add some new plugins to the server for different match types.  So far I've got another project set up (Like how commander has different projects for FFA and Duel) and some of the initial code work done.  However, once I add it the the config.xml file of the server, it always gets a null pointer exception for pointing to the jar file in "<project root>/mage.server/plugins" which doesn't exist.  Looking through all the project properties for my project vs other projects doesn't yield any help.

Why is this jar file having issues loading vs other plug in jars in the build environment?

**Comment by LevelX2** [comment]
Hard to say what's the problem without doing it myself.

**Comment by JRHerlehy** [comment]
Well, I feel dumb.  In all my going over the source files, it took me a week to notice that the class it was balking at wasn't made public.  Something you are so used to and yet so easy to miss.

This is solved.
