### ISSUE TITLE
Treasure Cove Draw

### ISSUE THREAD

**Issue by DominusMaximus** [magefree/mage#7460]
1.4.48.dev_2021-01-28_02-42

A card isn't drawn when sacrificing a Treasure to Treasure Cove's draw ability (the transformed side of Treasure Map).

**Comment by JayDi85** [comment]
Can you explain? Transformed card is fine.

Example with Arlinn Kord:
![shot_210129_090256](https://user-images.githubusercontent.com/8344157/106233890-0141fd00-6211-11eb-90e6-250006a14887.png)
![shot_210129_090310](https://user-images.githubusercontent.com/8344157/106233900-04d58400-6211-11eb-95b3-8a81a08aa62f.png)

Example with Treasure Map:
![shot_210129_084843](https://user-images.githubusercontent.com/8344157/106233948-1d459e80-6211-11eb-946b-858c501d55bd.png)

**Comment by JayDi85** [comment]
Argh, it's about a draw ability. I can confirm that bug.

**Comment by JayDi85** [comment]
Empty stack drawing fixed in newest beta build.
