### ISSUE TITLE
[KHM] Tergrid, God of Fright // Tergrid's Lantern is not castable from command zone

### ISSUE THREAD

**Issue by NicholasRage89** [magefree/mage#7462]
Neither side of this card is castable from the command zone, and one side shows both casting costs in the UI:

![tergrid](https://user-images.githubusercontent.com/78192399/106232707-a41f5a80-61c2-11eb-87a1-8a517dc59231.JPG)

**Comment by NicholasRage89** [comment]
Note- The card can be cast with the sum total of the mana cost (9cmc- 6bbb), though you can only cast the creature side

**Comment by veloper** [comment]
Note - Also, when you try to use the commander using a `commander free for all / variant magic - commander` game you're prompted with an "illegal commander" dialog. 
![Screen Shot 2021-01-30 at 12 48 32 PM](https://user-images.githubusercontent.com/340358/106363927-86084600-62f9-11eb-9c91-dbf8bdbb228b.png)

**Comment by JayDi85** [comment]
Fixed by Fixed by 50e5809a791bb29944fd772406d8cc3eaa7f0478
