### ISSUE TITLE
[KHM] Vorinclex, Monstrous Raider no longer doubles counters of Planeswalkers on ETB

### ISSUE THREAD

**Issue by Xhael** [magefree/mage#7463]
Apparently Vorinclex was changed in one of the most recent updates and now the counters of Planeswalkers are no longer doubled upon entering the battlefield. I tried this interaction via playing them from my library (through Sisay, Weatherlight Captain), with Vorinclex on the battlefield, as well as flickering planeswalkers with him on the battlefield. In both cases the amount of counters on those planeswalkers were unchanged. Vorinclex, Monstrous Raider only doubled counters upon using one of their +1/+2 etc. abilities.

**Comment by JayDi85** [comment]
What's your app version? Current release or beta.

**Comment by Xhael** [comment]
Beta

**Comment by JayDi85** [comment]
Fixed by 91bac931b720e3bfb4933dc58cc6608624f0267c
