### ISSUE TITLE
Bug: Can not pick a flipped card during a draft

### ISSUE THREAD

**Issue by THUNDERWANG** [magefree/mage#7472]
If a double-faced card is flipped during the draft, the player can not select the card. They have to flip the card back to the front to select it. In the following picture, if I try to select the back side of the card, xmage will generate the "pick sound", but not actually give me the card. 
![pathway](https://user-images.githubusercontent.com/59207918/106369201-3da25580-6304-11eb-8bfc-81586cfbb190.PNG)

**Comment by JayDi85** [comment]
Fixed by be77ecea849329f71a95eb711e293f0bdece8fb2
