### ISSUE TITLE
Game exception with Repeated Reverberation

### ISSUE THREAD

**Issue by Lepmim** [magefree/mage#7474]
Casted RepeatedReverberation and copied it on the stack with Fork. After all that resolved tried to cast Sensei's Divining Top then the error occured.

Game exception occurred: java.lang.ClassCastException: mage.game.stack.Spell cannot be cast to mage.game.stack.StackAbility
Server version: 1.4.48V0-beta9 (build: 2021-01-30 13:53)
mage.cards.r.RepeatedReverberationTriggeredAbility.checkTrigger(RepeatedReverberation.java:85)
mage.abilities.DelayedTriggeredAbilities.checkTriggers(DelayedTriggeredAbilities.java:39)
mage.game.GameState.handleEvent(GameState.java:759)
mage.game.GameImpl.fireEvent(GameImpl.java:2794)
mage.players.PlayerImpl.cast(PlayerImpl.java:1207)
mage.players.PlayerImpl.activateAbility(PlayerImpl.java:1459)
mage.player.human.HumanPlayer.activateAbility(HumanPlayer.java:1940)
mage.player.human.HumanPlayer.activateAbility(HumanPlayer.java:1963)
mage.player.human.HumanPlayer.priority(HumanPlayer.java:1094)
mage.game.GameImpl.playPriority(GameImpl.java:1358)
mage.game.turn.Step.priority(Step.java:61)
mage.game.turn.Phase.playStep(Phase.java:184)
mage.game.turn.Phase.play(Phase.java:89)
mage.game.turn.Turn.play(Turn.java:128)
mage.game.GameImpl.playTurn(GameImpl.java:897)
mage.game.GameImpl.play(GameImpl.java:809)
mage.game.GameImpl.start(GameImpl.java:794)
mage.server.game.GameWorker.call(GameWorker.java:34)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)

**Comment by JayDi85** [comment]
Fixed by c03279d835e03485de641b68bdfe6486ed47e073
