### ISSUE TITLE
Launcher issues

### ISSUE THREAD

**Issue by ldeluigi** [magefree/mage#7476]
Here's a couple XMage Launcher issues I ran into today:
1. Didn't find the updated source repository
1. In the settings menu, the custom branch name for the beta should be xmage.today, instead of rg.me/xmage

Furthermore, if the repo is public, I'd like too see the link placed in the main README too.

**Comment by JayDi85** [comment]
Yeah, launcher is outdated and must be updated someday. As example: 
* it must be packed as zip package with run-launcher script (windows 10 users can't run launcher from jar) -- see [beta client package](http://xmage.today/); 
* option to use system java instead inner (#6462);
* update default settings, button for settings reset (#5645);
* additional errors checks like read only folders, unsupported symbols in the path, run from download folder, updating while client/server running, etc (#4301, #6859);

Launcher source can be found in another org repository: https://github.com/magefree/Launcher

**Comment by ldeluigi** [comment]
I'll see what I can do ; )

**Comment by ldeluigi** [comment]
https://github.com/magefree/Launcher/pull/14
