### ISSUE TITLE
Construced_Decks_are_always_having_errors

### ISSUE THREAD

**Issue by Benomat187** [magefree/mage#7479]
We have an issue that creating a construced game is not working because the Error Message appears, which says for example: 

Server error: _Card not found - Heartless Act - IKO/366 for deck - null Possible reason is, that you use cards in your deck, that are only supported in newer versions of the server. So it can help to use the same card from another set, that's already supported from this server._  

But Heartless Act is a card which is only printed once.....so something is wrong, and we cant play some new decks 
:(

**Comment by jeffwadsworth** [comment]
What is the version number of your client and server?  That card should be several months old.

**Comment by JayDi85** [comment]
Thats error about server restart. If you played on beta then it restarted.
