### ISSUE TITLE
Vengeful Pharaoh -> multiple triggers

### ISSUE THREAD

**Issue by Blitkun** [magefree/mage#748]
Vengeful Pharaoh's triggered ability should trigger (from the graveyard) whenever a creature deals combat damage to its controller - and while this is done correctly, the resolution only applies to the first creature, as the Pharaoh is put onto the top of its owner's library. Ruling:

9/22/2011: If multiple creatures deal combat damage to you and to a planeswalker you control simultaneously, Vengeful Pharaoh will trigger twice. The first trigger will cause Vengeful Pharaoh to be put on top of your library. The second trigger will then do nothing, as Vengeful Pharaoh is no longer in your graveyard when it tries to resolve. Note that the second trigger will do nothing even if Vengeful Pharaoh is put back into your graveyard before it tries to resolve, as it's a different Vengeful Pharaoh than the one that was there before.

However, Pharaoh's ability currently resolves for EACH creature that dealt damage - meaning it is literally a one-sided sweeper as of now. The ability SHOULD trigger multiple times, but only the first resolution should REALLY destroy the creature. With that in mind, Pharaoh's ability is currently bugged.

**Comment by LevelX2** [comment]
fixed.
