### ISSUE TITLE
Tergrid casting cost

### ISSUE THREAD

**Issue by anf123** [magefree/mage#7481]
When attempting to summon Tergrid from the command zone, the cost is equal to her creature and artifact cost. So, instead of being 3 colorless and 2 black, she is  3 colorless, 3 colorless and 3 black. Hoping to see this fixed soon :)
![Screenshot 4](https://user-images.githubusercontent.com/78388855/106539156-13e35d00-64c3-11eb-8b24-638eb21fb106.png)

**Comment by JayDi85** [comment]
Related to #7370
