### ISSUE TITLE
[KHM] Esika can't be chosen as a commander for 5-color deck

### ISSUE THREAD

**Issue by dosfod** [magefree/mage#7483]
Hi, 

I'd like to report that I can't chose Esika as a commander for a 5-color deck. While I try to create a Commander game with her as the Commander a pop-up appears with multiple errors. I think that somehow the identity of Esika is green, not rainbow... Attached screenshots with the pop-up and the deck:

<img width="502" alt="image" src="https://user-images.githubusercontent.com/29545637/106631643-3afe6500-657d-11eb-94d2-3bc939fd3858.png">

<img width="1069" alt="image" src="https://user-images.githubusercontent.com/29545637/106631791-641ef580-657d-11eb-9116-bb321bab537e.png">

I guess this bug could affect other MDFC legends.

Please, let me know if you have any doubts.

Kind regards

**Comment by JayDi85** [comment]
Fixed in 31d134843a0851ad7acefd33595efe67261e7a0e

**Comment by dosfod** [comment]
Nice then :) Is that version released already to Beta Server?

**Comment by JayDi85** [comment]
I update beta in 15 minutes.

**Comment by dosfod** [comment]
Great, thanks :) Keep up the good work, great fan of the project here
