### ISSUE TITLE
[KHM] Can't cast MDFC Commanders while AI can

### ISSUE THREAD

**Issue by dosfod** [magefree/mage#7485]
Hi, 

I am unable to cast MDFC Commanders from the Command zone, but the IA seems to be able. It is weird, first it happened to me with Esika and I reproduced it with Tergrid, so I guess it happens with all of them. 

For test purposes I created a deck with only lands and Tergrid as the Commander and created a match with 2 IAs. As shown in the attached screenshot, both IAs are able to cast the second part of the card while I can't cast any:

<img width="1019" alt="image" src="https://user-images.githubusercontent.com/29545637/106654642-adc90980-6598-11eb-9c02-099f0149e7d5.png">

The UI indicates that I can cast it (the frame is bordered in purple), but when I click on the card nothing happens. 

Let me know if you need more information.

Thanks in advance, 

Kind regards.

**Comment by JayDi85** [comment]
Fixed by cc03cbbb6746b070f3c9128d7bd3c8b84ef9fcd8
