### ISSUE TITLE
yawgmoths will.

### ISSUE THREAD

**Issue by ignitaxiom** [magefree/mage#7490]
i cast yawgmoths will, cast a card from my graveyard and my entire hand and gy get exiled.

**Comment by weirddan455** [comment]
Not able to reproduce this.  Need more information about what was on the battlefield and what you were trying to cast.

**Comment by copperfield42** [comment]
it might be related to #6738

**Comment by JayDi85** [comment]
Cards disappear can be fixed in #6738
