### ISSUE TITLE
Bug: KDH Draft Booster are compiled wrong

### ISSUE THREAD

**Issue by Don-Cruz** [magefree/mage#7492]
Some draft packs do not contain any land.
All packs should include at least one snow land: a basic snow or a snow double land.
Double lands do not appear at all.
The boosters have too few cards. There are only nine commons instead of ten, sometimes the land slot is empty.
Example of a fresh pack:
![grafik](https://user-images.githubusercontent.com/78379079/106756690-cfc19b00-662f-11eb-950c-0b8360ac91d3.png)

**Comment by JayDi85** [comment]
@theelk801 saw discord report what it sill miss snow or dual lands in some boosters:

> Hi, congrats to the release today. I did my first draft and in some packs no snow lands or basic lands showed up.

**Comment by theelk801** [comment]
I'll look into it

**Comment by JayDi85** [comment]
Related issue #7521

**Comment by theelk801** [comment]
gonna close this one then
