### ISSUE TITLE
[KHM] Tergrid, God of Fright is not castable from the command zone

### ISSUE THREAD

**Issue by NicholasRage89** [magefree/mage#7496]
![image](https://user-images.githubusercontent.com/78192399/106839562-7166dd80-666c-11eb-96cf-7338cb47f7d2.png)

**Comment by NicholasRage89** [comment]
Tergrid (and possibly other MFDC legendaries) are not castable from the command zone. They appear with the purple "castable" aura, but do nothing when clicked.

Tegrid _seems_ castable now, which is an improvement from previously, but even with 9 open mana, she (or her opposite side) cannot be cast.

**Comment by JayDi85** [comment]
Fixed in #7489 by cc03cbbb6746b070f3c9128d7bd3c8b84ef9fcd8, beta updated too.
