### ISSUE TITLE
Flashback split cards with Snapcaster Mage are duplicated in GUI

### ISSUE THREAD

**Issue by weirddan455** [magefree/mage#7500]
I think this is due to the following workaround somehow applying twice.  I had the same thing happen when I was testing my Foretell fix in PR #7498.  I first tried using this workaround on Foretell until I found a better solution (which resolved GUI duplication.)

I'm wondering if we can have Snapcaster Mage just add the Flashback ability to split cards in the Snapcaster Mage code and remove this workaround (or are there other cards that depend on this?)

https://github.com/magefree/mage/blob/bc99de1a480c4cb629c1085ce9314bfb339b09ad/Mage/src/main/java/mage/cards/CardImpl.java#L265-L279

![flashback](https://user-images.githubusercontent.com/8128047/106928766-259e4d80-66d9-11eb-964e-d4e6568f2c9c.jpg)

**Comment by JayDi85** [comment]
or are there other cards that depend on this

Flashback ability added to main card all the around. Search by `= new FlashbackAbility(`.

Duplicated abilities list in split cards were fixed by 0de71e03488f85eaef6333d96b3f3c3dc861ad14

**Comment by weirddan455** [comment]
OK.  I guess we can close this since you fixed the issue.
