### ISSUE TITLE
Omenkeel bug in Commander games

### ISSUE THREAD

**Issue by ignitaxiom** [magefree/mage#7503]
omenkeel triggers twice when it hits an opponent, exiling 6 cards instead of 3.

**Comment by weirddan455** [comment]
Not able to reproduce this.  I'm only seeing 3 exiled cards.  Omenkeel does trigger " Whenever a Vehicle you control deals combat damage to a player", not just off itself.  Was there another vehicle attacking?

**Comment by ignitaxiom** [comment]
just onemkeel. i'll try it again


________________________________

**Comment by ignitaxiom** [comment]
all of the mdfc commanders seem to trigger twice

**Comment by weirddan455** [comment]
Oh, you didn't mention it was in commander.  Probably related to #7501

**Comment by JayDi85** [comment]
Fixed by ac98a3a31ae96372302a71f9dc737ae5e4522c07
