### ISSUE TITLE
cosima

### ISSUE THREAD

**Issue by ignitaxiom** [magefree/mage#7504]
didn't ask me to put cosima back in the command zone when killed. just went straight to the graveyard.

**Comment by ignitaxiom** [comment]
just doesn't appear to recognize cosima as my commander at all. i.e can't cast fierce guardianship for free.

**Comment by JayDi85** [comment]
Commanders "die" dialog works fine. Fierce Guardianship and other cards affected by commanders on battlefield fixed by dc0a29007cce6b54d316d9adcc48971cd7acb607
