### ISSUE TITLE
Card Not Found Error (Beta Server)

### ISSUE THREAD

**Issue by J164** [magefree/mage#7508]
![image](https://user-images.githubusercontent.com/43323130/107123706-9f167700-6864-11eb-978a-902a7396a5bf.png)
![image](https://user-images.githubusercontent.com/43323130/107123711-a473c180-6864-11eb-9f07-5bc1225bc4cb.png)
![image](https://user-images.githubusercontent.com/43323130/107123717-ad649300-6864-11eb-9974-29b08c27a0cd.png)

One of the decks I tried to use has Kaldheim cards in it but the other two do not and work on the regular servers.

This only happens on the public beta server. Local server works fine

**Comment by JayDi85** [comment]
Server restarted
