### ISSUE TITLE
Some card requests

### ISSUE THREAD

**Issue by Zorkony** [magefree/mage#751]
I was just wondering if it was possible to consider adding the following cards?

- Fatespinner
- False prophet
- Blazing Archon
- Sen Triplets (I know this one isn't easy :( )

**Comment by jeffwadsworth** [comment]
The best time frame we can give is “when it gets done”.  Please use the card request forum here and thanks for using XMage:

http://www.slightlymagic.net/forum/viewtopic.php?f=70&t=4554
