### ISSUE TITLE
XMage Client could not open after updating (broken java jvm.cfg)

### ISSUE THREAD

**Issue by JolKael** [magefree/mage#7518]
My client did not start. The console shows this message:
"Error: could not open `D:\Program Files\java\jre1.8.0_201\lib\amd64\jvm.cfg'

Tried updating my Java separately, and then rerunning the XMage launcher. First updating issue since last year.

Sorry if this isn't the right place to raise this issue. Appreciate all help!

**Comment by JayDi85** [comment]
Instructions to fix java:
https://github.com/magefree/mage/issues/1272#issuecomment-529789018
