### ISSUE TITLE
hero of bretagard

### ISSUE THREAD

**Issue by ignitaxiom** [magefree/mage#7520]
when permanents are exiled put "that many" counters on it. so exiling 5 things at once should put 5 counters on it, not one.

**Comment by jeffwadsworth** [comment]
What card did you use to exile the permanents on the battlefield?  It is important that the card is exiling the permanents all at once.

**Comment by weirddan455** [comment]
@jeffwadsworth I was just taking a look at this.  The triggered ability is always passing "1" to the effect.

https://github.com/magefree/mage/blob/10306787e26808bb580dd5b5c1bd5834725907e9/Mage.Sets/src/mage/cards/h/HeroOfBretagard.java#L120

**Comment by weirddan455** [comment]
Although, I just tested with Yorion.  I flickered 3 creatures and it did get 3 counters (though it created 3 triggers which I'm not sure is correct or not.)

**Comment by jeffwadsworth** [comment]
@weirddan455 Yes, I know about that, but, it is also important to fix any cards not exiling everything at once.  I will fix the issue once I note the card used.
