### ISSUE TITLE
KHM Snow Dual Lands in Draft

### ISSUE THREAD

**Issue by MilkManJ** [magefree/mage#7521]
Hello,

Thanks for all you do, you are appreciated. I did a handful of drafts last night and I believe the packs to be collated incorrectly with regards to the snow dual lands in each pack. If this has been addressed I am so sorry. If I can help any further please let me know.

thank you,
Jespen

**Comment by weirddan455** [comment]
There's not a snow dual in every pack.  You get either a snow dual or a snow basic.  What did you find that's incorrect?

**Comment by MilkManJ** [comment]
I understand there isn’t a snow dual in every pack, apologies for not being clearer. In about ten drafts I saw zero snow duals in packs and in game. Also there are basic non-snow lands that show up in some draft packs that don’t show up in irl draft boosters. https://magic.wizards.com/en/articles/archive/feature/kaldheim-product-overview-2021-01-25

Thanks for your help and time,
J

**Comment by JayDi85** [comment]
BTW you can test booster drafts in deck editor:
* choose only one set (KHM) from the filter;
* press booster button in main panel;
* it adds cards from one booster;
* clear cards list and repeat.

**Comment by weirddan455** [comment]
@JayDi85 The "open booster" button?  I'm curious why there's a "CURRENTLY NOT WORKING" message on it but if this is correct data, I opened a basic Plains in my first booster which would be incorrect (the land slot in KHM boosters should be snow lands only.)
![booster](https://user-images.githubusercontent.com/8128047/107239922-f6e0e980-69ee-11eb-9a2e-c26a029372a7.jpg)
