### ISSUE TITLE
This is a wierd one (hand disappear in AI games)

### ISSUE THREAD

**Issue by ignitaxiom** [magefree/mage#7524]
i've had this happen a few times now i i think it might be connected to foretell.

i use dream devourer to exile a card, my opponent responds by saccing a sakura tribe elder, and my hand, graveyard and everything i foretold vanishes. i don't mean exilied. just ceases to exist.
![Capture](https://user-images.githubusercontent.com/65003308/107268832-56022680-6a0e-11eb-8ec2-38d09466cf38.PNG)

**Comment by jeffwadsworth** [comment]
I am testing this scenario.

**Comment by weirddan455** [comment]
I think this is #6738 

Probably nothing directly related to Dream Devourer.

**Comment by JayDi85** [comment]
Cards disappear can be fixed in #6738
