### ISSUE TITLE
Bug: Log tells opponents which card was foretold

### ISSUE THREAD

**Issue by copyosaurus** [magefree/mage#7526]
If you activate foretold it displays something like this:

> 20:44, T17.M1: User activates: from Starnheim Unleashed [b33]
> 20:44, T17.M1: User moves Starnheim Unleashed [b33] from hand to the exile zone

You probably wouldn't want to display the cardname in this instance.

**Comment by jeffwadsworth** [comment]
Already fixed.  https://github.com/magefree/mage/commit/ec01caece12af93a2f2799f4694744bd15711957
