### ISSUE TITLE
Aegar, the Freezing Flame does not trigger Path of Ancestry

### ISSUE THREAD

**Issue by EllNubNub** [magefree/mage#7538]
Aegar, the Freezing Flame does not trigger Path of Ancestry's scry ability when cast from the command zone using the mana from the lands ability.

**Comment by ldeluigi** [comment]
[[Aegar, the Freezing Flame]] [[Path of Ancestry]]

**Comment by JayDi85** [comment]
Fixed by 19693c94f7faf578a9c79cbaaea1bec782b7875a
