### ISSUE TITLE
Mystic Reflection does nothing when cast.

### ISSUE THREAD

**Issue by AsterAether** [magefree/mage#7541]
Mystic Reflection doen't seem to work.
Opponent played it from exile, chose a creature, but creatures entering the battlefield still came down normally.

**Comment by giadasp** [comment]
[[Mystic Reflection]]

**Comment by ldeluigi** [comment]
[[Mystic Reflection]]

**Comment by peter-thoenen** [comment]
Confirmed here as well, was just about to bug report it.

**Comment by jeffwadsworth** [comment]
The code from Essence of the Wild (which works perfectly) was used for the copy process, but it doesn't work in this case.  It will take a bit longer to track down the issue.

[[Essence of the Wild]]

**Comment by Tharkon** [comment]
I think it only works for creatures and not for planeswalkers.
Yet a planeswalker entering does seem to expend the effect.
Line 134 should probably also have something like isPlaneswalker().

**Comment by jeffwadsworth** [comment]
Yes.  Just missed in the refactor.
