### ISSUE TITLE
Jeskas Will not giving Option 1

### ISSUE THREAD

**Issue by Lepmim** [magefree/mage#7543]
We had a bug with Jeska's Will, where it was showing only option two. It looks like there might have been some kind of overflow happening since it says: (selected 0 of <bigass number>, min 1)

Further info:
My commander was "Chandra, Fire of Kaladesh" and Jeska's Will had the error regardless of which form she was in.
It was a 1on1 game and my opponent had over 10 cards in hand.

![image](https://user-images.githubusercontent.com/28779638/107530740-7839a700-6bbc-11eb-9dd0-313eadc4e483.png)

**Comment by Lepmim** [comment]
My opponent had shroud. So not being able to choose option 1 was correct. So the numbers on top may need some fixing in that, case, but that wouldn't be important.

**Comment by ldeluigi** [comment]
[[Jeska's Will]]
