### ISSUE TITLE
Ranar the Ever-Watchful and Curse of the Swine

### ISSUE THREAD

**Issue by ignitaxiom** [magefree/mage#7544]
i exile 3 creatures with curse of the swine and get 2 spirits.

**Comment by jeffwadsworth** [comment]
Ranar the Ever-Watchful correctly checks for cards being exiled at one time.  If an effect exiles cards incorrectly (one at a time), it will do this.  I will check out Curse of the Swine.

**Comment by ldeluigi** [comment]
[[Ranar the Ever-Watchful]] [[Curse of the Swine]]

**Comment by ignitaxiom** [comment]
also cast winds of abandon overloaded, exiling 4 creatures and got 2 spirit tokens. i think it may be giving a token for each player that has a creature exiled.

**Comment by ignitaxiom** [comment]
also when an opponent casts path to exile on my creature, i get a spirit token and probably shouldn't.

**Comment by jeffwadsworth** [comment]
Yes, that will be fixed as well.  Too busy today to do anything, but tomorrow I should have some time.
