### ISSUE TITLE
Herald's Horn and Urza's Incubator not working on Changeling commander

### ISSUE THREAD

**Issue by conflagrator** [magefree/mage#7547]
I have Herald's Horn and Urza's Incubator out as well as 4 open mana. I am not able to cast Morophon, the Boundless. I am pretty sure it worked before the update. 

![image](https://user-images.githubusercontent.com/584514/107586917-25361300-6c01-11eb-9c4d-a37a576f94c6.png)

**Comment by ldeluigi** [comment]
[[Herald's Horn]] [[Urza's Incubator]] [[Morophon, the Boundless]]

**Comment by conflagrator** [comment]
Also [[Eldrazi Temple]] is affected by this (you should be allowed to spent the two mana on a changeling)
