### ISSUE TITLE
Tibalt, Cosmic Impostor emblem not able to cast Ephemerate if it is not owned by you from Exile

### ISSUE THREAD

**Issue by Beroestheenvoy** [magefree/mage#7548]
Tibalt, Cosmic Impostor gives emblem that allows to cast exiled cards with him despite him being on the battlefield or not but I couldnt cast ephemerate on instant speed even though there were legal targets for me to cast it.

**Comment by ldeluigi** [comment]
[[Tibals, Cosmic Impostor]] + [[Ephemerate]]

**Comment by ldeluigi** [comment]
[[Tibalt, Cosmic Impostor]]

**Comment by jeffwadsworth** [comment]
Interesting.  I can't cast Ephemerate from the Exile zone under any circumstances; other cards work fine.  I will check it out.

**Comment by jeffwadsworth** [comment]
If Ephemerate is owned by someone other than yourself, this issue with arise.

**Comment by weirddan455** [comment]
@jeffwadsworth I think #7598 is the fix.  Does that look right to you?

**Comment by JayDi85** [comment]
Fixed by #7598
