### ISSUE TITLE
Cyclone Summoner not returning all permanents. 

### ISSUE THREAD

**Issue by martok22** [magefree/mage#7550]
Cyclone Summoner failed to return legal permanents (A "bird" token and "Egon, God of Death").
It's at the bottom of the game log.

[20210211_145641_Two Player Duel_1.txt](https://github.com/magefree/mage/files/5967663/20210211_145641_Two.Player.Duel_1.txt)

**Comment by theelk801** [comment]
Looks like your opponent had a [[Maskwood Nexus]] on the battlefield, so their creatures had all creature types and therefore were not returned.

**Comment by martok22** [comment]
Totally missed it.
