### ISSUE TITLE
Spark Double Copying Spark Double Copy

### ISSUE THREAD

**Issue by DominusMaximus** [magefree/mage#7553]
1.4.48.dev_2021-02-07_19-21

If I cast Spark Double and choose a Grizzly Bears on the battlefield, and then cast a second Spark Double which chooses the copy of Grizzly Bears, XMage will create a copy of Grizzly Bears with two +1/+1 counters. It should enter with only one +1/+1 counter. It seems that the Spark Double ability "...except it enters with an additional +1/+1 counter on it..." is being added to the copy, which is then being copied by additional Spark Doubles.

**Comment by ldeluigi** [comment]
[[Spark Double]] [[Grizzly Bears]]

**Comment by JayDi85** [comment]
Fixed by 2accab79c5051225b8ea4f21bbb5edfccae82ff6
