### ISSUE TITLE
There is not a snow land in every KHM draft pack

### ISSUE THREAD

**Issue by mrovirasacie** [magefree/mage#7555]
The title pretty much sums it up, I've drafted Kaldheim (KHM) many times and some packs don't have a snow land (i.e. there is a basic non-snow land) and in some there are no lands at all. This makes it impossible to effectively draft the snow archetype and disrupts a KHM draft.

Attached is a foto of proof of this in a pack 1 pick 1 scenario.

![no-snow-land](https://user-images.githubusercontent.com/54272586/107788312-8e786c00-6d50-11eb-9620-a5c76fc8ea0e.png)

**Comment by theelk801** [comment]
this is fixed with a90e992
