### ISSUE TITLE
Realmwright ability does not work (well at least on Field of Ruin)

### ISSUE THREAD

**Issue by peter-thoenen** [magefree/mage#7559]
I swear this worked before so I wonder if it had anything to do with the island walk fix you did recently but Realmwright (island chosen) did not add the island type to my field of ruin.

**Comment by JayDi85** [comment]
[[Realmwright]] [[Field of Ruin]]

**Comment by JayDi85** [comment]
Tested it in current developer version and all works fine: Realmwright gives selected land type to all lands and that works for landwalk abilities like [Benthic Djinn].

![shot_210213_161758](https://user-images.githubusercontent.com/8344157/107849807-1628ae00-6e17-11eb-9d66-c62fa7f2681c.png)
![shot_210213_161740](https://user-images.githubusercontent.com/8344157/107849799-12952700-6e17-11eb-89cc-b3ff3b1b73a8.png)

```
[test Realmwright]
// cast Realmwright
battlefield:Human:Island:1
hand:Human:Realmwright:1
// remove island
battlefield:Human:Swamp:5
hand:Human:Desecrated Earth:1
// creatures to attack/defend
battlefield:Human:Field of Ruin:1
battlefield:Computer:Benthic Djinn:3
battlefield:Human:Grizzly Bears:1
```

**Comment by JayDi85** [comment]
[[Benthic Djinn]]

**Comment by JayDi85** [comment]
There are another cards that removes land types like [[Blood Moon]]. So your land can be affected by it (e.g. gained land type from the Realmwright's was removed somehow).

**Comment by peter-thoenen** [comment]
Nah I double checked that in the game but I can't recreate either.  GA close and I will re-open if I can recreate.
