### ISSUE TITLE
Bronzehide Lion 

### ISSUE THREAD

**Issue by Gamefreak1476** [magefree/mage#7575]
![xMage issue Bronzehide Lion](https://user-images.githubusercontent.com/79058214/107886077-96105000-6ecb-11eb-9b90-8a655f4963f2.png)

I was playing an online match. Opponent forced a sacrifice of Bronzehide Lion with Dictate of Erebos. The following popped up and we got stuck in a loop of being unable to select a target for Bronzehide and the server rolling back the trigger. Screenshot of the error attached.

**Comment by sumsarz** [comment]
Fixed in [7f64822](https://github.com/magefree/mage/commit/7f6482221a403f7131e1924fa15ba8bf2c144411)

**Comment by ldeluigi** [comment]
[[Bronzehide Lion]]
