### ISSUE TITLE
Automatically select spell or ability to play if there is only one option

### ISSUE THREAD

**Issue by Ebola16** [magefree/mage#7582]
Selecting from one option seems like an unnecessary click.

![2021-02-15 copy copy](https://user-images.githubusercontent.com/17330088/107919734-cbec1d80-6f39-11eb-90ea-4d980ea00ca5.PNG)

**Comment by JayDi85** [comment]
It's by design -- users must see non standard abilities to activate (example: if land have playable additional ability then you must see it -- so no miss-clicks for mana).

**Comment by Ebola16** [comment]
I have rarely encountered a miss-click for mana but frequently encounterd needing to select from a list of one option. Perhaps make my request an optional setting but have the default behavior as what XMage currently does here?

**Comment by JayDi85** [comment]
There is a special option that enable that dialog on 1 activated ability (it's outdated description but it do what you want):
![shot_210215_122449](https://user-images.githubusercontent.com/8344157/107922099-f74a2900-6f88-11eb-8a6e-35da76fec2da.png)

You can enable or disable it real time from battlefield (if you change it by phase buttons instead main menu).

**Comment by Ebola16** [comment]
Ah, I shall test this option. Thank you!
