### ISSUE TITLE
Cascade rule change

### ISSUE THREAD

**Issue by weirddan455** [magefree/mage#7583]
The cascade rule has been changed in today's B&R announcement.

https://magic.wizards.com/en/articles/archive/news/february-15-2021-banned-and-restricted-announcement?x=iazoidrnet

> The new rule for cascade is as follows:
> 
> 702.84a. Cascade is a triggered ability that functions only while the spell with cascade is on the stack. "Cascade" means "When you cast this spell, exile cards from the top of your library until you exile a nonland card whose converted mana cost is less than this spell's converted mana cost. You may cast that spell without paying its mana cost if its converted mana cost is less than this spell's converted mana cost. Then put all cards exiled this way that weren't cast on the bottom of your library in a random order."

They went into more detail at the bottom of the page.  If I'm understanding this correctly, I believe it will only change how MDFCs and Adventure cards work with Cascade.  I think split cards should work the same since their CMC is determined by adding both sides of the card anyway.  Please correct me if I'm wrong here.  I'll look into getting this implemented.

**Comment by theelk801** [comment]
Yeah, that's right. Split cards work the same.

**Comment by theelk801** [comment]
Actually, do cards like [[Yahenni's Expertise]] work correctly? You shouldn't be able to use a card like that to cast Tibalt.

**Comment by JayDi85** [comment]
Yes, "cast a spell" and "cast a card" is different. That's the main change in cascade too:

![shot_210215_230818](https://user-images.githubusercontent.com/8344157/107985031-b979ee80-6fe2-11eb-8d49-31342fa5eee5.png)

**Comment by weirddan455** [comment]
@theelk801 Looks like the Oracle text on that card was updated at some point from "you may cast a card" to "you may cast a spell."  I believe with the old wording, you would have been able to cast Tibalt but now I don't think so (not 100% sure though.)

I'm finishing up cascade now so I haven't tested yet but a quick look at the code shows we're using the original text (only checking the CMC of the card in hand.)

**Comment by theelk801** [comment]
Yeah there have been a lot of changes like that, I think in part due to adventures and MDFCs. Probably needs to be a whole project. We also need to be able to play MDFC lands off the top with [[Oracle of Mul Daya]].

**Comment by JayDi85** [comment]
"You may cast spell/play lands" -- must looks and allows each sides independently. You "may cast card/play card" -- must looks at the card's CMC and main side (for mdf is left side).

See same rules changing Oracle of Mul Daya:
https://www.mtgsalvation.com/forums/magic-fundamentals/magic-rulings/819758-mdfc-and-oracle-of-mul-daya

**Comment by JayDi85** [comment]
> Yeah there have been a lot of changes like that, I think in part due to adventures and MDFCs. Probably needs to be a whole project. We also need to be able to play MDFC lands off the top with Oracle of Mul Daya.

It already works. See same card [[Radha, Heart of Keld]] and `test_PlayFromNonHand_SecondSideAsLand_ByRadhaHeartOfKeld`.

**Comment by JayDi85** [comment]
Implemented in #7584
