### ISSUE TITLE
Geode Golem causes you to pay commander tax twice with Tibalt, Cosmic Imposter.

### ISSUE THREAD

**Issue by EllNubNub** [magefree/mage#7593]
When Geode Golem triggers and lets you cast your commander from the command zone, it was making me pay the commander tax twice upon choosing the Tibalt, Cosmic Imposter side of the MDFC. This may be a larger problem with MDFC commanders, i am not sure. A side note, i also witnessed Tibalt get bounced (as my commander) and it did not ask me if i wanted to put it to the command zone. It was bounced with Tidespout Tyrant.

**Comment by JayDi85** [comment]
Fixed by f6c0f4c71247f344dc7ceb3436d5d29718bf2509
