### ISSUE TITLE
Client crash when player joins queue with xlib threads lost error

### ISSUE THREAD

**Issue by zorkmead** [magefree/mage#7594]
Client crashes with following error message in console

[xcb] Unknown sequence number while processing queue
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
java: ../../src/xcb_io.c:259: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.

Ubuntu Linux 18.04 with 4.15.0-135-generic

**Comment by JayDi85** [comment]
Are you running it from game launcher or from script? If it's a script then report your java/JDK version too.

**Comment by JayDi85** [comment]
Tested it with Ubuntu 18.04 (run game from launcher) -- all works fine.

java and ubuntu versions:
```
jaydi@ubuntu:~/Desktop/games/xmage$ java --version
openjdk 11.0.10 2021-01-19
OpenJDK Runtime Environment (build 11.0.10+9-Ubuntu-0ubuntu1.18.04)
OpenJDK 64-Bit Server VM (build 11.0.10+9-Ubuntu-0ubuntu1.18.04, mixed mode, sharing)
```
Run launcher script: `sh run-launcher-linux.sh`:
```
java -jar XMageLauncher-0.3.8.jar
```

**Comment by zorkmead** [comment]
Running from the launcher. Crash occurs when a player joins a queue after me - as I start a sealed tourney, then a player joins and the client crashes.

**Comment by JayDi85** [comment]
Tested it in different plays and clients combination -- all works fine with ubuntu 18.04.

Problem related to your **graphic card and drivers**, it's not an xmage problem or bug. You can find examples [here](https://bugs.launchpad.net/ubuntu/+source/freecad/+bug/1754084) and [here](https://github.com/gstreamer-java/gst1-java-core/issues/131):
* try to find/change graphic card settings or update the system (e.g. opengl libs or acceleration);
* try to [apply some java related settings in then launcher](https://github.com/magefree/mage#linux-tweaks) to disable/enable additional graphic features.
