### ISSUE TITLE
Clear match password fields when client closed or after match

### ISSUE THREAD

**Issue by fireshoes** [magefree/mage#760]
I've seen a number of cases of people starting a match and not realizing that their password from a previous match or use of the client is still filled from before, so they sit there wondering why no one is joining their match.

**Comment by LevelX2** [comment]
Some time ago I implemented to different preference values for passwords you set for a new table and passwords you use to join a pw protected game.
So it should no longer happen that you protect your game accidently because you joined a pw protected game before.
