### ISSUE TITLE
Elsha of the Infinite issue with modal DFCs

### ISSUE THREAD

**Issue by Kryos257** [magefree/mage#7605]
When Elsha of the Infinite is in play, cards drawn seem to retain the ability to be cast as though they had flash until end of turn. If a MDFC is drawn (in this case Birgi, God of Storytelling, Reidane, God of the Worthy and Alrund, God of the Cosmos) then I am only given the option to cast non-creature sides of those cards.

**Comment by JayDi85** [comment]
[[Elsha of the Infinite]] is correct. All cards with "play XXX from the top of your library" changed the oracle texts last year:
* from cards: "You may cast the top **card** of your library if it's a noncreature, nonland **card**"
* to spells: "You may cast noncreature **spells** from the top of your library."

So now it checks each card's parts and allows only a specific part to play/cast, not a full card. Same rules changes were made for Cascade from last oracle update (read more in #7583).

**Comment by Kryos257** [comment]
I understand that I can only play allowed sides of MDFCs from top of library. The issue is that when I draw those cards, I am then only allowed to play the noncreature sides of the card from hand also during that turn and they can still be played from hand as though they have flash that turn.
eg. I have Reidane on top of library, I can cast Valkmira but not Reidane. I then draw Reidane but can still only cast Valkmira from hand

**Comment by Kryos257** [comment]
![ElshaBug3](https://user-images.githubusercontent.com/78707966/108614053-36e09d00-73ef-11eb-9567-379d0799bfe2.PNG)
![ElshaBug2](https://user-images.githubusercontent.com/78707966/108614055-39db8d80-73ef-11eb-83db-e2b19dbbbddb.PNG)
![ElshaBug1](https://user-images.githubusercontent.com/78707966/108614056-3c3de780-73ef-11eb-8a4a-314b628f1f11.PNG)

On attempting to recreate the issue, the MDFCs actually work correctly. I think the issue must have been me trying to play it while something was on the stack? However, Elsha does still seem to give noncreature spells from hand flash speed

**Comment by JayDi85** [comment]
Original bug: flash ability applies to all non creature cards
