### ISSUE TITLE
Finale of devastation

### ISSUE THREAD

**Issue by anf123** [magefree/mage#7609]
Finale of devastation not applying +X/+X to creatures after resolving

**Comment by theelk801** [comment]
what was the value of X?

**Comment by anf123** [comment]
Hello, had two separate moments where it occurred, once where X was 11 and
another time when X was 14. I searched for craterhoof so I don’t know if
that could possibly affect the spell somehow

**Comment by ldeluigi** [comment]
[[Finale of devastation]]

**Comment by awjackson** [comment]
I can't reproduce this.
