### ISSUE TITLE
Desertion - rollback error on multiple counter spell

### ISSUE THREAD

**Issue by DanKitzman** [magefree/mage#7613]
Crash report

Game exception occurred: java.lang.NullPointerException
Server version: 1.4.48V1 (build: 2021-02-13 16:43)
mage.cards.d.DesertionReplacementEffect.applies(Desertion.java:84)
mage.abilities.effects.ContinuousEffects.getApplicableReplacementEffects(ContinuousEffects.java:367)
mage.abilities.effects.ContinuousEffects.replaceEvent(ContinuousEffects.java:852)
mage.game.GameState.replaceEvent(GameState.java:769)
mage.game.GameState.replaceEvent(GameState.java:762)
mage.game.GameImpl.replaceEvent(GameImpl.java:2814)
mage.game.ZonesHandler.maybeRemoveFromSourceZone(ZonesHandler.java:332)
mage.game.ZonesHandler.lambda$moveCards$0(ZonesHandler.java:99)
java.util.ArrayList.removeIf(ArrayList.java:1413)
mage.game.ZonesHandler.moveCards(ZonesHandler.java:99)
mage.game.ZonesHandler.moveCard(ZonesHandler.java:50)
mage.cards.CardImpl.moveToZone(CardImpl.java:446)
mage.cards.CardImpl.moveToZone(CardImpl.java:426)
mage.players.PlayerImpl.moveCardToGraveyardWithInfo(PlayerImpl.java:4298)
mage.players.PlayerImpl.moveCardsToGraveyardWithInfo(PlayerImpl.java:4282)
mage.players.PlayerImpl.moveCards(PlayerImpl.java:4092)
mage.players.PlayerImpl.moveCards(PlayerImpl.java:4067)
mage.game.stack.Spell.counter(Spell.java:436)
mage.game.stack.SpellStack.counter(SpellStack.java:89)
mage.game.stack.SpellStack.counter(SpellStack.java:63)
mage.abilities.effects.common.CounterTargetEffect.apply(CounterTargetEffect.java:34)
mage.abilities.AbilityImpl.resolveMode(AbilityImpl.java:186)
mage.abilities.AbilityImpl.resolve(AbilityImpl.java:173)
mage.game.stack.StackAbility.resolve(StackAbility.java:86)
mage.game.GameImpl.resolve(GameImpl.java:1447)
mage.game.GameImpl.playPriority(GameImpl.java:1393)
mage.game.turn.Step.priority(Step.java:61)
mage.game.turn.Phase.playStep(Phase.java:184)
mage.game.turn.Phase.play(Phase.java:89)
mage.game.turn.Turn.play(Turn.java:128)
mage.game.GameImpl.playTurn(GameImpl.java:911)
mage.game.GameImpl.play(GameImpl.java:821)
mage.game.GameImpl.start(GameImpl.java:797)
mage.server.game.GameWorker.call(GameWorker.java:34)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)

**Comment by JayDi85** [comment]
Fixed by a377999f578dd7a99e95d3fd56932369679eb6e0
