### ISSUE TITLE
Blood Moon / Blood Sun "tap" lands bug

### ISSUE THREAD

**Issue by TheRealArtisan** [magefree/mage#7614]
Playing a Land that "enter the battlefield tapped" while Blood Moon or Blood Sun on the battlefield should enter UN-tapped.
Due to them being Mountains or having no other abilities, respectively. 
These interactions works correctly on MTG Arena. 
However, on XMage, Lands like Lotus Field (often played with Blood Sun), enter the battlefield tapped while Blood Sun is on the battlefield. 
The same bug also happens if Blood Moon is out and a player plays the new dual-snow Lands (ie: Sulfurous Mire), currently, the land enters tapped. Whereas it should be a Mountain (and entering UN-tapped).

**Comment by sumsarz** [comment]
#4202
