### ISSUE TITLE
Leyline of Combustion and Collective Brutality

### ISSUE THREAD

**Issue by filipebfs** [magefree/mage#7616]
Leyline of Combustion triggers multiple times when Collective Brutality cast with more than one escalate option

**Comment by ldeluigi** [comment]
[[Leyline of Combustion]] and [[Collective Brutality]]

**Comment by filipebfs** [comment]
Gatherer: 
"7/12/2019 | If a spell targets you and/or a permanent you control multiple times, or if a spell targets you and one or more permanents you control, Leyline of Combustion’s triggered ability triggers once."
-- | --

**Comment by weirddan455** [comment]
Fixed in #7626
