### ISSUE TITLE
Rollback Error with Valki

### ISSUE THREAD

**Issue by Zerrisx** [magefree/mage#7618]
I cast Draconic Roar on Valki in response to his ability activation (attempting to turn into Thunderbreak Regent).  Valki died, but then the activation resolution caused a crash.

Probably an issue with Valki's ability resolving when he's no longer on the battlefield.

**Comment by ldeluigi** [comment]
[[Draconic Roar]] [[Valki]] [[Thunderbreak Regent]]

**Comment by JayDi85** [comment]
Rollback error for Valki and other cards were fixed in 91f4d7899269e7811da668da123e0d37dc5e6769 (error if no exile). So I think it must be fixed
