### ISSUE TITLE
Bronze hide Lion trigger auto roll back

### ISSUE THREAD

**Issue by zorkmead** [magefree/mage#7627]
the following popped up when a bronze hide lion died in a THS sealed

An error has occurred on the MAGE server. Your last action will be rollbacked.
Please post the following report here: https://github.com/magefree/mage/issues

Game exception occurred: java.lang.IllegalArgumentException: Wrong code usage. Don't use that method for permanents, use permanent.addAbility(a, source, game) instead.
Server version: 1.4.48V1 (build: 2021-02-13 16:43)
mage.cards.CardImpl.addAbility(CardImpl.java:313)
mage.cards.b.BronzehideLionContinuousEffect.apply(BronzehideLion.java:164)
mage.abilities.effects.ContinuousEffects.apply(ContinuousEffects.java:1062)
mage.game.GameState.applyEffects(GameState.java:602)
mage.game.GameImpl.applyEffects(GameImpl.java:1576)
mage.players.PlayerImpl.moveCards(PlayerImpl.java:4118)
mage.players.PlayerImpl.moveCards(PlayerImpl.java:4067)
mage.players.PlayerImpl.moveCards(PlayerImpl.java:4058)
mage.cards.b.BronzehideLionReturnEffect.apply(BronzehideLion.java:96)
mage.abilities.AbilityImpl.resolveMode(AbilityImpl.java:186)
mage.abilities.AbilityImpl.resolve(AbilityImpl.java:170)
mage.abilities.TriggeredAbilityImpl.resolve(TriggeredAbilityImpl.java:81)
mage.game.stack.StackAbility.resolve(StackAbility.java:86)
mage.game.GameImpl.resolve(GameImpl.java:1447)
mage.game.GameImpl.playPriority(GameImpl.java:1393)
mage.game.turn.Step.priority(Step.java:61)
mage.game.turn.Phase.playStep(Phase.java:184)
mage.game.turn.Phase.play(Phase.java:89)
mage.game.turn.Turn.play(Turn.java:128)
mage.game.GameImpl.playTurn(GameImpl.java:911)
mage.game.GameImpl.play(GameImpl.java:821)
mage.game.GameImpl.start(GameImpl.java:797)
mage.server.game.GameWorker.call(GameWorker.java:34)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)

**Comment by JayDi85** [comment]
fixed in #7564
