### ISSUE TITLE
After changing password, cannot open client (ubuntu 20.04)

### ISSUE THREAD

**Issue by acabaca24** [magefree/mage#7639]
Basically, I play in 2 different PCs and in both I checked this checkbox:
![image](https://user-images.githubusercontent.com/61804801/109657940-f3f49700-7b5d-11eb-8955-983d9cbb2be0.png)

In PC A I changed my password and everything is fine.

But in PC B when I try to open Xmage this happens:

![image](https://user-images.githubusercontent.com/61804801/109658119-2c947080-7b5e-11eb-9069-a03188a58bfa.png)

Client log:
![image](https://user-images.githubusercontent.com/61804801/109657860-dfb09a00-7b5d-11eb-8c61-1800887e28e4.png)

Note: If i use another OS user(like root for example), it prompts the login form. So i think this data is linked to the OS user.

Also the only way I found to close xmage with that gray screen, was to kill the process. Doesn't matter much, but it's a good thing to know.

**Comment by JayDi85** [comment]
You must disable auto-login. Follow [that instructions](https://github.com/magefree/mage/issues/4461#issuecomment-361108597).

**Comment by acabaca24** [comment]
Thank you! It worked just fine!
