### ISSUE TITLE
Problem with Khorvath's Fury and Bronzehide Lion

### ISSUE THREAD

**Issue by meetaig** [magefree/mage#7641]
During a game of EDH just now we had two NULL pointer exceptions
1) When Bronzehide Lion died and came back as an enchantment it seemed like targeting a creature broke something. Got a popup with a stack trace (unfortunately I didnt get a screenshot of it). After that some blocked creatures that had died came back to life including the lion.

2) Khorvath's Fury produced a stacktrace popup when Friend was chosen for each player. In both cases it was not me that played those cards. 

This happened on the german server with the newest version of Xmage.
Hope this can be reproduced. Sorry for not thinking of making a screenshot.

**Comment by ldeluigi** [comment]
[[Bronzehide Lion]] [[Khorvath's Fury]]

**Comment by JayDi85** [comment]
What's server (de or us)?

**Comment by meetaig** [comment]
> This happened on the **german** server with the newest version of Xmage.

It was on the DE server

**Comment by JayDi85** [comment]
NPE error fixed by 491fc560e846be1445818dd34076d02fd09d57f1
