### ISSUE TITLE
Client crashes on startup with "Graphics Device Initialization failed"

### ISSUE THREAD

**Issue by Aivech** [magefree/mage#7643]
client log: https://gist.github.com/Aivech/8a020e13debe25ca0e34dc2af330b92f

Error only occurs when launching from the launcher. Launching via the script works fine, but throws similar errors about a missing JavaFX.

Java version is adoptopenjdk-8.0.275+1.openj9-0.23.0

> Operating System: Arch Linux
> KDE Plasma Version: 5.21.2
> KDE Frameworks Version: 5.79.0
> Qt Version: 5.15.2
> Kernel Version: 5.10.16-arch1-1
> OS Type: 64-bit
> Graphics Platform: X11
> Processors: 16 × AMD Ryzen 7 4800H with Radeon Graphics
> Memory: 15.1 GiB of RAM
> Graphics Processor: AMD RENOIR

**Comment by JayDi85** [comment]
Launcher uses oracle java (1.8) from ./xmage/java folder, script uses default system java (adoptopenjdk). So the problem in oracle's support/compatibility with your system.

Look [here](https://stackoverflow.com/questions/21185156/javafx-on-linux-is-showing-a-graphics-device-initialization-failed-for-es2-s) for more solutions. It can be missing or outdated GTK graphic library.

**Comment by Aivech** [comment]
potentially related issue: not having JFX on the system seems to make all server connections fail

**Comment by JayDi85** [comment]
Nope, xmage must works fine without jfx. It's a client side library only.

Real reason can be in your default system java (if you run it by script). Official servers uses java 1.8, so your system java must be same. If not (e.g. java 9) then you will see empty hand, strange errors or wrong connection.

**Comment by Aivech** [comment]
I got it working, somehow, by launching the launcher from the command line with java -jar. Might have something to do with using asdf to manage java versions for different programs.
