### ISSUE TITLE
Mycosynth Lattice, Solemnity and Planeswalkers 

### ISSUE THREAD

**Issue by spjspj** [magefree/mage#7644]
I believe that now with the game checking what continuous effects would apply to it, the PWs (being artifacts) should now come in with 0 loyalty counters and thus die. 
https://www.mtgsalvation.com/forums/magic-fundamentals/magic-rulings/780768-general-questions-concerning-solemnity

I think this is similar to the blood moon changes though in that they're hard :)

**Comment by JayDi85** [comment]
> game checking what continuous effects would apply to it

But game is not checking that. That's the main problem of "blood moon" #4202 -- game must look ahead, put new permanent to battlefield, apply all effects and take a characteristics for real ETB:

![shot_210304_143522](https://user-images.githubusercontent.com/8344157/109951301-f5a59280-7cf6-11eb-88ed-5059adc3dda0.png)

[[Mycosynth Lattice]] [[Solemnity]]

**Comment by spjspj** [comment]
I think this is a non issue.  Solemnity doesn't actually prevent PWs from coming in with Loyalty counters (even if they are artifacts).
