### ISSUE TITLE
AI able to play lands from my graveyard with Crucible of Worlds

### ISSUE THREAD

**Issue by dosfod** [magefree/mage#7645]
Hey, 

during a game, the AI is able to play lands from my graveyard with its own [[Crucible of Worlds]]. Attached screenshots:

![image](https://user-images.githubusercontent.com/29545637/110004249-83917580-7d17-11eb-8297-f4e8b4186b03.png)

![image](https://user-images.githubusercontent.com/29545637/110004233-7d02fe00-7d17-11eb-94b2-27a62d1b7a34.png)

![image](https://user-images.githubusercontent.com/29545637/110004210-75dbf000-7d17-11eb-9c48-6986a1f3d507.png)

For the record, the AI had a [[Tergrid's Lantern]] on the battlefield, in case that matters.

Kind regards

**Comment by weirddan455** [comment]
It wasn't an AI bug.  The card was bugged for human players as well.  Should be fixed now.
