### ISSUE TITLE
Bug: Cascading Cataracts

### ISSUE THREAD

**Issue by imendi7** [magefree/mage#7649]
When Cascading Cataracts is played, it stops freezes the game for a couple of minutes until it resumes on its own

**Comment by ldeluigi** [comment]
Was an AI in the game?

**Comment by imendi7** [comment]
No, it was between two player. The other player said that it's happening often when playing that it.On Mar 10, 2021 11:26, ldeluigi ***@***.***> wrote:
Was an AI in the game?
