### ISSUE TITLE
Brain Maggot bug still

### ISSUE THREAD

**Issue by filipebfs** [magefree/mage#765]
version 1.3.0dev 2015-02-07 v7

Exiled card does not returns to owner hand

**Comment by LevelX2** [comment]
I can't reproduce this problem.
You know that the effect doesn't go to the stack. So it's easy to overlook the line about the card movement in the log.

Can you descripe in detail what happened exactly in you game so that the card did not return to hand?

**Comment by filipebfs** [comment]
game log:

<font color="White">RAGE casts Brain Maggot</font>
<font color="#CCCC33">15:06: </font><font color="White">Ability triggers: 
    Brain Maggot - When Brain Maggot enters the battlefield, target opponent 
    reveals his or her hand and you choose a nonland card from it. Exile that 
    card until Brain Maggot leaves the battlefield. - targeting FBF </font>
<font color="#CCCC33">15:06: </font><font color="White">FBF reveals Shrapnel 
    Blast, Satyr Firedancer, Font of Ire, Arc Lightning</font>
<font color="#CCCC33">15:06: </font><font color="White">RAGE moves Arc 
    Lightning from hand to exile</font>
<font color="#CCCC33">15:06: </font><font color="White">RAGE attacks with 0 
    creatures</font>
<font color="#CCCC33">15:06: </font><font color="Orange">Turn 5 FBF (19 - 20)</font>
<font color="#CCCC33">15:06: </font><font color="White">FBF draws a card</font>
<font color="#CCCC33">15:07: </font><font color="White">FBF plays Darksteel 
    Citadel</font>
<font color="#CCCC33">15:07: </font><font color="White">FBF sacrificed 
    Briber's Purse</font>
<font color="#CCCC33">15:07: </font><font color="White">FBF casts Shrapnel 
    Blast targeting RAGE </font>
<font color="#CCCC33">15:07: </font><font color="White">RAGE loses 5 life</font>
<font color="#CCCC33">15:07: </font><font color="White">Ability triggers: 
    Satyr Firedancer - Whenever an instant or sorcery spell you control deals 
    damage to an opponent, Satyr Firedancer deals that much damage to target 
    creature that player controls. - targeting Brain Maggot </font>
<font color="#CCCC33">15:07: </font><font color="White">Brain Maggot died</font>
<font color="#CCCC33">15:08: </font><font color="White">FBF attacks with 1 
    creature</font>

**Comment by drmDev** [comment]
will test later

**Comment by drmDev** [comment]
cannot duplicate - old issue
