### ISSUE TITLE
Twinning Staff must support non standard copy spells (increase copied amount)

### ISSUE THREAD

**Issue by JayDi85** [magefree/mage#7653]
[[Twinning Staff]] allows to increase copied spells amount. It works fine with standard copy code (that uses `Spell.createCopyOnStack`) but doesn't work with another copy code (that uses `Spell.copySpell`).

Search code for `see Twinning Staff` or `.copySpell`. It must be modified same way as `createCopyOnStack`:
* use two copy events (before and after copy);
* use replaced `amount` value for multiple copies creation;
* research: some copied spells uses auto-target but Twinning Staff must allow to choose new target (maybe copy event must have additional param, don't know).

Broken card example: [[Fork]] (combo with Twinning Staff doesn't work).

![shot_210306_200057](https://user-images.githubusercontent.com/8344157/110212818-b160f080-7eb6-11eb-9c5e-5a440ce68fc8.png)

**Comment by theelk801** [comment]
I'm looking into this right now, the rulings on these interactions isn't completely clear (the judge chat seemed unsure) but I've tweeted at the rules manager for clarification.

**Comment by JayDi85** [comment]
Maybe @emerald000 can help with rules details. From the code side it's looks like same/related.

**Comment by emerald000** [comment]
What's the question exactly?

**Comment by theelk801** [comment]
How does Twinning Staff interact with Fork, Beamsplitter Mage and Precursor Golem?

**Comment by emerald000** [comment]
You get an additional copy of the spell, which you can place before, after, or anywhere in between the "normal" copies. The targets are kept the same as the original spell, but you are allowed to change them if you want.
