### ISSUE TITLE
Bugged Deicide interaction with non-creature god cards

### ISSUE THREAD

**Issue by revilosnikwad** [magefree/mage#7661]
Deicide appears to be bugged. When exiling Heliod, Sun crowned, it does not give an option to search the opponent’s hand etc. This may be due to God cards not being Gods on the battlefield (as they are not creatures until a certain devotion). This should not matter however, as Deicide checks the card in exile, where it is a God.

**Comment by ingmargoudt** [comment]
Confirmed. LoseCreatureTypeSourceEffect removes both the CardType 'Creature', as well as all Creature Subtypes

**Comment by ingmargoudt** [comment]
Related ruling: 


4/26/2014 | Deicide looks at the card in exile, not the permanent that was exiled, to determine if it is a God. For each of the Gods in the Theros block, it won’t matter what your devotion to its color(s) was. The card is a God card when not on the battlefield.
-- | --

**Comment by DanielePalmieri** [comment]
same bug discovered today, deicide doesn't work on heliod

**Comment by Alex-Vasile** [comment]
[[Deicide]]
