### ISSUE TITLE
Invasion of the giants chapter III not working as intended.

### ISSUE THREAD

**Issue by dihimono** [magefree/mage#7664]
https://github.com/magefree/mage/blob/d5822a72462d4798dae2ab2da390aae3a1401060/Mage.Sets/src/mage/cards/i/InvasionOfTheGiants.java#L115

In my testing this will not apply the cost reduction if the giant spell you played is not the first turn you played that turn.

**Comment by ldeluigi** [comment]
{{Invasion of the giants}}
