### ISSUE TITLE
Beta Server Tables not showing up

### ISSUE THREAD

**Issue by Dumoque** [magefree/mage#7667]
I'm on the beta server and when I create a table it does not show up in the list. Meaning no one can join my table (unless there is a way to invite people that I'm not aware of). The player list also is incorrect. It shows 2 users, but not myself or my friend.

**Comment by JayDi85** [comment]
1. Beta restarted, so active tables visible now again;
2. Users list can be updated with timeout, so you can see yourself in next minute after connect;
