### ISSUE TITLE
Abilities that trigger upon dying of artifacts sacrificed with Goblin Welder do not trigger.

### ISSUE THREAD

**Issue by Tharkon** [magefree/mage#7672]
Ancient Stone Idol's last ability does not trigger when it is sacrificed because of Goblin Welder.

It does trigger if the idol is destroyed by Terminate, sacrificed to Altar of Dementia, Krark-Clan Ironworks or Plaguecrafter.

**Comment by Tharkon** [comment]
Wormcoil engine's ability does not trigger either so the problem seems to be with Goblin Welder and not with the Ancient Stone Idol.

**Comment by ldeluigi** [comment]
[[Goblin Welder]]
