### ISSUE TITLE
Sometimes lose the ability to choose from multiple abilities on lands

### ISSUE THREAD

**Issue by alexander-novo** [magefree/mage#7676]
I've had this happen to me in two games in the past couple of days now. The first game had a [[Dictate of Karametra]] and I suspected it had something to do with that, but the second game didn't have any mana doubling replacement effects. I now suspect it has something to do with large board states. But reducing the board state with a wipe or something doesn't bring the functionality back.

So if there is a land with multiple abilities (dual land, utility land, or enchanted land), once the game gets into this state, it will only ever use the first ability when clicked on - regardless of when I click them - and doesn't show the window to choose ability. This means dual lands only ever produce one color (the first one listed), utility lands can't use their utility ability, and enchanted lands that have abilities added can't use those additional abilities.

I've observed it on normal duals like [[Hallowed Fountain]], which could then only produce blue mana, utility lands like [[Hall of Heliod's Generosity]], which would only produce colorless even when I wanted to activate the recursion ability, and [[Weirding Wood]], whose enchanted land I could only ever tap for one mana (note that auras that added triggered abilities like [[Utopia Sprawl]] work fine).

I've tried tapping while no costs are being paid, tapping while paying a cost, and tapping while paying a cost with only a specific color left, and none of these situations changed the functionality. For instance, I tried casting something with only a {G} left to pay and tapping an island enchanted with [[Weirding Wood]] would only add a blue to my mana pool.

It doesn't affect what the game highlights as thinking is castable - it can sometimes just be impossible to pay the costs if you're relying on abilities which aren't first in the list.

**Comment by JayDi85** [comment]
Try to right click on battlefield and change mana ability click -- there are a special option that activate mana ability by default.

**Comment by alexander-novo** [comment]
Ah. I noticed I accidentally turned something on in the right click menu a while back. Thank you.
