### ISSUE TITLE
Mana abilities should be activated before costs are paid when casting a spell

### ISSUE THREAD

**Issue by emerald000** [magefree/mage#768]
This is a pretty minor mistake in how spells are technically cast currently.

The second-to-last step in casting a spell is activating mana abilities. The last is paying costs. The distinction between those two steps usually don't matter, but they can end up mattering in some corner cases.

For example, you shouldn't be able to cast Will-Forge Golem (Convoke for {6}) with 3 Eldrazi Spawn. If you tap them for Convoke, it is too late to sacrifice them for the mana ability. If you sacrifice them, you obviously can't tap them afterwards.

**Comment by stravant** [comment]
Does anyone know how MTGO handles this? 

I'm not sure how the UI could reasonably implement this distinction. It would be pretty painful to have to activate mana abilities separately from actually paying them into the cost. Maybe the UI should act like it does now but the underlying data model should be modified differently with the "correct" sequencing of mana payment / mana ability activation?

**Comment by emerald000** [comment]
There is 2 ways I could see to go about this.

1- Have special mana payments (convoke, delve) only usable after mana payments. This is the most accurate way to go with it, but it may confuse players unless it is quite explicit about what is happening. ("Finish mana payments. Continue with special payments." or something similar)

2- Keep the current interface. If a special payment has been used, once the total cost is paid for, check to make sure the special payment could have still been used. If not, revert back.

**Comment by JayDi85** [comment]
[Related topic from mtgsalvation](https://www.mtgsalvation.com/forums/magic-fundamentals/magic-rulings/magic-rulings-archives/607097-eldrazi-spawn-tokens-and-convoke):

> No. After the total cost of the spell is determined, you are given a chance to activate mana abilities. After that, you pay the cost of the spell. You would have to sacrifice the tokens to get mana before you are allowed to tap them to help pay the cost.
> 
> For reference:
> 
> 601.2f If the total cost includes a mana payment, the player then has a chance to activate mana abilities (see rule 605, “Mana Abilities”). **Mana abilities must be activated before costs are paid.**
> 
> 601.2g The player pays the total cost in any order. Partial payments are not allowed. Unpayable costs can’t be paid. 

Rules from convoke:

> If a creature you control has a mana ability with {T} in the cost, activating that ability while casting a spell with convoke will result in the creature being tapped when you pay the spell’s costs. You won’t be able to tap it again for convoke. Similarly, **if you sacrifice a creature to activate a mana ability while casting a spell with convoke, that creature won’t be on the battlefield when you pay the spell’s costs, so you won’t be able to tap it for convoke**. (2014-07-18)

**Comment by JayDi85** [comment]
Fixed via #6670
