### ISSUE TITLE
CardRepository crashes when using Cursed Scroll (server's memory leak)

### ISSUE THREAD

**Issue by Mysticodex** [magefree/mage#7680]
Using Cursed Scroll's ability, and the list of cards in the database doesn't load in order to choose a matching card name to something from my hand. See the screenshot below:

![image](https://user-images.githubusercontent.com/6277799/111851230-b323ae80-88cf-11eb-999d-85d78a9c9697.png)

![image](https://user-images.githubusercontent.com/6277799/111851185-8e2f3b80-88cf-11eb-9736-680e42eb061a.png)

**Comment by JayDi85** [comment]
It can be memory leak or too many played games (most of the database errors related to memory usage). Just try to restart local server and try again -- is it help or not. If you catch same error with same card again then it can be a bug with card or AI code.

If you catch "strange errors" in random places too often with AI games, then try to increase server memory by launcher (follow same instructions as client memory usage do but for server options).

**Comment by Mysticodex** [comment]
Is there a best practice for restarting the server mid-game, or will I always have to crash out? Right now I can't close the dialogue box to select a card from the database.

I have just upped my -Xmx to 2g, hopefully, this will help in the future.

**Comment by JayDi85** [comment]
Server's restart reset all games, so you can't continue same game after that. If you catch missing card error or database error then server is broken and you can't play on it. So only restart can help.

BTW if you want to test some combos or game situations then I recommends to use special test mode to setup battlefield by simple commands:
https://github.com/magefree/mage/wiki/Development-Testing-Tools
