### ISSUE TITLE
Prototype Portal copying transformable card doesn't transform when triggered

### ISSUE THREAD

**Issue by rystan** [magefree/mage#7682]
I used [[Prototype Portal]] to imprint a [[Thaumatic Compass]].  At end step the trigger to transform the Compass fired, but the token did not turn into the reverse side land.  I had more than 7 lands in play.
![image](https://user-images.githubusercontent.com/6609665/111857438-d4a08c80-8907-11eb-8d49-2f450ae00a74.png)

Nothing else in play would have prevented a transformation that I can tell:
![image](https://user-images.githubusercontent.com/6609665/111857544-a0799b80-8908-11eb-9324-53ef1043fd58.png)

**Comment by emerald000** [comment]
Tokens do not have a backside and cannot transform.
