### ISSUE TITLE
Server Error -- Card Not Found US Server

### ISSUE THREAD

**Issue by spcphd1976** [magefree/mage#7686]
I am getting the same server issue for every single deck that I have used in the past: "Server Error--card not found." All of these decks have worked. I am using XMage version on 1.4.48V2. I have downloaded all of the images and tokens. It tells me that I am using cards for use on a newer version of the server? I was using the US server. What is going on?

**Comment by JayDi85** [comment]
It's a standard server error about restart needs. US restarted now.

**Comment by spcphd1976** [comment]
Thank you !

By the way, I’ve been trying to get some folks to subscribe to your Patreon. I’m a subscriber. How much money would you need to have a better dedicated server in the US? 

Please advise.

-Sean Connolly

**Comment by JayDi85** [comment]
@spcphd1976 it depends but can be improved. Write to me on jaydi85@gmail.com for more details.
