### ISSUE TITLE
Server Error--Card Not Found?

### ISSUE THREAD

**Issue by spcphd1976** [magefree/mage#7687]
I am getting the same server issue for every single deck that I have used in the past: "Server Error--card not found." All of these decks have worked. I am using XMage version on 1.4.48V2. I have downloaded all of the images and tokens. It tells me that I am using cards for use on a newer version of the server? I was using the US server. What is going on?

**Comment by JayDi85** [comment]
It's a standard server error about restart needs. US restarted now.
