### ISSUE TITLE
Bug with Intet, The Dreamer and is mana ability

### ISSUE THREAD

**Issue by Takezo90** [magefree/mage#7690]
Game exception occurred: java.lang.IllegalArgumentException: ERROR, can't call applies method on empty affectedAbility
Server version: 1.4.48-V2 (build: 2021-02-27 18:40)
mage.abilities.effects.common.asthought.PlayFromNotOwnHandZoneTargetEffect.applies(PlayFromNotOwnHandZoneTargetEffect.java:87)
mage.abilities.effects.common.asthought.PlayFromNotOwnHandZoneTargetEffect.applies(PlayFromNotOwnHandZoneTargetEffect.java:79)
mage.abilities.decorator.ConditionalAsThoughEffect.applies(ConditionalAsThoughEffect.java:73)
mage.abilities.effects.AsThoughEffectImpl.applies(AsThoughEffectImpl.java:44)
mage.abilities.effects.ContinuousEffects.asThough(ContinuousEffects.java:577)
mage.abilities.PlayLandAbility.canActivate(PlayLandAbility.java:28)
mage.players.PlayerImpl.canPlay(PlayerImpl.java:3125)
mage.players.PlayerImpl.findActivatedAbilityFromPlayable(PlayerImpl.java:3370)
mage.players.PlayerImpl.getPlayable(PlayerImpl.java:3584)
mage.players.PlayerImpl.getPlayableObjects(PlayerImpl.java:3713)
mage.server.game.GameSessionPlayer.getGameView(GameSessionPlayer.java:195)
mage.server.game.GameSessionWatcher.lambda$update$0(GameSessionWatcher.java:54)
java.util.Optional.ifPresent(Optional.java:159)
mage.server.game.GameSessionWatcher.update(GameSessionWatcher.java:54)
mage.server.game.GameController.updateGame(GameController.java:762)
mage.server.game.GameController.lambda$init$3aa0d15c$1(GameController.java:124)
mage.game.events.EventDispatcher.fireEvent(EventDispatcher.java:28)
mage.game.events.TableEventSource.fireTableEvent(TableEventSource.java:39)
mage.game.GameImpl.fireUpdatePlayersEvent(GameImpl.java:2547)
mage.game.GameImpl.playPriority(GameImpl.java:1398)
mage.game.turn.Step.priority(Step.java:61)
mage.game.turn.CombatDamageStep.priority(CombatDamageStep.java:31)
mage.game.turn.Phase.playStep(Phase.java:184)
mage.game.turn.Phase.play(Phase.java:89)
mage.game.turn.Turn.play(Turn.java:128)
mage.game.GameImpl.playTurn(GameImpl.java:911)
mage.game.GameImpl.play(GameImpl.java:821)
mage.game.GameImpl.start(GameImpl.java:797)
mage.server.game.GameWorker.call(GameWorker.java:34)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)

**Comment by JayDi85** [comment]
Fixed in #8090
