### ISSUE TITLE
Profane Transfusion - X/X token dies straight after resolution

### ISSUE THREAD

**Issue by johnmeat** [magefree/mage#7695]
![image](https://user-images.githubusercontent.com/64497504/112627862-0fd01d80-8e2a-11eb-8479-01d4357acd01.png)

After resolving X/X token is put into the graveyard straight away:
![image](https://user-images.githubusercontent.com/64497504/112627933-2b3b2880-8e2a-11eb-9e66-2f7bc3bada91.png)

**Comment by theelk801** [comment]
fixed with d4792e3
