### ISSUE TITLE
UI Feel-Bad: The Draft Deckbuilder "Submit in 1 Min" button gives an unbuilt deck if clicked with < 1 min on countdown timer

### ISSUE THREAD

**Issue by duelcastermage** [magefree/mage#7701]
If a player clicks the "Submit in 1 Min" button while they have < 1 Min left on their countdown timer, XMage still gives them an "unbuilt" deck.

From a UI perspective, I think it's clear that they should be able to play their games 1s with the deck they actively submitted.

**Comment by JayDi85** [comment]
What you mean by "unbuilt deck"? 

P.S. XMage saves current deck every 5 secs and auto-use it on time out.

**Comment by duelcastermage** [comment]
> What you mean by "unbuilt deck"?
> 
> P.S. XMage saves current deck every 5 secs and auto-use it on time out.

Sorry, I mean like they get a deck as if no submit button was pressed at all: ~90 cards, assortment of equal basic lands, etc.

I haven't experienced this myself, speaking on behalf of someone in my draft group that said this happened to them.

**Comment by JayDi85** [comment]
Possible use case:
* start building deck;
* press "submit in 1 minute" -- xmage start 1 minute timer to submit;
* continue to build deck -- xmage send deck every 5 seconds to server;
* timeout without submit -- xmage will use deck from last 5 seconds update (it can be from 1 to 5 seconds ago).

Conclusion: do not build deck in last seconds until timeout -- you can lost you changes from last 1-5 seconds.

**Comment by JayDi85** [comment]
Possible GUI improve: show "unsaved deck" warning text (if you changed deck but server do not get it from you in last 5 seconds).

**Comment by sprangg** [comment]
That auto save function is a fantastic feature and I think it fixes this issue https://github.com/magefree/mage/issues/2173

**Comment by sprangg** [comment]
I just tested the auto save function with the current stable release and it doesn't seem to work.

Tested by starting a sealed tournament vs a bot. Put 40 random cards in my deck and waited for the 6 minute timer to run out. Expected result was a 40 card deck, but got a deck that was over a hundred cards (presumably my whole sealed pool + some lands).

**Comment by xenohedron** [comment]
#10159 should fix this
