### ISSUE TITLE
Help with installing

### ISSUE THREAD

**Issue by anf123** [magefree/mage#7705]
I need help installing xmage. I cant run it as an executable jar. file for some reason. Currently on windows 10 and ive done some research but I just cant seem to figure this out. Any help is appreciated. This isnt a problem with xmage itself, it is a problem with a new laptop. I do have the most recent java installed

**Comment by JayDi85** [comment]
Download and unpack that file to any folder like `D:\games\xmage\`. Double click on run-launcher.
http://xmage.today/X/run.zip
