### ISSUE TITLE
Commander's Plate incorrectly displays "protection from multicolored"

### ISSUE THREAD

**Issue by Ebola16** [magefree/mage#7707]
[[Commander's Plate]] incorrectly displays "protection from multicolored". Commander is [[Heliod, Sun-Crowned]]

![2021-03-31](https://user-images.githubusercontent.com/17330088/113220150-ab112a80-9250-11eb-988b-ef9b892889e7.png)

**Comment by Alex-Vasile** [comment]
<img width="515" alt="Commander's Plate" src="https://user-images.githubusercontent.com/48962821/168721409-ebc599b4-d7b0-4e8b-ba15-4ea69994f48c.png">

This seems to have been fixed at some point since being posted.
