### ISSUE TITLE
Attacking token created by Sigiled Sword of Valeron doesn't interact with Linden, the Steadfast Queen

### ISSUE THREAD

**Issue by Ebola16** [magefree/mage#7708]
I'm not 100% sure but shouldn't the attacking token created with [[Sigiled Sword of Valeron]] trigger the effect of [[Linden, the Steadfast Queen]]? It currently doesn't.

**Comment by emerald000** [comment]
It should not. The token is never declared as an attacker, so Linden should not trigger.
