### ISSUE TITLE
Soulhunter Rakshasa not implemented correctly

### ISSUE THREAD

**Issue by johnmeat** [magefree/mage#7711]
Using reanimate on Soulhunter Rakshasa, causes it's triggered ability to trigger when it shouldn't, plus it seems to always do 5 damage when it should do damage equal to the number of swamps:

![image](https://user-images.githubusercontent.com/64497504/113418928-57245400-93be-11eb-9b4c-ecb4288a0e90.png)

**Comment by ldeluigi** [comment]
[[Soulhunter Rakshasa]]
