### ISSUE TITLE
Rana doesn't trigger when exiling a token creature

### ISSUE THREAD

**Issue by johnmeat** [magefree/mage#7712]
Exiling a 1/1 spirit token with the land, Ranar's ability doesn't trigger:
![image](https://user-images.githubusercontent.com/64497504/113419739-f72ead00-93bf-11eb-9cf5-fc5591723120.png)

Non-token creatures work fine:
![image](https://user-images.githubusercontent.com/64497504/113419879-3c52df00-93c0-11eb-966c-af7271b47460.png)

EDIT: this just seems to be just Ranar related i.e. exiling a token create with any effect doesn't cause Ranar to trigger.

**Comment by ldeluigi** [comment]
[[Ranar]]

**Comment by Tharkon** [comment]
I don't think Ranar ever triggers for anything on the battlefield anymore, not a token, not a card, not himself. Not with your permanents, not with your opponents'. It does trigger when exiling a Simian Spirit Guide from your hand or when Fortelling a card.

**Comment by jeffwadsworth** [comment]
This is fixed already.  Just wait for the next release.

**Comment by jeffwadsworth** [comment]
https://github.com/magefree/mage/commit/ffe75f77edc86a5b6d8864ba34e8ea5dda8027c0
