### ISSUE TITLE
Vish Kal, Blood Arbiter has incorrect ability text

### ISSUE THREAD

**Issue by Necamijat** [magefree/mage#7713]
Vish Kal's last ability in-game (i.e., when you hover over the card) states it gives +1/+1 to creatures instead of -1/-1 which is its Oracle text. The actual functionality of the ability is not affected (he gives -1/-1 as intended).

**Comment by ldeluigi** [comment]
[[Vish Kal, Blood Arbiter]]

**Comment by awjackson** [comment]
This was fixed by b0fdb4ef5a845f7cf8ca795cf184dd77dc988856
