### ISSUE TITLE
Bronnzehide Lion: "Wrong code usage. Don't use that method for permanents, use permanent.addAbility(a, source, game) instead"

### ISSUE THREAD

**Issue by Manu404** [magefree/mage#7718]
Initial situation (upkeep)
![image](https://user-images.githubusercontent.com/6137494/113570204-24739900-9614-11eb-8fee-f660e0ba64bd.png)

Turn Actions: 
- Activate Phyrexian Reclamation targeting Pawn of Ulamog, pay cost, resolve
- Sacrifice an eldrazi spawn
- Erebos double trigger (teysa)
- Opponent sacrifice bronzehide lion, lion trigger is on the stack
- Resolve => error message

Exception seems pretty straight forward to solve "Wrong code usage. Don't use that method for permanents, use permanent.addAbility(a, source, game) instead." Yet, here are all the infos I can give:

Gamelog:
1:36 PM: Turn 17 IAmTheLowest (26 - 28)
1:43 PM, T17.UP: IAmTheLowest loses 2 life from Phyrexian Reclamation [698]
1:43 PM, T17.UP: IAmTheLowest activates: return target creature card from your graveyard to its owner's hand. from Phyrexian Reclamation [698] targeting Pawn of Ulamog [53a]
1:44 PM, T17.UP: IAmTheLowest puts Pawn of Ulamog [53a] from graveyard into their hand
1:44 PM, T17.UP: IAmTheLowest sacrificed Eldrazi Spawn [8f0] (source: Eldrazi Spawn [8f0])
1:44 PM, T17.UP: IAmTheLowest - Ability triggers: Dictate of Erebos [488] - Whenever a creature you control dies, each opponent sacrifices a creature.
1:44 PM, T17.UP: IAmTheLowest - Ability triggers: Dictate of Erebos [488] - Whenever a creature you control dies, each opponent sacrifices a creature.
1:44 PM, T17.UP: Tinanielle sacrificed Qasali Pridemage [a3e] (source: Dictate of Erebos [488])
1:44 PM, T17.UP: Tinanielle sacrificed Bronzehide Lion [d6f] (source: Dictate of Erebos [488])
1:44 PM, T17.UP: Tinanielle - Ability triggers: Bronzehide Lion [d6f] - When Bronzehide Lion [d6f] dies, return it to the battlefield. It's an Aura enchantment with enchant creature you control and "  : Enchanted creature gains indestructible until end of turn," and it loses all other abilities. [BUG, stack window appear]
1:44 PM, T17.UP: Tinanielle puts Bronzehide Lion [d6f] from graveyard onto the Battlefield
1:44 PM, T17.DA: IAmTheLowest skip attack
1:44 PM, T17.M2: Rollback request denied by Tinanielle

Stacktrace

Game exception occurred: java.lang.IllegalArgumentException: Wrong code usage. Don't use that method for permanents, use permanent.addAbility(a, source, game) instead.
Server version: 1.4.48-V2 (build: 2021-02-27 18:40)
mage.cards.CardImpl.addAbility(CardImpl.java:313)
mage.cards.b.BronzehideLionContinuousEffect.apply(BronzehideLion.java:168)
mage.abilities.effects.ContinuousEffects.apply(ContinuousEffects.java:1082)
mage.game.GameState.applyEffects(GameState.java:602)
mage.game.GameImpl.applyEffects(GameImpl.java:1577)
mage.players.PlayerImpl.moveCards(PlayerImpl.java:4142)
mage.players.PlayerImpl.moveCards(PlayerImpl.java:4091)
mage.players.PlayerImpl.moveCards(PlayerImpl.java:4082)
mage.cards.b.BronzehideLionReturnEffect.apply(BronzehideLion.java:96)
mage.abilities.AbilityImpl.resolveMode(AbilityImpl.java:186)
mage.abilities.AbilityImpl.resolve(AbilityImpl.java:170)
mage.abilities.TriggeredAbilityImpl.resolve(TriggeredAbilityImpl.java:81)
mage.game.stack.StackAbility.resolve(StackAbility.java:86)
mage.game.GameImpl.resolve(GameImpl.java:1448)
mage.game.GameImpl.playPriority(GameImpl.java:1394)
mage.game.turn.Step.priority(Step.java:61)
mage.game.turn.Phase.playStep(Phase.java:184)
mage.game.turn.Phase.play(Phase.java:89)
mage.game.turn.Turn.play(Turn.java:128)
mage.game.GameImpl.playTurn(GameImpl.java:911)
mage.game.GameImpl.play(GameImpl.java:821)
mage.game.GameImpl.start(GameImpl.java:797)
mage.server.game.GameWorker.call(GameWorker.java:34)
java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
java.base/java.lang.Thread.run(Thread.java:834)

Thank you for xmage and have a great day ! :)

**Comment by JayDi85** [comment]
Fixed in #7564 (available in beta).
