### ISSUE TITLE
Bestowed Nighthowler bug

### ISSUE THREAD

**Issue by andyfries** [magefree/mage#772]
Nighthowler doesn't become a creature when the creature it is bestowed on dies. It stays on the battlefield as an Aura with no power or toughness.

**Comment by Nidhoegger** [comment]
Can confirm this, but for me it only happens when the bestowed creature is Anafenza and its tapped when it gets destroyed.

**Comment by LevelX2** [comment]
Related Forum post:  
http://www.slightlymagic.net/forum/viewtopic.php?f=70&t=17295&start=90#p181662
