### ISSUE TITLE
Endbringer bug

### ISSUE THREAD

**Issue by catman123456** [magefree/mage#7722]
Endbringer 3rd mode is not working for me.

![image](https://user-images.githubusercontent.com/64045003/113991339-5d805900-9820-11eb-9cdd-20e759fc930e.png)

![image](https://user-images.githubusercontent.com/64045003/113991480-7db01800-9820-11eb-9555-f3f22ad6418a.png)

**Comment by emerald000** [comment]
There's a Notion Thief in play.
