### ISSUE TITLE
Imprisoned in the Moon does not remove subtypes associated with removed types

### ISSUE THREAD

**Issue by alexander-novo** [magefree/mage#7724]
Just played [[Imprisoned in the Moon]] on an opponent's vampire commander. Then, on their turn, they used [[Sorin, Imperious Bloodlord]] to sacrifice their commander and bring it back to the command zone. But Sorin says

> You may sacrifice a Vampire.

And the rules say

> **205.1a** ... If an object’s card type is removed, the subtypes correlated with that card type will remain if they are also the subtypes of a card type the object currently has; otherwise, they are also removed for the entire time the object’s card type is removed.

Since their commander had the creature type removed, it should have had its Vampire subtype removed as well.

Comparing Imprisoned in the Moon to [[One with the Stars]] (a similar effect) reveals some issues with both cards:

https://github.com/magefree/mage/blob/754a5b38ebba104b83494629c1f3881020168b1e/Mage.Sets/src/mage/cards/i/ImprisonedInTheMoon.java#L93-L101

https://github.com/magefree/mage/blob/754a5b38ebba104b83494629c1f3881020168b1e/Mage.Sets/src/mage/cards/o/OneWithTheStars.java#L81-L95

One with the Stars calls `permanent.retainAllEnchantmentSubTypes(game);` which, contrary to its name, gets rid of all subtypes except enchantment subtypes (so Imprisoned in the Moon should probably call `retainAllLandSubTypes`). Also, Imprisoned in the Moon applies its effect on a specific layer, whereas One with the Stars does not - I suspect this might cause subtle bugs.

**Comment by theelk801** [comment]
This is fixed with 8399350
