### ISSUE TITLE
Trample + deathtouch doesn't work properly

### ISSUE THREAD

**Issue by Mikeyman88** [magefree/mage#7726]
I've given Ghalta deathtouch in several games and it never works as it should by dealing 1 dmg to each blocker and the rest to the player. This worked as it should one or two updates ago.

**Comment by theelk801** [comment]
this is fixed with 6091c7e

**Comment by Mikeyman88** [comment]
I don't get it, it's still not working...

**Comment by JayDi85** [comment]
@Mikeyman88 it fixed in beta, no in release yet.
