### ISSUE TITLE
Phantasmal Image on Card with Echo 

### ISSUE THREAD

**Issue by XmageUser666** [magefree/mage#7736]
Deranged Hermit has been cloned with Phantasmal Image. The Phantasmal Image version of the Deranged Hermit had to pay the echo cost multiple times.
[20210411_160223_Two Player Duel_2.txt](https://github.com/magefree/mage/files/6292061/20210411_160223_Two.Player.Duel_2.txt)
![echoHermitPhansamalImage_bug](https://user-images.githubusercontent.com/82326344/114309423-58a0fb00-9ae7-11eb-933f-6d655ab077e7.png)

**Comment by jeffwadsworth** [comment]
[[Deranged Hermit]]
[[Phantasmal Image]]
