### ISSUE TITLE
Hangerback Walker not producing tokens when sacked to Daretti, Scrap Savant

### ISSUE THREAD

**Issue by tylerFretz** [magefree/mage#7737]
Hangerback Walker with three counters on it produced no thopter tokens when sacked to Daretti's -2.

![xmage-bug-dareti](https://user-images.githubusercontent.com/47012039/114314924-b2df9300-9aca-11eb-945a-cb7a20934ab7.png)

**Comment by ldeluigi** [comment]
[[Hangerback Walker]] [[Daretti]]

**Comment by ldeluigi** [comment]
[[Hangarback Walker]]

**Comment by Alex-Vasile** [comment]
Duplicate of #8481
