### ISSUE TITLE
Rite of passage bug

### ISSUE THREAD

**Issue by catman123456** [magefree/mage#7740]
In the beta rite of passage is not putting counters on the creature. 

![image](https://user-images.githubusercontent.com/64045003/114580485-e2b6a400-9c4c-11eb-8e5a-d457f4861017.png)

**Comment by ldeluigi** [comment]
[[Rite of Passage]]

**Comment by ingmargoudt** [comment]
You seem to have a Vorinclex in play, halving the 1 P1P1 counter to 0.5, round down to 0 counters.

**Comment by ingmargoudt** [comment]
Test added for this scenario
