### ISSUE TITLE
Cyclonic Rift cascade

### ISSUE THREAD

**Issue by NapoleonBorn2Party** [magefree/mage#7741]
It is currently possible to overload cyclonic rift when you cascade into it, and it shouldn't. I assume the same is true for other overloadable cards and the cascade mechanic

**Comment by alexander-novo** [comment]
Dupe of #7410 and #6925.

**Comment by JayDi85** [comment]
Fixed with 6bc5a00e8ac604bd98e927bd88f03486830126a8
