### ISSUE TITLE
Effects which allow you to cast a spell with a given attribute need work

### ISSUE THREAD

**Issue by theelk801** [magefree/mage#7742]
Right now cards like [[Velomachus Lorehold]] and [[Hazoret's Undying Fury]] allow you to cast spells with specific stipulations from among exiled cards, but the current implementation only looks at the cards themselves and not at the spells that can be cast with them. 

These are no longer the same thing thanks to Adventures and MDFCs, so we should try to find a good way to handle this. The implementation of the cascade rule change manages to accomplish this this but we need something cleaner and more adaptable.

**Comment by JayDi85** [comment]
It already have. See cascade related code and usage hints from #7584 (91f4d7899269e7811da668da123e0d37dc5e6769). It's same as old code but you can work with card parts instead whole card:
- collect card parts, allows only specific part, call cast ability choose and cast.

From code comments:

> Force player to choose spell ability to cast. Use it in effects while casting cards.
> 
> Commands order in all use cases:
> * PlayFromNotOwnHandZone - true
> * chooseAbilityForCast
> * cast
> * PlayFromNotOwnHandZone - false

**Comment by JayDi85** [comment]
Also "CardUtil.getObjectParts" can find card parts, so you can use it to find and steam in your card specific code.

**Comment by theelk801** [comment]
I know, I'm saying the whole thing could be encapsulated better. It's a lot of work to do, which is why I opened this issue.
