### ISSUE TITLE
Game stuck when triggering Demonic Pact and Doom Foretold

### ISSUE THREAD

**Issue by Zerrisx** [magefree/mage#7753]
In my upkeep, I had a Demonic Pact with two options left and a Doom Foretold both trigger.  I clicked on the Doom Foretold (so it would be on the bottom of the stack), and the game pulled up my choices for Pact without removing the modal for trigger stacking.  This meant I could no longer click on anything or take any actions.

I could still mouse over cards and see arrows, as well as getting the highlight hover for the options... I just couldn't choose them.

![image](https://user-images.githubusercontent.com/59861365/115086010-14d83800-9ed1-11eb-8304-3b2cdb5f7f74.png)

**Comment by weirddan455** [comment]
This looks like #7638.  Workaround is to use the keyboard (1, 2, etc) to choose the mode.  I think we'd need to change the time the "order triggered abilities" dialog closes or make it non-modal to fix this bug but I haven't really looked at the GUI code to see exactly what it's doing.

**Comment by JayDi85** [comment]
Fixed in 46081d9185c489eddea1ca78ef4851585e76ae9c
