### ISSUE TITLE
Bugged while casting strategic planning

### ISSUE THREAD

**Issue by montegen10** [magefree/mage#7758]
Game exception occurred: java.lang.ClassCastException: mage.player.human.HumanPlayer cannot be cast to mage.filter.predicate.ObjectSourcePlayer
Server version: 1.4.48-V3-beta4 (build: 2021-04-17 10:42)
mage.filter.predicate.other.AnotherTargetPredicate.apply(AnotherTargetPredicate.java:21)
mage.filter.predicate.Predicates$AndPredicate.lambda$apply$0(Predicates.java:152)
java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1359)
java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499)
java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486)
java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
java.util.stream.ReferencePipeline.allMatch(ReferencePipeline.java:454)
mage.filter.predicate.Predicates$AndPredicate.apply(Predicates.java:152)
mage.filter.FilterImpl.match(FilterImpl.java:38)
mage.filter.common.FilterPermanentOrPlayer.match(FilterPermanentOrPlayer.java:58)
mage.target.common.TargetAnyTarget.canChoose(TargetAnyTarget.java:111)
mage.abilities.AbilityImpl.canChooseTargetAbility(AbilityImpl.java:931)
mage.abilities.AbilityImpl.canChooseTarget(AbilityImpl.java:919)
mage.abilities.SpellAbility.canActivate(SpellAbility.java:137)
mage.players.PlayerImpl.canPlay(PlayerImpl.java:3148)
mage.players.PlayerImpl.findActivatedAbilityFromPlayable(PlayerImpl.java:3393)
mage.players.PlayerImpl.getPlayable(PlayerImpl.java:3607)
mage.players.PlayerImpl.getPlayableObjects(PlayerImpl.java:3736)
mage.server.game.GameSessionPlayer.getGameView(GameSessionPlayer.java:202)
mage.server.game.GameSessionPlayer.lambda$ask$0(GameSessionPlayer.java:50)
java.util.Optional.ifPresent(Optional.java:159)
mage.server.game.GameSessionPlayer.ask(GameSessionPlayer.java:50)
mage.server.game.GameController.lambda$ask$12(GameController.java:785)
mage.server.game.GameController.perform(GameController.java:965)
mage.server.game.GameController.perform(GameController.java:958)
mage.server.game.GameController.ask(GameController.java:785)
mage.server.game.GameController.lambda$init$3aa0d15c$2(GameController.java:186)
mage.game.events.EventDispatcher.fireEvent(EventDispatcher.java:28)
mage.game.events.PlayerQueryEventSource.ask(PlayerQueryEventSource.java:36)
mage.game.GameImpl.fireAskPlayerEvent(GameImpl.java:2450)
mage.player.human.HumanPlayer.chooseUse(HumanPlayer.java:312)
mage.player.human.HumanPlayer.chooseUse(HumanPlayer.java:275)
mage.players.PlayerImpl.moveCardsToGraveyardWithInfo(PlayerImpl.java:4302)
mage.players.PlayerImpl.moveCards(PlayerImpl.java:4139)
mage.players.PlayerImpl.moveCards(PlayerImpl.java:4126)
mage.players.PlayerImpl.moveCards(PlayerImpl.java:4119)
mage.abilities.effects.common.LookLibraryControllerEffect.putCardsBack(LookLibraryControllerEffect.java:132)
mage.abilities.effects.common.LookLibraryControllerEffect.apply(LookLibraryControllerEffect.java:93)
mage.abilities.AbilityImpl.resolveMode(AbilityImpl.java:190)
mage.abilities.AbilityImpl.resolve(AbilityImpl.java:177)
mage.game.stack.Spell.resolve(Spell.java:236)
mage.game.GameImpl.resolve(GameImpl.java:1449)
mage.game.GameImpl.playPriority(GameImpl.java:1395)
mage.game.turn.Step.priority(Step.java:61)
mage.game.turn.Phase.playStep(Phase.java:184)
mage.game.turn.Phase.play(Phase.java:89)
mage.game.turn.Turn.play(Turn.java:128)
mage.game.GameImpl.playTurn(GameImpl.java:912)
mage.game.GameImpl.play(GameImpl.java:822)
mage.game.GameImpl.start(GameImpl.java:798)
mage.server.game.GameWorker.call(GameWorker.java:34)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)

**Comment by awjackson** [comment]
Same issue as #8086 and #9331
