### ISSUE TITLE
Omniscience reduces cost also if not cast from hand

### ISSUE THREAD

**Issue by LevelX2** [magefree/mage#776]
With Omniscience in play it's possible to cast a commander from command zone without paying it's mana costs.
Only the cost because the commander was already before has to be paid.

**Comment by ImperatorPrime** [comment]
This appears to function correctly. The commander price correctly goes up by 2 each time the commander goes back to the command zone, and the CMC of the commander is free.

**Comment by LevelX2** [comment]
http://tappedout.net/mtg-questions/omniscience-in-edh/
Sure that Omniscience let you cast your commander for free from the command zone?

**Comment by ImperatorPrime** [comment]
Whoops. I guess not.

**Comment by ImperatorPrime** [comment]
Fixed by 255d436148a8d2d80774d15d8bc998c6000f5f08. Unit test forthcoming when I get Omniscience to work in the framework.
