### ISSUE TITLE
The activated ability of Barbarian Bully doesn't work.

### ISSUE THREAD

**Issue by T-and-Em** [magefree/mage#7763]
https://scryfall.com/card/jud/79/barbarian-bully

Barbarian Bully has the text "Discard a card at random: Barbarian Bully gets +2/+2 until end of turn unless a player has Barbarian Bully deal 4 damage to them. Activate only once each turn." The discard works but the pump effect is not applied if all players decline to take the 4 damage.

**Comment by ldeluigi** [comment]
[[Barbarian Bully]]

**Comment by ldeluigi** [comment]
[[Barbarian Bully]]
