### ISSUE TITLE
Hoarding Dragon dies trigger is bugged

### ISSUE THREAD

**Issue by NoCoinFlips** [magefree/mage#7767]
Hello and thanks for the terrific work!

When I am using Sneak Attack or Purphoros Bronze-Blooded to put out Hoarding Dragon (https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=438700), the "dies" trigger does not put the chosen card in hand from exile. It's leaving the card in exile and thus not working as the card intended. 

Thank you again for XMage.

**Comment by theelk801** [comment]
fixed with 1abeec9
