### ISSUE TITLE
Couldn't Counter Logic Knot with Spell Snare

### ISSUE THREAD

**Issue by dpsommer** [magefree/mage#777]
Spell Snare seems to be miscalculating the cmc on spells with x in their mana costs.

**Comment by LevelX2** [comment]
What exactly happened?
Because CMC of X spells on the stack is calulated with the added X costs.
So it would be helpful to have the exact situation that did not work correctly.

**Comment by dpsommer** [comment]
This is my fault then; I was confused due to an article I read about Delve not affecting the cmc of spells, but since X is declared when the spell is cast, the cmc still becomes 2+X, regardless of how the cost is paid.

Sorry for the confusion.
