### ISSUE TITLE
Horobi and animate dead will generate infinite horobi triggers.

### ISSUE THREAD

**Issue by sagerin0** [magefree/mage#7772]
If you enchant horobi with animate dead, the game will generate infinite horobi triggers forcing you to infinitely put them onto the stack, timing you out

**Comment by ingmargoudt** [comment]
Confirmed, reproduced with a unit test.

**Comment by ldeluigi** [comment]
[[Horobi]] [[Animate Dead]]

**Comment by ldeluigi** [comment]
[[Horobi, Death]]

**Comment by ingmargoudt** [comment]
It looks like the AnimateDeadAttachToPermanentEffect targets, I changed it to not target , and the infinite loop was gone, but Horobi went to the graveyard.

**Comment by jeffwadsworth** [comment]
I noticed a while back that many effects get stuck in infinite loops...firing without end.
