### ISSUE TITLE
Attacking with Thrashing Mudspawn causes a java.lang.NullPointerException

### ISSUE THREAD

**Issue by T-and-Em** [magefree/mage#7774]
Screenshot of the game error:
![image](https://user-images.githubusercontent.com/76133892/115979124-60709d00-a5c7-11eb-9582-e56467b45d5c.png)

My opponent attacked with [[Thrashing Mudspawn]], damage was applied to me, it's triggered ability was put on the stack and the above exception was thrown.

**Comment by theelk801** [comment]
fixed with c3983da
