### ISSUE TITLE
lessons shown as creature in limited pool deck builder

### ISSUE THREAD

**Issue by Magicfanf** [magefree/mage#7789]
![Capture](https://user-images.githubusercontent.com/65718751/116748639-a37fa580-a9f7-11eb-912c-0009fdf2d439.PNG)
Academic probation in white is a lesson but not a creature, and still appears in the upper part of the build pool screen

**Comment by JayDi85** [comment]
Your current sorting mode is color (first: group cards by color; second: sort cards in same group by name). If you need a sort by card type (e.g. by creatures) then select another sort mode by "sort" button.

![shot_210501_000729](https://user-images.githubusercontent.com/8344157/116748941-3c6eea80-aa11-11eb-861a-11cd47e6fe48.png)

**Comment by Magicfanf** [comment]
indeed, but usually even by sorting by colors, the creatures are on one row, and the other spells on the next row

**Comment by JayDi85** [comment]
You are talking about battlefield card sorting and it can be changed by Preferences from main menu (enable/disable row split for creatures/other types). There are another preferences option to put non creature cards (like artifacts) to the right side of the battlefield.

Your first screenshot and my first comment was about Deck Editor. It's different.

**Comment by Magicfanf** [comment]
Thanks guys for checking this. I'll take another screenshot at the next opportunity.

**Comment by Magicfanf** [comment]
OK I checked for other lessons, they appear in the correct (lower) side of the screen
maybe it's just an issue for academic probation?

**Comment by JayDi85** [comment]
I've got that you are talking about -- it's about "creatures in separate row" sort options. Academic "sorted" as creature. It's a bug.

![shot_210506_011606](https://user-images.githubusercontent.com/8344157/117210424-b388f200-ae08-11eb-9a23-85f7f3e3ca2d.png)

**Comment by JayDi85** [comment]
Fixed by 67ee6fbf252d74718f7dbd3b946c63f3a3788dc1
