### ISSUE TITLE
Manifested creature with cloudform attached able to be blocked by non-flyer

### ISSUE THREAD

**Issue by ironmesh** [magefree/mage#779]
While playing, I had a manifest from Cloudform. I attacked into a field of non-flyers. The opponent then  blocked with a non-flyer. He tried to explain that the manifested creature didn't get flying because it had no name, but he is incorrect; and did not understand how manifest works. Could you please resolve this bug?

**Comment by ironmesh** [comment]
![manifest](https://cloud.githubusercontent.com/assets/8585996/6548653/4fad9432-c5d6-11e4-8d4c-8dc1d026bdf5.png)

**Comment by LevelX2** [comment]
This is probably already fixed by some adjustments to manifest.
@ImperatorPrime 
But if you check and can proove this would be nice.

**Comment by ImperatorPrime** [comment]
I'll have a look.

**Comment by ImperatorPrime** [comment]
Verified as working. Closing.
