### ISSUE TITLE
Emergent sequence at only 1 when playing it main 2, after playing a land main 1

### ISSUE THREAD

**Issue by Magicfanf** [magefree/mage#7791]
![Capture](https://user-images.githubusercontent.com/65718751/116759237-c5822380-aa09-11eb-924f-69559619490b.PNG)

**Comment by Magicfanf** [comment]
seems that actually, after a rollback, and playing both the land and the sequence main 1, the land gets only 1 counter

**Comment by theelk801** [comment]
has it been working correctly other times or always wrong?

**Comment by Magicfanf** [comment]
I think I have seen it working before
right now on top of this, it can't be tapped for mana

**Comment by theelk801** [comment]
alright, I'll have to investigate the counters issue but the mana ability issue should be fixed now

**Comment by Magicfanf** [comment]
OK thanks!
