### ISSUE TITLE
Dragon's Approach not working

### ISSUE THREAD

**Issue by Mekkiss** [magefree/mage#7796]
The second part of Dragon's Approach doesn't seem to work.
Steps to reproduce:

1. Have four or more copies of Dragon's Approach in your graveyard
2. Cast Dragon's Approach

Expected outcome: 3 damage to each opponent, prompt to exile four copies of Dragon's Approach to search for a dragon.
Actual outcome: 3 damage to each opponent.

Version 1.4.48-V3-beta5 (build 2021-04-25 18:48).

Looking at the code, it implies that it's expecting to target cards in graveyard, which is not correct (but I'm not a java coder, so I might be mistaken here).

**Comment by theelk801** [comment]
We use targeting for any kind of card selection, but use a `notTarget` flag for when it's not actually a target. The issue here was the exile source effect though, although I also accidentally left out the number of required targets. Thanks for the bug report.
