### ISSUE TITLE
error upon deck commit

### ISSUE THREAD

**Issue by Magicfanf** [magefree/mage#7806]
![image](https://user-images.githubusercontent.com/65718751/117353824-84c25880-aea8-11eb-8b2b-857794d7aaa2.png)

**Comment by Magicfanf** [comment]
OK seems to be a generic issue, not about the cards
it excludes each card in order of addition to the deck, when I remove the ones indicated in the error message, it just flags the next I added in the pool.

**Comment by Alex-Vasile** [comment]
This sort of issue happens when the server needs to be restarted.
