### ISSUE TITLE
Breena, the Demagogue [C21] triggered ability always puts counters on breena regardless of your choice

### ISSUE THREAD

**Issue by abeschwabacher** [magefree/mage#7809]
[Breena, the Demagogue](https://scryfall.com/card/c21/1/breena-the-demagogue)'s triggered ability correctly asks for a nontargeted creature choice, then ignores the choice and puts the counters on breena. The ability is very similar to the [Sword of Truth and Justice](https://scryfall.com/card/mh1/229/sword-of-truth-and-justice), and comparing the two it looks like Breena mistakenly puts the counters on the source instead of the target. The line at issue is this one:

`Permanent permanent = game.getPermanent(source.getSourceId());`

Sword of Truth and Justice's corresponding line is this:

`Permanent permanent = game.getPermanent(target.getFirstTarget());`

From what I can see, switching from referencing the ability's source to its target should fix the issue

**Comment by theelk801** [comment]
Yup, you got it on the nose. Thanks for finding one of the many "easter eggs" I hide in the code.
