### ISSUE TITLE
Vigor is SUPER bugged!

### ISSUE THREAD

**Issue by Dellg** [magefree/mage#7829]
[[Vigor]] affects every creature on the board, when it should affect only the creatures the player who control's vigor control.
Every attack makes big titans on the board! It's more chaotic than red itself.

![image](https://user-images.githubusercontent.com/26439598/118878958-8c312b00-b8c6-11eb-88c4-b9666c8e472f.png)

**Comment by theelk801** [comment]
fixed with 852aa56
