### ISSUE TITLE
Vigor counter application

### ISSUE THREAD

**Issue by nallstott** [magefree/mage#7836]
When the creature Vigor is on the field, and you swing with other creatures, damage is prevented, but ALL creatures dealt damage gain Vigor's  +1/+1 counters, not just the controlling player. Creatures are also killed by deathtouch, which shouldn't be possible since Vigor prevents damage.

**Comment by Grath** [comment]
Vigor applying to all creatures was fixed at the end of February, but there hasn't been a main version release in a while. Can you check if deathtouch kills creatures around Vigor on Beta?
