### ISSUE TITLE
[STX] Jadzi's alternate cost does not work on MDFCs

### ISSUE THREAD

**Issue by alexander-novo** [magefree/mage#7842]
![image](https://user-images.githubusercontent.com/11657716/119300570-d3e0eb00-bc15-11eb-8382-dc510c5071cb.png)

[[Jadzi, Oracle of Arcavios]]'s Magecraft ability's alternate cost does not work on MDFCs, as seen above. Ignore reduced cost, I had a cost reducer permanent on the battlefield.

**Comment by jeffwadsworth** [comment]
I noticed this out-of-hand while testing Intet, the Dreamer.  Same thing with split-cards, of course.  Just testing a fix.

**Comment by jeffwadsworth** [comment]
Nice.  This lead to the issue with Foretold issue as well.  Fix soon.

**Comment by alexander-novo** [comment]
I believe this should be fixed with the attached commit, so I'm closing
