### ISSUE TITLE
image for card Tactical Advantage replaced with old-boardered swamp 

### ISSUE THREAD

**Issue by michaelpaulsen** [magefree/mage#7860]
the card Tactical Advantage from ANA (the arena starter decks) is recognized as a card when I import it but the card image is an old-bordered swamp. 
so this happened 
![image](https://user-images.githubusercontent.com/14143704/120079912-00a85e80-c06b-11eb-9fab-5e9ff982826d.png)
as far as I can tell that is the only thing wrong 
How to reproduce: search Tactical Advantage in the deck editor and hover over it

**Comment by awjackson** [comment]
I can't reproduce this.
