### ISSUE TITLE
Problem Building for the First Time

### ISSUE THREAD

**Issue by crenshawda** [magefree/mage#787]
It looks like it's having trouble resolving some of the dependencies. I've included the relevant output of this command below run in the project root:

$ mvn -U clean install

Am I missing something?

-----
[INFO] ------------------------------------------------------------------------
[INFO] Building Mage Server 1.3.0
[INFO] ------------------------------------------------------------------------
Downloading: https://repository.jboss.org/nexus/content/groups/public/org/mage/mage-player-ai/1.3.0/mage-player-ai-1.3.0.pom
Downloading: file:///Users/crenshawda/NetBeansProjects/mage/Mage.Server/repository/org/mage/mage-player-ai/1.3.0/mage-player-ai-1.3.0.pom
Downloading: https://repo.maven.apache.org/maven2/org/mage/mage-player-ai/1.3.0/mage-player-ai-1.3.0.pom
[WARNING] The POM for org.mage:mage-player-ai:jar:1.3.0 is missing, no dependency information available
Downloading: https://repository.jboss.org/nexus/content/groups/public/org/mage/mage-player-aiminimax/1.3.0/mage-player-aiminimax-1.3.0.pom
Downloading: file:///Users/crenshawda/NetBeansProjects/mage/Mage.Server/repository/org/mage/mage-player-aiminimax/1.3.0/mage-player-aiminimax-1.3.0.pom
Downloading: https://repo.maven.apache.org/maven2/org/mage/mage-player-aiminimax/1.3.0/mage-player-aiminimax-1.3.0.pom
[WARNING] The POM for org.mage:mage-player-aiminimax:jar:1.3.0 is missing, no dependency information available
Downloading: https://repository.jboss.org/nexus/content/groups/public/org/mage/mage-player-ai-ma/1.3.0/mage-player-ai-ma-1.3.0.pom
Downloading: file:///Users/crenshawda/NetBeansProjects/mage/Mage.Server/repository/org/mage/mage-player-ai-ma/1.3.0/mage-player-ai-ma-1.3.0.pom
Downloading: https://repo.maven.apache.org/maven2/org/mage/mage-player-ai-ma/1.3.0/mage-player-ai-ma-1.3.0.pom
[WARNING] The POM for org.mage:mage-player-ai-ma:jar:1.3.0 is missing, no dependency information available
Downloading: https://repository.jboss.org/nexus/content/groups/public/org/mage/mage-tournament-boosterdraft/1.3.0/mage-tournament-boosterdraft-1.3.0.pom
Downloading: file:///Users/crenshawda/NetBeansProjects/mage/Mage.Server/repository/org/mage/mage-tournament-boosterdraft/1.3.0/mage-tournament-boosterdraft-1.3.0.pom
Downloading: https://repo.maven.apache.org/maven2/org/mage/mage-tournament-boosterdraft/1.3.0/mage-tournament-boosterdraft-1.3.0.pom
[WARNING] The POM for org.mage:mage-tournament-boosterdraft:jar:1.3.0 is missing, no dependency information available
Downloading: https://repository.jboss.org/nexus/content/groups/public/org/mage/mage-tournament-sealed/1.3.0/mage-tournament-sealed-1.3.0.pom
Downloading: file:///Users/crenshawda/NetBeansProjects/mage/Mage.Server/repository/org/mage/mage-tournament-sealed/1.3.0/mage-tournament-sealed-1.3.0.pom
Downloading: https://repo.maven.apache.org/maven2/org/mage/mage-tournament-sealed/1.3.0/mage-tournament-sealed-1.3.0.pom
[WARNING] The POM for org.mage:mage-tournament-sealed:jar:1.3.0 is missing, no dependency information available
Downloading: https://repository.jboss.org/nexus/content/groups/public/org/mage/mage-tournament-constructed/1.3.0/mage-tournament-constructed-1.3.0.pom
Downloading: file:///Users/crenshawda/NetBeansProjects/mage/Mage.Server/repository/org/mage/mage-tournament-constructed/1.3.0/mage-tournament-constructed-1.3.0.pom
Downloading: https://repo.maven.apache.org/maven2/org/mage/mage-tournament-constructed/1.3.0/mage-tournament-constructed-1.3.0.pom
[WARNING] The POM for org.mage:mage-tournament-constructed:jar:1.3.0 is missing, no dependency information available
Downloading: https://repository.jboss.org/nexus/content/groups/public/org/mage/mage-player-ai-draftbot/1.3.0/mage-player-ai-draftbot-1.3.0.pom
Downloading: file:///Users/crenshawda/NetBeansProjects/mage/Mage.Server/repository/org/mage/mage-player-ai-draftbot/1.3.0/mage-player-ai-draftbot-1.3.0.pom
Downloading: https://repo.maven.apache.org/maven2/org/mage/mage-player-ai-draftbot/1.3.0/mage-player-ai-draftbot-1.3.0.pom
[WARNING] The POM for org.mage:mage-player-ai-draftbot:jar:1.3.0 is missing, no dependency information available
Downloading: https://repository.jboss.org/nexus/content/groups/public/org/mage/mage-player-ai/1.3.0/mage-player-ai-1.3.0.jar
Downloading: https://repository.jboss.org/nexus/content/groups/public/org/mage/mage-player-aiminimax/1.3.0/mage-player-aiminimax-1.3.0.jar
Downloading: https://repository.jboss.org/nexus/content/groups/public/org/mage/mage-player-ai-ma/1.3.0/mage-player-ai-ma-1.3.0.jar
Downloading: https://repository.jboss.org/nexus/content/groups/public/org/mage/mage-tournament-boosterdraft/1.3.0/mage-tournament-boosterdraft-1.3.0.jar
Downloading: https://repository.jboss.org/nexus/content/groups/public/org/mage/mage-tournament-sealed/1.3.0/mage-tournament-sealed-1.3.0.jar
Downloading: https://repository.jboss.org/nexus/content/groups/public/org/mage/mage-tournament-constructed/1.3.0/mage-tournament-constructed-1.3.0.jar
Downloading: https://repository.jboss.org/nexus/content/groups/public/org/mage/mage-player-ai-draftbot/1.3.0/mage-player-ai-draftbot-1.3.0.jar
Downloading: file:///Users/crenshawda/NetBeansProjects/mage/Mage.Server/repository/org/mage/mage-player-ai/1.3.0/mage-player-ai-1.3.0.jar
Downloading: file:///Users/crenshawda/NetBeansProjects/mage/Mage.Server/repository/org/mage/mage-player-aiminimax/1.3.0/mage-player-aiminimax-1.3.0.jar
Downloading: file:///Users/crenshawda/NetBeansProjects/mage/Mage.Server/repository/org/mage/mage-player-ai-ma/1.3.0/mage-player-ai-ma-1.3.0.jar
Downloading: file:///Users/crenshawda/NetBeansProjects/mage/Mage.Server/repository/org/mage/mage-tournament-boosterdraft/1.3.0/mage-tournament-boosterdraft-1.3.0.jar
Downloading: file:///Users/crenshawda/NetBeansProjects/mage/Mage.Server/repository/org/mage/mage-tournament-sealed/1.3.0/mage-tournament-sealed-1.3.0.jar
Downloading: file:///Users/crenshawda/NetBeansProjects/mage/Mage.Server/repository/org/mage/mage-tournament-constructed/1.3.0/mage-tournament-constructed-1.3.0.jar
Downloading: file:///Users/crenshawda/NetBeansProjects/mage/Mage.Server/repository/org/mage/mage-player-ai-draftbot/1.3.0/mage-player-ai-draftbot-1.3.0.jar
Downloading: https://repo.maven.apache.org/maven2/org/mage/mage-player-ai/1.3.0/mage-player-ai-1.3.0.jar
Downloading: https://repo.maven.apache.org/maven2/org/mage/mage-player-aiminimax/1.3.0/mage-player-aiminimax-1.3.0.jar
Downloading: https://repo.maven.apache.org/maven2/org/mage/mage-player-ai-ma/1.3.0/mage-player-ai-ma-1.3.0.jar
Downloading: https://repo.maven.apache.org/maven2/org/mage/mage-tournament-boosterdraft/1.3.0/mage-tournament-boosterdraft-1.3.0.jar
Downloading: https://repo.maven.apache.org/maven2/org/mage/mage-tournament-sealed/1.3.0/mage-tournament-sealed-1.3.0.jar
Downloading: https://repo.maven.apache.org/maven2/org/mage/mage-tournament-constructed/1.3.0/mage-tournament-constructed-1.3.0.jar
Downloading: https://repo.maven.apache.org/maven2/org/mage/mage-player-ai-draftbot/1.3.0/mage-player-ai-draftbot-1.3.0.jar
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Mage Root .......................................... SUCCESS [  0.220 s]
[INFO] Mage Framework ..................................... SUCCESS [  1.260 s]
[INFO] Mage Common Classes ................................ SUCCESS [  0.084 s]
[INFO] Mage Plugins ....................................... SUCCESS [  0.004 s]
[INFO] Mage Counter Plugin ................................ SUCCESS [  0.027 s]
[INFO] Mage Client ........................................ SUCCESS [  1.391 s]
[INFO] Mage Theme Plugin .................................. SUCCESS [  0.176 s]
[INFO] Mage Sets .......................................... SUCCESS [ 14.069 s]
[INFO] Mage Server Plugins ................................ SUCCESS [  0.002 s]
[INFO] Mage Deck Constructed .............................. SUCCESS [  0.043 s]
[INFO] Mage Deck Limited .................................. SUCCESS [  0.013 s]
[INFO] Mage Game Commander Two Player ..................... SUCCESS [  0.012 s]
[INFO] Mage Game Commander Free For All ................... SUCCESS [  0.021 s]
[INFO] Mage Game Free For All ............................. SUCCESS [  0.012 s]
[INFO] Mage Game Two Player ............................... SUCCESS [  0.010 s]
[INFO] Mage Player Human .................................. SUCCESS [  0.021 s]
[INFO] Mage Game Tiny Leaders Two Player .................. SUCCESS [  0.009 s]
[INFO] Mage Server ........................................ FAILURE [ 18.916 s]
[INFO] Mage Server Console ................................ SKIPPED
[INFO] Mage Tests ......................................... SKIPPED
[INFO] Mage Updater ....................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 36.493 s
[INFO] Finished at: 2015-03-09T17:13:01-04:00
[INFO] Final Memory: 23M/129M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project mage-server: Could not resolve dependencies for project org.mage:mage-server:jar:1.3.0: The following artifacts could not be resolved: org.mage:mage-player-ai:jar:1.3.0, org.mage:mage-player-aiminimax:jar:1.3.0, org.mage:mage-player-ai-ma:jar:1.3.0, org.mage:mage-tournament-boosterdraft:jar:1.3.0, org.mage:mage-tournament-sealed:jar:1.3.0, org.mage:mage-tournament-constructed:jar:1.3.0, org.mage:mage-player-ai-draftbot:jar:1.3.0: Could not find artifact org.mage:mage-player-ai:jar:1.3.0 in jboss-public-repository (https://repository.jboss.org/nexus/content/groups/public) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :mage-server
-----

**Comment by Hotchmoney** [comment]
I'm having the same issue, I tried building in NetBeans as well. Perhaps the POM is out of date?

**Comment by emerald000** [comment]
Looks like some important stuff got deleted in the POM in commit 07db858f34b7ee806344a1494063a7aae0bd215e.

**Comment by LevelX2** [comment]
I added the deleted references again. Please try again to build after puliing again.

**Comment by crenshawda** [comment]
Things seem to work now, thanks!
