### ISSUE TITLE
Shadrix Silverquill: Triggered ability should be optional

### ISSUE THREAD

**Issue by rockydirtbag** [magefree/mage#7874]
[[Shadrix Silverquill]]

The trigger at the beginning of combat should allow picking exactly zero or exactly two options.

**Comment by BlueElectivire** [comment]
Looking at the code right now, the modes say you are able to choose none :
`// At the beginning of combat on your turn, you may choose two. Each mode must target a different player.
        Ability ability = new BeginningOfCombatTriggeredAbility(null, TargetController.YOU, false);
        ability.getModes().setMinModes(2);
        ability.getModes().setMaxModes(2);
        ability.getModes().setMaxModesFilter(filter0);
        ability.getModes().setMayChooseNone(true);`
are you sure that it does not work?

**Comment by rockydirtbag** [comment]
![image](https://user-images.githubusercontent.com/2265791/123535641-58e38680-d725-11eb-83a3-a653a355be19.png)

The cancel-option in this dialog doesn't actually cancel it. It just keeps popping up.
Maybe this parameter is a problem: ability.getModes().setMinModes(2); ?
Just guessing, I haven't actually worked on the xMage code yet.

**Comment by BlueElectivire** [comment]
I actually haven't started modifying the code either. When I get home I'll check it out. Thanks for checking!
