### ISSUE TITLE
Shivan Sand-Mage Cast

### ISSUE THREAD

**Issue by Barton1991** [magefree/mage#7896]
Game exception occurred: java.lang.IllegalStateException: Target wasn't handled. class:class mage.target.common.TargetPermanentOrSuspendedCard
Server version: 1.4.48-V3-beta8 (build: 2021-05-28 17:37)
mage.player.ai.ComputerPlayer.chooseTarget(ComputerPlayer.java:969)
mage.target.TargetImpl.chooseTarget(TargetImpl.java:319)
mage.target.Targets.chooseTargets(Targets.java:91)
mage.abilities.AbilityImpl.activate(AbilityImpl.java:357)
mage.players.PlayerImpl.triggerAbility(PlayerImpl.java:1504)
mage.game.GameImpl.checkTriggered(GameImpl.java:1867)
mage.game.GameImpl.checkStateAndTriggered(GameImpl.java:1825)
mage.game.GameImpl.playPriority(GameImpl.java:1364)
mage.game.turn.Step.priority(Step.java:61)
mage.game.turn.Phase.playStep(Phase.java:184)
mage.game.turn.Phase.play(Phase.java:89)
mage.game.turn.Turn.play(Turn.java:128)
mage.game.GameImpl.playTurn(GameImpl.java:912)
mage.game.GameImpl.play(GameImpl.java:822)
mage.game.GameImpl.start(GameImpl.java:798)
mage.server.game.GameWorker.call(GameWorker.java:34)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)

**Comment by JayDi85** [comment]
Fixed and improved in 7dcdc12c0fd42ff90b2324ebbd365052611cc751
