### ISSUE TITLE
GUI: Right-click function on the "choose which replacement effect to apply"

### ISSUE THREAD

**Issue by thefnitalian** [magefree/mage#7914]
How hard would it be to have right-click function on the "choose which replacement effect to apply" dialog box so that we can set which replacement effect we want to apply always similar to triggered abilities?

**Comment by alexander-novo** [comment]
+1. This would be nice to have for effects, like Lotus Cobra, that use the same dialog box for combo-ing off.

**Comment by thefnitalian** [comment]
I can’t tell you how many times I’ve had to click through hundreds of replacement effects from a similar source.

**Comment by JayDi85** [comment]
Implemented as remember answer checkbox, see details in https://github.com/magefree/mage/issues/6676#issuecomment-895016420
