### ISSUE TITLE
Path of Ancestry doesn't trigger for my commander

### ISSUE THREAD

**Issue by copperfield42** [magefree/mage#7917]
what the title said, [[Path of Ancestry]] doesn't trigger if I cast my commander with it.

Version: 1.4.48-dev (2021-06-12 18-19)

**Comment by alexander-novo** [comment]
Have you tried this with multiple commanders or just a specific one. There is an issue with effects detecting creature types of commanders with changeling: #7822

**Comment by copperfield42** [comment]
I noticed it with 2: [[Sythis, Harvest's Hand]] and [[Korvold, Fae-Cursed King]]

**Comment by JayDi85** [comment]
Fixed by 19693c94f7faf578a9c79cbaaea1bec782b7875a
