### ISSUE TITLE
Unable to Sacrifice Mountain to Flashback Lava Dart on Beta Client

### ISSUE THREAD

**Issue by Raspherbel** [magefree/mage#7918]
On the beta client, choosing a mountain to sacrifice to pay Lava Dart's Flashback cost gave the following error and rolled back the action. I was able to recreate the error by attempting to sacrifice the same nonbasic mountain on a different turn, and also by attempting to sacrifice a basic mountain. I was unable to recreate the error on the live build.

![image](https://user-images.githubusercontent.com/86109740/122557716-c810fa80-d002-11eb-9954-58e555a4769b.png)

**Comment by JayDi85** [comment]
Bug related to another card with spells count condition like [[Show of Confidence]]. Fixed by 9a4489b47f2af46e38519515e3f3c3f9334b9929
