### ISSUE TITLE
Cant Resolve Villianous Wealth in Beta Server

### ISSUE THREAD

**Issue by CastielsFallen1** [magefree/mage#7920]
i am testing a deck i just built against bots and the second game that i cast VW it wont let me resolve it

Game exception occurred: java.util.ConcurrentModificationException
Server version: 1.4.48-V3-beta9 (build: 2021-06-12 18:18)
java.util.ArrayList.writeObject(ArrayList.java:770)
sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.lang.reflect.Method.invoke(Method.java:498)
java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1140)
java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1496)
java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
java.util.ArrayList.writeObject(ArrayList.java:766)
sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.lang.reflect.Method.invoke(Method.java:498)
java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1140)
java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1496)
java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
java.util.LinkedHashMap.internalWriteEntries(LinkedHashMap.java:333)
java.util.HashMap.writeObject(HashMap.java:1363)
sun.reflect.GeneratedMethodAccessor11.invoke(Unknown Source)
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.lang.reflect.Method.invoke(Method.java:498)
java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1140)
java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1496)
java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
java.util.ArrayList.writeObject(ArrayList.java:766)
sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.lang.reflect.Method.invoke(Method.java:498)
java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1140)
java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1496)
java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
mage.remote.traffic.ZippedObjectImpl.zip(ZippedObjectImpl.java:31)
mage.remote.traffic.ZippedObjectImpl.<init>(ZippedObjectImpl.java:23)
mage.utils.CompressUtil.compress(CompressUtil.java:56)
mage.interfaces.callback.ClientCallback.setData(ClientCallback.java:57)
mage.interfaces.callback.ClientCallback.<init>(ClientCallback.java:26)
mage.interfaces.callback.ClientCallback.<init>(ClientCallback.java:20)
mage.server.game.GameSessionPlayer.lambda$ask$0(GameSessionPlayer.java:50)
java.util.Optional.ifPresent(Optional.java:159)
mage.server.game.GameSessionPlayer.ask(GameSessionPlayer.java:50)
mage.server.game.GameController.lambda$ask$12(GameController.java:785)
mage.server.game.GameController.perform(GameController.java:965)
mage.server.game.GameController.perform(GameController.java:958)
mage.server.game.GameController.ask(GameController.java:785)
mage.server.game.GameController.lambda$init$3aa0d15c$2(GameController.java:186)
mage.game.events.EventDispatcher.fireEvent(EventDispatcher.java:28)
mage.game.events.PlayerQueryEventSource.ask(PlayerQueryEventSource.java:36)
mage.game.GameImpl.fireAskPlayerEvent(GameImpl.java:2444)
mage.player.human.HumanPlayer.chooseUse(HumanPlayer.java:312)
mage.player.human.HumanPlayer.chooseUse(HumanPlayer.java:275)
mage.cards.v.VillainousWealthEffect.apply(VillainousWealth.java:79)
mage.abilities.AbilityImpl.resolveMode(AbilityImpl.java:190)
mage.abilities.AbilityImpl.resolve(AbilityImpl.java:177)
mage.game.stack.Spell.resolve(Spell.java:230)
mage.game.GameImpl.resolve(GameImpl.java:1449)
mage.game.GameImpl.playPriority(GameImpl.java:1395)
mage.game.turn.Step.priority(Step.java:61)
mage.game.turn.Phase.playStep(Phase.java:184)
mage.game.turn.Phase.play(Phase.java:89)
mage.game.turn.Turn.play(Turn.java:128)
mage.game.GameImpl.playTurn(GameImpl.java:912)
mage.game.GameImpl.play(GameImpl.java:822)
mage.game.GameImpl.start(GameImpl.java:798)
mage.server.game.GameWorker.call(GameWorker.java:34)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)

**Comment by JayDi85** [comment]
Must be fixed in d202278ccd6876f8113d26951e6bd018f6e9b792. Beta server updated too. So if you see that error again then report.
