### ISSUE TITLE
BETA .49v1 - Thrasios Rollback on Token Shenanigans

### ISSUE THREAD

**Issue by BlackWyvern** [magefree/mage#7921]
`Game exception occurred: java.util.ConcurrentModificationException
Server version: 1.4.49-V1-beta1 (build: 2021-06-19 04:44)
java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909)
java.util.ArrayList$Itr.next(ArrayList.java:859)
mage.abilities.AbilitiesImpl.containsKey(AbilitiesImpl.java:267)
mage.game.permanent.PermanentImpl.addAbility(PermanentImpl.java:375)
mage.abilities.effects.common.continuous.GainAbilityControlledEffect.apply(GainAbilityControlledEffect.java:115)
mage.abilities.effects.ContinuousEffectImpl.apply(ContinuousEffectImpl.java:112)
mage.abilities.effects.ContinuousEffects.apply(ContinuousEffects.java:1091)
mage.game.GameState.applyEffects(GameState.java:602)
mage.game.GameImpl.applyEffects(GameImpl.java:1578)
mage.game.GameImpl.playPriority(GameImpl.java:1379)
mage.game.turn.Step.priority(Step.java:61)
mage.game.turn.Phase.playStep(Phase.java:184)
mage.game.turn.Phase.play(Phase.java:89)
mage.game.turn.Turn.play(Turn.java:128)
mage.game.GameImpl.playTurn(GameImpl.java:912)
mage.game.GameImpl.play(GameImpl.java:822)
mage.game.GameImpl.start(GameImpl.java:798)
mage.server.game.GameWorker.call(GameWorker.java:34)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)
`

When using Thrasios's ability in Main 2 by sacrificing two treasure tokens made in the previous combat step (Via attacking with Magda, Goldspan Dragon, & Vault Robber [Plus Academy Manufactor & Parallel Lives]).

Activating Thrasios with these treasures on the opponent's next turn, using the exact same procedure functions properly.

**Comment by JayDi85** [comment]
Fixed in 1664ee01cf30af2e85d725d63f22808ffdf2d61f
