### ISSUE TITLE
Commander played count not resetting properly on new game

### ISSUE THREAD

**Issue by jbureau-qc** [magefree/mage#7922]
Hey guys, using the latest XMage version 1.4.48V2 and there is a bug when you play games that requires more than 1 win that if you played your commander during the first game and the game reset, sometimes the played count does not reset on the commander effectively making it cost 2 colorless or more before it was ever played in the current game only in the previous one.

**Comment by JayDi85** [comment]
I can't reproduce commander's bug with played count (tried new rounds, rollbacks and restarts by [[Karn Liberated]] -- all works in current dev version). There were some improves and changes in restart, ai and commander code (62d6675be67d2614372c75203d9ed23db66f32ac, b929b28e435a4ac05fa9f10c2282432ed01a6a55) -- so maybe it fixed it. Report again if you catch that bug in new release.
