### ISSUE TITLE
Cannot attach Bronzehide Lion Enchantment to Arasta of the Endless Web

### ISSUE THREAD

**Issue by DirtyConsole64** [magefree/mage#7930]
Game exception occurred: java.lang.IllegalArgumentException: Wrong code usage. Don't use that method for permanents, use permanent.addAbility(a, source, game) instead.
Server version: 1.4.48-V2 (build: 2021-02-27 18:40)
mage.cards.CardImpl.addAbility(CardImpl.java:313)
mage.cards.b.BronzehideLionContinuousEffect.apply(BronzehideLion.java:168)
mage.abilities.effects.ContinuousEffects.apply(ContinuousEffects.java:1082)
mage.game.GameState.applyEffects(GameState.java:602)
mage.game.GameImpl.applyEffects(GameImpl.java:1577)
mage.players.PlayerImpl.moveCards(PlayerImpl.java:4142)
mage.players.PlayerImpl.moveCards(PlayerImpl.java:4091)
mage.players.PlayerImpl.moveCards(PlayerImpl.java:4082)
mage.cards.b.BronzehideLionReturnEffect.apply(BronzehideLion.java:96)
mage.abilities.AbilityImpl.resolveMode(AbilityImpl.java:186)
mage.abilities.AbilityImpl.resolve(AbilityImpl.java:170)
mage.abilities.TriggeredAbilityImpl.resolve(TriggeredAbilityImpl.java:81)
mage.game.stack.StackAbility.resolve(StackAbility.java:86)
mage.game.GameImpl.resolve(GameImpl.java:1448)
mage.game.GameImpl.playPriority(GameImpl.java:1394)
mage.game.turn.Step.priority(Step.java:61)
mage.game.turn.Phase.playStep(Phase.java:184)
mage.game.turn.EndPhase.playStep(EndPhase.java:47)
mage.game.turn.Phase.play(Phase.java:89)
mage.game.turn.Turn.play(Turn.java:128)
mage.game.GameImpl.playTurn(GameImpl.java:911)
mage.game.GameImpl.play(GameImpl.java:821)
mage.game.GameImpl.start(GameImpl.java:797)
mage.server.game.GameWorker.call(GameWorker.java:34)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)

**Comment by DirtyConsole64** [comment]
I am playing vs a bot in Modern with 2 decks I've made myself, not randomly generated, if that helps. I am able to recreate this error every time I try to attach Bronzehide Lion as an Aura Enchantment to Arasta of the Endless Web.

**Comment by JayDi85** [comment]
Fixed in #7564
