### ISSUE TITLE
Brawl Format Rules without Card Legality Check

### ISSUE THREAD

**Issue by kmcgeejr** [magefree/mage#7931]
Hello,

Is it possible to set up a match using Brawl Format Rules (Command Zome, 25 life for 1v1, etc) without having the client check your deck legality? I want to play brawl using older cards.

Thanks.

**Comment by JayDi85** [comment]
You can use Freeform Unlimited Commander -- it allows any cards.

**Comment by kmcgeejr** [comment]
This still requires 100 cards, not 60.

**Comment by JayDi85** [comment]
Nope, Freeform Unlimited don't have any limits. It's a special format without any limits (any cards, any amount, no bans).

**Comment by kmcgeejr** [comment]
![image](https://user-images.githubusercontent.com/78182021/123022007-17f51600-d3a3-11eb-95ab-9937932ca154.png)

Not the error I was expecting, but an error nonetheless. Am I doing something wrong?
