### ISSUE TITLE
where is magical hack?

### ISSUE THREAD

**Issue by dmk218** [magefree/mage#7933]
i'd like this card to be added.

https://gatherer.wizards.com/Pages/Card/Details.aspx?name=magical%20hack

**Comment by theelk801** [comment]
Unfortunately xmage wasn't built with text-changing effects in mind, and it would take an astronomical amount of work to implement them

**Comment by JayDi85** [comment]
XMage's game engine have [limitation for text changing effects](https://github.com/magefree/mage/wiki/List-of-cards-that-will-not-be-implemented-on-Xmage#text-changing-effects), so some cards can't be implemented.
