### ISSUE TITLE
[Beta] Cannot sacrifice Mountain for Lava Dart

### ISSUE THREAD

**Issue by brbcoffee** [magefree/mage#7938]
Game State. Playing local beta server vs myself, just practicing. 

Modern. Merfolk vs UR Aggro. 

At endgame, error appears when I select to Sac a Mountain to Flashback Lava Dart (targeting Opponent's Face). Error pasted below.

Roll back to previous action appears successful. But error repeats if I try again. (even if I attempt to target a creature instead of Opponent's Face).

Thanks.

Error:
`Game exception occurred: java.lang.NullPointerException
Server version: 1.4.49-V1-beta1 (build: 2021-06-19 04:44)
mage.watchers.common.SpellsCastWatcher.watch(SpellsCastWatcher.java:53)
mage.watchers.Watchers.watch(Watchers.java:34)
mage.game.GameState.handleEvent(GameState.java:756)
mage.game.GameImpl.fireEvent(GameImpl.java:2835)
mage.players.PlayerImpl.cast(PlayerImpl.java:1214)
mage.players.PlayerImpl.activateAbility(PlayerImpl.java:1466)
mage.player.human.HumanPlayer.activateAbility(HumanPlayer.java:2038)
mage.player.human.HumanPlayer.activateAbility(HumanPlayer.java:2088)
mage.player.human.HumanPlayer.priority(HumanPlayer.java:1146)
mage.game.GameImpl.playPriority(GameImpl.java:1374)
mage.game.turn.Step.priority(Step.java:61)
mage.game.turn.Phase.playStep(Phase.java:184)
mage.game.turn.Phase.play(Phase.java:89)
mage.game.turn.Turn.play(Turn.java:128)
mage.game.GameImpl.playTurn(GameImpl.java:912)
mage.game.GameImpl.play(GameImpl.java:822)
mage.game.GameImpl.start(GameImpl.java:798)
mage.server.game.GameWorker.call(GameWorker.java:34)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)
`

**Comment by weirddan455** [comment]
Looks like same issue as #7918.  That's been fixed in 9a4489b47f2af46e38519515e3f3c3f9334b9929 which should be in the next beta release.

**Comment by brbcoffee** [comment]
thanks, i will start searching Issues before raising new one :)
