### ISSUE TITLE
MH2: Attacking with Terrirtorial Kavu and Goblin guide at the same time

### ISSUE THREAD

**Issue by Strangledoot** [magefree/mage#7944]
The prompt to order their attack triggers and the prompt to choose the mode on territorial kavu pop up at the same time and clicking to make a choice on either prompt does not work. 

This could be the case with Kavu and all creatures or it might just be goblin guide, but it's probably all attack triggers because any attack trigger would ask you to order the triggers

**Comment by timhae** [comment]
This seems to happen only when you need to select a specific trigger outcome, so for [these](https://scryfall.com/search?q=o%3Dwhenever+o%3Dattacks+o%3D%22choose+one%22&unique=cards&as=grid&order=name) creatures.

**Comment by weirddan455** [comment]
Looks like the same bug as #7638 and #7753

**Comment by JayDi85** [comment]
Fixed in 46081d9185c489eddea1ca78ef4851585e76ae9c
