### ISSUE TITLE
Xmage beta wrong client version issue

### ISSUE THREAD

**Issue by Pyrrhocore** [magefree/mage#7951]
Hello everyone,
I am trying to use the beta version to test some MH2 cards. Unfortunately once setup I am getting this error:
![Screenshot from 2021-06-30 09-07-49](https://user-images.githubusercontent.com/86709431/123919107-df49d380-d984-11eb-9a0d-2a4b2f83a46f.png)
I tried to update but doesn't help. May be to be specific I am running xmage on Linux Ubuntu 20.04 (never had such problem before on Ubuntu).
Also the standard xmage version works just fine.
Thanks for your help.

**Comment by JayDi85** [comment]
You are enter wrong server address. You must use `beta.xmage.today` server (BETA button in connection dialog), not de or us servers.

Beta server works fine.

**Comment by Pyrrhocore** [comment]
Thanks, you are right!
Sorry for the mistake.
Keep up with the great work!
