### ISSUE TITLE
AI does no longer play their Commander

### ISSUE THREAD

**Issue by tribo86** [magefree/mage#7955]
In a game versus AI, the AI does no longer play any Commander. I played round about 20 test games today with the newest version of xmage and it does not happen that the Commander came into play. In the versions before the behavior was different.

1.4.48-dev (2021-06-30 05-33)

**Comment by JayDi85** [comment]
Can you play your own commander?

**Comment by thefnitalian** [comment]
I haven't been able to play my commander after the update, so he isn't the only one.

**Comment by tribo86** [comment]
In one game I was not able to play my own commander, but in all others I was able.

**Comment by JayDi85** [comment]
It can be related to specific commander card/deck.

**Comment by tribo86** [comment]
I did try different ones. E.g. Ayula, Kathril or Zur as AI

**Comment by JayDi85** [comment]
Fixed by 62d6675be67d2614372c75203d9ed23db66f32ac
