### ISSUE TITLE
Blex, Vexing Pest BUG does not track/deal commander damage

### ISSUE THREAD

**Issue by EllNubNub** [magefree/mage#7956]
Commander damage is not tracked/dealt when he is the chosen commander.

Edit: New bug discovered, not sure what caused it exactly but i speculate. I was unable to cast Blex a second time from the command zone, he was exiled by Ugin's -x mass exile ability prior to the inability to cast.

**Comment by alexander-novo** [comment]
Dupe of #7843

**Comment by alexander-novo** [comment]
This has since been fixed and should be closed

**Comment by Alex-Vasile** [comment]
> This has since been fixed and should be closed

Did you also test the casting bug mentioned and found that it was also fixed?

**Comment by alexander-novo** [comment]
Oh I didn't actually notice that part
