### ISSUE TITLE
Void Mirror does not counter cascaded spell or 0-cost affinity spell

### ISSUE THREAD

**Issue by yunze-chia** [magefree/mage#7968]
Opponent played Shardless Agent and cascaded into Crashing Footfalls, Crashing Footfalls wasn't countered even though a Void Mirror was on the battlefield.

**Comment by yunze-chia** [comment]
Also encountered Void Mirror not countering a Frogmite casted for 0 via affinity.

**Comment by jeffwadsworth** [comment]
[[Shardless Agent]] [[Crashing Footfalls]] [[Void Mirror]]
