### ISSUE TITLE
Game Freezes After Mulligan

### ISSUE THREAD

**Issue by DominusMaximus** [magefree/mage#7969]
1.4.48-dev (2021-07-04 13-36)

After today's update, I can no longer play a game between two clients connected to the local server. After the 2nd player chooses to keep their hand, the client will remain at this position:

![xmage](https://user-images.githubusercontent.com/21368033/124396018-3f1de280-dcd5-11eb-82c8-8b40ec83c074.png)

Here are the logs:
 
[mageclient.log](https://github.com/magefree/mage/files/6760417/mageclient.log)
[magediag.log](https://github.com/magefree/mage/files/6760418/magediag.log)
[mageserver.log](https://github.com/magefree/mage/files/6760419/mageserver.log)

A related question, is there a way to download previous Beta versions?

**Comment by JayDi85** [comment]
Beta version workable.

Try:
1. Close client. Open images folder and delete all `*thumb.zip` files (`\xmage\mage-client\plugins\images`). Restart client and try to play.
2. If not helps then try to change game deck to another (for you and for opponent).

**Comment by DominusMaximus** [comment]
I tried both solutions and choosing a deck without an Escape card worked. Thank you.

**Comment by JayDi85** [comment]
Good. Escape ability fixed in 18db51eb4c92f0fd321497ac68df9d6cf17581ce and will be available with next update.
