### ISSUE TITLE
MDFC Instants/Sorceries don't have any effect

### ISSUE THREAD

**Issue by alexander-novo** [magefree/mage#7970]
![image](https://user-images.githubusercontent.com/11657716/124403631-3ab0f400-dcec-11eb-9d6b-8cf806d8fb81.png)

I cast [[Sea Gate Restoration]], it gets copied by [[Swarm Intelligence]], and both copies fail to resolve their effect. I included a screenshot of the battlefield to show that there are no effects preventing draws.

This is on the latest beta. No clue how consistently this happens - this is the first time it happened to me. I'll try testing it some more.

EDIT: I also just tried with [[Bala Ged Recovery]] and it didn't even let me target anything.

**Comment by jeffwadsworth** [comment]
Works fine for me.
![worksFineHere](https://user-images.githubusercontent.com/1496996/125200812-08dee680-e232-11eb-8e6c-28cbdab0bc70.jpg)

**Comment by alexander-novo** [comment]
I noticed your runtime is different than mine.

![image](https://user-images.githubusercontent.com/11657716/125208073-4305b380-e245-11eb-9ad3-81a2b4becb91.png)

Are you on the beta or live? This is a bug on beta.

**Comment by JayDi85** [comment]
`build: runtime` -- runing from current sources, e.g. run dev version. So it's the most actual.

**Comment by alexander-novo** [comment]
I can confirm it's still happening

![image](https://user-images.githubusercontent.com/11657716/125214501-66902480-e26c-11eb-96b2-759d9c4307b6.png)

**Comment by jeffwadsworth** [comment]
https://github.com/magefree/mage/commit/98aaa780812256b45d174384d870bb14457de9bf
