### ISSUE TITLE
The "put this ability always last" option for triggered abilities puts the ability before "put this ability always first" abilities

### ISSUE THREAD

**Issue by alexander-novo** [magefree/mage#7972]
![image](https://user-images.githubusercontent.com/11657716/124419160-d99c1700-dd11-11eb-82af-0a3ca64b103d.png)

When multiple triggered abilities trigger at the same time, if you right-click one and select "put this ability always last on the stack", first it immediately puts it on the stack (which you would normally want it to be put on the stack after every other ability has been put on the stack). Then, during subsequent triggers, it will actually be placed on the stack *before* any triggers which are automatically placed using the "put this ability always first" option, which isn't right.

In the example above, a bunch of "whenever you cast an instant or sorcery spell" triggers are shown on the stack, for two separate casts. In the first one, Jace's Sanctum is selected to "put this ability always last on the stack," but it ends up on the stack first because it was selected first (and even if I waited to select it - it can't be selected last, otherwise it will disappear without the option to auto-place). Then, all other options are placed with "put this ability always first". In the second set of triggers, Jace's Sanctum appears before any of the others.

**Comment by xenohedron** [comment]
Should be fixed by 921015e6 and related improves, reopen if can still confirm a bug
