### ISSUE TITLE
Sacrificing rollback bug

### ISSUE THREAD

**Issue by catman123456** [magefree/mage#7976]
![image](https://user-images.githubusercontent.com/64045003/124497322-a779cc00-dd88-11eb-9d80-287db28e67ce.png)

I believe  [[goblin bombardment]]  is causing the rollback issue with kresh & krovold

Game exception occurred: java.util.ConcurrentModificationException
Server version: 1.4.49-V1-beta3 (build: 2021-07-04 13:33)
java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909)
java.util.ArrayList$Itr.next(ArrayList.java:859)
mage.abilities.AbilitiesImpl.containsKey(AbilitiesImpl.java:267)
mage.game.permanent.PermanentImpl.addAbility(PermanentImpl.java:375)
mage.abilities.effects.common.continuous.GainAbilityControlledEffect.apply(GainAbilityControlledEffect.java:115)
mage.abilities.effects.ContinuousEffectImpl.apply(ContinuousEffectImpl.java:112)
mage.abilities.effects.ContinuousEffects.apply(ContinuousEffects.java:1091)
mage.game.GameState.applyEffects(GameState.java:641)
mage.game.GameImpl.applyEffects(GameImpl.java:1629)
mage.game.GameImpl.playPriority(GameImpl.java:1430)
mage.game.turn.Step.priority(Step.java:61)
mage.game.turn.Phase.playStep(Phase.java:184)
mage.game.turn.Phase.play(Phase.java:89)
mage.game.turn.Turn.play(Turn.java:128)
mage.game.GameImpl.playTurn(GameImpl.java:962)
mage.game.GameImpl.play(GameImpl.java:872)
mage.game.GameImpl.start(GameImpl.java:848)
mage.server.game.GameWorker.call(GameWorker.java:34)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)

**Comment by JayDi85** [comment]
Fixed in 1664ee01cf30af2e85d725d63f22808ffdf2d61f
