### ISSUE TITLE
Game crashes after keeping hand, only with a Hollow One Deck on BETA Server

### ISSUE THREAD

**Issue by nickmeyenburg** [magefree/mage#7980]
![grafik](https://user-images.githubusercontent.com/65238109/124623433-48957f00-de7c-11eb-9738-ddc3b8e5318d.png)
I get this error once both players decide to keep their hand. It only happens with this deck on the BETA server.

**Comment by nickmeyenburg** [comment]
looks like Ox of Agonas is the problem. Once I remove it from the deck, it works

**Comment by awjackson** [comment]
I can't reproduce this.
