### ISSUE TITLE
Soulfire Grand Master ability did not give life with Shrapnel Blast

### ISSUE THREAD

**Issue by filipebfs** [magefree/mage#799]
1.3.0dev2015-02-07v7 version

![sem titulo](https://cloud.githubusercontent.com/assets/2553458/6653340/e81c5268-ca6c-11e4-81ce-b220ec1b69ae.png)

**Comment by LevelX2** [comment]
Yes it's still an unsolved problem to get the correct reference for delayed damage dealing.

**Comment by LevelX2** [comment]
Should be fixed with 2015-03-14v5.
