### ISSUE TITLE
GUI: suggestion for dungeons (add button hints in choose/yes/no dialog)

### ISSUE THREAD

**Issue by copperfield42** [magefree/mage#7991]
![013 dungeon 1](https://user-images.githubusercontent.com/4504719/124993355-42d1a200-e012-11eb-9ec4-ae243e7f41e7.png)

for this part my suggestion just highlight the current room in negritas or some other color.

![image](https://user-images.githubusercontent.com/4504719/124993946-136f6500-e013-11eb-9244-6edd5bdde421.png)

for this part my suggestion is to include what the room does, maybe like include it in the message like:

choose which room to go to: Goblin Bazaar (create a Treasure Token) or Twisted Caverns (Target creature can’t attack until your next turn) 
[Goblin Bazaar] [Twisted Caverns]

**Comment by JayDi85** [comment]
Dungeon card hints and dialogs improved by bf2c4cac159cde4556b5eea578cbf605dc46f467 and b40e7222b3fa39c5389963103620e849cba759f8
