### ISSUE TITLE
Game Exception: NullPointerException

### ISSUE THREAD

**Issue by DominusMaximus** [magefree/mage#7993]
1.4.48-dev (2021-07-08 10-44)

In the following board state, casting [[Karn's Temporal Sundering]], targeting [[Toralf, God of Fury]], results in the following error upon resolution:

![Error](https://user-images.githubusercontent.com/21368033/125022422-aa0b4880-e04a-11eb-9ed5-a714eee53142.png)

`Game exception occurred: java.lang.NullPointerException
Server version: 1.4.49-V1-beta4 (build: 2021-07-08 10:44)
mage.players.PlayerImpl.moveCardToHandWithInfo(PlayerImpl.java:4259)
mage.players.PlayerImpl.moveCards(PlayerImpl.java:4177)
mage.players.PlayerImpl.moveCards(PlayerImpl.java:4117)
mage.players.PlayerImpl.moveCards(PlayerImpl.java:4108)
mage.cards.k.KarnsTemporalSunderingEffect.apply(KarnsTemporalSundering.java:76)
mage.abilities.AbilityImpl.resolveMode(AbilityImpl.java:194)
mage.abilities.AbilityImpl.resolve(AbilityImpl.java:181)
mage.game.stack.Spell.resolve(Spell.java:230)
mage.game.GameImpl.resolve(GameImpl.java:1504)
mage.game.GameImpl.playPriority(GameImpl.java:1450)
mage.game.turn.Step.priority(Step.java:61)
mage.game.turn.Phase.playStep(Phase.java:184)
mage.game.turn.Phase.play(Phase.java:89)
mage.game.turn.Turn.play(Turn.java:128)
mage.game.GameImpl.playTurn(GameImpl.java:966)
mage.game.GameImpl.play(GameImpl.java:876)
mage.game.GameImpl.start(GameImpl.java:852)
mage.server.game.GameWorker.call(GameWorker.java:34)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)`

The error doesn't occur if I target the [[Coldsteel Heart]] instead.

**Comment by alexander-novo** [comment]
I'm guessing this is an MDFC permanent issue - Karn's Temporal Sundering uses `getMainCard()` on the permanent it targets and then returns that card from the battlefield to the hand. For MDFCs the "main card" is the MDFC while what's actually on the battlefield is just one of the side cards, so when the game searched the battlefield for the permanent corresponding to that card, it fails to find it.
