### ISSUE TITLE
BETA Server "stuck"

### ISSUE THREAD

**Issue by calkno** [magefree/mage#7994]
I was able to connect, but when trying to create a new match it doesn't show up in the list and my username is not in the users list. The matches in the list have been in the same status for longer then the allotted threshold.
<img width="1226" alt="Screen Shot 2021-07-09 at 1 47 31 AM" src="https://user-images.githubusercontent.com/36138660/125029683-0aed4d80-e058-11eb-9c33-ed5a790afaa7.png">

**Comment by JayDi85** [comment]
server restarted

**Comment by ldeluigi** [comment]
happened again

**Comment by JayDi85** [comment]
restarted
