### ISSUE TITLE
The token created by Penumbra Spider has vigilance (it shouldn't)

### ISSUE THREAD

**Issue by duelcastermage** [magefree/mage#7997]
The 2/4 black spider created by Penumbra Spider has vigilance when it shouldn't.

**Comment by jeffwadsworth** [comment]
The code has it with Reach.  Vigilance is no where to be found.  What was your battlefield situation?

**Comment by duelcastermage** [comment]
> The code has it with Reach. Vigilance is no where to be found. What was your battlefield situation?

Pretty basic - I chump blocked a 6/6 flyer with the main card, which generated a 2/4 black spider token with reach. Next turn I attacked with the 2/4 spider token and it didn't tap.

**Comment by duelcastermage** [comment]
Update: I don't think this is a problem with Penumbra Spider per se. That might've been an expression of a problem where creatures *sometimes* don't tap when attacking. I noticed it in another game since then with another creature. I have no idea why the creatures don't tap sometimes, but it seems to be a thing that happens.

**Comment by JayDi85** [comment]
There were missing clear code related to attacking/tapped status changes (can cause some bugs potentially). Fixed in daed98fb0be21180100f5c3fb13897d27571d45a. BUT it affected only after game restart (e.g. on [[Karn Liberated]] ability usage). So I'm not sure that it related to the issue.
