### ISSUE TITLE
BETA Server Update/Restart Needed

### ISSUE THREAD

**Issue by calkno** [magefree/mage#8002]
Is there something I can do on my end to resolve this?

![Screen Shot 2021-07-11 at 4 00 19 PM](https://user-images.githubusercontent.com/36138660/125208550-2ecfaf80-e261-11eb-820a-e7b28c0fba15.png)

**Comment by JayDi85** [comment]
done

**Comment by JayDi85** [comment]
@calkno you can send me email to jaydi85@gmail.com next time restart.
