### ISSUE TITLE
Warp World Game Error

### ISSUE THREAD

**Issue by Cbemes** [magefree/mage#8008]
Game exception occurred: java.util.ConcurrentModificationException
Server version: 1.4.49-V1-beta5 (build: 2021-07-14 20:28)
java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909)
java.util.ArrayList$Itr.next(ArrayList.java:859)
mage.abilities.AbilitiesImpl.containsKey(AbilitiesImpl.java:267)
mage.game.permanent.PermanentImpl.addAbility(PermanentImpl.java:377)
mage.abilities.effects.common.continuous.GainAbilityControlledEffect.apply(GainAbilityControlledEffect.java:115)
mage.abilities.effects.ContinuousEffectImpl.apply(ContinuousEffectImpl.java:112)
mage.abilities.decorator.ConditionalContinuousEffect.apply(ConditionalContinuousEffect.java:101)
mage.abilities.effects.ContinuousEffects.apply(ContinuousEffects.java:1091)
mage.game.GameState.applyEffects(GameState.java:641)
mage.game.GameImpl.applyEffects(GameImpl.java:1633)
mage.game.GameImpl.playPriority(GameImpl.java:1434)
mage.game.turn.Step.priority(Step.java:61)
mage.game.turn.Phase.playStep(Phase.java:184)
mage.game.turn.Phase.play(Phase.java:89)
mage.game.turn.Turn.play(Turn.java:128)
mage.game.GameImpl.playTurn(GameImpl.java:966)
mage.game.GameImpl.play(GameImpl.java:876)
mage.game.GameImpl.start(GameImpl.java:852)
mage.server.game.GameWorker.call(GameWorker.java:34)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)

**Comment by Cbemes** [comment]
> Game exception occurred: java.util.ConcurrentModificationException
> Server version: 1.4.49-V1-beta5 (build: 2021-07-14 20:28)
> java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909)
> java.util.ArrayList$Itr.next(ArrayList.java:859)
> mage.abilities.AbilitiesImpl.containsKey(AbilitiesImpl.java:267)
> mage.game.permanent.PermanentImpl.addAbility(PermanentImpl.java:377)
> mage.abilities.effects.common.continuous.GainAbilityControlledEffect.apply(GainAbilityControlledEffect.java:115)
> mage.abilities.effects.ContinuousEffectImpl.apply(ContinuousEffectImpl.java:112)
> mage.abilities.decorator.ConditionalContinuousEffect.apply(ConditionalContinuousEffect.java:101)
> mage.abilities.effects.ContinuousEffects.apply(ContinuousEffects.java:1091)
> mage.game.GameState.applyEffects(GameState.java:641)
> mage.game.GameImpl.applyEffects(GameImpl.java:1633)
> mage.game.GameImpl.playPriority(GameImpl.java:1434)
> mage.game.turn.Step.priority(Step.java:61)
> mage.game.turn.Phase.playStep(Phase.java:184)
> mage.game.turn.Phase.play(Phase.java:89)
> mage.game.turn.Turn.play(Turn.java:128)
> mage.game.GameImpl.playTurn(GameImpl.java:966)
> mage.game.GameImpl.play(GameImpl.java:876)
> mage.game.GameImpl.start(GameImpl.java:852)
> mage.server.game.GameWorker.call(GameWorker.java:34)
> java.util.concurrent.FutureTask.run(FutureTask.java:266)
> java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> java.lang.Thread.run(Thread.java:748)

Here is another.

Game exception occurred: java.util.ConcurrentModificationException
Server version: 1.4.49-V1-beta5 (build: 2021-07-14 20:28)
java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909)
java.util.ArrayList$Itr.next(ArrayList.java:859)
mage.abilities.AbilitiesImpl.containsKey(AbilitiesImpl.java:267)
mage.game.permanent.PermanentImpl.addAbility(PermanentImpl.java:377)
mage.abilities.effects.common.continuous.GainAbilityControlledEffect.apply(GainAbilityControlledEffect.java:115)
mage.abilities.effects.ContinuousEffectImpl.apply(ContinuousEffectImpl.java:112)
mage.abilities.effects.ContinuousEffects.apply(ContinuousEffects.java:1091)
mage.game.GameState.applyEffects(GameState.java:641)
mage.game.permanent.token.TokenImpl.putOntoBattlefieldHelper(TokenImpl.java:342)
mage.game.permanent.token.TokenImpl.putOntoBattlefield(TokenImpl.java:203)
mage.game.permanent.token.TokenImpl.putOntoBattlefield(TokenImpl.java:167)
mage.game.permanent.token.TokenImpl.putOntoBattlefield(TokenImpl.java:137)
mage.abilities.effects.common.CreateTokenEffect.apply(CreateTokenEffect.java:77)
mage.abilities.AbilityImpl.resolveMode(AbilityImpl.java:194)
mage.abilities.AbilityImpl.resolve(AbilityImpl.java:178)
mage.abilities.TriggeredAbilityImpl.resolve(TriggeredAbilityImpl.java:120)
mage.game.stack.StackAbility.resolve(StackAbility.java:90)
mage.game.GameImpl.resolve(GameImpl.java:1504)
mage.game.GameImpl.playPriority(GameImpl.java:1450)
mage.game.turn.Step.priority(Step.java:61)
mage.game.turn.Phase.playStep(Phase.java:184)
mage.game.turn.Phase.play(Phase.java:89)
mage.game.turn.Turn.play(Turn.java:128)
mage.game.GameImpl.playTurn(GameImpl.java:966)
mage.game.GameImpl.play(GameImpl.java:876)
mage.game.GameImpl.start(GameImpl.java:852)
mage.server.game.GameWorker.call(GameWorker.java:34)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)

The deck is also slowed to a crawl and freezes my client all the time, it didn't used to do this in older versions of this deck.
The deck stacks a huge number of triggers on the stack which seems to break the game. Any Idea what I would need to do to give the client more resources to process the deck going off?

4 [AFR:200] Prosperous Innkeeper
3 [PSOI:233s] Tireless Tracker
3 [ELD:369] Gilded Goose
1 [STX:189] Galazeth Prismari
2 [CMA:170] Wood Elves
1 [PZ2:70649] Nesting Dragon
2 [MM2:156] Primeval Titan
3 [UMA:163] Eternal Witness
1 [PSOI:281s] Westvale Abbey
2 [PRM:59655] Gaea's Cradle
1 [ELD:388] Castle Garenbrig
2 [THB:330] Nyxbloom Ancient
1 [DKA:140] Huntmaster of the Fells
1 [V17:11] Huntmaster of the Fells
3 [RAV:150] Warp World
1 [THS:209] Xenagos, the Reveler
4 [OLGC:2017EU] Taiga
4 [IKO:250] Ketria Triome
4 [VMA:321] Tropical Island
3 [SLU:20] Riverglide Pathway
3 [ZNR:287] Cragcrown Pathway
2 [SLU:11] Barkchannel Pathway
2 [THB:254] Forest
1 [WAR:160] Finale of Devastation
1 [PC2:106] Thromok the Insatiable
1 [KHM:275] The World Tree
1 [THB:185] Nylea, Keen-Eyed
1 [IKO:328] Kogla, the Titan Ape
1 [CMR:673] Acidic Slime
1 [AFR:180] Druid Class

**Comment by jeffwadsworth** [comment]
https://github.com/magefree/mage/commit/d202278ccd6876f8113d26951e6bd018f6e9b792

**Comment by JayDi85** [comment]
Not actual any more
