### ISSUE TITLE
Volo's error

### ISSUE THREAD

**Issue by catman123456** [magefree/mage#8021]
When i cast man-o-war with 4 volo's and  4 Consecrated Sphinxes this happens 

![image](https://user-images.githubusercontent.com/64045003/126049690-0af93ce0-2911-4982-a961-a5a9f1557fea.png)

Game exception occurred: java.util.ConcurrentModificationException
Server version: 1.4.49-V1-beta5 (build: 2021-07-14 20:28)
java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909)
java.util.ArrayList$Itr.next(ArrayList.java:859)
mage.abilities.AbilitiesImpl.containsKey(AbilitiesImpl.java:267)
mage.game.permanent.PermanentImpl.addAbility(PermanentImpl.java:377)
mage.abilities.effects.common.continuous.GainAbilityControlledEffect.apply(GainAbilityControlledEffect.java:115)
mage.abilities.effects.ContinuousEffectImpl.apply(ContinuousEffectImpl.java:112)
mage.abilities.effects.ContinuousEffects.apply(ContinuousEffects.java:1091)
mage.game.GameState.applyEffects(GameState.java:641)
mage.game.GameImpl.applyEffects(GameImpl.java:1633)
mage.abilities.AbilityImpl.activate(AbilityImpl.java:241)
mage.abilities.ActivatedAbilityImpl.activate(ActivatedAbilityImpl.java:251)
mage.players.PlayerImpl.playAbility(PlayerImpl.java:1343)
mage.players.PlayerImpl.activateAbility(PlayerImpl.java:1469)
mage.player.ai.ComputerPlayer6.act(ComputerPlayer6.java:186)
mage.player.ai.ComputerPlayer7.priorityPlay(ComputerPlayer7.java:65)
mage.player.ai.ComputerPlayer7.priority(ComputerPlayer7.java:37)
mage.game.GameImpl.playPriority(GameImpl.java:1429)
mage.game.turn.Step.priority(Step.java:61)
mage.game.turn.Phase.playStep(Phase.java:184)
mage.game.turn.Phase.play(Phase.java:89)
mage.game.turn.Turn.play(Turn.java:128)
mage.game.GameImpl.playTurn(GameImpl.java:966)
mage.game.GameImpl.play(GameImpl.java:876)
mage.game.GameImpl.start(GameImpl.java:852)
mage.server.game.GameWorker.call(GameWorker.java:34)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)

**Comment by jeffwadsworth** [comment]
d202278

**Comment by JayDi85** [comment]
Not actual any more
