### ISSUE TITLE
Grist, the Hunger Tide issue

### ISSUE THREAD

**Issue by SofiaAViesti** [magefree/mage#8022]
First I would like to apologize in case this is a known issue (I couldn't find a known-bugs section so I will just post what I found)

What I did: EDH game versus CPU (3 players total), my commander was Grist. During the course of the game I activated Grist's abilities a few times.

What I found: Grist's first activated ability does increase loyalty by 1 as it should, but does not do anything else (doesn't create a token neither checks the top card of library, etc). Second and third abilities work as intended.

**Comment by theelk801** [comment]
thanks for the bug report, this was fixed with 2a367b7
