### ISSUE TITLE
DealsDamageToACreatureTriggeredAbility doesn't check if damaged permanent is a creature

### ISSUE THREAD

**Issue by Tharkon** [magefree/mage#8024]
After analysing a few different cards using this function:
Mirri the Cursed,, Stinkweed Imp, Obelisk Spider, Voracious Cobra, Kashi-Tribe Elite

I have come to the conclusion that DealsDamageToACreatureTriggeredAbility  does not actually verify that the damaged permanent is a creature.

I am also wondering why there is a DealsDamageToACreatureTriggeredAbility with a combatOnly parameter and a DealsCombatDamageToACreatureTriggeredAbility function. The latter does check if the permanent is a creature.
I think one should be a wrapper for the other, and of course the version that remains should check if the permanent is a creature.

P.s. I am fluent enough in Java to read the code, but not confident enough to make changes in it, nor knowledgeable enough about how Git works.

**Comment by jeffwadsworth** [comment]
It has a filter check inside the trigger for creature type.
https://github.com/magefree/mage/blob/master/Mage/src/main/java/mage/abilities/common/DealsDamageToACreatureTriggeredAbility.java

**Comment by Tharkon** [comment]
That filter is optional and I think it is meant to check for a creature's type, color or some other attribute.
The five cards above are implemented without a filter because they only care if it is a creature, which the name of the function implies, and that it is combat damage, which is a separate boolean.

**Comment by awjackson** [comment]
This was fixed by 79234b4059af972cb41496f0a49f564d52f7d239.
