### ISSUE TITLE
Feature Request: Intermediate Draft Pick Timer

### ISSUE THREAD

**Issue by duelcastermage** [magefree/mage#8033]
Hi guys,

Our group runs a lot of drafts and we are wishing there was a draft timer setting that was somewhere between Beginner and Regular. Beginner tends to be too slow and Regular a bit too fast.

The timer could also be more aggressively reduced starting with pick 9 since that's generally when cards are wheeling and have been seen before.

Thanks!

**Comment by JayDi85** [comment]
Current timeout for picks (in seconds):
https://github.com/magefree/mage/blob/754a5b38ebba104b83494629c1f3881020168b1e/Mage/src/main/java/mage/game/draft/DraftImpl.java#L29

Beginner mode increase timeouts by x2. It's possible to make more timeout modes and more special times (not 2x).

Can you make an example with timeouts (what's use cases and what's times you need)?

**Comment by duelcastermage** [comment]
If we take the regular mode as the base (1), then I would say to have the new Intermediate mode be 1.5x for the first 8 picks and 1x (same as regular) for picks 9-15 (because these cards are wheeling and would have been seen before by each drafter).

I believe this would be something like {113, 105, 98, 90, 83, 75, 68, 60, 35, 30, 25, 20, 15, 10, 5}.

Hopefully that makes sense.

**Comment by JayDi85** [comment]
Implemented by 400acae0c18b61985e7a2c11d2266dce15402f05

**Comment by duelcastermage** [comment]
Thank you so much!!

**Comment by T-and-Em** [comment]
Yes, thank you!

Looking at the changes - would the name for the shortest timer, currently "Profi" be better written as "Professional"?

https://github.com/magefree/mage/blob/400acae0c18b61985e7a2c11d2266dce15402f05/Mage/src/main/java/mage/game/draft/DraftOptions.java#L25
