### ISSUE TITLE
The draft pick timer calculates times incorrectly.

### ISSUE THREAD

**Issue by T-and-Em** [magefree/mage#8036]
The pick timer for each card uses this array to determine how long a user has to pick...
https://github.com/magefree/mage/blob/754a5b38ebba104b83494629c1f3881020168b1e/Mage/src/main/java/mage/game/draft/DraftImpl.java#L29

... with the array index calculated here for each pick...
https://github.com/magefree/mage/blob/754a5b38ebba104b83494629c1f3881020168b1e/Mage/src/main/java/mage/game/draft/DraftImpl.java#L273

... but with Beginner timing pick 1 starts at 70 seconds (times[1]) instead of the expected 75 seconds (times[0]) and times count down from there, with cards 14 and 15 both giving 5 seconds.

**Comment by JayDi85** [comment]
Fixed by 400acae0c18b61985e7a2c11d2266dce15402f05
