### ISSUE TITLE
Stalking Leonin's ability doesn't work

### ISSUE THREAD

**Issue by copperfield42** [magefree/mage#8038]
![017 madness text](https://user-images.githubusercontent.com/4504719/126574045-c404395f-909a-4d03-bd42-20138c026bce.png)

I can't use the ability of [[Stalking Leonin]], I can choose the player normally, computer 2 in this case, but I can't activate it to remove the attacking creature.

**Comment by jeffwadsworth** [comment]
The "reveal secretly chosen player" cost is bugged.  I will check it tomorrow.
