### ISSUE TITLE
New pick timer code shows incorrect pick number when drafting.

### ISSUE THREAD

**Issue by T-and-Em** [magefree/mage#8039]
The DraftPanel code is still expecting cards to count from 1, so the first pick is now shown as 0.

![image](https://user-images.githubusercontent.com/76133892/126765037-2b799336-2ba3-42f4-b4c7-75fe14dc1e84.png)

Offending line:
https://github.com/magefree/mage/blob/400acae0c18b61985e7a2c11d2266dce15402f05/Mage.Client/src/main/java/mage/client/draft/DraftPanel.java#L161

Fix:

`this.txtCardNo.setText(Integer.toString(draftView.getCardNum() + 1));`

**Comment by JayDi85** [comment]
Fixed by 06ae494c5b0695d8a5ca8af5bf7b97abfb4fbf85
