### ISSUE TITLE
Announced X= label annotation not working(?) for Engineered Explosives

### ISSUE THREAD

**Issue by jathanasiou** [magefree/mage#8046]
When [[Engineered Explosives]] has been cast with X=1, it does get the appropriate counter on it. However, the annotation for it displays X=0 instead.

Not sure if this is a bug, because admittedly it's CMC/MV in the battlefield is/should be 0 indeed. I am not entirely certain about the intent of this annotation to be honest. If it is a reminder about how the permanent was cast, then it should be displaying 1 I guess, but usually permanents themselves have a way to "remember" that, either via power/toughness setting or via counters, like EE does.

![Screenshot_20210725_114350](https://user-images.githubusercontent.com/8679925/126896845-5b9f285c-1f04-4a1e-8c3e-b56f427e987c.png)

**Comment by JayDi85** [comment]
> CMC/MV in the battlefield is/should be 0 indeed

That's right by mtg rules. But card icon uses for info, so it must show x value from original spell. I'll look at it.

**Comment by JayDi85** [comment]
Fixed by cdf6fbb5d894c18fc63707363a04df0067f3bdb7
