### ISSUE TITLE
Ragavan, Nimble Pilferer problem when playing for Dash

### ISSUE THREAD

**Issue by Tokyobylka** [magefree/mage#8047]
Several times I have played Ragavan, Nimble Pilferer for dash cost and when my opponent killed him, at the end of the turn he returned safely from my graveyard to my hand, although the card says that he must return to my hand from the battlefield. This is a bug that needs fixing. Thanks.

**Comment by jeffwadsworth** [comment]
[[Ragavan, Nimble Pilferer]]
