### ISSUE TITLE
Great Henge might be bugged (ConcurrentModificationException)

### ISSUE THREAD

**Issue by EllNubNub** [magefree/mage#8048]
Had a glitch happen when i played the great henge after cascading a bunch of cards prior. not sure what caused it to bug out i had too many things in play for me to pinpoint anything.

Game exception occurred: java.util.ConcurrentModificationException
Server version: 1.4.49-V1 (build: 2021-07-24 21:46)
java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909)
java.util.ArrayList$Itr.next(ArrayList.java:859)
mage.abilities.AbilityImpl.activateAlternateOrAdditionalCosts(AbilityImpl.java:472)
mage.abilities.AbilityImpl.activate(AbilityImpl.java:277)
mage.abilities.ActivatedAbilityImpl.activate(ActivatedAbilityImpl.java:251)
mage.game.stack.Spell.activate(Spell.java:131)
mage.players.PlayerImpl.cast(PlayerImpl.java:1213)
mage.players.PlayerImpl.activateAbility(PlayerImpl.java:1469)
mage.player.human.HumanPlayer.activateAbility(HumanPlayer.java:2038)
mage.player.human.HumanPlayer.activateAbility(HumanPlayer.java:2061)
mage.player.human.HumanPlayer.priority(HumanPlayer.java:1146)
mage.game.GameImpl.playPriority(GameImpl.java:1442)
mage.game.turn.Step.priority(Step.java:61)
mage.game.turn.Phase.playStep(Phase.java:184)
mage.game.turn.Phase.play(Phase.java:89)
mage.game.turn.Turn.play(Turn.java:128)
mage.game.GameImpl.playTurn(GameImpl.java:968)
mage.game.GameImpl.play(GameImpl.java:878)
mage.game.GameImpl.start(GameImpl.java:854)
mage.server.game.GameWorker.call(GameWorker.java:34)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)

**Comment by jeffwadsworth** [comment]
[[The Great Henge]]

**Comment by JayDi85** [comment]
Bug discussion in the d202278ccd6876f8113d26951e6bd018f6e9b792

**Comment by JayDi85** [comment]
Not actual any more
