### ISSUE TITLE
Xmage Not working

### ISSUE THREAD

**Issue by grandseraph** [magefree/mage#805]
Anytime i open XMAGE to try and play, on the launcher it says
"Reading config from http://xmage.info/xmage/config.json
  Error reading config from http://xmage/config.json
  possible causes: Site is offline or internet connection is unavailable."

 My internet connection is fine. And once launched i get an Error saying
(Java.lang.numberformatexception: For input string "")

Does anybody know a fix for this?

**Comment by LevelX2** [comment]
Seems like your setting for the XMage->XMage home is wrong.
Open the XMage setting in the launcher and check if the follwing URL is set:
http://xmage.info/xmage

**Comment by LevelX2** [comment]
I guess it's fixed.
