### ISSUE TITLE
Extraplanar Lens

### ISSUE THREAD

**Issue by catman123456** [magefree/mage#8050]
Extraplanar Lens is not working when I exiled a snow-covered land

**Comment by jeffwadsworth** [comment]
[[Extraplanar Lens]]

**Comment by ingmargoudt** [comment]
Looking into it,

**Comment by theelk801** [comment]
might be related to #7679

**Comment by ingmargoudt** [comment]
Did not know that issue though.
Problem was that in the getPlayer method, tappedPermanent was retrieved, but Extraplanar Lens did not set that.
