### ISSUE TITLE
Netherborn Phalanx bugged

### ISSUE THREAD

**Issue by mitchelljoneill** [magefree/mage#8051]
_Hi this is my first git post on the Xmage GitHub. Please let me know if I did something wrong, if so I am sorry!_ 

 Netherborn Phalanx is not hitting every single player in matches. 
 
 When Netherborn Phalanx enters the battlefield it usually only hits one player at random, I do not know why it is doing this but i have had it happen around 10 different times so I know it's not some effect on the battlefield that I missed.
 
It's gotten to the point where I just want to cut the card from my deck.

**Comment by ingmargoudt** [comment]
Seems like the effect returns after the first opponent lost life. Will make a fix for this.

**Comment by ingmargoudt** [comment]
fixed in c21b64fcbf
