### ISSUE TITLE
Balance did not count creatures

### ISSUE THREAD

**Issue by rexelallan** [magefree/mage#8052]
![image](https://user-images.githubusercontent.com/42716000/127054643-37ca9075-fd21-45de-9480-ff93e04442c5.png)

**Comment by jeffwadsworth** [comment]
The "balance effect" is buggy.  It also has issues if the lowest number is zero for a checked zone.

**Comment by jeffwadsworth** [comment]
https://github.com/magefree/mage/issues/7950

**Comment by weirddan455** [comment]
Fixed in https://github.com/magefree/mage/commit/aa4397dee5b76198c9145a6221a3c5c026e60281
