### ISSUE TITLE
Verdant Command bug

### ISSUE THREAD

**Issue by c0akz** [magefree/mage#8054]
Verdant command's "counter target planeswalker loyalty ability" not working

**Comment by theelk801** [comment]
are you unable to target the ability or does it just not counter anything?

**Comment by c0akz** [comment]
It won't even let the ability be targeted. It's like the mode doesn't exist.
    On Monday, July 26, 2021, 10:46:17 PM EDT, Evan Kranzler ***@***.***> wrote:  
 
 


are you unable to target the ability or does it just not counter anything?

**Comment by c0akz** [comment]
Thanks!
    On Monday, July 26, 2021, 10:51:28 PM EDT, Evan Kranzler ***@***.***> wrote:  
 
 


Closed #8054 via 978893a.
