### ISSUE TITLE
Permanents that are exiled from play via Dauthi Voidwalker don't get void counters

### ISSUE THREAD

**Issue by stevedavidmusic** [magefree/mage#8056]
- Cards exiled from play via Dauthi Voidwalker don't get void counters

- I tested discarding from hand / library to graveyard and those get void counters as expected.

**Comment by jeffwadsworth** [comment]
https://github.com/magefree/mage/issues/7959

**Comment by Alex-Vasile** [comment]
Closing as duplicate
