### ISSUE TITLE
Mage general issues (Mac)

### ISSUE THREAD

**Issue by treetoad** [magefree/mage#806]
Whenever I open the launcher, it says that it is my first time playing and re-dowloads a couple of documents. Also, whenever I open it again, all the image files do not show up and I have to re-dowload the whole 18000 card images each time I want to play. Sometimes the client also disconnects randomly then reconnects a second or two later.

Great program tho, 1000 times better than MTGO!

Way to go team!

**Comment by LevelX2** [comment]
The state of installation is saved to the installed.properties file in the launcher directory.
So could you please post the content of this file after you run through the install process.
On your system the launcher may not update this file or may not be able to read it.

**Comment by LevelX2** [comment]
Closed because of missing feedback.
