### ISSUE TITLE
Captivating Glance doesn't work properly

### ISSUE THREAD

**Issue by awjackson** [magefree/mage#8062]
[[Captivating Glance]]

>At the beginning of your end step, clash with an opponent. If you win, gain control of enchanted creature. Otherwise, that player gains control of enchanted creature

The "otherwise" clause of this ability doesn't seem to work. Once [[Captivating Glance]]'s controller has won a clash and gained control of the creature, the clash ability continues to trigger on future turns, but regardless of the result of the clashes the opponent never (re)gains control of the creature.

**Comment by Jipsu** [comment]
I'll comment here because this might be a related issue: permanent doesn't change ownership to opponent (maybe if the change is conditional). Case in point [[shuriken]] from a non-ninja, non-shapeshifter creature.
