### ISSUE TITLE
Cabal Therapy: Card picker dialog is occasionally empty

### ISSUE THREAD

**Issue by jumpinjackie** [magefree/mage#8065]
Version: 1.4.49-V1 client connecting to same server version

I was goldfishing a Hogaak deck in a local game against AI.

The sequence of turns was:

T1 - Opponent: Play Karakas

T1 - Me: Play Badlands, cast Stitcher's Supplier

3 cards get milled, one of which is Cabal Therapy

I then proceed to flashback Cabal Therapy targeting the opponent, sacrificing the Stitcher's Supplier, its trigger mills 3 more cards and then I resolve the Cabal Therapy.

For reasons not known, the card picker dialog that shows is empty, preventing me from naming a nonland card and the picker dialog is such that it cannot be dismissed/canceled, thus this game is effectively locked as a result with no way to get out of this state without closing the XMage client

As per the title of this issue, this seems to be occasionally happening as I have casted Cabal Therapy in other games where this empty card picker dialog doesn't happen, but I haven't yet collected enough data points to determine if this is only happening when flashed back or some other condition.

Screenshot of game state below:

![2021-07-28 22_55_58-Window](https://user-images.githubusercontent.com/563860/127325872-bb5e9c80-fd2e-49be-89b8-390648f10705.png)

**Comment by JayDi85** [comment]
* Original problem: server with low memory can't process some requests with too much data (example: find all cards names from database). Steps to reproduce: run local server under 500Mb settings and use the card like [[Brain Pry]];
* So client gets empty list and can't choose from it;
* Now (62474c12a4589e3f26b77a10234a588cc77d00db) choose dialog processing that type of error and you can press cancel button on empty list.
