### ISSUE TITLE
Kithkin Mourncaller's triggered ability, "Whenever an attacking Kithkin or Elf is put into your graveyard from the battlefield, you may draw a card.", doesn't trigger when an attacking Elf or Kithkin is put into your graveyard.

### ISSUE THREAD

**Issue by T-and-Em** [magefree/mage#8067]
With a [[Kithkin Mourncaller]] (owned and controlled by me) on the battlefield I tried the following - in all cases the ability did not trigger.
- Attacked my opponent with Llanowar Elves. Elves died to combat damage.
- Killing my attacking Llanowar Elves with Fatal Push.
- Attacked with a second Kithkin Mourncaller which died to combat damage.

**Comment by jeffwadsworth** [comment]
This one is a bit tricky because the LKI of the creature on the battlefield does not have it attacking.

**Comment by awjackson** [comment]
Does [[Kardur, Doomscourge]] work in xmage? If it does, you can use the same implementation but check that the dead creature is owned (not controlled) by Mourncaller's controller. I'm pretty sure that "[...]creature is put into your graveyard" is functionally the same as "[...]creature you own dies".

**Comment by jeffwadsworth** [comment]
Yeah, that one uses the attacking predicate and this one uses the filterAttackingCreature filter.  I will check it tomorrow.

**Comment by jeffwadsworth** [comment]
Well, Kardur, Doomscourge does not work either.  So something was broken along the way.

**Comment by jeffwadsworth** [comment]
https://github.com/magefree/mage/pull/7495
