### ISSUE TITLE
Hoarding Dragon does not let you retrieve the exiled card.

### ISSUE THREAD

**Issue by EllNubNub** [magefree/mage#8068]
Hoarding Dragon when dies, after had entering and exiling the chosen artifact card from your deck, gives you the option to return the card to your hand or leave it in exile and when you click return to hand it stays in exile and nothing happens. Also tried to rollback but the window hoarding dragon brings up when it exiles the artifact stayed there with the artifact i chose still sitting there without the ability to close the window.

**Comment by jeffwadsworth** [comment]
[[Hoarding Dragon]]
