### ISSUE TITLE
Mode Request: Swiss Rich Man (Chaos) tournament

### ISSUE THREAD

**Issue by duelcastermage** [magefree/mage#8070]
Currently Rich Man draft is only available as an elimination tournament. It would be great to have a Swiss option as well. Thanks!

**Comment by JayDi85** [comment]
PR with Rich Man Swiss Draft -- #7804. Are you talking about it?

**Comment by duelcastermage** [comment]
This does not seem to be available, at least from the menu options with version 1.4.49-V1 
![image](https://user-images.githubusercontent.com/46700039/127569533-92a08f16-3df7-49a7-8a03-c2e53566f0d5.png)

**Comment by JayDi85** [comment]
I know. It's not merged yet.

**Comment by duelcastermage** [comment]
Oh, sorry I misunderstood. Yes, that seems like it would address my request - thanks.

**Comment by xenohedron** [comment]
#7804 has been merged
