### ISSUE TITLE
Skeletal swarming bugged

### ISSUE THREAD

**Issue by grandogarndo** [magefree/mage#8072]
At first I was like "wow this card is great! I have just a couple skeletons out and I'm attacking for lethal!!!!" but then I re-read the card, and getting +50 +50 for just 7 or 8 skeletons on the board wasn't correct. picture here for proof:

![image](https://user-images.githubusercontent.com/56941237/127556946-82ead750-c5d9-4d37-a6a2-9ee4752ccb35.png)

**Comment by grandogarndo** [comment]
there are 9 skeletons out on the board, and one skeleton lord, so they should be getting +10 +1, I forgot to mention the effect should also only buff power, not toughness.

**Comment by jeffwadsworth** [comment]
[[Skeletal Swarming]]

**Comment by grandogarndo** [comment]
Why did you close the issue?

**Comment by jeffwadsworth** [comment]
> 
> 
> Why did you close the issue?

You see those blue numbers?  Click on that.

**Comment by grandogarndo** [comment]
Oops, sorry. Didn't realize that was a another issue. Thanks!

**Comment by jeffwadsworth** [comment]
Actually, it was fixed before and the code was fine.  It just isn't in the newest release yet.
