### ISSUE TITLE
An opponent's hand that becomes empty doesn't clear the last card

### ISSUE THREAD

**Issue by Grath** [magefree/mage#8077]
Testing with the latest beta, Sen Triplets now works (hooray!) but when you play the last card out of an opponent's hand it still shows their hand with the now-missing card (which gets de-highlighted, since you can't actually play it anymore, which is good.)
![](https://i.imgur.com/YWaFap6.png)

**Comment by Grath** [comment]
Update: If the card you played has an activated ability (I just played a Forest which was the last card in Computer 3's hand) clicking on the card that's shown in their hand will act like clicking on the card on your battlefield.

**Comment by JayDi85** [comment]
It's not a bug. Reveal windows un-attaches on priority (e.g. it will be visible until manual close).
