### ISSUE TITLE
Had this happen today while playing a Rich Man game Bo3

### ISSUE THREAD

**Issue by 1Heresy** [magefree/mage#8086]
Game exception occurred: mage.MageException: Iterated player priority after game exception too often, game ends! Last error:
 mage.player.human.HumanPlayer cannot be cast to mage.filter.predicate.ObjectSourcePlayer
Server version: 1.4.49-V2 (build: 2021-07-31 19:05)
mage.game.GameImpl.playPriority(GameImpl.java:1485)
mage.game.turn.Step.priority(Step.java:61)
mage.game.turn.Phase.playStep(Phase.java:184)
mage.game.turn.Phase.play(Phase.java:89)
mage.game.turn.Turn.play(Turn.java:128)
mage.game.GameImpl.playTurn(GameImpl.java:967)
mage.game.GameImpl.play(GameImpl.java:877)
mage.game.GameImpl.start(GameImpl.java:853)
mage.server.game.GameWorker.call(GameWorker.java:34)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)

**Comment by theelk801** [comment]
do you have any more information on what happened, what cards were being player etc?

**Comment by 1Heresy** [comment]
1st time, it was after playing Mascot Exhibition. Game went to sideboard
directly after with a game loss message. Had it happen also just passing
the turn.
