### ISSUE TITLE
Sword of Fire and Ice and Memnarch

### ISSUE THREAD

**Issue by jeffwadsworth** [magefree/mage#8089]
It was reported that Sword of Fire and Ice attached to a creature is not providing correct color protection.  Example given: Memnarch.
[[Sword of Fire and Ice]]
[[Memnarch]]

**Comment by theelk801** [comment]
the memnarch was also a commander, this is likely the same as #7987 and #7983

**Comment by Alex-Vasile** [comment]
Closing as duplicate of #7983
