### ISSUE TITLE
XMage AI keeps on triggering rollback (ConcurrentModificationException)

### ISSUE THREAD

**Issue by lehandroz** [magefree/mage#8091]
WOW! Surprise! In addition to taking forever just to "simulate passing priority, " the AI is now triggering rollbacks for anything I do, making me unable to forward the game state whatever I do.

Like I try to cast my game-winning Overloaded Cyclonic Rift. All they have to do is crack a fetchland in response, then after a minute or two, it causes a rollback. This happens frequently enough to render the game unplayable.

*OOT: I've also noticed Tergrid's "sacrifice" trigger does not work.

Here's the error:
Game exception occurred: java.util.ConcurrentModificationException
Server version: 1.4.49-V2 (build: 2021-07-31 19:05)
java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909)
java.util.ArrayList$Itr.next(ArrayList.java:859)
mage.abilities.AbilitiesImpl.containsKey(AbilitiesImpl.java:267)
mage.game.permanent.PermanentImpl.addAbility(PermanentImpl.java:377)
mage.abilities.effects.common.continuous.GainAbilityControlledEffect.apply(GainAbilityControlledEffect.java:115)
mage.abilities.effects.ContinuousEffectImpl.apply(ContinuousEffectImpl.java:112)
mage.abilities.effects.ContinuousEffects.apply(ContinuousEffects.java:1096)
mage.game.GameState.applyEffects(GameState.java:641)
mage.game.GameImpl.applyEffects(GameImpl.java:1645)
mage.game.GameImpl.playPriority(GameImpl.java:1446)
mage.game.turn.Step.priority(Step.java:61)
mage.game.turn.Phase.playStep(Phase.java:184)
mage.game.turn.Phase.play(Phase.java:89)
mage.game.turn.Turn.play(Turn.java:128)
mage.game.GameImpl.playTurn(GameImpl.java:967)
mage.game.GameImpl.play(GameImpl.java:877)
mage.game.GameImpl.start(GameImpl.java:853)
mage.server.game.GameWorker.call(GameWorker.java:34)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)

**Comment by lehandroz** [comment]
Additional detail: whenever this rollback triggers, the current phase/step is moved forward as if the Spacebar has been pressed (instead of staying in the current phase/step like a normal rollback).

**Comment by JayDi85** [comment]
@lehandroz can you send local server's logs to jaydi85@gmail.com ? From `beta_folder\xmage\mage-client\mageclient.log`

**Comment by JayDi85** [comment]
Correct logs path: `beta_folder\xmage\mage-server\mageserver.log`

**Comment by JayDi85** [comment]
`ConcurrentModificationException` must be fixed with 1664ee01cf30af2e85d725d63f22808ffdf2d61f (available on beta two weeks ago).
