### ISSUE TITLE
Devouring Greed can't be cast without spirits

### ISSUE THREAD

**Issue by Jipsu** [magefree/mage#8097]
[[Devouring Greed]] cannot be cast if you don't control Spirits or Changelings. Otherwise the card works correctly: you don't have to sacrifice creatures but you can, and the card correctly doesn't care if your opponent has spirits.

**Comment by ingmargoudt** [comment]
@JayDi85 Could you double check my commit ?

**Comment by JayDi85** [comment]
Yes, I'll check it later. BTW, additional cost is optional, e.g. if you doesn't activate additional cost then you must able to cast a card by normal mana. It must work without any workaround. Strange.

**Comment by ingmargoudt** [comment]
Additional costs can be optional. In case of the SacrificeCost, the canPay method first checks the battlefield for legal targets, but finds none because there are none.
