### ISSUE TITLE
Mutual Destruction doesn't gain flash even if you control a permanent with flash.

### ISSUE THREAD

**Issue by Grath** [magefree/mage#8102]
I can cast Grim Wanderer (proving that I do have priority and available mana and all that) but not Mutual Destruction, despite having Opposition Agent in play. Later, on my turn, I was able to cast Mutual Destruction at Sorcery speed.
![](https://i.imgur.com/0BCUY9L.png)

**Comment by Grath** [comment]
In case it helps, playing the first flash creature after drawing Mutual Destruction doesn't make it playable either.

**Comment by Grath** [comment]
I don't know what's substantively wrong between [[Crashing Tide]] and [[Mutual Destruction]] beyond where the filters/condition are created but Crashing Tide's implementation of gaining flash works while Mutual Destruction's doesn't.

**Comment by jeffwadsworth** [comment]
It was the "duration" setting.  Fix incoming.
