### ISSUE TITLE
Action text gobbldey-gook

### ISSUE THREAD

**Issue by Asgardian1** [magefree/mage#811]
I've installed xmage on 2 different windows machines and I have had the same result - all action text (do you wish to mulligan, etc...) shows up as random characters as seen in the screenshot below. One system is a windows 8.1 machine and the other is a Win7 machine - but I get the same issues on both.  I did a test on a linux machine and did not have this issue.  Does anyone know how to fix this?

![charactermismatch](https://cloud.githubusercontent.com/assets/2066790/6682255/dcd6fb00-cc75-11e4-8bf7-cc680c2690cd.jpg)

**Comment by LevelX2** [comment]
I've seen users complain about this problem already two or three times. Never found out the reason.
Any special installations two your windows (like any additional languages?).
One assumption was that there is a problem with font installation, but it never was confirmed.
Here are links to the threads from the forum.

http://www.slightlymagic.net/forum/viewtopic.php?f=70&t=11237&p=126788&hilit=characters#p126788
http://www.slightlymagic.net/forum/viewtopic.php?f=70&t=9174&p=110824&hilit=can%27t+read#p110824

**Comment by Asgardian1** [comment]
I do have my language set to Canadian English - will try to restore to US English and see what happens.

**Comment by Asgardian1** [comment]
So changing my language settings to US English has not solved the problem.  Any other thoughts?

**Comment by LevelX2** [comment]
I checked again the font handling of this area. The font family "times" ws used, what's at least no logical Java font. So maybe this could be a possible cause.
I changed it now to a logical Java font (Dialog). So please test with the next update (2015-03-14v3) that will be released tonight or tomorrow if this helps with your problem.

**Comment by Asgardian1** [comment]
Have not forgotten about this.  Could not connect to the server last night as it did not recognize the new xmage version and today it downloaded a new java version and I cannot properly connect to any network at all.  Will try again tomorrow and let you know.

**Comment by Asgardian1** [comment]
Just logged into the server and watched a game.  The text is now in English.  Thank you!
