### ISSUE TITLE
Lurebound Scarecrow sacrifice ability doesn't trigger when it should

### ISSUE THREAD

**Issue by awjackson** [magefree/mage#8114]
My AI opponent cast a [[Lurebound Scarecrow]] while it controlled no other colored permanents, and didn't have to sacrifice it.

**Comment by Jipsu** [comment]
I just tried a deck against AI with Lurebound Scarecrow and another artifact creature and it got sacced. Maybe there was something else involved?

**Comment by awjackson** [comment]
Disregard this, I'm a doofus. I rechecked the game log, and the computer had cast a lockdown aura on one of my creatures which matched the color it chose for the Lurebound.
