### ISSUE TITLE
Esix, Fractal Bloom preventing Nacatl War-Pride from exiling tokens

### ISSUE THREAD

**Issue by thefnitalian** [magefree/mage#8117]
Esix, Fractal Bloom preventing Nacatl War-Pride from exiling tokens at the end of the turn.
Relevant ruling:
https://www.reddit.com/r/magicTCG/comments/na8x8r/rule_question_re_esix_fractal_bloom_vs_nacatl/

**Comment by Alex-Vasile** [comment]
[[Esix, Fractal Bloom]], [[Nacatl War-Pride]]

**Comment by Alex-Vasile** [comment]
Couldn't reproduce. Added test.
