### ISSUE TITLE
Thraximundar's rules text is broken

### ISSUE THREAD

**Issue by alexander-novo** [magefree/mage#8118]
![image](https://user-images.githubusercontent.com/11657716/128768646-48b130ef-35f9-4cd7-9105-731eff1cd03f.png)

From live version. The controller of the deck says it's new, some I'm guessing it happened during the ability text refactor (#8010)

**Comment by Alex-Vasile** [comment]
This was fixed at some point and can be closed

![Screen Shot 2022-02-05 at 4 05 07 PM](https://user-images.githubusercontent.com/48962821/152659014-ab720cc5-25ad-4044-a612-3954c8cb6b70.png)
