### ISSUE TITLE
Gods Willing Scry Dialog Immediately Resolves

### ISSUE THREAD

**Issue by DominusMaximus** [magefree/mage#8120]
1.4.50-dev (2021-08-09 07-46)

The scry dialog for [[Gods Willing]] appears and then immediately goes away, automatically choosing to leave the card on top.

**Comment by awjackson** [comment]
I can't reproduce this.

**Comment by DominusMaximus** [comment]
I can no longer reproduce it on the current beta version. Thanks for looking into it.
