### ISSUE TITLE
Dress down is not preventing creatures entering with counters

### ISSUE THREAD

**Issue by dihimono** [magefree/mage#8122]
![image](https://user-images.githubusercontent.com/5095588/129129616-25e378cb-8271-4818-a401-7ee4cdce155b.png)
As shown in the screenshot, dress down should prevent thing in the ice entering with counters on it.

**Comment by jeffwadsworth** [comment]
[[Dress Down]]

**Comment by jeffwadsworth** [comment]
This issue is related to the dreaded "Blood Moon" issue.  Someone correct me if I am wrong.  I am looking at you, Elk.

**Comment by theelk801** [comment]
yeah it's the same thing unfortunately

**Comment by jeffwadsworth** [comment]
657981

**Comment by awjackson** [comment]
Closing as duplicate
