### ISSUE TITLE
Anya, Merciless Angel doesn't lose bonus when player loses

### ISSUE THREAD

**Issue by copperfield42** [magefree/mage#8124]
![image](https://user-images.githubusercontent.com/4504719/129301477-faa72d93-b7fe-4a85-aa8a-0f46e9ddeef2.png)
When the opponent that grants [[Anya, Merciless Angel]] bonus loses the game Anya continue too keep her bonus until the next turn of her controller.

In the img I just defeated computer 4 that was granting the bonus (computer 3 was defeated several turns prior)

**Comment by JayDi85** [comment]
Boost conditional uses opponents list. It updates once per turn due to rules:
> 801.2c The particular players within each player’s range of influence are determined as each turn begins.

Player information can be used even after player leaves:
> 800.4hIf an effect requires information about a specific player, the effect uses the current information about that player if he or she is still in the game; otherwise, the effect uses the last known information about that player before he or she left the game.

So card works correctly?

**Comment by copperfield42** [comment]
really? mmm that doesn't look very right to me, well I guess tomorrow I will ask in the judge forum or something to check...

**Comment by JayDi85** [comment]
That's hows current code works (it doesn't check that opponent in the the game). Yes, judge explain needs.

**Comment by JayDi85** [comment]
[Mtgsalvation has some hints](https://www.mtgsalvation.com/forums/magic-fundamentals/magic-rulings/magic-rulings-archives/639418-are-dead-players-still-opponents), but without rules refs:

> The reduction still applies. The ability looks in the past and sees that life was lost by an opponent earlier in the turn. It doesn't care what happened to that opponent since then. 

> To elaborate on the general question: The game recognizes opponents who have left the game for the purpose of determining information about past game actions (e.g. the above scenario, or the fact that spells that have been cast by that opponent this turn still contribute to Storm count.) **The game does not recognize opponents who have left the game for the purpose of effects that need current information about your opponents**. For example, your Mycosynth Fiend will get smaller if an opponent who had poison counters leaves the game, and cards that were in their graveyard won't buff your Consuming Aberration. 

So Anya must check `isInGame`. There are must be many other cards with same "bug".

**Comment by JayDi85** [comment]
Cards with same "bug":
[[Bloodghast]], [[Guul Draz Vampire]], [[Viridian Betrayers]]

**Comment by JayDi85** [comment]
I think @emerald000 can help to confirm it.

**Comment by copperfield42** [comment]
cool, I can't access the judged chat because I found myself _Blocked by DNSBL_ for some reason :/

**Comment by emerald000** [comment]
104.5. If a player loses the game, that player leaves the game.

So once a player has lost they stop being considered your opponent since they are not in the game anymore. So Anya should only check opponents still in the game for her abilities.

**Comment by copperfield42** [comment]
here is the list of the 28 cards that might be [potentially affected](https://scryfall.com/search?q=o%3A%22as+an+opponent%22&unique=cards&as=grid&order=color)

**Comment by JayDi85** [comment]
Effects with "opponent cards/permanents" condition are not affected (cards and permanents from leaved player are removes immediately). Example: [[Black Scarab]].
