### ISSUE TITLE
"Klauth, Unrivaled Ancient" - Mana generated from attacking is lost after attack phase

### ISSUE THREAD

**Issue by bwsinger** [magefree/mage#8137]
[[Klauth, Unrivaled Ancient]] generates mana of any color combination equal to the power of all attacking creatures. This works correctly.

However, Klauth, Unrivaled Ancient's ability specifies that "Until end of turn, you don't lose this mana as steps and phases end." Currently you lose this mana after changing phases from attack phase to Main Phase 2 (you also get the warning pop-up that you will lose the floating mana).

**Comment by jeffwadsworth** [comment]
Yeah, this just needs a continuous effect like [[Leyline Tyrant]] to keep the mana around.

**Comment by theelk801** [comment]
fixed with 7cc806b
