### ISSUE TITLE
xmage client server issue

### ISSUE THREAD

**Issue by Jezz-hub78** [magefree/mage#8150]
hello 
i just download xmage today and after an update , i suddenly launched the client server and it only show a black screen , i try to find a solution but nothing , please help

**Comment by JayDi85** [comment]
You must disable auto-login. Instructions:
https://github.com/magefree/mage/issues/4461#issuecomment-361108597

**Comment by Jezz-hub78** [comment]
Hey I just checked that javasoft/pref

And I don't see the mage file it only shows Google, any ideas.

**Comment by JayDi85** [comment]
Different OS store it in different places. See link above to find your OS and search it again. Or maybe "black screen" is logs screen, not a client -- it's a different problem (example: you are updating while server runs, so just restart computer and update again).
