### ISSUE TITLE
Ravnica Cards Broken in 1.3.0.dev2015-03-14v3?

### ISSUE THREAD

**Issue by dpsommer** [magefree/mage#816]
When I try to start a bot game with a deck containing cards from the Ravnica (RAV) set, I get the following error:

`Server error: Card not found - <CARD_NAME> - RAV for deck <DECK_NAME>
Possible reason is, that you use cards in your deck, that are only supported in newer versions of the server.
So it can help to use the same card from another set, that's already supported from this server.`

**Comment by LevelX2** [comment]
Should be resolved I guess. We fixed a spelling error in the set name that caused your problems.
