### ISSUE TITLE
Paradox Zone + Divine Visitation, the token doesn't get the counters 

### ISSUE THREAD

**Issue by copperfield42** [magefree/mage#8160]
the angel produced by [[Paradox Zone]] when [[Divine Visitation]] is out doesn't enter with +1/+1 counters

**Comment by jeffwadsworth** [comment]
I haven't looked at the code, but I have verified this bug.  This type of bug will most probably affect every card of this type in which replacement effect tokens do not have the additional effects applied to them.  I will check it out soon.

**Comment by jeffwadsworth** [comment]
This appears to require a refactor of adding any effects applied to the original token event to the new token event.  Right now, the only events that do this are DrawCardEvent() and DrawCardsEvent().  This particular case has the counter added via an effect embedded within the token object itself.

**Comment by JayDi85** [comment]
But put 1/1 counters to tokens implemented by last tokens ids. So there are must be another problem (why token ids doesn't contains all real ids).

![shot_210911_004548](https://user-images.githubusercontent.com/8344157/132915773-eae1b608-06b9-47f5-97d4-e1b33a24c8ed.png)

**Comment by copperfield42** [comment]
look like this is no longer an issue in version 1.4.51-dev (2022-05-27 06-01), today I play with those cards and the angel get the counter as expected

**Comment by theelk801** [comment]
yeah I fixed this one a while back, didn’t know this issue was open
