### ISSUE TITLE
2 Card Images Fail with 404s (1.3.0.dev2015-03-14v3)

### ISSUE THREAD

**Issue by dpsommer** [magefree/mage#817]
Here's the log:

`WARN  2015-03-19 02:26:14,573 Image download for Thunderbreak Regent(MGDC) failed - responseCode: 404 url: http://magiccards.info/scans/en/mgdc/44.jpg =>[pool-4-thread-2] DownloadPictures$DownloadTask.run`

`WARN  2015-03-19 02:26:14,573 Image download for Scaleguard Sentinels(MGDC) failed - responseCode: 404 url: http://magiccards.info/scans/en/mgdc/43.jpg =>[pool-4-thread-1] DownloadPictures$DownloadTask.run`

**Comment by LevelX2** [comment]
Probably because the cards are not up yet on magicards.info.
They have them up to 42 only now.
http://magiccards.info/mgdc/en.html
