### ISSUE TITLE
Options menu doesn't contain new feature

### ISSUE THREAD

**Issue by mattelonian** [magefree/mage#8175]
![image](https://user-images.githubusercontent.com/62502027/131377321-7cb6409a-9e68-46bd-abc4-b4f2602e9007.png)
![image](https://user-images.githubusercontent.com/62502027/131377354-bb2d1cb4-6710-457d-abcc-17dd9926da75.png)

Preferences menu does not contain the options stated to change preferences for different answers for different objects

**Comment by JayDi85** [comment]
The last one:

![shot_210830_220456](https://user-images.githubusercontent.com/8344157/131384274-e81a9b3b-ca95-4c8c-bc90-9cbdf41da9d0.png)

**Comment by mattelonian** [comment]
I must have misunderstood what the update was actually saying then, sorry
