### ISSUE TITLE
Xmage Crashing

### ISSUE THREAD

**Issue by ockhams** [magefree/mage#818]
Since the recent update, my xmage will crash every 10-20 seconds. The launcher gives me 
A fatal error has been detected by the Java Runtime Environment:
XCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x78ab0a4a, pid=3248, tid=5332
JRE version: Java(TM) SE Runtime Environment (8.0_40-b25) (build 1.8.0_40-b25)
Java VM: Java HotSpot(TM) Client VM (25.40-b25 mixed mode windows-x86 )
Problematic frame:
C  [msvcr100.dll+0x10a4a]
Failed to write core dump. Minidumps are not enabled by default on client versions of Windows

and

The crash happened outside the Java Virtual Machine in native code.
See problematic frame for where to report the bug.
Java HotSpot(TM) Client VM warning: ignoring option MaxPermSize=384m; support was removed in 8.0

Any suggestions?

**Comment by LevelX2** [comment]
Should be fixed with v4.
