### ISSUE TITLE
No sacrifice creatures trigger when casting Balance

### ISSUE THREAD

**Issue by Hipcat222** [magefree/mage#8183]
Bug - 

Opponent had a mother of runes and progenitus in play (both with summoning sickness). I had no creatures. Upon casting balance, triggers to sacrifice lands and cards in hard occured as normal, but there was no trigger to sac creatures. He was able to keep both on the board after balance resolved. 

Occured in vintage cube draft.

**Comment by Hipcat222** [comment]
Update - occurred with another player - apparently they were able to choose the creatures they wished to sacrifice.

**Comment by Jipsu** [comment]
A fix seems to be in the works, but the problem seems to be that a player can decide not to sacrifice if the other one has 0 of the thing. They should be able to sac but XMage doesn't force the rules yet. #7950

**Comment by jeffwadsworth** [comment]
No fix is being worked on as far as I know.
