### ISSUE TITLE
Moonmist fails to transform humans from night side to day side

### ISSUE THREAD

**Issue by awjackson** [magefree/mage#8187]
I discovered this issue while looking for other cards and interactions that are affected by #8185.

Put [[Moonmist]] in a deck with transforming cards that are humans on their night side such as [[Town Gossipmonger]], [[Hanweir Militia Captain]]. Cast some of those creatures, transform them by whatever means, and then cast [[Moonmist]]. The transformed humans should transform back to their day sides, but don't.

I think the problem is that night cards that don't have an ability of their own that transforms them don't set `this.transformable = true`, so they are unable to transform even via other cards' abilities.

**Comment by theelk801** [comment]
This is something I didn't notice until I started implementing this set, and it's probably just gonna fold into the rest of the TDFC refactoring we need to do.

**Comment by jeffwadsworth** [comment]
Yeah, we just add the option mentioned into the night-side cards unless there is some rule against it.

**Comment by theelk801** [comment]
I’m handling some of this in #8200 actually, there’s a lot of stuff with TDFCs that needs fixing
