### ISSUE TITLE
Casting Grief / Subtlety / etc that an opponent owns from exile asks owner to exile a card from hand if trying to pay evoke cost.

### ISSUE THREAD

**Issue by stevedavidmusic** [magefree/mage#8190]
- I've seen this issue with Hostage Taker / Gonti, Lord of Luxury when exiling Grief / Subtlety where it's the owner that is asked to exile a card when trying to pay its alternate casting cost from exile. I'm assuming the same issue will also occur for Fury / Endurance / Solitude. 

- I've tested Gonti exiling with an opponent's Force of Will / Unmask, and those interactions work fine when trying to cast them via their alternate costs.

**Comment by jeffwadsworth** [comment]
https://github.com/magefree/mage/commit/a04035036e3300b4548caadb3217eb78907d3436
