### ISSUE TITLE
[AFC] Prosper, Tome-Bound does not trigger from cards cast with Eye of the Storm

### ISSUE THREAD

**Issue by alexander-novo** [magefree/mage#8195]
[[Prosper, Tome-Bound]] does not trigger from cards cast with [[Eye of the Storm]]. I do not know how other copy, then cast from exile effects like [[Isochron Scepter]] are currently working, but it should be investigated too.

**Comment by alexander-novo** [comment]
Actually, disregard. Since these are copies not represented by real cards, prosper should not trigger.

**Comment by JayDi85** [comment]
From card's rules:
> The ability triggers when a player casts an instant or sorcery *card*. A copy of a card (such as those generated by Eye of the Storm itself) won’t trigger this ability. The card that was cast is exiled and won’t resolve, but the player will get a copy of the spell from Eye of the Storm. (2005-10-01)
