### ISSUE TITLE
Arcum Dagsson artifact creature sacrifice bug

### ISSUE THREAD

**Issue by zpxp** [magefree/mage#8198]
Sacrificing artifact creatures with dagsson does not trigger in death triggers.
Example:
Hangerback walker should create tokens on death, when sacked with dagsson, but this never happens
Junk diver and workshop assistant are 2 more examples that have on death triggers that do nothing

**Comment by jeffwadsworth** [comment]
Worked in my testing.
![worked](https://user-images.githubusercontent.com/1496996/131951022-635f891c-30ef-436e-934d-daa24b3a427f.jpg)

**Comment by zpxp** [comment]
I was playing edh with dagsson as the commander, if that makes any difference. Seen it occur in multiple games so doubt it was a card effect.

**Comment by jeffwadsworth** [comment]
Ahh, could very well be related to Commander mode.  No idea.

**Comment by Alex-Vasile** [comment]
> This happened to me as well, really nerfs my Arcum deck. Any ETA on the fix?

Have you tested on the newest beta to see if it's still an issue?

**Comment by Kolsemi** [comment]
Oh, sorry, I should have tested that earlier. The issue appears to have been fixed.
![Proof](https://user-images.githubusercontent.com/92222026/171996604-32a445c0-e6d3-4a9d-8c50-86c29c83e639.png)
