### ISSUE TITLE
Cannot view/edit decks in Deck Editor & Deck Editor overrides deck files with a blank

### ISSUE THREAD

**Issue by lucasofvalor** [magefree/mage#820]
Updated to the latest version of XMage and Java and now I cannot edit deck files.

Console:
Mar 20, 2015 2:29:41 PM java.util.prefs.WindowsPreferences <init>
WARNING: Could not open/create prefs root node Software\JavaSoft\Prefs at root 0x80000002. Windows RegCreateKeyEx(...) returned error code 5.
INFO  2015-03-20 14:29:43,198 Loading plugins...                                                                         =>[AWT-EventQueue-0] Plugins.loadPlugins 
INFO  2015-03-20 14:29:43,260 [Game counter plugin, version 0.1] has been loaded.                                        =>[AWT-EventQueue-0] CounterPluginImpl.newPlugin 
INFO  2015-03-20 14:29:43,276 Done.                                                                                      =>[AWT-EventQueue-0] Plugins.loadPlugins 
INFO  2015-03-20 14:29:44,274 Card pool load time: 0 seconds                                                             =>[AWT-EventQueue-0] MageFrame.checkForNewImages 
INFO  2015-03-20 14:29:44,274 Client start up time: 2 seconds                                                            =>[AWT-EventQueue-0] MageFrame$6.run 
FATAL 2015-03-20 14:29:49,921 Could not find card '' at line 2: 2 [KTK:249] Wooded Foothills
Could not find card '' at line 3: 1 [DTK:264] Forest
Could not find card '' at line 4: 4 [M15:51] Dissipate
Could not find card '' at line 5: 2 [ZEN:220] Misty Rainforest
Could not find card '' at line 6: 4 [RTR:98] Guttersnipe
Could not find card '' at line 7: 2 [ISD:78] Snapcaster Mage
Could not find card '' at line 8: 4 [DTK:65] Negate
Could not find card '' at line 9: 4 [RTR:247] Steam Vents
Could not find card '' at line 10: 4 [M10:146] Lightning Bolt
Could not find card '' at line 11: 3 [GTC:240] Breeding Pool
Could not find card '' at line 12: 3 [ISD:49] Curiosity
Could not find card '' at line 13: 3 [GTC:247] Stomping Ground
Could not find card '' at line 14: 4 [M14:194] Savage Summoning
Could not find card '' at line 15: 4 [NPH:118] Noxious Revival
Could not find card '' at line 16: 4 [MMA:191] Manamorphose
Could not find card '' at line 17: 1 [C14:331] Mountain
Could not find card '' at line 18: 3 [GTC:195] Simic Charm
Could not find card '' at line 19: 4 [ZEN:223] Scalding Tarn
Could not find card '' at line 20: 1 [KTK:257] Island
Could not find card '' at line 21: 3 [GTC:29] AEtherize
Could not find card '' at line 22: SB: 3 [M15:44] AEtherspouts
Could not find card '' at line 23: SB: 4 [MMA:67] Thirst for Knowledge
Could not find card '' at line 24: SB: 3 [ZEN:193] Vines of Vastwood
Could not find card '' at line 25: SB: 2 [C14:100] Cackling Counterpart
Could not find card '' at line 26: SB: 1 [MMA:49] Kira, Great Glass-Spinner
Could not find card '' at line 27: SB: 2 [RTR:219] Nivmagus Elemental
 =>[AWT-EventQueue-0] DeckImporter.importDeck 
FATAL 2015-03-20 14:29:52,745 Could not find card '' at line 2: 2 [KTK:249] Wooded Foothills
Could not find card '' at line 3: 1 [DTK:264] Forest
Could not find card '' at line 4: 4 [M15:51] Dissipate
Could not find card '' at line 5: 2 [ZEN:220] Misty Rainforest
Could not find card '' at line 6: 4 [RTR:98] Guttersnipe
Could not find card '' at line 7: 2 [ISD:78] Snapcaster Mage
Could not find card '' at line 8: 4 [DTK:65] Negate
Could not find card '' at line 9: 4 [RTR:247] Steam Vents
Could not find card '' at line 10: 4 [M10:146] Lightning Bolt
Could not find card '' at line 11: 3 [GTC:240] Breeding Pool
Could not find card '' at line 12: 3 [ISD:49] Curiosity
Could not find card '' at line 13: 3 [GTC:247] Stomping Ground
Could not find card '' at line 14: 4 [M14:194] Savage Summoning
Could not find card '' at line 15: 4 [NPH:118] Noxious Revival
Could not find card '' at line 16: 4 [MMA:191] Manamorphose
Could not find card '' at line 17: 1 [C14:331] Mountain
Could not find card '' at line 18: 3 [GTC:195] Simic Charm
Could not find card '' at line 19: 4 [ZEN:223] Scalding Tarn
Could not find card '' at line 20: 1 [KTK:257] Island
Could not find card '' at line 21: 3 [GTC:29] AEtherize
Could not find card '' at line 22: SB: 3 [M15:44] AEtherspouts
Could not find card '' at line 23: SB: 4 [MMA:67] Thirst for Knowledge
Could not find card '' at line 24: SB: 3 [ZEN:193] Vines of Vastwood
Could not find card '' at line 25: SB: 2 [C14:100] Cackling Counterpart
Could not find card '' at line 26: SB: 1 [MMA:49] Kira, Great Glass-Spinner
Could not find card '' at line 27: SB: 2 [RTR:219] Nivmagus Elemental
 =>[AWT-EventQueue-0] DeckImporter.importDeck 
![xmage_deck_editor](https://cloud.githubusercontent.com/assets/6914056/6759502/7bb9140c-cf0e-11e4-8eed-84f8b67f8a19.jpg)

**Comment by LevelX2** [comment]
The client DB is empty. That's not normal after a update.
How did you update?

Connect to a server to update/create the client database.
After that all should work as normal.

**Comment by krystlih** [comment]
I have this same issue, I forced an update and the DB clears itself on client launch.

**Comment by LevelX2** [comment]
Connect once to a XMage server to refill the clientDB with all cards!

The current v4 release has no prefilled client DB, that's a bug. It's fixed again with the next update.

**Comment by LevelX2** [comment]
I guess the problems are solved.
