### ISSUE TITLE
Casting Marath Generates random number of counters each time

### ISSUE THREAD

**Issue by dashosa** [magefree/mage#8204]
![image](https://user-images.githubusercontent.com/63882410/132072656-725fed3d-7815-475d-bad4-412b213293d4.png)

**Comment by JayDi85** [comment]
Possible reason: unsupported `Map<UUID, ManaPaidTracker>` data type in watcher copy code.

**Comment by JayDi85** [comment]
As stated above -- original problem was in watcher and unsupported `ManaPaidTracker`. Now watcher can copy any `Copyable<T>` data. So if you implement custom class for watcher then just make it copyable through `Copyable<T>` interface. 

Card fixed in latest commits.
