### ISSUE TITLE
The land brought into play with Emergent Sequence dies when you haven't played a land before casting it

### ISSUE THREAD

**Issue by sprangg** [magefree/mage#8208]
I played an [[Emergent Sequence]] without having played a land yet that turn, and the land brought into play with it went straight to the graveyard.

**Comment by JayDi85** [comment]
Yes, it must count. From rules:

> The last sentence of Emergent Sequence’s ability counts the land it put onto the battlefield. (2021-04-16)

**Comment by JayDi85** [comment]
Fixed by b56aef9341853313cdf76cfc5fa465b903a700ee
