### ISSUE TITLE
Rooms vanishing from lobby

### ISSUE THREAD

**Issue by peter-thoenen** [magefree/mage#8209]
Not sure how to describe this one nor if it's the US server only but other players on that server have confirmed.  Since the last server/client update if you create a room and leave it open for an extended period of time (5+ minutes) it vanishes from the lobby even though the room itself (as shown by the waiting for players window) still exists; just nobody can join as it's not in the lobby.  Maybe not a big issue on the DE server given the volume but a big deal on the US server given rooms are often open 30+ minutes.

**Comment by JayDi85** [comment]
Yes, it's known issue due auto-tables removes (once per 10 mins). After that changes e488997124a19ee794c3fffeb8eeb55e9decfb28.

**Comment by JayDi85** [comment]
Fixed by 5ded8468f7f5f3875f662814130aaccd61724a4f
