### ISSUE TITLE
Hurl through Hell doesn't exile creatue.

### ISSUE THREAD

**Issue by AsterAether** [magefree/mage#8211]
Hurl through Hell didn't exile the Gilded Drake, even though it resolved and showed the extra window for it.
![Unbenannt](https://user-images.githubusercontent.com/6317713/132100325-8b05b018-4a3a-411d-ba40-e0a6300631ea.PNG)

**Comment by jeffwadsworth** [comment]
[[Hurl through Hell]]

**Comment by jeffwadsworth** [comment]
This looks like a weird GUI issue.  Perhaps JayDi can figure it out.

**Comment by alexander-novo** [comment]
I can confirm it is just a visual issue.

**Comment by JayDi85** [comment]
It's not a visual bug. Game exiled a card, but not a permanent itself, so it was real. Fixed in e2098221909949c0ae6eabee1262df9491bbfe6c
