### ISSUE TITLE
Haunting Voyage not working properly when not fortold

### ISSUE THREAD

**Issue by cbpassingham** [magefree/mage#8223]
When I cast Haunting Voyage, it allows me to pick a creature type. The creatures in the graveyard, then highlight for a moment, but before I can select any, it advances, and Haunting Voyage is moved into the graveyard as if I had selected none.

Client: 1.4.50-V1 (build: 2021-08-30 10:46)
Server: 1.4.50-V1 (build: 2021-08-30 10:50)

Possibly related to #7862 ?

**Comment by cbpassingham** [comment]
When I ran into the issue, my graveyard consisted of Linden, the Steadfast Queen and General's Enforcer, and I chose the Human creature type.

**Comment by cbpassingham** [comment]
I think the fact that I'm seeing the highlights and prompt for a moment means that it's hitting this line.
https://github.com/magefree/mage/blob/754a5b38ebba104b83494629c1f3881020168b1e/Mage.Server.Plugins/Mage.Player.Human/src/mage/player/human/HumanPlayer.java#L587

**Comment by JayDi85** [comment]
Fixed by fe4d4c0834d9c76e564688153abf7911f2348ec6
