### ISSUE TITLE
issue with multiples triggers including a modal one

### ISSUE THREAD

**Issue by copperfield42** [magefree/mage#8225]
![image](https://user-images.githubusercontent.com/4504719/132147502-5545d1ca-46e1-4c2d-aeeb-3d3eeae25c47.png)
when multiple trigger go off of a single event including a modal one, you can't choose the options for the modal one, regardless of the order pick, with your mouse you need to do it with the numbers in the keyboard, because the order pick windows is interfering somehow. I suspect is the same for all such cards not just those in the image.

In the example, playing a land and triggering [[Field of the Dead]] and [[Retreat to Hagra]]

**Comment by copperfield42** [comment]
![021 modal trigger](https://user-images.githubusercontent.com/4504719/133912321-ab07b3ca-0653-4502-8fcb-405b7dd75bd7.PNG)
another sample

**Comment by JayDi85** [comment]
Overlapping dialogs fixed in 46081d9185c489eddea1ca78ef4851585e76ae9c. Wrong card icons drawing fixed in 61288b643990a2b296c07dabf26109d18e82db95.
