### ISSUE TITLE
Kaldra Compleat should not exile the creature if the creature is killed by combat damage

### ISSUE THREAD

**Issue by dihimono** [magefree/mage#8226]
https://github.com/magefree/mage/blob/90f09dd816c2eb912c949e4e879543884b3c755e/Mage.Sets/src/mage/cards/k/KaldraCompleat.java#L61

Kaldra Compleat's ability is a trigger ability, it should be put on the stack as normal, but when it resolves if the creature it affected is already dead, it should not be exiled.

**Comment by jeffwadsworth** [comment]
[[Kaldra Compleat]]

**Comment by jeffwadsworth** [comment]
From a discussion: https://tappedout.net/mtg-questions/kaldra-compleat-and-creatures-blocking-it/
If the equipped creature deals lethal damage, the creature dealt damage will be placed into the graveyard as a state based action be DC or the triggered ability has a chance to resolve, so it won't be able to find the creature to exile it.
