### ISSUE TITLE
Card Rules Enforcement Issue :: Dragonlord Dromoka and Dromoka's Command

### ISSUE THREAD

**Issue by wallenfox** [magefree/mage#823]
Dragonlord Dromoka's second line of text: "Your opponents can't cast spells during your turn." is not working.  Opponent's are able to cast spells on it's controller's turn when this card was in play on the battlefield.

Dromoka's Command is missing the option for "target creature you control fights target creature you don't control". The other modes seem to work fine.

**Comment by LevelX2** [comment]
Dragonlord Dromoka is already fixed for the next version.
Dromoka's Command mode 4 problem I can't reproduce. I guess you had no valid targets. In this case the mode is not shown.

**Comment by wallenfox** [comment]
I'll see if I can reproduce - my only valid targets at the time were 1/1 insect tokens with deathtouch that came into play the same turn from a hornet's nest. 


     On Sunday, March 22, 2015 4:48 PM, LevelX2 <notifications@github.com> wrote:
   

 Closed #823.—

**Comment by wallenfox** [comment]
Hi,
Have you heard anything about that book? Is it worth  reading?You may find the review here <http://raffaello.scottdoesrealestate.com/e4uv/3>

Take care, totalstar17@yahoo.com
