### ISSUE TITLE
Local AI problem - wrong client version

### ISSUE THREAD

**Issue by thehumankeyring** [magefree/mage#8232]
Unable to connect to local server for AI deck testing. Any help very appreciated.

Remote task error. Wrong client version.
Your version: 1.4.50-V2 (build: 2021-09-05 18:55)
Server version: 1.4.49-V3 (build: 2021-08-06 17:59)
....

![Screen Shot 2021-09-07 at 11 41 04 AM](https://user-images.githubusercontent.com/90280263/132394946-75b51496-b50b-4ef1-be0a-fd3b4ab3cdc7.png)

**Comment by JayDi85** [comment]
You are runs update with running local server, so it broken.How to fix: close all java apps or restart computer. After that run launcher and update again.

**Comment by thehumankeyring** [comment]
Thank you! 
Restarted, re-updated, now works as intended.
