### ISSUE TITLE
Great Hall of Starnheim doesn't allow sacrifice even when mana is available

### ISSUE THREAD

**Issue by cashmoneyhoes** [magefree/mage#8233]
![image](https://user-images.githubusercontent.com/90292347/132425382-c6993fc2-d79f-425b-b47b-ef66800f9caa.png)
I have both enough white and black mana in order to sacrifice [[Great Hall of Starnheim]] to get 4/4 Angel Warrior token, but it doesn't give me the option to sac it when I click on it, even though it's my main phase.

**Comment by weirddan455** [comment]
You don't have a creature on board to sacrifice...

**Comment by cashmoneyhoes** [comment]
My bad, didn't read the text closely enough.
