### ISSUE TITLE
[STX] Sparring Regimen triggered ability not triggering

### ISSUE THREAD

**Issue by cbpassingham** [magefree/mage#8235]
I have 2 Sparring Regimen and 1 Battlefield Raptor.

When I attack with Battlefield Raptor, neither Sparring Regimen triggers. They do not appear to be added to the stack at all.

I think what is supposed to happen is that both Sparring Regimens should trigger, allowing me to select an attacking creature to add a +1/+1 counter to and untap. In this case, resulting in me having a +2/+2 untapped Battlefield Raptor at the declare blockers step.

Client: 1.4.50-V2
Server: 1.4.50-V2

**Comment by weirddan455** [comment]
This should be fixed in 187e0736a054583bbb58e975c3671f482d35a9ba

There was a bug in a class that this card uses that made minimum attackers needed to trigger be +1 more than it should be.
