### ISSUE TITLE
Soaring Thought-Thief

### ISSUE THREAD

**Issue by Cinaed83** [magefree/mage#8238]
Mill 2 Attack Trigger not working properly when either STT or another Rogue attacks.

**Comment by jeffwadsworth** [comment]
[[Soaring Thought-Thief]]

**Comment by cbpassingham** [comment]
I'm guessing this is the same issue as #8228 and #8235.

If so, it should be fixed by https://github.com/magefree/mage/commit/187e0736a054583bbb58e975c3671f482d35a9ba
