### ISSUE TITLE
Cabal Pit forces you to take damage when casting a {B} spell with Urborg on the battlefield

### ISSUE THREAD

**Issue by emerald000** [magefree/mage#825]
I had a Cabal Pit while my opponent had an Urborg, Tomb of Yawgmoth. I casted a spell costing {B} and chose to pay for it with the Cabal Pit. I had no choice dialog pop up (unlike M15 painlands), and was forced to lose 1 life.

It should either figure out that I don't want to lose life or at least pop-up the choice window.

**Comment by jeffwadsworth** [comment]
Why would you get a choice whether or not to take 1 damage from the Cabal Pit once you choose to use it for the mana ability?

**Comment by emerald000** [comment]
There's always the corner-case of wanting a lower life total (for Death's Shadow for example).

**Comment by LevelX2** [comment]
You can deactivate auto payment before tapping the pit, that should give you the ability dialog. Or you can tap for the mana before casting the spell.

The players usually complain more about that mana tapping should be more automatic than it is now. And this is a perfect example where a lot of players will say the Pit should tap for {B} automatically if they click it (but sure only as long as they don't need to lose life).

So the route to go can only be to add more automatics but make them easy to switch off/on for specific situations.

Or what do you think about?

**Comment by emerald000** [comment]
I also agree the mana payment should be as automatic as possible and disable it if needed. 

But the automatic option in this case should be the painless {B}, not the take 1 damage {B}.

**Comment by LevelX2** [comment]
Seems to work as expected now, Auto mana for Cabal Pit uses the {B} mana without doing  1 damage to its controller.
