### ISSUE TITLE
Animate Dead: wrong interaction with Yarok, the Desecrated

### ISSUE THREAD

**Issue by Reya87** [magefree/mage#8253]
Hello,

When [[Animate Dead]] enters the battlefield and you control [[Yarok, the desecrated]], you have two ETB triggers from Animate Dead. 

The first trigger will resolve normaly and the targeted creature will come back onto the battlefield.

The problem occures when the second trigger resolves: the creature instantly goes back to the graveyard and instantly comes back onto the battlefield, for a second time! 

This situation leads to a potential 4 ETB trigger with Yarok on the battlefield (and a creature with an ETB on your graveyard). 

Normaly, the second ETB trigger from Animate Dead should just do nothing at all because the target is already on the battlefield and animate dead is already attached to the targeted creature. The second trigger should just "fizzle" and doing nothing.

**Comment by Reya87** [comment]
Hello. Is there any chance you can fix this ? Today I casted Animate Dead, targeting Mulldrifter in my graveyard, with Yarok the desecrated on the battlefield. At the end, I drew 8 cards. This is way too advantegeous for Yarok player !

**Comment by Alex-Vasile** [comment]
@weirddan455 close this one too

**Comment by weirddan455** [comment]
Fixed in ffe753fa91a5726f68879036fb1bd279e35f3685
