### ISSUE TITLE
Server Kicks you for AFK while waiting for stack.

### ISSUE THREAD

**Issue by Exhora58** [magefree/mage#8255]
Playing Storm with 3 veryan clones waiting for stack, got kicked for AFK.

**Comment by JayDi85** [comment]
If you got ping error before then thats the reason (ping session closed). I recommends to close and run app again on disconnection, not reconnect. Server checks your activity (any send commands or last ping).

**Comment by Exhora58** [comment]
No errors at all, I was waiting for veyran with 3 clones and thousand year storm 8x storm stack to clear and it just kicked me for being idle. I was sitting there with F10 on waiting for it to resolve. The system shouldn't kick you if a stack is actively resolving.

**Comment by JayDi85** [comment]
Are you talking about disconnect or loose the game?

**Comment by Exhora58** [comment]
I'm talking about the game conceding you out for being idle for 360 seconds.

**Comment by JayDi85** [comment]
well, after research... idle timer doesn't connected with connection timer/timeout (clicks on avatar will not work, also it doesn't related to ping session). 

It require your action/answer every 300 seconds (current de-server settings). So you must make any decision in 300 seconds to reset it.

Possible actions (except inform_personal):
![shot_210914_000948](https://user-images.githubusercontent.com/8344157/133150224-d41e44f2-6735-49a1-b9cd-dbc735bf85d6.png)

**Comment by Exhora58** [comment]
Alright thank you, I'll try to not have a stack that goes long from now on.

**Comment by JayDi85** [comment]
ok, it's not a bug... I made more research and found that it resets on any user feedback (e.g. clicks on avatars or cards will work).
