### ISSUE TITLE
Obosh, the Preypiercer doesn't double damage sometimes.

### ISSUE THREAD

**Issue by AsterAether** [magefree/mage#8263]
[[Obosh, the Preypiercer]] doesn't double damage sometimes, as confirmed ingame with the spell [[Slagstorm]] and attacking with Obosh directly. Player mentioned it does work sometimes, but most of the time it is bugged.

**Comment by jeffwadsworth** [comment]
This was already fixed.  Wait until the next release.

**Comment by jeffwadsworth** [comment]
https://github.com/magefree/mage/commit/26e9a92ea7e78bade4bc6366a7e0aa6465bd7cc5

**Comment by fearphage** [comment]
Duplicate of 8257
