### ISSUE TITLE
Sheltered Valley should not trigger on 4+ lands

### ISSUE THREAD

**Issue by sco0ter** [magefree/mage#8265]
Sheltered Valley has an intervening if clause, which is ignored when the ability triggers.

Currently its "At the beginning of your upkeep" ability goes on the stack and only checks the condition on resolution.

E.g. if you control 4 lands, it uses the stack. If you then stack Braids, Cabal Minion on top of it and sacrifice a land, you will gain 1 life. I think this is wrong, since Valley should never have triggered.

See https://blogs.magicjudges.org/rulestips/2011/09/the-intervening-if/

603.4
A triggered ability may read “When/Whenever/At [trigger event], if [condition], [effect].” When 
the trigger event occurs, the ability checks whether the stated condition is true. The ability triggers 
only if it is; otherwise it does nothing. If the ability triggers, it checks the stated condition again as it 
resolves. If the condition isn’t true at that time, the ability is removed from the stack and does 
nothing.

**Comment by weirddan455** [comment]
Yea, that's bugged.  It wasn't coded as an intervening if ability.  I've got a fix coming in just a minute.
