### ISSUE TITLE
Chromatic sphere/star cannot be sacrificed

### ISSUE THREAD

**Issue by yonivdt** [magefree/mage#827]
Hi,

Whenever I try to sacrifice chromatic star or sphere it pops up the dialog, but the dialog dissapears before I get the chance to select my color and click "ok".

Regards,
Y

**Comment by fireshoes** [comment]
I am guessing you are using a Linux OS. There is a know issue with that: https://github.com/magefree/mage/issues/584

The workaround that usually works is to right-click the blinking xmage icon in the system tray and select "Stop blinking". It will start blinking whenever a player joins or leaves a table you are at in the main lobby.

**Comment by LevelX2** [comment]
Closed because duplicate of #584.
