### ISSUE TITLE
Draconic Roar does not gain 6 life with Soulfire Grand Master and a dragon

### ISSUE THREAD

**Issue by mechler** [magefree/mage#828]
Player A has Soulfire Grand Master in play.

Player A cast Draconic Roar, revealing Thunderbreak Regent, targeting Player B's Brutal Hordechief.

Player B's Brutal Hordechief took 3 damage and Player B took 3 damage. Player A gained 3 life.

Player A should have gained 6 life.

**Comment by LevelX2** [comment]
Thanks for your post.
handled in #799.
