### ISSUE TITLE
game.preventDamage method appears to be bugged and unused

### ISSUE THREAD

**Issue by weirddan455** [magefree/mage#8280]
https://github.com/magefree/mage/blob/20fbde2860849cb661f82d127ae8a09c43293ad6/Mage/src/main/java/mage/game/GameImpl.java#L3070-L3073

The preventAllDamage flag is ignored here.  It always passes Integer.MAX_VALUE preventing all damage regardless.  "Find Usages" in IntelliJ IDEA is coming up empty so it looks like this code is never used.

Just wanted to make sure no one has objections to me removing this.

**Comment by jeffwadsworth** [comment]
Perhaps we are looking at different things here, but check out [[Awe Strike]]

**Comment by jeffwadsworth** [comment]
@weirddan455 Can we close this now?

**Comment by weirddan455** [comment]
I'll give it a little bit and if no one yells at me in the PR I'll merge it.

**Comment by JayDi85** [comment]
It's interesting find -- prevent all damage implemented as Integer.Max... So in theory it can be cheated with another multiple or infinite damage. Example:
* prevent infinite (prevent max);
* damage max (removes prevent max);
* damage 10 (it works here).

Just for fun. No need to do with that until reports.
