### ISSUE TITLE
Commander Tymna gets exiled after phasing out

### ISSUE THREAD

**Issue by Beroestheenvoy** [magefree/mage#8286]
My opponent cast Angel of Serenity, targeted one of my commanders, Tymna the Weaver. In response I cast Teferi's Protection and my permaments phased out but after resolution of Angel's ability my commander got exiled as though it was still on the battlefield normally.

**Comment by jeffwadsworth** [comment]
[[Angel of Serenity]] [[Tymna the Weaver]] [[Teferi's Protection]]
