### ISSUE TITLE
Creatures damaged and dying triggering abilities of creatures dying at the same time don't trigger.

### ISSUE THREAD

**Issue by Tharkon** [magefree/mage#8293]
Example:
A Rot Wolf and a Wight fight and kill each other by dealing damage.
Both creature's abilities should trigger.

Alternatively Seraph and Sengir Vampire.
In this case both would trigger and unless countered they will resolve. Sengir Vampire's ability will just not do anything. Seraph's controller will gain control of Sengir Vampire indefinitely, because there no longer exist a Seraph to lose control of.

For many of these cards it has been explicitly ruled, but the rule in general applies that if a creature dies along with other creatures, any abilities it has that would trigger off of those deaths do trigger. Wight is probably too new to have had a specific ruling but I would not be surprised it will gain one still.

**Comment by jeffwadsworth** [comment]
[[Rot Wolf]] [[Wight]] [[Seraph]] [[Sengir Vampire]]
