### ISSUE TITLE
Prowess bug?

### ISSUE THREAD

**Issue by pyested** [magefree/mage#8303]
Hi there,
I'm not sure if this is a bug, but I think so. After my opponent has gained control of Monastery Swiftspear with Archmage's Charm, the prowess ability keeps on triggering with my own spells, even though I don't control the creature anymore. I guess it's exactly the same for any creature with prowess (I remember it happened to me once with Soul-Scar Mage after they gained control of it).

**Comment by jeffwadsworth** [comment]
[[Monastery Swiftspear]] [[Archmage's Charm]]
