### ISSUE TITLE
 Minimus Containment  does nothing

### ISSUE THREAD

**Issue by alexander-novo** [magefree/mage#8319]
[[Minimus Containment]]  does nothing. It does not change any types, remove any abilities, or add any abilities. Here is a picture of my commander enchanted by Minimus Containment still able to block, and with all of its types:

![image](https://user-images.githubusercontent.com/11657716/134790902-f2b7e346-a831-489c-9f5e-a7c5b7971b45.png)

**Comment by jeffwadsworth** [comment]
Perhaps related to its Commander state.  It worked fine while tested in a normal game.

**Comment by alexander-novo** [comment]
I will note that someone the other day had a limited game up titled "Please do not draft Minimus Containment - it is bugged", so I assume it doesn't work in limited either.

**Comment by weirddan455** [comment]
Looks like this was fixed in cfd37619046642209a51908be18f988ea45c312c  This commit should be in the beta build but not stable.  If you're getting this on stable, that's probably the reason.

**Comment by alexander-novo** [comment]
Ah that's why. I did a search in the issues for Minimus Containment and didn't see anything, so I thought it wasn't reported/fixed.

**Comment by theelk801** [comment]
tip: remove the `is:open` tag when searching

**Comment by theelk801** [comment]
oh my bad, it must have been reported elsewhere
