### ISSUE TITLE
Maddening Hex does not update who it is attached to in the UI

### ISSUE THREAD

**Issue by alexander-novo** [magefree/mage#8320]
The purple arrow from [[Maddening Hex]] showing who it is attached to does not update after the ability resolves. As well, it doesn't show in the log who it is now attached to, so it is impossible to tell.

On a side note it might be a good idea to show in tooltips for player auras which player it is currently attached to.

**Comment by alexander-novo** [comment]
I wanted to add - this will also probably eventually be an issue with [[Lynde, Cheerful Tormentor]], since she moves attachment of curses as an effect. Since her ability doesn't target it will also be impossible to tell which players the curses are attached to.

**Comment by JayDi85** [comment]
XMage support only limited arrow types like targets or combat:
![shot_210928_191151](https://user-images.githubusercontent.com/8344157/135115598-3f870a8c-d25a-4b2d-9af0-d1e63c1917d8.png)

> it might be a good idea to show in tooltips for player auras which player it is currently attached to.

But it must show it already. Maybe something miss in the code.

**Comment by alexander-novo** [comment]
Right, this should fall under the use case of `ArrowUtil.drawArrowsForEnchantPlayers` - I just suspect that the arrow is not redrawn if the player an aura is enchanting changes while the aura remains on the battlefield... it isn't something that happens often. Maddening Hex changes the player it is attached to every time it triggers, and Lynde will also change the attachment of player auras with her ability.

**Comment by JayDi85** [comment]
Arrows redrawn on every game data update or on windows size change (well, on battlefield size change). Try to click on any avatar or  card after bug appear. If the click helps with arrow then it's a bug with wrong server events (example: game ask a player for next question without updated data).

**Comment by alexander-novo** [comment]
To be clear, here is what the current interface looks like:

![image](https://user-images.githubusercontent.com/11657716/135139198-df8c3ff8-51ef-40a6-99b4-6022443118d9.png)

There is a purple arrow that points to the enchanted player that appears only when hovering over the enchantment. When hovering, the tooltip doesn't say anything about which player is current enchanted. When the ability triggers and the enchanted player changes, hovering over the enchantment displays an arrow pointing to the originally enchanted player (not the currently enchanted player), even if you stop hovering and let the arrow go away and re-hover and let the arrow come back.

I am working on a video to show this right now.

**Comment by alexander-novo** [comment]
https://youtu.be/s1XVUGYtIDw

In this video, the Computer 3 is the original player that Maddening Hex is attached to. They cast a noncreature spell (Swan Song), triggering Maddening Hex. They take the damage, and the player Maddening Hex is attached to is changed randomly to Computer 2 (as they are the only other viable target). However, this information is not displayed in the log anywhere, and hovering Maddening Hex will still show the enchanted player as Computer 3. I try clicking every avatar and checking again, but the arrow is still pointing to Computer 3. However, if Computer 3 casts a noncreature spell, Maddening Hex will not trigger. Instead, if Computer 2 casts a noncreature spell it will trigger and Computer 2 will take the damage.

**Comment by sumsarz** [comment]
I can confirm this is a problem when playing Lynde. In EDH it just spreads its attachment tentacles to all opponents sooner or later.

**Comment by alexander-novo** [comment]
I actually believe the current issue is different - the pointer now correctly updates as it should. Rather, the new issue is simply that maddening hex does not unattach from a player as it should - rather it just adds the new player to the list of things it is attached to. The arrows are working correctly and display all things that permanent is attached to. This had the odd effect of effectively making maddening hex no longer move from opponent to opponent when it has moved to every opponent, since `addAttachment` checks to see that the permanent isn't already attached to that player and `permanent.getAttachedTo` only returns the last attachment.

Going forward, it might be apt to add a check to `addAttachment` that makes sure the permanent is not currently attached to anything (as I believe the comprehensive rules state that a permanent can only be attached to one object at a time?) and throw an error so we can catch these cases. Or maybe automatically unattaches it? I'll let someone with more experience decide.

I'll look into fixing maddening hex and adding a tooltip to all curses for which player they're attached to in case some functionality down the line breaks like this again.

**Comment by sumsarz** [comment]
I'm not entirely sure if it's related, or a separate issue (or both), but when you use [[Estrid's Invocation]] upkeep trigger and bring it back as a curse, it attaches itself (and keeps old one, if it was attached already) but doesn't come back as the copy of the curse but itself.

**Comment by alexander-novo** [comment]
That's an unrelated issue. Estrid's has been broken in general for a long time. It doesn't really work with any aura (and sometimes doesn't work with enchantments in general)
