### ISSUE TITLE
Ranger Class abilities don't work

### ISSUE THREAD

**Issue by EllNubNub** [magefree/mage#8325]
Leveled it up to level 2, attacked with a creature, and there was no trigger to place a counter on the creature that attacked.

**Comment by weirddan455** [comment]
Are you on the stable build?  I've fixed a bug with Ranger Class in https://github.com/magefree/mage/commit/187e0736a054583bbb58e975c3671f482d35a9ba that should be in beta.

**Comment by weirddan455** [comment]
I will close this for now.  Pretty sure this has been fixed in latest build.
