### ISSUE TITLE
Poison the Cup lets you scry if cast from exile, even if not foretold

### ISSUE THREAD

**Issue by alexander-novo** [magefree/mage#8334]
[[Poison the Cup]] lets you scry if cast from exile, even if not foretold. I've done this several times with [[Prosper, Tome-Bound]].

**Comment by alexander-novo** [comment]
Looking in ForetoldWatcher:

https://github.com/magefree/mage/blob/754a5b38ebba104b83494629c1f3881020168b1e/Mage/src/main/java/mage/watchers/common/ForetoldWatcher.java#L40-L50

It looks like any card cast from exile that has a foretell ability (regardless of if the ability was used or which cost was paid) is counted as foretold. I imagine this is a bug for the other "if foretold" cards too.

**Comment by jeffwadsworth** [comment]
I will check out this use case.
