### ISSUE TITLE
Morph power is visible to all players

### ISSUE THREAD

**Issue by Jipsu** [magefree/mage#8337]
Morphs give information about their power to all players. Morph stat box is colored green if flipped card has power below the current one, black if power is the same and red if flipper power is higher than current. It should always stay black to not give information.

![image](https://user-images.githubusercontent.com/22531697/135131599-c4aed505-f653-4ac8-934a-7f0fae3016a2.png)

Real stats are 1/1, 1/2, 2/1, 2/2, 1/3, 3/1, 2/3, 3/2 and 4/4.

**Comment by Jipsu** [comment]
![image](https://user-images.githubusercontent.com/22531697/135138821-08783bd8-537c-48dc-999a-a805f1358cb5.png)
Here's also an example from both sides of the table.

**Comment by sprangg** [comment]
The green or red P/T color is set here (lines 1102 and 1108) https://github.com/magefree/mage/blob/bae8a4e9e5925d0eaf2b983c888c98706ff9a33e/Mage.Client/src/main/java/org/mage/card/arcane/ModernCardRenderer.java#L1102 and it seems to compare the current P/T of the 2/2 facedown creature to the written stats of the faceup card.

Also interestingly only the creature's power is compared to the original written card, and if the current power of a creature is different than the original written power, both its power and its toughness are colored green/red based on that.
