### ISSUE TITLE
Error: could not open file

### ISSUE THREAD

**Issue by glitchkuh** [magefree/mage#8341]
When I try to start the game via the launcher, the following error appears in the command window: 

Error: could not open `D:\Games\xMage\java\jre1.8.0_201\lib\amd64\jvm.cfg'
![image](https://user-images.githubusercontent.com/37362328/135311463-8d27fef6-ff41-42ee-8210-798129022d7a.png)
![image](https://user-images.githubusercontent.com/37362328/135311572-6d1f5089-79a5-4983-8fec-a28b2283e4c6.png)

A few days ago the game worked just fine, what can I do about this or is a new install the only option?

**Comment by JayDi85** [comment]
Follow [that instruction](https://github.com/magefree/mage/issues/1272#issuecomment-529789018) to fix inner java.
