### ISSUE TITLE
Dash doesn't give an option to cast normally if cast from exile

### ISSUE THREAD

**Issue by alexander-novo** [magefree/mage#8342]
Reproduce: Exile [[Ragavan, Nimble Pilferer]] with [[Tibalt, Cosmic Impostor]] (unsure how it works while other cast from exile effect) . Then cast Ragavan from exile - the casting cost will be the dash cost and there will be no option to not dash it. After casting, Ragavan has haste.

Video pending.

**Comment by alexander-novo** [comment]
Video:
https://youtu.be/ov08-0y5SUo

**Comment by weirddan455** [comment]
Not able to reproduce in git build.  I think this is issue #8230 fixed in https://github.com/magefree/mage/commit/a04035036e3300b4548caadb3217eb78907d3436

![dash](https://user-images.githubusercontent.com/8128047/135354043-b57b7141-cf14-406d-9b5e-c645fa162428.jpg)

**Comment by alexander-novo** [comment]
It's interesting that in that example ragavan is the enabler, while I re-discovered the issue with ragavan as the bugged cost. Yes that does seem to be the same issue.
