### ISSUE TITLE
Soulfire Grand Master Issue

### ISSUE THREAD

**Issue by darthflaw** [magefree/mage#835]
During a game in which I was facing down a monstrous Stormbreath with a board of Seeker of the Way and nothing else. I untap, cast Soulfire Grand Master and use it to Convoke a Stoke the Flames. Since SGM gives my spells lifelink, I should have gained four, however I did not, meaning my plan of gain exactly seven to not die next turn couldn't work. Is this a bug or am I missing something?
Also in that same game I had two Grandmasters out and cast a Roast targetting an opponents Knuckleblade. The spell resolved but I only gained back five life. Shouldn't I have gained ten? Or am I misreading my cards?

**Comment by emerald000** [comment]
There is a current bug with Soulfire Grand Master not applying when it should (or applying when it shouldn't). See issue #799 for more information.

PS: Lifelink doesn't stack, so even if you have 2 Grandmasters, you can't gain more life than the spelt dealt.
