### ISSUE TITLE
Copy of Praetor's Grasp doesn't let you look at or play exiled card

### ISSUE THREAD

**Issue by alexander-novo** [magefree/mage#8352]
![image](https://user-images.githubusercontent.com/11657716/135652124-2c27cd8f-2dfb-4fad-8e55-72772b51f6c3.png)

I'm not really sure what is making this not work (I suspect it's the copy part since I don't think I've done that before), but I Cast [[Praetor's Grasp]] with [[Krark, the Thumbless]] on the field, so Krark triggered and I won the flip. Then the original copy of Praetor's Grasp is countered. The copy resolves, so I tutor for [[Niv-Mizzet, Parun]]. I have enough mana in the right colors for niv, but I can neither look at nor cast the face down card.

**Comment by jeffwadsworth** [comment]
Most probably related to the exile ID.
