### ISSUE TITLE
Xmage tries to add mythics to Legions boosters, resulting in rareless packs

### ISSUE THREAD

**Issue by sprangg** [magefree/mage#8361]
Xmage has Legions set to include mythics. When it tries to add one it can't find any since the set has no mythics, resulting in a rareless pack.

https://github.com/magefree/mage/blob/2e01f30b911b227a0a9496d0eb3797f1b05c4f2a/Mage.Sets/src/mage/sets/Legions.java#L30

**Comment by awjackson** [comment]
@JayDi85 There should probably be a test for this in `VerifyCardDataTest`...

**Comment by JayDi85** [comment]
Yeah

**Comment by sprangg** [comment]
Fwiw I went through all the sets and saw no similar issues
