### ISSUE TITLE
Storvald

### ISSUE THREAD

**Issue by theofitwas** [magefree/mage#8372]
When Storvald, Frost Giant attacks, if there is another trigger from a different creature/source that also goes on the stack then actions become stalled. The trigger window that asks you to choose which to resolve first pops up at the same time as the modal select window triggered by Storvald and then you cant click either one or anywhere else in the HUD for that matter.

I also cannot use the switch panels/deck editor tab etc. The only action is to close or force close Xmage.

See attached.

![GITHUBREPORT](https://user-images.githubusercontent.com/91949776/136008067-b3432db4-98b9-41e1-aa90-b26afa3b6c2c.JPG)

**Comment by JayDi85** [comment]
Fixed in #8225
