### ISSUE TITLE
Fractal Harness trigger bug

### ISSUE THREAD

**Issue by jeffwadsworth** [magefree/mage#8377]
The double counter effect apply runs twice.

**Comment by weirddan455** [comment]
The apply effect was not being run twice as far as I can tell.  The bug was caused by passing a Permanent object in getEffects.setValue.  In general, it is better to use immutable objects like UUID to avoid these kinds of bugs.  Added TODO in AttacksAttachedTriggeredAbility.

**Comment by weirddan455** [comment]
Changed this to use fixed target in 902fec22ddae3817d4742b4e20836343762873fc

Should probably refactor other uses at some point as well.
