### ISSUE TITLE
Ward & Evoke bug :bug:

### ISSUE THREAD

**Issue by quwetz** [magefree/mage#8378]
I attacked with [[Hall of Storm Giants]]. Opponent plays [[Solitude]] with evoke and only 2 Mana open. They target the Manland (with **Ward 3**)
**Ward 3** triggers and counters the **Evoke** Trigger, not the exile-ability. So Hall of Storm Giants is exiled and Solitude stays on Board.

**Comment by weirddan455** [comment]
See PR #8394.  Ward was countering whichever ability was put onto the stack last (top of stack).
