### ISSUE TITLE
Genesis always makes me select a creature card in graveyard

### ISSUE THREAD

**Issue by sco0ter** [magefree/mage#8381]
Genesis' ability always makes me select a creature card in graveyard when the ability goes on the stack, even if I don't want to pay 2G.

Later when it resolves, it asks me if I want to pay 2G, then returns the previously selected creature card.

I think it should only ask for a creature card, after 2G is payed during resolution, not when the ability enters the stack.

**Comment by theelk801** [comment]
This is how the card is supposed to work, the target is selected when it goes on the stack and then you choose whether to pay when it resolves.

**Comment by sco0ter** [comment]
@theelk801 Oh sorry then.

**Comment by theelk801** [comment]
No problem, it's sort of unintuitive if you go by the order of actions on the card.
