### ISSUE TITLE
CardCriteria minCardNumber and maxCardNumber are completely broken and unusable

### ISSUE THREAD

**Issue by awjackson** [magefree/mage#8383]
`mage.cards.repository.CardCriteria` has `minCardNumber` and `maxCardNumber` methods which would appear to allow specifying a numeric range of card numbers. However, card numbers are stored in the database not as integers but as strings (because some of them, mainly art variations, contain non-numeric characters) and as such the database performs not numeric but _alphabetical_ comparison on them. For example, a query with `maxCardNumber` set to 30 would incorrectly exclude card numbers 4, 5, 6, 7, 8 and 9.

`ExpansionSet` works around this by not using those methods, called out in the rather cryptic source comment `// Workaround after card number is numeric`. However, some of its subclasses (namely all the sets from 2015 to 2017 with Expedition/Masterpiece cards) _were_ using those methods and as a result boosters of those sets were not getting all the cards they should have.

If the underlying database issue isn't fixable (I don't know if it's possible to force the database to perform a numeric comparison on string fields) then these methods are nothing more than an attractive nuisance and should be removed completely.

**Comment by JayDi85** [comment]
There are possible to add additional field to cards database with numerical card number. I'll add it later.

**Comment by JayDi85** [comment]
Current min/max query used in mtga importer only. New db field with numerical card number implemented in a480e10bd890c9150900d06193df8edb80293a3f
