### ISSUE TITLE
Blazing Torch not working

### ISSUE THREAD

**Issue by michaelrfarcasin** [magefree/mage#8386]
I cast Traitorous Blood to steal an opponent's Voiceless Spirit with Blazing Torch equipped. When I attempt to use the creature's ability to sacrifice Blazing Torch, nothing happens.

I tried to target the Voiceless Spirit, another creature, and the opponent. Nothing happened in any case.

**Comment by awjackson** [comment]
This is not a bug. You can't pay the "sacrifice Blazing Torch" part of the activation cost because you don't control the Blazing Torch.

**Comment by awjackson** [comment]
> If a Blazing Torch controlled by one player somehow winds up equipping a creature a different player controls, the damage ability can’t be activated by either player. Only the creature’s controller may activate the ability — but since that player can’t sacrifice Blazing Torch (a permanent they don’t control), the ability’s cost can’t be paid.
