### ISSUE TITLE
Herald's Horn does not work with "elf" type

### ISSUE THREAD

**Issue by darianSmalley** [magefree/mage#8416]
Herald's Horn does not work with "elf" type. Neither the reduced cost nor the upkeep trigger.

**Comment by emerald000** [comment]
Just to be sure, was "Elf" chosen and not "Elves"?

**Comment by darianSmalley** [comment]
I will check and update once I have confirmation.

**Comment by jeffwadsworth** [comment]
[[Herald's Horn]]
