### ISSUE TITLE
UI pitfall: Pressing spacebar twice during a draft quits you from that draft

### ISSUE THREAD

**Issue by sprangg** [magefree/mage#8417]
In the past month our draft group has experienced it twice that a person has fumbled with their keyboard in such a way that they have been accidentally removed from the draft.

It's possible to quit the draft tournament by pressing spacebar twice. This does not happen during the first pick of a draft, but during any other pick after that, the quit-button in the top left is active in such a way that pressing spacebar brings up an "Are you sure you want to quit the draft tournament?" dialog. This dialog has the yes-button active by default so if you press spacebar again, you are considered to have quit the tournament.

This UI pitfall could be alleviated by, for example, having the no-button be the active default choice when opening the quit-dialog and/or if the quit-button wasn't active during the draft in such a way that spacebar brings up the quit dialog.
![2021-10-30 13_18_54-Window](https://user-images.githubusercontent.com/13901691/139529290-aac79cab-7295-4133-b7e1-69f32a708d1f.png)

**Comment by Jipsu** [comment]
Switching Yes and No buttons around would do wonders here. Very easy to accidentally quit a draft if you're careless or writing messages in another program.
