### ISSUE TITLE
Flame Channeler transforms by ability damage

### ISSUE THREAD

**Issue by filipebfs** [magefree/mage#8418]
[[Flame Channeler]] should only transform by spell damage.

![image](https://user-images.githubusercontent.com/2553458/139534678-4c21f0fe-a38e-488c-8dd8-9db11dc20e68.png)

**Comment by filipebfs** [comment]
[[Flame Channeler]]

**Comment by weirddan455** [comment]
I was able to reproduce this.  It looks like a similar problem to #8395.  The only information in the event is event.sourceId which refers to the card, not the ability.  So when this line from Flame Channeler executes:

`Spell spell = game.getSpellOrLKIStack(event.getSourceId());`

Viashino Pyromancer is still in LKI but we have no way of knowing from the event whether the damage was caused from casting the spell or from an ETB trigger.

**Comment by JayDi85** [comment]
`sourceId` for both events contains `attackerId` info... So you can try to find a permanent on battlefield -- if it exists then it's a trigger, ability or combat. If it doesn't exists then it's a spell. Maybe it will be work.

![shot_211031_000833](https://user-images.githubusercontent.com/8344157/139557156-4d9d8d7c-6448-4326-b94b-30ba5d999312.png)

**Comment by JayDi85** [comment]
Or maybe just check spell.isInstantOrSorcery :)

**Comment by weirddan455** [comment]
Oh yea I guess just checking instant or sorcery would work in this case.  I'll try that in a bit.

**Comment by emerald000** [comment]
Cycling a [[Deem Worthy]] should not transform the Flame Channeler.

**Comment by weirddan455** [comment]
> Cycling a [[Deem Worthy]] should not transform the Flame Channeler.

I just tested.  It doesn't with this change.  Cycling never puts a spell on the stack so nothing in LKI.
