### ISSUE TITLE
Nihiloor has multiple issues (triggers not occurring correctly, able to steal lands)

### ISSUE THREAD

**Issue by rye-bread5** [magefree/mage#8420]
With the two Nihiloor games I've played so far, I've seen three issues:

1. When I attack with a stolen creature, I both gain two life and lose two life.
2. When an opponent attacked me, they lost two life and I gained two life.
3. When I played Nihiloor, I was able to tap a creature and steal an opponent's land.

**Comment by jeffwadsworth** [comment]
[[Nihiloor]]
