### ISSUE TITLE
Alibou doesn't trigger when Esper Sentinel attacks alone

### ISSUE THREAD

**Issue by johnmeat** [magefree/mage#8424]
[[Alibou, Ancient Witness]] and [[Esper Sentinel]]. esper sentinal is an artifact creature so I believe Alibou's scry / damage ability should trigger (message log shows it hasn't against AI in test mode):

![image](https://user-images.githubusercontent.com/64497504/139593074-00900fd7-dd49-42b8-98b1-f0f9a051e041.png)

**Comment by awjackson** [comment]
Duplicate of #8228
