### ISSUE TITLE
AI Freezes When Charming Prince Enters the Battlefield

### ISSUE THREAD

**Issue by Zechr** [magefree/mage#8425]
Java Illegal State Exception: Target wasn't handled in computer's choose method: mage.target.common.TargetCreatureOrPlaneswalkerAmount

Steps to reproduce: When Charming Prince enters the battlefield, instead of getting the option to choose between its modes, the game freezes.

**Comment by Zechr** [comment]
![Screenshot 2021-11-01 21 41 12](https://user-images.githubusercontent.com/6924242/139788473-58131b4b-49be-454d-8905-1ab0f6015aa1.png)

**Comment by jeffwadsworth** [comment]
[[Charming Prince]]

**Comment by jeffwadsworth** [comment]
Just FYI:  Charming Prince is not related to this error.

**Comment by jeffwadsworth** [comment]
Unable to confirm this error.
