### ISSUE TITLE
TransformSourceEffect withoutTrigger maybe being used incorrectly

### ISSUE THREAD

**Issue by weirddan455** [magefree/mage#8427]
I've been coding the new VOW transform cards using the withoutTrigger flag on TransformSourceEffect because that's what Delver of Secrets was using.  However, I'm seeing that some cards don't have this set when they seem to be doing the same thing.

I can fix this if it's wrong but just wondering if anyone can give me some clarification on when this flag should be set.

Example:  Ambitious Farmhand does not use this flag but Delver does.  Is one of these wrong?

**Comment by theelk801** [comment]
It doesn't matter, all the arguments are removed in #8200
