### ISSUE TITLE
Rules Change: Tokens will now have "Token" in the name

### ISSUE THREAD

**Issue by theelk801** [magefree/mage#8429]
WIth the release of VOW, the name of a token will now include the word "token" at the end of its name if its name isn't otherwise specified.

Example:
- The token created by [[Doomed Dissenter]] will be named "Zombie token" as its name is not specified by the effect that creates it
- The token created by [[Sliversmith]] will be named "Metallic Sliver" as its name is specified

This will require a refactor, hopefully it can be automated fairly easily.

[source](https://twitter.com/WotC_Matt/status/1455687597376741379)

**Comment by JayDi85** [comment]
Can you link to original article or the twitter with the reason (why it was changed by wizards)?

**Comment by theelk801** [comment]
Right now the only sources are that tweet from the head editor and [this one](https://twitter.com/dunkatog/status/1455690251842641922?s=21) from the rules manager. They’ll have more details on it in the release notes.

**Comment by JayDi85** [comment]
So the reason:
> Seeing this question a lot; a rules change for token names will prevent [[Pithing Needle]] from stopping [[Blood]] tokens when you name Blood (half of the split card [[Flesh // Blood]]).

**Comment by theelk801** [comment]
yeah, it’s the first one of these artifact tokens that can be named with needle, although not the first instance of this happening ([[Goblin Wizard]] and [[Goblin Wizardry]] for example)
