### ISSUE TITLE
Can't log in, download symbols and pictures

### ISSUE THREAD

**Issue by kingreisi** [magefree/mage#8441]
Hello there,
for about i month i can't login to x-mage.
It just says "Unable connect to server. Server is not responding." I even deleted x-mage and everything.
Still the same.
But now i can't just login but i get errors when downloading symbols and it won't downloads any pictures.
![Screenshot (5)](https://user-images.githubusercontent.com/93842122/140623019-707b2a57-5841-41bb-9242-f05d77d2c16a.png)

Does anybody know what is up or is having the similar issues?

**Comment by JayDi85** [comment]
It can be proxy, ipv4 or firewall. Try [instructions from here](https://www.reddit.com/r/XMage/comments/agmcjf/new_xmage_release_with_ravnica_allegiance_rna/).

**Comment by kingreisi** [comment]
Haha, thank you very much!
