### ISSUE TITLE
Layout Mismatch Error Report

### ISSUE THREAD

**Issue by CrymsonNite** [magefree/mage#8444]
Just wanted to report the cards I've found so far that cause the layout mismatch error.
Staff of Nin - PM13 - 217*
Ant Queen - PM10 - 166*
Glissa, the Traitor - PMBS - 96*
It looks like most the foil promos cause layout mismatch error, which is disappointing, because the only reason I use promos is they have great art.

**Comment by JayDi85** [comment]
If you loads old deck files then re-save it with new cards and try again. Maybe it will help. Current version doesn't use card numbers with `*` symbol (star).

**Comment by CrymsonNite** [comment]
yeah, I just chose the ones without the *, I just wanted it to be known that I had found this
