### ISSUE TITLE
unable to contact server. server is not responding

### ISSUE THREAD

**Issue by PsyLordJGG** [magefree/mage#8447]
i keep getting this problem everytime i try to log into the server. is xmage down? i check server status and everything is operational.

**Comment by JayDi85** [comment]
All servers works fine. It's a bad connection from your side. You must check firewall, proxy and ipv4 fixes/settings in the client. More details are [here](https://www.reddit.com/r/XMage/comments/agmcjf/new_xmage_release_with_ravnica_allegiance_rna/).
