### ISSUE TITLE
Game Error: playing with Dryad Of The Ilysian Grove

### ISSUE THREAD

**Issue by Ozwellx** [magefree/mage#8449]
Game exception occurred: java.lang.ClassCastException: mage.cards.d.DryadOfTheIlysianGrove cannot be cast to mage.game.permanent.Permanent
Server version: 1.4.50-V2 (build: 2021-09-05 18:59)
mage.cards.c.GiveControlEffect.apply(CustodyBattle.java:94)
mage.abilities.effects.ContinuousEffectImpl.apply(ContinuousEffectImpl.java:112)
mage.abilities.effects.ContinuousEffects.apply(ContinuousEffects.java:1021)
mage.game.GameState.applyEffects(GameState.java:643)
mage.game.GameImpl.applyEffects(GameImpl.java:1733)
mage.game.GameImpl.leave(GameImpl.java:2966)
mage.game.GameImpl.checkConcede(GameImpl.java:771)
mage.game.GameImpl.checkStateAndTriggered(GameImpl.java:1994)
mage.game.GameImpl.playPriority(GameImpl.java:1499)
mage.game.turn.Step.priority(Step.java:61)
mage.game.turn.CombatDamageStep.priority(CombatDamageStep.java:31)
mage.game.turn.Phase.playStep(Phase.java:184)
mage.game.turn.Phase.play(Phase.java:89)
mage.game.turn.Turn.play(Turn.java:128)
mage.game.GameImpl.playTurn(GameImpl.java:1034)
mage.game.GameImpl.play(GameImpl.java:944)
mage.game.GameImpl.start(GameImpl.java:920)
mage.server.game.GameWorker.call(GameWorker.java:34)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)

**Comment by jeffwadsworth** [comment]
[[Custody Battle]]

**Comment by jeffwadsworth** [comment]
Yikes.  I forgot how badly global continuous effects are in regards to something like [[Dryad Of The Ilysian Grove]].  Brutal.
