### ISSUE TITLE
Metamorphic Alteration copying a face-down creature results in wrong P/T

### ISSUE THREAD

**Issue by awjackson** [magefree/mage#8456]
If you enchant a creature with Metamorphic Alteration and choose a face-down creature as the thing to make it a copy of, the enchanted creature gets the face-up P/T of the copied creature, not the face-down values (normally 2/2).

![metamorphic alteration 1](https://user-images.githubusercontent.com/9252545/141692808-4d01540b-8b66-4233-951b-2642679230b8.png)

This seems to be specific to Metamorphic Alteration rather than a bug with copying effects in general--I tested with Shapesharer and it correctly became a 2/2 when copying a face-down creature.

**Comment by awjackson** [comment]
c355834a4e6c7fa6b02adaa0813ebdd1e5409fb1 fixes the most basic use case (copying a creature that is face down because it was cast as a morph) but there still seem to be many issues with how copying interacts with face down cards and with how we handle face down cards in general.

**Comment by Alex-Vasile** [comment]
> [c355834](https://github.com/magefree/mage/commit/c355834a4e6c7fa6b02adaa0813ebdd1e5409fb1) fixes the most basic use case (copying a creature that is face down because it was cast as a morph) but there still seem to be many issues with how copying interacts with face down cards (e.g. the enchanted creature in the screenshot has copied the subtype Bird from the face-down card, which it shouldn't have) and with how we handle face down cards in general.

Do you know if this has been addressed? Or does an issue need to be opened for it?
