### ISSUE TITLE
Dorothea, Vengeful Victim automatically gets removed from game once casted for its Disturb cost

### ISSUE THREAD

**Issue by cashmoneyhoes** [magefree/mage#8457]
![image](https://user-images.githubusercontent.com/90292347/141704779-a33c833a-c488-4a81-8b46-abbfdd8cdef0.png)
As shown in the log, I cast [[Dorothea, Vengeful Victim]] from the graveyard with its Disturb cost, coming back as Dorothea's Retribution, but Dorothea just gets exiled as soon as it hits the battlefield.

**Comment by jeffwadsworth** [comment]
That spell on the stack is the front-side, not the transformed side.  Thus, you don't get a target prompt.

**Comment by JayDi85** [comment]
Stack must contains transformed side on cast with disturb.

**Comment by awjackson** [comment]
The targets and effects of a spell are properties of the `SpellAbility` that's been put on the stack, not of the card (think of cards like Overload cards, which have alternate `SpellAbility`s that do totally different things) Thus, transforming the *card* while it's on the stack won't result in the correct targets or effects being used. I believe it is necessary to add them to the DisturbAbility (SpellAbility subclass) itself.
