### ISSUE TITLE
Xmage not found

### ISSUE THREAD

**Issue by kilopro** [magefree/mage#846]
Not sure where to ask this, but I just downloaded the xmage launcher and tried installing it but I keep getting this error. I have check my java versions many times. Any suggestions?

Downloading XMage from http://bit.ly/XMage2015-03-14v5
Java version installed:  1.8.0_40
Java version available:  1.8.0_40
XMage version installed:  
XMage version available:  1.3.0.dev2015-03-14v5 (2015-03-26)
XMage not found
Failed to download XMage from http://bit.ly/XMage2015-03-14v5

**Comment by pet142** [comment]
Same issue.

**Comment by bieno002** [comment]
Me too.  I already had XMage installed but trying to update keeps failing so I can't join any servers.

**Comment by rothgar88** [comment]
Exact same error here. Worked fine before today. Running on OS X.
Tried reinstalling, no change.

**Comment by kilopro** [comment]
found a link to the actually game download and its broken

http://www.slightlymagic.net/forum/viewtopic.php?f=70&t=16905&p=175032#p175032

**Comment by LevelX2** [comment]
Added a second download URL to the launcher config. 
It checks the first and if this fails the launcher tries to download from the second link.

So try again now, it should work.
