### ISSUE TITLE
Psychic Vortex and Obeka

### ISSUE THREAD

**Issue by MatFont** [magefree/mage#8460]
I got the following problem.
I can't use obeka effect on the end turn trigger of Psychic Vortex.
Is it possible to patch this?
Thanks a lot for your work.

**Comment by jeffwadsworth** [comment]
[[Psychic Vortex]] [[Obeka, Brute Chronologist]]

**Comment by theelk801** [comment]
can you elaborate on what was wrong?

**Comment by MatFont** [comment]
> can you elaborate on what was wrong?

At the end of my turn, psychic vortex trigger and i should sacrfice a land and discard my hand.
But with the end of turn effect of obeka, i should negate this effect while it's on the stack.
In the game when i tried that, i couldn't use obeka efffect on the stack. There was no moment to answer to the trigger.
Sorry for the bad english, don't hesitate to ask anything if it's not clear.

**Comment by theelk801** [comment]
So the trigger was on the stack, then before it resolved you tried to activate Obeka but couldn't?

**Comment by MatFont** [comment]
> So the trigger was on the stack, then before it resolved you tried to activate Obeka but couldn't?

Exactly

**Comment by theelk801** [comment]
Oh I see what happened, Vortex is implemented wrong and requires you to target a land when it triggers, so it was making you choose the land even though you would then be able to activate Obeka afterward and avoid sacrificing it. I'll fix it.
