### ISSUE TITLE
Zam Wesell must be reworked to use EntersBattlefieldAbility

### ISSUE THREAD

**Issue by JayDi85** [magefree/mage#8463]
Current implementation of Zam Wesell card (from Star Wars set) doesn't work:
> When you cast Zam Wesell, target opponent reveals their hand. You may choose a creature card from it and have Zam Wesell enter the battlefield as a copy of that creature card.

It must use `EntersBattlefieldAbility` to apply copy effect. See related test in `test_Copy_AsCloneFromCard_ZamWesell`

**Comment by Alex-Vasile** [comment]
What is a good card to look at for how to pass information from one ability to one that resolves later?

**Comment by sprangg** [comment]
This can be closed now that https://github.com/magefree/mage/pull/9799 has been merged
