### ISSUE TITLE
Sludge Monster's ability sometimes does not apply

### ISSUE THREAD

**Issue by alexander-novo** [magefree/mage#8466]
Sometimes, [[Sludge Monster]]'s ability doesn't apply, leaving creatures with slime counters on them with all their abilities and full stats.

![image](https://user-images.githubusercontent.com/11657716/142360362-901d0ae7-619d-4990-9491-04ed51a2407a.png)

Both the Niv-Mizzet and the opposition agent have slim counters on them, but Niv-Mizzet is full stats and has all abilities, while opp agent is a 2/2 with no abilities.

I've noticed in this game that it seems like only the first slime counter has worked (even flickering doesn't work properly), but counters from [[Toxrill]] work fine.

**Comment by theelk801** [comment]
fixed with 9ca9bfa
