### ISSUE TITLE
Support optional extra stages in tournaments

### ISSUE THREAD

**Issue by phughk** [magefree/mage#8467]
We were just playing a community picked tribal chaos format at XDHS. The rules were to draft as normal, save the picked cards as a deck, load up into the deck builder, add additional cards that were allowed (in this case, a fixed list of changelings limited to 1 each), save the deck, and rejoin the tournament with the deck.

It's really cool that this was at all possible. We were wondering if there would be the possibility to add these additional steps as part of the tournament. Some sort of wider deck building (beyond draft) and/or rules verification (ex card list, card count).

Another way to achieve this is to preload the sideboard with some additional cards.

Would this be an feasible change to introduce? Is it possible to add it as a plugin? Are there classes you could point to to have a look at how this could be added?

Thanks for all your hard work!

**Comment by JayDi85** [comment]
Additional steps for drafting are hard to implement. And its a very rare feature.
