### ISSUE TITLE
Tergrid didn't get haste when put into play via Sneak Attack.

### ISSUE THREAD

**Issue by Grath** [magefree/mage#8469]
![image](https://user-images.githubusercontent.com/1895280/142571642-d186e5f7-4706-4038-a693-38f3be5412d9.png)
You can see that Tergrid was put into play via Sneak Attack from the game log on the right side. I'm in combat now, and Tergrid doesn't have haste so I can't attack with her.

**Comment by jeffwadsworth** [comment]
[[Sneak Attack]]

**Comment by Alex-Vasile** [comment]
Duplicate of #8474
