### ISSUE TITLE
Unable connect to server. Server is not responding

### ISSUE THREAD

**Issue by SpartanWarrior13** [magefree/mage#8470]
I have ran into an issue recently where when I launch xmage client, I cannot connect to any servers. I tried every option multiple times and always get the same message. "Unable connect to server. Server is not responding." I cannot find any cause to this, as several friends will be actively playing a match, so I know the servers are not down. I have tried most of the fixes mentioned in the earlier post, but have had no luck and cannot get the rest to function as described
![Xmage not working](https://user-images.githubusercontent.com/94705024/142664216-8b92922c-ff46-45d7-aeb7-d51f278eb016.PNG)

**Comment by jeffwadsworth** [comment]
Try to ping the server name first to verify that it resolves to an ip address.  If it does, then verify that you can reach that port address on the server.

**Comment by JayDi85** [comment]
It's a bad connection from your side. You must check firewall/vpn, proxy and ipv4 fixes/settings in the client. More details are [here](https://www.reddit.com/r/XMage/comments/agmcjf/new_xmage_release_with_ravnica_allegiance_rna/).

**Comment by SpartanWarrior13** [comment]
> It's a bad connection from your side. You must check firewall/vpn, proxy and ipv4 fixes/settings in the client. More details are [here](https://www.reddit.com/r/XMage/comments/agmcjf/new_xmage_release_with_ravnica_allegiance_rna/).

I have already went through most of this list, and cannot get the rest to work as detailed by the post. Still have not resolved the issue

**Comment by CCTV-1** [comment]
> > It's a bad connection from your side. You must check firewall/vpn, proxy and ipv4 fixes/settings in the client. More details are [here](https://www.reddit.com/r/XMage/comments/agmcjf/new_xmage_release_with_ravnica_allegiance_rna/).
> 
> I have already went through most of this list, and cannot get the rest to work as detailed by the post. Still have not resolved the issue

if your jre version is ` 1.8.0_311`,try downgrade jre to `1.8.0_202` ,this might help you.

**Comment by Alex-Vasile** [comment]
This should be fixed by #8627 if it was the JRE version issue.

@SpartanWarrior13, do you still have this issue on the newest beta?
