### ISSUE TITLE
Token copies of MDFC cards have the types and abilities of both sides

### ISSUE THREAD

**Issue by alexander-novo** [magefree/mage#8476]
Token copies of MDFC cards have the types and abilities of both sides. Note this means token copies of MDFC *cards*, not MDFC permanents (i.e. the MDFCs have to be in a non-battlefield zone). Just observed with [[Feldon of the Third Path]] creating a copy of [[Tergrid, God of Fright]] from the graveyard, below:

![image](https://user-images.githubusercontent.com/11657716/142940363-5004570c-550e-484d-9066-8a1cd2f0985f.png)

**Comment by JayDi85** [comment]
Fixed by 6b86b1053fc10fa0e7ed9872f55d43f093acc229

![shot_240526_123956](https://github.com/magefree/mage/assets/8344157/206c10ba-2523-4817-b7a8-0393a71d1a6c)
