### ISSUE TITLE
Extra tokens from Chatterfang shouldn't enter tapped

### ISSUE THREAD

**Issue by theelk801** [magefree/mage#8477]
When extra tokens are made by [[Chatterfang, Squirrel General]], if the original tokens would enter tapped (like from [[Verdant Command]]), the additional ones shouldn't also be tapped. This will probably require refactoring token events, which hopefully isn't too much work. 

@weirddan455 I know you recently updated the token stuff so I dunno if you wanna take this but I don't mind doing it either

**Comment by Grath** [comment]
From the rulings on Chatterfang:

> The additional Squirrel tokens won’t have any abilities the other tokens were created with. Anything else specified in the effect creating the token (such as **tapped,** attacking, “That token gains haste,” or “Exile that token at end of combat”) applies to both the original tokens and the Squirrels.
> (2021-06-18)
