### ISSUE TITLE
Potential improvement: Select Creature Type dialogue sorted with creature types you currently have.

### ISSUE THREAD

**Issue by Grath** [magefree/mage#8478]
Don't know how feasible this is, but I'm most commonly selecting creature types for Urza's Incubator and Cavern of Souls in tribal decks. It would be nice if the creature types you have (in the deck, in play/your hand, whatever's the most simple) could be sorted to the top of the list so you can just pick your tribe from the top couple entries in the list rather than needing to type it in to search.

**Comment by JayDi85** [comment]
Check card hint popup in text mode (use mouse wheel to switch from image). It must contains additional info.

**Comment by Grath** [comment]
I know how to see which type was actually chosen. I would like it to be more easy to choose a (relevant) creature type. If I'm playing Dragon Tribal, I don't understand why Kithkin is ever the first choice in the creature type list.

**Comment by CommanderMasterEDH** [comment]
i get what he's asking

why not do it the same way forge does it? the first creature type on top is usually the tribe your using based on your deck list.

**Comment by JayDi85** [comment]
> If I'm playing Dragon Tribal, I don't understand why Kithkin is ever the first choice in the creature type list

Creature types list in choose dialog must be sorted by name. I'll check it.

> the same way forge does it

Creature type dialog is limited to a standard GUI, so you can't add additional elements to it (except description or popup hint). Maybe it can be improved with special sorting and hint.

**Comment by peter-thoenen** [comment]
@CommanderMasterEDH It's better to do it the MTGO does it over Forge in that it gives you the option based on what's on the board (for either player) AND YOUR hand, i.e. often your own decklist is pointless with the most common case, plague engineer and generally if you are playing something where this would come up on your own side (cavern) you probably either got one in your hand already OR on the board as well (fish, etc).

**Comment by JayDi85** [comment]
Example of new choose creature type dialog:

![shot_240719_030524](https://github.com/user-attachments/assets/5785c6fc-0999-4c19-8349-2b21f41b90f4)
