### ISSUE TITLE
Solemn doesn't trigger on death- Daretti PW - 2 ability

### ISSUE THREAD

**Issue by JohnPetfield** [magefree/mage#8481]
[[Daretti, Scrap Savant]] & [[Solemn Simulacrum]] on bf, [[Sol Ring]] in GY. Use Daretti's -2 ability sacrifice Solemn to bring back the Sol Ring, Solemn's death trigger doesn't happen:

![image](https://user-images.githubusercontent.com/64497504/143623920-52bc4eb9-dbbc-4776-997f-e8c4ec7b2244.png)

Sacrificing Solemn too [[Krark-Clan Ironworks]] or killing it with [[Lightning Bolt]] work fine.

**Comment by johnmeat** [comment]
The same is true for [[Hangarback Walker]], i.e. no death trigger when it has counters on when it's sacrificed to Daretti's -2 ability, triggers fine when sacrificed to KCI.
