### ISSUE TITLE
Rhoda,  Geist Avenger & Timin, Youthful Geist can't be commander partners

### ISSUE THREAD

**Issue by Bdett151** [magefree/mage#8482]
Won't allow me to use Rhoda and Timin as partner commanders. When trying to start game with the deck, got an error that stated they are not legal commanders.

**Comment by emerald000** [comment]
Can you share the deck file you are trying to load?

**Comment by Bdett151** [comment]
I can't seem to attach the deck file but I have attached an image of the error I am receiving when trying to start a game.
![Screenshot 2021-11-27 141818](https://user-images.githubusercontent.com/76190939/143719490-34b7af49-ca6d-49c5-b790-0ffb475c1aaf.png)

**Comment by theelk801** [comment]
this might be my fault, I’ll take a look at it
