### ISSUE TITLE
Authority of the Consuls and Blind Obedience bugs

### ISSUE THREAD

**Issue by catman123456** [magefree/mage#8487]
![image](https://user-images.githubusercontent.com/64045003/143683047-ad8440df-ca3f-4b67-b858-22435ec835df.png)

with Authority of the Consuls and Blind Obedience the creatures aren't coming in tapped and the extort is not activating.  

![image](https://user-images.githubusercontent.com/64045003/143683307-a09c6d12-55a1-4ccc-97bb-1c967ee1fc2a.png)

Thalia, Heretic Cathar is effecting me too

**Comment by awjackson** [comment]
Fixed by fa1051cec389679eabc48428dd17dd0b37959776
