### ISSUE TITLE
Loyal Apprentice makes 2 thopters with Partner commanders

### ISSUE THREAD

**Issue by brendansileo** [magefree/mage#8496]
When [[Loyal Apprentice]] makes a thopter at the beginning of combat while I have two commanders, it generates 1 with haste and 1 without haste each turn.

**Comment by brendansileo** [comment]
I had this happen about 10 minutes ago in a game I'm currently playing.

**Comment by johnmeat** [comment]
It isn't live yet I don't think.

**Comment by brendansileo** [comment]
Ahh gotcha, thanks!
