### ISSUE TITLE
Visions of Dominance accurately highlights as playable, but the actual flashback cost isn't discounted.

### ISSUE THREAD

**Issue by Grath** [magefree/mage#8499]
I suspect the rest of the cycle might be similarly bugged, but I haven't confirmed yet.

**Comment by Grath** [comment]
Can confirm, Visions of Glory has the same bug.

**Comment by jeffwadsworth** [comment]
[[Visions of Dominance]]

**Comment by Alex-Vasile** [comment]
Closing this as duplicate of #8454. See that issue for more info about problem. When that one is fixed, this and the other Visions of X will be fixed.

**Comment by Alex-Vasile** [comment]
Closing this as a duplicate. See that issue for more info about problem. When that one is fixed, this and the other Visions of X will be fixed.
