### ISSUE TITLE
BUG: No deathtriggers when sacrificing with Arcum Daggson's ability (EDH)

### ISSUE THREAD

**Issue by Furani** [magefree/mage#8501]
As described in the title, I play Arcum Daggson as my commander for several months now. And there are no deathtriggers when I sacrifice an artifact creature to his ability. (E.g. no draw-trigger when I sacrifice a Solemn Simulacrum) Deathtriggers that are not tied to the sacrificed creature, do trigger correctly. (E.g. Dross Scorpion, Thornbite Staff, etc.)

This happens with any creature that has a die-trigger. I tested with all kind of creatures (Solemn Simulacrum, Cathodion, Myr Retriever, Scrap Trawler, etc.). And never had any creature trigger.

Normally the creatures should trigger according to the official rulings related to the card.
"Any triggered abilities that trigger when the creature is sacrificed will be put onto the stack at the same time as any triggered abilities that trigger when the noncreature artifact enters the battlefield."
[https://gatherer.wizards.com/pages/card/Details.aspx?multiverseid=122124](url)

**Comment by weirddan455** [comment]
Confirmed bugged.  I tested with Solem Simulacrum.  If you choose to search your library, the death trigger never goes on the stack but if you decline to search, it does.

I'm not sure right now what the cause is.  Might be that the 2 zone change events are getting batched together.  Needs more investigation.

**Comment by weirddan455** [comment]
Did some debugging on this and it's failing the isInUsableZone check.  Looks like a case of the problem described in this TODO.  Not sure if there's an existing issue for this or not but it looks like a known bug that could take some in depth engine changes to fix.

https://github.com/magefree/mage/blob/86023e416418c5625fcd365d86477b42a8dfdd50/Mage/src/main/java/mage/abilities/TriggeredAbilityImpl.java#L299-L326

**Comment by JayDi85** [comment]
@weirddan455 can you test with that line?

`game.getState().processAction(game);`
![shot_211204_220712](https://user-images.githubusercontent.com/8344157/144719960-fe09f22d-e3e3-4bfe-80ba-963fd5b47c63.png)

**Comment by weirddan455** [comment]
> @weirddan455 can you test with that line?
> 
> `game.getState().processAction(game);` ![shot_211204_220712](https://user-images.githubusercontent.com/8344157/144719960-fe09f22d-e3e3-4bfe-80ba-963fd5b47c63.png)

Yea, looks like that fixes it.

**Comment by weirddan455** [comment]
@JayDi85 Should I just go ahead and push that change out if that's all we need to do?

**Comment by JayDi85** [comment]
Yes, you can add as fix.
