### ISSUE TITLE
Mistmeadow Witch doesn't return flickered creature to play if the Witch is no longer in play

### ISSUE THREAD

**Issue by Jipsu** [magefree/mage#8504]
If [[Mistmeadow Witch]] exiles a creature the creature doesn't return to the battlefield if the Witch is killed. Same bug happens if you use a Witch's ability to flicker itself. Having multiple Mistmeadow Witches in play makes no difference if the one that used the ability is no longer there at end step.

**Comment by jeffwadsworth** [comment]
Worked fine for me in the latest build.
