### ISSUE TITLE
Trying to join servers from IntelljIdea doesn't work

### ISSUE THREAD

**Issue by grandogarndo** [magefree/mage#8510]
The server seems to work and so does the client, I can view cards, change preferences, etc, but connecting to any servers, even my local one I know works doesn't work. Log: https://pastebin.com/FWQuMna2
I'm just doing this to try and use a custom card, I know the card loads in the game without causing any errors and I don't even have it in the files yet, I'm going to put it in when I can figure out the problem. Maybe I could add the card to a regular Xmage client but I don't know how to do that. Any help is awesome!

**Comment by JayDi85** [comment]
You can't use developer version (from sources) with current servers -- it's incompatible in most use cases. Versions must be same (example: [beta version + beta server](http://xmage.today/)).

If you run server app from sources too then it must works fine. Your logs contains `10.0.0.220:17171` -- you must able connect by `localhost` (127.0.0.1) to your machine. Maybe something wrong with host settings (some linux os doesn't have `localhost` record by default so you must add it manually, see your os instructions).

**Comment by grandogarndo** [comment]
Yeah I'm running the server from the same exact code, so it should work.

**Comment by JayDi85** [comment]
BTW if you want a custom card then you must:
* add card as new class;
* add card to one of the set (or add new custom set);
* delete `db` folders from server and client root dirs (Mage.Client\db and Mage.Server\db);
* it allows to see that card in deck editor and play it (I recommends to [run server with test mode](https://github.com/magefree/mage/wiki/Development-Testing-Tools#server-test-mode) and use cheats for testing)
* if you changed something in the card then no need to delete `db` folder (db used to show a card and popup info, but all code logic used from class file);

**Comment by grandogarndo** [comment]
Yeah I don't actually have the custom card in the files yet, I was just trying to get the server and the client to work, which I have done before in the same coding environment.  I have gotten the card to be implemented into the deck editor before, its just this weird problem with login in to any server, even my local one.

**Comment by grandogarndo** [comment]
Ok I might know the problem, the second port the server is pointing to is 17179,  while I have it as 17172 on my non-intelljidea server (which does work). Is there any way to change this?

**Comment by JayDi85** [comment]
You can change it by config: `Mage.Server\config\config.xml` as `secondaryBindPort` param

**Comment by grandogarndo** [comment]
OK so I copy pasted the exact config from my server I use to the config on this server, and when connecting with a regular or IntellIdea client it doesn't work. So I think there is a problem with the IntellJIdea client that needs to be fixed that will allow it connect to the IntellJidea server, or maybe the server is busted, or maybe both.

**Comment by JayDi85** [comment]
IntelliJ IDEA uses own java version (look at project settings). You must open firewall for that java.

**Comment by JayDi85** [comment]
Also make sure by logs that a server app started and listening correct address (0.0.0.0 or local ip).

**Comment by grandogarndo** [comment]
Yeah all of my java and intellij apps are forwarded both ways and my ip is port forwarded, it doesn't seem to matter either way. Is there any report of errors like this before? I'll resend my logs. Server: https://pastebin.com/Krya0JDW Client:https://pastebin.com/cZAfkJdC

**Comment by JayDi85** [comment]
@grandogarndo upload logs again, I can't open it.

**Comment by grandogarndo** [comment]
Client: https://pastebin.com/RzuFzZA6
Server: https://pastebin.com/RRgj3qAC
Yeah sorry I had to sign in, maybe I was pasting so much pastebin thought I was a bot and deleted my stuff.

**Comment by JayDi85** [comment]
Send me logs to jaydi85@gmail.com

**Comment by Alex-Vasile** [comment]
Same issue.
macOS (m1 arm cpu)

[mageclient.txt](https://github.com/magefree/mage/files/7918991/mageclient.txt)
[mageserver.txt](https://github.com/magefree/mage/files/7918992/mageserver.txt)

**Comment by Alex-Vasile** [comment]
@grandogarndo this issue should have been fixed in with a recent PR that fixes the networking issues.

Do you still have this issue?

**Comment by grandogarndo** [comment]
Nope we figured it out, it was an issue with the Java version.
