### ISSUE TITLE
Meren doesn't trigger from deaths from Necromantic Selection

### ISSUE THREAD

**Issue by johnmeat** [magefree/mage#8515]
[[Necromantic Selection]] [[Meren of Clan Nel Toth]].
Before:
![image](https://user-images.githubusercontent.com/64497504/145824994-6c9d1807-8be2-4343-92eb-8832fd5b6218.png)
After:
![image](https://user-images.githubusercontent.com/64497504/145825084-58cd3df0-9192-4139-857a-bc0e0f3c8b71.png)
Can see from game log, no Meren triggers to gain experience

**Comment by jeffwadsworth** [comment]
Ruling: If Meren of Clan Nel Toth leaves the battlefield at the same time as other creatures you control die, its first ability will trigger for each of those creatures.
