### ISSUE TITLE
Loyal Apprentice triggers if you control any commander, not just your commander.

### ISSUE THREAD

**Issue by Grath** [magefree/mage#8516]
I stole an opponent's commander with [[Dominating Licid]] and [[Loyal Apprentice]] triggered, when it should only trigger for controlling my commander.

**Comment by sumsarz** [comment]
To expand on this issue, when you control your commander Loyal Apprentice creates two thopters. One as expected with haste, and another one that is summoning sick.

**Comment by Alex-Vasile** [comment]
The double token creation was fixed in https://github.com/magefree/mage/commit/70b5a48c23e18de862f74c1bf910d2a64fe22955.

**Comment by Alex-Vasile** [comment]
Closed in 62a8983b48a2647b1d8cf7638b024ec528d0a4fd
