### ISSUE TITLE
Dragonlord Atarka Trigger does not go off

### ISSUE THREAD

**Issue by mewhite42** [magefree/mage#852]
I played a Dragonlord Atarka against a control player with no creatures but did have a Narset Transendent.  Atarka's EotB effect never went off to let me deal 5 damage to Narset.

**Comment by FenrisulfrX** [comment]
With https://github.com/magefree/mage/blob/master/Mage/src/mage/target/common/TargetCreatureOrPlaneswalkerAmount.java#L68 commented out the card works fine. Anyone knows if this is necessary and/or correct?
