### ISSUE TITLE
Random Booster Draft Packs Selector Dialog cut off and not resizable

### ISSUE THREAD

**Issue by jumpinjackie** [magefree/mage#8526]
Version: git master 18db39f131721c4d80f158810d6ccb7a630f0f87

The dialog for picking random booster draft packs is cut off and I have no idea what the button(s) on the right are.

![2021-12-19 01_25_15-Window](https://user-images.githubusercontent.com/563860/146644424-e3c94b82-0fee-4a9c-8a7d-39469847b97d.png)

**Comment by sprangg** [comment]
As a workaround, you can see what the hidden set is when you hover your mouse over its checkbox.

**Comment by Jipsu** [comment]
This issue has gotten worse with new sets coming to beta (duplicate in #7236 ). Now you can't select the rightmost sets at all and you can't click Accept. The completely hidden column is: ZNR, GRN, KLD, M15, DKA, ARB, CSP, LGN, UDS, MIR, ARN. 

Workaround is to navigate to hidden column with tab and use space to select/unselect. Same with Accept: click on LEA, hit tab three times, press space. Alternatively you can edit whatever is stored in Settings: Load by using Windows registry editor (can't remember where settings are on OSX and Linux). Registry location is something like Computer\HKEY_CURRENT_USER\SOFTWARE\JavaSoft\Prefs\mage\client and the line you want to modify is for example New/Tournament/Packs/Draft1 (this would be config1 for swiss draft).
