### ISSUE TITLE
Thing in the Ice - Dress Down interaction not working as intended

### ISSUE THREAD

**Issue by CosminBurloiu** [magefree/mage#8529]
There is a combo where I Dress Down on opponents End Step, then I cast Thing in the Ice on my main step. This should make my Thing In the Ice creature have 0 counters.

This doesn't happen on the actual xMage release, and it just enters with 4 counters.

The proper interaction can be observed here: https://youtu.be/yXAX8Bq27hY?t=1017

**Comment by Grath** [comment]
Duplicate of #4202 (and #8122 and #8176 ) - XMage cannot currently handle effects like this.

**Comment by jeffwadsworth** [comment]
[[Thing in the Ice]]

**Comment by awjackson** [comment]
Closing as duplicate
