### ISSUE TITLE
When a clone of Mosswort Bridge enters the battlefield, it triggers the ability of the first Mosswort Bridge

### ISSUE THREAD

**Issue by dashosa** [magefree/mage#8539]
When a clone of Mosswort Bridge enters the battlefield, it triggers the ability of the first Mosswort Bridge, as well as its own ability. Mosswort Bridge seems to say whenever a Mosswort Bridge enters *Hideaway" rather than whenever this land enters *Hideaway*.

**Comment by awjackson** [comment]
What card were you using to copy the Mosswort Bridge? I've just tested with [[Vesuva]] and with [[Moritte of the Frost]] and was unable to duplicate.
