### ISSUE TITLE
Split cards have blank text boxes in the deck builder

### ISSUE THREAD

**Issue by awjackson** [magefree/mage#8541]
Both the rendered card and the popup window display no rules text whatsover.
![Screenshot_20220102_012611](https://user-images.githubusercontent.com/9252545/147868065-203f50a1-5e00-463e-b735-e5d37cae7f91.png)

**Comment by awjackson** [comment]
The card viewer and draft are also affected. Basically, any time that a game is not in progress, split cards have no text.

**Comment by awjackson** [comment]
git bisect indicates that this regressed with https://github.com/magefree/mage/commit/76e57d009e8c2bd1bef300a35162c82f28d41ab4 (presumably, the removal of split card halves from the card database)

**Comment by theelk801** [comment]
can confirm that adding split halves back in completely fixes the issue
<img width="775" alt="image" src="https://user-images.githubusercontent.com/29759218/157879026-61743411-e78a-485d-8093-0e451fdd1b23.png">

not sure if we want to fix it a different way

**Comment by Alex-Vasile** [comment]
> can confirm that adding split halves back in completely fixes the issue <img alt="image" width="775" src="https://user-images.githubusercontent.com/29759218/157879026-61743411-e78a-485d-8093-0e451fdd1b23.png">
> 
> not sure if we want to fix it a different way

What was the reason for deleting it in the first place?

**Comment by theelk801** [comment]
I think it was just an attempt at optimizing the database

**Comment by Alex-Vasile** [comment]
> I think it was just an attempt at optimizing the database

That makes sense.

Would doing the same for dual face cards fix #8664?

**Comment by theelk801** [comment]
it would but I don't think it's necessary as `CardInfo` has a `secondSideName` field
