### ISSUE TITLE
Is there a way to upload my cube to the draft tournament drop down list? 

### ISSUE THREAD

**Issue by 1BrainFreeze1** [magefree/mage#8544]
instead of drafting from a deck? Thank you kindly.

**Comment by Alex-Vasile** [comment]
If you scroll the list to the bottom of the "Draft Cube" dropdown , there's a "Cube from deck" option. Is that what you're looking for?

![cube](https://user-images.githubusercontent.com/48962821/179142611-1f3ff4e9-f17f-4676-80de-03de73377bab.jpg)
