### ISSUE TITLE
Lotus Field still comes in tapped with Blood Sun on the field

### ISSUE THREAD

**Issue by cashmoneyhoes** [magefree/mage#8545]
![image](https://user-images.githubusercontent.com/90292347/148440864-2e12526e-6802-491e-99d2-d0d4cc5b509b.png)
As I understand it, [[Blood Sun]] overrides ETB tapped effects ever since the Ixalan rule change, so shouldn't [[Lotus Field]] come in untapped with Blood Sun already on the field? Apologies if I'm mistaken.

**Comment by jeffwadsworth** [comment]
This is a known issue and there is no fix on the horizon, unfortunately.  Note the Blood Moon issue.
https://github.com/magefree/mage/issues/4202

**Comment by copperfield42** [comment]
@jeffwadsworth how about this as a potential fix for the blood moon problem: add an additional effect to all tap land that check if Blood Moon is out and untap it or not tap it whatever is easier, given that tap and conditional tap land already work fine might as well make all tap lands into conditional tap one by checking for Blood Moon and friends in addition to their normal condition. This way there is no need to mess with whatever dark magic is stopping the proper working of Blood Moon and I think that it should work fine most of the time save for some weird and very specific scenery.

**Comment by awjackson** [comment]
Closing as duplicate
