### ISSUE TITLE
Nihiloor - both triggered abilities not implemented correctly

### ISSUE THREAD

**Issue by johnmeat** [magefree/mage#8547]
[[Nihiloor]] ETB trigger:

Tapping down a creature of your own allows you to gain control of other permanents such as lands and artifacts as well as creatures:
![image](https://user-images.githubusercontent.com/64497504/148641262-74a798fa-3bcf-4505-8b16-0403ecf0075e.png)

Attack trigger:

In a live game yesterday it's attack trigger would trigger for any creature attacking any opponent, it should be only for creatures that attack, that the Nihiloor player controls but does not own. Below screenshot shows the AI in test mode attacking me and Nihiloor has triggered:

![image](https://user-images.githubusercontent.com/64497504/148641825-03c518d4-f8ee-460b-a0bf-33fa116d8db5.png)

**Comment by jeffwadsworth** [comment]
Already fixed.  Just wait for the new release or use the beta.

**Comment by johnmeat** [comment]
informed has been already fixed, but not live.
