### ISSUE TITLE
Wrong interaction between Mogg Infestation and Ogre Battledriver

### ISSUE THREAD

**Issue by Reya87** [magefree/mage#8548]
Hello,

An opponent casted Mogg Infestation with 4 creatures on board (with an Ogre Battledriver among his creatures). When Mogg Infestation fully resolved, Ogre Battledriver triggered for each token creature created by Mogg Infestation.

This is wrong since the Ogre is already dead when tokens from Mogg Infestation are created.

**Comment by jeffwadsworth** [comment]
[[Mogg Infestation]]  [[Ogre Battledriver]]
