### ISSUE TITLE
Cannot download images.

### ISSUE THREAD

**Issue by TheWarrior987** [magefree/mage#8554]
Whenever I attempt to download images, even from just a set, it will either not download at all, or download everything except the last card, and then stop. I have tried every source, I have tried setting thethreads to 1, nothing works.

**Comment by JayDi85** [comment]
You must restart app after new images downloaded. Use only scryfall source. Use ipv4 settings from [here](https://www.reddit.com/r/XMage/comments/agmcjf/new_xmage_release_with_ravnica_allegiance_rna/). If you see utf-8 warning in startup logs then follow instructions from the log (you must add additional param to the launcher).

**Comment by TheWarrior987** [comment]
Thank you, the fix worked
