### ISSUE TITLE
Elkin Lair only allows for cast, not play

### ISSUE THREAD

**Issue by sumsarz** [magefree/mage#8558]
Expected: You can play a card exiled from hand with [[Elkin Lair]].

Actual: You can only cast a card exiled from hand.

**Comment by jeffwadsworth** [comment]
The code looks okay but I will test it soon.

**Comment by sumsarz** [comment]
I found the bug referenced buried in the bug compilation #6075 later.

**Comment by Alex-Vasile** [comment]
Can confirm this is happening

**Comment by Alex-Vasile** [comment]
Could not reproduce on the beta.

The linked issue was still open (fixing it) and stopped you from playing cards if you were not the owner of the lair.
