### ISSUE TITLE
Batch functionality for activated abilities

### ISSUE THREAD

**Issue by thefnitalian** [magefree/mage#8559]
![Capture](https://user-images.githubusercontent.com/14006184/149631277-b89d6193-2697-4844-9461-c675444902f5.PNG)
Add in a right click function for the transparent menu to allow the active player to choose how many times he or she would like to activate the ability that uses the GUI for Removing multiple +1/+1 counters so that you can specify how many then xmage would ask you to pay any relevant costs for the whole batch and then put that many activated abilities on the stack.

**Comment by JayDi85** [comment]
[[Spike Feeder]]
