### ISSUE TITLE
Dauthi Voidwalker doesn't grab milled cards

### ISSUE THREAD

**Issue by Iraklis21** [magefree/mage#8561]
One of the newer cards in Dauthi Voidwalker exiles every card that gets put into an opponents graveyard from anywhere. Since mill is "putting cards from top of targets library into targets graveyard" they should not get put into these graveyards and instead get exiled with a void counter on it.
I hope this can be fixed (and I hope that this is the correct way to report a bug - had to search for like half an hour to find a "form" for bug reports)

**Comment by jeffwadsworth** [comment]
[[Dauthi Voidwalker]]

**Comment by jeffwadsworth** [comment]
Worked fine for me.
