### ISSUE TITLE
can't proliferate counters on players

### ISSUE THREAD

**Issue by kons7** [magefree/mage#8565]
proliferating counters on players doesn't seem to work. i can't even target them (f.e. poison counters or experience counters)

**Comment by Grath** [comment]
If you click on the player, it will show you having selected an additional thing to proliferate on. The UI isn't great, but you absolutely can proliferate on players.

**Comment by kons7** [comment]
thanks, 10 other people i know had the same problem and thought it was a bug. i will inform everyone how it works.
