### ISSUE TITLE
progressbar at "Downloading images" window

### ISSUE THREAD

**Issue by PinPhreek** [magefree/mage#8566]
Hello,

could you please add a progress bar to the "Downloading images" window. It would be nice to have a clear visiual indication of the pregress. The bar could be fittingly implemented at the " x of y image download finished! Please wait! [z Mb]", whitch already looks like a progressbar.

Thank you,
Pin Phreek

**Comment by peter-thoenen** [comment]
TBH I would just like it when 100% to say "complete" ... I always feel it's stuck at 100%.

**Comment by JayDi85** [comment]
Images progress bar added by ca993eae397591bc44e54775aac446f67d4f542a. 

Example:
![shot_230319_215008](https://user-images.githubusercontent.com/8344157/226196904-a2321f8f-9cd2-47e5-b2c4-e05a082b6a06.png)
