### ISSUE TITLE
Chalice on Zero not stopping cascade casting

### ISSUE THREAD

**Issue by peter-thoenen** [magefree/mage#8579]
Noticed this awhile ago but just cost me a game again so figured would look up the guru text and report if bug (and it is).  Chalice of the Void on zero (0) isn't stopping the cascade effect even though it's cast for no mana (i.e. zero / free).

**Comment by awjackson** [comment]
[[Chalice of the Void]] cares about the mana value of spells, not the amount of mana spent to cast them. Chalice on 0 will counter spells that actually have a mana value of 0 (e.g. [[Ancestral Vision]]) but it won't counter any spell just because you cast it for free.

**Comment by peter-thoenen** [comment]
Guru text says otherwise, it's why on MTGO etc challice stops cascade

**Comment by emerald000** [comment]
Chalice on 0 will counter a cascading [[Crashing Footfalls]] since its mana value is 0. It will not counter a cascading [[Lightning Bolt]] since its mana value is 1.

**Comment by peter-thoenen** [comment]
Ah my bad .. yeah I'm literally thinking crashing footfalls lol.  My bad.
