### ISSUE TITLE
Theater of Horrors ignoring life lost

### ISSUE THREAD

**Issue by sumsarz** [magefree/mage#8585]
I was unable to cast a card exiled with [[Theater of Horrors]] after a player was hit with the life loss from [[Marionette Master]].

As soon as I had attacked and dealt 1 damage through combat I was able to cast it, however.

The source of lifeloss shouldn't matter.

**Comment by Alex-Vasile** [comment]
I was not able to reproduce.
1. Marionette Master and Theatre of Horror are on my battlefield before upkeep.
2. On upkeep Theatre exiles a card
3. I tap sack black lotus
4. Hit opponent for 1 damage with Marionette
5. I can cask the card exiled by Theatre

init.txt for testMode:
```
[init]
battlefield:Human:Swamp:6
battlefield:Human:Theater of Horrors:1
battlefield:Human:Marionette Master:1
battlefield:Human:Black Lotus:1
library:Human:Marionette Master:2
```
