### ISSUE TITLE
Reduce Boilerplate?

### ISSUE THREAD

**Issue by Alex-Vasile** [magefree/mage#8590]
Java isn't my main language so this may be naive, but it seems like there is an incredible amount of boiler-plate code that needs to be added in terms of the copy constructors.

Every card, effect, ability, and possibly a few others has these lines:
```Java
private X(final X x) {
	super(x);
}

public X copy() {
	return new X(this);
}
```

Most of the implementations do not make any further changes to these two functions, only a small fraction do.

Can these two be implemented into a super class so that there is a default behaviour which 99% of the implementations can use.

**Comment by theelk801** [comment]
I've looked into this kind of thing before and I think it might be more trouble than it's worth, unfortunately. Java's kind of weird with this stuff.

**Comment by JayDi85** [comment]
It's a copy constructors and some classes with inner data must add special code to it (one of the popular bug -- missing copy code, so some inner states will be lost between game cycles). Also it must return original class, not parent on the copy (another popular bug -- missed overrided copy method that leads to a missing copy constructor).

**Comment by JayDi85** [comment]
BTW IntelliJ IDEA can recognize a copy constructors and show a hints about missed fields.
