### ISSUE TITLE
Dermotaxi does not become a copy of the imprinted card following activation

### ISSUE THREAD

**Issue by Walrighti** [magefree/mage#8591]
I have followed all the correct steps with Dermotaxi - exiling a creature in a graveyard upon its etb, and then activating Dermotaxi by tapping two creatures, and it stays a 0/0.

I'm trying to make a spicy Dermotaxi deck where it'll turn into Griselbrand or Klauth, Unrivalled Ancient. Please help me make this a reality!

**Comment by jeffwadsworth** [comment]
[[Dermotaxi]]
