### ISSUE TITLE
Void Mirror is broken: it can counter spell that cannot be countered

### ISSUE THREAD

**Issue by Reya87** [magefree/mage#8604]
Hello.

I had a game with Void Mirror + Possibility Storm on the battlefield. I casted a creature spell. Possibility Storm exiled that spell and it was replaced by Vexing Shusher. Void Mirror triggered because no colored mana was spent to cast Vexing Shusher and the spell was countered.

But Vexing Shusher is a spell that cannot be countered. Void Mirror was able to dodge that! 

If you can fix this please. Thank you.

**Comment by jeffwadsworth** [comment]
[[Void Mirror]] [[Possibility Storm]] [[Vexing Shusher]]
