### ISSUE TITLE
Been a long time since the last release

### ISSUE THREAD

**Issue by Alex-Vasile** [magefree/mage#8610]
What tasks need to be done in order to get the next release out, and what can I do to help with those?

**Comment by jeffwadsworth** [comment]
I can tell you that a report of this kind is pretty useless.  The release happens when it happens.  It has always been like that.

**Comment by JayDi85** [comment]
Soon

**Comment by Alex-Vasile** [comment]
I hope it didn't come across the wrong way. I was only asking to see if there was something to help with.
