### ISSUE TITLE
Sasaya, Orochi Ascendant - AI creates endless loop revealing hand

### ISSUE THREAD

**Issue by rystan** [magefree/mage#8611]
[[Sasaya, Orochi Ascendant]] on the battlefield causes the AI to continuous activate the "reveal hand" ability, regardless of whether it has enough cards in hand to satisfy the flip requirements, every chance it has priority and results in an endless loop of revealing hands without ever passing priority and thus forcing the human opponents to concede the game.

**Comment by jeffwadsworth** [comment]
[[Sasaya, Orochi Ascendant]]
