### ISSUE TITLE
Glimpse the Cosmos exiles if you cast it from hand for U, doesn't exile if you cast it from graveyard for 1U

### ISSUE THREAD

**Issue by awjackson** [magefree/mage#8624]
If you have something like a [[Sapphire Medallion]] that allows you to cast [[Glimpse the Cosmos]] from your hand for U rather than 1U, Glimpse will go into exile after you cast it from your hand.

Conversely, if something like [[Thalia, Guardian of Thraben]] makes [[Glimpse the Cosmos]] cost 1U to cast from the graveyard, it will *not* go into exile when cast from the graveyard using its second ability.

The reason is that `GlimpseTheCosmosReplacementEffect` determines whether or not to exile the card based on *the cost paid*, rather than whether the ability allowing it to be cast from the graveyard was used.

I don't think that cards like Glimpse the Cosmos and [[Worldheart Phoenix]] that have an alternative cost and an effect that applies "if you cast it this way" can be correctly implemented using `AsThoughEffect` and `setCastSourceIdWithAlternateMana` (contrary to @JayDi85  https://github.com/magefree/mage/issues/8144), because I can't find any reliable way to verify whether the spell was in fact "cast this way".

**Comment by jeffwadsworth** [comment]
The code for Glimpse the Cosmos checks the from zone as being the stack, and not the graveyard.  I will check it out.

**Comment by awjackson** [comment]
(copypasted and lightly edited from Discord)
XMage currently has (at least) *three* completely different, completely nonoverlapping subsystems for applying alternative costs to spells.

One of them entails subclassing SpellAbility. This method is currently only used by keyworded mechanics and not by any individual cards (Glimpse the Cosmos formerly used this method but @JayDi85 demanded it be changed in https://github.com/magefree/mage/issues/8144)

A second method is used by Glimpse the Cosmos and Worldheart Phoenix (among other cards). It supports combining with AsThough to allow cards to be cast from zones they couldn't normally be cast from, but does not (as far as I can tell) provide any way to check after the fact whether the spell was cast for that alternate cost. It also looks hacky and unsafe to me: if the alternative cost is anything other than "free" then it is applied by overwriting the `SpellAbility`'s `manaCosts` (a field that other parts of xmage assume to be immutable!)

A third method is used by all the pitch spells like Force of Will, by the Dash, Prowl and Evoke keywords, and by the cycle of Masteries from STX. This method *does* provide a way to check whether the alternate cost was paid (which the named mechanics and the STX Masteries need) but it does not provide any way to allow the spell to be cast from an alternate zone.

**Comment by JayDi85** [comment]
Ability fully copied and reset on each game cycle. All cost reduction and adjusters applies to the ability from the scratch every time (and and be called from many places: from pay to playable analyse code and AI).

**Comment by awjackson** [comment]
The copy constructor of `AbilityImpl` doeesn't copy `manaCosts`, only `manaCostsToPay`. See https://github.com/magefree/mage/issues/6671. When an `Ability` gets copied, the original's `manaCosts` and the copy's `manaCosts` become references to the same `ManaCosts<ManaCost>` object.

![Screenshot_20220131_135401](https://user-images.githubusercontent.com/9252545/151855091-7c9ae8ce-7ff6-4752-b931-f107b8636ad2.png)

**Comment by JayDi85** [comment]
I saw that. It can be a bug (missing copy). Or some optimization (long ago mana cost objects were very annoying and eats all memory on the server — but not today). Must be research and fixed (if it doesn't brake any tests).

**Comment by JayDi85** [comment]
BTW xmage doesn't have immutable objects by design. Well, you can find something, but it just a code. Real reason: xmage uses game states to rollback while casting/paying, forced by users or by AI game simulations. Game state — all game data in the time. Its independent game states. So no shared changeable objects. Its important.

**Comment by awjackson** [comment]
So how do you recommend fixing Glimpse and Worldheart? The currently used method of checking the mana cost to determine whether the spell was cast "this way" is not reliable. IMO `SpellAbility` subclass is the only way to correctly implement these two cards without deep changes to game engine.

**Comment by JayDi85** [comment]
I didn’t look at the bug and at the code. So cant tell the details. There are possible to find a real SpellAbility object for casted spell/card — many cards uses it. I’ll look later to it if no fixes.

**Comment by awjackson** [comment]
Getting the `SpellAbility` object is not the problem. The problem is that the `SpellAbility` object doesn't contain any information that can be used to determine whether a specific `asThough` effect was used to cast the spell.

**Comment by awjackson** [comment]
> I saw that. It can be a bug (missing copy). Or some optimization (long ago mana cost objects were very annoying and eats all memory on the server — but not today). Must be research and fixed (if it doesn't brake any tests).

Adding the deep copy doesn't cause any tests to fail so I just did it. Let me know if there's a significant impact on memory usage.

**Comment by jeffwadsworth** [comment]
I am going to test an approvingObject solution to this.
