### ISSUE TITLE
Rogue Class doesn't let you play cards

### ISSUE THREAD

**Issue by Jipsu** [magefree/mage#8630]
Opponent had level 3 [[rogue class]] but was not able to play lands or cast spells that were exiled. The cards were exiled before rogue class leveled to third level.

**Comment by alexander-novo** [comment]
I can confirm this is broken

![image](https://user-images.githubusercontent.com/11657716/171252463-1e10a2c6-3d70-47eb-a6ed-30025136b2fa.png)

In the above picture, I have exiled my opponent's [[Dark Ritual]], have a level 3 [[Rogue Class]], and have enough mana to cast it, however clicking on "No, play/activate ability" causes nothing to happen. As well, the rest of the cards exiled are all swamps, and I cannot play them either.

**Comment by DreamWaker** [comment]
still broken... and it hurts!

**Comment by jeffwadsworth** [comment]
The cast from exile should be an effect on the card itself.  When the exile zone is check for "paying any mana", the card is already in the stack and out of the exile zone, so the check fails.
Also, the unique id for the exile zone must remain consistent for all checks.  Using the source ability will not work.
