### ISSUE TITLE
Speed Up Deck Editor

### ISSUE THREAD

**Issue by Alex-Vasile** [magefree/mage#8641]
By default, open the deck editor window loads ALL of the implemented cards. This usually takes several seconds.

I don't think that this default behaviour (seeing all 20,000 cards) is what most people want.

Some alternatives:
- show nothing, and have a show all button that shows all cards
- show the newest set

**Comment by JayDi85** [comment]
Its java classes loading. Can be at any moment (on startup, on deck editor open, etc). Cards db works very fast.

**Comment by Alex-Vasile** [comment]
I suspect it's the loading off all of the sets and cards. Can those be pushed off the main thread so that the UI does not freeze?

**Comment by JayDi85** [comment]
Nope, it can't be. Card classes needs for additional data and filtering (e.g. it needs on first access to the sets list). I tried to optimize deck loading in old days and that's all.
