### ISSUE TITLE
Willbreaker removed before the ability triggers bug

### ISSUE THREAD

**Issue by kotomaxibon** [magefree/mage#8642]
Expected behavior: When Willbreaker is removed with his ability still on the stack, nothing happens. 
(As per gatherer: If you lose control of Willbreaker before its ability resolves, you won’t gain control of the creature at all.)

Current behavior: Willbreaker's controller gains permanent control of the targeted creature.

**Comment by jeffwadsworth** [comment]
[[Willbreaker]]
