### ISSUE TITLE
Dack Fayden + Kaldra Complete, unable to -2 / steal when equiped

### ISSUE THREAD

**Issue by peter-thoenen** [magefree/mage#8649]
Dack Fayden using the -2 ability is unable to steal Kaldra Complete when equipment to the germ token.

**Comment by theelk801** [comment]
were you able to target it with the ability? it’s possible that you gained control of it but it stayed in place as it was still attached to the germ you didn’t control

**Comment by peter-thoenen** [comment]
Ah didn't think of that, I assume it would unattach.  Replays aren't saved and not sure how to test that single player.  I'm betting you are correct though.

**Comment by theelk801** [comment]
yeah, equipment stays attached when control changes, I’m gonna close this as that’s probably what happened
