### ISSUE TITLE
Really bad graphics bug

### ISSUE THREAD

**Issue by Witherx2** [magefree/mage#8656]
![image_2022-02-05_211424](https://user-images.githubusercontent.com/55571186/152666359-ed84289d-f75a-4907-aa56-5b1b5a22a66e.png)
This keeps happening and it doesnt go away until i restart the app. it proliferates whenever my mouse moves over a clickable, and seems to just choose a section of the screen some set distance from the cursor and tries to render that instead.

**Comment by JayDi85** [comment]
If no errors in the logs then it's an d3d bug with video drivers. Follow [that instructions](https://github.com/magefree/mage/issues/4626#issuecomment-374640070) to fix.
