### ISSUE TITLE
Gemstone mine not working in newest beta build

### ISSUE THREAD

**Issue by amartyads** [magefree/mage#8662]
Tapping [[Gemstone Mines]] gives color selector popup, but after selecting a color the land untaps and goes back to 3 counters.

Trying to tap the land to pay for a cast spell does not allow the land to be tapped.

**Comment by amartyads** [comment]
[[Gemstone Mine]]

**Comment by awjackson** [comment]
Altar of the Pantheon is also affected, but *not* Chromatic Sphere or Vivid Marsh. Seems to be limited to mana abilities with an additional effect that uses the `ConditionalOneShotEffect` decorator.

**Comment by theelk801** [comment]
looks like this is because of ba05bc1, I can look into it
