### ISSUE TITLE
Search for the back of a dual faced card in the deck editor returns nothing

### ISSUE THREAD

**Issue by Alex-Vasile** [magefree/mage#8664]
Say I'm looking for [[Brutal Cathar // Moonrage Brute]]. I can't search for moorage brute, I need to remember that Brutal Cathar is on the front side and look for Brutal Cathar instead.

**Comment by jeffwadsworth** [comment]
https://github.com/magefree/mage/pull/8618

**Comment by Alex-Vasile** [comment]
> #8618

I'm not sure how what I did there will help. That fixed assumed that the text import had the entire card name (FRONT NAME // BACK NAME). Here, I don't know the name of the front of the card.

**Comment by Alex-Vasile** [comment]
Nevermind, I understand what you meant: importing should also work if only the back of the card is listed in the text file.
