### ISSUE TITLE
Hello. Is there any chance you can fix this ? Today I casted Animate Dead, targeting Mulldrifter in my graveyard, with Yarok the desecrated on the battlefield. At the end, I drew 8 cards. This is way too advantegeous for Yarok player !

### ISSUE THREAD

**Issue by Reya87** [magefree/mage#8670]
Hello. Is there any chance you can fix this ? Today I casted Animate Dead, targeting Mulldrifter in my graveyard, with Yarok the desecrated on the battlefield. At the end, I drew 8 cards. This is way too advantegeous for Yarok player !

_Originally posted by @Reya87 in https://github.com/magefree/mage/issues/8253#issuecomment-1031912220_

**Comment by Alex-Vasile** [comment]
[[Animate Dead]], [[Mulldrifter]], [[Yarok, the Desecrated]]

**Comment by weirddan455** [comment]
I've got a fix.  About to push it.

**Comment by Reya87** [comment]
Great! I had no clue if my last topic was still "under investigation" ^^
