### ISSUE TITLE
Cards Foretold by Ethereal Valkyrie when copied by Twinflame cannot be cast

### ISSUE THREAD

**Issue by dashosa** [magefree/mage#8673]
![image](https://user-images.githubusercontent.com/63882410/153057505-5723d503-9830-449b-8b32-05db077e3e2d.png)

**Comment by jeffwadsworth** [comment]
[[Ethereal Valkyrie]] [[Twinflame]]

**Comment by jeffwadsworth** [comment]
How are you using Ethereal Valkyrie to exile "tokens" from your hand?

**Comment by dashosa** [comment]
Ah sorry, the ethereal valkyrie is a token created by twinflame
