### ISSUE TITLE
Phyrexian Metamorph stops being an artifact when it copies a creature

### ISSUE THREAD

**Issue by Jipsu** [magefree/mage#8679]
[[Phyrexian Metamorph]] cannot be targeted by "destroy target artifact" effects if it ETBs copying a creature. (If it copies an artifact it is correctly just an artifact.)

**Comment by pcasaretto** [comment]
I believe the Metamorph *is still an artifact* as the card text explicitly states. Therefore it **can** be targeted by "destroy artifact" effects.
https://www.mtgsalvation.com/forums/magic-fundamentals/magic-rulings/magic-rulings-archives/267588-destroy-target-artifact-creature

**Comment by stevedavidmusic** [comment]
Can confirm that this is bugged. I copied a Llanowar Elf and Phyrexian Metamorph did not turn itself into an artifact. Could not target it with artifact destruction. 

<img width="1280" alt="Screen Shot 2022-02-16 at 10 03 44 AM" src="https://user-images.githubusercontent.com/45299811/154307382-bf41e030-7557-4480-9e3f-c37aff1fdd8d.png">

**Comment by pcasaretto** [comment]
Oops, my bad. Misunderstood the bug report.
