### ISSUE TITLE
Knowledge pool using wrong player?

### ISSUE THREAD

**Issue by Alex-Vasile** [magefree/mage#8688]
Looking at Knowledge pool, it appears that the code uses Knowledge pool's controller to move the cast card to exile, rather than the controller of the spell.

This looks like a mistake to me. Is it?

https://github.com/magefree/mage/blob/d35e1fbfb19da4b24bf97e9e58221a0983f73966/Mage.Sets/src/mage/cards/k/KnowledgePool.java#L150

**Comment by jeffwadsworth** [comment]
[[Knowledge Pool]]

**Comment by jeffwadsworth** [comment]
Incredible that this wasn't noticed before.  It is a pretty important distinction.  Card was done ages ago.
