### ISSUE TITLE
Consistent crash when opening deck editor in Mac OS

### ISSUE THREAD

**Issue by pcasaretto** [magefree/mage#8696]
XMage Launcher version installed:  0.3.8
XMage Launcher version available:  0.3.8
Java version installed:  1.8.0_201
Java version available:  1.8.0_201
XMage version installed:  1.4.50V2 (2021-09-05)
XMage version available:  1.4.50V2 (2021-09-05)
Mac OS 12.0.1 (21A559)

The client crashes as soon as the deck editor opens up.

[Mac Os Crash Report](https://gist.github.com/pcasaretto/936f522480f93d586a4bdcdd6eb6bacf)
[Java error report](https://gist.github.com/pcasaretto/d36c466a7c7c1c4eef07c9c3897a0f91)

**Comment by Alex-Vasile** [comment]
See the comments in #8406.

Similar error, solution was to install a newer version of Java into the XMage directory.

**Comment by pcasaretto** [comment]
Closing as duplicate
