### ISSUE TITLE
Go-Shintai shrines error

### ISSUE THREAD

**Issue by catman123456** [magefree/mage#8701]
Go-Shintai of Lost Wisdom only mills me

![image](https://user-images.githubusercontent.com/64045003/153870133-a67e2917-86c9-4363-8618-48476fafd8c1.png)

**Comment by theelk801** [comment]
were you able to choose a target after you paid the 1?

**Comment by catman123456** [comment]
Yep but the effect  only effected me

**Comment by weirddan455** [comment]
Target pointer is getting over-written here:

https://github.com/magefree/mage/blob/4b4174b00ec5c51ded020f4ef79944d40c6d919a/Mage/src/main/java/mage/abilities/common/BeginningOfEndStepTriggeredAbility.java#L44-L52

**Comment by Tharkon** [comment]
Go-Shintai of Boundless Vigor also does not seem to do anything, could also be that it tries to put the +1/+1 counter on the controller, and I guess Hidden Cruelty tried to destroy its controller.
