### ISSUE TITLE
March of Otherworldly Light gets returned to hand when cast

### ISSUE THREAD

**Issue by cashmoneyhoes** [magefree/mage#8702]
![Screenshot (75)](https://user-images.githubusercontent.com/90292347/153969234-9bfc2aab-bc3c-4239-84c8-75101cbcd3d7.png)
I'm targeting [[Klothys, God of Destiny]] with [[March of Otherworldly Light]] with X set to 3, and I have 4 mana floating, but when I try to cast the spell, it automatically gets returned to my hand when I try to pay the full cost.

**Comment by theelk801** [comment]
Did it ask you to pay the mana before it asked you to exile the cards? If so then it should be fixed already.

**Comment by cashmoneyhoes** [comment]
> Did it ask you to pay the mana before it asked you to exile the cards? If so then it should be fixed already.

Yes. This just happened a couple of minutes ago.

**Comment by theelk801** [comment]
ok, then this should be fixed by cff38b74b9 next time beta restarts
