### ISSUE TITLE
Kotori, Pilot Prodigy bug

### ISSUE THREAD

**Issue by catman123456** [magefree/mage#8713]
the crew 2 abilty isn't working

![image](https://user-images.githubusercontent.com/64045003/154628210-b6282f3c-14c8-4433-9260-25b4307bfd25.png)

**Comment by theelk801** [comment]
what do you mean by "isn't working"?

**Comment by catman123456** [comment]
> what do you mean by "isn't working"?

When i use Kotori ability the vehicle stays uncrewed

**Comment by theelk801** [comment]
so you were able to activate the crew ability, it just didn't do anything when it resolved?

**Comment by jeffwadsworth** [comment]
You have to love layers.  The land type-changing issue from long ago was different in that a land intrinsically has the ability to produce mana of its color.  Thus we applied the “layer 6” at layer 4.  Weird, but necessary.
