### ISSUE TITLE
GUI bug: Client window being duplicated within window

### ISSUE THREAD

**Issue by Gahnik** [magefree/mage#8716]
Downloaded the client today and been having this recurring visual bug. It doesn't always happen, but seems to happen after some time. The entire window gets duplicated onto seemingly random spots. The duplications will disappear and reappear when moving the mouse around interactable buttons or sections, and sometimes clears completely. The issue doesn't go away until I close the client and reopen it again. Happens during games as well as on the table screen.

![XMage bug 1](https://user-images.githubusercontent.com/39975019/154826785-633110f5-e90e-4d11-afef-e5079e6341f1.png)
![XMage bug 2](https://user-images.githubusercontent.com/39975019/154826786-7dd513c2-d74f-4c49-ae0b-826ae113a64e.jpg)
![XMage bug 3](https://user-images.githubusercontent.com/39975019/154826787-312d0f74-c073-4a0d-a36b-69ba8a9ba1e0.jpg)

**Comment by JayDi85** [comment]
Try use [that fix](https://github.com/magefree/mage/issues/4626#issuecomment-374640070)
