### ISSUE TITLE
Clones of Icefall Regent do not keep creatures tapped

### ISSUE THREAD

**Issue by Greeneye0** [magefree/mage#872]
Steps to duplicate
1. Put out Icefall Regent, select target opponent creature to tap
2. Clone Icefall Regent with Fated Infatuation. Select a different opponent creature to tap

This doesn't seem to happen 100% of the time. For me it has been 2 out of 3.

Note that the creature you tapped with the clone untaps at the start of the next turn.

**Comment by Greeneye0** [comment]
I can duplicate the same issue using a frost lynx and mirror mockery. The copy comes on to the battlefield and it does tap the target creature, but the creature does not stay tapped during the next untap phase.

**Comment by LevelX2** [comment]
Couldn't reproduce the problem with the current version in development.
Please reopen if you still have the problem with version beyond v8.
