### ISSUE TITLE
Can spells on the stack targeting other spells indicate the spell being targeted?

### ISSUE THREAD

**Issue by jumpinjackie** [magefree/mage#8721]
Consider this example stack:

![2022-02-23 18_50_18-Window](https://user-images.githubusercontent.com/563860/155279481-c40c2376-f5b4-4427-b71b-976d0bd276b9.png)

Without looking at the game log, you wouldn't know that Force of Will is targeting the Pyroblast, which itself is targeting the Spirit of the Labyrinth. Some UI hints would help navigating stacks like this (especially in large counter wars):

 * Perhaps when hovering over a spell targeting another it renders an arrow pointing to the spell being targeted. Probably impractical for large stacks or when playing a [[Flusterstorm]] with a big enough storm count.
 * Or in its tooltip showing the card text, it also displays the name of the spell it is targeting

**Comment by jeffwadsworth** [comment]
How about something like the picture?
![targetOnStack](https://user-images.githubusercontent.com/1496996/156463159-1095d45e-fb27-470e-a0b3-7535d1a360a7.jpg)

**Comment by jumpinjackie** [comment]
@jeffwadsworth  That's perfect!

**Comment by jeffwadsworth** [comment]
Great.  I just have to test it with everything that targets stack objects to make sure it nothing breaks.
