### ISSUE TITLE
Go-Shintai of Ancient Wars hits caster when oppenent is selected for effect.

### ISSUE THREAD

**Issue by Exhora58** [magefree/mage#8723]
When using Go-shintai of Ancient Wars ability, the card hits the caster instead of the target.

**Comment by theelk801** [comment]
I think this may be a duplicate of #8701, not sure when the beta server was last updated

**Comment by awjackson** [comment]
This was fixed by https://github.com/magefree/mage/commit/957eca8d87bf67c0a4dec719005a9fcb3714eb8b
