### ISSUE TITLE
Go-Shintai of Hidden Cruelty does not destroy its target.

### ISSUE THREAD

**Issue by Tharkon** [magefree/mage#8727]
Even when paying {1} at the end of turn nothing is being destroyed.
Scanned the code my guess would be that the filter is looking for a permanent with the name  "creature with toughness less than or equal to the number of Shrines you control".
Of course, no such card exists.
But I might be reading the code wrong, nor would I know how to fix it.
Finale of Eternity is probably a good card to steal code from.

**Comment by theelk801** [comment]
this is related to #8723 and #8701, it’s likely that it will be fixed with the next beta update

**Comment by awjackson** [comment]
This was fixed by https://github.com/magefree/mage/commit/957eca8d87bf67c0a4dec719005a9fcb3714eb8b
