### ISSUE TITLE
All Hallow's Eve is unusable

### ISSUE THREAD

**Issue by jd2345** [magefree/mage#8728]
Although you can cast All Hallow's Eve and (upon resolution) it does go directly to exile it doesn't remove a scream counter during your next upkeep.  Instead, it moves from exile to your graveyard automatically without removing any counters, rendering the card unusable because all the creatures are stuck in their graveyards instead of being brought back onto the battlefield.

**Comment by Alex-Vasile** [comment]
This is getting fixed in #8699
