### ISSUE TITLE
Sengir, the Dark Baron is nearly fully broken...

### ISSUE THREAD

**Issue by DreamWaker** [magefree/mage#8730]
The adding counters part works fine, but the secondary effect half works, but does so incorrectly...

`Whenever another player loses the game, you gain life equal to that player's life total as the turn began.`

If a player dies, the turn it was summoned... It does nothing...
Otherwise, it seems to add the life total the player was at when they died (not what they started the turn with)

Both happened in the same game (Local AI, just playing around)
![Broken Sengir 1](https://user-images.githubusercontent.com/22373484/155936009-eed9be51-0374-43d3-9b44-c21ce6f6becb.jpg)
![Broken Sengir 2](https://user-images.githubusercontent.com/22373484/155936011-92f07c36-c2bf-43e8-9d9b-49a571715f7f.jpg)

**Comment by jeffwadsworth** [comment]
[[Sengir, the Dark Baron]]

**Comment by jeffwadsworth** [comment]
Worked fine in my testing.  In the examples, the player had 2 life at the beginning of the turn it lost the game.
![sengirExample](https://user-images.githubusercontent.com/1496996/156031049-a8125bba-16f5-4597-9ec9-71f73597056c.jpg)
![SengirExampleLifeGained2](https://user-images.githubusercontent.com/1496996/156031060-642f80ae-c5c7-4285-a884-6e596cf37836.jpg)

**Comment by jeffwadsworth** [comment]
I am testing the turned it was summoned as well.

**Comment by Alex-Vasile** [comment]
Might be an AI issue since the game log shows that the AI had it under their control
