### ISSUE TITLE
Vastwood Hydra targeting text bug

### ISSUE THREAD

**Issue by jeffwadsworth** [magefree/mage#8739]
[[Vastwood Hydra]]

Picture says it all.
![Vastwood Hydra GUI issue](https://user-images.githubusercontent.com/1496996/156655075-b311ec98-245f-4eb9-a053-b373a13a9dfb.jpg)

**Comment by jeffwadsworth** [comment]
I would assume any card that uses the distributed targets method will have the issue.

**Comment by awjackson** [comment]
Duplicate of #8069
