### ISSUE TITLE
Many ones!

### ISSUE THREAD

**Issue by Arakorn** [magefree/mage#874]
1st: heard that xmage will be only for premium members (aka_ guys with money) this is true?
2nd: lately the game is so slow, whys is that?
3th: in some computers images doesnt download total, why?

tnx

**Comment by LevelX2** [comment]
> 1st: heard that xmage will be only for premium members (aka_ guys with money) this is true?

no, but at least funny


> 2nd: lately the game is so slow, whys is that?

The hoster of the server has changed something in his infrastructure. Use xmage.de from the server list, it's much faster.


> 3th: in some computers images doesnt download total, why?

Wrong language (other than english) or firewall/router problems I guess.
