### ISSUE TITLE
Modernise configuration processing used in `Mage.Server`

### ISSUE THREAD

**Issue by cognivore** [magefree/mage#8749]
# Why?

As a part of effort to be compatible with JDK11+, we need to make sure everything, including `Mage.Server`, builds with `mvn package`.
Currently, due to [JAXB deprecation](https://docs.oracle.com/javase/9/docs/api/java.xml.bind-summary.html), it is impossible to generate `Config` class from `ConfigFactory`.
It should be noted, that I have tried to use every drop-in JAXB replacement out there, including `jaxb-api` + `jaxb-impl` dependencies and Spring's implementation, and all of those attempts failed.

# What?

 - [x] Provide `Config` class with an API similar to the existing one (see `ConfigFactoryTest`)

# How

## Strategy A

Admittedly, the lowest hanging fruit is to start by manually making a module which would follow current config's XML specification, perhaps even by slightly retouching the generated `./target/generated-sources/xjc/mage/server/util/config/Config.java`. 
A *huge* drawback of this approach, is that it destroys the single source of truth, which is the XML schema, creating maintenance strain whenever config schema is changed. That said, I don't see it as an event that happens all too often, this is why I think it's a possible angle of attack.

~- [ ] Add a manually crafted or machine-generated Config.java to the codebase~
~- [ ] Update tests to refer to Config class directly, rather than ConfigFactory~
~- [ ] Comment out code of ConfigFactory, referring to this issue~

## Strategy B

The proper way to solve this issue is to not search for a drop-in replacement for JAXB, but rather incorporate a modern approach for dynamic class generation based on XML specifications. I'm yet to learn how it's done in Java 11+, but I've already asked an expert Java developer to have a look and, perhaps, he'll provide some pointers.

~- [ ] Find out how JAXB-like functionality is implemented in modern Java~
~- [ ] Rewrite ConfigFactory to use that modern approach~
~- [ ] Adjust Config API (over which we won't have control in Strategy B) throughout the codebase, including `ConfigFactoryTest`~

## Strategy C

Perhaps, my lack of experience with `mvn`/`pom.xml` is the source of me failing to make a JAXB drop-in replacement work. If so:

 - [x] Find a JAXB drop-in replacement
 - [x] Add it to the dependencies
 - [x] Make sure it works 
     - [x] at build step,
     - [x] test step, 
     - [x] runtime

**Comment by cognivore** [comment]
Relevant files: 

 - https://github.com/magefree/mage/blob/master/Mage.Server/src/main/java/mage/server/util/ConfigFactory.java
 - https://github.com/magefree/mage/tree/master/Mage.Server/src/main/xml-resources/jaxb/Config

Perhaps, @fburato can help here big time!

**Comment by fburato** [comment]
@cognivore: To address directly the problem, the drop-in replacement is relatively easy to apply directly on the existing project. The dependencies to add to `Mage.Server` are the following:

```xml
        <dependency>
            <groupId>javax.xml.bind</groupId>
            <artifactId>jaxb-api</artifactId>
            <version>2.3.1</version>
        </dependency>
        <dependency>
            <groupId>com.sun.xml.bind</groupId>
            <artifactId>jaxb-impl</artifactId>
            <version>2.3.1</version>
        </dependency>
        <dependency>
            <groupId>org.glassfish.jaxb</groupId>
            <artifactId>jaxb-core</artifactId>
            <version>3.0.2</version>
        </dependency>
```

If you update the source and target Java version to 11 and ensure that you are running with JDK 11 on your path, then:

```bash
mvn clean package -pl Mage.Server
```

will work just fine.

However if I may just provide my two cents on the matter, XML has gone out of fashion, and it's not really pursued any longer as configuration format by the wider Java community (and I'm being farily generous with this characterisation). The most used format for configuration nowadays is YAML.

Automatically generating code from the XSD schema could arguably make sense for a very complex domain, but here we are talking about 102 lines of schema, which given the XML verbosity is miniscule, and the schema doesn't really change that often, which means that there is not really a risk of introducing mistakes making XSD validation very valuable. In addition to that, XSDs are useful if they are shared with other services as contract specification, but in this case there is no transport of the domain entities and there's no third party interested in knowing them, which makes using XSD even more unpalatable.

IMO, it would be simpler to just define the POJO representing the configuration directly as maintained source and drop the generation from XSD entirely.

**Comment by weirddan455** [comment]
I tried adding those dependencies to the pom.xml.  It built fine but then it throws this exception at runtime:

```
INFO  2022-03-09 17:10:39,942 Reading configuration from path=config/config.xml                                          =>[main] Main.main 
Exception in thread "main" mage.server.util.ConfigurationException: javax.xml.bind.JAXBException: Implementation of JAXB-API has not been found on module path or classpath.
 - with linked exception:
[java.lang.ClassNotFoundException: com.sun.xml.internal.bind.v2.ContextFactory]
	at mage.server.util.ConfigFactory.loadFromFile(ConfigFactory.java:17)
	at mage.server.Main.main(Main.java:104)
Caused by: javax.xml.bind.JAXBException: Implementation of JAXB-API has not been found on module path or classpath.
 - with linked exception:
[java.lang.ClassNotFoundException: com.sun.xml.internal.bind.v2.ContextFactory]
	at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:177)
	at javax.xml.bind.ContextFinder.find(ContextFinder.java:364)
	at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:508)
	at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:465)
	at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:366)
	at mage.server.util.ConfigFactory.loadFromFile(ConfigFactory.java:13)
	... 1 more
Caused by: java.lang.ClassNotFoundException: com.sun.xml.internal.bind.v2.ContextFactory
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at javax.xml.bind.ServiceLoaderUtil.nullSafeLoadClass(ServiceLoaderUtil.java:122)
	at javax.xml.bind.ServiceLoaderUtil.safeLoadClass(ServiceLoaderUtil.java:155)
	at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:174)
	... 6 more

Process finished with exit code 1
```

**Comment by fburato** [comment]
@weirddan455: it's hard to determine why that's happening given I don't know exactly how you are running the application. However, based on the fact that the build was failing when the dependency were not specified and succeeded when the dependency were introduced and the fact that the exception thrown is identical (`ClassNotFoundException` on `ContextFactory`), the best guess I can make is that whatever you are running doesn't include the JARs of the dependencies in the class-path.

Under the assumption that you are running the built application, you need to download the JARs from the maven repository (or from your local maven cache, since you are building locally), place them in the library directory, and ensure that those JARs are properly loaded.

**Comment by cognivore** [comment]
@fburato is there a way for maven to do that stuff itself? Something like `mvn get-dependencies`? I personally was trying to do `mvn package` with all the possible sets of JAXB replacements, sadly, to no avail. I was getting similar errors to @weirddan455. Also notice that it *does* have javax.xml.bind, which exports class `JAXBContext`, which even has a `newInstance` function. My interpretation is that the drop-in replacement is less drop-in than we thought. But I hope that I'm wrong and it's indeed a UX bug in `mvn`.

Interestingly, I found sources online that share this sentiment. Either way, I'm going to try to do Strategy B today.

**Comment by cognivore** [comment]
@fburato wow, drop-in seems to work when used together with VSCode Java extension! I have no idea why, but I'll keep investigating.

**Comment by fburato** [comment]
@cognivore: it's probably because VSCode is wiring in the classpath when you launch the client from the IDE. That's what I meant in my comment to @weirddan455 with "I don't know exactly how you are running the application", and more generally when the application is packaged it is important to ensure that the `lib` folder that is added in the client contains all the necessary dependencies. I'm not familiar enough with the release process of Mage to know how that works, but I assume there is going to be another change to make to include the new dependencies.

More generally, however, I was suggesting to add the JARs in the classpath manually just to confirm that the application would run that way. Figuring out how to automate the addition comes after we have validated that the hypothesis is correct :)

**Comment by cognivore** [comment]
Yeah, I'm going to do just that right now. The plan is to find the extension and then read its code to understand how it sets the classpath, replicate it manually, then automate in a temporary script, which shall later on be deprecated in favour of a nix expression. Thank you for chiming in, your help is absolutely instrumental! 🙇

**Comment by cognivore** [comment]
https://github.com/cognivore/mage/tree/issues/8749 works with JDK11, going to test now.

**Comment by fburato** [comment]
@cognivore: I've tried it out as well and I managed to get a running version that incorporate everything (JavaFX and JAXB). [fburato/mage#38](https://github.com/fburato/mage/pull/38) builds with the simplest possible invocation (`mvn clean install`), has all tests passing, and runs with the client and the server starting without issue and managing to connect to one another.

**Comment by cognivore** [comment]
[This tree](https://github.com/cognivore/mage/tree/issues/8749) builds and is deployed with OpenJDK11 over at play.memorici.de. I'll maintain an openjdk11 tree over in my fork.
https://doma.2038.io/software/mage-bundle.zip -- build
https://doma.2038.io/software/mage-bundle.zip.sha256 -- hash

Also, https://github.com/fburato/mage/pull/38/files supposedly builds with OpenJDK11 and doesn't deprecate JavaFX (even though I didn't test it in runtime).

Thank you everyone, who made OpenJDK11 builds possible!
