### ISSUE TITLE
Drafting NEO only shows one card, always a saga

### ISSUE THREAD

**Issue by grandogarndo** [magefree/mage#8753]
https://drive.google.com/file/d/1RxsdjmAUVSp1QN_N-_TDTejK3_vuUn56/view?usp=sharing
Its weird, because it seems the whole set is in the deck editor. Feel free to delete this issue if someone else has brought it up,I didn't see it though.

**Comment by awjackson** [comment]
Fixed by https://github.com/magefree/mage/commit/ae481f09a68a4288ca6b0c7593f554be5f970d0c
