### ISSUE TITLE
The most effective and reproducible way to build the project with Maven

### ISSUE THREAD

**Issue by cognivore** [magefree/mage#8756]
# Why?

`mvn` is non-hermetic and currently the best way I know to build the project is:

```
mvn clean && mvn package || mvn package || mvn package
```

It seems to progressively generate more and more code for peers to "see" more and more code during subsequent compilation attempts. Surely other developers build the project in a different way. It would be amazing to learn how.

# How?

 - [ ] The community shares their know-how about using maven

----

# Old issue

## Why?

`mvn package` builds don't seem to be hermetic and while most of the errors I worked around by running `mvn package` over and over again, the "fix point" seems to currently be the following:

```
[INFO] Running org.mage.test.cards.flipcoin.FlipCoinTest
FATAL 2022-03-11 15:16:28,008 Error loading card: mage.cards.e.EHondaSumoChampion (SLD)                                  =>[main] CardImpl.createCard 
java.lang.Error: Unresolved compilation problem: 
        CardsInTargetPlayerHandCount cannot be resolved to a variable
```

and

```
[ERROR] org.mage.test.cards.single.m11.InfernoTitanTest.test_MustAbleToTargetPlaneswalkers  Time elapsed: 0.001 s  <<< ERROR!
java.lang.Error: 
Unresolved compilation problem: 
        Config2 cannot be resolved to a variable
```

There are a lot of test failures, basically if something refers to Config2, it fails.

## How?

~- [ ] Those who were able to build the project with `mvn` should share their recipes of doing so, especially ensuring that card tests run, since I got just the last two build items to build!~
~- [ ] The know-how from the community should then be adopted in the automated, reproducible build process, per devops methodology.~

**Comment by cognivore** [comment]
A clarification: my current strategy of building is literally `mvn clean && mvn package || mvn package || mvn package`. Third invocation gets to the "fix point" of failing with not being able to resolve `Config2` and `CardsInTargetPlayerHand`. A way to tell mvn a dependency graph and how to respect generated classes is appreciated, but isn't crucial for solving this.

**Comment by cognivore** [comment]
*Ridiculously*, this error can't be reproduced on a fresh clone of https://github.com/cognivore/mage/tree/issues/8749

**Comment by awjackson** [comment]
xmage consists of several subpackages which are tightly interlinked with each other--e.g. `Mage.Client` and `Mage.Server` both depend on the rules engine in `Mage`, the card and set classes in `Mage.Sets`, and whatever the hell is in `Mage.Common`. The supported way to build the project is all at once via `mvn install` in the project root directory--building the client or server packages individually doesn't make sense.

**Comment by cognivore** [comment]
@awjackson thank you! I'll read about `mvn install`. I find it perplexing that `mvn package` doesn't `mvn install` first.

**Comment by cognivore** [comment]
To bundle dependencies into `lib`: 

```
mvn install dependency:copy-dependencies 
```

**Comment by cognivore** [comment]
Turns out there's also `cd Utils && perl ./build-and-package.pl`

**Comment by JayDi85** [comment]
Don't clean every time.

Full build: `mvn clean install -DskipTest`
Fast build: `mvn install -DskipTest`

Use fast build in your IDE's pre-step for run/debug, so you will run actual version every time and it works very fast (maven compile and build only changes files).

**Comment by JayDi85** [comment]
Wiki page has detailed instructions how-to build and run project by different IDEs and tools:
* https://github.com/magefree/mage/wiki/Setting-up-your-Development-Environment
