### ISSUE TITLE
Devout Invocation's hint text is wrong when cast be non-owner

### ISSUE THREAD

**Issue by Alex-Vasile** [magefree/mage#8759]
I swing with at an opponent with [[Etali, Primal Storm]] and exile a [[Devout Invocation]].

The card has hints on it indicating the number of untapped creatures "you" control. However, in this cast "you" should be me and not Devout's owner. Also, "untapped" is in lowercase instead of capitalized.

Unrelated, to Devout but maybe similar issue, I had an [[Inspiring Statuary]] on the board, and it also adds hint text to Devout Invocation. That hint text is also wrong. It's also counting the number of artifacts that Devout's owner has on the board, and not the number that I do.

**Comment by Alex-Vasile** [comment]
Looking into this one some more, not sure how to deal with it. Etali exiles the cards, but they remain under the control of the opponent.

**Comment by JayDi85** [comment]
Not a bug, hint uses card's controller. So all calcs will be for controller. Not for a current viewer/player.
