### ISSUE TITLE
Swift Reconfiguration Bug

### ISSUE THREAD

**Issue by jasonywang0** [magefree/mage#8764]
Game Log Exerpt:
8:45 PM, T25.M1: Urza casts Swift Reconfiguration [8e8] targeting Scavenging Ooze [ca5]
8:45 PM, T25.M1: Urza puts Swift Reconfiguration [8e8] from stack onto the Battlefield
8:45 PM, T25.M1: Auto-restored to T25.M1 due game error: Wrong code usage. Don't use that method for permanents, use permanent.addAbility(a, source, game) instead.
[game error.txt](https://github.com/magefree/mage/files/8238977/game.error.txt)

**Comment by Alex-Vasile** [comment]
[[Swift Reconfiguration]]
