### ISSUE TITLE
My card images not showing up

### ISSUE THREAD

**Issue by SecurityKoala** [magefree/mage#877]
When creating a deck or playing a game the images for the cards in my deck do not show up, instead they are blueish transparent.  My opponents cards show up fine and all card images appear when I search for a card when creating a deck.  I am on Ubuntu if that helps.

**Comment by LevelX2** [comment]
What was the reason?

**Comment by SecurityKoala** [comment]
I'm not sure, I just deleted the images folder and re-downloaded all of the card images and it started working.

**Comment by LevelX2** [comment]
ok, thanks for the info.
