### ISSUE TITLE
Night Soil bug

### ISSUE THREAD

**Issue by jeffwadsworth** [magefree/mage#8771]
The AI can pay the exile card cost using more than a single graveyard.

**Comment by jeffwadsworth** [comment]
[[Night Soil]]

**Comment by DeepCrimson** [comment]
Is this issue still reproducible? Once I target a card in one graveyard to pay Night Soil's cost, I'm unable to target cards in other graveyards to complete paying the cost.

**Comment by Alex-Vasile** [comment]
> Is this issue still reproducible? Once I target a card in one graveyard to pay Night Soil's cost, I'm unable to target cards in other graveyards to complete paying the cost.

Have to test with the AI. Sometimes it's able to do things that a human player cannot due to a difference in implementation.
