### ISSUE TITLE
Zangief (Maarika, Brutal Gladiator) trigger doesn't cause opponent to sacrifice anything

### ISSUE THREAD

**Issue by Grath** [magefree/mage#8775]
Trigger:
![image](https://user-images.githubusercontent.com/1895280/158692820-95296858-06c4-4271-9f81-4c70724873fa.png)
After resolution:
![image](https://user-images.githubusercontent.com/1895280/158692905-610bacc7-0dba-480c-81ac-98777d907467.png)
This happened repeatedly with my other opponent as well.

**Comment by theelk801** [comment]
so the ability triggered, went on the stack, and resolved, but the opponent was never prompted to sacrifice anything?

**Comment by Grath** [comment]
Yes, just confirmed with two clients, opponent's never prompted to sacrifice when the ability resolves.

**Comment by Grath** [comment]
Extra weird: I just had Zangief fight Zangief (simplest repro steps were both players using that deck) and [the player that initiated the fight was prompted to sacrifice a noncreature, but the other player was not.](https://www.youtube.com/watch?v=AL6kKWPWuD8) May be related to the creature dying and LKI?

**Comment by Grath** [comment]
Confirmed, if both Zangiefs are indestructible then both players are asked to sacrifice a permanent.

**Comment by theelk801** [comment]
this seems related to #8555 then

**Comment by Grath** [comment]
Can you check this with your fix for #9129? I suspect that firing damage triggers before SBAs are checked may have fixed this issue.

**Comment by awjackson** [comment]
I just checked and there is no change at all. That commit affected *batch* damage events. Individual damage events are never queued up, they are directly fired via `Game.fireEvent`.

**Comment by awjackson** [comment]
I think there are (at least) two separate bugs here. The screenshot appears to show Zangief dealing damage during the main phase, presumably via a fight spell (what is visible of the log pane shows "M1"). In that situation, Zangief's ability triggers but doesn't do anything on resolving. When Zangief deals excess *combat* damage, however, his ability doesn't trigger at all.

**Comment by Alex-Vasile** [comment]
Was this also fixed by https://github.com/magefree/mage/commit/665e47634dd9a813f207171ceb82bbb3696e6a7f?

**Comment by xenohedron** [comment]
[[Maarika, Brutal Gladiator]]

Reported again in discord today

**Comment by JayDi85** [comment]
Possible reason: if you need permanent's info only (not real permanent) then `getTargetPointer().getFirst` can be replaced by `getTargetPointer().getFirstTargetPermanentOrLKI`. Maarika needs only controller info, so it must use LKI

![shot_240622_224017](https://github.com/magefree/mage/assets/8344157/32408401-39b6-4257-80f7-3f463e05f5af)
![shot_240622_224301](https://github.com/magefree/mage/assets/8344157/d276bcc7-0780-4069-a858-16d112afbe36)
