### ISSUE TITLE
Opponent tried to cycle Sojourners of Bant, game auto-rollbacked, got the following. Cycling attempted after rollback but same effect.

### ISSUE THREAD

**Issue by radiasian** [magefree/mage#8778]
Game exception occurred: java.lang.ClassCastException: mage.game.events.GameEvent cannot be cast to mage.game.events.ZoneChangeEvent
Server version: 1.4.51-V3-beta6 (build: 2022-03-12 06:43)
mage.abilities.common.CycleOrDiesTriggeredAbility.checkTrigger(CycleOrDiesTriggeredAbility.java:34)
mage.abilities.TriggeredAbilities.checkTrigger(TriggeredAbilities.java:94)
mage.abilities.TriggeredAbilities.checkTriggers(TriggeredAbilities.java:55)
mage.game.GameState.handleEvent(GameState.java:805)
mage.game.GameImpl.fireEvent(GameImpl.java:3105)
mage.players.PlayerImpl.playAbility(PlayerImpl.java:1370)
mage.players.PlayerImpl.activateAbility(PlayerImpl.java:1495)
mage.player.human.HumanPlayer.activateAbility(HumanPlayer.java:2081)
mage.player.human.HumanPlayer.activateAbility(HumanPlayer.java:2104)
mage.player.human.HumanPlayer.priority(HumanPlayer.java:1191)
mage.game.GameImpl.playPriority(GameImpl.java:1534)
mage.game.turn.Step.priority(Step.java:61)
mage.game.turn.Phase.playStep(Phase.java:184)
mage.game.turn.EndPhase.playStep(EndPhase.java:47)
mage.game.turn.Phase.play(Phase.java:89)
mage.game.turn.Turn.play(Turn.java:132)
mage.game.GameImpl.playTurn(GameImpl.java:1059)
mage.game.GameImpl.play(GameImpl.java:969)
mage.game.GameImpl.start(GameImpl.java:945)
mage.server.game.GameWorker.call(GameWorker.java:34)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)

**Comment by jeffwadsworth** [comment]
https://github.com/magefree/mage/commit/4967750669f1d6198974c1ad0a95900d3effd30c

**Comment by theelk801** [comment]
yeah this was just fixed with 4967750
