### ISSUE TITLE
Bear Umbra bug

### ISSUE THREAD

**Issue by JoeyVers** [magefree/mage#8782]
Hi all,

The ability of [[Bear Umbra]] that says: "Enchanted creature gets +2/+2 and has "Whenever this creature attacks, untap all lands you control." isn't in Xmage. Is there a reason for that or is it a bug?

![image](https://user-images.githubusercontent.com/14837339/159306564-357f1df1-838c-4845-8a43-14608e7f183c.png)

Gr,
Joey

**Comment by awjackson** [comment]
Fixed in 4863eb3170d288b145f1087ab9de49c5442c6f12
