### ISSUE TITLE
Unable to connect to local server when buildilng release locally

### ISSUE THREAD

**Issue by thebear132** [magefree/mage#8784]
So when running the XMageLauncher.jar (official release from xmage.de) client and server, i am perfectly able to connect to the local server with no modifications to the settings.

But when building the release myself, i am getting "Unable connect to server. Server is not responding"
I am building the release myself using the perl script /Utils/building-and-package-console.pl, and its compiling fine with no errors
Logs:
[mageserver.log](https://github.com/magefree/mage/files/8329070/mageserver.log)
[mageclient.log](https://github.com/magefree/mage/files/8329068/mageclient.log) //I attempted connection twice
Note: It seems the server never logs any connection attempts?

So far i have tried this (changing my JAVA_HOME variable from jdk1.8.0_321 to jdk1.8.0_202
https://github.com/magefree/mage/issues/8470#issuecomment-980830855

I have tried different ports with no results

Is it my firewall?

**Comment by jeffwadsworth** [comment]
Make sure your client is set to connect to "localhost".  The ip address you are using is incorrect.

**Comment by jeffwadsworth** [comment]
Yeah, in that case, it may be getting firewalled from the server.  Try turning off your local firewall and see if you can connect.  Simple test first.

**Comment by thebear132** [comment]
Turning the firewall off in the control panel at Control Panel/System and security/Windows defender firewall. I turned everything off.
The errors persist "Unable connect to server".
[mageclient.log](https://github.com/magefree/mage/files/8334146/mageclient.log)
The log while firewall turned completely off

**Comment by jeffwadsworth** [comment]
In that case, I have no idea what the issue can be.  If JayDi shows up, perhaps he can help you troubleshoot the issue.

**Comment by Alex-Vasile** [comment]
If you boot it up with IntelliJ, does it work there?

**Comment by thebear132** [comment]
> Also, if you're building it locally, apply the patch from #8627 and see if that fixes things.

Just applied the patch manually by replacing
`assertThat(query).contains("serializationtype=jboss");`
with
`assertThat(query).contains("serializationtype=java");`
In ConnectionTest.java.
After running
`perl build-and-package-console.pl` with a succesfull build, its still the same issue, whether firewall is on or off

> If you boot it up with IntelliJ, does it work there?

I dont know why that should matter but i can try. I am following this guide
https://github.com/magefree/mage/wiki/Setting-up-your-Development-Environment#intellij-idea
I am following along until i get stuck at this part
>Navigate to Run -> Edit Configurations... and create the following by first clicking the green + in the top right corner and entering create the run configurations describe below as needed.

I can find the Add Configurations, but no description is provided of what to do?

**Comment by Alex-Vasile** [comment]
> Just applied the patch manually by replacing
> `assertThat(query).contains("serializationtype=jboss");` with`assertThat(query).contains("serializationtype=java");` In ConnectionTest.java.

Did you also make the changes needed to Connection.java? The changes to Connection.java are the important ones, ConnectionTest is only a unit test file.


> I dont know why that should matter but i can try. I am following this guide
https://github.com/magefree/mage/wiki/Setting-up-your-Development-Environment#intellij-idea
I am following along until i get stuck at this part
>> Navigate to Run -> Edit Configurations... and create the following by first clicking the green + in the top right corner and entering create the run configurations describe below as needed.
> I can find the Add Configurations, but no description is provided of what to do?


See [further down](https://github.com/magefree/mage/wiki/Setting-up-your-Development-Environment#running-server-and-client).

**Comment by thebear132** [comment]
> Did you also make the changes needed to Connection.java? The changes to Connection.java are the important ones, ConnectionTest is only a unit test file.

I missed that i am sorry. I am building again with Connection.java also updated from jboss to java.

> See [further down](https://github.com/magefree/mage/wiki/Setting-up-your-Development-Environment#running-server-and-client).

I have no idea man. The order in which the text is written is really confusing. I will look into it more once i check the new build.

**Comment by thebear132** [comment]
> > Did you also make the changes needed to Connection.java? The changes to Connection.java are the important ones, ConnectionTest is only a unit test file.
> 
> I missed that i am sorry. I am building again with Connection.java also updated from jboss to java.
> 
> > See [further down](https://github.com/magefree/mage/wiki/Setting-up-your-Development-Environment#running-server-and-client).
> 
> I have no idea man. The order in which the text is written is really confusing. I will look into it more once i check the new build.

Running the mageserver.bat now gives
`
Exception in thread "main" java.lang.NoClassDefFoundError: mage/cards/c/CitystalkerConnoisseur
        at mage.sets.AlchemyInnistrad.<init>(AlchemyInnistrad.java:24)
        at mage.sets.AlchemyInnistrad.<clinit>(AlchemyInnistrad.java:12)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Unknown Source)
        at mage.util.ClassScanner.checkClassForInclusion(ClassScanner.java:18)
        at mage.util.ClassScanner.findClassesInJar(ClassScanner.java:92)
        at mage.util.ClassScanner.findClasses(ClassScanner.java:57)
        at mage.cards.Sets.<init>(Sets.java:34)
        at mage.cards.Sets.<clinit>(Sets.java:23)
        at mage.cards.repository.CardScanner.scan(CardScanner.java:34)
        at mage.cards.repository.CardScanner.scan(CardScanner.java:20)
        at mage.server.Main.main(Main.java:158)
Caused by: java.lang.ClassNotFoundException: mage.cards.c.CitystalkerConnoisseur
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 12 more
`
...
I will be back in 30 minutes again and look at this.

**Comment by thebear132** [comment]
Okay i deleted my .m2 folder and attempted another build, this time success! It seems this was the solution.
>Also, if you're building it locally, apply the patch from https://github.com/magefree/mage/pull/8627 and see if that fixes things.
