### ISSUE TITLE
Missing card requests: Captain's Maneuver and Emblazoned Golem

### ISSUE THREAD

**Issue by NibiruMTG** [magefree/mage#8788]
[[Captain's Maneuver]] and [[Emblazoned Golem]], both from Apocalypse, are still unimplemented.

I'm creating these remastered sets for old blocks over at the XMage Draft Historical Society and Invasion block is up next. Both of these are kind of important for the set - not having Captain's Maneuver would affect the color balance in the set quite severely and Emblazoned Golem is an important defensive card for the multicolor/domain decks that also doubles as a finisher.

So yeah, these would be nice to have, and thanks to everyone who wants to try to implement them!

**Comment by hidde-vb** [comment]
I'll try and implement Emblazoned Golem later this evening.

**Comment by xenohedron** [comment]
Resolved by #10186
