### ISSUE TITLE
Sphere of Safety needs a hint for opponents

### ISSUE THREAD

**Issue by Alex-Vasile** [magefree/mage#8789]
Currently, [[Sphere of Safety]] does not have any hint text to let opponents know how much they have to pay to attack, it could really benefit from it.

![Sphere of Safety](https://user-images.githubusercontent.com/48962821/160257593-970714cb-9fd7-4bc3-b7a2-451c3b8b5e8d.png)

**Comment by theelk801** [comment]
I don’t think there’s currently a way to have hints be visible to players other than the controller

**Comment by Alex-Vasile** [comment]
Unless I'm misremembering, I believe commanders show how much damage they've dealt to each player, and that you can see this even on opponent commanders.

**Comment by theelk801** [comment]
hmmm, is that done using the hints system or is it specific to commanders?

**Comment by Alex-Vasile** [comment]
[[Maze's End]] has hint for opponents.
