### ISSUE TITLE
Don't reveal canceled spells to the opponent

### ISSUE THREAD

**Issue by duelcastermage** [magefree/mage#8790]
Can we make it so if a player starts to cast a spell, but changes their mind, the spell is not revealed to all opponents?

This is a huge information leak and can directly lead to losses. Sometime you accidentally click on a card and cancel in less than a second, but your opponent still sees the card.

And this is especially bad with morphs that you were going to play face down (if you cancel them on the stack, the opponent gets to see the actual card).

**Comment by radiasian** [comment]
I would like to second this

**Comment by sumsarz** [comment]
Would be a great QoL change, but I'm not sure how easy it would be to implement considering how the stack area works as of now.

**Comment by JayDi85** [comment]
Is it actual? Can opponents see a real morph card before cast, after cast or after cancel (in stack, in game logs, etc)?

Current GUI logic hide face down card from opponent until game end. Only controller can see a real name.

**Comment by ssk97** [comment]
I'm fairly certain it is no longer true as of my changes to Morph. Previously, as an alternate cost, trying to cancel the morph would first reveal the card's normal form before you could cancel that as well. Now that casting a Morph is a fully separate SpellAbility, that is no longer the case.

**Comment by ssk97** [comment]
Note that the main issue in the original request is for _all_ spells to not be revealed after the first click.

I don't think that idea is supported by the rules, however. The first step of casting a spell is moving it to the stack, where it's visible. Cancelling payment rolls back the game, but the card is still shown as per the rules.

**Comment by JayDi85** [comment]
Stack is public zone, so you can’t hide info in it. Current logic is good (put to stack then paying).
