### ISSUE TITLE
No response to Emrakul shuffle trigger

### ISSUE THREAD

**Issue by Vuuyi** [magefree/mage#8795]
Since a couple of days there is no time to respond to the trigger Emrakul has when it goes to the graveyard. The same happened with Nexus of Fate. This one might be different than Emrakul's trigger because of the wording. 

Could this be fixed?

**Comment by awjackson** [comment]
I can't reproduce this with Emrakul. I tested discarding the card with [[Merchant of the Vale]] and milling it with [[Thought Scour]] and in both cases the shuffle ability went onto the stack and could be responded to.

Nexus of Fate's shuffle-into-library clause is a replacement effect, not a triggered ability. Please note the difference between "*when* {this} *is* put into a graveyard from anywhere" and "*if" {this} *would be* put into a graveyard from anywhere". Replacement effects don't go on the stack and can't be responded to.
