### ISSUE TITLE
Didn't gain life when Luminate Primordial exiled

### ISSUE THREAD

**Issue by sumsarz** [magefree/mage#8798]
I've seen this happen 2-3 times, though I'm unsure if it's a 100% occurence or some weird 'just happens sometimes' thing. Perhaps in each case there's been a singular creature exiled only.

[[Luminate Primordial]] is supposed to give a player life equal to the exiled creature's power, but life didn't change.

**Comment by theelk801** [comment]
I just pushed some code that may fix it but I'm not sure, if it's only sometimes then it's hard to confirm whether it happened.
