### ISSUE TITLE
For proliferate you can't select opponent creatures with shroud or hexproof

### ISSUE THREAD

**Issue by Diegogrt93** [magefree/mage#880]
A few issues I've encountered during playing XMage:
- ~~My opponent casted Phyrexian Metamorph to copy my Olivia Voldaren. He used her ability to rob my own Olivia, so the legendary rule would make him sacrifice his Olivia/Metamorph. The ability resolved, but my Olivia remained with me.~~
- I casted Contagion Engine with the opponent having a shrouded creature (it was equipping Greaves). The creature got a -1/-1 counter. I used the 4-and-tap to proliferate twice, but the shroud-protected creature got no extra counters, and my planeswalker got only one additional loyalty counter, which means proliferate only happened once, and his creature wasn't affected, when it should.
- ~~My opponent had a creature enchanted with Angelic Destiny. I casted Soul Tithe targeting the Destiny, and after it resolved his creature vanished, leaving only the Destiny with Soul Tithe above it.~~

**Comment by LevelX2** [comment]
Fixed the the problem with Contagion Engine.
(Better create an separate issue for each bug next time).

**Comment by LevelX2** [comment]
Close this because fixed.
