### ISSUE TITLE
[DOM] Aryel, Knight of Windgrace's second ability can't be activated for X=0

### ISSUE THREAD

**Issue by awjackson** [magefree/mage#8808]
If there is a legal target (a creature with power 0) on the battlefield you can start to activate the ability and get as far as paying the mana cost of {B}, but Ayrel and the land you tapped to pay the mana cost remain untapped (or the floating mana you spent is returned to your mana pool) and the ability fails to go onto the stack.

**Comment by Alex-Vasile** [comment]
[[Aryel, Knight of Windgrace]]
