### ISSUE TITLE
Siphon Insight doesn't allow you to play lands from opponent's library

### ISSUE THREAD

**Issue by awjackson** [magefree/mage#8809]
Siphon Insight reads "you may *play* the exiled card" rather than "you may *cast*". It's different from Gonti (from which the ability implementation appears to have been copypasted) The Gatherer notes for the two cards confirm that Siphon does allow you to play lands exiled from the opponent's library whereas Gonti doesn't.

**Comment by jeffwadsworth** [comment]
[[Siphon Insight]]

**Comment by Alex-Vasile** [comment]
Closed by 5369d4bd9fced1a2409a0329692faf81e1877775
