### ISSUE TITLE
Warbringer dash cost reduction bugged

### ISSUE THREAD

**Issue by Jipsu** [magefree/mage#8815]
[[Warbringer]] doesn't let you cast a dashed creature with discount if you don't have mana for the full dash cost. When XMage asks if you want to dash the cost is displayed without discount. When you move to pay the dash cost you correctly pay the discounted price.

#6698 displays this bug as fixed.

**Comment by awjackson** [comment]
This was supposedly fixed by d18093daf24123ecd61d6af4398b6971b8b19566, but wasn't (I checked that it wasn't a subsequent regression)

Fixed by c58eeef77d3b9f6d9f6491f10ef486cc94c85313 for real this time (complete with a new test)
