### ISSUE TITLE
Cavern of Souls making creatures uncounterable when using "Add {1} to your mana pool."

### ISSUE THREAD

**Issue by Badaro** [magefree/mage#882]
Using version 1.3.0dev2015-03-14v5.

* Have a Cavern of Souls in play, naming "Construct"
* Cast a Wurmcoil (Artifact Creature - Wurm) using the "Add {1} to your mana pool." ability of the Cavern
* Opponent attempts to counter it, counterspell fizzles due to the Cavern's ability

**Comment by Badaro** [comment]
Gamelog: http://pastebin.com/gTHK3Ljj

**Comment by LevelX2** [comment]
Duplicate of #798

**Comment by Badaro** [comment]
Suspected it was a duplicate, but thought it would be better to let you confirm that. Hope the game log helps fixing it.
