### ISSUE TITLE
Vigilant creatures able to attack multiple planeswalkers at once

### ISSUE THREAD

**Issue by PurpleCrowbar** [magefree/mage#8825]
Image shows [[Linden, the Steadfast Queen]] attacking three planeswalkers _and_ an opponent directly. 

![image](https://user-images.githubusercontent.com/26198472/162576747-6bb9172f-34d1-4100-914b-e48648da0e1f.png)

For some reason selecting a planeswalker to attack does not count as the creature's sole "target". Issue likely only present with creatures with vigilance as they don't tap when selecting a target.

Next image is from chat, where it counts each individual attack of Linden to be from a separate creature (5 creatures = 4 Linden attacks and 1 expected attack from Sunscorch Regent):

![image](https://user-images.githubusercontent.com/26198472/162577012-a40df3a8-b872-45ea-8b74-9b7f4abaade1.png)

**Comment by Alex-Vasile** [comment]
This happen if you select the player first, or does it have to be planeswalkers first?

**Comment by PurpleCrowbar** [comment]
I can't seem to reproduce on the updated version that released today, so either it was fixed **or** it's specific to Linden **or** it's a bot-exclusive bug. I'm erring on the side of "bot-exclusive bug"

**Comment by Alex-Vasile** [comment]
Okay. So happened on beta6 (2022-03-12) but not beta7 (2022-04-09).

Do you remember the order that the attacks were declared in?

**Comment by PurpleCrowbar** [comment]
As this was done by a bot it happened instantly, no order of choices. May have something to do with the way bots choose targets to attack but I don't know how the bots work.

**Comment by awjackson** [comment]
This is a known issue with AI players: https://github.com/magefree/mage/issues/7434 Unless you can reproduce it as a human player, this issue should be closed as a duplicate.

**Comment by PurpleCrowbar** [comment]
I see, alright then I'll close it.

**Comment by jeffwadsworth** [comment]
I wonder if Commander is the gametype here?
