### ISSUE TITLE
Beta server error

### ISSUE THREAD

**Issue by ahart98** [magefree/mage#8827]
Whenever I try to start a match in the beta server I get an error that a card in my deck isn't found, shown in the picture. If I replace the card it gives me the error again with the next card alphabetically. Do I need to redo my entire deck or is there another solution?
![Capture](https://user-images.githubusercontent.com/95040653/162624554-dde339a9-2aa9-4eb5-861b-5380ab6b37a7.PNG)

**Comment by JayDi85** [comment]
Beta restarted
