### ISSUE TITLE
Bugged interaction between Skullbriar and Promise of Loyalty

### ISSUE THREAD

**Issue by PurpleCrowbar** [magefree/mage#8829]
[[Promise of Loyalty]] places vow counters on creatures and states that those creatures can't attack PoL's caster "for as long as it has a vow counter on it". But when [[Skullbriar, the Walking Grave]] has a vow counter put on him, its effect is negated when he goes back to the command zone and is re-played, meaning he can attack PoL's caster despite having a vow counter still on him.

Image attached shows Skullbriar with a vow counter attacking the caster of PoL.

![image](https://user-images.githubusercontent.com/26198472/162632304-7e143a4a-179d-4e1c-94a4-6cd63c1b8508.png)

**Comment by emerald000** [comment]
The effect is only applied to the targets of the spell and the counters are mostly aesthetic. By leaving and coming back, it's not the same Skullbriar and the effect does not apply.
