### ISSUE TITLE
Auto loss

### ISSUE THREAD

**Issue by catman123456** [magefree/mage#8833]
the CPU does nothing and i lose

Game exception occurred: mage.MageException: Iterated player priority after game exception too often, game ends! Last error:
 null
Server version: 1.4.51-V3-beta7 (build: 2022-04-09 16:42)
mage.game.GameImpl.playPriority(GameImpl.java:1592)
mage.game.turn.Step.priority(Step.java:61)
mage.game.turn.Phase.playStep(Phase.java:184)
mage.game.turn.Phase.play(Phase.java:89)
mage.game.turn.Turn.play(Turn.java:132)
mage.game.GameImpl.playTurn(GameImpl.java:1064)
mage.game.GameImpl.play(GameImpl.java:974)
mage.game.GameImpl.start(GameImpl.java:950)
mage.server.game.GameWorker.call(GameWorker.java:34)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)

![image](https://user-images.githubusercontent.com/64045003/162720496-c34ea69c-1a07-4fe7-861e-49b142e97e15.png)

**Comment by jeffwadsworth** [comment]
[[Hinata, Dawn-Crowned]]

**Comment by catman123456** [comment]
> Where does the Hinata, Dawn-Crowned fit into this? The picture you posted is from a game start.

After testing it for a bit. it does that with every game

**Comment by catman123456** [comment]
When I rolled back to my turn it gives me a lost 

![image](https://user-images.githubusercontent.com/64045003/163303281-09abb084-b3bf-481c-94fc-325d5ec6f24e.png)

**Comment by catman123456** [comment]
I tried to roll back and the game froze. I imput the fix command this happen.
![image](https://user-images.githubusercontent.com/64045003/164374993-d684bab3-760b-4dc4-892a-419ecbbfa41a.png)

**Comment by catman123456** [comment]
I fixed the issue
