### ISSUE TITLE
Thought-Knott Seer auto-skipping through trigger

### ISSUE THREAD

**Issue by Clipper70** [magefree/mage#8840]
Was playing a game on the beta server and TKS allows me to select an opponent to exile a card from their hand, but after selection it auto skips through my ability to select a card and i'm guessing assumes i'm selecting done without picking a card. This has not occurred in previous xmage versions so is it possible something changed with the new update relating to rules change/new Capenna mechanics?  thanks greatly.

**Comment by awjackson** [comment]
The issue is specifically that when the opponent has no nonland cards in their hand, their hand is not revealed at all. It looks like this regressed with 83c94322c6d030c2375975019153a4c7f3b9ddf4 .
