### ISSUE TITLE
Suggestion: Allow basic lands to be sideboarded in a private 1v1 Limited match

### ISSUE THREAD

**Issue by duelcastermage** [magefree/mage#8843]
It would be great/true to paper to have the option to sideboard any number of basic lands in a side match of Limited (deck type: Limited; game type: Two Player Duel).

If we do a draft and people are forced to play side matches with their draft deck, they are screwed if they want to add basic lands after sideboarding and they haven't modified their deck by adding them in the Deck Editor first.

**Comment by xenohedron** [comment]
I believe this was fixed in #9152
