### ISSUE TITLE
Hidden Dragonslayer Mega Morph is the only option for turning face up.

### ISSUE THREAD

**Issue by wallenfox** [magefree/mage#885]
Noticed with Hidden Dragonslayer but not with deathmist raptor, there is only an option to turn it face up for it's mega morph cost.  This was observed when it was manifested with mastery of the unseen or whisperwood elemental.  I did not have a chance to test with just a straight morph on this card.

**Comment by LevelX2** [comment]
This is fixed beyond v5.
