### ISSUE TITLE
Scry, Pick order of activated abilities, and probably other similar windows do not consistently show up

### ISSUE THREAD

**Issue by Alex-Vasile** [magefree/mage#8851]
I have had this happen somewhat inconsistently with [[Trelasarra, Moon Dancer]].

On a Mac with a touchpad using the newest beta (2022-04-09).

Steps to recreate:
- Two (2) abilities activate at the same time for gaining a life
- I try right clicking Trelasarra to say always put on stack first
- The right click menu shows up, but Trelasarra is also put on the stack first (and therefore the other ability is also put on the stack)
- I then click the always put on stack first for this ability.
- I continue playing

At some point, the ability will trigger again (either in that game, or another game). Then, one of two things happen:
- I will not remember that I said put on stack first, and it will ask me to order them, and the window shows up for me to pick the order
- It will not remember, and the window to pick the order DOES NOT show up, effectively locking me out of the game. I have to force quit the game since nothing else will let me continue playing.

I am not yet sure under which circumstances the second behaviour happens.

P.S. How do I tell it to forget the default that I told it? (Other than deleting the XMage folder and re-installing.

**Comment by Alex-Vasile** [comment]
Playing around with this more, it seems to be something with the choose order of things on stack in general. It's not being shown properly sometimes.

Rolling back to the start of turn and doing the same actions does not seem to trigger it

**Comment by Alex-Vasile** [comment]
Sometimes when this happens you are also unable to right click to anywhere on the board to bring up the menu in order to roll back. The window has to be resized several times and even made fullscreen before the ability comes back.

Rolling back to the start of the current turn _sometimes_ fixes the issue, but other times it has to be performed multiple times.

**Comment by Alex-Vasile** [comment]
It looks like the window initially appears in the top-left corner of the screen and is then supposed to be moved to the centre. I think that this movement is not always occurring properly.

**Comment by JayDi85** [comment]
fixed by #11189
