### ISSUE TITLE
Chandra Torch Of Defiance first +1 ability does not reset prompt on next activation

### ISSUE THREAD

**Issue by jumpinjackie** [magefree/mage#8858]
Play [[Chandra, Torch of Defiance]]

Activate her first +1 loyalty ability. Choose not to cast the exiled card.

Activate her first +1 loyalty ability on a future turn. It remembers the initial "no" choice and immediately exiles the card without prompting for whether you'd like to cast this exiled card or not

Expect: On future turn activations of that ability, I get the choice of whether to cast the exiled card or not.

**Comment by jeffwadsworth** [comment]
Works fine for me.

**Comment by theelk801** [comment]
were the exiled cards castable?

**Comment by jumpinjackie** [comment]
I'll try to see if the problem is reproducible

**Comment by jumpinjackie** [comment]
I think I found my source of confusion. I had been exiling **lands** with Chandra's ability, which are not castable, hence no prompt for casting it. Don't think UX beyond "read the F'n card!" can reduce that confusion. So yeah, things are working as designed.
