### ISSUE TITLE
Mairsil, The Pretender sometimes does not exile the chosen card

### ISSUE THREAD

**Issue by alexander-novo** [magefree/mage#8862]
[[Mairsil, The Pretender]]. I'm playing a game right now and I've exiled two cards from my hand, but I cannot exile a card from my graveyard.

**Comment by jeffwadsworth** [comment]
Another issue with it and I am sure others like it:  The other players must have the opportunity to respond after the card is targeted.  Right now, the target card (hand or graveyard) goes into the exile zone immediately...no chance to respond with something like [[Grim Harvest]] which would render the target illegal.

**Comment by theelk801** [comment]
You can’t respond to exiling because the choice happens during resolution of the ability. As for why it didn’t let you choose from your grave, did you choose no and it still didn’t let you pick a card?

**Comment by jeffwadsworth** [comment]
I misread the card and a rule that was assigned to it about "targets" and it thew me off.
