### ISSUE TITLE
Remote task error. Java heap space

### ISSUE THREAD

**Issue by calkno** [magefree/mage#8863]
When using the Beta client and attempting to connect to the beta.xmage.today, I receive this error. I can function locally, edit decks, etc. but only on attempted connect it throws this error. I didn't have this issue yesterday and have made no updates.

OS: MacOs Monterey

<img width="649" alt="Screen Shot 2022-04-20 at 2 26 27 AM" src="https://user-images.githubusercontent.com/36138660/164164418-e908bf59-9f39-40a3-85b5-a16394bedcfa.png">
<img width="727" alt="Screen Shot 2022-04-20 at 2 25 57 AM" src="https://user-images.githubusercontent.com/36138660/164164427-1f661d14-027d-4686-9373-73bfcd8bcdfe.png">
.

**Comment by JayDi85** [comment]
Beta restarted. If you catch same error type or miss card errors then report to jaydi85@gmail.com for beta server restart.

**Comment by calkno** [comment]
Beta server restart please

**Comment by JayDi85** [comment]
@calkno beta restarted
