### ISSUE TITLE
Game completely fails for everyone in the tournament on turn 1

### ISSUE THREAD

**Issue by duelcastermage** [magefree/mage#8864]
This was on the XMage Beta. Very bizarre error.

We just finished a 6 player chaos draft with 3 random sets (SHM, ARB, MM3). After everyone submitted their decks and round 1 started, all 3 games in the tournament crashed simultaneously seconds into turn 1 of game 1. The only game actions that were taken were playing a land or borderpost, nothing more. This error appeared on all of our screens:

> Game exception occurred: mage.MageException: Iterated player priority after game exception too often, game ends! Last error:
 null
Server version: 1.4.51-V3-beta7 (build: 2022-04-09 16:42)
mage.game.GameImpl.playPriority(GameImpl.java:1592)
mage.game.turn.Step.priority(Step.java:61)
mage.game.turn.Phase.playStep(Phase.java:184)
mage.game.turn.Phase.play(Phase.java:89)
mage.game.turn.Turn.play(Turn.java:132)
mage.game.GameImpl.playTurn(GameImpl.java:1064)
mage.game.GameImpl.play(GameImpl.java:974)
mage.game.GameImpl.start(GameImpl.java:950)
mage.server.game.GameWorker.call(GameWorker.java:34)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)

![image](https://user-images.githubusercontent.com/46700039/164359982-19177abe-fccf-4ee9-8c92-c29013174dfe.png)

This happened 3 times in a row across 2 different Beta servers, and it also occurred when we did a freeform "constructed" tournament with our Limited decks.

**Comment by awjackson** [comment]
Some investigation revealed that the crash is caused by `CycleOrDiesTriggeredAbility`. Merely having a card with this ability class in your *sideboard* causes a NPE shortly into a game.

**Comment by jeffwadsworth** [comment]
It would be nice to be able to specify multiple specific zones for a trigger vs using Zone.ALL.  In this particular case, Zone.HAND and Zone.Battlefield.

**Comment by awjackson** [comment]
Look at it this way, the bug was a lot easier to find this way.
