### ISSUE TITLE
Aetherstorm Roc targets before spending energy

### ISSUE THREAD

**Issue by Jipsu** [magefree/mage#8872]
This is a bit niche but [[Aetherstorm Roc]] targets a creature to tap first, then asks if you want to pay energy to use the ability. This effectively forces you to target stuff without paying the cost which can be an abusable benefit. See two attack phases from the log for examples where first I don't pay and then I do.

11:22 PM, T9.DA: Jipsu attacks with 1 creature 
11:22 PM, T9.DA: Jipsu - Ability triggers: Aetherstorm Roc [025] - Whenever Aetherstorm Roc [025] attacks, you may pay EE. If you do, put a +1/+1 counter on it and tap up to one target creature defending player controls. - targeting Aetherstream Leopard [909] 
11:22 PM, T9.DB: Attacker: Aetherstorm Roc [025] (3/3) unblocked

11:24 PM, T11.DA: Jipsu attacks with 4 creatures 
11:24 PM, T11.DA: Jipsu - Ability triggers: Aetherstorm Roc [025] - Whenever Aetherstorm Roc [025] attacks, you may pay EE. If you do, put a +1/+1 counter on it and tap up to one target creature defending player controls. - targeting Aetherstream Leopard [909] 
11:24 PM, T11.DA: Jipsu paid for Aetherstorm Roc [025] - Pay EE and put a +1/+1 counter on it and tap up to one target creature defending player controls?
11:24 PM, T11.DB: Attacker: Hotshot Mechanic [dba] (2/1) unblocked 
11:24 PM, T11.DB: Attacker: Countless Gears Renegade [92b] (2/2) unblocked 
11:24 PM, T11.DB: Attacker: Yahenni, Undying Partisan [41f] (2/2) unblocked 
11:24 PM, T11.DB: Attacker: Aetherstorm Roc [025] (4/4) unblocked

**Comment by theelk801** [comment]
This is the intended behavior, targets are chosen when the ability goes on the stack and costs like that are paid on resolution. That’s why you’re starting to see “when you do” templating on newer cards like [[Skyrider Patrol]] which work the way you’re expecting.
