### ISSUE TITLE
Dream Devourer's ability triggers off of other ways of sending cards to exile from the hand

### ISSUE THREAD

**Issue by alexander-novo** [magefree/mage#8876]
[[Dream Devourer]]'s second ability is only supposed to trigger whenever you foretell a card, but it also triggers off of things like suspend.

**Comment by jeffwadsworth** [comment]
How exactly did you suspend the card?

**Comment by alexander-novo** [comment]
I don't remember. I think it was just a card with a suspend ability, which I suspended from my hand.

**Comment by alexander-novo** [comment]
Here is my reproduction with suspending [[Sol Talisman]] from hand.

![image](https://user-images.githubusercontent.com/11657716/165601498-8ed7cb3d-2cfe-4ee7-8efe-255f8177b60f.png)
