### ISSUE TITLE
Limited Streets of New Capenna not working on beta server

### ISSUE THREAD

**Issue by pyested** [magefree/mage#8880]
Hi, I've been trying to test the new implemented cards choosing "Sealed elimination" as the tournament type in beta server against the computer. It seems that the pool of 6 packs is not generated. I also tried the prior set, Kamigawa Neon Dynasty, and everything works fine in that case. Shall we wait till next beta update??

**Comment by JayDi85** [comment]
@awjackson can you confirm what this was fixed in last commit 6fd4b46ca86406e9834207109557e7100ab8f2a6?

**Comment by JayDi85** [comment]
Beta updated with last fixes, so boosters must works.
