### ISSUE TITLE
BUG Toxrill slug counter didn't work correctly 

### ISSUE THREAD

**Issue by kons7** [magefree/mage#8881]
the goblins did get a slug counter in my endstep, but only died either in the opponents endstep (2 counter) or in my upkeep
![Bild_2022-04-26_203021753](https://user-images.githubusercontent.com/97984596/165368033-d707ffa3-5c1f-4cc5-9355-917e699935bf.png)

**Comment by jeffwadsworth** [comment]
[[Toxrill, the Corrosive]]

**Comment by jeffwadsworth** [comment]
![workedFineHere](https://user-images.githubusercontent.com/1496996/166809731-1a3a1a7e-54a4-4023-986a-d3d8b7ba2f8f.jpg)

**Comment by jeffwadsworth** [comment]
Worked for me.  Used 4 Memnite's for the opponent.  Tokens were created before I had to discard my excess cards.

**Comment by kons7** [comment]
> Worked for me. Used 4 Memnite's for the opponent. Tokens were created before I had to discard my excess cards.

it was only one time where it didn't work ( the one time i screenshotted it). but when it doesn't work once then there seems to be an issue somewhere
