### ISSUE TITLE
"Gain control of creature" effects tap the creature who control is swapped

### ISSUE THREAD

**Issue by alexander-novo** [magefree/mage#8884]
Observed with [[Puca's Mischief]] and [[Empress Galina]]

**Comment by awjackson** [comment]
I can't reproduce this with either card mentioned. In my testing, the permanents that change controller retain their tapped/untapped status.

**Comment by Alex-Vasile** [comment]
@alexander-novo

Was this on the beta?
Can't you stop reproduce it?

**Comment by alexander-novo** [comment]
I observed this a while back, but I haven't played Empress Galina in a while now. There's a possibility it isn't an issue anymore.

**Comment by PurpleCrowbar** [comment]
> I observed this a while back, but I haven't played Empress Galina in a while now. There's a possibility it isn't an issue anymore.

Just tested [[Empress Galina]] on latest build and newly controlled permanent is correctly not tapped, so this has presumably already been fixed at some point
