### ISSUE TITLE
"When this dies, draw a card" ability gained from Blitz persists across zones and accumulates

### ISSUE THREAD

**Issue by dashosa** [magefree/mage#8885]
![image](https://user-images.githubusercontent.com/63882410/165438766-20faf815-fb17-4389-ad8a-b653548edcad.png)

**Comment by jeffwadsworth** [comment]
[[Dictate of Erebos]]

**Comment by jeffwadsworth** [comment]
Works fine for me.

**Comment by stevedavidmusic** [comment]
> 

Happens when Blitzed from the graveyard.

**Comment by stevedavidmusic** [comment]
> 




> Works fine for me.

The draw triggers twice only when blitzed from the graveyard.

**Comment by stevedavidmusic** [comment]
Seems to be fixed now in the 5-27-22 update.

**Comment by awjackson** [comment]
This is a real bug and affects all creatures with Blitz. Somehow the "when this dies, draw a card" ability is persisting on the card across zones. The first time a creature cast with Blitz dies, you draw one card. If you return the creature card to your hand with [[Disentomb]] and cast it again, the second time it dies you get two triggers and draw two cards. If you return the card and cast it with Blitz a third time, you get three triggers and three cards the next time it dies.
