### ISSUE TITLE
Repeated Card Not Found Errors

### ISSUE THREAD

**Issue by Alex-Vasile** [magefree/mage#8897]
Trying to play on the newest beta on the public server. Adding a Nikya deck (attached below). When I try to join a game it says that a given card is not found, see screenshot.

<img width="544" alt="Screen Shot 2022-04-30 at 9 57 39 AM" src="https://user-images.githubusercontent.com/48962821/166113096-eed4cd36-efd9-4b5f-ba83-8f5af859e135.png">

Fixing that card buy switching sets for it leads to another issue, and then another.

Deck list as text file is attached. Import from clipboard and let XMage pick.

[nikyia.txt](https://github.com/magefree/mage/files/8597274/nikyia.txt)

**Comment by Alex-Vasile** [comment]
Happens with other decks I have now, which worked minutes ago. I think something is up with the beta server.

**Comment by JayDi85** [comment]
beta restarted

**Comment by Alex-Vasile** [comment]
Is it known what causes these issues?

**Comment by JayDi85** [comment]
@Alex-Vasile yes -- memory leaks, see #4520 (example: AI freezes in infinite cycle until all memory eats).
