### ISSUE TITLE
Essence Pulse not working correctly

### ISSUE THREAD

**Issue by rockydirtbag** [magefree/mage#8898]
When the player who cast Essence Pulse gains life after the spell resolved, creatures should not be affected any further. Currently the -X/-X effect is adjusted throughout the turn Essence Pulse was cast.

**Comment by jeffwadsworth** [comment]
[[Essence Pulse]]

**Comment by jeffwadsworth** [comment]
608.2h. If an effect requires information from the game (such as the number of creatures on the battlefield), the answer is determined only once, when the effect is applied.

**Comment by jeffwadsworth** [comment]
Good catch.  There are other cards with this issue as well.
