### ISSUE TITLE
"Banishing Light" effects don't get cancelled if they LTB while on the stack, resulting in permanent exile

### ISSUE THREAD

**Issue by Thelk641** [magefree/mage#8899]
-- Setup :

Both [[Lagrella, the Magpie]] and [[Charming Prince]] are ETBing together (both of these can be replaced with any "exile until ~ leaves the battlefield" and any way to make the first card LTB before it resolves). Pick Lagrella's target, then target her with Charming Prince, having his effect resolve first.

-- What happens : 

Charming Prince's effect resolves, Lagrella is exiled until the end of the turn. Lagrella's effect resolves, exiling its target. As she has already left the battlefield, there is no "leaves the battlefield" trigger possible, so those targets won't ever come back to the battlefield.

-- What should be happening :

Charming Prince's effect resolves, Lagrella is exiled until the end of the turn. Lagrella's effect fizzles, her effect is worded like Banishing Light's ("exile until ~ leaves the battlefield") and BL's ruling reads "If Banishing Light leaves the battlefield before its triggered ability resolves, the target permanent won’t be exiled. ". 

I picked Lagrella because she has a second, less bad bug : her effects reads "When an exiled card enters the battlefield under your control this way, put two +1/+1 counters on it.", but when it triggers it only puts a single +1/+1 counter instead of two.

**Comment by awjackson** [comment]
Flicker effects like Flicker of Fate still don't interact correctly. We need to use `source.getSourcePermanentIfItStillExists` to ensure that the permanent currently on the battlefield is the same one (i.e. same zone change counter) whose ability is resolving. Currently when you flicker a Banishing Light or similar permanent with the ability on the stack, you get to exile two permanents.

**Comment by awjackson** [comment]
addfd5166e8f0a62dcf7d30f7518bf7228d14bea fixed this for the common `ExileUntilSourceLeavesEffect` class, but there are many many custom versions of this effect.

**Comment by awjackson** [comment]
e310ede83710c853d4cc876c98b332cd2fecceb5 should have fixed this for all effects that exile permanents. [[Brain Maggot]] [[Kitesail Freebooter]] and [[Valki, God of Lies]] still need to be slightly reworked because the target opponent should still reveal their hand even if the source has left the battlefield (though you don't get to exile any cards).
