### ISSUE TITLE
[SNC] Creature with Blitz ability incorrectly drawing cards upon death when not cast for Blitz cost

### ISSUE THREAD

**Issue by craigbrennan24** [magefree/mage#8909]
Happened with Mayhem Patrol. Opponent cast it for its regular mana cost, but the blitz ability triggered upon death and drew them a card.

**Comment by craigbrennan24** [comment]
[[Mayhem Patrol]]

**Comment by jeffwadsworth** [comment]
How did the creature die?  I tested this and it worked as expected.

**Comment by craigbrennan24** [comment]
Yeah I'm having trouble replicating it as well, I'm guessing my opponent did actually cast for the blitz cost after all. I'm sure it was on the battlefield for more than 1 turn though

I'll close it for now and open another one if I can manage to replicate it

**Comment by awjackson** [comment]
Duplicate of #8885
