### ISSUE TITLE
Xmage beta server doesn't allow starting matches

### ISSUE THREAD

**Issue by AlexanderBulanov** [magefree/mage#8914]
![xmage beta server error](https://user-images.githubusercontent.com/8094020/166608171-c820f733-bb6f-4dc9-bbe8-ea9ea5cae661.png)

Unable to create matches on the beta xmage server due to server not recognizing cards in any decklist. This issue was resolved a few days ago but has returned since.

**Comment by JayDi85** [comment]
beta restarted
