### ISSUE TITLE
Battlefield layout does not support enchanted aura enchantments

### ISSUE THREAD

**Issue by LevelX2** [magefree/mage#892]
Diegogrt93 posted 3 days ago (#880)

My opponent had a creature enchanted with Angelic Destiny. I casted Soul Tithe targeting the Destiny, and after it resolved his creature vanished, leaving only the Destiny with Soul Tithe above it

Problem is reproducable.

**Comment by LevelX2** [comment]
http://www.slightlymagic.net/forum/viewtopic.php?f=70&t=16910&p=177951#p177951

**Comment by jeffwadsworth** [comment]
The creature permanent doesn't really disappear, it is actually behind the enchantment card.  Checking it out.
