### ISSUE TITLE
Estrid's Invocation doesn't copy anything when it is blinked

### ISSUE THREAD

**Issue by TakeHeedStruggler** [magefree/mage#8922]
[[Estrid's Invocation]] enters the battlefield as a copy of another enchanment as normal, but when it is blinked it simply comes back as itself

**Comment by copperfield42** [comment]
it happens to me too
![image](https://user-images.githubusercontent.com/4504719/167702726-d371d8f4-aa34-4d9c-8009-e39449aa195d.png)

In a previous turn I copy a Beastmaster Ascension with [[Mirage Mirror]], play [[Estrid's Invocation]] to copy the transformed Mirror, then in the next turn, in response to Estrid's Invocation trigger I use Mirror to copy an Assemble the Legion but this time the invocation doesn't copy it

**Comment by peter-thoenen** [comment]
Long known issue, dup of #7821
