### ISSUE TITLE
Toluz, Clever Conductor bug

### ISSUE THREAD

**Issue by catman123456** [magefree/mage#8930]
Toluz, Clever Conductor died and the cards exiled with it did not returned to my hand.

![image](https://user-images.githubusercontent.com/64045003/167469234-b214834f-31a9-4fbc-a2cc-5ff69e5311ca.png)

**Comment by catman123456** [comment]
[[Toluz, Clever Conductor]]

**Comment by jeffwadsworth** [comment]
This is similar to other examples of cards in the exile zone.  The source ability is being used as a exile reference, which is great, unless you are using another ability for the exile callback...which will fail.
