### ISSUE TITLE
Minotaur token redundancy

### ISSUE THREAD

**Issue by PurpleCrowbar** [magefree/mage#8947]
The cards [[Flurry of Horns]] and [[Sethron, Hurloon General]] create the exact same 2/3 red Minotaur token. Despite this, [Sethron](https://github.com/magefree/mage/blob/bdeb0dde66e61cc5383e1f33a341ba126ea6b867/Mage.Sets/src/mage/cards/s/SethronHurloonGeneral.java#L22) creates instances of "[MinotaurToken](https://github.com/magefree/mage/blob/9e0ea945ca81e0197caa7ec994c363b5b4d4fe32/Mage/src/main/java/mage/game/permanent/token/MinotaurToken.java)" whereas [Flurry of Horns](https://github.com/magefree/mage/blob/754a5b38ebba104b83494629c1f3881020168b1e/Mage.Sets/src/mage/cards/f/FlurryOfHorns.java#L9) creates intances of "[FlurryOfHornsMinotaurToken](https://github.com/magefree/mage/blob/9e0ea945ca81e0197caa7ec994c363b5b4d4fe32/Mage/src/main/java/mage/game/permanent/token/FlurryOfHornsMinotaurToken.java)".

I'd like to propose removing "FlurryOfHornsMinotaurToken" and replacing all instances of it in the code with "MinotaurToken" for consistency.

**Comment by PurpleCrowbar** [comment]
As it turns out there *is* actually a difference between the tokens generated by these two cards, that being that FoH's minotaurs have haste. The reason I was confused is that WotC seems to have made a mistake with FoH's minotaurs (pictured below, notably without haste), as despite the fact that the card creates "Minotaur creature tokens with haste" (as opposed to creating them then *granting* them haste) the set's only minotaur token depicts a 2/3 with no ability,

![image](https://user-images.githubusercontent.com/26198472/168166087-76a1d096-20f7-45da-9971-5e20c584d5c2.png)

This is the reason that on Scryfall both FoH and Sethron use the "same token", because the token image is the same (although the tokens are definitely not, as Sethron's don't have haste).

This means that FlurryOfHornsMinotaurToken.java **should not be removed** and FoH's tokens can be generated with the appropriate image. However I'm not sure what is to be done about Sethron as the Jumpstart set, as previously mentioned, has no token images. Usually with situations like this you could just take JMP out of the available image set codes for the token in question and it would default to using a random image from other sets but because these are technically not the same token this doesn't apply.

A potential (bandaid?) solution could be to add the minotaur token to the card-pictures-tok.txt and associate it with JMP and in the ScryfallImageSupportTokens.java use the download link for JOU's minotaur. I believe this would solve the problem and a more consistent solution can be used should WotC ever decide to print a card which generates 2/3 red minotaurs in the future.

**Comment by Alex-Vasile** [comment]
The same token file could still be used for both, but at the cost of more code inside Flurry of Horns. I believe it's possible to create tokens that have an ability rather than gaining the ability.

**Comment by PurpleCrowbar** [comment]
> The same token file could still be used for both, but at the cost of more code inside Flurry of Horns. I believe it's possible to create tokens that have an ability rather than gaining the ability.

This would be ideal, although I don't personally know how to implement that. Having FlurryOfHornsMinotaurToken.java removed and any reference to its creation in FlurryOfHorns.java replaced with an instance of MinotaurToken.java but with haste granted would solve the issue nicely and allow Sethron's minotaurs to have images too. It would also obviously have to have its name changed in [card-pictures-tok.txt](https://github.com/magefree/mage/blob/e3332fbea88789f1af2003133b9f37eaf7748157/Mage.Client/src/main/resources/card-pictures-tok.txt#L757) but that's easy.

**Comment by PurpleCrowbar** [comment]
There's a similar problem to this one with the [4/4 red Hellion token](https://scryfall.com/card/troe/3/hellion), as the card [[Hellion Eruption]] creates a regular Hellion and [[Hellion Crucible]] creates a Hellion with haste, despite it not having haste in the image, and this results in there being two separate tokens ("[HellionToken](https://github.com/magefree/mage/blob/9e0ea945ca81e0197caa7ec994c363b5b4d4fe32/Mage/src/main/java/mage/game/permanent/token/HellionToken.java)" and "[HellionHasteToken](https://github.com/magefree/mage/blob/9e0ea945ca81e0197caa7ec994c363b5b4d4fe32/Mage/src/main/java/mage/game/permanent/token/HellionHasteToken.java)") which both effectively share an image.

This is less of an issue than with Sethron because M13's Hellion Crucible has an M13 Hellion token of its own, so that can be used for the hasty Hellions even though the image itself doesn't show a Hellion with haste. This is unlike JMP which doesn't have a Minotaur token of its own.

**Comment by PurpleCrowbar** [comment]
Just found this code snippet in the [GoblinToken](https://github.com/magefree/mage/blob/master/Mage/src/main/java/mage/game/permanent/token/GoblinToken.java#L15) class. In this case it allows the GoblinToken class to be used for both hasted and non-hasted tokens. 
![image](https://user-images.githubusercontent.com/26198472/171516131-1501409f-127e-4173-b13e-92e0329cd568.png)
This seems to be the solution to both the minotaur and hellion problem - remove the [FlurryOfHornsMinotaurToken](https://github.com/magefree/mage/blob/master/Mage/src/main/java/mage/game/permanent/token/FlurryOfHornsMinotaurToken.java) and [HellionHasteToken](https://github.com/magefree/mage/blob/master/Mage/src/main/java/mage/game/permanent/token/HellionHasteToken.java) and implement this boolean haste functionality in the more general [MinotaurToken](https://github.com/magefree/mage/blob/master/Mage/src/main/java/mage/game/permanent/token/MinotaurToken.java) and [HellionToken](https://github.com/magefree/mage/blob/master/Mage/src/main/java/mage/game/permanent/token/HellionToken.java) classes.

**Comment by Alex-Vasile** [comment]
> Just found this code snippet in the [GoblinToken](https://github.com/magefree/mage/blob/master/Mage/src/main/java/mage/game/permanent/token/GoblinToken.java#L15) class. In this case it allows the GoblinToken class to be used for both hasted and non-hasted tokens. 
> 
> ![image](https://user-images.githubusercontent.com/26198472/171516131-1501409f-127e-4173-b13e-92e0329cd568.png)
> 
> This seems to be the solution to both the minotaur and hellion problem - remove the [FlurryOfHornsMinotaurToken](https://github.com/magefree/mage/blob/master/Mage/src/main/java/mage/game/permanent/token/FlurryOfHornsMinotaurToken.java) and [HellionHasteToken](https://github.com/magefree/mage/blob/master/Mage/src/main/java/mage/game/permanent/token/HellionHasteToken.java) and implement this boolean haste functionality in the more general [MinotaurToken](https://github.com/magefree/mage/blob/master/Mage/src/main/java/mage/game/permanent/token/MinotaurToken.java) and [HellionToken](https://github.com/magefree/mage/blob/master/Mage/src/main/java/mage/game/permanent/token/HellionToken.java) classes.

Given how other constructors of this type are handled in the project, shouldn't the no parameter version should call the Boolean version with a default value for the Boolean?

**Comment by Alex-Vasile** [comment]
> > > Just found this code snippet in the [GoblinToken](https://github.com/magefree/mage/blob/master/Mage/src/main/java/mage/game/permanent/token/GoblinToken.java#L15) class. In this case it allows the GoblinToken class to be used for both hasted and non-hasted tokens.
> > > ![image](https://user-images.githubusercontent.com/26198472/171516131-1501409f-127e-4173-b13e-92e0329cd568.png)
> > > This seems to be the solution to both the minotaur and hellion problem - remove the [FlurryOfHornsMinotaurToken](https://github.com/magefree/mage/blob/master/Mage/src/main/java/mage/game/permanent/token/FlurryOfHornsMinotaurToken.java) and [HellionHasteToken](https://github.com/magefree/mage/blob/master/Mage/src/main/java/mage/game/permanent/token/HellionHasteToken.java) and implement this boolean haste functionality in the more general [MinotaurToken](https://github.com/magefree/mage/blob/master/Mage/src/main/java/mage/game/permanent/token/MinotaurToken.java) and [HellionToken](https://github.com/magefree/mage/blob/master/Mage/src/main/java/mage/game/permanent/token/HellionToken.java) classes.
> > 
> > 
> > Given how other constructors of this type are handled in the project, shouldn't the no parameter version should call the Boolean version with a default value for the Boolean?
> 
> I don't know of other similar instances of this type of thing in xmage, but if what you have in mind for this would be better then please do so - token classes to be changed, to my knowledge, would be [MinotaurToken](https://github.com/magefree/mage/blob/e418ab04be33d494a1483647ae9d390dcbc0f1be/Mage/src/main/java/mage/game/permanent/token/MinotaurToken.java), [HellionToken](https://github.com/magefree/mage/blob/e418ab04be33d494a1483647ae9d390dcbc0f1be/Mage/src/main/java/mage/game/permanent/token/HellionToken.java), and [GoblinToken](https://github.com/magefree/mage/blob/7e523e655a586b82aaa00c2179805b2e8c242ee8/Mage/src/main/java/mage/game/permanent/token/GoblinToken.java)

It's the java way of handling default values for parameters. Take [EquipAbility's](https://github.com/magefree/mage/blob/309c2df7810d5e0af10a39d404ad33233e4b5f11/Mage/src/main/java/mage/abilities/keyword/EquipAbility.java) constructors. All of the constructors with fewer parameters call the ones with more parameters in order to provide the default values. It's used in other places, but usually further up the inheritance tree something like a concrete Token (since most of them always have the same options).

The code as it's currently implemented isn't wrong from a logic point of view, just inconsistent with the rest of the codebase.
