### ISSUE TITLE
Bug [VOW]: "Voltaic Visionary" does not transform

### ISSUE THREAD

**Issue by Don-Cruz** [magefree/mage#8966]
Voltaic Visionary should transform, when you play the card exiled with his ability. This does not happend, the trigger does not appear.

In this example the Visionary exiled the card "Wedding Security". I casted Wedding Security afterwards. No trigger showed up, the card did not transform.

![Voltaic Visionary](https://user-images.githubusercontent.com/78379079/168860925-d17df574-0426-4f63-8f84-dc3a0ef85918.PNG)

![Voltaic Visionary 2](https://user-images.githubusercontent.com/78379079/168860952-f74ed969-bed1-4e11-bcc5-b8c1b9d8dc35.PNG)

[https://scryfall.com/card/vow/183/voltaic-visionary-volt-charged-berserker](url)

**Comment by jeffwadsworth** [comment]
[[Voltaic Visionary]]
