### ISSUE TITLE
XMage Isn't Starting

### ISSUE THREAD

**Issue by Akira4712** [magefree/mage#8967]
I click start client, doesn't so shit, I click start server, doesn't do shit. 
I haven't has this issue with XMage before at all.
Please fix this.

**Comment by Alex-Vasile** [comment]
Is this on the beta?
What error do you get?

Have you tried:
- Restarting computring
- Forcing an update through the client
- Reinstalling the client?
Have you tried forcing an update?

**Comment by Alex-Vasile** [comment]
@Akira4712 ?
