### ISSUE TITLE
Ashiok Nightmare Muse ultimate small bug

### ISSUE THREAD

**Issue by thebear132** [magefree/mage#8971]
When using the -7 ability of [[Ashiok, Nightmare Muse]], it is also possible to cast your own cards in exile, even tho you should only be able to cast your opponents cards in exile.

Possibly these filters here in the AshiokNightmareMuse.java CastEffect class
`filter.add(TargetController.OPPONENT.getOwnerPredicate());`
`filter.add(Predicates.not(FaceDownPredicate.instance));`

Even though they look to be alright?

**Comment by Alex-Vasile** [comment]
I think the issue is the use of StaricFilters.FILTER_CARD. I can't check what parameter it's being in for, but that would be my guess.

**Comment by jeffwadsworth** [comment]
This worked fine for me.
