### ISSUE TITLE
Playing commander against 3 computers, game usually craps out after 4 rounds of turns. I have 4G dedicated ram. Windows latest versions of both Java and Xmage. Why is this?

### ISSUE THREAD

**Issue by Flexerhh** [magefree/mage#8978]

**Comment by Alex-Vasile** [comment]
Can you provide more info of what's happening.

Did you dedicate 4GB to the client or the server?

**Comment by Flexerhh** [comment]
So the game freezes almost, at a certain poiint, then if I minimise it, the screen is white when I maximise it again.

4GB to server and Client. I will post a screensho
![2022-05-20 (3)](https://user-images.githubusercontent.com/105883165/169622412-e3888f69-fceb-47b7-b0fd-2473ca88f667.png)
![2022-05-20 (2)](https://user-images.githubusercontent.com/105883165/169622414-2d83915f-e2cb-42f2-a311-de4b1c971586.png)
t

**Comment by copperfield42** [comment]
I have found that some card tend to cause problem, like those that have many possibles targets such as [[Inferno Titan]] and as such I never put those in the AI decks

**Comment by Alex-Vasile** [comment]
> So the game freezes almost, at a certain poiint, then if I minimise it, the screen is white when I maximise it again.
> 
> 
> 
> 4GB to server and Client. I will post a screensho
> 
> ![2022-05-20 (3)](https://user-images.githubusercontent.com/105883165/169622412-e3888f69-fceb-47b7-b0fd-2473ca88f667.png)
> 
> ![2022-05-20 (2)](https://user-images.githubusercontent.com/105883165/169622414-2d83915f-e2cb-42f2-a311-de4b1c971586.png)
> 
> t

Does this happen with specific decks? Or regardless of which decks you use?

**Comment by johnmeat** [comment]
I asked the same thing trying to use the beta server, under #8968. See the responses from JayDi. I had much better games when I swapped out the decks that the AI was using.

**Comment by Flexerhh** [comment]
Ive been using the commander decks from 2017. So the Edgar Markov deck was specified in the ticket @johnmeat Suggested in the ticket.

I will try others and will come back with results.

I will also take a look at the linked ticket on the linked ticket you posted @johnmeat 

Many thanks for the responses guys.

**Comment by Alex-Vasile** [comment]
> Ive been using the commander decks from 2017. So the Edgar Markov deck was specified in the ticket @johnmeat Suggested in the ticket.
> 
> 
> 
> I will try others and will come back with results.
> 
> 
> 
> I will also take a look at the linked ticket on the linked ticket you posted @johnmeat 
> 
> 
> 
> Many thanks for the responses guys.

Okay, if it was the same deck then I'll close this issue since they're the same problem.

Post your findings in that issue and I'll look into the decks you found to be problems
