### ISSUE TITLE
Dromoka's Command modes don't resolve in the correct order 

### ISSUE THREAD

**Issue by andyfries** [magefree/mage#898]
According to the first ruling on http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=394558 the modes should resolve in the order written. The behavior in xmage is that the modes resolve in reverse order of selection.

Example:
I have a 2/2 creature and my opponent also has a 2/2 creature. I cast Dromoka's Command choosing modes 3 and 4 to put a +1/+1 counter on my creature then fight my opponent's creature. The correct behavior would be for the counter to resolve, then for the fight to resolve, leaving my creature alive with  a +1/+1 counter on it. Currently the order depends on which mode is selected first, so if I select the +1/+1 counter then the fight, both creatures will die in the fight before the counter is placed on my creature.

**Comment by LevelX2** [comment]
Fixed.
