### ISSUE TITLE
Tide skimmer's ability does not trigger

### ISSUE THREAD

**Issue by FjolleJagt** [magefree/mage#8982]
When I attack with two flying creatures while Tide Skimmer is in play, I should draw a card. However, no ability gets put onto the stack. This was in XMage version 1.4.50V2 (2021-09-05)

**Comment by AmeyMirchandani** [comment]
When testing this out, it seems to work fine, could you give me the specific example?

**Comment by Alex-Vasile** [comment]
> When testing this out, it seems to work fine, could you give me the specific example?

They're having the issue in 1.4.50V2. It might have been fixed since then. You can try checking out older versions and see when it got fixed. Or check out the history of the file and see when it was fixed in the past

**Comment by FjolleJagt** [comment]
Thanks for looking into into it! If I remember correctly, I had Faerie Vandal, Skycat sovereign, and Tide Skimmer, and neither attacking with Faerie Vandal + Skycat Sovereign nor with Faerie Vandal + Tide Skimmer triggered the effect.

**Comment by AmeyMirchandani** [comment]
That's odd, as when I check the git history, it seems to only have been implemented once and then never changed.

**Comment by Alex-Vasile** [comment]
> That's odd, as when I check the git history, it seems to only have been implemented once and then never changed.

Tide skimmer was not changed, but the AttacksWithCreaturesTriggeredAbility had a bug which was fixed in  187e0736a054583bbb58e975c3671f482d35a9ba.

It was an off-by one issue. So if you were to attack with 3 creatures the ability should trigger.
