### ISSUE TITLE
Server error: Card not found

### ISSUE THREAD

**Issue by SchrodingersSwitch** [magefree/mage#8983]
Beta Server appears to rejecting all pre-built decks and failing to generate cards for a draft, Example Screenshot of error window:
![image](https://user-images.githubusercontent.com/105991126/169666329-c41d0089-46df-4893-91e3-d24c6a09f9ff.png)

**Comment by Alex-Vasile** [comment]
Same issue as #8897. Server needs a reboot @JayDi85

**Comment by JayDi85** [comment]
restarted
