### ISSUE TITLE
Server login Error

### ISSUE THREAD

**Issue by akuma508** [magefree/mage#8987]
![image](https://user-images.githubusercontent.com/106072848/169796161-622f0c7a-c98c-4be7-acf2-51d1ddb9664d.png)

I'll getting the attached error when trying to login to the Beta server via the beta client.

**Comment by Alex-Vasile** [comment]
A. This needs better error messages, I have no idea what the error is.

Do you get this problem when joining a local server? is it still happening today?

**Comment by LokiOnTheLowkey** [comment]
Hey, I had this same issue yesterday. It started around 8pm but doesn't seem to be an issue anymore today. It doesn't seem to be possible to create a game now though. I get the message below any time I try to start a game, and these are with decks that I made in the deck builder just before launch. I just forced an update and redownloaded images but that didn't seem to fix the issue.

![image](https://user-images.githubusercontent.com/77560311/169944375-003bb93b-d794-40ff-944b-f4ef1b6371b8.png)

**Comment by JayDi85** [comment]
@akuma508 you must open second port 17172 by default (look for it in server's config). Try to disable firewall or move all files to another folder to re-request firewall access on first run.

@LokiOnTheLowkey missing card error are beta restart needs, so you can write to jaydi85@gmail.com to request server's restart. It works fine now.

**Comment by akuma508** [comment]
It is gone now. Thank you

**Comment by LokiOnTheLowkey** [comment]
@JayDi85 Thanks, will do the next time I see this issue.
