### ISSUE TITLE
Launcher hangs if xmage.info site is not available

### ISSUE THREAD

**Issue by townxelliot** [magefree/mage#899]
The xmage.info site is currently down, but the Launcher just hangs as it tries to connect (the same way a browser does). This prevents the Launcher from starting at all.

If I change the xmage.home URL in installed.properties to a different site (which doesn't have config.json but does resolve in a browser), the Launcher starts and displays an error message, so I can still start the server and client.

I'd suggest the Launcher code is changed to automatically timeout the HTTP connection and show an error in the Launcher gui if xmage.info won't resolve or respond in a timely fashion.

**Comment by townxelliot** [comment]
Just realised there's a separate project for the Launcher, which is where this issue should probably be...

**Comment by goesta** [comment]
I'll close this issue because it seems to be outdated but feel free to create a new one if this problem still exists.
