### ISSUE TITLE
Instructions for building xmage from the command line

### ISSUE THREAD

**Issue by townxelliot** [magefree/mage#900]
I'd like to contribute to xmage, but don't want to have to install netbeans to do so. There's already Maven build infrastructure, which suggests I could build from the command line. I've got as far as compiling the project. However, I can't figure out a way to run the project once I've done `mvn install`.

I've tried:

```
java -jar ./Mage.Server/target/mage-server.jar
```

but get this error:

```
Exception in thread "main" java.lang.NoClassDefFoundError: org/jboss/remoting/transporter/TransporterServer
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2531)
	at java.lang.Class.getMethod0(Class.java:2774)
	at java.lang.Class.getMethod(Class.java:1663)
	at sun.launcher.LauncherHelper.getMainMethod(LauncherHelper.java:494)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:486)
Caused by: java.lang.ClassNotFoundException: org.jboss.remoting.transporter.TransporterServer
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
```

If I include all the jar files in the project in the classpath:

```
java -jar ./Mage.Server/target/mage-server.jar -cp "`find . -name *.jar | tr '\n' ' '`"
```

I still get the same error.

Are there any instructions for building and running xmage from the command line, or is some additional work required to download additional dependencies (presumably ones which are available if you're working on the project in netbeans?) ?

**Comment by LevelX2** [comment]
Probably this should be done with mvn exec:exec but I guess it won't work without some additional research and changes. And this whole configuration can be a very tricky thing.

My advice: Do yourself a favor and use Netbeans.

**Comment by Erotemic** [comment]
For those of us that prefer to work in a terminal environment, instructions for building and running from the command line would be very useful. The driving reason is that I'd like to be able to run this program on a headless server without a gui. 

I'm attempting to use netbeans just so I can get things running, but I'd much rather understand how this system works rather than let the build process by obfuscated by an IDE.

**Comment by Erotemic** [comment]
So, I'll write a quick summary laying out instruction for getting the development environment running via command-line instructions. These instructions will target Ubuntu 16.04, but other distros can swap out the `apt install` for the relevant commands / downloads. 

```bash
# Install Java Development Toolkit
sudo apt install default-jre
sudo apt install default-jdk

# Install Maven (a build automation tool for Java projects)
# Maven, uses the pom.xml files to download dependencies and build the project.
# Note that it will create a ~/.m2 directory
sudo apt install maven

# Set this to where you want your xmage sourcecode to live
CODE_DIR=$HOME/code
mkdir -p $CODE_DIR
cd $CODE_DIR

# Clone the repo
git clone https://github.com/magefree/mage.git

cd $CODE_DIR/mage

# Use maven to build the project (this might actually put something in your ~/.m2 directory, so there might be a better less invasive command to run for building here)
mvn install

# Start the Maven Server
cd $CODE_DIR/mage/Mage.Server
mvn exec:java -Dexec.mainClass=mage.server.Main 


# In a separate terminal (or if you use something like nohup to start the
# server in the background), start the Mage Client. This command will start the
# GUI.
cd $CODE_DIR/mage/Mage.Client
mvn exec:java -Dexec.mainClass=mage.client.MageFrame
```
