### ISSUE TITLE
Colorless non-flying spirit tokens show as white flying ones

### ISSUE THREAD

**Issue by sprangg** [magefree/mage#9005]
[[Baku Altar]] produces colorless non-flying spirit tokens but the tokens can look like white flying spirits. In the picture below, this kind of wrong token can be seen top right next to Baku Altar.

Someone said Neon Dynasty has a similar issue with its colorless non-flying spirit tokens. I wouldn't be surprised if all the cards producing these have the same issue.

![bakualtar](https://user-images.githubusercontent.com/13901691/170573470-ec412d20-76ab-40e3-bb22-05ed9f4c3095.png)
![spirittoken](https://user-images.githubusercontent.com/13901691/170573800-b49ee41f-85bf-4930-80c4-a8581812cbde.png)

**Comment by PurpleCrowbar** [comment]
Will solve this issue soon (pseudo self-assign).

> Someone said Neon Dynasty has a similar issue with its colorless non-flying spirit tokens. I wouldn't be surprised if all the cards producing these have the same issue.

This should no longer be the case as I fixed NEO's tokens a short while ago and NEO colorless spirit tokens seem to be fine now based on my testing. If you're playing on a non-official server and find that NEO tokens are causing problems I would urge them to update their version of xmage if possible.
