### ISSUE TITLE
Gitaxian Probe, not revealing all cards

### ISSUE THREAD

**Issue by K-Wind** [magefree/mage#904]
I played a Gitaxian Probe targeting my opponent, but for some reason it only revealed 4 of his 5 cards.
The fifth card was a Lightning Bolt, see attached screenshot for the remainder of his hand and the card counter.
![probe missing card](https://cloud.githubusercontent.com/assets/5469438/7105452/530a9ad0-e11a-11e4-8043-03c8eca37ea7.png)

**Comment by LevelX2** [comment]
The code of  Gitaxian Probe looks ok.
I have to check if the problem is reproducable.

**Comment by drmDev** [comment]
Will test later today.
