### ISSUE TITLE
Server Error. Card not found

### ISSUE THREAD

**Issue by akuma508** [magefree/mage#9041]
Using latest Beta server and client. Logging on Beta server, and seem to get this error all the time regardless of deck (just a different card is the error)

![image](https://user-images.githubusercontent.com/106072848/170967970-a46349f7-a27e-4e10-a0eb-a55d5aef78cd.png)

**Comment by JayDi85** [comment]
restarted

**Comment by Alex-Vasile** [comment]
Could we get a memory dump form the server when this happens to figure out what's causing it?

**Comment by JayDi85** [comment]
@Alex-Vasile  write me to jaydi85@gmail.com -- I'll send info

**Comment by akuma508** [comment]
This problem is back again

**Comment by akuma508** [comment]
This problem is back again
Maybe 6hr resets?

**Comment by JayDi85** [comment]
@akuma508  beta restarted
