### ISSUE TITLE
Share the Spoils always exiles from the top of the controller's library, not the library of the player who played the card

### ISSUE THREAD

**Issue by alexander-novo** [magefree/mage#9046]
[[Share the Spoils]] reads:

> When they do, exile the top card of their library.

However, it exiles the top card of the controller of Share the Spoils' library instead. This line is the culprit I believe:

https://github.com/magefree/mage/blob/8736340ecd14a8abdc3f989a2764022f96228b60/Mage.Sets/src/mage/cards/s/ShareTheSpoils.java#L308

It should instead look at the playerId of the event that triggered the ability.

**Comment by Alex-Vasile** [comment]
I am not sure how to get access to that information from inside the apply function. Hmmm

**Comment by alexander-novo** [comment]
Would overriding `public void trigger(Game game, UUID controllerId, GameEvent triggeringEvent)` from `TriggeredAbilityImpl` to set a flag based on the `triggeringEvent`, and then copying the flag in the copy constructor work?

**Comment by jeffwadsworth** [comment]
Just pass it the player ID from the trigger.

**Comment by Alex-Vasile** [comment]
> Just pass it the player ID from the trigger.

I've seen some cards setting a FixedTarget for a player/creature in the trigger and then reading the target in the effect. But won't that count as targeting the player?

**Comment by alexander-novo** [comment]
The trigger function is passed the triggering event, which has a function to get the triggering player ID. I have the fix written (and a test), just trying to get tests to run on my environment.

**Comment by Alex-Vasile** [comment]
> The trigger function is passed the triggering event, which has a function to get the triggering player ID. I have the fix written (and a test), just trying to get tests to run on my environment.

Worst case, push and open a PR, then the tests will run here. And you can figure out how to run the tests locally afterwards.
