### ISSUE TITLE
Engineered Explosives - Casting cost reflected in X = #, but not by counter

### ISSUE THREAD

**Issue by calkno** [magefree/mage#9067]
For Engineered Explosives, if you cast it with a value of X = 2, the actual counter on the card is "1" and when activated it is based off of the counter and not the X = 2.

**Comment by theelk801** [comment]
how many colors did you spend to cast it? it’s based on sunburst, not the X value

**Comment by calkno** [comment]
> how many colors did you spend to cast it? it’s based on sunburst, not the X value

2 red/blue

**Comment by theelk801** [comment]
are you sure you spent one of each and not two of the same?

**Comment by calkno** [comment]
> are you sure you spent one of each and not two of the same?

I used a basic island and a spire bluff canal. Thinking back, I don't recall it prompting me for color selection on the spire bluff

**Comment by theelk801** [comment]
alright, I’m guessing that you added two of the same color so I’m gonna close this unless you have evidence to the contrary

**Comment by Alex-Vasile** [comment]
> > are you sure you spent one of each and not two of the same?
> 
> 
> 
> I used a basic island and a spire bluff canal. Thinking back, I don't recall it prompting me for color selection on the spire bluff 

Shouldn't this be a bug by itself?  You should be prompted for a color choice on the spire bluff since it affects the outcome

**Comment by theelk801** [comment]
yeah that’s a good point, maybe we could flag certain mana costs to ignore automatic color choice
