### ISSUE TITLE
I can not register a new account

### ISSUE THREAD

**Issue by Kirbymain001** [magefree/mage#9077]
![image](https://user-images.githubusercontent.com/78285771/172504984-b3547cd0-9e62-4893-8030-6e3fc31a6e2c.png)
![image](https://user-images.githubusercontent.com/78285771/172505181-6fa13703-d9b8-41f8-a612-08a939975c08.png)
I am new to using Xmage so I don't know if I'm doing anything wrong, all I know is that I cant register an account and that the server being offline doesn't look like the problem

**Comment by JayDi85** [comment]
US server works without registration, just login with any user name. Try again.

**Comment by JayDi85** [comment]
Can you connect to other servers like de? If no then there are problem with firewall/antimalware -- try to disable it and check a connection.

**Comment by Kirbymain001** [comment]
> Can you connect to other servers like de? If no then there are problem with firewall/antimalware -- try to disable it and check a connection.

sorry, what is DE?

**Comment by Kirbymain001** [comment]
neverminded I think I found it.

**Comment by Kirbymain001** [comment]
And no I can not connect, I will see what I can do.

**Comment by Kirbymain001** [comment]
Ok, somehow, i dont know how, i got it to work, thank you for your help!
