### ISSUE TITLE
Eldrazi Temple Bug

### ISSUE THREAD

**Issue by mtgtester** [magefree/mage#908]
When casting Eldrazis using Eldrazi temples, XMage counts as a single mana rather than two

**Comment by LevelX2** [comment]
Only the automatic uses the first ability.
But if you tap the land before it works.
I'll have to check the automatic for this case.

**Comment by mtgtester** [comment]
You are correct, if I select the ability first (on the Eldrazi Temple) before I play the creature, I get the correct mana
