### ISSUE TITLE
When sacraficing Worldspine Wurm Clone a trigger happens that is hidden in the UI

### ISSUE THREAD

**Issue by Greeneye0** [magefree/mage#910]
Steps to duplicate
1. Have the following on the field
Jalira, Master polymorphist
Worldspine Wurm with Mirror Mockery Aura

2. Attack with Worldspine Wurm and allow Mirror Mockery to create a clone
3. Use Jalira's ability to sacrifice the clone

At this point a pick trigger ability comes up but there is no way to proceed. Player has to concede the game.

![image](https://cloud.githubusercontent.com/assets/11687236/7139953/2abf1926-e286-11e4-9f19-365a6ed6f45e.png)

Note: If you sacrifice the creature and not the token it does work as expected. 3 5/5 tokens appear and Jalira's ability occurs.

**Comment by LevelX2** [comment]
The problem seems to be caused by triggered abilities of tokens.
I can reproduce it but was not able yet to narrow down the reason why the abilities get lost on there way to the client.

**Comment by LevelX2** [comment]
Had another situation where this problem happens:
Frost Lynx enchanted with Mirror Mocker and Doubling Season in play.
So the two enters the battlefield trigger fire but are not shown in client.
