### ISSUE TITLE
[NCC] Change of Plans bugs

### ISSUE THREAD

**Issue by Susucre** [magefree/mage#9101]
[[Change of Plans]] is missing proper implementation for its conniving effect, not enforcing the following rule points:

> 701.47c If a permanent changes zones before an effect causes it to connive, its last known information is used to determine which object connived and who controlled it.
> 701.47d If multiple permanents are instructed to connive at the same time, the first player in APNAP order who controls one or more of those permanents chooses one of them and it connives. Then if any permanents remain on the battlefield which have been instructed to connive and have not done so, this process is repeated.

See https://github.com/magefree/mage/pull/9100 for an attempt at implementing [[Lethal Scheme]], the only other card so far having as an effect multiple conniving permanents.

**Comment by JayDi85** [comment]
Change of Plans implementation is fine. Whole spell will be fizzled due invalid target, so no connivie effect apply. I added LKI usage in ccb1a0aeedb6d95e6444ec3317140d2d1f68c6a9, but it's for better code style (any connivie related code must use lki).

**Comment by JayDi85** [comment]
hmm
