### ISSUE TITLE
Request: Disable bot games on the public beta server

### ISSUE THREAD

**Issue by sprangg** [magefree/mage#9110]
The public beta server (beta.xmage.today) is often suffering various performance-related issues and these could be alleviated by disabling bot games on the server (except draftbots).

Players can launch the local server if they want to play with bots, just like how it is with the non-beta xmage where the .de server doesn't allow bot games.

**Comment by JayDi85** [comment]
AI temporary disabled on beta server.

**Comment by sprangg** [comment]
Thank you! 🙏

This change should imo be permanent though, due to the reasons I outlined above.
