### ISSUE TITLE
Remote task error: can not find a free port for use. (try to close and restart a client app)

### ISSUE THREAD

**Issue by utterlymilked** [magefree/mage#9119]
Hello, i've had this error for over a year now but i felt like playing again so once again it became a problem. I'm not experienced with any such sort of thing so i don't really know what to do. Researching similar problems didn't solve it either. 

I can see the connection dialogue when i open the client app. I also happened to switch ISP's after the issue first presented itself and checking again now it has persisted, not sure if that's relevant at all

**Comment by JayDi85** [comment]
1. Make sure you can run and connect to local server (use launcher);
2. Disable all firewall and any antimalware tools and try connect to the server;

**Comment by utterlymilked** [comment]
I disabled my firewall and antivirus and attempted to launch and connect to the local server but i received the exact same message
