### ISSUE TITLE
Myrkul trigger caused bug

### ISSUE THREAD

**Issue by Gravelord-Anubis** [magefree/mage#9122]
Game exception occurred: java.lang.NullPointerException
Server version: 1.4.51-V4-beta5 (build: 2022-06-17 05:05)
mage.MageObject.retainAllEnchantmentSubTypes(MageObject.java:390)
mage.cards.m.MyrkulLordOfBonesEffect.lambda$apply$0(MyrkulLordOfBones.java:110)
mage.abilities.effects.common.CreateTokenCopyTargetEffect.apply(CreateTokenCopyTargetEffect.java:245)
mage.cards.m.MyrkulLordOfBonesEffect.apply(MyrkulLordOfBones.java:111)
mage.abilities.AbilityImpl.resolveMode(AbilityImpl.java:201)
mage.abilities.AbilityImpl.resolve(AbilityImpl.java:185)
mage.abilities.TriggeredAbilityImpl.resolve(TriggeredAbilityImpl.java:149)
mage.game.stack.StackAbility.resolve(StackAbility.java:89)
mage.game.GameImpl.resolve(GameImpl.java:1618)
mage.game.GameImpl.playPriority(GameImpl.java:1544)
mage.game.turn.Step.priority(Step.java:61)
mage.game.turn.Phase.playStep(Phase.java:184)
mage.game.turn.Phase.play(Phase.java:89)
mage.game.turn.Turn.play(Turn.java:132)
mage.game.GameImpl.playTurn(GameImpl.java:1042)
mage.game.GameImpl.play(GameImpl.java:952)
mage.game.GameImpl.start(GameImpl.java:928)
mage.server.game.GameWorker.call(GameWorker.java:34)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)

**Comment by jeffwadsworth** [comment]
[[Myrkul, Lord of Bones]]

**Comment by Tuxprogrammer** [comment]
fix for this is up in #9124

**Comment by jeffwadsworth** [comment]
Already fixed here as well.  Let me check yours.
