### ISSUE TITLE
Gond Gate causes itself and lands that ETB with it to enter untapped when they shouldn't always.

### ISSUE THREAD

**Issue by Grath** [magefree/mage#9125]
I just cast [[Scapeshift]] finding [[Gond Gate]] and a lot of other Gates. Because Gond Gate doesn't reference itself, it shouldn't apply the replacement effect unless it's already in play. I don't know if this is a Blood Moon situation where XMage can't do the interaction correctly or not, but if possible this should be adjusted.

**Comment by Alex-Vasile** [comment]
I'll look into. Should be identical to [[Archelos, Lagoon Mystic]] except it a restriction on the permanents it applies to

**Comment by Alex-Vasile** [comment]
In testing, I tested Scapeshift with several gates. Gond Gate does trigger cause itself to enter untapped, but the other gates still came in tapped. I couldn't reproduce the second part.
