### ISSUE TITLE
[Bug] A resolving copy of Approach of the Second Sun should make its controller gain 7 life

### ISSUE THREAD

**Issue by Susucre** [magefree/mage#9126]
[[Approach of the Second Sun]] is not working properly when it is being copied (by [[Fork]] for exemple).
It does not make its controller win the game (which is the right behavior), but still the copy should have its controller gain 7 life upon resolution.

**Comment by jeffwadsworth** [comment]
Strange.  The "else" statement in "Approach the Second Sun" is indeed reached but the life gain never happens.  No idea what is going on with this one.

**Comment by the-red-lily** [comment]
@jeffwadsworth I'm investigating and thought the same thing, until I realized the statement was reached within the CPU's "simulatePriority" logic. I think the computer player is merely predicting what might happen

**Comment by the-red-lily** [comment]
I found that in intelliJ I could add this to the breakpoint condition to disable breakpoints during the computer player's simulation:

`Arrays.stream(Thread.currentThread().getStackTrace()).noneMatch(s -> "simulatePriority".equals(s.methodName))`

And I found that the statement is actually not reached

**Comment by JayDi85** [comment]
@the-red-lily AI simulate all possible actions until empty stack and choose the best one action to play in real game. BTW you can also call `!game.isSimulation()` in the debug's filter to skip AI simulation breakpoints.

**Comment by the-red-lily** [comment]
Thanks, that's a simpler debug filter than what I used :)
