### ISSUE TITLE
[Abaddon the Despoiler] Error when entering battlefield;

### ISSUE THREAD

**Issue by Zenrei02** [magefree/mage#9138]
Pasting the error below as directed. Seems that this happens each time Abaddon enters the battlefield and applies Cascade to the cards in the player's hand. I tried searching to see if anyone has this issue. I thought it only affected cards with alternate casting costs like Living End (referenced below) and Chandra's Incinerator but it seems to apply to all cards in the player's hand.

I tried searching for this issue but nothing came up so I'm submitting it now. Hopefully this is of some help and not a repost of a known issue.

> Game exception occurred: java.lang.ClassCastException: mage.cards.l.LivingEnd cannot be cast to mage.game.stack.StackObject
> Server version: 1.4.51-V4-beta5 (build: 2022-06-17 05:05)
> mage.cards.a.AbaddonTheDespoilerPredicate.apply(AbaddonTheDespoiler.java:76)
> mage.filter.predicate.Predicates$AndPredicate.lambda$apply$0(Predicates.java:152)
> java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
> java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1359)
> java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
> java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
> java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
> java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
> java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
> java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
> java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
> java.util.stream.ReferencePipeline.allMatch(ReferencePipeline.java:454)
> mage.filter.predicate.Predicates$AndPredicate.apply(Predicates.java:152)
> mage.filter.FilterImpl.match(FilterImpl.java:38)
> mage.abilities.effects.GainAbilitySpellsEffect.apply(GainAbilitySpellsEffect.java:54)
> mage.abilities.effects.ContinuousEffectImpl.apply(ContinuousEffectImpl.java:115)
> mage.abilities.decorator.ConditionalContinuousEffect.apply(ConditionalContinuousEffect.java:100)
> mage.abilities.effects.ContinuousEffects.apply(ContinuousEffects.java:1097)
> mage.game.GameState.applyEffects(GameState.java:663)
> mage.game.GameImpl.applyEffects(GameImpl.java:1747)
> mage.players.PlayerImpl.moveCards(PlayerImpl.java:4542)
> mage.players.PlayerImpl.moveCards(PlayerImpl.java:4488)
> mage.game.stack.Spell.resolve(Spell.java:349)
> mage.game.GameImpl.resolve(GameImpl.java:1618)
> mage.game.GameImpl.playPriority(GameImpl.java:1544)
> mage.game.turn.Step.priority(Step.java:61)
> mage.game.turn.Phase.playStep(Phase.java:184)
> mage.game.turn.Phase.play(Phase.java:89)
> mage.game.turn.Turn.play(Turn.java:132)
> mage.game.GameImpl.playTurn(GameImpl.java:1042)
> mage.game.GameImpl.play(GameImpl.java:952)
> mage.game.GameImpl.start(GameImpl.java:928)
> mage.server.game.GameWorker.call(GameWorker.java:34)
> java.util.concurrent.FutureTask.run(FutureTask.java:266)
> java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> java.lang.Thread.run(Thread.java:748)

**Comment by the-red-lily** [comment]
I took a peek at this. Abaddon's predicate calls for a StackObject. But a similar card, ImotiCelebrantOfBounty, has a predicate which acts on MageObjects.

I'm assuming cards in hand are not StackObjects? That's probably causing the bug

**Comment by jeffwadsworth** [comment]
Saw that but was working on some other issue.  Take a look at a card like [[Maelstrom Nexus]].
