### ISSUE TITLE
Skip to certain item on the stack

### ISSUE THREAD

**Issue by the-red-lily** [magefree/mage#9140]
It would be nice to right click an item on the stack, and choose an option "Skip to this spell/ability/trigger". It would function the same as f10, but instead of skipping until stack is empty, it skips until the chosen item is on the top of the stack

**Comment by Alex-Vasile** [comment]
Duplicate of #8672

**Comment by the-red-lily** [comment]
Please re-open this suggestion, it is different from the mentioned one
