### ISSUE TITLE
Goaded creatures can only attack planeswalkers (if one is present)

### ISSUE THREAD

**Issue by stevedavidmusic** [magefree/mage#9148]
- If a creature is goaded and the opponent has at least one planeswalker, it is forced to only attack that planeswalker.

- If the opponent has multiple planeswalkers, it won't let you attack anything manually with the goaded creature because it doesn't let you choose what to attack when trying to attack with just the goaded creature. Selecting All Attack will let you select which planeswalker to attack, but it still won't let you attack the opponent directly with the goaded creature.

**Comment by the-red-lily** [comment]
Have you seen this issues with multiple planeswalkers, or just a specific one?

**Comment by stevedavidmusic** [comment]
Multiple planeswalkers.

**Comment by stevedavidmusic** [comment]
> Have you seen this issues with multiple planeswalkers, or just a specific one?

I've tested it with multiple planeswalkers.

**Comment by the-red-lily** [comment]
I tested with the latest code and was not able to replicate the issue, at least when I goaded my own creature. When I did so, I was able to attack the Player not their planeswalker

**Comment by Alex-Vasile** [comment]
@stevedavidmusic what version of XMage did you find this in?

**Comment by stevedavidmusic** [comment]
> @stevedavidmusic what version of XMage did you find this in?

The most recent beta version (and the previous one before that).

> I tested with the latest code and was not able to replicate the issue, at least when I goaded my own creature. When I did so, I was able to attack the Player not their planeswalker

I'm still able to replicate the issue. Here's a scenario where a 3/3 Beast token is 
goaded. When I try to select something to attack, none of the planeswalkers are highlighted.

<img width="1280" alt="Goaded Creature" src="https://user-images.githubusercontent.com/45299811/176252850-ad0a8f49-bf5c-4f1f-888e-6bd0d38f500a.png">

When I'm selecting what to attack with a non-goaded creature, the planeswalkers are highlighted:

<img width="1280" alt="Non-Goaded Creature" src="https://user-images.githubusercontent.com/45299811/176252892-801d7df1-3ba1-4b9e-b45f-68f7e18148ec.png">

Every time I've goaded a creature, it's been off of the Undercity dungeon if that matters.

**Comment by jeffwadsworth** [comment]
[[Undercity]]
