### ISSUE TITLE
Armix, Filigree Thrasher BUGGED

### ISSUE THREAD

**Issue by EllNubNub** [magefree/mage#9154]
The partner commander Armix, Filigree Thrasher seems to be bugged and gives the creature it targets with its -x/-x ability a greater number than the artifacts you control/in your graveyard. I was not able to confirm what the conditions for the additional -x/-x amount since the game ended too soon after i discovered the bug. it could be taking opponents artifacts into account or something else entirely im not sure.

**Comment by PurpleCrowbar** [comment]
[[Armix, Filigree Thrasher]]

**Comment by the-red-lily** [comment]
I took a look at the source code for that card, I don't see any glaring issues. Do you have any time to try to recreate the scenario and get a screengrab?

**Comment by EllNubNub** [comment]
Yeah i just got home I can play the card some more and see if i encounter it again.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by EllNubNub** [comment]
![xmage armis bug](https://user-images.githubusercontent.com/30028974/175788100-43892abe-322c-40eb-a163-3909eb9bb885.png)
ok so it happened again, in the image mairsil ends up getting -4/-4 which is the combined number of artifacts on the battlefield, it should only count mine. and there were no artifacts in any graveyard.

**Comment by the-red-lily** [comment]
Thanks for the extra detail, I'll get to debugging

**Comment by the-red-lily** [comment]
This seems to be fixed in the upcoming version. I replicated the issue on the released version but not on the current developer version. Here's my test with the up to date code (-2/-2 as I only controlled 2 of the 4 artifacts on battlefield)
![Armix](https://user-images.githubusercontent.com/82073293/175843759-0e1552d6-9f2a-4213-9fbb-e2be95e4deb6.PNG)

**Comment by the-red-lily** [comment]
Hmm now I see that the last release was  Sep 05, 2021. @JayDi85 I saw you released the last one, what's the process for a release and when might the next release be?

**Comment by jeffwadsworth** [comment]
The beta is essentially the "release" nowadays.  Lots of work in regards to official releases.

**Comment by jeffwadsworth** [comment]
This card works fine for me.

**Comment by the-red-lily** [comment]
> The beta is essentially the "release" nowadays. Lots of work in regards to official releases.
Is there any way we can reduce the work for official releases?

**Comment by JayDi85** [comment]
@the-red-lily just wait, it's almost ready.
