### ISSUE TITLE
Removing counters from a permanent as a cost should not target

### ISSUE THREAD

**Issue by rockydirtbag** [magefree/mage#9159]
Activating [[Power Conduit]], [[Sage of Fables]] or similar abilities that require you to remove a counter from a permanent you control as part of the cost don't target the permanent, so you should be able to remove a counter from a permanent with shroud. That is not the case right now.

**Comment by jeffwadsworth** [comment]
It will be fixed on Monday.  No doubt there may be other instances of this kind of errant targeting.
