### ISSUE TITLE
Luxior, Giada's Gift does not equip to planeswalkers

### ISSUE THREAD

**Issue by cashmoneyhoes** [magefree/mage#9162]
I tried equipping [[Luxior, Giada's Gift]] to my [[Liliana of the Veil]], which has 3 loyalty counters, and it doesn't equip. I attempted to do this twice, and it did not work either time.
![image](https://user-images.githubusercontent.com/90292347/175836114-393a0574-274b-40be-b3f7-4de19ade790e.png)

**Comment by PurpleCrowbar** [comment]
Fixed in 48a96e5e8f9b59a40d5f057da0249fe0dd112b6e, confirmed working on latest build. Will work fine on next beta update.
