### ISSUE TITLE
[CLB] Volo, Itinerant Scholar BUGGED

### ISSUE THREAD

**Issue by TheLobsterMan** [magefree/mage#9175]
Card 

Volo, Itinerant Scholar

shows unintended behavior, specifically the triggered ability of the unique artifact he creates:
_"Whenever you cast a creature spell, note one of its creature types that hasn't been noted for this artifact"_

When triggered, the resulting list of creature types is apparently dynamically altered, and therefore always excludes the creature types present in the creature spell that triggered it (For example, the "Vedalken"-subtype is present when playing a "Human Wizard" creature, but is absent when playing a "Vedalken Wizard"-creature. Likewise, the "Human"-Subtype is only present when the creature spell in question is NOT of the human type). Since the ability however requires to pick a subtype that is present in the spell, the card is effectively broken, since a matching subtype can never be selected.

Hypothesis: The loaded list is probably dynamically altered to exclude all types already noted on the artifact, but the reference might wrongly point to the triggering permanent, instead of the triggered one.

_(First Bug report here, sorry if i made any mistakes)_

**Comment by Alex-Vasile** [comment]
[[Volo, Itinerant Scholar]]

Thanks for the report.
