### ISSUE TITLE
[CLB] Delayed Blast Fireball BUGGED

### ISSUE THREAD

**Issue by TheLobsterMan** [magefree/mage#9180]
Delayed Blast Fireball will consistently throw the following exception whenever a copy of the card is created on the stack, and then resolves:

Game exception occurred: java.lang.NullPointerException
Server version: 1.4.51-V4-beta6 (build: 2022-06-24 13:26)
java.util.Objects.requireNonNull(Objects.java:203)
java.util.Optional.<init>(Optional.java:96)
java.util.Optional.of(Optional.java:108)
mage.cards.d.DelayedBlastFireballValue.calculate(DelayedBlastFireball.java:59)
mage.abilities.effects.common.DamagePlayersEffect.apply(DamagePlayersEffect.java:74)
mage.abilities.AbilityImpl.resolveMode(AbilityImpl.java:201)
mage.abilities.AbilityImpl.resolve(AbilityImpl.java:188)
mage.game.stack.Spell.resolve(Spell.java:241)
mage.game.GameImpl.resolve(GameImpl.java:1618)
mage.game.GameImpl.playPriority(GameImpl.java:1544)
mage.game.turn.Step.priority(Step.java:61)
mage.game.turn.Phase.playStep(Phase.java:184)
mage.game.turn.Phase.play(Phase.java:89)
mage.game.turn.Turn.play(Turn.java:132)
mage.game.GameImpl.playTurn(GameImpl.java:1042)
mage.game.GameImpl.play(GameImpl.java:952)
mage.game.GameImpl.start(GameImpl.java:928)
mage.server.game.GameWorker.call(GameWorker.java:34)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)

Probably an issue with the fact that it checks whether the spell was cast from exile, since a copy on the stack isnt cast from anywhere.

**Comment by the-red-lily** [comment]
For some reason, copying a spell is counting as a zone change. Therefore when we try to get the source of damage, we are getting null. Investigating

**Comment by the-red-lily** [comment]
On AbilityImpl.java line 1268:

`getSourceObjectZoneChangeCounter() == game.getState().getZoneChangeCounter(getSourceId())`

In a copied spell, the former is returning 2, while the latter returns 3.

For a non-copied spell, both are 2.

**Comment by xenohedron** [comment]
fixed by deb29c0
