### ISSUE TITLE
Travis CI: Owner magefree does not have enough credits

### ISSUE THREAD

**Issue by the-red-lily** [magefree/mage#9185]
Seen here: https://app.travis-ci.com/github/magefree/mage/requests

Who currently pays for magefree Travis CI access? Is there a way for me to contribute? Or do we have a way of getting free credits?

**Comment by Alex-Vasile** [comment]
> Seen here: https://app.travis-ci.com/github/magefree/mage/requests
> 
> 
> 
> Who currently pays for magefree Travis CI access? Is there a way for me to contribute? Or do we have a way of getting free credits?

If yo I know anything about github actions, there is this PR that still needs work for us to use GitHub actions instead.

#8248

**Comment by weirddan455** [comment]
I think we're getting some number of free credits from Travis CI for being an open source project.  It says we were issued some credits on June 15 but now we're out.  I think @JayDi85 usually requests more when we run out.  I'm not sure how to do that myself.  May need some admits rights on Travis CI that I don't have or I'm just not seeing the button.

**Comment by JayDi85** [comment]
Yes, I send request. Will be added in 1-2 days.

**Comment by xenohedron** [comment]
@JayDi85 I think this needs to be addressed again

**Comment by JayDi85** [comment]
Send request, will be added in 1 day

**Comment by xenohedron** [comment]
Just ran out again @JayDi85 . Anything we can do to help with this?

**Comment by Susucre** [comment]
If that is a $ cost that increased significantly with all my recent PRs, I'd be more than happy to participate. (provided some transparency on the monetary cost for the CI)

**Comment by JayDi85** [comment]
@Susucre nope, it's not a new tests -- it increase run time by 5-10% only. There are too many PRs and single commits, so credit points run out too fast. I send request so credit points will be added soon.

![shot_230820_063657](https://github.com/magefree/mage/assets/8344157/fd819c6b-8c17-4f37-9341-ee19710d9f20)

**Comment by Susucre** [comment]
Yeah sorry for that, did a lot of 1card PR for the new set.

**Comment by JayDi85** [comment]
That's ok for new MTG releases
