### ISSUE TITLE
DEV: "Quick start commander" needs multiplayer

### ISSUE THREAD

**Issue by Alex-Vasile** [magefree/mage#9199]
The current implementation of the "Quick start commander" button starts a 2 player match. However, the format is very much a multiplayer one. Having the quick setup be single-player makes it much harder to test many of the interactions and bugs.

**Comment by JayDi85** [comment]
Best version:
- Single for 2x commander (instead dual match), e.g. "test x2 game";
- Multiple for 4x commander with limited attack range, e.g. "test x4 game";

Reason: 2x commander game is same as current dual match but gives additional options for testing (workable commander zone);
