### ISSUE TITLE
NullPointerException when goaded creature is destroyed

### ISSUE THREAD

**Issue by baum314nk** [magefree/mage#9205]
We experienced a NullPointerException when a creature goaded with [[Karazikar, the Eye Tyrant]] was destroyed by [[Supreme Verdict]]. Karazikar was also to be removed by the same effect, but the controlling player sat behind the one controlling the goaded creature.
The exception originated from GoadTargetEffect class

**Comment by Alex-Vasile** [comment]
1. Do you have the full error log?
2. "Karazikar was also to be removed by the same effect, but the controlling player sat behind the one controlling the goaded creature." Do you mean that Karazikar was outside of the range of influence of the Supreme Verdict?

**Comment by Alex-Vasile** [comment]
Closed in da10b6397ccf36e0fe6f5e8630bb2f3499128196
