### ISSUE TITLE
DEV: Get Mtg Card Fetch Bot working on PRs

### ISSUE THREAD

**Issue by Alex-Vasile** [magefree/mage#9207]
The Card fetch bot doesn't work on PRs, and produces the following error:
```
Run ldeluigi/mtg-fetch-action@v1
  with:
    github-token: ***
Error: Resource not accessible by integration
```
E.g. https://github.com/magefree/mage/runs/7162460668?check_suite_focus=true

**Comment by ldeluigi** [comment]
I know that it works on PR comments. I don't know if it works on PR main body text tho... but it's weird because PRs and issue are basically the same thing

**Comment by ldeluigi** [comment]
In other words I couldn't reproduce it
