### ISSUE TITLE
GUI: Migrate from Netbeans 8 .form files, restore missing

### ISSUE THREAD

**Issue by Alex-Vasile** [magefree/mage#9211]
Many of the UIs are build using Netbeans 8. A VERY old version.

NetBeans must be a main GUI editor (95% of xmage forms written with it)

TODO
- [x] Figure what what format to move everything to (newer Netbean, IntelliJ, some other)
- [ ] Restore missing form files for some GUI components;
- [ ] Make forms openable by NetBeans (some require fixes, some migrate from IntelliJ to NetBeans);

**Comment by JayDi85** [comment]
No needs in restore old form files (it’s netbeans only feature and depend on it, also do not support GUI sizing). Must use runtime creation code with layouts. NetBeans can be used as code template how to setup or use layout.

There are few heavy and complex forms — too heavy for runtime:
* Connection dialog
* Preferences dialog
* New table and new tourney dialogs

All other form files are not necessary
