### ISSUE TITLE
[AFC] Nihiloor does not return creature if it changes state e.g. God becomes an enchantment

### ISSUE THREAD

**Issue by dashosa** [magefree/mage#9223]
Not sure if this is supposed to happen:

Nihilor takes Iroas
Nihilor dies
Nihilor does not return Iroas who is not a creature but an enchantment

**Comment by Alex-Vasile** [comment]
[[Nihiloor]]

**Comment by Alex-Vasile** [comment]
This is a bug, Iroas should be returned.

**Comment by Alex-Vasile** [comment]
[[Iroas, God of Victory]]

**Comment by awjackson** [comment]
I don't think this is actually a bug. Target legality is normally checked when first choosing the target and checked again when an ability is about to resolve. It isn't checked continuously except specifically for Auras.

For example, if you cast an instant that said "Target Goblin gets +2/+2 until end of turn" and it successfully resolved, and then after it resolved someone used their [[Amoeboid Changeling]] to make the affected creature stop being a Goblin, the +2/+2 boost wouldn't go away.

**Comment by Alex-Vasile** [comment]
I don't think this is an Iroas problem, I think Nihiloor isn't implemented right. It has the same issue when using a plain creature as the target.

**Comment by awjackson** [comment]
Deleted previous comment since I misunderstood the issue. Yeah, Nihiloor is currently never returning control no matter what the targetted creature is.
