### ISSUE TITLE
Xmage Launcher Issue "Xmage not found"

### ISSUE THREAD

**Issue by chili01** [magefree/mage#924]
I am unable to play or set up because I can't get past the Launcher.

I definitely have Java installed.

Here's my log:

XMage Launcher version installed:  0.3.1
XMage Launcher version available:  0.3.1
Removing previous versions ...
Java version installed:  1.7.0_75
Java version available:  1.7.0_75
XMage version installed:  
XMage version available:  1.3.0.dev2015-03-14v8 (2015-04-18)
XMage not found
Downloading XMage from http://bit.ly/XMage2015-03-14v8
Removing previous versions ...
Installing XMage ...Java version installed:  1.7.0_75
Java version available:  1.7.0_75
XMage version installed:  
XMage version available:  1.3.0.dev2015-03-14v8 (2015-04-18)
XMage not found

**Comment by LevelX2** [comment]
Which OS and version do you use?
Did the launcher work before on this system?

Can you show the content of the *installed.properties* file in launcher directory?
Does the content of the file *xmage_launcher.log*  in launcher directory show anything more?

**Comment by domajm32** [comment]
I am having the same issue... here is my log
Downloading Java from http://download.oracle.com/otn-pub/java/jdk/7u75-b13/jre-7u75-windows-x64.tar.gz
Installing Java ...Done
Downloading XMage from http://bit.ly/XMage2015-03-14v8
Installing XMage ...Java version installed:  1.7.0_75
Java version available:  1.7.0_75
XMage version installed:  
XMage version available:  1.3.0.dev2015-03-14v8 (2015-04-18)
XMage not found
Downloading XMage from http://bit.ly/XMage2015-03-14v8
Removing previous versions ...
Installing XMage ...Java version installed:  1.7.0_75
Java version available:  1.7.0_75
XMage version installed:  
XMage version available:  1.3.0.dev2015-03-14v8 (2015-04-18)
XMage not found

**Comment by zetetic6** [comment]
I'm having the same exact problem described here as well.  I'm using Windows 7 Home Premium 64-Bit.  The Launcher has not worked before for me. Any help would be much appreciated.
Here is what my installed.properties file says:

#---XMage Properties---
#Tue Apr 21 13:24:48 EDT 2015
xmage.launcher.version=0.3.1
java.version=1.7.0_75
xmage.client.console=true
xmage.client.javaopts=-Xms256m -Xmx512m -XX\:MaxPermSize\=384m -XX\:+UseConcMarkSweepGC -XX\:+CMSClassUnloadingEnabled
xmage.home=http\://xmage.info/xmage
xmage.version=
xmage.server.console=true
xmage.server.javaopts=-Xms256M -Xmx1G -XX\:MaxPermSize\=384m
xmage.torrent.downrate=0
xmage.torrent.uprate=50
xmage.torrent.use=false

And here is what the xmage_launcher log says:

ERROR 2015-04-21 13:22:50,194 Error:                                                                                     =>[SwingWorker-pool-1-thread-2] XMageLauncher$UpdateTask.updateXMage
java.io.IOException: The system cannot find the path specified
	at java.io.WinNTFileSystem.createFileExclusively(Native Method)
	at java.io.File.createNewFile(Unknown Source)
	at com.xmage.launcher.DownloadTask.unzip(DownloadTask.java:186)
	at com.xmage.launcher.XMageLauncher$UpdateTask.updateXMage(XMageLauncher.java:777)
	at com.xmage.launcher.XMageLauncher$UpdateTask.doInBackground(XMageLauncher.java:694)
	at com.xmage.launcher.XMageLauncher$UpdateTask.doInBackground(XMageLauncher.java:680)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by LevelX2** [comment]
> java.io.IOException: The system cannot find the path specified

I see here two possible reasons for the problem.
1) You use the launcher in a directory where the user does not have full access to write / edit files.
2) You use the launcher in a directory that has some characters in the path (like blanks) that may cause problems.

But I guess 1) is more likely.

Try to move the launcher to another directory (maybe a directory xmage in the home directory of the user)  and try again to install xmage with the launcher.

**Comment by Fishfosh** [comment]
I'm having this same problem, also on Windows 7 64-bit, and after checking this thread I've tried installing to 3 different directories now but with the same result every time.  I am absolutely positive that I should have full edit/write privileges to at least 2 of them, and none contain unusual characters or blanks.  The latest attempt was in a new folder (renamed to "Xmage") in my home directory.

Properties file:
#---XMage Properties---
#Wed Apr 22 02:43:41 EDT 2015
xmage.launcher.version=0.3.1
java.version=1.7.0_75
xmage.client.console=true
xmage.client.javaopts=-Xms256m -Xmx512m -XX\:MaxPermSize\=384m -XX\:+UseConcMarkSweepGC -XX\:+CMSClassUnloadingEnabled
xmage.home=http\://xmage.info/xmage
xmage.version=
xmage.server.console=true
xmage.server.javaopts=-Xms256M -Xmx1G -XX\:MaxPermSize\=384m
xmage.torrent.downrate=0
xmage.torrent.uprate=50
xmage.torrent.use=false


Launcher log file:
ERROR 2015-04-22 02:44:37,006 Error:                                                                                     =>[SwingWorker-pool-1-thread-2] XMageLauncher$UpdateTask.updateXMage
java.io.IOException: The system cannot find the path specified
	at java.io.WinNTFileSystem.createFileExclusively(Native Method)
	at java.io.File.createNewFile(Unknown Source)
	at com.xmage.launcher.DownloadTask.unzip(DownloadTask.java:186)
	at com.xmage.launcher.XMageLauncher$UpdateTask.updateXMage(XMageLauncher.java:777)
	at com.xmage.launcher.XMageLauncher$UpdateTask.doInBackground(XMageLauncher.java:694)
	at com.xmage.launcher.XMageLauncher$UpdateTask.doInBackground(XMageLauncher.java:680)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)


Seems pretty much the same as above, but I figured I'd post them for the sake of completeness.

**Comment by LevelX2** [comment]
Hmm, I hope I found the cause of the problem.
I made a new launcher version XMageLauncher-0.3.2.jar with a small fix.
Please test if it helps with this problem.

https://drive.google.com/file/d/0B69TXnHQFJaySWZmQzAxLUhQTDg/view

If not the Launcher log file would be of interest because at my curretn location I can't test it myself.

**Comment by LevelX2** [comment]
I updated the Launcher to version 0.33 it should automatically update the old launcher on start.
Please test if this solves your problems.

**Comment by Fishfosh** [comment]
Just tried it and the problem was solved for me.  Thank you.

**Comment by zetetic6** [comment]
That new launcher seems to have worked for me too.  Thank you very much for
your help.
