### ISSUE TITLE
cave of the frost dragon bug

### ISSUE THREAD

**Issue by catman123456** [magefree/mage#9241]
I have two lands in play but it comes in play tapped. [[cave of the frost dragon]]

![image](https://user-images.githubusercontent.com/64045003/177788442-6f3bd03a-2307-43a5-acc8-9d2799ed22d4.png)

**Comment by PurpleCrowbar** [comment]
Seems to be working as intended, no?

> If you control two or more other lands, Cave of the Frost Dragon enters the battlefield tapped.

**Comment by catman123456** [comment]
ah I guess so.
