### ISSUE TITLE
Morph that loses abilities from Minimus Containment stays a creature

### ISSUE THREAD

**Issue by Jipsu** [magefree/mage#9247]
Morph becomes a treasure but also stays a 2/2 creature if enchanted with [[Minimus Containment]]. Expected outcome should probably be to become a noncreature.

![unknown](https://user-images.githubusercontent.com/22531697/178104984-486beeb3-7a30-40ce-8a1c-3b6e64269b9e.png)

**Comment by xenohedron** [comment]
Needs testing with #11689
