### ISSUE TITLE
expressive iteration null

### ISSUE THREAD

**Issue by simply-pvm** [magefree/mage#9248]
Game exception occurred: java.lang.NullPointerException
Server version: 1.4.51-V4-beta7 (build: 2022-07-09 15:21)
mage.target.TargetImpl.tryToAutoChoose(TargetImpl.java:665)
mage.player.human.HumanPlayer.choose(HumanPlayer.java:730)
mage.cards.e.ExpressiveIterationEffect.apply(ExpressiveIteration.java:99)
mage.abilities.AbilityImpl.resolveMode(AbilityImpl.java:201)
mage.abilities.AbilityImpl.resolve(AbilityImpl.java:188)
mage.game.stack.Spell.resolve(Spell.java:241)
mage.game.GameImpl.resolve(GameImpl.java:1618)
mage.game.GameImpl.playPriority(GameImpl.java:1544)
mage.game.turn.Step.priority(Step.java:61)
mage.game.turn.Phase.playStep(Phase.java:184)
mage.game.turn.Phase.play(Phase.java:89)
mage.game.turn.Turn.play(Turn.java:132)
mage.game.GameImpl.playTurn(GameImpl.java:1042)
mage.game.GameImpl.play(GameImpl.java:952)
mage.game.GameImpl.start(GameImpl.java:928)
mage.server.game.GameWorker.call(GameWorker.java:34)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)

**Comment by Alex-Vasile** [comment]
Until next beta. Either :
1. Disable auto-choosing
2. Change auto-choose level to "All"

Closed in 7ca7e10d8058a1806fad36825990d33763bcf0c3.
