### ISSUE TITLE
Dryad of the Ilysian Grove slows the game down a lot (Too many ManaOptions)

### ISSUE THREAD

**Issue by Alex-Vasile** [magefree/mage#9259]
[[Dryad of the Ilysian Grove]]

**Comment by Alex-Vasile** [comment]
This seems to be caused by the fact that it adds a different mana ability for each color, e.g:
{T}: Add {W}
{T}: Add {R}
etc.

When all 5 are added this is equivalent to having a single mana ability that says: "{T}: Add 1 mana of any color".

I can imagine that there may some cards which interact which specific color mana abilities. But I don't know any off the time off my head. i.e. a coloured version of [[Forsaken Monument]]. Those such a card exist?

The same issue impacts [[Prismatic Omens]]. This is the same issue as the original implementation of Cascading cataracts (see #7649).

Changing `BecomesAllBasicsControlledEffect` to add a single `AnyColorManaAbility` instead of (at most) 5 different abilities (one for each WUBRG). The number of possible mana combinations for 2 of each of (Plains, Island, Swamp, Mountain, Forest, and Desert for a total of 12 lands) drops from ~4000 to 3 which is the correct answer (2 {C} +  10{ANY}, 1 {C} + 11{ANY}, and 12{ANY}).

**Comment by JayDi85** [comment]
Its not a real fix — its just hide the real problem: too much mana options in some use cases.

**Comment by JayDi85** [comment]
There are possible many mana permanents on battlefield, many ability gain effects and etc -- that's all adds additional mana options and generates many combinations.

**Comment by JayDi85** [comment]
I think "wubrg to any" replacing was part of the `removeDuplicated` code (see `getMoreValuableMana`). If not then it can be there (search wubrg and replace it with single any). I mean a real fix must be in mana optimization's code, not in the ability's code.

![shot_220713_002010](https://user-images.githubusercontent.com/8344157/178587774-3c6d7855-16a5-4e4f-8447-57a7480562ea.png)

**Comment by Alex-Vasile** [comment]
> I think "wubrg to any" replacing was part of the `removeDuplicated` code (see `getMoreValuableMana`). If not then it can be there (search wubrg and replace it with single any). I mean a real fix must be in mana optimization's code, not in the ability's code.
> 
> ![shot_220713_002010](https://user-images.githubusercontent.com/8344157/178587774-3c6d7855-16a5-4e4f-8447-57a7480562ea.png)

It was not. 
A) That operation IS the reason that having many mana options is expensive.
B) A WUBRG to ANY operation there would require anywhere between 1 and 4 searches of all remaining mana option for each mana inside mana option. This would be computationally expensive even if getMoreValuableMana was cheap, which it's not.

**Comment by Alex-Vasile** [comment]
> a real fix must be in mana optimization's code, not in the ability's code.

No matter how efficient of an algorithm we use for removing mana options, it will not be more efficient that simply not creating them in the first place. Whenever possible, like here, we should also try to optimize each ability.

**Comment by e314** [comment]
{Any} will cause choice issues with cards such as [[Ogre Savant]], [[Omnath, Locus of Mana]], ...

**Comment by Alex-Vasile** [comment]
> {Any} will cause choice issues with cards such as Ogre Savant, Omnath, Locus of Mana, ...

Both of those kinds of effects will work properly. Ogre Savant will currently require you to float the mana as it will autochoose for you. #9173 will fix that part.

Omnath will also work since when you tap to get mana from a "{T}: add one mana of any color" ability it will ask you for which color you want. You can still choose green and float it properly.
