### ISSUE TITLE
Increase beta stability now that it's VERY ACTIVE...?

### ISSUE THREAD

**Issue by stevedavidmusic** [magefree/mage#9262]
More of a feature request than a bug. Now that the beta has become more active, I was wondering if there were anyways to make it more stable. For example, I asked if there was a daily reset like DE server has, and I was told that it doesn't?

**Comment by JayDi85** [comment]
Mail me to jaydi85@gmail.com for beta server restart. I restart it manually once per few days or by request.

**Comment by sprangg** [comment]
Could you please enable the daily reset? In my opinion there are only upsides in it:
- Increased stability
- Predictable reset pattern that can be anticipated by players
- No manual restart work needed by you

For extra familiarity for players, you could make the beta server reset happen the same time as .de resets, which is 8:00 CET iirc.

**Comment by sprangg** [comment]
> XMage's servers doesn't needs an everyday restart (it's much more stable than few years ago). It's just a protection from the freezed/broken server (if something goes wrong then it will be auto-fixed in 24 hours max).

Ok, nevermind then! Thanks for the info.
