### ISSUE TITLE
Faldorn trigger is wrong

### ISSUE THREAD

**Issue by alfreedom96** [magefree/mage#9265]
Faldorn, Dread Wolf Herald doesn't trigger, and so create a wolf, when i cast cards from exile but when my opponents cast them

**Comment by alfreedom96** [comment]
Still most of the times the trigger doesn't happen

**Comment by Alex-Vasile** [comment]
> Still most of the times the trigger doesn't happen

You won't see any changes on the beta until a new beta version is released.

**Comment by alfreedom96** [comment]
Oh, I didn't know. So when?

**Comment by Alex-Vasile** [comment]
> Oh, I didn't know. So when?

Don't know, I'm not in charge of releasing updates.
