### ISSUE TITLE
[GUI, Refactor] Certain restriction effects should show a card hint, not a prompt

### ISSUE THREAD

**Issue by Alex-Vasile** [magefree/mage#9275]
The implementation of certain restriction effect should be changed from "show pop-up to user saying X can't be done" to "show hint on card".

Originally described as: "If it's day and you have a transformed werewolf with nightbound, immerwolf creates a million dialogue boxes that you have to click through every time something happens."

In this case, the affected cards should simply get a hint saying they can't transform and then not transform them. Prompted the user for a pop-up to dismiss feels really bad, and is *incredibly* annoying.

**Comment by awjackson** [comment]
Fixed by #9709
