### ISSUE TITLE
ComputerPlayer.chooseTarget does not implement all TargetTypes

### ISSUE THREAD

**Issue by SofiaAViesti** [magefree/mage#9276]
When playing against computer I kept getting the rollback error that asked me "Please send this in our issues page on github" so here I am:

Game exception occurred: java.lang.IllegalStateException: Target wasn't handled in computer's chooseTarget method: mage.target.common.TargetActivatedOrTriggeredAbility
Server version: 1.4.51-V4-beta7 (build: 2022-07-09 15:21)
mage.player.ai.ComputerPlayer.chooseTarget(ComputerPlayer.java:1071)
mage.target.TargetImpl.chooseTarget(TargetImpl.java:326)
mage.target.Targets.chooseTargets(Targets.java:90)
mage.abilities.AbilityImpl.activate(AbilityImpl.java:372)
mage.players.PlayerImpl.triggerAbility(PlayerImpl.java:1532)
mage.game.GameImpl.checkTriggered(GameImpl.java:2046)
mage.game.GameImpl.checkStateAndTriggered(GameImpl.java:2005)
mage.game.GameImpl.playPriority(GameImpl.java:1513)
mage.game.turn.Step.priority(Step.java:61)
mage.game.turn.Phase.playStep(Phase.java:184)
mage.game.turn.Phase.play(Phase.java:89)
mage.game.turn.Turn.play(Turn.java:132)
mage.game.GameImpl.playTurn(GameImpl.java:1042)
mage.game.GameImpl.play(GameImpl.java:952)
mage.game.GameImpl.start(GameImpl.java:928)
mage.server.game.GameWorker.call(GameWorker.java:34)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)

PS: Any updates on when we are getting the release of Phabine/Syrix/Gluntch/LGBT Secret Lair arts?

**Comment by Alex-Vasile** [comment]
What was on the board?

**Comment by SofiaAViesti** [comment]
I don't remember all of them, it was kinda late game. I had Amareth the Lustrous and Inexorable Tide on my side. My opponents were Gavi and Dhalsim (the secret lair street fighter guy). Whenever I tried to play anything off my hand, the rollback happened.

**Comment by SofiaAViesti** [comment]
Oh I see... Damn I really don't remember. But knowing those decks, it could've been Crystalline Resonance from Gavi, or maybe Swarmyard from Dhalsim. I really should've taken a print of the table, sorry about that

**Comment by Alex-Vasile** [comment]
I'll take a look at those. Could you make note of which decks you gave them in case I need to just play against the decks until I figure out what happened.

**Comment by SofiaAViesti** [comment]
The decks are these two:
[decks- Gavi and Dhalsim.zip](https://github.com/magefree/mage/files/9124620/decks-.Gavi.and.Dhalsim.zip)
balwip/
sorry for the delay responding, best of luck trying to figure the error out! I appreciate the effort, and sorry again for not being much help :(

**Comment by Alex-Vasile** [comment]
> The decks are these two:
> [decks- Gavi and Dhalsim.zip](https://github.com/magefree/mage/files/9124620/decks-.Gavi.and.Dhalsim.zip)
> sorry for the delay responding, best of luck trying to figure the error out! I appreciate the effort, and sorry again for not being much help :(

Just and Fyi for you, it's actually [[Nimble Obstructionist]]. The AI does not yet have code for choose targets for those kinds of effects.
