### ISSUE TITLE
[CLB] Wrathful Red Dragon seem bugged

### ISSUE THREAD

**Issue by rockydirtbag** [magefree/mage#9278]
The trigger from [[Wrathful Red Dragon]] seems to deal damage equal to the total damage the source has dealt. In this example, [[Blasphemous Act]] was cast, dealing 13 damage to 7 creatures each, including another dragon ([[Vrondiss, Rage of Ancients]]). The target then was dealt 91 damage instead of 13. 
Additionally, the ability should have triggered twice, once for Vrondiss and once for the Wrathful Red Dragon itself (both controlled by the same player).
![wrathful](https://user-images.githubusercontent.com/2265791/179354022-53e04634-b838-43af-9f5b-50dd78f9c39a.png)

**Comment by Alex-Vasile** [comment]
A) Should there be two wrathful dragon triggers (1 for itself and one for Vrondiss)
B) I am not sure that either should trigger since the text says "Whenever a Dragon you control is dealt damage, **it** deals"" But in this case the dragons (Wrathful and Vrondiss) would both be dead by the time the ability resolves.

**Comment by rockydirtbag** [comment]
Wrathful Red Dragon's ability triggers whenever any dragon controlled by the same player is dealt damage. This includes itself, and in the example above also Vrondiss, which is a dragon as well, and both of them are dealt 13 damage at the same time. That's why there should be two triggers on the stack.

I am very certain that these triggers should both deal 13 damage each in the example situation, regardless of whether the creatures are still on the battlefield. (Otherwise [[Stalking Vengeance]] would be a very bad card 😜)
