### ISSUE TITLE
descent into avernus trigger is wrong

### ISSUE THREAD

**Issue by alfreedom96** [magefree/mage#9279]
descent into avernus trigger is wrong because it creates all treasures under its owner control.

**Comment by Alex-Vasile** [comment]
I am also unsure about the interaction with [[Xorn]]. Currently, Descent is creating X tokens one token at a time. Should Descent be creating the X tokens as on instance?

**Comment by Alex-Vasile** [comment]
Looking at similar cards, they should be created all at once.
