### ISSUE TITLE
Cannot connect to a public hosted server

### ISSUE THREAD

**Issue by J1HN** [magefree/mage#9286]
Hi, i'm trying to run a public server hosted on a debian vps cloud machine.
 I've got the server running, i can't find a way to make the client connect to it, despite trying ~ everything.

my configuration is as follow:
my server is exposed via: my_domain.xyz
both client and server are running under jdk8: https://www.oracle.com/fr/java/technologies/javase/javase8-archive-downloads.html
server-side cfg:
xmage server start arguments: 
```sh
java8 -Xms256M -Xmx512M -Dfile.encoding=UTF-8 -Djava.net.preferIPv4Stack=true -Djava.security.policy=./config/security.policy -Dlog4j.configuration=file:./config/log4j.properties -jar ./lib/mage-server-1.4.50.jar
```

xmage server config:
```xml
   <server serverAddress="my_domain.xyz"
            serverName="my_domain.xyz"
            port="17171"
            secondaryBindPort="17179"
            backlogSize="200"
            numAcceptThreads="2"
            maxPoolSize="300"
            leasePeriod="12000"
```

the xmage starts log:
```
Started MAGE server - listening on my_domain.xyz:17171/?serializationtype=jboss&maxPoolSize=300 =>[main] Main.main 
```

firewal is set to accept both 17171 and 17179 input traffic
iptables -L:
```sh
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:17171
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:17179
```
hosts and hostname cfg is as follow:

/etc/hostname
`my_domain`

/etc/hosts
```sh
127.0.0.1	localhost
127.0.1.1         my_domain
0.0.0.0	        my_domain.xyz
```

from both my client computer and my server, i can connect to the server via telnet:
server telnet
```
telnet my_domain.xyz 17171                                                                                 
Trying 0.0.0.0...
Connected to my_domain.xyz.
Escape character is '^]'.
jbs1{
```

client telnet:
```
telnet my_domain.xyz 17171                                                                                 
Trying __my_real_server_ip__...
Connected to my_domain.xyz.
Escape character is '^]'.
jbs1{
```

problem is the xmage client can't connect to the server, and at this point i really don't know why...

client starts options: `java8  -Xms512m -Xmx1024m  -Djava.net.preferIPv4Stack=true -Dfile.encoding=UTF-8 -jar ./lib/mage-client-1.4.50.jar &
`

client connection parameters:
Server name: my_domain.xyz
port: 17171

Failed to connect, client log is:
```sh
INFO  2022-07-18 09:53:36,678 Connect: connecting to server my_domain.xyz:17171                                               =>[SwingWorker-pool-5-thread-4] SessionImpl$5.work 
WARN  2022-07-18 09:54:06,794 Cannot connect                                                                             =>[SwingWorker-pool-5-thread-3] SessionImpl.handleCannotConnectException 
org.jboss.remoting.CannotConnectException: Error setting up client lease upon performing connect.
	at org.jboss.remoting.Client.connect(Client.java:1928)
        ...
	at org.jboss.remoting.Client.connect(Client.java:1924)
	... 10 more
Caused by: org.jboss.remoting.InvocationFailureException: Socket timed out.  Waited 29960 milliseconds for response while calling on InvokerLocator [bisocket://my_domain.xyz:17171/?onewayThreadPool=mage.remote.CustomThreadPool&serializationtype=jboss]; nested exception is: 
	java.net.SocketTimeoutException: Read timed out
       ...
Caused by: java.net.SocketTimeoutException: Read timed out
INFO  2022-07-18 09:54:06,806 Disconnecting DONE                                                                         =>[SwingWorker-pool-5-thread-3] SessionImpl.disconnect 
INFO  2022-07-18 09:54:06,806 Disconnected from user mode                                                                =>[SwingWorker-pool-5-thread-3] MageFrame.disconnected 
```

Is there something that i missed or do i encounter a random bug ?

**Comment by Alex-Vasile** [comment]
1. Are you able to connect a local client to it (one also started on the vps?)
2. Is this the beta or regular release?

**Comment by J1HN** [comment]
for the 1., i don't have any X11 running, i don't know if i can connect to the local server using a client. is there anyway to connect the client using only command line / start option ?

for the2., it's the server downloaded via the XMageLauncher-0.3.8.jar , the server starting logs returns:
`Starting MAGE server version 1.4.50-V2 (build: 2021-09-05 18:59)`

**Comment by Alex-Vasile** [comment]
> for the 1., i don't have any X11 running, i don't know if i can connect to the local server using a client. is there anyway to connect the client using only command line / start option ?
> 
> 
> 
> for the2., it's the server downloaded via the XMageLauncher-0.3.8.jar , the server starting logs returns:
> 
> `Starting MAGE server version 1.4.50-V2 (build: 2021-09-05 18:59)`

Try the beta as well, xmage.today.  The "stable" version that you got from xmage.de hasn't been updated in almost a year.

Beyond that I am not sure what else to try for server connection issues.

**Comment by J1HN** [comment]
the beta version extracted from xmage.today did the trick ! 
guess i felt in the trap of deprecated xmage.de download :)
Thanks.
