### ISSUE TITLE
beta freezes a lot mid-match

### ISSUE THREAD

**Issue by lordi-erez** [magefree/mage#9289]
task manager shows memory usage is far higher than what th in-game tracker shows when these freezes happen

maybe that info is importat

**Comment by Alex-Vasile** [comment]
Are you playing with AI?
What decks do they have?
What difficulty did you set the AI to?

**Comment by lordi-erez** [comment]
i played multiplayer

**Comment by Alex-Vasile** [comment]
Was the server hosted locally? Or was it the public beta server?

What was going on the board when these freezes were happening?

**Comment by lordi-erez** [comment]
public beta server

it doesnt matter whats on the board, as it happens regardless of what happens

**Comment by Alex-Vasile** [comment]
Then this isn't a bug, this is just the beta server being very busy. (I don't think it has as many resources are the main servers).
