### ISSUE TITLE
Kaito Shizuki Emblem Doesn't Trigger

### ISSUE THREAD

**Issue by stevedavidmusic** [magefree/mage#9290]
A user reported that Kaito Shizuki's emblem doesn't trigger when you deal combat damage to the opponent. I was able to replicate the bug down below: 

<img width="1280" alt="Screen Shot 2022-07-19 at 10 27 33 AM" src="https://user-images.githubusercontent.com/45299811/179789267-1c1f8e0e-fd90-4edc-ae4e-9fbed4b0b5fa.png">

**Comment by jeffwadsworth** [comment]
[[Kaito Shizuki]]
