### ISSUE TITLE
Cryptic Command doesn't counter flashbacked spells

### ISSUE THREAD

**Issue by bigzwine** [magefree/mage#930]
This happened today:

1) Opponent casts Snapcaster Mage targeting Anticipate with the ability.
2) After ability resolved, opponent cast Anticipate from graveyard.
3) I cast Cryptic Command choosing to counter Anticipate and draw a card.
4) Messages area said Anticipate was countered but Anticipate did not leave the stack and resolved normally.

**Comment by bigzwine** [comment]
Seems to be the case with any counter spell and cards flashbacked with Snapcaster. Had the same thing happen again when I tried to counter a flashbacked Lightning Bolt with Spellstutter Sprite.

23:49: Player moves Lightning Bolt from stack to the exile zone
23:49: Lightning Bolt is countered by Spellstutter Sprite
23:49: Spellstutter Sprite is countered by Cryptic Command
23:49: Player draws a card
23:49: bigzwine loses 3 life

**Comment by bigzwine** [comment]
Could be that this is fixed by pull request https://github.com/magefree/mage/pull/928

**Comment by LevelX2** [comment]
> Could be that this is fixed by pull request #928

Yes possible, that's what I also assumed but did not check yet.

**Comment by ImperatorPrime** [comment]
I can confirm that this issue is fixed by pull request #928

**Comment by LevelX2** [comment]
So closed.
