### ISSUE TITLE
Revel in Silence is bugged

### ISSUE THREAD

**Issue by HabsFanatic** [magefree/mage#9305]
Once a player plays Revel in Silence, no one can't cast spells for remainder **of the game**!

**Comment by Alex-Vasile** [comment]
[[Revel in Silence]]

**Comment by cassius1213** [comment]
Issue may be Duration on `RevelInSilenceEffect`--currently `WhileOnBattlefield` instead of `EndOfTurn`.

Additionally, `FlamescrollCelebrantTriggeredAbility` appears to be dealing 2 damage instead of 1.

First contribution.
