### ISSUE TITLE
Can't select Anything 

### ISSUE THREAD

**Issue by catman123456** [magefree/mage#9320]
When making tokens with[[Junk Winder]] if there is nothining to select it soft locks.

![image](https://user-images.githubusercontent.com/64045003/180982355-ced92872-4c0c-4d4e-a98f-07b34b45d418.png)

**Comment by Alex-Vasile** [comment]
I can't reproduce. Looking at the screenshot it looks like the [[Vampiric Link]] attached to your Master of Ceremonies is highlighted. Does that belong to one of the AI?

**Comment by catman123456** [comment]
Oh  the[[[Vampiric Link](https://c1.scryfall.com/file/scryfall-cards/normal/front/a/9/a9be1058-0668-4938-8801-e9a98464651c.jpg?1562578939)]] is the cpu's
