### ISSUE TITLE
[NEO] Mighty Servant of Leuk-o missing ability

### ISSUE THREAD

**Issue by Metalb00** [magefree/mage#9324]
[[Mighty Servant of Leuk-o]]  becomes crewed by 2 creatures for the first time each turn it gains "when this creature deals combat damage to a player draw 2 cards" until end of turn

the draw trigger isn't working

**Comment by Alex-Vasile** [comment]
Related to #9204

**Comment by xenohedron** [comment]
Fixed in a6c19c4
