### ISSUE TITLE
How to make a Commander deck

### ISSUE THREAD

**Issue by heaviermelero** [magefree/mage#933]
Hi.

I dont know if this is the right place to post it, but the general forum doesnt send me the activation mail...

I want to build a commander deck but I dont know how it works in the deck editor. Do I have to do something to chose the commander?

Thanks.

**Comment by emerald000** [comment]
For a standard commander deck, put your commander in your sideboard (with the 99 cards in the main deck).

For a Tiny Leaders, put your main deck/sideboard normally and put your commander's name in the deck name field in the upper left of the screen.

**Comment by heaviermelero** [comment]
thanks so much
