### ISSUE TITLE
[RIX] See Red - The "At the beginning of your end step..." trigger triggers when in hand and library.

### ISSUE THREAD

**Issue by T-and-Em** [magefree/mage#9339]
See screenshot. Deck has 20 mountains and 20 copies of See Red. All 20 copies of See Red trigger have triggered on my first end step despite not being in play. The card seems to work fine otherwise.

![image](https://user-images.githubusercontent.com/76133892/182011148-fcf5e161-4d0a-4913-8802-c5347679d330.png)

**Comment by weirddan455** [comment]
I've got a fix.  It was creating a delayed trigger which is incorrect for this ability.  Changed to a normal beginning of end step trigger and it will now only trigger for cards on the battlefield.

**Comment by awjackson** [comment]
It wasn't even "creating a delayed trigger", it was just using a `DelayedTriggeredAbility` subclass for a normal triggered ability.
