### ISSUE TITLE
Connive trigger not recognizing power to allow double strike.

### ISSUE THREAD

**Issue by LegionedintheDamned** [magefree/mage#9344]
Kamiz, Obscura Oculus' ability in tandem with Geist of Saint Traft.  Geist was a 4/4, attacked.

1. Kamiz's ability on stack.
2. Geist's ability on stack.
3. Player duplicated Geist's ability with Strionic Resonator.
4. 4/4 Angel 1 ETB.
5. 4/4 Angel 2 ETB.
6. Connive triggers, placing counter on Geist.
7. No double strike effect triggers.  I believe it was due to Geist being a 4/4 at the beginning of the combat phase.

The following turn the same player attached with a larger Geist (7/7) and it functioned correctly.
![Screenshot 2022-07-31 211713](https://user-images.githubusercontent.com/82664393/182066007-694c550e-c951-4159-9b45-9960521531fb.png)

**Comment by satchmosanzabar** [comment]
Can confirm this issue is still present.
