### ISSUE TITLE
Playing a commander game, attacked by lots of goaded creatures, attacker made a bunch of tokens

### ISSUE THREAD

**Issue by aRobinhs** [magefree/mage#9349]
Game exception occurred: mage.MageException: Iterated player priority after game exception too often, game ends! Last error:
 null
Server version: 1.4.51-V4-beta8 (build: 2022-07-29 22:25)
mage.game.GameImpl.playPriority(GameImpl.java:1586)
mage.game.turn.Step.priority(Step.java:61)
mage.game.turn.CombatDamageStep.priority(CombatDamageStep.java:31)
mage.game.turn.Phase.playStep(Phase.java:184)
mage.game.turn.Phase.play(Phase.java:89)
mage.game.turn.Turn.play(Turn.java:132)
mage.game.GameImpl.playTurn(GameImpl.java:1054)
mage.game.GameImpl.play(GameImpl.java:964)
mage.game.GameImpl.start(GameImpl.java:940)
mage.server.game.GameWorker.call(GameWorker.java:34)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)

**Comment by Alex-Vasile** [comment]
Do you have a picture of the board?
What made all of the tokens?
When did this error show up? Declaring attackers, blockers, damage?

**Comment by aRobinhs** [comment]
Sorry I don't have that much info, it happened pretty randomly and the game crashed so I only had a few seconds to see the board before it kicked us out of the lobby. I don't remember that much useful info, just that someone made a ton of elf tokens during the declare attackers step. My apologies for wasting your time.

**Comment by Alex-Vasile** [comment]
Hmmm. There's not a lot to go on. Maybe related to #9302.
You say they made a ton of elf tokens, did the stack resolve, or did the crash happen as tokens were being made?
Do you remember what was making the elves? Was it one ability, or lots of them?

If you open up your xmage folder, go to client, and go to the gamely folder. Do you have a log in there from this game?

**Comment by aRobinhs** [comment]
iirc it was after the tokens were made, and it was one ability but i dont remember what it was. I went through the logs and didnt see a log for this game.

**Comment by Alex-Vasile** [comment]
There really isn't much to go off of for this one.

Was it a multiplayer game or 1v1?
Could you upload your decklist and your opponents (if playing with a friend) or at least what their commander(s) were

**Comment by Alex-Vasile** [comment]
Not enough info to reproduce or search on. If it happens again, either comment here with a screenshot and/or game log or open a new issue with that info.
