### ISSUE TITLE
Fellwar Stone produces types of mana it shouldn't

### ISSUE THREAD

**Issue by sumsarz** [magefree/mage#9351]
[[Fellwar Stone]] shows colorless as a type of mana that it can produce when tapped, which it shouldn't be able to.

It also ignores replacement effects like [[Hall of Gemstone]], and allows for production of any color as usual (plus colorless), even though all opponent lands only produce the chosen color from Hall of Gemstone.

_2009-10-01: The colors of mana are white, blue, black, red, and green. Fellwar Stone can't be tapped for colorless mana, even if a land an opponent controls could produce colorless mana._

_2009-10-01: When determining what colors of mana your opponents' lands could produce, take into account any applicable replacement effects that would apply to those lands' mana abilities (such as Contamination's effect, for example). If there is more than one, consider them in any possible order._

**Comment by Alex-Vasile** [comment]
Same with [[Gond Gate]]
