### ISSUE TITLE
Emrakul, the Aeons Torn protection doesn't work against colored auras

### ISSUE THREAD

**Issue by stevedavidmusic** [magefree/mage#9357]
I was able to target Emrakul, the Aeons Torn when casting Control Magic when I shouldn't because Emrakul has protection from spells that are one or more color.

<img width="1280" alt="Screen Shot 2022-08-04 at 11 56 50 PM" src="https://user-images.githubusercontent.com/45299811/183004593-c48b7824-e80c-460d-87ba-bf5183202748.png">

**Comment by awjackson** [comment]
Emrakul should not have protection from things like Oblivion Ring (because the spell does not target, a triggered ability of the permanent it becomes does) but it *should* have protection from Aura spells.
