### ISSUE TITLE
Lazav, Dimir Mastermind copying ability ends if the copied card is exiled from the graveyard

### ISSUE THREAD

**Issue by andyfries** [magefree/mage#936]
If I copy my opponent's creature when it goes to the graveyard with Lazav, then exile that card from their graveyard (e.g. with Dimir Doppelganger), Lazav stops being a copy of that creature. Since Lazav's ability doesn't have a duration,  he should stay a copy of that creature regardless of which zone the card ends up in.

**Comment by ImperatorPrime** [comment]
Fixed by 7648ca4b4f75d78f4cb35c78e950c4673dfdbfdd.
