### ISSUE TITLE
Can't cast Turntimber Symbiosis from graveyard with Jace, Telepath Unbound

### ISSUE THREAD

**Issue by stevedavidmusic** [magefree/mage#9365]
Found a bug where I can't cast Turntimber Symbiosis from the graveyard with Jace, Telepath Unbound (the backside of Jace, Vryn's Prodigy). I targeted Turntimber Symbiosis with Jace's -3 ability to cast an instant or sorcery from the graveyard, but nothing is happening when i click the Turntimber Symbiosis. I tried turning off automatic mana payments and everything, nothing worked. I'm not sure if this is just an issue with Turntimber Symbiosis or MDFCs in general.

<img width="1280" alt="Screen Shot 2022-08-07 at 12 10 22 AM" src="https://user-images.githubusercontent.com/45299811/183276352-2f8ad9f1-ca88-4cc7-b4b8-5725863166d9.png">

**Comment by stevedavidmusic** [comment]
Just tested it with another Sea Gate Restoration, also didn't work. Must be an MDFC issue?

<img width="1280" alt="Screen Shot 2022-08-07 at 12 19 57 AM" src="https://user-images.githubusercontent.com/45299811/183276568-286cd2ac-d495-467f-91bc-744288bb4266.png">

**Comment by stevedavidmusic** [comment]
On the plus side, MDFCs seem to work fine with Snapcaster Mage, probably because it gives flashback where Jace, Telepath Unbound just lets you cast the card. 

<img width="1280" alt="Screen Shot 2022-08-07 at 12 26 29 AM" src="https://user-images.githubusercontent.com/45299811/183276749-5f07e218-f085-44bb-ab21-3572af838860.png">

**Comment by Susucre** [comment]
Improvements and refactor on play/cast effects have solved this one already (added test to prove it.)
