### ISSUE TITLE
Boseiju, Who Endures + Artifact with "dies" trigger

### ISSUE THREAD

**Issue by JuliusFiedler** [magefree/mage#9366]
Found a bug, where [Boseiju, Who Endures's](https://scryfall.com/card/neo/266/boseiju-who-endures) channel ability destroys a [Wurmcoil Engine](https://scryfall.com/card/2xm/308/wurmcoil-engine), but no ability is put on the stack. Opponent said, the same thing happend with [Sundering Titan](https://scryfall.com/card/2xm/292/sundering-titan) leaving the game due to Boseiju and trigger was put on the stack (although I cant confirm the second scenario).

**Comment by jeffwadsworth** [comment]
Worked fine for me.

**Comment by Alex-Vasile** [comment]
> Found a bug, where [Boseiju, Who Endures's](https://scryfall.com/card/neo/266/boseiju-who-endures) channel ability destroys a [Wurmcoil Engine](https://scryfall.com/card/2xm/308/wurmcoil-engine), but no ability is put on the stack. Opponent said, the same thing happend with [Sundering Titan](https://scryfall.com/card/2xm/292/sundering-titan) leaving the game due to Boseiju and trigger was put on the stack (although I cant confirm the second scenario).

Was this on the beta?

**Comment by Chewbaklava** [comment]
I've had similar experiences when I sac artifacts with Daretti Scrap Savant. Wurmcoil and Solemn Simulacrum didn't death trigger.

**Comment by JuliusFiedler** [comment]
> > Found a bug, where [Boseiju, Who Endures's](https://scryfall.com/card/neo/266/boseiju-who-endures) channel ability destroys a [Wurmcoil Engine](https://scryfall.com/card/2xm/308/wurmcoil-engine), but no ability is put on the stack. Opponent said, the same thing happend with [Sundering Titan](https://scryfall.com/card/2xm/292/sundering-titan) leaving the game due to Boseiju and trigger was put on the stack (although I cant confirm the second scenario).
> 
> Was this on the beta?

Yes this was on the beta server, sorry for not mentioning.

**Comment by stevedavidmusic** [comment]
I also experienced the bug, although it's not consistent. It was difficult to replicate at first, but I think it's dependent on wether or not the player searching their library has any basics in their library. 

- When I first tried to replicate the bug, the deck playing the artifacts with death triggers had no fetchable basics with Boseiju, only Mishra's Workshop. Was unable to re-produce bug in this scenario.

- When I added some basic lands / duals to the deck, the bug happened immediately.

<img width="1280" alt="Screen Shot 2022-09-01 at 12 23 18 AM" src="https://user-images.githubusercontent.com/45299811/187839188-3ac334cb-0cfa-4a4d-ae9b-8cb9b039881f.png">


- When I sided out fetchable lands, the bug wasn't happening anymore (you can see death trigger go on the stack).
<img width="1243" alt="Screen Shot 2022-09-01 at 12 30 16 AM" src="https://user-images.githubusercontent.com/45299811/187839222-bd3bada8-d6b4-4935-b3f3-679cb095f934.png">

**Comment by awjackson** [comment]
Fixed by changing the card implementation to match [[Assassin's Trophy]], separating the "destroy target" and "controller searches their library" parts into two separate effects.
