### ISSUE TITLE
DEV: Unable to build mage-server ("package does not exist")

### ISSUE THREAD

**Issue by Rhystic1** [magefree/mage#9368]
Hello,

I've been trying to clone the project on IntelliJ, however when I try to build the Server module I am getting loads of errors coming from AuthorizedUser.java, as seen here:

![image](https://user-images.githubusercontent.com/3988944/183463026-ece6af1a-2944-47f5-8cb8-612c95ac7b81.png)

I have tried running the clean install command with Maven multiple times, and even re-cloning the repo without success. Am I doing something wrong? Thanks for the help.

**Comment by Alex-Vasile** [comment]
When you set up the maven build configuration, what did you set as the working directory?
![maven](https://user-images.githubusercontent.com/48962821/183520669-68b46296-c791-48d1-b941-3f07a4c31d85.jpg)

**Comment by Rhystic1** [comment]
> When you set up the maven build configuration, what did you set as the working directory? ![maven](https://user-images.githubusercontent.com/48962821/183520669-68b46296-c791-48d1-b941-3f07a4c31d85.jpg)

Hello, the Server is now building and running correctly after clean installing again with Maven, however the client is still not building with similar errors. This is my configuration:

![image](https://user-images.githubusercontent.com/3988944/183750077-e1388e9d-e49b-4ed3-87f2-4385a9614f9c.png)

**Comment by Alex-Vasile** [comment]
> > When you set up the maven build configuration, what did you set as the working directory?
> 
> Hello, the Server is now building and running correctly after clean installing again with Maven, however the client is still not building with similar errors. This is my configuration:

See my config above. I usually build the whole project, you will have to do that if you want to build and play from source.

**Comment by Rhystic1** [comment]
> > > When you set up the maven build configuration, what did you set as the working directory?
> > 
> > 
> > Hello, the Server is now building and running correctly after clean installing again with Maven, however the client is still not building with similar errors. This is my configuration:
> 
> See my config above. I usually build the whole project, you will have to do that if you want to build and play from source.

I have your same configuration as shown here:

![image](https://user-images.githubusercontent.com/3988944/183754980-497e5f80-6992-4f36-abb9-01e53cfbbd50.png)

Anything else I could check or try? Thanks in the meantime!

**Comment by Alex-Vasile** [comment]
Under Settings > Build, Execution > Build Tools > Maven > Runner. Do you have "Delegate IDE build/run actions to Maven" selected?

What is the actual error you're getting now?

**Comment by Rhystic1** [comment]
> Under Settings > Build, Execution > Build Tools > Maven > Runner. Do you have "Delegate IDE build/run actions to Maven" selected?
> 
> What is the actual error you're getting now?

I did not, however trying to check it and then running the Client had the same effect. Should I leave it on?
The error is: `C:\Users\<myuserpath>\IdeaProjects\mage\Mage.Client\src\main\java\mage\client\cards\BigCard.java:6:22
java: package mage.constants does not exist`

And I'm also getting the following other errors:
![image](https://user-images.githubusercontent.com/3988944/183758089-49447794-b0d6-4e93-8682-7191afed0d29.png)

**Comment by Alex-Vasile** [comment]
Have you run the maven configuration you copied from my screenshot above? You have to set up that maven setting, then run it, and after that's done you can run the client

**Comment by Alex-Vasile** [comment]
and yes, you should leave it on.

**Comment by Rhystic1** [comment]
Yes, as you can see from the screenshot that I posted above, the configuration is identical to yours.

I ran the maven config again, then the Client one, but it still isn't building with the same error messages.

**Comment by Alex-Vasile** [comment]
When you say the client one, do you mean the client build maven config? You don't have to do that.

The steps should be:
1. Build clean (afterwards you can use the green build hammer for incremental builds)
2. Run the client and server using the steps from [here](https://github.com/magefree/mage/wiki/Setting-up-your-Development-Environment#running-server-and-client). **Running** the client needs a new run configuration as "Application" and not as "Maven"

**Comment by Rhystic1** [comment]
Is there something wrong with the screenshot that I shared? Genuinely asking if it got cut off on your side for some reason, because you should clearly see that, once again, the "build clean" config is _exactly the same_ as yours, and that Run Server and Run Client are configured as "Application".

And yes, I always followed the two steps, and the server runs fine but the client gives those errors.

**Comment by Alex-Vasile** [comment]
> ![image](https://user-images.githubusercontent.com/3988944/183750308-4e48ae55-72d7-4468-a68d-0f8c06f68c12.png)

Sorry, I mistake this image as a build one since it says "built and run".
And the other one I didn't even see that there were application settings.
My mistake

Try the following change:
1. Change both of the applications to not build before being run (go to each one, and above the "-cp mage-client" box click on "Modify Options" then check "Do not build before run".

**Comment by Rhystic1** [comment]
> > ![image](https://user-images.githubusercontent.com/3988944/183750308-4e48ae55-72d7-4468-a68d-0f8c06f68c12.png)
> 
> Sorry, I mistake this image as a build one since it says "built and run". And the other one I didn't even see that there were application settings. My mistake
> 
> Try the following change:
> 
> 1. Change both of the applications to not build before being run (go to each one, and above the "-cp mage-client" box click on "Modify Options" then check "Do not build before run".

No problem at all!

I have done the changes you suggested (and also did a fresh clean install), but yet again the Server works perfectly and the Client fails. Here are the error messages:

![image](https://user-images.githubusercontent.com/3988944/184129094-60b7fc3e-ece0-47a3-814e-7137a2411d60.png)

![image](https://user-images.githubusercontent.com/3988944/184129162-57c4cbdd-a69b-4c1e-9f1d-cb3c0c77bb1d.png)

This is my Project tab:

![image](https://user-images.githubusercontent.com/3988944/184129268-d8e554d9-cda3-415f-aa54-cd1f33bf033b.png)

**Comment by Alex-Vasile** [comment]
> ![image](https://user-images.githubusercontent.com/3988944/184129268-d8e554d9-cda3-415f-aa54-cd1f33bf033b.png)

What's strange is that the "Run Server" tab shows up with a Maven icon, but the "Run Client" does not. When I run mine, both server and client show the Maven Icon.

If you open the Run Client tab, it should have a command at the very top (the command that IntelliJ ran in order to run your application). Can you post it? E.g. Mine looks like this:
```
/Users/alex/Library/Java/JavaVirtualMachines/openjdk-18.0.2/Contents/Home/bin/java -Dvisualvm.id=575555828502958 -Dmaven.multiModuleProjectDirectory=/Users/alex/Documents/GitHub/mageMain/Mage.Client -Dmaven.home=/Applications/IntelliJ IDEA.app/Contents/plugins/maven/lib/maven3 -Dclassworlds.conf=/Applications/IntelliJ IDEA.app/Contents/plugins/maven/lib/maven3/bin/m2.conf -Dmaven.ext.class.path=/Applications/IntelliJ IDEA.app/Contents/plugins/maven/lib/maven-event-listener.jar -javaagent:/Applications/IntelliJ IDEA.app/Contents/lib/idea_rt.jar=50258:/Applications/IntelliJ IDEA.app/Contents/bin -Dfile.encoding=UTF-8 -classpath /Applications/IntelliJ IDEA.app/Contents/plugins/maven/lib/maven3/boot/plexus-classworlds.license:/Applications/IntelliJ IDEA.app/Contents/plugins/maven/lib/maven3/boot/plexus-classworlds-2.6.0.jar org.codehaus.classworlds.Launcher -Didea.version=2022.2 -DskipTests=true -Dexec.workingdir=/Users/alex/Documents/GitHub/mageMain/Mage.Client -Dexec.args=-Xverify:none -client -Xss2m -Xms512m -Xmx1G -XX:+PerfBypassFileSystemCheck -classpath %classpath mage.client.MageFrame umlit -c unlimited -debug -Dexec.executable=/Users/alex/Library/Java/JavaVirtualMachines/openjdk-18.0.2/Contents/Home/bin/java exec:exec
```

**Comment by Rhystic1** [comment]
Sure, here is what I have:

`"C:\Program Files\Java\jdk1.8.0_311\bin\java.exe" "-javaagent:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2022.2\lib\idea_rt.jar=64360:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2022.2\bin" -Dfile.encoding=UTF-8 -classpath "C:\Program Files\Java\jdk1.8.0_311\jre\lib\charsets.jar;C:\Program Files\Java\jdk1.8.0_311\jre\lib\deploy.jar;C:\Program Files\Java\jdk1.8.0_311\jre\lib\ext\access-bridge-64.jar;C:\Program Files\Java\jdk1.8.0_311\jre\lib\ext\cldrdata.jar;C:\Program Files\Java\jdk1.8.0_311\jre\lib\ext\dnsns.jar;C:\Program Files\Java\jdk1.8.0_311\jre\lib\ext\jaccess.jar;C:\Program Files\Java\jdk1.8.0_311\jre\lib\ext\jfxrt.jar;C:\Program Files\Java\jdk1.8.0_311\jre\lib\ext\localedata.jar;C:\Program Files\Java\jdk1.8.0_311\jre\lib\ext\nashorn.jar;C:\Program Files\Java\jdk1.8.0_311\jre\lib\ext\sunec.jar;C:\Program Files\Java\jdk1.8.0_311\jre\lib\ext\sunjce_provider.jar;C:\Program Files\Java\jdk1.8.0_311\jre\lib\ext\sunmscapi.jar;C:\Program Files\Java\jdk1.8.0_311\jre\lib\ext\sunpkcs11.jar;C:\Program Files\Java\jdk1.8.0_311\jre\lib\ext\zipfs.jar;C:\Program Files\Java\jdk1.8.0_311\jre\lib\javaws.jar;C:\Program Files\Java\jdk1.8.0_311\jre\lib\jce.jar;C:\Program Files\Java\jdk1.8.0_311\jre\lib\jfr.jar;C:\Program Files\Java\jdk1.8.0_311\jre\lib\jfxswt.jar;C:\Program Files\Java\jdk1.8.0_311\jre\lib\jsse.jar;C:\Program Files\Java\jdk1.8.0_311\jre\lib\management-agent.jar;C:\Program Files\Java\jdk1.8.0_311\jre\lib\plugin.jar;C:\Program Files\Java\jdk1.8.0_311\jre\lib\resources.jar;C:\Program Files\Java\jdk1.8.0_311\jre\lib\rt.jar;C:\Users\<user folder>\IdeaProjects\mage\Mage.Server\production\mage-client" mage.client.MageFrame
`

**Comment by Alex-Vasile** [comment]
![image](https://user-images.githubusercontent.com/48962821/184507443-632f3fc9-b8d5-4d10-b144-4ed1282486bd.png)
This is what my run config looks like on windows.

The command you have above does not include anything about maven

**Comment by Alex-Vasile** [comment]
Open up the maven tab and click these two buttons "Reload all maven projects" and "Generate Sources and Update Folders for all projects". Then do a clean build, and then try launching again
![buttons](https://user-images.githubusercontent.com/48962821/184507653-aa2b40d4-4d07-473f-99ca-4a0a1e63e362.png)
t

**Comment by Rhystic1** [comment]
> Open up the maven tab and click these two buttons "Reload all maven projects" and "Generate Sources and Update Folders for all projects". Then do a clean build, and then try launching again ![buttons](https://user-images.githubusercontent.com/48962821/184507653-aa2b40d4-4d07-473f-99ca-4a0a1e63e362.png) t

It worked! Thank you so much! I think these two steps should be included in the guide...
