### ISSUE TITLE
[VOW] Howlpack Avenger (Ill-tempered Loner) has the same issue as Wrathful Red Dragon

### ISSUE THREAD

**Issue by rockydirtbag** [magefree/mage#9369]
With a transformed [[Ill-tempered Loner]] (Howlpack Avenger) and six other creatures in play, [[Star of Extrinction]] was cast, dealing 20 damage to each of them. However Howlpack Avenger triggered only once instead of six times, and the ability dealt 120 damage to the target (instead of 20 damage to each of six targets).

[[Wrathful Red Dragon]] had the same issue, which was solved in #9278.

**Comment by Jengamon** [comment]
[[Star of Extinction]]
