### ISSUE TITLE
In Search of Greatness only scry's

### ISSUE THREAD

**Issue by LegionedintheDamned** [magefree/mage#9370]
Evening,
I tried rolling back to see how it worked, but it seems 'In Search of Greatness' only scry's, it does not give the option for a free cast.  I tried many times over many games on different turns.  Perhaps I've missed something in how it functions, but it should be:
-Check highest mana cost on battlefield under your control
-Check hand to see if there is a valid target
-If so, give yes/no choice
-If choice, highlight only valid targets
-If no, or no choice, scry 1

**Comment by awjackson** [comment]
Fixed by 506c09d20744c115b061f2d2fe62121166ccd520
