### ISSUE TITLE
Unable connect to server. Server is not responding

### ISSUE THREAD

**Issue by ZeusGaming1337** [magefree/mage#9373]
I have been getting this error for awhile and have tried multiple fixes for this but nothing works. Part of this issue is that my download for xmage doesn't come with a launcher. I've tried manually creating the run command for it but it does not work either.

**Comment by Alex-Vasile** [comment]
Where did you download xmage from?

**Comment by ZeusGaming1337** [comment]
I have downloaded it from both the xmage website and github. Xmage worked on my PC for a long time but i would have to download the updates from github and replace files.

**Comment by Alex-Vasile** [comment]
Try downloading the beta from xmage.today.

downloading and building from source won’t work if you try to connect to any of the public servers.

**Comment by ZeusGaming1337** [comment]
I downloaded the beta and it works. Can open the launcher and connect to the beta server, but cant connect to any other servers.

**Comment by Alex-Vasile** [comment]
Yes.

If you download the beta you can only play on the beta server (or someone else hosting the beta server). If you download the stable version you can play on other servers (other than beta) but it's much older.

If you download and build from source you will only be able to play on a server build from the same source version.
