### ISSUE TITLE
Assault Suit (and generally "cannot be sacrificed") bug

### ISSUE THREAD

**Issue by PurpleCrowbar** [magefree/mage#9375]
Found this while working on the implementation of [[Jon Irenicus, Shattered One]] who makes use of a very similar effect.

[[Assault Suit]] states that "Equipped creature gets +2/+2, has haste, can’t attack you or planeswalkers you control, and **can’t be sacrificed**." It has the following ruling:

> _[If an effect instructs you to sacrifice a creature, and you control any creatures other than the creature equipped with Assault Suit, you must sacrifice one of them. You can’t try to sacrifice the equipped creature, fail, and therefore ignore the effect.](https://scryfall.com/card/cma/208/assault-suit#rulings)_

In xmage currently, attempting to sacrifice a creature who cannot be sacrificed due to being equipped by Assault Suit will prematurely end the effect requiring a sacrifice, even if there are other valid targets. (So, directly breaks the ruling above)

Tested this with [[Desecration Elemental]] equipped with A.S. and another creature in play, cast a spell therefore triggering D.E.'s triggered ability requiring a creature be sacrificed, selected D.E. as the target, got the pop-up reading "This creature can't be sacrificed", and then the sacrifice requirement ended and the spell resolved.

**Comment by theelk801** [comment]
this is something I’ve been ignoring for a while since there was only one “can’t be sacrificed” card until now, we need to refactor every effect that sacrifices to use a special filter/target class specifically for choosing things to sacrifice like we have `TargetDiscard`

**Comment by PurpleCrowbar** [comment]
> this is something I’ve been ignoring for a while since there was only one “can’t be sacrificed” card until now, we need to refactor every effect that sacrifices to use a special filter/target class specifically for choosing things to sacrifice like we have TargetDiscard for discard effects

I was thinking maybe an ability ("CantBeSacrificed" or something), having permanents receive that ability for whatever reason such as Jon Irenicus, and having [SacrificeEffect.java](https://github.com/magefree/mage/blob/80e11b20528dfb88a91c3f3be66a354818a0606b/Mage/src/main/java/mage/abilities/effects/common/SacrificeEffect.java)'s filter contain a predicate which filters out any permanents with that ability. Do you think that would work or would every effect that extends SacrificeEffect also need to have that filter predicate added in?

**Comment by theelk801** [comment]
The problem is that there are a ton of other places where players are prompted to choose something to sacrifice, so each of those instances needs to be refactored. It’s not impossible but it’s a fair amount of work to do

**Comment by Alex-Vasile** [comment]
Wouldn't it make more sense to check inside `Player.choose` with something like `Outcome == .Sacrifice && ability instance of CantBeSacrificedAbility`, as well as inside and `Permanent.sacrifice`? (also move the ability into common abilities).

**Comment by theelk801** [comment]
I dunno about tying it to the outcome, it should probably be a specific targeting class that extends `TargetPermanent`, plus we’d still have to go in and make sure the outcome is always sacrifice

**Comment by Alex-Vasile** [comment]
> I dunno about tying it to the outcome, it should probably be a specific targeting class that extends `TargetPermanent`, plus we’d still have to go in and make sure the outcome is always sacrifice

Yeah good point about the outcome. Changing all of the targeting is going to be a pain, but at will also run faster than having to check every .choose call.

**Comment by PurpleCrowbar** [comment]
How would changing the targeting affect cards like [[Mercy Killing]] (opponent chooses the creature for you) or [[Death Pit Offering]] (player doesn't target the creature(s) they want to sacrifice)?

**Comment by theelk801** [comment]
in both of those cases it would be handled by the sacrifice method like it already is, we would just be adding the targeting restraint in addition to what we already have

**Comment by theelk801** [comment]
I’m gonna take this one once I’m back in the groove with DMU, I know what needs to be done
