### ISSUE TITLE
DistributeCountersEffect allows you to put 0 counters on a creature

### ISSUE THREAD

**Issue by sprangg** [magefree/mage#9379]
The `DistributeCountersEffect` used by [[Elven Rite]] and similar counter-distributing cards allows you to target a creature and then put 0 counters on it. This has side-effects like being able to kill a creature enchanted with [[Spinal Graft]] by putting 0 counters on it, or being able to put 0 counters on a creature with [[Biogenic Upgrade]] but still getting to double that creature's counters.

The rule, from Biogenic Upgrade's scryfall page:

> You choose how many targets Biogenic Upgrade has and how the counters are distributed as you cast it. Each target must receive at least one counter. This means, for example, that you can't target three creatures, assign them two, one, and zero counters.

**Comment by awjackson** [comment]
This bug also affects damage distributing effects like Flames of the Firebrand.

> 601.2d If the spell requires the player to divide or distribute an effect (such as damage or counters) among one or more targets, the player announces the division. **Each of these targets must receive at least one of whatever is being divided**. *(emphasis added)*

**Comment by tiera3** [comment]
You choose how the counters will be distributed as you cast Grove's Bounty. Each target must receive at least one +1/+1 counter.
(2023-09-01)

The above appears in the Rulings information (on Gatherer and Scryfall) for Elusive Otter. So even Grove's Bounty (the adventure spell part of Elusive Otter) should still incur this restriction. The only question is whether you can cast it with zero targets and x=0 - just for a cast trigger.)
