### ISSUE TITLE
[ZNR] Yasharn, Impacable Earth bugged when cast via Castcade

### ISSUE THREAD

**Issue by BenjaminUDover** [magefree/mage#9387]
Game exception occurred: java.util.NoSuchElementException: No value present
Server version: 1.4.51-V4-beta9 (build: 2022-08-13 09:30)
java.util.Optional.get(Optional.java:135)
mage.cards.y.YasharnImplacableEarthEffect.applies(YasharnImplacableEarth.java:157)
mage.abilities.effects.ContinuousEffects.preventedByRuleModification(ContinuousEffects.java:845)
mage.players.PlayerImpl.getPlayableFromObjectSingle(PlayerImpl.java:3870)
mage.players.PlayerImpl.getPlayableFromObjectAll(PlayerImpl.java:3839)
mage.players.PlayerImpl.getPlayable(PlayerImpl.java:4016)
mage.players.PlayerImpl.getPlayableObjects(PlayerImpl.java:4147)
mage.server.game.GameSessionPlayer.prepareGameView(GameSessionPlayer.java:214)
mage.server.game.GameSessionPlayer.getGameView(GameSessionPlayer.java:198)
mage.server.game.GameSessionWatcher.lambda$update$0(GameSessionWatcher.java:54)
java.util.Optional.ifPresent(Optional.java:159)
mage.server.game.GameSessionWatcher.update(GameSessionWatcher.java:54)
mage.server.game.GameController.updateGame(GameController.java:788)
mage.server.game.GameController.lambda$init$3aa0d15c$1(GameController.java:124)
mage.game.events.EventDispatcher.fireEvent(EventDispatcher.java:28)
mage.game.events.TableEventSource.fireTableEvent(TableEventSource.java:39)
mage.game.GameImpl.fireUpdatePlayersEvent(GameImpl.java:2842)
mage.game.GameImpl.playPriority(GameImpl.java:1560)
mage.game.turn.Step.priority(Step.java:61)
mage.game.turn.Phase.playStep(Phase.java:184)
mage.game.turn.Phase.play(Phase.java:89)
mage.game.turn.Turn.play(Turn.java:132)
mage.game.GameImpl.playTurn(GameImpl.java:1054)
mage.game.GameImpl.play(GameImpl.java:964)
mage.game.GameImpl.start(GameImpl.java:940)
mage.server.game.GameWorker.call(GameWorker.java:34)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)

**Comment by Alex-Vasile** [comment]
[[Yasharn, Implacable Earth]]
