### ISSUE TITLE
Thespian's Stage Dark Depths combo

### ISSUE THREAD

**Issue by Berksmb** [magefree/mage#940]
I've been trying to play Thespian's Stage Dark Depths combo and it hasn't worked in any of my games. When it asks to sacrifice because of the legend rule I choose the one with 10 counters (original) and it sacrifices the copy without counters. I've tried it 3 times now and it always does this.

**Comment by ImperatorPrime** [comment]
Based on what you describe, this seems to be working as intended. The help text says "select a Dark Depths to keep (Legendary Rule)". Thus the one you select (the one with counters) is the one that is kept.

![darkdepths](https://cloud.githubusercontent.com/assets/1624520/7384165/0f2ba2da-ede2-11e4-9af4-9c4cd3b17272.png)

**Comment by Berksmb** [comment]
Wow, that's awkward. I'll read the help text better next time. Thank you.
