### ISSUE TITLE
Unknown Error (An error has occurred on the MAGE server. Your last action will be rollbacked.)

### ISSUE THREAD

**Issue by BenjaminUDover** [magefree/mage#9410]
Game exception occurred: mage.MageException: Iterated player priority after game exception too often, game ends! Last error:
 null
Server version: 1.4.51-V4-beta9 (build: 2022-08-13 09:30)
mage.game.GameImpl.playPriority(GameImpl.java:1586)
mage.game.turn.Step.priority(Step.java:61)
mage.game.turn.CombatDamageStep.priority(CombatDamageStep.java:31)
mage.game.turn.Phase.playStep(Phase.java:184)
mage.game.turn.Phase.play(Phase.java:89)
mage.game.turn.Turn.play(Turn.java:132)
mage.game.GameImpl.playTurn(GameImpl.java:1054)
mage.game.GameImpl.play(GameImpl.java:964)
mage.game.GameImpl.start(GameImpl.java:940)
mage.server.game.GameWorker.call(GameWorker.java:34)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)

**Comment by Alex-Vasile** [comment]
A little late now, but do you have any info of what happened?

**Comment by BenjaminUDover** [comment]
Uhhh, does the ticket have any information about the effect? Is there a
date on it? I could possibly say more if I knew more than the subject line
entails, if there isn't any more info, I might have started to write a
report and mistakenly sent it.

**Comment by Alex-Vasile** [comment]
> Uhhh, does the ticket have any information about the effect? Is there a date on it? I could possibly say more if I knew more than the subject line entails, if there isn't any more info, I might have started to write a report and mistakenly sent it.
> […](#)

The only information is that It was August 24, with the build from Aug 13, and that the error during the Combat Damage step when players have priority

**Comment by BenjaminUDover** [comment]
Hmm. Yeah, I'm looking over my decklists for stuff I might have played then, and I can't really pin point what it was. I think, and it's probably not worth investigating if it was this, that Laccolith Rig caused the error. The only other card I know I was playing at the time that was, to my knowledge, buggy was Battle Angels of Tyr, but I don't think that ever caused rollback errors.

**Comment by Alex-Vasile** [comment]
> Hmm. Yeah, I'm looking over my decklists for stuff I might have played then, and I can't really pin point what it was. I think, and it's probably not worth investigating if it was this, that Laccolith Rig caused the error. The only other card I know I was playing at the time that was, to my knowledge, buggy was Battle Angels of Tyr, but I don't think that ever caused rollback errors.

[[Laccolith Rig]]

I will keep this here for someone to investigate if they have the time, but I'm not hopeful on being able to reproduce it.
