### ISSUE TITLE
Katilda's Rising Dawn Doubles the +X+X P/T Increase

### ISSUE THREAD

**Issue by dashosa** [magefree/mage#9416]
![image](https://user-images.githubusercontent.com/63882410/186907275-2babe9fb-d191-4e0f-92ba-1e032efd3103.png)

**Comment by awjackson** [comment]
I can't reproduce this.

![Screenshot_20220826_125956](https://user-images.githubusercontent.com/9252545/186955981-9667b36b-140d-4944-b0ea-a9cd08772328.png)

**Comment by Alex-Vasile** [comment]
Do you have a picture of the whole battlefield?

**Comment by Susucre** [comment]
[[Katilda's Rising Dawn]]
