### ISSUE TITLE
MIstbind Clique doesn't tap all lands

### ISSUE THREAD

**Issue by cosmokai2000** [magefree/mage#942]
Mistbind Clique doesn't tap all lands when championing a faerie. I've been able to reproduce this

**Comment by ImperatorPrime** [comment]
Duplicate of 938.

**Comment by cosmokai2000** [comment]
938 was fixed yesterday, I was able to to this twice today

**Comment by ImperatorPrime** [comment]
Using the regular launcher or checked out code? Because the fix hasn't been released yet.

**Comment by cosmokai2000** [comment]
Launcher. Sorry then, my apologies
