### ISSUE TITLE
[CLB] Server Error when I cast Dusk Mangler

### ISSUE THREAD

**Issue by adoukimskywalk** [magefree/mage#9424]
When I cast Dusk Mangler I have always this error messsage (see picture) and I must restart XMAGE.
![2022-08-27 08_35_02-XMage  Client_ 1 4 51-V4-beta9 (build_ 2022-08-13 09_30)  Server_ 1 4 51-V4-beta](https://user-images.githubusercontent.com/29253964/187030641-e899dbe1-7fc2-4432-98bb-75850661177b.png)
![2022-08-27 08_37_50-2022-08-27 08_35_02-XMage  Client_ 1 4 51-V4-beta9 (build_ 2022-08-13 09_30)  Se](https://user-images.githubusercontent.com/29253964/187030650-e6b95c40-8363-445b-a2f8-12b536be866d.png)

**Comment by Alex-Vasile** [comment]
[[Dusk Mangler]]
