### ISSUE TITLE
Cryptborn horror devotion is not being calculated correctly for Mogis

### ISSUE THREAD

**Issue by Greeneye0** [magefree/mage#944]
Here I have 8 devotion to black and red: Phoenix = 2R, Cryptborn = 2R + 2B, Mogis = 1R + 1B

But Mogis has not been chanted in to a creature:
![image](https://cloud.githubusercontent.com/assets/11687236/7416150/9c94da40-ef1a-11e4-92aa-05af63e5585b.png)

**Comment by LevelX2** [comment]
hybrid mana does not count twice.
check the rules.

**Comment by Greeneye0** [comment]
See the following:
http://archive.wizards.com/Magic/Magazine/Article.aspx?x=mtg/daily/feature/therosmechanics


It doesn't come up in Theros, but hybrid mana symbols and other unusual colored mana symbols also count toward your devotion to each of their colors. For example, a permanent that costs Red or Green ManaRed or Green Mana adds two to your devotion to red and two to your devotion to green.

**Comment by LevelX2** [comment]
No, sorry you're wrong. You only count the number of mana symbols.

700.5. A player’s devotion to [color] is equal to the number of mana symbols of that color among the mana costs of permanents that player controls. A player’s devotion to [color 1] and [color 2] is equal to the number of mana symbols among the mana costs of permanents that player controls that are [color 1], [color 2], or both colors.
