### ISSUE TITLE
Chun-Li and ordering spells

### ISSUE THREAD

**Issue by mitchelljoneill** [magefree/mage#9448]
Hi devs, 

First wanted to say thank you for working so hard on this and pushing so many different commits. This truly is the best tool for online commander. Anyways i'll dive into the issue I found. 

On Xmage when using Chun-li I've noticed that it does not allow you to choose the order the spells are cast. For instance, if you have exiled _Astral Steel_ and a _Healing Salve_, you can choose to cast the Healing Salve first, so the Spell count is +1. Then, cast the Astral Steel so its Storm count includes the +1 from the Healing Salve.

The spells you cast from Chun-li are cast Sequentially. Not Simultaneously. Xmage does not let you order the spells currently. 

Now I could be wrong, but Mizzix's Mastery and Chandra, Pyromaster have similar rulings so I am pretty sure this is right. This is also how I play Chun-li in paper at events and i've never had another player or judge correct me.

**Comment by Alex-Vasile** [comment]
In terms of similarity, it'd say that [[Arcane Bonbardment]] is much closer.

But yes, you should be able to order the casts.

**Comment by jeffwadsworth** [comment]
[[Chun Li, Countless Kicks ]]
