### ISSUE TITLE
Receiving error after most recent update

### ISSUE THREAD

**Issue by Bdett151** [magefree/mage#9449]
After completing the most recent update, I was able to play for a few minutes but the client suddenly stopped working and I received the error shown. I tried closing everything down and re-connecting but this error keeps coming up now.

![image](https://user-images.githubusercontent.com/76190939/187803485-368623a6-0015-43d9-b0a9-2dfc0dd029d4.png)

**Comment by Alex-Vasile** [comment]
What is in the logs? Xmage/mage-client/mageclient.log?

**Comment by JayDi85** [comment]
"end of file" -- it can be proxy or vpn problem (disconnected from the server). You can try to play on local server with AI (use launcher) -- is it fine or not.
