### ISSUE TITLE
Add a icon on permanents with special actions

### ISSUE THREAD

**Issue by LevelX2** [magefree/mage#945]
With a special icon that signals that the permanent has a special action the players will be more aware how to use the special action.
http://www.slightlymagic.net/forum/viewtopic.php?f=70&t=16910&p=177951#p177901

**Comment by drmDev** [comment]
This has been confusing to many players, whether they use MTGO or XMage when interacting with Leonin Arbiter in particular.

**Comment by JayDi85** [comment]
Playable cards highlighting works fine with special actions, so that issue is no more actual.
