### ISSUE TITLE
[DMU] Jaya, Fiery Negotiator's -1 ability does nothing

### ISSUE THREAD

**Issue by stevedavidmusic** [magefree/mage#9451]
Jaya, Fiery Negotiator's -1 ability doesn't do anything. It prompts you the choice of card X or Y, but doesn't actually do anything once you select them. 

BEFORE
<img width="1280" alt="Screen Shot 2022-09-01 at 12 09 30 AM" src="https://user-images.githubusercontent.com/45299811/187836462-49e46dca-bb17-4918-9c2b-1e9188194b54.png">

AFTER
<img width="1280" alt="Screen Shot 2022-09-01 at 12 09 36 AM" src="https://user-images.githubusercontent.com/45299811/187836472-82c6cf7a-dad3-4b28-8716-960a09bb8d0e.png">

**Comment by Alex-Vasile** [comment]
[[Jaya, Fiery Negotiator]]
