### ISSUE TITLE
Wear//Tear x Suspend problem

### ISSUE THREAD

**Issue by Blitkun** [magefree/mage#946]
Just happened in a game:
I cast Wear//Tear with Fuse;
Opponent cast Delay targeting Wear//Tear - it resolved;
3 Turns later, after the last time counter on Wear//Tear was removed, I tried casting the Tear half of the card.

Selection Screen appears, I click on "Destroy target enchantment". Game freezes, priority is passed to my opponent, but he is unable to respond. After selecting "Skip Stack (F10)", Game Error window appears.

Uploaded Screenshot.

The link provided by the Game Error message leads to a blocked topic.

Game keeps rollbacking my action and does not allow any player to do anything else.

EDIT: Added GameLOG

---

Game Error
An error has occurred on the MAGE server. Your last action will be rollbacked.
Please post the following report here: http://www.slightlymagic.net/forum/posting.php?mode=reply&f=70&t=3116

Game exception occurred: java.lang.NullPointerException
Server version: 1.3.0dev2015-03-14v8
mage.players.PlayerImpl.cast(PlayerImpl.java:916)
mage.abilities.keyword.SuspendPlayCardEffect.apply(SuspendAbility.java:375)
mage.abilities.AbilityImpl.resolve(AbilityImpl.java:199)
mage.abilities.TriggeredAbilityImpl.resolve(TriggeredAbilityImpl.java:105)
mage.game.stack.StackAbility.resolve(StackAbility.java:107)
mage.game.GameImpl.resolve(GameImpl.java:1188)
mage.game.GameImpl.playPriority(GameImpl.java:1150)
mage.game.turn.Step.priority(Step.java:87)
mage.game.turn.Phase.playStep(Phase.java:203)
mage.game.turn.Phase.play(Phase.java:115)
mage.game.turn.Turn.play(Turn.java:140)
mage.game.GameImpl.playTurn(GameImpl.java:724)
mage.game.GameImpl.play(GameImpl.java:647)
mage.game.GameImpl.start(GameImpl.java:614)
mage.game.GameImpl.start(GameImpl.java:599)
mage.server.game.GameWorker.call(GameWorker.java:60)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
java.lang.Thread.run(Thread.java:745)

![gameerrorxmage1](https://cloud.githubusercontent.com/assets/9158612/7442767/e9d26308-f0d3-11e4-86dd-a354d16d3294.png)

Game Log:

<html>
  <head>

  </head>
  <body>
    <font color="#CCCC33">4:46 PM: </font><font color="Orange">Blitkun has 
    joined the game</font>
<font color="#CCCC33">: </font><font color="Orange"><br><b>Match score:</b><br>Blitkun 
    - 1 win<br>DeckHash: 8689016074881616545<br>Bharamhir - 0 wins<br>DeckHash: 
    2500087760673307240<br><br>You have to win 2 games to win the complete 
    match<br><br>Game has started<br><br></font>
<font color="#CCCC33">4:46 PM: </font><font color="White">Bharamhir shuffles 
    his or her library.</font>
<font color="#CCCC33">4:46 PM: </font><font color="White">Blitkun shuffles his 
    or her library.</font>
<font color="#CCCC33">4:46 PM: </font><font color="White">Bharamhir chooses 
    that he or she takes the first turn</font>
<font color="#CCCC33">4:46 PM: </font><font color="White">Bharamhir draws 
    seven cards</font>
<font color="#CCCC33">4:46 PM: </font><font color="White">Blitkun draws seven 
    cards</font>
<font color="#CCCC33">4:46 PM: </font><font color="White">Bharamhir decides to 
    take mulligan</font>
<font color="#CCCC33">4:46 PM: </font><font color="White">Blitkun keeps hand</font>
<font color="#CCCC33">4:46 PM: </font><font color="White">Bharamhir shuffles 
    his or her library.</font>
<font color="#CCCC33">4:46 PM: </font><font color="White">Bharamhir mulligans 
    for free and draws 7 cards</font>
<font color="#CCCC33">4:46 PM: </font><font color="White">Bharamhir draws 
    seven cards</font>
<font color="#CCCC33">4:46 PM: </font><font color="White">Bharamhir keeps hand</font>
<font color="#CCCC33">4:46 PM: </font><font color="Orange">Turn 1 Bharamhir 
    (20 - 20)</font>
<font color="#CCCC33">4:47 PM: </font><font color="White">Bharamhir plays 
    Stirring Wildwood</font>
<font color="#CCCC33">4:47 PM: </font><font color="White">Bharamhir attacks 
    with 0 creatures</font>
<font color="#CCCC33">4:47 PM: </font><font color="Orange">Turn 2 Blitkun (20 
    - 20)</font>
<font color="#CCCC33">4:47 PM: </font><font color="White">Blitkun draws a card</font>
<font color="#CCCC33">4:47 PM: </font><font color="White">Blitkun plays Arid 
    Mesa</font>
<font color="#CCCC33">4:47 PM: </font><font color="White">Blitkun attacks with 
    0 creatures</font>
<font color="#CCCC33">4:47 PM: </font><font color="Orange">Turn 3 Bharamhir 
    (20 - 20)</font>
<font color="#CCCC33">4:47 PM: </font><font color="White">Bharamhir draws a 
    card</font>
<font color="#CCCC33">4:47 PM: </font><font color="White">Bharamhir loses 2 
    life</font>
<font color="#CCCC33">4:47 PM: </font><font color="White">Bharamhir plays 
    Hallowed Fountain</font>
<font color="#CCCC33">4:47 PM: </font><font color="White">Bharamhir casts 
    Isochron Scepter</font>
<font color="#CCCC33">4:47 PM: </font><font color="White">Ability triggers: 
    Isochron Scepter - <i>Imprint &#8212; </i>When Isochron Scepter enters the 
    battlefield, you may exile an instant card with converted mana cost 2 or 
    less from your hand.</font>
<font color="#CCCC33">4:47 PM: </font><font color="White">Bharamhir moves 
    Delay from hand to the exile zone</font>
<font color="#CCCC33">4:47 PM: </font><font color="White">Bharamhir attacks 
    with 0 creatures</font>
<font color="#CCCC33">4:47 PM: </font><font color="White">Blitkun loses 1 life</font>
<font color="#CCCC33">4:47 PM: </font><font color="White">Blitkun sacrificed 
    Arid Mesa</font>
<font color="#CCCC33">4:47 PM: </font><font color="White">Blitkun activates: 
    search your library for a Mountain or Plains and put it onto the 
    battlefield. Then shuffle your library. from Arid Mesa</font>
<font color="#CCCC33">4:47 PM: </font><font color="White">Blitkun searches his 
    or her library</font>
<font color="#CCCC33">4:47 PM: </font><font color="White">Blitkun puts Sacred 
    Foundry from library onto the Battlefield</font>
<font color="#CCCC33">4:47 PM: </font><font color="White">Blitkun shuffles his 
    or her library.</font>
<font color="#CCCC33">4:47 PM: </font><font color="Orange">Turn 4 Blitkun (18 
    - 19)</font>
<font color="#CCCC33">4:47 PM: </font><font color="White">Blitkun draws a card</font>
<font color="#CCCC33">4:48 PM: </font><font color="White">Blitkun plays 
    Flagstones of Trokair</font>
<font color="#CCCC33">4:48 PM: </font><font color="White">Blitkun attacks with 
    0 creatures</font>
<font color="#CCCC33">4:48 PM: </font><font color="Orange">Turn 5 Bharamhir 
    (18 - 19)</font>
<font color="#CCCC33">4:48 PM: </font><font color="White">Bharamhir draws a 
    card</font>
<font color="#CCCC33">4:48 PM: </font><font color="White">Bharamhir attacks 
    with 0 creatures</font>
<font color="#CCCC33">4:48 PM: </font><font color="Orange">Turn 6 Blitkun (18 
    - 19)</font>
<font color="#CCCC33">4:48 PM: </font><font color="White">Blitkun draws a card</font>
<font color="#CCCC33">4:48 PM: </font><font color="White">Blitkun plays 
    Mountain</font>
<font color="#CCCC33">4:48 PM: </font><font color="White">Blitkun attacks with 
    0 creatures</font>
<font color="#CCCC33">4:48 PM: </font><font color="Orange">Turn 7 Bharamhir 
    (18 - 19)</font>
<font color="#CCCC33">4:48 PM: </font><font color="White">Bharamhir draws a 
    card</font>
<font color="#CCCC33">4:48 PM: </font><font color="White">Bharamhir attacks 
    with 0 creatures</font>
<font color="#CCCC33">4:48 PM: </font><font color="White">Blitkun casts fused 
    Wear // Tear left half targeting Isochron Scepter right half targeting 
    Leyline of Sanctity </font>
<font color="#CCCC33">4:48 PM: </font><font color="White">Bharamhir activates: 
    You may copy the exiled card. If you do, you may cast the copy without 
    paying its mana cost. from Isochron Scepter</font>
<font color="#CCCC33">4:49 PM: </font><font color="White">Bharamhir casts 
    Delay targeting Wear // Tear </font>
<font color="#CCCC33">4:49 PM: </font><font color="White">Bharamhir moves Wear 
    // Tear from stack to the exile zone</font>
<font color="#CCCC33">4:49 PM: </font><font color="White">Bharamhir moves Wear 
    // Tear from hand to the exile zone</font>
<font color="#CCCC33">4:49 PM: </font><font color="White">Bharamhir suspends 3 
    - Wear // Tear</font>
<font color="#CCCC33">4:49 PM: </font><font color="Orange">Turn 8 Blitkun (18 
    - 19)</font>
<font color="#CCCC33">4:49 PM: </font><font color="White">Ability triggers: 
    Wear // Tear - At the beginning of your upkeep, if this card is suspended, 
    remove a time counter from it.</font>
<font color="#CCCC33">4:49 PM: </font><font color="White">Removed 1 time 
    counter from Wear // Tear (2 left)</font>
<font color="#CCCC33">4:49 PM: </font><font color="White">Blitkun draws a card</font>
<font color="#CCCC33">4:49 PM: </font><font color="White">Blitkun plays 
    Flagstones of Trokair</font>
<font color="#CCCC33">4:49 PM: </font><font color="White">Flagstones of 
    Trokair is put into graveyard from battlefield</font>
<font color="#CCCC33">4:49 PM: </font><font color="White">Ability triggers: 
    Flagstones of Trokair - When Flagstones of Trokair is put into a graveyard 
    from the battlefield, you may search your library for a Plains card and 
    put it onto the battlefield tapped. Then shuffle your library.</font>
<font color="#CCCC33">4:49 PM: </font><font color="White">Blitkun searches his 
    or her library</font>
<font color="#CCCC33">4:49 PM: </font><font color="White">Blitkun puts Sacred 
    Foundry from library onto the Battlefield</font>
<font color="#CCCC33">4:49 PM: </font><font color="White">Blitkun shuffles his 
    or her library.</font>
<font color="#CCCC33">4:49 PM: </font><font color="White">Blitkun casts Ajani 
    Vengeant</font>
<font color="#CCCC33">4:49 PM: </font><font color="White">Blitkun activates: 
    Target permanent doesn't untap during its controller's next untap step. 
    from Ajani Vengeant targeting Isochron Scepter </font>
<font color="#CCCC33">4:50 PM: </font><font color="White">Blitkun attacks with 
    0 creatures</font>
<font color="#CCCC33">4:50 PM: </font><font color="Orange">Turn 9 Bharamhir 
    (18 - 19)</font>
<font color="#CCCC33">4:50 PM: </font><font color="White">Isochron Scepter 
    doesn't untap (Ajani Vengeant)</font>
<font color="#CCCC33">4:50 PM: </font><font color="White">Bharamhir draws a 
    card</font>
<font color="#CCCC33">4:50 PM: </font><font color="White">Bharamhir attacks 
    with 0 creatures</font>
<font color="#CCCC33">4:50 PM: </font><font color="Orange">Turn 10 Blitkun (18 
    - 19)</font>
<font color="#CCCC33">4:50 PM: </font><font color="White">Ability triggers: 
    Wear // Tear - At the beginning of your upkeep, if this card is suspended, 
    remove a time counter from it.</font>
<font color="#CCCC33">4:50 PM: </font><font color="White">Removed 1 time 
    counter from Wear // Tear (1 left)</font>
<font color="#CCCC33">4:50 PM: </font><font color="White">Blitkun draws a card</font>
<font color="#CCCC33">4:50 PM: </font><font color="White">Blitkun activates: 
    Target permanent doesn't untap during its controller's next untap step. 
    from Ajani Vengeant targeting Isochron Scepter </font>
<font color="#CCCC33">4:50 PM: </font><font color="White">Blitkun casts Hero 
    of Bladehold</font>
<font color="#CCCC33">4:50 PM: </font><font color="White">Blitkun attacks with 
    0 creatures</font>
<font color="#CCCC33">4:50 PM: </font><font color="Orange">Turn 11 Bharamhir 
    (18 - 19)</font>
<font color="#CCCC33">4:50 PM: </font><font color="White">Isochron Scepter 
    doesn't untap (Ajani Vengeant)</font>
<font color="#CCCC33">4:50 PM: </font><font color="White">Bharamhir draws a 
    card</font>
<font color="#CCCC33">4:50 PM: </font><font color="White">Bharamhir attacks 
    with 0 creatures</font>
<font color="#CCCC33">4:50 PM: </font><font color="Orange">Turn 12 Blitkun (18 
    - 19)</font>
<font color="#CCCC33">4:50 PM: </font><font color="White">Ability triggers: 
    Wear // Tear - At the beginning of your upkeep, if this card is suspended, 
    remove a time counter from it.</font>
<font color="#CCCC33">4:50 PM: </font><font color="White">Removed 1 time 
    counter from Wear // Tear (0 left)</font>
<font color="#CCCC33">4:50 PM: </font><font color="White">Ability triggers: 
    Wear // Tear - When the last time counter is removed from this card, if 
    it's removed from the game, play it without paying its mana cost if able. 
    If you can't, it remains removed from the game.</font>
<font color="#CCCC33">4:52 PM: </font><font color="White">Ability triggers: 
    Wear // Tear - At the beginning of your upkeep, if this card is suspended, 
    remove a time counter from it.</font>
<font color="#CCCC33">4:53 PM: </font><font color="White">Removed 1 time 
    counter from Wear // Tear (0 left)</font>
<font color="#CCCC33">4:53 PM: </font><font color="White">Ability triggers: 
    Wear // Tear - When the last time counter is removed from this card, if 
    it's removed from the game, play it without paying its mana cost if able. 
    If you can't, it remains removed from the game.</font>
<font color="#CCCC33">4:55 PM: </font><font color="White">Ability triggers: 
    Wear // Tear - At the beginning of your upkeep, if this card is suspended, 
    remove a time counter from it.</font>
<font color="#CCCC33">5:03 PM: </font><font color="White">Bharamhir has 
    conceded.</font>
<font color="#CCCC33">5:03 PM: </font><font color="White">Blitkun has won the 
    game</font>
<font color="#CCCC33">5:03 PM: </font><font color="White">Bharamhir has lost 
    the game.</font>
  </body>
</html>

**Comment by drmDev** [comment]
guess I'll take a look at this...

**Comment by Zerrisx** [comment]
Can't check this due to #6549, which breaks at an earlier point in the workflow

**Comment by JayDi85** [comment]
Fixed via 121dc3501ef3eb89cc35b317fcde40b1367eb319
