### ISSUE TITLE
Saffi Eriksdotter doesn't return targeted creatures from graveyard to play

### ISSUE THREAD

**Issue by MultiverseLabyrinth** [magefree/mage#947]
Upon resolve of Saffi Eriksdotter's triggered effect on targeted creature, the ability triggers and resolves, but the creature is never returned.

.gif displays problem:
http://i.imgur.com/OEEXJC5.gif

**Comment by ImperatorPrime** [comment]
Fixed by ddc2128f780482bebafb4f52ba737c643ee508da.

**Comment by LevelX2** [comment]
The change did break that target cards in graveyard that were removed from graveyard before the effect resolves do no longer exists for the effect and nothing may be moved. 
Now the card will be moved to battlefield from every zone it is in now.

**Comment by ImperatorPrime** [comment]
Ok, I hopefully really fixed it under f9f6b078ab95b2921e0337c6814b492cf3ebda16. All tests are now passing. (Plus a new one I added for It That Betrays)

**Comment by LevelX2** [comment]
IT That Betrays ruling:
6/15/2010 If the sacrificed permanent that caused the second ability to trigger somehow leaves the graveyard before the ability resolves (possibly because it was returned to the battlefield by the ability of another It That Betrays), the ability simply won't do anything when it resolves.

With two in play wouldn't it put it twice into play?

**Comment by ImperatorPrime** [comment]
Hm, true. So It that Betrays isn't quite right yet. However, the trigger isn't a dying trigger, correct? 


http://www.mtgsalvation.com/forums/magic-fundamentals/magic-rulings/magic-rulings-archives/514629-rest-in-peace-vs-sacrifice-non-creature

So in the case of Rest In Peace being in play, the ability would still find the card?

**Comment by ImperatorPrime** [comment]
Ok, I fixed It That Betrays to only return on the first battlefield transition (I think). Thanks for all your help.
