### ISSUE TITLE
Shield Counter Always Removed by Non-Lethal Damage

### ISSUE THREAD

**Issue by dashosa** [magefree/mage#9475]
![image](https://user-images.githubusercontent.com/63882410/188502433-bea9586b-9689-46ea-be7c-b3f7764e1210.png)

**Comment by PurpleCrowbar** [comment]
What's the bug? Shield counters are removed when either the creature would die or would take damage.

**122.1c** A shield counter on a permanent creates one replacement effect and one prevention effect that protect the permanent. These effects are “If this permanent would be destroyed as the result of an effect, instead remove a shield counter from it” and “If damage would be dealt to this permanent, prevent that damage and remove a shield counter from it.”

**Comment by awjackson** [comment]
Shield counters are not the same as regeneration shields.
