### ISSUE TITLE
Last Release

### ISSUE THREAD

**Issue by JoseEduardo** [magefree/mage#9489]
Is there any particular reason why we don't have the latest release available? (The available version does not contain the latest commits)

**Comment by Alex-Vasile** [comment]
If you're asking about the stable version (www.xmage.de) then forget about it. Work under the assumption that it's dead and not coming back anytime soon.

As for the beta (www.xmage.today), it is only 8 days behind in terms of commits. A new version comes out approximately every 2-3 weeks.

**Comment by JayDi85** [comment]
de updated soon too, wait.
