### ISSUE TITLE
Cannot connect properly to any server

### ISSUE THREAD

**Issue by Nebruken** [magefree/mage#949]
hi, up until a few days ago i could connect to xmage servers and play without any problem. of recent i am unable to connect to any server. the program just tells me 'the connection has been lost to server. reconnect?' then i press ok and it tells me 'Network error. you have been disconnected' then i press ok and it comes again and i press ok again and after it sends me to a blankish  server without any available game, nearly no people and the only option i have to do with the games going is 'None' instead of 'Watch', and when i organise a standard duel it shows on the available games list BUT instead of 'Join' button all there is is a blank button. how can i fix this? do i have to reinstall xmage? will i lose my decks?

**Comment by LevelX2** [comment]
You can't join again your own match, so it's normal that this button is blank.

To which server do you join?
I recommend to use xmage.de, that server I do monitor often and has a lot of players online normally and runs very stable lately.

Maybe post  a screenshot of the tables so I can understand your problem more clearly.

**Comment by Nebruken** [comment]
![Uploading image.png…]()

i press connect and this happens
 then the connect button becomes available to press again and once i do that it tells me the connection to the server was lost. reconnect? i press yes and it sends me to the empty server and under it der is a window network error

**Comment by Nebruken** [comment]
hmm not sure u got the image, basically i press connect, nothing happens except the connect button becoming unpressed, then i press it again and i get sent to the empty server.

**Comment by Nebruken** [comment]
can u please tell me which of the 3 proxies in the connection part of the option menu do i choose and give me the port number to your server please maybe i can fix it like that

**Comment by LevelX2** [comment]
You use Proxy = None as long as you do not connect to the internet using a proxy server (what's probably the case is).

If you open the connect window, use the find button to select a public server from the list of servers.
So the name/IP and port number will be filled in automatically.
![connect](https://cloud.githubusercontent.com/assets/2066790/7481580/47fbd5a0-f371-11e4-8eb0-d18861ce6ca5.jpg)

**Comment by WJDeVries** [comment]
I am unable to connect to any server as well. I was able to connect earlier today, but now when I hit "Connect," the button is "clicked" and it says "connecting" but nothing happens after that. I can't connect to a localhost server either.
