### ISSUE TITLE
Is there a block a player option?

### ISSUE THREAD

**Issue by EmblemMan** [magefree/mage#950]
Honestly I would rather the person just get banned but alas I doubt that will happen. I was playing and a guy did nothing but belittle and insult me while playing and then came into my other games and did the same while I was playing. I just want to block him from my games so that my opponent does not have to deal with his immature comments. Anyway let me know if this is already an option thanks.

**Comment by LevelX2** [comment]
No sorry, no option yet only disallow spectators, but that ommits all users but the players.

And kind of hard to implement so it would help you in this situation. As long as you can create XMage accounts for free, there is no way in my opinion to do this really effective.

We could create a ban function by ip, but it's absolutely easy to reconnect to your ISP and get a new ip. So I think it's not really worth the efford.

In case of this maybe disallow spectators from your matches for some time, so he can't join your match chat.
