### ISSUE TITLE
Deceiver of Form causing Rollback error

### ISSUE THREAD

**Issue by thefnitalian** [magefree/mage#9501]
Deceiver of Form is causing a Rollback error during combat the turn you cast him. The game cannot proceed and needs to be exited.

**Comment by Alex-Vasile** [comment]
Another (maybe related bug) [[Deceiver of Form]] bug is in #9294.

**Comment by jeffwadsworth** [comment]
It worked fine for me.  The next time it happens, please grab the error and make note what was on the battlefield, etc.
