### ISSUE TITLE
Burrenton Forge-Tender not preventing damage properly

### ISSUE THREAD

**Issue by aastrand** [magefree/mage#952]
I noticed that when I sac it to prevent Pyroclasm from dealing damage to all my creatures it has no effect. I think I can reproduce the bug but I fail to figure out why it doesnt work.

Here's the attempt at a reproducer:
```
package org.mage.test.cards.single.lrw;

import mage.constants.PhaseStep;
import mage.constants.Zone;
import org.junit.Test;
import org.mage.test.serverside.base.CardTestPlayerBase;

/**
 *
 * @author Kranken
 */

public class BurrentonForgeTenderTest extends CardTestPlayerBase {

    @Test
    public void testPreventDamageFromStack() {
        addCard(Zone.BATTLEFIELD, playerA, "Burrenton Forge-Tender");
        addCard(Zone.BATTLEFIELD, playerA, "Soldier of the Pantheon");

        addCard(Zone.HAND, playerB, "Lightning Bolt");
        addCard(Zone.BATTLEFIELD, playerB, "Mountain", 1);

        skipInitShuffling();

        castSpell(1, PhaseStep.PRECOMBAT_MAIN, playerB, "Lightning Bolt", "Soldier of the Pantheon");
        activateAbility(1, PhaseStep.PRECOMBAT_MAIN, playerA, "Sacrifice {this}: Prevent all damage a red source of your choice would deal this turn.");
        playerA.addChoice("Lightning Bolt");

        setStopAt(1, PhaseStep.END_TURN);
        execute();

        assertPermanentCount(playerA, "Burrenton Forge-Tender", 0);
        assertGraveyardCount(playerA, "Burrenton Forge-Tender", 1);
        assertPermanentCount(playerA, "Soldier of the Pantheon", 1);
        assertGraveyardCount(playerA, "Soldier of the Pantheon", 0);
    }

}
```

Here the solder will still die, which is wrong.
My first thought was that the ability had its Zone set to BATTLEFIELD but that proved fruitless.
Any insight into why this happens? How can we fix this? :)

**Comment by ImperatorPrime** [comment]
The issue in question is fixed by efb48e2ace66f8fe1e4b83ff1e58fadd76f8275b. As for your test case, I don't think it quite works correctly because the test framework isn't able to properly capture responding to other spells on the stack. (Or if it can, I couldn't make it work)

**Comment by LevelX2** [comment]
I added the suggested test and 3 more tests.
@ImperatorPrime 
Unfortunately it's a bit more complicated than just using the sourceId for check as you basically did with your fix ignoring the zoneChangeCounter. The FixedTarget (as all TargetPointer) saves the zoneChangeCounter of the object targeted and checks later it's the same object by comparing this zone change counter.
If you like you can check out by changing the effect in your local repository back to your solution and running the 4 tests.

I recommend reading this http://www.slightlymagic.net/forum/viewtopic.php?f=116&t=14516 to get more information.

Target handling is a very tricky thing at least as XMage design is not optimal yet to support it.
But I remember how long I had to work with the project to get it more clear and still I have often the feeling I don't understand it fully.

Please continue with your help for the project, I think it's great if we check out our changes each other to find possible mistakes/bugs.

See you

**Comment by LevelX2** [comment]
And I forget:
Be careful using the card obejct. You solution did for example not work with a Token doing damage because you don't get a card object back for a TokenPermanent obejct.

**Comment by ImperatorPrime** [comment]
I will be more careful with the card object in the future.

As for FixedTarget, doesn't it have a getTarget object? This returns the
UUID without checking the zone, which is relevant if the card you want to
reference has changed zones.

I had a read over your link. Is this a replacement for TargetPointer? I'm a
little unclear what is different between MageObjectReference and the
existing TargetPointer.
