### ISSUE TITLE
how to get the cards code?

### ISSUE THREAD

**Issue by copperfield42** [magefree/mage#9526]
Hello, I want to build a little script to import a given text file to xmage format, I know that xmage already have it, but the card selection on it is weird, for example the version chosen for _Sol Ring_ is the SUM, rather that a more recent set like DMC, that would be the first reason for why I want to make my own, the second is to automatically include my favorite version of a given card. For this I will be using Python, because I don't know much of Java.

So my question is if isn't too much to ask how can I get the xmage-codes of a given card (from my local installation), for example [DMC:190] for Sol Ring, in order to make the .dck file? 

Thanks :)

**Comment by spjspj** [comment]
Look through mage\Mage.Sets\src\mage\sets\ for any lines that look like:
        super("World Championship Decks 2004", "WC04", ExpansionSet.buildDate(2004, 9, 1), SetType.PROMOTIONAL);
for example in:
mage\Mage.Sets\src\mage\sets\WorldChampionshipDecks2004.java

**Comment by JayDi85** [comment]
Use import button from deck editor. It's support multiple formats and clipboard copy-paste. Just prepare cards list in any format like mtga or mtgo and import it.

**Comment by copperfield42** [comment]
@JayDi85 the issue isn't that I can't import the deck that work perfectly fine as far as I can tell, the issue is the chosen versions of card, for example, importing the following from the clipboard 

![image](https://user-images.githubusercontent.com/4504719/190726573-74427f3a-acdb-4bfe-9927-ca6537394f77.png)
![image](https://user-images.githubusercontent.com/4504719/190726686-87b55221-5fa2-4898-9392-33ef4bbd6e31.png)

I would prefer that the chosen version of the card be the most recent one by default

![image](https://user-images.githubusercontent.com/4504719/190727025-4f39f813-5ea9-4269-a1a2-e10f5edd5632.png)

**Comment by copperfield42** [comment]
I retract partially my previous statement, the clipboard import also have some issue
for example this deck I have in Scryfall https://scryfall.com/@copperfield/decks/6d6c1edb-1ea6-4117-8c9e-422182e2d070

if I exported to the clipboard, it complain about empty lines (and the missing card but that is to be expected), but succeed, if I do the copy to arena it fail completely, so I guess it does not support that. downloading it as MTGO work fine, as TXT is the same as with the clipboard, .CVS is not supported and JSON said it can't find any info

**Comment by copperfield42** [comment]
@spjspj that is too tedious, the local database seem to be located in the folder xmage\mage-client\db\cards.h2.mv.db I will see if I can find a way to connect to it

**Comment by weirddan455** [comment]
> So my question is if isn't too much to ask how can I get the xmage-codes of a given card (from my local installation), for example [DMC:190] for Sol Ring, in order to make the .dck file?

Not entirely sure what you're asking here.  The code is just in the format [3 letter set code:card number].  It's not a specific xmage code.  That's the way it's printed on the card.

> if I exported to the clipboard, it complain about empty lines (and the missing card but that is to be expected), but succeed, if I do the copy to arena it fail completely

It looks like it doesn't like the way scryfall exports the set/card number.  It looks like "1 Migration Path (IKO) 164" which differs from xmage format.  Exporting from mtggoldish.com in Arena format works because they don't include set and card number.  This could probably be improved to accept scryfall's format.

**Comment by copperfield42** [comment]
> Not entirely sure what you're asking here. The code is just in the format [3 letter set code:card number]. It's not a specific xmage code. That's the way it's printed on the card.

I'm basically asking where xmage store those so I can go a grad it from there, I can do it the brute force way, if you will, which is to make a deck file for each set, but that is rather tedious...

**Comment by copperfield42** [comment]
I found what I wanted, so I close this.
