### ISSUE TITLE
Popup an actual card when in the game log

### ISSUE THREAD

**Issue by spjspj** [magefree/mage#9529]
Currently the hyperlink pops up the card text only - would be nice to have the actual card popup when it's hovered over or clicked.

**Comment by JayDi85** [comment]
Use mouse wheel to switch popup hint mode from text to image.

**Comment by JayDi85** [comment]
Now it support to show a real object data in card popup:
* text mode shows real object (if not found then show original card with same name);
* image mode shows default card image;

As side effect -- it fixed not workable popups for tokens.

Example:

![shot_231126_143904](https://github.com/magefree/mage/assets/8344157/6c7258f8-f2b6-43ea-a02d-f21c08e5879f)
![shot_231126_143832](https://github.com/magefree/mage/assets/8344157/61acd41c-cee0-4cf9-9e88-aca687a3e4c3)
![shot_231126_144420](https://github.com/magefree/mage/assets/8344157/f7c52ebe-3d5e-4042-998b-492af2a87b62)
