### ISSUE TITLE
Fact or Fiction changed from selecting what goes to graveyard now

### ISSUE THREAD

**Issue by stevedavidmusic** [magefree/mage#9531]
So I noticed that the functionality of Fact or Fiction has changed. For the longest time, you'd select what goes to your HAND, not GRAVEYARD, but this has changed in a recent patch. Was this intentional? Fact or Fiction's wording is weird where it's not explicit like Liliana of the Veil is worded. If this was intentional, I'll live with it, but personally I think it's more intuitive to have it work like it did in the past where you choose what goes to your hand. 

<img width="1280" alt="Fact or Fiction Bug" src="https://user-images.githubusercontent.com/45299811/190866690-65a2589e-14e9-4de5-b4fa-3afd23a6ab00.png">

**Comment by Alex-Vasile** [comment]
This was changed as part of https://github.com/magefree/mage/commit/02968c9cc12de53875d590c9a322c41f4bfa4bbe when several cards with similar effects were refactored to have a common effect.

[[Fact or Fiction]]

**Comment by stevedavidmusic** [comment]
Ok, while I see the benefits of re-organizing the code, can it still be made so that you choose what goes to HAND? It's a lot more intuitive and both Fact or Fiction and Sphinx of Clear Skies order putting it into your hand first.

**Comment by theelk801** [comment]
I think that's a reasonable request, I can do that
