### ISSUE TITLE
Arvinox, the Mind Flail does not allow me to cast cards exiled by it

### ISSUE THREAD

**Issue by Omega0zero** [magefree/mage#9535]
Playing [[Arvinox, the Mind Flail]] as my general and I have a [[Swords to Plowshares]] exiled that I can't play.

**Comment by PurpleCrowbar** [comment]
Arvinox's second ability reads:
> At the beginning of your end step, exile the bottom card of each opponent's library face down. For as long as those cards remain exiled, you may look at them, **you may cast permanent spells from among them**, and you may spend mana as though it were mana of any color to cast those spells.

Emphasis on the part in bold which says "you may cast permanent spells from among them", Arvinox does not allow you to cast *any* spells from his ability, only permanents

**Comment by Omega0zero** [comment]
> Arvinox's second ability reads:
> 
> > At the beginning of your end step, exile the bottom card of each opponent's library face down. For as long as those cards remain exiled, you may look at them, **you may cast permanent spells from among them**, and you may spend mana as though it were mana of any color to cast those spells.
> 
> Emphasis on the part in bold which says "you may cast permanent spells from among them", Arvinox does not allow you to cast _any_ spells from his ability, only permanents

Yeah I am what we call, obviously incapable of reading. Thanks.
