### ISSUE TITLE
Balustrade Spy - Manaless Dredge

### ISSUE THREAD

**Issue by BTolputt** [magefree/mage#954]
When Balustrade Spy is returned to the battlefield, the trigger freezes the UI/engine. This is probably because it has to reveal the entire library before sending the cards to the graveyard. Manaless Dredge is a deck archetype in Legacy which would be good for XMage to handle

**Comment by LevelX2** [comment]
I can't reproduce this problem.
Can you describe more in detail what exactly happens before the UI freezes?

**Comment by BTolputt** [comment]
I play a few turns until such time as there is a Dread Return & Balustrade Spy in the graveyard. I sacrifice three creatures to bring back Balustrade Spy, select myself as target, then click through the stack until Balustrade Spy is meant to reveal all cards in my library before putting them in my graveyard.

I can't attach the deck to this post. It was easily reproducible here until the recent Mac OSX issue (server crash).

**Comment by BTolputt** [comment]
Note, the deck has no lands at all. The point of the Balustrade Spy is to stick everything in the library into the graveyard, bar a "shuffle back into library" safety card like the Blightsteel Colossus. 

This is a common tactic in Manaless Dredge (with most decks I've seen running the full playset of Balustrade Spy for that reason). I've not had it work once in XMage with each attempt freezing the interface.

**Comment by LevelX2** [comment]
Should already be fixed w ith 1.4.0v2.
