### ISSUE TITLE
Triumphant Reckoning + Gift of Immortality

### ISSUE THREAD

**Issue by LegionedintheDamned** [magefree/mage#9547]
Player caster Triumphant Reckoning while Gift of Immortality was in the graveyard.  Daxos the Returned was already on the battlefield.  Gift of Immortality returned to the battlefield, failed to attach, then went back to the graveyard.

11/10/2020 | If you return an Aura card to the battlefield this way, the Aura isn't being cast, so you choose what it will enchant as is enters the battlefield. An Aura returned this way doesn't target anything (so it could be attached to an opponent's permanent with hexproof, for example), but the Aura's enchant ability restricts what it can be attached to. If the Aura can't legally be attached to anything, it remains in the graveyard.

**Comment by awjackson** [comment]
I couldn't reproduce this. I got Gift of Immortality and several other Auras into my graveyard, cast Triumphant Reckoning, and the "choose a creature (to attach ~ to)" replacement effect correctly happened for each of the Auras including Gift of Immortality.
