### ISSUE TITLE
Client Potential Memory leaks

### ISSUE THREAD

**Issue by Alex-Vasile** [magefree/mage#9548]
Reported potential issues to look into:
- [ ] "if I open and close the card viewer, the memory used slowly climbs up"
- [ ] "Not consistently repeatable, but routinely after I do an EDH game I'll have higher resting memory usage than before it. And it keeps creeping up each game I play"

Also reported is 70% cpu usage (on an 8 core, 16 thread cpu) on the client after the client has been up for >24 hours. Memory usage was close to the max memory amount (so the cpu usage could be caused by constant calls to GC).

**Comment by JayDi85** [comment]
You must set max memory param and repeat until out of memory error. That's
will be real memory leaks. If you see memory growing without oom error then
this is image cache and it's ok.

**Comment by Alex-Vasile** [comment]
> You must set max memory param and repeat until out of memory error. That's will be real memory leaks. If you see memory growing without oom error then this is image cache and it's ok.

When does the image cache empty itself, or at least make itself smaller?

**Comment by JayDi85** [comment]
It uses constant memory limit and free it on usage. See cache constructor
for comments/params -- I optimized some time ago to fix deck editor memory
eating.

But it can be cards objects or something else from deck editor too. So must
be research.

**Comment by Alex-Vasile** [comment]
Current implementation of the caches use a maximum *number* of entries, and not a maximum size (as far as I've been able to find so far). Based on testing, the cache also does not allow itself to be CG'd aggressively enough in response to low memory.

https://github.com/magefree/mage/blob/cb2ae0295fae901ce58abf49f1b93be9494c3473/Mage.Client/src/main/java/mage/client/util/SoftValuesLoadingCache.java#L20-L26
