### ISSUE TITLE
Can't join/watch games?

### ISSUE THREAD

**Issue by HammerD72** [magefree/mage#955]
As you can see in the picture in the link, where I could usually double click "join" to join, instead of a button there is now just text. I can't watch games either.
People are still able to join my and other players games so maybe something changed and I'm doing something wrong?

[EDIT] After talking to players in chat, it seems like I'm the only one with the issue.
I've forced an update through the launcher which did not fix.
I've uninstalled java, and installed java 7.79 just in case. Also, redownloaded the xmage launcher and started from scratch there. 

I dunno. Didn't have this issue yesterday so I have no idea what could have changed.

http://i74.photobucket.com/albums/i280/NoodlezNightmare/Untitled-1.jpg

**Comment by LevelX2** [comment]
You have to move the action column of the grid of tables to the most right one and restart the XMage client.

There seems to be a bug if you changed the action column position in the order of colmuns it's not correctly handled on restart of the client.

**Comment by LevelX2** [comment]
Fixed with 1.4.0v0.
