### ISSUE TITLE
AI: RadiateTest.test_Play_AI still fails randomly from time to time

### ISSUE THREAD

**Issue by Alex-Vasile** [magefree/mage#9550]
https://github.com/magefree/mage/blob/b5016693652deba8307c067f5dc9a39e392915b4/Mage.Tests/src/test/java/org/mage/test/cards/single/tor/RadiateTest.java#L48-L49

**Comment by JayDi85** [comment]
Fixed by 6f12d6288264649dec20944b547a3dc1cb1f9898, real reason: `MageObject->getIdName` do not return a unique value, last part of the id can be same for diff objects. So it can't be used for a key in maps and sets.
