### ISSUE TITLE
Tomik, Distinguished Advokist doesn't let me target my own lands

### ISSUE THREAD

**Issue by duelcastermage** [magefree/mage#9551]
I had [[Tomik, Distinguished Advokist]] on the battlefield and an [[Awakening of Vitu-Ghazi]] in hand with 3GG mana open on my opponent's end step. I tried casting the Awakening, but XMage wouldn't allow it.

I'm guessing it is because Tomik is programmed to incorrectly give all my lands "shroud" instead of hexproof.

**Comment by awjackson** [comment]
Tomik uses `CantBeTargetedAllEffect` with a filter containing an `ObjectSourcePlayerPredicate`. However, `CantBeTargetedAllEffect` invokes the filter with the two-argument form of `match`, which silently ignores `ObjectSourcePlayerPredicate`s. In fact, `CantBeTargetedAllEffect` is using the base generic class `FilterObject` for the stack object, which doesn't even support four-argument matching or predicates.
