### ISSUE TITLE
Boom // Bust vs Spell Snare and Spellstutter Sprite

### ISSUE THREAD

**Issue by Blitkun** [magefree/mage#956]
I cast Boom // Bust, and my opponent countered it with Spell Snare and Spellstutter Sprite (with another Faerie on the battlefield).
However, client proceeded to destroy the targeted lands, even after considering that the spell was countered, it resolved.

Game Log below: (relevant part is exactly at the end)

<html>
  <head>
    
  </head>
  <body>
    <font color="#CCCC33">12:11 AM: </font><font color="Orange">Blitkun has 
    joined the game</font>
<font color="#CCCC33">: </font><font color="Orange"><br><b>Match score:</b><br>PRSplayer 
    - 0 wins<br>DeckHash: -2265005694992351001<br>Blitkun - 0 wins<br>DeckHash: 
    -1830852543837326731<br><br>You have to win 1 game to win the complete 
    match<br><br>Game has started<br><br></font>
<font color="#CCCC33">12:11 AM: </font><font color="White">Blitkun shuffles 
    his or her library.</font>
<font color="#CCCC33">12:11 AM: </font><font color="White">PRSplayer shuffles 
    his or her library.</font>
<font color="#CCCC33">12:11 AM: </font><font color="White">PRSplayer won the 
    toss</font>
<font color="#CCCC33">12:11 AM: </font><font color="White">PRSplayer chooses 
    that he or she takes the first turn</font>
<font color="#CCCC33">12:11 AM: </font><font color="White">PRSplayer draws 
    seven cards</font>
<font color="#CCCC33">12:11 AM: </font><font color="White">Blitkun draws seven 
    cards</font>
<font color="#CCCC33">12:11 AM: </font><font color="White">PRSplayer keeps hand</font>
<font color="#CCCC33">12:11 AM: </font><font color="White">Blitkun keeps hand</font>
<font color="#CCCC33">12:11 AM: </font><font color="Orange">Turn 1 PRSplayer 
    (20 - 20)</font>
<font color="#CCCC33">12:11 AM: </font><font color="White">PRSplayer plays 
    Celestial Colonnade</font>
<font color="#CCCC33">12:11 AM: </font><font color="White">PRSplayer attacks 
    with 0 creatures</font>
<font color="#CCCC33">12:11 AM: </font><font color="Orange">Turn 2 Blitkun (20 
    - 20)</font>
<font color="#CCCC33">12:11 AM: </font><font color="White">Blitkun draws a card</font>
<font color="#CCCC33">12:11 AM: </font><font color="White">Blitkun plays 
    Mountain</font>
<font color="#CCCC33">12:11 AM: </font><font color="White">Blitkun attacks 
    with 0 creatures</font>
<font color="#CCCC33">12:11 AM: </font><font color="Orange">Turn 3 PRSplayer 
    (20 - 20)</font>
<font color="#CCCC33">12:11 AM: </font><font color="White">PRSplayer draws a 
    card</font>
<font color="#CCCC33">12:11 AM: </font><font color="White">PRSplayer plays 
    Mutavault</font>
<font color="#CCCC33">12:11 AM: </font><font color="White">PRSplayer attacks 
    with 0 creatures</font>
<font color="#CCCC33">12:11 AM: </font><font color="Orange">Turn 4 Blitkun (20 
    - 20)</font>
<font color="#CCCC33">12:11 AM: </font><font color="White">Blitkun draws a card</font>
<font color="#CCCC33">12:12 AM: </font><font color="White">Blitkun plays Arid 
    Mesa</font>
<font color="#CCCC33">12:12 AM: </font><font color="White">Blitkun attacks 
    with 0 creatures</font>
<font color="#CCCC33">12:12 AM: </font><font color="White">PRSplayer casts 
    Anticipate</font>
<font color="#CCCC33">12:12 AM: </font><font color="White">PRSplayer moves a 
    card to hand</font>
<font color="#CCCC33">12:12 AM: </font><font color="White">PRSplayer puts a 
    card from library to the bottom of his or her library</font>
<font color="#CCCC33">12:12 AM: </font><font color="White">PRSplayer puts a 
    card from library to the bottom of his or her library</font>
<font color="#CCCC33">12:12 AM: </font><font color="Orange">Turn 5 PRSplayer 
    (20 - 20)</font>
<font color="#CCCC33">12:12 AM: </font><font color="White">PRSplayer draws a 
    card</font>
<font color="#CCCC33">12:12 AM: </font><font color="White">PRSplayer plays 
    Hallowed Fountain</font>
<font color="#CCCC33">12:12 AM: </font><font color="White">PRSplayer attacks 
    with 0 creatures</font>
<font color="#CCCC33">12:12 AM: </font><font color="White">Blitkun loses 1 life</font>
<font color="#CCCC33">12:12 AM: </font><font color="White">Blitkun sacrificed 
    Arid Mesa</font>
<font color="#CCCC33">12:12 AM: </font><font color="White">Blitkun activates: 
    search your library for a Mountain or Plains and put it onto the 
    battlefield. Then shuffle your library. from Arid Mesa</font>
<font color="#CCCC33">12:12 AM: </font><font color="White">Blitkun searches 
    his or her library</font>
<font color="#CCCC33">12:12 AM: </font><font color="White">Blitkun puts Sacred 
    Foundry from library onto the Battlefield</font>
<font color="#CCCC33">12:12 AM: </font><font color="White">Blitkun shuffles 
    his or her library.</font>
<font color="#CCCC33">12:12 AM: </font><font color="Orange">Turn 6 Blitkun (19 
    - 20)</font>
<font color="#CCCC33">12:12 AM: </font><font color="White">Blitkun draws a card</font>
<font color="#CCCC33">12:12 AM: </font><font color="White">Blitkun plays Arid 
    Mesa</font>
<font color="#CCCC33">12:12 AM: </font><font color="White">Blitkun casts Boom 
    targeting Arid Mesa Celestial Colonnade </font>
<font color="#CCCC33">12:13 AM: </font><font color="White">Blitkun loses 1 life</font>
<font color="#CCCC33">12:13 AM: </font><font color="White">Blitkun sacrificed 
    Arid Mesa</font>
<font color="#CCCC33">12:13 AM: </font><font color="White">Blitkun activates: 
    search your library for a Mountain or Plains and put it onto the 
    battlefield. Then shuffle your library. from Arid Mesa</font>
<font color="#CCCC33">12:13 AM: </font><font color="White">PRSplayer casts 
    Remand targeting Boom </font>
<font color="#CCCC33">12:13 AM: </font><font color="White">PRSplayer puts Boom 
    from stack into its owner's hand</font>
<font color="#CCCC33">12:13 AM: </font><font color="White">PRSplayer draws a 
    card</font>
<font color="#CCCC33">12:13 AM: </font><font color="White">Blitkun searches 
    his or her library</font>
<font color="#CCCC33">12:13 AM: </font><font color="White">Blitkun puts 
    Mountain from library onto the Battlefield</font>
<font color="#CCCC33">12:13 AM: </font><font color="White">Blitkun shuffles 
    his or her library.</font>
<font color="#CCCC33">12:13 AM: </font><font color="White">Blitkun attacks 
    with 0 creatures</font>
<font color="#CCCC33">12:13 AM: </font><font color="Orange">Turn 7 PRSplayer 
    (18 - 20)</font>
<font color="#CCCC33">12:13 AM: </font><font color="White">PRSplayer draws a 
    card</font>
<font color="#CCCC33">12:13 AM: </font><font color="White">PRSplayer plays 
    Flooded Strand</font>
<font color="#CCCC33">12:13 AM: </font><font color="White">PRSplayer casts 
    Soulfire Grand Master</font>
<font color="#CCCC33">12:13 AM: </font><font color="White">PRSplayer attacks 
    with 0 creatures</font>
<font color="#CCCC33">12:14 AM: </font><font color="White">Blitkun casts 
    Lightning Bolt targeting Soulfire Grand Master </font>
<font color="#CCCC33">12:14 AM: </font><font color="White">PRSplayer loses 1 
    life</font>
<font color="#CCCC33">12:14 AM: </font><font color="White">PRSplayer 
    sacrificed Flooded Strand</font>
<font color="#CCCC33">12:14 AM: </font><font color="White">PRSplayer 
    activates: search your library for a Plains or Island and put it onto the 
    battlefield. Then shuffle your library. from Flooded Strand</font>
<font color="#CCCC33">12:14 AM: </font><font color="White">PRSplayer searches 
    his or her library</font>
<font color="#CCCC33">12:14 AM: </font><font color="White">PRSplayer puts 
    Island from library onto the Battlefield</font>
<font color="#CCCC33">12:14 AM: </font><font color="White">PRSplayer shuffles 
    his or her library.</font>
<font color="#CCCC33">12:14 AM: </font><font color="White">PRSplayer casts 
    Spellstutter Sprite</font>
<font color="#CCCC33">12:14 AM: </font><font color="White">Ability triggers: 
    Spellstutter Sprite - When Spellstutter Sprite enters the battlefield, 
    counter target spell with converted mana cost X or less, where X is the 
    number of Faeries you control. - targeting Lightning Bolt </font>
<font color="#CCCC33">12:14 AM: </font><font color="White">Lightning Bolt is 
    countered by Spellstutter Sprite</font>
<font color="#CCCC33">12:14 AM: </font><font color="Orange">Turn 8 Blitkun (18 
    - 19)</font>
<font color="#CCCC33">12:14 AM: </font><font color="White">Blitkun draws a card</font>
<font color="#CCCC33">12:14 AM: </font><font color="White">Blitkun plays Plains</font>
<font color="#CCCC33">12:14 AM: </font><font color="White">Blitkun casts 
    Outpost Siege</font>
<font color="#CCCC33">12:15 AM: </font><font color="White">Outpost Siege: 
    Blitkun has chosen Khans</font>
<font color="#CCCC33">12:15 AM: </font><font color="White">Blitkun attacks 
    with 0 creatures</font>
<font color="#CCCC33">12:15 AM: </font><font color="Orange">Turn 9 PRSplayer 
    (18 - 19)</font>
<font color="#CCCC33">12:15 AM: </font><font color="White">PRSplayer draws a 
    card</font>
<font color="#CCCC33">12:15 AM: </font><font color="White">PRSplayer plays 
    Polluted Delta</font>
<font color="#CCCC33">12:15 AM: </font><font color="White">PRSplayer attacks 
    with 2 creatures</font>
<font color="#CCCC33">12:15 AM: </font><font color="White">Attacker: Soulfire 
    Grand Master (2/2) unblocked</font>
<font color="#CCCC33">12:15 AM: </font><font color="White">Attacker: 
    Spellstutter Sprite (1/1) unblocked</font>
<font color="#CCCC33">12:15 AM: </font><font color="White">Blitkun loses 2 life</font>
<font color="#CCCC33">12:15 AM: </font><font color="White">PRSplayer gains 2 
    life</font>
<font color="#CCCC33">12:15 AM: </font><font color="White">Blitkun loses 1 life</font>
<font color="#CCCC33">12:15 AM: </font><font color="Orange">Turn 10 Blitkun 
    (15 - 21)</font>
<font color="#CCCC33">12:15 AM: </font><font color="White">Ability triggers: 
    Outpost Siege - &#8226; Khans &#8212; At the beginning of your upkeep, exile the top 
    card of your library. Until end of turn, you may play that card.</font>
<font color="#CCCC33">12:15 AM: </font><font color="White">Blitkun moves 
    Chandra, Pyromaster from library to the exile zone</font>
<font color="#CCCC33">12:15 AM: </font><font color="White">Blitkun draws a card</font>
<font color="#CCCC33">12:15 AM: </font><font color="White">Blitkun casts 
    Chandra, Pyromaster</font>
<font color="#CCCC33">12:16 AM: </font><font color="White">PRSplayer 
    sacrificed Polluted Delta</font>
<font color="#CCCC33">12:16 AM: </font><font color="White">PRSplayer loses 1 
    life</font>
<font color="#CCCC33">12:16 AM: </font><font color="White">PRSplayer 
    activates: search your library for a Island or Swamp and put it onto the 
    battlefield. Then shuffle your library. from Polluted Delta</font>
<font color="#CCCC33">12:16 AM: </font><font color="White">PRSplayer searches 
    his or her library</font>
<font color="#CCCC33">12:16 AM: </font><font color="White">PRSplayer puts 
    Island from library onto the Battlefield</font>
<font color="#CCCC33">12:16 AM: </font><font color="White">PRSplayer shuffles 
    his or her library.</font>
<font color="#CCCC33">12:16 AM: </font><font color="White">PRSplayer casts 
    Anticipate</font>
<font color="#CCCC33">12:16 AM: </font><font color="White">PRSplayer moves a 
    card to hand</font>
<font color="#CCCC33">12:16 AM: </font><font color="White">PRSplayer puts a 
    card from library to the bottom of his or her library</font>
<font color="#CCCC33">12:16 AM: </font><font color="White">PRSplayer puts a 
    card from library to the bottom of his or her library</font>
<font color="#CCCC33">12:16 AM: </font><font color="White">Blitkun activates: 
    Chandra, Pyromaster deals 1 damage to target player and 1 damage to up to 
    one target creature that player controls. That creature can't block this 
    turn. from Chandra, Pyromaster targeting PRSplayer Spellstutter Sprite </font>
<font color="#CCCC33">12:16 AM: </font><font color="White">PRSplayer loses 1 
    life</font>
<font color="#CCCC33">12:16 AM: </font><font color="White">Spellstutter Sprite 
    died</font>
<font color="#CCCC33">12:16 AM: </font><font color="White">Blitkun plays Plains</font>
<font color="#CCCC33">12:16 AM: </font><font color="White">Blitkun attacks 
    with 0 creatures</font>
<font color="#CCCC33">12:16 AM: </font><font color="Orange">Turn 11 PRSplayer 
    (15 - 19)</font>
<font color="#CCCC33">12:16 AM: </font><font color="White">PRSplayer draws a 
    card</font>
<font color="#CCCC33">12:17 AM: </font><font color="White">PRSplayer 
    activates: until end of turn Mutavault becomes a 2/2 creature with all 
    creature types that's still a land. from Mutavault</font>
<font color="#CCCC33">12:17 AM: </font><font color="White">PRSplayer attacks 
    with 2 creatures</font>
<font color="#CCCC33">12:17 AM: </font><font color="White">Attacker: Mutavault 
    (2/2) unblocked</font>
<font color="#CCCC33">12:17 AM: </font><font color="White">Attacker: Soulfire 
    Grand Master (2/2) unblocked</font>
<font color="#CCCC33">12:17 AM: </font><font color="White">PRSplayer gains 2 
    life</font>
<font color="#CCCC33">12:17 AM: </font><font color="White">PRSplayer loses 2 
    life</font>
<font color="#CCCC33">12:17 AM: </font><font color="White">PRSplayer plays 
    Hallowed Fountain</font>
<font color="#CCCC33">12:17 AM: </font><font color="Orange">Turn 12 Blitkun 
    (15 - 19)</font>
<font color="#CCCC33">12:17 AM: </font><font color="White">Ability triggers: 
    Outpost Siege - &#8226; Khans &#8212; At the beginning of your upkeep, exile the top 
    card of your library. Until end of turn, you may play that card.</font>
<font color="#CCCC33">12:17 AM: </font><font color="White">Blitkun moves 
    Mountain from library to the exile zone</font>
<font color="#CCCC33">12:17 AM: </font><font color="White">Blitkun draws a card</font>
<font color="#CCCC33">12:17 AM: </font><font color="White">Blitkun plays 
    Mountain</font>
<font color="#CCCC33">12:17 AM: </font><font color="White">Blitkun casts 
    Lightning Helix targeting Soulfire Grand Master </font>
<font color="#CCCC33">12:18 AM: </font><font color="White">PRSplayer casts 
    Cryptic Command (mode 1) targeting Lightning Helix (mode 2) targeting 
    Outpost Siege </font>
<font color="#CCCC33">12:18 AM: </font><font color="White">Lightning Helix is 
    countered by Cryptic Command</font>
<font color="#CCCC33">12:18 AM: </font><font color="White">PRSplayer puts 
    Outpost Siege from battlefield into its owner's hand</font>
<font color="#CCCC33">12:18 AM: </font><font color="White">Blitkun casts Hero 
    of Bladehold</font>
<font color="#CCCC33">12:18 AM: </font><font color="White">Blitkun activates: 
    Chandra, Pyromaster deals 1 damage to target player and 1 damage to up to 
    one target creature that player controls. That creature can't block this 
    turn. from Chandra, Pyromaster targeting PRSplayer Soulfire Grand Master </font>
<font color="#CCCC33">12:19 AM: </font><font color="White">PRSplayer loses 1 
    life</font>
<font color="#CCCC33">12:19 AM: </font><font color="White">Blitkun attacks 
    with 0 creatures</font>
<font color="#CCCC33">12:19 AM: </font><font color="Orange">Turn 13 PRSplayer 
    (15 - 18)</font>
<font color="#CCCC33">12:19 AM: </font><font color="White">PRSplayer draws a 
    card</font>
<font color="#CCCC33">12:19 AM: </font><font color="White">PRSplayer plays 
    Polluted Delta</font>
<font color="#CCCC33">12:19 AM: </font><font color="White">PRSplayer 
    sacrificed Polluted Delta</font>
<font color="#CCCC33">12:19 AM: </font><font color="White">PRSplayer loses 1 
    life</font>
<font color="#CCCC33">12:19 AM: </font><font color="White">PRSplayer 
    activates: search your library for a Island or Swamp and put it onto the 
    battlefield. Then shuffle your library. from Polluted Delta</font>
<font color="#CCCC33">12:19 AM: </font><font color="White">PRSplayer searches 
    his or her library</font>
<font color="#CCCC33">12:19 AM: </font><font color="White">PRSplayer shuffles 
    his or her library.</font>
<font color="#CCCC33">12:19 AM: </font><font color="White">PRSplayer puts 
    Island from library onto the Battlefield</font>
<font color="#CCCC33">12:19 AM: </font><font color="White">PRSplayer casts 
    Anticipate</font>
<font color="#CCCC33">12:19 AM: </font><font color="White">PRSplayer moves a 
    card to hand</font>
<font color="#CCCC33">12:19 AM: </font><font color="White">PRSplayer puts a 
    card from library to the bottom of his or her library</font>
<font color="#CCCC33">12:19 AM: </font><font color="White">PRSplayer puts a 
    card from library to the bottom of his or her library</font>
<font color="#CCCC33">12:19 AM: </font><font color="White">PRSplayer casts 
    Path to Exile targeting Hero of Bladehold </font>
<font color="#CCCC33">12:19 AM: </font><font color="White">PRSplayer moves 
    Hero of Bladehold from battlefield to the exile zone</font>
<font color="#CCCC33">12:20 AM: </font><font color="White">Blitkun searches 
    his or her library</font>
<font color="#CCCC33">12:20 AM: </font><font color="White">Blitkun shuffles 
    his or her library.</font>
<font color="#CCCC33">12:20 AM: </font><font color="White">Blitkun puts Plains 
    from library onto the Battlefield</font>
<font color="#CCCC33">12:20 AM: </font><font color="White">PRSplayer 
    activates: until end of turn Mutavault becomes a 2/2 creature with all 
    creature types that's still a land. from Mutavault</font>
<font color="#CCCC33">12:20 AM: </font><font color="White">PRSplayer attacks 
    with 2 creatures</font>
<font color="#CCCC33">12:20 AM: </font><font color="White">Attacker: Mutavault 
    (2/2) unblocked</font>
<font color="#CCCC33">12:20 AM: </font><font color="White">Attacker: Soulfire 
    Grand Master (2/2) unblocked</font>
<font color="#CCCC33">12:20 AM: </font><font color="White">Blitkun loses 2 life</font>
<font color="#CCCC33">12:20 AM: </font><font color="White">PRSplayer gains 2 
    life</font>
<font color="#CCCC33">12:20 AM: </font><font color="White">Chandra, Pyromaster 
    is put into graveyard from battlefield</font>
<font color="#CCCC33">12:20 AM: </font><font color="Orange">Turn 14 Blitkun 
    (13 - 19)</font>
<font color="#CCCC33">12:20 AM: </font><font color="White">Blitkun draws a card</font>
<font color="#CCCC33">12:20 AM: </font><font color="White">Blitkun casts 
    Outpost Siege</font>
<font color="#CCCC33">12:20 AM: </font><font color="White">Outpost Siege: 
    Blitkun has chosen Khans</font>
<font color="#CCCC33">12:20 AM: </font><font color="White">Blitkun plays 
    Flagstones of Trokair</font>
<font color="#CCCC33">12:21 AM: </font><font color="White">Blitkun casts Boom 
    targeting Flagstones of Trokair Celestial Colonnade </font>
<font color="#CCCC33">12:21 AM: </font><font color="White">PRSplayer casts 
    Spell Snare targeting Boom </font>
<font color="#CCCC33">12:21 AM: </font><font color="White">Boom is countered 
    by Spell Snare</font>
<font color="#CCCC33">12:21 AM: </font><font color="White">Flagstones of 
    Trokair was destroyed</font>
<font color="#CCCC33">12:21 AM: </font><font color="White">Celestial Colonnade 
    was destroyed</font>
<font color="#CCCC33">12:21 AM: </font><font color="White">Ability triggers: 
    Flagstones of Trokair - When Flagstones of Trokair is put into a graveyard 
    from the battlefield, you may search your library for a Plains card and 
    put it onto the battlefield tapped. Then shuffle your library.</font>
<font color="#CCCC33">12:22 AM: </font><font color="White">Blitkun searches 
    his or her library</font>
<font color="#CCCC33">12:22 AM: </font><font color="White">Blitkun puts Sacred 
    Foundry from library onto the Battlefield</font>
<font color="#CCCC33">12:22 AM: </font><font color="White">Blitkun shuffles 
    his or her library.</font>
<font color="#CCCC33">12:22 AM: </font><font color="White">Blitkun attacks 
    with 0 creatures</font>
<font color="#CCCC33">12:22 AM: </font><font color="Orange">Turn 15 PRSplayer 
    (13 - 19)</font>
<font color="#CCCC33">12:22 AM: </font><font color="White">PRSplayer draws a 
    card</font>
<font color="#CCCC33">12:22 AM: </font><font color="White">PRSplayer 
    activates: until end of turn Mutavault becomes a 2/2 creature with all 
    creature types that's still a land. from Mutavault</font>
<font color="#CCCC33">12:22 AM: </font><font color="White">PRSplayer attacks 
    with 2 creatures</font>
<font color="#CCCC33">12:22 AM: </font><font color="White">Attacker: Mutavault 
    (2/2) unblocked</font>
<font color="#CCCC33">12:22 AM: </font><font color="White">Attacker: Soulfire 
    Grand Master (2/2) unblocked</font>
<font color="#CCCC33">12:22 AM: </font><font color="White">Blitkun loses 2 life</font>
<font color="#CCCC33">12:22 AM: </font><font color="White">Blitkun loses 2 life</font>
<font color="#CCCC33">12:22 AM: </font><font color="White">PRSplayer gains 2 
    life</font>
<font color="#CCCC33">12:22 AM: </font><font color="Orange">Turn 16 Blitkun (9 
    - 21)</font>
<font color="#CCCC33">12:22 AM: </font><font color="White">Ability triggers: 
    Outpost Siege - &#8226; Khans &#8212; At the beginning of your upkeep, exile the top 
    card of your library. Until end of turn, you may play that card.</font>
<font color="#CCCC33">12:23 AM: </font><font color="White">Blitkun moves Boom 
    // Bust from library to the exile zone</font>
<font color="#CCCC33">12:23 AM: </font><font color="White">Blitkun draws a card</font>
<font color="#CCCC33">12:23 AM: </font><font color="White">Blitkun casts 
    Oblivion Ring</font>
<font color="#CCCC33">12:23 AM: </font><font color="White">Ability triggers: 
    Oblivion Ring - When Oblivion Ring enters the battlefield, Exile target 
    another nonland permanent. - targeting Soulfire Grand Master </font>
<font color="#CCCC33">12:23 AM: </font><font color="White">Blitkun moves 
    Soulfire Grand Master from battlefield to the exile zone</font>
<font color="#CCCC33">12:24 AM: </font><font color="White">Blitkun casts Boom 
    targeting Plains Mutavault </font>
<font color="#CCCC33">12:24 AM: </font><font color="White">PRSplayer 
    activates: until end of turn Mutavault becomes a 2/2 creature with all 
    creature types that's still a land. from Mutavault</font>
<font color="#CCCC33">12:24 AM: </font><font color="White">PRSplayer casts 
    Spellstutter Sprite</font>
<font color="#CCCC33">12:24 AM: </font><font color="White">Ability triggers: 
    Spellstutter Sprite - When Spellstutter Sprite enters the battlefield, 
    counter target spell with converted mana cost X or less, where X is the 
    number of Faeries you control. - targeting Boom </font>
<font color="#CCCC33">12:24 AM: </font><font color="White">Boom is countered 
    by Spellstutter Sprite</font>
<font color="#CCCC33">12:24 AM: </font><font color="White">Plains was destroyed</font>
<font color="#CCCC33">12:24 AM: </font><font color="White">Mutavault died</font>
<font color="#CCCC33">12:26 AM: </font><font color="White">PRSplayer has won 
    the game</font>
<font color="#CCCC33">12:26 AM: </font><font color="White">Blitkun has 
    conceded.</font>
<font color="#CCCC33">12:26 AM: </font><font color="White">Blitkun has lost 
    the game.</font>
  </body>
</html>

**Comment by drmDev** [comment]
will need to test later

**Comment by drmDev** [comment]
Unable to duplicate - old issue. closing
