### ISSUE TITLE
Token copies of Chasm Skulker do not produce tokens when they die

### ISSUE THREAD

**Issue by Greeneye0** [magefree/mage#957]
When the token with +1/+1 counters die the squid tokens do not appear:
![image](https://cloud.githubusercontent.com/assets/11687236/7527251/b22cc270-f4d6-11e4-9d87-ce03424aeded.png)

**Comment by Greeneye0** [comment]
Sorry, in this case it looks like it was a clone that died, not a token. But I believe the results are the same for a token

**Comment by drmDev** [comment]
Unclear what the issue is here. Only when Chasm Skulker dies should a token be created. "When Chasm Skulker dies, put X 1/1 blue Squid creature tokens with islandwalk onto the battlefield, where X is the number of +1/+1 counters on Chasm Skulker"
