### ISSUE TITLE
Empty Catch block in try-catch inside DraftImpl

### ISSUE THREAD

**Issue by Alex-Vasile** [magefree/mage#9573]
Several of the functions inside DraftImpl (and possible elsewhere) use a try-catch block. But the catch block is completely empty, there isn't even a comment stating if this is on purpose or not. This needs to be investigated. E.g.
https://github.com/magefree/mage/blob/7926193e34cfea7802f2db2a727227452bb22950/Mage/src/main/java/mage/game/draft/DraftImpl.java#L216-L224

**Comment by JayDi85** [comment]
InterruptedException - it’s default code style for any thread sync/waiting code. If you rename exception param to ignore then IDE will stop highlighting it as wrong.

Well, its little smells due wait usage without timeout param (e.g. that infinite waiting pick can freeze forever or until it will be interrupted from another thread). But I’m not sure that its a problem — don't know about freezes drafts/picks.
