### ISSUE TITLE
Duplicate of #9562

### ISSUE THREAD

**Issue by catman123456** [magefree/mage#9575]
Duplicate of #9562

_Originally posted by @awjackson in https://github.com/magefree/mage/issues/9568#issuecomment-1257090017_

**Comment by catman123456** [comment]
![image](https://user-images.githubusercontent.com/64045003/192171119-3ad72aad-d39b-49db-9146-a0967de0a942.png)

Game exception occurred: java.lang.ClassCastException: mage.game.permanent.PermanentToken cannot be cast to mage.game.permanent.token.Token
Server version: 1.4.52-V1-beta4 (build: 2022-09-24 06:33)
mage.watchers.common.CreatedTokenWatcher.watch(CreatedTokenWatcher.java:34)
mage.watchers.Watchers.watch(Watchers.java:34)
mage.game.GameState.handleEvent(GameState.java:817)
mage.game.GameState.handleSimultaneousEvent(GameState.java:792)
mage.abilities.AbilityImpl.resolveMode(AbilityImpl.java:226)
mage.abilities.AbilityImpl.resolve(AbilityImpl.java:185)
mage.abilities.TriggeredAbilityImpl.resolve(TriggeredAbilityImpl.java:149)
mage.game.stack.StackAbility.resolve(StackAbility.java:89)
mage.game.GameImpl.resolve(GameImpl.java:1634)
mage.game.GameImpl.playPriority(GameImpl.java:1560)
mage.game.turn.Step.priority(Step.java:61)
mage.game.turn.Phase.playStep(Phase.java:184)
mage.game.turn.Phase.play(Phase.java:89)
mage.game.turn.Turn.play(Turn.java:132)
mage.game.GameImpl.playTurn(GameImpl.java:1055)
mage.game.GameImpl.play(GameImpl.java:965)
mage.game.GameImpl.start(GameImpl.java:941)
mage.server.game.GameWorker.call(GameWorker.java:34)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)

**Comment by Alex-Vasile** [comment]
This like the duplicate has already been fixed. Will be out in next beta.
