### ISSUE TITLE
"An Error Occurred on the Mage Server" when making tokens.

### ISSUE THREAD

**Issue by BasiliskXVIII** [magefree/mage#9579]
This is something that's only been happening since the most recent update. Any time a token is created, the system demands a rollback, which can often lead to an inescapable loop. Error is as a follows: 

Game exception occurred: java.lang.ClassCastException
Server version: 1.4.52-V1-beta4 (build: 2022-09-24 06:33)

**Comment by Grath** [comment]
[#9562](https://github.com/magefree/mage/issues/9562) is already fixed for next release of beta, take Idol of Oblivion, Bennie Bracks, Thalisse, Ellyn Harbreeze, or Vazi Keen out of the deck to stop getting it.
