### ISSUE TITLE
[DMU] Can't activate the ability on Karn's emblem

### ISSUE THREAD

**Issue by Alex-Vasile** [magefree/mage#9585]
[[Karn, Living Legacy]]

It does not shown as tappable and tapping on it does nothing.

~~[[Ob Nixilis of the Black Oath]] may have a similar issue since it also has an activated ability.~~

![image](https://user-images.githubusercontent.com/48962821/192621661-c15820fa-3164-4024-b00f-5ec222a43bcf.png)

**Comment by PurpleCrowbar** [comment]
Just tested, Ob Nixilis of the Black Oath works as expected
