### ISSUE TITLE
Xmage not working

### ISSUE THREAD

**Issue by JobieParr** [magefree/mage#959]
I have been using Xmage for the last week or so and it has been working fine until now. Whenever I try to open Xmage and I click on the Launch Client and Server option it tells me "Error:could not open 'C:\Users\Name\Downloads\java\jre1.7.0_75\lib\amd64\jvm.cfg'  Does anyone know what is causing this and how I would fix it?

**Comment by LevelX2** [comment]
Did you install other java applications meanwhile?
Maybe you have a problem like described here:
http://jaykhimani.blogspot.de/2012/09/error-could-not-open-cprogram.html

Where the java.exe files were also installed to the windows C:\Windows\System32\ directory causing the problem.

**Comment by JobieParr** [comment]
...so how do I fix it? lol or erase the Java applications completely

**Comment by JobieParr** [comment]
I got it fixed. Thank you for your help

**Comment by LevelX2** [comment]
> I got it fixed. Thank you for your help

What caused the problem or how did you fix it?

**Comment by JobieParr** [comment]
I just simply deleted the old Java from my computer, reinstalled the newest
version, opened up the Xmage launcher, forced an update and the launched
the client and server and it worked.

**Comment by LevelX2** [comment]
Thanks for the reply.
