### ISSUE TITLE
[NCC] Phabine, Boss's Confidant  bugged

### ISSUE THREAD

**Issue by satchmosanzabar** [magefree/mage#9603]
Greetings,

The "creatures you control get +1/+1 until end of turn" part of Phabine's trigger never works. Also, I've randomly had her not create citizen tokens when land cards are revealed, but I'm not sure how to reproduce that part.

Regards

**Comment by Alex-Vasile** [comment]
[[Phabine, Boss's Confidant]]

**Comment by theelk801** [comment]
@Alex-Vasile it's because the effect is using `effect.apply` instead of `game.addEffect`, which I'm pretty sure I should have caught when I was reviewing

**Comment by Alex-Vasile** [comment]
> @Alex-Vasile it's because the effect is using `effect.apply` instead of `game.addEffect`, which I'm pretty sure I should have caught when I was reviewing

A ha! Thank you. I was trying to figure out why the boost effect disappears after being applied to the tokens.

The other issue is that I had incorrectly assumed that Parley.count returns the number of nonLandCards, and *not* the number of land cards.
