### ISSUE TITLE
Zaxara creating tokens on every single cast

### ISSUE THREAD

**Issue by LegionedintheDamned** [magefree/mage#9606]
[[Zaxara, the Exemplary]] has started creating tokens on every single cast since the new update.  It should only be on X spells.

![image](https://user-images.githubusercontent.com/82664393/193380043-33b0cad2-ff55-435f-81ae-3931bbf5bc50.png)

**Comment by PurpleCrowbar** [comment]
Duplicate of #9597, fixed by 5fa9a850b1f5eee2bde490d9d1c4f722c85da5f6, will be fixed next time the beta is updated
