### ISSUE TITLE
Jace, Telepath Unbound can't cast split cards from graveyard

### ISSUE THREAD

**Issue by stevedavidmusic** [magefree/mage#9607]
Ran into an issue where Jace, Telepath Unbound cannot cast split cards like Fire // Ice from the graveyard with its -3 ability. Might be related to #9365, where Jace, Telepath Unbound also can't cast MDFCs from the graveyard. Snapcaster Mage works fine with split cards / MDFCs though. 

<img width="1272" alt="Screen Shot 2022-10-01 at 11 36 19 AM" src="https://user-images.githubusercontent.com/45299811/193419309-7c889914-c37a-4aae-a800-5c1eea72dc93.png">

**Comment by Susucre** [comment]
Same as #10272

**Comment by Susucre** [comment]
Improvements and refactor on play/cast effects have solved this one already (added test to prove it.)
