### ISSUE TITLE
Zaxara, the Exemplary does not trigger when you cast a spell with X in its mana cost

### ISSUE THREAD

**Issue by Yamorama** [magefree/mage#9608]
I tried multiple X cost spells, mostly hydras, and Zaxara would not trigger. However, if you cast a non X cost spell, Zaxara would sometimes trigger, which he shouldn't, and create a 0/0 hydra that would immediately die. I'm not sure why but his main effect does not seem to be working.

**Comment by Alex-Vasile** [comment]
Duplicate of #9597. Fix will be live in next beta
