### ISSUE TITLE
[LEG] Bronze Horse - bug incorrectly prevents combat damage

### ISSUE THREAD

**Issue by xenohedron** [magefree/mage#9614]
[[Bronze Horse]] should only prevent damage by spells that target it (when condition is met). It has been observed to prevent combat damage.

Relevant oracle text reads "As long as you control another creature, prevent all damage that would be dealt to Bronze Horse by spells that target it."

**Comment by awjackson** [comment]
This seems to related to rollbacks somehow. If I never rollback (including cancelling mana abilities) the card works correctly, but as soon as I cancel an action even once, the card starts preventing damage when it shouldn't (though it never prevents damage to anything other than itself).

**Comment by awjackson** [comment]
It's just a missing copy constructor issue. When the card's custom effect gets copied it gets "sliced" down to its super class, `PreventAllDamageToSourceEffect`

**Comment by awjackson** [comment]
I'm now looking at other custom damage prevention effects and two of the first three I looked at (Argothian Treefolk and Enchanted Being) were likewise missing copy constructors. This could be a very widespread issue.
