### ISSUE TITLE
[MH1] Spiteful Sliver - changelings should get the ability

### ISSUE THREAD

**Issue by xenohedron** [magefree/mage#9615]
Controlled a Venomous Changeling and a [[Spiteful Sliver]], the changeling was dealt 5 damage in combat but did not trigger to deal damage to player. The effect does work for Spiteful Sliver itself.

**Comment by awjackson** [comment]
Same issue as #9129 and likewise fixed by 665e47634dd9a813f207171ceb82bbb3696e6a7f.
