### ISSUE TITLE
Rewind untaps lands when it fizzles

### ISSUE THREAD

**Issue by HadesThemself** [magefree/mage#9622]
I cast [[Rewind]] which then fizzled due to my opponents [[Autumn Veil]] , but I was still prompted to untap lands despite the ruling:

"If the spell is an illegal target when Rewind tries to resolve, perhaps because it was countered by another spell or ability, Rewind won't resolve and none of its effects will happen. You won't untap any lands."

We were playing 2 player EDH on the beta client 1.4.51-dev (2022-09-30 05-18).

**Comment by awjackson** [comment]
Autumn's Veil does not say "spells cannot be the targets...", it says they "can't be countered". The spell remains a legal target and Rewind still resolves, its "counter" effect just doesn't do anything. This is the correct interaction.

**Comment by HadesThemself** [comment]
It's on the gatherer page, that's where I quoted from.
https://gatherer.wizards.com/pages/card/details.aspx?multiverseid=5670

**Comment by theelk801** [comment]
the gatherer rulings mention illegal targets, which is not the case in this situation as the spell being uncounterable doesn't actually make it an illegal target
