### ISSUE TITLE
[BUG] Curse of Opulence not triggering?

### ISSUE THREAD

**Issue by satchmosanzabar** [magefree/mage#9623]
![image](https://user-images.githubusercontent.com/69054847/194317549-05c7866a-01d5-491e-882d-fe342f5aad73.png)

Hello,

On the turn I played Curse of Opulence, I attacked the player I targeted with it, but it did not trigger. I did not get my precious gold token :(

**Comment by satchmosanzabar** [comment]
again, same game 
![image](https://user-images.githubusercontent.com/69054847/194318492-5dc31057-0d65-4116-9d7d-c5f5730071f3.png)

**Comment by satchmosanzabar** [comment]
Works for my opponents though!? :)

![image](https://user-images.githubusercontent.com/69054847/194320594-2a23b481-c5df-4616-9ccc-0f23b4f3b5b5.png)

**Comment by PurpleCrowbar** [comment]
Just tested and confirmed this, pretty sure it's a regression

**Comment by awjackson** [comment]
Seems to be another regression caused by https://github.com/magefree/mage/commit/fd16f2a16b19c273839d11abfa6f8535db03e07a
