### ISSUE TITLE
Satyr Firedancer activating too often.

### ISSUE THREAD

**Issue by Bivvz** [magefree/mage#963]
I played a game last night where satyr firedancer's ability to copy a sorcery/instant's damage this turn and apply it to a creature was activating way too much.  My opponent casted Hordeling Outburst and any time those goblins attacked me the satyr firedancer activated his ability.  I'm not positive but it may have also been activating on sorcery/instants with no damage component at all.

I'm sorry if I'm just misunderstanding the card.

Thanks

**Comment by ERWINhodo** [comment]
No, that's definitely incorrect and I can confirm that I'm seeing the same thing. I was making newbie decks to teach a friend with and we had to edit the red one because Satyr Firedancer was glitched.
