### ISSUE TITLE
Mila, Crafty Companion token in Momir has Luka, Wayward Bonder's abilities

### ISSUE THREAD

**Issue by Taylor3621** [magefree/mage#9639]
Pretty self explanatory. I was playing Momir Basic, and somehow, the token of [[Mila, Crafty Companion]] had [[Luka, Wayward Bonder]]'s loyalty abilities, which could be activated.

![image](https://user-images.githubusercontent.com/107843203/194816400-2b8468df-44c3-41d5-ace4-82c58bd739e6.png)

**Comment by awjackson** [comment]
Duplicate of #8476
