### ISSUE TITLE
PutCards usage must be reworked

### ISSUE THREAD

**Issue by JayDi85** [magefree/mage#9643]
New code uses `PutCards` objects instead standard zones and details (example changes: e40934921fcdb56f582567bd974761d3eb5a2444)

![shot_221011_102101](https://user-images.githubusercontent.com/8344157/195011685-da419bf7-a126-45c3-96af-4a98d4be81f6.png)

This list will change indefinitely. Already changing and duplicating similar cases (`BATTLEFIELD` and `BATTLEFIELD_TAPPED`, `BOTTOM_ANY` and `BOTTOM_RANDOM`, etc). All that code will be broken on new `PutCards` elements. It's popular bugs style with miss/unsupported elements in if/switch and you can't catch that bug until user report (example: TargetController).

![shot_221011_103923](https://user-images.githubusercontent.com/8344157/195016899-d4ea43d8-78ed-4cfb-93fc-b6886051186d.png)

So code logic must goes from inside, not from the name. And works with element's params:
![shot_221011_102733](https://user-images.githubusercontent.com/8344157/195012620-138c0676-580c-486f-abfd-e6e084a0f653.png)

Also naming style must be same, so `TOP_ANY` -> `LIBRARY_TOP_ANY`, `BOTTOM_ANY` -> `LIBRARY_BOTTOM_ANY`, etc.

**Comment by awjackson** [comment]
Is #9644 what you had in mind?

**Comment by awjackson** [comment]
I know the text generation logic for `LookLibraryAndPickControllerEffect` looks horribly convoluted, but it is the result of me "reverse engineering" the templating of hundreds of actual cards. It can't be standardized or parametrized any more than it is or it won't match the real card texts and many more cards will need hardcoded 'setText'.

**Comment by JayDi85** [comment]
> Is 9644 what you had in mind?

@awjackson Definitely not about this

I told about if/switch cases. 

Example: 
* must use `putIt.getZone() == Zone.BATTLEFIELD` 
* instead checking `putIt == PutCards.BATTLEFIELD || putIt == PutCards.BATTLEFIELD_TAPPED`

**Comment by JayDi85** [comment]
But it's ok to keep your refactor. Also I recommends to add Exception instead default move (it will raise error and informs dev about miss command).

**Comment by awjackson** [comment]
The `default` case is not an error, it is the code path for values of `PutCards` that don't require a unique `Player` method call.

**Comment by JayDi85** [comment]
BTW it's a good practice to add exception instead error/warn log. The sooner the problem appears, the better for us. Many poorly-used cards can be buggy for years until someone accidentally notices it.

**Comment by awjackson** [comment]
Added comments to clarify what the `default` cases are for.

**Comment by JayDi85** [comment]
> The default case is not an error, it is the code path for values of PutCards that don't require a unique Player method call.

It's a good example of hard finding bug from my original comment -- if new dev adds additional element to PutCards, then it can broken something due miss supporting code inside engine.

P.S. Also noticed about miss PutCards.BATTLEFIELD here. It's looked like a bug even if it require a default move. I recommends to process as much as possible elements -- it's a good practice. IntelliJ IDEA has special check for miss switch elements.

![shot_221011_141000](https://user-images.githubusercontent.com/8344157/195063188-116fea02-f204-4829-9849-6549e856bf93.png)

**Comment by awjackson** [comment]
okay, all elements are now explicitly handled in both switches and default now throws an exception.
