### ISSUE TITLE
Blinking a modal card does not force it face-up.

### ISSUE THREAD

**Issue by Tharkon** [magefree/mage#9646]
I cast [[Ghostly Flicker]] on [[Glasspool Shore]].
This should cause it to enter the battlefield as [[Glasspool Mimic]], since that is its front face.
But instead it just enters as Glasspool Shore.

> Rule 712.10. A double-faced card put onto the battlefield from a zone other than the stack enters the
> battlefield with its front face up by default.

**Comment by xenohedron** [comment]
Checked this interaction with latest build and it now works correctly. There is an existing unit test for a similar interaction with flickering an MDFC, though could add another test for this version that returns immediately rather than at end step.
