### ISSUE TITLE
Gustha's Scepter doesn't trigger on losing control, nor does it put cards into graveyard

### ISSUE THREAD

**Issue by PurpleCrowbar** [magefree/mage#9676]
[[Gustha's Scepter]]'s third paragraph reads:
> When you lose control of Gustha’s Scepter, put all cards exiled with Gustha’s Scepter into their owner’s graveyard.

In xmage, this ability does not trigger on losing control by means of an opponent gaining control of the permanent (e.g., the original controller casts Harmless Offering on it, causing an opponent to gain control of it). The ability *does* trigger when the permanent is destroyed under your control, but not whenever you lose control of it by any other means. In addition, the effect of the cards exiled with Gustha's Scepter going to the graveyard doesn't do anything - the ability goes on the stack, resolves, and nothing happens, the cards remain in exile. The only part of this card that seems to function is the second activated ability.

**Comment by xenohedron** [comment]
see #11133 for a possible root cause
