### ISSUE TITLE
Raggadragga not showing up in deck editor

### ISSUE THREAD

**Issue by savi0r117** [magefree/mage#9680]
The only thing I found here on the github says he was implemented, but when I go to add him to a deck he doesn't show up. I have no clue how this works but figured I could mention it here.

**Comment by copperfield42** [comment]
I check and it was implement the oct 22, the current beta was release the oct 15, in the next beta you can play with it... 
(I don't know when they will release the next beta)

**Comment by copperfield42** [comment]
the new beta is up, now you can play with Raggadragga to your heart content XD
