### ISSUE TITLE
Industrial Advancement not triggering death triggers

### ISSUE THREAD

**Issue by dashosa** [magefree/mage#9688]
![image](https://user-images.githubusercontent.com/63882410/198353130-ea64c667-02b8-42d3-a5d7-48bff073337c.png)

Something I noticed a few times is that Industrial Advancement ignores the death triggers of creatures it sacrifices; I might be missing something ruling-wise, but couldn't figure it out.

**Comment by Alex-Vasile** [comment]
[[Industrial Advancement]]
