### ISSUE TITLE
java.lang.null.exception error

### ISSUE THREAD

**Issue by salyG** [magefree/mage#970]
i am sorry to trouble but i need help. What is this?

FATAL 2015-05-15 09:51:12,266 Communication error                                                                        =>[pool-1-thread-1] SessionImpl.handleThrowable 
java.lang.NullPointerException

**Comment by LevelX2** [comment]
Try to connect to xmage.de instead of woogerworks.com.

**Comment by salyG** [comment]
okay sure.thank you
