### ISSUE TITLE
[MID][VOW] Most of the variant double-faced cards lack backside art

### ISSUE THREAD

**Issue by sprangg** [magefree/mage#9701]
Crimson Vow has three cycles of variant cards, the Dracula-themed, black-and-white, and alt art/frame. I've tested most of them, and the only one that I've seen show any art on the backside is [this version of Jacob Hauken, Inspector](https://scryfall.com/card/vow/320/jacob-hauken-inspector-haukens-insight). The other variant versions of that card don't show any backside art.

Edit: Midnight Hunt double-faced cards are suffering from the same issue.

**Comment by Alex-Vasile** [comment]
Something strange is indeed happening. For me, I am getting back side arts on everything I try, but it doesn't always match. E.g. this [Dorothea](https://scryfall.com/card/vow/322/dorothea-vengeful-victim-dorotheas-retribution) has the correct BW front, but uses the regular back for some reason.

**Comment by sprangg** [comment]
Alright, figured out something more. This happens because for all the VOW double-faced cards, xmage downloads only one of the backside images no matter how many variants there are.

This doesn't seem to be a systematic problem in xmage though, because at least the ZNR double-faced cards have all their backside variants downloaded correctly.

**Comment by Alex-Vasile** [comment]
Also reported: "I have the back out for the promo Tolvar downloaded, when I look at it in the deck editor I can flip and see the back. But when I'm actually in game, when Tolvar flips it doesn't show the image."

**Comment by sprangg** [comment]
I think I found a fix for this. Going to test and PR if it works.

**Comment by JayDi85** [comment]
Fixed by 4e9ffdfaf95521ad402e2d87904d7869fe4e7a35
