### ISSUE TITLE
[BUG] Baba Lysaga , Night Witch not counting multiple card types

### ISSUE THREAD

**Issue by satchmosanzabar** [magefree/mage#9703]
Greetings,

When using Baba Lysaga, Night Witch's activated ability, and sacrificing less than 3 permanents, the draw 3 cards and life gain / life loss part of the trigger doesn't work. I ensured that of the two permanents I sacrificed, one was both a creature and a land, and the other was an artifact. This has happened both times I have tried to play this card, with various cards as sacrifice targets.

**Comment by Alex-Vasile** [comment]
[[Baba Lysaga, Night Witch]]

**Comment by PurpleCrowbar** [comment]
It seems like Baba Lysaga fails to recognise *gained* card types. E.g. I tried sacrificing a [[Nyxborn Seaguard]] (Creature and Enchantment) and [[Lodestone Golem]] (Creature and Artifact), which is 2 creatures, and it successfully triggered the effect as expected, as it recognised the creature, enchantment, and artifact card types. Testing with a [[Mycosynth Lattice]] to make the Nyxborn Seaguard into an artifact (so creature, enchantment, and artifact on one card) and *just* sacrificing the Seaguard to Baba Lysaga caused the effect not to trigger. This would also explain why the card does not work as expected with [[Inkmoth Nexus]], as it is not considering the newly gained creature and artifact types.

**Comment by MrOppsokopolis** [comment]
I'm new to the codebase, but here's my cursory look. I'm guessing the `game` parameter is null when Baba's effect calls `apply`, resulting in checking only static types of the sacrificed permanents rather than the dynamic types.

In `mage\Mage\src\main\java\mage\MageObjectImpl.java`:
```java
    @Override
    public List<CardType> getCardType(Game game) {
        if (game != null) {
            // dynamic
            MageObjectAttribute mageObjectAttribute = game.getState().getMageObjectAttribute(getId());
            if (mageObjectAttribute != null) {
                return mageObjectAttribute.getCardType();
            }
        }

        // static
        return cardType;
    }
```

In `mage\Mage.Sets\src\mage\cards\b\BabaLysagaNightWitch.java`:
```java
    @Override
    public boolean apply(Game game, Ability source) {
        if (CardUtil
                .castStream(source.getCosts().stream(), SacrificeTargetCost.class)
                .filter(Objects::nonNull)
                .map(SacrificeTargetCost::getPermanents)
                .flatMap(Collection::stream)
                .map(permanent -> permanent.getCardType(game)) // for some reason "game" is null?
                .flatMap(Collection::stream)
                .distinct()
                .count() < 3) {
            return false;
        }
```
This could easily be wrong, but I wanted to contribute what I could if someone wanted to try fixing this.

**Comment by Susucre** [comment]
Same bug as #10210
