### ISSUE TITLE
Cadric, Soul Kindler's tokens are considered legendary

### ISSUE THREAD

**Issue by GallinaFina** [magefree/mage#9708]
As the card states, the legend rule shouldn't apply to [Cadric, Soul Kindler]'s tokens, but it seems like it does.
![cadric](https://user-images.githubusercontent.com/112827360/198861176-c7591415-be08-4bf0-bc9c-1c0a80f402b0.png)

**Comment by awjackson** [comment]
Duplicate of #9691
