### ISSUE TITLE
[SOI] Bound by Moonsilver - enchanted creatures can transform

### ISSUE THREAD

**Issue by brotendomtg** [magefree/mage#9709]
I had a game where a creature (Solitary Hunter) enchanted by Bound by Moonsilver transformed several times

![Screenshot 2022-10-30 000807](https://user-images.githubusercontent.com/114497501/198862190-2c0b6466-27c0-4deb-ab2a-544da3d4aa8b.png)

**Comment by awjackson** [comment]
There were two completely different implementations of "can't transform", each used by exactly one card. Bound By Moonsilver used a `RestrictionEffect` (which didn't work) and Immerwolf used a `ContinuousRuleModifyingEffectImpl` (which did work, but was extremely annoying UI-wise). I fixed the `RestrictionEffect` version, simplified it a little (`RestrictionEffect.canTransform` didn't need all those parameters, the checking was already done in `applies`) and made both cards use it.
