### ISSUE TITLE
Login for the card implementation list?

### ISSUE THREAD

**Issue by ImperatorPrime** [magefree/mage#971]
I'm posting this here because I'm not sure where else to put this. How does one get a login for the card list?

**Comment by LevelX2** [comment]
You mean the Card Trecker i guess.
I can create you an account but I near an email address or an forum account where I can send the Dara to from you.

**Comment by ImperatorPrime** [comment]
The ideal email would be imperatorprime@hotmail.com.

I have an account on the forum as Imperator.

**Comment by LevelX2** [comment]
I send you the profile data to your forum account.
