### ISSUE TITLE
[MH2] Endurance problem

### ISSUE THREAD

**Issue by Alex-Vasile** [magefree/mage#9717]
"i can't choose target player with [[Endurance]], i'm putting envoke trigger above the shuffle trigger and i can't choose target player when i have trigger on resolve, it just fizzles"

From Discord.

**Comment by awjackson** [comment]
I can't reproduce this, and the person reporting it seems not to understand the rules (you choose targets for triggered abilities as you put the trigger on the stack, not as they resolve).
