### ISSUE TITLE
Dredge does let you pick the order of the cards going to the graveyard

### ISSUE THREAD

**Issue by jmharmon** [magefree/mage#9723]
The title basically says it all. This is on the beta server. I have checked and unchecked the preference where it asks for this options.

**Comment by jeffwadsworth** [comment]
When multiple cards enter the Graveyard at the same time, their owner chooses their relative order.

**Comment by jeffwadsworth** [comment]
What is the problem here, OP?  Dredge works as intended unless I am misunderstanding your issue report.
