### ISSUE TITLE
No life link on triggered abilityMogis + Whip of ere

### ISSUE THREAD

**Issue by Greeneye0** [magefree/mage#973]
Since Mogis does the damage the Player should be gaining life when the ability happens and the other player selects to take 2 damage:
![image](https://cloud.githubusercontent.com/assets/11687236/7665456/b5f9eff0-fb74-11e4-91d8-4b3f7ce0ce25.png)

**Comment by emerald000** [comment]
In your image, Mogis is not a creature and therefore does not have lifelink.

**Comment by Greeneye0** [comment]
Heh, thanks. Was late, I didn't catch. it does work when he is a creature
