### ISSUE TITLE
Local Server

### ISSUE THREAD

**Issue by Devilboon** [magefree/mage#9731]
Am I doing something wrong? I can't update anything else.

<img width="666" alt="Bildschirm­foto 2022-11-04 um 17 33 02" src="https://user-images.githubusercontent.com/84149095/200027840-31abbcf3-77d8-4688-b4fa-fe3ff554c829.png">

**Comment by JayDi85** [comment]
It's broken files (your are run app while updating). 

How to fix: close all "java" apps from task manager or restart your computer. Then run launcher and press update button again.
