### ISSUE TITLE
Upgrade JUnit 4 tests to JUnit 5 tests 

### ISSUE THREAD

**Issue by phughk** [magefree/mage#9738]
Some of the tests in the project are still tied to JUnit 4. We should adapt the remaining tests to use JUnit 5 and remove the vintage dependency in mage.

**Comment by phughk** [comment]
Feel free to assign this to me.

**Comment by Alex-Vasile** [comment]
> Feel free to assign this to me.

Are you saying that you are starting to work on this?

**Comment by phughk** [comment]
Yes. I will be opening PRs per individual test file or module to keep things small. Is that ok? I realise such things should be coordinated. Maybe should have mentioned on gitter.

**Comment by Alex-Vasile** [comment]
> Yes. I will be opening PRs per individual test file or module to keep things small. Is that ok? I realise such things should be coordinated. Maybe should have mentioned on gitter.

That depends on how many there are/how many changes each file needs.

Open up a PR with a few files, I can't picture how changes each file will need

**Comment by phughk** [comment]
For people wondering how to identify the different tests

JUnit 4 tests include the following import
```
import org.junit.Test;
```

JUnit 5 tests include this import instead
```
import org.junit.jupiter.api.Test;
```

I will open a demonstration PR with a single test so we can see how much things change 👍

**Comment by phughk** [comment]
@Alex-Vasile first of quite a few as I have counted 1295 files.
https://github.com/magefree/mage/pull/9739

**Comment by JayDi85** [comment]
No needs to rewrite all tests to junit 5. XMage already supports both junit v4 and v5 in one project (I added v5 last year with code coverage support). junit v5 for new tests and new devs, 95% xmage tests uses v4.

**Comment by phughk** [comment]
Tbh I was doing this to get familiar with the codebase 😂 But is that a strong decision not to upgrade or an advice that it isn't necesesary?
The reason I wanted to do this is to better understand issues with builds. But you are right that this is perhaps excessive and unnecessary. I could still just do the mage module only as that only has 14 tests. But then again - it doesn't really make a difference.

**Comment by JayDi85** [comment]
I think v5 can be useful for tests with exceptions or other special use cases.

My point is that rewriting all the tests would take a lot of effort that could have been spent on more useful things (like adding NEW tests with examples from MTG rules or MTG articles, thereby increasing the percentage of test coverage).

P.S. My vision: XMage tests must be simple as much as possible and human's readable (for code and diff changes review, fails research, etc). So code's simplify can be good here. If you can do that then feel free to try.

**Comment by phughk** [comment]
Agree on the above and thanks for clarity. Maybe we can just land that single file change to ManaTest and close the issue then as the justification is clear.

**Comment by phughk** [comment]
Actually, maybe before we lay this to rest - what about the base classes for card testing? If we upgrade the card tests, then we can do trait testing with interfaces. For example testing that "dies" gets triggered everytime a "sacrifice" card is triggered. Perhaps that makes sense to do?
Example https://github.com/magefree/mage/issues/9741 would then implement HasSacrifice on Industrial Advancement and the SacrificeTraitTest would use JUnit 5 interface tests on it. The interfaces could be empty and simply used as a declaration of keyword testing.

**Comment by JayDi85** [comment]
It's a bad idea to setup IoC/DI for card tests -- it's must be simple (devs must use test api with commands + results). If you want to test triggers then use stack commands and checks (I think current test API allows to test your card).

IoC/DI can be useful for engine, gui, ux, db, network, etc. Not cards.
