### ISSUE TITLE
Industrial Advancement - Trigger ability can cause some death triggers not to activate

### ISSUE THREAD

**Issue by xmagescrub** [magefree/mage#9741]
Card: Industrial Advancement

Issue: When this trigger resolves, if the selected sacrifice target has a death trigger, it is not triggered and the death effect does not go on the stack.

Example: If I sacrifice a Rampant Rejvenator to the Industrial Advancement trigger, the death trigger for the Rampant Rejuvenator does not trigger.

**Comment by jeffwadsworth** [comment]
Duplicate of https://github.com/magefree/mage/issues/9688
