### ISSUE TITLE
[BUG] Cadric, Soul Kindler - legendary tokens are still affected by the legend rule

### ISSUE THREAD

**Issue by MrOppsokopolis** [magefree/mage#9750]
When you activate [[Cadric, Soul Kindler]]'s ability to create a legendary token copy of a legendary permanent you play, you are prompted to sacrifice one of the two legendary permanents due to the legend rule.

**Comment by Grath** [comment]
Duplicate of #9691

**Comment by jeffwadsworth** [comment]
It appears to work fine for me.
![worksFine](https://user-images.githubusercontent.com/1496996/200930115-4042aa0e-982f-4002-b7cb-2a32cdd4a8c0.jpg)

**Comment by Grath** [comment]
@jeffwadsworth It's fixed in the code, but the fix was checked in shortly after the last beta release was done. If you're testing it off master, that would be why.

**Comment by bwsinger** [comment]
Thank you for the follow-up.

**Comment by jeffwadsworth** [comment]
Fixed with https://github.com/magefree/mage/commit/3ed26a2b1f27e3498e028a5adf21e0daedbf6297
