### ISSUE TITLE
[40K] Missing Card: Sicarian Infiltrator

### ISSUE THREAD

**Issue by JeremyLyleBrown** [magefree/mage#9759]
The card from the 40K set Sicarian Infiltrator is missing from XMage. I'd love to add it to one of my commander decks on the platform.

**Comment by Grath** [comment]
The Squad mechanic hasn't been implemented yet, so you won't be able to add Sicarian Infiltrator until that happens. WotC's death march of card releases has meant that folks are having to pace implementation to avoid burnout.
