### ISSUE TITLE
Double the deck size limit ?

### ISSUE THREAD

**Issue by Susucre** [magefree/mage#9760]
I have a very large cube (varying between 1200 & 1500) that I do occasionally draft with a few friends.
Would it hurt to bump the deck size limit from 1000 to 2000 cards?
I can make a PR for it, I am only worried there would be a technical reason that would not be a good idea.
It is only for my own convenience, since currently the workaround is to pre-randomize a subset of the cube each draft to go below the limit and be able to start a tournament with the subset.

**Comment by JayDi85** [comment]
Deck size related to GUI issues in most use cases. If you can't open and edit your big deck then try to increase memory limits in the launcher settings -- see memory stats menu for more details.

Max cube size increased in your PR (#9762).
