### ISSUE TITLE
[BUG][Donal, Herald of Wings] creature copies are keeping their power and toughness instead of being 1/1

### ISSUE THREAD

**Issue by satchmosanzabar** [magefree/mage#9764]
Greetings,

Creature copies made when [[Donal, Herald of Wings]] is in play are keeping their power and toughness instead of being 1/1. See my board in screenshot below. Thanks!

![image](https://user-images.githubusercontent.com/69054847/202329047-af2c2740-f6d0-407d-b7a0-c5ea163be5a5.png)

**Comment by jeffwadsworth** [comment]
[[Donal, Herald of Wings]]

**Comment by xenohedron** [comment]
Fixed in #10389
