### ISSUE TITLE
Tawnos does not copy all aspects of creatures spells with X in mana cost 

### ISSUE THREAD

**Issue by dashosa** [magefree/mage#9767]
![image](https://user-images.githubusercontent.com/63882410/202926149-f8ac6089-fba7-49c1-a810-955925981ff4.png)

**Comment by jeffwadsworth** [comment]
[[Tawnos, the Toymaker]]

**Comment by Grath** [comment]
Gonna mark this as a duplicate of #9697 now to keep the info in one issue, since the issue is with all copying of X-cost permanent spells.
