### ISSUE TITLE
[BUG] Issue Resolving with Noncombat Damage

### ISSUE THREAD

**Issue by MetaSkipper** [magefree/mage#9781]
Not sure what the problem card here is, but the game cannot resolve the following game state.

I control two Soul-Scar Mages, a Boros Reckoner, and a Howlpack Avenger.
I cast from hand Rile.
On the stack goes Rile, then Mage 1, then Mage 2.
Mage 2 resolves, then Mage 1,
Rile attempts to resolve. I select Reckoner, and the game forces a rollback.

Below is the game state, followed by the error log.

![xmageBug01](https://user-images.githubusercontent.com/119142793/204115002-6a1a3943-b0b4-412b-ba85-aa8716681a08.PNG)

Game exception occurred: java.lang.ClassCastException: mage.game.events.DamagedPermanentEvent cannot be cast to mage.game.events.DamagedPermanentBatchEvent
Server version: 1.4.52-V2-beta1 (build: 2022-11-26 06:47)
mage.cards.h.HowlpackAvengerTriggeredAbility.checkTrigger(HowlpackAvenger.java:84)
mage.abilities.TriggeredAbilities.checkTrigger(TriggeredAbilities.java:94)
mage.abilities.TriggeredAbilities.checkTriggers(TriggeredAbilities.java:55)
mage.game.GameState.handleEvent(GameState.java:815)
mage.game.GameImpl.fireEvent(GameImpl.java:3110)
mage.game.permanent.PermanentImpl.doDamage(PermanentImpl.java:969)
mage.game.permanent.PermanentImpl.damage(PermanentImpl.java:906)
mage.abilities.effects.common.DamageTargetEffect.apply(DamageTargetEffect.java:136)
mage.abilities.AbilityImpl.resolveMode(AbilityImpl.java:200)
mage.abilities.AbilityImpl.resolve(AbilityImpl.java:187)
mage.game.stack.Spell.resolve(Spell.java:241)
mage.game.GameImpl.resolve(GameImpl.java:1635)
mage.game.GameImpl.playPriority(GameImpl.java:1561)
mage.game.turn.Step.priority(Step.java:61)
mage.game.turn.Phase.playStep(Phase.java:184)
mage.game.turn.Phase.play(Phase.java:89)
mage.game.turn.Turn.play(Turn.java:132)
mage.game.GameImpl.playTurn(GameImpl.java:1056)
mage.game.GameImpl.play(GameImpl.java:966)
mage.game.GameImpl.start(GameImpl.java:942)
mage.server.game.GameWorker.call(GameWorker.java:34)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)

**Comment by MetaSkipper** [comment]
I attempted casting Rile on Howlpack Avenger, and once again got a forced rollback.

Below is the error log.

Game exception occurred: java.lang.ClassCastException: mage.game.events.DamagedPermanentEvent cannot be cast to mage.game.events.DamagedPermanentBatchEvent
Server version: 1.4.52-V2-beta1 (build: 2022-11-26 06:47)
mage.cards.h.HowlpackAvengerTriggeredAbility.checkTrigger(HowlpackAvenger.java:84)
mage.abilities.TriggeredAbilities.checkTrigger(TriggeredAbilities.java:94)
mage.abilities.TriggeredAbilities.checkTriggers(TriggeredAbilities.java:55)
mage.game.GameState.handleEvent(GameState.java:815)
mage.game.GameImpl.fireEvent(GameImpl.java:3110)
mage.game.permanent.PermanentImpl.doDamage(PermanentImpl.java:969)
mage.game.permanent.PermanentImpl.damage(PermanentImpl.java:906)
mage.abilities.effects.common.DamageTargetEffect.apply(DamageTargetEffect.java:136)
mage.abilities.AbilityImpl.resolveMode(AbilityImpl.java:200)
mage.abilities.AbilityImpl.resolve(AbilityImpl.java:187)
mage.game.stack.Spell.resolve(Spell.java:241)
mage.game.GameImpl.resolve(GameImpl.java:1635)
mage.game.GameImpl.playPriority(GameImpl.java:1561)
mage.game.turn.Step.priority(Step.java:61)
mage.game.turn.Phase.playStep(Phase.java:184)
mage.game.turn.Phase.play(Phase.java:89)
mage.game.turn.Turn.play(Turn.java:132)
mage.game.GameImpl.playTurn(GameImpl.java:1056)
mage.game.GameImpl.play(GameImpl.java:966)
mage.game.GameImpl.start(GameImpl.java:942)
mage.server.game.GameWorker.call(GameWorker.java:34)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)

**Comment by MetaSkipper** [comment]
Had another issue with Howlpack Avenger.

Below is a screenshot of the gamestate, followed by the error log.

![xmageBug02](https://user-images.githubusercontent.com/119142793/204119398-ac70f64f-b9dc-43c8-aa69-859232739bfb.PNG)

Game exception occurred: java.lang.ClassCastException: mage.game.events.DamagedPermanentEvent cannot be cast to mage.game.events.DamagedPermanentBatchEvent
Server version: 1.4.52-V2-beta1 (build: 2022-11-26 06:47)
mage.cards.h.HowlpackAvengerTriggeredAbility.checkTrigger(HowlpackAvenger.java:84)
mage.abilities.TriggeredAbilities.checkTrigger(TriggeredAbilities.java:94)
mage.abilities.TriggeredAbilities.checkTriggers(TriggeredAbilities.java:55)
mage.game.GameState.handleEvent(GameState.java:815)
mage.game.GameImpl.fireEvent(GameImpl.java:3110)
mage.game.permanent.PermanentImpl.doDamage(PermanentImpl.java:969)
mage.game.permanent.PermanentImpl.damage(PermanentImpl.java:901)
mage.cards.m.MaraudingRaptorEffect.apply(MaraudingRaptor.java:86)
mage.abilities.AbilityImpl.resolveMode(AbilityImpl.java:200)
mage.abilities.AbilityImpl.resolve(AbilityImpl.java:184)
mage.abilities.TriggeredAbilityImpl.resolve(TriggeredAbilityImpl.java:150)
mage.game.stack.StackAbility.resolve(StackAbility.java:89)
mage.game.GameImpl.resolve(GameImpl.java:1635)
mage.game.GameImpl.playPriority(GameImpl.java:1561)
mage.game.turn.Step.priority(Step.java:61)
mage.game.turn.Phase.playStep(Phase.java:184)
mage.game.turn.Phase.play(Phase.java:89)
mage.game.turn.Turn.play(Turn.java:132)
mage.game.GameImpl.playTurn(GameImpl.java:1056)
mage.game.GameImpl.play(GameImpl.java:966)
mage.game.GameImpl.start(GameImpl.java:942)
mage.server.game.GameWorker.call(GameWorker.java:34)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)

**Comment by JayDi85** [comment]
Fixed by a648268c4c2270593626278623e4a484dee4f321
