### ISSUE TITLE
Could blood moon and other relatively complex code issues be solved by ChatGPT?

### ISSUE THREAD

**Issue by Clipper70** [magefree/mage#9791]
I'm sorry if this is not relevant to bring up. I don't actually have any personal experience coding so couldn't answer the question my self.  cheers!

https://openai.com/blog/chatgpt/

**Comment by jeffwadsworth** [comment]
The complexity of the Mage code would be incredibly daunting for it.  Right now, you can feed it snippets of code to analyze, which is does a great job at.  Perhaps later on, they will allow the user to send it a git project/source code and have it analyze it.
