### ISSUE TITLE
Bug Report: Cards Karn, Living Legacy and Tenuous Truce not working as intended.

### ISSUE THREAD

**Issue by geerizzle** [magefree/mage#9794]
Upon using his -1 Ability, Karn, Living Legacy would return the selected card from my hand to the library, even tho the ability works the other way around.

I also noticed that upon casting Tenuous Truce from my hand, the enchantment would sacrifice itself instantly for no reason.

- [ ] Karn, Living Legacy
- [x] Tenuous Truce

**Comment by PurpleCrowbar** [comment]
[[Karn, Living Legacy]] [[Tenuous Truce]]

**Comment by Tharkon** [comment]
I don't know how to edit the code, but I think these are the changes necessary for Karn, Living Legacy.
Insert a new line after line before line 95:
`cards.remove(card);`
Then the old line 95, which is now 96, should be changed from:
`player.putCardsOnBottomOfLibrary(card, game, source, false);`
to:
`player.putCardsOnBottomOfLibrary(cards, game, source, false);`

Just look at lines 83 and 85 from Thassa's Oracle.
