### ISSUE TITLE
Question: How to handle cards with the same name but different abilities?

### ISSUE THREAD

**Issue by Merlingilb** [magefree/mage#9801]
I am currently in the process of implementing the new sets for the star wars expansion and there is a card called "War Room" which is completly different to the already existing "War Room".

How do I handle this regarding the card class name?

([Link to Star Wars War Room](https://imgur.com/pqQ9kzt))

**Comment by e314** [comment]
Add (Star Wars) to the card name (this has already been done for Revenge, to avoid conflicts with [[Revival // Revenge]])

The class name ends up as WarRoomStarWars

**Comment by Merlingilb** [comment]
Nice, that was the one I used as a placeholder 😉
