### ISSUE TITLE
Ardoz not triggereing.

### ISSUE THREAD

**Issue by LegionedintheDamned** [magefree/mage#9802]
Ardoz, Cobbler of War is not triggered on her own entry.

![image](https://user-images.githubusercontent.com/82664393/206959937-d5ee844c-e36c-4d6e-9f92-a11b13e5e3a0.png)

**Comment by Merlingilb** [comment]
Fixed in PR #9803

**Comment by PurpleCrowbar** [comment]
Closed by 33ded4622ec82caec11fa90975cb95a78e474295
