### ISSUE TITLE
Dev Question: Workflow for developers

### ISSUE THREAD

**Issue by Merlingilb** [magefree/mage#9807]
May I ask how the dev worklow works here?
Since I started playing around with the code last week, I fixed some cards and made some pull requests.
Because there was no reaction to them I wonder how the workflow is supposed to work.

I don't want to be impatient, I just want to know if I should have done anything in a different way.
Thanks for your answer.

**Comment by theelk801** [comment]
You didn't do anything wrong, it's just that all the regular devs are taking a break and so nobody's really approving things right now. I'm probably gonna start contributing again soon and I'll definitely review your PRs when I do if no one else has.

**Comment by Merlingilb** [comment]
Thanks for your reply.
Sad to hear, that there is a break in development.
