### ISSUE TITLE
No draw Mighty Servant of Leuk-o

### ISSUE THREAD

**Issue by LegionedintheDamned** [magefree/mage#9808]
Crewed Mighty Servant of Leuk-o with Ethersworn Canonist and activated creature Mishra's Factory.  It did not gain the "when crewed by exactly 2 creatures" ability.
![image](https://user-images.githubusercontent.com/82664393/207946375-d329f9e0-a81f-4851-926e-cd796f981899.png)

**Comment by xenohedron** [comment]
Duplicate of #9324
