### ISSUE TITLE
Identifier and morphed or manifested or other face down cards.

### ISSUE THREAD

**Issue by LevelX2** [magefree/mage#981]
Showing the identifier for morphed cards gives some information which card it is, if the card was played before and was cast again.

Each morphed creature instance needs to have an own identifier.

**Comment by LevelX2** [comment]
Reports:
http://www.slightlymagic.net/forum/posting.php?mode=edit&f=70&p=187997

**Comment by 18ths** [comment]
On the other hand:

"707.6. If you control multiple face-down spells or face-down permanents, you must ensure at all times that your face-down spells and permanents can be easily differentiated from each other. This includes, but is not limited to, knowing the order spells were cast, the order that face-down permanents entered the battlefield, which creature attacked last turn, and any other differences between face-down spells or permanents. Common methods for distinguishing between face-down objects include using counters or dice to mark the different objects, or clearly placing those objects in order on the table."

So, if you play Ixidron, you still should be able to bolt a particular creature, not some random one and hope for the best. The same should happen with Backslide, or Death Raptor, or Master of the Veil.

My point is its only Jeskai Infiltrator needs to be fixed, maybe some other corner cases too, but certainly its not the whole face-down card behaviour.

**Comment by JayDi85** [comment]
Object ids all around, it’s impossible to hide or change it. So it’s will not implemented, see details here: https://github.com/magefree/mage/issues/11881#issuecomment-1972105765
