### ISSUE TITLE
Computer can cheat

### ISSUE THREAD

**Issue by LegionedintheDamned** [magefree/mage#9810]
I have seen it where the computer can attack multiple people - and the person being attacked cannot block.
I have seen it where the computer can attack a person and planeswalker with a single creature simultaneously.
Today, the computer player a creature without haste, and someone got the attack trigger.

![image](https://user-images.githubusercontent.com/82664393/208225096-ea93dbdb-c3a4-41b0-8775-3ae94573ed95.png)

**Comment by JayDi85** [comment]
Multiple attacks bug (player + planeswalker) by single creature from #7434. It was fixed in the beginning of 2024.
