### ISSUE TITLE
Game is unplayable due to troll crashing server. 

### ISSUE THREAD

**Issue by Kwhorstkamp** [magefree/mage#9821]
Not sure if anybody is aware, but some asshole keeps crashing the server, saying "they'll never get rid of me, they're too stupid to hardware ban me". So, at this point the only solution is to just happen to login while this guy is asleep, because apparently he has like 16 hours a day to kill, every day. Fucking annoying.

**Comment by Merlingilb** [comment]
I am willing to help to find the bug but without server logs it is difficult to try to find anything.
