### ISSUE TITLE
Rodolf Duskbringer bug

### ISSUE THREAD

**Issue by catman123456** [magefree/mage#9822]
The trigger ability did not work

![image](https://user-images.githubusercontent.com/64045003/208588493-fa1b90a6-df12-4cc8-8a83-35a819d3ca2a.png)

**Comment by Merlingilb** [comment]
[[Rodolf Duskbringer]]

**Comment by Merlingilb** [comment]
Fixed

**Comment by PurpleCrowbar** [comment]
Closed by #9824
