### ISSUE TITLE
Hexproof / shroud prevents me from selecting a wolf for Master of the Wild Hunt

### ISSUE THREAD

**Issue by juggalotic** [magefree/mage#9827]
![Screenshot (8)](https://user-images.githubusercontent.com/121203446/209023626-aa1689f7-1dcf-45b3-b853-096581bc04aa.png)

**Comment by Tharkon** [comment]
This seems to apply to other sources of hexproof as well such as [[Heroic Intervention]].
Possibly shroud as well.

[[Master of the Wild Hunt]]
[[Shalai, Voice of the Plenty]]

**Comment by Tharkon** [comment]
Possibly related: You can't use ninjutsu on creatures with shroud.
So maybe the issue is with shroud/hexproof preventing too much.
