### ISSUE TITLE
Combust should kill Swans of Bryn Argoll

### ISSUE THREAD

**Issue by emerald000** [magefree/mage#983]
Since you can't prevent damage that Combust deals, it should be able to kill Swans of Bryn Argoll. ~~And you still get to draw 5 cards.~~

**Comment by TGower** [comment]
Swans lets the source's controller draw cards equal to the amount of damage prevented, so when no damage is prevented no cards should be drawn unless I'm missing something.

**Comment by emerald000** [comment]
Whoops, misread the card. You shouldn't get to draw cards then. But you still kill it.
