### ISSUE TITLE
Commander with Blitz does not work as intended

### ISSUE THREAD

**Issue by Merlingilb** [magefree/mage#9834]
[[Jaxis, the Troublemaker]] is a commander with the blitz ability.
But casting it with blitz ability does not trigger the blitz ability.

Problem is, that casting it from command zone triggers the activate method of CastCommanderAbility and not BlitzAbility.
Suggested fix: Add a activate overwrite in CastCommanderAbility to trigger the setValue onto the game state to set the blitz activations count.

**Comment by Merlingilb** [comment]
Fixed by #9835

**Comment by xenohedron** [comment]
Fixed by #10790
