### ISSUE TITLE
Melee ability doesn't trigger

### ISSUE THREAD

**Issue by catman123456** [magefree/mage#9848]
[[Adriana, Captain of the Guard]] is not activating. 

![image](https://user-images.githubusercontent.com/64045003/210158850-a5743b9d-eac3-4921-a690-dd05faf0beea.png)

**Comment by catman123456** [comment]
melee in general is not working

**Comment by Grath** [comment]
Correction: Melee triggers, but doesn't buff creatures. This is caused by https://github.com/magefree/mage/commit/2d2438ba660d7c3e66cca1a70cd697f3f39579c1 but I don't immediately see what's wrong with it.

**Comment by catman123456** [comment]
melee is still not buffing

![image](https://user-images.githubusercontent.com/64045003/233475654-f8b8c334-e956-4585-aab1-420a1fbdd170.png)

**Comment by Grath** [comment]
The issue was fixed about 12 hours after the last new build, but with new builds happening every couple of days lately you hopefully won't be waiting too long.

**Comment by Grath** [comment]
Just confirmed on my side, Melee will be actually fixed with the new update.
