### ISSUE TITLE
Najeela, the Blade-Blossom is all 5 colors, even though she is only red

### ISSUE THREAD

**Issue by alexander-novo** [magefree/mage#9852]
[[Najeela, the Blade-Blossom]] is only red. Notice below how her color indicator shows all colors, though. My opponent used [[Bloom Tender]] to tap for all five colors.

![image](https://user-images.githubusercontent.com/11657716/210272586-aec2485c-40b4-4fc1-83d2-5734785cf6ab.png)

**Comment by PurpleCrowbar** [comment]
I could not recreate this, see below with her only being red:
![image](https://user-images.githubusercontent.com/26198472/210273219-ab6f6549-ad4e-4653-8c01-774ec8e8ba43.png)
Do you know which other permanents were in play at the time?

**Comment by alexander-novo** [comment]
![image](https://user-images.githubusercontent.com/11657716/210273269-32e6daa5-341d-4764-b54e-85f7cc6cbddf.png)

 Here's another example from my current game where she is in the command zone

**Comment by PurpleCrowbar** [comment]
I can't recreate with her as the commander either
![image](https://user-images.githubusercontent.com/26198472/210273539-dfad8b33-0b29-48b3-83dc-e69ffdec313a.png)
The visual variant shouldn't matter, and testing with her as a commander using that variant yields expected results:
![image](https://user-images.githubusercontent.com/26198472/210273880-87fb587a-f79a-4ca6-adfa-b26674adc1d6.png)

There seems to be some irreproducable issues cropping up lately, but mostly on non-official servers. Strange that it's happening on the xmage.today now

**Comment by alexander-novo** [comment]
I didn't get a screenshot of it, but earlier today I was playing on my local server on the beta version, and Najeela began the game as just red, but changed to 5 color sometime later in the game.

**Comment by jeffwadsworth** [comment]
Works fine for me as well.

**Comment by alexander-novo** [comment]
Here's another example of it happening with [[Sisay, Weatherlight Captain]] in a bot game on the newest version:

![image](https://user-images.githubusercontent.com/11657716/216534414-9837c7b5-ada1-4b4f-a009-20f24c1e1815.png)

I suspect they start out the game as normal, and something triggers them to become 5 color sometime later.

**Comment by alexander-novo** [comment]
Hey just wanted to share some more info:

![image](https://github.com/magefree/mage/assets/11657716/cbc056b4-6131-4490-ab79-9bdb35174d09)

The new card [[Ulalek, Fused Atrocity]] also has this issue (and it's devoid!).

![image](https://github.com/magefree/mage/assets/11657716/d0682197-6b1a-4fcb-aefb-b49e025dbe6a)

It only has the problem if it's the commander... a non-commander version in hand is properly colorless.

![image](https://github.com/magefree/mage/assets/11657716/8769df81-4b0b-4a50-a0f9-a6ef8fb14bc0)

And on the battlefield
