### ISSUE TITLE
[BUG] Venom Connoisseur

### ISSUE THREAD

**Issue by smolpp69** [magefree/mage#9861]
After playing two separate cards that attempted to trigger [[Venom Connoisseur]], I got this error message.

Game exception occurred: java.lang.NullPointerException
Server version: 1.4.52-V2-beta2 (build: 2022-12-19 08:29)
mage.watchers.common.AbilityResolvedWatcher.getResolutionCount(AbilityResolvedWatcher.java:39)
mage.abilities.effects.common.IfAbilityHasResolvedXTimesEffect.apply(IfAbilityHasResolvedXTimesEffect.java:40)
mage.abilities.AbilityImpl.resolveMode(AbilityImpl.java:200)
mage.abilities.AbilityImpl.resolve(AbilityImpl.java:184)
mage.abilities.TriggeredAbilityImpl.resolve(TriggeredAbilityImpl.java:150)
mage.game.stack.StackAbility.resolve(StackAbility.java:89)
mage.game.GameImpl.resolve(GameImpl.java:1635)
mage.game.GameImpl.playPriority(GameImpl.java:1561)
mage.game.turn.Step.priority(Step.java:61)
mage.game.turn.Phase.playStep(Phase.java:184)
mage.game.turn.Phase.play(Phase.java:89)
mage.game.turn.Turn.play(Turn.java:132)
mage.game.GameImpl.playTurn(GameImpl.java:1056)
mage.game.GameImpl.play(GameImpl.java:966)
mage.game.GameImpl.start(GameImpl.java:942)
mage.server.game.GameWorker.call(GameWorker.java:34)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)

**Comment by jeffwadsworth** [comment]
https://github.com/magefree/mage/pull/9869
