### ISSUE TITLE
[BUG] Cult Conscript remembers that a creature died after a rollback

### ISSUE THREAD

**Issue by NibiruMTG** [magefree/mage#9873]
If one of your non-Skeleton creatures dies and [[Cult Conscript]] is in your graveyard, you can then roll back to the start of the turn and Cult Conscript can still be successfully activated. This is not true for similar cards like [[Brackish Trudge]] or [[Gutterbones]].

**Comment by xenohedron** [comment]
I can no longer reproduce this, so I believe it was most likely fixed incidentally when the watcher copy code was reworked as part of #11406.
