### ISSUE TITLE
The Temporal Anchor doesn't let you play cards exiled with it

### ISSUE THREAD

**Issue by alexander-novo** [magefree/mage#9884]
[[The Temporal Anchor]]

![image](https://user-images.githubusercontent.com/11657716/213033943-45cc05da-c4a7-4bc3-89a5-1c5347ca0d71.png)

**Comment by PurpleCrowbar** [comment]
I believe this is fixed, see #9793. I made the commit that fixed this on the 25th of December, and it seems that the beta's most recent version is from the 19th of December.
