### ISSUE TITLE
Omnath, Locus of Creation 2nd Trigger

### ISSUE THREAD

**Issue by LegionedintheDamned** [magefree/mage#9887]
When Omnath, Locus of Creation is on the battlefield, along with Ancient Greenwarden: the 1st and 3rd triggers duplicate correctly.  However, the 2nd trigger (add mana) does not.

**Comment by Grath** [comment]
Just to clarify: The correct resolution with Omnath, Locus of Creation and Ancient Greenwarden is that, when both are in play:
You play one land, and Omnath triggers twice. You gain 4 life when the first resolves, then add the mana when the second resolves.
You play an additional land, and Omnath triggers twice again. The first resolution causes 4 damage to each opponent and each of their planeswalkers, the second resolution does nothing. Any additional lands played that turn cause Omnath triggers which do nothing.

You should not gain more than 4 life, or deal more than 4 damage.

**Comment by Grath** [comment]
I just tested locally in my development build and it resolved correctly (First land gained 4 life, 4 mana, second land dealt 4 damage, then additional triggers resolving do nothing.)

**Comment by jeffwadsworth** [comment]
[[Omnath, Locus of Creation]]

**Comment by LegionedintheDamned** [comment]
I haven't been able to replicate this - I will let you know if I can.
