### ISSUE TITLE
[BUG] Master of Cruelties ability triggers even when blocked

### ISSUE THREAD

**Issue by CoolKnight95** [magefree/mage#9904]
im not sure if this bug happens only when [[Master of Cruelties]] is put on the battlefield with [[Alesha, Who Smiles at Death]] but when Master of crulties attacks they bring opponents life totals to 1 even when hes blocked

**Comment by PurpleCrowbar** [comment]
I could not reproduce this bug with or without Alesha, the trigger did not go on the stack after MoC was blocked.
