### ISSUE TITLE
Invalid config

### ISSUE THREAD

**Issue by salyG** [magefree/mage#992]
Sorry to bother boss. But what is this ?

Invalid config from http://xmage.info/xmage/config.json

**Comment by LevelX2** [comment]
The xmage.info domain is no longer valid.

You have to change the "XMage Home" in the xmage launcher setting to this:
http://xmage.de/xmage

This will update to Launcher 0.3.4 that's the same without the updated default xmage home.

Secondly you need to change the Xmage Preferences => Connection => URL server List to:
http://XMage.de/files/server-list.txt

**Comment by salyG** [comment]
Okay boss. thanks
