### ISSUE TITLE
Goad Null error

### ISSUE THREAD

**Issue by catman123456** [magefree/mage#9924]
Game exception occurred: mage.MageException: Iterated player priority after game exception too often, game ends! Last error:
 null
Server version: 1.4.52-V2-beta3 (build: 2023-01-20 14:06)
mage.game.GameImpl.playPriority(GameImpl.java:1591)
mage.game.turn.Step.priority(Step.java:61)
mage.game.turn.CombatDamageStep.priority(CombatDamageStep.java:31)
mage.game.turn.Phase.playStep(Phase.java:184)
mage.game.turn.Phase.play(Phase.java:89)
mage.game.turn.Turn.play(Turn.java:132)
mage.game.GameImpl.playTurn(GameImpl.java:1056)
mage.game.GameImpl.play(GameImpl.java:966)
mage.game.GameImpl.start(GameImpl.java:942)
mage.server.game.GameWorker.call(GameWorker.java:34)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)

**Comment by CBreyer** [comment]
I got the same error playing against a Goad deck just now, ended the game immediately and couldn't be reverted.

**Comment by catman123456** [comment]
Still get the Null error 

Game exception occurred: java.lang.NullPointerException
Server version: 1.4.52-V2-beta7 (build: 2023-02-25 14:46)


![image](https://user-images.githubusercontent.com/64045003/222679814-276a9145-5c8a-4205-8363-082fb50effab.png)

**Comment by xenohedron** [comment]
Possibly fixed by 22552ed ?
