### ISSUE TITLE
[BUG] No cards which trigger when a card is played actually check to see if there is a physical card being played

### ISSUE THREAD

**Issue by alexander-novo** [magefree/mage#9931]
![image](https://user-images.githubusercontent.com/11657716/215582863-75cb454f-1d72-46c9-b1e5-65106c307f43.png)

[[Mnemonic Deluge]] [[Prosper, Tome-Bound]]

Notable section from the rules:

> **108.2**. When a rule or text on a card refers to a “card,” it means only a Magic card or an object represented by a Magic card.

Menmonic Deluge creates copies of a card, which themselves aren't cards since they aren't represented by a physical magic card. Last time I checked, a similar interaction with [[Mizzix's Mastery]] was working properly, but it could have since changed.

**Comment by alexander-novo** [comment]
Actually, after checking cards with similar wording as Prosper:

- [[Null Profusion]]
- [[Recycle]]
- [[Search the City]]

None of them seem to check that when a spell is cast, there is actually a physical card representing that spell. Spells can be cast in a variety of ways without a physical card representing them, such as with Mnemonic Deluge (mentioned above), [[Isochron Scepter]], and [[Mizzix's Mastery]]. See the oracle rulings for Null Profusion:

> The triggered ability will trigger when you play a land card or cast a nonland card as a spell. It won’t trigger when you play a copy of a card, such as with Isochron Scepter. _(2007-02-01)_

**Comment by xenohedron** [comment]
Fixed in #10436
