### ISSUE TITLE
[BUG] - Savior of Ollenbock

### ISSUE THREAD

**Issue by brotendomtg** [magefree/mage#9937]
Had a game today where Savior of Ollenbock trained but couldn't target/select a creature on the battlefield. There weren't any creatures in graveyards, so I'm not sure if that would have worked. 

![Screenshot 2023-01-31 155641](https://user-images.githubusercontent.com/114497501/215914715-28e099f8-05a7-45b7-bdbd-6e3ec9fb9184.png)

**Comment by PurpleCrowbar** [comment]
Duplicate of #9561
