### ISSUE TITLE
Alluring Siren does not force creatures to attack its controller

### ISSUE THREAD

**Issue by PurpleCrowbar** [magefree/mage#9939]
[[Alluring Siren]] reads:

> {T}: Target creature an opponent controls attacks you this turn if able.

In Xmage, this ability reads the same except it omits the word "you", and it only forces the creature to *attack* this combat, not necessarily attack *you* this combat. See text in Xmage below:

![image](https://user-images.githubusercontent.com/26198472/216127235-9a8425b6-244d-4668-a869-18c32d5f3ad3.png)

**Comment by FranzCorsaro** [comment]
Ability target AS-IS:

`ability.addTarget(new TargetCreaturePermanent(StaticFilters.FILTER_OPPONENTS_PERMANENT_CREATURE));`

I guess changing to:

`ability.addTarget(new TargetPlayer(StaticFilters.FILTER_PLAYER_CONTROLLER));`

would fix that

**Comment by PurpleCrowbar** [comment]
> Ability target AS-IS:
> 
> `ability.addTarget(new TargetCreaturePermanent(StaticFilters.FILTER_OPPONENTS_PERMANENT_CREATURE));`
> 
> I guess changing to:
> 
> `ability.addTarget(new TargetPlayer(StaticFilters.FILTER_PLAYER_CONTROLLER));`
> 
> would fix that

No, as that code determines the target of the ability, which is a creature an opponent controls

**Comment by FranzCorsaro** [comment]
Hello,
That was very wrong, sorry about that.
I'd like to contribute, is it possible to join the github project
contributors?
I'll just look further into that issue for now, and try to test a possible
fix.

Regards,
Corsaro

Il giorno mer 8 feb 2023 alle ore 23:02 PurpleCrowbar <
***@***.***> ha scritto:

**Comment by Grath** [comment]
The typical beginning for contributing is to fork the project, push your changes to a branch in your fork, and then you can open a pull request to be reviewed on here.

**Comment by FranzCorsaro** [comment]
Thank you Grath,
I'll fork the project.

Il giorno mer 8 feb 2023 alle ore 23:06 Grath ***@***.***> ha
scritto:

**Comment by JayDi85** [comment]
Fixed by 930d18a77d67f93efcf6a900ff93c4807fa68b04
