### ISSUE TITLE
Blast-Furnace Hellkite Bug

### ISSUE THREAD

**Issue by catman123456** [magefree/mage#9940]
When I try to flash in [[Blast-Furnace Hellkite]] this happens

![image](https://user-images.githubusercontent.com/64045003/216209675-8fb1d3fc-935d-4547-92e8-c8dabb292b4a.png)

Game exception occurred: java.lang.NullPointerException
Server version: 1.4.52-V2-beta3 (build: 2023-01-20 14:06)
mage.abilities.keyword.OfferingCostReductionEffect.apply(OfferingAbility.java:229)
mage.abilities.effects.ContinuousEffects.costModification(ContinuousEffects.java:741)
mage.abilities.AbilityImpl.activate(AbilityImpl.java:394)
mage.abilities.ActivatedAbilityImpl.activate(ActivatedAbilityImpl.java:265)
mage.game.stack.Spell.activate(Spell.java:142)
mage.players.PlayerImpl.cast(PlayerImpl.java:1212)
mage.players.PlayerImpl.activateAbility(PlayerImpl.java:1470)
mage.player.human.HumanPlayer.activateAbility(HumanPlayer.java:2149)
mage.player.human.HumanPlayer.activateAbility(HumanPlayer.java:2172)
mage.player.human.HumanPlayer.priority(HumanPlayer.java:1239)
mage.game.GameImpl.playPriority(GameImpl.java:1540)
mage.game.turn.Step.priority(Step.java:61)
mage.game.turn.Phase.playStep(Phase.java:184)
mage.game.turn.Phase.play(Phase.java:89)
mage.game.turn.Turn.play(Turn.java:132)
mage.game.GameImpl.playTurn(GameImpl.java:1056)
mage.game.GameImpl.play(GameImpl.java:966)
mage.game.GameImpl.start(GameImpl.java:942)
mage.server.game.GameWorker.call(GameWorker.java:34)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)

**Comment by jeffwadsworth** [comment]
What card were you or another player using that had the "offering cost reduction"?

**Comment by catman123456** [comment]
I was trying to use a treasure to sac to flash it in

**Comment by JayDi85** [comment]
Fixed by ce3cf742c99beab3f2d18c10dafb6bc7d37cc3a8
