### ISSUE TITLE
Atraxa, Grand Unifier does not reveal the cards put into hand 

### ISSUE THREAD

**Issue by stevedavidmusic** [magefree/mage#9949]
Atraxa, Grand Unifier does not reveal the cards put into hand. Logs just show that the player put a card from library to their hand. 

![Uploading Screen Shot 2023-02-05 at 5.07.08 PM.png…]()

**Comment by stevedavidmusic** [comment]
@PurpleCrowbar the issue still persists.

<img width="1280" alt="Screen Shot 2023-03-12 at 1 43 01 PM" src="https://user-images.githubusercontent.com/45299811/224565805-2dc797cc-2553-4794-bda4-c8549177644e.png">

**Comment by PurpleCrowbar** [comment]
The cards put into hand are actually shown in the screenshot where it says "SteveMan1 reveals Black Lotus, Show and Tell, Atraxa Grand Unifier" after the initial reveal but it's not clear that those are the chosen cards to put into hand so will fix
