### ISSUE TITLE
Cancel button not working after tapping Sylvan Caryatid

### ISSUE THREAD

**Issue by Bivvz** [magefree/mage#995]
When I tap this card for mana the game gives the option to cancel this action however after hitting the cancel button nothing happens.

**Comment by LevelX2** [comment]
I can't reproduce such a problem. Probably already fixed.
If not reopen and describe in detail how to reproduce.

One similar report in forum:
http://www.slightlymagic.net/forum/viewtopic.php?f=70&t=17365&p=181844#p181844
