### ISSUE TITLE
[BUG] Potential issue with MDFCs and Aminatou's Augury

### ISSUE THREAD

**Issue by alexander-novo** [magefree/mage#9956]
![image](https://user-images.githubusercontent.com/11657716/217071193-e233e380-4d8d-4cfd-a7a4-deb9e3104097.png)

I can't cast [[Sea Gate Restoration]] from exile with [[Aminatou's Augury]], even though I can cast [[Terminus]], which is also a sorcery. I don't know for sure, but I suspect that this is because Sea Gate Restoration is an MDFC with a land on the back, and therefore it's getting filtered out on this line:

https://github.com/magefree/mage/blob/45eafed123a03ee075ea77830f8f6f50e9e8e1b9/Mage.Sets/src/mage/cards/a/AminatousAugury.java#L113-L117

Board state for reference:

![image](https://user-images.githubusercontent.com/11657716/217071790-c7f158a1-8765-4097-9f63-e05f0ac7ac4f.png)

**Comment by jeffwadsworth** [comment]
Yes, the filter must apply to the front face of the MDFC, not the entire card, as is the case here.
