### ISSUE TITLE
ConcurrentModificationException with alternate/additional costs

### ISSUE THREAD

**Issue by KaarSim** [magefree/mage#9957]
Basically, after i cast Omniscience, every other spell i cast triggers the error. I've never encountered that error before.
Here's the report:
Game exception occurred: java.util.ConcurrentModificationException
Server version: 1.4.50-V2 (build: 2021-09-05 18:59)
java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909)
java.util.ArrayList$Itr.next(ArrayList.java:859)
mage.abilities.AbilityImpl.activateAlternateOrAdditionalCosts(AbilityImpl.java:472)
mage.abilities.AbilityImpl.activate(AbilityImpl.java:277)
mage.abilities.ActivatedAbilityImpl.activate(ActivatedAbilityImpl.java:280)
mage.game.stack.Spell.activate(Spell.java:131)
mage.players.PlayerImpl.cast(PlayerImpl.java:1216)
mage.players.PlayerImpl.activateAbility(PlayerImpl.java:1472)
mage.player.human.HumanPlayer.activateAbility(HumanPlayer.java:2083)
mage.player.human.HumanPlayer.activateAbility(HumanPlayer.java:2106)
mage.player.human.HumanPlayer.priority(HumanPlayer.java:1191)
mage.game.GameImpl.playPriority(GameImpl.java:1509)
mage.game.turn.Step.priority(Step.java:61)
mage.game.turn.Phase.playStep(Phase.java:184)
mage.game.turn.Phase.play(Phase.java:89)
mage.game.turn.Turn.play(Turn.java:128)
mage.game.GameImpl.playTurn(GameImpl.java:1034)
mage.game.GameImpl.play(GameImpl.java:944)
mage.game.GameImpl.start(GameImpl.java:920)
mage.server.game.GameWorker.call(GameWorker.java:34)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)

**Comment by PurpleCrowbar** [comment]
I cannot recreate this. With [[Omniscience]] and [[Jodah, Archmage Eternal]] in play, any time I go to cast a spell I'm given the option to pay one of the alternative casting costs, and whichever one I choose goes as you'd expect, with Omniscience's casting it for free and Jodah's casting it for WUBRG.

**Comment by KaarSim** [comment]
Ahh, it's probably some other element of the boardstate I was in, and since I haven't saved it, I can't give you any more info unfortunately. Thanks for the reply mate, cheers. 🙂

**Comment by jeffwadsworth** [comment]
Did you recreate this issue?  We just need to know the board/hand state.

**Comment by KaarSim** [comment]
No, and only from memory I'm afraid, as I didn't get screenshots of the
boardstate. I do remember I had a Fist of Suns on field, but that's about
it. Every spell I would attempt casting after Omniscience would trigger the
error.

Στις Τετ 8 Φεβ 2023, 01:27 ο χρήστης Jeff Wadsworth <
***@***.***> έγραψε:

**Comment by PurpleCrowbar** [comment]
I tested with a Fists of Suns, Jodah, and Omniscience all in play at the same time and couldn't recreate the issue so the problem likely isn't stemming from any of those three

**Comment by KaarSim** [comment]
OK, I'll see if I can find it myself and let you know.

Στις Τετ 8 Φεβ 2023, 06:25 ο χρήστης PurpleCrowbar ***@***.***>
έγραψε:

**Comment by KaarSim** [comment]
UPDATE: I manage to recreate it, it think.
![Στιγμιότυπο οθόνης (6)](https://user-images.githubusercontent.com/124718162/217532376-b559a0ce-c0f6-4304-86f9-93dab1f261fa.png)
Here's the log:
Game exception occurred: java.util.ConcurrentModificationException
Server version: 1.4.52-V2-beta4 (build: 2023-02-02 10:49)
java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909)
java.util.ArrayList$Itr.next(ArrayList.java:859)
mage.abilities.AbilityImpl.activateAlternateOrAdditionalCosts(AbilityImpl.java:483)
mage.abilities.AbilityImpl.activate(AbilityImpl.java:288)
mage.abilities.ActivatedAbilityImpl.activate(ActivatedAbilityImpl.java:265)
mage.game.stack.Spell.activate(Spell.java:142)
mage.players.PlayerImpl.cast(PlayerImpl.java:1212)
mage.players.PlayerImpl.activateAbility(PlayerImpl.java:1470)
mage.player.human.HumanPlayer.activateAbility(HumanPlayer.java:2149)
mage.player.human.HumanPlayer.activateAbility(HumanPlayer.java:2172)
mage.player.human.HumanPlayer.priority(HumanPlayer.java:1239)
mage.game.GameImpl.playPriority(GameImpl.java:1540)
mage.game.turn.Step.priority(Step.java:61)
mage.game.turn.Phase.playStep(Phase.java:184)
mage.game.turn.Phase.play(Phase.java:89)
mage.game.turn.Turn.play(Turn.java:132)
mage.game.GameImpl.playTurn(GameImpl.java:1056)
mage.game.GameImpl.playExtraTurns(GameImpl.java:1015)
mage.game.GameImpl.play(GameImpl.java:970)
mage.game.GameImpl.start(GameImpl.java:942)
mage.server.game.GameWorker.call(GameWorker.java:34)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)

**Comment by jeffwadsworth** [comment]
[[Nexus of Fate]]

**Comment by jeffwadsworth** [comment]
Please post your "dec" file for the deck you are using.  I tested with some of those cards and at times had 20 objects on the stack and it worked fine.  We can play games with the AI using your deck and see it it exposes the issue.
