### ISSUE TITLE
[BUG] Attempting to cast a spell for free from Aminatou's Augury, then cancelling prevents you from casting that spell later

### ISSUE THREAD

**Issue by alexander-novo** [magefree/mage#9960]
![image](https://user-images.githubusercontent.com/11657716/217449915-48c8ec4f-6f3d-4c87-b6e5-764677f71f3f.png)

[[Aminatou's Augury]]. I attempted to cast Time Stretch, but hit "undo" when it asked me to target a player. It went back into exile, but I couldn't play it later.

**Comment by jeffwadsworth** [comment]
Works fine for me in the latest build.  The option I get is "cast..."  and "cancel".  The cancel works fine and just puts it back, ready to be cast again.
