### ISSUE TITLE
Haunting Voyage only allows 2 targets when foretold

### ISSUE THREAD

**Issue by LegionedintheDamned** [magefree/mage#9962]
I have tried multiple times and posted in the Oct 2021 thread.  Human tribal, EDH, 4 human players, commanders are Silvar and Trynn.  Only allows 2 targets on resolution.

**Comment by jeffwadsworth** [comment]
[[Haunting Voyage]]

**Comment by jeffwadsworth** [comment]
It worked fine for me in a normal game.  Perhaps another dev that plays with Commander can test it there.
