### ISSUE TITLE
Ayesha Tanaka, Armorer bug

### ISSUE THREAD

**Issue by VGBBY** [magefree/mage#9974]
game kept rolling back when trying to use her ability

![image](https://user-images.githubusercontent.com/125227902/218348914-a4a8193d-691c-4379-a48c-db1b088bfe95.png)

the error - 
Game exception occurred: java.lang.NullPointerException
Server version: 1.4.52-V2-beta5 (build: 2023-02-11 14:32)
mage.cards.a.AyeshaTanakaArmorerPredicate.apply(AyeshaTanakaArmorer.java:86)
mage.cards.a.AyeshaTanakaArmorerPredicate.apply(AyeshaTanakaArmorer.java:80)
mage.filter.FilterCard.lambda$match$0(FilterCard.java:68)
java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1359)
java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499)
java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486)
java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
java.util.stream.ReferencePipeline.allMatch(ReferencePipeline.java:454)
mage.filter.FilterCard.match(FilterCard.java:68)
mage.filter.FilterCard.match(FilterCard.java:60)
mage.cards.CardsImpl.lambda$count$1(CardsImpl.java:109)
java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
java.util.Iterator.forEachRemaining(Iterator.java:116)
java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
java.util.stream.LongPipeline.reduce(LongPipeline.java:439)
java.util.stream.LongPipeline.sum(LongPipeline.java:397)
java.util.stream.ReferencePipeline.count(ReferencePipeline.java:526)
mage.cards.CardsImpl.count(CardsImpl.java:109)
mage.player.human.HumanPlayer.chooseTarget(HumanPlayer.java:805)
mage.abilities.effects.common.LookLibraryAndPickControllerEffect.actionWithLookedCards(LookLibraryAndPickControllerEffect.java:135)
mage.abilities.effects.common.LookLibraryControllerEffect.apply(LookLibraryControllerEffect.java:77)
mage.abilities.AbilityImpl.resolveMode(AbilityImpl.java:200)
mage.abilities.AbilityImpl.resolve(AbilityImpl.java:184)
mage.abilities.TriggeredAbilityImpl.resolve(TriggeredAbilityImpl.java:150)
mage.game.stack.StackAbility.resolve(StackAbility.java:89)
mage.game.GameImpl.resolve(GameImpl.java:1635)
mage.game.GameImpl.playPriority(GameImpl.java:1561)
mage.game.turn.Step.priority(Step.java:61)
mage.game.turn.Phase.playStep(Phase.java:184)
mage.game.turn.Phase.play(Phase.java:89)
mage.game.turn.Turn.play(Turn.java:132)
mage.game.GameImpl.playTurn(GameImpl.java:1056)
mage.game.GameImpl.play(GameImpl.java:966)
mage.game.GameImpl.start(GameImpl.java:942)
mage.server.game.GameWorker.call(GameWorker.java:34)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)

**Comment by JayDi85** [comment]
Must be fixed after refactor in 5474787641a7f19cc5fc471327cf73549d7d7c06 and 689b93d0058e512eca3abf31cb3b3616be29aa7a
