### ISSUE TITLE
melee in general is not working

### ISSUE THREAD

**Issue by catman123456** [magefree/mage#9977]
melee in general is not working

_Originally posted by @catman123456 in https://github.com/magefree/mage/issues/9848#issuecomment-1417944852_

**Comment by catman123456** [comment]
![image](https://user-images.githubusercontent.com/64045003/218368834-7513e3be-1aa9-4496-9921-7792cc9a574f.png)

**Comment by PurpleCrowbar** [comment]
Duplicate of #9848
