### ISSUE TITLE
Counters Don't Cancel

### ISSUE THREAD

**Issue by skeet70** [magefree/mage#998]
> 704.5r If a permanent has both a +1/+1 counter and a -1/-1 counter on it, N +1/+1 and N -1/-1 counters are removed from it, where N is the smaller of the number of +1/+1 and -1/-1 counters on it.

Counters aren't cancelling each other out. Reproducible with any creature (graft and bloodthirst in my case) with a single +1/+1 counter on it, with a single -1/-1 placed on it (Grim Affliction, Instill Infection, etc). The counters should cancel each other out, leaving neither on the creature, which they don't (though visually there aren't any counters sitting on the card). Triggering proliferate at any point now (Thrumming Bird, Steady Progress, etc) will give you the option to add another of either counter, where you shouldn't have any as an option.

**Comment by LevelX2** [comment]
Fixed with c71b3ea7e80e3f1cc2a0528f47a96c1d4fcead1e.
