### ISSUE TITLE
Cant cast Chandra, Acolyte of Flame with Interplanar Beacon's ability

### ISSUE THREAD

**Issue by Undume** [magefree/mage#9983]
[[Chandra, Acolyte of Flame]]  [[Interplanar Beacon]]

**Comment by Undume** [comment]
[[Chandra, Acolyte of Flame]]

**Comment by jeffwadsworth** [comment]
[[Interplanar Beacon]]

**Comment by Merlingilb** [comment]
I could not reproduce this.
In my test I could use the first ability to pay the generic mana and the second ability to pay one of the red mana.

What was the exact order you played which did not work?
